= Import a File

You can import files, either separately or bundled together in .zip files, into the projects in which you are creating API specifications and API fragments. The files can be RAML 1.0 files, JSON files, or OpenAPI Specification (OAS) 2.0 files. The API Designer converts imported OAS files to RAML.

== Before you begin

* OAS 2.0 does not support all of the features of RAML 1.0. Therefore,


== About this task

Importing API specifications::
+
You can include more than one API specification in an API-specification project. You might want to have more than one specification in a project if the specifications are closely related in functionality. When you publish your project on Exchange, you select one of the specifications as the main specification.
+
Additional specifications that you import can be in RAML or OAS. If a specification that you import is written in OAS, the API Designer converts the specification to RAML.

Importing API fragments::
+
Both API specifications and API fragments can include reusable portions that are contained in separate files. For example, suppose you want to use OAuth 2.0 for securing implementations of your API. You might have a security scheme defined in a RAML file named `oauth_2_0.raml` that explains the settings for implementations to use, as well as other info such as headers and responses. You would import `oauth_2_0.raml` into your project. Then, in your API specification, you would include the security scheme, as in this example:
+
....
securitySchemes:
  - oauth_2_0: !include oauth_2_0.raml
....
+
Then, use the `securedBy` keyword to refer to the scheme, as in this example:
+
....
securedBy: [ oauth_2_0 ]
....
+
You can import annotation types, data types, examples of response messages, libraries, resource types, security schemes, and traits.

[NOTE]
====
If you want your imported files in a directory structure in your project, import them in a `.zip` file that contains the directory structure. 
====


== Procedure

. In the left pane of the editor, click the dots to the right of *Files* and select *Import*.
.
