= Download and Launch Anypoint Studio
:keywords: download, studio, server, test, deploy, applications

*Anypoint Studio* is the graphical integration design environment of the Anypoint Plaform for applications that are deployed to Mule runtime.

= To Download and Install Anypoint Studio

* Before downloading and launching Anypoint Studio, make sure you have the Java SE JDK 7 or Java SE JDK 8 installed.

To install Anypoint Studio:

. Download Anypoint Studio from the link:https://www.mulesoft.com/lp/dl/studio/previous[Anypoint Studio Download Site] and extract it.
** *Windows*: It's important to extract Anypoint Studio into the 'C:\' root folder. Also, if you are using a Windows Anti-Virus application, ensure that the `plugin/` and `features/` directories are under the “trusted” category.
** *OS X*: If you're using OS version Sierra, it's important that you move your extracted app to the `/applications` folder before you launch it
** *Linux*: To support some of Studio Themes in Linux, it is recommended to have GTK version 2 installed.
+
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace.

Anypoint Studio displays a welcome message when it loads for the first time. +
Click Get Started to start using Anypoint Studio.


== Installing Enterprise Modules

If you are running *Anypoint Studio* with *Mule Enterprise Edition (EE)*, you can add additional modules to your Studio instance.

* link:/mule-user-guide/v/3.8/installing-anypoint-enterprise-security[Anypoint Enterprise Security] 

* link:/mule-user-guide/v/3.8/anypoint-connectors[Anypoint Connectors] 

* mailto:sales@mulesoft.com[Contact MuleSoft] to acquire entitlements to access the link:/mule-user-guide/v/3.8/mulesoft-enterprise-java-connector-for-sap-reference[SAP Connector] and/or link:/mule-user-guide/v/3.8/mule-high-availability-ha-clusters[High Availability Clustering]

== Updating Studio

Anypoint Studio notifies you when an update is available.

[TIP]
You can also check this manually going to *Help* > *Check for Updates*.

Keep in mind that updating your Studio installation to the latest release using this method does not update the bundled Runtime version that's announced in the link:/release-notes/anypoint-studio[release notes].

If you updated Studio from the update site and want to get the announced runtime version bundled with your version of Studio follow these steps:

. Go to *Help* > *Install New Software ...*.
. In the _Work with_ drop down menu select *Anypoint Studio Update Site*.
. Expand the *Anypoint Studio* entry.
. Select the *Mule Server Runtime {version}* that appears listed.
. Follow the instructions on screen to complete the installation.

== See Also

* link:/anypoint-studio/v/6/[Essentials of Anypoint Studio].
