= Workflow: Configuring Java JDK for Studio (Windows)

After downloading the JDK from Oracle's site and following the installation instructions, you need to make sure that the JAVA_HOME environment variable is pointing to your JDK installation:

. In Search, search for System (Control Panel) and select it.
. Click Advanced system settings.
. Click Environment Variables.
. In the section System Variables, find the PATH environment variable and select it.
. Click Edit. If the PATH environment variable does not exist, click New.
. In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable.
. Make sure that the jdk1.8.0/bin directory is the first item in your PATH variable.
+
[NOTE]
--
Blank spaces are not allowed when defining a path on Windows.
--
+
. Click OK.
. Reopen Command prompt window, and verify that you configured your installation correctly
+
[source,bash,linenums]
----
> java -version
----
+
This should print the version of the java tool. If the version is old or you get the error "java: Command not found", then the JDK is not properly installed.

Under certain circumstances, if you had a JRE installation previous to installing the JDK, your default VM could still be configured as the JRE. +
You can configure Anypoint Studio to point to your JDK installation as the default VM, by following the "Configure Studio's Default VM on Windows" task. +
If after following those steps, Anypoint Studio still does not recognize your JDK installation, consider uninstalling your JRE.

== See Also

* link:/anypoint-studio/v/6/studio-configure-vm-task-wx[Configure Studio's Default VM on Windows]
