= Troubleshooting Studio Issues

== Issues with Your Default OS Browser

Anypoint Studio uses your configured default browser to display web content such as Exchange and the Runtime Manager UI when deploying an application to Anypoint Platform.

If your default internet browser does not display this content correctly, you can configure Anypoint Studio to use a *Mozilla/XULRunner* runtime environment as the underlying renderer for the Web UI. +
To configure this:

. Download `XULRunner` (we recommend link:http://ftp.mozilla.org/pub/xulrunner/releases/24.0b9/runtimes/[v24.0]).
. Unzip your package and install it.
. Locate your `AnypointStudio.ini` file:
.. On Windows: This file is located within your Anypoint Studio's installation directory.
.. On Linux: `/usr/lib/anypointstudio/anypointstudio.ini`
.. On OSx: `AnypointStudio.app/Contents/Eclipse`:
... Right click in your Anypoint Studio Package
... Select `Show Package Contents`
... Navigate to `Contents > Eclipse > AnypointStudio.ini`
. Add a `-Dorg.eclipse.swt.browser.XULRunnerPath=` variable with the full path to your XULRunner:
+
[source]
----
-Dorg.eclipse.swt.browser.XULRunnerPath={YourXULRunnerFolder}
----

[TIP]
For more information about this configuration, check the link:https://www.eclipse.org/swt/faq.php#howusemozilla[Eclipse Documentation resource].

Additionally, if you are using Windows with Internet Explorer configured as your default browser, and experiencing unexpected crashes, you must disable *ActiveX Filtering*:

. In Internet Explorer, select the *Tools* button.
. Select `Internet options`.
. Go to the `Security` tab, select the *Internet* zone and click on the `Custom level…` button.
. Navigate to the `ActiveX controls and plug-ins` option and select *Disable*
