= Troubleshooting Studio Issues


=== My default OS browser configuration prevents Web UIs such as Exchange to Display correctly.

This is probably because Studio's standard widget toolkit (SWT) is conflicting with the native graphical user interface libraries of your OS' default browser.

You need to point Anypoint Studio to use a *Mozilla/XULRunner* runtime environment as the underlying renderer for the Web UI. +
To configure this, follow these steps:

. Download `XULRunner` (we recommend link:http://ftp.mozilla.org/pub/xulrunner/releases/24.0b9/runtimes/[v24.0]).
. Unzip your package and install it.
. Locate your `AnypointStudio.ini` file:
.. On Windows: This file is located within your Anypoint Studio's installation directory.
.. On Linux: `/usr/lib/anypointstudio/anypointstudio.ini`
.. On OSx: `AnypointStudio.app/Contents/Eclipse`:
... Right click in your Anypoint Studio Package
... Select `Show Package Contents`
... Navigate to `Contents > Eclipse > AnypointStudio.ini`
. Add a `-Dorg.eclipse.swt.browser.XULRunnerPath=` variable with the full path to your XULRunner:
+
[source]
----
-Dorg.eclipse.swt.browser.XULRunnerPath={YourXULRunnerFolder}
----

[TIP]
For more information about this configuration, check the link:https://www.eclipse.org/swt/faq.php#howusemozilla[Eclipse Documentation resource].


=== My Exchange web UI crashes when running Studio on Windows

This is probably because your installation is using Internet Explorer as your default browser, and *ActiveX Filtering* is enabled causing Studio's internal browser to unexpectedly crash.

We highly recommend disabling *ActiveX Filtering* when using Internet Explorer as your default browser:

. In Internet Explorer, select the *Tools* button.
. Select `Internet options`.
. Go to the `Security` tab and click on the `Custom level...` button.
. Navigate to the `ActiveX controls and plug-ins` option and select *Disable*
