= To Perform Additional Installation Tasks

This topic describes additional installation steps that you may need to perform.

== Configure Log Forwarding

[NOTE]
This section refers to forwarding log data from Anypoint Platform itself. For instructions on how to forward log data from the Mule servers and applications that run on the platform, see link:/runtime-manager/sending-data-from-arm-to-external-monitoring-software[Sending data from Runtime Manager to External Monitoring Software].


Anypoint Platform uses rsyslog to handle logging. To forward these logs to remote hosts you must configure this in the Ops Center.

See link:/anypoint-platform-private-cloud-edition/v/1.5/managing-via-the-ops-center#configure-log-forwarding[Configure Log Forwarding] for detailed steps on how to do this on the Ops Center.


[NOTE]
It's assumed that you're forwarding your logs to a 3rd-party log solution, like Splunk. It's not supported to send data to a cloud-based log solution, like Splunk Cloud.


== Set up SMTP

In order to handle e-mail alerts for both Runtime Manager and API Manager, you must have an SMTP server configured on your network. You must direct your local installation of Anypoint Platform to this server, by configuring the link:/access-management/private-cloud-edition-features#smtp[Access Management panel].

////
[CAUTION]
--
Currently, only unsecure connections are supported for SMTP, meaning that a server that uses SMTPS can't be used for this.
--
////

== Provide Platform IP or Domain

You need to provide the DNS or IP with which your instance of the Anypoint Platform is exposed to the local network, this is necessary for Mule runtimes to be able to communicate with it. You can easily do this by accessing the *Acess Management* section, and following the steps detailed on link:/access-management/private-cloud-edition-features#dns-or-ip[Private Cloud Edition features].


== SSL Certificate

In order to use Anypoint Platform, you must provide SSL credentials. You can upload a certificate through the Anypoint Platform UI, see link:/access-management/private-cloud-edition-features#security[on premises features]. This certificate must be trusted by every machine that’s connected to the platform.


== Handling Third Party Authentication

You can have your users log in to Anypoint Platform via various third party authentication tools. See link:/access-management/external-identity[External Identity] for how to configure this on each of the available options. You can use link:/access-management/managing-users#configure-ldap[LDAP], link:https:/access-management/managing-api-clients#ping-federate[ping federate], link:/access-management/managing-users#instructions-for-saml-configuration[SAML] or link:/access-management/managing-api-clients#openam[Open AM]. On this version of the platform, all of your users must be registered in the platform via external identity (except the admin you register via the installation wizard).

== Adding a Custom Disclaimer Message

You can add a custom message to your login page, that all users in your organization will see every time you log in. To set this custom message, see link:/access-management/private-cloud-edition-features#disclaimer[Private Cloud Edition].

== Next Steps

Now that your installation is complete, your platform is ready for being used. Users registered in your external identity service should have access to your Anypoint platform link:/access-management/organization[organization]. As an admin you can now add link:/access-management/roles[roles] to these users. You can also start link:/runtime-manager/managing-servers[registering servers] so that you can then link:/runtime-manager/deploying-to-your-own-servers[deploy to them], etc.

The developers of your organization that create Mule apps through the link:/anypoint-studio/v/6/index[Anypoint Studio] IDE should set up their editors so that these interface with your locally installed Anypoint Platform (instead of the default cloud Anypoint Platform). See link:/anypoint-studio/v/6/setting-up-your-development-environment#enable-on-premises-setup[Enable on-premises Setup].

See link:/anypoint-platform-private-cloud-edition/v/1.5/managing-via-the-ops-center[Managing via the Ops Center] for instructions on how to add or remove servers from the platform cluster and other changes you may want to carry out after installation.