= To Create a Load Balancer

Anypoint Platform Private Cloud Edition should be run in production on more than one server, you must provide your own load balancer to enable this. A load balancer is necessary to distribute traffic between these, and to restrict open ports to just the necessary ones. You can use any standard tool for creating this load balancer, like NGINX.

[NOTE]
Even if you plan to deploy the platform to a single server, a load balancer is strongly recommended.

////
(diagrama de lucidchart) ???
////

You can configure this load balancer with any strategy you want, but a *round robin* strategy is most often the ideal.

This load balancer should be reachable through an IP address that is accessible by all machines in your network.

Your load balancer must route the following TCP ports:

[%header%autowidth.spread]
|===
|Load Balancer Port |Instance Port | Internal Usage
|`80` | `30080`  | HTTP redirects to HTTPs.
|`443` | `30443` | HTTPS port
|`8889` | `30889` | WebSocket Port for Runtimes to connect
|`9500` | `32009` | Ops Center Access Port
|`9501` | `30083` | Monitoring Tooling Access Port
|===


In every case, your load balancer must listen on the *Load Balancer Port* and redirect incoming requests to the *Instance Port*. Your installation of Anypoint Platform includes an internal NGINX server that listens on each of the *Instance Ports* and then performs the action listed in the *Internal Usage* column of the above table.

Additionally, your load balancer should poll the address `HTTPS:10250/healthz` to run a *health check* on your platform servers and confirm that they are accessible.

[TIP]
If you're not sure how to make a load balancer, see link:/anypoint-platform-private-cloud-edition/v/1.5/creating-load-balancer-onprem[creating a load balancer] for instructions on how to create a basic NGINX load balancer for Anypoint Platform Private Cloud Edition.


[NOTE]
To configure SSL credentials, you don't need to set them up in your load balancer. You can configure them via the Anypoint Platform UI, see <<SSL Certificate>>.

