= Anypoint Platform for PCF
:keywords:pcf, pivotal cloud foundry,

[WARNING]
This product was previously named Anypoint Platform On-Premises Edition. Beginning with the 1.5.1 release, it is named Anypoint Platform Private Cloud Edition.

If you have multiple PCF installations, each installation must be linked to its own separate Anypoint Platform Private Cloud Edition installation.


== Overview

The Anypoint Platform for PCF solution is a fully integrated solution that enables organizations to design, develop, deploy, manage, and operate APIs, connectivity apps and microservices within the fully automated and transparent infrastructure provided by  link:https://pivotal.io/platform[Pivotal Cloud Foundry]. The different deployment scenarios that Runtime Manager supports are described in detail here: link:/runtime-manager/deployment-strategies[Deployment Strategies].

If you are using Anypoint Platform for PCF and you have multiple PCF installations, each must be linked to its own separate installation of Anypoint Platform Private Cloud Edition.

If you have a PCF installation with multiple spaces in it, then these can be handled via a single Anypoint Platform installation, but each of these spaces must be paired with a separate installation of the *Space Configuration Tool*. If your Anypoint Platform organization uses multiple different link:/access-management/environments[environments], then it's recommended that you have one PCF space for each.

The Anypoint Platform for PCF solution enables you to:

* Deploy Mule applications to PCF using the Runtime Manager UI.
* Create and deploy a Mule proxy application to PCF. A proxy application intercepts traffic to a non-Mule application, enabling you to apply policies and view usage metrics.


The Anypoint Platform for PCF solution provides three services. These services forward Anypoint credentials and mule license information to Mule applications as they’re deployed to PCF.

* **Runtime Manager Service**: exposes PCF as a deployment target within the Anypoint Runtime Manager and lets you deploy Mule applications to PCF, alongside other deployment targets.

* **API Gateway Service**: enables you to create and deploy a Mule API proxy that intercepts traffic to a non-Mule application running on PCF. This allows you to use the Mulesoft interface to apply policies over the API and the PCF interface to view usage and policy metrics. 

* **Anypoint Metering Service**: provides an API that enables you to view usage metrics for Mule applications deployed to PCF. You can view usage metrics for production, pre-production, staging, and development environments.


== Configuration

For step by step instructions on how to install and configure Anypoint Platform for PCF, see link:pcf-workflow[Workflow: Install, Configure, and Use Anypoint Platform for PCF].


