= Workflow: Install and Verify Prerequisites
:keywords:anypoint platform, on premises

This topic describes the workflow for verifying that your system is ready to install Anypoint Platform Private Cloud Edition.

1. Contact your MuleSoft account representative to obtain a product license.

1. Review the minimum system requirements described in link:./system-requirements[About Minimum System Requirements].
+
[WARNING] 
If your system does not meet all of the minimum system requirements, you cannot install Anypoint Platform Private Cloud Edition.

1. Understand the basics of link:https://www.docker.com/[Docker] and link:https://kubernetes.io/[Kubernetes].
+
Although the installation wizard makes it easy for you to install the platform without interacting with either Docker or Kubernetes, it is important to be familiar with how these work for managing and troubleshooting the platform.

1. (Optional) Create a Virtual Machine

1. Verify your disk and network performance.
+
Before running the Anypoint Platform Private Cloud Edition installer, ensure that your disk and network performance meets the minimum requirements. See link:./prereq-verify[To Verify System Requirements] for tips on how to complete this prerequisite.

1. Enable forwarding when using firewalld
+
If you are running Red Hat Enterprise Linux (RHEL), 7.3 using firewalld, you must enable forwarding as described in link:./prereq-firewalld-forwarding[To Enable Forwarding When Using firewalld]

1. Ensure that the clocks on all servers are synchronized. Unsynchronized clocks can cause problems with platform communications.

After installing and verifying these prerequisites, you are ready to perform the installation. See link:install-workflow[Workflow: Install Anypoint Platform Private Cloud Edition] for more information.