= To Migrate from 1.5.0 to 1.5.1

This topic describes how to migrate Anypoint Platform Private Cloud Edition from version 1.5.0 to 1.5.1.

[WARNING]
During the migration process, there may be some downtime as each node is migrated. Any users who are currently signed are be logged off.

== Prerequisites

Before migrating, perform the following:

* Ensure that your system meets all of the system and network requirements described in link:system-requirements[About Minimum System Requirements]

* Ensure that you have enabled TCP port 5973 intra-node to allow communication to the database cluster.

* Ensure you have permission to run the `sudo` command on the node where you launch the migration tool.

* Ensure that the kubectl command is available in the node where you are performing the migration. To verify that kubectl is installed:
+
----
$ sudo gravity enter
$ kubectl
----

== To Perform the Upgrade

1. Download the `anypoint-1.5.1-installer.tar.gz` package from the support portal.

1. Uncompress the gzip archive.
+
----
tar -xvf anypoint-1.5.1-installer.tar.gz
----

1. Navigate to the `anypoint-1.5.1` directory, then the upload script.
+
----
sudo ./upload
----
+
This command migrates the gravity software on all nodes and restarts the pods. 

1. Ensure that all gravity instances are running using the following command:
+
----
$ sudo gravity enter
$ kubectl get pods --namespace=kube-system
----
+
This command displays output similar to the following:
+
----
NAME                  READY     STATUS    RESTARTS   AGE
bandwagon             1/1       Running   0          2h
bandwagon-mulesoft    1/1       Running   0          2h
grafana-pxsmy         1/1       Running   0          2h
gravity-site-35wti    1/2       Running   0          5m
gravity-site-asjda    2/2       Running   0          5m
gravity-site-xm3vd    1/2       Running   0          4m
heapster-gv4zl        1/1       Running   0          2h
influxdb-r3foe        1/1       Running   0          2h
kube-dns-v18-97jb8    3/3       Running   0          2h
kube-dns-v18-lntzw    3/3       Running   0          2h
kube-dns-v18-wvrgi    3/3       Running   0          2h
log-collector-8kovo   1/1       Running   0          2h
log-forwarder-9lpxk   1/1       Running   1          2h
log-forwarder-eiaom   1/1       Running   1          2h
log-forwarder-q536l   1/1       Running   1          2h
----
+
[WARNING]
Ensure that each of the gravity-site-* instances is running before proceeding to the next step.
+
1. Login to the Ops Center, then click the **Updates** tab.
+
This tab displays the 1.5.1 update.
+
1. Click **Update to this version** to begin the update process.