= To Upgrade from 1.5.0 to 1.5.1

This topic describes how to upgrade Anypoint Platform Private Cloud Edition from version 1.5.0 to 1.5.1.

== Prerequisites

* To perform the upgrade, you must have permission to run sudo on the node where you launch the installer.

* Before performing the upgrade from 1.5.0 to 1.5.1, you must ensure that the kubectl command is available in the node where you are launching the update. To verify that kubectl is installed:
+
```
$ sudo gravity enter
$ kubectl
```

== To Upgrade from 1.5.0 to 1.5.1

* Download the `anypoint-1.5.1-installer.tar.gz` package from the support portal.

* Uncompress the gzip archive.
+
----
tar -xvf anypoint-1.5.1-installer.tar.gz
----

* From the command line, move to the location where you unzipped this archive, then run the following command:
+
----
sudo ./upload
----

* The script prompts you for the interface you want to listen on. Select the IP address you want to use out of the list that is presented and confirm this decision.

* In the output of this command, look for a network address that is signaled by the text `OPEN THIS IN BROWSER`
+
----
OPEN THIS IN BROWSER: https://{HOST}:61009/web/installer/new/gravitational.io/anypoint/{VERSION}?install_token={TOKEN}
----
+
Paste this address in a web browser to access the wizard.
+
