[[_null_safe]]
= Null Safe

Sometimes you want a `@Parameter` to be instantiated even though the user hasn't provided any value.

The clearest example is, given the following parameter:

[source, java, linenums]
----
@Parameter
@Optional
private List<Integer> numbers;
----

While interacting with *numbers* in your code, you will have to check if `numbers == null` at some point to avoid crashing into an undesirable `NullPointerException`.

It would be nice that the SDK automatically created a value for you if the value wasn't configured. Just as simple as providing an empty list instead of `null`.
They way you have of informing such desired behaviour is by adding the `@NullSafe` annotation to the parameter and it's done!
And that's only one of the many flavours `@NullSafe` can have.

`@NullSafe` can be used alongside `List` and `Map` interfaces, and it will provide you a default
implementation for those collections. But the interesting part comes when you want a POJO to be your *null safe type*.

[source, java]
----
@Parameter
@Optional
@NullSafe
private Foo foo;
----

As you may expect, the SDK will instantiate `Foo` and assign it to your `foo` parameter saving you the manual nullity check.

`@NullSafe` cannot be used with any POJO, there is a restriction which is that all the parameters
declared inside the POJO must all be optionals (if something is *required*, it means that there is no
default value the SDK can use and the whole meaning of the `@NullSafe` automatically instating
parameters would be meaningless).

`@NullSafe` can be configured to instantiate a certain class instead of using the parameter's type.
This is really handy in the cases in which the parameter's type is not instantiable (like an abstract class or an interface).

The way of specifying the class to be instanciated is by setting the `defaultImplementingType` attribute in the annotation.

[source, java, linenums]
----
@Parameter
@Optional
@NullSafe(defaultImplementingType = Foo.class)
private AbstractFoo foo;
----
