[[_exclusive_optionals]]
= Exclusive Optionals

While developing a module, we found useful to have a way of establishing the following restriction:

> "From this set of parameters, only one shall be used at any time"

It happens when you have several ways of configuring the same thing,
but you only one of those options should be used.

The SDK provides you a way of enforcing this restriction by using the `@ExclusiveOptionals`
annotation.

== @ExclusiveOptionals

the `@ExclusiveOptionals` annotation can only be used on types used as `@ParameterGroup`.
For more information about parameter groups, please refer to the <<_parameters, Parameters>> documentation.

Let's start with an example:

[source, java, linenums]
----
@ExclusiveOptionals
public class ExclusiveOptionalsExample {

    @Parameter
    private String requiredParameter;

    @Parameter
    @Optional
    private String optionalParameter;

    @Parameter
    @Optional
    private String anotherOptionalParameter;
}
----

As the name of the annotation clearly states, the exclusivity restriction only runs for
the optional parameters. That means that in the example above we could have `requiredParameter` set as the same time as `optionalParameter` or `anotherOptionalParameter`,
but having `optionalParameter` and `anotherOptionalParameter` at the same time will throw an error.

[TIP] You can have as many parameters as you want inside an object annotated with `@ExclusiveOptionals`,
but only one optional parameter is allowed to be set at any time.

== Enforcing at least one parameter

So far, we presented a restriction that guarantee us that no more than one optional parameter
can be present at the same time, but what happens if none of them are present? It's
still a valid scenario because we are not violating the _no more than one_ statement.

It is not crazy to think that sometimes we may want at least one of them to be present,
which in plain english sounds like "Only one of them should be always set, no more, no less".

Doing that is as simple as configuring the annotation with `@ExclusiveOptionals(isOneRequired = true)`.

[source, java, linenums]
----
@ExclusiveOptionals(isOneRequired = true)
public class OneRequiredExample {

    @Parameter
    private String requiredParameter;

    @Parameter
    @Optional
    private String optionalParameter;

    @Parameter
    @Optional
    private String anotherOptionalParameter;
}
----

So, configuring `requiredParameter` but not setting `optionalParameter`
nor `anotherOptionalParameter` will result in an error.
