= About the Mule SDK
:keywords: mule, sdk

The Mule SDK is a tool which allows to extend the Mule 4 Runtime by creating new modules which can be installed in the applications. Examples of such modules are connectors such as HTTP or modules with custom functionality such as the Validations Module.

The SDK provides a stable API which allows you to:

* Faster development of Mule components
* Decouple the built modules from the Runtime internals
* Assure consistency across Mule components and other modules such as cloud connectors

== Differences with Devkit

If you ever developed custom components for Mule 3.x, then this should sound pretty similar to the old Anypoint Devkit for Connectors. The Mule SDK is an evolution of that Devkit and takes its place for Mule 4.0 as the canonical way of extending the runtime (Devkit is not available for Mule 4).

Although the SDK builds on the same idea of annotated Java classes, it's pretty different in its inner workings:

* The SDK isn't a code generator. The built module does not contain any generated code (not event the XSD schema). Your module will interact with the Runtime through a clearly defined _Extensions API_. Users don't need to learn the details of this API, the SDK as a framework takes care of that for you.
* The SDK is way more powerful and supports features not available in the old Devkit such as:
  ** Transactions
  ** Request-Response message sources
  ** Dynamic configurations
  ** Routers
  ** Non Blocking operations
  ** Classloading isolation
  ** Enhanced interoperability with Runtime services
  ** Much, much more
