= Object Streaming (Pagination)

Object Streaming is similar to <<3.1_binary_streaming#_binary_streaming, binary streaming>>, only that instead of streaming a raw
byte stream, we stream complete java objects.

If you are familiar with the old Devkit from Mule 3, you can think of this feature as
an evolution of the Auto Pagination feature.

The main difference between this and the support in the old devkit, is that now we support
repeatable, random and concurrent access.

Let's see an example of how to use this feature, through an oversimplified select operation from the Database connector:

[source, java, linenums]
----
public PagingProvider<DbConnection, Map<String, Object>> list(@Text String sql) { // <1>
    return new PagingProvider<DbConnection, Map<String, Object>>() {

      private ResultSet resultSet;

      @Override
      public List<Map<String, Object>> getPage(DbConnection connection) { // <2>
        if (resultSet == null) {
            resultSet = executeQuery(connection, sql); // <3>
        }

        return extractPageFrom(resultSet);
      }

      @Override
      public java.util.Optional<Integer> getTotalResults(DbConnection connection) {
        return java.util.Optional.empty(); // <4>
      }

      @Override
      public void close(DbConnection connection) throws MuleException {
        resultSet.close(); // <5>
      }
    }
}
----

<1> Two things to notice about the signature of this method:
* The method returns a `PagingDelegate` object. `PagingDelegate` requires two generic types. The first one is the type of
connection the delegate will use to get the next pages, and the second is the type of the elements in the page.
* The list operation operation receives the parameters but notice it doesn't receive a connection object. Paged operations
cannot receive connections. Instead, they must always use the connections that the runtime passes to the `PagingProvider`.

In summary, what this signature means is that it will return the results of the query in pages, using a DbConnection object
and each item in the stream will be a `Map<String, Object>` which represents each row in the result.

<2> The `getPage()` fetches the next page and returns it. It receives the connection to use to fetch that page. When the stream is
over, this method needs to
<3> Depending on the operation's logic, you might need to contain logic to handle the obtention of the first page vs. logic to
obtain the next pages.
<4> Another feature of object streaming is the ability to tell how many object are actually in the streams. the `getTotalResults()`
method needs to be implemented to determine that. The problem is that not all APIs support that. For example, the _Salesforce_ API
does support that. JDBC (the API powering the Database connector) does not. That is why this method returns a java `Optional`, in
this case, an empty one. Users of your paginated operation can obtain this value through an expression similar to `#[payload.size]`
<5> Finally, the `close()` method will be invoked when no more objects are in the stream. This method *IS NOT* for closing
the connection, the SDK will do that automatically. It's for releasing any resources that this paging delegate might be holding.
For example, in this case the paging delegate has a `ResultSet` from which each of the pages values are extracted. That `ResultSet`
needs to be released.

== Sticky Connections

By default, there's no guarantee that the connection that the `getPage()` method receives will be the same one on each
invocation. And that's fine. For most API's (specially Rest APIs) this is not only a problem but in same cases it's even
a feature. However, there're other cases (like Database) in which all pages *MUST* be obtained using the *SAME* connection.
This was impossible to do with Devkit.

In the new SDK, we added what we call sticky connections, which is a way to signal that the Runtime must guarantee that the
`getPage()` method is always invoked with the same transaction. This is as easy as this:

[source, java, linenums]
----
public PagingProvider<DbConnection, Map<String, Object>> list(String sql) {
    return new PagingProvider<DbConnection, Map<String, Object>>() {

      private ResultSet resultSet;

      @Override
      public List<Map<String, Object>> getPage(DbConnection connection) {
        ...
      }

      @Override
      public java.util.Optional<Integer> getTotalResults(DbConnection connection) {
        ...
      }

      @Override
      public void close(DbConnection connection) throws MuleException {
        ...
      }

      @Override
      public boolean useStickyConnections() {
        return true;
      }
    }
}
----

== Configuring Streaming

Just like with binary streaming, auto-paged operation also automatically get streaming configuration through the
`<repeatable-in-memory-iterable />`, `<ee:repeatable-file-store-iterable />` and `<non-repeatable-iterable />`. For details
on these elements please check the streaming documentation linked above, but here's an example of how you would configure
custom file store streaming for the select example above:

[source, xml, linenums]
----
<db:select sql="select * from REALLY_LARGE_TABLE">
    <ee:repeatable-file-store-iterable inMemoryObjects="100"/>
</db:select>
----
