= TLS
:keywords: mule, sdk, security, tls

Adding support for TLS configuration in your module is as simple as declaring a <<parameters#, parameter>> of type `TlsContextFactory`. The `TlsContextFactory` parameter can then provide an `SSLContext`, a `SSLSocketFactory` or a `SSLServerSocketFactory`, as well as enabled TLS protocols and cipher suites, allowing you to set up most Java components that use TLS/SSL.

Just take a look at the following example:

[source, java, linenums]
----
@Parameter
@Optional
private TlsContextFactory tlsContextFactory;
----

This will automatically generate support for this XML setting:

[source, xml, linenums]
----
<tls:context enabledProtocols="TLSv1.2,SSLv3">
    <tls:trust-store path="my-trust-store.jks" password="myPassword"/>
    <tls:key-store path="my-key-store.jks" keyPassword="myPassword" password="myPassword"/>
</tls:context>
----

Take into consideration that a TLS context can also be defined as a global element of your application,
so you can reference it by its name anywhere you need it.

If the TLS needs are hidden from the user (for example, if you need to connect safely to a service internally) you can create your own `TlsContextFactory` using its builder:

[source, java, linenums]
----
private final TlsContextFactory tlsContextFactory = TlsContextFactory.builder()
                                                        .trustStorePath("tls/trustStore")
                                                        .trustStorePassword("mulepassword")
                                                        .build()
----

This builder also allows creating default instances of `TlsContextFactory`:

[source, java, linenums]
----
private final TlsContextFactory defaultTlsContextFactory = TlsContextFactory.builder().buildDefault();
----

To see how to correctly configure TLS context and all the available parameters that
you can set please head to the reference for link:/connectors/common-about-tls[Mule TLS Context].
