= Packaging Your Connector for Release
:keywords: devkit, connector, packaging, documenting use cases, readme

When your connector is ready for release to a broad audience, take the following additional steps to ensure user success:

* Create a license agreement for your connector.
* See the advantages of building your connector with link:/release-notes/anypoint-connector-devkit-3.9.x-release-notes[DevKit 3.9] and packaging two sets of connector logo-icons to support the old and new Studio UI.
* Develop end-to-end walkthroughs to illustrate performing common use cases with your connector.
* Create a compressed file for distribution.

== Prerequisites

This document assumes you have:

* Developed your connectors
* Documented them in preparation for their release. Additional information about documenting your connector is provided in <<Documenting With Use Cases>>.
* Completed testing as described in link:/anypoint-connector-devkit/v/3.8/developing-devkit-connector-tests[Developing DevKit Connector Tests].

== Apply a License Agreement and Header

During connector installation, Studio presents you with a license agreement. You can customize the contents of this agreement to reflect your terms and the wording you want for your connector license.

Maven first searches for a `LICENSE.md` file in the same directory as the `pom.xml` file during the build process.

If this file is not found, Maven goes through the following steps to locate a license agreement: 

. Maven checks for a `LICENSE.txt` file in the same directory as the `pom.xml` file. 
. If the `pom.xml` file contains a *Licenses* section (as described in the link:http://maven.apache.org/pom.html#Licenses[Maven documentation]), the DevKit attempts to to download the text from the license's URL, then saves the downloaded content as a new `LICENSE.md` file.
. If no license text is found by the above steps, the build fails.

In addition to the global license file, the DevKit requires that your source files also contains a license header. To apply the license header to every source file in your project, run the following command in a command console at the root of your project, which contains your connector project's `pom.xml` file: 

[source,code,linenums]
----
mvn license:format
----

This command goes through your whole project and applies the license header defined in the `LICENSE_HEADER.txt` file to each source file. This includes Java files, SQL scripts, XML files, and more.

== Install Connector Into Local Maven Repo

Run the following command to install your connector with your updated license information into your local Maven repository. 

[IMPORTANT]
Run `mvn license:format` before running this Maven install command because Maven verifies the license headers first before installing: 

[source,code]
----
mvn clean install
----

[NOTE]
====
To enable verbose logging, use:

`mvn clean install -Ddevkit.verbose.logging=true`
====

== Package Connector using Maven

You can also use the following Maven command to package the connector instead of installing. This creates an update site that you can use to install the connector in Anypoint Studio. This update site contains everything you need to use the connector inside your Mule applications (icons for the palette, XSDs, source files, etc.) Therefore it is important that your source files have the license headers before packaging.

*Note*: Packaging the connector does not check for license headers in your source files. To package your connector, run the following command at the root folder:

[source,code]
----
mvn clean package
----

Find the packaged connector in the connector's `/target` folder to install and make the connector available in Studio.

== Tip - Document Use Cases

Before releasing your connector, document your connector effectively. Useful documentation can help reduce your support and training costs, as well as improving customer satisfaction.

Documentation tips:

* *Readme* - Provide a Readme file that customers can readily access. The best Readme file appears automatically during installation, such as part of an installation wizard. The Readme needs to contain installation information and explain any required software that customers need to install or configure first before they can install your connector.
* *Use Cases*: Explain why, when, and how a customer uses your connector. For each use case, provide examples with explanations. For information, see link:http://en.wikipedia.org/wiki/Use_case[Wikipedia's Use Case] topic.
* *Release Notes*: Ensure your connector is versioned and that you help customers understand what changes between releases. We recommend that you list new features, known issues, and what issues were fixed.
* *APIDoc*: Generate link:/anypoint-connector-devkit/v/3.8/connector-reference-documentation[Connector Reference Documentation] that leverages Javadoc, running a simple Maven command run from your connector's root folder.


////
The link:https://github.com/mulesoft/box-connector/blob/master/doc/sample.md[Box connector] provides an excellent example of an effective connector use case, including a step-by-step walkthrough of installing and using the connector. 
////

[TIP]
====
Certify and Publish Your Connector

MuleSoft's program certifies and publishes third party connectors to be distributed through Anypoint Exchange. For more information about this program, please move on to link:/anypoint-connector-devkit/v/3.8/connector-certification-program-guidelines[Connector Certification Program Guidelines].
====

== Uploading your Connector to Exchange

Anypoint Studio identifies each connector by a *Feature ID* that spans all versions of the connector. In order to expose your connector via the link:/mule-fundamentals/v/3.8/anypoint-exchange[Anypoint Exchange], you will be prompted by Anypoint Exchange to provide the Feature ID when uploading your connector asset, as well as a version number.

Follow the steps below to obtain the Feature ID:

. Unzip the file containing your connector's Update Site.
. In the created folder, look for the `content.xml` file and open it with a text editor.
. In this file, search for a string that follows the following pattern: `id=’org.mule.tooling.ui.extension.<connector name>.feature.group’`. That entire value is your connector’s Feature ID. As a more concrete example, your Feature ID could be something like ’org.mule.tooling.ui.extension.cloudhub.3.6.0.feature.group’

In this same `content.xml` file is a tag named *version*. The version string is what Exchange considers the Feature ID. Provide this value in the *Connector Version* field in Exchange. Consumers will later only see the simpler version number. For example if the version number you provide is 2.0.1.201606101417, they only see 2.0.1. The full version number displays ONLY when you are editing a specific version.

[NOTE]
====
In Anypoint Studio 6.0.1 and later, Feature ID is not a mandatory field. If not provided Studio is able to install the connector, however Exchange won’t be able to differentiate the status of the connector. Therefore, you will always see the *Install* button next to it in Exchange, even if you already have the latest version installed.

Also, you don’t need to provide the full version number anymore. Following the example above, you can just provide 2.0.1 as the Connector Version and Studio makes a best effort to find an exact version based on this provided version.
====


== See Also

* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
