= Anypoint Visualizer

**TODO: Change name of product when PM finalizes.**

Anypoint Visualizer helps people see, understand, and act upon their application network. At its core, Anypoint Visualizer exposes purpose-built views of different aspects of the complete application network graph (A.K.A the topograph) that users can use to explore their application network to answer questions and act on it. Anypoint Visualizer powers use cases like architectural review and compliance, troubleshooting, and security.

Anypoint Visualizer provides a graphical representation of 3rd party systems, APIs, and Mule applications within your application network. The data is automatically updated, there's no coding of configuration required to make it work, and it's secured by design so only the allowed users can access it and only view the allowed APIs and applications in your application network. 

The following image shows how a typical application network appears in Anypoint Application Network Visualizer.

image:application-network[Application Network]

In this image, each node of the application network is represented by a box. Connections between the nodes are represented by arrows.

Anypoint Visualizer provides a real-time view of your application network. It only displays nodes for applications or APIs that are running and discoverable, and any 3rd party service that's being invoked by a Mule API, proxy or application. The connections between nodes are based on traffic between applications or APIs that occurred in the last seven days. If an application appears in multiple workers, they appear as two distinct nodes in the graph.

Anypoint Visualizer also enables you to view CPU and memory usage for each node within your application network.

== Getting started
In order to access the Anypoint Visualizer, users have to have the right permissions. For information on how to configure this go to link:setup[setup.adoc]

The Anypoint Visualizer collects data from the Mule applications, APIs and proxies to discover all incoming and outgoing connections through an embedded plugin. As long as the application, API, and proxy is running on the supported Mule runtimes, it will be discovered along with their dependencies. For more information about supported Mule runtimes go to [setup|setup.adoc]. For more information about collected data, go to link:howItWorks[how it works].

Once in the Anypoint Visualizer, users can select which environments they want to see, arrange applications in layers, inspect their operational monitoring information, and customize node's and edges' text. For more information go to link:view[Using Anypoint Visualizer]

== Use Cases

**Reviewers: This section needs additional work to iron out clear use cases. Any suggestions would be helpful.**

The following use cases provide examples of how you can use Anypoint Visualizer.

* **Discussing Current Design State**: Enterprise architect Kara has developed a plan for how the architecture she’s responsible for will accommodate a new product. She needs to capture its current state so she can plan the transition and get buy-in from stakeholders on her proposal.

* **Implementing API-led Connectivity**: Site reliability engineer Tom is tired of maintaining several separate connections to Salesforce. He wants to identify redundant point-to-point connections so he can come up with requirements for a new process API.

* **Exploring the Application Network**: Anypoint Visualizer provides a real-time view of the application network. This means that architects and product owners can see how the application network evolves explore the appliation network to discover and plan how to unlock data and break down siloed systems, knowing that the visualization is always up-to-date.
**Rewrite this as usecases above

* **Define API-Led Connectivity Classifications**: Anypoint Visualizer enables you to assign the nodes of the graph into layers. This enables you to quickly inspect if the APIs are correctly categorized, and if the architectural principles of API-led connectivity are being followed.
**Rewrite this as usecases above

* **Accelerating time-to-production**: Architect Kara can see how projects are being built from the development environment, throughout test, staging, and production. This allows Kara to review the architecture as the code is being deployed and rise any concerns to ensure that best practices and agreed upon architecture are being followed without waiting for the documentation to be generted.

