= MuleSoft Documentation
:keywords: platform, arm, rest, soa, saas, api, proxy, design, develop, anypoint platform, studio, mule, devkit, studio, connectors, auth, exchange, api design, apikit, raml, application network, anypoint, arm, rest, soa, saas, api, proxy

MuleSoft provides the Anypoint Platform to help your organization create integrations and APIs, simplifying the task of connecting multiple data sources.


[[what-is]]
== What is Anypoint Platform?

Anypoint Platform is MuleSoft's *integration application and API suite*. It comprises a unique toolset that enables organizations to create, integrate, model, build, and deploy services, APIs, and Mule applications.

The Anypoint Platform tools are accessed primarily through a browser but also have command line tools and APIs. Through the platform it is possible to control most aspects of integration applications and APIs throughout their entire lifecycle.


== Set up Anypoint Platform

Follow these steps to get an Anypoint Platform account and set up your workstation.

* link:https://anypoint.mulesoft.com/login/#/signup?apintent=exchange[Create an Anypoint Platform account].
* Consider the link:/mule-user-guide/v/3.8/hardware-and-software-requirements[MuleSoft hardware and software requirements]
* For development of Mule apps or API design, set up your workstation according to the link:#getting-started-dev[Developer Toolkit].
* To manage and deploy Mule apps, see the link:#getting-started-deploy[Deployment Toolkit].
* To set up platform permissions or monitor deployed assets see the link:#getting-started-manage[Administrator Toolkit].



[[getting-started-dev]]
== Developer Toolkit

After obtaining access to the Anypoint Platform, you are a few steps away from developing integrations with Mule.

. link:/anypoint-studio/v/6/download-and-launch-anypoint-studio[Download and Install Anypoint Studio]. Studio comes with a test Mule server.
. If you are an API developer, ensure you read up on link:/api-manager/[API Manager], accessible from Anypoint Platform, to design, publish and manage APIs.
. Check out templates, connectors and more from Anypoint Exchange, where you can find and publish developer resources. You can use Exchange to publish private repositories too.

[NOTE]
If you're working with Mule outside Studio or you have an enterprise license, see how to link:/mule-user-guide/v/3.8/configuring-maven-to-work-with-mule-esb[Configure Maven] to properly manage the dependencies used by your Mule apps.

[[getting-started-deploy]]
== Deployment Toolkit

For *API deployment*, see link:/api-manager[API Manager], accessible from Anypoint Platform.

For *Mule application deployment*, see link:/runtime-manager/deployment-strategies[deployment strategies]. This document explains the standard app-to-runtime deployment workflows and tools.


See instructions on how to deploy applications to link:/getting-started/deploy-to-cloudhub[CloudHub] or to link:/getting-started/deploy-to-server[local Mule runtime instances] via the Anypoint Platform.


[[getting-started-manage]]
== Administrator Toolkit

If you are an administrator, provision access to your organization's Anypoint Platform instance through the link:/access-management[Access Management console].

link:/access-management/external-identity[Set up external identities] to manage users and clients using your organization's external federated identity system.

To manage Mule apps and servers, use link:/runtime-manager/[Runtime Manager], the same platform tool used to deploy apps to Mule anywhere.

For APIs, see link:/api-manager[API Manager] and link:/api-manager/[Anypoint Analytics].


== Contribute to the Documentation

MuleSoft welcomes contributions to our documentation from the community. To make a contribution:

. Click *Edit on GitHub* at the top of any page.
+
The source page on GitHub appears.
+
. Click *Edit this file* and make a change using the link:https://en.wikipedia.org/wiki/Lightweight_markup_language[asciidoc markup language].
. Accept the link:http://www.mulesoft.org/legal/contributor-agreement.html[contributor's agreement] so that we can acknowledge your contribution.

For more information about making a contribution, see the link:https://github.com/mulesoft/mulesoft-docs/blob/master/README.adoc[README.adoc file]. Your positive impact in the community by improving MuleSoft documentation is appreciated and recognized.

== Archived Documentation

Documentation for product versions that are no longer supported or have reached their end of life is available at https://docs.archive.mulesoft.com/.

== See Also

* *NEXT STEP:* link:/getting-started/[Getting Started] gives you an overview of API and Mule app lifecycles.
* link:/api-manager/designing-your-api[Designing an API]
* link:/anypoint-studio/v/6/basic-studio-tutorial[Basic Studio Tutorial]
* link:https://anypoint.mulesoft.com/login/#/signin?apintent=exchange[Sign into Anypoint Platform]
