= MuleSoft Documentation

MuleSoft provides the Anypoint Platform to help your organization create integrations and APIs, simplifying the task of connecting multiple data sources.


[[what-is]]
== What is Anypoint Platform?

Anypoint Platform is MuleSoft's *integration application and API suite*. It comprises a unique toolset that enables organizations to create, integrate, model, build, and deploy services, APIs, and Mule applications.

The Anypoint Platform tools are accessed primarily through a browser but also have command line tools and APIs. Through the platform it is possible to control most aspects of integration applications and APIs throughout their entire lifecycle.


== Set up Anypoint Platform

Follow these steps to get an Anypoint Platform account and set up your workstation.


[[getting-started-dev]]
== Developer Toolkit

After obtaining access to the Anypoint Platform, you are a few steps away from developing integrations with Mule.

. Studio comes with a test Mule server.
. If you are an API developer, ensure you read up on , accessible from Anypoint Platform, to design, publish and manage APIs.
. Check out templates, connectors and more from, where you can find and publish developer resources. You can use Exchange to publish private repositories too.

[NOTE]
If you're working with Mule outside Studio or you have an enterprise license, see how to Configure Maven to properly manage the dependencies used by your Mule apps.

[[getting-started-deploy]]
== Deployment Toolkit

For *API deployment*, see API Manager, accessible from Anypoint Platform.

For *Mule application deployment*, see deployment strategies. This document explains the standard app-to-runtime deployment workflows and tools.


See instructions on how to deploy applications to CloudHub or to local Mule runtime instances via the Anypoint Platform.


[[getting-started-manage]]
== Administrator Toolkit

If you are an administrator, provision access to your organization's Anypoint Platform instance through the Access Management console.

Set up external identities to manage users and clients using your organization's external federated identity system.

To manage Mule apps and servers, use Runtime Manager, the same platform tool used to deploy apps to Mule anywhere.

For APIs, see API Manager and Anypoint Analytics.


== Contribute to the Documentation

MuleSoft welcomes contributions to our documentation from the community. To make a contribution:

. Click *Edit on GitHub* at the top of any page.
+
The source page on GitHub appears.
+
. Click *Edit this file* and make a change using the asciidoc markup language.
. Accept the contributor's agreement so that we can acknowledge your contribution.

For more information about making a contribution, see the README.adoc file. Your positive impact in the community by improving MuleSoft documentation is appreciated and recognized.
