= Design Center Beta Release
:keywords: platform, arm, rest, soa, saas, api, proxy, design, develop, anypoint platform, studio, mule, devkit, studio, connectors, auth, exchange, api design, apikit, raml, application network, anypoint, arm, rest, soa, saas, api, proxy


== Flow Designer 1.0 Beta 1

We’re very excited to announce the initial version of Design Center. This release includes the new web based flow designer, that enables users to easily create web based integration flows. With this release of the flow designer you can:

* Create and manage Mule Application projects
* Ability to design flows using a simple step by step process
* Connect to systems and protocols using different connectors, including databases, FTP, HTTP, and SOAP web services.
* Perform complex data transformations using link:/mule-user-guide/v/4.0/dataweave[DataWeave] with a visual drag and drop editor
* Create and manage data types for XML, JSON, CSV and objects
* Store and retrieve information from the Mule Object Store

Underpinning this release is the initial release of Mule 4. This release is currently only available to Design Center users. More details on whats new in Mule 4 can be found in the link:/mule-runtime/v/4.0/[Mule Runtime section].



== Minimum Requirements

The following browsers are supported for running the Design Center:

* Chrome (version 54.0.x)
* FireFox (version 50.0.x)

You must also have:

* An Anypoint Platform account
* At least 0.2 sandbox VCores available to test.
+
[NOTE]
For the GA release, Flow designer, will not need additional sandbox VCores.

* Your account must have the necessary link:/design-center/v/1.0/to-obtain-flow-designer-permissions[permissions] to use the Design Center.

== Limitations


With the flow designer, you currently can't:

* Automatically build out an API backend based on a RAML API definition file
* Deploy directly to a customer-managed server (i.e.: a runtime outside CloudHub)
* Use TLS for secure protocols such as HTTPS and SMTPS
* Write custom code
* Use advanced functionality such as Spring or Maven
* Create Mule projects that run on a runtime version prior to 4.0.0
* Create flows that reference other flows or subflows. A project may have multiple flows but all of them are independent.
* Access resources (APIs, Database, FTP sites, etc.) that aren't accessible via the public internet or via your VPC.

[TIP]
All of these things can be accomplished with Anypoint Studio, our more advanced desktop eclipse-based IDE.

== Know Issues

* TLS configuration for connectors is not supported
* Rename a project that has already been created is not fully supported.
* Projects that include a *logger* component placed immediately in a flow after a *Transform* component don't work as expected at runtime.
