= MuleSoft Doc ARCHIVES
:experimental:
ifdef::env-github[]
:caution-caption: :fire:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

This branch of the doc repo is for archived versions of MuleSoft's tech docs. In general, these docs are for products or product versions that have reached their end of life (EOL) and are no longer supported by MuleSoft. Its content will only change as new docs are archived. Otherwise, it will not undergo any updates or corrections.

This content is published to this URL: [TBD]

== Contents

link:index.adoc[Archived MuleSoft Documentation]

== Archive Process

. Add files to the archive branch:
+
* Copy files to be archived from the `master` branch to this `archive` branch.
* Update the TOCs (top level and product or product version level).
* Update the top-level landing page (index.adoc) to include a link to the archived docs.
* Add ARCHIVE labels to the landing page for the newly archived docs.
* Fix any broken links in the files copied files to the `archive` branch.
+
. Build to `_site` and test the docs locally.
+
* Build: `$ ./gradlew`
* Test by running a link checker (such as blc) and making sure that the TOCs, Archive labels, and landing pages are ok.
+
. Make sure that IT gets a copy of the final `_site/` content so they can publish it on the Amazon S3 bucket that serves the Archive Doc Site. (Note that IT can build this content themselves once it's ready for publication.)
. Remove archived files from `master`.
. Fix any broken links in `master`.
. Test links in master.

== Tools and Tips

* Link Checker: A good link checker is Broken Link Checker (`blc`). You can download it and run a command like this on a local doc build:
`$ blc -roe http://127.0.0.1/ > ../link_check`
+
The `link_check` file clearly identifies links that are BROKEN in each file on the local site. Typically, there are a handful of patterns to what's broken, which makes the cleanup process manageable. For example, where there are links out to docs that are still out on `docs.mulesoft.com`, you can often do a global find and replace for all instances of that pattern. For example, assume link:/some_dir/v/1.1/some-file[Some Topic], you can replace `link:/some_dir/` with `link:https://docs.mulesoft.com/some_dir/`. This is the most common sort of fix.
+
* One easy way to get files from the `master` to the `archive` branch:
+
. Check out the `master` branch: `$ git checkout master`
. Copy the directory that contains the files you want to archive: $ cp -r /4.1 /4.1.archive`
. Check out the `archive` branch: `$ git checkout archive`
. Rename the folders back to their original name.
. Add the contents of the folders to the `archive` branch: `git add /path/to/4.1/*`
. Commit an push the new files in.
