= MuleSoft Doc ARCHIVES
:experimental:
ifdef::env-github[]
:caution-caption: :fire:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

This branch (`archive`) of the doc repo is for archived versions of MuleSoft's tech docs. In general, these docs are for products or product versions that have reached their end of life (EOL) and are no longer supported by MuleSoft. The content here will only change as additional docs are archived. Otherwise, it will not undergo any updates or corrections.

This content is published to this URL: [TBD]

== Contents

link:index.adoc[Archived MuleSoft Documentation]

== Archive Process

. Add files to the archive branch:
+
* Copy files to be archived from the `master` branch to this `archive` branch. See <<tools_tips>> below for guidance.
+
. Prepare the archive files for publication: 
+
* Update the TOCs (top-level and product or product-version level `_toc.adoc` files) to reflect the archived state, for example: link:/mule-user-guide/v/3.4/_toc.adoc[Mule Runtime Doc Archives] and the link:_toc.adoc[Top-level TOC].
* Update the top-level landing page (index.adoc) to include a link to the archived docs, for example: link:index.adoc[Archived MuleSoft Documentation] 
* Add ARCHIVE labels to the landing page for the newly archived docs, for example: link:/mule-user-guide/v/3.4/index.adoc[Mule Runtime (v3.4 Archives)].
* Make sure that the `_config.yml` file reflects the correct setting for `isLatest: true|false`. For example, if the latest archived version was 3.3, and you are now adding 3.4 docs to the archive, you need to change the setting to `false` for the 3.3 docs and to `true` for the 3.4 docs, for example: https://github.com/mulesoft/mulesoft-docs/blob/archive/mule-user-guide/v/3.4/_config.yml[mule-user-guide/v/3.4/_config.yml].
* Fix any broken links in the files copied files to the `archive` branch (see <<tools_tips>> for more on this topic).
+
. Build to `_site` and test the docs locally.
+
* From the root directory of the `archive` branch, use this build command: `$ ./gradlew`
* Test the build by running a link checker (such as blc) and making sure that the TOCs, Archive labels, and landing pages are ok.
+
. Make sure that IT gets a copy of the final `_site/` content so they can publish it on the Amazon S3 bucket that serves the Archive Doc Site. (Note that IT can clone this repo and build this content themselves once it's ready for publication.)
. Remove archived files from `master`.
. Fix any broken links in `master`.
. Test links in `master`, then commit and push in the changes to `master`.

[[tools_tips]]
== Tools and Tips

* Link Checker: A good link checker is Broken Link Checker (`blc`) -- thx, Fer! You can download it and run a command like this on a local doc build:
`$ blc -roe http://127.0.0.1/ > ../link_check`
+
The `link_check` file clearly identifies links that are BROKEN in each file on the local site. Typically, there are a handful of patterns to what's broken, which makes the cleanup process manageable. For example, where there are links out to docs that are still out on `docs.mulesoft.com`, you can often do a global find and replace for all instances of that pattern. For example, assume `+link:/some_dir/v/1.1/some-file[Some Topic]+` in your `.adoc` file. You can do a global find and replace, that replaces `link:/some_dir/` with `link:https://docs.mulesoft.com/some_dir/`. This is the most common sort of fix.
+
This assumes you are hosting your build locally. You can use Apache HTTP for that. For guidance with that setup on Mac, see https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions. You can ignore the PHP part. 
+
* One easy way to get files from the `master` to the `archive` branch:
+
. Check out the `master` branch: `$ git checkout master`
. Copy the directory that contains the files you want to archive, for example: `$ cp -r /4.1 /4.1_archive`
. Check out the `archive` branch: `$ git checkout archive`
. Rename the folders back to their original name, for example: `$ cp -r /4.1_archive /4.1`
. Add the contents of the folders to the `archive` branch: `$ git add /path/to/4.1/*`
. Commit and push the new files in: `$ git commit -am 'all my new archive files'` then `$git push`
