// author: Dan D
= Migration to Mule 4

Mule 4 introduces many exciting new improvements over Mule 3, which make it easier to learn,
develop and manage. For an overview of these capabilities, be sure to read
link:/mule-user-guide/4.0/mule-runtime-updates[What's New in Mule 4],
which gives a high level of the new features.

This guide is for Mule users who wish to migrate applications manually or who wish to learn
more about the differences between Mule 3 and Mule 4. It is organized into the following sections:

 * Mule 4 for Mule 3 users - an overview Mule 4 for those who already know Mule 3
 * Preparing for the migration - steps users should think about before migrating an application.
 * Migration Examples - end to end examples which show the before and after syntax
 * Migration Reference - a reference for the Mule components and the syntax for Mule 3 vs Mule 4

MuleSoft will be releasing a tool to help automatically update applications to Mule 4 soon. We recommend that unless there is some urgent need, that users wait to update their applications until this is available to save time.

This guide should apply to all 3.x versions, however examples will reference Mule 3.9.

== See Also
 * link:index[Migrating to the Mule 4 Runtime]
 * link:migration-scope[What Changed?]
 * link:migration-prep[Preparing for the Migration]
 * link:migration-examples[Migration Examples]

////
 * link:migration-connectors[Migrating Core Connectors]
 * link:migration-connectors-noncore[Migrating Non-Core Connectors]
 * link:migration-components[Migrating Components]
 * link:migration-patterns[Migrating Common Features]
 * link:migration-testing[Testing the Migration]
 * link:migration-devkit[Migrating from DevKit to the Mule SDK]
 * link:migration-munit[Migrating Munit]
 * link:migration-other[Other Stuff to Migrate...]
////
