= Introduction to Mule 4: Connectors

In Mule 3, there were two ways of connecting to systems: transports and connectors. Transports used
the concept of inbound and outbound endpoints to send data. Connectors used the concept of operations to invoke
systems, for example, `<http:request>` or `<db:select>`. In Mule 3, MuleSoft started to replace some of these
transports through the new HTTP and Database connectors. Mule 4 completes this change by
completely standardizing the approach so that all connectivity is built as connectors. This has
improved the consistency and usability of connectors, as well as enabled more powerful connectors.

== Independent release cycles for Core Connectors and Modules

Another big difference is how the connectors are shipped and released. In Mule 3, there were a number of connectors/transports that were part of the Mule Runtime distribution (e.g.: File, Ftp, Sftp, HTTP, Database, JMS, XML, Validations, etc). To get fixes and enhancements to any of these connectors we had to wait for the next Mule Runtime release to be made available. Meanwhile, there were other connectors (typically the SaaS connectors) that were shipped and released independently (e.g.: Salesforce, Workday, ServiceNow, SAP, etc).

In Mule 4 we standarized in the latest model. The Mule 4 distribution ships with no connectors or modules, having each application include the modules it needs. This has the following advantages:

* Faster innovation in core modules/connectors by having all connectors in their own release cycle. Each time we add a new feature or bug fix, we can made that available to our users without having to wait for the next Mule Runtime release.
* Ability to have different applications using different versions of the same module. This allows for easier adoption of new releases without the need to run a full regression on applications that don't necesarilly benefit from the upgrade
* Consistent approach