= Introduction to Mule 4: Java Integration

== Expressions versus Code
Experienced Mule users will notice that Mule 4 takes a more opinionated approach to how applications should be structured,
limiting what can be done in the expression language.
The intention here is to provide a clear separation between business logic that should be extracted through code, and the flow logic.

If you want to extract, query, transform or otherwise work with data in your flows, DataWeave expressions and
transforms are the recommended tool. If you want to write complex logic, instantiate Java objects, or call arbitrary methods,
MuleSoft recommends that you encapsulate this code into scripts or classes, which can be easily injected and tested.
This means that we've removed the Expression component and Expression transformer to encourage you to cleanly separate
your logic into scripts or Java classes instead.

== Calling Java Functions from DataWeave

For the times where you want to call out to Java logic to aide in formatting or parsing of data, DataWeave now allows you to call out to static functions. Take this Java function, for example:
[source,Java,linenums]
----
package org.acme;
public class MyCompanyUtils {
  public static String reformat(String input) {
    return …;
  }
}
----
You can call it through the following DataWeave code:
[source,DataWeave,linenums]
----
import java!org::acme::MyCompanyUtils
---
{
  date: MyCompanyUtils::reformat(payload.input)
}
----

// == Calling Java Components From Flows
// TODO

== Scripting Module
The Scripting module is updated for Mule 4, enabling you to embed your Groovy, Ruby, Python, or JavaScript scripts inside Mule flows. You can inject data from the Mule message into your code using the new configuration attribute for parameters.

[source,XML,linenums]
----
<script:execute engine="groovy">
    <script:code>
         return "$payload $prop1 $prop2"
    </script:code>
    <script:parameters>
         #[{prop1: "Received", prop2: "A-OK"}]
    </script:parameters>
</script:execute>
----
