= Introduction to Mule 4

Mule 4's simplified language and reduced management complexity enables you to speed up the on-ramping process and deliver applications faster.

Conceptually, you can think of Mule 4 as an evolution of Mule 3. Many of the core concepts are the
same: applications, flows, connectors, DataWeave, etc. However, we've worked to simplify it so
there is less to learn and less for you to manage.

This overview will take you through the high-level changes in Mule 4 so that you can quickly learn the basics, and will cover:

* Mule Message - the Mule Message structure has evolved to make it easier to work with properties and provide more consistency across connectors.
* Expression language - the Mule Expression Language has been replaced with the DataWeave language so that you can more easily work with data and more easily learn Mule.
* Connectors - the approach to connectivity was unified in Mule 4. The Mule 3 transports were replaced with new operation oriented connectors wich are easier to use, have better out-of-the-box defaults, and provide new advanced capabilities.
* Error Handling - easier and more powerful error handling with a new Try scope.
* DataWeave - DataWeave includes minor changes to simplify the syntax and make it easier to learn.
* Studio 7 - featuring a simplified palette, improved Maven integration, and many other usability improvements.
* Runtime engine - the internal execution engine has been updated to achieve with a new self tunning non-blocking reactive engine. This allows for better performance and scalability out-of-the-box.
