= Mule 4 for Mule 3 Users: Java Integration

== Expressions vs. Code
Experienced Mule users will notice that DataWeave takes a more opinionated approach to what users can can do with the expression language.
The intention here is to provide clearly separation between business logic that should be extracted via code, and the flow logic.

If you wish to extract, query, transform or otherwise work with data in your flows, DataWeave expressions and
transforms are the recommended tool. If you wish to write complex logic, instantiate Java objects, call arbitrary methods
we recommend that you encapsulate this code into scripts or classes, which can be easily injected and tested.

For the times where you want to call out to Java logic to aide in formatting or parsing of data, DataWeave now allows you to call out to static functions. Take this Java function:
[source,DataWeave,linenums]
----
package org.acme;
public class MyCompanyUtils {  
  public static String reformat(String input) {    
    return …;  
  }
}
----
You can call it via the following DataWeave code:
[source,DataWeave,linenums]
----
import java!org::acme::MyCompanyUtils
---
{
  date: MyCompanyUtils::reformat(payload.input)
}
----

== Calling Java components from Flows
// ToDO