= Introduction to Mule 4: Configuring Mule Applications
In Mule 3, users often used Spring property placeholders to configure applications dynamically for the environment
they were deployed in. Mule 4 contains a built in mechanism to do this that allows setting of default values and nsures users are not required to learn Spring.

These properties are stored in a YAML file 
[source,yaml]
----
http:
  path: service
  port: "10000"
----

You can add the YAML file to your Mule app through the Global Element called Configuration Properties. The XML for it looks like this:
[source,xml]
----
<configuration-properties file="myConfiguration.yaml" doc:name="Configuration properties" doc:id="872422be-3571-4a52-a383-a2b0e16859d7" />
----

We highly recommend that you do not package the configuration files for all the environments inside your application. Instead,
we recommend that you use this file to provide defaults, then use Runtime Manager to override each of these properties at deployment time.

== See Also
* link:/mule-runtime/4.0/configuring-properties.html[Configuring Property Placeholders]