= Migrating Reconnection Strategies

Reconnection strategy settings are similar in Mule 3 and Mule 4. However, custom reconnection strategies are not available in Mule 4.

The examples below show changes to the XML for these settings:

* None: Default. Same as Do Not Use A Reconnection Strategy in Mule 3.
* Standard: Same as Standard Reconnection in Mule 3. Both have the same options: Frequency (ms), Reconnection Attempts
* Forever: Same as Reconnect Forever in Mule 3.
+
This example uses a database reconnection strategy to illustrate a pattern that is common to many connectors:
+
.Mule 3 Examples: Reconnection Settings (for a SQL database)
[source,xml, linenums]
----
<db:mysql-config ...>
  <reconnect frequency="4000" count="4"/>`
</db:mysql-config>

<db:mysql-config ...>
  <reconnect-forever frequency="4000"/>`
</db:mysql-config>
----
+
.Mule 4 Examples: Reconnection Settings (for a SQL database)
[source,xml, linenums]
----
<db:mssql-connection ...>
  <reconnection failsDeployment="true">
    <reconnect frequency="4000" count="4"/>
  </reconnection>
</db:mssql-connection>

<db:mssql-connection ...>
  <reconnection >
    <reconnect-forever frequency="4000" />
  </reconnection>
</db:mssql-connection>
----

Only available in Mule 4:

* Fail Deployment When Test Connection Fails (`failsDeployment="true|false"`).

== See Also

link:migration-examples[Migration Examples]

link:migration-patterns[Migration Patterns]

link:migration-connectors[Migrating Connectors]
