// Contacts/SMEs: Esteban Wasinger, Ana Felisatti, Mariano Gonzalez
= Preparing for the Migration

Mule 4 introduces many fundamental changes, so it is very important to plan for the migration from Mule 3 before attempting to perform a migration. Here is some basic guidance:

* <<when_to_start>>
* <<prepare_dev_environ>>
* <<prepare_to_deploy>>
* <<write_code>>

[[when_to_start]]
== When to Start Using Mule 4

First, you must think about when you and your organization should start using Mule 4. Once Mule 4 is GA, we recommend that you develop all *new* projects on Mule 4, provided that:

* You and your team has updated your skills for Mule 4 via the documentation or formal training.
* You have a deployment environment that is ready (see below).
* You do not require all applications applications to be on a single version of Mule (see below).

For projects which are already in development or deployed on Mule 3 (whether a prospect or customer), we recommend that you wait to migrate these applications until the Mule 3 to Mule 4 migration tool is released. However, if customers wish, they can follow this migration guide and do so manually.

Once the migration tool is released, you should migrate your applications if any one of the following conditions is met:

* The 3.x version you're using reaches end of life
* You want to make significant updates to the existing applications
* You want to take advantage of key Mule 4 capabilities
* You decide to upgrade all their apps to Mule 4 because you require all apps to be on one version (some onprem customers)

[[prepare_dev_environ]]
== Setting up Your Local Development Environment

First, you will need to download Studio 7 and install it. If you're deploying locally, you will also need to download the Mule 4 standalone runtime.
// TODO link to pages

[[prepare_to_deploy]]
== Getting Ready to Deploy
Next, you need to make sure your deployment environment is ready. Depending on which environment you have, different steps may be required.

[%header,cols="1,3"]
|===
|Deployment Mechanism | Instructions

|CloudHub
|CloudHub is Mule 4 ready.

|Hybrid Deployment
|You must install the standalone version of Mule 4 your servers.

|Private Cloud Edition
|You must be running PCE 1.7.1 or later to use Mule 4 with Runtime Manager. A future version will support Mule 4 via API Manager. You must also install the standalone version of Mule 4 on your servers.

|PCF
|PCF support is in development.
|===

// TODO link to instructions about installing standalone Mule 4

[[write_code]]
== Writing the Code

That's it! You're ready to start building and deploying Mule 4 applications.

You should review these topics to get an overview of the migration process and understand changes introduced in Mule 4:

link:migration-process[About the Migration Process]

link:intro-overview[Introduction to Mule 4]
