= Migrating Connectors to Mule 4

This section covers the migration of connector-specific features. (*NOTE: We can break the files out on a per connector basis if necessary*)

* From Mariano G: Multipart and attachment handling in email, WSC and Http (Contact: Ana Felisatti, Juani
 ** From Ana: HTTP should map directly to the docs on DW's support for multipart. Already created that ticket.
* <<connector_1>>: Description of migrated featured here.
* <<connector_2>>: Description of migrated featured here.

[[connector_1]]
== Connector_1

Intro re features covered:

 ** Feature_1
 ** Feature_2

=== Feature_1

Describe what changed from 3.x to 4.x.

.Mule 3 example
----
Mule 3 example goes here.
----

.Mule 4 example
----
Mule 4 example goes here.
----

=== Feature_2

Describe what changed from 3.x to 4.x.

.Mule 3 example
----
Mule 3 example goes here.
----

.Mule 4 example
----
Mule 4 example goes here.
----

[[connector_2]]
== Connector_2

Follows the same pattern.

== See Also

link:migration-examples[Migration Examples]

link:migration-patterns[Migration Patterns]

link:migration-components[Migrating Components]
