// sme: DF, author: sduke?
= Migrating the Choice Router

Little changed between Choice router for Mule 3 and Mule 4 except for the use of DataWeave 2 as the expression language for the `when` statements, rather than DataWeave 1 or the Mule Expression Language (MEL). In addition, the Choice Exception Strategy is now handled through Mule 4 error handlers.

== Expression Language for the When Block

You need to upgrade your Choice component expressions to use DataWeave 2.

.Mule 3 Example: MEL
----
<choice>
  <when expression="#[payload.getPurchaseType() == 'book']">
    <-- so something -->
  </when>
  <when expression="#[payload.getPurchaseType() == 'mp3']">
    <-- so something -->
  </when>
</choice>
----

.Mule 3 Example: DataWeave 2
----
<choice>
  <when expression="#[payload.puchaseType == 'book']">
    <-- do something -->
  </when>
  <when expression="#[payload.puchaseType == 'mp3']">
    <-- do something -->
  </when>
  <otherwise>
    <-- do something -->
  </otherwise>
</choice>
----

=== Example (flowVars vs. vars)

For the Mule 3 example, notice that the `when` expression uses the expression `#[flowVars.language == 'french']` to set a variable.

.Mule 3 Example
----
<choice doc:name="Choice">
  <when expression="#[flowVars.language == 'french']">
    <set-payload value="Bonjour!" doc:name="Reply in French"/>
  </when>
  <when expression="#[flowVars.language == 'spanish']">
    <set-payload value="Hola!" doc:name="Reply in Spanish"/>
  </when>
  <otherwise>
    <set-variable variableName="language" value="English" doc:name="Set to English"/>
    <set-payload value="Hello!" doc:name="Reply in English"/>
  </otherwise>
</choice>
----

For the Mule 4 example, notice that the `when` expression uses the expression `#[vars.language == 'french']` to set a variable.

.Mule 4 example
----
<choice doc:name="Set Language" doc:id="f480b975-c0ba-4174-9415-67d83d8fd7f8" >
  <when expression="#[vars.language == 'french']" >
    <set-payload value='"Bonjour!"' doc:name="Reply in French" doc:id="f4600b8d-6dc7-48b7-9bac-247cf217380f" />
  </when>
  <when expression="#[vars.language == 'spanish']" >
    <set-payload value="Hola!" doc:name="Reply in Spanish" doc:id="abcb0ec5-c01e-4854-9010-9cd042941c55" />
  </when>
  <otherwise >
    <set-payload value="Hello!" doc:name="Reply in English" doc:id="d169c96a-41ec-4110-81e1-17230af3f862" />
  </otherwise>
</choice>
----

[[choice_exception_strategy]]
== Choice Exception Strategy

In Mule 4, the Error Handler (`<error-handler>`) replaces the Choice Exception Strategy (`choice-exception-strategy`). Its child handlers are matched through the error type, rather than as a Java exception.

.Mule 3 Example
----
<flow name="Sample_Flow">
...
  <choice-exception-strategy doc:name="Choice Exception Strategy">
    <catch-exception-strategy doc:name="Catch Exception Strategy"  when="#[exception.causedBy(org.mule.api.routing.filter.FilterUnacceptedException)]">
      <set-variable variableName="errorStatusCode" value="404" doc:name="Set status code"/>
      <set-variable variableName="errorReasonPhrase" value="Not Found" doc:name="Set reason phrase"/>
    </catch-exception-strategy>
    <rollback-exception-strategy doc:name="Rollback Exception Strategy">
      <logger level="INFO" doc:name="Logger" message="Unknown error"/>
    </rollback-exception-strategy>
  </choice-exception-strategy>
</flow>
----

For a Mule 4 example, see link:migration-core-exception-strategies[Migrating Exception Strategies to Mule Error Handlers]

== See Also

link:migration-intro-error-handlers[Introduction to Mule 4: Error Handlers]
link:migration-mel[Migrating from MEL to DataWeave]
link:migration-dataweave[Migrating from DataWeave 1.0 to 2.x]
link:migration-core-exception-strategies[Migrating Exception Strategies to Error Handlers]
