// sme: DF, author: sduke?
= Migrating the Choice Router

Little changed between Choice router for Mule 3 and Mule 4 except for the use of DataWeave 2 as the expression language for the `when` statements, rather than DataWeave 1 or the Mule Expression Language (MEL). In addition, the Choice Exception Strategy is now handled through Mule 4 error handlers.

== Expression Language for the When Block

=== Example (MEL to DataWeave)

TODO: PROVIDE INTRO

.Input
----

----


.Mule 3 Example
----
<choice>
  <when expression="#[payload.getPurchaseType() == 'book']">
    <jms:outbound-endpoint queue="bookPurchases" />
  </when>
  <when expression="#[payload.getPurchaseType() == 'mp3']">
    <jms:outbound-endpoint queue="songPurchases" />
  </when>
 </choice>
----

.Mule 4 Example



=== Example (flowVars vs. vars)

For the Mule 3 example, notice that the `when` expression uses the expression `#[flowVars.language == 'french']` to set a variable.

.Mule 3 Example
----
<choice doc:name="Choice">
  <when expression="#[flowVars.language == 'french']">
    <set-payload value="Bonjour!" doc:name="Reply in French"/>
  </when>
  <when expression="#[flowVars.language == 'spanish']">
    <set-payload value="Hola!" doc:name="Reply in Spanish"/>
  </when>
  <otherwise>
    <set-variable variableName="language" value="English" doc:name="Set to English"/>
    <set-payload value="Hello!" doc:name="Reply in English"/>
  </otherwise>
</choice>
----

For the Mule 4 example, notice that the `when` expression uses the expression `#[vars.language == 'french']` to set a variable.

.Mule 4 example
----
<choice doc:name="Set Language" doc:id="f480b975-c0ba-4174-9415-67d83d8fd7f8" >
  <when expression="#[vars.language == 'french']" >
    <set-payload value='"Bonjour!"' doc:name="Reply in French" doc:id="f4600b8d-6dc7-48b7-9bac-247cf217380f" />
  </when>
  <when expression="#[vars.language == 'spanish']" >
    <set-payload value="Hola!" doc:name="Reply in Spanish" doc:id="abcb0ec5-c01e-4854-9010-9cd042941c55" />
  </when>
  <otherwise >
    <set-payload value="Hello!" doc:name="Reply in English" doc:id="d169c96a-41ec-4110-81e1-17230af3f862" />
  </otherwise>
</choice>
----

[[choice_exception_strategy]]
== Choice Exception Strategy

The Error Handler (`<error-handler>`) replaces the Choice Exception Strategy. Its child handlers are matched through the error type, rather than as a Java exception.

== See Also

link:migration-mel[Migrating from MEL to DataWeave]

link:migration-dataweave[Migrating from DataWeave 1.0 to 2.x]

link:migration-patterns-error-handlers[Migrating Exception Strategies]

////
link:migration-examples[Migration Examples]

link:migration-patterns[Migration Patterns]

link:migration-components[Migrating Components]
////
