// Contacts/SMEs: Andres Alleva
= About the Migration Process

//TODO: LINK TO MULE 4 SECTIONS FOR ALL THESE STEPS.

Here are the high-level steps for a manual migration:

. Adding all required modules, such as the Database connector, to Studio 7 palette.
+
Note that all Mule projects are Mavenized by default when you add the modules to your project.
+
. Migrating all the global configurations.
. Migrating configuration properties.
+
// .yaml or .properties. Include link to properties config in Mule 4.
+
. Check how the components work in Mule 4 to see what has changed from Mule 3.
. Understand how changes to the Mule message structure (attributes, payload, and variables).
. Update your expressions and scripts to DataWeave 2:
** Be aware of changes in DataWeave 2 scripts, for example, importing specific function modules and understanding syntax changes.
+
// TODO: ASK ABOUT MIGRATION TOOL, TASK TO MIGRATE SCRIPTS FROM 1.0 TO 2.
+
** Change MEL expressions to DataWeave 2, for example, in an connector or Choice component.
. Update all exception handling to Mule 4 with the new exception types that are available.
. If you are working with APIs, check for way to set HTTP status codes.
