// sme: MG, author: sduke?
= Migrating to the FTP and SFTP Connector

////
MVP: Just take the blog post and format following the object-store template. Keep in mind these connectors were splitted
////

// Explain generally how and why things changed between Mule 3 and Mule 4.
Intro here: What we're migrating from/to?

What's covered in this section:

* Feature_1
* Feature_2

[[connector_ftp]]
== Migrating to FTP

Intro re features covered:

 ** Feature_1
 ** Feature_2

=== Feature_1

Describe what changed from 3.x to 4.x.

.Mule 3 example
----
Mule 3 example goes here.
----

.Mule 4 example
----
Mule 4 example goes here.
----

=== Migrating to SFTP

Describe what changed from 3.x to 4.x.

.Mule 3 example
----
Mule 3 example goes here.
----

.Mule 4 example
----
Mule 4 example goes here.
----

[[connector_2]]
== Connector_2

Follows the same pattern.

== See Also

link:migration-examples[Migration Examples]

link:migration-patterns[Migration Patterns]

link:migration-components[Migrating Components]
