// sme: DF, author: sduke?
= Migrating the For Each Scope

Little changed between For Each scope for Mule 3 and Mule 4 except for the use of DataWeave 2 as the expression language, rather than DataWeave 1 or the Mule Expression Language (MEL).

.Mule 3 example
----
<foreach doc:name="For Each in Studio 6" batchSize="10" collection="#[payload.myNode]" counterVariableName="myCounter6" rootMessageVariableName="myRootMessage6">
  <some-nested-element/>
  <some-other-nested-element/>
</foreach>
----

For the Mule 4 example, notice that the `when` expression uses the expression `#[vars.language == 'french']` to set a variable.

.Mule 4 example
----
<foreach doc:name="For Each in Studio 7" collection="#[payload.myNode]" batchSize="10" rootMessageVariableName="myRootMessage7" counterVariableName="myCounter7">
  <some-nested-element/>
  <some-other-nested-element/>
</foreach>
----

[[choice_exception_strategy]]
== Choice Exception Strategy

The Error Handler (`<error-handler>`) replaces the Choice Exception Strategy. Its child handlers are matched through the error type, rather than as a Java exception.

== See Also

link:migration-patterns-error-handlers[Migrating Exception Strategies]

link:migration-mel[Migrating from MEL to DataWeave]

link:migration-dataweave[Migrating from DataWeave 1.0 to 2.x]

////
link:migration-examples[Migration Examples]

link:migration-patterns[Migration Patterns]

link:migration-components[Migrating Components]
////
