= Migrating Connectors and Components

This section covers the migration of specific components, connectors, and common features they share.

Topics for this section:

* Very short description of processor, component, connector, module, and related terminology.
* For processors that are not supported anymore, provide a general idea of how to approach the migration, with examples as needed for critical ones.
* For those with important diffs in 4.x that affect migration, explain how to deal with those diffs. Representative examples.
 ** Core connectors: Could Mariano G. help provide this info since he is documenting these connectors?
Multipart and attachment handling in email, WSC and Http
 ** Cloud connectors (built inhouse): Could Marcos Nunes Cortes help provide this info?
 ** Non-core connectors (built by 3rd party contractors): Could Nathan or dev teams help provide this info? TBD, waiting to hear back from Nathan.
 ** Components: Could component devs help provide info on migration processes?
* For those that are supported and migration is easy or straightforward, TBD
* Anything else?

////
== See Also
////
