// sme: MG?, author: sduke?
= Migrating Watermarks

// Explain generally how and why things changed between Mule 3 and Mule 4.
Watermarks are... sync data ... etc. MORE INTRO

NOTES FOR PREPARING DOCS:

MG says there's a new boolean in some core connectors to enable the watermark. Watermark is new to Cloud connectors though (talk to MNC). Core connectors are FTP/SFTP, VM, File by Mule 4 GA, and DB soon after that.

TODO: Not sure how we handle Mule4-compatible connectors that support a watermark but don't have the switch.

See blogs:
https://blogs.mulesoft.com/tag/watermark/
https://blogs.mulesoft.com/dev/mule-dev/how-poll-scope-and-watermark/


.Mule 3 example
----
Mule 3 example goes here.
----

In Mule 4, you instead create a

.Mule 4 example
----
Mule 4 example goes here.
----

[[topic_2]]
=== Topic_2

SAME PATTERN AS TOPIC 1

.Mule 3 example
----
Mule 3 example goes here.
----

.Mule 4 example
----
Mule 4 example goes here.
----


== See Also

link:migration-examples[Migration Examples]

link:migration-patterns[Migration Patterns]

link:migration-components[Migrating Components]
