// Contacts/SMEs: Esteban Wasinger, Ana Felisatti
= Migrating MEL to DataWeave

////
Note:
Mariano G. says most people using MEL to access the payload. For simple expressions, migration tool will do it, but we will have to help migrate complex mappings. No date on migrator, but is first priority after GA. Somewhere in the Mule.

We'll try to map some of the most frequently used MEL expressions to DW expressions for initial release of guide and add to that list as needed in subsequent versions of guide.
////

Topics to cover:

* MEL expressions to DataWeave 2.x (2.1?)
* Preliminary plan is to take examples from Mule 3 docs and show how to migrate them to 4.0. See https://docs.mulesoft.com/mule-user-guide/v/3.9/mule-expression-language-mel
* 3 primary use cases (from Dan Feist):
 ** Extract of a value from a message (for logging, or simple transformation etc).
 ** Evaluate of a condition (for use in validation, routing etc)
 ** Define a target: Dan says “was primarily only used in enricher which is now not supported in 4.0”. Looks like this will be covered in link:migration-patterns[Migration Patterns].
+
We now use the target variable instead in 4.0
For those who have not used DW, guide them through (or point them to info on) DW basics:
+
  *** Selectors
  *** Basic operators
  *** Control flow
  *** Map, filter functions (advanced feature but helps give an idea of what you can do with DW)
  *** Instead of accessing data with Java methods, access with DW selectors
  *** Can call static Java functions directly from DW (e.g., to get the object’s properties), but can’t call Java methods in the object or alter state of the object.
  *** Instead of inboundProperties (e.g., #[message.inboundProperties.'propertyName']) use attributes (e.g., attributes.header.propertyName)
  *** MEL flowVars.myVar is DW vars.myVar
  *** MEL XPath, regex, and wildcards can be matched to DW features, e.g.:
  **** MEL regex function vs. DW matches and match functions
  **** MEL XPATH to DW _TODO_ (ask Mariano D'Achaval or Shoki)
  **** Wildcards to DW _TODO_ (ask Mariano D'Achaval of Shoki)
  **** Update Choice example (from docs.mulesoft.com) to manipulate the flow
  **** Cannot assign values in DW as in MEL: need to use the Scripting module for that
