// sme: MG?, author: sduke?
= Migrating the Enricher to a Target Variable

// Explain generally how and why things changed between Mule 3 and Mule 4.
The Message Enricher and its functionality in Mule 3 is replaced by the Target Variable in Mule 4. The Enricher provided a way to add information not provided by the source system. In Mule 4, several modules (including Flow Ref, Object Store, HTTP, FTP, SFTP, and Database) can store and output a Target Variable for such data in a variable (such as `myVar`). Other components in a Mule flow can then access that data from the Mule event through a DataWeave selector (for example, `vars.myVar`).

Consider a message from a source system that contains a zip code, but the target system needs the two letter state. In Mule 3, the Message Enricher might look up the state using the zip code from an enrichment resource. The Enricher calls out to the enrichment resource with the current message (containing the zip code), then enriches the current message with the result.

.Mule 3 example
----
<flow name="orderProcessingFlow">
   <inbound-endpoint ref="orderEndpoint"/>
   <enricher target="#[variable:state]">
       <outbound-endpoint ref="stateLookup"/>
   </enricher>
   <outbound-endpoint ref="orderStep2"/>
</flow>
----

In Mule 4, you create a target variable through a component, such as Flow Ref. The target variable for Flow Ref will store the output of a flow. You can then use that output in a transformation to enrich your message.

For example, similar to the Mule 3 example, the flow `stateLookup` below might look up a state based on a zip code in the record retrieved through an operation, such as the Database Select operation (`db:select`). The next component in the flow (here, a FTP Write operation called `Write record that includes zip code`) can then perform a transformation that uses output from the `stateLookup` process to enrich the record with state name. That transformation might call something like `#[vars.state]` to get the state code from the variable.

.Mule 4 example
----
<flow name="orderProcessingFlow">
  <http:listener/>
  <db:select doc:name="Select record containing zip code" .../>
  <flow-ref doc:name="stateLookup" name="stateLookup" target="state" targetValue="#[payload]"/>
  <ftp:write doc:name="Write record that includes zip code" config-ref="FTP_Config" path="/output"/>
</flow>
<flow name="stateLookup">
  <!-- Your stateLookup processes here to retrieve the zip code -->
</flow>
----

////
== See Also

link:migration-examples[Migration Examples]
link:migration-reference[Migration Reference]
////
