// Contacts/SMEs: Esteban Wasinger, Ana Felisatti
= Migrating MEL to DataWeave

In Mule 4, the DataWeave expression language replaces Mule Expression Language (MEL). This section provides guidance on migrating MEL expressions in your Mule apps to  link:https://beta-anypt-dw.docs-stgx.mulesoft.com/mule-user-guide/v/4.0/dataweave[DataWeave 2.0 and later].

ALSO TODO: show how to use MEL expressions in DW?

TODO, SEE THESE TO MAKE SURE EXAMPLES COVERED:
https://blogs.mulesoft.com/dev/mule-dev/why-dataweave-main-expression-language-mule-4/


// _TODO: THIS LINK WILL CHANGE_

// Explain generally how and why things changed between Mule 3 and Mule 4.
Intro here.

Here are the main differences between MEL and DataWeave:

[%header,cols="2,3a"]
|===
| MEL | DataWeave or Alternative Procedure

| Extracting data, for example: `#[_TODO_]`
| Use DataWeave selectors such as `#[_TODO_]`. See _TODO: PROVIDE LINK_.

| Assigning values, for example: _TODO_
| Use the Scripting component instead. See _TODO: PROVIDE LINK_

| Using Java methods, for example: `#[]`
| Only static Java methods are allowed in DataWeave. Otherwise, you should use the Java component to act on the Mule event.

| Target definitions such as `#[flowVars.output]`.
| Use a Target Variable from a Mule component or connector. See link:/connectors/target-variables[About Target Variables].

| XPath 3 such as `#[xpath3('//root/element1')]`
| Use DataWeave selectors. Note that navigation to ancestor nodes is not supported. _TODO: ALT PROCEDURE NEEDED: HOW TO HANDLE THIS?_

| Wildcards
| _TODO_

| link:https://docs.mulesoft.com/mule-user-guide/v/3.9/mel-cheat-sheet#server-mule-application-and-message-variables[Mule context variables] are largely the same.
|
[%hardbreaks]
For DataWeave, see
//_TODO: THIS LINK WILL CHANGE_
link:https://beta-anypt-dw.docs-stgx.mulesoft.com/mule-user-guide/v/4.0/dataweave-variables-context[Context Variables in DataWeave]. However, the following MEL variables are unavailable in DataWeave (_TODO: VERIFY AND COMPLETE THIS LIST_):

* `apps.registry` replaced by _TODO_
* `message.flowVars` replaced by `vars`, for example, `#[vars.myVar]` where `myVar` is the name of the variable.
* `message.inboundProperties` replaced by _TODO_
* `message.inboundAttachments` replaced by _TODO_
* `message.outboundProperties` replaced by _TODO_
* `message.outboundAttachments` replaced by _TODO_
* `message.sessionVars` replaced by _TODO_
* `server.dateTime` replaced by _TODO_
|===



Topics to cover:

* MEL expressions to DataWeave 2.x (2.1?)
* Preliminary plan is to take examples from Mule 3 docs and show how to migrate them to 4.0. See https://docs.mulesoft.com/mule-user-guide/v/3.9/mule-expression-language-mel
* 3 primary use cases (from Dan Feist):
 ** Extract of a value from a message (for logging, or simple transformation etc).
+
Examples:
+
 *** `#[payload]` same in DW.
 *** `#[message.payload]` to DW: `#[payload]`
 *** *TODO*: `#[message.inboundProperties.'propertyName']` to DW: `#[attributes.inboundProperties.'propertyName']`
 *** `#[<logger message="#[payload]" />]` same DW.
 *** *TODO*: `#[payload.methodCall(parameters)]` to DW:
 *** *TODO*: `#[xpath3('//root/element1')]` to DW:
 ** Evaluate of a condition (for use in validation, routing etc)
 *** `#[payload.age > 21]` same as DW.
 *** *TODO*: `#[message.inboundProperties.'locale' == 'en_us']`
 ** Define a target:
 *** Dan says “was primarily only used in enricher which is now not supported in 4.0”. Looks like this will be covered in link:migration-patterns[Migration Patterns].
 *** `#[flowVars.output]` is now handled through Target Variables. See previous link.
+
We now use the target variable instead in 4.0
For those who have not used DW, guide them through (or point them to info on) DW basics:
+
  *** Selectors.
  *** Basic operators
  *** Control flow
  *** Map, filter functions (advanced feature but helps give an idea of what you can do with DW)
  *** Instead of accessing data with Java methods, access with DW selectors.
  *** Can call static Java functions directly from DW (e.g., to get the object’s properties), but can’t call Java methods in the object or alter state of the object.
  *** Instead of inboundProperties (e.g., #[message.inboundProperties.'propertyName']) use attributes (e.g., attributes.header.propertyName)
  *** MEL flowVars.myVar is DW vars.myVar
  *** MEL XPath, regex, and wildcards can be matched to DW features, e.g.:
  **** MEL regex function vs. DW matches and match functions
  **** MEL XPATH to DW _TODO_ (ask Mariano D'Achaval, Shoki, or Esteban W.)
  **** Wildcards to DW _TODO_ (ask Mariano D'Achaval, Shoki, or Esteban W.)
  **** Update Choice example (from docs.mulesoft.com) to manipulate the flow:
+
.MEL Expression
----
<choice>
   <when expression="#[payload.getPurchaseType() == 'book']">
        <jms:outbound-endpoint queue="bookPurchases" />
    </when>
   <when expression="#[payload.getPurchaseType() == 'mp3']">
        <jms:outbound-endpoint queue="songPurchases" />
    </when>
 </choice>
----
+
+
.DataWeave Expression
*TODO: DW example needs to align better with MEL example*
----
<choice doc:name="Choice">
  <when expression="#[vars.language == 'french']">
    <set-payload value="Bonjour!" doc:name="Reply in French"/>
  </when>
  <when expression="#[var.language == 'spanish']">
    <set-payload value="Hola!" doc:name="Reply in Spanish"/>
  </when>
  <otherwise >
    <set-variable variableName="language" value="English" doc:name="Set Language to English"/>
    <set-payload value="Hello!" doc:name="Reply in English"/>
  </otherwise>
</choice>
----
+
  **** Cannot assign values in DW as in MEL: need to use the Scripting module for that. *TODO: Need example.*


FROM ANA'S BLOG:

== Date Time
* MEL: `#[payload.name ++ '.' ++ dataType.mimeType.subType]`
* DataWeave: `#[payload ++ { date : now() }]`


////
  Note:
  Mariano G. says most people using MEL to access the payload. For simple expressions, migration tool will do it, but we will have to help migrate complex mappings. No date on migrator, but is first priority after GA. Somewhere in the Mule.

  We'll try to map some of the most frequently used MEL expressions to DW expressions for initial release of guide and add to that list as needed in subsequent versions of guide.
////

== See Also

link:https://blogs.mulesoft.com/dev/mule-dev/why-dataweave-main-expression-language-mule-4/[Why DataWeave is the Main Expression Language in Mule 4 Beta]
