= Migrating the Secure Properties Placeholder 

In mule 3, the Secure Properties Placeholder was part of the Security Module. In Mule 4, it is separated in it's own module.

.Complete example of Secure Properties Placeholder in Mule 3
[source,xml, linenums]
----
<secure-property-placeholder:config name="Secure_Property_Placeholder" key="${prod.key}" location="test.${env}.properties" encryptionAlgorithm="Blowfish" encryptionMode="CBC"/>
----
In the new Secure Configuration Properties module, the attribute `location` is replaced by `file`, for consistency with other components. In the Mule 3 module, the location attribute could have defined more than one file, separated by `;`. In the new version, this is not possible, for troubleshooting purposes. In case of working with more than one file, then it will be necesary to define a `<secure-properties:config>` tag for each file. Also, in case of overlapping properties between those files, in Mule 3 the one that was preserved was the last definition. Instead, in the new module it will be the first one.

The encryption attributes (`mode` and `algorithm`) are defined in the child tag `<secure-properties:encrypt/>`, and the supported algorithms and modes are the same for both Mule 3 and 4 (see [[secure_configuration_properties]] for more information).

The full migration of the previous example would be: 
.Complete migration example
[source,xml, linenums]
----
<secure-properties:config key="${prod.key}" file="test.${env}.properties" name="Secure_Property_Placeholder">
    <secure-properties:encrypt algorithm="Blowfish" mode="CBC"/>
</secure-properties:config>
----

== See also
[[secure_configuration_properties]]
* link:/connectors/secure-configuration-properties[Mule 4 Secure Configuration Properties]