// Contacts/SMEs: Andres Alleva
= About the Migration Process

//TODO: LINK TO MULE 4 SECTIONS FOR ALL THESE STEPS.
After learning how to prepare for the migration, it is important to understand the high-level migration steps:

. Add all required modules, such as the Database connector, to the Studio 7 palette. 

NOTE: 

Many modules can be added directly in the Studio 7 Mule Palette. Other modules can be searched and added from Anypoint Exchange. 
+
Note: that all Mule projects are Mavenized by default when you add the modules to your project.
+
. Migrate all the global configurations.
. Migrate configuration properties.
+
// .yaml or .properties. Include link to properties config in Mule 4.
+
. Learn how the components work in Mule 4 to see what has changed from Mule 3.
. Understand how changes to the Mule message structure (attributes, payload, and variables) affect your configurations.
. Update your expressions and scripts to DataWeave version 2:
** Be aware of changes between DataWeave 1 and DataWeave 2, for example, importing specific function modules and understanding syntax changes.
+
// TODO: ASK ABOUT MIGRATION TOOL, TASK TO MIGRATE SCRIPTS FROM 1.0 TO 2.
+
** Change MEL expressions to DataWeave 2, for example, in an connector or Choice component.
. Update all exception handling to Mule 4 with the new exception types that are available.
. If you are working with APIs, understand how to set HTTP status codes.

== See Also

link::migration-prep[Preparing for the Migration]

link:intro-overview[Introduction to Mule 4]
