= Topics to Cover in Migration Guide (3.x to 4.x)

If you have any additions or comments, please do a pull request on the beta-migration branch so I can catch it. Thanks!

* Intro

From github, see [Migrating to the Mule 4 Runtime](index.adoc).
See link:index.adoc[Migrating to the Mule 4 Runtime]

* Prepare for migration
+
(Contacts/SMEs: Mariano G?)
+
See link:migration-prep[Preparing for the Migration]

* Example(s) of Mule app migration walkthrough
+
(Contact/SME: Andres Alleva)
+
See link:migration-examples[Migration Examples]

* Common patterns
+
(Contact/SME: Mariano Gonzalez)
+
See link:migration-patterns[Migration Patterns]

* Migrating specific Components, Connectors, Strategies, etc.
+
(Contact/SME: Mariano Gonzalez, Marcos Nunes Cortes, Matias Baldini, Nathan Nam?)
+
See link:migration-processors[Migration Connectors and Components]

* MEL to DW guidance
+
(Contacts/SMEs: Ana Felisatti, Esteban Wasinger)
+
See link:migration-mel[Migrating MEL to DataWeave]

* Deploy to a test or staging environment?
+
TBD if this section is needed.

* Testing app
+
(Contact/SME: Andres Alleva?)
+
* Tips or recommendations?

See link:migration-testing[Testing the Migration to Mule 4]

Other potential contacts or reviewers:

* Andy Hoy (recommended by Lorraine)
* Drew Jaegle (recommended by Lorraine)
* Ethan Port for DW/MEL
