= Anypoint Studio Features 
:keywords: anypoint, studio, eclipse, visual editor, XML editor

Anypoint Studio, MuleSoft's Eclipse-based integration development environment, offers a wealth of features for building, debugging and testing Mule applications and more.


== Basic Functionality

* link:/anypoint-studio/v/6.5/importing-and-exporting-in-studio[Importing and Exporting projects]
* link:/anypoint-studio/v/6.5/keyboard-shortcuts-in-studio[Keyboard Shortcuts]
* link:/anypoint-studio/v/6.5/changing-runtimes-in-studio[Changing Mule Runtimes]

[TIP]
For a basic overview of how to use both the Visual editor and the XML editor to create Mule applications, see the link:/anypoint-studio/v/6.5/[parent document] of this section.

== Metadata Visualization

Get exposure to *metadata* at design-time through link:/anypoint-studio/v/6.5/datasense[DataSense]. By clicking on any element of your flows, you can link:/anypoint-studio/v/6.5/using-the-datasense-explorer[see] the metadata that describes both the expected input and output of that element, using everything that is known to Studio as a context for deducing that.



== Powerful Data Mapping

Handle complex data mappings and transformations through the link:/anypoint-studio/v/6.5/transform-message-component-concept-studio[Transform Message Component], that leverages the powerful link:/mule-user-guide/v/3.8/dataweave[DataWeave] language. This component allows you to create your transformations both through a simple drag and drop visual interface or by coding in DataWeave to unleash all of the language's potential.


== Debugging and Testing

=== Embedded Server

Anypoint Studio comes with an embedded test server that's ready for easily deploying your applications without leaving your IDE.

[NOTE]
Note that this server is not meant for production deployments, as uptime restrictions apply.


=== Visual Debugger

Use the link:/anypoint-studio/v/6.5/studio-visual-debugger[Studio Visual Debugger] to run your application placing breakpoints and viewing data as it transitions through your flows to find the root of an issue.


=== Unit Testing with MUnit

Use link:/munit/v/1.2.0/using-munit-in-anypoint-studio[MUnit] to automatically create and run unit tests on your applications. That way you can be certain that any changes you make to your application won't brake it or alter how it behaves.


== APIKit

* Based on a link:https://raml.org/[*RAML*] or a *WSDL* file, you can use link:/apikit/[APIkit] to automatically build scaffoldings for all of the backend flows of a Mule application, as well as exception handling flows. All you have to do then is populate these with operations.

* Also, as a beta feature, you can use APIkit with link:/apikit/creating-an-odata-api-with-apikit[OData]

== Additional RAML Support

link:https://raml.org/[RAML] is a widely used standard for defining APIs through a very simple syntax, similar to that of YAML.

* You can import RAML files for your APIs that are managed in the Anypoint Platform by the link:/api-manager[API Manager] and link:/anypoint-studio/v/6.5/api-sync-reference[keep them in sync] with the platform.

* While working with a RAML file, you can also view an embedded interactive API Console that's automatically built from the resources and methods described in your RAML.





== Advanced Functionality

* link:/anypoint-studio/v/6.5/starting-the-runtime-in-cluster-mode-in-studio[Starting the Runtime in Cluster Mode in Studio]
* link:/anypoint-studio/v/6.5/adding-source-attachments-to-studio[Adding Source Attachments to Studio]



== See Also 

* link:/getting-started/build-a-hello-world-application[Build an application in Anypoint Studio].
* link:/anypoint-studio/v/6.5/setting-up-your-development-environment[Setting Up Your Development Environment]
