Are we going to continue to talk about Jetty endpoints in the docs, or is the audience for this info relative to our new products too small?

https://docs.google.com/document/d/1Pj9XGN1Xj6WLE3P5YOr_WfZ0PBZuHlPugCy-Ycx5sck/edit

Old--per api permission
New- per environment permission

zip files imported from DC, Exchange, and API Manager

In the meeting with Eva and Ruiz, she confirmed that apikit changes w/b minimal. also, most of the gateway changes would impact policy and proxy reference docs. they will provide a rough draft of those docs.

unclassified -- not previously in an environment
classify -- put into an environment
promote -- happens only on an environment

You can have multiple instances of an api, name of instance

You need to be on Crowd release to use Mule 4

Nov release will have some of the GW features

GW 4.0 -- all of features on GA in Jan

API Manager will no support all GW features, no proxy, no deploy thru API manager.

Policies will have dependencies.

custom policies need to have dependents

more latency OOTB policies

Lite weight specify Mavin repo and heavy-weight policy -- download all

OOTB policy living in Exchange

Custom policy upload to org in Exchange

Exchange has no UI yet, will have to use maven

Policy packaging-- in JAR

Custom policy will have JAR, HTTP custom policy include dependency for HTTP (heavy), put reference to Maven where dependent policy w/b downloaded.

Configure and upload custom policy thru exchange using Maven

See if doc in Runtime.

Big changes in configuration of custom policy.

Old way = before/after

Change template

Apply outbound policy, more managability of flow of policy

Error handling new

Still have offline policy

Removing some pointcuts (where, applied)

Everything is non-blocking in mule 4

How policies are stred, folder with xml

docs have to explain where to find them

OOTB--support some adding a new RAML validator policy

Policy was extension of application, now it's like its own applicaiton, has a class loader

All authorization that the policy accepts will be in the auth object, so customer applications will be able to ....

Headers won't be by default -- a vulnerability, optional

No dependency in policy built into policy

OOTB used to have authorization, now will have BASIC and LDAP


Auto discovery changes slightly, schema name, align with crowd, api id

You do not create API in API Mgr.

Resource level policy supported for any HTTP application, not just RAML.

Order policies in any order, doesn't make sense to have CORS anywhere but first

Proxies =-- heavier, now include dependencies--RAML, HTTP, and WSDL

going to rtake longer to download 5 min, 13 min, 17 WSDL

-----------------------------------------


https://docs.google.com/document/d/1Pj9XGN1Xj6WLE3P5YOr_WfZ0PBZuHlPugCy-Ycx5sck/edit?ts=59efa765


Policy packaging
JARs with its dependencies
Lightweight/Heavyweight.
Mechanism to download online policies JARs
Upload custom policies to Exchange
SDLC of policies: independent releases

Policies in general
New outlook of policies

<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns:http-policy="http://www.mulesoft.org/schema/mule/http-policy"
...>

   <http-policy:proxy name="policy-template">
       <http-policy:source>
before
           <http-policy:execute-next/>
after
       </http-policy:source>
<http-policy:operation>
   <http-policy:execute-next/>
</http-policy:operation>
   </http-policy:proxy>
</mule>

Outbound policies
Any policy can stop the chain by not executing “<http-policy:execute-next/>”
Removed App, Endpoint pointcuts
Offline policies
How policies are stored in FS
Everything is non-blocking

OOTB Policies
Mention new OOTB policies
RAML Validator
Add / Remove headers [Not for EA]
Authentication info is propagated in Authentication/Principal instead of flowVars or properties
Headers are not propagated anymore by default from policies. It can be enabled, though
PF/SLA not one policy anymore. They can be aggregated.
Simple Security Manager is dead.
Dependencies are no longer supported. E.g: Basic Auth LDAP 

Custom Policies
What’s new? 
Error Handling
Chaining errors
Different behaviours: on-error-continue vs on-error-propagate
Flow Refs
Scoping: Variables have policy scope only. Message is propagated through policies/flow
Handlebars instead of Mustache
Examples:
We should migrate some Exchange custom policies

General
Auto discovery create true removed.
Autodiscovery element change to only require id
Resource pointcuts not only for RAMLs
Policy ordering not fixed anymore (throttling, CORS)

Proxies
WSDL is using Compatibility plugin
Heavy and lightweight options for proxies

-------------------------------------------------
When you write your section on Manage API from Exchange, would you reference these Exchange concepts?

HTTP API - Users can create an HTTP API asset in a Private Exchange that they apply proxies and policies to in API Manager. Described in https://beta-exchange2.docs-stgx.mulesoft.com/anypoint-exchange/to-create-an-asset
Exchange Visibility Settings - Users can indicate in a Private Exchange whether a proxy or policy associated with a service is public within the portal or private so that it's only visible to a select group. This is described in a doc I'm writing that will have this URL tomorrow: https://beta-exchange2.docs-stgx.mulesoft.com/anypoint-exchange/to-configure-api-settings
Thank you,
---------------------------------------------------

https://www.mulesoft.org/jira/browse/AP-3306 -- Custom Policies GUI