= Policy Reference

Prerequisites for adding, removing, and applying policies are:

* Roles: Organization Administrators or API Versions Owner
* A configured implementation URL
* On a private server, policies need to be downloaded to the Mule Runtime /policies directory.
+
Each runtime is configured with the client id and client secret for the Anypoint Platform account.

= Applying and Removing Policies

In the list of out-of-the-box policies and any custom policies that appears when you attempt to apply a policy, an unavailable Apply indicates one of the following conditions:

* Another applied policy fulfills the requirement.

* Another policy is required before applying this policy.

== Ordering Policies

You can set the order of execution of policies. Custom policies that don’t have an order configured are executed after out-of-the-box policies.

Logs show the order of policies:

----

INFO  2015-09-28 15:37:54,214 [[leagues-rest].httpListenerConfig.worker.01] org.mule.api.processor.LoggerMessageProcessor: POLICY A
INFO  2015-09-28 15:37:54,214 [[leagues-rest].httpListenerConfig.worker.01] org.mule.api.processor.LoggerMessageProcessor: POLICY B
----

== Policy-Related Notifications

When an Organization Owner defines the order of policy enforcement, conflicts can occur if existing API Owners have set policies on their APIs. The API Manager notifies both parties in the event of a conflict. An API Owner needs to update policies and resolve any conflicts.


== See Also

* link:/api-manager/tutorial-manage-an-api[To Apply Policies and SLA Tiers]
* link:/api-manager/resource-level-policies-about[About Resource Level Policies]
* link:/api-manager/disable-edit-remove-task[To Disable, Edit, or Remove a Policy]
* link:/api-manager/reorder-policies-task[To Re-order Policies]