= Anypoint Exchange
:keywords: exchange, exchange2, anypoint exchange

Anypoint Exchange provides a unified user interface and API for discovery and consumption of connectivity and API assets.   

* Works directly with Anypoint Platform and Anypoint Studio
to provide a single point of access for information and assets.
* Provides a central hub for discovering your organization’s APIs, best practices, templates, examples, and information.

Anypoint Exchange provides listings of public and organizational APIs, connectors, examples, templates, and custom pages such as blogs videos.

MuleSoft certifies its public content, and reviews and approves partner connectors. 

All private content is internal to an organization and not visible outside their organization. Customers are responsible for any private content they publish within their Exchange.

== To Use Anypoint Exchange

* Access content: Click an asset card, search for an asset, or filter the cards by clicking All Types.
+
The types of content are:
+
** Connector - Anypoint Studio is preloaded with a large set of connectors, but the full listing can be found in Exchange. To install connectors, open Exchange from within Anypoint Studio.
** Module - 
** Template - Packaged integration patterns that address common use cases and are built on best practices. Use case applications to which you add your information to complete a user case or solution.
** Example - Implementation projects that explain development elements within Anypoint Studio and how these can be leveraged to achieve specific API and integration objectives. Examples are applications that are ready to run and demonstrate a use case or solution.
** REST API - API descriptions. See link:http://raml.org[raml.org] for more information.
** SOAP API - API descriptions in a WSDL that helps make the adoption of the Anypoint Platform easier and faster.
** RAML Fragment - 
** Custom - Blogs/Articles/Videos and more - Links that assist with knowledge sharing, such as information on DataWeave, MEL, batch processing, MUnit, policies, and links to knowledge sharing information sources. 
+
* Rate Content: Provide feedback on each asset. 
+
See: link:/getting-started/ex2-rate[To Review an Asset in Exchange]
+
* Add New assets or maintain existing assets.
+
See: link:/getting-started/ex2-add-asset[To Add an Asset to Exchange] to start.
