= Deploying Mule Applications in Anypoint Platform

This topic provides a general overview of application deployment in Anypoint Platform and outlines the multiple ways you can deploy a Mule application.

After designing a Mule application, you need a way of testing the application, and ultimately, making it accessible to user. Anypoint Platform provides multiple tools for designing APIs and Mule applications. After desiging an API or Mule application, you need a way to test it, and ultimately, make it accessible to users in a production environment.  This is accomplished by deploying the application from your working environment to a Mule runtime. The Mule runtime you deploy to can be within testing or production environment. Deployment refers to the process of moving  from your development environment to a Mule runtime so that they are available for testing or production.

Anypoint Platform provides multiple methods for deploying Mule applications. The exact method you use to deploy depends partially on whether you are deploying to a sandbox or production environment and on whether you need to automate the deployment process.

The following sections describe different ways of deploying a Mule application within Anypoint Platform.

== Design Center

Enables you to deploy directly to CloudHub. You can specify the environment where you want to deploy. In a normal workflow, this would be a sandbox environment used for testing your application. See link:/design-center/v/1.0/promote-app-prod-env-design-center[To Deploy an App (Design Center)] for more information.

== Anypoint Studio

Anypoint Studio provides a built-in Mule runtime environment. Deploy your Mule application to this environment for local testing during development.

Additionally, you can link:/anypoint-studio/v/7.1/deploy-mule-application-task[Deploy a Mule Application to CloudHub] from Anypoint Studio. 

== Runtime Manager

CloudHub, Hybrid, PCE, PCF

== CloudHub API

== Anypoint Platform CLI

== Mule Maven Plugin

== Standalone Mule

https://docs.mulesoft.com/mule-user-guide/v/3.9/deploying-to-multiple-environments

[%header%autowidth.spread]
|===
| Component | Description | Links
| Studio |  | link:/anypoint-studio/v/7.1/deploy-mule-application-task[To Deploy a Mule Application to CloudHub (Anypoint Studio)]
| Design Center | Enables you to deploy directly to CloudHub. You can specify the environment where you want to deploy. In general, this would be a sandbox environment used for testing your application.
| Runtime Manager | 
| CloudHub API | 
| Anypoint Platform CLI | CloudHub, PCE, PCF
| Mule Maven Plugin | 
| Standalone Mule | https://docs.mulesoft.com/mule-user-guide/v/3.9/deploying-to-multiple-environments
|===


== See Also

