= Deploying Mule Applications in Anypoint Platform

This topic provides a general overview of application deployment in Anypoint Platform and outlines different ways you can deploy a Mule application.

After designing a Mule application, you need a way of testing the application, and ultimately, making it accessible to users in a productione environment. Anypoint Platform provides multiple tools for deploying Mule applications.

Deployment refers to the process of moving an application from your development environment to a Mule runtime. The Mule runtime you are deploying to is called the deployment target. The deployment target can be a testing or production environment. It can also be a Mule runtime in a Mulesoft-hosted or customer-hosted envrionment. 

The following table describes different deployment targets that Anypoint Platform supports:

[%header%autowidth.spread]
|===
| Deployment Target | Description
| CloudHub  | 
| Hybrid | 
| Customer-manage Mule runtimes | 
| PCF |
|===

Anypoint Platform provides multiple ways of deploying Mule applications. The exact method you use depends on the following:

* The location of your deployment target.
* If you are deploying to a sandbox or production environment
* If you need to automate the deployment process.

The following sections describe different ways of deploying a Mule application within Anypoint Platform.

== Design Center

Designer is a web-based application that enables you to create Mule applications. Design Center
enables you to deploy directly to CloudHub. You can specify the environment where you want to deploy. In a normal application development workflow, this would be a sandbox environment used for testing your application. 

See link:/design-center/v/1.0/promote-app-prod-env-design-center[To Deploy an App (Design Center)] for more information.

== Anypoint Studio

Anypoint Studio provides a built-in Mule runtime environment. Deploy your Mule application to this environment for local testing during development.

Additionally, you can link:/anypoint-studio/v/7.1/deploy-mule-application-task[Deploy a Mule Application to CloudHub] directly from Anypoint Studio. 

== Runtime Manager

Runtime Manager is a component of Anypoint Platform that enables you to deploy and manage Mule applications. Runtime Manager is primarily used by system administrators who may need to deploy a Mule application to different deployment target.

Runtime Manager enables you to deploy to the following deployment targets:

* CloudHub
* Hybrid 
* Customer-manage Mule runtimes
* PCF

== CloudHub API

== Anypoint Platform CLI

== Mule Maven Plugin

== Standalone Mule

https://docs.mulesoft.com/mule-user-guide/v/3.9/deploying-to-multiple-environments

[%header%autowidth.spread]
|===
| Component | Description | Links
| Studio |  | link:/anypoint-studio/v/7.1/deploy-mule-application-task[To Deploy a Mule Application to CloudHub (Anypoint Studio)]
| Design Center | Enables you to deploy directly to CloudHub. You can specify the environment where you want to deploy. In general, this would be a sandbox environment used for testing your application.
| Runtime Manager | 
| CloudHub API | 
| Anypoint Platform CLI | CloudHub, PCE, PCF
| Mule Maven Plugin | 
| Standalone Mule | https://docs.mulesoft.com/mule-user-guide/v/3.9/deploying-to-multiple-environments
|===


== See Also

