= Getting Started with Anypoint Platform
:keywords: getting started, how to, platform, mule, api

Welcome to the Getting Started section to help you become familiar with basic aspects of API and application creation and steps to get them running in production. These tutorials help you toward integration of your digital assets through APIs and Mule applications that work with link:/mule-user-guide/v/3.8/key-concepts[Mule Runtime], MuleSoft's flagship integration platform.

== How to Design and Manage APIs

. Find out link:/getting-started/design-an-api[How to Design an API] with the Anypoint Platform tools.
. After designing the API, learn link:/getting-started/implement-and-test[How to Implement and Test an API].
. To bring your API to your organization or a larger audience, see link:/getting-started/sync-api-apisync[How to Sync an API to the Platform].

[NOTE]
Go to the link:/api-manager/[API Manager] and link:api-manager/designing-your-api[API Designer] product documentation to learn to design and manage new or legacy APIs. Publish interactive documentation about your APIs on an link:/api-manager/tutorial-create-an-api-portal[API Portal].

== How to Develop Mule Applications

The documentation for Mule application development requires some familiarity with link:/anypoint-studio/v/6/index[Anypoint Studio]. Make sure you have it installed and get acquainted with it using the link:/anypoint-studio/v/6/basic-studio-tutorial[Basic Studio Tutorial].

[NOTE]
Install the link:/anypoint-studio/v/6/setting-up-your-development-environment[Studio hardware and software requirements] where you design your Mule apps. If you have or need an idea for the integration you want, browse the connector, API and template resources in link:/getting-started/anypoint-exchange[Anypoint Exchange]. From the browser or within Anypoint Studio, you can find all MuleSoft and partner-supported link:/mule-user-guide/v/3.8/anypoint-connectors[connectors], which work out of the box to help you hook into SaaS applications like ServiceNow and Salesforce, or generic data structures like databases, files and object stores. Use Exchange to install or retrieve artifacts to meet your integration objectives.

. link:/getting-started/build-a-hello-world-application[Build and Deploy a Hello World Mule Application] 
. Try out the link:/getting-started/anypoint-connector[Anypoint Connector Tutorial] where you find out Mule applications can do anything you already do with SaaS apps with greater efficiency. The tutorial uses the Twitter service as an example, but you can plug in another connector of your choice.
. In a Mule application, it is important to be able to route messages to different places depending on their contents. See an example in the link:/getting-started/content-based-routing-tutorial[Content-Based Routing Tutorial]
. link:/mule-user-guide/v/3.8/dataweave[DataWeave] - Weave data transformations into your Mule applications to quickly transform and map Mule message payloads to other data structures.


== Deploy and Manage Mule Applications

. Use the legacy deployment tool to deploy an app locally, following this /mule-management-console/v/3.8/mmc-walkthrough[Mule Management Console (MMC) Walkthrough] or do the same using Runtime Manager to link:/runtime-manager/deploying-to-your-own-servers[Deploy to Your Own Servers]. Runtime Manager is a more flexible tool that allows link:/runtime-manager/managing-servers[hybrid] management.
. Deploy apps to the MuleSoft cloud using the Anypoint Platform command line interface in the link:/getting-started/build-a-hello-world-application[Build and Deploy a Hello World Mule Application Tutorial].
. See how the cloud deployment can be achieved in the CloudHub UI in the link:/runtime-manager/hello-world-on-cloudhub[Hello World on CloudHub Tutorial].


Dive into more strategies for controlling how your Mule applications are run and managed starting from the link:/mule-user-guide/v/3.8/installing[Installing and Deploying] documentation for Mule runtime.

== Developer Tools

* link:/getting-started/anypoint-exchange[Anypoint Exchange] - access templates, connectors, API resources or publish your own.

* link:/mule-user-guide/v/3.8/[Mule Runtime]
* link:/anypoint-studio/v/6/index[Anypoint Studio]
* link:/api-manager/[API Manager]
* link:/runtime-manager/cloudhub[CloudHub] and more.

Access link:/release-notes/[Release Notes] for the release history of any MuleSoft product.


== Resources

* Access link:/release-notes/[Release Notes] for the release history of any MuleSoft product.
* link:https://anypoint.mulesoft.com/login/#/signup[Sign up for the Anypoint Platform] or link:https://anypoint.mulesoft.com/login/#/signin[sign in to your account]
