= Command Line Interface Shell.
:keywords: cloudhub, cloud, cli

CloudHub provides an interface to display and interact with your applications through a command line that supports both interactive shell and standard CLI modes.

== Assumptions

This document assumes that you are familiar with the link:/cloudhub/cloudhub-at-a-glance[basic concepts of Cloudhub] and that you are able to link:/cloudhub/managing-cloudhub-applications[manage your own applications on CloudHub].

== Installation

[IMPORTANT]
First you need to make sure you have the node.js runtime environment installed in your machine. Along with it, you'll need to use node's default package manager (npm) to be able to install Cloudhub-CLI.
Following the steps in the link:https://docs.npmjs.com/getting-started/installing-node[node documentation] will help you get both resources.

You can install Cloudhub-CLI using node's default package manager by typing in your console

[source,bash]
----
$ npm install -g cloudhub-cli
----

== Usage
Every instance of Cloudhub-CLI will take any of the following parameters:

[width="100a",cols="50a,50a",options="header"]
|===
|Parameter |Description
|username | Your Anypoint Platform username. You can also `export CLOUDHUB_USERNAME=<name>` +
[red]*required*
|password | Your Anypoint Platform password. You can also `export CLOUDHUB_PASSWORD=<pwd>` +
[red]*required*
|organization| Your organization within Anypoint Platform. You can also `export CLOUDHUB_ORG=<name>`
|environment| Your Cloudhub environment.  You can also `export CLOUDHUB_ENV=<name>`
|host| Your database host name.  You can also `export CLOUDHUB_HOST=<name>`
|===

[IMPORTANT]
--
A few considerations to keep in mind while using Cloudhub-CLI:

. As instructed above, the username and password parameters are required. If you don't pass them, Cloudhub-CLI will not run. +
. If you don't set an environment, you will be automatically sent to `production`. +
. Your session with Cloudhub won't expire if you are accessing through Cloudhub-CLI.
--

Once you have your parameters in order, you can pass commands. +
A list of available commands is below:
[width="100a",cols="50a,50a",options="header"]
|===
|Command |Description
|<<account>> | Show account details
|<<business-groups>> | Lists business groups
|<<apps>> | Lists all applications in the environment
|<<show>> | Show application details
|<<json>> | Show raw application JSON response
|<<stop>> | Stop a running application
|<<start>> | Start an application
|<<restart>> | Restart a running application
|<<delete>> | Delete an application
|<<deploy>> | Deploy a new application
|<<update>> | Update an existing application, optionally updating the zip file
|<<tail>> | Tail application logs
|<<environments>> | Lists environments
|<<regions>> | Lists all supported regions
|<<runtimes>> | Lists all supported runtimes
|<<token>> | Show API access token
|<<download-logs>> | Download application logs to specified directory
|<<create environment>> | Create new environment
|<<delete environment>> | Delete existing environment
|<<exit>> | Exits Cloudhub-CLI
|===

A Cloudhub-CLI call should then have the following form:
[source,bash]
----
$ cloudhub-cli [params] [command]
----

If you choose not to pass a command, Cloudhub-CLI will run in *interactive mode*.
In order to access this, your call should look like this:

[source,bash]
----
$ cloudhub-cli --username=yourAnypointUsername --password=yourAnypointPassword
----

== List of commands

[TIP]
Use the `--help` option with a command to see what options are available.

=== account
[source,bash]
----
$ account [options]
----
This command simply returns the information for your account. This includes organization and environment to which you are connected, along with your username, Full name, email and date of creation of your account. +
This command does not take any options, except for the default `--help`.

=== business-groups
[source,bash]
----
$ business-groups [options]
----
This command displays all link:/anypoint-platform-administration/manage-your-organization-and-business-groups[business-groups]. It will return the name of the business group, the type ('Master' or 'Business unit') and the Id.
This command does not take any options, except for the default `--help`.

=== apps
[source,bash]
----
$ apps [options]
----

This command lists all applications available in your Cloudhub. It will return your application name, its status, the amount of vCores assigned and the last time it was updated.
This command does not take any options, except for the default `--help`.

=== show
[source,bash]
----
$ show [options] <name>
----

This command displays information on the application you pass in <name>. +
It will return data such as the application's domain, its status, last time it was updated, the Runtime version, the .zip file name, the region, monitoring and Workers; as well as 'TRUE' or 'FALSE' information for persistent queues and static IPs enablement.
This command does not take any options, except for the default `--help`.

=== json
[source,bash]
----
$ json [options] <name>
----
This command returns the raw JSON response of the application you specify in <name>.
This command does not take any options, except for the default `--help`.

=== stop
[source,bash]
----
$ stop [options] <name>
----
This command stops the running application you specify in <name>
This command does not take any options, except for the default `--help`.

=== start
[source,bash]
----
$ start [options] <name>
----
This command starts the running application you specify in <name>
This command does not take any options, except for the default `--help`.


=== restart
[source,bash]
----
$ restart [options] <name>
----
This command restarts the running application you specify in <name>
This command does not take any options, except for the default `--help`.


=== delete
[source,bash]
----
$ delete [options] <name>
----
This command deletes the running application you specify in <name>

[WARNING]
This command won't prompt twice before deleting. If you send a delete instruction, it will automatically delete without asking for confirmation.

This command does not take any options, except for the default `--help`.

=== deploy
[source,bash]
----
$ deploy [options] <name> <zipfile>
----

This command deploys the Mule deployable archive .zip file that you specify in <zipfile> using the name you set in <name>.
You will have to provide the absolute or relative path to the deployable zip file in your local hard drive and the name you give to your application has to be unique.

The options this command can take are:
[width="100a",cols="50a,50a",options="header"]
|===
|Option |Description
|--runtime [runtime]                                     | Name of the runtime
|--workers [workers]                                     | Number of workers. (This value is '1' by default)
|--workerSize [workerSize]                               | Size of the workers in vCores. (This value is '1' by default)
|--region [region]                                       | Name of the region to deploy to.
|--property [property]                                   | Set a property (name:value). Can be specified multiple times
|--propertiesFile [propertiesFile]                       | Overwrite all properties with values from this file. The file format is 1 or more lines in name=value format. Set the absolute path of the properties file in your local hard drive.
|--persistentQueues [persistentQueues]                   | Enable or disable persistent queues. Can take 'true' or 'false' values. (This value is 'false' by default)
|--persistentQueuesEncrypted [persistentQueuesEncrypted] | Enable or disable persistent queue encryption. Can take 'true' or 'false' values. (This value is 'false' by default)
|--staticIPsEnabled [staticIPsEnabled]                   | Enable or disable static IPs. Can take 'Enable' or 'Disabled' values. (This value is 'Disabled' by default)
|--autoRestart [autoRestart]                             | Automatically restart app when not responding. Can take 'true' or 'false' values. (This value is 'false' by default)
|--help                                                  | output usage information
|===

Note that from Cloudhub-CLI you won't be able to allocate static IPs. You can simply enable and disable them.

[IMPORTANT]
If you deploy without using any options, your application will deploy using all your default values.

=== update
[source,bash]
----
$ update [options] <name> [zipfile]
----
This command updates the settings of an existing application. Optionally you can update it by uploading a new .zip file.
This command can take all the same options as the *deploy* option.

=== tail
[source,bash]
----
$ tail [options] <name>
----
This command tails application logs.
This command does not take any options, except for the default `--help`.

=== environments
[source,bash]
----
$ environments [options]
----
This command lists all your Environments in your Anypoint Platform. It will return your environment name, its Id and whether it's sandboxed or not.
This command does not take any options, except for the default `--help`.

=== regions
[source,bash]
----
$ regions [options]
----
This command lists all supported regions.
This command does not take any options, except for the default `--help`.

=== runtimes
[source,bash]
----
$ runtimes [options]
----
This command lists all supported runtimes.
This command does not take any options, except for the default `--help`.

=== token
[source,bash]
----
$ token [options]
----
This command lists all your API access tokens.
This command does not take any options, except for the default `--help`.

=== download-logs
[source,bash]
----
$ download-logs <name> <directory>
----
This command downloads logs the for application specified in <name> to the specified directory. +
Keep in mind that contrarily to what you see in the UI, the logs you download from the CLI won't separate system logs from worker logs.


=== create environment [options]
[source,bash]
----
$ create environment [options] <name>
----
Creates an environment with the specified name.
Along with the default '--help' option, you can also use `--sandbox` to create this environment as a sandbox.


=== delete environment
[source,bash]
----
$ delete environment [options] <name>
----
This command deletes the specified environment.
This command does not take any options, except for the default `--help`.

=== exit
[source,bash]
----
$ exit [options]
----
This command exits Cloudhub-CLI.
Additionally you can use the -f or --force options to force quit without confirmation.
