= To Export Analytic Data to ELK

*_The feature described in this topic is currently in BETA_*

== Requirements

To export external analytics data to ELK, you must have the following software:

* Mule Runtime, version 3.8.4 or greater
* Mule Runtime Manager Agent, version 1.7.0 or greater
* ElasticSearch, version 5.6.1
* Filebeat, version 5.6.1
* Kibana, version 5.6.1

== Prerequisites

* Ensure that you have intalled and configured your Mule runtime instances.
* Ensure that you have registered these instances with Runtime Manager.

== Enable Event Tracking

To export business and event tracking data, you must enable event tracking in runtime manager.

. From Anypoint Platform, click Runtime Manager.
. Click Servers.
. Click the row containing the server wher you want to configure ELK.
. Click Manager Server, then click the Plugins tab.
. Under Event Tracking, select Business Events from the Levels drop down.
. Click the switch to Enable event tracking on ELK. 
+
Runtime Manager displays the ELK Integration dialog.

. Configure the log files as necessary.
. Click Apply

== Enable API Analytics

To export API analytics, you must enable API analytics in Runtime Manager.

. From Anypoint Platform, click Runtime Manager.
. Click Servers.
. Click the row containing the server wher you want to configure ELK.
. Click the switch to enable API analytics, the click the switch next to ELK.
. Configure the log files as necessary.
. Click Apply


== Edit the wrapper.conf Properties File

In your Mule runtime installation, edit the following the `conf/wrapper.conf` file.

. Set the `analytics_enabled` property to `true`.
+
----
wrapper.java.additional.<n>=-Danypoint.platform.analytics_enabled=true
----

. Remove the URI value from the `analytics_base_uri` property.
+
----
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=
----

. Set the `on_prem` property to `true`. 
+
----
wrapper.java.additional.<n>=-Danypoint.platform.on_prem=true
----

== Install and Configure the Filebeat Agent

You must install the Filebeat agent on each server where you have Mule runtime instances. 

. Download and install Filebeat for your operating system.
. Ensure that Filebeat is running as a service on your server.
+
You must configure Filebeat to start automatically during system restart. For example, if you are using an RPM package manager:
+
----
sudo chkconfig --add filebeat
----

== Configure the Mule Filebeat Module

You must install the Filebeat module on each server where you have Mule runtime instances. 

. Ensure that you have configured the `MULE_HOME` environment variable.
. Download and expand the Filebeat Module archive from the following URL:
+
----
URL TO BE ADDED
----

. Add the absolute paths of each log file to the `filebeat.yml` file:
+
* Add the event log paths to the `var.paths` variable of `business_events` as shown in the following example:
+
----
business_events:
    enabled: true
    ...
    var.paths: 
      - /var/mule/logs/instance1_events.log
      - /var/mule/logs/instance2_events.log
    ...
----
+
* Add the API analytics log paths to the `var.paths` variable of `api_analytics` as shown in the following example:
+
----
api_analytics:
  enabled: true
  	...
    var.paths:
      -  /var/mule/logs/instance1_api-analytics-elk.log
      -  /var/mule/logs/instance2_api-analytics-elk.log
----

. Add your Elastic Search host to the `hosts` property:
+
----
output.elasticsearch:
	...
	hosts: ["http://your_elastic_installation:9200"]
	...
----

. Update the Filebeat configuration
+
* If you installed Filebeat using a Linux package manager, run the following script:
+
----
 setup_mule_module.sh
----
+
* If you installed Filebeat using another method, you must copy `filebeat.template.mule.json` and `filebeat.yml` to the root installation folder of Filebeat.

. Start Filebeat:
+
For example, if you are using an RPM package manager:
----
sudo /etc/init.d/filebeat start
----
+
Or, if you are using a Debian Linux environment:
+
----
sudo service filebeat start
----

== Import Kibana Charts

== Install the Elastic Search Geoip and Agent Modules

== See Also

 