= To Install Anypoint Platform Private Cloud Using Automated Installer

This topic describes how to install Anypoint Platform Private Cloud Edition using an automated installer. The automated installer enables you to specify all required parameters on the command line.

== Prerequisites

To run the automated installer, you must have root access on all of the servers in your environment. 

Before running the installer, you must gather the following:

* The IP address of each server in your installation.
* The path to the Docker location on each server
* Your Anypoint Platform Private Cloud Edition License file

== Running the Installer

1. Copy the application archive to each server node in your cluster.
1. Run the following command on one of the nodes in your cluster:
+
----
sudo ./gravity install --advertise-addr=<installer_IP> --token=<secret token> --cluster=<cluster name> --cloud-provider=generic --flavor=<flavor name> --license="$(cat license.pem)" --docker-device=<device> --role=<role>
----
+
Using the following values:

[%header,cols="2*a"]
|===
|installer_IP | Specifies the IP address used to access the node.
|secret_token | Specifies a secure token used for intra-server communication during the installation.
|cluster_name | Defines the name of your cluster.
|flavor | Specifies the number of nodes in your cluster.
|device | Specifies the the path to the Docker device on each server.
|role | Specifies the role of the server where you are running the command. Valid values are: `master` and `general_node`.
|===

1. While the `./gravity install` command is running, run the following command:
+
**Note:** Use the same values you provided in the previous command.
+
----
sudo ./gravity join <installer IP> --advertise-addr=<node IP> --token=<secret token> --docker-device=<device> --role=<role>
----
+
This command causes each of the nodes to join the cluster created using the `./gravity install` command.

1. After the `./gravity install` and `./gravity join` commands have completed, run the following:
+
----
sudo gravity enter
gravity user create --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure --email=username@mulesoft.com --password=Password1 --type=admin
----
+
This command creates the default admin user and password. You can use these credentials to access Ops Center.

