= To Install Anypoint Platform Private Cloud Using the Automated Installer

This topic describes how to install Anypoint Platform Private Cloud Edition using an automated installer. The automated installer enables you to specify all required parameters on the command line.

== Prerequisites

To run the automated installer, ensure that you have root access on all of the servers in your environment. 

Before running the installer, you will need the following:

* The IP address of each server in your installation.
* The path to the Docker installation on each server
* Your Anypoint Platform Private Cloud Edition License file

== About the Installation Scripts

The automated installation consists of two scripts:

* `gravity install`: begins the installation and handles intra-server communication during the install. This script also installs the platform on the server. 
* `gravity join`: installs the platform on each additional server.

The scripts you run one each ndoe and the values of the `role` parameter depend on the type of installation you are performing:

[%header,cols="4*a"]
|===
|If you are installing a ... |Run ... |Value of the `flavor` parameter |Value of the `role` parameter
|1-node configuration |`gravity install` on 1 node |`flavor=one` |`role=general`
|3-node configuration |`gravity install` on 1 node |`flavor=three` |`role=general`
| |`gravity join` on the 2 remaining nodes |N/A |`role=general`
|6-node configuration |`gravity install` on 1 node |`flavor=six` |`role=data_node`
| |`gravity join` on 2 nodes |N/A |`role=data_node`
| |`gravity join` on the 3 remaining noodes |N/A |`role=app_node`
|===


== Running the Automated Installation

1. Copy the application archive to each server node in your cluster.
1. Run the following command on one of the nodes in your cluster:
+
----
sudo ./gravity install --advertise-addr=<installer_IP> --token=<secret token> --cluster=<cluster name> --cloud-provider=generic --flavor=<flavor name> --license="$(cat license.pem)" --docker-device=<device> --role=<role>
----
+
Using the following values:
+
[%header,cols="2*a"]
|===
|installer_IP | Specifies the IP address used to access the node.
|secret_token | Specifies a secure token used for intra-server communication during the installation.
|cluster_name | Defines the name of your cluster.
|flavor | Specifies the number of nodes in your cluster. Valid values are: `one`, `three`, and `six`.
|device | Specifies the the path to the Docker device on each server.
|role | Specifies the role of the server where you are running the command. Valid values are: `general_node`, `data_node` and `app_node`.
|===

1. While the `./gravity install` command is running, run the following command:
+
**Note:** Use the same values you provided in the previous command.
+
----
sudo ./gravity join <installer_IP> --advertise-addr=<node_IP> --token=<secret_token> --docker-device=<device> --role=<role>
----
+
This command causes each of the nodes to join the cluster created using the `./gravity install` command.
+
Wait for the `./gravity install` and `./gravity join` commands to complete. This may take some time.

1. Enter the gravity shell:
+
----
sudo gravity enter
----

1. Run the following command to create the Ops Center user:
+
----
gravity user create --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure --email=username@mulesoft.com --password=Password1 --type=admin
----
+
This command creates the default admin user and password. You can use these credentials to access Ops Center.

1. Create the Anypoint Platform user by running the following command in the gravity shell:
+
----
curl -X POST http://bandwagon-mulesoft.default.svc/api/complete -H "Content-Type:application/json" -d '{"organization": "Test Org", "email": "username@mulesoft.com", "name": "username", "password": "Password1", "support": false}'
----

== See Also

* link:system-requirements[About Minimum System Requirements]
* link:install-installer[To Run the Anypoint Platform Private Cloud Edition Installer]

