= XML Cryptography
:keywords: cryptography, module, sign, encrypt, xml, AES
:toc:
:toc-title:

== Encrypting

.Example: JCE configuration
[source, xml, linenums]
----
<crypto:jce-config name="symmetricConfig" keystore="secret.jks" password="mule1234" type="JCEKS">
    <crypto:jce-key-infos>
        <crypto:jce-symmetric-key-info keyId="mySymKey" alias="aes128test" password="mule1234"/>
    </crypto:jce-key-infos>
</crypto:jce-config>
----
The example above configures a keystore which contains a symmetric key that will later be used for encryption.

.Example: Using the Encrypt operation
[source, xml, linenums]
----
<crypto:xml-encrypt config-ref="symmetricConfig" keyId="mySymKey" algorithm="AES_CBC" elementPath="//song"/>
----
In this example, the XML encrypt operation is used to encrypt an specific element of the XML document.
The elementPath is an XPath expression that identifies the element to encrypt.
Depending on your needs, you can use a symmetric or asymmetric key for encrypting an XML document.

== Decrypting

.Example: JCE configuration
[source, xml, linenums]
----
<crypto:jce-config name="jceConfig" keystore="keystore.jks" password="mule1234">
    <crypto:jce-key-infos>
        <crypto:jce-symmetric-key-info keyId="mySymKey" alias="aes128test" password="mule1234"/>
        <crypto:jce-asymmetric-key-info keyId="myAsymKey" alias="test1" password="test1234"/>
    </crypto:jce-key-infos>
</crypto:jce-config>
----

.Example: Using the Decrypt operation
[source, xml, linenums]
----
<crypto:xml-decrypt config-ref="jceConfig" keyId="myAsymKey"/>
----
In this example, the XML decrypt operation is used to decrypt an XML document. The operation uses the asymmetric key
stored in the referenced Keystore.
Depending on your needs, you can use a symmetric or asymmetric key for decryption.

== Signing

.Example: JCE configuration
[source, xml, linenums]
----
<crypto:jce-config name="asymmetricConfig" keystore="keystore.jks" password="mule1234">
    <crypto:jce-key-infos>
        <crypto:jce-asymmetric-key-info keyId="myAsymKey" alias="test1" password="test1234"/>
    </crypto:jce-key-infos>
</crypto:jce-config>
----

.Example: Enveloped Signature
[source, xml, linenums]
----
<crypto:xml-sign config-ref="asymmetricConfig" keyId="myAsymKey" type="ENVELOPING" digestAlgorithm="SHA256" elementPath="/PurchaseOrder/Buyer"/>
----
The example above uses the asymmetric key to sign an XML document by creating an XML envelope and inserting the Signature inside the content that is being signed.

.Example: Detached Signature
[source, xml, linenums]
----
<crypto:xml-sign config-ref="asymmetricConfig" keyId="myAsymKey" type="DETACHED" digestAlgorithm="SHA256" elementPath="/PurchaseOrder/Buyer"/>
----
In this example, a detached XML signature is created based on an element of the XML document. Instead of being inserted in the signed content,
the detached signature is returned as a separate XML element.

== Validating a signature

.Example: JCE configuration
[source, xml, linenums]
----
<crypto:jce-config name="asymmetricConfig" keystore="keystore.jks" password="mule1234">
    <crypto:jce-key-infos>
        <crypto:jce-asymmetric-key-info keyId="myAsymKey" alias="test1" password="test1234"/>
    </crypto:jce-key-infos>
</crypto:jce-config>
----

.Example: Using the Validate operation
[source, xml, linenums]
----
<crypto:xml-validate config-ref="asymmetricConfig" keyId="myAsymKey" elementPath="/PurchaseOrder/Buyer"/>
----
In this example, the asymmetric key is used to validate the signature of the XML element specified by the elementPath XPath expression.
