= PGP Cryptography
:keywords: cryptography, module, sign, encrypt, pgp, AES
:toc:
:toc-title:

Mule can encrypt all or part of a message using Pretty Good Privacy (PGP). PGP combines data compression and data encryption to secure messages. The compression reduces the size of the payload to help reduce the transmission time later on your application.

Due to its increased complexity, PGP encryption is a heavy-load task when compared to JCE or XML encryption, both of which are explained <<below>>.

There are two scenarios that this document addresses:

* Using another party's public key to *encrypt* an outgoing message in a Mule application.
* Using your own private key to *decrypt* an incoming message in a Mule application.

== Prerequisites

This document assumes that you are reasonably familiar with PGP encryption, as well as the concepts of public and private keys and asymmetric cryptography.

== Encrypting

When using PGP encryption, the sender of the message must encrypt its content using the receiver's public key. Thus, whenever you want to encrypt messages
in your Mule application using someone else's public key, you must add the public key to your key ring, that you will then configure in your PGP configuration.
When adding a new PGP configuration to your Mule application, you will be asked to provide your key ring file where the encryption module will access to get the
public key and encrypt the message.

1. Use a tool such as GPG Suite to import the other party's public key. Refer to section below for more details about using GPG to facilitate implementation of
PGP cryptography in Mule.
2. Using the same tool, export the public key, selecting binary as the output format. This produces a key ring file with a *.gpg* extension.
3. Ensure that the key ring (*.gpg*) file is stored in a place that the Mule application will be able to access in runtime.

.Example: PGP Configuration
[source, xml, linenums]
----
<crypto:pgp-config name="encrypt-conf" publicKeyring="pgp/pubring.gpg">
    <crypto:pgp-key-infos>
        <crypto:pgp-asymmetric-key-info keyId="myself" fingerprint="DE3F10F1B6B7F221"/>
    </crypto:pgp-key-infos>
</crypto:pgp-config>
----

.Example: Using the Encrypt Operation
[source, xml, linenums]
----
<crypto:pgp-encrypt config-ref="encrypt-conf" keyId="myself"/>
----

The example above will return an ASCII-armored encrypted payload, which is suitable to be sent over plain-text channels.
Similarly, if you want to return a binary output instead, you can use the pgp-encrypt-binary operation:

----
<crypto:pgp-encrypt-binary config-ref="pgpConfig" keyId="recipient"/>
----
Producing a binary output is faster when comparing to ASCII-armored. On the other hand, the output is not standard and may not be ideal to be sent over to other systems for decryption.

If you later need to send such payload over to another system, you can transform it to ASCII-armored:

----
<crypto:pgp-binary-to-armored/>
----
The operation above has a single input parameter which is the message payload to transform.

== Decrypting

When using PGP decryption, the receiver of the message must use its private key to decrypt the contents of a message that was encrypted using a public key.
Therefore, the receiver must distribute its public key to those who will use it to send encrypted messages.

.Example: PGP Configuration
[source, xml, linenums]
----
<crypto:pgp-config name="decrypt-conf" privateKeyring="pgp/secring.gpg">
    <crypto:pgp-key-infos>
        <crypto:pgp-asymmetric-key-info keyId="myself" fingerprint="DE3F10F1B6B7F221" passphrase="mule1234"/>
    </crypto:pgp-key-infos>
</crypto:pgp-config>
----
In the example above, notice that you need to provide at least three parameters to be able to use the private key ring in the decrypt operation:

* Key ID: the internal ID that will allow you to reference this key from an operation.
* Key Fingerprint: the last 16 characters of your key fingerprint, which can be obtained from your external GPG tool (such as GPG Keychain).
* Passphrase: The passphrase of the private key.

.Example: Using the Decrypt Operation
[source, xml, linenums]
----
<crypto:pgp-decrypt config-ref="decrypt-conf"/>
----

== Signing

.Example: Using the Sign Operation
[source, xml, linenums]
----
<crypto:pgp-sign config-ref="sign-conf" keyId="myself"/>
----

== Validating a signature

.Example: Using the Validate Operation
[source, xml, linenums]
----
<crypto:pgp-validate config-ref="validate-conf" value="#[payload]" expected="#[vars.expected]"/>
----
