= JCE Cryptography

The JCE strategy allows you to use cryptography capabilities in two ways:

* PBE (Password based encryption): encrypt/sign content by providing only an encryption password.
* Key based encryption: similarly to how PGP and XML encryption works, this lets you configure a symmetric or asymmetric key to perform 
encryption/signing operations.

== PBE

This method consists on applying a hash function over the provided password to generate a symmetric key that is compatible with standard 
encryption algorithms.
Since PBE only requires a password, a global configuration element is not needed for the PBE operations.

.Example: PBE encryption
[source, xml, linenums]
----
<crypto:jce-encrypt-pbe password="a-Sup3r_Secure-Passw0rd"/>
----
If no algorithm is specified, PBEWithHmacSHA256AndAES_128 will be used.

.Example: PBE decryption
[source, xml, linenums]
----
<crypto:jce-decrypt-pbe algorithm="PBEWithHmacSHA256AndAES_128" password="a-Sup3r_Secure-Passw0rd"/>
----

.Example: PBE signature
[source, xml, linenums]
----
<crypto:jce-sign-pbe password="a-Sup3r_Secure-Passw0rd"/>
----
If no algorithm is specified, PBEWithHmacSHA256 will be used.

.Example: PBE signature validation
[source, xml, linenums]
----
<crypto:jce-validate-pbe password="a-Sup3r_Secure-Passw0rd" algorithm="PBEWithHmacSHA256" expected="#[vars.expectedSignature]"/>
----
The expected parameter, defines the signature to compare against when validating a message.

== Key based encryption

=== Configuration

.Example: JCE configuration
[source, xml, linenums]
----
<crypto:jce-config name="jceConfig" keystore="jce/keys.jceks" password="123456" type="JCEKS">
    <crypto:jce-key-infos>
        <crypto:jce-symmetric-key-info keyId="aes128" alias="aes128" password="123456"/>
        <crypto:jce-symmetric-key-info keyId="blowfish" alias="blowfish" password="123456"/>
        <crypto:jce-symmetric-key-info keyId="hmacsha256" alias="hmacsha256" password="123456"/>
        <crypto:jce-asymmetric-key-info keyId="rsa" alias="myrsakey" password="123456"/>
        <crypto:jce-asymmetric-key-info keyId="dsa" alias="mydsakey" password="123456"/>
    </crypto:jce-key-infos>
</crypto:jce-config>
----
In this example, a keystore with different type of keys is defined in a JCE configuration.

=== Asymmetric

.Example: Asymmetric encryption
[source, xml, linenums]
----
<crypto:jce-encrypt config-ref="jceConfig" keyId="rsa" algorithm="RSA"/>
----

.Example: Asymmetric decryption
[source, xml, linenums]
----
<crypto:jce-decrypt config-ref="jceConfig" keyId="rsa" algorithm="RSA"/>
----

=== Symmetric

.Example: Symmetric encryption
[source, xml, linenums]
----
<crypto:jce-encrypt config-ref="jceConfig" keyId="aes128" algorithm="AES"/>
----

.Example: Symmetric decryption
[source, xml, linenums]
----
<crypto:jce-decrypt config-ref="jceConfig" keyId="aes128" algorithm="AES"/>
----

=== Signature

.Example: Signing a message
[source, xml, linenums]
----
<crypto:jce-sign config-ref="jceConfig" keyId="dsa" algorithm="SHA256withDSA"/>
----

.Example: Validating a signature
[source, xml, linenums]
----
<crypto:jce-validate config-ref="jceConfig" keyId="dsa" algorithm="SHA256withDSA" expected="#[vars.expectedSignature]"/>
----
The expected parameter, defines the signature to compare against when validating a message.