= About DataWeave Functions
DataWeave can define functions similarly to other programming languages like Java or JavaScript.

You define a function using the `fun` declaration in the header section. Like other programming languages, DataWeave functions allow you to refactor DataWeave expressions into reusable code blocks. In DataWeave, every code block is an expression that is immediately evaluated when it is called from the DataWeave body expression. Functions can define and use one or more arguments.

Here is a simple DataWeave function that accepts a single String argument:

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
fun toUpper(aString) = upper(aString)
---
toUpper("hello") //results in "HELLO"
----

The argument to a DataWeave function can be any DataWeave expression. This function produces the same result as the previous example:

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
fun toUpper(aString) = upper(aString)
---
toUpper("h" ++ "el" ++ lower("LO") ) //results in "HELLO"
----

Because any DataWeave expression can be passed into a function, you might need to test the type of argument passed into a function before using the expression. The match operator can be helpful for this:

[source,DataWeave, linenums]
----
%dw 2.0
output application/json
fun toUpper(aString)
= aString match {
  case is String -> upper(aString)
  else -> null
}
---
toUpper("h" ++ "el" ++ lower("LO") ) //results in "HELLO"
----

== See Also

link:dw-functions[DataWeave Function Reference]
