= DataWeave Functions for Arrays (dw::core::Arrays)

Returns true if some element of the list matches the condition.
It stops the iterations after the first match.

[[function_countBy]]
== `countBy`

.countBy(Array<T>, (T) -> Boolean): Number

Counts the matching elements using a matchingFunction(T)

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
output application/json
---
[1, 2, 3] countBy (($ mod 2) == 0)
----

.Output
[source,json,linenums]
----
1
----

////
TODO: NOT IN STUDIO YET
== `divideBy`

.divideBy(Array<T>, Number): Array<Array<T>>

Divides an Array of items into sub arrays.
.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
output application/json
---
[1, 2, 3, 4, 5] divideBy 2
----

.Output
[source,json,linenums]
----
[
   [
     1,
     2
   ],
   [
     4,
     5
   ]
 ]
----
////

[[function_every]]
== `every`

.every(Array<T>, (T) -> Boolean): Boolean

Returns true if every element of the list matches the condition. It stops the iterations after the first negative evaluation.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
var arr0: Array<Number> = []
output application/json
---
{
  ok: [
    [1,2,3] some (($ mod 2) == 0),
    [1,2,3] some (($ mod 2) == 1),
    [1,2,3,4,5,6,7,8] some (log('should stop at 2 ==', $) == 2),
    [1,2,3] some ($ == 1),
    [1,1,1] every ($ == 1),
    [1,1,1] some ($ == 1),
    [1] every ($ == 1),
    [1] some ($ == 1),
  ],
  err: [
    [1,2,3] every ((log('should stop at 2 ==', $) mod 2) == 1),
    [1,2,3] some ($ == 100),
    [1,1,0] every ($ == 1),
    [0,1,1,0] every (log('should stop at 0 ==', $) == 1),
    [1] some ($ == 2),
    [1,2,3] every ($ == 1),
    arr0 every true,
    arr0 some true,
    arr0 some ($ is Number)
  ]
}
----

.Output
[source,json,linenums]
----
{
  "ok": [
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    true
  ],
  "err": [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false
  ]
}
----

////
TODO?
== `internalDivideBy`

.internalDivideBy(Array<T>, Number, Array<T>): Array<Array<T>>
////

////
TODO?
== `private_every`

.private_every(Array<T>, (T) -> Boolean): Boolean
////

== `some`

.some(Array<T>, (T) -> Boolean): Boolean

See <<function_every, `every`>>.

== `sumBy`

.sumBy(Array<T>, (T) -> Number): Number

Adds the values returned by the right hand side function

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
output application/json
---
sumBy([ { a: 1 }, { a: 2 }, { a: 3 } ], (item) -> item.a)
/* same as [ { a: 1 }, { a: 2 }, { a: 3 } ] sumBy $.a */
----

.Output
[source,json,linenums]
----
6
----

== See Also

link:dw-functions[DataWeave Functions]
