= Choosing Between Flows and Patterns

Because of the emphasis on ease of use, simplicity, and flexibility that guided the creation of Mule 3, a number of choices are open at the outset.

== Choosing Configuration Patterns and Flows

Take a look at link:using-mule-configuration-patterns[configuration patterns] and link:using-flows-for-service-orchestration[flows].

Mule 3 includes a number of configuration patterns designed to solve common integration problems with minimal XML. These patterns are similar to Enterprise Integration Patterns which are also widely supported in Mule but tackle bigger use cases, like creating a web service proxy. Take a moment to inspect the list of patterns.

If your project requires a more complex set of operations, you might want to consider flows, which are introduced in Mule 3.

For more information about patterns, read the link:configuration-reference[Configuration Reference].

* link:component-configuration-reference[Component Configuration Reference]
* link:endpoint-configuration-reference[Endpoint Configuration Reference]
* link:exception-strategy-configuration-reference[Exception Strategy Configuration Reference]
* link:bpm-configuration-reference[BPM Configuration Reference]
* link:filters-configuration-reference[Filters Configuration Reference]
* link:global-settings-configuration-reference[Global Settings Configuration Reference]
* link:notifications-configuration-reference[Notifications Configuration Reference]
* link:properties-configuration-reference[Properties Configuration Reference]
* link:security-manager-configuration-reference[Security Manager Configuration Reference]
* link:transactions-configuration-reference[Transactions Configuration Reference]

* link:using-flows-for-service-orchestration[Using Flows for Service Orchestration]
* link:using-mule-configuration-patterns[Using Mule Configuration Patterns]
