= About Anypoint Platform Management and Deployment Scenarios

Mulesoft supports different deployment scenarios.

== MuleSoft Cloud

In this deployment scenario, MuleSoft manages all of the application components.
	- Enables you to deploy and manage Mule applications.

MuleSoft handles all of the scalability requirements for each of the applications components, including high-availability and fail over.

One advtage of this deployment scenario is that application components are automatically upgraded as new versions are release.
This ensures that you always have access to the most currrent features of the Anypoint Platform.

== Hybrid Cloud
	- Application design and management components are available in the MuleSoft Cloud.
	- Enables automated version upgrades of these components.
	- Runtime components run in your own data center.
	- Gives you control over scaling and HA

== Anypoint Platform Private Cloud Edition
	- Anypoint Platform Private Cloud Edition
	- Anypoint Platform Private Cloud Edition is a MuleSoft product that enables you to run the Anypoint Platform in your own data center
	

== Anypoint Platform for Pivotal Cloud Foundry (PCF)

	- Anypoint Platform for Pivotal Cloud Foundry (PCF)
	- Is a MuleSoft product that enables you to deploy Mule applications to Mule Runtime engines on PCF
	- Design and management applications run in Anypoint Platform Private Cloud Edition

== Feature Comparsion

