= About Mule Applications

This topic provides general information about Mule applications and describes the Anypoint Platform components that enable you to create them.

A Mule application is a deployable, web-based application that enables you to 

Mule applications are built around one or more flows. Typically, a Mule application begins processing a message it receives at an inbound endpoint in a flow. In general, a flow performs one of the following:

* Implement all processing stages, or 
* Route the message to other flows or subflows to perform specific tasks.

To create flows within a Mule application, Anypoint Platform provides the following tools.

Mule applications are built around one or more flows. Typically, a Mule application begins processing a message it is received by an inbound endpoint in a flow. This flow can then either implement all processing stages, or route the message to other flows or subflows to perform specific tasks. Relative to the flow which triggered its execution, a flows and subflows can process messages either synchronously or asynchronously

Mule applications accept and process events as messages through several message processors. Message processors are arranged into a flow . A flow is the construct within which you link together several individual elements to handle the receipt, processing, and eventual routing of a message. the different types of elements in a flow.

[%header%autowidth.spread]
|===
| Component | Description
| Design Center | Provides a web-based editor that enables you to create a Mule application, create flows, and add connectors and components to a flow.
| Anypoint Studio | Provides an integrated IDE that enables you to build out Mule applications. Studio includes a flow editor that enables you to drag and drop components into a your application flow.
|===


== See Also:

* link:/mule-user-guide/v/3.9[Mule Runtime]
* link:/mule-user-guide/v/3.9/flows-and-subflows[Flows and Subflows]


