= About the Crowd Release

**THIS TOPIC IS NOT USED. WILL BE DELETED.**

The Crowd release of Anypoint Platform introduces additional product components and features that enhance your ability to create ...


API Design

Create and share API fragments
Accelerate API spec creation using fragments
Save APIs to Exchange with one click

API fragments are reusable segments of API specification such as security schemes, data types, and libraries. Within the new API designer, save API fragments to Anypoint Exchange with one click. Once saved into the Exchange, anyone within the organization can quickly browse and use the fragments to accelerate their API design. It’s fast and easy for them, while you get to ensure consistency in the design of APIs across your organization.

Asset Discovery and Reuse

Save and discover reusable assets in one place
Curate assets for users or groups
Rate and review assets

Once APIs and other reusable integration assets have been saved, curate the assets for individuals or sub-organizations so that each user’s Exchange contains what is relevant to them. Encourage the discovery and reuse of your assets by adding rich information, including relevant videos, links, and diagrams, and by responding to feedback and questions within the Exchange.


Rapid Innovation

Design integration flows online
Follow the guided design process
Click to consume reusable APIs

The new web-based flow designer is perfect for those who are new to integration and want a simplified tool to quickly solve their use case. It provides a guided integration experience with simple drag-and-drop data transformation capabilities, auto-population of reusable assets, and visual error identification to help new users see success quickly.

== See Also

* Design Center