= About Designing and Implementing an API

This topic provides general information about designing and implementing an API using Anypoint Platform. It also describes the platform components that enable you to work with APIs.

== Design (RAML)

Build API specifications with RESTful API Modeling Language (RAML)
Save and reuse API fragments to build the full API spec
Design according to best practices with a context-aware shelf
Validate designs before writing any code with the mocking service

[%header%autowidth.spread]
|===
| Component | Description
| Design Center | 
| Anypoint Studio | A unified graphical design environment enables you to build out APIs and Integration applications. Anypoint Studio is an Eclipse plugin that provides a drag-and-drop interface that enables you to build application flows from a collection of components.
|===

== Publish

After creating an API specification in RAML, you can publish you API to Anypoint Exchange.
Publishing your API enables both collaboration and discovery.
Collaboration enables you to work with other API designers and stake holders to further define and refine your API.
Discovery enables other members of your organization to know about and use your API.
Save your API into Anypoint Exchange for consumption in Design Center or Studio

== Implement

After your API has been finalized, Anypoint Platform also provides tools that enable you to implement your API as a working Mule application.

[%header%autowidth.spread]
|===
| Component | Description
| Design Center | 
| Anypoint Studio |
|===

== See Also

* link:/design-center/v/1.0/[Design Center]
* link:/design-center/v/1.0/design-raml-api-task[o Design a RAML API Specification]
