= About Designing and Implementing an API

**THIS TOPIC IS NOT USED. WILL BE DELETED.**

This topic provides general information about designing and implementing an API using Anypoint Platform. It also describes the Anypoint Platform tools that enable you to design an implement an API.

== Design an API

The first step in creating an API is to design an API specification. Anypoint Platform uses the RESTful API Modeling Language (RAML) to build API specifications.

[%header%autowidth.spread]
|===
| Component | Description
| Design Center | Design Center, is a web-based editor that enables you to define API specifications and fragments or create functional Mule applications. Using Design Center, you can author, simulate, and validate an API. At any stage of the API design process, you can publish your API to Exchange 2.0 to obtain feedback and collaborate with other API designers. In previous versions, APIs were created and edited using Anypoint API Manager.
| Anypoint Studio | A unified graphical design environment enables you to build out APIs and Integration applications. Anypoint Studio is an Eclipse plugin that provides a drag-and-drop interface that enables you to build application flows from a collection of components.
|===

In addition to defining a full API specifciation, you can also create API fragments. API fragments enable you to define reusable components that you can share with other API developers. Using these fragments you can create a a full API specification from reusable components.

Validate designs before writing any code with the mocking service

== Publish an API

After creating an API specification in RAML, you can publish you API to Anypoint Exchange. Publishing your API enables both collaboration and discovery. Collaboration enables you to work with other API designers and stake holders to further define and refine your API. Discovery enables other members of your organization to know about and use your API.

After publishing your API to Anypoint Exchange, you or other users of your API can open it in Design Center or Studio

== Implement an API

After your API has been finalized, Anypoint Platform also provides tools that enable you to implement your API as a working Mule application.

[%header%autowidth.spread]
|===
| Component | Description
| Design Center | Provides a web-based editor that enables you to open an API as a RAML file then add implementation details. Design Center enables you to deploy a working Mule application. Or, you can republish the Mule application to Exchange for additional collaboration.
| Anypoint Studio | 
|===

== See Also

* https://raml.org/[RAML]
* link:/design-center/v/1.0/[Design Center]
* link:/design-center/v/1.0/design-raml-api-task[Design a RAML API Specification]
* link:/anypoint-studio/v/6/basic-studio-tutorial[Basic Studio Tutorial]