= About API Life Cycle Changes in the Crowd Release

This topic describes changes to the API life cycle introduced in the The Crowd release of Anypoint Platform introduces new tools that

== API Lifecycle Release Comparison

The Crowd release of Anypoint Platform introduces changes to the API lifecycle. These changes include features and product components that enhance and improve the API lifecycle, including:

* A new web-based tool, Anypoint Design Center, that enables you to create API definitions and Mule flows.
* Enahancements to Exchange that enhace collaboration and discovery.
* Further ingtegration of Anypoint Platform tools

The following table lists each stage of the API lifecycle and compares the tools introduced in the Crowd release with those used in the previous release:

[%header%autowidth.spread]
|===
| |Design (RAML) | Publish | Implement | Deploy | Manage (Policies)
| Previous Releases | API Manager | Exchange 1.0  / API Manager | Studio  | Runtime Manager | API Manager
| Crowd Release | Design Center | Design Center / Exchange 2.0 | Design Center/ Studio | Runtime Manager | API Manager / Runtime Manager
|===

== Which Version of the API Lifecycle Can I Use?

If the following applies to you, you  have access to the new API designer:

* *New Anypoint Platform accounts created after July 29*: If you create a new trial account, you will see all the elements of the Crowd release including the API designer within Design Center.
* *Anypoint Platform accounts (Customer, trial, and partner organizations) created before
July 29 with no APIs in API Manager*: If you do not have APIs in API Manager or a subscription to API Manager and Analytics, you will have the new API designer starting Aug 6, 2017. The current API designer within API Manager will be disabled for these accounts.

If you meet the above conditions and don’t see the option to Create API Specification or Create API Fragment option in Design Center, please check to ensure that the user has the permission to be a Design Center Developer. If you still can’t see the options of Create ‘API Specification’ or Create ‘API Fragment’ after following this step, please contact MuleSoft support.

If you do not meet the above conditions, you will see API designer in Design Center during the upcoming Phase 2 of the Crowd release. Note that the new API designer will be enabled only after your APIs are migrated. Additional migration information will be available during the upcoming release.

== See Also

* https://www.mulesoft.com/platform/new-product-features[Anypoint Platform Crowd Release]