= About API Life Cycle Changes in the Crowd Release

This topic describes changes to the API life cycle introduced in the The Crowd release of Anypoint Platform. This release introduces new tools that simplify and enhance the process of creating and sharing APIs.

== API Lifecycle Release Comparison

The Crowd release of Anypoint Platform introduces changes to the API lifecycle. These changes include new features and tools that enhance and improve the API lifecycle, including:

* A new web-based tool, Anypoint Design Center, that enables you to create API definitions and Mule flows.
* Enhancements to Exchange that increase collaboration and discovery.
* Further integration of Anypoint Platform components

The following table lists each stage of the API lifecycle and compares the tools introduced in the Crowd release with those available in the previous release:

[%header%autowidth.spread]
|===
| |Design (RAML) | Publish | Implement | Deploy | Manage (Policies)
| Previous Releases | API Manager | Exchange 1.0  / API Manager | Studio  | Runtime Manager | API Manager
| Crowd Release | Design Center | Design Center / Exchange 2.0 | Design Center/ Studio | Runtime Manager | API Manager / Runtime Manager
|===

== Which Version of the API Lifecycle Should I Use?

If the following applies to your Anypoint Platform Environment, then you  have access to the new API designer:

* *New Anypoint Platform accounts created after July 29*: If you create a new trial account, you have access to all the components of the Crowd release, including the API designer within Design Center.
* *Anypoint Platform accounts (Customer, trial, and partner organizations) created before
July 29 with no APIs in API Manager*: If you do not have APIs in API Manager or a subscription to API Manager and Analytics, you have access to the new API designer in a future release. The current API designer within API Manager is disabled for these accounts.

If you meet the above conditions, but do not see the option to Create API Specification or Create API Fragment option in Design Center, ensure that the user has the permission  Design Center Developer. If you still cannot see the options Create API Specification or Create API Fragment, contact MuleSoft support.

== See Also

* https://www.mulesoft.com/platform/new-product-features[Anypoint Platform Crowd Release]