= About Changes to the API Lifecycle

This topic describes changes to the API lifecycle introduced in the Crowd release of Anypoint Platform. This release includes changes and additions to Anypoint Platform that enhance and improve the API lifecycle, including:

* A new web-based tool, Anypoint Design Center, that enables you to create API definitions and Mule flows.
* Enahancements to Exchange that enhace collaboration and discovery.
* Further ingtegration of Anypoint Platform tools

The following table lists each stage of the API lifecycle and compares the tools introduced in the Crowd release with those used in the previous release:

[%header%autowidth.spread]
|===
| |Design (RAML) | Engage | Implement | Deploy | Manage (Policies)
| Previous Release | API Manager | Exchange 1.0  / API Manager | Studio  | Runtime Manager | API Manager
| Crowd Phase 1 | Design Center | Exchange 2.0 | Design Center/ Studio | Runtime Manager | API Manager
|===

The following sections provide information about the changes introduced in each stage of the API lifecycle:

== Design (RAML)

This release introduces Design Center, a web-based RAML editor that enables you to author, simulate, and validate an API. At any stage of the API design process, you can publish your API to Exchange to obtain feedback and collaborate.

Previously, API Manage provided a RAML editor for creating and editing APIs.

== Engage

Exchange 2.0 provides additional collaboration features. After publishing an API specification from Design Center to Exchange 2.0, you can solicite feedback from contributors. Using Design Center and Exchange 2.0, you can continue the process of authoring, simulation, and validation, while collaborating and obtaining feedback.

Exchange 2.0 also provides enhanced discoverablitiy that enhances reuse by making it easier for collaborators and consumers to find your APIs.

== Implement

The Crowd release provides additional tools for implementing an API after the design stages:

* Anypoint Design Center: provides web-based editor that is targetted to contributors with diverse skill sets (line-of-business, application developers).
* Anypoint Platform Studio:  provides an IDE that is fully integrated within the new API lifecycle. You can export a project from Design enter and load it in Studio.


== Deployment

Continues to use ARM

== Manage

Continues to use API manager

== See Also

* https://mule4-docs.mulesoft.com/munit/v/2.0/munit-2-changes
* https://mule4-docs.mulesoft.com/mule-user-guide/v/4.0/mule-4-changes
* https://mule4-docs.mulesoft.com/mule-user-guide/v/4.0/dataweave2-snytax-changes
* https://mule4-docs.mulesoft.com/anypoint-exchange/ex2-migrate