= About Anypoint Platform and Mule Runtime

This topic provides general information about Anypoint Platform and Mule Runtime.

Anypoint Platform provides a set of tools that enable you to design, deploy and manage a network of applications, data, and devices based on API-led connectivity. Mule runtime provides a the run-time environment where you can deploy integration applications and expose APIs.

== The Application Network

The application landscape of a modern IT infrastructure is a collection of disparate applications and data sources. An organization's infrastructure can include multiple comibnation of SaaS aplications, databases, CRM systems, and legacy systems. Designing an application that can connect to these disparate systems requires you to work with a variety of protocols, credentials, data formats, etc.

<image - spaghetti graphic>

This often results in applications and data that are siloed and difficult to integrate. Also, when one component is down, this can cause performance bottlenecks and disruptions.

To solve this problem, Anypoint Platform and Mule runtime provide an application network that seamlessly connects applications, data and devices through a common set of protocols and greatly simplifies the way those applications data and devices can talk to each other.

<image - grid graphic>

The application network provides a seamless network of applications, data, and devices, that can run in the cloud or in your own IT infrastructure.

== API-driven Application Development

To facilitate integration and connectivity between applications within the application network, Anypoint Platform supports and promotes an API-driven application development model. 

* Mention RAML

== Anypoint Platform

To implement an application network and facilitate API-driven application development, Anypoint Platform provides tools and frameworks that enable you to design, build, deploy, and manage applications. These tools are grouped in these categories:

* Anypoint Design Center:
* Anypoint Management Center:
* Anypoint Exchange:


== Mule Runtime

After you have designed and implemented your application or API, you can deploy it to the Mule runtime. The Mule runtime runs cloud applications and enables you to apply policies. The Mule runtime is composed of the Mule runtime engine and supporting services.

Anypoint Platform supports deploying 

The mule runtime engine is a Java-base enterprise service bus (ESB).
Provides the backbone of the application network.

CloudHub

=== Mule Applications

=== Connectors

== See Also

* link:about-building-managing-sharing[About Anypoint Platform Design and Management Centers]
* link:about-running-mule-apps[About Running Mule Applications]
* link:about-deployment[About Anypoint Platform Management and Deployment Scenarios]