= About Managing API Proxies and Policies

This topic describes how to manage an API in Anypoint Platform. After defining and deploying an API, you can control how users access it by configuring an API proxy and policies that define who has access to the API.

[%header%autowidth.spread]
|===
| Application | Description
| API Manager | A web-based application that enables you to design, build, manage, and publish APIs.
| Anypoint Runtime Manager | A web-based application that enables you to deploy and manage Mule applications to a Mule runtime engine. Anypoint Runtime Manager provides a unified view of your applications, servers and APIs
|===

== API Proxies

API proxies enable you to specify how users connect to and use a deployed API. Proxies act as intermediaries between your API consumers and the backend services your API connects to. This helps to ensure that changes to backend services do not affect how an API is used. API proxies provide an additional layer of security by shielding access to backend services and IP addresses.

Using API Manager, you can deploy a proxy to an API running on Mulesoft's CloudHub. To deploy a proxy to an API on a user-hosted Mule runtime, use Anypoint Runtime Manager.

== API Policies

API policies enable you to control who has access to a deployed API by applying filters to incoming network traffic. API policies filters generally control authentication, access, allotted consumption, and service level access (SLA).

Anypoint Platform provides several pre-defined policies. You can also create your own custom policies as required. Using API Manager, you can create and deploy policies for APIs deployed to CloudHub or to a user-hosted Mule runtime. 

== Service Level Access (SLA)

API Manager enables you to define an SLA for a deployed API. A Service Level Access (SLA) tier is a category of user access that you can specify for an API. The tier definition combined with an SLA-based policy determines whether access to the API at a certain level requires approval from an API Versions Owner orx a member of the Organization Administrators role. 

== See Also

* link:/api-manager/[API Manager]
* link:/api-manager/proxy-about[About Proxies]
* link:/api-manager/tutorial-set-up-and-deploy-an-api-proxy[To Set Up and Deploy an API Proxy]
* link:/api-manager/using-policies[About Policies]
* link:/api-manager/policy-reference[Policy Reference]
* link:/api-manager/defining-sla-tiers[SLA Tiers Reference]
* link:/api-manager/rate-limiting-and-throttling-sla-based-policies[Rate Limiting and Throttling - SLA-Based Policies]