= About Managing API Proxies and Policies

This topic provides general information about managing APIs in Anypoint Platform. After defining an API, you can allow users to access and use it by deploying it to a Mule runtime. After deploying an API, you can control how users access it by configuring an API proxy and defining policies that specify who has access to the API.

Anypoint Platform uses API Manager to deploy and manage APIs, API proxies and API polices.

== Deploying an API

After defining and API, you can deploy your API to the API Gateway of a Mule Runtime. Deploying an API enables users to access and use your API.

The implementation of your API can be one of the following:

* An external service: your API can point to an external service available outside of a Mule runtime. In this case, your API serves as a proxy for that service. You can also define policies that determine how users access your the service.

* A Mule application: your API can point to a Mule application deployed to a Mule runtime. In this case, the API enables you to specify policies that determine how users access the application.


To deploy and define API policies, Anypoint Platform provides the following tools:

[%header%autowidth.spread]
|===
| Component | Description
| API Manager | Enables you to deploy an API to an API Gateway, apply policies, define custom policies, create alerts for an API, and view API analytics.
| Runtime Manager | Enables you configure the servers where an API Gateway is running and view its performance.
| Analytics | A dashboard that enables you to view usage statistics for and API and to determine an API's performance. This dashboard also provides information about transactions and MQ analytics.
|===


Using API Manager, you can deploy a proxy to an API Gateway running on Mulesoft's CloudHub. To deploy a proxy to an API on a user-hosted Mule runtime, use Anypoint Runtime Manager.


== API Proxies

API proxies enable you to specify how users connect to and use a deployed API. Proxies act as intermediaries between your API consumers and the backend services your API connects to. This helps to ensure that changes to backend services do not affect how an API is used. API proxies provide an additional layer of security by shielding access to backend services and IP addresses.

== API Policies

API policies enable you to control who has access to a deployed API by applying filters to incoming network traffic. API policies filters generally control authentication, access, allotted consumption, and service level access (SLA).

Anypoint Platform provides several pre-defined policies. You can also create your own custom policies as required. Using API Manager, you can create and deploy policies for APIs deployed to CloudHub or to a user-hosted Mule runtime. 

== Service Level Access (SLA)

API Manager enables you to define an SLA for a deployed API. A Service Level Access (SLA) tier is a category of user access that you can specify for an API. The tier definition combined with an SLA-based policy determines whether access to the API at a certain level requires approval from an API Versions Owner orx a member of the Organization Administrators role. 

== See Also

* link:/api-manager/[API Manager]
* link:/api-manager/proxy-about[About Proxies]
* link:/api-manager/tutorial-set-up-and-deploy-an-api-proxy[To Set Up and Deploy an API Proxy]
* link:/api-manager/using-policies[About Policies]
* link:/api-manager/policy-reference[Policy Reference]
* link:/api-manager/defining-sla-tiers[SLA Tiers Reference]
* link:/api-manager/rate-limiting-and-throttling-sla-based-policies[Rate Limiting and Throttling - SLA-Based Policies]