= Manipulating Requests Using Scripting

So far we have seen how we can write Java code to interact with Mule. This example introduces using scripting in Mule. Scripting is a powerful way to manipulate requests and create custom logic. The benefit of scripting is that you can use different languages in Mule namely, link:http://www.groovy-lang.org/[Groovy], Ruby (using link:http://jruby.org[JRuby]), Python (using link:http://jython.org[Jython]) and server-side link:http://www.mozilla.org/rhino[JavaScript]. This example uses Groovy to transform an incoming message.

== What You  Learn

* Using the Script Transformer and configuring it from Mule Studio
* Embedding script code in your configuration file, removing the need to create an external code file

10 minutes

== Building It Now!

=== Prerequisites

Ideally, you should be working through these tutorials in sequence and have completed the Invoking a Component Method lesson.

== Running the Example

== What Just Happened?

* You created a scripting transformer configured to use Groovy as the language
* You embedded a script in your Mule configuration file to perform a transformation on the incoming request
* The resulting behavior was the same as Working with Transformers except you didn't need to create a separate Java class to perform the transformation.

== Next Steps

* link:/mule-user-guide/v/3.2/[Back to Index] 
* link:/mule-user-guide/v/3.2/using-outbound-endpoints-to-publish-data[Using Outbound Endpoints to Publish Data]
