:keywords: agent, mule, esb, servers, monitor, notifications, external systems, third party, get status, metrics


= Mule Agent API

For the vast majority of use cases, all you'll need to do with the Mule Agent is install it and configure it according to what you can read in link:/mule-agent/v/1.5/installing-and-configuring-mule-agent[Installing and Configuring the Mule Agent]

If you wish to use the Mule Agent for more than communicating the Runtime Manager with Mule Runtimes on-premises, then you may have an interest in the documents in this section:

* link:/mule-agent/v/1.5/administration-service[Administration Service]
* link:/mule-agent/v/1.5/managing-applications-and-domains[Managing Applications and Domains]
* link:/mule-agent/v/1.5/jmx-service[JMX Service]
* link:/mule-agent/v/1.5/mule-agent-notifications[Mule Agent Notifications]


[NOTE]
None of these topics relate to the link:/mule-management-console/v/3.8/index[Mule Management Console]. These topics are about the Mule Agent that communicates the Runtime Manager with local runtimes.
