= Configuration Overrides

:keywords: mule, sdk, config, configuration, override, parameter

There are times when a certain parameter of your Configuration could be thought as a "global default", stating
a default value/behavior for that parameter for other operations an sources to use. In that
case you would also want to be able to override the value in certain components of the
application, to keep it flexible. Lucky for you, @ConfigOverride allows you to do exactly that.

== What is a Configuration Override

This feature binds a parameter from a source or operation to a parameter that exists
on a configuration. When a parameter is annotated with `@ConfigOverride` and a value is
not specified for it on the DSL, the configuration value for the parameter with the _exactly_ same
name will be injected on it.

This annotation can either be applied to an argument of an Operation method or to a field
of a Source, and it cannot be used on configurations nor connections.

For example, if you have a Parameter declared in your Configuration like this:

[source, java, linenums]
----
@Parameter
@Optional(defaultValue = "10")
int maxRetries;
----

And that configuration is used on an operation:

[source, java, linenums]
----
public void request(@Config ConfigType config, @ConfigOverride int maxRetries)
  // ...
}
----

Then there are three different possibilities for how the parameter `maxRetries` on the operation
`request` will get its value:

*  The default value of the `maxRetries` parameter provided by the configuration will be used
when neither the configuration nor the operation provide a value for `maxRetries`.

[source, xml, linenums]
----
<extension:config name="sampleConfig">

<flow name="requestFlow">
  <extension:request config-ref="sampleConfig">
</flow>
----

On the operation, the `maxRetries` parameter takes the value 10.

* The value provided for the `maxRetries` parameter in the configuration will be used
when the value for the parameter is not specified on the operation but is explicit on the configuration

[source, xml, linenums]
----
<extension:config name="sampleConfig" maxRetries=2>

<flow name="requestFlow">
   <extension:request config-ref="sampleConfig">
</flow>
----

On the operation, the `maxRetries` parameter takes the value 2.

* The value provided for the `maxRetries` parameter in the operation is used When
this parameter is explicitly added on the DSL.

[source, xml, linenums]
----
<extension:config name="sampleConfig" maxRetries=2>

<flow name="requestFlow">
   <extension:request config-ref="sampleConfig" maxRetries=5>
</flow>
----

On the operation, the `maxRetries` parameter takes the value 5.

NOTE: This feature does not change the values on the configuration. It only injects the configuration values
on the parameters or leaves the ones specified.

== Configuration Override Requirements

There are a couple of requirements that have to be met for overriding configuration parameters:

* The name and type of the parameter in the configuration must be the same as the one annotated with `@ConfigOverride`.

* If an operation has a parameter annotated with `@ConfigOverride`, it must also have the corresponding Configuration as parameter.

* If a source has a field annotated with `@ConfigOverride`, it must also have the corresponding Configuration as a field.

== Configuration Override Parameter within Parameter Groups

This annotation can also be used to reference a `Parameter` that belong to a `ParameterGroup` within
a Configuration. This is an example of how to do it:

[source, java, linenums]
----
public class ConfigType{

  @ParameterGroup(name = "Strategy")
  private RetryStrategy retryStrategy;

  // ... Parameter getters
}
----

[source, java, linenums]
----
public class RetryStrategy{

  @Parameter
  private int maxRetries;

  @Parameter
  private String retriesExhaustedMessage;

  // ... Parameter getters
}
----

On this operation we use the `@ConfigOverride` referencing `maxRetries` that is inside the
`RetryStrategy` class:

[source, java, linenums]
----
public void request(@Config ConfigType config, @ConfigOverride int maxRetries)
  // ...
}
----

== Configuration Override with POJOs

If your configuration have parameters that are POJOs you can override those too. The content
of the POJO parameter on the operation/source will either be totally defined by the configuration or
totally defined by the operation. This means, you cannot define a partially populated POJO and expect the
rest of the POJO to have the configuration values injected.

The logic to decide which values to use is the same as if it was a simple java type.

== Configuration Parameter without Default Value

If the configuration parameter is optional, does not have a default value and an operation/source parameter
references it with a `@ConfigOverride`, its value will default to null. Let's see an example of this:

This is a parameter declared in the configuration:

[source, java, linenums]
----
@Parameter
@Optional
private String retriesExhaustedMessage;
----

This is an operation that has that configuration as a parameter and a configuration override
parameter:

[source, java, linenums]
----
public void request(@Config ConfigType config, @ConfigOverride String retriesExhaustedMessage)
  // ...
}
----

If `retriesExhaustedMessage` is not specified in the configuration and the operation, then its value
will be null.

== Configuration Override Example

This is a simplified example of the usage of `@ConfigOverride` :

The definition of the Configuration:

[source, java, linenums]
----
@Configuration(name = "config")
@Operations({AmqpConsume.class, AmqpPublish.class, AmqpPublishConsume.class, })
public class AmqpConfig {

  @Parameter
  @Expression(NOT_SUPPORTED)
  @Optional(defaultValue = "*/*")
  private String contentType;


  @Expression(NOT_SUPPORTED)
  @ParameterGroup(name = "Consumer Config", showInDsl = true)
  private AmqpConsumerConfig consumerConfig;


  // ... All parameter getters

}
----

This is the `AmqpConsumerConfig` class that has the parameters that will be referenced
by the `@ConfigOverride` annotation on this example:

[source, java, linenums]
----
public final class AmqpConsumerConfig {

  @Parameter
  @Optional(defaultValue = "IMMEDIATE")
  @Expression(NOT_SUPPORTED)
  private AckMode ackMode;

  @Parameter
  @Optional(defaultValue = "false")
  @Expression(NOT_SUPPORTED)
  private boolean noLocal;

  @Parameter
  @Optional(defaultValue = "false")
  @Expression(NOT_SUPPORTED)
  private boolean exclusiveConsumers;

  @Parameter
  @Optional(defaultValue = "4")
  @Expression(NOT_SUPPORTED)
  private int numberOfConsumers;

  // ... All parameter getters
}
----

Source that has a `AmqpConfig` and parameters with the `ConfigOverride` annotation:

[source, java, linenums]
----
@Alias("listener")
@EmitsResponse
@MetadataScope(outputResolver = AmqpOutputResolver.class)
public class AmqpListener extends Source<Object, AmqpMessageAttributes> {


  @Connection
  private ConnectionProvider<AmqpTransactionalConnection> connectionProvider;

  private AmqpTransactionalConnection connection;

  @Config
  private AmqpConfig config; // <1>

  @Parameter
  private String queueName;

  @Parameter
  @ConfigOverride
  private AckMode ackMode; // <2>

  @Parameter
  @ConfigOverride
  private int numberOfConsumers; // <2>

  @Parameter
  @Optional
  private String consumerTag;


  @Override
  public void onStart(SourceCallback<Object, AmqpMessageAttributes> sourceCallback) throws MuleException {
    // ...
  }
  // ...
  @Override
  public void onStop() {
    // ...
  }
  // ...
}
----

<1> Configuration from which the values to override the `@ConfigOverride` annotated parameters
will be taken.

<2> Parameter that if not specified on the operation will inherit the configuration value of the
one with _exactly_ the same name. Note that the parameters with these names belong to a `ParameterGroup`

Let's see an example of how the override behaves.

[source, xml, linenums]
----
<amqp:config name="config">
 <amqp:connection host="localhost" port="5671" virtualHost="/" username="guest" password="guest"/>
 <amqp:consumer-config numberOfConsumers="16" /> // <1>
</amqp:config>

<flow name="amqpStatisticsListen">
  <amqp:listener config-ref="config" queueName="statisticsQueue" numberOfConsumers="1"/> // <2>
  <!-- process statistics -->
  <logger level="INFO" message="#[payload]"/>
</flow>
----

<1> In the Config, `numberOfConsumers` is set to 16 while `ackMode` takes the default value
<2> In the Source, `numberOfConsumers` is specified so it will take the value 1, while `ackMode` is not, so
it will take the value from the config, which is `IMMEDIATE`.
