= Mule Services Injection

:keywords: mule, sdk, dependency, inject, registry, service

== Using Mule Services

When implementing your module you may need to use some of the services that mule provides, some
examples of these services are `ObjectStoreManager`, `LockFactory` or `HttpService`.

To achieve this there is no need to get them from the actual registry from the MuleContext. You can
simply inject them to your component(Operation, Source, Configuration, etc) through the `@Inject` annotation.

This is a simplified example of how to inject a service from the registry to your component:

[source, java, linenums]
----
public class ObjectStoreOperations {
// ...
  @Inject
  private ObjectStoreManager runtimeObjectStoreManager;
// ...
  @Throws(StoreErrorTypeProvider.class)
  public void store(String key,
                  @Content TypedValue<Serializable> value,
                  @Optional @ParameterDsl(allowInlineDefinition = false) ObjectStore objectStore) {
    ObjectStore os = objectStore == null ? runtimeObjectStoreManager.getDefaultPartition() : objectStore;
    os.store(key, value);
  }
// ...
}
----

This is a list of useful services that can be injected:

* *LockFactory*: All mule components that require synchronization for access shared
data must be synchronized using locks from the default implementation of this interface.

* *ExpressionManager*: Provides universal access for evaluating expressions embedded in
Mule configurations, such as XML, Java, scripting and annotations.

* *TransformationService*: Service that tries to transform a value into another given
type.

* *HttpService*: Provides both HTTP server and client implementations. Whenever using
HTTP connection on your connector, you should try to use this service.

* *ExtensionManager*: Manages the extension models available in the current context and their
state.This class is also the access point to obtaining configuration instances of the extensions in
use.

* *SchedulerService*: Provides access to the different schedulers and thread pools that exist
in the Mule runtime, allowing you to schedule tasks on those.

* *SoapService*: Service that creates SOAP clients to consume SOAP services.

* *ObjectStoreManager*: Manager in charge of creation and management of ObjectStore
instances.
