= To Configure Web Service Security
:keywords: web service consumer, security
:toc:
:toc-title: Page Contents

toc::[]

//MG what is WS-security, under the hood?

The web service consumer lets you add security for the outgoing and incoming SOAP messages.

The supported security mechanisms are:

 * <<UsernameToken>>
 * <<Timestamp>>
 * <<Signature>>
 * <<Encrypt>>
 * <<Decrypt>>

Define `<wsc:security-strategies>` to support each security strategy.

See also: <<Keystore Configuration>>, <<Truststore Configuration>>, and <<Multiple Security Strategies Configuration>>.

=== UsernameToken

Adds a username token to the outgoing SOAP message.

[source,xml,linenums]
----
<wsc:connection wsdlLocation="http://.../usernameToken?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
       <wsc:wss-username-token-security-strategy
      username="admin"
      password="textPassword"
      passwordType="TEXT"
      addCreated="true"
      addNonce="true"/>
   </wsc:security-strategies>
</wsc:connection>
----

This security strategy exposes the following configuration attributes:

* `username`: Defines the username to access Web service; added to header of request sent to Web service.
* `password`: Defines the password to access Web service; added to header of request sent to Web service.
* `passwordType`: This specifies how the password should be serialized, *DIGEST* or *TEXT*. The _password digest_ option is non-standard and should only be used for interop issues where the message receiver desires an extra SHA-1 Hash of the password. Defaults to *TEXT.*
* `addCreated`: Specifies whether or not to add a "Created" header to the Web service request. Defaults to *_false_*
* `addNonce`: Specifies whether or not to add a "Nonce" header to the Web service request. Defaults to *_false_*

=== Timestamp

Adds a timestamp entry to the outgoing message, it only contains two attributes: `timeToLive` and `timeToLiveUnit`.

[source,xml,linenums]
----
<wsc:connection wsdlLocation="http://.../sign?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
       <wsc:wss-timestamp-security-strategy
         timeToLive="1"
         timeToLiveUnit="MINUTES"/>
   </wsc:security-strategies>
</wsc:connection>
----

* `timeToLive`: Length of time the message is valid. This attributes is qualified by the `timeToLiveUnit` attribute. The default value is 60 (seconds, qualified by the time unit `timeToLiveUnit`). 
* `timeToLiveUnit`: Unit of time which qualifies the `timeToLive` attribute. The default is `SECONDS`.

=== Signature

Signs the outgoing message using the keystore configuration provided.


[source,xml,linenums]
----
<wsc:connection wsdlLocation="http://.../sign?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
      <wsc:wss-sign-security-strategy>
          <wsc:key-store-configuration
          keyStorePath="path/To/Key/Store"
          password="changeit"
          alias="s1as"
          type="jks"/>
      </wsc:wss-sign-security-strategy>
   </wsc:security-strategies>
</wsc:connection>
----


=== Verify Signature

Validates the signature of an incoming SOAP message using the truststore configuration provided.

[source,xml,linenums]
----
<wsc:connection wsdlLocation="http://.../sign?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
      <wsc:wss-verify-signature-security-strategy>
         <wsc:trust-store-configuration
         trustStorePath="path/To/TrustStore"
         password="mulepassword"/>
      </wsc:wss-verify-signature-security-strategy>
   </wsc:security-strategies>
</wsc:connection>
----

=== Encrypt

Encrypts the body of an outgoing SOAP message using the keystore configuration provided.

[source,xml,linenums]
----
<wsc:connection wsdlLocation="http://.../sign?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
      <wsc:wss-encrypt-security-strategy>
          <wsc:key-store-configuration keyStorePath="path/To/Key/Store"
          password="changeit"
          alias="s1as"
          type="jks"/>
      </wsc:wss-encrypt-security-strategy>
   </wsc:security-strategies>
</wsc:connection>
----

=== Decrypt

Decrypts the body of an incoming SOAP message using the keystore configuration provided.

[source,xml,linenums]
----
<wsc:connection wsdlLocation="http://.../sign?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
      <wsc:wss-decrypt-security-strategy>
          <wsc:key-store-configuration
          keyStorePath="path/To/Key/Store"
          password="changeit"
          alias="s1as"
          type="jks"/>
      </wsc:wss-decrypt-security-strategy>
   </wsc:security-strategies>
</wsc:connection>
----

== Keystore Configuration

Enables the configuration of keystore for signing, encrypting, or decrypting. 

The keystore is a POJO with 5 fields:

* `keyStorePath`: The location of the keyStoreFile.
* `password`: The password used to access the store.
* `alias`: The alias of the private key to use.
* `keyPassword`: The password used to access the private key. If required.
* `type`: The type of store (jks, pkcs12, jceks). Defaults to `jks`.

[source,xml,linenums]
----
<wsc:key-store-configuration
  keyStorePath="path/To/Key/Store"
  password="changeit"
  alias="s1as"
  keyPassword="asdasd123123"
  type="jks"/>
----

== Truststore Configuration

Enables the configuration of truststore for verifying signatures. 

The truststore is a POJO with 3 fields:

 * `trustStorePath`: The location of the trustStore file.
 * `password`: The password used to access the store.
 * `type`: The type of store (jks, pkcs12, jceks). Defaults to `jks`.

[source,xml,linenums]
----
<wsc:trust-store-configuration  trustStorePath="path/To/TrustStore"
password="enterpassword"
type="jks"/>
----

Both the keystore and truststore configurations can be defined as global elements 
so that they can be reused in different configurations.

[source,xml,linenums]
----
<wsc:key-store-configuration
  name="keyStoreGlobalConfig"
  keyStorePath="path/To/Key/Store"
  password="changeit"
  alias="s1as" type="jks"/>

<wsc:connection wsdlLocation="http://.../sign?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
      <wsc:wss-decrypt-security-strategy name="keyStoreGlobalConfig"/>
   </wsc:security-strategies>
</wsc:connection>
----

== Multiple Security Strategies Configuration

Declaring multiple security strategies is valid.

The following Web Service Consumer connector example is secured with encryption, decryption, and a timestamp.

[source,xml,linenums]
----
<wsc:connection wsdlLocation="http://.../sign?wsdl" service="Service" port="Port">
   <wsc:security-strategies>
      <wsc:wss-timestamp-security-strategy timeToLive="1" timeToLiveUnit="MINUTES"/>
           <wsc:wss-encrypt-security-strategy>
          <wsc:key-store-configuration keyStorePath="path/To/Key/Store"
          password="changeit"
          alias="s1as"
          type="jks"/>
      </wsc:wss-encrypt-security-strategy>
      <wsc:wss-decrypt-security-strategy>
          <wsc:key-store-configuration keyStorePath="path/To/Key/Store2"
          password="changeit"
          alias="anotherAlias"
          type="jks"/>
      </wsc:wss-decrypt-security-strategy>
   </wsc:security-strategies>
</wsc:connection>
----

== See Also

* link:/mule-user-guide/v/4.0/core-connectors/web-service-consumer[Web Service Consumer Connector].
