== To Create a Connection
:keywords: web service consumer, create connection
:toc:
:toc-title: Page Contents

toc::[]

To connect with a SOAP service, three parameters must be provided:

* *WSDL* location (URL or a local file),
* *service name* from the specified *WSDL*
* *port name* for the specified *service name*

By default, the service looks for the address in the *WSDL* with the binding that defines the provided service and port. Also, you can specify the SOAP version that you want to build the request for with link:https://www.w3.org/TR/2000/NOTE-SOAP-20000508/[SOAP 1.1] configured as the default.


[source,xml,linenus]
----
<wsc:connection service="aService"
  port="aPort"
  wsdlLocation="http://www.serviceAddress.com/path?wsdl"
  soapVersion="SOAP12"/>
----

The connection parses the provided WSDL file and loads all the referenced schemas to find the types and elements as needed.
//MG a connection parses the wsdl?

If the SOAP server supports MTOM the connection can have MTOM enabled using the `mtomEnabled` flag. What this does is send all the attachments for the operations in an HTTP multipart message (if JMS is configured as the underlying transport this is not possible). MTOM is disabled by default.

[source,xml]
----
<wsc:connection service="aService" port="aPort" wsdlLocation="...?wsdl" mtomEnabled="true"/>
----
//If JMS is enabled, what does this mean for MTOM then? Are these two features mutually exclusive


All connections created by the web service consumer are reusable and the provider is implemented as a `PoolingConnectionProvider`.


== See Also

* link:/mule-user-guide/v/4.0/core-connectors/web-service-consumer[Web Service Consumer Connector].
