= APIkit Reference
:keywords: apikit, maven

This reference contains dependency, namespace, schema, and other information for APIkit.

== Retrieving RAML Resources 

You can retrieve the root raml file and its resources by performing a GET request using curl or an HTTP client, such as Postman.

If you are using RAML 0.8, you can resolve the root RAML file and all included files in one call. Send a Header and the URL in a GET request, as follows:

* HEADER: *Accept: application/raml+yaml*
* URL: `{scheme}://{host}:{port}/{console path}`

*RAML 0.8 Example - Get the Root RAML File*

* HEADER: Accept: application/raml+yaml
* URL: `+http://localhost:8081/console+`

If you are using RAML 1.0, you don't need to send a header. You can get the root RAML in one call using the GET method. You can also get any other included resource using the GET method as follows:

URL: `{scheme}://{host}:{port}/{console path}/{api resources folder}{optional resource path}/?raml`

*RAML 1.0 Example - Get the Root RAML file*

URL: `+http://localhost:8081/console/api/?raml+`

*RAML 1.0 Example - Get an included file*

URL: `+http://localhost:8081/console/api/user.schema.json?raml+`

*RAML 1.0 Example - Get a RAML Fragment*

URL: `+http://localhost:8081/console/api/types/raml-types.raml?raml+`

== APIkit Dependency Information (Beta)

----
<dependency>
  <groupId>org.mule.modules</groupId>
  <artifactId>mule-apikit-module</artifactId>
  <version>1.0.0-BETA.3</version>
</dependency>
----

*APIkit Namespace and Schema (Beta)*

----
xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core" 
xsi:schemaLocation="http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd"
----

=== apikit Elements

[%header,cols="30a,50a,8a"]
|===
|Element Name |Description |Required 
|*apikit:config* |APIkit configuration |Y 
|*apikit:console* |Refers to the config-ref property in the http:listener element in the api-console flow that defines the API Console URL |N 
|*apikit:router* |A rest routing message processor nested in the flow element |Y 
|===

=== apikit:config Attributes

These elements are of type NonBlankString.

[%header,cols="22a,10a,68a"]
|===
|Attribute Name|Required |Description
|*outboundHeadersMapName* |N |Used to identify the name of the map the contains response headers
|*httpStatusVarName* |N |The name of the variable that stores the HTTP status code in the response
|*keepRamlBaseUri* |N |Rewrites (false) or does not rewrite (true) the baseUri in the RAML definition of the API.
|*name* |Y |Configuration name that other elements, such as apikit:router, reference
|*raml* |Y |Name of RAML file in src/main/api
|===

If you are using APIkit behind a reverse proxy, you can use APIkit Console if you set `keepRamlBaseUri` to true to put the URL of a proxy in the baseUri property.

