= APIkit 4.x Reference
:keywords: apikit, rest, console, load balancer, configuring path

APIkit supports RAML 1.0 and 0.8 versions as described in the release notes. APIkit projects can run onsite or on CloudHub. 

== Configuring the Path for Deployment on CloudHub

CloudHub requires a unique application name regardless of the region where you deploy the API. You can, for example, add the region name to the application name to ensure uniqueness. For example:

`test-customers-eu`

`test-customers-na`

By default, APIkit adds a base path `/api` to each API. The final URL of the APIs deployed on CloudHub is:

`+http://test-customers.eu.cloudhub.io/api/customers+`

`+http://acceptance-customer.eu.cloudhub.io/api/customers+`

== Changing APIkit Elements

Under the following conditions, you need to customize the mapping of RAML resources and actions:

* You generated backend flows as part of the backend-first design process.
* You renamed a backend flow.

Customizing the mapping of RAML resources and actions is described in the backend-first design process.

== Using a Load Balancer

If your API implementation involves putting a load balancer in front of your APIkit application, configure the load balancer to redirect URLs that reference the `baseUri` of the application directly. If the load balancer does not redirect URLs, any calls that reach the load balancer looking for the application do not reach their destination. For example, you deploy an APIkit application to `myapp.mycompany.com`, and then add a load balancer at `www.exampleloadbalancer.com`. A call to the API arrives at `www.exampleloadbalancer.com` and the load balancer redirects the call to `myapp.mycompany.com` to get a response.

When using a load balance, set the `keepRamlBaseUri` to true to put the URL of a proxy in the baseUri property.

== See Also

* link:/apikit/apikit-tutorial-jsonplaceholder[REST tutorial]
* link:/release-notes/apikit-4.0-release-notes[Release Notes]
