= About APIkit 3.x and 4.x

*Documentation for APIkit 4.x*

APIkit is a tool for building Mule REST or SOAP APIs. APIkit simplifies the design and implementation of Mule RESTful APIs by creating skeletal Mule flows in the Studio project. You develop APIs based on one of the following modeling languages:

* RESTful API Modeling Language (RAML) 1.0 and 0.8 versions
* Web Service Description Language (WSDL)

APIkit uses a scaffolding technique to generate final code for Mule Runtime can using the RAML or WSDL specification and pre-defined code templates:

* Basic configuration files
* XML configuration (Mule code)

The generated, minimal flows meet the communication operations required by REST or web service contract. Included are flows for routing and binding to RAML resources, handling error conditions, setting status codes, and making RESTful calls or SOAP API requests. 

APIkit projects can run onsite or on CloudHub. You can create APIkit flows for Mule in XML. Using Studio automates the process. 

After generating the API, you can simulate calls using API Console. 

== See Also

* link:/apikit/apikit-simulate[To Simulate API Calls using API Console]




