= APIkit Overview
:keywords: api, apikit, raml
 

APIkit and APIkit for SOAP are toolkits for REST or SOAP API development. APIkit converts standard web service specification documents into skeletal flows in the Mule project. The generated, minimal flows meet the communication operations required by the web service contract. Included are flows for handling error conditions, setting status codes, and making RESTful calls or SOAP API requests.

You develop APIs based on one of the following modeling languages:

* RESTful API Modeling Language 
* Web Service Description Language

You can reference an external RAML or WSDL design, import the design into Studio, or build the RAML or WSDL within Studio using the text editor. 

You can use API Console to simulate calls to a RAML-based API.

After APIkit generates the framework of the flows, you build out the flows to implement the API: add web services, document, and so on.

The best practice for API design with APIkit is first to design the RAML or WSDL interface outside Studio. For RAML development, MuleSoft recommends using Design Center. Next, you import the file into a Studio project to construct your main and backend flows. Alternatively, you can design the backend first by adding an API to an existing Studio project. 

After designing an API to the RAML specification using APIkit, you can apply policies to the API in Anypoint Platform.

== Limitations

The following limitations apply:

* APIkit for SOAP works only on Mule EE runtime 3.8.0 or later. 
* APIkit for SOAP does not download protected resources from the web. 
+
For example, a WSDL file behind a schema model, such as Basic Authentication, is not supported. You need to manually download the WSDL file and all dependencies, such as XSD, and select those files locally.

=== Security, Protocol, and baseUriParameter Limitations

APIkit 3.8.1 and later supports RAML 1.0. Mule 3.8.0 runtime limitations related to earlier versions of APIkit are covered in the RAML 1.0 early access document.

In API Gateway Runtime 2.x and earlier, APIkit is designed to work very tightly with RAML interfaces, but does not automatically import the following items from the RAML definition:

* securitySchemes
* protocols
* baseUriParameters

The protocol, URI host, and path defined in the RAML file are disregarded in favor of the ones that you define in the APIkit project's HTTP Connector.


=== API Console Limitations

APIkit does not support the Client Credentials and Resource Owner Password Credentials grant types in the embedded API Console. To use these grant types, access the APIkit Console from a web browser. APIkit Console does not support scopes.

== See Also

* link:/api-manager/using-policies[Applying policies]
* link:/mule-user-guide/v/3.8/http-listener-connector[Basic authentication filters]
* link:/mule-user-guide/v/3.8/configuring-security[Security Manager] 
* link:/mule-user-guide/v/3.8/anypoint-enterprise-security[Anypoint Enterprise Security] 
* link:/api-manager/using-policies[Runtime policy management]
* link:/api-manager/oauth2-provider-configuration#configuring-scopes[Configurinng scopes]
* https://docs.mulesoft.com/release-notes/raml-1-early-access-support[RAML 1.0 early access document]


