= APIkit Overview

APIkit is a tool for building Mule REST or SOAP APIs. APIkit 4.0 simplifies the design and implementation of Mule RESTful APIs by creating skeletal Mule flows in the Mule project. You develop APIs based on one of the following modeling languages:

* RESTful API Modeling Language (RAML) 1.0 and 0.8 versions
* Web Service Description Language (WSDL)

For RAML development, MuleSoft recommends using Design Center. Alternatively, use the RAML Editor in Studio or any text editor.

The generated, minimal flows meet the communication operations required by the web service contract. Included are flows for routing and binding to RAML resources, handling error conditions, setting status codes, and making RESTful calls or SOAP API requests. APIkit 4.0 supports Mule Runtime 4.0 features, such as error handling.

APIkit projects can run onsite or on CloudHub. You can create APIkit flows for Mule in XML. Using Studio automates the process.

After generating the API, you can simulate calls using API Console. 

== See Also

* link:/apikit/apikit-simulate[To Simulate API Calls using API Console]
* https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/[RAML]



