= APIKit
:keywords: api, apikit, raml

APIkit is an open-source, declarative toolkit that facilitates REST and SOAP API implementation using link:http://raml.org[RAML] and link:http://en.wikipedia.org/wiki/Web_Services_Description_Language[WSDL], respectively. You import, reference, or build the RAML or WSDL in Studio, and then use APIkit to efficiently develop the API further. For example, you can add web services, document, test, and enforce best practices, such as proper exception handling. 

When you use an existing RAML or SOAP that declares a baseURI to create a Mule project, the APIkit Router appears in your flow. Some tasks that the APIkit Router performs are:

* Routes messages
* Validates payloads, headers, query-params, uri-params
* Serializes responses

Message routing consists of routing incoming API requests to existing Mule flows and returning outgoing HTTP response codes to exceptions.

APIkit generates a backend flow for each resource/action pairing in a RAML or for each operation in a WSDL. Backend flows mock responses of the REST API for simulating calls to the API or provide XML responses to the request in the SOAP API. APIkit projects based in RAML include the same console for this simulation as the link:/api-manager/designing-your-api#simulating-calls-to-the-api[API Designer]. API and application developers use the console to interact with the API and browse RAML embedded documentation.