= About Starting an APIkit Project

In Studio, you can start an APIkit project in several ways:

* File > New > Mule Project, check Add APIkit Components.
* File > New > Mule Project, check Add APIkit Components, and enter an API definition file location or URL.
* Create the RAML file within an existing Studio project (called a backend-first APIkit design).

The API definition file is a RAML or WSDL. When you check Add APIkit Components but don't import or reference an API definition file, scaffolding occurs, generating a skeletal RAML file and XML configuration that includes the following things:

* A main flow
+
[source,xml,linenums]
----
<flow name="api-main">

</flow>
----
+
* HTTP Listener configuration in the main flow
* APIkit Router component
* Error handlers

When you check Add APIkit Components and do import or reference an API definition file, scaffolding creates an archetype depending on the type of API definition file. The following things are generated:

* RAML
+
** A main flow
** HTTP Listener configuration
** APIkit Router component
** Error handlers
** RAML dependencies
+
Push or pull changes from one location, such as Studio, to the other, such as Design Center.
+
* Backend flows containing REST resource-action mappings
+
* WSDL
+
** Everything listed above
** A main flow with an HTTP Listener
** A SOAP Router
** A SOAP fault response template
** Backend flows containing SOAP message templates.

Use a SOAP testing tool, such as SoapUI, to simulate calls to the API. If you change the WSDL, regenerate backend flows using Mule > Generate SOAP Flows.


