= Deploying an APIkit project
:keywords: deploy, api, runtime, apikit, gateway

You can deploy an APIkit project to a Mule runtime on-premises or in the cloud. You can deploy an APIkit project to the legacy API Gateway Runtime 2.x or 1.3.x if the number of connectors, other than HTTP/S, Jetty, and/or Web Service Consumer, does not exceed two.

Perform the following set up to step through the deployment procedures:

. link:_attachments/my-raml-implementation.zip[Download an APIkit project].
. In Studio, select *File* > *Import*.
. Select *Anypoint Studio* > *Anypoint Studio generated Deployable Archive (zip)*.
. Click *Next*.
+
The *Import Mule Project* dialog appears.
+
. Browse to the downloaded file.
. Click *Finish*.

== On-Premises Mule Runtime

Deploy an APIkit project to an on-premises runtime as described in the following procedure. 

. If you have not downloaded the Mule standalone runtime, link:https://developer.mulesoft.com/docs/display/current/Installing[follow steps to install the latest version].
. Start Mule in the command line by running:
+
Windows: `<MULE_HOME>\bin\mule`
+
Mac and Unix: `<MULE_HOME>/bin/mule`
+
`<MULE_HOME`> is the value of the MULE_HOME variable employed by Mule, usually the root directory of the installation, such as `/opt/Mule/mule-standalone-3.8.0/`

. Navigate to the directory where the .zip file is located and copy the .zip file.
+
Ensure that your copy of the file does not have any spaces in the name.
+ 
. Drop the copy of the .zip file into the `<MULE_HOME>/apps` folder.
. Mule polls this folder for new applications every five seconds. Watch your command line window to track the progress of the deployment.
. When you see the message `Started app 'TshirtService'`, then your API is deployed to the Mule runtime.

If you want to undeploy your application, navigate to the `app` directory and delete the file `your_application.txt`. This removes your application from the `/app` directory, which automatically undeploys it.

== Cloud-Based Mule Runtime

This procedure assumes that you have an Anypoint Platform account.

Deploy an APIkit project to a Cloud runtime as described in the following procedure.

. Right-click on the project in Package Explorer, and then click *Anypoint Platform* > *Deploy to Cloud* from the cascading menu.
+
The Anypoint Platform Sign In dialog appears.
. Enter your user name and password, and click *Sign In*.
+ 
The *Deploy to Runtime Manager* dialog opens. 
. Type an arbitrary domain name up to 42 characteris in length.
. Select an Environment and a Mule Version.
+
Click *Finish*.
+
Anypoint Studio packages, uploads, and deploys your application to CloudHub.
. Browse to the URL of yourdomain.cloudhub.io (also shown in the pop-up window above). 
+
The link:/runtime-manager[Runtime Manager] indicates that the API is running.

To stop the application, click the *Settings* tab and click *Cancel deployment*.

== Deploying an APIkit Project in Studio

If you created or modified the file in Anypoint Studio:

. Save the project, and go to *File* > *Export...*
. Select *Anypoint Studio Project to Mule Deployable Archive (includes Studio metadata)*, and click *Next*.
. Select the name of your application from the *Project* drop-down, and click *Browse...* to select a destination for the file. 
. Click *Finish* .

If your organization has On Premises Auto-Deploy enabled, and you have already configured Auto-deployment, then you can also deploy your applications on premises link:/runtime-manager/managing-servers[via the Anypoint Runtime Manager Console].
