= Anypoint MQ Connector
:keywords: mq, connector

https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[_Select_]

*Release Notes:* link:/release-notes/mq-connector-release-notes[Anypoint MQ Connector Release Notes] +
*Reference:* link:/mule-user-guide/v/3.8/anypoint-mq-connector-reference[Anypoint MQ Connector Reference]

The Anypoint MQ connector provides publish-subscribe messaging in Anypoint Studio. Anypoint MQ supports hybrid use cases, IoT where you collect data from different devices, and a REST API you can use with device applications. You can also use Anypoint MQ with other application frameworks such as node.js, to communicate to queues.

== Prerequisites

To use this connector, you should be familiar with Anypoint Studio, Anypoint connectors, and Mule flows. The Anypoint MQ connector is free, but connecting to the service in Anypoint Platform requires a license.

*Note:* You cannot complete the configuration information in this document without an Anypoint MQ license. 

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |Mule 3.7.4 and later
|Anypoint Studio |v5 and later
|===

== To Install This Connector

. In Anypoint Studio, click the Exchange icon in the Studio taskbar.
. Click Login in Anypoint Exchange and supply your Anypoint Platform credentials.
. In the Exchange window, search for this connector, and click Install.
. Follow the prompts to install the connector.

=== To Update from an Older Version

When an updated version of a connector is released, Anypoint Studio displays the Updates Available popup in the bottom right corner of Studio. Click the popup and install the new version.

== To Configure with the Studio Visual Editor

. In Studio, click File > New > Mule Project.
. Search for "http" and drag the HTTP connector to the Studio Canvas. Click the HTTP connector, and click the green plus sign to the right of Connector Configuration. Click OK to accept the defaults. In the HTTP properties window, set the Path to `/mq/{messageId}`.
. Search for "mq" and drag the *Anypoint MQ* connector to the canvas. If you cannot find this connector, return to
<<To Install This Connector>> and ensure you installed the connector.
. Click the green plus sign to the right of Connector Configuration.
. In the Global Element Properties window:
.. In Anypoint Platform, click MQ > Client Apps:
.. Create a client app. 
.. Copy the Anypoint Platform > MQ > Client App > Client App ID value to Studio's Client ID field.
.. Copy the Client App > Client Secret value to Studio's Client Secret field. You can ignore the other settings to test your first connector.
+
If you want to set the remaining fields or tabs, see <<About Global Element Properties>>.
+
.. Click *OK*.
. Click the *Operation* field and specify an operation such as Publish or Consume.
. Specify the *Destination* as the name of the queue or message exchange that you set in Anypoint Platform.

For a list of configuration fields, see link:/mule-user-guide/v/3.8/anypoint-mq-connector-reference[Anypoint MQ Connector Reference].

=== About the Studio TLS/SSL and Proxy Tabs

The TSL/SSL and Proxy tabs share the same information as the
link:/mule-user-guide/v/3.8/http-connector[HTTP Connector].

=== About the Studio Prefetch Tab

Lets you set the number of messages to receive at once when asking for messages. The response can contain fewer messages than this number depending on the `Polling Time` (`pollingTime` in XML) setting.

When you subscribe a flow to an Anypoint MQ queue, the flow pool regularly polls the queue looking for messages. This operation can be very time consuming. In order to avoid delays, prefetch was introduced. This is a component placed between the flow and the Anypoint MQ queue that polls the queue regularly, but without processing the pooled messages. You can change these values depending on your site's performance and use case needs.

The Prefetch tab fields are:

[%header,cols="25s,75a"]
|===
|Value |Description
|Fetch Size |Number of messages to prefetch. *&#8224;*
|Fetch Timeout |Maximum duration in milliseconds to wait for the required amount of messages. When this time elapses, the response is sent with as many messages as taken during the period.
|Frequency |The duration in milliseconds to execute
the retrieve operation when the prefetch queue is not empty.
|===

*&#8224;* *Fetch Size Notes*: 

* For best performance, set `Fetch Size` to 10 (maximum value) and reduce `Frequency` to increase the polling time and the resulting dequeuing of transactions per second (TPS). You can increase `Fetch Timeout` if message processing is slow. For example, if processing takes 5 seconds, set the `Fetch Timeout` to at least double this time (10000 milliseconds). 
* If Fetch Size is greater than 1, multiple messages are requested at the same time. This has the effect of launching separate messages though the Mule flow, potentially concurrently, depending on the Mule worker thread configuration (see link:/mule-user-guide/v/3.8/tuning-performance[Tuning Performance] for thread configuration information). 
* Fetch Size does not guarantee messages process in parallel, some messages may, others do not.

Apart from these performance-related parameters, it is important to properly configure the xref:am[Acknowledgement Mode].

The equivalent XML for the Prefetch default values is:

[source,xml]
----
<anypoint-mq:prefetch fetchSize="10" fetchTimeout="1000" frequency="5000"/>
----

== About Basic Settings

[%header,cols="25s,75a"]
|===
|Studio Field |Description
|Operation |Operation that this connector instance performs.

Possible values:

* `publish` - Send a message to a queue or message exchange.
* `consume` - Consume a message from a queue.
* `ack` - Acknowledge a message, that is, accept a message and delete the message.
* `nack` - Negatively acknowledge a message, that is, do not accept a message and return the message to the queue.

*Required:* Yes +
*Default:* None
|===

== About Publisher Settings

[%header,cols="25s,75a"]
|===
|Studio Field |Description
|Destination |Queue or message exchange name.

*Required:* Yes +
*Default:* None
|Message ID |Optional ID of a message to publish. When publishing to FIFO queues,
if you specify a custom Message ID and the Message ID is the same on multiple messages, the
messages with the same Message ID cannot be redelivered. For applications such as those used in transactional use cases where messages need to be processed exactly once, Anypoint MQ supports exactly once delivery of messages when messages are published to FIFO queues. FIFO queues supports deduplication of messages. For example, if you retry sending a message with the same message ID within the 5-minute deduplication interval to a FIFO queue, Anypoint MQ guarantees the messages with the same message ID are retrieved and processed exactly once by the subscriber. When building applications requiring this feature on Anypoint Studio, you can set the message ID in publisher settings inside Anypoint MQ connector. If a message ID is not explicitly set, MQ auto generates a unique message ID for each message that's sent to a queue.

*Required:* No +
*Default:* None
|Send Outbound Properties |Send properties when publishing.

*Required:* Yes +
*Default:* Checked
|Send Content Type |Send content type when publishing.

*Required:* Yes +
*Default:* Checked
|Property |Optional property content to set for publish.

*Required:* No +
*Default:* None
|Value |Optional value content to set for publish.

*Required:* No +
*Default:* None
|===

== About Consumer Settings

[%header,cols="25s,75a"]
|===
|Studio Field |Description
|Destination |Queue name.

*Required:* Yes +
*Default:* None
|Acknowledgement Mode |If you use
the Anypoint MQ connector as a message processor, the operations are `MANUAL (default)` or `NONE`. If the MQ connector is used as an entry point, the mode options are `From configuration (Default)`, `AUTO`, `MANUAL`, or `NONE`. 
For more information,
see link:/anypoint-mq/mq-ack-mode[Anypoint MQ Acknowledgement Mode].  *Note:* This value overrides the *Acknowledgement Mode* field in the Global Elements Properties Basic Settings.

*Required:* No +
*Default:* MANUAL if connector is a message processor,
or From configuration if connector is an entry point
|Acknowledgement Timeout |Duration in milliseconds until the acknowledgement mode
times out. *Note:* This value overrides the *Acknowledgement Timeout* field in the Global Elements Properties Basic Settings.
|Polling Time |Duration in milliseconds that the MQ connector polls the queue or message exchange for messages. *Note:* This value overrides the *Polling Time* field in the Global Elements Properties Basic Settings. The default is 10000 milliseconds (10 seconds).
|Reconnection Wait Time |Duration in milliseconds for how long to wait before MQ attempts to re-establish a connection to the MQ backend server. The default is 3000 milliseconds (3 seconds).
|Reconnection Attempts |Number of times MQ should attempt to re-establish a connection to the MQ backend server. -1 means try forever.
|===

== About Subscriber Settings

[%header,cols="25s,75a"]
|===
|Studio Field |Description
|Destination |Queue name.

*Required:* Yes +
*Default:* None
|Acknowledgement Mode |When the MQ connector is used as an entry point, the mode options are `From configuration (Default)`, `AUTO`, `MANUAL`, or `NONE`. 

*Notes:* 

* This value overrides the *Acknowledgement Mode* field in the Global Elements Properties Basic Settings.
* The default value automatically ACKs every message sent to the destination queue.

*Required:* No +
*Default:* From configuration if connector is an entry point
|Acknowledgement Timeout |Duration in milliseconds until the acknowledgement mode
times out. *Note:* This value overrides the *Acknowledgement Timeout* field in the Global Elements Properties Basic Settings.
|Polling Time |Duration in milliseconds that the MQ connector polls a queue for messages. *Note:* This value overrides the Polling Time field in the Global Elements Properties Basic Settings.
|Reconnection Wait Time |Duration in milliseconds for how long to wait before MQ attempts to re-establish a connection to the MQ backend server. The default is 3000 milliseconds (3 seconds).
|Reconnection Attempts |Number of times MQ should attempt to re-establish a connection to the MQ backend server. -1 means try forever.
|===

== XML and Standalone Configuration

For a list of XML fields, see link:/mule-user-guide/v/3.8/anypoint-mq-connector-reference[Anypoint MQ Connector Reference].

== Anypoint MQ XML Examples

This section provides these topics:

* <<Example 1: MQ and DataWeave>>
* <<Example 2: MQ and Object Store>>
* <<About Common XML Elements>>

=== Example 1: MQ and DataWeave

The following example illustrates the use of the Anypoint MQ connector with DataWeave to transform
a Mule message to JSON:

[source,xml,linenums]
----
include::_sources/mq-studio.xml[]
----

=== Example 2: MQ and Object Store

The following example shows the use of the Anypoint MQ connector to consume
information from an object store.

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>

<mule xmlns:anypoint-mq="http://www.mulesoft.org/schema/mule/anypoint-mq"
    xmlns:objectstore="http://www.mulesoft.org/schema/mule/objectstore"
    xmlns:dw="http://www.mulesoft.org/schema/mule/ee/dw"
    xmlns:http="http://www.mulesoft.org/schema/mule/http"
    xmlns:tracking="http://www.mulesoft.org/schema/mule/ee/tracking"
    xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
    xmlns:spring="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/objectstore http://www.mulesoft.org/schema/mule/objectstore/current/mule-objectstore.xsd
http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
http://www.mulesoft.org/schema/mule/ee/dw http://www.mulesoft.org/schema/mule/ee/dw/current/dw.xsd
http://www.mulesoft.org/schema/mule/ee/tracking http://www.mulesoft.org/schema/mule/ee/tracking/current/mule-tracking-ee.xsd
http://www.mulesoft.org/schema/mule/anypoint-mq http://www.mulesoft.org/schema/mule/anypoint-mq/current/mule-anypoint-mq.xsd">

    <objectstore:config name="ObjectStore_Configuration" partition="employees" doc:name="ObjectStore: Configuration"/>
    <http:listener-config name="HTTP_Listener_Configuration" host="0.0.0.0" port="8081" doc:name="HTTP Listener Configuration"/>
    <anypoint-mq:config name="Anypoint_MQ_Configuration" doc:name="Anypoint MQ Configuration">
        <anypoint-mq:provider url="https://mq-us-east-1.anypoint.mulesoft.com/api/v1" clientId="<ID>" clientSecret="<SECRET>"/>
    </anypoint-mq:config>
    <flow name="objectstore-store-flow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/store" doc:name="HTTP"/>
        <objectstore:store config-ref="ObjectStore_Configuration" key="#[message.inboundProperties.'http.query.params'.key]" value-ref="#[message.inboundProperties.'http.query.params'.value]" doc:name="ObjectStore"/>
        <anypoint-mq:consume config-ref="Anypoint_MQ_Configuration" destination="MyDemoQueue" doc:name="Anypoint MQ"/>
        <set-payload value= "OK" doc:name="Set Payload"/>
    </flow>
    <flow name="objectstore-retrieve-employee-flow">
        <http:listener config-ref="HTTP_Listener_Configuration" path="/retrieve" doc:name="HTTP"/>
        <objectstore:retrieve config-ref="ObjectStore_Configuration" key="#[message.inboundProperties.'http.query.params'.key]" doc:name="Retrieve"/>
        <logger message="Value: #[payload]" level="INFO" doc:name="Log"/>
        <set-payload value="Value : #[payload]" doc:name="Show"/>
    </flow>
</mule>
----


== See Also

* link:/mule-user-guide/v/3.8/anypoint-mq-connector-reference[Anypoint MQ Connector Reference]
* link:/anypoint-mq/[Anypoint MQ Documentation]
