= About the Cassandra Connector
:keywords: connectors, anypoint, studio, esb, cassandra, databases
:imagesdir: _images
:icons: font
:toc: macro
:toclevels: 2


The Anypoint Connector for Apache Cassandra connects Mule applications to an Apache Cassandra database or cluster for accessing data. The Cassandra Connector is in the Select support category described in "Connector Categories." You can download the Cassandra Connector from Anypoint Exchange:

`+https://www.mulesoft.com/exchange+`

== Prerequisites

* Cassandra database or cluster 1.2 or later
* CQL spec 3.x
* MuleSoft software: Anypoint Studio/Mule Runtime 3.5 or later
* Configure Cassandra as described in this software and restart.
* Configure the Cassandra Connector as described in this document.

== Supported Data Types

The operations of the connector support the following CQL primitive data types only:

[frame=none]
|===
| ascii | boolean | double | inet | timestamp | varchar 
| bigint | counter | float | int | timeuuid | varint 
| blob | decimal | frozen | text | uuid |  
|===

The connector maps the primitive data types using uppercase. You need to specify data types in one of the following ways:

* Use uppercase for names of data types
* Use a transformer to map the type to uppercase:

----
{
 "columns": payload.columns map {
  name: $.name,
  primaryKey: $.primaryKey,
  type: upper $.type
 }
----

== Unsupported Data Types

The Cassandra connector does not support the following CQL data types:

* list
* map
* set
* tuple

To create a table with columns of unsupported CQL types, or to add a new column of a complex type to an existing table, use the Execute CQL operation.


== See Also

link:/mule-user-guide/v/3.8/anypoint-connectors#connector-categories[Select support policy]