= Configuring Mule as a Windows NT Service
:keywords: anypoint, on premises, on premise, windows

[NOTE]
In Mule 3.8.0, the Tanuki wrapper was upgraded to a newer version, implying a change to the certificate by which the wrapper is signed. See link:/release-notes/mule-3.8.0-release-notes#enterprise-edition-library-changes[Mule 3.8.0 release notes concerning Tanuki Wrapper upgrade] for details on resolving compatibility issues.

If you want to install Mule as a Windows NT Service, type

[source]
----
mule install
----

Likewise, to remove Mule from your services, type:

[source]
----
mule remove
----

Once you have installed Mule as a service, you can invoke the service exactly as you did before, but with an additional parameter:

[source]
----
mule [start|stop|restart]
----

You can also use the Windows `net` utility:

[source]
----
net [start|stop] mule
----

== Adding Properties to wrapper.conf File After Installation

Properties that are defined after the installation of the Mule as a Windows service 
in the `wrapper.conf` file can be overridden by properties generated in the `wrapper.additional.conf` file.

There are different behaviors for:

* <<Mule Community Edition Properties>>
* <<Mule Enterprise Edition Properties>>

=== Mule Community Edition Properties

In Mule CE:

. After adding a new property, reinstall or restart the Windows Service. 
. Add the property and ensure that its index is greater than the greatest index in the `wrapper-additional.conf` file. Otherwise, your property can be overidden.
+
For example if the wrapper-additional.conf has the property:
+
`wrapper.java.additional.n=-Dproperty=value`
+
When n is the greatest index, you should add your property in the `wrapper.conf` file incrementing the index:
+
`wrapper.java.additional.n+1=-DyourProperty=valueOfYourProperty`

=== Mule Enterprise Edition Properties

In Mule EE:

. By default, you can add  20 extra properties after installing Mule as a Service.
. Configure the number of extra properties you need, using the following command line argument 
when you install the service:
+
`-additionalJavaProperties=numberOfExtraProperties`
