= Hardware and Software Requirements
:keywords: mule, requirements, os, jdk, installation, jre

Find below the hardware and software requirements for running Mule runtime, Anypoint Platform and several other complementary MuleSoft products. As this list is not comprehensive, see individual product release notes from the link:/release-notes/[Release Notes directory] for the latest versions of dependencies tested for any MuleSoft product release.

[TIP]
For hardware and software requirements for Anypoint Studio, MuleSoft's IDE for building integration applications, see link:/anypoint-studio/v/6/hardware-and-software-requirements[Anypoint Studio Hardware and Software Requirements].


== Mule Runtime Hardware Requirements

This hardware requirements list is a recommendation and a starting point. Different applications have different requirements for the amount of latency (and thus raw CPU power) or the size and number of simultaneous messages that applications need to process (which in turn determines the amount of RAM Mule needs).

* 2GHz CPU or 1 virtual CPU in virtualized environments
* 1GB of RAM
* 4GB of storage

== Mule Runtime Software Requirements

The only mandatory requirement for Mule is Java. Mule should also run on any later versions of the tested operating systems, as well as any other operating systems supported by the JREs. See link:/release-notes/mule-esb[Mule Release Notes] for the latest changes to Mule.

NOTE: After installing a JRE or JDK, install the link:http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8] or link:http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[JCE 7] unlimited strength jurisdiction policy files.

=== Supported Java Versions

* Oracle link:http://www.oracle.com/technetwork/java/javase/overview/index.html[JRE 1.8]
* Oracle link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7.0] (recommended: link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7.0_79/80])
* Oracle JDK 8
* Oracle JDK 7
* IBM JRE 1.8
* IBM JRE 1.7
* OpenJDK 8

=== Supported Operating Systems

* Apple Mac OS 10.10
* Apple Mac OS 10.9
* IBM AIX
* IBM AIX 7.1
* Linux Debian - *Note:* Not tested in house
* Linux SUSE - *Note:* Not tested in house
* Linux Red Hat RHEL 7
* Linux Red Hat RHEL 6.6
* Linux Red Hat RHEL 5.11
* Linux Red Hat RHEL 5.8
* Linux Ubuntu 16.04
* Linux Ubuntu 15.04
* Linux Ubuntu 14.04
* Linux Ubuntu Server 12.04.2
* Linux Ubuntu Server 11.04 (64bit)
* Microsoft Windows 8.1
* Microsoft Windows 7
* Microsoft Windows Server 2012 R2
* Microsoft Windows Server 2008
* Microsoft Windows Server 2003
* Oracle Solaris 11 (Solaris Sparc and Solaris Intel)


=== Supported Application Servers

* Apache Tomcat 7
* Eclipse Jetty 8
* Geronimo - *Note:* not tested in house
* IBM WebSphere 8
* JBoss 6.1EE
* Oracle WebLogic 12c
* Tcat Server
* Wildfly 8


=== Supported Database Servers

* Apache Derby 10.9.1.0
* IBM DB2 10.1
* Microsoft SQL Server 2012
* MySQL 5.5
* Oracle 12c
* Oracle Database11g
* PostgreSQL 9.6


== Anypoint Platform Browser Requirements

Anypoint Platform browser tools are tested and supported on these internet browsers (minimum screen resolution of 1024x768):

* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 10 or newer


[NOTE]
Anypoint Platform comprises various tools whose release notes you can access easily from the link:/release-notes/[Release Notes directory].If planning to host Anypoint Platform in your datacenters see link:/anypoint-platform-on-premises/v/1.5.0/prerequisites-platform-on-premises[the on-prem requirements].

== API Gateway Runtime 2.x and 1.3.x

Mule 3.8.0 unifies the API Gateway runtime with the core Mule runtime, simplifying
development and operations. Mule continues to support and document API Gateway 2.x and 1.3.x for customers who do not plan to upgrade immediately.

The following requirements pertain to API Gateway Runtime 2.x and 1.3.x.

NOTE: After installing a JRE or JDK, install the link:http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8] or link:http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[JCE 7] unlimited strength jurisdiction policy files.

=== API Gateway Runtime Hardware Requirements

* 2GHz, dual-core CPU, or 2 virtual CPUs in virtualized environments
* 2GB of RAM
* 4GB of storage

This hardware requirements list is a recommendation and a starting point. Different applications have different requirements for the amount of latency (and thus raw CPU power) or the size and number of simultaneous messages that applications need to process (which in turn determines the amount of RAM Mule needs).

=== API Gateway Runtime Software Requirements

*Java Runtime Environments:*

* API Gateway Runtime 1.3.n and older: Oracle link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7]
* API Gateway Runtime 2.x:
** Oracle link:http://www.oracle.com/technetwork/java/javase/overview/index.html[JRE 1.8]
** JRE 1.7.0 (recommended: link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[JRE 1.7.0_79/80])
** IBM version 1.7

Because the only mandatory requirement for the API Gateway Runtime is Java, the API Gateway should also run on any later versions of the tested operating systems in the above list, as well as any other operating systems supported by the JRE.

=== Supported Operating Systems

API Gateway Runtime *2.x* validates against the following operating systems:

* Mac OS 10.10.0
* HP-UX 11i V3
* IBM AIX 7.1
* Microsoft Windows 2012 R2 Server
* Microsoft Windows 8.1
* Solaris 11.2
* RHEL 7
* Ubuntu Server 14.0.4

API Gateway Runtime *1.3.n and older* validates against the following operating systems:

* Microsoft Windows (32- and 64-bit) 2003, 2008, Windows 7, Windows 2012
* Mac OS 10.7, 10.8
* Linux RHEL (64-bit) 5.3, 6.1
* Ubuntu Server 12.04 (64-bit) - If you use SSL, MuleSoft recommends installing Ubuntu Server 12.14 (64-bit) and newer instead of 12.04.
* Solaris OS 10
* HP-UX 11i V3
* AIX V7.1



== Anypoint Connector DevKit Requirements

Any version of Anypoint Connector DevKit from 3.5 and newer is compatible with
all Mule versions 3.5 and newer. DevKit version numbering
does not correspond to Mule versions. DevKit 3.9 is
compatible with Mule versions 3.5, 3.6, 3.7, and 3.8.

We recommend using the latest version of Mule with DevKit to get the
latest fixes and improvements.

See link:/release-notes/anypoint-connector-devkit-release-notes[Anypoint Connector DevKit Release Notes] for the latest changes.

== Mule Management Console (MMC)

See link:/release-notes/mule-management-console-3.8.1[Mule Management Console 3.8.1] release notes for the latest changes to this software.

NOTE: After installing a JRE or JDK, install the link:http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8] or link:http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[JCE 7] unlimited strength jurisdiction policy files.

=== Hardware Requirements

We strongly recommend running MMC on a separate server from the hardware that runs Mule Runtime.

* 2GHz CPU
* 4 GB of RAM
* 10 GB of storage

=== Software Requirements

*Java Runtime Environments:*

* Oracle link:http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jre-7u80-oth-JPR[Java 1.7] and Oracle link:http://www.oracle.com/technetwork/java/javase/overview/index.html[Java 1.8]

*Web Application Servers:*

* JBoss 6 or 6.1
* Apache Tomcat 6.x or 7.x
* WebSphere Application Server 7.0 and 8.0
* Oracle Weblogic 12.1.x (in MMC 3.7.3 and newer)

*Operating Systems:*

MMC runs the operating systems supported by the above web application servers.

*Browsers:*

* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 10 or newer
* Minimum screen resolution of 1024x768


=== Compatible Databases for Persisting Data

* link:/mule-management-console/v/3.8/persisting-mmc-data-to-oracle[Oracle]
* link:/mule-management-console/v/3.8/persisting-mmc-data-to-postgresql[Postgres]
* link:/mule-management-console/v/3.8/persisting-mmc-data-to-mysql[MySQL]
* link:/mule-management-console/v/3.8/persisting-mmc-data-to-ms-sql-server[MS SQL Server]

=== Run MMC as a Web Application

Mule Management Console should be run as a web application deployed on a web container such as JBoss or Tomcat, and NOT as a Mule application. We recommend configuring the web application server's memory areas with the following minimum sizes:

*  Heap: 2GB (3GB recommended) 
*  Permanent Generation: 512MB


== See Also

* Learn how to link:/mule-user-guide/v/3.8/downloading-and-starting-mule-esb[download, install, and launch] Mule.
* Learn more about installing an link:/mule-user-guide/v/3.8/installing-an-enterprise-license[Enterprise license].
* link:/getting-started[Get started] with Anypoint Platform.
* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:https://www.mulesoft.com/platform/studio[Download Anypoint Studio]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
