= Hardware and Software Requirements
:keywords: mule, requirements, jdk, installation, jre

You need to meet these general hardware and software requirements to set up Mule Runtime and use Anypoint Platform. Included at the end of this section are requirements for the Anypoint Connector DevKit. link:/release-notes/[Individual release notes] for complementary MuleSoft Products describe other requirements if there are any. 

This section does not include requirements for running the following products:

* Anypoint Platform On-premises Edition
+
See link:/anypoint-platform-on-premises/v/1.5.0/prerequisites-platform-on-premises[On-premises documentation].
+
* API Gateway Runtime 2.x
+
Mule 3.8.0 and later incorporate API Gateway. To install API Gateway for an earlier Mule version, see requirements in link:/api-manager/api-gateway-runtime-archive[API Gateway Runtime--Archive].

== Mule Runtime Hardware Requirements

The minimum hardware required to run Mule Runtime depends on the application. For example, key factors in determining the RAM you need include the acceptable latency and the size and number of simultaneous messages that applications need to process. The following hardware is the recommended minimum:

* 2GHz CPU or 1 virtual CPU in virtualized environments
* 1GB of RAM
* 4GB of storage

== Mule Runtime Software Requirements

Software requirements are:

* Java
+
The next section lists currently supported versions of Java versions. link:/release-notes/mule-esb[Mule Release Notes] lists the Java requirements for previous Mule releases. 
+
* An operating system that supports the Java versions listed in link:/mule-user-guide/v/3.8/hardware-and-software-requirements#supported-java-versions[supported Java version]
+
link:/mule-user-guide/v/3.8/supported-sw-and-systems#supported-operating-systems[Supported Operating Systems] lists operating systems that MuleSoft tests for use with Mule. 
+
* For Microsoft Dynamics GP connector use, link:http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8] or link:http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html[JCE 7] unlimited strength jurisdiction policy files
+
If you do not use this connector, you do not need JCE. Install a JRE or JDK first, then install JCE.

=== Supported Java Versions

* Oracle JDK, JRE 1.8.0 (JRE 1.8.0_91/92 recommended)
* Oracle JDK, JRE 1.7.0
* IBM JRE 1.8
* IBM JRE 1.7
* OpenJDK 8


== Anypoint Connector DevKit Requirements

Anypoint Connector DevKit 3.5 and later is compatible with
Mule versions 3.5 and later. DevKit version numbering
does not correspond to Mule versions. DevKit 3.9 is
compatible with Mule versions 3.5, 3.6, 3.7, and 3.8.

To take advantage of the latest fixes and improvements, use the current version of Mule with its corresponding DevKit.
latest fixes and improvements.

See link:/release-notes/anypoint-connector-devkit-release-notes[Anypoint Connector DevKit Release Notes] for the latest changes.
