= HTTP Connector
:keywords: anypoint studio, esb, connectors, http, https, http headers, query parameters, rest, raml

Using the HTTP or HTTPS protocol, the HTTP connector performs one of the following operations:

* Listener
+
Starts executing the Mule flow upon receiving a message from a source.
+
* Request
+
Consumes a web service.
+
* Basic security filter
* Load a static resource

From Mule Palette, you drag and drop an HTTP connector to a new flow. An error state occurs until you configure the host, port, and path. You can quickly configure an app to consume a web service using the two HTTP connector instances as follows:

* Listener configuration: Path = */somepath*, for example
* Request configuration: Path Or URL = the URL of the web service you want to consume

You run the app and enter the URL ending in `/somepath` in the browser. The listener detects the request, and the flow executes.

You can configure the HTTP connector to send or receive *HTTPS* requests using Transport Level Security (TLS) encryption.

== See Also

* 
