= About the HTTP Connector
:keywords: anypoint studio, esb, connectors, http, https, http headers, query parameters, rest, raml

Using the HTTP or HTTPS protocol, the HTTP connector performs one of the following operations:

* Listener
+
Starts executing the Mule flow upon receiving a message from a source.
+
* Request
+
Consumes a web service.
+
* Basic security filter
+
Secures and authenticates requests to your service.
+
* Load static resource
+
Brings a resource, such as a script, from the file system into your app.

You can configure the HTTP connector to send or receive *HTTPS* requests using Transport Level Security (TLS) encryption. A TLS/SSL configuration that includes a trust store implicitly requires client authentication. Implement two-way TLS by including both a trust store and a key store. If you're using a 2-way TLS authenticated connection, the client certificate is exposed using the attribute `http.client.cert`. You can access the client principal through: `attributes['http.client.cert'].getSubjectDN()`.

// Check ^ kris 7/9/2017

== HTTP Operations

From Mule Palette, you drag and drop an HTTP connector to a new flow. An error state occurs until you configure the host, port, and path. In a new flow, the connector resides on the source side of a flow and peforms a listen operation. Drag an HTTP connector to the process side of a flow to perform one of the other HTTP connector operations.

You can quickly configure an app to consume a web service using the two HTTP connector instances:

* Listener configuration: Path = */somepath*, for example
* Request configuration: Path Or URL = the URL of the web service you want to consume

You run the app and enter the URL ending in */somepath* in the browser. The listener hears the request, and the flow executes.

To authenticate requests to your service, put a listener followed by a basic security filter into a flow. To load a resource, put a listener followed by a load static resource into the flow. Specify the path to and name of the resource.  In case of loading failure, you also set the name of a file in the same directory as the resource to use as a backup. 


== See Also

* 
