= Mule User Guide
:keywords: mule, getting started, transform, message, payload

This guide offers information about how to use link:https://www.mulesoft.org/what-mule-esb[Mule Runtime], commonly called *Mule*, or *Mule ESB* link:/anypoint-studio/v/6/[Anypoint Studio] to integrate systems, orchestrate Web services, or connect any system with another. The visual representations of Mule flows you see throughout are usually taken within the Anypoint Studio IDE.

Integration developers write Mule applications to process inbound information in a pre-defined manner. A proper request to a Mule application typically triggers a process that creates, transforms and routes the Mule message to its destination in the format expected by the recipient. 

The Mule application is defined in an XML document that specifies the necessary dependencies for the Mule application to run. You can configure your Mule application in a variety of ways. Mule is packaged with components, connectors, and transformers that work quickly to get the data and metadata you need from your Mule application, and feed it to any destination.

== Learn the Development Tools

Check out the link:/mule-user-guide/v/3.8/developing[Developing] section to see what you can do to develop Mule applications on Mule runtime.

Use the navigation tree at left to access other sections and learn more about Mule features and projects.

* link:/mule-user-guide/v/3.8/installing[Installing Mule Runtime]
* link:/mule-user-guide/v/3.8/developing[Developing on Mule Runtime]
* link:/mule-user-guide/v/3.8/securing[Securing Mule Applications]
* link:/mule-user-guide/v/3.8/debugging[Debugging Mule Applications]
* link:/mule-user-guide/v/3.8/testing[Testing Mule Applications]
* link:/mule-user-guide/v/3.8/deploying[Deploying Mule Applications]
* link:/mule-user-guide/v/3.8/extending[Extending Mule]
* link:/mule-user-guide/v/3.8/reference[Reference]

== See Also

* link:/mule-user-guide/v/3.8/installing[Install and Run Mule]
* link:/mule-fundamentals/v/3.8/first-30-minutes-with-mule[Start Using Anypoint Studio] 
* link:/mule-management-console/v/3.8/setting-up-mmc[Set up the Mule Management Console]
* link:/runtime-manager/cloudhub[Run Mule Applications on CloudHub]
* link:/anypoint-connector-devkit/v/3.8[Extend Mule with DevKit]
* link:https://www.mulesoft.com/webinars/api/mule-101-anypoint-platform-overview[Watch the Mule 101 Webinar to learn the basic Mule concepts]
* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
