= Mule User Guide

This section offers information about how to use link:https://www.mulesoft.org/what-mule-esb[Mule Runtime], commonly called *Mule*, or *Mule ESB* link:/anypoint-studio/v/6/[Anypoint Studio] to integrate systems, orchestrate Web services, or connect anything to anything. The visual representations of Mule flows you see throughout are usually taken within the Anypoint Studio IDE.

Mule is an architectural model that allows you to run applications or services based on a highly customizable configuration - we refer to these services or applications as Mule applications. You can configure your Mule application to accept data from inbound endpoints, transform it, and route it to appropriate destinations via outbound endpoints. The Mule universe is full of components, connectors, and transformers that work quickly to get you what you want out of your data and send it reliably. The data that flows through a service is packaged in a "payload", which is part of a larger "envelope" called a Mule message, where the message context is stored.

Check out the link:/mule-user-guide/v/3.8/developing[Developing] section to see what you can do to develop Mule applications on Mule runtime.

Use the navigation tree at left to access other sections and learn more about Mule features and projects.

* link:/mule-user-guide/v/3.8/installing[Installing Mule Runtime]
* link:/mule-user-guide/v/3.8/developing[Developing on Mule Runtime]
* link:/mule-user-guide/v/3.8/securing[Securing Mule Applications]
* link:/mule-user-guide/v/3.8/debugging[Debugging Mule Applications]
* link:/mule-user-guide/v/3.8/testing[Testing Mule Applications]
* link:/mule-user-guide/v/3.8/deploying[Deploying Mule Applications]
* link:/mule-user-guide/v/3.8/extending[Extending Mule]
* link:/mule-user-guide/v/3.8/reference[Reference]

== See Also

* link:/mule-user-guide/v/3.8/installing[Install and Run Mule]
* link:/mule-fundamentals/v/3.8/first-30-minutes-with-mule[Start Using Anypoint Studio] 
* link:/mule-management-console/v/3.8/setting-up-mmc[Set up the Mule Management Console]
* link:/runtime-manager/cloudhub[Run Mule Applications on CloudHub]
* link:/anypoint-connector-devkit/v/3.8[Extend Mule with DevKit]
* link:https://www.mulesoft.com/webinars/api/mule-101-anypoint-platform-overview[Watch the Mule 101 Webinar to learn the basic Mule concepts]
* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
