= Mongo DB Connector API Reference

:toc:               left
:toc-title:         Connector Summary
:toclevels:         2
:last-update-label!:
:docinfo:
:source-highlighter: coderay
:icons: font

+++
MongoDB is an open source, high-performance, schema-free, document-oriented database that manages collections of BSON documents.
+++

*Additional Info*

[width="50", cols=".<60%,^40%" ]
|===
| Requires Mule Enterprise License |  Yes icon:star[]  {nbsp}
| Requires Entitlement |  No icon:remove[]  {nbsp}
| Mule Version | 3.6.0 or higher
|===

---

== Configs

=== Configuration

`<mongo:config>`

`Connection Management`

==== Attributes

[%header%autowidth.spread]
|===
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| username | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The username to use for authentication.+++ |   | {nbsp}
| password | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The password to use for authentication. If the password is null or whitespaces only, the connector won't use authentication and username must be empty too.+++ |   | {nbsp}
| database | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++Name of the database+++ |   | *x*{nbsp}
| host | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++A list of MongoDB instance, with the format <code>host:port</code>, separated by commas.
<p>
<pre>
Example: 127.0.0.1:27017, 192.168.1.2:27017
</pre>+++ |  localhost:27017 | {nbsp}
| connectionsPerHost | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The number of connections allowed per host (the pool size, per host)+++ |   | {nbsp}
| threadsAllowedToBlockForConnectionMultiplier | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Multiplier for connectionsPerHost for # of threads that can block.+++ |   | {nbsp}
| maxWaitTime | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The max wait time for a blocking thread for a connection from the pool in ms.+++ |   | {nbsp}
| connectTimeout | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The connection timeout in milliseconds; this is for establishing the socket connections (open). 0 is default and infinite.+++ |  30000 | {nbsp}
| socketTimeout | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The socket timeout. 0 is default and infinite.+++ |   | {nbsp}
| ssl | +++boolean+++ | +++This is for enabling an SSL connection. It is disabled by default.+++ |  false | {nbsp}
| authenticationDatabase | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | ++++++ |   | {nbsp}
|===

---

=== Connection String

`<mongo:config-connection-string>`

`Connection Management`

==== Attributes

[%header%autowidth.spread]
|===
| Name | Java Type | Description | Default Value | Required
|name | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | The name of this configuration. With this name can be later referenced. | | *x*{nbsp}
| connectionString | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | ++++++ |   | *x*{nbsp}
|===

---

== Processors


=== Add User

`<mongo:add-user>`

+++
Adds a new user for this db
+++

==== XML Sample

[source,xml]
----
<mongo:add-user config-ref="Mongo_DB__Configuration" newUsername="myUser" newPassword="myPassword"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
newUsername  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++Name of the user+++ |  | *x*{nbsp}
|
newPassword  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++Password that is used for authentication+++ |  | *x*{nbsp}
|===

---

==== Returns
[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++Result of the operation+++
|===

---

=== Drop Database

`<mongo:drop-database>`

+++
Drop the current database
+++

==== XML Sample

[source,xml]
----
<mongo:drop-database config-ref="Mongo_DB__Configuration"/>
----

==== Attributes
[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|===

---

=== List Collections

`<mongo:list-collections>`

+++
Lists names of collections available at this database
+++

==== XML Sample

[source,xml]
----
<mongo:list-collections config-ref="Mongo_DB__Configuration"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|===

---

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html">Iterable</a><<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>>+++ | +++The list of names of collections available at this database+++
|===

---

=== Exists Collection

`<mongo:exists-collection>`

+++
Answers if a collection exists given its name
+++

==== XML Sample

[source,xml]
----
<mongo:exists-collection config-ref="Mongo_DB__Configuration" collection="aColllection"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection icon:envelope[] | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection+++ | &#x0023;[payload] | {nbsp}
|===

---

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++boolean+++ | +++If the collection exists+++
|===

---

=== Drop Collection

`<mongo:drop-collection>`.

+++
Deletes a collection and all the objects it contains. If the collection does not exist, does nothing.
+++

==== XML Sample
[source,xml]
----
<mongo:drop-collection config-ref="Mongo_DB__Configuration" collection="aCollection"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection icon:envelope[] | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection to drop+++ | &#x0023;[payload] | {nbsp}
|===

---

=== Create Collection

`<mongo:create-collection>`

+++
Creates a new collection. If the collection already exists, a MongoException is thrown.
+++

==== XML Sample

[source,xml]
----
<mongo:create-collection config-ref="Mongo_DB__Configuration" collection="aCollection" capped="true"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection to create+++ |  | *x*{nbsp}
|
capped  | +++boolean+++ | +++If the collection is capped+++ | false | {nbsp}
|
maxObjects  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The maximum number of documents the new collection is able to contain+++ |  | {nbsp}
|
size  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++The maximum size of the new collection+++ |  | {nbsp}
|===

---

=== Insert Document

`<mongo:insert-document>`

+++
Inserts a document in a collection, setting its ID if necessary.
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:insert-document config-ref="Mongo_DB__Configuration" collection="Employees">
</mongo:insert-document>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection where to insert the given document.+++ |  | *x*{nbsp}
|
document icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> instance.+++ | &#x0023;[payload] | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The id that was just inserted+++
|===

---

=== Insert Documents

`<mongo:insert-documents>`

+++
Inserts a list of documents in a collection, setting its id if necessary.
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:insert-documents config-ref="Mongo_DB__Configuration" collection="Employees">
</mongo:insert-documents>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection where to insert the given document.+++ |  | *x*{nbsp}
|
documents icon:envelope[] | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/util/List.html">List</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++a <a href="http://docs.oracle.com/javase/8/docs/api/java/util/List.html">List</a> of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>.+++ | &#x0023;[payload] | {nbsp}
|
ordered  | +++boolean+++ | +++Indicates if the list of write operations is ordered or unordered. By default, if an error occurs during the processing of one of the write operations, MongoDB returns without processing any remaining write operations in the list.+++ | true | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the operation result+++
|===

---

=== Update Documents

`<mongo:update-documents>`

+++
Updates documents that matches the given query. If a query is not specified, all documents are retrieved. If the `multi` parameter is set to false, only the first document matching
it is updated. Otherwise, all the documents matching it are updated.
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:update-documents config-ref="Mongo_DB__Configuration" collection="myCollection" query-ref="#[payload]">
</mongo:update-documents>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection to update+++ |  | *x*{nbsp}
|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query object used to detect the element to update.+++ |  | {nbsp}
|
element icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory object that replaces that one which matches the query.+++ | &#x0023;[payload] | {nbsp}
|
multi  | +++boolean+++ | +++If all or just the first document matching the query is updated+++ | true | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++A <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the update status+++
|===

---

=== Update Documents by Function

`<mongo:update-documents-by-function>`

+++
Update documents using a Mongo function. If query is not specified, all documents are retrieved.
<p/>
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:update-documents-by-function config-ref="Mongo_DB__Configuration" 
  collection="myCollection" element-ref="#[payload]" upsert="true" function="$set">
</mongo:update-documents-by-function>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection to update+++ |  | *x*{nbsp}
|
function  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The function used to execute the update+++ |  | *x*{nbsp}
|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document used to detect the element to update.+++ |  | {nbsp}
|
element icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory document that replaces that one which matches the query.+++ | &#x0023;[payload] | {nbsp}
|
upsert  | +++boolean+++ | +++If the database should create the element if it does not exist.+++ | false | {nbsp}
|
multi  | +++boolean+++ | +++If all or just the first document matching the query is updated.+++ | true | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++A <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the update status.+++
|===

---

=== Update Documents by Functions

`<mongo:update-documents-by-functions>`

+++
Update documents using one or more Mongo function(s). If query is not specified, all documents are retrieved. If there are duplicated operators, only the last one executes.
+++

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection to update+++ |  | *x*{nbsp}
|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document used to detect the element to update+++ |  | {nbsp}
|
functions icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> of functions used to execute the update. for example, <$set,{"key":123}>+++ | &#x0023;[payload] | {nbsp}
|
upsert  | +++boolean+++ | +++Whether the database should create the element if it does not exist+++ | false | {nbsp}
|
multi  | +++boolean+++ | +++If all or just the first document matching the query is updated+++ | true | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with the update status.+++
|===

---

=== Save Document

`<mongo:save-document>`

+++
Inserts or updates a document based on its object ID.
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:save-document config-ref="Mongo_DB__Configuration" collection="myCollection">
</mongo:save-document>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The collection where to insert the object+++ |  | *x*{nbsp}
|
document icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The mandatory <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> document to insert.+++ | &#x0023;[payload] | {nbsp}
|===

---

=== Remove Documents

`<mongo:remove-documents>`

+++
Removes all the documents that match the a given optional query. If query is not specified, all documents are removed. However, note that this is normally less performant than dropping the collection and creating it and its indices again.
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:remove-documents config-ref="Mongo_DB__Configuration" collection="myCollection">
</mongo:remove-documents>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The collection whose elements to remove+++ |  | *x*{nbsp}
|
query icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query object. Documents that match it are removed.+++ | &#x0023;[payload] | {nbsp}
|===

---

=== Map Reduce Objects

`<mongo:map-reduce-objects>`

+++
Transforms a collection into a collection of aggregated groups, by applying a supplied element-mapping function to each element, that transforms each one into a key-value
pair, grouping the resulting pairs by key, and finally reducing values in each group applying a suppling 'reduce' function.

Each supplied function is coded in JavaScript.

Note that the correct way of writing those functions may not be obvious; consult MongoDB documentation for writing them.
+++

==== XML Sample

[source,xml]
----
<mongo:map-reduce-objects config-ref="Mongo_DB__Configuration" collection="myCollection" mapFunction="myMapFunction" reduceFunction="myReduceFunction"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection to map and reduce+++ |  | *x*{nbsp}
|
mapFunction  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++A JavaScript encoded mapping function+++ |  | *x*{nbsp}
|
reduceFunction  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++A JavaScript encoded reducing function+++ |  | *x*{nbsp}
|
outputCollection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the output collection to write the results, replacing previous collection if existed, mandatory when results may be larger than 16 MB. If outputCollection is unspecified, the computation is performed in-memory and not persisted.+++ |  | {nbsp}

|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++an iterable that retrieves the resulting collection of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++
|===

---

=== Count Documents

`<mongo:count-documents>`

+++
Counts the number of documents that match the given query. If no query is passed, returns the number of elements in the collection
+++

==== XML Sample

[source,xml]
----
<mongo:count-documents config-ref="Mongo_DB__Configuration" collection="myCollection" query-ref="dbObject"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The target collection+++ |  | *x*{nbsp}
|
query icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/conversions/Bson.html">Bson</a>+++ | +++The optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query for counting documents. Only documents matching it are counted. If unspecified, all documents are counted.+++ | &#x0023;[payload] | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++long+++ | +++The amount of documents that matches the query+++
|===

---

=== Find Documents

`<mongo:find-documents>`

+++
Finds all documents that match a given query. If no query is specified, all documents of the collection are retrieved. If no fields object is specified, all fields are retrieved.
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:find-documents config-ref="Mongo_DB__Configuration" collection="myCollection" 
  limit="5" numToSkip="10" query-ref="#[payload]" sortBy-ref="#[new org.bson.Document()]">
  <mongo:fields>
    <mongo:field>field1</mongo:field>
    <mongo:field>field2</mongo:field>
  </mongo:fields>
</mongo:find-documents>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The target collection+++ |  | *x*{nbsp}
|
query icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document. If unspecified, all documents are returned.+++ | &#x0023;[payload] | {nbsp}
|
fields  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>>+++ | +++Alternative way of passing fields as a literal List+++ |  | {nbsp}
|
numToSkip  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Number of documents skip (offset)+++ |  | {nbsp}
|
limit  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html">Integer</a>+++ | +++Limit of documents to return+++ |  | {nbsp}
|
sortBy  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++Indicates the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> used to sort the results+++ |  | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++An iterable of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++
|===

---

=== Find One Document

`<mongo:find-one-document>`

+++
Finds the first document that matches a given query. Throws a MongoException if no one matches the given query.
+++

==== XML Sample

[source,xml,linenums]
----
<mongo:find-one-document config-ref="Mongo_DB__Configuration" collection="myCollection">
  <mongo:fields>
    <mongo:field>field1</mongo:field>
    <mongo:field>field2</mongo:field>
  </mongo:fields>
</mongo:find-one-document>
----



==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The target collection+++ |  | *x*{nbsp}
|
query icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The mandatory <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query document that the returned object matches.+++ | &#x0023;[payload] | {nbsp}
|
fields  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>>+++ | +++alternative way of passing fields as a literal List+++ |  | {nbsp}
|
failOnNotFound  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Flag to specify if an exception is thrown when no object is found. For backward compatibility the default value is true.+++ | true | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> that matches the query. If nothing matches and the failOnNotFound is set to false, null is returned+++
|===

---

=== Find One and Update Document

`<mongo:find-one-and-update-document>`

+++
Finds and update the first document that matches a given query. When returnNew = true, returns the updated document instead of the original document.
+++


==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The target collection+++ |  | *x*{nbsp}
|
query  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query that the returned object matches.+++ |  | {nbsp}
|
element icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory object that replaces that one which matches the query+++ | &#x0023;[payload] | {nbsp}
|
fields  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/util/List.html">List</a><<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>>+++ | +++alternative way of passing fields as a literal List+++ |  | {nbsp}
|
returnNewDocument  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Boolean.html">Boolean</a>+++ | +++Flag to specify if the returning <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> should be the updated document instead of the original. Defaults to false, returning the document before modifications+++ | false | {nbsp}
|
sortBy  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++indicates the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> used to sort the results.+++ |  | {nbsp}
|
remove  | +++boolean+++ | +++removes the <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> specified in the query field. Defaults to false+++ | false | {nbsp}
|
upsert  | +++boolean+++ | +++whether the database should create the element if it does not exist+++ | false | {nbsp}
|
bypassDocumentValidation  | +++boolean+++ | +++lets you update documents that do not meet the validation requirements. Defaults to false+++ | false | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> that matches the query. If nothing matches, null is returned+++
|===

---

=== Create Index

`<mongo:create-index>`


+++
Creates a new index
+++

==== XML Sample

[source,xml]
----
<mongo:create-index config-ref="Mongo_DB__Configuration" collection="myCollection" field="myField" order="DESC"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection where the index is created+++ |  | *x*{nbsp}
|
field  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the field which is indexed+++ |  | *x*{nbsp}
|
order  | +++<a href="http://mulesoft.github.io/mongo-connector/4.2.0/apidocs/javadocs/org/mule/modules/mongo/api/IndexOrder.html>IndexOrder</a>+++ | +++The indexing order. This is an enum with 2 possible values, ASC (1) for ascending order and DESC (-1) for descending order.+++ | ASC | {nbsp}
|===

---

=== Drop Index

`<mongo:drop-index>`

+++
Drops an existing index
+++

==== XML Sample

[source,xml]
----
<mongo:drop-index config-ref="Mongo_DB__Configuration" collection="myCollection" index="myIndex"/>
----

==== Attributes
[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection where the index is+++ |  | *x*{nbsp}
|
index  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the index to drop+++ |  | *x*{nbsp}
|===

---

=== List Indices

`<mongo:list-indices>`

+++
List existent indices in a collection
+++

==== XML Sample

[source,xml]
----
<mongo:list-indices config-ref="Mongo_DB__Configuration" collection="myCollection"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
collection  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The name of the collection+++ |  | *x*{nbsp}

|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/util/Collection.html">Collection</a><<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>>+++ | +++a collection of <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> with indices information+++
|===

---

=== Create File from Payload

`<mongo:create-file-from-payload>`


+++
Creates a new GridFSFile in the database, saving the given content, filename, contentType, and extraData, and answers it.
+++

==== XML Sample

[source,xml]
----
<mongo:create-file-from-payload config-ref="Mongo_DB__Configuration" filename="#[variable:filename]" metadata-ref="myDbObject"/>
----


==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
payload icon:envelope[] | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Object.html">Object</a>+++ | +++The mandatory content of the new gridfs file. It may be a java.io.File, a byte[] or an InputStream.+++ | &#x0023;[payload] | {nbsp}
|
filename  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The mandatory name of new file.+++ |  | *x*{nbsp}
|
metadata  | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The optional <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> metadata of the new content type+++ |  | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++ | +++The new GridFSFile <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++
|===

---

=== Find Files

`<mongo:find-files>`

+++
Lists all the files that match the given query
+++

==== XML Sample

[source,xml]
----
<mongo:find-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
query icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> query+++ | &#x0023;[payload] | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>>+++ | +++a <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a> files iterable+++
|===

---

=== Find One File

`<mongo:find-one-file>`

+++
Answers the first file that matches the given query. If no object matches it, a MongoException is thrown.
+++

==== XML Sample

[source,xml]
----
<mongo:find-one-file config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
query icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> mandatory query+++ | &#x0023;[payload] | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++ | +++a <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++
|===

---

=== Get File Content

`<mongo:get-file-content>`

+++
Answers an inputstream to the contents of the first file that matches the given query. If no object matches it, a MongoException is thrown.
+++

==== XML Sample

[source,xml]
----
<mongo:get-file-content config-ref="Mongo_DB__Configuration" query-ref="myDbObject" />
----


==== Attributes
[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
fileId icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/BsonObjectId.html">BsonObjectId</a>+++ | +++The BsonObjectId of the file to be deleted+++ | &#x0023;[payload] | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html">InputStream</a>+++ | +++an InputStream to the file contents+++
|===

---

=== List Files

`<mongo:list-files>`

+++
Lists all the files that match the given query, sorting them by filename. If no query is specified, all files are listed.
+++

==== XML Sample

[source,xml]
----
<mongo:list-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject"/>
----


==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
query icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The <a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a> optional query+++ | &#x0023;[payload] | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html">Iterable</a><<a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>>+++ | +++an iterable of <a href="https://api.mongodb.org/java/3.1/com/mongodb/client/gridfs/model/GridFSFile.html">GridFSFile</a>+++
|===

---

=== Remove Files

`<mongo:remove-files>`


+++
Removes the file that matches the given file ID. If no file ID is specified, all files are removed.
+++

==== XML Sample

[source,xml]
----
<mongo:remove-files config-ref="Mongo_DB__Configuration" query-ref="myDbObject"/>
----


==== Attributes
[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
fileId icon:envelope[] | +++<a href="https://api.mongodb.org/java/3.1/org/bson/BsonObjectId.html">BsonObjectId</a>+++ | +++The BsonObjectId of the file to be deleted+++ | &#x0023;[payload] | {nbsp}
|===

---

=== Execute Command

`<mongo:execute-command>`

+++
Executes a command on the database.
+++


==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
commandName  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The command to execute on the database+++ |  | *x*{nbsp}
|
commandValue  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++The value for the command+++ |  | {nbsp}
|===

==== Returns

[%header%autowidth.spread]
|===
|Return Java Type | Description
|+++<a href="https://api.mongodb.org/java/3.1/org/bson/Document.html">Document</a>+++ | +++The result of the command+++
|===

---

=== Dump

`<mongo:dump>`

+++
Executes a dump of the database to the specified output directory. If no output directory is provided then the default /dump directory is used.
+++

==== XML Sample
[source,xml]
----
<mongo:dump config-ref="Mongo_DB__Configuration" oplog="true"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
outputDirectory  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++output directory path, if no output directory is provided the default /dump directory is assumed+++ | dump | {nbsp}
|
outputName  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++output file name, if it's not specified the database name is used+++ |  | {nbsp}
|
zip  | +++boolean+++ | +++whether to zip the created dump file or not+++ | false | {nbsp}
|
oplog  | +++boolean+++ | +++point in time backup (requires an oplog)+++ | false | {nbsp}
|
threads  | +++int+++ | +++amount of threads to execute the dump+++ | 5 | {nbsp}
|===

---

=== Incremental Dump

`<mongo:incremental-dump>`

+++
Executes an incremental dump of the database.
+++

==== XML Sample

[source,xml]
----
<mongo:incremental-dump config-ref="Mongo_DB__Configuration" />
----


==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
outputDirectory  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++output directory path, if no output directory is provided the default /dump directory is assumed+++ | dump | {nbsp}
|
incrementalTimestampFile  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++file that keeps track of the last timestamp processed, if no file is provided one is created on the output directory+++ |  | {nbsp}
|===

---

=== Restore

`<mongo:restore>`

+++
Takes the output from the dump and restores it. Indexes are created on a restore. It only does inserts with the data to restore, if existing data is there, it is not replaced.
+++

==== XML Sample

[source,xml]
----
<mongo:restore config-ref="Mongo_DB__Configuration" inputPath="dump/test.zip" oplogReplay="true"/>
----

==== Attributes

[%header%autowidth.spread]
|===
|Name |Java Type | Description | Default Value | Required
| config-ref | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | Specify which config to use | |*x*{nbsp}
|
inputPath  | +++<a href="http://docs.oracle.com/javase/8/docs/api/java/lang/String.html">String</a>+++ | +++input path to the dump files, it can be a directory, a zip file or just a bson file+++ | dump | {nbsp}
|
drop  | +++boolean+++ | +++whether to drop existing collections before restore+++ | false | {nbsp}
|
oplogReplay  | +++boolean+++ | +++replay oplog for point-in-time restore+++ | false | {nbsp}
|===
