= Mule Secure Token Service OAuth 2.0 Provider
:keywords: esb, security, oauth, authentication, oauth provider, token, private key, secret key, access key

Mule Secure Token Service is one of the following OAuth 2.0 solutions in Mule:

* Client App authentication required by a server
+
The OAuth 2.0 solution is provided by a connector, such as the HTTP or Salesforce connector
+
* Authentication to protect an API from Clients
+
The OAuth 2.0 solution is provided by an API Manager policy.
+
* Authentication for a CloudHub App
+
The Mule Secure Token Service can provide a solution in CloudHub.


== Client Authentication Required by Server

Configure authentication in your client Mule app when sending requests to a service that requires authentication, such as the Github OAuth2 server described in link:/mule-user-guide/v/3.8/authentication-in-http-requests#oauth2-authorization-code[OAuth2 - Authorization Code]. 

== Authentication to Protect API from Clients

When you want to protect your API or app from receiving requests from unauthorized access, use an API Manager policy, such as the OAuth 2.0 Access Token Enforcement Using External Provider policy. To expose a Web service protected by OAuth 2.0 security, see link:/api-manager/building-an-external-oauth-2.0-provider-application[API Manager documentation].

== Client Authentication Required by CloudHub API

The *Mule OAuth 2.0 Secure Token Service* functionality on *CloudHub* is limited due to the known link:/runtime-manager/managing-application-data-with-object-stores#semantics-and-storage-limits[Object Store limitations].

If those limitations don't affect your development, you can use the *Mule OAuth 2.0 Secure Token Service* on Cloudhub. Otherwise, create your own Object Store and configure the OAuth2 module to use your custom Object Store instead of the default. 
For more information, go to the link:http://www.mulesoft.com/support-login[MuleSoft Customer Portal] and open a ticket.

Use Mule Secure Token Service to apply Oauth 2.0 to your Web service provider to:

* grant consumers of your Web service limited access to secure data
* avoid disclosing an end user's access credentials to a Web service consumer
* retain the authority to revoke the consumer’s access to an end user's secure data at any time

For more information about OAuth in Mule, see link:/api-manager/aes-oauth-faq[About OAuth 2.0].

== Next Steps

Run the link:/mule-user-guide/v/3.8/mule-sts-oauth-2.0-example-application[Mule STS OAuth 2.0 Example Application]

