= Supported Software and Systems
:keywords: mule, requirements

Mule runs on operating systems that support the Java versions listed in link:/mule-user-guide/v/3.8/hardware-and-software-requirements#supported-java-versions[Supported Java Versions]. Mule Runtime runs as a standalone server and does not require an application server; however, Mule Runtime can run under one. Mule Runtime does not require a database unless you need to access a data store.

== Supported Operating Systems

The following operating systems have been tested for use with Mule:

* Apple Mac OS 10.11.4
* HP-UX 11i V3
* IBM AIX 7.2
* Linux Red Hat RHEL 7
* Microsoft Windows 8.1
* Microsoft Windows Server 2012 R2
* Oracle Solaris 11.3



== Supported Application Servers

You can run Mule Runtime under the following application servers.

* Apache Tomcat 7 and 8
* IBM WebSphere 8
* Jetty 8 and 9
* Oracle WebLogic 12c
* Wildfly 8 and 9

== Supported Database Servers

The database servers you can use if you need a data store for you application include the following ones:

* Apache Derby 10
* IBM DB2 10
* Microsoft SQL Server 2014
* MySQL 5.5+
* Oracle 12c
* Oracle 11g
* PostgreSQL 9

=== Supported Browsers for Anypoint Platform

Anypoint Platform browser tools are tested and supported on these internet browsers (minimum screen resolution of 1024x768):

* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
* Internet Explorer 10 or later
