= Using Mule with Spring
:keywords: anypoint studio, studio, mule, spring

Mule leverages the Spring framework for developing Java applications. Mule ESB 3.7 and later supports the latest version of the framework, Spring 4.1.6, making use of the Eclipse-based development environment.

*link:/mule-user-guide/v/3.8/about-the-xml-configuration-file[About the XML Configuration File]* +
The most common way to configure Mule ESB is with Spring XML files that use custom Mule namespaces. +
Use one of the two namespaces in your spring framework schema in Mule:

* http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd
* http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd

*link:/mule-user-guide/v/3.8/spring-application-contexts[Spring Application Contexts]* +
Mule offers several options for creating and managing Spring application contexts for your application.

* Single application context
* Multiple application context
* Existing application context
* Existing application context as parent

*link:/mule-user-guide/v/3.8/using-spring-beans-as-flow-components[Using Spring Beans as Flow Components]* +
Build Spring beans to define component behaviors which Mule applications can reference.

*Spring Bean Definition Profiles* +
Mule’s configuration file takes advantage of Spring 4.1.6's ability to create *bean definition profiles*. You can use Spring bean definition profiles to register different beans for different target environments, instead of using one bean for all target environments. For more information, see link:http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#beans-definition-profiles[Bean Definition profiles] in the Spring Framework Reference.

== See Also

* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
