= Hardware and Software Requirements
:keywords: mule, requirements, jdk, installation, jre

Recommended minimum hardware is:

* 2GHz CPU or 1 virtual CPU in virtualized environments
* 1GB of RAM
* 4GB of storage

Adjust RAM to match your latency requirements and the size and number of simultaneous messages that applications process.

Software requirements are:

* One of the following Java versions:
+
** Oracle JDK 1.8.0 (JDK 1.8.0_144 recommended)
** IBM JDK 1.8
** OpenJDK 8 (JDK 1.8.0_144 recommended)
+
* For Microsoft Dynamics GP connector install Java Cryptography Extension (JCE) 8 after installing JRE or JDK.

Mule Runtime is tested against operating systems listed in the "Supported Software and Systems" table.

== Anypoint Connector DevKit Requirements

Anypoint Connector DevKit 3.5 and later is compatible with
Mule versions 3.5 and later. DevKit version numbering
does not correspond to Mule versions. For example, DevKit 3.9 is
compatible with Mule versions 3.5-3.8. For the latest fixes and improvements, use the current version of Mule with its corresponding DevKit as listed in release notes.

== See also

* link:/anypoint-private-cloud/v/1.5/system-requirements[About Minimum System Requirements for Anypoint Private Cloud]
* link:/mule-user-guide/v/3.9/supported-sw-and-systems#supported-operating-systems[Supported Operating Systems table]
* link:http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html[Java Cryptography Extension (JCE) 8]
* link:/release-notes/anypoint-connector-devkit-release-notes[Anypoint Connector DevKit Release Notes]
