= MEL DataWeave functions
:keywords: mel, cheat, sheet

The link:/mule-user-guide/v/3.8/mule-expression-language-mel[Mule Expression Language (MEL)] includes two functions that take advantage of the powerful link:/mule-user-guide/v/3.8/dataweave[DataWeave] transformation language, ideal for carrying out complex data transformations.

All components in Mule that support Mule Expression Language also support expressions written in DataWeave Language.

[TIP]
The DataWeave language is easiest to use by adding a *Transform Message Component* to your flow, as it offers a graphical UI to build automatic mappings through a drag-and-drop interface, as well as rich debugging features. See link:/anypoint-studio/v/6/transform-message-component-concept-studio[About Transform Message Component] for more details.

== Prerequisites

This document assumes you are familiar with both link:/mule-user-guide/v/3.8/mule-expression-language-reference[Mule Expression Language] and link:/mule-user-guide/v/3.8/dataweave-language-introduction[DataWeave Language].

== The DW Function

To invoke an expression written in DataWeave language, simply invoke the `dw()` function, the expression will return whatever the transform outputs.

DataWeave expressions defined within this function work just as those defined within a Transform Message element, the only difference is that the output is returned into the expression's result, wherever it may be.

[NOTE]
The DataWeave expression that you write in this function must be enclosed in "quotation marks"

For example, you can define a custom object and populate it with elements from the payload:

[source,code]
----
dw("myobject:{id:payload.accountid, user:payload.user}")
----

That same expression could be added inside a Logger, within a MEL expression, to print out its result:

[source,code]
----
#[dw("myobject:{id:payload.accountid, user:payload.user}")]
----




Full attribute reference for the function:

[%header,cols="30a,70a"]
|===
|Attributes |Description
|DataWeave Expression |The actual DataWeave expression to carry out
|Output Type	| The type of the output of the transform
|Reader Properties	| For inputs such as CSV, sometimes some properties are needed to know how to parse the input, see link:/anypoint-studio/v/6/input-output-structure-transformation-studio-task[To Define Input and Output Structure of a Transformation]
|Writer Properties	| For inputs such as CSV, sometimes some properties are needed to compose the output, see link:/anypoint-studio/v/6/input-output-structure-transformation-studio-task[To Define Input and Output Structure of a Transformation]

|===

[NOTE]
Reader and writer properties are only supported on versions link:/release-notes/mule-3.8.2-release-notes[Mule Runtime 3.8.2 Release Notes] and newer.

Below is a more elaborate example that uses all the attributes:

[source,code]
----
#[dw(payload.script,'application/xml', ['payload': ['nullValueOn':'empty']], ['output': ['indent':'true']])]
----

In the example above, the first attribute is a simple DW expression that references an element in the payload, the second tells DataWeave to output this as 'application/xml', the third includes a map with reader properties, the fourth includes a map with writer properties.

The maps for reader and writer properties should follow this structure:

* The first key defines the target of the configuration, the value for this key is another map
* Within this map, you list key value pairs for the features to configure

[source,code]
----
['output': ['indent':'true']]
----

[TIP]
See link:/mule-user-guide/v/3.8/dataweave-formats[DataWeave Formats] for a reference of all the different properties you can set for reader and writer. The available options vary depending on the format.

== The Split Function

The `split()` function runs an expression written in DataWeave language and returns an iterator who's result can then be processed by your flow one index at a time. It takes at least two arguments: a DataWeave expression and the desired output type. This function may be equivalent to running the 'dw()' function and then adding an additional step to your flow, such as a link:/mule-user-guide/v/3.8/foreach[Foreach Scope], but it's less heavy on resources.

[NOTE]
The DataWeave expression that you write in this function must be enclosed in "quotation marks" (either single quotation marks `'` or double quotation marks `"`. The result of the split function must also return a single array.

Below is the most basic DW expression you can write, but you could also put any other DW expression as long as it returns an iterable list.

[source,code]
----
split('payload','application/json')
----

That same expression could be added inside a link:/mule-user-guide/v/3.8/foreach[Foreach Scope] in the *Collection* field, to use this expression to parse the payload into a separate set of messages to process individually (one at a time):

[source,xml,linenums]
----
<flow name="myFlow">
    <foreach collection="split('payload','application/json')" doc:name="For Each">
        <logger message="#[payload]" level="INFO" doc:name="Logger"/>
    </foreach>
</flow>
----




The function has the following attributes:

[%header,cols="30a,70a"]
|===
|Attributes |Description
|DataWeave Expression |The actual DataWeave expression to carry out
|Output Type	| The type of the output of the transform
|Reader Properties	| For inputs such as CSV, sometimes some properties are needed to know how to parse the input, see link:/anypoint-studio/v/6/input-output-structure-transformation-studio-task[To Define Input and Output Structure of a Transformation]
|Writer Properties	| For inputs such as CSV, sometimes some properties are needed to compose the output, see link:/mule-user-guide/v/3.8/dataweave-language-introduction#output-directive[Output Directive]
|===


== See Also

* link:/mule-user-guide/v/3.8/mule-expression-language-reference[Mule Expression Language Reference]
* link:/mule-user-guide/v/3.8/dataweave-language-introduction[DataWeave Language Introduction]
