= Using Maven in Mule
:keywords: studio, maven, mule, version control, dependencies, libraries

The pages in this section detail how to use Maven outside of Anypoint Studio, working directly with Mule. You can use Mule plugins to develop your Mule applications within Maven, and to control Mule instances from within a Maven environment.

To work with Maven outside Studio, you need to modify your Maven installation to enable it to work with Mule. These modifications entail adding support for Mule plugins and adding the MuleSoft community or Enterprise repositories.

*Note*: Mule supports any link:https://maven.apache.org/download.cgi[Maven 3.x version] for use with Mac, Windows, and Linux.

This section contains the following pages:

* link:/mule-user-guide/v/3.9/maven-tools-for-mule-esb[Maven Tools for Mule] – Describes the Mule plugin that allows you to develop Mule applications in Maven
* link:/mule-user-guide/v/3.9/mule-maven-plugin[Mule Maven Plugin] - Describes the Mule plugin that allows you to control Mule from within Maven
* link:/mule-user-guide/v/3.9/configuring-maven-to-work-with-mule-esb[Configuring Maven to Work with Mule] – Details how to modify your Maven configuration to work with Mule plugins and add Mule repositories

[TIP]
For info on how to use Maven in the context of Anypoint Studio, MuleSoft's IDE for developing integration applications, see link:/anypoint-studio/v/6/using-maven-in-anypoint-studio[Use Maven in Anypoint Studio]
