= API Quick Start

Jump-start your skills on the application network by stepping through the procedures in this guide. link:/api-quick-start/create-an-api[Create a simple RESTful API] in the Anypoint Platform from the ground up in less than TBD minutes.

Using Anypoint Studio 6.0, you can create a RESTful or WSDL API interface for connecting users to a web service. You build such an interface based on one of the following modeling languages:

* RESTful API Modeling Language (RAML)
* Web Service Description Language (WSDL)

Hypothetically link:/api-quick-start/enhance-an-api-using-anypoint-studio[modernize a legacy project] based on a WSDL and incorporate a RAML file to move the legacy project from SOAP to REST.

This quick start introduces key features of Anypoint Studio, including:

* link:/[How to test an API using MUnit]
* How to set up an API in Anypoint Studio for link:/api-quick-start/create-an-api-from-an-existing-raml#deploy-the-api-to-anypoint-platform-for-auto-discovery[auto-discovery] by Anypoint Platform
* How to synchronize work in Anypoint Studio and Anypoint Platform
