= Test an Enanced API Using MUnit
:keywords: tests, qa, quality assurance, verify, functional testing, unit testing, stress testing

== Overview

Following the example developed in link:/api-quick-start/v/latest/enhance-an-api-using-anypoint-studio[the previous article], this tutorial focuses on giving you an easy walkthrough to develop a *unit test* for said application.

A _unit test_ consists of verifying that a single _unit of code_ works as expected. +
In this particular example, we focus on verifying the statuses and payloads returned by your APIKit router configuration following your `file.raml` specs. +
The purpose of running unit tests is making sure that the core functions of your application behave as you intend them to behave and return the values that you expect them to return. +
Later on, you can choose to automate each test to run before you deploy the application so you can make sure that all core functionalities in your project comply with your design.

To do this, we employ link:/munit/v/1.2.0/index[MUnit], a _Mule application testing framework_ that allows you to build automated tests for your integrations and APIs. +
For this example, we are using a few components to write the test. +
Keep in mind that MUnit provides a full suite of integration and unit test capabilities. To learn more about its components and how to integrate MUnit with your continuous deployment environment, check the link:/munit/v/1.2.0/index[MUnit documentation].

== Install MUnit

MUnit is fully integrated with Anypoint Studio, allowing you to design your tests the same way you would design a Mule application in Studio. +
To use it, you first need to install it in your current Studio version. +

Go to `Help` / `Install New Software...` and click the `Add...` button. +
Set the *Name:* field as `MUnit Update Site` and the *Location:* field as `http://studio.mulesoft.org/beta/r5/munit`

Check *Munit* and *Munit Tools for Mule*, and click *Next* to comlete the installation.

After installation, restart your Studio.

== Writing Your Test

MUnit Studio integration is mainly built around XML-based tests, so an MUnit test looks very similar to the Mule application it's testing.

The most basic way to create a new MUnit test in Studio is to right-click a specific flow, selecting *MUnit* and selecting *Create new suite*.
