= About MUnit
:version-info: 2.0 and newer
:keywords: munit, testing, unit testing

MUnit is a Mule application testing framework that allows you to easily build automated tests for your integrations and APIs. It provides a full suite of integration and unit test capabilities, and is fully integrated with Maven and Surefire for integration with your continuous deployment environment.

With MUnit you can:

* Create your Mule test by writing Mule code
* Create your Mule test by writing Java code
* Disable flow inbound endpoints
* Disable endpoint connectors
* Mock outbound endpoints
* Mock message processors
* Spy any message processor
* Verify message processor calls
* Create not only unit tests but also integration tests in a local environment -- MUnit allows you to start a local FTP/SFTP or DB server
* Call the Mule client from Mule code
* Assert flow exceptions
* Enable or disable particular tests
* See assertion/error reports with Mule stack trace
* Extend the MUnit framework with plugins
* Check visual coverage in Studio
* Debug your tests with Studio


MUnit version 2.0, works with all Mule versions since 4.0

MUnit is divided among several sub modules. From a user's point of view there are only two that are really important. Both modules are compatible amongst themselves.

The important sub modules are:

MUnit is fully integrated with Anypoint Studio, allowing you to create, design and run MUnit tests just like you would Mule applications. You can also use Anypoint Studio Visual Debugger to debug your MUnit tests.

== See Also

* link:/munit/v/2.0/message-processors[About MUnit Event Processors]
