= About MUnit Coverage Reports

The MUnit Coverage feature provides a metric on how much of a Mule application has been executed by a set of MUnit tests. +
This lets you obtain a quality metric for your application.

MUnit Coverage is based on the amount of event processors executed. +
MUnit Coverage provides metrics for:

* Application overall coverage: An average of the items below.
* Resource coverage: Refers to each Mule configuration file under src/main/app. Each of is considered a resource by MUnit Coverage.
* Flow coverage: Refers to any of the following components: Flows, Sub-flows, and Batch jobs.

[NOTE]
Coverage report runs only for EE edition runtimes

The following is a coverage report sample in JSON format. +
Use the code callouts below to understand each field in the report:

[source, json, linenums]
----
{
 "coverage" : 75.0, //<1>
 "requiredApplicationCoverage" : 40.0, //<2>
 "requiredResourceCoverage" : 30.0,
 "requiredFlowCoverage" : 25.0,
 "flowCount" : 3, //<3>
 "messageProcessorCount" : 4, //<4>
 "files" : [ {
   "coverage" : 100.0, //<5>
   "flowCount" : 1, //<6>
   "messageProcessorCount" : 2, //<7>
   "weight" : 100.0, //<8>
   "flows" : [ {
     "coverage" : 100.0, //<9>
     "messageProcessorCount" : 2, //<10>
     "name" : "file1Flow1" //<11>
   } ],
   "name" : "file1.xml" //<12>
 }, {
   "coverage" : 50.0,
   "flowCount" : 2,
   "messageProcessorCount" : 2,
   "flows" : [ {
     "coverage" : 0.0,
     "messageProcessorCount" : 1,
     "name" : "file2Flow1"
   }, {
     "coverage" : 100.0,
     "messageProcessorCount" : 1,
     "name" : "file2Flow2"
   } ],
   "name" : "file2.xml"
 } ]
}
----

<1> Coverage percentage of the whole application
<2> Required coverages for application, resources and flow, if the
user did not configure any value it defaults to -1
<3> Amount of flows in the application
<4> Amount of event processors in the application
<5> Coverage percentage of that file
<6> Amount of flows in that file
<7> Amount of event processors in that file
<8> Contribution of that file to the coverage percentage of the whole application
<9> Coverage percentage of that flow
<10> Amount of event processors in that flow
<11> Name of that flow
<12> Name of that file


== See Also

* link:/munit/v/2.0/faq-how-munit-coverage[FAQ: How Does MUnit Calculate Coverage]
* link:/munit/v/2.0/coverage-studio-concept[About Coverage Report in Anypoint Studio]
