= To Configure MUnit Maven Plugin From the POM File

== Additional Classpath Elements

During a test run, you may want to add additional elements to the classpath such as a resource or an external library. The path of this entry must be specified, and it will be added at the end of the classpath. The path specified can be absolute or written as a maven placeholder.

[source,xml,linenums]
.Additional Classpath Element using absolute paths
----
<additionalClasspathElements>
    <additionalClasspathElement>/path/to/myfile.jar</additionalClasspathElement>
</additionalClasspathElements>
----

[source,xml,linenums]
.Additional Classpath Element using a maven placeholder
----
<additionalClasspathElements>
    <additionalClasspathElement>${project.basedir}/lib/myfile.jar</additionalClasspathElement>
</additionalClasspathElements>
----

== Additional argument lines

Since the tests are being run in a new JVM, additional argument lines can be specified
to the JVM. Each argument should be specified in separate `argLine`.

[source,xml,linenums]
.Argument lines
----
<argLines>
    <argLine>-XX:MaxPermSize=512m</argLine>
    <argLine>-Xmx1024m</argLine>
</argLines>
----

== Exclude Dependencies from the Classpath

In contrast to adding elements to the classpath, there is a way of excluding dependencies from
the classpath by specifying its `groupId` and `artifactId` with the format `groupId:artifactId`.

[source,xml,linenums]
.Exclude dependency from classpath
----
<classpathDependencyExcludes>
    <classpathDependencyExclude>com.example:myproject</classpathDependencyExclude>
</classpathDependencyExcludes>
----


== To Enable Coverage

To enable MUnit Coverage, add the following configuration to the MUnit Plugin:

[source,xml,linenums]
.MUnit Coverage - Minimal Configuration
----
<plugin>
  <groupId>com.mulesoft.munit.tools</groupId>
  <artifactId>munit-maven-plugin</artifactId>
  <version>${project.version}</version>
  ...
  <configuration>
    <coverage>
      <runCoverage>true</runCoverage>   //<1>
    </coverage>
  </configuration>
</plugin>
----
<1> This enables the coverage feature


== To Set a Minimum Coverage Level

One of the features of MUnit Coverage is to fail the build if a certain coverage level is not reached.

To make the build fail, add the following lines to the configuration:

[source,xml,linenums]
.MUnit Coverage - Fail Build
----
<coverage>
  <runCoverage>true</runCoverage>
  <failBuild>true</failBuild>       //<1>
</coverage>
----
<1> Enable *Fail Build Feature*

Now, the next logical step is to define the coverage levels.


== To Ignore Flows for Coverage Report

[source,xml,linenums]
.MUnit Coverage - Ignoring Flows
----
<coverage>
  <ignoreFlows>
	  <ignoreFlow>the-name-of-your-flow</ignoreFlow>       //<1>
  </ignoreFlows>
</coverage>
----
<1> The name of the flow you want to ignore.

This is a list, so you can ignore as many flows as you need.


== Dynamic Ports

When testing a Mule application in a continuous integration (CI) environment, you might encounter the following scenario:

`Your application tries to open a specific port. The port is already in use. The application fails with a port binding exception.`

The easy solution to this problem is to have your application use a free port.
The MUnit Maven Plugin comes with a built-in feature to do just that.

`MUnit Dynamic Ports` instructs the MUnit Maven Plugin to look for unbound ports and reserve them before running the tests over the Mule application. Each port selected is placed in a system property under the name indicated in the configuration.
The application can acquire the port number through the use of placeholders afterward.

TIP: The Ports to be selected by the plugin are taken from the following range: `[40000,50000)`

[CAUTION]
--
Dynamic Ports feature is only available as part of the MUnit Maven Plugin. +
You can not expect this feature to work when running tests from inside Anypoint Studio.
--

=== Enabling Dynamic Ports

To enable the feature, you need to add the following code to the `configuration` section of the MUnit Maven Plugin:

[source, xml, linenums]
.Dynamic Ports Configuration
----
<dynamicPorts>
  <dynamicPort>a.dynamic.port</dynamicPort>
</dynamicPorts>
----

If you have the `${http.port}` placeholder in your application, the configuration looks something like:

[source, xml, linenums]
.Example
----
<dynamicPorts>
  <dynamicPort>http.port</dynamicPort>
</dynamicPorts>
----

==== Preparing Your Application

A placeholder must parametrize the part of the application trying to make use of a port. +
For instance, you may want to have your Mule application listening for HTTP traffic. To do that you should provide the following configuration:

[source, xml, linenums]
.HTTP Simple Application
----
<http:listener-config name="HTTP_Listener_Configuration" host="0.0.0.0" port="8081"/>
<flow name="httpFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/"/>
</flow>
----

Now this application always listens in port `8081`. To make it dynamic, change it to:

[source, xml, linenums]
.HTTP Simple Application with dynamic port
----
<http:listener-config name="HTTP_Listener_Configuration" host="0.0.0.0" port="${http.port}"/> //<1>
<flow name="httpFlow">
    <http:listener config-ref="HTTP_Listener_Configuration" path="/" />
</flow>
----
<1> Notice the placeholder `${http.port}`.

With the application coded in this way and the configuration of Dynamic Ports in place, your application starts each run listening on a different port.

== Enable surefire reports

MUnit has built-in support for Surefire. No additional configuration is needed for this but it can be disabled if not needed.

[source,xml,linenums]
.Disabling surefire reports
----
<enableSurefireReports>false</enableSurefireReports>
----

The reports can be found under `${project.build.directory}/surefire-reports`.

By default, it is set to `true`.

== Environment Variables

To set additional environment variables during the test run, you can specify
them with the respective key and value.

[source,xml,linenums]
.Additional Environment Variables
----
<environmentVariables>
  <MY_ENV>exampleValue</MY_ENV>
</environmentVariables>
----

Environment variables can be used to replace placeholders such as `${MY_ENV}`
(using the example above).

== Mule Working Directory

Changing the mule working directory can be useful if there is a need to specify
a different directory that won't be overridden by another run. +
The path specified can be absolute or written as a maven placeholder.

[source,xml,linenums]
.Mule Working Directory using an absolute path
----
<muleWorkingDirectory>/My/Absolute/Path</muleWorkingDirectory>
----

[source,xml,linenums]
.Mule Working Directory using maven placeholder
----
<muleWorkingDirectory>${project.build.directory}/mymulefolder</muleWorkingDirectory>
----

By default, the mule working directory is `${project.build.directory}/.mule`.

== Redirect Test Output to File

When running several tests, the build output can get very complex to read. You may want
to redirect the output of each Test suite to a file. This way what remains in the build
output will be the test results and to check the standard output of each test suite you can find it
in its respective file.

These files will be located in the `testOutputDirectory` folder following this naming convention:
`munit.${suiteName}-output.txt`, where the `suiteName` represents the name of the XML file relative to the
MUnit test folder.

The test run output that doesn't belong to a particular suite won't be printed to keep the build output clean, but it can be enabled by running maven in _debug_ mode.

[source,xml,linenums]
.Redirect test output to file
----
<redirectTestOutputToFile>true</redirectTestOutputToFile>
----

By default, it is set to `false`

== System Properties Variables

You may wish to define specific system variables needed for your MUnit test to run successfully. The example below shows how you can send them.

[source, xml, linenums]
.Setting system property variables
----
    <systemPropertyVariables>
      <my.property.key>my.property.value</my.property.key>
    </systemPropertyVariables>
----
System Property variables override any property set in the `mule-
app.properties` file or with a property placeholder.

[TIP]
====
Depending on the execution context, the system properties values may vary. When referencing these properties, it is a good practice to override their value to enforce test reproducibility.

You can do so using the ­`-D` argument when running MUnit with Maven. +
Variables passed with the `-D` argument take full priority over any other property.

For example:

`-Dmy.property.key=my.property.another.value`
====




== Test Output Directory

You may want to choose the location where the test output files will be created.
The path specified can be absolute or written as a maven placeholder.

[source,xml,linenums]
.Test output directory with absolute path
----
<testOutputDirectory>/my/absolute/path</testOutputDirectory>
----

[source,xml,linenums]
.Test output directory using maven placeholders
----
<testOutputDirectory>${project.build.directory}/my/output/folder</testOutputDirectory>
----

By default, the files will be created in `${project.build.directory}/munit-reports/output/`.

== See Also
