= Autodiscovery Reference (Mule 4)

The `api-platform-gw` gateway global element contains the information needed to register an API in Anypoint Platform. The global element includes the description and tag attributes. The api-platform-gw attributes include the `flowRef` attribute. In an APIkit project, the global element includes an `apikitRef` that references the APIkit global configuration.

API Manager 2.x doesn't support the `create` attribute. You need to create an API in API Manager before using Autodiscovery.

The following table lists the `api-platform-gw` attributes when you use API Manager 2.x and Mule 4:

[%header,cols="3*a"]
|===
|Attribute |Required |Description
|*apiId* |Yes |The friendly API name that appears on API Manager and in Studio on Global Element Properties.
|*flowRef* |Yes |A reference to the main flow of your project. It triggers the agent to discover this flow and use it when performing the auto-registration.
|*apikitRef* |No |A reference to the APIkit configuration. Used to upload the RAML file to Anypoint Platform after API registration completes and for resource level policies.
|===

The following configuration.xml is an example of an API configured for Autodiscovery in Mule Runtime 4.x:

*Mule Runtime 4.x*

[source, xml, linenums]
----
<api-gateway:autodiscovery apiId="${api.id}" flowRef="proxy" doc:name="API Autodiscovery"/>
----

In Mule Runtime 4.x, `create`, `apikitRef` attributes and `description`, `tag` elements were removed.

== api-platform-gw Nested Elements

The following attributes list the `api-platform-gw` nested elements.

[%header,cols="34a,33a,33a"]
|===
|Nested Element |Required |Description
|*api-platform-gw:description* |No |A description of the API that appears on the API version details page when Anypoint Platform discovers and registers the API.
|*api-platform-gw:tag* |No |The tag is searchable metadata in the API Manager and API that appears on the API version details page when Anypoint Platform discovers and registers the API.
|===

== Autodiscovery Namespace, Schema, and Dependency Information

----
xmlns:api-gateway="http://www.mulesoft.org/schema/mule/api-gateway"
http://www.mulesoft.org/schema/mule/api-gateway http://www.mulesoft.org/schema/mule/api-gateway/current/mule-api-gateway.xsd
----

*Autodiscovery Dependency Information*

----
<dependency>
  <groupId>com.mulesoft.anypoint</groupId>
  <artifactId>mule-module-autodiscovery</artifactId>
  <version>4.0.0</version>
</dependency>
----
