= About Auto-Discovery

API Auto-Discovery is the mechanism by which an API representing a HTTP resource can be managed from API Manager: it provides API Tracking, Policy application and API Analytics reporting.

To pair the Mule Runtime to API Manager a set of conditions must occur:

* The API must exist in API Manager, see: link:/api-manager/v/2.x/manage-exchange-api-task[To Manage an API from Exchange]
* The Auto-Discovery element must be defined in an application in the Mule Runtime.
* The Mule Runtime must be configured with API Manager credentials that give access to the API configuration (see TODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODOTODO).

The relationship between an HTTP Listener and an Auto-Discovery is 1:N. This means an Auto-Discovery element must be linked to a single listener in the whole Runtime, no matter how many apps are deployed.

== To define the Auto-Discovery in an Mule Application.

API Auto-Discovery element has syntactically changed between Mule 3.x and 4.x, though its purpose remains the same. Once the element is defined in the application, and credentials are set _(credentials can only be set at startup)_ (ADD LINK HEREHEREHEREHERE), the Mule Runtime will automatically track and keep up to date the API configuration defined in API Manager.

=== XML Element

The Auto-Discovery element in a Mule Application has the following format:

* link:/api-manager/v/2.x/configure-autodiscovery-3-task[Mule 3.x XML element]: `<api-platform-gw:api (...)/>`.
* link:/api-manager/v/2.x/configure-autodiscovery-4-task[Mule 4.x XML element]: `<api-gateway:autodiscovery (...)/>`.


