= About Auto-Discovery

API auto-discovery is the mechanism to manage an API from API Manager by pairing the deployed application to an API created on the platform. API Management includes tracking, enforcing policies if you apply any, and reporting API analytics. Critical to the auto-discovery process is identifying the API. The way you configure identification depends on the Mule release you use, as described in the linked configuration topic below.

To connect to an organization in Anypoint Platform from Mule Runtime, if the API is managed by API Manager, the client ID and client secret of the organization's _environment_ are configured automatically. Anypoint Platform assigns the unique and immutable organization ID and environment ID at organization and environment creation times. You can track APIs using the organization ID.

== Unsupported Uses of Auto-Discovery

* Multiple auto-discovery elements pointing to an API instance is unsupported. For each supported Mule runtime version for an API instance, you can have only one autodiscovery element pointing to the API in API Manager.

* The auto-discovery element is not supported in Studio 7.0 or Mule Runtime 4.0. 
+
To connect and manage an API from Studio, you need to manually add the element to your Studio 7 applications or configure Mule Runtime 4.1 or later.

== See Also

* link:/api-manager/v/2.x/configure-auto-discovery-new-task[To Configure Auto-Discovery]
* link:/api-manager/v/2.x/api-auto-discovery-new-reference[Auto-Discovery Reference]



