= To Promote the API to another Environment

A tight integration of Anypoint Platform components extends the use of environments to API management. In this procedure, you change the environment of an API. 

. In API Manager, in API Administration, click Promote From Environment.
+
. In Promote API From Environment, in Source Environment, select the environment of the API you want to promote.
. In API, select an API from the list of APIs in the source environment.
. In API Version, select the version of the API.
. In API instance label, optionally select the API instance name if you created any instances. 
. Select or deselect things to include in the promotion: Policies, SLAs, Alerts, API Configuration
. Click Promote.


*Note*: Promoting an API affects only the API definition, not the existing deployed applications subscribed to the API. After promoting an API, the API Name remains the same, but the API Version changes.

For existing applications that need to subscribe to a promoted API, you need to make following changes:

. Update the API Version. 
. As each environment has different client id and secret, update the application's client id and secret. 


== See Also

* link:/access-management/environments[Environments]
* link:/api-manager/v/2.x/create-instance-task[To Create an API Instance]

