= Choosing the SDK Version
:keywords: mule, sdk, create, new, project, getting, started, version

//TODO: IS THIS 1.1 ONLY, NOT 1.0

Developers tend to use the latest available version of a given product. This should not be the case with the Mule SDK. When choosing a version of the SDK to use for extending a Mule module, you should:

* Identify the features you need.
* Choose the lowest version that includes the features you need.

Why is that? We'll explain next.

== Extensions API

When you're developing with the SDK, you're really just using an API, the `Extensions API` to preciselly. Whenever you annotate a field or method with any of the SDK annotations, or when you implement any interface, you're just using parts of this Extensions API. The module that you will ship only contains your code, it doesn't contain any of the code which bridges your module with the Mule Runtime internals. This gap is actually bridged in Runtime, thanks to your use of the `Extensions API`.

== Minimum Mule Version

Each version of the Mule runtime ships with support to one particular version of the `Extensions API`, plus all the version that preceeded it. So for example:

* if Mule `4.1` ships with SDK version `1.1`
* and Mule `4.2` ships with SDK version `1.2`

Mule `4.2` will fully support any module developed with both SDK versions `1.2`, `1.1`, and `1.0`. If Mule `4.3` introduces SDK 1.3, it will also support `1.2` and `1.1` and so on...

This concept works both ways:

* Because any Mule Runtime version will support all the SDK versions which were released before, this guarantees that a module which works in Mule `4.1` should work in any Mule 4.x for which x >= 1
* It also means, that if a module was built using SDK v`1.2`, then it will only works in Runtimes which support that SDK version. In the case of this example, this module will not work in Mule `4.1`

== Idenfity your required features

This is why you shouldn't aim to use the latest SDK version available, because this will mean that your module will only be compatible with the latest Mule Runtime available. Instead, you should use the oldest version which includes all the features you need. So for example:

* If you're just doing a simple connector, and you need nothing else than connectivity and basid DataSense, then just use version `1.0`
* If you also need to use the PollingSource interface, then use SDK 1.1 since that's the version in which that feature will be introduced, and thus, only Runtimes with support for that feature will be able to run your module.


For any new SDK feature, the documentation includes the version in which it was introduced. If no particular version is specified, then it means that the feature has been present since the very first version.

[TIP]
The recommended approach is to just start all your projects using version `1.0.0` and only upgrade the versions as you face the need for particular features.

Following this guidelines will make your module compatible with a wider number of Mule Runtime versions and, as a consequence, more people will be able to use your
module. If you do require features from newer versions, then there's no real reason for you to use the newer versions.


== What if there's a bug in the SDK

Because the `Extensions API` is just an API and the actual implementation resides in the Mule Runtime, most SDK related bug fixes will not be made available through new SDK versions but through new Mule Runtime versions, more precisely through patch releases and Service Packs.

In some corner cases, the issue might actually be in the API definition, in which case a path release of the SDK will be made available (e.g: `1.1.2`). You should always choose the higher bugfix version. For example between `1.0.0` and `1.0.4`, you should pick `1.0.4`.

[TIP]
The above are just examples, at the moment of writing this article, there're no bug fix versions of the SDK

== Changing Version

The SDK Version is specified in your module project `pom.xml` file, inside the
parent element.

[source, xml, linenums]
----
<parent>
  <groupId>org.mule.extensions</groupId>
  <artifactId>mule-modules-parent</artifactId>
  <version>1.0.0</version>
</parent>
----

To change to another version, you just need to change the parent version for
the desired one.
