= Choosing the SDK version
:keywords: mule, sdk, create, new, project, getting, started, version

This page provides information about which version of the SDK you should choose
when developing a mule module.

When choosing an SDK version there are a few things to consider:

* Which mule runtimes the chosen SDK version supports.
* Which features the chosen SDK version supports.
* Which SDK features does the module require.

While the latest versions of the SDK provide great new APIs for your module,
you should try to support older versions of the mule runtime by choosing lower
SDK versions. If you don't require one of the latest APIs then you don't need to use
the version that comes with that API, this will let you support a wider number of
mule runtime versions and, as a consequence, more people will be able to use your
module. If you do require a particular feature released in a newer version, you must
known in which versions will your module be able to run.

All SDK versions are *forward compatible*, this means that modules that use a particular
version will support that SDK version's target mule runtime version and all the forward
major mule runtime releases.

NOTE: Take in mind that SDK versions have a bugfix subversion (major.minor.bugfix e.g.: 1.0.3) that won't add
APIs nor change behavior but add bugfixes. You should always choose the higher bugfix
version. For example between 1.0.0 and 1.0.4, you should pick 1.0.4.

== Changing Version

The SDK Version is specified in your module project `pom.xml` file, inside the
parent element.

[source, xml, linenums]
----
<parent>
  <groupId>org.mule.extensions</groupId>
  <artifactId>mule-modules-parent</artifactId>
  <version>1.0.0</version>
</parent>
----

To change to another version, you just need to change the parent version for
the desired one.
