= Devkit Migration Tool
:keywords: mule, sdk, devkit, migration, migrate, connector

The Devkit Migration Tool *(DMT)* works as a starting point for anyone wanting
to move from a Connector built with Devkit that runs on Mule 3.x to the new SDK
model of Mule 4.

The DMT introspects the devkit connector code and generates the source Java code
of a new SDK Extension. The new Extension code will wrap around the current Connector code,
as it would with any other java lib, delegating all the actual code responsibility
to the already tested Connector code.

== Executing the DMT

The DMT can be executed from the command line as a maven plugin, but first you need
to change your connector pom.xml file.

To declare a Devkit version a connector specifies the devkit-parent version in
the pom.xml file, like this:

[source, xml, linenums]
----
<parent>
  <groupId>org.mule.tools.devkit</groupId>
  <artifactId>mule-devkit-parent</artifactId>
  <version>3.9.4</version>
</parent>
----

in order to be able to execute the DMT you must move you current version to *4.0.0*

[source, xml, linenums]
----
<parent>
  <groupId>org.mule.tools.devkit</groupId>
  <artifactId>mule-devkit-parent</artifactId>
  <version>4.0.0</version>
</parent>
----

Now, from the your connector's root directory you can execute the following line
to start the migration.

----
mvn clean package
----

Once finished you should see a `Build Success` message and you will find the generated
extension project under the _{rootdir}/target/generated-sources/extension_ folder.

== Supported Components

The following elements of a Devkit Connector will be ported to it’s new Extension representation.

=== Processors

All the processors will be migrated to Operations, all within the same class.
Parameters of the Processor should be reflected in the Operation parameters and
also elements as Config or injected fields present in the old Connector that should
be setup will be passed in as parameters.

see: link:operations[SDK Operations Documentation Reference] to learn more about Extension Operations.

=== Sources

see: link:sources[SDK Sources Documentation Reference] to learn more about Extension Sources.

=== Connection Strategies
==== Configuration
==== Connection Management

=== Also Supported


== Compatibility Rules

In order to migrate a Connector the following compatibility rules have to be considered.
For migration to be as strict as possible, we’ll consider only DevKit 3.8.x or Higher compatible connectors,
not migrating (at least to a fully working Extension) those connectors that don’t respect the latest verifications
or those that use deprecated components/annotations.

Since SDK’s model and api will grow over time, this is table will be updated and more rules, matches and restrictions will appear.
