= Modules Licensing

Modules written with the SDK have three possible kinds of licensing, each setting different requirements
to how the application can be executed.

== Community Module

The default for all Modules, applications that use a Community Module can be executed in all Mule
runtimes with no further requirements.

== Enterprise Module

Only Mule EE Runtimes can be used to execute the applications that use the Enterprise Modules,
which means that the user of the Module needs a MuleSoft Enterprise License. +
Declaring a Module to be EE-only is very easy, you just have to add the `@RequiresEnterpriseLicense`
annotation:

[source,java,linenum]
----

@Extension(name = "enterprise")
@RequiresEnterpriseLicense
public class EnterpriseConnector {

}
----

By default, `RequiresEnterpriseLicense` forces the user to have a full MuleSoft Enterprise License,
but you can also declare the Module to allow an evaluation license to be used in for the Runtime.
This can be configured using the `allowEvaluationLicense` flag in the `RequiresEnterpriseLicense` annotation:

[source,java,linenum]
----

@Extension(name = "enterprise")
@RequiresEnterpriseLicense(allowEvaluationLicense = true)
public class EnterpriseConnector {

}
----

== Custom Module License

MuleSoft Certified Connectors can request to MuleSoft a _certified license generation key_ that allows them to
create their own Connector’s Custom License, ensuring that anyone that wants to use
that Certified Connector has to contact the Partner that developed the Module in order
to obtain their Custom License.

Partners that have built a MuleSoft Certified Connector can give potential customers the chance
to build a Mule application with their connector and test it at design-time, but upon deploying
the Mule application with the connector, customers are prompted  for the Partner’s Custom License.


=== Obtaining a License Generation Key for your Connector

Before submitting the developed connector to MuleSoft for certification, the prospective certified connector
partner must complete these steps:

. Include the following information for MuleSoft to use before generating a partner key and keystore.
.. *Company Name* (also known as "Provider Name"), *Contact Email*, *Contact Message*, *Connector Name*
. Request the key and keystore from MuleSoft which are:
.. The public `.key` file that you store in the connector
.. The `.jks` master keystore is for you as the partner to generate licenses with.

== Adjusting the Connector Code and Storing the Public Key

After obtaining the key and keystore:

. The partner adjusts the connector project code by applying the `@RequiresEntitlement` annotation
 and entering values for all requested attributes.
.. `name` must be the name of the connector
.. the `provider` attribute must be the part before the `.key` suffix. For example, if MuleSoft generated a vendor key “prov-name.key”, then the partner puts “prov-name” as the provider.
+
[source, java, linenums]
----
@Extension(name="connector-name", provider="prov-name")
@RequiresEntitlement(name="connector-name")
public class LicensedConnector {
  ...
----
+
. Put the MuleSoft-provided `.key` file under `src/main/resources` or `src/main/resources/license` in the connector’s project directory.

=== Sample Partner Connector

You can download and import the sample connector to Studio to see how the license management annotations are configured in the connector code, understanding that and where the customer `.key` license file should live in the connector directory. (`src/main/resources`).

// TODO: NEED TO ADD ZIP FOR SAMPLE CONNECTOR TO _attachments:  link:_attachments/licSampleConnector.zip[sample connector]

== Producing a License File

MuleSoft partners use the `.jks` file, and the license generation plugin to generate a license to send to the connector customer.

From the command line, where "vendor.keystore" should be replaced with the path to your jks file, execute the command in the same directory where the `.jks` file is:

//TODO redeploy license plugin as org.mule.extension:mule-extension-license
[source, code]
----
mvn org.mule.tools.devkit:mule-devkit-license:license -Dvendor.keystore=betaprovider-license-demo.jks
----

[INFO]
Optionally, you may specify the expiration date of the license by appending `-Ddays.to.expire=<days-until-this-license-expires>` to the above command. To add the customer's name to the license, append `-Dclient=<client-name>`.

If the license is successfully created, the output is similar to this:

----
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- mule-devkit-license:license (default-cli) @ standalone-pom ---
* Enter the name of the client whom will receive this license: Bob
* Enter the name of the provider of the Entitlement as it appears in the @RequiresEntitlement annotation: betaprovider
* Enter the name of the Entitlement as it appears in the @RequiresEntitlement annotation: lic-demo
* Enter the name of the Connector as it appears in the @Connector "name" attribute: license-demo
* Enter keystore password:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.151s
[INFO] Finished at: Thu Dec 10 09:34:41 ART 2015
[INFO] Final Memory: 6M/287M
[INFO]
----

== Developing a Mule Application with a Licensed Connector

For the customer to validate their working connector license, they must make their license (`.lic` file) available through either the Mule application or the Mule server, accordingly.

=== License File in the Mule Application

Once the customer has already bought a license for the connector, the `.lic` file provided to the customer by the partner/vendor can be placed either:

* under `src/main/resources` in the application (developed in Studio) or,
* under `app/classes` if the application has already been unpacked and deployed on the server.

=== License File in the Mule Server

Instead of storing the license in the application, it can be placed in the `conf/` folder of the Mule server.

[NOTE]
Storing the license in the Mule server is the recommended approach if multiple applications require the same license.
