= Advanced Sources Settings

== @ClusterSupport

*Available since version 1.1*

Allows to indicate how should the Source behave when the Mule Runtime is running in Cluster mode. For example:

[source, java, linenums]
----
@ClusterSupport(DEFAULT_PRIMARY_NODE_ONLY)
public class JmsListener extends Source<Object, JmsAttributes> {
// ...
}
----

The `@ClusterSupport` annotation takes a parameter of type `SourceClusterSupport` which can take the following values:

* NOT_SUPPORTED: The source doesn't support cluster mode and hence only runs on the primary node. If the primary node crashes, a new primary node will be designated and the source will be started on it
* DEFAULT_ALL_NODES: Runs on all the cluster nodes by default, but the user can choose to only run on the primary one
* DEFAULT_PRIMARY_NODE_ONLY: Only runs on the primary node by default, but the user can choose to run on all the nodes

When the selected value is other than `NOT_SUPPORTED`, a parameter named `primaryNodeOnly` is automatically added to allow the user to configure whether the source should run in all nodes or just the primary ones.

[TIP]
Notice that when this parameter is in fact added, it will be optional and its default value will depend on the select cluster support mode
