= Static Metadata Annotations

When explaining what static metadata is, the cases mentioned were cases on which the connector developer
did not have to add any annotation for it to work. This are the cases of simple java types and custom
POJOs. On those cases the structure is well known or can be introspected.

Static Metadata is the Metadata bounded to a component that won't change depending
on the value of another parameters, it is known at compile time. The advantage of static
metadata over dynamic is that, because it does not change and is known at compile
time, there is no need to recalculate its structure depending on another parameter value. This means that
the resolution is already done when developing an application.

On this section you will see usages of static metadata resolution that are not automatically handled.

== XML and JSON Types

*Available since version 1.1*

Sometimes, operations require parameters to be JSONs or XMLs that follow a certain structure. To have
DataSense signal these types of structure, there are annotations to make this possible. These annotations
enable you to indicate if certain parameter, output payload or output attributes are of JSON or XML type,
and on each case, which structure do they follow.

=== JSON Type

In order to determine the structure of a JSON type , a JSON schema must be provided.

* `@OutputJsonType`

[source, java, linenums]
----
@OutputJsonType(schema = "person-schema.json")
public Result<InputStream, RetrieveAttributes> retrievePerson() {
  // ...
}
----

* `@AttributesJsonType`

[source, java, linenums]
----
@AttributesJsonType(schema = "resolution-attributes-schema.json")
public Result<Integer, InputStream> getSolution() {
  // ...
}
----

* @`InputJsonType`

[source, java, linenums]
----
public void addPerson(@InputJsonType(schema = "person-schema.json") InputStream person) {
  // ...
}
----


=== XML Type

In order to determine the structure of an XML, an xsd file and the qualified name
used to reference the element to be loaded must be provided.

* `@OutputXmlType`

[source, java, linenums]
----
@OutputXmlType(schema = "order.xsd", qname = "shiporder")
public Result<InputStream, OrderAttributes> retrieveOrder() {
  // ...
}
----

* `@AttributesXmlType`

[source, java, linenums]
----
@AttributesXmlType(schema = "order-attributes.xsd", qname = "attributes")
public Result<Integer, InputStream> getOrderStatistics() {
  // ...
}
----

* `@InputXmlType`

[source, java, linenums]
----
public void createOrder(@InputXmlType(schema = "order.xsd", qname = "shiporder") InputStream order) {
  // ...
}
----
