= Anypoint Platform On-Premises Edition

This section shows you how to install and use both the *Anypoint Platform On-Premises Edition* and the *Runtime Manager On-Premises Edition*. The Anypoint Platform On-Premise Edition offers all of the features that are available in the online version of the link:anypoint.mulesoft.com[Anypoint Platform] as a service that you can run on your local servers, guarded by any security policies you may require.
Similarly, the Runtime Manager On-Premises Edition offers a reduced version of the Anypoint Platform, that only comprises the link:/cloudhub[CloudHub] functionality that allows you to deploy applications to your own servers.

* link:/anypoint-platform-on-premises/v/1.1.0/installing-anypoint-on-premises[Installing Anypoint On-Premises]
* link:https://docs.mulesoft.com/anypoint-platform-for-apis/[Anypoint Platform for APIs]
* link:https://docs.mulesoft.com/cloudhub/[Anypoint Runtime Manager]
* link:https://docs.mulesoft.com/anypoint-platform-administration/[Anypoint Platform Administration]
