= Anypoint Platform On-Premises Edition

[NOTE]
For more information regarding Anypoint Platform On-Premises Edition, please contact your MuleSoft account team.


This section shows you how to install and use both the *Anypoint Platform On-Premises Edition* and the *Runtime Manager On-Premises Edition*. The Anypoint Platform On-Premises Edition offers all of the features that are available in the online version of the link:https://anypoint.mulesoft.com[Anypoint Platform] as a service that you can run on your local servers, guarded by any security policies you may require.

When you choose to run Anypoint Platform on-premises, MuleSoft systems do not interact with your data at all. You configure and run the software and handle all storing, processing and transmitting of data directly, without interference from MuleSoft.






* link:/anypoint-platform-on-premises/v/1.1.0/installing-anypoint-on-premises[Installing Anypoint On-Premises]
* link:https://docs.mulesoft.com/anypoint-platform-for-apis/[Anypoint Platform for APIs]
* link:https://docs.mulesoft.com/runtime-manager/[Anypoint Runtime Manager]
* link:https://docs.mulesoft.com/anypoint-platform-administration/[Anypoint Platform Administration]

