= BAT Command Reference

This reference covers the syntax and key options you can use with the BAT command. Using the BAT command, you debug and run tests, get credentials for scheduling tests, schedule tests, list test schedules, and perform other operations.

*NAME*

bat - the API Monitoring command line interface 

*SYNOPSIS*

`bat <file> ... | <option> ...`

`bat login --username=<value> --password=<value> --profile=<value> [--bat-env=<value>]`

_where_

* file is the relative path to a yaml file or a .dwl file and the file name.

* option is:
+
** `--env=<name>`
+
Selects a configuration file (from config folder) and registers the result as a global variable.

** `--version`
+
Prints to standard output the version numbers of installed BAT and wrapper. If the latest version is not installed, that version is downloaded.
+
** `--bat-version=0.3.256`
+
Executes BAT using the specified version.
+
** `--update`
+
Installs the latest BAT CLI.
+
** `--validate`
+
Validates the file or folder. Also works with `--env` to validate
specific configurations.

+
** `--debug`
+
Sends troubleshooting information to standard output during an execution.
+
** `--zip`
+
Generate a zip having all the components in the current directory, and upload the zip to Exchange.
+
** `--bat-env=devx`
+
Specify the bat server.
+
** `--track`
+
Send data from the local executions.
+
** `get_token`
+
Return the token for accessing Anypoint Platform in the credentials file. Requires that you first run `bat login`. 
+
** `worker register`
+
Generate a post with the machine name and create a dummy target.
+
** `schedule list`
+
List all the schedulers in a particular enviroment.
+
** `schedule create`
+
Create a scheduler using a cron expression of 15 minutes and generating a zip that includes the tests and all the files.
+
** `whoami`
+
Sends Anypoint Platform connection information to standard output.
+
** `--username=<value>`
+
Value is an Anypoint Platform user name.
+
** `--password=<value>` 
+
Value is an Anypoint Platform password.
+
** `--profile=<value>`
+
Profile is an arbitrary identifier, such as *devx*, that sets the profile for accessing an Anypoint Platform location. DOC NOTE: IS profile A SERVER ALIAS? 
+
** `bat --env=<val>`
+
Value specifies an environment in your organization that specifies an environment for running tests using subsequent bat commands. The default environment is used if not specified.

== BAT Command Examples

* Run a single file.
+
`bat ./test/myFile.dwl`
* Determine the installed version.
+
`bat --version`
+
Example output if you do not have the latest version is:
+
----
Downloading version 0.3.338. Please wait.......................
BAT Wrapper: 1.0.53
BAT Version: 0.3.338
----


