= BAT CLI Reference

The BAT CLI provides a command line utility that you use to run tests locally and schedule monitors for continuous API testing. You can schedule tests in the cloud using the CLI-xAPI.  The BAT CLI is integrated with Anypoint Platform.

This reference covers the syntax and key options you can use with the BAT command. Using the BAT command, you debug and run tests, get credentials for scheduling tests, schedule tests, list test schedules, and perform other operations.

*NAME*

bat - the API functional monitoring command line interface

*SYNOPSIS*

`bat [<file> ... | <option> ...]`

`bat [login --username=<value> [--profile=<value>] --host=<value>]`

This option displays an interactive command for the password.

** `password for user [username]: <password>`

Optionally, you can include the option `--password=<password>` in the login command.

_where_

* file is the relative path to the path and file name. The file must have one of the following base names and one of the following extensions:
+
** base file names: main, bat
** extensions: .yaml, or .yml
+
When you execute bat without any arguments, it reads the YAML in the current directory and runs specified tests.
You can create a config folder and create different configuration files for the environments.
```
test-project
├── bat.yaml
├── tests
└── config
    ├── default
    ├── devx
    ├── qax
    ├── stgx
    └── prod

```

* option is:
+
** `--config=<name>`
+
Selects a configuration file (from config folder) and registers the result as a global variable.

** `--version`
+
Prints to standard output the version numbers of installed BAT and wrapper. If the latest version is not installed, that version is downloaded.
+
** `--bat-version=1.0.39`
+
Executes BAT using the specified version.
+
** `--update`
+
Installs the latest BAT CLI.
+
** `--validate`
+
Validates the file or folder. Also works with `--config` to validate specific configurations.
+
** `--debug`
+
Sends troubleshooting information to standard output during an execution.
+
** `--track`
+
Send data from the local executions.
+
** `get_token`
+
Return the token for accessing Anypoint Platform in the credentials file. Requires that you first run `bat login`.
+
** `worker register`
+
Generate a post with the machine name and create a dummy target.
+
** `schedule create [--cron="<expression>"]`
+
Create a scheduler using a cron expression and generating a zip that includes the tests and all the files. By default, if a cron expression is not entered, tests are scheduled to run every 5 minutes.
+
** `schedule endpoint <arbitrary-URL> [--profile=<value>] [--init-folder]`
+
Create a monitor in Exchange of using an arbitrary URL, for example `+http://example.com+`. Optionally, store generated exchange.json and main.dml in the currrent directory. By default, tests are scheduled to run every 5 minutes.
+
** `schedule list [--profile=<value>]`
+
List all the schedulers in a particular enviroment.
+
** `--username=<value>`
+
Value is an Anypoint Platform user name.
+
** `--password=<value>`
+
Value is the password for the Anypoint Platform user name.

** `--profile=<value>`
+
Profile is 1) the name of a profile for accessing an Anypoint Platform location and retaining the login information between BAT sessions. Using this option eliminates the need to relogin between sessions. Optional. 2) the name of a profile for scheduling an endpoint that can be different from the BAT login profile you used. By default, BAT uses the login profile for scheduling. Optional.
+
** `--init-folder`
+
Stores the files, exchange.json and main.dwl, generated by creating the monitor in the current directory. Optional.
** `--init`
+
The command `bat init` sets up a basic project folder. The folder contains the following files:
```
bat.yaml
tests/
tests/HelloWorld.dwl
config/
config/default.dwl
config/prod.dwl
config/dev.dwl
```

== BAT Command Examples

* Run multiple test files that are listed in bat.yaml.
+
`bat bat.yaml`
+
* Run a single file.
+
`bat ./test/myFile.dwl`
* Determine the installed version.
+
`bat --version`
+
Example output if you do not have the latest version is:
+
----
Downloading version 0.3.338. Please wait.......................
BAT Wrapper: 1.0.53
BAT Version: 0.3.338
----

== See Also

** link:/api-function-monitoring/bat-schedule-test-task[To Schedule a Test]
