= bat Command Reference

The key options you can use with the bat command are listed below.

== Syntax


`bat [<file>] <options ... >`

`bat login --username=<val> --password=<val> [--profile=<val>] [--bat-env=<val>]`

_where_

file:

(optional) a yaml file or a .dwl file

* options:
+
** `--env=<name>`
+
Selects a configuration file (from config folder) and registers the result as a global variable.

** `--version`
+
Prints to standard output the version numbers of installed BAT and wrapper. If the latest version is not installed, that version is downloaded.
+
** `--bat-version=0.3.256`
+
Executes BAT using the specified version.
+
** `--update`
+
Installs the latest BAT CLI.
+
** `--validate`
+
Validates the file or folder. Also works with `--env` to validate
specific configurations.

+
** `--debug`
+
Sends troubleshooting information to standard output during an execution.
+
** `--zip`
+
Generate a zip having all the components in the current directory, and upload the zip to Exchange.
+
** `--bat-env=devx`
+
Specify the bat serve.
+
** `--track`
+
Send data from the local executions.
+
** `get_token`
+
Return the token for accessing Anypoint Platform in the credentials file. Requires that you first run `bat login`. 
+
** `worker register`
+
Generate a post with the machine name and create a dummy target.
+
** `schedule list`
+
List all the schedulers in a particular enviroment.
+
** `schedule create`
+
Create a scheduler using a cron expression of 15 minutes and generating a zip that includes the tests and all the files.
+
** whoami
+
Sends Anypoint Platform connection information to standard output.

== General BAT Examples

* Run a file.
+
Run a single file.
+
`bat ./test/myFile.dwl`
+
* Determine the installed version.
+
`bat --version`
+
Example output if you do not have the latest version is:
+
----
Downloading version 0.3.338. Please wait.......................
BAT Wrapper: 1.0.53
BAT Version: 0.3.338
----

== Anypoint Platform-Related bat Commands

You run the `bat login` command to connect to Anypoint Platform for scheduling tests. This command creates a token for accessing Anypoint Platform and saves it in the credentials file.

`bat login --username=<val> --password=<val> [--profile=<val>] [--bat-env=<val>]`

*Options*

* `--username=<val1>`
* `--password=<val2>` 
+
_where_
+
** val1 is an Anypoint Platform user name
** val2 is an Anypoint Platform password
+
* `--profile=<val>`
+
** val is an arbitrary identifier, such as *devx*, that sets the profile for accessing an Anypoint Platform location. DOC NOTE: IS profile A SERVER NAME? 
+
* `bat --env=<val>`
+
** val is the name of an environment in your organization that specifies an environment for running tests using subsequent bat commands:



