= bat Command Reference

The key options you can use with the bat command are listed below.

== Syntax

`bat <file?> <options...>`

_where_

file:
+
(optional) a yaml file or a .dwl file

* options:
+
** `--env=<name>`
+
Selects a configuration file (from config folder) and registers the result as a global variable.

** `--version`
+
Prints the bat-wrapper and latest installed BAT version.
+
** `--bat-version=0.3.256`
+
Executes using the specified version.
+
** `--update`
+
Installs the latest CLI version.
+
** `--validate`+
Validates the file or folder. Also works with `--env` to validate
specific configurations.

+
** `--debug`
+
Executes displaying debug information.

== Examples

To run just one file:

`bat ./test/myFile.dwl`

To specify an environment for running tests using subsequent bat commands:

`bat --env=qa`

== Other bat Options

Other options you can use with the bat command provide synchronization with Anypoint Platform.

* `--zip`
+
Generate a zip having all the components in the current directory, and upload the zip to Exchange.
* `--bat-env=devx`
+
Specify the bat serve.
+
* `--track`
+
Send data from the local executions.
+
* `get_token`
+
Return the token in the credentials file.
+
* `login --username=x --password=y` 
+
Create a token and save it in the credentials file.
+
* `--profile=devx`
+
Determinate the profile to save the credentials or use it.
* `worker register
+
Generate a post with the machine name and create a dummy target.
+
* `schedule list`
+
List all the schedulers in a particular enviroment.
+
* `schedule create
+
Create a scheduler using a cron expression of 15 minutes and generating a zip that includes the tests and all the files.


