= Integration with Exchange 2.0 Beta

Anypoint Studio 6.3 Beta allows you to connect to Exchange 2.0 Beta to publish your project as a new asset.

[NOTE]
The Publish to Exchange feature only works in Mavenized projects.

By default, Studio 6.3 Beta points to the Exchange 2.0 Beta URL +https://anypoint.mulesoft.com/exchange2/+.

== To Publish to Exchange 2.0 Beta

. In a Mavenized project, right click the project folder on your Package Explorer View.
. Select Anypoint Platform and then Publish to Exchange.
. Select your Anypoint Platform user and business group.
:: Additionally you can click the "Add Account" button to use a new Anypoint Platform account.
. Review the information about your project:
* Group Id: This field is required. The group Id uniquely identifies your project across others. By default, Studio uses the group Id configured in your pom.xml file.
* Artifact Id: This field is required. The artifact Id is the name of your project without a version. By default, Studio uses the artifact Id configured in your pom.xml file.
* Version: This field is required. The version of the asset you are publishing.
. Select a project type.
. Select the "Save updated project information to the pom.xml"  if you want to update your pom.xml file with the data you just provided.
+
[NOTE]
--
If selected, the "Save updated project information to the pom.xml" option updates your local project's information with the data configured in the Publish to Exchange window. +
If not, the project is deployed with the configured data, but your local project information is not updated.
--
+
. Click Finish.

You can follow the deployment progress in the Console View. +
After confirmed, the deployment to Exchange 2.0 cannot be stopped.


== See Also

* link:https://docs.mulesoft.com/anypoint-studio/v/6/enabling-maven-support-for-a-studio-project[Mavenize a Studio project].
