= Administration

If you select the Home partner, the Administration tab appears in the left-hand navigation pane.

[width="100%", cols="30a,70a",options="header"]
|===
|Setting |Description

| API Key

|Create a new API Key

* In the *API Key* section, click *Create a new API key*. The API Application Program Interface (API) Key is a 32-bit alphanumeric universal unique identifier (UUID) string that APM generates for you; you use it to access the Anypoint B2B API.

WARNING: Store your API key in a secure location. If you lose it, you will need to create a new API key. APM does not store your API key.

|===

== Environments

The information in this section is required when using link:/anypoint-b2b/partner-manager-connector[Partner Manager Connector].

== Next steps

* link:/anypoint-b2b/identifiers[Go back to the previous configuration page]
* link:/anypoint-b2b/format-defaults[Move on to the next configuration page]
* See link:/anypoint-b2b/more-information[More information] for links to these and other Anypoint B2B pages
