= Administration

NOTE: Current Anypoint Partner Manager solutions will continue to be supported in accordance with the https://www.mulesoft.com/legal/support-maintenance-terms[Product Support and Maintenance Terms] but will not be available for new customers or upgrades. Contact your MuleSoft representative for more information on MuleSoft's B2B solutions. 

Use these pages to configure administrative settings for your company.

Your company may have been set up during the provisioning process. If so, its name appears at the top of the Name list on the Partner Configuration Page, identified as *Your company*.

include::/_sources/edit-home-partner-settings.adoc[]

[start=3]

. In the left-hand navigation pane, click the page name that corresponds to the settings with which you want to work.
+
The page that you clicked in the left-hand pane appears. For information about the page, click the corresponding link in the following list.

* link:/anypoint-b2b/environments[Environments]
* link:/anypoint-b2b/error-codes[Error Codes]
* link:/anypoint-b2b/security[Security]
* link:/anypoint-b2b/lookup-tables[Lookup Tables Administration]
