= Anypoint Partner Manager Concepts

:keywords: Anypoint b2b Anypoint Partner Manager concepts

This page explains Anypoint Partner Manager concepts. For more information, see link:/anypoint-b2b/anypoint-partner-manager[Anypoint Partner Manager].

== B2B Routing Framework

<content to come from Kent>

== Hierarchical Resolution Logic

<content to come from Claude>

== Tracking

This section suggests use cases in which you would want to use Anypoint Partner Manager (APM) to track B2B exchanges. We assume a basic knowledge of APM in this section; if necessary, refer link:/anypoint-b2b/anypoint-partner-manager[Overview] for more information. For specific information about how to implement APM, see link:/anypoint-b2b/anypoint-partner-manager-users-guide[Anypoint Partner Manager User's Guide].

=== Scenarios

==== Replaying an incomplete transaction

On the link:/anypoint-b2b/monitor-b2b-transactions[B2B Transactions Page], the link:/anypoint-b2b/monitor-b2b-transactions#Transactions[Transactions View] includes a table in which each row corresponds to a transaction. The first column shows transaction completion status; if it shows a red '*x*', the transaction has an error.

To fix this error, you can use APM to replay the transaction, as follows:

. Click on the *Transaction* that has an error (This is designated through a red X)
. In the upper right corner there is a blue *replay* button. Before you click this button to replay the transaction you should be in communication with someone who can fix the error.
. Once the problem has been fixed you can click on the *replay* button.
. When this button is clicked it will disable itself and will let you know that the transaction is being replayed.
. Once the transaction has been replayed a blue replay circle will appear in the status of the transaction that you replayed.
. In order to see if the replayed transaction succeeded or failed click on the replayed transaction
. Then in the detail panel there will be a link to *View Replays* at the top.
. This will automatically filter the grid to only see transactions that have been replayed off of that original transaction.
. If the replayed transaction failed again, you can keep repeating this process until the replay goes through.
. You will always be able to get a full list of all of the transactions that are replayed from the same original by clicking the link in the detail panel of any of the transactions with the blue replay circle in their status.
. Once the replay has succeeded and you have a green check next to the replayed transaction.
. If for some reason you need to continue replaying the transaction you can do so with the same replay button as before, but you will be alerted with a warning before you can continue. This is to stop unnecessary replays from happening.

==== Common Errors or Confusing Errors

If there are an abnormal amount of similar errors we provide a way to look through all of them.

* The *Overview* at the top of the B2B Transactions Tab provides an overview of what has happened recently including how many errors have been detected that day.
* You can tell what kind of errors have happened by *hovering over different slices* of the pie.
* If you wish to inspect this further you can *click* on one of the *slices* to automatically sort the errors by this type.
** This will take you to our *errors tab* and automatically filter the results.
** This gives you access to all the same errors so you can look for a pattern among these in order to find a solution.
* This is useful for when transactions are failing but you can't find the solution by just looking at the transactions themselves.
* Being able to view the whole suite of errors will allow you to look for patterns in the data that otherwise would be hard to find.
* From here we provide a way to view the transactions that these errors are associated with through our *navigation buttons* in the top right.

==== Transport Problem Identification

* If you notice that you are getting a large number of your errors all from one type of transport you can sort your transmissions under the *Transmission tab* with a filter.
** This filter will allow you to look at all the same transport types and see the differences between those that failed and those that succeeded.
** You can find additional relevant information in the *detail panel* to the right.
* From here you can see what happened with individual transactions that these transmissions were involved in through a *navigation* click in the upper corner.
* This will allow you to follow transactions through their entire cycle, and if necessary *replay* them through their transactions on that tab.

Navigation is important in looking for patterns and correcting errors. That is why some of the more important filters will also follow you from tab to tab. This will allow you to look for commonalities in all of the types of data.

==== When a Partner Needs Records

A common scenario that you might run into is when a partner requires different information relating to a Transaction or a Transmission or a document. Here we will run through some of those scenarios. From these you should be able to figure out any other situation that might arise.

===== Finding Transmissions

* In the B2B Transaction Tab of the APM you can filter through the different tabs at the top to find Transactions, Transmissions, or Documents.
* If you were to select *Transmissions* you would be taken to a tab that only shows you received and sent transmissions.
* From there we provide a simple *filter* that takes an ID that the partner gave you relating to their query.
* Through our *detail panel* on the right, you can find what they are looking for and provide them with the relevant information.
* If the Partner is trying to find a specific ID then you can also get that to them with the copy button that we provide to the right of all long strings.
* Sorting and filtering through these grids is easy and can make your job really simple. Mess around with the table headers and the filters as you figure things out to find what you need.
** If you ever get lost you can use the *Clear Filters* button to get back to the full view.
* If you need to find out more information about a transmission or just where it exists in the larger scope you can click on the *Transaction* button in the upper right corner to view the transmission in context.

===== Finding Documents

* In the B2B Transaction Tab of the APM you can filter through the different tabs at the top to find Transactions, Transmissions, or Documents.
* If you were to select *Documents* you would be taken to a tab that only shows you documents.
* From there we provide some *filters*. Some of which take an ID that the partner gave you relating to their query.
* Through our *detail panel* on the right, you can find what they are looking for and provide them with the relevant information.
* If the Partner is trying to find a specific ID then you can also get that to them with the copy button that we provide to the right of all long strings.
* Sorting and filtering through these grids is easy and can make your job really simple. Mess around with the table headers and the filters as you figure things out to find what you need.
** If you ever get lost you can use the *Clear Filters* button to get back to the full view.
* If you need to find out more information about a document or just where it exists in the larger scope you can click on the *Transaction* button in the upper right corner to view the transmission in context.

== Working with Environments

=== Guido's section

. step 1
. step 2

