= Anypoint Partner Manager API

:keywords: Anypoint Partner Manager API, Partner Manager Query Language, PMQL

Clients will often want to interact with APM programmatically in order to automate their
processing tasks. APM has two distinct APIs that clients can call for this purpose. These APIs
are called _Trading Partner Management Service API_ (_TPM Service API_) and _Tracker API_. TPM
Service API allows you to manage partner-related configurations such as document definitions.
Tracker API gives you access to run-time data such as transactions and business documents.
Each API is described in RAML and can be downloaded from the following locations:

* TPM Service API: https://anypoint.mulesoft.com/b2b/tpm/api/definition/api.raml
* Tracker API: https://anypoint.mulesoft.com/b2b/tracker/api/definition/api.raml

Furthermore, you can experiment with the APIs through API Console at the following
locations:

* TPM Service API: https://anypoint.mulesoft.com/b2b/tpm/api/console
* Tracker API: https://anypoint.mulesoft.com/b2b/tracker/api/console

== Partner Manager Query Language

Resources having the _Searchable_ trait can be queried through the _q_ query parameter
using Partner Manager Query Language (PMQL). PMQL is a SQL-like language giving you
the ability to search for resources by fields other than the resource ID. Before diving into the syntax,
here are a few examples of queries expressed in PMQL:
[source]
name == 'AS2 Receive'

[source]
documentPropertyValue =like= 'MuleSoft%'

[source]
processedAt > '2005-04-29 00:00:00' and processedAt <= '2005-04-29 00:00:01'

[source]
standard =in= ('X12', 'EDIFACT') and (direction == 'INBOUND' or messageType=='PO') and processedAt >= '2000-01-01 00:00:00'

A PMQL expression is composed of one or more comparisons, related to each other with logical operators:

* Logical AND: *and*
* Logical OR: *or*

By default, the AND operator takes precedence (i.e., it is evaluated before any OR operators are).
However, a parenthesized expression can be used to change the precedence, yielding whatever
the contained expression yields.

Comparison is composed of a selector, an operator and an argument:
[source]
comparison = selector, comparison operator, arguments

==== Selector

A selector identifies a field of the resource representation to filter by. It can be
any non-empty Unicode string that does not contain reserved characters (see below) or a white space.

==== Comparison Operator

A comparison operator can by any one of the following:

* Equal to: *==*
* Not equal to: *!=*
* Less than: *<*
* Less than or equal to: *<=*
* Greater than operator: *>*
* Greater than or equal to: *>=*
* In: *=in=*
* Like: *=like=*

==== Argument

An argument can be a single value, or multiple values in parenthesis separated by comma.
Multiple values can only be used with operators that support such argument types like
the _IN_ operator. An argument value that does not contain any reserved character or a
white space can be unquoted, other arguments must be enclosed in single or double quotes.
