= Anypoint Partner Manager User's Guide

:keywords: b2b, portal, partner, manager

Anypoint Partner Manager (APM) is a full-featured, web-browser-based graphical user interface you can use to:

* link:/anypoint-b2b/configure-trading-partners[Configure Trading Partners]
* link:/anypoint-b2b/monitor-b2b-transactions[Monitor B2B Transactions]

== Getting Started

. Using the web browser of your choice, navigate to the APM URL. Typically, this URL is established during the provisioning process; if you don't know it, see your Mule representative.
+
The B2B Transactions page appears, open to Overview for Today.
+
. To configure the home partner or a trading partner, or to edit the configuration of either, see link:/anypoint-b2b/configure-trading-partners[Configure Trading Partners].
+
NOTE: You must configure the _Home Partner_ (a specific type of trading partner, typically your company) to use APM.
+
To monitor B2B transactions, see link:/anypoint-b2b/monitor-b2b-transactions[Monitor B2B Transactions].





.
