= Company information

== Enter Company information

=== Add a new partner

. On the Company information Page, if you are adding a new partner, enter the name of the partner in the *Company Name* box.
. Click the *Save* bar.


== Enter contact information

. The name of the partner you selected on the Trading Partners Page (or added on this page, as a new partner) appears in the *Company Name* box. If appropriate, you can change it.
. In the *Contacts* section of the *Company information* page, enter the following:

** *Contact type* +
(In the dropdown listbox, select *Technical*, *Business*, or *Both*.)
. After you enter a contact type, you can enter the following contact-specific information. All fields are link:/anypoint-b2b/anypoint-partner-manager-glossary#sects[standard APM field format].

** *First Name*
** *Last Name*
** *Title*
** *E-mail*
** *Office Phone*
** *Mobile Phone*
** *Fax*
** *Address Line 1*
** *Address Line 2*
** *City*
** *State*
** *Postal Code*
** *Country*

. Click *Save* to save the values you entered in the previous steps.
