
= Configure Trading Partners

:keywords: b2b, portal, partner, manager


To configure a trading partnership using Anypoint Partner Manager (APM), you must:

. Set up the _Home Partner_. The Home Partner is you - that is, the company licensing Anypoint B2B.
+
NOTE: The Home Partner may have been set up during the provisioning process. If so, its name appears at the top of the Name list on the Trading Partner page, identified as *Your company*.

. Set up a trading partner


== Getting Started

. Start APM. In the left-hand navigation pane, click *Trading Partners*.
. On the Trading Partners Page:
.. To add or edit settings for the Home Partner (your company), in the Name table, click the name of your company
.. To add a new partner, click *New Partner*.
.. To edit settings for an existing trading partner, in the Name table, click the name of the partner.
. The Company information page appears.
+
To add or edit company information, see <<Company information>>.
+
To add or edit settings for any of the following, click the page name in the left-hand navigation pane. See the corresponding section for information about the settings on the page.

<<Partners>>::
* <<Company information>>
* <<Identifiers>>
* <<Administration>> options (Home partner only)

Format Defaults::
* <<X12>>
* <<EDIFACT>>
* <<CSV>>

Configuration::
* <<Document Types>>
* <<Endpoints>>
* <<Maps>>
* <<Channels>>
* <<Routes>>

=== Saving settings

On each page, a red bar appears on the lateral margins of boxes that correspond to required settings. When each required setting on a given page contains a valid value, the *Save* box at the top of the page is enabled.

To save new settings, click *Save*.

== Partners

=== Company information

==== Enter Company information

. On the Company information Page, the name of the partner you selected on the Trading Partners Page appears. If appropriate, you can change it.

==== Enter contact information

. In the *Contacts* section of the *Company information* page, enter the following:

** *Contact type* +
(In the dropdown listbox, select *Technical*, *Business*, or *Both*)
. After you enter a contact type, you can enter the following contact-specific information:
** *First Name*
** *Last Name*
** *Title*
** *E-mail*
** *Office Phone*
** *Mobile Phone*
** *Fax*
** *Address Line 1*
** *Address Line 2*
** *City*
** *State*
** *Postal Code*
** *Country*

. Click *Save* to save the values you entered in the previous steps.

=== Identifiers

==== AS2 Identity Settings

. In the *AS2 Identity* box, enter the trading partner-assigned name associated with this trading partner’s Production AS2 ID.
. Click *Choose File* to select and upload this trading partner’s AS2 Certificate.
+
The *Certificate Name*, *Expiration* and *Thumbprint* fields populate when an AS2 certificate is uploaded.

=== Administration

If you select the Home partner in <<Getting Started>>, the Administration tab appears in the left-hand navigation pane.

==== API Key

===== Create a new API Key
. In the *API Key* section, click *Create a new API key*. The API Application Program Interface (API) Key is a 32-bit alphanumeric universal unique identifier (UUID) string that APM generates for you; you use it to access the Anypoint B2B API.

WARNING: Store your API key in a secure location. If you lose it, you will need to create a new API key. APM does not store your API key.

==== Environments

The information in this section is required when using link:/anypoint-b2b/partner-manager-connector[Partner Manager Connector].

== Format Defaults

You can provide defaults for these formats:

* <<X12>>
* <<EDIFACT>>
* <<CSV>>

=== X12

X12 standards define the structure, format, and content of business transactions conducted through Electronic Data Interchange (EDI) and are used in conjunction with AS2 or FTPS as transport for these documents.

==== Enter X12 Identity Settings

===== Interchange ID qualifier - ISA
Value of the EDI ID Qualifier for your trading partner. Some of the most common values are listed below. If you choose *Custom*, you can define the trading partner's EDI X12 qualifier.

Required?::
Yes

Valid values::

* `01 (DUNS Number)`
* `08 (UCC EDI Number)`
* `12 (Phone Number)`
* `14 (DUNS Number plus Suffix Number)`
* `ZZ (Mutually Defined)`
* `Custom`

Default::

* No default provided

---

===== Interchange ID - ISA
EDI X12 ISA ID for your trading partner; can be up to 15 characters. Your trading partner will supply you with the proper EDI X12 Interchange ID.

Required?::
Yes

Valid values::

Alphanumeric

Default::

No default provided

---

==== Enter X12 Settings Inbound (Read)

===== Envelope Headers (ISA)

===== Auth. Info. Qualifier (ISA 01)
Most common value is *00*; rarely is another used.

Required?::
No

Valid values::

* `00`
* `01`
* `02`
* `03`
* `04`
* `05`
* `06`

Default::

`00`

---

===== Authorization Information (ISA 02)
Enter a value if appropriate for your organization.

NOTE: If the value in the previous box (ISA 01) is `00` (the default), then this box is disabled.

Required?::
No

Valid values::
Alphanumeric

Default::
Defaults to ten blank spaces

---

===== Security Inf. Qualifier (ISA 03)
Select a value from the dropdown listbox (if appropriate for your organization).

Required?::
No

Valid values::

* `00`
* `01`

Default::

`00`

NOTE:	If the value in (ISA 03) is 01, then a valid password value is required in ISA 04.

---

===== Security Information (ISA 04)
Enter a value if appropriate for your organization.

NOTE: If the value in the previous box (ISA 03) is `00` (the default), then this box is disabled

Required?::
No

Valid values::

Alphanumeric

Default::
Defaults to ten blank spaces

---

===== Interchange sender ID qualifier (ISA 05)
This value populates based on the value saved in <<Interchange ID qualifier - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID qualifier - ISA>>)

---

===== Interchange sender ID (ISA 06)
This value populates based on the value entered and saved in <<Interchange ID - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID - ISA>>




===== Interchange receiver ID qualifier (ISA 07)
This value populates based on the value entered and saved in <<Interchange ID qualifier - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID qualifier - ISA>>)

---

===== Interchange receiver ID (ISA 08)
This value populates based on the value entered and saved in <<Interchange ID - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID - ISA>>)

---

===== Interchange Control Version (ISA 12)
Identifies the X12 version this partner uses.

Required?::
No

Valid values::

* `00401 (4010)`
* `00501 (5010)`

Default::

`00401 (4010)`

---

===== Parser Settings (Failure conditions)

* `Fail document when value length outside allowed range`
* `Fail document when invalid character in value`
* `Fail document if value is repeated too many times`
* `Fail document if unknown segments are used`
* `Fail document when segments are out of order`
* `Fail document when unused segments are included`
* `Fail document when too many repeats of a segment`
* `Fail document when unused segments are included`

Each of these options identifies a condition for which APM can fail an inbound  document from a trading partner. If any of these options selected, and an X12 document meets the condition in a selected option, a 997 message stating a failure will be sent.

===== Parser Settings (Other options)

Require 997::
If selected, a 997 message will be sent regardless of whether or not an error condition is met.

Generate 999::
If a 999 acknowledgement is needed check this box. The default X12 acknowledgement will be 997.

====== Character Set and Encoding

Drop-down listbox enabling choice of three character sets.

Valid values::

* *Basic* +
This character set includes:
** Uppercase letters `A` through `Z`
** Digits `0` through `9`
** Special characters +
`! “ & ’ ( ) * + , - . / : ; ? =`
** The character created by pressing the space bar.

* *Extended* +
This character set includes:
** All characters in the Basic character set
** Lowercase letters `a` through `z`
** Select language characters
** Other special characters: +
`% @ [ ] _ { } \ | < > ~ # $`

* *Unrestricted* character set - includes all characters.

Default::
`Basic`

===== Control Number Settings

These settings, when selected, require unique inbound *ISA 13*, *GS 06* and *ST 02* control numbers on all inbound documents for a trading partner.

* `Require unique ISA control numbers (ISA 13)`
* `Require unique GS control numbers (GS 06)`
* `Require unique transaction set control numbers (ST 02)`

==== Enter X12 Settings - Outbound (Write)

===== Envelope Headers (ISA)

The fields in this section enable you to set envelope header options.

===== Auth Info. Qualifier (ISA 01)
The most common value is `00`; rarely is another used.

Required?::
No

Valid values::
* `00`
* `01`
* `02`
* `03`
* `04`
* `05`
* `06`

Default::

`00`

---

===== Authorization Information (ISA 02)
NOTE: If the value in the previous box (ISA 01) is `00` (the default), then this box is disabled.

Required?::
No

Valid values::

Alphanumeric

Default::

Ten blanks

---

===== Security Inf. Qualifier (ISA 03)
In the dropdown listbox, enter a value for this trading partner.

Required?::
Yes

Valid values::

* `00`
* `01`

Default::

`00`

NOTE:	If the value in (ISA 03) is 01, then a valid password value is required in ISA 04.

---

===== Security Information (ISA 04)

NOTE: If the value in the previous box (ISA 03) is `00` (the default), then this box is disabled.

Required?::
No

Valid values::

Alphanumeric

Default::

None

---

===== Interchange sender ID qualifier (ISA 05)
This value populates based on the value saved in <<Interchange ID qualifier - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID qualifier - ISA>>)

---

===== Interchange sender ID (ISA 06)
This value populates based on the value entered and saved in <<Interchange ID - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID - ISA>>)


---

===== Interchange receiver ID qualifier (ISA 07)
This value populates based on the value entered and saved in <<Interchange ID qualifier - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID qualifier - ISA>>)

---

===== Interchange receiver ID (ISA 08)
This value populates based on the value entered and saved in <<Interchange ID - ISA>>

Required?::
Yes (must be entered and saved in <<Interchange ID - ISA>>)

---

Repetition separator character (ISA 11)::
Drop-down listbox that enables you to choose a repetition character.

Required?::
No

Valid values::

* `U`
* `^`
* `+`

Default::

`^`

---

===== Interchange Control Version (ISA 12)
Drop-down listbox that enables you to choose which X12 version you use. If you choose `Custom`, another box appears in which you can enter an numeric value of your choice. Currently `004010` and `005010` are the supported X12 versions.

Required?::
No

Valid values::

* `004010 (4010)`
* `005010 (5010)``
* `Custom`

Default::

`004010 (4010)`

---

===== Request Interchange Acknowledgements (ISA 14)
Drop-down list that enables you to choose whether or not a 997 message is required.

Required?::
Yes

Valid values::

* `0 (997 not required)`
* `1 (997 required)`

Default::

* `1 (997 required)`

---

===== Default Interchange usage indicator (ISA 15)
Indicates whether  you are in Test or Production with this trading partner.


Required?::
Yes

Valid values::

* `Production`
* `Test`

Default::

`Production`

---

===== Component element separator character (ISA 16)
Indicates the character used to separate data.
"*>*" is a commonly used character.


Required?::
No

Valid values::
Most special characters excluding numbers; must be a single character.

Alphanumeric

Default::

`>`

---

==== Group Headers (GS)

==== Version identifier code suffix (GS 08)
Enables you to identify the X12 version being used in the outbound message.

Required?::
Yes

Valid values::

12 characters, alphanumeric

Default::

`004010`

---

===== Terminator/Delimiter

====== Segment terminator character
Identifies the end of X12 segment.
"*~*" is a commonly used terminator character.

Required?::
 No

Valid values::
Most special characters; must only be a single character only.

Default::
 `~`

---

===== Data Element Delimiter
Separates data elements from each other.
One of the most common values used in this field is “***”


Required?::
No

Valid values::

Most special characters except whole numbers; must be a single character only.

Default::

`*`

---

===== String substitution character
Character to be used to replace invalid characters in string values.
Sends `null` to the server if has no value

Required?::
No

Valid values::
Most special characters except whole numbers; must be a single character only.

Default::

None provided

---

===== Character Set and Encoding

====== Character Set
Drop-down listbox enabling choice of three character sets.

Valid values::

* *Basic* +
This character set includes:
** Uppercase letters `A` through `Z`
** Digits `0` through `9`
** Special characters +
`! “ & ’ ( ) * + , - . / : ; ? =`
** The character created by pressing the space bar.

* *Extended* +
This character set includes:
** All characters in the Basic character set
** Lowercase letters `a` through `z`
** Select language characters
** Other special characters: +
`% @ [ ] _ { } \ | < > ~ # $`

* *Unrestricted* character set - includes all characters.

Default::
`Basic`

---

====== Character Encoding
Drop-down listbox enabling you to select character encoding.

Required?::
Yes

Valid values::

* `ASCII`
* `ISO-8859-1`
* `IBM 1047`

Default::

`ASCII`

---

====== Line ending between segment
Drop-down listbox that enables you to specify the type of line-ending you want on your outbound data
Options include Carriage return (`CR`), Line feed (`LF`), Line feed carriage return (`LFCR`) or none.


Required?::
Yes

Valid values::

* `None`
* `CR`
* `LF`
* `LFCR`

Default::

`None`

---

==== Control Number Settings

===== Initial Interchange control number (ISA 13)
You can use this box to specify a whole number to appear in the ISA control number that begins your outbound documents with a Trading Partner. If a single digit is specified it will be padded with leading zeros.


Required?::
 No

Valid values::
 Alphanumeric

Default::
 `1`

---

===== Initial GS control number (GS 06)
You can use this box to specify a whole number to appear in the GS control number that begins your outbound documents with a Trading Partner. If a single digit is specified it will be padded with leading zeros.


Required?::
 No

Valid values::
 Alphanumeric

Default::
 `1`

---

===== Initial transaction set control numbers (ST 02)
You can use this box to specify a whole number to appear in the ST control number that begins your outbound documents with a Trading Partner. If a single digit is specified it will be padded with leading zeros.


Required?::
 No

Valid values::
 Alphanumeric

Default::
 `1`

---

===== Implementation Convention reference (ST 03)
Used in the Healthcare space in X12 versions 5010 and above.

Required?::
No

Valid values::

Alphanumeric

Default::

None provided

---

===== Require unique GS control numbers (GS06)
Select this checkbox to require unique GS control numbers.

===== Require unique transaction set control numbers (ST02)
Select this checkbox to require unique transaction set control numbers.

=== EDIFACT

EDIFACT (Electronic Data Interchange For Administration, Commerce and Transport) provides a set of standard messages which allow multi-country and multi-industry business document exchanges. EDIFACT is widely used across Europe.

==== EDIFACT Identity Settings

===== Interchange ID qualifier - UNB
Enter your trading partners EDIFACT Interchange ID qualifier here. Choose from commonly used EDIFACT qualifiers or enter a custom qualifier.


Required?::
No

Valid values::

* `8`
* `9`
* `12`
* `14`
* `16`
* `ZZZ`
* `Custom`


Default::

None provided

---

====== Interchange ID - UNB
Enter your trading partners EDIFACT Interchange ID here.

Required?::
No

Valid values::

Alphanumeric, 35 character maximum

Default::

None provided

---

===== Enter EDIFACT Settings - Inbound (Read)

====== Header Settings (UNB)

====== Request Acknowledgements - UNB 9
This drop-down setting correlates to the EDIFACT document CONTRL. This document acts as a functional acknowledgement accepting or rejecting the documents sent.

Required?::
Yes

Valid values::

* `1 (Acknowledgement requested)`
* `2 (Confirmation of receipt only)`


Default::

None provided

---

====== Interchange Sender ID (UNB 2.1)
EDIFACT Interchange ID for your EDIFACT trading partner; auto-populated with the value entered in <<Interchange ID - UNB>>. If no value appears in this box, you must enter a value in <<Interchange ID - UNB>>.

---

====== Interchange sender ID qualifier (UNB 2.2)
Trading partners EDIFACT qualifier, auto-populated from <<Interchange ID qualifier - UNB>>. If no value appears in the box, you must enter a value in <<Interchange ID qualifier - UNB>>.

---

====== Interchange Receiver ID (UNB 3.1)
Your company’s EDIFACT Interchange Receiver ID; auto-populated from <<EDIFACT Identity Settings>>. If no value appears in the box, you must enter a value in <<EDIFACT Identity Settings>>.

---

====== Interchange receiver ID qualifier (UNB 3.2)
Auto-populated from <<EDIFACT Identity Settings>>. If no value appears in the box, you must enter a value in <<EDIFACT Identity Settings>>.

---

====== Parser Settings

There are eight optional parser settings that can be chosen for your trading partners inbound documents. The fields are listed below. The expected behavior if these options are checked is a CONTRL stating a failure will be sent for the condition.

*	Fail document when value length outside allowed range

*	Fail document when invalid character in value

*	Fail document if value is repeated too many times

*	Fail document if unknown segments are used

*	Fail document when segments are out of order

*	Fail document when unused segments are included

*	Fail document when too many repeats of a segment

====== Terminator/Delimiter settings

These settings specify which special characters a trading partner wants to use as separators and terminators in the EDIFACT data. The min/max for this field is 1. All these fields are editable.

Data element separator character::
The default value is “+”

Component element separator character::
The default value is “:”

Repetition separator character::
The default value is “*”

Segment terminator character::
The default value is “ ‘ “

Release character::
The default value is “? “

String substitution character::
Character to be used to replace invalid characters in string values; no default given.

====== Control Number settings

These settings if checked will require unique inbound control numbers on all inbound documents for this trading partner.

*	Require unique Message Reference Numbers
*	Require unique Interchange Control Numbers
*	Require unique Group Numbers

===== Enter EDIFACT Settings - Outbound (Write)

====== Header Settings (UNB)

====== Interchange Sender ID (UNB 2.1)
This field is the EDI Interchange ID for your Company. This is auto populated from
<<EDIFACT Identity Settings>>.

---

====== Interchange sender ID qualifier (UNB 2.2)
This is a field for your EDIFACT Interchange sender ID qualifier. This is auto populated from
<<EDIFACT Identity Settings - Home Org>>.

 ---

====== Interchange Receiver ID (UNB 3.1)
This field is your trading partners EDIFACT Interchange Receiver ID. This is auto populated from
<<Interchange ID - UNB>>.

 ---

====== Interchange receiver ID qualifier (UNB 3.2)
This field is your trading partners EDIFACT Interchange Receiver ID qualifier. This is auto populated from
<<Interchange ID qualifier - UNB>>.

 ---

====== Request Acknowledgements (UNB 9)
Indicates if your trading partner requires EDIFACT document acknowledgements; correlates to the EDIFACT document CONTRL.

Required?::
No

Valid values::

* `1 (Acknowledgement requested)`
* `2 (Confirmation of receipt only)`

Default::

None provided

---

====== Default test indicator (UNB 11)
Checkbox; select if you are testing EDIFACT documents (Outbound) with this trading partner.

Required?::
No

Default::
Not selected

---

====== Syntax version (UNB 1.2)

Required?::
No

Valid values::
* `2`
* `3`
* `4`
Default::

`4`

---

====== Parser Settings (checkboxes)

* *Always send UNA*
* *Fail document when invalid character in value*

====== Terminator/Delimiter

These settings specify which special characters your Company wants to use with a trading partner to separate and use as terminators in the EDIFACT data. The min/max for this field is 1. All these fields are editable.

Data element separator character::
The default value is “+”

Component element separator character::
The default value is “:”

Repetition separator character::
The default value is “*”

Segment terminator character::
The default value is “ ‘ “

Release character::
The default value is “? “

Line ending between segments::
Drop-down box that enables you  to specify on your outbound data you
would like CR (Carriage return) or Line feed (LF) or Line feed carriage return (LFCR) or none.

String substitution character::
Character to be used to replace invalid characters in string values; no default given.

====== Character Set and Encoding

Message character encoding

Required?::
No

Valid values::

* `ONOA (ISO 646)`
* `UNOB (ISO 646)`
* `UNOC (ISO 8859-1)`
* `UNOD (ISO 8859-2)`
* `UNOE (ISO 8859-5)`
* `UNOF (ISO 8859-7)`
* `UNOG (ISO 8859-3)`
* `UNOH (ISO 8859-4)`
* `UNOI (ISO 8859-6)`
* `UNOJ (ISO 8859-8)`
* `UNOK (ISO 8859-9)`
* `UTF8`

Default::
`UNOA (ISO 646)`


====== Control Number Settings

====== Initial Interchange Control Reference
A whole number can be specified in the Initial Interchange Control Reference number to begin on your outbound documents with this Trading Partner. If a single digit is specified it will be padded with leading zeros.

Required?::
No

Valid values::

Alphanumeric

Default::

`None`

---

====== Initial Message Reference Number

 A whole number can be specified to begin on your outbound documents with this Trading Partner. If a single digit is specified it will be padded with leading zeros.


Required?::
 No

Valid values::

 Alphanumeric

Default::

 `None`

 ---

====== Initial Group Reference
 A whole number can be specified to begin on your outbound documents with this Trading Partner. If a single digit is specified it will be padded with leading zeros.


Required?::
 No

Valid values::
Alphanumeric

Default::
 `None`

 ---

 Checkbox options:

 *	Use groups
 *	Use unique Message Reference Numbers
 *	Use unique Group Reference Numbers

=== CSV


==== Enter CSV Settings - Inbound (Read)

===== Delimiter

Add doc

---

===== Has Header Row

Add doc

---

==== Enter CSV Settings - Outbound (Write)

===== Delimiter

Add doc

---

===== Has Header Row

Add doc

== Configuration

You can configure:

* <<Document Types>>
* <<Endpoints>>
* <<Maps>>
* <<Channels>>
* <<Routes>>

=== Document Types

==== Add a new document

Click *New*. The Document page appears.

===== Name

This field is populated based on the partner name and the value you enter in the *Format* field.

===== Format

Available format options depend on the choice you make for <<Standard>>

====== Standard

Select a standard from the dropdown listbox. Based on the standard you select, the appropriate settings options appear. For guidance on these settings, click the link that corresponds to the standard you choose in *Valid values*.

Required?::
No

Valid values::

* `X12` (see <<Format (X12)>>)
* `EDIFACT` (see <<Format (EDIFACT)>>)
* 'CSV' (see <<Format (CSV)>>)
* 'XML' (see <<Format (XML)>>)
* 'JSON' (see <<Format (JSON)>>)

Default::

None

===== Format (X12)

====== Version

Select a value from the dropdown listbox, or enter a different value.

Required?::
Yes

Valid values::

* `4010`
* `5010`

Default::

None

---

====== Message Type

Select a value from the dropdown listbox, or enter a different value.

Required?::
Yes

Valid values::

See listbox

Default::

None

---

====== Default Checkboxes

Select or deselect these checkboxes in order to use default Outbound X12, Inbound X12, or both for partner.

Default::

Selected

---

===== Schema

Click *Choose File*, then choose a file from the selection window.

Required?::

Documentation in development

---

===== Document Properties

====== Add new document properties

Click *New*. The *Document Properties* section appears.

====== Label

Select a value from the listbox.

Required?::
No

Valid values::

Documentation in development

Default::

None

====== Path

Type a value in the box.

Required?::
No

Valid values::

Documentation in development

Default::

None

===== Format (EDIFACT)

====== Version

Select a value from the dropdown listbox, or enter a different value.

Required?::
Yes

Valid values::

Alphanumeric

Default::

None

---

====== Message Type

Select a value from the dropdown listbox, or enter a different value.

Required?::
Yes

Valid values::

See listbox

Default::

None

---

====== Default Checkboxes

Select or deselect these checkboxes in order to use default Outbound EDIFACT, Inbound EDIFACT, or both for partner

Default::

Selected

---

===== Schema

Click *Choose File*, then choose a file from the selection window.

Required?::



---

===== Document Properties

====== Add new document properties

Click *New*. The *Document Properties* section appears.

====== Label

Select a value from the listbox.

Required?::
No

Valid values::

Documentation in development

Default::

None

====== Path

Type a value in the box.

Required?::
No

Valid values::

Documentation in development

Default::

None

===== Format (CSV)

====== Version

Select a value from the dropdown listbox, or enter a different value.

Required?::
No

Valid values::

* `4010`
* `5010`

Default::

None

---

====== Message Type

Select a value from the dropdown listbox, or enter a different value.

Required?::
Yes

Valid values::

See listbox

Default::

None

---

====== Use default Inbound CSV for partner

This checkbox is enabled if values have been chosen for this partner in <<CSV>>.

Default::

Selected (if enabled)

====== Use default Outbound CSV for partner

This checkbox is enabled if values have been chosen for this partner in <<CSV>>.

Default::

Selected (if enabled)

====== Schema

Click *Choose File*, then choose a file from the selection window.

Required?::

Documentation in development

---

===== Document Properties

====== Add new document properties

Click *New*. The *Document Properties* section appears.

====== Label

Select a value from the listbox.

Required?::
No

Valid values::

Documentation in development

Default::

None

---

====== Path

Type a value in the box.

Required?::
No

Valid values::

Documentation in development

Default::

None

==== Format (XML)

---

===== Namespace

Type a value in the box.

Required?::
No

Valid values::

Documentation in development

Default::

None

---

===== Root Node

Type a value in the box.

Required?::
Yes

Valid values::

Documentation in development

Default::

None


===== Schema

Click *Choose File*, then choose a file from the selection window.

Required?::

Documentation in development

---

===== Document Properties

====== Add new document properties

Click *New*. The *Document Properties* section appears.

====== Label

Select a value from the listbox.

Required?::
No

Valid values::

Documentation in development

Default::

None

====== Path

Type a value in the box.

Required?::
No

Valid values::

Documentation in development

Default::

None

==== Format (JSON)

===== Message Type

<insert description>

Required?::
Yes

Valid values::

Documentation in development

Default::

None


===== Schema

Click *Choose File*, then choose a file from the selection window.

Required?::

Documentation in development

---

===== Document Properties

====== Add new document properties

Click *New*. The *Document Properties* section appears.

====== Label

Select a value from the listbox.

Required?::
No

Valid values::

Documentation in development

Default::

None

===== Path

Type a value in the box.

Required?::
No

Valid values::

Documentation in development

Default::

None

=== Endpoints

If you are working with the Home Partner, you can add a new Endpoint or change an existing Endpoint.

==== Add a new Endpoint

. On the Endpoints page, click *New*.
. The Endpoint page appears.

If you are working with other partners, you can change an existing Endpoint, but you cannot add a new Endpoint.


==== Name

Name for this endpoint

Required?::
No

Valid values::

Alphanumeric

Default::

None

==== Protocol

Protocol for this endpoint

Required?::
No

Valid values::

* 'AS2'
* 'FTPS'
* 'HTTP'

Default::

None

==== Type

Type of endpoint

Required?::
No

Valid values::

* 'SEND'
* 'RECEIVE'

Default::

None

==== Default for _partner_ checkbox

Select this box if you want the choices you have made for this endpoint to apply to all endpoints for this partner.

include::endpoint-as2-send.adoc[More information]

include::endpoint-as2-receive.adoc[More information]

include::endpoint-ftps-send.adoc[More information]

include::endpoint-ftps-receive.adoc[More information]

include::endpoint-https-send.adoc[More information]

include::endpoint-https-receive.adoc[More information]



=== Maps

==== Name

Type a value in the box, or click *Auto Fill*.

Required?::
No

Valid values::

Documentation in development

Default::

None

==== Source Document, Target Document

When you click either the Source Document or the Target Document box, the Pick document selection page appears. You can select from available documents.

==== Mapping Type

Select a mapping type from the dropdown listbox.

Required?::
No

Valid values::

* 'Dataweave'
* 'XSLT'

Default::

None

==== Select file containing map definition

Click *Choose File*, then choose a file from the selection window.


Required?::

Documentation in development

Valid values::

<restrictions on file type? what does "Custom Files" mean?>

Default::

None

=== Channels

==== To add a new Channel

. On the Channel page, click *New*.
. The Channel page appears.

==== Name

<insert description>

Required?::
No

Valid values::

<values>

Default::

<value | None>


==== Type

<insert description>

Required?::
Yes

Valid values::

<values>

Default::

<value | None>


==== Document

<insert description>

Required?::
No

Valid values::

<values>

Default::

<value | None>


==== Document Map

<insert description>

Required?::
No

Valid values::

<values>

Default::

<value | None>


==== Endpoint

<insert description>

Required?::
No

Valid values::

<values>

Default::

<value | None>

=== Routes

. On the Routes page, click *New*.
. The Route page appears.

==== Source Channel, Target Channel

When you click either the Source Channel or the Target Channel box, the Pick channel selection page appears. You can make the following selections:

===== Partnership

<insert description>


Required?::
No

Valid values::

Documentation in development

Default::

None

===== Standard

<insert description>

Required?::
No

Valid values::

Documentation in development

Default::

None

===== Version

<insert description>

Required?::
No

Valid values::

Documentation in development

Default::

None

===== Message Type

<insert description>

Required?::
No

Valid values::

Documentation in development

Default::

None

==== Type

Select a type from the dropdown listbox.

Required?::
No

Valid values::



Default::

None

==== Transport

<insert description>

Required?::
No

Valid values::

<values>

Default::

<value | None>

include::more-information[More information]
