

= Configure Trading Partners

:keywords: b2b, portal, partner, manager


To configure a trading partnership using Anypoint Partner Manager (APM), you must:

. Set up the _Home Partner_. The Home Partner is you: That is, the company that is licensing Anypoint B2B.
+
NOTE: The Home Partner may have been set up during the provisioning process. If so, its name appears at the top of the Name list on the Trading Partner page, identified as *Your company*.

. Set up a trading partner


== Getting Started

. Start APM. In the left-hand navigation pane, click *Trading Partners*.
. On the Trading Partners Page:
.. To add or edit settings for the Home Partner (your company), in the Name table, click the name of your company
.. To add a new partner, click *New Partner*.
.. To edit settings for an existing trading partner, in the Name table, click the name of the partner.
. The Company information page appears.
+
To add or edit company information, see link:/anypoint-b2b/company-information[Company Information].
+
To add or edit settings for any of the following, click the page name in the left-hand navigation pane. See the corresponding section for information about the settings on the page.

* link:/anypoint-b2b/partners[Partners]
** link:/anypoint-b2b/company-information[Company Information]
** link:/anypoint-b2b/identifiers[Identifiers]
** link:/anypoint-b2b/administration[Administration] (Home partner only)
** link:/anypoint-b2b/error-codes[Error Codes]
** link:/anypoint-b2b/security[Security]

* link:/anypoint-b2b/format-defaults[Format Defaults]
** link:/anypoint-b2b/x12-settings[X12 Settings]
** link:/anypoint-b2b/edifact-settings[EDIFACT]
** link:/anypoint-b2b/csv-settings[CSV Settings]

* link:/anypoint-b2b/configuration[Configuration]
** link:/anypoint-b2b/document-types[Document Types]
** link:/anypoint-b2b/endpoints[Endpoints]
** link:/anypoint-b2b/maps[Maps]
** link:/anypoint-b2b/channels[Channels]
** link:/anypoint-b2b/routes[Routes]

== Saving settings

On each page, a red bar appears on the lateral margins of boxes that correspond to required settings. When each required setting on a given page contains a valid value, the *Save* box at the top of the page is enabled.

To save new settings, click *Save*.
