= SFTP Receive settings


== Server information

[%header,cols="3s,7a"]
|===
|Name |Description

|Host
| <doc> +
Type: link:/anypoint-b2b/anypoint-manager=gloassary[Standard APM field format] +
Required: Yes +
Default: None

|Port |&nbsp; +
Type: link:/anypoint-b2b/anypoint-manager=glossary[Standard APM field format] +
Required: Yes +
Default: None

|Path | &nbsp; +
Type: link:/anypoint-b2b/anypoint-manager=glossary[Standard APM field format] +
Required: No +
Default: None

|Username | &nbsp; +
Type: link:/anypoint-b2b/anypoint-manager=glossary[Standard APM field format] +
Required: Yes +
Default: None

|Password | &nbsp; +
Type: link:/anypoint-b2b/anypoint-manager=glossary[Standard APM field format] +
Required: Yes +
Default: None

|===

== Timing

[%header,cols="3s,7a"]
|===
|Name |Description
|Polling frequency |&nbsp; +
Type: link:/anypoint-b2b/anypoint-manager=glossary[Standard APM field format] +
Required: No +
Default: None

|File Age |&nbsp; +
Type: link:/anypoint-b2b/anypoint-manager=glossary[Standard APM field format] +
Required: No +
Default: None

|Size Check Wait Time |&nbsp; +
Type: link:/anypoint-b2b/anypoint-manager=glossary[Standard APM field format] +
Required: No +
Default: None

|===

== Next steps

* link:/anypoint-b2b/ftps-send[Go back to the previous configuration page]
* link:/anypoint-b2b/endpoint-https-receive[Move on to the next configuration page]
* See link:/anypoint-b2b/more-information[More information] for links to these and other Anypoint B2B pages
