= AS2 Receive settings

[width="100%", cols="3s,7a",options="header"]
|===
|Setting |Description

| URL
| URL you  expose in MuleSoft to receive messages from a trading partner. Enter the URL, including the port.

Required?::
Yes, if AS2 is the transport protocol.

Example::
`www.midsizesupplier.com:8080`



| MDN Subject
| Subject of the MDN (Message Disposition Notification) sent

Required?::
Yes

Valid values::
Alphanumeric

Default::
`Message Disposition Notification`



| Preferred Digest Algorithm
| MIC algorithm for use in signing the returned receipt.

Required?::
Yes

Valid values::
`None` +
`SHA1` +
`MD5`

Default::
`None`



| Checkbox options

| Compress::
Compresses message-size

Message Encrypted::
Adds an encryption wrapper around the document, signature, and compression payloads

Message Signed::
Adds a signature wrapper around the document payload

|===

////
MDN Required::
An Async MDN will return the MDN to the URL at a later time for files sent if an MDN is required. If you are using Async MDN, enter the URL and port to which it should be sent.

NOTE: If this checkbox is selected, the *Require Receipt for Unsupported Digest Algorithm* and *Require Receipt for Unsupported Signature Format* checkboxes appear.

MDN Signed::
Ensures trading partner validation and security
////

== Next steps

* link:/anypoint-b2b/endpoint-as2-send[Go back to the previous configuration page]
* link:/anypoint-b2b/endpoint-ftps-send[Move on to the next configuration page]
* See link:/anypoint-b2b/more-information[More information] for links to these and other Anypoint B2B pages
