= APM in Action

== Before You Begin

=== Verify Your Access to Anypoint Studio and Anypoint Partner Manager

=== Verify Your APM Setup

==== Environment

==== Tenant

==== Business Group

==== Username

== Download Project Materials

=== Zip

==== Routing Engine

==== Persistence Flows

==== Configuration

==== Maps

==== Sample messages

==== Certificates

==== Partner Simulator

==== Postman Collection

== Configure Transactions

=== Configure Partners

==== Supplier

Home Org aka Your Company

==== Buyer

Sends 850 to Supplier

=== Configure Document Types

==== Source Doc

Partner Configuration/Buyer/Document Types/New
Standard: X12
Version: 4010
Message Type: 850

Partner Configuration/Buyer/Document Types/Documents
X12-00401-850-Buyer

==== Target Doc


Partner Configuration/Supplier/Document Types/New

Standard: JSON
Message Type: PurchaseOrder

Partner Configuration/Supplier/Document Types
JSON-PurchaseOrder-Supplier

=== Configure Map

Partner Configuration/Buyer/Maps/New/

Source Document - pick X12-00401-850-Buyer
Target Document - pick JSON-PurchaseOrder-Supplier
Mapping Type: DataWeave
Map Definition: Choose from saved

==== View Map

Partner Configuration/Buyer/Maps
Select added map, review

=== Configure Endpoints

==== Buyer

===== Receive

Partner Configuration/Endpoints/New

Protocol: AS2
Type: Receive
URL: http://localhost:8085/edi
Select Message Encrypted, Message signed

====== Create Property

New Property
@ Add Property Modal
Direction
* may need to add prop
Constant
Inbound
Save
@ Endpoint Page shows new PropType
Save

@ Endpoints shows new Endpoint

===== Send

@ Endpoints Page
New
@ Endpoint Page
AS2
Send
URL: http://localhost:8089/850
Encrypted, Signed, MDN Required
Save
@ Endpoints Page shows both new endpoints

==== Supplier (HomeOrg)

@ Supplier/Endpoints
New
@ Endpoint Page
Send, HTTP
Operation Settings/Host = 0.0.0.0
Port:8086
Path: /PurchaseOrder
Authentication: None
Save
@ Endpoints Page shows new endpoint (HTTP-Send-Supplier)


=== Configure Channels

==== Source Channel

@ Partners
Buyer
Channels
@ Channels
! New
@ Channel
! Source
! Document
@ Pick a document Modal
Pick X12-00401-850-Buyer
@ Channel
Document Map
@ Pick a Map Modal
! X12-00401-850-Buyer-JSON-PurchaseOrder-Supplier
! Endpoint
@ Pick a endpoint

==== Target Channel

@ Supplier
! Channels
@ Channels
! New
@ Channel
!


Autofills to Target-JSON-PurchaseOrder-Supplier-Http






=== Configure Routes


=== Configure

=== Configure

== Configure Routing Engine

== Configure Partner Simulator

== Start Walkthru

== Monitor Transactions
