
= Monitor B2B Transactions

Anypoint Partner Manager (APM) enables you to monitor B2B _transaction_ data.
A transaction is the full set of end-to-end events (including transmissions, documents, and errors) involved in processing a transmission.

You can:

* Filter to find the specific transaction data for which you are looking
* Review and monitor errors and acknowledgements.
* Search for metadata

This page identifies the APM components you use to monitor transactions. For information about transaction-monitoring scenarios, see
link:/anypoint-b2b/anypoint-partner-manager-concepts#tracking[the "Tracking" section in Anypoint Partner Manager Concepts].

== Page elements

The B2B Transactions Page consists of the following elements:

Anypoint Platform Header:: At the top of every page.
* Menu on the left enables you to switch to other Anypoint applications.
* *?* button provides access to support resources.
* _Master Organization_ name appears at top right. For more information, see link:/access-management/organization[Organization] and link:/anypoint-b2b/working-with-environments[Working with Environments].

Navigation Sidebar (left):: Use this sidebar to move from page to page.

Top Bar::
* Fixed on scroll
* Provides all action buttons associated with any selection you might have made.

Detail Sidebar (right)::
* Provides the details of what you have selected in the Central Pane.
* Most IDs have a copy button to the far right of them.
** Clicking on this will add the ID to your clip board.

Central Pane:: Presents content associated with the selection in the Navigation Sidebar. +
The next section (and the rest of this page) identifies elements that can appear within this pane.

== Central Pane elements

=== Dashboard

* Top of Central Pane
* Provides data for the timeframe you select in the <<*Overview for _timeframe_* Dropdown List>> at the upper left.

==== Overview for _timeframe_ Dropdown List

Enables you to present data specific to the following timeframes:

* *Today*
* *Past 48 Hours*
* *This Week*
* *This Month*

The default is *Today*.



===== Dashboard Data

Between the <<Overview for _timeframe_ Dropdown List>> and the <<View Dropdown List>>, Dashboard Data is presented in two forms:

Numerical form:: The actual number

Pie chart::
* A representation of the data as a percentage of all data of that type over that time frame. It is split by the different sections of said data.
* When you hover over or click on a section of the error pie chart, the section illuminates and provides the number corresponding to that section.
* When you click a section of the piechart, the content area will apply necessary filters to display the corresponding data

=== View Dropdown List

This menu, just above the <<Filter Bar>> grid, presents the following view choices:

* *Transactions*
* *Transmissions*
* *Errors*
* *Documents*

The type of data that appears in the <<Content Area>> depends on the menu option you choose here.

=== Filter Bar

* Enables users to filter the results of a view.
* Consists of Dropdown Filter lists that enable you to specify the criteria by which you want to filter.
* Which specific Dropdown Filter Lists appear depends on the value in the <<View Dropdown List>>.
* Any of the type-able fields will auto-filter as you type into them. In some cases, copying and pasting the value may be helpful.

==== To clear a Filter

. Click the Dropdown Filter List you want to clear.
+
The Filter List appears.
. At the top right of the Filter List, click the *clear* button.

==== To clear all Filters

. In the Filter Bar, click the *Clear Filters* button.


=== Content area

A table appears in the lower part of the Central Pane. Table column headings depend on  on the choices you make in the <<Overview for _timeframe_ Dropdown List>> and the <<View Dropdown List>>.

The following views are possible:

* <<Transactions View>>
* <<Transmissions View>>
* <<Errors View>>
* <<Documents View>>



==== Transactions View

The Transactions View is the default view for B2B Transactions page.

===== Content Area

The Content Area displays a table consisting of rows, each of which presents data specific to a transaction.

======  Transaction rows

Each row has five columns, each of which present data about a specific type of data.

Column 1 (not labeled): Transaction completion status:: Contains either a green checkmark or a red '!'.
* A green checkmark means the transaction was successful
* A red '!' means that an error occurred somewhere in the transaction.

Column 2 (not labeled): Replay status:: This column may contain:
* A blue partial circle with an arrowhead pointing right, which means that the transaction has been replayed
* A gray partial circle with an arrowhead pointing left, which means that the transaction is a replay of another transaction
* A gray circle with two sequential arrows, which means the transaction is currently being replayed

Column 3 (From):: The partner from whom the transaction originated

Column 4 (To):: To whom the transaction was destined

Column 5 (Date):: Date and time at which the transaction occurred

====== Transaction Event rows

To view detailed information for the events that comprise a transaction, click anywhere in a transaction row. A new table appears beneath the transaction row. Events appear in inverse chronological order (oldest first). Columns are:

From:: Partner from whom the event originated
To:: Partner to whom the event was sent
Type:: Event type
Direction:: Either *Inbound* or *Outbound*
Date:: Date and time at which the event occurred
Label:: Indicates what happened in the event

===== Transaction Detail Pane
This pane appears on the right side of the page. In addition to information displayed in the <<Transaction row>>, it displays the *Transaction ID*.

If a transaction has been replayed, a *view replays* link appears, enabling you to view replays for the transaction.


===== Filters

You can filter transactions based on:

Date::
* Today
* Past 48 Hours
* This Week
* This Month

From:: Select a date from calendar; only transactions that occurred after that date will appear.
To:: Select a date from calendar; only transactions that occurred before that date will appear.
Partner:: Configured partners. For more information, see link:/anypoint-b2b/configure-trading-partners[Configure Trading Partners].
Transaction ID:: ID that you enter. When a Transaction ID filter is set, you can choose to include the replayed transactions originated from that Transaction ID.


====== To show all transactions
Click *Clear filters*.

===== Top Bar
* The *Replay* button will appear if transaction you have selected can be replayed.

==== Transmissions View

===== Content Area
Each row has 6 columns:

From:: Who the transmission came from
To:: Who it was sent to
Date:: Date and time at which the event occurred
Direction:: Either *Inbound* or *Outbound*
Transmission Type:: What it was sent over
Label:: Any label associated with the transmission

===== Detail Pane
* Contains information about the transmission
* The Message payload is viewable through a link provided
* All IDs can be copied through the copy button to the right of it

===== Filters
Direction:: Inbound or Outbound
Partner:: Pick the partner associated with the transmission
File Name:: Enter in part or all of a file name
Transport:: Pick the transport the transmission was sent over

Date::
* Today
* Past 48 Hours
* This Week
* This Month

From:: Select a date from calendar; only errors that occurred after that date will appear.
To:: Select a date from calendar; only errors that occurred before that date will appear.

====== To show all transmissions
Click *Clear filters*.

===== Top Bar
* A *Transaction* button will appear when a transmission is selected
** This will take you to the *Transaction* view and highlight this specific transmission

==== Errors View

===== Content Area
Each row has 5 columns

From:: What partner the error came from
To:: Who it was going to
Date:: Date and time at which the error occurred
Error Code:: Code associated with the error

===== Detail Pane
Displays detailed information specific to the error code

===== Filters

You can filter errors based on:

Date::
* Today
* Past 48 Hours
* This Week
* This Month

From:: Select a date from calendar; only errors that occurred after that date will appear.
To:: Select a date from calendar; only errors that occurred before that date will appear.

Error code / type:: For example, *4- Languishing*

Error Source::
* Transmission
* Transaction
* Errors
* Document

Error ID::
Enter a specific error identifier.


====== To show all errors
Click *Clear filters*.

===== Top Bar
* *Related error source* button will appear when a row is selected. This will allow you to view the transaction, transmission, or document associated with the error.


==== Documents View

===== Content Area
* Each row has 6 columns
From:: Who the document was sent to
To:: Who it was sent to
Date:: Date and time at which the document was sent
Standard:: The standard used
Message Type:: The type of the messaging
Direction:: Inbound or Outbound
Label:: Short information describing the document

===== Detail Pane
* Contains information associated with the document
* Message Payload can be viewed through the link provided
* All IDs can be copied though the copy button to the right of the ID

===== Filters

Date::
* Today
* Past 48 Hours
* This Week
* This Month

From:: Select a date from calendar; only errors that occurred after that date will appear.
To:: Select a date from calendar; only errors that occurred before that date will appear.
Direction:: Inbound or Outbound
Partner:: Filter by the Partner that is associated with the document
Message Type:: Filter for message type field containing string
Property Name:: Filter for document having property name
Property Value:: Filter for document having property value containing string
Standard:: Filter by the standard
Document ID:: Filter by document id

====== To show all documents
Click *Clear filters*.

===== Top Bar
* A *Transaction* button will appear when a document is selected
** This will take you to the *Transaction* view and highlight this specific document


include::more-information.adoc[More information]

////

== More information

* link:/anypoint-b2b/anypoint-partner-manager-users-guide[Anypoint Partner Manager User's Guide]
* link:/anypoint-b2b/configure-trading-partners[Configure Trading Partners]
* link:/anypoint-b2b/as2-and-edi-x12-purchase-order-walkthrough[AS2 and EDI X12 Purchase Order Walkthrough]
* link:/anypoint-b2b/ftps-and-edi-x12-purchase-order-walkthrough[FTPS and EDI X12 Purchase Order Walkthrough]
* link:/anypoint-b2b/transaction-tracking-walkthrough[Transaction Tracking Walkthrough]
////
