
= Monitor B2B Transactions

Anypoint Partner Manager (APM) enables you to monitor B2B _transaction_ data.
A transaction is the full set of end-to-end events (including transmissions, documents, and errors) involved in processing a transmission.

You can:

* Filter to find the specific transaction data for which you are looking
* Review and monitor errors and acknowledgements.
* Search for metadata

This page identifies the APM components you use to monitor transactions. For information about transaction-monitoring scenarios, see "Tracking" in link:/anypoint-b2b/anypoint-partner-manager-concepts[Anypoint Partner Manager Concepts]

Test link:
link:/anypoint-b2b/anypoint-partner-manager-concepts#tracking[Anypoint Partner Manager Concepts (Tracking section)]

== Page elements

The B2B Transactions Page consists of the following elements:

Anypoint Platform Header:: At the top of every page.::
* Menu on the left enables you to switch to other Anypoint applications
*  ? provides access to support resources
* Master Organization name appears at top right (for more information, see link:/access-management/organization[Organization])

Navigation Sidebar (left):: Use this sidebar to move from page to page.

Central Pane:: Presents content associated with the selection in the Navigation Sidebar

Top bar::
* Fixed on scroll
* Provides all action buttons associated with any selection you might have made.

Detail sidebar (right)::
* Provides the details of what you have selected in the Central Pane.
* Most IDs have a copy button to the far right of them.
** Clicking on this will add the ID to your clip board.

== Central Pane elements

=== View Options Dropdown Menu

This menu, just above the grid, presents the following view choices:

* Transmissions
* Transactions
* Errors
* Documents

The data that appears in the <<Content Area>> depends on the menu option you choose here.

=== Dashboard

* Top of pane
* Provides status based on timeframe you select in the dropdown list at the upper left.

==== Overview data

Given for:

* Transmissions
* Transactions
* Errors
* Partners

Given in:

Numerical form:: The actual number

Pie chart::
* A representation of the data as a percentage of all data of that type over that time frame. It is split by the different sections of said data.
* When you hover over or click on a section of the error pie chart, the section illuminates and provides the number corresponding to that section.

=== Filter bar

* Enables you to filter data for quick navigation
* Bottom of pane

* The filter bar allows users to filter through the results of the view. It is different for each view depending on what the user would want to filter by.
* Clicking on the down arrow on any of the drop-down filters allows you to pick what you want to filter by.
* Any of the type-able fields will auto-filter as you type into them. The recommendation is to copy and paste in what you are searching for.
* You can remove any filters at anytime individually or use the *Clear Filters* button to clear all the filters.

=== Content area

A table appears in the lower part of the Central Pane. Table column headings may be changed based on the choices you make in <<Overview data>>. Possible views include:

==== Transactions View

The Transactions View is the default view for B2B Transactions page.

===== Content Area

======  Transaction row

Each row has 5 columns, each of which present data about a given transaction.

Column 1:: Contains either a green checkmark or a red 'x'.
* A green checkmark means the transaction was successful
* A red 'x' means that an error occurred somewhere in the transaction.

Column 2:: The replay column. This column contains either:
* A blue partial circle with an arrowhead pointing right, which means that the transaction has been replayed
* A gray partial circle with an arrowhead pointing left, which means that the transaction is a replay of another transaction

Column 3 (From):: The partner from whom the transaction originated

Column 4 (To):: To whom the transaction was destined

Column 5 (Date):: Date and time at which the transaction occurred

====== Transaction Event rows

To view detailed information for the events that comprise a transaction, click anywhere in a transaction row. A new table appears beneath the transaction row. Events appear in inverse chronological order (oldest first). Columns are:

From:: Partner from whom the event originated
To:: Partner to whom the event was sent
Type:: Event type
Direction:: Either *Inbound* or *Outbound*
Date:: Date and time at which the event occurred
Label:: Indicates what happened in the event

===== Transaction Detail Pane
This pane appears on the right side of the page. In addition to information displayed in the <<Transaction row>>, it displays the *Transaction ID*.

If a transaction has been replayed, a *view replays* link appears, enabling you to view replays for the transaction.


===== Filters

You can filter transactions based on:

Partner:: Configured partners. For more information, see link:/anypoint-b2b/configure-trading-partners[Configure Trading Partners].
Transaction ID:: ID that you enter
Date::
* Today
* Past 48 Hours
* This week
* This month

From:: Select a date from calendar; only transactions that occurred after that date will appear.
To:: Select a date from calendar; only transactions that occurred before that date will appear.

====== To show all transactions
Click *Clear filters*.


===== Top Bar
* The *Replay* button will appear if transaction you have selected can be replayed.

==== Error View

===== Content Area
Each row has 5 columns

From:: What partner the error came from
To:: Who it was going to
Date:: Date and time at which the error occurred
Error Code:: Code associated with the error
Error Message:: Quick view of what went wrong
+
_I don't see this column -- IW_

===== Detail Pane
Displays detailed information specific to the error code

===== Filters

You can filter errors based on:

Date::
* Today
* Past 48 Hours
* This week
* This month

From:: Select a date from calendar; only errors that occurred after that date will appear.
To:: Select a date from calendar; only errors that occurred before that date will appear.

Error code / type:: For example, *4- Languishing*

Error Source::
* Transmission
* Transaction
* Errors
* Business_Document

Error ID::
Enter a specific error identifier.


====== To show all errors
Click *Clear filters*.

===== Top Bar
* *Documents* button will appear when a row is selected. This will allow you to view the document associated with the error.

_<<This doesn't seem to happen for me>>_

==== Transmission View

===== Content Area
Each row has 6 columns:
From:: Who the transmission came from
To:: Who it was sent to
Date::
Direction:: Inbound or Outbound
Transmission Type:: What it was sent over
Label:: Any label associated with the transmission

===== Detail Pane
* Contains information about the transmission
* The Message payload is viewable through a link provided
* All IDs can be copied through the copy button to the right of it

===== Filters
* Direction:: Inbound or Outbound
* Partner:: Pick the partner associated with the transmission
* File Name:: Enter in part or all of a file name
* Transport:: Pick the transport the transmission was sent over
* Date
** From
** To

====== To show all transmissions
Click *Clear filters*.

===== Top Bar
* A *Transaction* button will appear when a transmission is selected
** This will take you to the *Transaction* view and highlight this specific transmission

==== Document View

===== Content Area
*Each row has 6 columns
From:: Who the document was sent to
To:: Who it was sent to
Date::
Document Type:: The type of document it is
Direction:: Inbound or Outbound
Label:: Short information describing the document

===== Detail Pane
* Contains information associated with the document
* Message Payload can be viewed through the link provided
* All IDs can be copied though the copy button to the right of the ID

===== Filters
Direction:: Inbound or Outbound
Partner:: Filter by the Partner that is associated with the document
File Name:: Enter part or all of a file name
Date::
From::
To::


====== To show all documents
Click *Clear filters*.

===== Top Bar
* A *Transaction* button will appear when a document is selected
** This will take you to the *Transaction* view and highlight this specific document


include::more-information[More information]

////

== More information

* link:/anypoint-b2b/anypoint-partner-manager-users-guide[Anypoint Partner Manager User's Guide]
* link:/anypoint-b2b/configure-trading-partners[Configure Trading Partners]
* link:/anypoint-b2b/as2-and-edi-x12-purchase-order-walkthrough[AS2 and EDI X12 Purchase Order Walkthrough]
* link:/anypoint-b2b/ftps-and-edi-x12-purchase-order-walkthrough[FTPS and EDI X12 Purchase Order Walkthrough]
* link:/anypoint-b2b/transaction-tracking-walkthrough[Transaction Tracking Walkthrough]
////
