= Routes

. On the Routes page, click *New*.
. The Route page appears.

[%header,cols="3s,7a"]
|===
|Setting |Description

|Name
|Type a name for this channel.

Valid values:: link:/anypoint-b2b/anypoint-partner-manager-glossary#sects[Standard APM field format]


|===

== Source Channel, Target Channel

When you click either the Source Channel or the Target Channel box, the Pick a Channel selection page appears. You can make the following selections:

[%header,cols="3s,7a"]
|===
|Setting |Description

|Partnership

| Required?::
No


Default::

None

|Name

| Required?::
No


Default::

None

|===





////

|Standard



Required?::
No

Valid values:: <Documentation in progress>



Default::

None

|Version



Required?::
No

Valid values:: <Documentation in progress>



Default::

None

|Message Type



Required?::
No

Valid values:: <Documentation in progress>



Default::

None

| Type

Select a type from the dropdown listbox.

Required?::
No

Valid values:: <Documentation in progress>



Default::

None

== Transport



Required?::
No

Valid values:: <Documentation in progress>



Default::

<value | None>

////
