= Understanding Anypoint Partner Manager
:keywords: b2b

This page explains Anypoint Partner Manager concepts. For more information, see link:/anypoint-b2b/anypoint-partner-manager[Anypoint Partner Manager].

== B2B Routing Framework

<content to come from Kent>

== Hierarchical Resolution Logic

<content to come from Claude>

== Tracking

<content to come from Cooper>

This walkthrough shows you how to use the Anypoint Partner Manager (APM) to track B2B exchanges by explaining how the software can be used to get through different scenarios. We assume a basic knowledge of APM in this section, if you lack that knowledge please refer back to our link:/anypoint-b2b/anypoint-partner-manager[Overview].

=== Scenarios

=== Replaying a bad Transaction

If you notice in the B2B Transactions Tab that you have a transaction that has an error in it you will probably want to fix this error and replay the transaction. We give an option to do this through our replay button.

Simply click on the Transaction that has an error (This is designated through a red exclamation point) and in the upper right corner you should notice a blue replay button. Before you click this button to replay the transaction you should be in communication with someone who can fix the error that went wrong. Once you think that the situation won't happen again you should click on the replay button.

When this button is click it will disable itself and will let you know that the transaction is being replayed. Once the transaction has been replayed a blue replay circle will appear in the status of the transaction that you replayed. In order to see if the replayed transaction succeeded or failed you can click on the replayed transaction and then in the detail panel you will notice that at the very top there will be a link to View Replays. This will automatically filter the grid to only see transactions that have been replayed off of that original transaction.

If the replayed transaction failed again, you can keep repeating this process until the replay goes through. You will always be able to get a full list of all of the transactions that are replayed from the same original by clicking the link in the detail panel of any of the transactions with the blue replay circle in their status.

Once the replay has succeeded and you have a green check next to the replayed transaction you will hopefully be done. If for some reason you need to continue replaying the transaction you can do so with the same replay button but you will be alerted with a warning before you can continue. This is to stop unnecessary replays from happening which can cause problems in the database and elsewhere.

=== Common Errors or Confusing Errors

If one day for some reason you run into an abnormal amount of similar errors we provide a convenient way to look through all of them. The Dashboard at the top of the B2B Transactions Tab provides an overview of what has happened recently, so if you come into the day and a large number of errors have happened you will know right away.

You will also quickly be able to tell what kind of errors have happened by hovering over different slices of the pie. If you wish to inspect this further you can click on one of the slices to automatically sort the errors by this type.

This will take you to our errors tab and automatically filter the results. This will give you quick access to all the same errors so you can look for a common pattern among these in order to find a solution.

This is useful for when transactions are failing but you can't find the solution by just looking at the transactions themselves. Being able to view the whole suite of errors will allow our user to look for patterns in the data that otherwise would be hard to find.

From here we provide a way to view the transactions that these errors are associated with through our navigation buttons in the top right.

=== Transport Problem Identification

If you notice that you are getting a high number of your errors all from AS2 transmissions you can quickly sort your transmissions under the transmission tab with a filter. This filter will allow you to quickly look at all the AS2 transmissions and see the differences between those that failed and those that succeeded.

From here you can see what happened with individual transactions that these transmissions were involved in through a simple navigation click in the upper corner. This will allow you to follow transactions through their entire cycle, and if necessary replay them through their transactions.

Quick and useful navigation is hugely important in looking for patterns and correcting errors. That is why some of the more important filters will also follow you from tab to tab. This will allow you to look for commonalities in all of the types of data.

=== Partner Needs Records

A common scenario is when a partner requires different information relating to a Transaction or a Transmission or a document. In the B2B Transaction Tab of the APM you can filter through the different tabs at the top to find Transactions, Transmissions, or Documents. From there we provide a simple filter to use an ID that the partner gave you to find the event that they are talking about.

From here you can easily find what they are talking about and provide them with the relevant information quickly and easily. If the Partner is trying to find a specific ID then you can also get that to them relatively quickly with the copy button that we provide to the right of all the long strings.
