= MUnit
:version-info: 3.7.0 and newer
:keywords: munit, testing, unit testing

== Overview

MUnit is a Mule application testing framework that allows you to easily build automated tests for your integrations and APIs. It provides a full suite of integration and unit test capabilities, and is fully integrated with Maven and Surefire for integration with your continuous deployment environment.

With MUnit you can:

* Create your Mule test by writing Mule code
* Create your Mule test by writing Java code
* Disable flow inbound endpoints
* Disable endpoint connectors
* Mock outbound endpoints
* Mock message processors
* Spy any message processor
* Verify message processor calls
* Create not only unit tests but also integration tests in a local environment -- MUnit allows you to start a local FTP/SFTP, DB server or mail server
* Call the Mule client from Mule code
* Assert flow exceptions
* Enable or disable particular tests
* See assertion/error reports with Mule stack trace
* Extend the MUnit framework with plugins
* Check visual coverage in Studio
* Debug your tests with Studio

== MUnit Versions

See the link:/release-notes/munit-1.2.1-release-notes[Release Notes] to see what's new.

TIP: MUnit version 1.2 works with all Mule versions since 3.6.0  (for 3.6.x minor limitations, see link:/release-notes/munit-1.2.1-release-notes#migration-guidance[MUnit Release Notes - Compatibility Information]).

== MUnit Compatibility

MUnit is divided among several sub modules. From a user's point of view there are only two that are really important. Both modules are compatible amongst themselves.

The important sub modules are:

* *MUnit* - The latest MUnit works with any Mule version from 3.6.x. These
compatibility rules are followed:
+
[%header%autowidth.spread]
|===
|MUnit Version |Mule MUnit Support Version
|1.0.x |3.6.x, 3.7.x
|1.1.x |3.6.x, 3.7.x
|*1.2.x* |*All versions since 3.6.x*
|===
* *Mule MUnit Support* - The Mule MUnit Support module is meant to follow Mule ESB releases:
+
[%header%autowidth.spread]
|===
|Mule MUnit Support Version |Mule ESB Version
|3.6.x |3.6.0 to 3.6.x
|3.7.x |3.7.0 to 3.7.x
|3.8.x |3.8.0 to 3.8.x
|===
+
NOTE: The *x* at the end of each version number refers to the latest version within that minor version.
+
TIP: Currently the latest released versions of Mule MUnit Support are:  *3.6.4*, *3.7.4*, *3.8.1*.


[[studio]]
== MUnit and Anypoint Studio

MUnit is fully integrated with Anypoint Studio, allowing you to create, design and run MUnit tests just like you would Mule applications. You can also use Anypoint Studio's link:/anypoint-studio/v/5/studio-visual-debugger[Studio Visual Debugger] to debug your MUnit tests.

For an overview of MUnit in Anypoint Studio, see link:/munit/v/1.2/using-munit-in-anypoint-studio[Using MUnit in Anypoint Studio].

== What's in These Docs

The pages listed below provide an overview of MUnit features including simple examples. Topics include the MUnit message processors, the DB and FTP servers provided by MUnit, Maven support and more. For a short step-by-step guide to creating a test, see the link:/munit/v/1.2/munit-short-tutorial[MUnit Tutorial].

TIP: The examples in these pages are XML-only; however, as stated <<studio,above>>, you can also use MUnit via Anypoint Studio's graphical interface. See link:/munit/v/1.2/using-munit-in-anypoint-studio[Using MUnit in Anypoint Studio] for details.

* link:/munit/v/1.2/using-munit-in-anypoint-studio[Using MUnit in Anypoint Studio]
* link:/munit/v/1.2/munit-suite[MUnit Suite]
* link:/munit/v/1.2/mock-message-processor[Mock Message Processor]
* link:/munit/v/1.2/verify-message-processor[Verify Message Processor]
* link:/munit/v/1.2/set-message-processor[Set Message Processor]
* link:/munit/v/1.2/spy-message-processor[Spy Message Processor]
* link:/munit/v/1.2/assertion-message-processor[Assertion Message Processor]
* link:/munit/v/1.2/munit-matchers[MUnit Matchers]
* link:/munit/v/1.2/munit-database-server[MUnit Database Server]
* link:/munit/v/1.2/munit-ftp-server[MUnit FTP Server]
* link:/munit/v/1.2/munit-maven-support[MUnit Maven Support]
* link:/munit/v/1.2/munit-domain-support[Munit Domain Support]
* link:/munit/v/1.2/munit-coverage-report[Munit Coverage Reports]
* link:/munit/v/1.2/munit-short-tutorial[MUnit Short Tutorial]
* link:/munit/v/1.2/run-and-wait-scope[Run And Wait Scope]
* link:/munit/v/1.2/example-testing-apikit[Example: Testing APIKit]
* link:/munit/v/1.2/munit-1.2-migration-guide[MUnit 1.2 Migration Guide]

