= Alerts

Alerts indicate whether a resource (such as a Mule app) is behaving as expected or exceeding a defined threshold. 

There are several types of alerts. From the Alerts page in Anypoint Monitoring, you can link out to alerts for API and Runtime alerts. If your subscription permits, you can also view, enable, and disable alerts that are configured for graphs in custom dashboards.

//When the data exceed a configured threshold on your resources over a period of time, you can also receive notification to take action.


//TODO: VERIFY THAT ALL THESE FEATURES ARE ACTUALLY IMPLEMENTED
////
Alerting features in Anypoint Monitoring include:

* Threshold-based alerting: Notification when a specific metric that is related to a resource goes beyond the acceptable threshold for the period of time that you define.
* Batch Alert Assignments: Assignment of your alert definitions to multiple resources of the same type at once to help you save time of setting up each individually.
* Channel Integrations: Ability to specify a channel (such as PagerDuty, SMS, or Slack) to which notifications are sent.
* Alert Rollup: Ability to received a limited number of notifications on the same issue so that crucial notifications do not get overlooked because they are buried within a lot of redundant notifications.
* Alert History: An Alert History page shows status changes of a single alert. When you are troubleshooting an issue, you can have a view of istoric data and see if the current issue has any  precedent.
////

See link:alerts-config[Configuring Alerts]
