= About Alerts

////
*TODO: STEPS, AND DESCRIPTION OF SCALABLE ALERTS*
Scalable alerts: Limited, Per App (base subscription) vs. Included, Unlimited for Premium Add on
////

Alerting allows you to define different rules (thresholds) and policies for different resources. When these rules are "crossed" for a certain period of time, you receive notification to take action. The method of notification depends on the severity of the alert that you define

Alerting features include:

* Threshold-based alerting: Notification when a specific metric that is related to a resource goes beyond the acceptable threshold for the period of time that you define.
* Batch Alert Assignments: Assignment of your alert definitions to multiple resources of the same type at once to help you save time of setting up each individually.
* Channel Integrations: Ability to specify a channel (such as PagerDuty, SMS, or Slack) to which notifications are sent.
* Alert Rollup: Ability to received a limited number of notifications on the same issue so that crucial notifications do not get overlooked because they are buried within a lot of redundant notifications.
* Alert History: An Alert History page shows status changes of a single alert. When you are troubleshooting an issue, you can have a view of historic data and see if the current issue has any  precedent.

== See Also

link:alerts-config[Configuring Alerts]

////
TODO: ALERT LIST PANEL? WILL THERE BE ONE?
The alert list panel allows you to display your dashbords alerts. The list can be configured to show current state or recent state changes. You can read more about alerts here.

Alert List Options

Show: Lets you choose between current state or recent state changes.
Max Items: Max items set the maximum of items in a list.
Sort Order: Lets you sort your list alphabeticaly(asc/desc) or by importance.
Alerts From This Dashboard`: Shows alerts only from the dashboard the alert list is in.
State Filter: Here you can filter your list by one or more parameters.
////

////
TODO: HOW TO'S ON THIS STUFF

TODO: ARE THESE STILL PLANNED?

* Enable Alert
* Disable Alert
* View Alert History
* View Alert Properties
** Alert Name
** Status
  *** Disabled
  *** Enabled
  *** OK
  *** Alerting

* Status (Disabled)
* Source (Application - API)
* Severity (Critical - Warning -info)
* Owner
* Date created (date)
* Last modified (date)
* Log of alert's status change

*  Search alerts by alert-name

* Filter by source type
* Filter by status type
* Filter by severity
* Filter by all of the above
////
