= About Alerts

In Anypoint Monitoring, you can define rules (thresholds) and policies for alerts on your resources. When these rules are "crossed" for a certain period of time, you receive notification to take action. The method of notification depends on the severity of the alert that you define

Alerting features in Anypoint Monitoring include:

* Threshold-based alerting: Notification when a specific metric that is related to a resource goes beyond the acceptable threshold for the period of time that you define.
* Batch Alert Assignments: Assignment of your alert definitions to multiple resources of the same type at once to help you save time of setting up each individually.
* Channel Integrations: Ability to specify a channel (such as PagerDuty, SMS, or Slack) to which notifications are sent.
* Alert Rollup: Ability to received a limited number of notifications on the same issue so that crucial notifications do not get overlooked because they are buried within a lot of redundant notifications.
* Alert History: An Alert History page shows status changes of a single alert. When you are troubleshooting an issue, you can have a view of historic data and see if the current issue has any  precedent.

See link:alerts-config[Configuring Alerts]
