= Creating a Custom Dashboard

TODO

A custom dashboard enables advanced users to bring together, on one screen,  specific metrics and data points that are important to them.

Built In dashboards expose the metrics relevant to different topologies of users systems as out of the box dashboards

User story - SPECIFY RESOURCES AND METRICS TO MONITOR
As a sysadmin based on the project at hand I want to be able to specify the resources and metrics that I want to monitor alongside each other so that I can correlate diverse metrics and perform comparative analysis so that I can differentiate between regular trends and anomalies so that I can isolate the real issue faster

Supporting feature
Custom dashboards
Simple query maker
Selecting resource
Selecting the metric that needs to be monitored
Advanced query maker
Selecting resources
Selecting the metrics that needs to be monitored for each resource
Moving widgets around
Adjusting the size of widgets


User story - COMPARE LIVE TO HISTORIC DATA
As a sysadmin I want to be able to compare live data with historic data so that I can detect anomalies and troubleshoot faster.

Supporting feature
Custom dashboards
Time shift
