= About Custom Dashboards

//NOTE: from orig outline
*TODO: GENERAL DESCRIPTIONS OF WIDGETS, SEE BELOW, and is USING INFO SIMPLE ENOUGH TO ADD TO THIS PAGE OR IS ANOTHER NEEDED?*

Custom dashboards in the Monitoring Center can bring together important metrics and data points that you need to see on one screen. You can specify the resources and metrics that you want to monitor, allowing you to:

* Correlate diverse metrics
* Perform comparative analysis
* Differentiate between regular trends and anomalies
* Isolate issues quickly

An important use case is compare live data with historic data so that you can detect anomalies and expedite the troubleshooting process.

Custom dashboards can contain one or more items (widgets) in each row.

.Widgets Available for Custom Dashboards
images::dashboard-custom-widgets.png[Custom Dashboard Widgets]

* Graphs: For charts that support a query language capable of retrieving a wide variety of data and pinpointing the exact data you want to see. You can graph as many metrics and as much time-series data as you want.
* Singlestat: *TODO* For displaying a single statistic. It reduces of a single query into a single number, such as the number of errors or ...
* Table:
* Text:

////
Supporting feature
Custom dashboards
Time shift
////
