= Creating and Using Custom Dashboards

//NOTE: from orig outline

Custom dashboards in the Monitoring Center can bring together important metrics and data points that you need to see on one screen. You can specify the resources and metrics that you want to monitor, allowing you to:

* Correlate diverse metrics
* Perform comparative analysis
* Differentiate between regular trends and anomalies
* Isolate issues quickly

An important use case is compare live data with historic data so that you can detect anomalies and expedite the troubleshooting process.

////
Supporting feature
Custom dashboards
Time shift
////

[[use_case_create_dashboard]]
== Creating a Custom Dashboard

You can create one or more custom dashboard. Each dashboard can contain multiple charts.

. From the Monitoring Center, click Custom Dashboards.
. Click New Dashboard.
. Add a Graph, Singlestat, Table, or Text to the dashboard.
. Save your changes.

[[use_case_view_dashboard]]
== Viewing an Existing Custom Dashboard

. From the Monitoring Center, click Custom Dashboards.
. Find the dashboard in on the page, or search for it.

[[use_case_add_row]]
== Adding Charts to a Custom Dashboard

* Find and Click Add Row.

This button is located at the bottom lefthand side of your dashboard.

////
Supporting feature
Custom dashboards
Simple query maker
Selecting resource
Selecting the metric that needs to be monitored
Advanced query maker
Selecting resources
Selecting the metrics that needs to be monitored for each resource
Moving widgets around
Adjusting the size of widgets
////

== See Also

link:dashboard-bookmarking[Bookmarking Dashboards]
