= Getting Metrics from your Built-in Dashboard

//NOTE: MIGHT NEED TO MAKE THIS MORE USE CASE FOCUSED

Built-in dashboards in the Monitoring Center provide visibility into Mule apps that are deployed to any of your environments.

//TODO: SHORT DESCRIPTIONS FOR THESE NEEDED
Built-in dashboards contain the following charts:

* Response Time by App
* Messages Processed
* Response Time by Inbound Endpoint
* Response Time by Outbound Endpoint
* CPU
* Memory

== Viewing a Built-in Dashboard:

. Click Built-in Dashboards.
. Select and environment to view, such as your Design or Sandbox environment.
. Select a Mule app.

//TODO: LIST OF BUILT-IN CHARTS?

== Configuring Charts

Charts in your dashboard can display data points:

* Over specific time intervals, such as the last 5 minutes, hour, 3 hours, 24 hours, 5 days, 15 days, and so on.
* Over a customizable date and time range.

== Drilling Down to Specific Data Points

You can drill down from summary dashboards to the information most pertinent to your current task. For example, if you are currently looking at a chart that shows data for the last 5 hours, you can narrow the range to the last 30 minutes to expose more detailed data points within that 30-minute range.

* Use your mouse to select a range of data points from the chart.

The chart will display a new view with more detailed data points for the narrowed time range.

////
Supporting feature
Supporting the per widget drilldown (linking) functionality in custom dashboards
////

== Refreshing Data

You can refresh data in the charts manually, or if your license permits, at a regular interval (such as 5s, 30s, 5m, 1h, 1d) that you set through the Auto-Refresh.

== See Also

link:dashboard-bookmarking[Bookmarking Dashboards]
