= Configuring Tables in a Custom Dashboard

In Anypoint Monitoring, you can configure data and pagination properties of tables for custom dashboards. *TODO: OTHER PROPERTIES ARE CONFIGURABLE* By default, a table includes a Time column that you can configure or change to another type of column.

//GENERAL SETTINGS shared by singlestat, graph, table
//== General
include::include-general-config.adoc[]

// TIME RANGE SETTINGS shared by singlestat and table
//==Time Range
include::include-time-range-config.adoc[]

== Options

You can data layout, column, and paging options for tables in a custom dashboard.

[%header,cols="1,4"]
|===
2+| Data Settings
| Table Transform a|

Valid values:

* Time Series to Rows: Creates a table that shows values for a given metric at a given time period. Like Time Series to Columns, the first column, Time, is for timestamps (such as `2018-04-25 06:37:40`). However, subsequent columns are Metric (for listing specific metrics, such as `worker-0`) and Value for listing the values of the metric at that time period.
* Time Series to Columns: Creates a table that shows values for a given metric at a given time period. Like Time Series to Rows, the first column, Time, is for timestamps. However, there is a column for each metric, such as `worker-0`, which lists the values of that metric at a given time period.
* Time Series to Aggregations: Transforms time series into a table that calculates totals, averages, and so on for a given metric. The first column, Metric, is for metrics such as `worker-0`, and subsequent columns are for any combination of these values: Avg, Min, Max, Total, Current, or Count for a given metric.
* Annotations: Displays annotations in a table if annotations are enabled for the dashboard. In this mode, queries you have in the metrics tab will be ignored. *TODO: VERIFY and how do you enable annotations?*
* Table: *TODO, what does this do* Columns and their order are determined by the data query.
* JSON Data: Mode to use for Elasticsearch or Elasticsearch Raw Document queries without a date histogram. *TODO: VERIFY mention Elasticsearch?*
| Columns a|

Valid values:

* Auto: Columns and their order are determined by the data query. Only available setting when Time Series to Rows, Time Series to Columns, Annotations, or Table is selected.
* Avg: *TODO* Average ... Defaults for Time Series to Aggregations.
* Min: *TODO* Minimum ...
* Max: *TODO* Maximum ...
* Total: *TODO*
* Current: *TODO*
* Count: *TODO*
* A blank text box: Appears when JSON Data is selected.  *TODO: need JSON example?*
|===

.Paging
[%header,cols="1,4"]
|===

| Rows per Page | Number of table rows allowed per page.
| Scroll | Checkbox for making .... *TODO* scrollable.
| Font Size | Percentage from 80% to 250%. ... *TODO*
|===

After you complete your configuration, you can click Save Changes. To exit the configuration and return to the dashboard, simply click the `X`.

== Column Styles

You can create (+Add) and apply one or more rules for table columns. The rules are listed on the left side of the Column Styles pane.

To remove a rule, you need to click it, then find and click the Remove Rule button near the bottom left of the screen.

[%header, cols="1,4"]
|===
2+| Options
| Apply To Columns Named  | Identifies the column or columns to which the rule applies. You need to provides the name or a regular expression (regex) that matches the name of one or more columns in the table. For a regex, you  the following syntax: `/my.*regex/`
| Column Header | Provides a title for the column. You can use stings such as `$1` for a regular expression. *TODO: VERIFY*
| Render Value As Link | Displays a Link fields when checked. *TODO: MORE ABOUT LINKS*
|===

[%header, cols="1,4"]
|===
2+| Link
| URL a|
Appears when Render Value As Link is checked. Specifies a URL (relative or absolute) Use special variables to specify cell values:

Valid values:

* `$__cell` refers to current cell value.
* `$__cell_n` refers to Nth column value in current row. Column indexes are started from `0`. For instance, ``$__cell_1` refers to second column's value.
| Tooltip a|

Specifies text for a link tooltip. This title appears when the end user hovers over the cell with the link. Use the same variables as for URL.
| Open In New Tab | *TODO - opens the referenced page in a new tab?*
|===

[%header, cols="1,4"]
|===
2+| Type
| Type | Data type for values in the column. Valid values are Number, String, Date, and Hidden.
| Unit | Unit label for the value, such as `seconds (s)` and `megabytes/second`. A wide variety of units are available.
| Decimals | The level of precision allowed for a decimal value, for example, `2` to limit a value of `10.12345` to `10.12`. *TODO: VERIFY*
|===

Thresholds are only available when the Type is Number.

[%header, cols="1,4"]
|===
2+| Thresholds
| Thresholds | Comma-separated values ... *TODO*
| Color Mode | *TODO* ... values Disabled, Cell, Value, Row
| Color | *TODO* ... rgb options, including inversion ... *TODO* and Invert...
|===

After you complete your configuration, you can click Save Changes. To exit the configuration and return to the dashboard, simply click the `X`.

////
Options overview
The table panel has many ways to manipulate your data for optimal presentation.

Data: Control how your query is transformed into a table.
Paging: Table display options.
Data to Table

The data section contains the To Table Transform (1). This is the primary option for how your data/metric query should be transformed into a table format. The Columns (2) option allows you to select what columns you want in the table. Only applicable for some transforms.

Table Display

Scroll: The scroll bar checkbox toggles the ability to scroll within the panel, when unchecked, the panel height will grow to display all rows.
Font Size: The font size field allows you to increase or decrease the size for the panel, relative to the default font size.
Column Styles
The column styles allow you control how dates and numbers are formatted.
////
