//INCLUDED IN GRAPH CONFIG FILE
[[alerts_config]]
== Alerts

You can create, configure, delete, test, and send alerts to people who need to see them. The rules you configure trigger alerts when conditions reach a specified threshold value, for example: *TODO*  You can also get the history of an alert.

. To configure an alert, navigate to the Alert configuration tab for a graph.
. Click Create Alert.

.Alert Config
[cols="1,4"]
|===

| Name | A title for your alert.
| Evaluate Every | Interval at which to poll for an alert, for example, every sixty seconds (`60s`).
| Conditions a|
* WHEN: `min()`, `max()`, `sum()`, `count()`, `last()`, `median()`, `diff()`, `percent_diff()`, `count_non_null()`
* OF: Example: `query(A, 5m, now)`
* IS ABOVE or *TODO for other relationships*
* If No Data or All Values Are Null SET STATE TO `Alerting`, `No Data`, `Keep Last State`, or `Ok`.
* If Execution Error or Timeout SET STATE TO `Alerting` or `Keep Last State`
| Test Rule |
|===


.Notifications
[cols="1,4"]
|===
| Send To | Email address for a recipient of the alert.
| Message | Message to send to the recipient.
|===

After you complete your configuration, you can click Save Changes. To exit the configuration and return to the dashboard, simply click the `X`.
