= About Logs

The Monitoring Center aggregates your log files so you can manage, search for, filter, and analyze your logs. You can use aggregated logs in conjunction with monitoring to help identify causes and investigate failures quickly.

=== Searching Logs

You can search for text within logs using full terms, such as `"code 400"` for a bad request. For exact matches when there is white space between search terms, you need to surround your search term in quotation marks. Here are the results of the search:

image::log-search-string[Log Search]

You can also use wildcards such as `payload=org.glassfish.grizzly*`. Here are the results of that search:

image::log-search-wildcard[Log Search Using a Wildcard]

=== Filtering Logs

The Monitoring Center provides a query

[cols="1,3", ]
|===
| Filter | Description
| `_id` | The log identifier (ID).
|  `_index` |
|  `_type` |
|  `application` |
|  `class` |
|  `environment` |
|  `environment type` |
|  `host` |
|  `log level` |
|  `environment` |
|  `` | 
|===

//*TODO |NEED STEPS & INFO ON APP NETWORK DIAGNOSTIC LOG SEARCH, BEHAVIOR WITH INSIGHTS?*
////
App network diagnostic log search |Limited, Singe App (base subscription) vs. Included for Premium Add on

Can we action on an alert from the portal, say retry or skip thetransaction which generated the alert?Yes, transactions can be retried and skipped when Insights is turned on.
////


////
TODO |NEED DESCRIPTIONS
* Log-based profiler?
* Thread and heap dump
////

All of these use cases aim to help you expedite the process of finding and addressing issues:

* Support for comparative analysis and identification of event and information patterns based on searches across selected Mule apps and environments.
* Ability to search within the logs of a specific worker (or set of workers) for a Mule app so that you can narrow scope of issues to check.
* Ability to share a snapshot of important logs with developers who can work on the source of the issue.



////
Log Designs
Logs supported actions
Logs filtering and facets
Logs filtering through content (interactive with hotspots)
Navigating within selected logs

Explorations
Logs filtering and facets explorations
////
