= About Logs

The Monitoring Center aggregates your log files so you can manage, search, and analyze your logs. You can use aggregated logs in conjunction with monitoring to help identify causes and investigate failures quickly.

//*TODO: NEED STEPS & INFO ON APP NETWORK DIAGNOSTIC LOG SEARCH, BEHAVIOR WITH INSIGHTS?*
////
App network diagnostic log search: Limited, Singe App (base subscription) vs. Included for Premium Add on

Can we action on an alert from the portal, say retry or skip thetransaction which generated the alert?Yes, transactions can be retried and skipped when Insights is turned on.
////


////
TODO: NEED DESCRIPTIONS
* Log-based profiler?
* Thread and heap dump
////

All of these use cases aim to help you expedite the process of finding and addressing issues:

* Support for comparative analysis and identification of event and information patterns based on searches across selected Mule apps and environments.
* Ability to search within the logs of a specific worker (or set of workers) for a Mule app so that you can narrow scope of issues to check.
* Ability to share a snapshot of important logs with developers who can work on the source of the issue.



////
Log Designs
Logs supported actions
Logs filtering and facets
Logs filtering through content (interactive with hotspots)
Navigating within selected logs

Explorations
Logs filtering and facets explorations
////
