= Using Logs

The Monitoring Center aggregates your log files so you can manage, search for, filter, and analyze your logs. You can use aggregated logs in conjunction with monitoring to help identify causes and investigate failures quickly.

=== Searching Logs

You can search for text in logs in a couple of ways:

* Using Elasticsearch Query DSL. The Logs UI provides a link to the query documentation.
+
image::log-filter-timestamp[Filter Using Elasticsearch Query]
+
* Typing your search query into the search field.
+
You can provide full terms, such as `"code 400"` for a bad request. For exact matches to multi-worded searches, you need to surround your search in quotation marks. Here are the results of the search:
+
image::log-search-string[Log Search]
+
You can also provide wildcards such as `payload=org.glassfish.grizzly*`. Here are the results of that search:

image::log-search-wildcard[Log Search Using a Wildcard]

=== Filtering Logs

The Monitoring Center provides a query

[cols="1,3", ]
|===
| Filter | Description
| `_id` | The log identifier (ID).
|  `_index` |
|  `_type` |
|  `application` |
|  `class` |
|  `environment` |
|  `environment type` |
| `envType.keyword`   |
|  `host` |
|  `host.keyword` |
|  `message` |
|  `message.keyword` |
|  `orgId.keyword` |
|  `source` |
|  `source.keyword` |
|  `timestamp` |
|  `worker` |
|  `workerId.keyword` |
|===
