= Metrics-Based Monitoring
1.
User story
As a sysadmin I want to be able to see a holistic view of my environment so that I can at a glance make sense of the overall health of my environment and identify anomalies as soon as possible so that I can prevent potential future issues from happening.

Supporting feature
Cross environment Built-in dashboards  (out of the box dashboard)

Design
Early explorations

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2.
User story
As a sysadmin I want to be able to drill down from within my overview summary dashboards to the information most pertinent to the current task.

Supporting feature
Automatically linking cross environment built in dashboard chart lines to their correlated resource level dashboard
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

3.
User story
As a sysadmin after solving a significant problem/s related to a resource/s I need to be able to monitor the resource/s for a while so that I can detect other minor problems that could be causing the same symptoms.

Supporting feature
Customizing what to be shown in the monitoring center landing page (Adding the resource’s widgets to the Monitoring center landing page
