= Deploying

As of version 3.1, Mule standalone can run multiple applications. This means you can include the same name spaces within different applications and they will neither collide nor share information.

* In effect, it's now an app server.
* In addition, Mule checks for new apps (in the apps directory) and will start them.
* It will also restart apps if it detects that they have changed, meaning you can drop a revised version of an existing, running application into the /apps directory, Mule will stop the existing app and restart using the new files.
* This results in one fewer reason to run Mule inside a container.

* link:deployment-scenarios[Deployment Scenarios]
* link:mule-high-availability-ha-clusters[Mule High Availability HA Clusters]
* link:mule-deployment-model[Mule Deployment Model]
* link:configuring-logging[Configuring Logging]
* link:mule-server-notifications[Mule Server Notifications]
* link:profiling-mule[Profiling Mule]
* link:hardening-your-mule-installation[Hardening your Mule Installation]
* link:configuring-mule-for-different-deployment-scenarios[Configuring Mule for Different Deployment Scenarios]
* link:using-subversion-with-studio[Using Subversion with Studio]

