= Streaming

Streaming enables efficient processing of large data objects such as files, documents, and records by streaming the data through Mule ESB rather than reading the whole thing into memory. Streaming provides the following advantages:

* Allows flows to consume very large messages in an efficient way
* Message payloads are not read into memory
* Simple routing rules based on message metadata are still possible
* You can combine streaming and non-streaming endpoints

== Streaming Transports Connectors and Modules

The following transports, connectors and modules support streaming:

* link:cxf-module-reference[CXF]
* link:streaming-data-processing-with-datamapper[DataMapper]
* link:file-transport-reference[File] (set the `streaming` attribute to false to access the File object directly)
* link:ftp-transport-reference[FTP]
* HTTP and HTTPS
* link:jetty-transport-reference[Jetty] and link:jetty-ssl-transport[Jetty SSL]
* link:servlet-transport-reference[Servlet]
* link:tcp-transport-reference[TCP]
* link:udp-transport-reference[UDP]
* link:vm-transport-reference[VM]

== Streaming Transformers and Filters

Many transformers and filters can read input streams, process the contents, and send them on. However, most of these do not process the stream in real time; instead, they read the stream, load it into memory, process it, and then send it on. Therefore, transformers and filters can become a bottleneck in your application if you regularly stream large files.

The following transformers and filters do support true streaming and process the data as streams without loading them into memory first:

* link:xslt-transformer[XSLT Transformer]
* link:xmltoxmlstreamreader-transformer[XmlToXMLStreamReader Transformer]
* link:domtoxml-transformer[DomToOutputHandler transformer] (if the incoming XML format is a SAXSource or XMLStreamReader)
* link:sxc-module-reference[SXC filter]
