:keywords: agent, mule, esb, servers, monitor, notifications, external systems, third party, get status, metrics

= Advanced Usage

The topics under this document describe the underlying architecture and the advanced configuration settings for the Mule Agent.

For the vast majority of use cases, all you'll need to do with the Mule Agent is install it and configure it according to what you can read in link:/runtime-manager/installing-and-configuring-mule-agent[Installing and Configuring the Mule Agent]

If you wish to use the Mule Agent for more than managing the communication between the link:/runtime-manager/index[Runtime Manager] and Runtimes on-premises, then you may find the documents in this section helpful:

* link:/runtime-manager/mule-agent-architecture[Mule Agent Architecture]
* link:/runtime-manager/mule-agent-api[Agent API]
* link:/runtime-manager/event-tracking[Event Tracking]
* link:/runtime-manager/internal-handler-buffering[Internal Handler Buffering]
* link:/runtime-manager/extending-the-mule-agent[Extending the Mule Agent]

[NOTE]
None of these topics relate to the link:/mule-management-console/v/3.8/index[Mule Management Console]. These topics are about the Mule Agent that communicates the Runtime Manager with local runtimes.
