= CloudHub Load Balancer
:keywords: cloudhub, runtime manager, arm, load balancing, vanity url, ssl, two way tls,


== Overview

CloudHub features a backend load-balancing service designed to automate the provisioning of infrastructure components.

By using this service to proxy your CloudHub-deployed apps, you can:

. Enforce two way SSL authentication
. Enforce SSL authentication with custom certificates
. Easily configure proxy rules that map your CloudHub applications to custom domains, enabling you to for example host everything under a single vanity domain
. Handle Load balancing amongst the different CloudHub workers that run your application

[NOTE]
--
This is an optional addition to your cloud infrastructure that is not included by default in all CloudHub plans. To enable it, you must first own a link:/runtime-manager/virtual-private-cloud[Virtual Private Cloud].
You can associate multiple environments to the same VPC, meaning that you can use the same load balancer for your different environments.
--

== Load Balancer Architecture

Each Load Balancer has an internal domain name.
The structure is `<lb-name>-internal.lb.anypointdns.net` where `<lb-name>` is the name you gave the load balancer when you created it. This is the reason why the load balancer`s name must be unique.

Additionally, each load balancer has an external domain name that you can ping from outside your network: `<lb-name>.lb.anypointdns.net` where `<lb-name>` is the name you gave the load balancer when you created it.

If you want your load balancer to handle all connections to your application and you don´t want your default domain name for your application publicly exposed, then your application needs to be listening over http on port 8091 or 8092, or you can create a custom mapping policy to redirect outside requests from your load balancer to your specific application.

[NOTE]
--
Your load balancer listens for outside requests over https, but it communicates internally with your worker over http. If your Mule application is listening over https, it won´t be able to communicate with your load balancer.
--

== Using the Load Balancer

Although this feature will eventually be built into the Runtime Manager UI, currently it’s only available as a service that can be used via the link:/runtime-manager/anypoint-platform-cli[Anypoint Command Line Interface] or using the link:/runtime-manager/runtime-manager-api[Cloudhub API] through the endpoints `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/loadbalancers` and `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/vpcs`.

[NOTE]
--
For a full list of Anypoint-CLI commands and their respective usage, check our link:/anypoint-platform-for-apis/anypoint-platform-cli#list-of-commands[reference page]. +
A full description of `loadbalancers` and `vpcs` endpoints is available accesing your link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal].

In the link above, search among other Mule APIs for the "CloudHub" API and enter its latest version.
--

=== Mapping

The load balancer configuration is defined by a list of <<Mapping Rules, mapping rules>> which describe how input URL should be translated into calls to different CloudHub apps.

When creating a simple matching rule, one input address is literally matched to the defined output: the endpoint of one of your applications. +
Instead of using literal matchings you can also use a *Pattern* to match a variable-like input text to an endpoint.

By using proxy rules, you can map a domain or subdomain to one of your Mule applications that run in CloudHub

==== Pattern

A pattern is a string that defines a template for matching an input text. Whatever is placed into curly brackets (`{   }`) is treated like a variable.
These variables can contain only letters (a-z) and cannot contain any other characters, such as digits, slashes, etc. The variable values can contain the following characters ‘a-z0-1.&?-_’ but no slashes.

For example, you can literally bind two host names for redirect:

[source,Example,linenums]
----
‘app.example.com’ -> ‘app/example’
----

Or you can define a pattern to hold the input value:

[source,Example,linenums]
----
‘example.com/{mypattern}’ -> `app/{mypattern}`
----

The example above causes that both ’example.com/bookings’ and ‘example.com/sales’ match to `app/bookings` and `app/sales` respectively, as the variable `mypattern` holds these values. +
For input=”bookings.example.com”, the pattern can be resolved by assigning `_mypattern_=”bookings” and for input=`sales.example.com`, the pattern is resolved asignining `_mypattern_=”sales”

Depending on your design, you can choose to leverage your internal redirects to your endpoints using patterns or simply literal mappings.

== Mapping Rules

A mapping rule is a set of fields that define an *Input URL*, and a set of fields that describe the *Output URL*.

* The _input URL_ is described using a URI parameter which can be specified by the user:
. *URI* - a String or Pattern that describes the Input URI.
+
[NOTE]
--
The input URL follows the main load balancer’s domain (This value should remain constant for the same load balancer)
--
+
* The _Output URL_ is specified by two fields.
. *appName* - Output CloudHub application name where the request will be forwarded to.
. *appURI* - the URI string that is passed to the resolved application.

Both input and output URLs can be defined using patterns or literal Strings.

Mapping rules are attributes of the load balancer's SSL endpoint, which is identified by the certificate name. +
When you create a mapping rule, you need to specify a certificate CN. Omitting the `[certificateName]` parameter adds the mappings to the default endpoint.

If your SSL endpoint sets a link:https://en.wikipedia.org/wiki/Wildcard_certificate[wildcard certificate], and you want to use the subdomain portion in a mapping rule, you can use the pre-defined `{inputsubdomain}` variable.

The rule which is defined first has high priority against other ones defined after it. This means that the first matched rule will be applied. +
You can create, view and delete existing rules using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[mappings add], link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-describe[mappings describe] and link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-remove[mappings remove] commands respectively.

=== Rule Examples

The table below contains some rule examples:

[NOTE]
Given that the external load balancer domain name depends on the unique name you assign to it, assume that the load balancer in these examples is `lb-demo`.

[CAUTION]
--
By default your load balancer listens external requests on https and communicates with your workers internally through http. +
You need to configure your application to listen through `http` on port 8091 for your load balancer to reach it.
--

==== URL mapping

You can pass the app name as an input URI and map it directly to the app name in CloudHub:

[%header,cols="10a,20a,20a,10a"]
|===
|Rule # |Input URL 2+^| Output URL
|   |    *URI*   |       *appName*   |   *appURI*
| 0 | /{app}/    | {app}             | /
|===

This rule maps `lb-demo.lb.anypointdns.net/{app}` to `{app}.cloudhub.io`. +
{app} being a pattern for application name you choose to pass.

==== Host mapping

If you have a wildcard certificate (like `*.example.com`), you can use the ´inputSubdomain´ variable to map any subdomain:

[%header,cols="10a,20a,20a,10a"]
|===
|Rule # |Input URL 2+^| Output URL
|   |  *URI*   |       *appName*    |  *appURI*
| 0 | /        | {inputSubdomain}   | /
|===
This rule automatically maps any request passed to a subdomain of example.com to the corresponding appName. For example:

* Passing `api.example.com` would redirect to `api.cloudhub.io` +
* Passing `application.example.com` is mapped to `application.cloudhub.io`.

==== 1:1 mapping

If you have only one application, you can map the literal app name.

[%header,cols="10a,20a,20a,10a"]
|===
|Rule # |Input URL 2+^| Output URL
|   |  *URI*  |   *appName* |   *appURI*
| 0 | /       |    myApp    | /
|===
This maps your default load balancer `lb-demo.lb.anypointdns.net` directly to your app in Cloudhub `myApp.cloudhub.io`.

=== Rule Order

Rules are grouped into groups by same subdomain name. Groups with longer subdomain names are checked first. So rules with short subdomain name (numbers or symbols) have less priority. The group with empty subdomain name is checked last.

Within a group (rules with same subdomain) the rules with longer inputURI expressions are checked first, and if they don’t match, the rules with shorter inputURI expressions are checked.


[WARNING]
--
Rules order is essential.
It’s highly recommended to pay attention to the rules’ order when creating them as it's currently not possible to edit them.
--

==== Setting a Rule Priority Order

You can set an order when creating the rule using the link:/runtime-manager/anypoint-platform-cli#cloudhub-add-lb-rule[cloudhub-add-lb-rule] command in the Anypoint-CLI by specifying an index value.

When using the API, you can't specify a priority order, but you can send a `PUT` request to the endpoint `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/loadbalancers/{loadbalancerId}` and update your rules expressions to match your needs based on the order logic explained above (longer URIs within the same subdomain are checked first).

[NOTE]
--
The load balancer ID is provided to you when you create it. +
You can also perform a `GET` request to your endpoint /organizations/{orgid}}/loadbalancers` to get the ID.
--

== Whitelists

It is possible to whitelist a list of IP addresses from your load balancers by simply passing it a CIDR block of IPs to whitelist.

The whitelist works for inbound connections at the load balancer level, not at the CN certificate level. Make sure you only pass IP addresses. +
It is recommended that in order to whitelist inbound connections to your load balancer, you configure your workers to use link:/runtime-manager/deploying-to-cloudhub#static-ips-tab[static IP addresses]

== Managing Certificates

The Cloudhub Load Balancer provides a 2-way SSL client authentication. +
It allows you to provide a `.pem` file certificate to your load balancer´s SSL endpoint to validate client requests.

=== Uploading Certificates

The certificate that you upload to your Load Balancer must be contained in one _pem_ encoded and unencrypted file.
This file must contain the entire certificate chain ordered one after the other, similar to the example section below:

[%header,cols="30a,70a"]
|===
| Certificate | Example
| The Primary Certificate | -----BEGIN CERTIFICATE----- +
(Your Primary SSL certificate: your_domain_name.crt) +
-----END CERTIFICATE-----
| The Intermediate Certificate | -----BEGIN CERTIFICATE----- +
(Your Intermediate certificate: DigiCertCA.crt) +
-----END CERTIFICATE-----
|===


[NOTE]
--
It is not necessary to include the root certificate in the certificate chain. However, make sure to include the beginning and end tags on each certificate.
--

You can upload an SSL-Endpoint to your load balancer when creating one using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-create[cloudhub load-balancer create] or upload a new SSL endpoint to an existing load balancer using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-ssl-endpoint-add[cloudhub load-balancer ssl-endpoint add] command.

==== Certificate Validation

The load balancer passes the certificate data to the API using the http headers below:

===== X-SSL-Client-Verify

This header returns either `SUCCESS`, `FAILED`, or `NONE`
Only after `SUCCESS`, the client is verified. +
It returns `NONE` when the certificate is not present and `FAILED` when other validation problems occur.

===== X-SSL-Client-DN

Contains the full Distinguished Name of the client certificate.

===== X-SSL-Issuer

Contains the full Distinguished Name of the issuing certificate.

===== X-SSL-Client-Serial

Contains the serial number used by the CA to identify the client.

==== Adding Revocation Lists

CloudHub Load balancer does not support OCSP, so you need to manage your revocations using CRL.

You can add a revocation list when creating the load balancer using the ´-crl´ option in your link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-create[load-balancer create] command.

Additionally if your load balancer is already created, you can use the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8617/versions/85955[REST API] to update it. +
You can send a `PATCH` request to the `/organizations/{orgid}/vpcs/{vpcId}/loadbalancers/{lbId}` endpoint adding a `revocationList` element:

[source,json,linenums]
----
[
  {
    "op": "replace",
    "path": "/sslEndpoints/0/revocationList",
    "value": "-----BEGIN X509 CRL-----\nMIIBTTCBtwIBATANBgkqhkiG9w0BAQUFADBXMQswCQYDVQQGEwJBVTETMBEGA1UE\nCBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRk\nMRAwDgYDVQQDEwdvcmcuY29tFw0xNjAzMTUwOTI2MThaFw0xODAzMTUwOTI2MTha\nMBwwGgIJAIBvvO4dJHjhFw0xNjAzMTUwODUwMTZaoA4wDDAKBgNVHRQEAwIBBjAN\nBgkqhkiG9w0BAQUFAAOBgQCCAbGXW+Hnzmd1bXqWsFXfogOsJScoxkJOhhmjui3I\nhTUyO5plGHUBLjBnDkypM+iLfn0W4wPcNj7FZdz4Hu/WLntxwrTtR5YOcfIhEGcq\nwvJq/1+WKUPC6eqGwx0iKOOBIWsaf5CNOOUQMo6RaeTeu8Uba2EGFk1Vu/SoZYAK\nsw==\n-----END X509 CRL-----\n"
  }
]
----

[NOTE]
--
It is recommended to use the CloudHub REST API to programmatically update your revocation lists. +
In order to get the necessary vpcId, and loadbalancerId from the CLI, you can use a link:/runtime-manager/anypoint-platform-cli#cloudhub-vpc-describe-json[vpc JSON describe] and link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-describe-json[load-balancer JSON describe] command respectively.
--

You can send a PATCH request to your load balancer's endpoint to update any other property.


==== Certificate Ciphers

A list of recommended ciphers suites with a good balance between compatibility and security for your SSL endpoint are below: +
They all offer forward secrecy, except RC4-SHA which is there to support Internet Explorer 8.

----
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES128-GCM-SHA256
ECDHE-RSA-AES256-SHA384
ECDHE-RSA-AES128-SHA256
ECDHE-RSA-AES256-SHA
ECDHE-RSA-AES128-SHA
DHE-RSA-AES256-SHA256
DHE-RSA-AES128-SHA256
DHE-RSA-AES256-SHA
DHE-RSA-AES128-SHA
ECDHE-RSA-DES-CBC3-SHA
EDH-RSA-DES-CBC3-SHA
AES256-GCM-SHA384
AES128-GCM-SHA256
AES256-SHA256
AES128-SHA256
AES256-SHA
AES128-SHA
DES-CBC3-SHA
----

ClourHub´s dedicated load balancer supports TLSv1.1 and TLSv1.2. Additionally you can configure TLS v1.0, but bear in mind that such protocol is no longer accepted by PCi compliance due to its significant vulnerabilities.

== See Also

* Learn how to manage your deployed applications and load balancers using link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI]. +
* Learn how to interact directly with your applications using link:/runtime-manager/runtime-manager-api[Runtime Manager API]. +
* Check out the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties and expected responses. Just search among other Mule APIs for the "CloudHub" API and click on its latest version.
