= About Cloudhub Dedicated Load Balancer
:keywords: cloudhub, runtime manager, arm, load balancing, vanity url, ssl, two way tls,

CloudHub features a backend load-balancing service designed to automate the provisioning of infrastructure components. You can use this service to deploy one or more custom load-balancers within a link:/runtime-manager/virtual-private-cloud[VPC].

[NOTE]
You must have at least one VPC defined in your organization before you can configure a dedicated load balancer. 

Each dedicated load balancers allows you to:

. Handle Load balancing amongst the different CloudHub workers that run a Mule application.
. Define <<SSL Endpoints,SSL configurations>> to provide custom certificates and optionally enforce two-way SSL client authentication.
. Easily configure <<Mapping Rules,proxy rules>> that map your applications to custom domains, enabling you to for example host everything under a single vanity domain.

[NOTE]
--
This is an optional addition to your Anypoint infrastructure that is not included by default in all Anypoint Platform plans. Prior to a Dedicated Load Balancer's creation, you must first have an Anypoint link:/runtime-manager/virtual-private-cloud[Virtual Private Cloud] created for your organization.
You can associate multiple environments to the same VPC, meaning that you can use the same dedicated load balancer for your different environments.
--

Check the <<Creating and Configuring a Dedicated Load Balancer>> section for more information.


== Load Balancer Architecture

A CloudHub Dedicated Load Balancer can be used to route both internal and external traffic, and can route requests for multiple deployed Mule applications. 

A CloudHub Dedicated Load Balancer is assigned to a particular Virtual Private Cloud (VPC). The dedicated load balancer then routes traffic to that particular VPC within the particular service region of the VPC. 

[NOTE]
For a Mule application to be managed by the dedicated load balancer, the Mule application must be deployed into the VPC for the dedicated load balancer.  


Your CloudHub Dedicated Load Balancer has an internal domain name to be used by applications and clients within the VPC.
The structure is `internal-<lb-name>.lb.anypointdns.net` where `<lb-name>` is the name you give the load balancer when you created it.
Additionally, your Dedicated Load Balancer exposes an external domain name resolving to 2 public IP addresses which can be reached from outside of your CloudHub VPC network: `<lb-name>.lb.anypointdns.net` where `<lb-name>` is the name you gave the load balancer when you created it.

Each Dedicated Load Balancer has a DNS A Record `<lb-name>.lb.anypointdns.net` resolving to 2 Public IP addresses of its two instances. +
Through your DNS provider, you can add a CNAME record pointing to this A record and use your own domain names to access.

If you want your load balancer to handle all connections to your application and you don't want your default domain name for your application publicly exposed, then each application needs to be listening over HTTP on port *8091* or *8092*, or you can create a custom mapping policy to redirect outside requests from your load balancer to your specific application.

[NOTE]
--
Your load balancer listens for outside requests over HTTPS and, by default, communicates internally with your worker over HTTP. If you configured your Mule application within the VPC to listen on HTTPS, make sure you set `upstreamProtocol` to `HTTPS` when creating the mapping list using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[load-balancer mappings add] command.
--

== SSL Endpoints

By providing a certificate and private key pair, you configure an *SSL endpoint* for your load balancer to serve to clients. +
Each load balancer can have multiple and independent SSL endpoints. Each one of them identified by their server certificate common name.

[NOTE]
A dedicated load balancer needs to have at least one certificate associated to it, meaning that at least one SSL endpoint needs to be configured when creating the load balancer.

=== Requirements

To associate an SSL endpoint you need to provide:

. One file containing a pem encoded and not encrypted certificate file.
. A second file containing the private key of your `.pem` certificate.
+
[CAUTION]
The private key file needs to be _passphraseless_

Each SSL Endpoint can have multiple CA certificates and CRLs. Each of these certificates needs to be provided in a single unencrypted, _pem_ encoded file. Ordering for independent CA certificates is not important, but certificates in a chain of trust must be concatenated together.

=== Uploading Certificates

The certificate that you upload to your Load Balancer must be contained in one _pem_ encoded and unencrypted file.
This file could contain the entire certificate chain ordered one after the other, similar to the example section below:

[%header,cols="30a,70a"]
|===
| Certificate | Example
| The Primary Certificate | -----BEGIN CERTIFICATE----- +
(Your Primary SSL certificate: your_domain_name.crt) +
-----END CERTIFICATE-----
| The Intermediate Certificate | -----BEGIN CERTIFICATE----- +
(Your Intermediate certificate: DigiCertCA.crt) +
-----END CERTIFICATE-----
|===

[NOTE]
--
It is not necessary to include the root certificate in the certificate chain. However, make sure to include the ASCII armor in each certificate.
--

[NOTE]
You can upload an SSL-Endpoint to your load balancer when creating one using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-create[cloudhub load-balancer create] or upload a new SSL endpoint to an existing load balancer using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-ssl-endpoint-add[cloudhub load-balancer ssl-endpoint add] command.

=== Certificate Validation

If at least one CA certificate is provided for the SSL endpoint, the load balancer passes the client certificate data to the API using the HTTP headers below:

==== X-SSL-Client-Verify

This header returns either `SUCCESS`, `FAILED`, or `NONE`
Only after `SUCCESS`, the client is verified. +
It returns `NONE` when the certificate is not present and `FAILED` when other validation problems occur.

==== X-SSL-Client-DN

Contains the full Distinguished Name of the client certificate.

==== X-SSL-Issuer

Contains the full Distinguished Name of the issuing certificate.

==== X-SSL-Client-Serial

Contains the serial number used by the CA to identify the client.

=== Adding Revocation Lists

The CloudHub Load balancer can optionally verify client requests against Certificate Revocation Lists (CRL). All CRL files need to be concatenated into a single _pem_ encoded file for upload. Ordering is not important.

You can add a revocation list when creating the load balancer using the ´--crl´ option in your link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-create[load-balancer create] command.

Additionally, if your load balancer is already created, you can use the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8617/versions/85955[REST API] to update it. +
You can send a `PATCH` request to the `/organizations/{orgid}/vpcs/{vpcId}/loadbalancers/{lbId}` endpoint adding a `revocationList` element:

[source,json,linenums]
----
[
  {
    "op": "replace",
    "path": "/sslEndpoints/0/revocationList",
    "value": "-----BEGIN X509 CRL-----\nMIIBTTCBtwIBATANBgkqhkiG9w0BAQUFADBXMQswCQYDVQQGEwJBVTETMBEGA1UE\nCBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRk\nMRAwDgYDVQQDEwdvcmcuY29tFw0xNjAzMTUwOTI2MThaFw0xODAzMTUwOTI2MTha\nMBwwGgIJAIBvvO4dJHjhFw0xNjAzMTUwODUwMTZaoA4wDDAKBgNVHRQEAwIBBjAN\nBgkqhkiG9w0BAQUFAAOBgQCCAbGXW+Hnzmd1bXqWsFXfogOsJScoxkJOhhmjui3I\nhTUyO5plGHUBLjBnDkypM+iLfn0W4wPcNj7FZdz4Hu/WLntxwrTtR5YOcfIhEGcq\nwvJq/1+WKUPC6eqGwx0iKOOBIWsaf5CNOOUQMo6RaeTeu8Uba2EGFk1Vu/SoZYAK\nsw==\n-----END X509 CRL-----\n"
  }
]
----

=== Using the CloudHub REST API to Manage VPCs and Dedicated Load Balancers
--
It is recommended to use the CloudHub REST API to programmatically update your revocation lists. You can also use the CloudHub REST API to check the status of your VPCs and dedicated load balancers. In particular, you can make REST API requests to see the status after you deploy changes to your VPCs and dedicated load balancers. 

Many REST API calls require you to get the vpcId and loadbalancerId. Like the organizationId and environmentId tha is required for many Anypoint Platform REST API calls, these ids are not the same as the VPC and load-balancer names. 

+
In order to get the necessary vpcId and loadbalancerId from the Anypoint CLI, you can use a link:/runtime-manager/anypoint-platform-cli#cloudhub-vpc-describe-json[vpc describe-json option] and link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-describe-json[load-balancer describe-json option] command respectively to display the raw JSON response from the REST API. This will include all the raw data, including the vpn-id and load-balancer id, respectively.

For example, you can first list the available load-balancers for a particular Environment, within a particular business group, by using the anypoint-cli command:

[source,Example,linenums]
----
> cloudhub vpc list

┌────────────────────┬───────────────┬────────────────────┬────────────┬────────────┬────────────────────┬────────────────────┐
│ Name               │ Region        │ CIDR Block         │ Inherited  │ Default    │ Environments       │ Business Groups    │
├────────────────────┼───────────────┼────────────────────┼────────────┼────────────┼────────────────────┼────────────────────┤
│ MyVPC              │ us-west-2     │ 10.0.0.0/16        │ No         │ Yes        │ Production         │ MyBusinessGroup    │
└────────────────────┴───────────────┴────────────────────┴────────────┴────────────┴────────────────────┴────────────────────┘

----

Suppose this returns a vpc named MyVPC. You can then get the id for MyVPC by running the anypoint-cli commmand:

[source,Example,linenums]
----
> cloudhub vpc describe-json MyVPC

{ id: 'vpc-c6cb8cbf',
  name: 'MyVPC',
  region: 'us-west-2',
  cidrBlock: '10.0.0.0/16',
  internalDns: { dnsServers: [], specialDomains: [] },
  isDefault: true,
  associatedEnvironments: [ 'b139880f-1df7-4165-8449-b968adb80ee1' ],
  ownerId: '9d63be6d-df6f-4454-9d95-5c5a7f3fa07c',
  sharedWith: [],
  firewallRules: 
   [ { cidrBlock: '10.0.0.0/16',
       protocol: 'tcp',
       fromPort: 8092,
       toPort: 8092 },
     { cidrBlock: '0.0.0.0/0',
       protocol: 'tcp',
       fromPort: 8082,
       toPort: 8082 },
     { cidrBlock: '10.0.0.0/16',
       protocol: 'tcp',
       fromPort: 8091,
       toPort: 8091 },
     { cidrBlock: '0.0.0.0/0',
       protocol: 'tcp',
       fromPort: 8081,
       toPort: 8081 } ] }----

This will print out the raw JSON with all the details for MyVPC, including the `id` key/value pair. 

You can also view the load-balancers associated with the VPC. For example: 

[source,Example,linenums]
----
> cloudhub vpc describe-json MyVPC
┌──────────────────────────────┬────────────────────────────────────────────────────────────────┐
│ Name                         │ MyVPC                                                          │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Region                       │ us-west-2                                                      │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ CIDR Block                   │ 10.0.0.0/16                                                    │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Inherited                    │ No                                                             │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Organization default         │ Yes                                                            │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Special domains              │                                                                │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ DNS Servers                  │                                                                │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Firewall rules               │ 5                                                              │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Environments                 │ Production                                                     │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Business groups              │                                                                │
├──────────────────────────────┼────────────────────────────────────────────────────────────────┤
│ Load balancers               │ mydlb                                                          │
└──────────────────────────────┴────────────────────────────────────────────────────────────────┘
----


You can also list all the load-balancers in the current environment and business group, then verify which VPC is associated with a particular load-balancer:

[source,Example,linenums]
----
> cloudhub load-balancer list

┌────────────────────┬────────────────────┬──────────┬────────────────────┬────────────────────┬────────────────────────────────────────┐
│ Name               │ Domain             │ Status   │ VPC                │ IPs                │ Primary Certificate                    │
├────────────────────┼────────────────────┼──────────┼────────────────────┼────────────────────┼────────────────────────────────────────┤
│ mydlb              │ lb.anypointdns.net │ STARTED  │ MyVPC              │ 34.218.203.107     │ *.example.com                         │
│                    │                    │          │                    │ 52.33.162.33       │                                        │
└────────────────────┴────────────────────┴──────────┴────────────────────┴────────────────────┴────────────────────────────────────────┘

----

Once you know the dedicated load-balancer assigned to the VPC, you can get the load-balancer's id using a command like: 

[source,Example,linenums]
----
> cloudhub load-balancer describe-json mydlb

{ id: '5ac3cd7ce4b04ff3d4793cdf',
  name: 'mydlb',
  domain: 'lb.anypointdns.net',
  state: 'STARTED',
  ipAddresses: [ '34.218.203.107', '52.33.162.33' ],
  ipWhitelist: [ '0.0.0.0/0' ],
  httpMode: 'redirect',
  defaultSslEndpoint: 1,
  sslEndpoints: 
   [ { privateKeyDigest: '018e174606dedb09eed8a2bc754d2e5812514c44',
       publicKeyLabel: 'example-com-san-crt.pem',
       publicKeyDigest: 'f7bdcec99fb2339933a8717f0af50a67a7dd73d6',
       publicKeyCN: 'learn.mulesoft.com',
       privateKeyLabel: 'example-com-private-decrypted.pem',
       verifyClientMode: 'off',
       tlsv1: false,
       mappings: 
        [ { inputUri: '/',
            appName: '{subdomain}-app',
            appUri: '/',
            upstreamProtocol: 'http' } ] },
     { privateKeyDigest: '568dc9fa0767d056087c3eb252ec7312bea70aac',
       publicKeyLabel: 'example-com-wildcard-crt.pem',
       publicKeyDigest: 'fa34cdbc545cef64e72c63b1f08863d2809bb52b',
       publicKeyCN: '*.example.com.com',
       privateKeyLabel: 'example-com-wildcard-private-decrypted.pem',
       verifyClientMode: 'off',
       tlsv1: false,
       mappings: 
        [ { inputUri: '/',
            appName: '{subdomain}-app',
            appUri: '/',
            upstreamProtocol: 'http' } ] } ],
  staticIPsDisabled: false,
  vpcId: 'vpc-c6cb8cbf',
  workers: 2,
  vpc: { id: 'vpc-c6cb8cbf', name: 'MyVPC' } }
----

Once you have teh vpcId and loadbalancerId, you can make a REST API call to get the status of a load-balancer.

One easy way to run this command is with the Anypoint Platform Developer Portal. First navigate to https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals and select the latest version of the CloudHub REST API, then select the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8617/versions/2321502/pages/107964[API Reference tab]. 

Scroll to the /organizations/{orgid}/vpcs/{vpcId}/loadbalancers/{lbId}/deployments resource, the click GET then click TRY IT. Fill in the Username and Password for the owner of the business group where the dedicated load balancer is deployed. 

You can get the organization id using:

[source,Example,linenums]
----
> account business-group list

┌────────────────────────────────────────┬───────────────┬────────────────────────────────────────┐
│ Name                                   │ Type          │ Id                                     │
├────────────────────────────────────────┼───────────────┼────────────────────────────────────────┤
│ MyBG                                   │ Master        │ fd604b43-365c-42e8-810f-733a2b7f411f   │
└────────────────────────────────────────┴───────────────┴────────────────────────────────────────┘
----

Now you can fill in the organizationId, vpcId, and loadbalanderId values. 

When you click GET, if all the ids are correct, you should receive a 200 status response. In the body is a history of every deployment to this dedicated load-balancer. The most recent deployment will be listed first in the JSON response:

[source,Example,linenums]
----
{
  "data": [
    {
      "id": "5ac41c26e4b04ff3d47a5e58",
      "state": "DONE",
      "ticketConfig": "{\"id\":\"5ac3cd7ce4b04ff3d4793cdf\",\"name\":\"mydlb\",\"prvtDomainPrefix\":\"mule-worker-internal-\",\"prvtDomainSuffix\":\"cloudhub.io\",\"imageName\":\"NGINX_V3\",\"instanceSize\":\"c4.large\",\"vpcId\":\"vpc-c6cb8cbf\",\"workers\":2,\"deploymentId\":\"5ac41c26e4b04ff3d47a5e58\",\"activeDeploymentId\":\"5ac41b0ee4b04ff3d47a5aaa\",\"staticIPsCount\":2,\"version\":17}",
      "createTime": 1522801702520,
      "startTime": 1522801702981,
      "endTime": 1522801760928
    },
    {
      "id": "5ac41b0ee4b04ff3d47a5aaa",
      "state": "DONE",
      "ticketConfig": "{\"id\":\"5ac3cd7ce4b04ff3d4793cdf\",\"name\":\"mydlb\",\"prvtDomainPrefix\":\"mule-worker-internal-\",\"prvtDomainSuffix\":\"cloudhub.io\",\"imageName\":\"NGINX_V3\",\"instanceSize\":\"c4.large\",\"vpcId\":\"vpc-c6cb8cbf\",\"workers\":2,\"deploymentId\":\"5ac41b0ee4b04ff3d47a5aaa\",\"activeDeploymentId\":\"5ac41a08e4b04ff3d47a5794\",\"staticIPsCount\":2,\"version\":16}",
      "createTime": 1522801422315,
      "startTime": 1522801422932,
      "endTime": 1522801483543
    }
  ],
  "total": 2
}
----

You can use this REST API call to troubleshoot deployment issues. 

For example, one common deployment issue is if you have misconfigured the certificate for one of the SSL endpoints in the dedicated load-balancer configuration. 

--

You can send a PATCH request to your load balancer's endpoint to update any other property.


=== Certificate Ciphers

A list of recommended ciphers suites with a good balance between compatibility and security for your SSL endpoint are below: +
They all offer forward secrecy, except RC4-SHA which is there to support Internet Explorer 8.

----
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-RSA-AES128-GCM-SHA256
DHE-RSA-AES256-GCM-SHA384
DHE-RSA-AES128-GCM-SHA256
ECDHE-RSA-AES256-SHA384
ECDHE-RSA-AES128-SHA256
ECDHE-RSA-AES256-SHA
ECDHE-RSA-AES128-SHA
DHE-RSA-AES256-SHA256
DHE-RSA-AES128-SHA256
DHE-RSA-AES256-SHA
DHE-RSA-AES128-SHA
AES256-GCM-SHA384
AES128-GCM-SHA256
AES256-SHA256
AES128-SHA256
AES256-SHA
AES128-SHA
----

ClourHub's dedicated load balancer supports TLSv1.1 and TLSv1.2. Additionally, you can configure TLS v1.0, but bear in mind that such protocol is no longer accepted by PCi compliance due to its significant vulnerabilities.


== Mapping Rules

The load balancer configuration is defined by a list of *Mapping Rules* which describe how input URL should be translated into calls to different CloudHub apps. +
Mapping rules are attributes of the load balancer's SSL endpoint. +
When you create a mapping rule, you need to specify a certificate CN. Omitting the `[certificateName]` parameter adds the mappings to the default endpoint.

When creating a simple matching rule, one input address is literally matched to the defined output: the endpoint of one of your applications. +
Instead of using literal matchings you can also use a *Pattern* to match a variable-like input text to an endpoint.

By using proxy rules, you can map a domain or subdomain to one of your Mule applications that run in CloudHub

=== Using Patterns in Mapping Rules

A pattern is a string that defines a template for matching an input text. Whatever is placed into curly brackets (`{   }`) is treated like a variable.
These variables can contain only letters (a-z) and cannot contain any other characters, such as digits, slashes, etc. The variable values can contain the following characters ‘a-z0-1.&?-_’ but no slashes.

Suppose you have set up a DNS CNAME records from  `example.com` to `<lb-name>.lb.anypointdns.net`. Then you can map `app.example.com` to a different deployed CloudHub Mule application name. 

For example, you can literally bind two hostnames for redirect:

[source,Example,linenums]
----
‘app.example.com’ ->  application: `app` URI: `/example’
----

In this case external requests to `https://app.example.com` would be directed to http://app.cloudhub.io/example

Or you can define a pattern to hold the input value:

[source,Example,linenums]
----
‘example.com/{mypattern}’ -> application: `app-{mypattern}` URI: /data
----

The example above ensures both ’example.com/bookings’ is directed to `app-bookings.cloudhub.io/data` and ‘example.com/sales’ is directed to ``app-sales.cloudhub.io/data`, as the variable `mypattern` holds these values. +

For input=”bookings.example.com”, the pattern can be resolved by assigning `_mypattern_=”bookings” and for input=`sales.example.com`, the pattern is resolved to assign `_mypattern_=”sales”

Depending on your design, you can choose to leverage your internal redirects to your endpoints using patterns or simply literal mappings.

[CAUTION]
Currently patterns in the application URI are not supported.

=== Creating Mapping Rules

A mapping rule is a set of fields that define an *Input URL*, and a set of fields that describe the *Output URL*.

* The _input URL_ is described using a URI parameter which can be specified by the user:
. *URI* - a String or Pattern that describes the Input URI.
+
[NOTE]
--
The input URL follows the main load balancer’s domain (This value should remain constant for the same load balancer)
--
+
* The _Output URL_ is specified by two fields.
. *appName* - Output the application name where the request will be forwarded to.
. *appURI* - the URI string that is passed to the resolved application.

Both input and output URLs can be defined using patterns or literal Strings.

Mapping rules are attributes of the load balancer's SSL endpoint, which is identified by the certificate name. +
When you create a mapping rule, you need to specify a certificate CN. Omitting the `[certificateName]` parameter adds the mappings to the default endpoint.

If your SSL endpoint sets a link:https://en.wikipedia.org/wiki/Wildcard_certificate[wildcard certificate], such as `*.example.com`, and you want to use the subdomain portion of an input URL in a mapping rule, you can use the pre-defined `{subdomain}` variable.

In the list of mapping rules, the rule which is defined first has high priority against other ones defined after it. This means that the first matched rule will be applied. +
You can create, view, and delete existing rules using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[mappings add], link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-describe[mappings describe] and link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-remove[mappings remove] commands respectively.

=== Mapping Rule Examples


The table below contains some mapping rule examples:

[NOTE]
Given that the external load balancer domain name depends on the unique name you assign to it, assume that the load balancer in these examples is `lb-demo`.

[CAUTION]
--
By default, your load balancer listens to external requests on HTTPS and communicates internally with your worker over HTTP. If you configured your Mule application within the VPC to listen on HTTPS, make sure you set `upstreamProtocol` to `HTTPS` when creating the mapping list using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[load-balancer mappings add] command.
--

==== URL Mapping

You can pass the app name as an input URI and map it directly to the app name in CloudHub:

[%header,cols="10a,20a,20a,10a"]
|===
|Rule # |Input URL 2+^| Output URL
|   |    *URI*   |       *appName*   |   *appURI*
| 0 | /{app}/    | {app}             | /
|===

This rule maps `example.com/{app}` to `{app}.cloudhub.io`. +
{app} being a pattern for any application name you choose to pass in the inbound request.

For this to work, you should configure a DNS CNAME record to route `example.com` to `lb-name.lb.anypointdns.net`, and you should configure the SSL endpoint with a certificate for the common name = example.com. 

This mapping will also work if you call the dedicated load-balancer directly. So https://lb-name.lb.anypointdns.net/{app}` routes to `http://app.cloudhub.io`. 




==== Host Mapping

If you have a wildcard certificate (like `*.example.com`), you can use the ´subdomain´ variable to map any subdomain:

[%header,cols="10a,20a,20a,10a"]
|===
|Rule # |Input URL 2+^| Output URL
|   |  *URI*   |       *appName*    |  *appURI*
| 0 | /        | {subdomain}        | /
|===
This rule automatically maps any request passed to a subdomain of example.com to the corresponding appName. For example:

* Passing `api.example.com` would redirect to `api.cloudhub.io` +
* Passing `application.example.com` is mapped to `application.cloudhub.io`.

The same applies for the link:https://en.wikipedia.org/wiki/Subject_Alternative_Name[Subject Alternative Names] (SANs) of your SSL Endpoints. +


Instead of using a wildcard certificate, which permits any subdomain application name to be passed through the dedicated load balancer, you can restrict the allowed subdomain names. To do this, you must have different SANs configured for a certificate's common name, you can use the ´subdomain´ variable to map the subdomain portion of your domain name to your application.  

For example, having:

* Two deployed applications:
** dev-app
** qa-app
* And an SSL endpoint with the Subject Alternative Names:
** dev.example.com
** qa.example.com
* The mapping rule:
+
[%header,cols="10a,20a,20a,10a"]
|===
|Rule # |Input URL 2+^| Output URL
|   |  *URI*   |       *appName*    |  *appURI*
| 0 | /        | {subdomain}-app   | /
|===

Then, this rule would map the subdomain part of your domain name to the application name:

* Passing `dev.example.com` redirects to `dev-app.cloudhub.io`.
* Passing `qa.example.com` redirects to `qa-app.cloudhub.io`.


==== 1:1 Mapping

If you have only one application, you can map the literal app name.

[%header,cols="10a,20a,20a,10a"]
|===
|Rule # |Input URL 2+^| Output URL
|   |  *URI*  |   *appName* |   *appURI*
| 0 | /       |    myApp    | /
|===
This maps your default load balancer `lb-demo.lb.anypointdns.net` directly to your app in Cloudhub `myApp.cloudhub.io`.

=== Indexing the Priority of Rules

When creating a _mapping rule_, you need to assign an index to it to define the rule's priority order. +
A rule defined first, at index `0` has higher priority against other rules defined after it. The higher the index assigned, the less priority the mapping rule has.

Every rule must have a priority defined.  It is highly recommended to pay attention to each rules’ order when creating them, and multiple rules might override each other.

==== Ordering and Prioritizing Rules

You can set the order of your mapping rules when creating them using the link:https://docs.mulesoft.com/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-mappings-add[cloudhub load-balancer mappings add] command in the Anypoint-CLI by specifying an index value.

When using the API to create a rule, you can not specify a priority order, but you can send a `PATCH` request later to the load balancer endpoint `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/loadbalancers/{loadbalancerId}` and update your rules expressions with an order index, to match your needs based on the order logic explained above.

[NOTE]
--
The load balancer ID is provided to you when you create it. +
You can also perform a `GET` request to your endpoint /organizations/{orgid}}/loadbalancers` to get the ID.
--

== Whitelists

In order to whitelist IP addresses to your load balancers, you need to pass those IP addresses in CIDR notation using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-whitelist-add[load-balancer whitelist add] command.

The whitelist works for inbound connections at the load balancer level, not at the CN certificate level. Make sure you only pass IP addresses.

== Creating and Configuring a Dedicated Load Balancer

[TIP]
In order to be able to create and configure a load balancer, your profile needs to be an administrator of the organization to which the load balancer is associated.

There are three ways of creating and configurin a dedicated load balancer for your VPC:

. Using the link:/runtime-manager/anypoint-platform-cli#cloudhub-load-balancer-create[cloudhub load-balancer create] command from the *Anypoint Platform Command Line Interface*
. Using the link:/runtime-manager/runtime-manager-api[Cloudhub API] through the endpoints `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/loadbalancers` and `anypoint.mulesoft.com/cloudhub/api/organizations/{orgid}/vpcs`.
. Using link:https://docs.mulesoft.com/runtime-manager/lb-create-arm[Runtime Manager] from the *Anypoint Platform UI*

[NOTE]
--
A full description of `loadbalancers` and `vpcs` endpoints is available accessing your link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal]. +
In the link above, search among other Mule APIs for the "CloudHub" API and enter its latest version.
--
