= About Clusters

A Cluster is a set of servers that act as a single deployment target, in which instances of the application are aware of one another and share common information and synchronize statuses.

An on-premise cluster enables up to 8 servers to participate in a high availability processing unit so that in case one server should fail, another server takes over processing applications. A cluster can run multiple applications.

[NOTE]
Remember that you must first <<Add a Server, register>> each of the servers in the cluster, by downloading and installing the same version of the link:https://www.mulesoft.com/platform/mule[Mule runtime] and then running the link:/runtime-manager/managing-servers#add-a-server[amc_setup] script on each.
A cluster can only be made up of servers that are not already in a server group or part of another cluster.

[NOTE]
The minimum Mule version that supports this feature is Mule version 3.7.0 and newer. The minimum Runtime Manager Agent version that supports this feature is Agent version 1.1.1 and newer.