= About Clusters

A Cluster is a set of servers that act as a single deployment target, in which instances of the application are aware of one another and share common information and synchronize statuses. An on-premise cluster enables up to 8 servers to participate in a high availability processing unit so that in case one server should fail, another server takes over processing applications. A cluster can run multiple applications.

Before creating a  cluster, you must create each of the Mule runtimes that are part of the cluster. You must download and install the same version of the Mule runtime. The supported versions of these components are:

* Mule runtime, version 3.7.0 and later.
* Runtime Manager Agent, version 1.1.1 and later.

Before creating a cluster, you must create each of the servers that connect your Mule runtimes to Runtime Manager.

== See Also

* Mule Runtime
* link:/runtime-manager/servers-setup-runtime[To Setup Your Runtime Environment to Create Servers, Server Groups, and Clusters]
* link:/runtime-manager/servers-create[To Create a Server]