= Create a VPC Using Anypoint Platform CLI

This section shows you how to create the same VPC set up from the Runtime Manager UI, using the Anypoint Platform CLI.

In your environment, link:/runtime-manager/anypoint-platform-cli#logging-in[log in to your organization] and use the link:/runtime-manager/anypoint-platform-cli#cloudhub-vpc-create[vpc create] command to create the VPC:

[source,Example]
----
cloudhub vpc create // <1>
vpc-tutorial // <2>
us-east-1 // <3>
10.111.0.0/24 // <4>
--default
----

In this example:

. Our VPC is called `vpc-tutorial`
. Is bound to the `us-east-1` region
+
[NOTE]
--
All VPCs need to be associated to a CloudHub region.
--
+
. We are setting the size to `10.111.0.0/24`. In CIDR notation, this grants us 256 IP addresses from 10.111.0.0 to 10.111.0.255.
+
[CAUTION]
--
It is not possible to resize a VPC once created. +
Understanding how to size your VPC is crucial at this point. If you are not sure how to configure this, make sure to follow our link:/runtime-manager/virtual-private-cloud#size-your-vpc[VPC sizing] guide
--
+
[NOTE]
--
We are *not passing* any environment information. +
Not setting a specific environment makes that every application deployed to US-EAST is associated to this VPC disregarding to which environment it is being deployed. +
All VPCs need to also be bound to an link:/access-management/environments[environment] inside your CloudHub organization or business group.
--
+
. We are setting it as default. This means that all environments in this region that are not associated to a VPC will be, by default, associated to this VPC.
+
[NOTE]
--
We are *not passing* any business group information. +
By doing so, we are associating this VPC to the main organization.
--
+
When the operation succeeds, the CLI shows you the details of the newly created VPC.


Once the VPC is created, All inbound traffic is blocked by default. You need to create firewall rules to allow traffic to your VPC. +
In order to do so, you need to use the link:/runtime-manager/anypoint-platform-cli#cloudhub-vpc-firewall-rules-add[vpc firewall-rules add] command:

[source,Example]
----
cloudhub vpc firewall-rules add
// <1>
vpc-tutorial // <2>
0.0.0.0/0 // <3>
tcp // <4>
8091
----

. Refer to the recently created `vpc-tutorial` VPC to set the new firewall rules.
. Set the IP range to allow all possible IP addresses by setting `0.0.0.0/0`. +
In CIDR notation, this allows the range 0.0.0.0 to 255.255.255.255.
. Set the whitelisted protocol to `tcp`
. Allow the port number `8091` +
Given that, by default, a link:/runtime-manager/cloudhub-dedicated-load-balancer[CloudHub dedicated load balancer] proxies all external communications to your workers through port 8091 (the default `http.private` port), setting this firewall rule allows your load balancer to communicate to your workers using its default configurations.
+
Additionally, in order to properly receive requests from the load balancer, all applications that we deploy to the VPC must be listening on port 8091.

You just created a private and isolated network in the US-EAST region and allowed inbound traffic to it through port 8091.
Learn how to associate a load balancer following the link:/runtime-manager/dedicated-load-balancer-tutorial[load balancer tutorial].

==== Update an Existing VPC

Although it is not possible to update certain values from your VPC through the Anypoint Platform CLI, you can use the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8617/versions/85955/pages/107964[Cloudhub API]:

Log in to the CloudHub services passing your credentials through the `https://anypoint.mulesoft.com/accounts/login` endpoint.

Then, update your VPC using a `PUT` request to the `qa.anypoint.mulesoft.com/cloudhub/api/organizations/<yourOrganizationId>/vpcs/<yourVPCId>/` endpoint with a JSON payload:

[source,json,linenums]
----
{
	"associatedEnvironments": [
		"<EnvironmentId>"
	]
}
----

[NOTE]
--
`<EnvironmentId>` needs to be replaced by the Id of the environment to which you want to associate this VPC. +
You can get the Ids for your environments running a link:/runtime-manager/anypoint-platform-cli#account-environment-list[account environment list] command.
--

The same applies to update all other properties of your VPC. Follow the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8617/versions/85955/pages/107964[Cloudhub API's portal documentation] to know how to update specific resources.
