= About Load Balancers (CloudHub)

This topic provides general information about load balancers in CloudHub. CloudHub provides a backend load-balancing service that automatically provisions infrastructure components. 

CloudHub provides two types of load balancers:

Public Load Balancer: Provides basic load balancing functionality.
Dedicated Load Balancer: Enables you to deploy and configure one or more custom load-balancers within a VPC.

== Public Load Balancers

CloudHub provides a default public load balancer that is available in all environments. This load balancer provides basic funcionality, including TCP load balancing and SSL certification pass through. Public load balancers do not allow you to configure custom SSL certificates or configure proxy rules. 

Additionally, public load balancers have rate limits that help ensure platform stability. MuleSoft regularly monitors and scales these limits as necessary. Rate limits are applied according to region. If you are deploying an application to workers in multiple regions, the rate limit for each region may be different. If an application exceeds the rate limit for a public load balancer, the load balancer returns a 503 Service Unavailable response.

To perform custom load balancer configuration or avoid rate limits, you must create a dedicated load balancer.

== Dedicated Load Balancers

Dedicated load balancers enable you to:

* Handle Load balancing among the different CloudHub workers that run your application.
* Define SSL configurations to provide custom certificates and optionally enforce two-way SSL client authentication.
* Configure proxy rules that map your applications to custom domains. This enables you to host your applications under a single domain.

Dedicated load balancers are an optional component of Anypoint Platform. To use a dedicated load balancer in your environment, you must be running an Anypoint Virtual Private Cloud (VPC). You can associate multiple environments to the same VPC. This enables you to use the same dedicated load balancer in different environments.

You can view the load balancer and VPCS endpoints in your Anypoint Platform organization from the API Portal.

== See Also

* link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal]
* link:/runtime-manager/cloudhub[CloudHub]
* link:/runtime-manager/virtual-private-cloud[Virtual Private Cloud]
* link:/runtime-manager/lb-architecture[About Load Balancer Architecture]
