= About Load Balancers (CloudHub)

This topic provides general information about load balancers in CloudHub. CloudHub provides a backend load-balancing service that automatically provisions infrastructure components. You can use this service to deploy one or more custom load-balancers within a VPC.

Load balancers enable you to:

* Handle Load balancing among the different CloudHub workers that run your application.
* Define SSL configurations to provide custom certificates and optionally enforce two-way SSL client authentication.
* Configure proxy rules that map your applications to custom domains. This enables you to host your applications under a single domain.

Load balancers are an optional component of Anypoint Platform. To user load balancers, you must be running an Anypoint Virtual Private Cloud (VPC). You can associate multiple environments to the same VPC. This enables you to use the same dedicated load balancer in different environments.

You can view the load balancer and VPCS endpoints in your Anypoint Platform organization from the API Portal.

== See Also

* link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal]
* link:/runtime-manager/cloudhub[CloudHub]
* link:/runtime-manager/virtual-private-cloud[Virtual Private Cloud]
* link:/runtime-manager/lb-architecture[About Load Balancer Architecture]
