= Deploy a Mule Applications Application using the CloudHub API

This topic describes how to deploy a Mule application using the link:/runtime-manager/cloudhub-api[CloudHub API]. For information on deploying an applicatinon using Runtime Manager see link:/runtime-manager/deploying-to-cloudhub[Deploy a Mule Application to CloudHub].

The POST method, specified with the `/api/applications/{domain}/deploy` resource (where `{domain}` is the application domain), allows you to deploy an Mule application zip file to CloudHub. This is commonly done after you've created the application in Anypoint Studio or using Maven from the command line- then you need to upload the actual zip file to CloudHub. After you've deployed the zip file, you can monitor the status of your deployment by link:/runtime-manager/logs[viewing the logs].

*Example Request:*

[source,json, linenums]
----
POST https://anypoint.mulesoft.com/cloudhub/api/applications/hello/deploy
 
.. application data ...
----

*Example Response:*

[source,json, linenums]
----
200 OK
----

[TIP]
====
Check out the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[API Portal] of the CloudHub API to see an interactive reference of all the supported resources, methods, required properties and expected responses.

In the link above, search among other Mule APIs for the "CloudHub" API and click on its latest version.
====


== See Also

* link:/runtime-manager[Runtime Manager]
* link:/runtime-manager/cloudhub[CloudHub]
* link:/runtime-manager/managing-deployed-applications[Managing Deployed Applications]
* link:/runtime-manager/managing-applications-on-cloudhub[Managing Applications on CloudHub]
* link:/runtime-manager/monitoring[Monitoring Applications]
