= FAQ: How to Size Your VPC

When you create a VPC, the range of IP addresses for this network needs to be specified in the form of a Classless Inter-Domain Routing (CIDR) block, using CIDR notation.

In order to calculate the proper sizing for your VPC, you first need to understand that the number of dedicated IP addresses is not the same as the number of workers you have deployed. +
For each worker deployed to CloudHub, the following IP assignation takes place:

* For better fault tolerance the VPC subnet may be divided into up to 4 Availability Zones.
* A few IP addresses are reserved for infrastructure.
* At least two IP addresses per worker to perform at zero-downtime.

Due to this structure, the smallest network subnet block you can assign for your VPC is /24 and the largest /16. +
A /24 CIDR notation subnet has 256 IP addresses. +
Reserving one IP address for the network and one for broadcast you have 254 hosts for your worker, which get divided into 4 availability zones of 62 hosts each. Consider that each worker potentially needs two IP addresses for zero-downtime, that's around 30 IP addresses to assign to your workers.

[NOTE]
--
Updating the size of a VPC once it's created and hosting workers, demands all applications to be undeployed before resizing. +
When planning a VPC size, keep in mind to leave a few spare IP addresses in case you need to host more workers.
--

The safe rule of thumb for deciding the size of your VPC subnet is `10 times the maximum number of expected apps to deploy in the VPC`.

== See Also

* link:/runtime-manager/to-request-vpc-connectivity[To Request VPC Connectivity to Your Network]
