= FAQ: How to Configure a VPC for Your Account

In order to properly configure a VPC for your account, you need to keep a few considerations in mind.

Defining a proper size for your VPC at the beginning is crucial since once a VPC is created you need to remove all your workers and redeploy them once the change is complete. In order to avoid unnecessary downtime, it is recommended to design your VPC to scale accordingly.
More information can be found in the <<Size Your VPC, VPC size section below>>.

Creating a VPC is the first step. In order for the VPC to be able to host your Workers, it needs to be bound to a business group and a specific CloudHub region, and once it's created, you need to redeploy your applications. +
More information about this can be found in the <<Deploying To Your VPC, deployment section below>>.

You also need to make sure that the firewall rules are configured according to your needs. Check the <<Firewall Rules,firewall rules section below>> for more information.

Once this is defined, you can proceed to create your VPC using:

. The link:/runtime-manager/vpc-tutorial[VPC UI] available in your Runtime Manager section.
. The link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI] (Look for the specific `vpc create` command).

If you need to connect other private networks to your CloudHub VPC, follow the steps described in the <<VPC Connectivity Methods, connectivity methods section>>.

== See Also
