= About Schedule Management (Hybrid)

[NOTE]
Schedule management is only supported on servers in a hybrid deployment environment using Mule runtime version 3.9 or later. It is not supported on servers within a server group or cluster.

You can use Runtime Manager to view and control polling elements within the flows of your deployed applications. Runtime Manager automatically detects the polling elements within your flows. These elements are listed on the Schedulers tab of the Manage Applications page.

From this tab, you can perform the following:

* Enable or disable polling elements.
* Change the polling frequency.

You can perform these tasks at runtime, without having to make changes to or redeploy the application.

Schdule Management is useful in the following contexts:

* You have a job that runs nightly but you want to trigger it right now so you can debug it. You want to do this in runtime so you don’t need to update the schedule in your underlying application.
* You want to change your schedules in your application at runtime without redeploying.
* You want to disable a scheduled job while one of the applications you are connecting to is undergoing maintenance.
* You want runtime visibility into the schedules in your application.

== See Also

* To Configure Schedule Management for an Application (Hybrid)