= About Load Balancer Architecture

Your CloudHub Dedicated Load Balancer has an internal domain name that is used by applications and clients within the VPC. The naming convention used by the internal domain is:

----
internal-<lb-name>.lb.anypointdns.net
----

`<lb-name>` is the name you gave the load balancer when you created it. Additionally, your dedicated load Balancer exposes an external domain name that resolves to two public IP addresses which are accessible from outside your CloudHub VPC network.

----
 <lb-name>.lb.anypointdns.net 
----

`<lb-name>` is the name you gave the load balancer when you created it.

Each dedicated load balancer has a DNS A Record `<lb-name>.lb.anypointdns.net` that resolves to the two public IP addresses of the two instances. Through your DNS provider, you can add a CNAME record pointing to this record and use your own domain names to access.

If you want your load balancer to handle all connections to your application, but do not want your default domain name for your application publicly exposed, then each application needs to be listening on HTTP on port 8091 or 8092. Alternately, you can create a custom mapping policy to redirect outside requests from your load balancer to your specific application.

Your load balancer listens for outside requests over HTTPS and, by default, communicates internally with your worker over HTTP. If you configured your Mule application within the VPC to listen on HTTPS, you must set upstreamProtocol to HTTPS when creating the mapping list using the load-balancer mappings add command.

== See Also

* link:/runtime-manager/cloudhub[CloudHub]
* link:/runtime-manager/virtual-private-cloud[Virtual Private Cloud]
