= Maintenance and Upgrade Policy
:keywords: cloudhub, support, upgrade, subscription

image:runtime-manager-logo[runtime manager]

All maintenance to the Runtime Manager console, platform services, and worker cloud (see link:/runtime-manager/cloudhub-architecture[CloudHub Architecture]) is performed during the maintenance windows specified in the link:http://www.mulesoft.com/terms/msa/current[subscription agreement], except for critical security issues which are fixed immediately.

MuleSoft's policy is to perform all maintenance transparently and without any downtime to your integration(s) running in the worker cloud wherever possible. In cases where downtime for the console, platform services, or workers is unavoidable, MuleSoft communicates these maintenance windows at least 8 hours in advance and typically 7 days in advance, with the exception of critical security patches which may be fixed immediately.

View the live status and detailed service history for the Runtime Manager console, CloudHub platform services, and the CloudHub worker cloud on link:http://status.mulesoft.com/[status.mulesoft.com].

For our versioning and back support policy, please see link:https://www.mulesoft.com/legal/versioning-back-support-policy[here].
