= To Delete a Mule Application
:keywords: runtime manager, anypoint platform, private cloud

You can delete a Mule application through the Runtime Manager UI. The only way to restore a deleted application is to redeploy it.

Deleted applications lose their log data in the Runtime Manager UI. However,
CloudHub archives this data for a limited period. To recover log data before it is purged, mailto:cloudhub-support@mulesoft.com[contact Support].

[[navigate_to_runtime_manager_settings]]
include::manage-include-navigate-to-settings.adoc[]

. Select Delete from the top-left dropdown menu in the panel.
+
. Confirm your deletion.

////
== See Also
TODO: Think about whether we should link out to steps for this through the CLI tool or some API or whatever other means there are. An alternative might be to add such info here.
[IMPORTANT]
====
After you delete an application, your log data is no longer accessible through the console. CloudHub archives old log data for a limited period of time before being purged. This allows you to recover the data if needed. Open a support case at: link:https://support.mulesoft.com[https://support.mulesoft.com] for more information.
====
////
