:keywords: agent, mule, esb, servers, monitor, notifications, external systems, third party, get status, metrics


= Mule Agent API

For the vast majority of use cases, all you'll need to do with the Mule Agent is install it and configure it according to what you can read in link:/runtime-manager/installing-and-configuring-mule-agent[Installing and Configuring the Mule Agent]

The Mule Agent exposes an API, that you can leverage to both retrieve information and configure settings.

If you wish to use the Mule Agent for more than managing the communication between the link:/runtime-manager/index[Runtime Manager] and Runtimes on-premises, then you may find the documents in this section helpful:

* link:/runtime-manager/administration-service[Administration Service]
* link:/runtime-manager/managing-applications-and-domains[Managing Applications and Domains]
* link:/runtime-manager/jmx-service[JMX Service]
* link:/runtime-manager/mule-agent-notifications[Mule Agent Notifications]


[NOTE]
None of these topics relate to the link:/mule-management-console/v/3.8/index[Mule Management Console]. These topics are about the Mule Agent that communicates the Runtime Manager with local runtimes.
