= About Servers

This topic provides a general description of servers in Runtime Manager.

Runtime Manager provides a single management interface where you can manage applications running in the cloud, on local servers, on server groups that are on-premises within your data center, or on clusters of servers. Applications that are on-premises run on Mule runtime instances on a single server or on a group of servers.

Servers enable Runtime Manager to communicate with runtime manager agent. After creating a server, you can use Runtime Manager to deploy applications to remote runtimes. Servers also enable you to view information about the local environment where a Mule runtime is installed.

You must create a server for each Mule runtime you want to manage. To manage environments with multiple Mule runtimes, you can create server groups and clusters.

== Prerequisites

To manage servers in a customer-hosted environment, you must have one of the following installed:

* Mule runtime, version 3.6 or above
* API Gateway runtime, version 2.0 or above

This document assumes that, if using the API Gateway, you are using version 2.0 or higher. The steps needed to complete server tasks differ between API Gateway 2.0 and previous versions.

You also need to have the latest version of the Runtime Manager Agent to handle the communication between the Runtime and Runtime Manager.

If you are using Anypoint Platform Private Cloud Edition, then you must have the supported version of the agent. You can then install it following the instructions in link:/runtime-manager/installing-and-configuring-runtime-manager-agent[Installing and Configuring the Runtime Manager Agent].

If you need to whitelist IPs or ports for connecting to the Anypoint Platform through a firewall, see link:/runtime-manager/installing-and-configuring-mule-agent#ports-ips-and-hostnames-to-whitelist[Ports and IPs to Whitelist].

== The Servers Dashboard

The servers dashboard provides information about server performance, including heap memory and CPU performance. It also provides the following information:

* A list of applcations deployed to the server
* The status of each application
* Mule messages for each application
* Error messages for each application

== The Manage Servers Page



== See Also

* To Create a Server
* About Server Groups and Clusters
