= To Setup Your Runtime Environment to Create Servers, Server Groups, and Clusters

This topic describes how to use the `amc_setup` script to configure the Runtime Manager Agent to communicate with Runtime Manager. The server communicates with Runtime Manager using the Runtime Manager Agent. To make a server visible in the Runtime Manager console and be able to manage it, you must first register it with the Runtime Manager Agent.

If the server you want to add is already registered with a different instance of Runtime Manager, you cannot add it until you remove if from the other instance. To do this, delete the server from the Server tab in Runtime Manager, then delete the 'mule-agent.yaml' configuration file found on your '{RUNTIME PARENT FOLDER}/conf' folder.

If your environment requires all outbound calls to go through a proxy you will need to modify the proxy settings in the 'wrapper.conf' file in the '{RUNTIME PARENT FOLDER}/conf' folder.


== The amc_setup Command

The `amc_setup` command described in this topic is located in the `$MULE_HOME/bin` directory. If you do not run this command from this directory, you must do one of the following:

* Set the `MULE_HOME` environment variable before running the command
* Use the `--mule-home` parameter as shwon in the following example:
+
[source,java, linenums]
----
/opt/mule-3.7.0/bin/amc_setup --mule-home /opt/mule-3.7.0 -H ...
----

The `amc_setup` script calls the Runtime Manager Agent installation script, which has several useful parameters for configuring security and proxies. For details on the options, see *Installation Options* in .

== The Server Registration Token

The registration token provided by Runtime Manager (included in the command with the `-H` parameter) is specific to a single environment. For example, if you register a server in a QA environment by clicking *Add Server*, you get one token. However if you try to register into your *Production* environment by also clicking *Add Server*,  you get a different token. Tokens are specific to the environment in which you register a server. You can only copy and paste a token to register multiple Mules if you want all servers to be in the same environment.

== Setting Up Your Runtime Environment

Before creating a server, you must run the `amc_setup` script in the local environment where your Mule runtime is running.

. If you have previously configured your runtime environment you must delete the server and its corresponding configuration file.
.. Delete the server from Runtime Manager.
.. Remove the `mule-agent.yml` file from the `$MULE_HOME/conf` directory.

. From Anypoint Platform, select Runtime Manager, then click the Servers tab.
. 