= About Server Properties

Runtime Manager enables you to view and configure properties 

Custom Properties

Enable you to define properties 

Discovered Properties

JVM Arguments
Environment Properties
System Properties

After creating a server in a hybrid deployment scenario, Runtime manager enables you to define and configure server-side properties. These properties are defined as name/value pairs and are used by the JVM where the server is running.

== Setting Server-side Properties

To set a server-side property:

. From the Servers page, select a server, then click Manage Server.
. Click the Properties tab.
. Provide a key and value, then click Apply Changes.

== Viewing Server-side Properties

After adding a server, you can view informmation about the server from Runtim Manager:

. Click Servers, then select the server whose properties you want to view.
. Click Manage Servers.

Runtime manager displays the following information:

* Status
* Type
* Gateway version
* Agent version
* Server IPs
* Server OS
* VM Vendor
* License Expiration Date

== See Also

* To Create a Custom Server-side Property
* To View Server-side Properties