= About Requirements for Using Servers

== Prerequisites

To manage servers in a customer-hosted environment, you must have one of the following installed:

* Mule runtime, version 3.6 or above
* API Gateway runtime, version 2.0 or above

This document assumes that, if using the API Gateway, you are using version 2.0 or higher. The steps needed to complete server tasks differ between API Gateway 2.0 and previous versions.

You also need to have the latest version of the Runtime Manager Agent to handle the communication between the Runtime and Runtime Manager.

If you are using Anypoint Platform Private Cloud Edition, then you must have the supported version of the agent. You can then install it following the instructions in link:/runtime-manager/installing-and-configuring-runtime-manager-agent[Installing and Configuring the Runtime Manager Agent].

If you need to whitelist IPs or ports for connecting to the Anypoint Platform through a firewall, see link:/runtime-manager/installing-and-configuring-mule-agent#ports-ips-and-hostnames-to-whitelist[Ports and IPs to Whitelist].