= About Virtual Private Cloud

The Virtual Private Cloud (VPC) offering allows you to virtually create a private and isolated network in the cloud to host your CloudHub workers. +
As opposed to the default configuration, where all CloudHub workers reside in a multi-tenant global public worker cloud, balanced by a publicly accessible load balancer, the Virtual Private Cloud grants you a logically private and isolated network dedicated to host your CloudHub worker instances.

This allows you to:

* Host your applications in a VPC and take advantage of its dedicated load balancer features. +
Each VPC can host one or more dedicated load balancers with a DNS A record that you can add to your own DNS CNAME record to point to. This way you can configure your VPC's load balancer to handle requests to your own domain. +
This allows you, for example, to set your private DNS server so the workers hosted in your VPC communicate with your internal network using your private hostnames.
* Configure your own firewall rules to apply to your workers. +
You can choose to expose or block your custom ports using your own firewall rules, and even block requests to your apps coming from CloudHub's publicly accessible load balancer so you balance your requests using your own dedicated load balancer.
* Connect your VPC to your corporate intranet – whether on-premises or in other clouds – via a VPN connection as if they were all part of a single, private network. +
You can connect your VPC to any other network via a secure VPN connection. This allows CloudHub workers to access resources behind your corporate firewall. You can leverage an *IPSec* gateway or *Amazon Web Services (AWS) _Direct Connect_* for VPN connectivity.

== See Also

* link:/runtime-manager/vpc-tutorial[Tutorial: Creating a VPC (Runtime Manager)]
* link:/runtime-manager/cloudhub-architecture[CloudHub Architecture]
* link:/runtime-manager/faq-virtual-private-cloud[FAQ: Virtual Private Cloud]
//_TODO: Add this as a See Also link:
// link:/runtime-manager/cloudhub-architecture#cloudhub-workers[CloudHub workers]
// link:/runtime-manager/cloudhub-dedicated-load-balancer[dedicated load balancer features]
// <<Set up Internal DNS, DNS server>>
// CH Architechture
