= FAQ: How To Deploy To My VPC

All VPCs need to be created inside a master organization or business group, and associated to a CloudHub region, and an environment. Every application deployed to that organization/business group, region, and environment is then automatically deployed to your VPC.

Because you can have more than one VPC per region, you can choose to set your VPC as default for a specific region. This associates the VPC to all environments in that region that are not explicitly associated with other VPC. +
For example, if you have three environments in US-EAST:

. Production
. QA
. Staging

And setting one VPC (vpc-1) for _Production_ in *US-EAST* and vpc-2 as default for *US-EAST* causes for all applications deployed to _Staging_ and _QA_ to automatically deploy to vpc-2.

Applications that were deployed before creating your VPC are not automatically migrated. It is necessary to redeploy the applications so they can be hosted in the VPC.

== See Also

* link:/runtime-manager/vpc-provisioning-concept[About Provisioning a VPC]
* link:/runtime-manager/vpc-architecture-concept[About VPC Network Architecture]
