= Troubleshooting Anypoint VPN

This topic describes possible errors you may encounter when attempting to connect Anypoint VPN.

== Unable to Connect to the VPN

If you are unable to connect to the VPN, you should ensure any firewalls that are configured are allowing traffic through the IP addresses in the localExternalIpAddress field in the VPN tunnels.

== NO_PROPOSAL_CHOSEN Error or Cannot Establish Phase 4 Connection

This is likely due to a problem with your Phase 1 configuration.

Our vpn connections only support IKEv1, and any IKEv2 connections will not work.

Additionally, the following Phase 1 Diffie-Hellman (DH) groups are supported:

2 14-18 22 23 24

== Cannot Establish a Phase 2 Connection

It is possible that your phase 2 DH group is not supported. The supported Phase 2 groups are:

2 5 14-18 22 23 24

== VPN Tunnel Connection Works, but Routes Are Not Propagated

Be sure that the neighbor IP address for the tunnel is taken from the Local PTP IP Address. Using the above API response as an example, the property that should be used is localPtpIpAddress

== Phase 2 SA Established, but Traffic Not Passing Through Tunnel

The VPN Connection only supports one Security Association (SA) pair per tunnel, so any more than one traffic selector per connection will result in unexpected traffic problems.

To solve this, ensure that only one unique SA is used per VPN tunnel connection. If more than one policy is needed, you must consolidate and filter traffic in your network.