= Create a CloudHub VPN 

This topic describes how to create, view, and delete a CloudHub VPN using Anypoint Runtime Manager. 

For information on creating a using the CloudHub API see link:https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/[CloudHub API].

== Prerequisites

Before creating a VPN, you must create and least one Virtual Private Cloud (VPC). See link:/runtime-manager/virtual-private-cloud[About Virtiual Private Cloud] for more information. You should also ensure that the components of your external network are configured correctly.

Additionally, you will need to following to configure a VPN:

* Remote IP address: the IP address of the device you are connecting to. [See link to supported devices]
* Pre-shared Key (PSK): the shared secret used by the network tunnel that connects between Anypoint Platform and your network.
* Point-to-Point CIDR: the IP range used by the network tunnel. You must configure a unique IP address range for each tunnel.
* Remote and Local Autonomous System Number (ASN): specifies the collection of routing prefixes. You must configure both a remote and local ASN before creating a VPN. When creating a VPN, you must provide the IP address of both.
* Classless Inter-Domain Routing (CIDR): specifies the routing address of your network. This is required only if you are using static routing.

== Procedure

. From the Mangagment Center, select Runtime Manager.
. Go to the environment where you want to create a VPN.
. Click the *VPN* tab, then click *Create VPN*.
. Enter a name for your VPN.
. Select a Virtual Private Cloud from the drop down list.
. Enter the remote IP address used to connect to your VPN.
. Select the routing type you want to use for your VPN.
+
We recommend that you use Border Gateway Protocol (BGP) routing when possible. See link:/runtime-manager/vpn-routing[About CloudHub VPN Routing] for more information.
+
If you are using BGP routing:
+
.. Enter the port of your local ASN. The default value is 65000.
. Select the type of tunnel configuration for your VPN:
+
** *Automatic*: automatically configures the required tunnels for your VPN using the default values.
** *Custom*: enables you to manually configure the tunnels used by your VPN.
+
See link:/runtime-manager/vpn-tunnels[About CloudHub VPN Tunnels] for more information.
+
If you are using static routing:
+ 
.. Click *Add New Rule*.
.. Enter a Classless Inter-Domain Routing (CIDR) address. For example:
+
----
10.0.0.0/8
----

. Configure the tunnel used to connect between Anypoint Platform and your network.
+
You must configure two tunnels that connect between different endpoints. You can use the same PSK value for both connections, but you must use different IP ranges.
+
.. Enter a vallue for the  PSK. 
.. Enter the address range for the *Point-To-Point CIDR*. For example:
+
----
169.254.1.1/30
----

. Click *Create VPN*

== Result

After creating the VPN, it appears in the list of VPNs. Initially, the *Status* column displays a valude of PENDING and both VPN tunnels display DOWN. If your VPN connection is successful, the values should be AVAILABLE and UP.

== See Also

