= About the CloudHub VPN

The CloudHub VPN enables you to create a secure connection to systems within your network that are hosted outside Anypoint Platform. If required, you can create multiple VPNs to connect to different networks or different regions within a network.

The number of VPNs you can create depends on the VPN capacity allocated to your account.

[Diagram showing connection options]

The to create and maintain a secure connection with your external network, the CloudHub VPN supports the following:

* *Network address translator (NAT) Traversal*: enables Anypoint Platform to connect to private IP addresses within your network.
* *2-byte and 4-byte Autonomous System Numbers (ASN)*: defines the routing policies used to connect to your network through the VPN.
* *Reusable IP addresses*: 
* *Tunnel configuration*: 

Additionally, the CloudHub VPN supports the following methods for encrypting data communications bewtween Anypoint Platform and your network:

* AES 256-bit encryption
* SHA-2 hasing
* Diffie-Hellman groups

== See Also

* To Create a CloudHub VPN from Runtime Manager
* CloudHub VPN Routing
* CloudHub VPN Tunnels
* VPC
