= To Create a CloudHub VPN from Runtime Manager

This topic describes how to create a CloudHub VPN using Anypoint Runtime Manager. For information on creating a ClouHub VPN using the CloudHub API see link:https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/[CloudHub API].

Before creating a VPN, you must create and least one Virtual Private Cloud (VPC). See [link] for more information. You should also ensure that the components of your external network you are connecting with the VPC is configured correctly.

. From the Mangagment Center, select Runtime Manager.
. Go to the environment where you want to create a VPN.
. Click the VPN tab, then click Create VPC.
. Enter a name for your VPN.
. Select a Virtual Private Cloud from the drop down list.
. Enter the remote IP address used to connect to your VPN.
. Select the routing type you want to use for your VPN.
+
MuleSoft recommends that you use Border Gateway Protocol (BGP) routing when possible. See link:/runtime-manager/vpn-routing[About CloudHub VPN Routing] for more information.
+
If you are using static routing:
+ 
.. Click Add CIDR Value.
.. [Need to see UI]

If you are using BGP routing:
+
.. [Need to see UI]

. Enter the port of your local ASN. The default value is 65000.
. Select the type of tunnel configuration for your VPN:
+
** *Automatic*: automatically configures the required tunnels for your VPN using the default values.
** *Custom*: enables you to manually configure the tunnels used by your VPN.
+
See link:/runtime-manager/vpn-tunnels[About CloudHub VPN Tunnels] for more information.

== See Also

