= About Anypoint VPN

Anypoint VPN enables you to create a secure connection to systems within your network that are hosted outside Anypoint Platform. If required, you can create multiple VPNs to connect to different networks or different regions within a network.

The number of VPNs you can create depends on the VPN capacity allocated to your account.

The to create and maintain a secure connection with your external network, the Anypoint VPN provides the following features:

* Route-based access via 2-byte and 4-byte Autonomous System Numbers (ASN). This defines the routing policies used to connect to your network through the VPN.
* Reusable IP addresses
* Tunnel configuration 


*Note*: Network Address Translation (NAT) is not supported.


== Supported Data Encryption Methods

Anypoint VPN supports the following methods for encrypting data communications bewtween Anypoint Platform and your network:

* AES 256-bit encryption
* SHA-2 hasing
* Diffie-Hellman groups

== Anypoint VPN Routing

The Anypoint VPN supports two types of routing:

* *Border Gateway Protocol (BGP) routing*: enables you to use dynamic routing. This allows the device you are connecting to broadcast routes to the VPN. We recommend using BGP routing if your device supports this protocol.
* *Static routing*: requires you to specify the routes that the Anypoint VPN uses to communicate with your network.


== See Also

* link:/runtime-manager/vpn-create[Create an Anypoint VPN]
* link:/runtime-manager/vpn-supported-devices[Supported Network Devices]
* link:/runtime-manager/virtual-private-cloud[About Virtiual Private Cloud]
