= To Configure Mule Runtime (EU Control Plane)

- The biggest change is around the Gateway configuration to point to EU URLs. 
- By default it is pointing to US. Should be on the gateway configuration, a change of 4 URLs, that would be for standalone and Studio. 
- And the configuration is different for Mule 4.


= To Configure Mule Runtime as an API Gateway (EU Control Plane)

To configure Mule Runtime as an API gateway within the EU Control Plane, you must configure properties that enable the API gateway to point to the EU Control Plane. By default, the Mule runtime is configured to point to the US Control Plane.

The properties you must define depend on which version of Mule runtime you are using.

== To Configure Mule Runtime 4.0

=== wrapper.conf

To configure the API gateway using the `wrapper.conf` file, modify the following properties.

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<env client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<env client secret>
wrapper.java.additional.<n>=-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

In the above example, replace `<n>` with a unique integer.

=== Command Line

To configure the the API gateway from the command line, use the following:

----
./mule -M-Danypoint.platform.client_id=<env client ID> -M-Danypoint.platform.client_secret=<env client secret> -M-Danypoint.platform.base_uri=https://eu1.anypoint.mulesoft.com 
-M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

== To Configure Mule Runtime 3.x

=== wrapper.conf

To configure the API gateway using the `wrapper.conf` file, modify the following properties.

----
wrapper.java.additional.<n>=-Danypoint.platform.client_id=<org client ID>
wrapper.java.additional.<n>=-Danypoint.platform.client_secret=<org client secret>
wrapper.java.additional.<n>=-Danypoint.platform.platform_base_uri=https://eu1.anypoint.mulesoft.com/apiplatform
wrapper.java.additional.<n>=-Danypoint.platform.coreservice_base_uri=https://eu1.anypoint.mulesoft.com/accounts
wrapper.java.additional.<n>=-Danypoint.platform.contracts_base_uri=https://eu1.anypoint.mulesoft.com/apigateway/ccs
wrapper.java.additional.<n>=-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----

In the above example, replace `<n>` with a unique integer.

=== Command Line

To configure the the API gateway from the command line, use the following:

----
./mule -M-Danypoint.platform.client_id=<org client ID> -M-Danypoint.platform.client_secret=<org client secret> -M-Danypoint.platform.platform_base_uri=https://eu1.anypoint.mulesoft.com/apiplatform -M-Danypoint.platform.coreservice_base_uri=https://eu1.anypoint.mulesoft.com/accounts -M-Danypoint.platform.contracts_base_uri=https://eu1.anypoint.mulesoft.com/apigateway/ccs -M-Danypoint.platform.analytics_base_uri=https://analytics-ingest.eu1.anypoint.mulesoft.com
----