= To Create a Server (EU Control Plane)

[NOTE]
From the EU Control Plane, you can only create servers using Mule Runtime Agent version 1.9.2 and later.

To manage a remote server from the EU Control Plane you must run the `amc_setup` script to create a server by configuring the Runtime Manager Agent to communicate with Runtime Manager. 

The procedures for creating a server are the similar to those for creating a server in the US Control Plane. The difference is that you must use the `--region eu1` option when running `amc_setup` as shown in the following example:

----
./amc_setup --region eu1 -H 1234321xyzabc----16 your-eu-server-name
----

This flag ensures that the server connects to Runtime Manager in the EU Control Plane. When you click Add Server in the  Runtime Manager > Servers tab, Runtime Manager in the EU Control Plane automatically inserts this flag in the generated script.

== See Also

* link:/runtime-manager/servers-create[To Create a Server in Runtime Manager (Hybrid)]

