= To Access the EU Control Plane (Anypoint Studio)

You can configure your Anypoint Studio installation to point to your EU control plane. +
This task is available since Aynpoint Studio 6.4 Update Site 2.

. Go to Anypoint Studio in your top navigation bar, and click Preferences.
. Expand Anypoint Studio in the left navigation bar, and select Region.
. Select the EU option from the region dropdown menu. +
Additionally you can select the Other option from dropdown menu if your region is not listed. +
When selecting Other, you need to provide the prefix for the region and the master org key for that region.
. Click OK.

All your Anypoint Platform tools embedded in Anypoint Studio display your Anypoint Platform from the EU Control plane. +
Tasks such as deploying to CloudHub, importing an asset from Exchange, or importing an API definition from Design Center, are now taking place within the EU Control plane.

This configuration persists within your Anypoint Studio installation. +
If you need to distribute this configuration, you can follow this task, zip your Anypoint Studio application, and distribute the resulting zip file.

== See Also

* link:/eu-control-plane/[EU Control Plane]
* link:/eu-control-plane/platform-access-eu[To Access the EU Control Plane]
