=MUnit Coverage Reports

== Objective

The MUnit Coverage feature provides a metric on how much of a Mule application has been executed by a set of MUnit tests.
This lets the users obtain a quality metric for the application.
For more information, see this link:https://en.wikipedia.org/wiki/Code_coverage[Wikipedia article on Code Coverage].

It's worth noticing, MUnit Coverage is based on the amount of message processors executed.
MUnit Coverage provides metrics for:

* *Application overall coverage*: An average of the items below.
* *Resource coverage*: Refers to each Mule configuration file under `src/main/app`. Each of is considered a resource by MUnit Coverage.
* *Flow coverage*: Refers to any of the following `Flows`, `Sub-flows`, and `Batch jobs`.

== Calculating Coverage
// TODO
// Import how coverage is calulated from PDF

== Coverage in Maven
You can run coverage reports for your Mule application using the MUnit Maven Pluging by following the instructions in link:/munit/v/1.2.1/munit-maven-support#coverage[Munit Maven Plugin section].

== Coverage in Anypoint Studio
 You can run coverage reports for your MUnit tests from Studio by following the steps detailed in the link:/munit/v/1.2.1/using-munit-in-anypoint-studio#viewing-coverage-reports[MUnit in Studio section].
