= To Prevent the SOAP Fault

In this procedure, you resolve the SOAP fault you generated. You add the Transform Message component to the flow and specify a message in DataWeave for responding to the request, effectively implementing the operation. In the DataWeave code, you use the proper namespace to avoid a soap:Server faultcode at the beginning of the response to the request.

The Transform Message component works on the process side after the endpoint defined in the WSDL has been hit, triggering the main flow of the Mule application to execute, which then calls the backend flow.

. In the OrderTshirt:\soapkit-config flow, click to open the Transform Message component.
+
The Transform Message properties window displays the generated DataWeave code.
+
. Modify the DataWeave code as follows:
+
[source,xml,linenums]
----
%dw 2.0
output application/java
ns ns0 http://mulesoft.org/tshirt-service
---
{
    body: {
        ns0#OrderTshirtResponse: {
            orderId: "I got a request from " ++ (payload.body.ns0#OrderTshirt.name default "")
        }
    } write "application/xml"
}
----
. Save and rerun the project.
+
. In the SoapUI client, repeat the request.
+
The output changes to a valid response:

[source,xml,linenums]
----
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <soap:Body>
      <ns0:OrderTshirtResponse xmlns:ns0="http://mulesoft.org/tshirt-service">
         <orderId>I got a request from John</orderId>
      </ns0:OrderTshirtResponse>
   </soap:Body>
</soap:Envelope>
----

