= Backup and Disaster Recovery
:keywords:on-prem, anypoint platform on-prem, anypoint platform, on prem, on premise, on premises, backup, disaster recovery

== Performing Backups

Scheduling hourly backups to external storage every hour is recommended to preserve your data. Make sure you copy the archive to an external reliable storage outside of the Anypoint cluster, using appropriate storage system used in your organization.

You can launch the creation of a backup by running the command below from any one of the servers registered in the cluster:

----
sudo gravity planet enter -- --notty /usr/bin/gravity -- system backup gravitational.io/anypoint:0.0.0+latest /ext/share/backup.tar.gz
----

This will create an archive of the system state, stored in `/var/lib/gravity/planet/share/backup.tar.gz`.

== Restoring the System

To restore a system from your backup, use the existing cluster or create a new fresh cluster with the same amount of servers as the restored version. In either case, you must do the following:

. Enter one of the nodes in your cluster, having root access.
. Place the ‘tar.gz` archive file in the location `/var/lib/gravity/planet/share`. You can transfer this file securely via the following command:

+
----
scp /backup-path/to-restore.tar.gz your_username@remotehost.edu:/var/lib/gravity/planet/share
----

. Run the command below:
+
----
sudo gravity planet enter -- --notty /usr/bin/gravity -- system restore gravitational.io/anypoint:0.0.0+latest /ext/share/to-restore.tar.gz
----
+
This command will restore your entire cluster from one of your backups.

. Restart all of the pods in your cluster to pull up the new secrets


== Applying Updates

Application updates will be provided to you as a `.tar.gz` archive file. To apply them, do the following:

. Copy the file to the server with scp (i.e. scp anypoint-update.tar.gz username@server:/home/username)
. SSH to the server
. Copy the update file to `/var/lib/gravity/planet/share`
. Run the following command:
+
----
sudo gravity planet enter -- --notty /usr/bin/gravity -- app import --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure /ext/share/anypoint-update.tar.gz
----

. Then run:
+
----
sudo gravity planet enter -- --notty /usr/bin/gravity -- app export --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure gravitational.io/anypoint:<version>
----

. Finally, in the Site management UI in your browser. Click the ‘Update’ button on the new version now available on the ‘Updates’ screen.
