= Backup and Disaster Recovery
:keywords:on-prem, anypoint platform on-prem, anypoint platform, on prem, on premise, on premises, backup, disaster recovery

Scheduling hourly backups to external storage every hour is recommended to preserve your data. Make sure you copy the archive to an external reliable storage outside of the Anypoint cluster, using appropriate storage system used in your organisation.

You can launch the creation of a backup by running the command below from any one of the servers registered in the cluster:

----
sudo gravity planet enter -- --notty /usr/bin/gravity -- system backup gravitational.io/anypoint:0.0.0+latest /ext/share/backup.tar.gz
----

This will create an archive of the system state, stored in `/var/lib/planet/share/backup.tar.gz`.

To restore a system from your backup, use the existing cluster or create a new fresh cluster with the same amount of servers as the restored version. In either case, you must do the following:

. Enter one of the nodes in your cluster, having root access.
. Place the ‘tar.gz` archive file in the location `/var/lib/planet/share`. You can transfer this file securely via the following command:

+
----
scp your_username@remotehost.edu:to-restore.tar.gz /var/lib/planet/share
----

. Run the command below:
+
----
sudo gravity planet enter -- --notty /usr/bin/gravity -- system restore gravitational.io/anypoint:0.0.0+latest /ext/share/to-restore.tar.gz
----
+
This command will restore your entire cluster from one of your backups.
