= Configuring Anypoint Platform for PCF
:keywords:anypoint platform, on premises


== Overview

For the Anypoint Platform for PCF solution to work, you must install the following things:

* The <<Anypoint Platform Service Brokers for PCF Tile>>
* The <<Mule Runtime BuildPack>>
* The <<Space Configuration Tool>>. This installs a bundle of elements that includes:
** The Cloud Manager, which mediates the communication between Anypoint Platform and PCF
** The *Runtime Manager Service* - Meant for Mule runtime applications
** The *API Gateway Service* - Meant for proxying non-Mule applications that are deployed on PCF


[NOTE]
Each instance of the Space Configuration Tool is linked to one PCF space. Therefore, if you wish to manage multiple PCF spaces you must also perform multiple installations of the Space Configuration Tool to match these. If you have multiple Anypoint Platform link:/access-management/environments[environments], it's recommended that you have one PCF space for each.


== Anypoint Platform Service Brokers for PCF Tile

See instructions for installing this component on Pivotal's documentation:
link:[Anypoint Platform Service Brokers for PCF] Tile

== Mule Runtime BuildPack

Download and install the Mule runtime BuildPack. This BuildPack contains an image that includes Mule Runtime 3.8.1.

If the default settings on the Mule Runtime BuildPack don’t match what you require, you can link:link:/anypoint-platform-on-premises/v/1.5.0/customize-mule-runtime-buildpack[Customize Mule Runtime BuildPack]

You can have multiple BuildPacks installed, when link:https://docs.mulesoft.com/runtime-manager/deploying-to-pcf[Deploying] on the Anypoint Platform you can select which to use.


== Space Configuration Tool



== Set up a Hazelcast Server

[NOTE]
This step is only necessary if you intend to deploy your Mule applications into clusters in PCF.

If you don’t have a hazelcast cluster configured, you must configure one. You must use the mule hazelcast server provided by MuleSoft. See link:/anypoint-platform-on-premises/v/1.5.0/mule-hazelcast-server[Mule Hazelcast server].

Once the cluster is installed, take note of the cluster node IPs and ports and the cluster group name and password. You will need this information to bind Mule runtime instances to the cluster.

=== Hazelcast as PCF user-provided service

In order to allow your Mule applications to pick up the cluster configuration, you must create a user-provided service in PCF for each of the nodes in the Hazelcast cluster that you will be connecting your Mule applications to.

[source]
----
cf cups HAZELCAST_NODE_NAME -p ‘{“host”:”HAZELCAST_NODE_IP”,"port":"HAZELCAST_NODE_PORT","clusterId":"HAZELCAST_CLUSTER_GROUP_NAME","clusterPassword":"HAZELCAST_CLUSTER_GROUP_PASSWORD"}'
----

In the above command, replace the following placeholders:
* `HAZELCAST_NODE_NAME`: Logical name of the Hazelcast node from the cluster that you are defining. It must start with hazelcast.
* `HAZELCAST_NODE_IP`: IP to connect to the Hazelcast node
* `HAZELCAST_NODE_PORT`: Port to connect to the Hazelcast node
* `HAZELCAST_CLUSTER_GROUP_NAME`: Group name set in the Hazelcast cluster configuration
* `HAZELCAST_CLUSTER_GROUP_PASSWORD`: Group password set in the Hazelcast cluster configuration

For example:

[source]
----
cf cups hazelcast_dev_node1 -p '{"host":"172.16.12.61","port":"5701","clusterId":"dev","clusterPassword":"dev-pass"}'
----
