= Configuring Anypoint Platform for PCF
:keywords:anypoint platform, on premises


== Overview

For the Anypoint Platform for PCF solution to work, you must install and configure the following things:

* The <<Anypoint Platform Service Brokers for PCF Tile>>
* The <<Mule Runtime BuildPack>>
* <<Set the PCF Flag Manually>>
* The <<Space Configuration Tool>>. This installs a bundle of elements that includes:
** The Cloud Manager, which mediates the communication between Anypoint Platform and PCF
** The *Runtime Manager Service* - Meant for Mule runtime applications
** The *API Gateway Service* - Meant for proxying non-Mule applications that are deployed on PCF


[NOTE]
Each instance of the Space Configuration Tool is linked to one PCF space. Therefore, if you wish to manage multiple PCF spaces you must also perform multiple installations of the Space Configuration Tool to match these. If you have multiple Anypoint Platform link:/access-management/environments[environments], it's recommended that you have one PCF space for each.


== Anypoint Platform Service Brokers for PCF Tile

See instructions for installing this component on Pivotal's documentation:
link:http://docs.pivotal.io/mulesoft/[Anypoint Platform Service Brokers for PCF] Tile

== Mule Runtime BuildPack

Download and install the Mule runtime BuildPack. This BuildPack contains an image that includes Mule Runtime 3.8.1. Naming convention for build pack should be 
---- 
mule_runtime_buildpack_{mule-version} 
---- 
----
Example: mule_runtime_buildpack_3_8_1
---- 

If the default settings on the Mule Runtime BuildPack don’t match what you require, you can link:link:/anypoint-platform-on-premises/v/1.5.0/customize-mule-runtime-buildpack[Customize Mule Runtime BuildPack]

You can have multiple BuildPacks installed, when link:https://docs.mulesoft.com/runtime-manager/deploying-to-pcf[Deploying] on the Anypoint Platform you can select which to use.


== Set the PCF Flag Manually

In order to make PCF visible as an option on the Runtime Manager UI, you must manually enable a flag in the platform. Future releases will avoid needing this additional step.

See link:link:/anypoint-platform-on-premises/v/1.5.0/set-pcf-flag-manually[Set PCF Flag Manually] for a detailed step by step walkthrough of how to set this.

== Space Configuration Tool


The Space Configuration Tool creates the following components:
* two services, the `runtime-manager-service` and the `api-Gateway-Service`
* A cloud installer app named: `cloudmanager-<uuid>` (where the “uuid” is a unique value for a combination of space and Anypoint Platform organization)

[NOTE]
Each instance of the Space Configuration Tool is linked to one PCF space. Therefore, if you wish to manage multiple PCF spaces you must also perform multiple installations of the Space Configuration Tool to match these.

To install the Space Configuration Tool, follow the steps below:

. Download the Space Configuration Tool here [zip file]
. Open the `cloud_settings.yml` file and edit the properties in it to match your account, following the reference in <<Cloud Settings File, the section below>>.
. Run the script in your Cloud Foundry environment through the following command:
+
----
python cloud_installer.py -i cloud_settings.yml
----
+
[NOTE]
CF CLI should be available before you run this command

=== Cloud Settings File

In the `cloud_settings.yml` file, you must complete the following fields:

.PCF services

You must provide a reference to each of the services that you want to use: the `runtime-manager-Service` and the `api-Gateway-Service`. The service name and the plan that you assign to these must match the names you manually provided in the link:http://docs.pivotal.io/mulesoft/[Anypoint Platform Service Brokers for PCF Tile], on the corresponding tab for each service broker.

[TIP]
====
You can access this info through the following CF command, which lists all of the available service plans:

----
cf marketplace
----
====

The example below shows how you can register both services in this file. Note that the names of your services and plans may differ from those in the example based on the tile installation

[source, yaml, linenums]
----
pcf-services:
  - servicename: 'runtime-manager-service' # Update if changed in tile installation
    serviceplan: 'runtime-manager-plan-v1' # Update if changed in tile installation
    serviceinstancename: 'runtime-manager-service' # Update if changed in tile installation
  - servicename: 'API-gateway-service-v1'  # Update if changed in tile installation
    serviceplan: 'API-gateway-plan-v1'   # Update if changed in tile installation
    serviceinstancename: 'api-gateway-service' # Update if changed in tile installation
----


[TIP]
====
Remember that the Runtime Manager Service is required when deploying Mule runtime applications to PCF (see link:/runtime-manager/deploying-to-pcf[Deploying to PCF] for details on how to use it).
The API Gateway Service is required when deploying a simple proxy packaged as a Mule application to a newly created Mule server. The service also registers a new API on API Manager in the Anypoint Platform (see link:/runtime-manager/deploying-to-pcf[Deploying to PCF] for details on how to use it)
====

.pcf-cloud-commands

This set of parameters sets up the Space Configuration Tool, which is the component that actually deploys/manages apps through Runtime Manager and notifies their status to Runtime Manager.

[source, yaml, linenums]
----
pcf-cloud-params:
  anypoint-org: orgId for the Anypoint Platform organization you want to set up with the Space Configuration Tool
  anypoint-env: ID for the Anypoint Platform environment that matches the PCF space you want set up with this Space Configuration Tool instance
  anypoint-url: URI through which the Anypoint Platform is available on your local network
  manifest:
    applications:
      memory: memory that’s assigned to the cloud installer
      Instances: 1
      path: 'anypoint-mcm-web-1.0.4.jar' #cloud-manager jar file
      env:
         COM_MULESOFT_CLOUD_MANAGER_PCF_APIURL: PCF API URL (PCF Apps manager)
         COM_MULESOFT_CLOUD_MANAGER_PCF_DOMAIN: PCF domain
         COM_MULESOFT_CLOUD_MANAGER_PCF_USERNAME: PCF username and password. The user must have a minimum role of `SpaceDeveloper`.
         COM_MULESOFT_CLOUD_MANAGER_PCF_PASSWORD:
         COM_MULESOFT_CLOUD_MANAGER_PCF_SPACE:
         COM_MULESOFT_CLOUD_MANAGER_PCF_ORG:
         COM_MULESOFT_CLOUD_MANAGER_PCF_SKIPSSLVALIDATION: true # set this to false only if PCF deployment doesn't have valid HTTPS certifications.
         COM_MULESOFT_ARMSERVICES_CLIENT_CLIENTID:  `masterorg clientId` to access Anypoint platform.
         COM_MULESOFT_ARMSERVICES_CLIENT_CLIENTSECRET: `masterorg clientSecret` to access Anypoint platform.
         COM_MULESOFT_ARMSERVICES_CLIENT_BASEURL:
         COM_MULESOFT_ARMSERVICES_CLIENT_INSECURE: true # set this to false only of ARM platform doesn't have valid HTTPS certifications.
         AUTHENTICATION_URL:
         AUTHENTICATION_INSECURE: true # set this to infalse only if Anypoint platform doesn't have valid HTTPS certifications.
         
----

[TIP]
You can obtain your `clientId` and `clientSecret` on the Anypoint Platform UI by going to *Access Management > Organization* and opening the settings for your main organization. See link:https://docs.mulesoft.com/access-management/organization[organizations].


=== Verifying the Space Configuration Tool installation

After running the Space Configuration Tool, you should verify that the different components were created.
You can see the list of available services through the following Cloud Foundry command:

----
cf services
----

[TIP]
If the script worked well, you should see two services, “runtime-manager-service” and the “api-gateway-service”


You can see the list of installed apps through PCF APPS manager UI or with the following Cloud Foundry command:

----
cf apps
----

[TIP]
====
If the script works well, you should see an app named following this structure: 

----
cloud-manager-<uuid>
----

The “uuid” is a unique value for a combination of space and Anypoint Platform organization. You must never delete `cloud-manager` as it is used by the Anypoint Platform to deploy apps to PCF spaces.
====


== Set up a Hazelcast Server

[NOTE]
This step is only necessary if you intend to deploy your Mule applications into clusters in PCF.

If you don’t have a hazelcast cluster configured, you must configure one. You must use the mule hazelcast server provided by MuleSoft. See link:/anypoint-platform-on-premises/v/1.5.0/mule-hazelcast-server[Mule Hazelcast server].

Once the cluster is installed, take note of the cluster node IPs and ports and the cluster group name and password. You will need this information to bind Mule runtime instances to the cluster.

=== Hazelcast as PCF user-provided service

In order to allow your Mule applications to pick up the cluster configuration, you must create a user-provided service in PCF for each of the nodes in the Hazelcast cluster that you will be connecting your Mule applications to.

[source]
----
cf cups HAZELCAST_NODE_NAME -p ‘{“host”:”HAZELCAST_NODE_IP”,"port":"HAZELCAST_NODE_PORT","clusterId":"HAZELCAST_CLUSTER_GROUP_NAME","clusterPassword":"HAZELCAST_CLUSTER_GROUP_PASSWORD"}'
----

In the above command, replace the following placeholders:
* `HAZELCAST_NODE_NAME`: Logical name of the Hazelcast node from the cluster that you are defining. It must start with hazelcast.
* `HAZELCAST_NODE_IP`: IP to connect to the Hazelcast node
* `HAZELCAST_NODE_PORT`: Port to connect to the Hazelcast node
* `HAZELCAST_CLUSTER_GROUP_NAME`: Group name set in the Hazelcast cluster configuration
* `HAZELCAST_CLUSTER_GROUP_PASSWORD`: Group password set in the Hazelcast cluster configuration

For example:

[source]
----
cf cups hazelcast_dev_node1 -p '{"host":"172.16.12.61","port":"5701","clusterId":"dev","clusterPassword":"dev-pass"}'
----
