= Anypoint Platform On-Premises Edition

This section shows you how to install and use the *Anypoint Platform On-Premises Edition*. The Anypoint Platform On-Premises Edition offers all of the features that are available in the online version of the link:https://anypoint.mulesoft.com[Anypoint Platform] as a service that you can run on your local servers, guarded by any security policies you may require.

When you choose to run Anypoint Platform on-premises, MuleSoft systems do not interact with your data at all. You configure and run the software and handle all storing, processing and transmitting of data directly, without interference from MuleSoft.

The Anypoint Platform On-Premises Edition includes the following functionalities:

* link:/runtime-manager/index[Runtime Manager], which lets you keep track of your deployed Mule applications
* link:/api-manager/index[API Manager], which lets you keep track of your registered APIs
* link:/getting-started/anypoint-exchange[Anypoint Exchange], where your organization can share various kinds assets that can be reused throughout your integrations

[NOTE]
The Anypoint Platform on-Premises Edition 1.5 is based on link:https://www.docker.com/[Docker] and link:https://kubernetes.io/[Kubernetes], and provides built in high availability. Although the installation wizard makes it easy for you to install the platform without needing to know about either Docker or Kubernetes, it is important to be familiar with how these work for managing and troubleshooting the platform.



* link:/anypoint-platform-on-premises/v/1.5.0/installing-anypoint-on-premises[Installing Anypoint On-Premises]
* link:https://docs.mulesoft.com/api-manager/[API Manager]
* link:https://docs.mulesoft.com/runtime-manager/[Anypoint Runtime Manager]
* link:https://docs.mulesoft.com/access-management/[Access Management]

[NOTE]
Version 1.5.2 of the Runtime Manager Agent is the only one that works with this version of the platform. Version 1.5.3 of the Runtime Manager Agent (which is bundled with Mule runtime 3.8.3) is not currently supported by this release.
