= Mule Hazelcast server documentation
:keywords:pcf, hazelcast, clusters, pivotal cloud foundry,


[NOTE]
Setting this up is an optional step when link:/anypoint-platform-on-premises/v/1.5.0/configuring-anypoint-platform-for-pcf[configuring Anypoint Platform for PCF]. You need this in case you plan to deploy your applications to clusters on PCF.


Mule Hazelcast server is a customization of the link:https://hazelcast.org/[hazelcast] distribution adapted for the needs of the Mule Runtime.

This custom implementation doesn't change the Hazelcast behavior at all. It just set up basic configuration required by the
Mule Runtime plus default configuration for logging using log4j.

== Requirements

The only requirement is to have JDK 1.8 installed and the JAVA_HOME environment variable properly set

== Installation

.To install:
* Unzip the distribution into your working directory
* Execute `bin/start.sh` (in linux) or `bin.start.bat` (in windows)

This will start a Hazelcast server node using the default configuration located in the `conf/hazelcast.xml` file.

== Configuration

=== Log4j Configuration

To configure log4j just customize the log4j configuration file located in `conf/log4.xml`.

=== Hazelcast Configuration

To customize the Hazelcast configuration, just modify the file located in conf/hazelcast.xml following
the http://docs.hazelcast.org/docs/3.6.2/manual/html-single/[hazelcast documentation] instructions. Take into account that the Hazelcast version being used is 3.6.2.

Proper configuration requires:

* Change the default group name and group password. These values are used to define a cluster with Hazelcast. All nodes with the same group name/password will create a cluster
* Configure the network parameters for proper communication between the cluster nodes
