= Set PCF Flag Manually
:keywords:pcf, pivotal cloud foundry, buildpack


. Enter the Kubernetes cluster:
+
----
sudo gravity enter
----

. You must modify the `amc-ui-facade.properties` file to set the `features.pcf.enabled` property to `true`. In order to do this, you must first copy its contents via the following command:
+
----
kubectl get secret/amc-ui-rest-facade-cloudhub -o yaml | grep amc-ui-facade.properties | awk '{print $2}' | base64 -d
----
+
This command will return something resembling the following example:
+
----
# AMC
amc.rest.host=hybrid-rest.default.svc
amc.rest.v1.path=/hybrid/api/v1
amc.rest.port=8081

# Cloudhub
cloudhub.rest.host=nginx
cloudhub.rest.v2.path=/cloudhub/api/v2
cloudhub.rest.port=443

# CS
coreservices.rest.host=cs-auth.default.svc
coreservices.rest.path=/api
coreservices.rest.port=3005

# AMC UI Facade server configuration
http.port=5005
http.pathPrefix=/armui/api/v1

# Onprem configuration
features.cloudhub.enabled = false
features.pcf.enabled = false
----

. Copy the *entire contents* of this file

. Exit the Kubernetes cluster through the following command:
+
----
exit
----

. From the instance, create a new properties file:
+
----
touch new.amc-ui-facade.properties
----

. Open vi and paste the content you just copied from the current properties file:
+
----
vi new.amc-ui-facade.properties
----
+
[TIP]
You can also use SCP or any other alternative editing tool you prefer.

. In vi, edit the file to set the value of the property `features.pcf.enabled` to `true`. Then save.

. Encode the content of the file new.amc-ui-facade.properties into another file (This is needed to create the k8s secret):

+
----
cat new.amc-ui-facade.properties | base64 -w0 > new.amc-ui-facade.properties.base64
----

. Make a backup of the previous secret, exporting the content of that secret to a file. To achieve that:

.. enter the k8s cluster again with:
+
----
sudo gravity enter
----

.. export the content of the current secret to a file:
+
----
kubectl get secret/amc-ui-rest-facade-cloudhub -o yaml > /var/lib/gravity/planet/share/amc-ui-rest-facade-cloudhub-backup.yaml
----

.. Exit the k8s cluster again typing exit.

.. Make a copy of your secret’s backup file:
+
----
cp /var/lib/gravity/planet/share/amc-ui-rest-facade-cloudhub-backup.yaml /var/lib/gravity/planet/share/amc-ui-rest-facade-cloudhub.yaml
----

. On the newly copied file (`amc-ui-rest-facade-cloudhub.yaml`), modify the value of the secret with the encoded value you generated in the file new.amc-ui-facade.properties.base64. So, first copy the content of the file new.amc-ui-facade.properties.base64 and then type:

+
----
vi /var/lib/gravity/planet/share/amc-ui-rest-facade-cloudhub.yaml
----
+
Look for the key with the name amc-ui-facade.properties and replace its value with the content of the new.amc-ui-facade.properties.base64 file. Then save changes.

. Go inside the k8s cluster again by typing sudo gravity enter

. Replace the `amc-ui-rest-facade` secret:
+
----
kubectl replace -f /var/lib/gravity/planet/share/amc-ui-rest-facade-cloudhub.yaml
----
. Delete the pod and wait until the a file named amc-ui-rest-facade-*************** is created (you can verify the state of the pods through the command `kubectl get pods`):
+
----
amc-ui-rest-facade-***************
----

. You can check that pcf is enabled by opening the newly created amc-ui-rest-facade-************ pod:
+
----
kubectl exec -it amc-ui-rest-facade-3591398653-9pqj7 bash

cat /opt/cloudhub/amc-ui-facade.properties
----

There you should see the `features.pcf.enabled` property set to `true`.
