= Installing Anypoint Platform On Premises Edition
:keywords:anypoint platform, on premises


== Overview

The Anypoint Platform On-Premises Edition requires that you set up an SMTP server to manage alert e-mails. This document explains how to refer your Anypoint Platform installation to your existing SMTP server in your local network. This document assumes that you have already completed the link:/anypoint-platform-on-premises/installing-anypoint-platform-on-premises[installation of the platform] through the wizard.

Currently, setting up SMTP for alert e-mails for link:/api-manager[API Manager] is handled via the link:/access-management/on-premises-features#smtp[Access Management panel], but the SMTP settings for alert e-mails for link:/runtime-manager[Runtime Manager] must be set up manually as explained in this document. In future releases, both will be set via the Access Management UI.

== Configuring an SMTP Server

. Enter one of the nodes on which you installed the Anypoint Platform
. Run the following command:
+
----
`sudo gravity enter`
----
. Export the content of the secret to a file, so as to have a *backup*:
+
----
kubectl get secret/mule-message-processor-mulesoft -o yaml > mule-message-processor-mulesoft.yaml
----

+
[TIP]
====
You can check the current content of the secret via the following command:

----
kubectl get secret/mule-message-processor-mulesoft -o yaml | grep override.properties | awk '{print $2}' | base64 -D
----
====

. Create a file named `override.properties` inside the folder `/var/lib/gravity/planet/share/`. In this file, add the following SMTP properties, which will replace the default onees:

+
----
...
smtp.host=<new value>
smtp.port=<new value>
smtp.user=<new value>
smtp.password=<new value>
----

. Delete the old secret via the following command:
+
----
kubectl delete secret/mule-message-processor-mulesoft
----

. Create a new secret:
+
----
kubectl create secret generic mule-message-processor-mulesoft --from-file=override.properties
----

. Delete the old pod through the following command:
+
----
kubectl delete pod <pod-name>
----

+
[TIP]
====
You can obtain the pod name by running the command:
----
kubectl get pods
----

Look for the pod assigned to *mule-message-processor*
====

. You can validate that this procedure was successful by checking the content of the file `/opt/mulesoft/override.properties`, and by running an SSH command to the pod, as shown below:
+
----
kubectl exec -it <pod-name> bash
----
