= About the Mule SDK
:keywords: mule, sdk

The Mule SDK is a tool that allows you to extend the Mule 4 Runtime by creating new modules you can install in  applications. Examples of such modules are connectors, such as HTTP, or modules with custom functionality such as the Validations Module.

The SDK provides a stable API for:

* Faster development of Mule components.
* Decouples the built modules from the Runtime internals.
* Assures consistency across Mule components and other modules such as cloud connectors.

== Differences with Devkit

If you developed custom components for Mule 3.x, then this should sound pretty similar to the old Anypoint Devkit for Connectors. The Mule SDK is an evolution of that DevKit and takes its place for Mule 4.0 as the canonical way of extending the runtime (DevKit is not available in Mule 4).

Although the SDK builds on the same idea of annotated Java classes, it's different in its inner workings:

* The SDK isn't a code generator. The built module does not contain any generated code (not even the XSD schema). Your module  interacts with the Runtime through a clearly defined _Extensions API_. Users don't need to learn the details of this API, the SDK as a framework takes care of that for you.
* The SDK is way more powerful and supports features not available in the old DevKit such as:
  ** Transactions
  ** Request-Response message sources
  ** Dynamic configurations
  ** Routers
  ** Non-Blocking operations
  ** Classloading isolation
  ** Enhanced interoperability with Runtime services
  ** Much, much more
