= Pushing Messages to a Flow form a Message Source
:keywords: mule, sdk, sources, listener, triggers, generate, push, message

Once the source generates a piece of information that needs to be sent to the flow, it will do it through
the `SourceCallback`. Going back to the minimalistic Http listener example:

[source, java, linenums]
----
public class HttpListener extends Source<InputStream, HttpRequestAttributes> {

    @Override
    public void onStart(SourceCallback<InputStream, HttpRequestAttributes> sourceCallback) throws MuleException {
        httpServer = serverProvider.connect(); // <1>

        server.listen(path).onRequest(request -> { // <2>
            Result<InputStream, HttpRequestAttributes> result = requestToResult(request); // <3>
            sourceCallback.handle(result); // <4>
        });
    }
}
----

<1>  We use the ConnectionProvider to obtain an HttpServer. The connection provider has most likely already
configured the server with the proper host and port.
<2> Http requests are pushed into the server by the remote clients and the  `HttpServer` component will
notify the source of every request. The source then uses the `SourceCallback` to push the message into the flow
<3> To message is represented leveraging the same `Result` object that operations use to communicate
complex outputs. Check the <<result-object#, `Result`>> documentation for more information.
<4> We use the `handle(Result)` method in the `SourceCallback` to pass the message.

== Threading model

Once the Result object is passed to the `SourceCallback` through the `handle(Result)` method, the actual
processing of that message happens asynchronously in a different thread than the one invoking the method.

Keep reading the next step in order to know how to catch the result of the Flow processing and optionally
sending a response.

== Next step

* link:sources-response[Obtaining Flow output and Sending responses from a Message Source]
