= About Event Processors

Event Processors are the Mule components, connectors, and modules used to conduct backend processes for specific business logic around the Mule event.

By default, each Event processor (connector or other component in the flow) that receives a Mule event, returns a new Mule message, typically with the set of attributes and payload that the processor returns. The processor passes on new message as output to the next processor in the flow. Unlike variables in the Mule event, which persist for the duration of the flow, the Mule message . 

They are grouped based on the actions they facilitate:

* link:/mule-user-guide/v/4.0/about-operations[About Operations]
* link:/mule-user-guide/v/4.0/scopes-concept[About Scopes]
* link:/mule-user-guide/v/4.0/about-routers[About Routers]
* link:/mule-user-guide/v/4.0/about-transformers[About Transformers]
* link:/mule-user-guide/v/4.0/modules-and-connectors-about[About Modules]


== See Also

* link:/mule-user-guide/v/4.0/about-components[About Components]
