
= About Event Processors

Event Processors are the components used to conduct backend processes for specific business logic around the *Mule event*.

They are grouped based on the actions they facilitate:

* <<Operation>>
* <<Scope>>
* <<Router>>
* <<Transformer>>
* <<Module>>


== Operation

*Operations* apply specific actions in the Mule application. They can be used to generate a request to an external source, or to point to local resources within an application's package structure.

Examples of *operations* are any connectors that are supported by a module, like the Database Connector. Most connectors are now based on the operation model.


== Scope

*Scopes* can wrap a group of *operations* within a *flow* to define a fine-grained behavior for them to apply. They can be used to define the frequency at which to perform an operation, or to specify that a certain group of *operations* should be applied asynchronously.

// REVIEW: is async a scope or a router?
Some examples of scopes are *Poll* and *Async*.

//TODO: Can I use a scope to enrich a message payload?

== Router

*Routers* can be used to direct, resequence, split and aggregate Mule events.

Some examples of routers are _Splitter_, _Scatter-gather_ and _Resequencer_.

== Transformer

A transformer is a *component* that changes the contents of the *Mule event*.

Some examples of *transformers* are _Object to XML_ and the _Object to String_ transformers.

[CAUTION]
Transformers are included in Mule 4 Beta for compatibility reasons. They will be deprecated for future releases. +
Transformations should be carried out through DataWeave expressions in the Transform component.


== Module

A module is a package of functionality for Mule. It can combine *Event sources*, perform *operations* and offer a number *configurations*, each of which may support a subset of operations.

Each *Module* can extend the runtime capabilities allowing users to configure connections to different services almost automatically.

// REVIEW: Modules to use to validate

// REVIEW: Determine if this is technically accurate
Importantly, *modules* don't have to have any Mule-specific code; they can simply be POJOs, Spring beans, Java beans, Groovy scripts, or web services containing the business logic for processing data. Components can even be developed in other languages such as Python, JavaScript, Ruby, and PHP. Mule’s catalog of *components* support the most commonly used Enterprise Integration Patterns.

Some examples of *modules* are the _SalesForce Connector_ and the _SAP Connector_.

=== Configurations

Global configurations for a specific *module* are typically defined for a connector

// REVIEW: Removing DW as a core concept.
// == DataWeave
//
// Dataweave is the primary language used for formulating expressions in Mule, allowing you to access, manipulate, and use information from the message and its environment. 
//
// At runtime, Mule evaluates expressions while executing a flow to:
//
// * Extract information from the Mule event.
// * Restructure or manipulate any part of the Mule event.
// // REVIEW: Define if DW can be used to filter muleEvents.
// * Define a filter, to allow certain *Mule events* to continue to be processed in a *flow* based on certain criteria.
// * Set or manipulate a value in the message attribute, the payload, or a variable.
// * Perform an operation on information in the Mule event, application, Mule instance, or server.

== See Also

* link:/mule-user-guide/v/4.0/about-components[About Components]
