
= About Event Processors

Event Processors are the components used to conduct backend processes for specific business logic around the Mule event.

They are grouped based on the actions they facilitate:

* <<Operation>>
* <<Scope>>
* <<Router>>
* <<Transformer>>
* <<Module>>


== Operation

Operations apply specific actions in the Mule application. They can be used to generate a request to an external source, or to point to local resources within an application's package structure.

Examples of operations are any connectors that are supported by a module, like the Database Connector. Most connectors are now based on the operation model.


== Scope

Scopes can wrap a group of operations within a flow to define a fine-grained behavior for them to apply. They can be used to define the frequency at which to perform an operation, or to specify that a certain group of operations should be applied asynchronously.

Some examples of scopes are Poll and Async.

== Router

Routers can be used to direct, resequence, split and aggregate Mule events.

Some examples of routers are _Splitter_, _Scatter-gather_ and _Resequencer_.

== Transformer

A transformer is a component that changes the contents of the Mule event.

Some examples of transformers are _Object to XML_ and the _Object to String_ transformers.

[CAUTION]
Transformers are included in Mule 4 Beta for compatibility reasons. They will be deprecated for future releases. +
Transformations should be carried out through DataWeave expressions in the Transform component.


=== Configurations

Global configurations for a specific module are typically defined for a connector


== See Also

* link:/mule-user-guide/v/4.0/about-components[About Components]
