= To Configure the Cache Scope

. In your Mule app, add a Cache scope to a flow.
. Click to open the General tab for the Cache scope.
. Configure the Cache scope:
+
* Provide a Display Name.
* Select a Caching strategy.
+
MuleSoft recommends that you reference a caching strategy that uses an ObjectStore instead of using the default in a production environment.
+
** From the UI: Caching_Strategy
** In the Studio XML: `cachingStrategy-ref="Caching_Strategy"`
+
If you need to create a Caching Strategy, see the procedure in <<See Also>>.
+
* Filter specific message from the Cache scope flow.
+
Instead of processing all messages, you can filter messages in these ways:
+
** Using a DataWeave expression.
+
Example: `filterExpression="#[user.isPremium()]"`
+
If the message matches the expression(s), Mule executes the caching strategy.
+
If the message does not match expression(s), Mule processes the message through all message processors within the cache scope but never saves or offers cached responses.
+
** Using a global filter.
+
Example: `filter-ref="MyGlobalFilter"`
. Add one or more message processors (components or connectors) to the Cache component.

== See Also

link:cache-scope-strategy[To Set Up a Caching Strategy]

link:cache-scope[About the Cache Scope]

////
// TODO
* To Set up a Caching Strategy
* To Configure a Response Generator
* To Configure a Consumable Message Filter
////
