= To Set Up a Caching Strategy for the Cache Scope

You can create a caching strategy from a Cache component or from the Global Elements configuration in Anypoint Studio. Once you create a strategy, a Cache component in the flow can reference it.

. Open the Caching Strategy configuration window from the Cache component or from the Caching Strategies option available from the Global Elements tab in Studio.
. Provide a Name for your caching strategy.
. Reference an ObjectStore or create one for your Cache component to reference.
+
. Select a mechanism for generating key used for storing events within the caching strategy:
+
** Default
** Key Expression: A DataWeave expression (for example, `keyGenerationExpression=“#[vars.requestId]`).
+
Note that for two requests that are the same ("equal"), you need to generate the same key. Otherwise, you can get wrong results.
+
** Key Generator: Requires you to implement the `com.mulesoft.mule.runtime.cache.api.key.MuleEventKeyGenerator` interface.
+
. Perform any optional steps:
+
* Select or create a Response Generator.
+
Note that this step requires that you implement the
`com.mulesoft.mule.runtime.cache.api.response.ResponseGenerator` interface.
+
* Select or create a Consumable Message Filter.
+
Note that this step requires that you implement the `com.mulesoft.mule.compatibility.core.api.routing.filter.Filter` interface.
+
* Change the Event Copy Strategy from Simple (the default, where data is immutable) to Serializable (where data is mutable).

== See Also

link:cache-scope[About the Cache Scope]

link:cache-scope-to-configure[To Configure the Cache Scope]

link:/connectors/v/latest/object-store-to-define-a-new-os[Example: To Define a Global ObjectStore]

////
// TODO
NEED TO PROVIDE LINK TO THE API DOCS ONCE THEY BECOME AVAILABLE.
////
