= About the Cache scope
:keywords: cache, anypoint, studio

The Cache scope is for storing and reusing frequently called data. You can use a Cache scope to reduce the processing load on the Mule instance and to increase the speed of message processing within a flow. It is particularly effective for these tasks:

* Processing repeated requests for the same information.

* Processing requests for information that involve large, non-consumable message payloads.

You can put any number of message processors (such as connectors or components) into a Cache scope and configure the caching strategy to store the responses (which contain the payload of the response message) produced by the processing that occurs within the scope.

==  Caching Strategy

By default, the Cache scope uses a caching strategy that stores data `InMemoryObjectStore` instead of an `ObjectStore`. MuleSoft recommends that you only use the default for non-production purposes, such as testing. For production environments, you should set up a caching strategy that uses the `ObjectStore`.

== Caching Flow

When a message processor in a Mule app sends a message to the Cache scope, the parent flow expects an output. The Cache scope processes the message, delivers the output to the parent flow, and saves the output (that is, caches the response). The next time the Cache scope receives the same kind of message, the scope can offer a cached response rather than invoking a potentially time-consuming process again.

== Filters

Instead of processing all messages that it receives, the Cache scope can exclude specific messages from the Cache scope flow based on an DataWeave expression or a global filter.

== Supported Exchange Patterns

You can configure these exchange patterns in a Cache scope:

* Request-response
* One-way

Regardless of exchange pattern settings or any data retrieval activity that might occur within it, the Cache scope simply caches the output of the flow inside it. When a message next enters the scope, the Cache scope offers the cached output, or cached response.

For instance, you can use a Cache scope to manage customer requests for flight information. Many customers might request the same pricing information about flights from San Francisco to Buenos Aires. Rather than using a lot of processing power to send separate requests to several airline databases with each customer query, you can use a Cache scope to arrange to send a request to the databases fewer times – say, once every ten minutes – and present users with the cached flight pricing information. Where timeliness of data is not critical, Cache scope can save time and processing power.

== See Also

link:cache-scope-to-configure[To Configure the Cache Scope]

link:cache-scope-caching-strategy[About Caching Strategies with the Cache Scope]
