= About the Cache scope
:keywords: cache, anypoint, studio

The Cache scope is for storing and reusing frequently called data. You can use a Cache scope to reduce the processing load on the Mule instance and to increase the speed of message processing within a flow. It is particularly effective for:

* Processing repeated requests for the same information.

* Processing requests for information that involve large, non-consumable message payloads.

The default caching strategy defines how data are stored and reused, but if you want to adjust cache behavior, you can customize a global caching strategy in Mule and make it available for use by all Cache scopes in your application.

You can put any number of message processors into a Cache scope and configure the caching strategy to store the responses (which contain the payload of the response message) produced by the processing that occurs within the scope.

Mule sends a message into the Cache scope, and the parent flow expects an output. The Cache scope processes the message, delivers the output to the parent flow, and saves the output (that is, caches the response). The next time Mule sends the same kind of message into the Cache scope, the Cache scope might offer a cached response rather than invoking a potentially time-consuming process again.

Note that you can configure the exchange patterns of connectors in a Cache scope to operate:

* Request-response
* One-way

Regardless of exchange pattern settings or any data retrieval activity that might occur within it, the Cache scope simply caches the output of the flow inside it. When a message next enters the scope, the Cache scope offers the cached output, or cached response.

For instance, you can use a Cache scope to manage customer requests for flight information. Many customers may request the same pricing information about flights from San Francisco to Buenos Aires. Rather than using a lot of processing power to send separate requests to several airline databases with each customer query, you can use a Cache scope to arrange to send a request to the databases fewer times – say, once every ten minutes – and present users with the cached flight pricing information. Where timeliness of data is not critical, Cache scope can save time and processing power.

== See Also

link:cache-scope-caching-stragegy[About Caching Strategies with the Cache Scope]
