= About the Choice Router

The choice flow control dynamically routes messages based on message payload or properties. It adds conditional programming to a flow, similar to an if/then/else code block.

A choice flow control uses expressions to evaluate the content of a message, then it routes the message to one of the routing options within its scope (see image below). It directs messages to the first routing option in the scope that matches the routing configurations (evaluates to true). If none of expressions evaluate to true, the choice flow control directs the message to the default (else) route.





To configure the choice flow control, you need to determine the following message routing details:

What content the choice flow router evaluates to determine routing

Number of routing options for the choice flow control

What processing Mule performs for each routing option

Default routing option

After you determine your routing goals, follow this procedure to define the routing options, then the routing instructions.


== See Also
