= Choice XML Reference


A Choice flow control component follows the structure described below.


* A single root element `<choice>`
* A `<when>` child element for each of the choices it handles. It can optionally also include an `<otherwise>` to handle all other cases.
* Components that are conditionally executed under each of the choices are defined as child elements of the `when` and `otherwise` elements.



When

Use to define all non-default routing options within the choice flow control.

Otherwise

Use to define the default routing option for the message, should none of the preceding when expressions evaluate to "true"



expression

Use DataWeave to define an expression that the choice router uses to evaluate the contents of a message. If the expression evaluates to "true", it directs message to this routing option.


[source,xml,linenums]
----
<choice doc:name="Choice">
           <when expression="#[flowVars.language == 'french']">
               <set-payload value="Bonjour!" doc:name="Reply in French"/>
            </when>
           <when expression="#[flowVars.language == 'spanish']">
               <set-payload value="Hola!" doc:name="Reply in Spanish"/>
            </when>
           <otherwise >
               <set-variable variableName="language" value="English" doc:name="Set Language to English"/>
               <set-payload value="Hello!" doc:name="Reply in English"/>
            </otherwise>
</choice>
----





== See Also
