= About Property Placeholders in Mule Apps

Instead of using static values for connections and other configurations in your Mule app, you can create and use property placeholders that you define in a configuration file (a `.yaml` or `.properties` file). You can manage the values from the configuration file and through system properties. Using system properties is useful if you need to change the settings when deploying to a new environment, as when you promote the application to a production environment.

You follow this general procedure:

. Specify each placeholder and placeholder value in a configuration file.
. Pass the key for the placeholder to a connector or component in your Mule app.
. Create a global configuration property for your Mule app that references the configuration file.
. Use system properties, as needed, to change the values of the placeholders in the configuration file or to change the configuration file that you pass to the global configuration property.

The procedures are detailed through the topics in the See Also section.

== See Also

* link:/mule-user-guide/v/4.0/mule-app-properties-to-configure[To Create Property Placeholders for Mule Apps]
* link:/mule-user-guide/v/4.0/mule-app-properties-system[Working with System Properties]
// * link:/mule-user-guide/v/4.0/mule-app-property-placeholders-spring[To Create Placeholders for Spring Configurations]
