= About Property Placeholders in Mule Apps

Instead of using static values for connections and other configurations in your Mule app, you can create and use property placeholders that you define in a configuration file. You can manage the values from the configuration file and through system properties. Using system properties is useful if you need to change the settings when deploying to a new environment, as when you promote the application to a production environment.

[[typical_use_case]]
Typical use cases:

* The configuration file provides default values that you can override through system properties.
* You use a system property to choose a file with the properties that you need for the environment. In this case, you might have a configuration file for two different environments, for example, one file for development, another for production.

[[general_tasks]]
General tasks for these use cases:

* Specifying each placeholder in a configuration file, for example:
** In a YAML file: `port: 8080`
** In a properties file: `port=8080`
* Passing the key for the placeholder (such as `${port}`) to a connector or component in your Mule app.
* Creating a global configuration property for your Mule app that references the configuration file, for example:
+
`<configuration-properties file="dev.yaml"/>` or `<configuration-properties file="${environment}.yaml"/>`
+
In the Studio UI, this XML is generated when you create a Global Element of type Configuration Properties.
+
Note that `.properties` files are also acceptable here.
+
* Specifying system properties as arguments to the command used to run the Mule app, for example:
** Passing in `-Dport=80` to change the values of the placeholders in the configuration file.
** Passing in `-Denvironment=prod` to change the configuration file that you pass to the global configuration property.

More information about performing these tasks is available in the topics listed in the See Also section.

== See Also

* link:/mule-user-guide/v/4.0/mule-app-properties-to-configure[To Create Property Placeholders for Mule Apps]
* link:/mule-user-guide/v/4.0/mule-app-properties-system[Working with System Properties]
// * link:/mule-user-guide/v/4.0/mule-app-property-placeholders-spring[To Create Placeholders for Spring Configurations]

////
== Example

Assume that you have properties files, one called `dev.yaml` (or `dev.properties`) where you specify development environment properties and another called `prod.yaml` (or `prod.properties`) where you specify properties for the development environment. You also have an `environment.properties` where you specify the environment (for example, `environment=dev`).

Assume that you have this global configuration property for your Mule app:
`<configuration-properties file="${environment}.properties"/>`

In this scenario, can use system properties to inject the properties of the correct configuration file from Studio or from the command line, for example:
`-Denvironment=prod`
////
