= DataWeave Operators [by some grouping]

_Alt 3 notes:_
We are looking for suggestions about what groupings of operators might make sense.

We are not suggesting the specific groupings shown on this page. For example, it could be difficult to maintain groupings by input data types, and some choices around data types are not as clear-cut as others.

Our main goal should be to get customers to the operators they want to see and to prevent them from having to examine every single operator we have. It would be great if the groups were mutually exclusive, but that might not be possible.

[cols="1",options="header"]
|===
|Operators

|link:/mule-user-guide/v/4.0/dataweave-operators-common[Common Operators]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-numbers[Operators for Numbers]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-strings[Operators for Strings]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-other[Operators TODO]

| SOME OTHER GROUPING...
|===

////
|link:/mule-user-guide/v/4.0/dataweave-operators-for-arrays[Operators for Arrays]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-dates[Operators for Dates]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-objects[Operators for Objects]
////
