= About DataWeave
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datawave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

DataWeave is the MuleSoft expression language for accessing and transforming data received through a Mule app. DataWeave is tightly integrated with Mule runtime, which runs the scripts and expressions in your Mule app.

DataWeave acts on the Mule event. Most commonly, you use it to access and transform data in the message payload. For example, after a component in your app retrieves data from one system, you can use DataWeave to modify and output selected fields in that data to a new data format, then use another component in your app to pass on that data to another system.

DataWeave supports several file input and output formats, including XML and JSON. It provides a number of functions for manipulating data and includes selectors for accessing nodes in the data structure. It can handle a number of data types, including arrays, key-value pairs, Java objects, strings, and numbers. It also supports the creation and use of your own functions, data types, and variables in your scripts.

The simple example below demonstrates a few important features of the DataWeave language:

* Data transformation from one format to another. The example transforms `application/json` input to `application/xml` output.
* Data selectors that access nodes in a data structure. The script selects keys in a JSON object from the message payload input and then outputs their values.
* Applies a core DataWeave function to the value of one of the input fields (`(upper(payload.author))`).

.Input Payload
[source,json,linenums]
----
{
  "title": "Java 8 in Action: Lambdas, Streams, and functional-style programming",
  "author": "Mario Fusco",
  "year": 2014
}
----

.Transform
[source, dataweave, linenums]
----
%dw 2.0
output application/xml
---
{
  order: {
    'type': 'Book',
    'title': payload.title,
    'author': (upper(payload.author)),
    'year': payload.year
  }
}
----

.Output Payload
[source,xml,linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<order>
  <type>Book</type>
  <title>Java 8 in Action: Lambdas, Streams, and functional-style programming</title>
  <author>MARIO FUSCO</author>
  <year>2014</year>
</order>
----

Far more complex data manipulation and transformations are possible.

You write DataWeave scripts and expressions within message processors (components, connectors, and modules) when creating apps in Anypoint Studio and Design Center.

* The Transformer component is for creating scripts that perform data transformations, whether simple format conversions or complex data extraction and transformation processes.
* Fields in many Mule message processors support DataWeave expressions, allowing you to access and even use core DataWeave function on parts of the Mule event that you need.

== See Also

* link:about-mule-event[About the Mule Event]
* link:dataweave-formats[Formats that are Supported by DataWeave]
* link:dataweave-selectors[DataWeave Selectors]
* link:dataweave-scripts[DataWeave Scripts]
* link:about-components[About Components for Mule Apps]
* link:/connectors/index[Connectors and Modules]
