= Example: Inserting Attributes to an XML Tag
:keywords: studio, anypoint, transform, transformer, format, xml, json, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This example uses `@(key:value)` syntax (for example, `@(loc: "US")`) to create an XML attribute for a key:value pair.

It uses these functions:

* `map` to go through the 1=`key:value` pairs in an array.

.DataWeave
[source,DataWeave, linenums]
----
%dw 1.0
%output application/xml
---
{
  bookstore: { (payload map {
      book : {
      title @(lang: "en"): $.item.properties.title,
      year: $.item.properties.year,
      price: $.item.price,
      ($.item.properties.author map
      author @(loc: "US"): $)
    }
  }) }
}
----

////
[tabs]
------
[tab,title="Input: JSON"]
....
////

.Input JSON
[source, json, linenums]
----
[
  {
    "item": {
      "type": "book",
      "price": 30,
      "properties": {
        "title": "Everyday Italian",
        "author": [
          "Giada De Laurentiis"
        ],
        "year": 2005
      }
    }
  },
  {
    "item": {
      "type": "book",
      "price": 29.99,
      "properties": {
        "title": "Harry Potter",
        "author": [
          "J K. Rowling"
        ],
        "year": 2005
      }
    }
  },
  {
    "item": {
      "type": "book",
      "price": 49.99,
      "properties": {
        "title": "XQuery Kick Start",
        "author": [
          "James McGovern",
          "Per Bothner",
          "Kurt Cagle",
          "James Linn",
          "Vaidyanathan Nagarajan"
        ],
        "year": 2003
      }
    }
  },
  {
    "item": {
      "type": "book",
      "price": 39.95,
      "properties": {
        "title": "Learning XML",
        "author": [
          "Erik T. Ray"
        ],
        "year": 2003
      }
    }
  }
]
----

////
....
[tab,title="Output: XML"]
....
////

.Output XML
[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<bookstore>
  <book>
    <title lang="en">Everyday Italian</title>
    <year>2005</year>
    <price>30</price>
    <author loc="US">Giada De Laurentiis</author>
  </book>
  <book>
    <title lang="en">Harry Potter</title>
    <year>2005</year>
    <price>29.99</price>
    <author loc="US">J K. Rowling</author>
  </book>
  <book>
    <title lang="en">XQuery Kick Start</title>
    <year>2003</year>
    <price>49.99</price>
    <author loc="US">James McGovern</author>
    <author loc="US">Per Bothner</author>
    <author loc="US">Kurt Cagle</author>
    <author loc="US">James Linn</author>
    <author loc="US">Vaidyanathan Nagarajan</author>
  </book>
  <book>
    <title lang="en">Learning XML</title>
    <year>2003</year>
    <price>39.95</price>
    <author loc="US">Erik T. Ray</author>
  </book>
</bookstore>
----

////
....
------
////


== Related Examples

* link:/mule-user-guide/v/4.0/dataweave-cookbook-output-self-closing-xml-tags[Outputting self-closing XML tags]

* link:/mule-user-guide/v/4.0/dataweave-cookbook-remove-certain-xml-attributes[Remove Certain XML Attributes]


== See Also


* link:/mule-user-guide/v/4.0/dataweave-operators[DataWeave Operators]

* link:/mule-user-guide/v/4.0/dataweave-selectors[DataWeave Selectors]

* link:/mule-user-guide/v/4.0/dataweave-cookbook[DataWeave Cookbook]
