= DataWeave Types
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping


The DataWeave language functions essentially as a template engine that describes an output structure through the use of elements that may be of various different types.

== `Any`

`Any` is the top level type. Any extends all of the system types. That means anything can be assigned to a `Any` typed variable.

//.Definition

== `Array`

An array is a sequence of elements. It requires a Type(T) to represent the elements of the list. For example: `Array<Number>`` represents an array of numbers.
// TODO: NEED MORE INFO AND PROBABLY AN EXAMPLE that shows what we're talking about with Type(T)

.Example
[source,DataWeave,linenums]
----
%dw 2.0
output application/json
var x = "words"
---
[ "My", "three", x ]
----

=== Conditional Elements

Arrays can define elements that appear or don't, based on a condition.

Conditional elements have the form `(value) if condition`

.Transform
[source,DataWeave,linenums]
----
%dw 2.0
output application/json
---
[(1) if true, (2) if false]
----

.Output
[source,json,linenums]
----
[1]
----

[[dw_type_boolean]]
== `Boolean`

A `Boolean` is defined by the keywords `true` and `false`.

[[dw_type_binary]]
== `Binary`

`Binary` is the type for a blob.

[[dw_type_cdata]]
== `CData`

XML defines a custom type named `CData`, which inherits from and extends `String`. It  is used to identify a CDATA XML block. It can be used to tell the writer to wrap the content inside CDATA or to check if the input string arrives inside a CDATA block.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/xml
---
{
  users:
  {
    user : "Mariano" as CData,
    age : 31 as CData
  }
}
----

.Output
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<users>
  <user><![CDATA[Mariano]]></user>
  <age><![CDATA[31]]></age>
</users>
----

//.Definition

[source]
----
String {cdata: true}
----

[[dw_type_comparable]]
== `Comparable`

A union type that represents all the types that can be compared to each other.

//.Definition

[source]
----
String | Number | Boolean | DateTime | LocalDateTime | LocalTime | Time | TimeZone
----

[[dw_type_dates]]
== Date and Time Types

Dates in DataWeave follow the link:https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html[ISO-8601 standard] and literals are defined between `|` characters.

The language has the following native date types:

* `Date`
* `DateTime`
* `LocalDateTime`
* `LocalTime`
* `Period`
* `Time`
* `TimeZone`

[[dw_type_dates_date]]
=== `Date`

A `Date` represented by `Year`, `Month`, and `Day`, specified as `|YYYY-MM-dd|`. The `Date` type has no time component.

.Example
[source,DataWeave, linenums]
-----------------------------------------------------------------
|2003-10-01|
-----------------------------------------------------------------

[[dw_type_dates_datetime]]
=== `DateTime`

A Date and Time within a TimeZone. It is the conjunction of `Date` + `Time` + `TimeZone`.

.Example
[source,DataWeave, linenums]
-----------------------------------------------------------------
|2003-10-01T23:57:59-03:00|
-----------------------------------------------------------------

=== `LocalDateTime`

A `DateTime` in the current `TimeZone`.

.Example
[source,DataWeave, linenums]
-----------------------------------------------------------------
|2003-10-01T23:57:59|
-----------------------------------------------------------------

[[dw_type_dates_localtime]]
=== `LocalTime`

A `Time` in the current `TimeZone`.

[[dw_type_dates_period]]
=== `Period`

Periods have the form:

- `P[n]Y[n]M[n]DT[n]H[n]M[n]S`
- `P<date>T<time>`

Where the [n] is replaced by the value for each of the date and time elements that follow the [n].

`P` is the duration designator placed at the start of the duration representation.

- `Y` is the year designator (e.g. `|P1Y|`)
- `M` is the month designator (e.g. `|P1M|`)
- `D` is the day designator (e.g. `|P1D|`)

`T` is the time designator that precedes the time components of the representation.

- `H` is the hour designator (e.g. `|PT1H|`)
- `M` is the minute designator (e.g. `|PT1M|`)
- `S` is the second designator (e.g. `|PT1S|`)

.Transform
[source,DataWeave, linenums]
----------------------------------------------------------------
%dw 2.0
output application/json
---
a: |20:00:00| + |PT1M1S|
----------------------------------------------------------------

.Output
[source,json,linenums]
----------------------------------------------------------------
{
  "a": "20:01:01"
}
----------------------------------------------------------------

[[dw_type_dates_time]]
=== `Time`

A time in a specific `TimeZone`, specified as `|HH:mm:ss.SSS|`.

.Example
[source,DataWeave, linenums]
-----------------------------------------------------------------
|23:59:56|
-----------------------------------------------------------------

[[dw_type_dates_timezone]]
=== `TimeZone`

The `Time` relative to Greenwich Mean Time (GMT). A `TimeZone` must include a `+` or a `-`. For example, `|03:00|` is a time, while `|+03:00|` is a `TimeZone`.

.Example
[source,DataWeave, linenums]
----
|-08:00|
----

=== Date Decomposition

In order to access the different parts of the date, special selectors must be used.

.Transform
[source,DataWeave, linenums]
-----------------------------------------------------------------
%dw 2.0
output application/json
var myDate = |2003-10-01T23:57:59.700-03:00|
---
{
  year: myDate.year,
  month: myDate.month,
  day: myDate.day,
  hour: myDate.hour,
  minutes: myDate.minutes,
  seconds: myDate.seconds,
  milliseconds: myDate.milliseconds,
  nanoseconds: myDate.nanoseconds,
  quarter: myDate.quarter,
  dayOfWeek: myDate.dayOfWeek,
  dayOfYear: myDate.dayOfYear,
  offsetSeconds: myDate.offsetSeconds
}
-----------------------------------------------------------------

.Output
[source,json,linenums]
-----------------------------------------------------------------
{
  "year": 2003,
  "month": 10,
  "day": 1,
  "hour": 23,
  "minutes": 57,
  "seconds": 59,
  "milliseconds": 700,
  "nanoseconds": 700000000,
  "quarter": 4,
  "dayOfWeek": 3,
  "dayOfYear": 274,
  "offsetSeconds": -10800
}
-----------------------------------------------------------------

=== Changing the Format of a Date

You can specify a date to be in any format you prefer through using *as* in the following way:

.Transform
[source,DataWeave, linenums]
----------------------------------------------------------------
%dw 2.0
output application/json
---
formattedDate: |2003-10-01T23:57:59| as String {format: "YYYY-MM-dd"}
----------------------------------------------------------------

.Output
[source,json,linenums]
-----------------------------------------------------------------
{
  "formattedDate": "2003-10-01"
}
-----------------------------------------------------------------

If you are doing multiple similar conversions in your transform, you might want to define a custom type as a directive in the header and set each date as being of that type.

.Transform
[source,DataWeave, linenums]
----------------------------------------------------------------
%dw 2.0
output application/json
type Mydate = String { format: "YYYY/MM/dd" }
---
{
  formattedDate1: |2003-10-01T23:57:59| as Mydate,
  formattedDate2: |2015-07-06T08:53:15| as Mydate
}
----------------------------------------------------------------

.Output
[source,json,linenums]
-----------------------------------------------------------------
{
  "formattedDate1": "2003/10/01",
  "formattedDate2": "2015/07/06"
}
-----------------------------------------------------------------

[NOTE]
Type names are case-sensitive.

[[dw_type_dictionary]]
== Dictionary
Generic Dictionary interface.

//.Definition
// QUESTION: Internal???
////
[source]
----
{ _?: T }
----
////

[[dw_type_enum]]
== `Enum`

This type is based on the link:https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html[Enum Java class].
It must always be used with the `class` property, specifying the full Java class name of the class, as shown in this example.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/java
---
"Male" as Enum {class: "com.acme.GenderEnum"}
----

//.Definition
////
[source]
----
String {enumeration: true}
----
////

[[dw_type_iterator]]
== `Iterator`

The `Iterator` type is based on the link:https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html[Iterator Java class], that iterates through arrays. `Iterator` contains a collection and includes methods to iterate through and filter it.

Note that like the Java class, the iterator is designed to be consumed only once. For example, if you then pass this value to a logger would result in consuming it and it would no longer be readable to further elements in the flow.

[[dw_type_key]]
== `Key`

A `Key` type of an `Object`. See also, the `Object` and `Value` types.

//.Definition

[[dw_type_namespace]]
== `Namespace`

A `Namespace` type, represented by a URI and a Prefix.

//.Definition

[[dw_type_nothing]]
== `Nothing`

The `Nothing` type is the bottom-level type. It can be assigned to all the types.
//.Definition

[[dw_type_null]]
== `Null`

`Null` type.
// TODO

[[dw_type_number]]
== `Number`

There is only one number type that supports both floating point and integer numbers. There is no loss of precision in any operation, the engine always stores the data in the most performant way that does not compromise precision.

[[dw_type_object]]
== `Object`

Represents any object as a collection of `key:value` pairs.

.Example

[source,DataWeave,linenums]
---------------------------------------------------------
%dw 2.0
output application/json
---
{
  name: "Annie"
}
---------------------------------------------------------

=== Single Value Objects

If an Object has only one `key:value` pair, the enclosing curly brackets `{ }` are not required:

.Example

[source,DataWeave,linenums]
---------------------------------------------------------
%dw 2.0
output application/json
---
name: "Annie"
---------------------------------------------------------

=== Conditional Elements

Objects can define conditional *key*: *value* pairs based on a conditional expression.
Conditional elements have the form `(key:value) if condition`

[source,DataWeave,linenums]
---------------------------------------------------------
%dw 2.0
output application/xml
---
file: {
  name: "transform",
  (extension: "zip") if payload.fileSystem?
}
---------------------------------------------------------

This example outputs an additional field called "extension" only when the fileSystem property is present in payload (this field may contain any value, not just `true`).

[source,xml,linenums]
--------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<file>
  <name>transform</name>
  <extension>zip</extension>
</file>
--------------------------------------------------------

If absent:

[source,xml,linenums]
--------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<file>
  <name>transform</name>
</file>
--------------------------------------------------------

=== Dynamic Keys

In order to specify a key via an expression, the expression should be wrapped in parentheses.

.Transform
[source,DataWeave,linenums]
----
%dw 2.0
output application/json
var dynamicKey = "language"
---
{
  (dynamicKey): "Data Weave"
}
----

.Output
[source,json,linenums]
----
{
  "language": "Data Weave"
}
----

=== Dynamic Elements

Dynamic elements allow you to add the result of an expression as `key:value` pairs of an object. That expression must be either an `object` or an `array of objects`.

.Transform
[source,DataWeave,linenums]
--------------------------------------------------------
%dw 2.0
output application/json
var x = [
  {b: "b"},
  {c: "c", d: "d"}
],
var y = {e: "e"}
---
{
  a: "a",
  (x),
  (y)
}
--------------------------------------------------------

.Output
[source,json,linenums]
--------------------------------------------------------
{
  "a": "a",
  "b": "b",
  "c": "c",
  "d": "d",
  "e": "e"
}
--------------------------------------------------------

=== Conditional XML Attributes

You might want your output to only include certain XML attributes based on a condition.
Conditional elements have the form `(key:value) if condition`

.Transform
[source,DataWeave,linenums]
----
%dw 2.0
output application/xml
---
{
  name @(
    (company: "Acme") if false,
    (transform: "Anything") if true
  ): "DataWeave"
}
----

.Output
[source,xml,linenums]
----
<?xml version='1.0' encoding='US-ASCII'?>
<name transform="Anything">DataWeave</name>
----

=== Dynamic XML Attributes

You might want to include a changing set of key:value pairs in a specific location as XML attributes.

.Input
[source,json,linenums]
----
{
  "company": "Mule",
  "product": "DataWeave"
}
----

.Transform
[source,dataweave,linenums]
----
%dw 2.0
output application/xml
---
transformation @((payload)): "Transform from anything to anything"
----

.Output
[source,xml,linenums]
----
<?xml version='1.0' encoding='US-ASCII'?>
<transformation company="Mule" product="DataWeave">Transform from anything to anything</transformation>
----

[[dw_type_range]]
== `Range`

A Range type represents a sequence of numbers.

//.Definition
////
[source]
----
Range
----
////

[[dw_type_regex]]
== `Regex`

Regular Expressions are defined between `/`. For example `/\d+/` represents multiple numerical digits from 0-9. These may be used as arguments in certain operations that act upon strings, like Matches or Replace, or on operations that act upon objects and arrays, such as filters.

[[dw_type_simpletype]]
== `SimpleType`

A union type that represents all the simple types.

//.Definition

[source]
----
String | Boolean | Number | DateTime | LocalDateTime | Date | LocalTime | Time | TimeZone | Period
----

[[dw_type_string]]
== `String`

A string can be defined by the use of double quotes or single quotes.

[source,DataWeave, linenums]
--------------------------------------------------------
{
  doubleQuoted: "Hello",
  singleQuoted: 'Hello',
}
--------------------------------------------------------

=== String Interpolation

String interpolation allows you to embed variables or expressions directly in a string.

.Transform
[source,DataWeave, linenums]
--------------------------------------------------------
%dw 2.0
output application/json
var name = "Shoki"
---
{
    Greeting: "Hi, my name is $name",
    Sum: "1 + 1 = $(1 + 1)"
}
--------------------------------------------------------

.Output
[source,json,linenums]
--------------------------------------------------------
{
  "Greeting": "Hi, my name is Shoki",
  "Sum": "1 + 1 = 2"
}
--------------------------------------------------------

[[dw_type_tryresult]]
== `TryResult`

Evaluates the delegate and returns an object with the result or an error message. See the `try` example. A successful `TryResult` contains the `result` field and a `success` value of `true`. An unsuccessful `TryResult` contains the `error` field  and a `success` value of `false`.

.Definition

[source,Dataweave, linenums]
----
{
  success: Boolean,
  result?: T,
  error?: {
    kind: String,
    message: String,
    stack?: Array<String>,
    location?: String
  }
}
----

[[dw_type_type]]
== `Type`

Represents a Type in the DataWeave Type System.

// TODO.

[[dw_type_uri]]
== Uri

A URI, specified as `Uri`.

//.Definition
////
[source]
----
Uri

----
////

== See Also

* link:/mule-user-guide/v/4.0/dataweave-language-introduction[DataWeave Language Introduction]
* link:/mule-user-guide/v/4.0/dw-functions-core[DataWeave Core Functions]
*  link:https://www.mulesoft.com/exchange#!/?filters=DataWeave&sortBy=rank[Anypoint Exchange (List of Projects that use DataWeave)]

////
= DataWeave Types:
== String
== Boolean
== Number
== Range
== Namespace
== Uri
== DateTime
== LocalDateTime
== Date
== LocalTime
== Time
== TimeZone
== Period
== Binary
== Null
== Regex
== Nothing
== Any
== Array
== Object
== Type

==TryResult
