= DataWeave Operators [by some grouping]

We are looking for input on groupings that might make sense.

The main goal should be to get customers to the operators they want to see and to prevent them from having to look through every single operator we have. If there are no clearcut groupings, then the alpha ordered table might suffice.

Here are some sample groupings for operators. _We are not suggesting these specific groupings_. For example, it could be difficult to maintain groupings by input data types, and some choices around data types are not as clearcut as others.

[cols="1",options="header"]
|===
|Operators

|link:/mule-user-guide/v/4.0/dataweave-operators-common[Common Operators]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-numbers[Operators for Numbers]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-strings[Operators for Strings]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-other[Operators TODO]

| SOME OTHER GROUPING...
|===

////
|link:/mule-user-guide/v/4.0/dataweave-operators-for-arrays[Operators for Arrays]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-dates[Operators for Dates]

|link:/mule-user-guide/v/4.0/dataweave-operators-for-objects[Operators for Objects]
////
