= Example: Pass Functions as Arguments
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This example sets all of the keys in the input to lower case. It includes a function in the header that recieves as arguments an element to act upon and another function to apply to its keys. It then applies this passed function recursively to every child element below the one that was passed as argument.  In this case, the function that is passed as an argument sets keys to lower case.

The example uses the following:

* A custom function that is applied recursively, ie: it calls itself for each child element in its input.
* `mapObject` to sort through each child of the element that is passed to the function in the header.
* `lower` to make every Key in the input lower case.
* `is` to check if the passed element is of type `Object` (and therefore has children).
* `when` and `otherwise` to only have the function call itself when the the condition is met, and to otherwise end the recursive loop.



.DataWeave
[source,dataweave, linenums]
----
%dw 2.0
%output application/xml
%function applyToKeys(element, func)
    element mapObject (value, key) -> {
             (func(key)) : applyToKeys( value, func)
    } when element is Object otherwise element
---
applyToKeys(payload, (key) -> lower(key))
----

.Input XML
[source,xml, linenums]
----
<CATALOG>
  <CD>
    <TITLE>Empire Burlesque</TITLE>
    <ARTIST>Bob Dylan</ARTIST>
    <COUNTRY>USA</COUNTRY>
    <COMPANY>Columbia</COMPANY>
    <PRICE>10.90</PRICE>
    <YEAR>1985</YEAR>
  </CD>
  <CD>
    <TITLE>Hide your heart</TITLE>
    <ARTIST>Bonnie Tyler</ARTIST>
    <COUNTRY>UK</COUNTRY>
    <COMPANY>CBS Records</COMPANY>
    <PRICE>9.90</PRICE>
    <YEAR>1988</YEAR>
  </CD>
</CATALOG>
----

.Output XML
[source,xml, linenums]
----
<?xml version='1.0' encoding='US-ASCII'?>
<catalog>
  <cd>
    <title>Empire Burlesque</title>
    <artist>Bob Dylan</artist>
    <country>USA</country>
    <company>Columbia</company>
    <price>10.90</price>
    <year>1985</year>
  </cd>
  <cd>
    <title>Hide your heart</title>
    <artist>Bonnie Tyler</artist>
    <country>UK</country>
    <company>CBS Records</company>
    <price>9.90</price>
    <year>1988</year>
  </cd>
</catalog>
----

== See Also

link:/mule-user-guide/v/4.0/dataweave-types[DataWeave Value Types]

link:/mule-user-guide/v/4.0/dataweave-operators[DataWeave Operators]

link:/mule-user-guide/v/4.0/dataweave-selectors[DataWeave Selectors]

link:/mule-user-guide/v/4.0/dataweave-examples[DataWeave Examples]
