= dwcore::system

System Module
Defines all core functionality that all mapings will have autoimported

== ++

=== ++(lhs: Array<S >, rhs: Array<T >): Array<S  | T >


It returns the resulting array of concatenating two existing arrays.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: [0, 1, 2] ++ [3, 4, 5]
}
----

.Output
[source,json,linenums]
----
{
"a": [0, 1, 2, 3, 4, 5]
}
----

=== Using Concat on a String

.(':string', ':string') => ':string'

Strings are treated as arrays of characters, so the operation works just the same with strings.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
name: "Mule" ++ "Soft"
}
----

.Output
[source,json,linenums]
----
{
"name": MuleSoft
}
----
=== ++(lhs: String, rhs: String): String


Strings are treated as arrays of characters, so the operation works just the same with strings.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
name: "Mule" ++ "Soft"
}
----

.Output
[source,json,linenums]
----
{
"name": MuleSoft
}
----
=== ++(lhs: Object, rhs: Object): Object

Returns the resulting object of concatenating two existing objects.

.Transform
[source,DataWeave,linenums]
----
%dw 1.0
%output application/xml
---
concat: {aa: "a"} ++ {cc: "c"}
----

.Output
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<concat>
<aa>a</aa>
<cc>c</cc>
</concat>
----

The example above concatenates object {aa: a} and {cc: c} in a single one => {aa: a , cc: c}
=== ++(lhs: Date, rhs: LocalTime): LocalDateTime

You can append a date to a time (or localtime) object so as to provide a more precise value.


.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: |2003-10-01| ++ |23:57:59|,
b: |2003-10-01| ++ |23:57:59Z|
}

----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59",
"b": "2003-10-01T23:57:59Z"
}
----


Note that the order in which the two objects are appended is irrelevant, so logically a ':date' + ':time'  will result in the same as a '#:time' + ':date'.
=== ++(lhs: LocalTime, rhs: Date): LocalDateTime

You can append a date to a time (or localtime) object so as to provide a more precise value.


.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: |2003-10-01| ++ |23:57:59|,
b: |2003-10-01| ++ |23:57:59Z|
}

----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59",
"b": "2003-10-01T23:57:59Z"
}
----


Note that the order in which the two objects are appended is irrelevant, so logically a ':date' + ':time'  will result in the same as a '#:time' + ':date'.
=== ++(lhs: Date, rhs: Time): DateTime

You can append a date to a time (or localtime) object so as to provide a more precise value.


.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: |2003-10-01| ++ |23:57:59|,
b: |2003-10-01| ++ |23:57:59Z|
}

----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59",
"b": "2003-10-01T23:57:59Z"
}
----


Note that the order in which the two objects are appended is irrelevant, so logically a ':date' + ':time'  will result in the same as a '#:time' + ':date'.
=== ++(lhs: Time, rhs: Date): DateTime

You can append a date to a time (or localtime) object so as to provide a more precise value.


.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: |2003-10-01| ++ |23:57:59|,
b: |2003-10-01| ++ |23:57:59Z|
}

----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59",
"b": "2003-10-01T23:57:59Z"
}
----


Note that the order in which the two objects are appended is irrelevant, so logically a ':date' + ':time'  will result in the same as a '#:time' + ':date'.
=== ++(lhs: Date, rhs: TimeZone): DateTime

Appends a time zone to a date type value.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59-03:00"
}
----
=== ++(lhs: TimeZone, rhs: Date): DateTime

Appends a time zone to a date type value.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59-03:00"
}
----
=== ++(lhs: LocalDateTime, rhs: TimeZone): DateTime

Appends a time zone to a date type value.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59-03:00"
}
----
=== ++(lhs: TimeZone, rhs: LocalDateTime): DateTime

Appends a time zone to a date type value.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59-03:00"
}
----
=== ++(lhs: LocalTime, rhs: TimeZone): Time

Appends a time zone to a date type value.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59-03:00"
}
----
=== ++(lhs: TimeZone, rhs: LocalTime): Time

Appends a time zone to a date type value.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
a: |2003-10-01T23:57:59| ++ |-03:00|
----

.Output
[source,json,linenums]
----
{
"a": "2003-10-01T23:57:59-03:00"
}
----

== --

=== --(lhs: Array<S >, rhs: Array<Any>): Array<S >


Removes a set of elements from an array when an element in the base array matches one of the values in the substracted array. If multiple elements in the array match a value, they will all be removed.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
a: [0, 1, 1, 2] -- [1,2]
----

.Output
[source,json,linenums]
----
{
"a": [0],
}
----
=== --(lhs: Object, rhs: Object): Array<S >


== Abs

=== abs(rhs: Number): Number


Returns the absolute value of a number,

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: abs(-2),
b: abs(2.5),
c: abs(-3.4),
d: abs(3)
}
----

.Output
[source,json,linenums]
----
{
"a": 2,
"b": 2.5,
"c": 3.4,
"d": 3
}
----


== Avg

=== avg(rhs: Array<Number>): Number

Creates an average of all the values in an array and outputs a single number. The array must of course contain only numerical value in it.


.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: avg([1..1000]),
b: avg([1, 2, 3])
}
----

.Output
[source,json,linenums]
----
{
"a": 500.5,
"b": 2.0
}
----


== Camelize

=== camelize(rhs: String): String


Returns the provided string in camel case.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: camelize("customer"),
b: camelize("customer_first_name"),
c: camelize("customer name")
}
----

.Output
[source,json,linenums]
----
{
"a": "customer",
"b": "customerFirstName",
"c": "customer name"
}
----


== Capitalize

=== capitalize(rhs: String): String


Returns the provided string with every word starting with a capital letter and no underscores.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: capitalize("customer"),
b: capitalize("customer_first_name"),
c: capitalize("customer NAME")
}
----

.Output
[source,json,linenums]
----
{
"a": "Customer",
"b": "Customer First Name",
"c": "Customer Name"
}
----

== Ceil

=== ceil(rhs: Number): Number

Rounds a number upwards, returning the first full number above than the one provided.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---

{
a: ceil(1.5),
b: ceil(2.2),
c: ceil(3)
}
----

.Output
[source,json,linenums]
----
{
"a": 2,
"b": 3,
"c": 3
}
----

== Contains

=== contains(lhs: Array<T >, rhs: Any): Boolean

You can evaluate if any value in an array matches a given condition:

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
ContainsRequestedItem: payload.root.*order.*items contains "3"
----


.Input
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root>
<order>
<items>155</items>
</order>
<order>
<items>30</items>
</order>
<order>
<items>15</items>
</order>
<order>
<items>5</items>
</order>
<order>
<items>4</items>
<items>7</items>
</order>
<order>
<items>1</items>
<items>3</items>
</order>
<order>
null
</order>
</root>
----
.Output
[source,json,linenums]
----
{
"ContainsRequestedItem": true
}
----
=== contains(lhs: String, rhs: String): Boolean


You can also use contains to evaluate a substring from a larger string:

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
ContainsString: payload.root.mystring contains "me"
----

.Input
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root>
<mystring>some string</mystring>
</root>
----
.Output
[source,json,linenums]
----
{
"ContainsString": true
}
----
=== contains(lhs: String, rhs: Regex): Boolean

Instead of searching for a literal substring, you can also match it against a regular expression:


.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
ContainsString: payload.root.mystring contains /s[t|p]ring/`
----


.Input
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<root>
<mystring>A very long string</mystring>
</root>
----
.Output
[source,json,linenums]
----
{
"ContainsString": true
}
----


== Dasherize

=== dasherize(rhs: String): String


Returns the provided string with every word separated by a dash.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: dasherize("customer"),
b: dasherize("customer_first_name"),
c: dasherize("customer NAME")
}
----

.Output
[source,json,linenums]
----
{
"a": "customer",
"b": "customer-first-name",
"c": "customer-name"
}
----

== DistinctBy

=== distinctBy(lhs: Array<T >, rhs: (T , Number)=> R ): Array<T >

Returns only unique values from an array that may have duplicates.
The lambda is invoked with two parameters: *index* and *value*.
If these parameters are not defined, the index is defined by default as $$ and the value as $.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{

book : {
title : payload.title,
year: payload.year,
authors: payload.author distinctBy $
}
}
----


.Input
[source,json,linenums]
----
{
"title": "XQuery Kick Start",
"author": [
"James McGovern",
"Per Bothner",
"Kurt Cagle",
"James Linn",
"Kurt Cagle",
"Kurt Cagle",
"Kurt Cagle",
"Vaidyanathan Nagarajan"
],
"year":"2000"
}
----
.Output
[source,json,linenums]
----
{
"book": {
"title": "XQuery Kick Start",
"year": "2000",
"authors": [
"James McGovern",
"Per Bothner",
"Kurt Cagle",
"James Linn",
"Vaidyanathan Nagarajan"
]
}
}
----

=== distinctBy(lhs: Object<{K ? : V }>, rhs: (V , K )=> Object): Object


== EndsWith

=== endsWith(lhs: String, rhs: String): String

Returns true or false depending on if a string ends with a provided substring.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: "Mariano" endsWith "no",
b: "Mariano" endsWith "to"
}
----

.Output
[source,json,linenums]
----
{
"a": true,
"b": false
}
----


== Fail

=== fail(message: String): T

Fails with the specified message

== FailIf

=== failIf(value: T , evaluator: (value: T )=> Boolean): T

Fails with the specified message if the evaluator returns true

== Filter

=== filter(lhs: Array<T >, rhs: (T , Number)=> Boolean): Array<T >


Returns an array that only contains those that pass the criteria specified in the lambda. The lambda is invoked with two parameters: *index* and the *value*.
If these parameters are not named, the index is defined by default as *$$* and the value as *$*.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
biggerThanTwo: [0, 1, 2, 3, 4, 5] filter $ > 2
}
----

.Output
[source,json,linenums]
----
{
"biggerThanTwo": [3,4,5]
}
----

=== filter(lhs: Object<{K ? : V }>, rhs: (V , K )=> Boolean): Object


== Find

=== find(lhs: Array<T >, rhs: Any): Array<T >

=== find(lhs: String, rhs: Regex): Array<Array<Number>>

=== find(lhs: String, rhs: String): Array<Number>

Given a string, it returns the index position within the string at which a match was matched. If found in multiple parts of the string, it returns an array with the various idex positions at which it was found. You can either look for a simple string or a regular expression.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: "aabccde" find /(a).(b)(c.)d/,
b: "aabccdbce" find "a",
c: "aabccdbce" find "bc"
}
----


.Output
[source,json,linenums]
----
{
"a": [[0,0,2,3]],
"b": [0,1],
"c": [2,6]
}
----


== Flatten

=== flatten(rhs: Array<Array<T > | Q >): Array<T  | Q >


If you have an array of arrays, this function can flatten it into a single simple array.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
flatten payload
----


.Input
[source,json,linenums]
----
[
[3,5],
[9,5],
[154,0.3]
]
----
.Output
[source,json,linenums]
----
[
3,
5,
9,
5,
154,
0.3
]
----


== Floor

=== floor(rhs: Number): Number

Rounds a number downwards, returning the first full number below than the one provided.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: floor(1.5),
b: floor(2.2),
c: floor(3)
}
----

.Output
[source,json,linenums]
----
{
"a": 1,
"b": 2,
"c": 3
}
----

== GroupBy

=== groupBy(lhs: Array<T >, rhs: (T , Number)=> R ): Object<{R : Array<T >}>

Partitions an array into a Object that contains Arrays, according to the discriminator lambda you define.
The lambda is invoked with two parameters: *index* and the *value*.
If these parameters are not named, the index is defined by default as *$$* and the value as *$*.


.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
"language": payload.langs groupBy $.language
----


.Input
[source,json,linenums]
----
{
"langs": [
{
"name": "Foo",
"language": "Java"
},
{
"name": "Bar",
"language": "Scala"
},
{
"name": "FooBar",
"language": "Java"
}
]
}
----
.Output
[source,json,linenums]
----
{
"language": {
"Scala": [
{"name":"Bar", "language":"Scala"}
],
"Java": [
{"name":"Foo", "language":"Java"},
{"name":"FooBar", "language":"Java"}
]
}
}
----

=== groupBy(lhs: Object<{K ? : V }>, rhs: (V , K )=> R ): Object<{R : Array<T >}>


== IsBlank

=== isBlank(value: String): Boolean

Returns true is the characters are only whitespaces.
.Transform
[source,DataWeave,linenums]
----
$dw 1.0
%output application/json
---
{
empty: isBlank(""),
withSpaces: isBlank("      "),
withText: isBlank(" 1223")
}
----

.Output
[source,Json,linenums]
----
{
"empty": true,
"withSpaces": true,
"withText": false
}
----

== IsDecimal

=== isDecimal(rhs: Number): Boolean

Returns true is the number has decimals.
.Transform
[source,DataWeave,linenums]
----
$dw 1.0
%output application/json
---
{
decimal: isDecimal(1.1),
integer: isDecimal(1)
}
----

.Output
[source,Json,linenums]
----
{
"decimal": true,
"integer": false
}
----

== IsEmpty

=== isEmpty(rhs: Array): Boolean

Returns wether an Array is empty or not

.Transform
[source,DataWeave,linenums]
----
$dw 1.0
%output application/json
---
{
empty: isEmpty([]),
nonEmpty: isEmpty([1])
}
----

.Output
[source,Json,linenums]
----
{
"empty": true,
"nonEmpty": false
}
----
=== isEmpty(rhs: String): Boolean

Returns wether a String is empty or not

.Transform
[source,DataWeave,linenums]
----
$dw 1.0
%output application/json
---
{
empty: isEmpty(""),
nonEmpty: isEmpty("DataWeave")
}
----

.Output
[source,Json,linenums]
----
{
"empty": true,
"nonEmpty": false
}
----
=== isEmpty(rhs: Object): Boolean

Returns wether an Object is empty or not

.Transform
[source,DataWeave,linenums]
----
$dw 1.0
%output application/json
---
{
empty: isEmpty({}),
nonEmpty: isEmpty({name: "DataWeave"})
}
----

.Output
[source,Json,linenums]
----
{
"empty": true,
"nonEmpty": false
}
----

== IsEven

=== isEven(n: Number): Boolean

Returns true if the specified number is Even

== IsInteger

=== isInteger(rhs: Number): Boolean

Returns true is the number doesn't have decimals.
.Transform
[source,DataWeave,linenums]
----
$dw 1.0
%output application/json
---
{
decimal: isInteger(1.1),
integer: isInteger(1)
}
----

.Output
[source,Json,linenums]
----
{
"decimal": false,
"integer": true
}
----

== IsLeapYear

=== isLeapYear(dateTime: DateTime): Boolean

Returns true is the year of the specified DateTime is leap
=== isLeapYear(date: Date): Boolean

Returns true is the year of the specified Date is leap
=== isLeapYear(rhs: LocalDateTime): Boolean

Returns true is the year of the specified LocalDateTime is leap

== IsOdd

=== isOdd(n: Number): Boolean

Returns true if the specified number is Odd

== JoinBy

=== joinBy(lhs: Array, rhs: String): String


Merges an array into a single string value, using the provided string as a separator between elements.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
aa: ["a","b","c"] joinBy "-"
----

.Output
[source,json,linenums]
----
{
"aa": "a-b-c"
}
----

== Log

=== log(prefix: String, value: T ): T

Logs the specified `value` with the given `prefix` and returns the `value`. +
It is a identity function that as side effect log it out. +
Example:
[source,DataWeave,linenums]
----
%input payload application/json
%output application/xml
---
{ age: log("My Age", payload.age) }
----
Input:
[source,json,linenums]
----
{ "age" : 33 }
----
This will print out: `My Age - 33`
Output:
[source,xml,linenums]
----
<age>33</age>
----

== Lower

=== lower(rhs: String): String

Returns the provided string in lowercase characters.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
name: lower("MULESOFT")
}
----

.Output
[source,json,linenums]
----
{
"name": mulesoft
}
----


== Map

=== map(lhs: Array<T >, rhs: (T , Number)=> R ): Array<R >


Returns an array that is the result of applying a transformation function (lambda) to each of the elements.
The lambda is invoked with two parameters: *index* and the *value*.
If these parameters are not named, the index is defined by default as *$$* and the value as *$*.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
users: ["john", "peter", "matt"] map  upper($)
----

.Output
[source,json,linenums]
----
{
"users": [
"JOHN",
"PETER",
"MATT"
]
}
----

In the following example, custom names are defined for the index and value parameters of the map operation, and then both are used to construct the returned value.
In this case, value is defined as *firstName* and its index in the array is defined as *position*.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
users: ["john", "peter", "matt"] map ((firstName, position) -> position ++ ":" ++ upper firstName)
----

.Output
[source,json,linenums]
----
{
"users": [
"0:JOHN",
"1:PETER",
"2:MATT"
]
}
----

== MapObject

=== mapObject(lhs: Object<{K ? : V }>, rhs: (V , K )=> Object): Object

Similar to Map, but instead of processing only the values of an object, it processes both keys and values as a tuple. Also instead of returning an array with the results of processing these values through the lambda, it returns an object, which consists of a list of the key:value pairs that result from processing both key and value of the object through the lambda.

The lambda is invoked with two parameters: *key* and the *value*.
If these parameters are not named, the key is defined by default as *$$* and the value as *$*.

.Transform
[source,DataWeave,linenums]
----
%dw 1.0
%output application/json
%var conversionRate=13.45
---
priceList: payload.prices mapObject (
'$$':{
dollars: $,
localCurrency: $ * conversionRate
}
)
----


.Input
[source,xml,linenums]
----
<prices>
<basic>9.99</basic>
<premium>53</premium>
<vip>398.99</vip>
</prices>
----

.Output
[source,json,linenums]
----
{
"priceList": {
"basic": {
"dollars": "9.99",
"localCurrency": 134.3655
},
"premium": {
"dollars": "53",
"localCurrency": 712.85
},
"vip": {
"dollars": "398.99",
"localCurrency": 5366.4155
}
}
}
----


[TIP]
Note that when you use a parameter to populate one of the keys of your output, as with the case of $$ in this example, you must either enclose it in quote marks or brackets. '$$' or ($$) are both equally valid.

In the example above, as key and value are not defined, they're identified by the placeholders *$$* and *$*.
For each key:value pair in the input, the key is preserved and the value becomes an object with two properties:
one of these is the original value, the other is the result of multiplying this value by a constant that is defined as a directive in the header.

The mapping below performs exactly the same transform, but it defines custom names for the properties of the operation, instead of using $ and $$. Here, 'category' is defined as referring to the original key in the object, and 'money' to the value in that key.

.Transform
[source,DataWeave,linenums]
----
%dw 1.0
%output application/json
%var conversionRate=13.45
---
priceList: payload.prices mapObject ((money, category) ->
'$category':{
dollars: money,
localCurrency: money * conversionRate
}
)
----

[TIP]
Note that when you use a parameter to populate one of the keys of your output, as with the case of *category* in this example, you must either enclose it in brackets or enclose it in quote marks adding a $ to it, otherwise the name of the property is taken as a literal string. '$category' or (category) are both equally valid.

== Match

=== match(lhs: String, rhs: Regex): Array<String>

Match a string against a regular expression. Match returns an array that contains the entire matching expression, followed by all of the capture groups that match the provided regex.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
hello: "anniepoint@mulesoft.com" match /([a-z]*)@([a-z]*).com/
----

.Output
[source,json,linenums]
----
{
"hello": [
"anniepoint@mulesoft.com",
"anniepoint",
"mulesoft"
]
}
----

In the example above, we see that the search regular expression describes an email address. It contains two capture groups, what's before and what's after the @. The result is an array of three elements: the first is the whole email address, the second matches one of the capture groups, the third matches the other one.


== Matches

=== matches(lhs: String, rhs: Regex): Boolean

Matches a string against a regular expression, and returns *true* or *false*.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
b: "admin123" matches /(\d+)/
----

.Output
[source,json,linenums]
----
{
"b": false
}
----

[TIP]
For more advanced use cases where you need to output or conditionally process the matched value, see link:/mule-user-guide/v/3.8/dataweave-language-introduction#pattern-matching[Pattern Matching].


== Max

=== max(rhs: Array<Number>): Number

Returns the highest number in an array or object.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: max([1..1000]),
b: max([1, 2, 3]),
d: max([1.5, 2.5, 3.5])
}
----
.Output
[source,json,linenums]
----
{
"a": 1000,
"b": 3,
"d": 3.5
}
----

== Min

=== min(rhs: Array<Number>): Number

Returns the lowest number in an array or object.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: min([1..1000]),
b: min([1, 2, 3]),
d: min([1.5, 2.5, 3.5])
}
----

.Output
[source,json,linenums]
----
{
"a": 1,
"b": 1,
"d": 1.5
}
----

== Mod

=== mod(lhs: Number, rhs: Number): Number


Returns the remainder after division of the first number by the second one

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: 3 mod 2,
b: 4 mod 2,
c: 2.2 mod 2
}
----

.Output
[source,json,linenums]
----
{
"a": 1,
"b": 0,
"c": 0.2
}
----

== Native

=== native(identifier: String): T

Function used to load a native function using the specified identifier.

== Now

=== now(): DateTime

Returns a datetime object with the current date and time.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
current_time: now
}
----

.Output
[source,json,linenums]
----
{
"current_time": "2016-10-20T17:15:06.196Z"
}
----

== OrderBy

=== orderBy(lhs: O , rhs: (V , K )=> R ): O


Returns the provided array (or object) ordered according to the value returned by the lambda. The lambda is invoked with two parameters: *index* and the *value*.
If these parameters are not named, the index is defined by default as *$$* and the value as *$*.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
orderByLetter: [{ letter: "d" }, { letter: "e" }, { letter: "c" }, { letter: "a" }, { letter: "b" }] orderBy $.letter
----

.Output
[source,json,linenums]
----
{
"orderByLetter": [
{
"letter": "a"
},
{
"letter": "b"
},
{
"letter": "c"
},
{
"letter": "d"
},
{
"letter": "e"
}
]
}
----

[TIP]
====
The *orderBy* function doesn't have an option to order in descending order instead of ascending. What you can do in these cases is simply invert the order of the resulting array.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
orderDescending: ([3,8,1] orderBy $)[-1..0]
----

.Output
[source,json,linenums]
----
{ "orderDescending": [8,3,1] }
----

====
=== orderBy(lhs: Array<T >, rhs: (T , Number)=> R ): Array<T >


== Ordinalize

=== ordinalize(rhs: String): String

Returns the provided numbers set as ordinals.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: ordinalize(1),
b: ordinalize(8),
c: ordinalize(103)
}
----

.Output
[source,json,linenums]
----
{
"a": "1st",
"b": "8th",
"c": "103rd"
}
----

== Pluck

=== pluck(lhs: Object<{K ? : V }>, rhs: (V , K )=> R ): Array<R >

Pluck is useful for mapping an object into an array. Pluck is an alternate mapping mechanism to mapObject.
Like mapObject, pluck executes a lambda over every key:value pair in its processed object as a tuple,
but instead of returning an object, it returns an array, which may be built from either the values or the keys in the object.

The lambda is invoked with two parameters: *key* and the *value*.
If these parameters are not named, the key is defined by default as *$$* and the value as *$*.

.Transform
[source,DataWeave,linenums]
----
%dw 1.0
%output application/json
---
result: {
keys: payload.prices pluck $$,
values: payload.prices pluck $
}
----

.Input
[source,xml,linenums]
----
<prices>
<basic>9.99</basic>
<premium>53</premium>
<vip>398.99</vip>
</prices>
----
.Output
[source,json,linenums]
----
{
"result": {
"keys": [
"basic",
"premium",
"vip"
],
"values": [
"9.99",
"53",
"398.99"
]
}
}
----

== Pluralize

=== pluralize(rhs: String): String

Returns the provided string transformed into its plural form.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: pluralize("box"),
b: pluralize("wife"),
c: pluralize("foot")
}
----

.Output
[source,json,linenums]
----
{
"a": "boxes",
"b": "wives",
"c": "feet"
}
----

== Pow

=== pow(lhs: Number, rhs: Number): Number


Returns the result of the first number `a` to the power of the number following the `pow` operator.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: 2 pow 3,
b: 3 pow 2,
c: 7 pow 3
}
----

.Output
[source,json,linenums]
----
{
"a": 8,
"b": 9,
"c": 343
}
----

== Random

=== random(): Number

Returns a random value

== Read

=== read(stringToParse: String, contentType: String, readerProperties: Object): T

Reads the content using the specified contentType and readerProperties
Example:
[source,DataWeave,linenums]
----
%output application/xml
---
read('{"name":"DataWeave"}', "application/json")
----
Output:
[source,xml,linenums]
----
<name>DataWeave</name>
----

== ReadUrl

=== readUrl(url: String, contentType: String, readerProperties: Object): T


== Reduce

=== reduce(lhs: Array<T >, rhs: (T , T )=> T ): T


Apply a reduction to the array using just two parameters:
the accumulator (*$$*), and the value (*$*).
By default, the accumulator starts at the first value of the array.

.Transform
[source,DataWeave,linenums]
----
%dw 1.0
%output application/json
---
sum: [0, 1, 2, 3, 4, 5] reduce $$ + $
----

.Output
[source,json,linenums]
----
{
"sum": 15
}
----

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
concat: ["a", "b", "c", "d"] reduce $$ ++ $
----

.Output
[source,json,linenums]
----
{
"concat": "abcd"
}
----

In some cases, you may not want to use the first element of the array as an accumulator. To set the accumulator to something else, you must define this in a lambda.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
concat: ["a", "b", "c", "d"] reduce ((val, acc = "z") -> acc ++ val)
----

.Output
[source,json,linenums]
----
{
"concat": "zabcd"
}
----
=== reduce(lhs: Array<T >, rhs: (T , A )=> A ): A


== Replace

=== replace(lhs: String, rhs: Regex): ((Array<String>, Number)=> String)=> String

Replaces a section of a string for another, in accordance to a regular expression, and returns a modified string.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
b: "admin123" replace /(\d+)/ with "ID"
----

.Output
[source,json,linenums]
----
{
"b": "adminID"
}
----


== Round

=== round(rhs: Number): Number

Rounds the value of a number to the nearest integer

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: round(1.2),
b: round(4.6),
c: round(3.5)
}
----

.Output
[source,json,linenums]
----
{
"a": 1,
"b": 5,
"c": 4
}
----

== Scan

=== scan(lhs: String, rhs: Regex): Array<Array<String>>


Returns an array with all of the matches in the given string. Each match is returned as an array that contains the complete match, as well as any capture groups there may be in your regular expression.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
hello: "anniepoint@mulesoft.com,max@mulesoft.com" scan /([a-z]*)@([a-z]*).com/
----

.Output
[source,json,linenums]
----
{
"hello": [
[
"anniepoint@mulesoft.com",
"anniepoint",
"mulesoft"
],
[
"max@mulesoft.com",
"max",
"mulesoft"
]
]
}
----

In the example above, we see that the search regular expression describes an email address. It contains two capture groups, what's before and what's after the @. The result is an array with two matches, as there are two email addresses in the input string. Each of these matches is an array of three elements, the first is the whole email address, the second matches one of the capture groups, the third matches the other one.

== Singularize

=== singularize(rhs: String): String

Returns the provided string transformed into its singular form.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: singularize("boxes"),
b: singularize("wives"),
c: singularize("feet")
}
----

.Output
[source,json,linenums]
----
{
"a": "box",
"b": "wife",
"c": "foot"
}
----

== SizeOf

=== sizeOf(rhs: Array<T >): Number


Returns the number of elements in an array (or anything that can be converted to an array such as a string).

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
arraySize: sizeOf [1,2,3]
}
----

.Output
[source,json,linenums]
----
{
"arraySize": 3
}
----
=== sizeOf(rhs: Object): Number


Returns the number of elements in an object .

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
objectSize: sizeOf {a:1,b:2}
}
----

.Output
[source,json,linenums]
----
{
"objectSize": 2
}
----
=== sizeOf(rhs: String): Number


Returns the number of characters in an string

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
textSize: sizeOf "MuleSoft"
}
----

.Output
[source,json,linenums]
----
{
"textSize": 8
}
----

== SplitBy

=== splitBy(lhs: String, rhs: Regex): Array<String>


Performs the opposite operation as Join By. It splits a string into an array of separate elements, looking for instances of the provided string and using it as a separator.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
split: "a-b-c" splitBy /-/
----

.Output
[source,json,linenums]
----
{
"split": ["a","b","c"]
}
----
=== splitBy(lhs: String, rhs: String): Array<String>


Performs the opposite operation as Join By. It splits a string into an array of separate elements, looking for instances of the provided string and using it as a separator.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
split: "a-b-c" splitBy "-"
----

.Output
[source,json,linenums]
----
{
"split": ["a","b","c"]
}
----

== Sqrt

=== sqrt(rhs: Number): Number

Returns the square root of the provided number

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: sqrt(4),
b: sqrt(25),
c: sqrt(100)
}
----

.Output
[source,json,linenums]
----
{
"a": 2.0,
"b": 5.0,
"c": 10.0
}
----

== StartsWith

=== startsWith(lhs: String, rhs: String): Boolean

== Starts With

.(':string', ':string') => ':boolean'

Returns true or false depending on if a string starts with a provided substring.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: "Mariano" startsWith "Mar",
b: "Mariano" startsWith "Em"
}
----

.Output
[source,json,linenums]
----
{
"a": true,
"b": false
}
----

== Sum

=== sum(rhs: Array<Number>): Number


== To

=== to(from: Number, to: Number): Range

Returns a range with the specified boundries. Upper boundry is inclusive.

== Trim

=== trim(rhs: String): String

Removes any excess spaces at the start and end of a string.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
"a": trim("   my long text     ")
}
----

.Output
[source,json,linenums]
----
{
"a": "my long text"
}
----

== TypeOf

=== typeOf(rhs: T ): Type<T >

Returns the type of a value

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
typeOf("A Text")
----

.Output
[source,json,linenums]
----
"String"
----

== Underscore

=== underscore(rhs: String): String

Returns the provided string with every word separated by an underscore.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: underscore("customer"),
b: underscore("customer-first-name"),
c: underscore("customer NAME")
}
----

.Output
[source,json,linenums]
----
{
"a": "customer",
"b": "customer_first_name",
"c": "customer_NAME"
}
----

== Unzip

=== unzip(rhs: Array<Array<T >>): Array<Array<T >>

Performs the opposite function of <<zip arrays>>, that is: given a single array where each index contains an array with two elements, it outputs two separate arrays, each with one of the elements of the pair. This can also be scaled up, if the indexes in the provided array contain arrays with more than two elements, the output will contain as many arrays as there are elements for each index.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: unzip([[0,"a"],[1,"b"],[2,"c"],[3,"d"]]),
b: unzip([ [0,"a"], [1,"a"], [2,"a"], [3,"a"]]),
c: unzip([ [0,"a"], [1,"a","foo"], [2], [3,"a"]])
}
----

.Output
[source,json,linenums]
----
{
"a":[
[0, 1, 2, 3],
["a", "b", "c", "d"]
],
"b": [
[0,1,2,3],
["a","a","a","a"]
],
"c": [
[0,1,2,3]
]
}
----

Note even though example b can be considered the inverse function to the example b in <<zip array>>, the result is not analogous, since it returns an array of repeated elements instead of a single element. Also note that in example c, since the number of elements in each component of the original array is not consistent, the output only creates as many full arrays as it can, in this case just one.


== Upper

=== upper(rhs: String): String


Returns the provided string in uppercase characters.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
name: upper("mulesoft")
}
----

.Output
[source,json,linenums]
----
{
"name": MULESOFT
}
----

== Wait

=== wait(value: T , timeout: Number): T

Stops the execution for the specified timeout (in milliseconds)

== With

=== with(toBeReplaced: ((Array<String>, Number)=> String)=> String, callback: (Array<String>, Number)=> String): String

Used with the replace applies the specified function

== Write

=== write(value: Any, contentType: String, writerProperties: Object): Any


== Zip

=== zip(lhs: Array<T >, rhs: Array<X >): Array<Array<T  | X >>


Given two or more separate lists, the zip function can be used to merge them together into a single list of consecutive n-tuples.  Imagine two input lists each being one side of a zipper: similar to the interlocking teeth of a zipper, the zip function interdigitates each element from each input list, one element at a time.

.Transform
[source,DataWeave, linenums]
----
%dw 1.0
%output application/json
---
{
a: [0, 1, 2, 3] zip ["a", "b", "c", "d"],
b: [0, 1, 2, 3] zip "a",
c: [0, 1, 2, 3] zip ["a", "b"]
}
----

.Output
[source,json,linenums]
----
{
"a": [
[0,"a"],
[1,"b"],
[2,"c"],
[3,"d"]
],
"b": [
[0,"a"],
[1,"a"],
[2,"a"],
[3,"a"]
],
"c": [
[0,"a"],
[1,"b"]
]
}
----

Note that in example b, since only one element was provided in the second array, it was matched with every element of the first array. Also note that in example c, since the second array was shorter than the first, the output was only as long as the shortest of the two.


Here is another example of the zip function with more than two input lists.

.Transform
[source,DataWeave, linenums]
----------------------------------------------------------------------
%dw 1.0
%output application/json
---
payload.list1 zip payload.list2 zip payload.list3
----------------------------------------------------------------------

.Input
[source,json,linenums]
----------------------------------------------------------------------
{
"list1": ["a", "b", "c", "d"],
"list2": [1, 2, 3],
"list3": ["aa", "bb", "cc", "dd"],
"list4": [["a", "b", "c"], [1, 2, 3, 4], ["aa", "bb", "cc", "dd"]]
}
----------------------------------------------------------------------
.Output
[source,json,linenums]
----------------------------------------------------------------------
[
[
"a",
1,
"aa"
],
[
"b",
2,
"bb"
],
[
"c",
3,
"cc"
]
]
----------------------------------------------------------------------



== Iterator = Array

This type is based in the link:https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html[iterator Java class]. The iterator contains a collection, and includes methods to iterate through and filter it.

[NOTE]
Just like the Java class, the iterator is designed to be consumed only once. For example, if you then pass this value to a link:/mule-user-guide/v/3.8/logger-component-reference[logger] would result in consuming it and it would no longer be readable to further elements in the flow.


== Enum = String

In order to put an enum value in a java.util.Map, the DataWeave java module defines a custom type called Enum.
It allows you to specify that a given string should be handled as the name of a specified Enum type.
It should always be used with the class property with the java class name of the enum.%type Enum = String
== CData = String


XML defines a custom type named :cdata, it extends from string and is used to identify a CDATA XML block.
It can be used to tell the writer to wrap the content inside CDATA or to check if the input string arrives inside a CDATA block. `:cdata` inherits from the type `:string`.

.Transformπ
[source,DataWeave, linenums]
----------------------------------------------------------------------
%dw 1.0
%output application/xml
---
{
users:
{
user : "Mariano" as :cdata,
age : 31 as :cdata
}
}
----------------------------------------------------------------------

.Output
[source,xml,linenums]
----------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<users>
<user><![CDATA[Mariano]]></user>
<age><![CDATA[31]]></age>
</users>
----------------------------------------------------------------------
