= Example: Renaming JSON Keys
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

This example renames some keys in a JSON object, while retaining the names of all others in the output.

It uses these functions:

* `mapObject` to go through the `key:value` pairs in a JSON object.
* `when` by itself to determine when to change the name of a key.
* `when` with `and` to retain the name of all keys except the two with new names.
* `as` to coerce the type of the keys into a String.

.DataWeave
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
payload.flights map (flight) -> {
(flight mapObject (value, key) -> {
        (emptySeats: value) when key as String == 'availableSeats',
        (airline: value) when key as String == 'airlineName',
        ((key):value) when key as String !='availableSeats' and key as String != 'airlineName'
    })
}
----

.Input
[source, json, linenums]
----
{
  "flights":[
  {
  "availableSeats":45,
  "airlineName":"Ryan Air",
  "aircraftBrand":"Boeing",
  "aircraftType":"737",
  "departureDate":"12/14/2017",
  "origin":"BCN",
  "destination":"FCO"
  },
  {
  "availableSeats":15,
  "airlineName":"Ryan Air",
  "aircraftBrand":"Boeing",
  "aircraftType":"747",
  "departureDate":"08/03/2017",
  "origin":"FCO",
  "destination":"DFW"
  }]
}
----


.Output
[source, json, linenums]
----
[
  {
    "emptySeats": 45,
    "airline": "Ryan Air",
    "aircraftBrand": "Boeing",
    "aircraftType": "737",
    "departureDate": "12/14/2017",
    "origin": "BCN",
    "destination": "FCO"
  },
  {
    "emptySeats": 15,
    "airline": "Ryan Air",
    "aircraftBrand": "Boeing",
    "aircraftType": "747",
    "departureDate": "08/03/2017",
    "origin": "FCO",
    "destination": "DFW"
  }
]
----

== Related Examples



* link:/mule-user-guide/v/4.0/dataweave-cookbook-output-a-field-when-present[Outputting a Field When Present]

* link:/mule-user-guide/v/4.0/dataweave-cookbook-map-based-on-an-external-definition[Dynamic Mapping Based On a Definition]

* link:/mule-user-guide/v/4.0/dataweave-cookbook-pass-functions-as-arguments[Passing Functions as Arguments]


== See Also


* link:/mule-user-guide/v/4.0/dw-functions-core[DataWeave Core Functions]

* link:/mule-user-guide/v/4.0/dataweave-selectors[DataWeave Selectors]

* link:/mule-user-guide/v/4.0/dataweave-cookbook[DataWeave Cookbook]
