= About DataWeave Variables
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

[[dataweave_variables]]
In DataWeave, you can initialize and use both global and local variables in DataWeave scripts.

* Global variables are initialized in the header of the DataWeave script and can be referenced by name from anywhere in the body of a DataWeave script.
+
The header of a DataWeave script accepts a `var` directive that initializes a variable, for example: `var language='Espa単ol'`. You can declare multiple global variables on separate lines in the header.
+
* Local variables are initialized in the body of the DataWeave script and can be referenced by name only from within the scope of the expression where they are initialized.
+
The syntax for initializing a local variable looks like this:
`using (<variable-name> = <expression>)`
+
It must use the keyword `using`.
+
Within parentheses, you can define one or more local variables, for example: `using (firstName='Annie', lastName='Point')`

Note that DataWeave variables cannot be reassigned. They are also distinct from variables that are part of the Mule message (such as target variables). DataWeave variables do not persist beyond the scope of the script in which they are initialized.

[[example_global_variable]]
=== Example: Global DataWeave Variables

This example initializes the `language` variable in the header and inserts the constant value `Espa単ol` in the output `language` element.

.Transform
[source, dataweave, linenums]
----
%dw 2.0
output application/xml
var language='Espa単ol'
---
{
  document: {
    language: language,
    text: "Hola mundo"
  }
}
----

.Output
[source,xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<document>
  <language>Espa単ol</language>
  <text>Hola Mundo</text>
</document>
----

[[example_local_variable]]
=== Examples: Local DataWeave Variables

To initialize local variables, you can use either literal expressions, variable reference expressions, or functional expressions. These expressions can reference any other local variables within their scope or any input or global variables.

You can only reference a local variable by name from within the scope of the expression that initializes it. The declaration can be prepended to any literal expression. The literal delimits the scope of the variable, so you cannot reference any variable outside of its scope.

The examples that follow show initialization of local variables used in literal expressions. The syntax is the same

.Example: Scoped to Simple Value
[source, dataweave, linenums]
----
%dw 2.0
output application/json
---
using (x = 2) 3 + x
----

The result is `5`.

.Example: Scoped to an Array Literal
[source, dataweave, linenums]
----
%dw 2.0
output application/json
---
using (x = 2) [1, x, 3]
----

The result is `[ 1, 2, 3]`

.Example: Scoped to Object literal
Here, the reference to `user` is valid because it is within the object `person`.

[source, dataweave, linenums]
----
%dw 2.0
output application/xml
---
{
  person: using (user='Greg', gender='male') {
    name: user,
    gender: gender
  }
}
----

.Output
[source, xml, linenums]
----
<?xml version='1.0' encoding='UTF-8'?>
<person>
  <name>Greg</name>
  <gender>male</gender>
</person>
----

.Example: Invalid Reference that is Outside the Scope
This example produces an error because `gender` is referenced from outside the scope of `person`, where `gender` is initialized.

[source, dataweave, linenums]
----
%dw 2.0
output application/xml
---
entry: using (firstName = "Annie", lastName = "Point") {
  person: using (user = firstName, gender = "male") {
    name: user,
    gender: gender
  },
  sn: lastName,
  gen: gender
}
----

The invalid example returns this error:
`Unable to resolve reference of gender.`

.Example: Scoped to a Global Variable and to a Function
[source, dataweave, linenums]
----
%dw 2.0
output application/json
var myGlobalVar = 2
---
{
  examples: {
    // x is a global variable that is referenced by a literal expression.
    'ex_a': using (x = myGlobalVar) 3 + x,
    // y is an expression that coerces a Boolean into a string,  then referenced by the upper function.
    'ex_b': using (y = true as String) upper(y ++ ' as a string'),
    // z is a function expression that is referenced by a literal object.
    'ex_c': using (z = ["a", "b", "c"] map upper($)) {mapping : z}
  }
}
----

.Output
[source, json, linenums]
----
{
  "examples": {
    "ex_a": 5,
    "ex_b": "TRUE AS A STRING",
    "ex_c": {
      "mapping": [
        "A",
        "B",
        "C"
      ]
    }
  }
}
----
