= Example: Outputting Self-closing XML Tags
:keywords: studio, anypoint, transform, transformer, format, xml, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

For XML, DataWeave by default outputs every value within an opening and closing tag, even if the tag contains no value (for example, `<element2></element2>`).

To output empty tags as a self-closing XML element (for example, `<element2/>`), you can set the `inlineCloseOn="empty"` output directive in the DataWeave header.

.DataWeave
[source,Dataweave,linenums]
----
%dw 1.0
%output application/xml inlineCloseOn="empty"
---
payload
----

.Input XML
[source,xml,linenums]
----
<parent>
  <child1>15</child1>
  <child2></child2>
  <child3>8</child3>
  <child4></child4>
</parent>
----

.Output XML
[source,xml,linenums]
----
<?xml version='1.0' encoding='US-ASCII'?>
<parentElement>
  <element1>15</element1>
  <element2/>
  <element3>8</element3>
  <element4/>
</parentElement>
----

////
NOT CLEAR WHY THIS CONTENT WAS ON THIS PAGE:

1. inlineCloseOn is not valid for JSON.
2. We're talking about XML tags here, not JSON.

PROBABLY CHOPPED UP EXAMPLE INCORRECTLY.
TODO: NEED TO FIND REST OF CONTENT AND FIX.

removeAttribute(payload, "password")
----

{
  "parentchild":{

    "child":{},
    "child2":{},
    "child3":{}
  }
}
----
////

== See Also

link:/mule-user-guide/v/4.0/dataweave-types[DataWeave Value Types]

link:/mule-user-guide/v/4.0/dataweave-operators[DataWeave Operators]

link:/mule-user-guide/v/4.0/dataweave-selectors[DataWeave Selectors]

link:/mule-user-guide/v/4.0/dataweave-examples[DataWeave Examples]
