= About DataWeave Scripts
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

DataWeave scripts are divided into two sections divided by a triple-dash delimiter (`---`):

* Header: Contains directives to apply to the expression in the body. The example shows the most common directives.
* Body: Contains an expression for generating the output structure.

.Example: Simple DataWeave Script
[source, dataweave, linenums]
----
%dw 2.0
output application/xml
---
{
  user: {
    name: payload.user_name,
    lastName: payload.user_lastName
  }
}
----

.dwl File
Note that in addition to specifying DataWeave scripts in the Transform and other components, you can also specify the scripts in a `.dwl` file. In Studio projects, your script files are stored in `src/main/resources`.

== DataWeave Header

This example shows all the header directives.

.DataWeave Script
[source, dataweave, linenums]
----
%dw 2.0
import * from dw::core::Arrays
var myVar=13.15
fun toUser(obj) = {
  firstName: obj.field1,
  lastName: obj.field2
}
ns msg http://www.mulesoft.com/anypoint/SOA/message/v1.0`
output application/xml
---
/*
 * Body here.
 * /
----

* `%dw`: DataWeave version is optional. Default is `2.0`.
+
Example: `%dw 2.0`
+
* `output`: Commonly used directive that specifies the mime type that the script outputs.
+
Example: `output application/xml`
+
Valid values: link:dataweave-formats[Mime Types that are Supported by DataWeave].
+
Default: If no output is specified, the default output is based on an algorithm that examines the inputs (payload, variables, and so on) used in the script:
+
. If the there is no input, the default is `output application/java`.
. If all inputs are the same mime type, the script outputs to the same mime type. For example, if all input is `application/json`, then it outputs `output application/json`.
. If the mime types of the inputs differ, and no output is specified,  the script throws an exception so that you know to specify an output mime type.
+
Note that only one output type can be specified. See <<dataweave-formats, DataWeave Formats>> for a list of valid mime types.
+
* `import`: For importing a DataWeave function module. See link:dw-functions[DataWeave Functions].
* `var`: Global variables for defining constants that you can reference throughout the body of the DataWeave script:
+
.Example
[source, dataweave, linenums]
----
%dw 2.0
var conversionRate=13.15
output application/json
---
{
 price_dollars: payload.price,
 price_localCurrency: payload.price * conversionRate
}
----
+
* `ns`: Namespaces, used to import a namespace.
+
Example: `ns msg http://www.mulesoft.com/anypoint/SOA/message/v1.0`
+
* `fun`: For creating custom functions that can be called from within the body of the script.
+
.Example
[source, dataweave, linenums]
----
%dw 2.0
output application/json
fun toUser = (user) -> {firstName: user.name, lastName: user.lastName}
---
{
  user: toUser(payload)
}
----

////
TODO
//* `type`: TODO
// TODO: type myType
////

== DataWeave Body

The expression in the body acts on the input data to produce output in the mime type that is specified or based on the algorithm used to determine the mime type automatically.




////
Note that the output of a DataWeave expression can include these data types:

* Simple Values: Strings and numbers, for example: `Some String`, `18`.
* Arrays: A sequence of comma separated values, for example: `1, 2, 3`. The values can be any supported data type.
* Objects: A collection of key-value pairs, for example: `{"key": "some value"}`. The values can be any supported data type.
////

== DataWeave Comments
Comments that use a Java-like syntax are also accepted by DataWeave.
----
// My single-line comment here.

/*
 * My multi-line comment here.
 */
----

////
== See Also
////
