= DataWeave 2.0 Syntax Changes
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping


DataWeave 2.0 (packaged as part of Mule runtime 4.0) introduces the following syntax changes over previous versions:

* Removed automatic coercion from object to array (this implies for example, that the map function no longer works over an Object)
* Updated version header to `%dw 2.0`
* Removed `%` from all other directives
* Changed all type names format, now written without a colon and with an upper case latter (`Object` instead of `:object` as before)
* All operators are now functions (`is()`, `typeOf()`, etc...). Therefore, they must include their arguments between parenthesis.
* Custom functions are declared in the DataWeave header via the keyword `fun`, rather than `function`. For example `fun funName(args) = body`
* The `..` operator is no longer used for selecting ranges (still works as a descendants selector). Its functionality is replaced by `to`. Example: `[2 to 15]`.
* `when`, `unless` and `otherwise` are no longer used for conditional logic. They have been replaced by `if` and `else`. This requires that you slightly change the order of the expression. Example `if payload is(String) uppercase(payload)`.
* Binary functions (that take two arguments) support an alternative infix notation (arg1 function arg2). For example `payload.*items contains "3"` instead of `contains(palyoad.*items, "3")`.
* New key-value pair selector (`.&`) returns all matching keys and values. It returns them as a single object containing these.
* New namespace selector (`.#`) returns the namespace used.
* The functions `filter` and `groupBy` are overloaded to operate on objects.
* The functions `map`, `mapObject` and `filter` support a null input (in which case they return null).
* New supported syntax for `match` when using arrays  `[head ~ tail]`

* Namespace prefixes can no longer contain the character `-`.
* Multiple functions are no longer packaged as part of the core functions module. The package they belong to must be manually imported in the header before they can be called.
* Added index as 3rd param to `mapObject`, `pluck`, `filter`, and `groupBy`.


////
* Changed pattern matching     ... how?
* explain `[head ~ tail]` better
////




== See Also


* link:/mule-user-guide/v/4.0/dataweave-language-introduction[DataWeave Language Introduction]

* link:/mule-user-guide/v/4.0/dataweave-core-functions[DataWeave Core Functions]

* link:/mule-user-guide/v/4.0/dataweave-import-task[To Import DataWeave Modules]
