= Selectors
:keywords: studio, anypoint, esb, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

The structures of Objects and Arrays can be navigated using Selector Expressions. Each selector expression returns either an object, an array, or a simple type.

A selector always operates within a given context, which can be a reference to a variable, an object literal, an array literal, or the invocation of a function. As DataWeave processes a selector, a new context is set for further selectors, so you can navigate through the complex structures of arrays and objects by using chains of selectors, who's depth is limited only by the depth of the current context.

[%header,cols="20,30,20,30"]
|===
|Selector Type |Syntax |Return Type | Summary

|Single Value selector|.<key-name>|Value of a key:value pair|
|Multi Value selector|.*<key-name>||
|Descendants Selector|..<key-name>||
|Indexed Selector|[<index>]||
|Range Selector|[<index>..<index>]||
|XML Attribute Selector|.@<key-name>||
|All XML Attributes|.@||
|===


Applying the *Single level Explicit Selector*, the *Descendants Selector*, or the *Indexed Selector* returns the value of the key:value pair that matches the expression.

[NOTE]
Each of these selector expressions supports having a '?' appended at the end of the chain. This changes the expression into a query that checks upon the existence of the key. The return type in this case is a boolean true or false.


== Single Value selector

Value selectors may be applied over an `:object` or an `:array`.

=== Over :object

This selector returns the first value whose key matches the expression, that is, *payload.name*, which returns the value whose key matches *name*.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/xml
---
{
  address: payload.people.person.address
}
----



.Input
[source, json,linenums]
----
{
  "people": {
    "size" : 1,
    "person": {
      "name": "Nial",
      "address": {
        "street": {
          "name": "Italia",
          "number": 2164
        },
        "area": {
          "zone": "San Isidro",
          "name": "Martinez"
        }
      }
    }
  }
}
----

.Output
[source, xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<address>
  <street>
    <name>Italia</name>
    <number>2164</number>
  </street>
  <area>
    <zone>San Isidro</zone>
    <name>Martinez</name>
  </area>
</address>
----



=== Over :array

This selector is applied on each of the elements of the array that are of type `:object` and returns an array with all the selected values

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
payload.people.person.address.street
----



.Input
[source,DataWeave, linenums]
----
{
  "people": [ # //<1>
    {
      "person": {
        "name": "Nial",
        "address": {
          "street": {
            "name": "Italia",
            "number": 2164
          },
          "area": {
            "zone": "San Isidro",
            "name": "Martinez"
          }
        }
      }
    },
    {
      "person": {
        "name": "Coty",
        "address": {
          "street": {
            "name": "Monroe",
            "number": 323
          },
          "area": {
            "zone": "BA",
            "name": "Belgrano"
          }
        }
      }
    }
  ]
}
----
<1> As 'people' is an array, this sets the context for searching across both 'person' instances. The result from this is always an array.

.Output
[source, json,linenums]
----
[ # <1>
  {
    "name": "Italia",
    "number": 2164
  },
  {
    "name": "Monroe",
    "number": 323
  }
]
----

<1> As the context is an array, the output is always an array. An array is returned even if there's a single matching value.





== Multi Value selector

Multi value selector can either be applied over an `:object` or an `:array`.

=== Over :object

This selector returns an array with all the values whose key matches the expression.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  users: payload.users.*user
}
----



.Input
[source, xml, linenums]
----
<users>
  <user>Mariano</user>
  <user>Martin</user>
  <user>Leandro</user>
</users>
----

.Output
[source, json, linenums]
----
{
  "users": [
    "Mariano",
    "Martin",
    "Leandro"
  ]
}
----



=== Over :array

The selector is applied on each of the elements of the array that are of type `:object` and returns an array with all the selected values.


== Descendants Selector

This selector is applied to the context using the form *..<field-name>* and retrieves the values of all matching key:value pairs in the sub-tree under the current context. Regardless of the hierarchical structure these fields are organized in, they are all placed at the same level in the output.



.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  names: payload.people..name <1>
}
----



.Input
[source, json,linenums]
----
{
  "people": {
    "person": {
      "name": "Nial",
      "address": {
        "street": {
          "name": "Italia",
          "number": 2164
        },
        "area": {
          "zone": "San Isidro",
          "name": "Martinez"
        }
      }
    }
  }
}
----

.Output
[source, json,linenums]
----
{
  "names": [
    "Nial",
    "Italia",
    "Martinez"
  ]
}
----
<1> In this example, all of the fields that match the key "name" are placed in a list called "names" regardless of their cardinality in the tree of the input data.





=== Selecting all the Descendant Key Value Pairs



.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/xml
---
{
  names: payload.people..name as Object<1>
}
----
<1> The *as Object* makes the expression return an object rather than an array (which would be returned by default). This implies that each value has a key. Without this conversion, in XML the returned array would be a single long string of characters comprised of all three names merged into one.



.Input
[source, json,linenums]
----
{
  "people": {
    "person": {
      "name": "Nial",
      "address": {
        "street": {
          "name": "Italia",
          "number": 2164
        },
        "area": {
          "zone": "San Isidro",
          "name": "Martinez"
        }
      }
    }
  }
}
----

.Output
[source, xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<names>
  <name>Nial</name>
  <name>Italia</name>
  <name>Martinez</name>
</names>
----




== Indexed Selector

The index selector returns the element at the specified position, it can be applied over an `:array`, an  `:object` or a `:string`

=== Over :array

This selector can be applied to String literals, Arrays and Objects. In the case of Objects, the value of the key:value pair found at the index is returned. The index is zero based.

. If the index is bigger or equal to 0, it starts counting from the beginning.
. If the index is negative, it starts counting from the end where -1 is the last element.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
payload.people[1]
----



.Input
[source, json,linenums]
----
{
  "people": [
        {
          "name": "Nial",
          "address": "Martinez"
        },
        {
          "name": "Coty",
          "address": "Belgrano"
        }
    ]
}
----

.Output
[source, json,linenums]
----
{
  "name": "Coty",
  "address": "Belgrano"
}
----



When using the Index Selector with a String, the string is broken down into an array, where each character is an index.

.Transform
[source,DataWeave, linenums]
--------------------------------------------------------
output application/json
---
{
  name: "MuleSoft"[0]
}
--------------------------------------------------------

.Output
[source,json,linenums]
--------------------------------------------------------
{
  "name": "M"
}
--------------------------------------------------------

=== Over :string

The selector picks the character at a given position, treating the string as an array of characters.

. If the index is bigger or equal to 0, it starts counting from the beginning.
. If the index is negative, it starts counting from the end.

.Transform
[source,DataWeave, linenums]
--------------------------------------------------------
%dw 2.0
output application/json
---
{
  name: "Emiliano"[0]
}
--------------------------------------------------------

.Output
[source,json,linenums]
--------------------------------------------------------
{
  "name": "E"
}
--------------------------------------------------------

== Over :object

The selector returns the value of the key : value pair at the specified position.

== Range selector

=== Over :array

Range selectors limit the output to only the elements specified by the range on that specific order. This selector allows you to slice an array or even invert it.

.Transform
[source,DataWeave, linenums]
------------------------------------------------------------
%dw 2.0
output application/json
---
{
  slice: [0,1,2][0..1],
  last: [0,1,2][-1..0]
}
------------------------------------------------------------

.Output
[source,json,linenums]
----
{
  "slice": [
    0,
    1
  ],
  "last": [
    2,
    1,
    0
  ]
}
----

=== Over :string

The Range selector limits the output to only the elements specified by the range on that specific order, treating the string as an array of characters. This selector allows you to slice a string or even invert it.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  slice: "DataWeave"[0..1],
  last: "DataWeave"[-1..0]
}
----

.Output

[source,json,linenums]
----
{
  "slice": "Da",
  "last": "evaeWataD"
}
----


== XML Attribute Selector

In order to query for the attributes on an XML element, the syntax *.@<key-name>* is used. If you just use *.@* (without <key-name>) it returns an object containing each key:value pair in it.


.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  item: {
    type : payload.product.@type,
    name : payload.product.brand,
    attributes: payload.product.@
  }
}
----




.Input
[source, xml,linenums]
----
<product id="1" type="tv">
  <brand>Samsung</brand>
</product>
----

.Output
[source, json,linenums]
----
{
  "item:" {
    "type": "tv",
    "name": "Samsung",
    "attributes": { # <1>
      "id": 1,
      "type": tv
    }
  }
}
----

<1> The third element in this output retrieves an object with all of the attributes in it, in this case both the id and the type.





.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  item: {
    attributes : payload.product.@,
    name : payload.product.brand
  }
}
----

.Output
[source, json,linenums]
----
{
  "item": {
    "attributes": {
      "id": 1,
      "type": "tv"
    },
    "name": "Samsung"
  }
}
----

=== Selecting the key value pair

As selectors only return the value of a key:value pair, in order to get both the key and value, you can use a type conversion to object.



.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/xml
---
user: payload.name as Object <1>
----

<1> Using the *as Object* transforms the value into an object that contains the key as well as the value. Without this conversion to object, the returned XML body would simply be <user>Mariano</user>.




.Input
[source, json,linenums]
----
{
  "name": "Mariano",
  "lastName" : "Doe"
}
----

.Output
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<user>
  <name>Mariano</name>
</user>
----







== Selectors modifiers

There are two selectors modifiers: ? and !.

* The question mark returns true or false whether the keys are present on the structures.
* The exclamation mark evaluates the selection and fails if any key is not present.

=== Key Present

Returns true if the specified key is present in the object.



.Transform
[source,DataWeave,linenums]
--------------------------------------------------------
%dw 2.0
output application/xml
---
present: payload.name?
--------------------------------------------------------



.Input
[source,json,linenums]
--------------------------------------------------------
{
  "name": "Annie"
}
--------------------------------------------------------

.Output:
[source,xml,linenums]
--------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<present>true</present>
--------------------------------------------------------



In the example above, if a 'name' key does exist in the input, it returns *true*.

This operation also works with XML attributes:



.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
{
  item: {
    typePresent : payload.product.@type?
  }
}
----



.Input
[source, xml,linenums]
----
<product id="1" type="tv">
  <brand>Samsung</brand>
</product>
----

.Output
[source, json,linenums]
----
{
  "item": {
    "typePresent": true
  }
}
----



You can also use this validation operation as part of a filter:



.Transform
[source,DataWeave,linenums]
--------------------------------------------------------
%dw 2.0
output application/xml
---
users: payload.users.*name[?($ == "Mariano")]
--------------------------------------------------------



.Input
[source,xml,linenums]
--------------------------------------------------------
<users>
  <name>Mariano</name>
  <name>Luis</name>
  <name>Mariano</name>
</users>
--------------------------------------------------------

.Output
[source,xml,linenums]
--------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<users>
  <name>Mariano</name>
  <name>Mariano</name>
</users>
--------------------------------------------------------



The example above selects key:value pairs with value "Mariano" => {name: Mariano, name: Mariano}

=== Assert Present

Returns an exception if any of the specified keys are not found.


.Transform
[source,DataWeave,linenums]
--------------------------------------------------------
%dw 2.0
output application/xml
---
present: payload.lastName!<1>
--------------------------------------------------------
<1> Throws the exception "There is no key named 'lastName'".



.Input
[source,json,linenums]
--------------------------------------------------------
{
  "name": "Annie"
}
--------------------------------------------------------

Exception: "There is no key named 'lastName'"



== See Also

* link:/mule-user-guide/v/4.0/dataweave-cookbook-extract-data[Dataweave cookbook: Extract Data]
* link:/mule-user-guide/v/4.0/dataweave-language-introduction[DataWeave Language Introduction]
* link:/mule-user-guide/v/4.0/dataweave-core-functions[DataWeave Core Functions]
