= match

<<match1>> |


[[match1]]
== match(String, Regex): Array<String>

Matches a string against a regular expression. It returns an array that contains
the entire matching expression, followed by all of the capture groups that match
the provided regex.

It can be applied to the result of any evaluated expression, and can return any evaluated expression. See the Match operator in link:/mule-user-guide/v/3.8/dataweave-language-introduction[the DataWeave Language Introduction].


.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
hello: "anniepoint@mulesoft.com" match /([a-z]*)@([a-z]*).com/
----

.Output
[source,json,linenums]
----
{
  "hello": [
    "anniepoint@mulesoft.com",
    "anniepoint",
    "mulesoft"
  ]
}
----

In the example above, we see that the search regular expression describes an email address. It contains two capture groups, what's before and what's after the @. The result is an array of three elements: the first is the whole email address, the second matches one of the capture groups, the third matches the other one.


