= Runtime Types

This are the native types of DataWeave. Those are the only types that allow the `???` definition (for example, `type String = ???`).
// NOTE TO MARIANO: Please alphabetize the types.

== Any

`Any` type, is the top level type. Any extends all of the system types. That means anything can be assigned to a `Any` typed variable.

== Array

`Array` type, requires a Type(T) to represent the elements of the list. Example: `Array<Number>` represents an array of numbers.

== Binary

A Blob

== Boolean

A `Boolean` type `true` of `false`

== Date and Time Types

=== Date

A Date represented by Year Month Day

=== DateTime

A Date Time with in a TimeZone

=== LocalDateTime

A DateTime in the current TimeZone. Example: TODO

=== LocalTime

A Time in a specific TimeZone. Example: TODO

=== Time

A Time in the current TimeZone. Example: TODO

=== TimeZone (or Time?)

A TimeZone. Example: TODO

== Dictionary<T> = {_?: T}

Generic Dictionary interface.

== Key

A Key of an Object.

== Namespace

 A namespace type represented by a URI and a Prefix.

== Nothing

Bottom type. This type is can be assigned to all the types

== Null

A null type.

== Number

A number any number decimals and integers are represented by `Number` type.

== Object

`Object` type. Represents any object, collection of Key Value Pairs

== Period

A Period

== Range

A Range type represents a sequence of numbers.

== Regex

Regex type. TODO: which regex flavor allowed

== String

//A description

== Type<T>

Represents a Type in the DataWeave Type System

== Union Types

=== Comparable

A union type that represents all the types that  can be compared to each other.

`type Comparable = String | Number | Boolean | DateTime | LocalDateTime | LocalTime | Time | TimeZone`

=== SimpleType

A union type that represents all the simple types.

`type SimpleType = String | Boolean | Number | DateTime | LocalDateTime | Date | LocalTime | Time | TimeZone | Period`

== Uri

A URI.

== See Also

link:dw-functions[DataWeave Functions]
