= DataWeave Functions for Objects (dw::core::Objects)

Returns a list of key value pair object describing the object entries

.Example
[source, DataWeave, linenums]
----
%dw 2.0
import dw::core::Objects
---
Objects::entrySet({a: true, b: 1})
----

.Transform
[source,DataWeave, linenums]
----
[{key: "a", value: true}, {key: "b", value: 1}]
----

== `divideBy`

=== divideBy(Object, Number): Array<Object>

Divides the object into sub objects with the specified amount of properties

.Transform
[source,DataWeave, linenums]
----
output application/json
---
 {a: 123,b: true, a:123,b:false} divideBy 2
----

.Output
[source,json, linenums]
----
[
   {
     "a": 123,
     "b": true
   },
   {
     "a": 123,
     "b": false
   }
 ]
----

////
== `entrySet`

=== entrySet(T)
// TODO: NO EXAMPLES
////

////
== `internalDivideBy`

=== internalDivideBy(Object, Number, Object): Array<Object>

// TODO: NO EXAMPLES
////


== `keySet`

=== keySet(T): ?

Returns the list of key names of an object

.Example
[source,DataWeave, linenums]
----
%dw 2.0
import dw::core::Objects
---
Objects::nameSet({a: true, b: 1})
----

.Output
[source,json, linenums]
----
["a","b"]
----


== `mergeWith`

=== mergeWith(T, V): ?

Overrides the source with the target object so that the result with contain all the properties from the target
plus the properties on the source that are not declared on the target

.Example
[source,DataWeave, linenums]
----
%dw 2.0
import mergeWith from dw::core::Objects
---
{a: true, b: 1} mergeWith {a: false, c: "Test"}
----

.Output
[source,json, linenums]
----
{a: false, b: 1 , c: "Test"}
----

=== mergeWith(Null, T): T

Helper method to make `mergeWith` null friendly

=== mergeWith(T, Null): T

Helper method to make `mergeWith` null friendly

////
./do-import/transform.dwl
./integration-1/transform.dwl
./objects-lib/transform.dwl
////

== `nameSet`

=== nameSet(Object): Array<String>

Returns the list of key names of an object

.Example
[source,DataWeave, linenums]
----
%dw 2.0
import dw::core::Objects
---
Objects::nameSet({a: true, b: 1})
----

.Output
[source,json, linenums]
----
["a","b"]
----


== `valueSet`

=== valueSet({ K?: V }): Array<V>

Returns the list of key values of an object

.Example
[source,DataWeave, linenums]
----
%dw 2.0
import dw::core::Objects
---
Objects::nameSet({a: true, b: 1})
----

.Output
[source,json, linenums]
----
[true,1]
----

== See Also

link:dw-functions[DataWeave Functions]
