= DataWeave Functions for Arrays (dw::core::Arrays)

Returns true if some element of the list matches the condition.
It stops the iterations after the first match.

== `countBy`

=== countBy(Array<T>, (T) -> Boolean): Number

Counts the matching elements using a matchingFunction(T)

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
[1, 2, 3] countBy (($ mod 2) == 0)
----

.Output
[source,json,linenums]
----
1
----


== `divideBy`

=== divideBy(Array<T>, Number): Array<Array<T>>

Divides an Array of items into sub arrays.
.Transform
[source,DataWeave, linenums]
----
output application/json
---
[1, 2, 3, 4, 5] divideBy 2
----

.Output

[source,json,linenums]
----
[
   [
     1,
     2
   ],
   [
     4,
     5
   ]
 ]
----


== `every`

=== every(Array<T>, (T) -> Boolean): Boolean

Returns true if every element of the list matches the condition. It stops the iterations after the first negative evaluation.


== `internalDivideBy`

=== internalDivideBy(Array<T>, Number, Array<T>): Array<Array<T>>




== `private_every`

=== private_every(Array<T>, (T) -> Boolean): Boolean




== `some`

=== some(Array<T>, (T) -> Boolean): Boolean




== `sumBy`

=== sumBy(Array<T>, (T) -> Number): Number

Adds the values returned by the right hand side function

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
output application/json
---
sumBy([ { a: 1 }, { a: 2 }, { a: 3 } ], (item) -> item.a)
// same as [ { a: 1 }, { a: 2 }, { a: 3 } ] sumBy $.a
----

.Output
[source,json,linenums]
----
6
----

== See Also

link:dw-functions[DataWeave Functions]
