= DataWeave Functions for Assertions (dw::core::Assertions)

// TODO: NEED DESCRIPTION of what an Assertion error is.

== `assert`

.assert(Boolean, String): Boolean

Raises an execution error when the first argument is false. The second argument is the error message.

This example raises an assertion error (`raises an assertion`):

----
%dw 2.0
import * from dw::core::Assertions
output application/json
---
assert(('a' is Number),'raises an assertion')
----

This example does not raise an assertion error.

----
%dw 2.0
import * from dw::core::Assertions
output application/json
---
assert(('a' is String),'does not raise an assertion')
----

////
TODO? NEED BETTER EXAMPLES?
./read-binary-files/transform.dwl
./hex/transform.dwl
./crypto/transform.dwl
////

== `mustEqual`

.mustEqual(a, b): Boolean

Raises an execution error if the arguments are not exactly the same.

This example raises an assertion error (`"a" must equal "b"`):

----
%dw 2.0
import * from dw::core::Assertions
output application/json
---
mustEqual('a','b')
----

This example does not raise an assertion error.

----
%dw 2.0
import * from dw::core::Assertions
output application/json
---
mustEqual('a','a')
----

////
./read-binary-files/transform.dwl
./try/transform.dwl
./urlEncodeDecode/transform.dwl
////

== `mustMatch`

.mustMatch(String, Regex): Boolean

Raises an execution error when the first argument (String) doesn't match the second argument (Regex).

This example raises an assertion error (`"a" must match expression "[bc]"`):

----
%dw 2.0
import * from dw::core::Assertions
output application/json
---
mustMatch('a', '[bc]')
----

This example does not raise an assertion error.

----
%dw 2.0
import * from dw::core::Assertions
output application/json
---
mustMatch('a', '[abc]')
----

== See Also

link:dw-functions[DataWeave Functions]
