= DataWeave Functions for Binaries (dw::core::Binaries)

// TODO: MISSING EXAMPLE
== `fromBase64`

=== fromBase64(String): Binary

Converts a base64 string representation into a binary.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Binaries
output application/json
---
toBase64(fromBase64(12463730))
----

.Output
----
12463730
----

// TODO: MISSING EXAMPLE
////
./base64/transform.dwl
./octet-stream-write/transform.dwl
./read-binary-files/transform.dwl
////

== `fromHex`

=== fromHex(String): Binary

Converts an hexadecimal string representation into a binary.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Binaries
output application/json
---
fromHex('4D756C65')
----

.Output
----
Mule
----

// TODO: MISSING EXAMPLE
////
./hex/transform.dwl
////

== `toBase64`

=== toBase64(Binary): String

Transforms the specified binary into the base64 string representation.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Binaries
output application/json
---
toBase64(fromBase64(12463730))
----

.Output
----
12463730
----

// TODO: MISSING EXAMPLE
////
./base64/transform.dwl
./crypto-hash/transform.dwl
./read-binary-files/transform.dwl
////

== `toHex`

=== toHex(Binary): String

Transforms the specified binary into the hexadecimal String representation.

.Transform
[source,DataWeave, linenums]
----
%dw 2.0
import * from dw::core::Binaries
output application/json
---
toHex('Mule')
----

.Output
----
"4D756C65"
----

////
./hex/transform.dwl
////

== See Also

link:dw-functions[DataWeave Functions]
