= DataWeave Functions for URL (`dw::core::URL`)

== `compose`

=== compose(Array<String>, Array<String>): String

Compose is a custom interpolator used to replace URL components by the encodeURIComponent result of it.
Example:
[source, dataweave]
----
 compose `http://asd/$(' text to encode ')/text to encode`
  ==
 'http://asd/%20text%20to%20encode%20/text to encode'
----


== `decodeURI`

=== decodeURI(String): String

The `decodeURI()` function decodes a Uniform Resource Identifier (URI) previously created by encodeURI or by a similar routine. Replaces each escape sequence in the encoded URI with the character that it represents, but does not decode escape sequences that could not have been introduced by encodeURI. The character `#` is not decoded from escape sequences.


== `decodeURIComponent`

=== decodeURIComponent(String): String

The `decodeURIComponent()` function decodes a Uniform Resource Identifier (URI) component previously created by encodeURIComponent or by a similar routine.


== `encodeURI`

=== encodeURI(String): String

The `encodeURI()` function encodes a Uniform Resource Identifier (URI) by replacing each instance of certain characters by one, two, three, or four escape sequences representing the UTF-8 encoding of the character (will only be four escape sequences for characters composed of two "surrogate" characters).

Assumes that the URI is a complete URI, so does not encode reserved characters that have special meaning in the URI.

With the exception of the types in the table below, `encodeURI()` replaces all characters with the appropriate UTF-8 escape sequences.

[%header%autowidth.spread]
|===
| Unescaped Types      | Includes
| Reserved characters  | ; , / ? : @ & = $
| Unescaped characters | alphabetic, decimal digits, - _ . ! ~ * ' ( )
| Number sign          | #
|===

== `encodeURIComponent`

=== encodeURIComponent(String): String

The `encodeURIComponent()` function encodes a Uniform Resource Identifier (URI) component by replacing each instance of certain characters by one, two, three, or four escape sequences representing the UTF-8 encoding of the character (will only be four escape sequences for characters composed of two "surrogate" characters).

`encodeURIComponent()` escapes all characters except these: alphabetic, decimal digits, - _ . ! ~ * ' ( )

`encodeURIComponent()` differs from `encodeURI()`  in that it encodes reserved characters and the Number sign (`#`) of `encodeURI()`:

[%header%autowidth.spread]
|===
| Type                 | Includes
| Reserved characters  |
| Unescaped characters | alphabetic, decimal digits, - _ . ! ~ * ' ( )
| Number sign          |
|===

== `parseURI`

=== parseURI(String): URI

Parses an URL and returns an URI object. The `isValid: Boolean` property denotes if the parse was succeed. Every field in the URI object is optional, and it will be present only if it was present in the original URL

== URI Types

// == URI

// TODO . Definition

[source]
----
{
  isValid: Boolean,
  host?: String,
  authority?: String,
  fragment?: String,
  path?: String,
  port?: Number,
  query?: String,
  scheme?: String,
  user?: String,
  isAbsolute?: Boolean,
  isOpaque?: Boolean
}
----

== See Also

link:dw-functions[DataWeave Functions]
