= Dynamic Evaluate Component
:keywords: mule, ee, esb, studio, dynamic, evaluate, expression

This component evaluates an expression that should result in another script, evaluating
that for a final result. Such behavior allows to dynamically select the script, instead
of hardcoding it as in the link:mule-user-guide/v/4.0/transform-component-about[Transform Component].

The script can use any of the usual link:mule-user-guide/v/4.0/dataweave-variables-context[context variables],
such as `message`, `payload`,`vars` or `attributes`, but you can also add custom ones
by providing a set of key-value pairs.

In the following example, the script is selected from a database according to a
`userId` query parameter and stored in a variable. The dynamic-evaluate component
will then access the variable to get the desired script evaluated, adding a
`name` variable from a `userName` query parameter.

.Example: XML Configuration of the Flow
[source,xml,linenums]
----
<flow name="raise-error-example-flow">
  <http:listener config-ref="HTTP_Listener_Configuration" path="/"/>
  <db:select config-ref="dbConfig" target="userScript">
    <db:sql>#["SELECT script FROM SCRIPTS WHERE ID = $(attributes.queryParams.userId)"]</db:sql>
  </db:select>
  <ee:dynamic-evaluate expression="#[vars.userScript]">
    <ee:parameters>#[{name: attributes.queryParams.userName}]</ee:parameters>
  </ee:dynamic-evaluate>
</flow>
----

== Dynamic Evaluate Configuration

[%header,cols="1,1,2,2"]
|===
| Field | Value | Description | Example

| Expression | DataWeave expression | Specifies the expression that will be evaluated into the final script. |
`expression="#[vars.generateOrderScript]"`
| Parameters | DataWeave expression | Specifies key-value pairs that should be bound to evaluate the final script. |
`#[{joiner: ' and ', id: payload.user.id}]`

|===
