= For Each Scope XML Reference



Foreach scopes open and close with a `<foreach>` tag. Components that are affected by this scope are defined as child elements of the `foreach` tag.




== Configurable Properties

[%header,cols="30,70"]
|===
|Property | Default |Description
|collection | Payload |

Where to find the data to split and process. For example, "#[payload.items]" makes the Foreach scope deal with the elements of a collection in `payload.topics`.
Any data outside this collection, such as in `payload.transactionId`, is ignored.

| counterVariableName | counter
| Name the variable that Foreach uses to record the number of the elements it has processed.

| batchSize | 1
| Number of elements in each batch that Foreach processes. For example, if a collection has 200 elements and you set the batch size to 50, it processes 4 batches of 50 elements.

| rootMessageVariableName | rootMessage
| Name the variable that Foreach uses to reference the complete, unsplit message collection.
|===





== Example

[source,xml,linenums]
----
<foreach collection="#[payload.name]" doc:name="For Each" counterVariableName="counter" rootMessageVariableName="rootMessage" batchSize="5">
    <some-nested-element/>
    <some-other-nested-element/>
</foreach>
----










== See Also
