= About the For Each Scope


The Foreach scope splits a collection into elements and processes them iteratively through the processors embedded in the scope, then returns the original message to the flow. It's similar to a for-each/for-loop code block.


Can process any type of collection, including maps, lists, arrays, and MuleMessageCollections.  (?)
Any element, not just payload  (?)


Foreach vs collection splitter :   Under some circumstances, splitting a message collection into pieces can cause certain vital bits  — metadata in the header or footer, for example — to be dropped from the re-aggregated message.   Foreach splits collections into elements, then processes them iteratively without losing any of the message payload.   (?)

 it doesn’t re-aggregate those individual elements into a MuleMessageCollection; rather, it returns the original message. (This results in "Java in, Java out" rather than "Java in, MuleMessageCollection out.")   (?)


The only type of message processor you cannot drag into a Foreach scope is an inbound connector.



You can optioanlly use an expression to split data in a custom way
ex:
"#[payload.topic]"

Optional) Default value = counter - Enter a name in this field to label the variable that Foreach uses to record the number of the elements it has processed.

Batch Size
Enter an integer to indicate the number of elements in each batch that Foreach processes. Potentially, these batches promote quicker processing. If greater than one, each batch is treated as a separate Mule message. For example, if a collection has 200 elements and you set the batch size to 50, Foreach iteratively processes 4 batches of 50 elements, each as a separate Mule message.

Optional) Default value = rootMessage - Enter a name in this field to label the variable that Foreach uses to reference the complete, unsplit message collection. If your collection already uses the label rootMessage for another variable, this field is blank and you need to enter a different label for the Root Message Variable Name.


== Error Handling

 If a message in a collection throws an exception, Foreach stops processing that collection and invokes the exception strategy.


== Persisting Data

 In case the message inside the foreach scope is persisted, not only the item in the collection is serialized but also all the variables associated with the current message. The rootMessage variable, associated with the message, contains a reference of the complete, unsplit message collection that could potentially be holding thousands of items. Therefore, serialization/deserialization of the rootMessage variable could impact memory consumption considerably when this collection is large enough.

 To avoid this issue you must first remove the rootMessage variable from the message before persisting it. For this you can use the <remove-variable> element like so:


== See Also
