= For Each Scope XML Reference


The Foreach scope splits a collection into elements and processes them one by one through the components that you place in the scope. It then regroups them into a single message containing a collection. It's similar to a for-each/for-loop code block in most programming languages.

It Can process any type of collection, including maps, lists, arrays.


You can optionally use an expression to split data in a custom way


"#[payload.topic]"








collection


default Payload


(Optional) Enter an expression that tells Foreach where to find the data it must split and process. For example, enter an expression that instructs Foreach to split and process a collection from the header section – rather than the payload. Unless this attribute specifies otherwise, Foreach assumes that the message payload is the collection.

counterVariableName


default counter


(Optional) Specify to label the variable that Foreach uses to record the number of the elements it has processed. If your collection already uses the label counter for another variable, select a unique name.

batchSize


default 1


(Optional) Specify an integer to indicate the number of elements in each batch that Foreach processes. Potentially, these batches promote quicker processing. For example, if a collection has 200 elements and you set the batch size to 50, Foreach iteratively processes 4 batches of 50 elements.

rootMessageVariableName


default rootMessage


(Optional) Specify to label the variable that Foreach uses to reference the complete, unsplit message collection. If your collection already uses the label rootMessage for another variable, select a unique name.





<foreach collection="#[payload.name]" doc:name="For Each" counterVariableName="counter" rootMessageVariableName="rootMessage" batchSize="5">
    <some-nested-element/>
    <some-other-nested-element/>
</foreach>






== See Also
