= Mule User Guide
:keywords: mule, getting started, transform, message, payload

This guide offers information about how to use link:https://www.mulesoft.org/what-mule-esb[Mule Runtime], commonly called *Mule*, or *Mule ESB* to integrate systems, orchestrate web services and configure the runtime environment. The visual representations of Mule applications you see throughout the documentation are usually depicted as seen in the link:/anypoint-studio/v/6[Anypoint Studio IDE].

== About Mule

*Mule* is the *lightweight integration runtime engine* that allows you to connect anything, anywhere. Rather than creating multiple point-to-point integrations between systems, services, APIs, and devices, you use Mule to create applications that intelligently manage message routing, data mapping, orchestration, reliability, security, and scalability between nodes. Plug other systems and applications into Mule and let it handle communication between systems, allowing you to track and monitor your application ecosystem and external resources.

[NOTE]
Mule is so named because it “carries the heavy load” of developing an infrastructure that supports multiple applications and systems both flexibly and intelligently.

== What is a Mule Application?

Integration developers write Mule applications to tie together various systems. Mule applications are configured to run on Mule runtime to process inbound information, and ingest this information in a pre-defined manner. An expected request to a running Mule application naturally triggers Mule to encode the event and data in a Mule message, passing it along a single thread or multiple threads. Mule transforms and routes the Mule message in stages, according to the processors configured to interact with the message at the various stages. Mule gets the message to its destination, passing the requisite data to the recipient.

The Mule application is defined in an XML document that specifies the necessary dependencies for the Mule application to run. You can configure your Mule application to process data in a variety of ways, and can adjust the Mule runtime instance accordingly. Mule is packaged with components, connectors, and transformers that work quickly to get the data and metadata you need from your Mule application, and feed it to any destination.

== Developing with Mule You Can...

* *Deploy or integrate* applications or systems on premises or in the cloud
* Employ out-of-the-box connectors to create *SaaS integration* applications
* Build and *expose APIs*
* *Consume APIs*
* Create Web services which *orchestrate calls* to other services
* Create interfaces to expose applications for *mobile consumption*
* *Integrate B2B* with solutions that are secure, efficient, and quick to build and deploy
* Shift applications onto the *cloud*
* Connect *B2B e-commerce* activities

== Mule Installation Options

[NOTE]
Install a standalone instance of Mule, or included with *Mule Management Console*, or *Anypoint Studio IDE*.
See link:/mule-user-guide/v/4.0/downloading-and-starting-mule-esb[Download and Start Mule Runtime]



// == Mule Reference Material
//
// Learn more about Mule features and configuring applications that run on Mule.
//
// * link:/mule-user-guide/v/3.8/reference[Reference]
// * link:/mule-user-guide/v/3.8/publishing-and-consuming-apis-with-mule[Publishing and Consuming APIs with Mule]
// * link:/mule-user-guide/v/3.8/business-events[Business Events]
// * link:/mule-user-guide/v/3.8/using-maven-with-mule[Using Maven with Mule]
// * link:/mule-user-guide/v/3.8/improving-performance-with-the-kryo-serializer[Improving Performance with the Kryo Serializer]
// * link:/mule-user-guide/v/3.8/error-handling[Error Handling]
// * link:/mule-user-guide/v/3.8/batch-processing[Batch Processing]
// * link:/mule-user-guide/v/3.8/transaction-management[Transaction Management]
// * link:/mule-user-guide/v/3.8/adding-and-removing-user-libraries[Adding and Removing User Libraries]
// * link:/mule-user-guide/v/3.8/shared-resources[Shared Resources]
// * link:/mule-user-guide/v/3.8/mule-versus-web-application-server[Mule versus Web Application Server]
