= Introduction to Mule 4: Configuring Mule Applications

In Mule 3, you often used Spring property placeholders to configure applications dynamically for the environment they were deployed in. Mule 4 contains a built-in mechanism to do this that allows setting of default values, and you are not required to learn Spring.

These properties are stored in a YAML file:
[source,yaml]
----
http:
  path: service
  port: "10000"
----

You can add the YAML file to your Mule app through the Global Element called Configuration Properties. The XML for it looks like this:
[source,xml,linenums]
----
<configuration-properties file="myConfiguration.yaml" />
----

We highly recommend that you do not package the configuration files for all the environments inside your application. Instead,
we recommend that you use this file to provide defaults, then use Runtime Manager to override each of these properties at deployment time.


== See Also

link:/mule-user-guide/v/4.0/configuring-properties[Configuring Property Placeholders]
