= About the Mule Application

You create Mule apps to perform system integrations. Mule apps are configured to run on Mule Runtime. A request to a Mule app triggers Mule to encode the event and data in a Mule Event, and to pass it along a single or multiple threads.

The main building blocks of Mule apps are connectors, components, and modules that provide connectivity to external servers, handle data transformations, and route and process Mule events.

The Mule app is defined in an XML document that specifies dependencies needed for the app to run. Though it is possible to write the XML by hand, you can avoid working with XML by using the graphical interfaces in Design Center or Anypoint Studio UIs. As you use the UIs to structure and define the behavior of your Mule app, the underlying XML is provided for you.

== See Also

* link:/mule-user-guide/v/4.0/about-mule-event[About the Mule Event]
* link:/mule-user-guide/v/4.0/about-mule-message[About the Mule Message]
* link:/mule-user-guide/v/4.0/about-components[About Components]
* link:/mule-user-guide/v/4.0/about-flows[About Flows]
* link:/mule-user-guide/v/4.0/about-event-source[About the Event Source]
* link:/mule-user-guide/v/4.0/about-event-processors[About Event Processors]
