= About the Mule Application

Mule apps perform system integrations. The are configured to run on Mule Runtime to process and ingest inbound information in a pre-defined manner. A request to a running Mule application triggers Mule to encode the event and data in a Mule Event, passing it along a single or multiple threads.

The main building blocks of Mule apps are connectors, components, and modules that provide connectivity to external servers, handle data transformations, and route and process Mule events.

The Mule app is defined in an XML document that specifies the necessary dependencies for the Mule application to run. Though it is possible to write the XML by hand, you can avoid working with XML by using the graphical interfaces in Design Center or Anypoint Studio UIs. As you build your Mule app, these UIs supply the underlying XML so that you can focus on the overall structure and behavior of your app.

== See Also

* link:/mule-user-guide/v/4.0/about-mule-event[About the Mule Event]
* link:/mule-user-guide/v/4.0/about-mule-message[About the Mule Message]
* link:/mule-user-guide/v/4.0/about-components[About Components]
* link:/mule-user-guide/v/4.0/about-flows[About Flows]
* link:/mule-user-guide/v/4.0/about-event-source[About the Event Source]
* link:/mule-user-guide/v/4.0/about-event-processors[About Event Processors]
