= To Configure Mule App Properties

In situations such as deploying a Mule app to a new environment, it is often necessary to update configurations, such as the HTTP port, that are specific to that environment. To address this need, you can create a YAML file that defines these properties. Updates to that file inject new values into a Mule app when it deploys.

The properties in the file takes this form:
----
http:
  path: service
  port: "10000"
----

You must store the file in the project directory for your Mule app:
* `/src/main/resources`

You add the YAML file to your Mule app through the Global Element called Configuration Properties. The XML for it looks like this:

`<configuration-properties file="myConfiguration.yaml" doc:name="Configuration properties" doc:id="872422be-3571-4a52-a383-a2b0e16859d7" />`

Once the attributes are configured, you can reference them using this syntax: `${http.path}` and `${http.port}`.

For example, your HTTP Listener might pass the port like this:
`<http:listener-connection host="0.0.0.0" port="${http.port}" />`

== To Set and Use Spring Configurations

The Spring module allows you to use any sort of Spring configurations in Mule apps, and you can use these configurations as placeholders in Spring configuration files.

You can define the Spring property placeholders in a `.properties` file, for example, `spring-properties.properties`.

The properties in the file takes this form:
----
springPropertyA=springPropertyAValue
springPropertyB=springPropertyBValue
----

The prefix (`${`) and suffix (`}`) is fixed in Spring.

You must store the file in the project directory for your Mule app:
* `/src/main/resources`

You add the `.properties` file to your Mule app through the Global Element called Configuration Properties. The XML for this element looks like this:

`<configuration-properties file="spring-properties.properties" doc:name="Spring Property Placeholders" doc:id="07ee5c11-bc54-4d55-91b8-ce02f743cb7a" />`

Here, a Spring Framework configuration provides the location of Spring Property placeholders as `spring-properties.properties`.

----
<?xml version=“1.0” encoding=“UTF-8"?>
<beans xmlns=“http://www.springframework.org/schema/beans”
       xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance”
       xsi:schemaLocation=”
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd”>

  <bean class=“org.springframework.beans.factory.config.PropertyPlaceholderConfigurer”>
        <property name=“location”>
            <value>spring-properties.properties</value>
        </property>
  </bean>
</beans>
----
