= Mule Runtime v4.0 Updates
:keywords: news, updates, mule ESB, mule runtime, 4.0, Mule 4.0, Mule 4.0 for mule 3 developers, what's new Mule 4

*Mule 4.0* introduces significant changes from previous versions. +

*Mule 4.0*'s simplified language and reduced management complexity allows users to speed up the on ramping process and deliver applications faster.

If you are familiar with the concepts of the previous versions of the runtime, check sections below to learn what's changing in *Mule Runtime v4.0*:


== Inteligent Self-Tuning Runtime

As opposed to Mule 3.x, *Mule 4.0* is an entirely _self-tuning_ and _non-blocking_ runtime, meaning that it uses a *task-oriented* execution model allowing the user to take advantage of non-blocking IO calls and avoiding performance problems due to incorrect processing strategies configurations. +

*Mule 4.0* removes complex tuning requirements to achieve optimum performance.

Each Mule event process can now inform the runtime if it is a CPU intensive, CPU light, or IO intensive operation. This will in turn help Mule self-tune for different workloads dynamically, removing the need for customers to manage threadpools manually.


== Module Consistency

*Mule 4.0* introduces more consistency around *connectors* and *extensions* unifying everything as link:/mule-user-guide/v/4.0/mule-concepts#modules[Modules] to extend the behavior inside a Mule application.

Both custom and core connectors are created and managed using the *Mule SDK*, allowing the user a unified connector/module experience.

[TIP]
In the Mule 4.0 ecosystem, we refer to connectors as Modules. +
After all, a _Connector_ is just a Module with connection capabilities.


// COMBAK: Smart connectors are not going to be available for BETA
// Introducing *_Smart Connectors_*: Modules designed using XML to manipulate connections. +
// Users can define the module, set configurations and define operations that can later be invoked in the mule application to manipulate connections.

// TODO: Need confirmation about private flows going away.

== Simplified Message Structure and Scopes

*Mule 4.0* includes a simplified link:/mule-user-guide/v/4.0/mule-concepts#mule-message[Mule message] composed by a _payload_ and _metadata_. +
The Mule message is now part of an entire _contextual information_ known as the link:/mule-user-guide/v/4.0/mule-concepts#mule-event[Mule event].

All other concepts around the former link:/mule-user-guide/v/3.8/mule-message-structure[Mule message structure] have been deprecated. Meaning that there are no more _inbound_ nor _outbound_ properties, and all information around the Mule event is now exposed through link:/mule-user-guide/v/4.0/mule-concepts#variables[variables], allowing the user to completely manage the *Mule event*.

Everything contained within a Mule application is a link:/mule-user-guide/v/4.0/mule-concepts#components[component]. +
*Components* that act on a Mule Event are link:/mule-user-guide/v/4.0/mule-concepts#event-processors[event processors], and every *processor* that defines an operation to apply to the Mule event are known as link:/mule-user-guide/v/4.0/mule-concepts#operations[operations].

Before executing, *Mule 4.0* gathers input context and retrieves information to parametrize the _operation_. For example, an HTTP request is generated using an *HTTP Module*, with an `http:request` *operation*, and a link:mule-user-guide/v/4.0/mule-concepts#module-configurations[Module configuration] (`requestConfig`).

//TODO Double check this example

[source,XML,linenums]
----
<httpn:request config-ref="requestConfig" method="#[dw:attributes.method]" path="#[dw:attributes.requestPath]" parseResponse="false">
       <httpn:request-builder>
           <httpn:query-params>#[dw:attributes.queryParams]</httpn:query-params>
           <httpn:headers>#[dw:attributes.headers]</httpn:headers>
       </httpn:request-builder>
</httpn:request>
----

Once an operation executes, the result is a new message, replacing the message in the *Mule event*.

It is also possible to define a _target_ to save the new Mule message in a Variable:

[source,XML,linenums]
----
<httpn:request target="myVar" config-ref="requestConfig" method="#[dw:attributes.method]" path="#[dw:attributes.requestPath]" parseResponse="false">
      <httpn:request-builder>
          <httpn:query-params>#[dw:attributes.queryParams]</httpn:query-params>
          <httpn:headers>#[dw:attributes.headers]</httpn:headers>
      </httpn:request-builder>
</httpn:request>
----
This saves the Mule message in the `myVar` *variable* to be accessed later.


== Error Handling Strategies

//TODO: Need more information about Error handling strategies
*Mule 4.0* moves away from the Exception scenario and allows users to handle custom errors.


== Mule API

*Mule 4.0* includes new, well defined APIs. These make it easier to extend Mule and provide clarity to developers on what the proper extension points are.

The runtime exposes 3 main APIs that allow developers to build on top and extend the runtime capabilities:

* Core API: Mule message
* Extensions API: APIs which allow users to create modules, message processors, transformers, etc. which extend the runtime.
* Tooling API: All DataSense metadata and propagation is now part of the runtime, and can be accessed as part of the tooling API, which is bundled with the Mule Agent.

== Classloader Isolation

*Mule 4.0* loads each *Module* in its own classloader, isolating the modules from internal Mule code. +
Given that applications are no longer dependent from internal Mule changes, users are able to upgrade their runtime version without breaking compatibility with other modules.

All modules are distributed outside the runtime, meaning that *Mule 4.0* does not include any _connector_ by default.

== DataWeave 2.0: The Mule Expression Language

[CAUTION]
MEL is being deprecated, and *Dataweave* is now the default expression language within the runtime.

*DataWeave 2.0* improves the language and runtime, adding features such as:

* Language simplifications - everything is now a function!
* DataWeave scripts can now be packaged and reused, via the new imports and modules features. This replaces the *transformers* from Mule 3.x.

[NOTE]
Some operations are not available outside EE. +
A community version of DataWeave is shipped with the Mule Kernel.

== Compatibility Module

To help users migrate to *Mule 4.0*, we included a *Compatibility Module* with a migration tool for the new semantics.
