= To Create Mule Domain Projects 
In Anypoint Studio, create a new Mule Domain Project. 

Just like with a new Mule application project, a new Mule domain project will have a configuration.xml file. This XML file contains similar namespace definitions as a Mule application. 

For example: 
+
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<domain:mule-domain
        xmlns:http="http://www.mulesoft.org/schema/mule/http"
        xmlns="http://www.mulesoft.org/schema/mule/core"
        xmlns:domain="http://www.mulesoft.org/schema/mule/ee/domain"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/ee/domain http://www.mulesoft.org/schema/mule/ee/domain/current/mule-domain-ee.xsd
http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="00ac6cd8-046c-4a65-8d55-5f0d76b10a47" >
		<http:listener-connection host="0.0.0.0" port="8081" />
	</http:listener-config>


    <!-- configure here resource to be shared within the domain -->

</domain:mule-domain>
----
+
You can copy/paste resources from a Mule application, but you will also have to carefully copy/paste the namesapce declaration and the corresponding XSD files. 


Instead, you can use the Global Elements editor to add shared elements to the domain project. 

Just like with a Mule application, you will have to import the module for whatever connector or other module you want to add to the domain project. But because the Mule domain project does not include a flow editor, you instead click the Manage Module button in the Global Elements editor. 
This will bring up a Properties editor. 
Then click Add Module to add a common module directly from inside Studio, or you can seach for other modules in Anypoint Exchange. 

= Understanding a Mule Domain's POM File 
A Mule domain is identified to other Mule applications using a Maven artifact ID. This appears in the Mule domain's POM file. For example, here is a Mule domain identified with the artifactId muledomain2. 

+
[source,xml,linenums]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mycompany</groupId>
    <artifactId>muledomain2</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>mule-domain</packaging>

    <name>muledomain</name>
----

= Adding a Mule Application to a Mule Domain
Any Mule application can be added to a Mule domain by assigning the Mule domain's artifactId inside a <dependency> tag. 

For example, here is the dependency you would add to the Mule application's POM file to associate the Mule application with the muledomain2 Mule domain:

+
[source,xml,linenums]
----
	<dependencies>
		<dependency>
            <groupId>com.mycompany</groupId>
            <artifactId>muledomain2</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <classifier>mule-domain</classifier>
            <scope>provided</scope>
        </dependency>
    </dependencies>
    ...
----


