= Raise Error Component
:keywords: mule, esb, studio, raise, error

This component will generate a link:mule-user-guide/v/4.0/mule-error-concept[Mule Error],
as if a failure had occurred, allowing you to customize its description and type.

The following example flow produces a `CONNECTIVITY` error and will result in a
500 response with body `Could not connect to backend.`.

.Example: XML Configuration of the Flow
[source,xml,linenums]
----
<flow name="raise-error-example-flow">
  <http:listener config-ref="HTTP_Listener_Configuration" path="/"/>
  <raise-error type="CONNECTIVITY" description="Could not connect to backend."/>
  <logger message="Never logged" level="INFO"/>
</flow>
----

== Raise Error Configuration

[%header,cols="1,1,2,2"]
|===
| Field | Value | Description | Example

| Description | String or DataWeave expression | Specifies the error description. |
`description="Invalid email. Cannot complete transaction."`

| Type | String | Specifies the type of the error. |
`type="ORDER:INVALID_DATA"`

|===

Note that you can only raise core errors, such as `SECURITY`, or custom ones.
A custom error features a specific error namespace that's not used elsewhere in
your app, meaning you cannot use `HTTP` as namespace if you are using HTTP operations,
for example.  

This raises an error with a dynamic description by using expressions and features
a custom type using the `ORDERS` namespace:

[source, xml, linenums]
----
 <raise-error description="#['Email ' ++ payload.email + ' is invalid. Cannot complete transaction.']" type="ORDER:INVALID_DATA"/>
----
