= About Reconnection Strategies
:keywords: anypoint, studio, reconnection strategies, reconnection strategy, retry policies, retry

Reconnection Strategies specify how a connector behaves when its connection fails.

These strategies allow you to better control the behavior of a failed connection. +
For example, you can configure a connector to re-attempt the connection only once every 15 minutes, and to give up after 30 attempts. You can also send an automatic notification to your IT administrator whenever this reconnection strategy goes into effect. You can even define a strategy that attempts to reconnect only during business hours.

By default, a reconnection strategy blocks a flow execution until it is able to connect/reconnect. +
You can enable a non-blocking reconnection strategy so your Mule application does not wait for all endpoints to re-connect before it restarts. Furthermore, if a connection is lost, the reconnection takes place on a thread separate from the application thread. +
Note that this behavior consumes more resources of your Mule application and might not be optimal in terms of performance.

When transactions are properly configured, any message being routed by Mule at the moment a reconnection strategy goes into effect is not dropped. Instead, the transaction is rolled back and only committed once the transport successfully reconnects via the reconnection strategy.

== See Also

* link:/mule-user-guide/v/4.0/reconnection-strategy-reference[Reconnection Strategy Reference]
// COMBAK: Enable transactions when available * link:/mule-user-guide/v/4.0/transactions-concept[About Transactions]
