= About Reconnection Strategies
:keywords: anypoint, studio, reconnection strategies, reconnection strategy, retry policies, retry

When a Mule app starts, a connectivity test runs on components that need to connect to an external server, such as the HTTP or FTP connector. If the test fails, the default behavior is to log a warning message and continue with the deployment of the app, instead of blocking the deployment.

You can modify this behavior by setting reconnection attempts and by forcing the deployment to fail when all connection attempts fail.

* Fail Deployment (`failsDeployment`): Forces the deployment to fail once the default or specified connection attempts are exhausted and end in failure.
+
Example that forces the deployment to fail after `5` unsuccessful reconnection attempts:
+
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
    <reconnection failsDeployment="true" >
      <reconnect frequency="4000" count="5" />
    </reconnection>
  </http:request-connection>
</http:request-config>
----
+
* Reconnect: Attempts to reconnect up to a specified number of times at a given interval. For example, you might set a `count` of `5` reconnection attempts at a `frequency` of every `4000` milliseconds (ms). Defaults to `2` reconnection attempts every `2000` ms.
* Reconnect Forever: Attempts to connect at a given interval, for example, every `4000` ms for as long as the app runs. Defaults to every `2000` ms.
+
Example that uses `reconnect-forever`:
+
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80" >
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connection>
----

== See Also

* link:/mule-user-guide/about-components[About Mule Components]
* link:/connectors/[Connectors and Modules]
