= To Download and Install Mule Runtime 4.0 EE

* Before downloading and installing Mule Runtime, make sure you have Java SE JDK 1.8 installed.

== To Download Mule 4

. Download the Mule 4 binary file from the Download Site and unzip it.
. Inside your extracted folder there is a mule directory. Set an environment variable called MULE_HOME to the mule directory inside your extracted folder.
// :: On Linux/Unix environments it would be:
// +
// [source,bash]
// ----
// export MULE_HOME=~/Downloads/mule-enterprise-standalone-4.0.0/
// ----
// +
// On Windows environments it would be:
// +
// [source,powershell]
// ----
// $env:MULE_HOME=C:\Downloads/mule-enterprise-standalone-4.0.0/
// ----

== To Start Mule 4 service

* You can run Mule Runtime Standalone by starting the mule service inside $MULE_HOME/bin/ directory.
** On Linux/Unix environments:
+
[source,bash]
----
> $MULE_HOME/bin/mule start
----
** On Windows environments:
+
[source,powershell]
----
> $MULE_HOME/bin/mule.bat start
----
* After Mule Runtime boots, you can deploy your Mule applications by moving your packaged JAR files to the apps directory on $MULE_HOME.

To stop Mule from running, press CTRL-C.

== See Also

* link:/anypoint-studio/v/7/to-download-and-install-studio[To Install Anypoint Studio 7.0]
* link:/mule-user-guide/v/4.0/mule-runtime-updates[What's New]
