= Scheduler XML Reference


A Scheduler follows the structure described below.

* A `scheduler` parent element that encloses the rest of the elements.
* A `scheduling-strategy` block inside it
* A `fixed-frequency` or `cron` element inside the scheduling-strategy` block , describing the behavior.


== Properties of `<fixed-frequency>`

[%header,cols="34,33,33"]
|===
|Attribute |Description |Example
|`frequency` |Triggering frequency, relative to time unit. When set to 0 or a negative value, it switches to the default. a|
----
frequency="1000"
----

|`timeUnit` a|
The time unit for the frequency and startDelay values.

MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS

 a|
----
timeUnit="MILLISECONDS"
----

|`startDelay` |Upon triggering the flow for the first time, Mule stalls the running of the scheduler for a specific amount of time. This time period is expressed in the same time units as the frequency. |`startDelay="0"`
|===

[source, xml, linenums]
----
<scheduler doc:id="0fcf8905-af22-4666-adcc-481b583eda67" doc:timestamp="" doc:name="Scheduler">
    <scheduling-strategy>
           <fixed-frequency frequency="5" timeUnit="SECONDS" startDelay="0"/>
    </scheduling-strategy>
</scheduler>

----

== Properties of `<cron>`



[%header,cols="4*"]
|===
|Parameter |Default Value |Description |Example
|`expression` |- |Use a cron expression for when to do a trigger. a|
----
expression="1 1 1 1,7 * ?"
----
|timeZone | Time zone passed as system property, or in machine's operating system. | Timezone in link:https://docs.oracle.com/javase/7/docs/api/java/util/TimeZone.html[java time zone] format  a|
----
timeZone="America/Argentina/Buenos_Aires"
----

|===

[source, xml, linenums]
----
<scheduler doc:id="0fcf8905-af22-4666-adcc-481b583eda67" doc:timestamp="" doc:name="Scheduler">
       <scheduling-strategy>
            <cron expression="1 1 1 1,7 * ?" />
       </scheduling-strategy>
</scheduler>
----

== See Also

* link:/mule-user-guide/v/4.0/scheduler-concept[About Scheduler]
