= About Scheduler

The Scheduler component allows you to trigger a flow based on a time condition. You can configure it to either trigger regularly at a constant frequency, or to follow a Cron condition.



The scheduler follows the timezone used by the machine where the Mule runtime is running. In case of deploying to a CloudHub worker, check the region of the worker.


== Fixed Frequency

You can set a Scheduler so that it triggers your flow at a regular interval. For this you can select a time unit, an amount and an initial delay before the first triggering occurs.


== Cron Expressions

Cron is a widely used standard for describing time and date. It can be used to signal a specific event that occurs just once, or a recurring event that might be yearly, monthly, weekly, daily, hourly, etc.

Here are a few sample Cron expressions:

[%header,cols="2*"]
|====
|Expression |Behavior
|0 15 10 * * * |Run at 10:15am every day
|0 15 10 * * ? 2005 |Run at 10:15am every day during the year 2005
|0 * 14 * * ? |Run every minute starting at 2pm and ending at 2:59pm, every day
|0 0/5 14 * * ? |Run every 5 minutes starting at 2pm and ending at 2:55pm, every day
|1 1 1 1,7 * ? |Run the first day of January and the first day of June, every year (in the first second of the first minute of the first hour) +
|====

[TIP]
There are a number of free online tools that can help you build cron expressions without needing to learn the syntax.




== See Also

* link:/mule-user-guide/v/4.0/scheduler-xml-reference[Scheduler XML Reference]
