= Set Payload
:keywords: anypoint studio, mule, set payload, payload

The Set Payload (`set-payload`) component lets you define the payload of the Message in a Mule Event. The payload can be a literal string or a DataWeave expression. You can access the payload value through a component such as the Logger by using the `payload` keyword.

[%header,cols="1,5"]
|===
| Field | Description

| Display Name (`doc:name`)
| Editable field for the name of the component.

| Value (`value`)
| Accepts a literal string or DataWeave expression that defines how to set the payload, for example, ``"some string"`` or `#[now()]`.

|===

This example sets the message payload to "Hello, World" and retrieves today's date using a DataWeave expression:
`#['Hello World!' ++ ' Today is ' ++ now()]`

XML example:
`<set-payload value="#['Hello World!' ++ ' Today is ' ++ now()]" doc:name="Set Payload" />`

Output:
`Hello World! Today is 2017-09-22T23:16:24.976-07:00`

== See Also

* link:/about-mule-message[Mule Message Structure]
* link:/dataweave[About DataWeave]
