= Set Payload
:keywords: anypoint studio, mule, set payload, payload

The Set Payload (`set-payload`) component lets you update the payload of the message.
The payload can be a literal string or a DataWeave expression. The `set-payload`
component, however, is not recommended for complex expressions or transformations
but rather simple ones, such as selections. The link:transform-component-about[Transform Component]
should be use in complex scenarios instead.

[%header,cols="1,1,5"]
|===
| Field | Usage | Description

| `value`
| Required
| Accepts a literal string or DataWeave expression that defines how to set the payload, for example, ``"some string"`` or `#[now()]`.

| `mimeType`
| Optional
| The mime type of the value assigned to the payload, e.g. `text/plain` or `application/json`.

|`encoding`
| Optional
| The encoding of the value assigned to the payload, for example, `UTF-8`.

|===

[WARNING]
--
The `mimeType` and `encoding` attributes will not affect a DataWeave expression
used as `value`, they will only affect the output Mule Message. If a transformation
 is required the DataWeave expression must contain an explicit output directive.
--

This XML example sets a payload with static values:

.Static Content Example:
[source,xml,linenums]
----
<set-payload value="{ 'name' : 'Ana', 'office' : 'BA' }" mimeType="application/json" encoding="UTF-8"/>
----

This example sets the message payload to "Hello, World" appending today's date using a DataWeave expression:
`#['Hello World!' ++ ' Today is ' ++ now()]`

.Expression Content Example:
[source,xml,linenums]
----
<set-payload value="#['Hello World!' ++ ' Today is ' ++ now()]"/>
----

== See Also

* link:about-mule-message[Mule Message Structure]
* link:dataweave[About DataWeave]
