= Set Payload
:keywords: anypoint studio, mule, set payload, payload

The Set Payload (`set-payload`) component lets you update the payload of the message. The payload can be a literal string or a DataWeave expression.

[%header,cols="1,5"]
|===
| Field | Description

| Display Name (`doc:name`)
| Editable field for the name of the component.

| Value (`value`)
| Accepts a literal string or DataWeave expression that defines how to set the payload, for example, ``"some string"`` or `#[now()]`.

|===

This example sets the message payload to "Hello, World" appending today's date using a DataWeave expression:
`#['Hello World!' ++ ' Today is ' ++ now()]`

XML example:
`<set-payload value="#['Hello World!' ++ ' Today is ' ++ now()]" doc:name="Set Payload" />`

Output:
`Hello World! Today is 2017-09-22T23:16:24.976-07:00`

This XML example sets a payload with static values:
`<set-payload value="{ 'name' : 'Ana', 'office' : 'BA' }" mimeType="application/json" encoding="UTF-8"/>`

This example sets the same payload using selectors in a DataWeave script. It assumes the `name` attribute is available as input to Set Payload.
`<set-payload value="#[output application/java --- payload.name]"/>`

== See Also

* link:about-mule-message[Mule Message Structure]
* link:dataweave[About DataWeave]
