= Smart Connectors
:keywords:

:toc:

== About Smart Connectors

A Smart Connector is a framework for creating Connectors that can then be used as part of a Mule application. It allows you to do so entirely in Mule DSL, taking advantage of knowledge that Mule developers already have.

Even for novice Mule runtime users will be simple, as there are just a few syntactic idoms around a Smart Connector such as the `<module>`, `<operation>s`, or `<parameter>s`. Below is a short snippet that defines a single operation in the `Math Smart Connector`:

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="Hello Smart Connector" minMuleVersion="4.0.0" ...>
  <operation name="say-hello" doc:description="Greets you!">
    <body>
      <mule:set-payload value="Hello World!"/>
    </body>
    <output type="string"/>
  </operation>
</module>
----

Its usage in a Mule `<flow>` element will be the same as any other connector, executing the flow `"random-flow"` will put the `"Hello World!"` value (result of executing the operation `<hello-smart-connector:say-hello>`) into the payload:
[source,xml,linenums]
----
<flow name="random-flow">
  <hello-smart-connector:say-hello>
</module>
----
A great advantage of building through Smart Connectors is its debugging capabilities, once created, a connector can be easily debuggable by any user as its internals are composed of either already known message processors (e.g.: `mule:set-payload`, `http:requester`, `mule:choice`, etc.) or unknown (e.g.: `sfdc:create`).

It is also worth of mentioning that a Smart Connector is strongly typed, which means every defined parameter for every operation is statically known, for both input and outputs.

== Basics of a Smart Connectors
The structure of a Smart Connector is composed by three distinctive and key elements that will delineate both behavior and contract of it: *operations*, *properties + global elements* and *module*.

=== Operation
An `<operation>`, similarly to a function, is a prescriptive way of defining a set of input parameters and a single output. Any given operation will have three well defined blocks: *input parameters*, *body* and *output*, similar to a function with the following conditions.

* *Input parameters*: declares a set of types to be entered when calling the operation. Keep in mind that these parameters are the only data the message processors within the `<body>` scope will be able to read.
* *Body*: a chain of message processors (e.g.: `mule:set-payload`, `http:requester`, `mule:choice`, etc.) to be executed.
* *Output*: declares the result of the `<body>` execution. Notice that the outcome of an operation is what was left behind as the payload in the current event.

Lets create a Smart Connector with a single operation that does the sum of two numbers
[source,xml,linenums]
----
<module name="Math Smart Connector"...>
  ...
  <operation name="sum" doc:description="Takes two numbers and returns the sum of them">
    <parameters>
      <parameter name="numberA" type="integer"/>
      <parameter name="numberB" type="integer"/>
    </parameters>
    <body>
      <mule:set-payload value="#[parameters.numberA + parameters.numberB]"/>
    </body>
    <output type="integer"/>
  </operation>
</module>
----
To invoke this from a Mule Application, we would need to do the following:
[source,xml,linenums]
----
<flow name="mule-flow">
  <math-smart-connector:sum numberA="10" numberB="5"/>
  <!-- payload here is 15 -->
</flow>
----

*<parameter> attributes*
|===
|name | use | default value | description

|name
|required
|NA
|Name of the `<parameter>`

|defaultValue
|optional
|NA
|If used, when invoking the current `<operation>` without any value for this `<parameter>`, it will take the default value.

|use
|required
|AUTO
| Set of defined uses for a given property/parameter. *REQUIRED* implies the property/parameter must be present. It can not be *REQUIRED* if the parameter/property has a defaultValue; *OPTIONAL* implies the property/parameter could be absent; *AUTO* will default at runtime to *REQUIRED* if defaultValue is absent, otherwise it will be marked as *OPTIONAL*.

|type
|required
|NA
|Defines the type of the `<parameter>` by using any primitive type such as *string*, *boolean*, *datetime*, *date*, *integer*, *time*, or it can also rely on any type defined in the catalog.

|password
|optional
|false
|Marks the `<parameter>` with `\****` in the UI.

|role
|required
|BEHAVIOUR
|Set of defined roles for a given parameter that modifies the generated XSD for the current `<parameter>`. *BEHAVIOUR* will render an attribute; *CONTENT* implies support for DataWeave in place as a child element; *PRIMARY* works similarly to *CONTENT* although it also implies it will map to the payload by default.

|doc:description
|optional
|NA
|Documentation of the current `<parameter>`
|===

Finally, the attribute `type=".."` of the `<output>` element is allowed to use `void` as a valid value, which will make the `<operation>` call not modify the event *despite* of putting values in the payload as described above.

=== Properties + Global elements
There will be cases where several operations will need to handle state between them, which is the case of a connector that handles session to an external API. A configuration of a Smart Connector is composed by two well defined elements: *properties* and *global elements*.

* *Properties*: similarly to the `<parameter>` exposed by operations, they are usually simple types to initialize elements of the Smart Connector or have default values for every operation.
* *Global Elements*: Mule link:https://docs.mulesoft.com/mule-user-guide/v/3.7/global-elements[Global elements], such as `<http:requester-config ../>`, to delegate connectivity to, allowing the use of any other connector in a Smart Connector.

The intention behind using a parametrization by properties is to expose just the right amount of values for a given Smart Connector, not "confusing" the consumer of it by setting lots of properties.
As a sample, lets imagine we create a Smart Connector that hits link:https://developer.github.com/v3/users/#get-the-authenticated-user[GitHub API V3] to retrieve an authenticated user:
[source,xml,linenums]
----
<module name="Github" minMuleVersion="4.0.0" ...>
  <property name="username" type="string" doc:description="Username credential."/>
  <property name="password" type="string" password="true" doc:description="Password credential"/>

  <httpn:request-config name="github-httpreq-config" basePath="/">
    <httpn:request-connection host="api.github.com" protocol="HTTPS" port="443">
      <httpn:authentication>
        <httpn:basic-authentication username="#[properties.username]" password="#[properties.password]"/>
      </httpn:authentication>
    </httpn:request-connection>
  </httpn:request-config>

  <operation name="get-user" doc:description="Lists public and private profile information when authenticated.">
    <body>
      <httpn:request config-ref="github-httpreq-config" path="user" method="GET"/>
    </body>
    <output type="string" doc:description="User information if logged properly."/>
  </operation>
</module>
----
To properly consume the previous Smart Connector, we would need something like the following in a Mule Application:
[source,xml,linenums]
----
<mule ...>
  <github:config name="lautaro-github-config" username="fernandezlautaro" password="****"/>
  <flow name="test-github-flow">
    <github:get-user config-ref="lautaro-github-config"/>
  </flow>
</mule>
----
Every execution of the `"test-github-flow"` will return, if provided with the correct credentials, the GitHub information of the authenticated user:
[source,json,linenums]
----
{
  "login": "fernandezlautaro",
  "id": 4719511,
  "avatar_url": "https://avatars1.githubusercontent.com/u/4719511?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/fernandezlautaro",
  ...
}
----
Or the error response from GitHub:
[source,json,linenums]
----
{
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3"
}
----
In this sample we are seeing how a `<property>` can be used in a global element as the `http:requester-config`, but it is also accessible from any `<operation>` within the `<module>` its defined.

*<property> attributes*
|===
|name | use | default value | description

|name
|required
|NA
|Name of the `<property>`

|defaultValue
|optional
|NA
|If used, when invoking the current `<module>` without any value for this `<property>`, it will take the default value.

|use
|required
|AUTO
| Set of defined uses for a given property/parameter. *REQUIRED* implies the property/parameter must be present. It can not be *REQUIRED* if the parameter/property has a defaultValue; *OPTIONAL* implies the property/parameter could be absent; *AUTO* will default at runtime to *REQUIRED* if defaultValue is absent, otherwise it will be marked as *OPTIONAL*.

|type
|required
|NA
|Defines the type of the `<property>` by using any primitive type such as *string*, *boolean*, *datetime*, *date*, *integer*, *time*, or it can also rely on any type defined in the catalog.

|password
|optional
|false
|Marks the `<parameter>` with `\****` in the UI.

|doc:description
|optional
|NA
|Documentation of the current `<parameter>`
|===

=== Module
The `<module>` element is the root element of the Smart Connector, which helds the responsibility of assembling the previous concepts in a single package.

*<module> attributes*
|===
|name | use | default value | description

|name
|required
|NA
|Name of the `<module>`

|category
|optional
|COMMUNITY
|There are different types of connectors in the platform. *COMMUNITY* does not requires an Enterprise Mule runtime to work with; *SELECT* requires an Enterprise Mule runtime to work with; *PREMIUM* requires an Enterprise Mule runtime to work with and also a plugin entitlement to work; *CERTIFIED* MuleSoft Certifierd connector and requires an Enterprise Mule runtime to work with

|vendor
|optional
|"MuleSoft"
|Vendor of the Smart Connector

|minMuleVersion
|required
|NA
|Defines the minimal Mule runtime version this Smart Connector runs on.

|prefix
|optional
|NA
|Expected prefix of the module to look for when generating the schemas. If left empty it will create a default one based on the Smart Connector's name attribute, by hyphenizing and escaping it.

|namespace
|optional
|NA
|Expected namespace of the module to look for when generating the schemas. If left empty it will default to http://www.mulesoft.org/schema/mule/<prefix>, where `<prefix>` is the attribute prefix attribute value.

|doc:description
|optional
|NA
|Documentation of the current `<parameter>`
|===

The way of importing the Smart Connector schema in a Mule Application is by using the `namespace` attribute, as the XML schemas are dynamically generated. Lets see how `namespace`, `prefix`, and `name` attributes work together.

*<module> provides `name`, `prefix` and `namespace`*
|===
|provided values | generated values

|`name="hello with spaces"`
|`name="hello with spaces"`

|`prefix="hello-prefix"`
|`prefix="hello-prefix"`

|`namespace="http://www.mulesoft.org/schema/a/different/path/mule/hello"`
|`namespace="http://www.mulesoft.org/schema/a/different/path/mule/hello"`
|===

*<module> provides `name` and `prefix`*
|===
|provided values | generated values

|`name="hello with spaces"`
|`name="hello with spaces"`

|`prefix="hello-prefix"`
|`prefix="hello-prefix"`

|NA
|`namespace=http://www.mulesoft.org/schema/mule/hello-prefix/current/mule-hello-prefix.xsd`
|===

*<module> provides just `name`*
|===
|provided values | generated values

|`name="hello with spaces"`
|`name="hello with spaces"`

|NA
|`prefix="hello-with-spaces"`

|NA
|`namespace=http://www.mulesoft.org/schema/mule/hello-with-spaces/current/mule-hello-with-spaces.xsd`
|===

The following Smart Connector will have just the `name="hello with spaces"`, which means that the `prefix` value will be dynamically generated from the `name`, ended up in `hello-with-spaces`, to which will create a dynamic `namespace` with the value of `http://www.mulesoft.org/schema/mule/hello-with-spaces/current/mule-hello-with-spaces.xsd` which means the Mule Application must have the a schema location pointing at a reference that matches to that value
[source,xml,linenums]
----
<module name="hello with spaces" minMuleVersion="4.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation=" ... ">
  <operation name="an-operation" />
</module>
----
The usage in a Mule Application will be:
[source,xml,linenums]
----
<mule xmlns="http://www.mulesoft.org/schema/mule/core"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:hello-with-spaces="http://www.mulesoft.org/schema/mule/hello-with-spaces"
      xsi:schemaLocation="
      http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
      http://www.mulesoft.org/schema/mule/hello-with-spaces http://www.mulesoft.org/schema/mule/hello-with-spaces/current/mule-hello-with-spaces.xsd">

    <flow name="some-flow">
        <hello-with-spaces:an-operation/>
    </flow>
</mule>
----

== Create a Smart Connector Project
In order to be able to create a Smart Connector, you need to have Maven previously installed.
Then, from a command line execute the following:
[source,json,linenums]
----
mvn archetype:generate                                       \
  -DarchetypeGroupId=org.mule.smart.connector                \
  -DarchetypeArtifactId=smart-connector-project-archetype    \
  -DarchetypeVersion=1.0.0-BETA-SNAPSHOT                     \
  -DgroupId=org.mule.smart.connector                         \
  -DartifactId=hello-smart-connector                         \
  -DmuleConnectorName=Hello
----
When prompted if the values are correct, press `enter` to continue. This maven archetype will create a stub project with the minimal amount of code to have a Smart Connector and a functional test to run it.
The structure will be something like the following:
[source,xml,linenums]
----
➜  ~ tree hello-smart-connector
hello-smart-connector
├── pom.xml
├── smart-connector
│   ├── pom.xml
│   └── src
│       └── main
│           └── resources
│               └── module-Hello.xml // <1>
└── smart-connector-it
    ├── mule-application.json
    ├── pom.xml
    └── src
        ├── main
        │   └── mule
        │       └── mule-config.xml
        └── test
            └── munit
                └── assertion-munit-test.xml // <2>

10 directories, 7 files
➜  ~
----
The resource (1) `hello-smart-connector/smart-connector/src/main/resources/module-Hello.xml` defines the Smart Connector root element and the (2) `hello-smart-connector/smart-connector-it/src/test/munit/assertion-munit-test.xml` an assertion operation that calls the Smart Connector operation.

Running `mvn clean install` in the `hello-smart-connector` folder will create the plugin for the `Hello Smart Connector` and it will also run the suite through MUnit for the operation defined in the connector.
[source,xml,linenums]
----
➜  hello-smart-connector mvn clean install
 ...
 ..
 .
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Parent POM Hello Smart Connector and Mule App integration test SUCCESS [  0.142 s]
[INFO] Hello Smart Connector .............................. SUCCESS [  4.540 s]
[INFO] Hello Smart Connector Mule Application Integration Test SUCCESS [ 33.389 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.166 s
[INFO] Finished at: 2017-06-14T22:07:42-03:00
[INFO] Final Memory: 61M/928M
[INFO] ------------------------------------------------------------------------
➜  hello-smart-connector
----
[NOTE]
Due to small issues with Aether and how MUnit works, building the `hello-smart-connector` might produce a `FAILURE` in the `Hello Smart Connector Mule Application Integration Test` project.
If that happens, then to fix it just run `mvn clean install` from the subfolder `smart-connector-it` rather than the parent `hello-smart-connector` folder.


== Relying on other Connectors
We previously show that it is possible to leverage code into a working connector from a Smart Connector, which is quite similar to what happens in a Mule Application.
In order to properly consume other connector from within a Smart Connector is:

*1)* Add the dependency into the Smart Connector POM file.
Lets say a specific connector needs the HTTP Connector and the OAuth module, then it needs to add the following dependencies into the Smart Connector:
[source,xml,linenums]
----
<dependencies>
  <dependency>
    <groupId>org.mule.connectors</groupId>
    <artifactId>mule-http-connector</artifactId>
    <version>0.8.0-SNAPSHOT</version>
    <classifier>mule-plugin</classifier>
    <scope>compile</scope>
  </dependency>
  <dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-oauth-module</artifactId>
    <version>0.8.0-SNAPSHOT</version>
    <classifier>mule-plugin</classifier>
    <scope>compile</scope>
  </dependency>
</dependencies>
----
*2)* Add the proper schema location into the `<module>` root element.
[source,xml,linenums]
----
<module name="Hello Smart Connector" prefix="module-hello" minMuleVersion="4.0.0-BETA-SNAPSHOT"
    ...
    xmlns:httpn="http://www.mulesoft.org/schema/mule/http"
    xmlns:oauth="http://www.mulesoft.org/schema/mule/oauth"
    xsi:schemaLocation=" ...
 http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd
 http://www.mulesoft.org/schema/mule/oauth http://www.mulesoft.org/schema/mule/oauth/current/mule-oauth.xsd">
 ...
  <!-- use of the HTTP and OAuth connector -->
</module>
----

== Smart Connectors' Catalog
The provided types for either a `<property>`/`<parameter>` are just some primitive types: *string*, *boolean*, *datetime*, *date*, *integer*, *time*.

There are other scenarios where it is possible to define types much more complex types than those, to which we provide a way to inject a custom catalog with predefined types. To do so, we will create a file `hello-smart-connector/smart-connector/src/main/resources/module-Hello-catalog.xml` with the following content:
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<types:mule xmlns="http://www.mulesoft.org/schema/mule/core"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:types="http://www.mulesoft.org/schema/mule/types">
    <types:catalog>
        <types:type name="PersonXsdType" location="./person-schema.xsd" element="{http://uri}Person"/>
        <types:type name="PersonJsonType" location="./person-schema.json"/>
    </types:catalog>
</types:mule>
----
Under `hello-smart-connector/smart-connector/src/main/resources/` we will also create two more files. The `hello-smart-connector/smart-connector/src/main/resources/person-schema.xsd` (same name defined in the catalog) with the following content:
[source,xml,linenums]
----
<xs:schema targetNamespace="http://uri" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Person">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="name"/>
        <xs:element type="xs:string" name="lastName"/>
        <xs:element type="xs:integer" name="age"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
----
The `hello-smart-connector/smart-connector/src/main/resources/person-schema.json` (same name defined in the catalog) with the following content:
[source,json,linenums]
----
{
  "type": "object",
  "properties": {
    "age": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "lastname": {
      "type": "string"
    }
  },
  "additionalProperties": false
}
----
The structure of the `tree hello-smart-connector/smart-connector` folder will be as follow:
[source,json,linenums]
----
➜  ~ tree hello-smart-connector/smart-connector
hello-smart-connector/smart-connector
├── pom.xml
└── src
    └── main
        └── resources
            ├── module-Hello-catalog.xml
            ├── module-Hello.xml
            ├── person-schema.json
            └── person-schema.xsd
----
Once placed, we can start leveraging `type`s to the defined ones in the catalog as well as the primitive ones (*string*, *integer*, *boolean*, etc.), which in this scenario are `PersonXsdType` and `PersonJsonType` by just adding an operations such as:
[source,xml,linenums]
----
<module name="Hello Smart Connector" prefix="module-hello" minMuleVersion="4.0.0-BETA-SNAPSHOT" ... >
  ...
  <operation name="person-xml-to-json" doc:description="Takes a Person in XML format and translates it to JSON">
    <parameters>
      <parameter name="content" type="PersonXsdType"/>
    </parameters>
    <body>
      <ee:transform>
        <ee:set-payload><![CDATA[
          %dw 2.0
          %output application/json encoding='UTF-8'
          ---
          {
            "name" : parameters.content.person.name,
            "lastname" : parameters.content.person.lastName,
            "age" : parameters.content.person.age as Number
          }
          ]]></ee:set-payload>
      </ee:transform>
    </body>
    <output type="PersonJsonType"/>
  </operation>
  <operation name="person-json-to-xml" doc:description="Takes a Person in JSON format and translates it to XML">
    <parameters>
      <parameter name="content" type="PersonJsonType"/>
    </parameters>
    <body>
      <ee:transform>
        <ee:set-payload><![CDATA[
          %dw 2.0
          %output application/xml
          ---
          person : parameters.content
          ]]></ee:set-payload>
      </ee:transform>
    </body>
    <output type="PersonXsdType"/>
    </operation>
<module/>
----
Notice that to use DataWeave we would also need to add an extra dependency to our Smart Connector, so that when reading the `<ee:transform ..>` the mandatory schema (`mule-ee.xsd`) can be found:
[source,xml,linenums]
----
<dependency>
    <groupId>com.mulesoft.mule.runtime.modules</groupId>
    <artifactId>mule-module-spring-config-ee</artifactId>
    <version>${mule.version}</version>
    <scope>provided</scope>
</dependency>
----
To use the above operations, we would need to properly feed the values and execute them as follow:
[source,xml,linenums]
----
<mule ...>
  <flow name="person-xml-2-json-flow">
    <!-- create a XML Person and store it in the payload -->
    <ee:transform>
      <ee:set-payload><![CDATA[
        %dw 2.0
        %output application/xml
        ---
        person : {
          name : "Lautaro",
          lastName: "Fernandez",
          age : 54
        }
        ]]></ee:set-payload>
    </ee:transform>
    <!-- call the operation -->
    <module-hello:person-xml-to-json content="#[payload]"/>
    <!-- at this point, the payload is a JSON Person -->
  </flow>

  <flow name="person-json-2-xml-flow">
    <!-- create a JSON Person and store it in the payload -->
    <ee:transform>
      <ee:set-payload><![CDATA[
        %dw 2.0
        %output application/json
        ---
        {
          name : "Lautaro",
          lastName: "Fernandez",
          age : 54
        }
        ]]></ee:set-payload>
    </ee:transform>
    <!-- call the operation -->
    <module-hello:person-json-to-xml content="#[payload]"/>
    <!-- at this point, the payload is a XML Person -->
  </flow>
</mule>
----
It might be common that for parameterizing values that are not primitive types, the defined `<operation>` declare them as `role="CONTENT"` so that it won't be mandatory to use an extra processor in the `<flow>` to call the operation. Taking the `person-xml-to-json` operation, we will add the extra attribute to the `content` parameter:
[source,xml,linenums]
----
<module name="Hello Smart Connector" prefix="module-hello" minMuleVersion="4.0.0-BETA-SNAPSHOT" ... >
  ...
  <operation name="person-xml-to-json" doc:description="Takes a Person in XML format and translates it to JSON">
    <parameters>
      <parameter name="content" type="PersonXsdType" role="CONTENT"/>
    </parameters>
    <body>
      <ee:transform>
        <ee:set-payload><![CDATA[
          %dw 2.0
          %output application/json encoding='UTF-8'
          ---
          {
            "name" : parameters.content.person.name,
            "lastname" : parameters.content.person.lastName,
            "age" : parameters.content.person.age as Number
          }
          ]]></ee:set-payload>
      </ee:transform>
    </body>
    <output type="PersonJsonType"/>
  </operation>
  ...
<module/>
----
To use the above operations, we would need to properly feed the values and execute them as follow:
[source,xml,linenums]
----
<mule ...>
  <flow name="person-xml-2-json-using-content-flow">
    <!-- call the operation -->
    <module-hello:person-xml-to-json>
      </module-hello:content><![CDATA[
        %dw 2.0
        %output application/xml
        ---
        person : {
          name : "Lautaro",
          lastName: "Fernandez",
          age : 54
        }]]>
      </module-hello:content>
    </module-hello:person-xml-to-json>
    <!-- at this point, the payload is a JSON Person -->
  </flow>
  ..
</mule>
----

== Smart Connectors' Working Samples
In *https://github.com/mulesoft-labs/smart-connectors-integration-tests* there are more samples with different types of Smart Connectors (depending on DataWeave, HTTP Connector, File Connector, Validation Module, etc.) with some Mule Applications that depend on them:

=== Using Core Components
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-core[smart-connectors/smart-connector-using-core]`: depends on just core components, e.g.: `mule:set-payload`
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-core"
        minMuleVersion="4.0.0"
        doc:description="This module relies entirely in runtime provided components (no other Plugin dependencies)"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:mule="http://www.mulesoft.org/schema/mule/core"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd">

    <operation name="set-payload-hardcoded" doc:description="Sets the payload to the String value 'Wubba Lubba Dub Dub'">
        <body>
            <mule:set-payload value="Wubba Lubba Dub Dub"/>
        </body>
        <output type="string" doc:description="Payload's output"/>
    </operation>

    <operation name="set-payload-hardcoded-two-times" doc:description="Sets the payload to the String value 'Wubba Lubba Dub Dub'">
        <body>
            <mule:set-payload value="Wubba Lubba Dub Dub"/>
            <mule:set-payload value="#[payload ++ 'Dub Dub']"/>
        </body>
        <output type="string" doc:description="Payload's output"/>
    </operation>

 </module>
----
=== Using JSON custom types
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-custom-types-json[smart-connectors/smart-connector-using-custom-types-json]`: depends on JSON types
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-custom-types-json"
        minMuleVersion="4.0.0"
        doc:description="This module relies entirely in runtime provided components (no other Plugin dependencies)"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:mule="http://www.mulesoft.org/schema/mule/core"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd">

    <operation name="set-payload-hardcoded" doc:description="Sets the payload to the String value 'Wubba Lubba Dub Dub'">
        <body>
            <mule:set-payload value="Wubba Lubba Dub Dub"/>
        </body>
        <output type="a-custom-type" doc:description="Payload's output"/>
    </operation>
 </module>
----
Catalog
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<types:mule xmlns="http://www.mulesoft.org/schema/mule/core"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:types="http://www.mulesoft.org/schema/mule/types">

    <types:catalog>
        <types:type name="a-custom-type" location="./a-custom-type-schema.json"/>
    </types:catalog>

</types:mule>
----
Schema
[source,xml,linenums]
----
{
  "type": "object",
  "properties": {
    "number": {
      "type": "number"
    },
    "street_name": {
      "type": "string"
    },
    "street_type": {
      "type": "string",
      "enum": [
        "Street",
        "Avenue",
        "Boulevard"
      ]
    }
  },
  "additionalProperties": false
}
----
=== Using XML custom types
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-custom-types-xsd[smart-connectors/smart-connector-using-custom-types-xsd]`: depends on XML types
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-custom-types-xsd"
        minMuleVersion="4.0.0"
        doc:description="This module relies entirely in runtime provided components (no other Plugin dependencies)"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:mule="http://www.mulesoft.org/schema/mule/core"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd">

    <operation name="operation-with-custom-types">
        <parameters>
            <parameter name="value" type="XsdType1"/>
        </parameters>
        <body>
            <mule:set-payload value="hello world!"/>
        </body>
        <output type="string"/>
    </operation>

 </module>
----
Catalog
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<types:mule xmlns="http://www.mulesoft.org/schema/mule/core"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:types="http://www.mulesoft.org/schema/mule/types">

    <types:catalog>
        <types:type name="XsdType1" location="./type1-schema.xsd" element="Root"/>
    </types:catalog>

</types:mule>
----
Schema 1
[source,xml,linenums]
----
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Root">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    A user with all the information
                </xs:documentation>
            </xs:annotation>
            <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:element type="xs:string" name="lastName"/>
                <xs:element type="xs:boolean" name="male"/>
                <xs:element type="xs:integer" name="age"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
----
=== Using DataWeave
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-dw[smart-connectors/smart-connector-using-dw]`: depends on DataWeave, e.g.: `ee:transform`
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-dw"
        minMuleVersion="4.0.0"
        doc:description="This module relies entirely in runtime provided components (no other Plugin dependencies) and DW"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:mule="http://www.mulesoft.org/schema/mule/core"
        xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
           http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd">

    <operation name="set-payload-through-dw" doc:description="Sets the payload to the String value 'Wubba Lubba Dub Dub'">
        <body>
            <ee:transform>
                <ee:set-payload><![CDATA[
                    %dw 2.0
                    %output application/json encoding='UTF-8'
                    ---
                    'Wubba Lubba Dub Dub'
            ]]></ee:set-payload>
            </ee:transform>
        </body>
        <output type="string" doc:description="Payload's output"/>
    </operation>
 </module>
----
=== Using File Connector
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-file[smart-connectors/smart-connector-using-file]`: depends on File Connector, e.g.: `file:list`
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-file"
        minMuleVersion="4.0.0"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:file="http://www.mulesoft.org/schema/mule/file"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/file http://www.mulesoft.org/schema/mule/file/current/mule-file.xsd">

    <property name="workingDir" type="string"/>
    <property name="filenamePattern" type="string"/>

    <file:config name="file">
        <file:connection workingDir="#[properties.workingDir]"/>
    </file:config>
    <file:matcher name="globalMatcher" directories="REQUIRE" filenamePattern="#[properties.filenamePattern]" />

    <operation name="list">
        <parameters>
            <parameter name="path" type="string"/>
        </parameters>
        <body>
            <file:list directoryPath="#[parameters.path]" config-ref="file" matcher="globalMatcher"/>
        </body>
        <output type="string"/>
    </operation>

 </module>
----
=== Using HTTP Connector
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-http[smart-connectors/smart-connector-using-http]`: depends on HTTP Connector, e.g.: `http:requester`
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-http"
        minMuleVersion="4.0.0"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:mule="http://www.mulesoft.org/schema/mule/core"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
        xmlns:httpn="http://www.mulesoft.org/schema/mule/http"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
           http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd">

    <property name="username" type="string" doc:description="the login user credential."/>
    <property name="password" type="string" password="true" doc:description="the login password credential"/>

    <httpn:request-config name="github-httpreq-config" basePath="/">
        <httpn:request-connection host="api.github.com" protocol="HTTPS" port="443">
            <httpn:authentication>
                <httpn:basic-authentication username="#[properties.username]" password="#[properties.password]"/>
            </httpn:authentication>
        </httpn:request-connection>
    </httpn:request-config>

    <operation name="search-issues" doc:description="Get a list of Issue objects that match the specified filter data">
        <parameters>
            <parameter name="repo" type="string" doc:description="the repository name"/>
            <parameter name="since" type="string" defaultValue="2017-02-06T09:29:49Z" doc:description="date from which restoring issues, sample: 2016-07-31T12:37:07Z"/>
        </parameters>
        <body>
            <mule:logger level="ERROR" doc:name="Logger" message="#['repo:[' ++ parameters.repo + '], since:[' + parameters.since ++']']" />
            <httpn:request config-ref="github-httpreq-config" path="search/issues" method="GET" >
                <httpn:query-params>
                    #[{q : 'repo: $(parameters.repo) created:>=$(parameters.since)', type: 'Issues'}]
                </httpn:query-params>
            </httpn:request>
            <mule:set-payload value="#[payload]" mimeType="application/json" />
        </body>
        <output type="string" doc:description="List of issues"/>
    </operation>

 </module>
----
=== Using other Smart Connector
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-smart-connector[smart-connectors/smart-connector-using-smart-connector]`: depends on another Smart Connector (particularly, it relies on the first one of this set of samples)
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-smart-connector"
        minMuleVersion="4.0.0"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:module-using-core="http://www.mulesoft.org/schema/mule/module-using-core"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/module-using-core http://www.mulesoft.org/schema/mule/module-using-core/current/module-using-core.xsd">

    <operation name="proxy-set-payload-hardcoded">
        <body>
            <module-using-core:set-payload-hardcoded/>
        </body>
        <output type="string"/>
    </operation>

 </module>
----
=== Using Validation Module
Location `link:https://github.com/mulesoft-labs/smart-connectors-integration-tests/tree/master/smart-connectors/smart-connector-using-validation[smart-connectors/smart-connector-using-validation]`: depends on Validation Module, e.g.: `validation:is-email`
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-using-validation"
        minMuleVersion="4.0.0"

        xmlns="http://www.mulesoft.org/schema/mule/module"
        xmlns:validation="http://www.mulesoft.org/schema/mule/validation"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           http://www.mulesoft.org/schema/mule/module http://www.mulesoft.org/schema/mule/module/current/mule-module.xsd
           http://www.mulesoft.org/schema/mule/validation http://www.mulesoft.org/schema/mule/validation/current/mule-validation.xsd">

    <operation name="is-really-email">
        <parameters>
            <parameter name="inputEmail" type="string"/>
        </parameters>
        <body>
            <validation:is-email email="#[parameters.inputEmail]"/>
        </body>
        <output type="boolean"/>
    </operation>

 </module>
----


== Smart Connector Mule BETA limitations
The following issues/limitations will be fixed for Mule runtime GA:

* A Smart Connector that depends on other Smart Connector won't be properly rendered in the UI (neither Studio or Flow Designer), although it will work in the runtime (can be used with XML editing of the Mule Application).
* Custom types will only work for XML and JSON schemas (RAML types will be for Mule runtime GA).
* There's no support for test connection
* UI Creation support: Studio doesn't support creation of Smart Connectors right now, but properly displays them as any other connector.
* Type support will be improved, where *string*, *boolean*, *datetime*, *date*, *integer*, *time* will be dropped to support the link:https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#raml-data-types[RAML Types], which contains the current Smart Connectors support for primitive types and many others (e.g.: float, double, number, object, array, etc.)

== Smart Connector limitations
The following items are limitations that might be supported in a future, but they are not planned:

* Support inbound operations. Smart Connectors will only provide outbound operations, not sources (aka:`<scheduler>`), neither routers.
* Operations will not support recursive calls.

== See Also
???
