= About Streaming in Mule 4.0

Mule 4.0 handles data streaming using Repeatable Streams. As the Stream is consumed by a component, its content is saved into a temporal buffer. The runtime does not keep track of every Stream generated by either an operation nor an Event source.

This way, when streaming, Mule 4.0 feeds each component that receives a type of stream from the temporal buffer, making sure that each component receives the full stream, regardless of how much of the stream was already consumed by any prior component. +
Repeatable streams also allow concurrent access, so any number of concurrent threads can safely access the streamed data.

This enables Mule 4.0 to allow:

* Reading a stream more than once.
* Concurrent access to the stream.

Every component in Mule 4.0 that returns an InputStream or a Streamable collection support repeatable streams.
These components are:

* File Connector
* FTP Connector,
* DataBase Connector
* HTTP Connector
* Sockets

You can configure different streaming strategies to set how their streamed content is consumed.


== See Also

* link:/mule-user-guide/v/4.0/streaming-strategies-concept[About Streaming Strategies]
* link:/mule-user-guide/v/4.0/streaming-strategies-reference[Streaming Strategies Reference]
