= About Streaming Strategies

// COMBAK: Add Examples and Add Screenshots.

== File Stored Repeatable Stream

This is the default streaming strategy in Mule Runtime Enterprise Edition. It uses a temporary file to provide repeatable access to any input stream. +
It initially uses an in-memory buffer size of 512 KB. If the stream is larger than that, it creates a temporary file on your disk to store the contents without overflowing your memory.

When you know you need to deal with large or small files, you can change the buffer size to optimize performance. +
Configuring a bigger buffer size increases performance by avoiding the number of times the runtime needs to write the buffer to your disk. The same way, configuring a smaller buffer size saves you memory load. You can even set the buffer's unit of measurement, so you don't have to go through unit conversions.

For example, if you know that you are going to read a file that's always around 1 MB size, you can configure a 1 MB buffer:

[source,xml,linenums]
----
<file:read path="bigFile.json">
  <repeatable-file-store-stream
    InMemorySize="1"
    bufferUnit="MB"/>
</file:read>
----

Or if you know you are always processing a file no bigger than 10 KB, you can save memory:

[source,xml,linenums]
----
<file:read path="smallFile.json">
  <repeatable-file-store-stream
    InMemorySize="10"
    bufferUnit="KB"/>
</file:read>
----

Based on performance test, the default configuration of this strategy does not significantly impact performance in most scenarios.

[NOTE]
This option is only available on Mule EE

== In Memory Repeatable Stream

This configuration is the default for Mule Runtime Community Edition. It uses an in-memory buffer to provide repeatable access to any input stream. It uses a default configured buffer size of 512 KB. If the stream is larger than that, the buffer is expanded to another 512 KB.

You can customize this behavior by setting the initial size of the buffer, the rate at which the buffer increases, the maximum buffer size, and the measurement unit. +
For example, these settings configure an in-memory repeatable stream with a 512 KB initial size, which grows at a rate of 256 KB and allows up to 2 MB of content in memory:

[source,xml,linenums]
----
<file:read path="exampleFile.json">
  <repeatable-in-memory-stream
    initialBufferSize="512"
    bufferSizeIncrement="256"
    maxInMemorySize="2000"
    bufferUnit="KB"/>
</file:read>
----

== Non Repeatable Stream

This strategy allows you to use the plain old streams, where an input stream can only be read once and does not allow concurrent access from concurrent threads.

For example, if you don't need to set any kind of buffer for your stream, you can set a non-repeatable streaming strategy:

[source,xml,linenums]
----

<file:read path="exampleFile.json">
  <non-repeatable-stream />
</file:read>

----

This strategy is not suitable for scenarios in which the stream needs to be consumed more than once.

== See Also

* link:/mule-user-guide/v/4.0/streaming-about[About Streaming]
* link:/mule-user-guide/v/4.0/streaming-strategies-reference[Streaming Strategies Reference]
