= About Streaming in Mule 4.0

Traditionally, when a component reads a stream of data, that stream cannot be either processed, nor accessed concurrently by another component. +
This is because data streams cannot be consumed more than once and cannot be consumed at the same time.

For example, if a JSON payload is transferred from an Event Source to a File connector with a write operation, the stream would be consumed by the File connector, and the payload would not be available for being processed by any other module. +
However, Mule 4.0 handles data streaming using Repeatable Streams. As the Stream is consumed by a component, its content is saved into a temporal buffer.

This all happens automatically, so no special configuration is needed from your end.

Repeatable Streams enable you to:

* Read a stream more than once.
* Have concurrent access to the stream.

When streaming, Mule 4.0 feeds each component that receives a type of stream from the temporal buffer, making sure that each component receives the full stream, regardless of how much of the stream was already consumed by any prior component. +
Repeatable streams also allow concurrent access, so any number of concurrent threads can safely access the streamed data.



This way, a Mule 4.0 application can transfer the JSON payload from an HTTP listener, write it to a file using a File Connector, and then could use another File connector to write the JSON in another file. +
It could also process the JSON payload through a Scatter-Gather router and allow the stream to be processed by different processor chains simultaneously.

Every component in Mule 4.0 that returns an InputStream or a Streamable collection supports repeatable streams.
These components are:

* File Connector
* FTP Connector
* DataBase Connector
* HTTP Connector
* Sockets

You can configure different streaming strategies to set how their streamed content is consumed.


== See Also

* link:/mule-user-guide/v/4.0/streaming-strategies-concept[About Streaming Strategies]
* link:/mule-user-guide/v/4.0/streaming-strategies-reference[Streaming Strategies Reference]
