= TLS Configuration
:keywords: tls, trust, store, https, ssl, secure messages, encryption, trust store, key store, keystore, truststore

Mule Runtime 4.x supports Transport Layer Security (TLS) 1.1/1.2. 
TLS is a cryptographic protocol that provides communications security for your Mule app. TLS offers many different ways of exchanging keys, encrypting data, and authenticating message integrity. This topic describes the methods supported by Mule and how to configure TLS in Mule apps.

You configure the tls:context element in the Mule XML configuration file to set up TLS. This element is independent of any module or transport. For example, you can configure TLS for use with HTTP (server and client), FTPS (client), Email (client), Sockets (client).

The following examples show how to set up TLS.

== FTPS Example

The following example secures a client by setting up a trust store:

[source, xml, linenums]
----
<ftps:config name="ftps">
    <ftps:connection username="anonymous" password="password" host="localhost" port="${ftpPort}" workingDir="${workingDir}">
        <tls:context >
            <tls:trust-store path="${trustStorePath}" password="mulepassword" />
        </tls:context>
    </ftps:connection>
</ftps:config>
----

== HTTP Listener

The following example secures a server by setting up a keystore:

[source, xml, linenums]
----
<http:listener-config name="nestedConfig">
    <http:listener-connection protocol="HTTPS" host="localhost" port="${port2}">
        <tls:context>
            <tls:key-store path="tls/ssltest-keystore.jks" keyPassword="changeit" password="changeit"/>
        </tls:context>
    </http:listener-connection>
</http:listener-config>
----

== Two-Way TLS Authentication

The following example sets up two-way, or mutual, authentication, described later in this document. 

[source, xml, linenums]
----
<http:listener-config name="nestedConfig">
    <http:listener-connection protocol="HTTPS" host="localhost" port="${port2}">
        <tls:context>
            <tls:trust-store path="tls/ssltest-cacerts.jks" password="changeit"/>
            <tls:key-store path="tls/ssltest-keystore.jks" keyPassword="changeit" password="changeit"/>
        </tls:context>
    </http:listener-connection>
</http:listener-config>
----

== Disabling Validations

Using the insecure property, described later in this document, you can disable validations for prototyping and development. Not recommended for use otherwise.

[source, xml, linenums]
----
<tls:context>
    <tls:trust-store path="tls/ssltest-cacerts.jks" password="changeit" insecure="true"/>
</tls:context>
----

== Adding Additional Cipher Suites and Protocol Restrictions

[source, xml, linenums]
----
<tls:context name="tlsClientContext" enabledProtocols="TLSv1.2" enabledCipherSuites="TLS_DHE_DSS_WITH_AES_128_CBC_SHA256">
    <tls:trust-store path="tls/trustStore" password="mulepassword"/>
</tls:context>
----

For more information about configuring TLS, see the XML reference later in this document.

== Keystores and Truststores

A TLS service needs to have a private key and a public certificate. The private key never leaves the server. The public certificate is exposed through TLS. Clients can verify that they trust the server.

There is no default Java keystore in the standard JDK distribution, so you must generate your own key. You likely already have corporate certificates for your client apps and don't need to create them. Often, these certificates work with the JRE truststore, so no set up is required for the client app.

A well-known Certificate Authority (CA) can generate certificates, or you can generate a certificate locally without external approval (self-signed certificate). A truststore stores certificates from trusted CAs that the client uses to verify a certificate presented by the server. 

You import certificates and private keys into a keystore file that Mule uses. Truststore files are also keystores that by convention include only public certificates of trusted servers.

The tls:trust-store and tls:key-store elements in a Mule configuration can reference a specific certificate and key, but if you don't provide a values for the trust-store, Mule uses the default Java truststore. Java updates the default truststore when you update Java, so getting regular updates is recommended to keep well-known CA certificates up-to-date.

Mule supports many types of keystores, including the following ones:

* JCEKS
* PKCS12
* JKS

The keystore type is configurable at the JRE level.

If you already have a corporate certificate to use for your client app, it might work with the JRE trust store. In this case, there is nothing to set up. To generate your own certificates, you can use the Java Keytool. For more information, see Oracle documentation:

`+https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html+`

=== Generating a Keystore

You can use the Oracle keytool to generate the keystore and perform the other tasks mentioned in this procedure.

. Generate a keystore that exposes your server's credentials. 
+
The generated keystore contains a private key and a public certificate. This certificate is self signed so it is not be trusted by clients unless you share the public certificate with them.
+
Keytool generates certificates using the DSA algorithm by default. You can instead specify it to use the RSA algorithm.
. Export the server's certificate from the keystore to share with clients.
+
The standard JDK distribution does not include a keystore by default, so you generate your own.
+
If you also want to get the certificate signed by a Certification Authority (CA), you export your certificate in the standard CSR format. You specify the name you want to give to your certificate file. You send the CSR file to the CA and follow their instructions to obtain their signature. After you have obtained the CA's signature, you can import the signed certificate file.
+
The alias you assign when importing must not be linked to any existing key or the process fails.

=== Generating a Trust Store

The standard JRE distribution includes a default trust store with certificates for several major certificate authorities (CA's) which is used by default in the 'tls:trust-store' element, but you can generate your own if you want to have greater security or if you use self-signed certificates.

To create a trustStore, you can use the Oracle Java keytool.

The client trusts the server if a chain of trust can be established, either directly to the server (in case its certificate is in the truststore) or through a signing CA whose certificate is present in the truststore; otherwise, the connection fails. A trust store must be defined when using self-signed certificates.

== Configuring TLS

Adding a truststore or a keystore to a TLS configuration implicitly implements the one of the following forms of authentication:

* Truststore: Security based on certificates from a CA
* Keystore: Security based on a private key and self-signed certificate

Adding both a keystore and a trust store to the configuration implicitly implements two-way TLS authentication, also known as mutual authentication.

Trust store contents differ depending on its location:

* Server side: the trust store contains certificates of the trusted clients.
* Client side: the trust store contains certificates of the trusted servers.

The keystore contains the private and public key of the server.

The keystore might contain two passwords, as one of them can serve to access the entire keystore file. The other (keyPassword) can serve to access the server’s private key, which is inside this file.

=== Configuration for Sending a Request

If the `tls:context` is empty (no key-store or trust-store defined), then the default values of the JVM are used, which likely already include a trust store with certificates for all the major certifying authorities.

If the client requires a certificate from the server that it is trying to connect to, then the `<tls:trust-store>` element must be added. Set the path field set to the location of the truststore file that contains the certificates of the trusted servers.

If the server validates certificates from the clients, then the `<tls:key-store>` element should be also added with the path field set to the location of the keystore file that contains the private/public keys of the client.


=== Configuration for Listening for a Request

The `tls:context` is required to contain a `tls:key-store` element to listen for a request using a secure connection  (HTTPS). You set the path field to the location of the keystore file that contains the private/public keys of the server.

If the server needs to validate certificates from clients, you need to add a `tls:trust-store` element. You set the path field to the location of the trust store file that contains the certificates of the trusted clients.

== Protocols and Cipher Suites

When a TLS communication takes place between two systems, a negotiation determines which protocol and cipher suite are used. 

You can configure protocols and cipher suites in the Mule `/conf` directory in `$MULE_HOME. $MULE_HOME` is the directory where your Mule installation resides, for example `/opt/mule-4.0`. Select one of two files for fine-tuning the configuration by manually setting which cipher suites and protocols Mule will use:

* tls-default.conf
+
Allows fine-tuning when Mule is not configured to run in Federal Information Processing Standards (FIPS) security mode.
+
* tls-fips140-2.conf
+
Allows fine-tuning when Mule is running in FIPS security mode.

Open the relevant file and comment or uncomment items in the lists to manually configure the allowed cipher suites and SSL protocols. If you make no changes to these files, Mule allows the configured security manager to select cipher suites and protocols.

The list of protocols and cipher suites that you set in these configuration files can then be constrained locally by what is set up in an individual `tls:context` element if those parameters are defined.

Only those protocols and cipher suites enabled on both ends can be used. 

If you do not configure protocols and cipher suites, the default Java environment protocol and cipher suites are used.

If you configure multiple protocols and cipher suites in the global TLS configuration file, you can then specify a subset in the tls:context element for use by TLS. You configure the protocols and cipher suites in the enabledProtocols and enabledCipherSuites in the tls:context element.

In the tls:context element, you cannot reference protocols or cipher suites here that are not included in your global TLS configuration file. In the tls:context element, you can set enabledProtocols and enabledCipherSuites to the value `default`. In this case, TLS uses the following protocols and cipher suites:

* Those configured in your global TLS configuration if it exists
* The defaults provided by your Java environment if a global TLS configuration does not exist.

Cipher suite names can be long and impact the readability of your XML code. To improve readability, keep these names in an external properties file in your Mule project and refer to it.

You can then reference your properties using the following syntax:

[source, xml, linenums]
----
<tls:context name="serverTlsContext" enabledCipherSuites="${myCipherSuites}" >
----

== XML Reference for TLS

This following tls:context element and attributes define TLS communication in a Mule app. You typically define a TLS configuration globally and reuse it. You refer to the global definition to apply it to a specific use, such as listening for or sending a request.

=== Globally Defined TLS Element

The tls:context element defines a configuration for TLS, which can be used from both the client and server sides. It can be referenced by other configuration objects of other modules (or defined as a nested element of one of them).

You can include two nested elements: key-store and trust-store. Including one is required.

[source, xml, linenums]
----
<tls:context name="customContext">
    <tls:trust-store path="trustStore" password="mulepassword"/>
    <tls:key-store path="clientKeystore" keyPassword="mulepassword"
password="mulepassword"/>
 </tls:context>
----

=== Attributes of the tls-context Element

The attributes are optional.

* enabledProtocols: The protocols named in the the global TLS configuration to enable
* enabledCipherSuites: The cipher suites named in global TLS configuration to enable

=== Attributes of the trust-store Element

The attributes other than the path attribute are optional. 

* path: The path to the file that contains the trust store (required)
* type: The type of the trust store. Default = JKS
* password: The trust store password
* algorithm: The algorithm the trust store uses. Default = SunX509
* insecure: Boolean that determines whether or not to validate the trust-store. If set to true, no validation occurs. Default = false

Setting 'insecure' to 'true' renders connections vulnerable to attacks and is recommended only for prototyping and testing purposes.

=== Attributes of the key-store Element

The attributes other than the path attribute are optional.

* path: The path to the file that contains the keystore (required)
* type: The type of the keystore (default JKS)
* password: The keystore password
* keyPassword: The key manager password, which is the password for the private key inside the keystore
* algorithm: The algorithm used in the key store. Default = SunX509

== Using a UI to Configure TLS

You can configure TLS in Studio and Design Center. For example, you can set up TLS in the HTTP Connector Global configuration or Web Service Consumer > Security.

== See Also

* link:/http://docs.oracle.com/javase/8/docs/technotes/tools/#security[Oracle Java keytool documentation]
