= Transaction Management
:keywords: transaction, management, demarcation, jms, jdbc, vm, database, resource

Transactions are operations in a Mule app for which the result cannot remain indeterminate. Where a series of steps in a flow must succeed or fail as one unit, Mule uses a transaction to demarcate that a unit. For example, you might use a transaction to encapsulate several steps in a flow for which the end result involves committing information to a database.  In this type of scenario, the commit is either entirely complete and succeeds, or is incomplete and it fails. Even if partially complete, the commit – or transaction – fails. Where a transaction fails, Mule rolls back the operations within the transaction so that no one part results in partial completion.

Try scope provides a way to configure a transaction from its General tab. The XML for this configuration looks like this:

.XML Example: Transaction Configuration in the Try Scope
----
<try doc:name="Try" transactionalAction="ALWAYS_BEGIN" transactionType="XA">
  <component_here/>
  <component_here/>
</try>
----

In Studio, operations in these connectors provide an Advanced tab for setting up transactions:

* JMS
 ** Listener supports Local and XA transaction types. When set, the entire flow is treated as a transaction.
 ** Consume and Publish operations support transactions.
* VM
 ** Listener supports Local and XA transaction types. When set, the entire flow is treated as a transaction.
 ** Consume, Publish, and Publish Consume operations support transactions.
* Database
 ** All database operations support transactions.

.XML Example: Transaction Configuration for VM Listener
----
 <vm:listener doc:name="Listener" transactionType="XA" transactionalAction="ALWAYS_BEGIN" primaryNodeOnly="true"/>
----

.XML Example: Transaction Configuration for a JMS Consume Operation
----
<jms:consume doc:name="Consume" transactionalAction="ALWAYS_JOIN"/>
----

Note that a Mule flow can begin with a non-transactional connector (such as HTTP) that requires a transaction within the flow. For example, a Mule flow might accept information from an external Web service, then transform the data before charging a credit card and saving invoice information to a database. In such a situation, you might use the Try scope to set up a transaction by wrapping the credit card charge and database commit operations within a transaction to ensure either complete success or complete failure and rollback.

== Transactional Actions

A Transactional Action (`transactionalAction`)

* ALWAYS_BEGIN - Always start a new transaction when receiving a message. An exception will be thrown if a transaction already exists. Listeners that support transactions have this option.

* ALWAYS_JOIN - Always expect a transaction to be in progress when a message is received. If there is no transaction, an exception is thrown. Operations that support transactions have this option.

* BEGIN_OR_JOIN - If a transaction is already in progress when a message is received, join the transaction if possible. Otherwise, start a new transaction. Scopes that support transactions provide this setting.

* JOIN_IF_POSSIBLE: Join the current transaction if one is available. Otherwise, no transaction is created. Operations that support transactions provide this setting.

* INDIFFERENT: Do not treat actions as a transaction. Scopes that support transactions provide this setting.

* NONE - Never participate in a transaction. Listeners that support transactions provide this setting.

* NOT_SUPPORTED: Execute outside any existent transaction. Operations that support transactions provide this setting. Scopes that support transactions provide this setting.

== Transaction Types

Mule supports Single Resource (Local, the default) and Extended Architecture (`XA`) transaction types (`transactionType`). The following table describes characteristics of each type.

* Single Resource Transactions (Local)
 ** Receives or sends messages to only one resource.
 ** Performs better than XA.

* XA Transactions
 ** Receives or sends messages to more than one resource.
 ** Involves using a two-phase commit algorithm. 
 ** Connectors must be XA-enabled.
 ** Slower but more reliable than Local.

////
TODO:
== See Also

link:transactions-single-resource.adoc[Single Resource (Local) Transactions]

link:transactions-xa.adoc[XA Transactions]
////
