= Try Scope

The Try scope allows you to handle errors that may occur when attempting to execute its child components. It allows you to set a fine grained configuration to a specific part of your flow with a certain error-handling strategy. It also distinguishes different error types, and can apply different behaviors accordingly.

== Handling Transactions

You configure a Try Scope so that it treats its child operations as an indivisible transaction. A transaction is a series of actions that should never be partially executed, errors should lead to either a rollback or a commit.

The Try scope can be set to treat the components within it as a transaction. It can be configured in the following ways:

* Ignore (`INDIFFERENT`):
+
Default. Actions are not treated as a transaction. Errors cause no rollbacks or commits.

* Always Begin (`ALWAYS_BEGIN`)
+
A new transaction is started every time the scope is executed.

* Begin or Join (`BEGIN_OR_JOIN`)
+
Only relevant in cases where execution order may vary (for example due to asynchronous actions happening outside the flow). If the current processing of the flow has already begun a transaction, join it. Otherwise, begin a new one.


== See Also

* link:/mule-user-guide/v/4.0/try-scope-xml-reference[Try Scope XML Reference]
* link:/mule-user-guide/v/4.0/error-handling[Error Handling]
* link:/mule-user-guide/v/4.0/scopes-concept[About Scopes]
