= Try Scope

The Try scope allows you to handle errors that may occur when attempting to execute any of the child components inside the Try scope. The Try scope has its own error handling that you configure in the same way you configure error handling for a flow. It allows you to set fine grained configuration for a specific part of your flow with a certain error handling, without having to extract those elements into a separate flow. Like all error handling, the Try scope can also distinguish between various error type conditions, and accordingly to then apply different behaviors to each error type condition.

== Handling Transactions

You configure a Try scope so that it treats its child operations as an indivisible transaction. A transaction is a series of actions that should never be partially executed, errors should lead to either a rollback or a commit.

The Try scope can be set to treat the components within it as a transaction. It can be configured in the following ways:

* Ignore (`INDIFFERENT`):
+
Default. Actions are not treated as a transaction. Errors cause no rollbacks or commits.

* Always Begin (`ALWAYS_BEGIN`)
+
A new transaction is started every time the scope is executed.

* Begin or Join (`BEGIN_OR_JOIN`)
+
Only relevant in cases where execution order may vary (for example due to asynchronous actions happening outside the flow). If the current processing of the flow has already begun a transaction, join it. Otherwise, begin a new one.


== See Also

* link:/mule-user-guide/v/4.0/try-scope-xml-reference[Try Scope XML Reference]
* link:/mule-user-guide/v/4.0/error-handling[About Error Handling]
* link:/mule-user-guide/v/4.0/scopes-concept[About Scopes]
