= About Set Variable
:keywords: anypoint studio, studio, mule, variable transformer, variables, set variable, edit variable, remove variable

The Set Variable component can set a variable on the Mule event within the the flow where you set it. You access the variable through the DataWeave identifier `vars`. For example, access an integer `myInt` using `#[vars.myInt]`.

[%header,cols="15a,15a,70a"]
|===
|Field |Value |Description
|Display Name |Variable |Customize to display a unique name for the transformer in your application.

XML: `doc:name="Variable`
.2+|Operation |Set Variable |Select to set a new variable on your message (as shown in screenshot above).

XML: `<set-variable>`
|Remove Variable |Select to delete an existing variable from your message.

XML: `<remove-variable>`
|Name |String or Mule Expression |Specify the name for the variable that you are creating, or identify the name of the variable that you are removing. If you are removing variables, this field accepts a wildcard `""` character.

XML: `variableName="MyNewVariableName"`
|Value |String or Mule Expression |This field displays only if you are setting a new variable. Specify the value using either a string or a Mule expression.

XML: `value="MyNewVariableValue"`
|MIME Encoding |Drop-down menu |(Optional) Indicates the MIME encoding language. Only appears when setting a variable.

XML: `encoding="language"`
|MIME Type |Drop-down menu |(Optional) Indicates the MIME type. Only appears when setting a variable.

XML: `mimeType="value"`
|===


[source, code, linenums]
----
#Set Variable

<set-variable variableName="MyNewVariableName" value="MyNewVariableValue" doc:name="Variable"/>

#Remove Variable

<remove-variable variableName="NameofVariabletoRemove" doc:name="Variable"/>
----


[%header,cols="30a,70a"]
|===
|Element Attribute |Description
|`doc:name` |
Customize to display a unique name for the transformer in your application.

Note: Attribute not required in Mule Standalone configuration.

|`variableName` |
The name of the variable that you are setting or removing. Can be a string or a Mule expression.

Note: If you are using the remove-variable element, you may use a wildcard `*` character. For example, a remove-variable transformer with a variable name `http.*` removes all variables with a name that begins with "http." from the message.

|`value` |The value of the variable that you are setting. This attribute is only relevant for the set-variable element. Can be a string or a Mule expression.
|===

== Example - Store Variable, Output in Exception Strategy

In many cases, it is useful to preserve the original payload of a message, before it is processed, for use later in the flow or to use it in an exception strategy. For this purpose, you can store whole or part of the message's payload in a variable (named, in the example below, "originalRequest") where you can retrieve it later if needed. In this example, if the HTTP connector or the groovy component (blank on purpose here) fails to process the message, the logger in the flow's exception strategy logs the failed request by retrieving it from the `originalRequest` variable.

== See Also

* link:/mule-user-guide/v/4.0/mule-event[About the Mule Event]
