= About Set Variable
:keywords: anypoint studio, studio, mule, variable transformer, variables, set variable, edit variable, remove variable

The Set Variable component is for creating or updating a variable to store values
for use within the flow of a Mule app. You can store simple literal values such
as strings or messages, message payloads, or attribute objects. For example,
you might store the original payload of a message (before it is processed) so you
can use it later in the flow or within an error handler.

The `set-variable` component is not recommended for complex expressions or transformations
but rather simple ones, such as selections. The link:transform-component-about[Transform Component]
should be use in complex scenarios instead.

[%header,cols="20a,20a,60a"]
|===
|Field | Usage | Description

| `variableName`
| Required
| Name of the variable. Names can only include numbers, characters, and underscores. For example, hyphens are not allowed in the name.

| `value`
| Required
| Value for the variable, which can be a string or a DataWeave expression.

| `mimeType`
| Optional
| Sets the variable MIME type, such as `text/plain` or `application/json`.

| `encoding`
| Optional
| Sets the variable encoding, such as `ISO 10646/Unicode(UTF-8)`.

|===

[WARNING]
--
The `mimeType` and `encoding` attributes will not affect a DataWeave expression
used as `value`, they will only affect the output value stored. If a transformation
is required the DataWeave expression must contain an explicit output directive.
--

== Examples

This example sets the variable to a string:

* Name = `myVar`
* Value = `my first variable`

This example sets the variable by using a DataWeave operation that results in a value of `5`:

* Name = `myVar`
* Value = `#[max([1,2,3] ++ [3,4,5])]` in Anypoint Studio.

This example sets the variable to the message payload:

* Name = `myVar`
* Value = `payload` in Design Center, `#[payload]` in Anypoint Studio.

This example sets the variable to the message attributes:

* Name = `myVar`
* Value = `attributes` in Design Center, `#[attributes]` in Anypoint Studio.

This example sets the variable to the entire message:

* Name = `myVar`
* Value = `message` in Design Center, `#[message]` in Anypoint Studio.

This XML example sets a variable that takes a map as a value:
`<set-variable variableName="employee" value="{ 'name' : 'Ana', 'office' : 'BA' }" mimeType="application/json" encoding="UTF-8/>`

This example sets the same variable using selectors in a DataWeave script. It assumes the `name` attribute is available as input to Set Variable:
`<set-variable variableName="employee" value="#[output application/java --- payload.name]"/>`

== See Also

* link:about-mule-variables[About Variables in the Mule Event]
* link:target-variables[Enriching Data with Target Variables]
