= To Access Usage Data with the PCF Metering API.
:keywords: pcf, pivotal cloud foundry,

After your Mule applications are deployed to PCF, you can view their usage metrics via the PCF Metering API. Using this API, you can query the following information:

* Details of your plan
* Monthly usage data for your PCF installation
* Monthly or daily usage for a space
* Monthly or daily usage for a specific application

For more information, see the RAML definition of the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/8482323/versions/115119/pages/168687[PCF Metering API]. The API returns usage data as a JSON object.

To access usage data using the PCF Metering API:

1. Ensure that you have installed the cf CLI

1. Login to the PCF API endpoint of your installation
+
cf login

1. Enter your credentials

1. Select the org

1. List the spaces assigned to your org
+
cf spaces

1. Determine the guid of your space:
+
cf space SPACE_NAME --guid

1. List the applications running in your space

cf space SPACE_NAME

1. Determine the guid for an application running in a space:
+
cf app APP_NAME —-guid

1. Using the space and application guids, query the API.
+
For example, to view a daily report for a specific application, use a URL similar to the following URL:
+
...
http://your-pcf-domain.com/metering/spaces/e2f03cf2-1610-4a1b-b477-ec04d47063a7/reports/apps/<appid>/day
...

Using this example, you can perfom other queries supported by the API