= Workflow: Install and Verify Prerequisites
:keywords:anypoint platform, on premises

This topic describes the workflow for verifying that your system is ready to install Anypoint Platform Private Cloud Edition.

1. Review the minimum system requirements described in link:./system-requirements[About Minimum System Requirements].
+
[WARNING] 
If your system does not meet all of the minimum system requirements, you cannot install Anypoint Platform Private Cloud Edition.

1. (Optional) Create a Virtual Machine
+
If you are installing Anypoint Platform Private Cloud Edition in a virtual environment, see link:./prereq-create-vm-vmware[To Create a Virtual Machine Using VMWare]

1. Verify your disk and network performance.
+
Before running the Anypoint Platform Private Cloud Edition installer, ensure that your disk and network performance meets the minumum requirements. See link:./prereq-verify[To Verify System Requirements] for tips on how to perform this task.

1. Enable forwarding when using firewalld
+
If you are running Red Hat Enterprise Linux (RHEL), 7.3 using firewalld, you must enable forwarding as described in link:./prereq-firewalld-forwarding[To Enable Forwarding When Using firewalld]

After installing and verifying these prerequisites, you are ready to run the installer. See link:./install-installer[To Install Anypoint Platform Private Cloud Edition] for more information.