= Workflow: Install and Verify Prerequisites
:keywords:anypoint platform, on premises

This topic the workflow to verify that you system is ready to install Anypoint Platform Private Cloud Edition.

1. Review the minimum system requirements described in link:./system-requirements[About Minimum System Requirements].
+
[WARNING] 
If your system does not meet all of the minimum system requirements, you cannot install Anypoint Platform Private Cloud Edition.

1. (Optional) Create a Virtual Machine
+
If you are installing Anypoint Platform Private Cloud Edition in a virtual environment, see link:./create-vm-vmware[To Create a Virtual Machine Using VMWare]

1. Verify your disk and network performance.
+
Before running the Anypoint Platform Private Cloud Edition installer, ensure that your disk and network performance meets the minumum requirements. See link:./verify-system-requirements[To Verify System Requirements] for tips on how to perform this task.

1. Enable forwarding when using firewalld
+
If you are running Red Hat Enterprise Linux (RHEL), 7.3 using firewalld, you must enable forwarding as described in link:./firewalld-forwarding[To Enable Forwarding When Using firewalld]


