= Deploy a Mule Application to a Runtime Fabric

This topic describes how to deploy a Mule application to an Anypoint Runtime Fabric.

== Before You Begin

Before deploying an application to an Anypoint Runtime Fabric, you must perform the following:

* Installed and configured at least one Anypoint Runtime Fabric.
* Ensure that your Runtime Fabric is associated with an environment.
* Determine the resource allocation requirements for your application. See [link to docs on scaling and number of cores/memory] for more information.

== Procedure
. Provide a name for your deployed application in the *Application Name* field.
. Select the application you want to deploy by clicking *Choose File*, then select one of the following options:
	* *Import file from Exchange*: enables you to select a Mule application that has been published to Exchange.
	* *Upload file*: enables you to select a Mule applcation file.
. Select a Runtime Fabric from the *Deployment Target* drop-down list.
+
_Result_: The *Deployment Target*, *EDGE Configuration*, and *Properties* tabs are displayed. Use these tabs to enter additional configuration information for your application.

. Select the *Deployment* Target tab.
+
This tab displays the name and type of the deployment target you selected above.

. Select the Mule runtime version from the *Runtime Version* drop-down list.
+
See [link to supported runtimes] for more information.

. Select the number of workers you want allocate to the application.
+
See [link to work/core/memory topic] for more information.

. Specify the number of *Cores* and *Memory* you want to allocate to the application by adjusting the sliders to the appropriate values.
+
See [link to docs on scaling and number of cores/memory] for more information.

. Specify additional network configuration for the application. (Optional)

.. Click the *EDGE Configuration* tab.
.. Enable or disable the following options:
+
* *Enable inbound traffic to this application*:
* *Enable Last-Mile security*: 
* *Enable application to run in Runtime Cluster Mode*:  

. Configure application properties (Optional)
.. Click the *Properties* tab.
.. Specify your application properties as key-value pairs.

. Click *Deploy Application*.

_Result_: Runtime Manager displays a status message related to the application. After a few seconds, Runtime Manager displays the list of deployed applications, including the application you just deployed.

== What to do Next

Initially, the application status is Starting, but it should eventually change to Started. Monitor the application status to ensure that it starts successfully. 

== See Also

* Deploy a Mule Application to CloudHub
* Deploy a Mule Application to a Hybrid Environment