= HL7 Mule Expression Language Support
:keywords: hl7, mel, mule expression language, hl7segment

[NOTE]
This feature is part of the link:/healthcare-toolkit/v/1.3[Mule Healthcare Toolkit], which also includes transformers and components for receiving, processing and sending HL7 messages. For details and a full list of available tools, consult the Toolkit's link:/healthcare-toolkit/v/1.3[documentation main page].

The Mule Healthcare toolkit includes two link:/mule-user-guide/v/3.5/mule-expression-language-mel[Mule Expression Language] (MEL) functions:

* `hl7segment()` allows access to a segment in an HL7 message
* `hl7()` allows access to values within a segment

The functions use the link:http://hl7api.sourceforge.net/[HAPI] (HL7 Application Programming Interface) link:http://hl7api.sourceforge.net/apidocs/ca/uhn/hl7v2/util/Terser.html[Terser] to provide access to HL7 fields. You can use MEL to access HL7 message contents in any message processor that supports MEL.

=== Examples

.Obtaining values
[width="100%",cols="40a,60a"]
|===
|[source]
----
hl7('/PID-5-1')
----
|Returns the value of the `PID-5-1` field of the current message
|[source]
----
hl7segment('AL1')
----
|Returns the value of the `Al1` segment of the current message
|===

.Modifying values
[%header%autowidth.spread]
|===
|[source]
----
hl7('/PID-5-1', 'Polly')
----
|Sets the value of the `PID-5-1` field of the current message to `Polly`
|[source]
----
hl7segment('AL1','AL1\|1\|\|^Penicillin\|\|Produces hives')
----
|Sets the value of the `AL1` segment of the current message
|===

=== Usage Examples

Use a link:/mule-user-guide/v/3.5/variable-transformer-reference[Variable Transformer] to initialize the variable `HL7event` with the value of the `EVN` segment of the HL7 message:

[source,xml]
----
<set-variable variableName="HL7event" value="#[hl7segment('EVN')]"/>
----

Use a link:/mule-user-guide/v/3.5/set-payload-transformer-reference[Set Payload Transformer] to obtain a string composed of the fields `PID-5-1` and `PID-5-2`:

[source,xml]
----
<set-payload value="#[hl7('/PID-5-1') + ' ' + hl7('/PID-5-2')]"/>
----

Use an link:/mule-user-guide/v/3.5/expression-component-reference[Expression Component] to set modify fields `PID-5-1` and `PID-5-2`:

[source,xml, linenums]
----
<expression-component>
        hl7('/PID-5-1', 'Polly');
        hl7('/PID-5-2', 'Hedra');
</expression-component>
----

== See Also

* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
