= To Add Modules to Your Studio Project

// REVIEW: Studio7 is calling them Modules.

You can add Modules and Connectors to your Mule project using the Mule Palette.

. Go to your Mule Palette, and click Add Module.
. Click Add Extension.
. Select your desired module from the Available Modules list.
:: By default, this list shows the available public modules. If you configured your Anypoint Platform credentials in Studio, you can also see your organization's private modules. +
If you have no credentials configured in Studio, you can click Log In to Anypoint Platform to access your organization's modules.
. Click Finish to exit the Module Management window, and then OK.

The selected module is now part of your Mule Palette.

Modules are dependencies of your Mule project. Adding a module to a Mule project in Studio does not make that module available to other projects in your Studio workspace. +

== See Also

* link:/anypoint-studio/v/7/set-credentials-in-studio-to[To Set Credentials in Studio]
