= FAQ: Troubleshooting JDK Requirement

Anypoint Studio 7 requires JDK 8 to run properly.

If you do not see an HTTP Connector in the Mule Palette, then you are not using the JDK. +
To configure the JDK:

. Download the JDK from Oracle's site and follow the installation instructions for your OS.
. Set the JAVA_HOME environment variable to point to your JDK installation.

Even though you have JDK 1.8 installed on your machine, you need to ensure that your PATH variable in your ~/.bashrc file includes $JAVA_HOME/bin as the first item.


* Windows:
::
+
. In Search, search for System (Control Panel) and select it.
. Click Advanced system settings.
. Click Environment Variables.
. In the section System Variables, find the PATH environment variable and select it.
. Click Edit. If the PATH environment variable does not exist, click New.
. In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable.
+
[NOTE]
--
Make sure that the jdk1.8.0/bin directory is the first item in your PATH variable
--
+
. Click OK.
. Reopen Command prompt window, and run your java code.

* Unix/Linux: +
::

. Edit the startup file (~/.bashrc)
. Modify PATH variable
+
[source,bash,linenums]
----
PATH=/usr/local/jdk1.8.0/bin:$PATH
export PATH
----
. Save and close the file
. Load the startup file
+
[source,bash,linenums]
----
> . /.profile
----

To verify that you configured your installation correctly, type

[source,bash,linenums]
----
> java -version
----

This should print the version of the java tool. If the version is old or you get the error "java: Command not found", then the path is not properly set.


== See Also

* link:http://docs.oracle.com/javase/8/docs/technotes/guides/install/windows_jdk_install.html#A1097936[Oracle JDK installation Instructions]
