= FAQ: Troubleshooting JDK Requirement

Anypoint Studio 7 requires JDK 8 to run properly.

If you do not see an HTTP Connector in the Mule Palette, then you are not using the JDK, or your JDK installation is not properly set. +

== To install the JDK

. Download the JDK from Oracle's site and follow the installation instructions for your OS.
. Set the JAVA_HOME environment variable to point to your JDK installation.

After you installed JDK 1.8 on your machine, you need to ensure that your PATH variable in your ~/.bashrc file includes $JAVA_HOME/bin as the first item.

* Windows:
::
+
. In Search, search for System (Control Panel) and select it.
. Click Advanced system settings.
. Click Environment Variables.
. In the section System Variables, find the PATH environment variable and select it.
. Click Edit. If the PATH environment variable does not exist, click New.
. In the Edit System Variable (or New System Variable) window, specify the value of the PATH environment variable.
.. Make sure that the jdk1.8.0/bin directory is the first item in your PATH variable.
+
[NOTE]
--
Blank spaces are not allowed when defining a path on Windows.
--
+
. Click OK.
. Reopen Command prompt window, and run your java code.

* Unix/Linux: +
::
+
. Edit the startup file (~/.bashrc)
. Modify PATH variable
+
[source,bash,linenums]
----
PATH=/usr/local/jdk1.8.0/bin:$PATH
export PATH
----
. Save and close the file
. Load the startup file
+
[source,bash,linenums]
----
> . /.profile
----

To verify that you configured your installation correctly, type

[source,bash,linenums]
----
> java -version
----

This should print the version of the java tool. If the version is old or you get the error "java: Command not found", then the JDK is not properly installed.

== To Configure The JDK as Your Default JVM For Studio

Under certain circumstances, if you had a JRE installation previous to installing the JDK, your default VM could still be configured as the JRE. To point Anypoint Studio to use the JDK as the default VM:

. Locate your `AnypointStudio.ini` file:
.. On Windows: This file is located within your Anypoint Studio's installation directory.
.. On Linux: `/usr/lib/anypointstudio/anypointstudio.ini`.
.. On OSx: `Applications/AnypointStudio`.
. Add the -vm option to point to your specific JDK installation path.
+
::
* On Windows:
+
[source,sample,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\bin\javaw.exe
----
+
As stated above, blank spaces are not allowed when defining paths on Windows. This is why `\Program Files\` changes to `\progra~1\`.
+
If you encounter “Java was started but returned exit code=1” error while starting Anypoint Studio, modify the -vm argument to point to the jvm.dll as follows:
+
[source,sample,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\jre\bin\server\jvm.dll
----
+
* On Linux:
+
[source,sample,linenums]
----
-vm
/opt/sun-jdk-1.6.0.02/bin/java
----
+
* On OSx:
+
[source,sample,linenums]
----
-vm
/usr/bin
----

When configuring the -vm option, its format must be exact:

* The -vm option and the installation path must be in separate lines.
* The value must be the full absolute or relative path to the Java executable, not just to the Java home directory.
* The -vm option must occur after the other Studio-specific options (such as -product, --launcher.*, etc), but before the -vmargs option, since everything after -vmargs is passed directly to the JVM.

If after following the steps above, Anypoint Studio still does not recognize your JDK installation, consider uninstalling your JRE.

== See Also

* link:http://docs.oracle.com/javase/8/docs/technotes/guides/install/windows_jdk_install.html#A1097936[Oracle JDK Installation Instructions]
* link:https://wiki.eclipse.org/Eclipse.ini[Eclipse -vm Option Configuration Instructions]
