= To Install Anypoint Studio 7.0 Beta

//COMBAK Installation Wizard?

* Before downloading and launching Anypoint Studio, install link:http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html[Java SE JDK 7] or link:http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Java SE JDK 8].

* If you are using a Mac computer running OS X and if you are installing Anypoint Studio on a new computer or a fresh installation, you must also install link:https://support.apple.com/kb/DL1572[JRE 1.6], which provides important libraries used by later JDK versions. Install JDK 6 first and then install link:http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html[JDK 7] or link:http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Java SE JDK 8].
+
After installing JDK 7 or 8, you need to change the default Java virtual machine (JVM) from v6 to the later version.

** Open a Terminal and enter this command as shown in the following example:

[source,code,linenums]
----
/usr/libexec/java_home -V
----

It should return

[source,source,linenums]
----
Matching Java Virtual Machines (2):
1.8.0_101, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
----

** Enter a command such as this that sets the JDK 8 to the default JVM.

[source]
----
export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_101`
----

To install Anypoint Studio 6.3.0 Beta:

. Unzip the Studio 6.3 Beta zip file that you downloaded from the beta invite.
+
[WARNING]
====
*Windows*: It's important to extract Anypoint Studio into the 'C:\' root folder. Also, if you are using a Windows Anti-Virus application, ensure that the `plugin/` and `features/` directories are under the “trusted” category.

*OS X*: If you're using OS version Sierra, it's important that you move your extracted app to the `/applications` folder before you launch it

*Linux*: To support some of Studio Themes in Linux, it is recommended to have GTK version 2 installed.
====
+
. Open Anypoint Studio:
.. *Windows*: Double-click the *AnypointStudio.exe* file, located in the *AnypointStudio* directory.
.. *Linux*: Double-click the *AnypointStudio* file icon, located in the *AnypointStudio* directory.
.. *OSx*: Double-click the *AnypointStudio.app* file icon, located in the *Applications* directory.
. If the wrong version of Java is present on your computer, the following may occur after you start Studio:
.. *Mac*: The command triggers a prompt to install the JDK tools directly from Apple. Follow the instructions to download and install JDK 7 or JDK 8.
.. *Windows*: This message appears when you start Studio:
Incompatible JVM - Version _<number>_ of the JVM is not suitable for this product. Version 1.7 or greater is required.
Go to link:http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html[Java SE JDK 7] or  or link:http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Java SE JDK 8], download the JDK, and install it. Then restart AnypointStudio.exe from where you unzipped the software distribution.
. Click *OK* to accept the default workspace.
. Anypoint Studio launches, then displays a Welcome page. Click *Create a Project* to begin development immediately.

== See Also

* link:/anypoint-studio/v/6.3/exchange-integration[Integration with Exchange 2.0 Beta]
* link:/anypoint-studio/v/6.3/import-api-def-dc[To Import an API Definition from Design Center Beta]
