= Anypoint Application Network Visualizer

**TODO: Change name of product when PM finalizes.**

Anypoint Application Network Visualizer provides a graphical representation of the APIs and Mule applications within your application network. This representation enables you to view the relationships between applications in an application network. It also shows relationship between each node. This is useful when performing architectural reviews or your network, ensuring compliance, troubleshooting, etc.

The following image shows how a typical application network appears in Anypoint Application Network Visualizer.

image:application-network[Application Network]

In this image, each node of the application network is represented by a box. Connections between the nodes are represented by arrows.

Anypoint Application Network Visualizer provides a real-time view of your application network. It only displays nodes for applications or APIs that are running and discoverable. The connections between nodes are based on connections between applications or APIs that occurred in the last seven days. If an application appears in multiple workers, they appear as two distinct nodes in the graph.

Anypoint Application Network Visualizer also enables you to view CPU and memory usage for each node within your application network.

== Use Cases

**Reviewers: This section needs additional work to iron out clear use cases. Any suggestions would be helpful.**

The following use cases provide examples of how you can use Anypoint Application Network Visualizer.

* **Discussing Current Design State**: Enterprise architect Kara has developed a plan for how the architecture she’s responsible for will accommodate a new product. She needs to capture its current state so she can plan the transition and get buy-in from stakeholders on her proposal.

* **Implementing API-led Connectivity**: Site reliability engineer Tom is tired of maintaining several separate connections to Salesforce. He wants to identify redundant point-to-point connections so he can come up with requirements for a new process API.

* **Understand Application Network Architecture**: Anypoint Application Network Visualizer provides a real-time view of the application network. This enables developers or architects to understand the architecture of an application network. Also shows the interactions between nodes and any external dependencies.

* **Define API-Led Connectivity Classifications**: Anypoint Application Network Visualizer enables you to assign the nodes of the graph into layers. This enables you to organize the graph according to classifications used by API-led connectivity. When deploying a new application, you can ensure that it is displayed in the correct layer by specifying the layer as a property during deployment. You can also create new layers as required by your application network.

* **Ensure Architectural Best Practices**: TBD

* **Monitor External Dependencies**: TBD