= Use Layers in Anypoint Visualizer

This topic describes how to work with layers in Anypoint Vizualizer.


== Add an Application Node to an Default Layer

By default when you view an environment using Anypoint Visualizer, none of the nodes in the application are assigned to a layer. You can a node to an existing layer. The following procedures are also applicable for changing the layer of a node.

. Select the application node you want to add to a layer.
+
_Result_: The *Details* panel for the node appears in the right-hand pane as shown in the following image:
+
image:select_node[Select Node]

. In the *Details* panel, expand the drop-down list next to *Layer* as shown in the following image:
+
image:select_layer[Select Layer]

. Select the layer you want from the drop-down list.

_Result_: The node you selected appears within the layer as shown in the following image:

image:select_layer_result[Node in Layer]  

== Create a New Layer

In addition to the default layers provided by Anypoint Visualizer, you can create new layers to customize the view of your application network.

. Select the node you want to add to a new layer.
. From the drop-down list in the *Details* panel, select *New Layer ....*
. Enter a name for your layer in the dialog box, then click *Create Layer*.

_Result_: The node appears in the new layer. You can add additional nodes to this layer as necessary.


== Delete a Layer

You can delete layers from Anypoint Vizualizer as required. Deleting a layer does not delete the nodes. 

. In the visualizer display, click inside of the layer you want to delete. Do not click a node within the layer.
. Click the *Delete Layer* icon above the *Details* panel.
. Click *Delete Layer* to confirm.

_Result_: Anypoint Visualizer automatically adjust the network display. Nodes that were part of the deleted layer no longer have a layer assigned.