= Setup Anypoint Visualizer

This topic describes how to configure the roles and permission required to use Anypoint Visualizer. It also provides information and considerations when deploying applications.

== Configure Permissions

To access Anypoint Visualizer, you must be assigned a role that has the *Visualizer Viewer* permission assigned to it. See [xref to Access Management] for more information.

**TODO: Need to add information about "Runtime Manager Privileges.**

== Verify Supported Runtimes and Connectors

Anypoint Visualizer only includes activity from applications deployed to a supported Mule runtime. When deploying an Mule application or API, you must ensure that you are using a supported Mule runtime as the deployment target. 

Anypoint Visualizer is supported on the following Mule runtimes running on CloudHub:

* Mule Runtime, version 3.9.x
* Mule Runtime, version 4.1.x 

Additonally, Anypoint Visualizer can monitor activity for outbound connections on specific connectors.

For Mule runtime, version 3.9.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* All connectors based on the Connector DevKit

For Mule runtime, version 4.1.x, the following connectors are supported:

* Salesforce
* HTTP/HTTPS
* Database
* Mule 4 Extension Connectors

== Deploy an Application

