= View an Application Network

== View an Application Network in an Organization


. From Management Center, select Application Network Visualizer.
+
If Application Network Visualizer is not available contact your system administrator to ensure that you have the correct permissions to access the application.

. Select an environment from the drop-down list.
+
Application Network Visualizer displays only the environments you have permissions to view.

. Click the check box for the business group you want to view.

_Result:_ After selecting the organization and environment group, Application Network Visualizer displays a graph of your application network.

== View Information About a Node in Your Network

When you select a node within the graph, Application Network Visualizer displays information about the node in the details panel on the right-hand side of the application. This panel is divided into the following sections:

* **Details**: provides information about the node, including the layer the node is assigned to. You can change the layer from this section. See link:/visualizer/layers[Use Layers in Anypoint Visualizer].
* **CPU Utilization**: displays a graph showing recent CPU utilization for the node.
* **Memory Usage**: displays a graph showing recent memory usage for the node.

From the details panel, you can rename a node by clicking the *Rename Node* button.

== View Information About a Connection in Your Network

When you select a connect within the graph, Application Network Visualizer displays basic information about the connection in the details panel on the right-hand side of the application.

From the details panel, you can rename the connection by clicking the *Set Edge Name* button.

== See Also

* /visualizer/layers[Use Layers in Anypoint Visualizer]
