= Command Line Interface Shell for Anypoint Platform.
:keywords: administration, api, organization, users, gateway, theme, cli

Anypoint Platform provides you a command line tool to interact with your Cloudhub applications, link:/runtime-manager/virtual-private-cloud[VPCs] and link:/runtime-manager/cloudhub-load-balancer[Cloudhub load balancers] through both interactive shell and standard CLI modes.

== Assumptions

This document assumes that you are familiar with our link:/anypoint-platform-for-apis/anypoint-platform-for-apis-walkthrough[Anypoint platform for APIs walkthrough] and that you are able to link:/anypoint-platform-for-apis/managing-your-api[manage your API using Anypoint Platform].

== Installation

[IMPORTANT]
First you need to make sure you have the node.js runtime environment installed in your machine. Along with it, you'll need to use node's default package manager (npm) to be able to install Anypoint-CLI.
Following the steps in the link:https://docs.npmjs.com/getting-started/installing-node[node documentation] will help you get both resources.

You can install Anypoint-CLI using node's default package manager by typing in your console

[source,bash]
----
$ npm install -g anypoint-cli
----

== Usage

Every instance of Anypoint-CLI takes any of the following parameters:

[width="100a",cols="15,75a,10a",options="header"]
|===
|Parameter |Description| Required
|username | Your Anypoint Platform username. +
You can also use an environment variable (e.g. `export ANYPOINT_USERNAME=<name>`)| *Yes*
|password | Your Anypoint Platform password. +
You can also use an environment variable (e.g. `export ANYPOINT_PASSWORD=<pwd>`)| *Yes*
|organization| Your organization within Anypoint Platform. +
You can also use an environment variable (e.g. `export ANYPOINT_ORG=<name>`)| No
|environment| Your Anypoint-CLI environment. +
You can also use an environment variable (e.g. `export ANYPOINT_ENV=<name>`)| No
|===

=== Logging In

As instructed above, the username and password parameters are required. If you don't pass them, Anypoint-CLI will not run. +
The recommended way of passing your credentials is using the `credentials` file located in the `~/.anypoint/` directory in Linux and OSx or `C:\Users\USERNAME \.anypoint\` in Windows. +

[NOTE]
The `/.anypoint/` directory is not automatically created during installation, so you need to create it in the user's directory of your corresponding system.

Set up a blank file named `credentials` with the following structure:

[source,credentials,linenums]
----
{
 "default": {
  "username": "yourAnypointUserName",
  "password": "yourAnypointPassword"
 },
 "otherProfile": {
  "username": "",
  "password": "",
  "organization": "",
  "environment": "",
  "host": ""
 }
}
----

The `default` profile is used unless the `ANYPOINT_USERNAME` environment variable is set or you pass the `--username` parameter in the Command Line.

If you choose to pass the credentials when running Anypoint-CLI, we strongly recommend to pass both parameters as environment variables: +
`$ANYPOINT_USERNAME` and `$ANYPOINT_PASSWORD`.

Environment variables override credentials file parameters and Command line parameters override environment variables.

[IMPORTANT]
--
A few considerations to keep in mind while using Anypoint-CLI:

. If you don't set an environment, you will be automatically sent to `production`. +
. Your Anypoint session won't expire if you are accessing through this command line interface. +
. Anypoint-CLI works with autocomplete. You can start typing the name of the command or parameter and hit `tab` for an autocomplete, or double tap `tab` for a list of all possible options.
--

Once you have your parameters in order, you can pass commands. +
A list of available commands is below:

// Names from branch updated 27th June +
// https://github.com/sebastiankorol/anypoint-cli/commit/2a6256d52863acb6a5bba39eb9cd44f58d03d467#diff-04c6e90faac2675aa89e2176d2eec7d8

[width="100a",cols="35a,65a",options="header"]
|===
|Command |Description
|<<account describe-me>>| Show account details
|<<account describe-business-groups>>| Lists business groups
|<<account describe-business-group>>| Show details of a business group
|<<account switch-business-group>>| Make specified business-group active
|<<account describe-environments>>| Lists environments
|<<account use-environment>>| Make specified environment active
|<<account create-environments>>| Create new environment
|<<account delete-environment>>| Delete an environment
|<<runtime-mgr describe-applications>>| Lists all applications in the environment
|<<runtime-mgr describe-application>>| Show application details
|<<runtime-mgr describe-application-json>>| Show raw application JSON response
|<<runtime-mgr stop-application>>| Stop a running application
|<<runtime-mgr start-application>>| Start an application
|<<runtime-mgr restart-application>>| Restart a running application
|<<runtime-mgr delete-application>>| Delete an application
|<<runtime-mgr deploy-application>>| Deploy a new application
|<<runtime-mgr modify-application>>| Modify an existing application, optionally updating the zip file
|<<runtime-mgr revert-application-runtime>>| Reverts application to its previous runtime
|<<runtime-mgr download-application-logs>>| Download application logs to specified directory
|<<runtime-mgr tail-application-logs>>| Tail application logs
|<<cloudhub load-balancer list>>| Lists all Load balancers in an organization
|<<cloudhub load-balancer describe>>| Show LB details
|<<cloudhub load-balancer describe-json>>| Show raw LB JSON response
|<<cloudhub load-balancer create>>| Create a Load balancer
|<<cloudhub load-balancer start>>| Starts a Load balancer
|<<cloudhub load-balancer stop>>| Stops a Load balancer
|<<cloudhub load-balancer delete>>| Delete a Load balancer
|<<cloudhub load-balancer ssl-endpoint add>>| Add an additional certificate to an existing Load balancer
|<<cloudhub load-balancer ssl-endpoint remove>>| Remove a certificate from a Load balancer
|<<cloudhub load-balancer ssl-endpoint set-default>>| Set the default certificate that the Load balancer will serve
|<<cloudhub load-balancer ssl-endpoint describe>>| Show the Load balancer configuration for a particular certificate
|<<cloudhub load-balancer whitelist add>>| Add an IP or range of IPs to the Load balancer whitelist
|<<cloudhub load-balancer whitelist remove>>| Remove an IP or range of IPs from the Load balancer whitelist
|<<cloudhub load-balancer mappings describe>>| Lists the proxy mapping rules for a Load balancer. If no certificateName is given, the mappings for the default SSL endpoint are shown
|<<cloudhub load-balancer mappings add>>| Add a proxy mapping rule at the specified indexIf no certificateName is given, the mappings for the default SSL endpoint are shown
|<<cloudhub load-balancer mappings remove>>| Remove a proxy mapping ruleIf no certificateName is given, the mappings for the default SSL endpoint are shown
|<<cloudhub describe-regions>>| Lists all supported regions
|<<cloudhub describe-runtimes>>| Lists all available runtimes
|<<cloudhub vpc list>>| Lists all VPCs
|<<cloudhub vpc describe>>| Show VPC details
|<<cloudhub vpc describe-json>>| Show raw VPC JSON response
|<<cloudhub vpc create>>| Create a new VPC
|<<cloudhub vpc delete>>| Delete an existing VPC
|<<cloudhub vpc environments add>>| Modifies the VPC association to Runtime Manager environments.
|<<cloudhub vpc environments remove>>| Modifies the VPC association to Runtime Manager environments.
|<<cloudhub vpc business-groups add>>| Share a VPC with a list of Business Groups.
|<<cloudhub vpc business-groups remove>>| Share a VPC with a list of Business Groups.
|<<cloudhub vpc dns-servers set>>| Sets the domain names that are resolved using your internal DNS servers. If used with no option, internal DNS will be disabled
|<<cloudhub vpc firewall-rules describe>>| Show firewall rule for Mule applications in this VPC
|<<cloudhub vpc firewall-rules add>>| Add a firewall rule for Mule applications in this VPC
|<<cloudhub vpc firewall-rules remove>>| Remove a firewall rule for Mule applications in this VPC
|===

An Anypoint-CLI call should then have the following form:
[source,bash]
----
$ anypoint-cli [params] [command]
----

If you choose not to pass a command, Anypoint-CLI will run in *interactive mode*.
If you choose to pass a specific command and there is an error, the application will exit and return you a description of the issue.

== List of commands

[TIP]
Use the `--help` option with a command to see what options are available.

=== account describe-me
[source,bash]
----
$ account describe-me  [options]
----

This command simply returns the information for your account. This includes your username, your full name, your email address, and creation of your account. +
This command does not take any options, except for the default `--help`

=== account describe-business-groups
[source,bash]
----
$ account describe-business-groups [options]
----

This command displays all link:/access-management/organization#business-groups[business groups]. It returns return the name of the business group, the type ('Master' or 'Business unit') and the Id. +
This command does not take any options, except for the default `--help`.


=== account describe-business-group
[source,bash]
----
$ account describe-business-group  [options] <name>
----

This command displays information on the business group you pass in <name>.

[NOTE]
--
If your business group or organization name contains spaces, you need to enclose its name between `"` characters.

----
account describe-business-group "QA Organization"
----
--

It returns data such as the owner, the type, subscription information, the entitlements of the group and in which environment is running.
This command does not take any options, except for the default `--help`.

=== account switch-business-group
[source,bash]
----
$ account switch-business-group  [options] <name>
----
This command makes the business group you specified in <name> active.

[NOTE]
--
If your business group or organization name contains spaces, you need to enclose its name between `"` characters.

----
account switch-business-group "QA Organization"
----
--

=== account describe-environments
[source,bash]
----
$ account describe-environments [options]
----
This command lists all your Environments in your Anypoint Platform. It will return your environment name, its Id and whether it's sandboxed or not. +
This command does not take any options, except for the default `--help`.

=== account use-environment
[source,bash]
----
$ account use-environment [options] <name>
----
This command makes active the environment specified in <name>. +
This command does not take any options, except for the default `--help`.

=== account create-environments
[source,bash]
----
$ account create-environments [options] <name>
----
This command creates a new environment using the name you set in <name>. +
You can use the `--sandbox` option to create this environment as a sandbox, or use the default `--help`.

=== account delete-environment
[source,bash]
----
$ account delete-environment  [options] <name>
----
This command deletes the environment specified in <name> +

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default `--help`.

=== runtime-mgr describe-applications
[source,bash]
----
$ runtime-mgr describe-applications [options]
----

This command lists all applications available in your Anypoint-CLI. It returns your application name, its status, the amount of vCores assigned and the last time it was updated. +
This command does not take any options, except for the default `--help`.

=== runtime-mgr describe-application
[source,bash]
----
$ runtime-mgr describe-application [options] <name>
----

This command displays information on the application you pass in <name>. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
It will return data such as the application's domain, its status, last time it was updated, the Runtime version, the .zip file name, the region, monitoring and Workers; as well as 'TRUE' or 'FALSE' information for persistent queues and static IPs enablement. +
This command does not take any options, except for the default `--help`.

=== runtime-mgr describe-application-json
[source,bash]
----
$ runtime-mgr describe-application-json  [options] <name>
----

This command returns the raw JSON response of the application you specify in <name>. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== runtime-mgr stop-application
[source,bash]
----
$ runtime-mgr stop-application  [options] <name>
----

This command stops the running application you specify in <name> +
You can start typing your application's name and hit `tab` for Anypoint-ClI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== runtime-mgr start-application
[source,bash]
----
$ runtime-mgr start-application [options] <name>
----

This command starts the running application you specify in <name> +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== runtime-mgr restart-application
[source,bash]
----
$ runtime-mgr restart-application  [options] <name>
----

This command restarts the running application you specify in <name> +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== runtime-mgr delete-application
[source,bash]
----
$ runtime-mgr delete-application [options] <name>
----

This command deletes the running application you specify in <name>

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default `--help`.

=== runtime-mgr deploy-application
[source,bash]
----
$ runtime-mgr deploy-application  [options] <name> <zipfile>
----

This command deploys the Mule deployable archive .zip file that you specify in <zipfile> using the name you set in <name>. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
You will have to provide the absolute or relative path to the deployable zip file in your local hard drive and the name you give to your application has to be unique.

The options this command can take are:
[width="100a",cols="30a,70a",options="header"]
|===
|Option |Description
|--runtime                                   | Name of the runtime environment
|--workers                                      | Number of workers. (This value is '1' by default)
|--workerSize                               | Size of the workers in vCores. (This value is '1' by default)
|--region                                        | Name of the region to deploy to. +
For a list of all supported regions, use the <<cloudhub describe-regions>> command.
|--property                                    | Set a property (name:value). Can be specified multiple times
|--propertiesFile                        | Overwrite all properties with values from this file. The file format is 1 or more lines in name=value format. Set the absolute path of the properties file in your local hard drive.
|--persistentQueues                   | Enable or disable persistent queues. Can take 'true' or 'false' values. (This value is 'false' by default)
|--persistentQueuesEncrypted  | Enable or disable persistent queue encryption. Can take 'true' or 'false' values. (This value is 'false' by default)
|--staticIPsEnabled                                      | Enable or disable static IPs. Can take 'Enable' or 'Disabled' values. (This value is 'Disabled' by default)
|--autoRestart                            | Automatically restart app when not responding. Can take 'true' or 'false' values. (This value is 'false' by default)
|--help                                                  | output usage information
|===
Note that from Anypoint-CLI you won't be able to allocate static IPs. You can simply enable and disable them.

After typing any option, you can double tap the `tab` key for a full list of all possible options.
For exmaple:
[source,bash]
----
$ deploy <app name> --runtime [tab][tab]
----
Lists all possible runtimes you can select.

[IMPORTANT]
====
If you deploy without using any options, your application will deploy using all your default values.
====

=== runtime-mgr modify-application
[source,bash]
----
$ runtime-mgr modify-application  [options] <name> [zipfile]
----
This command updates the settings of an existing application. Optionally you can update it by uploading a new .zip file. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.
This command can take all the same options as the *deploy* option.

You can also start typing your option and hit `tab` for Autocomplete-CLI to autocomplete it for you.

=== runtime-mgr revert-application-runtime
[source,bash]
----
$ runtime-mgr revert-application-runtime [options] <name>
----
This command reverts the application defined in <name> to its previous runtime environment. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== runtime-mgr download-application-logs
[source,bash]
----
$ runtime-mgr download-application-logs [options] <name> <directory>
----
This command downloads logs the for application specified in <name> to the specified directory. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
Keep in mind that contrarily to what you see in the UI, the logs you download from the CLI won't separate system logs from worker logs.

=== runtime-mgr tail-application-logs
[source,bash]
----
$ runtime-mgr tail-application-logs [options] <name>
----

This command tails application logs. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== cloudhub load-balancer list
[source,bash]
----
$ cloudhub cloudhub load-balancer list [options]
----
This command lists all load balancers in your Anypoint Platform. It displays load balancer's name, domain, its state and the VPC Id to which the load balancer is bound. +
This command does not take any options, except for the default `--help`.

=== cloudhub load-balancer describe
[source,bash,linenums]
----
cloudhub load-balancer describe [options] <name>
----
This command displays information about the load balancer that is specified in <name>. +
You can start typing your load balancer's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
It displays load balancer's name, domain, its state and the VPC Id to which the load balancer is bound.
This command does not take any options, except for the default `--help`.

=== cloudhub load-balancer describe-json
[source,bash,linenums]
----
cloudhub load-balancer describe [options] <name>
----
This command displays raw JSON response of the load balancer that is specified in <name>. +
You can start typing your load balancer's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== cloudhub load-balancer create
[source,bash,linenums]
----
cloudhub load-balancer create [options] <vpc> <name> <certificate> <privateKey>
----
This command creates a load balancer using the specified values in the variables.
[cols="12,53a,35a",options="header"]
|===
|Value |Description |Example
| vpc |Id of the VPC to which this load balancer is bound. | vpc-827160e6
| name |Name for the load balancer. | newtestloadbalancer
| Certificate |Absolute path to the `.pem` file of your certificate in your local hard drive. | /Users/mule/Documents/cert.pem
| privateKey |Absolute path to the `.asc` file of your private key in your local hard drive. | /Users/mule/Documents/privateKey.asc
|===
This command does not take any options, except for the default `--help`.

[CAUTION]
The name for the load balancer that you pass in <name> must be unique. +
By defualt your load balancer listens external requests on https and communicates with your workers internally through http. You need to configure your application to listen through http on port 8091 for your load balancer to work.

=== cloudhub load-balancer start
[source,bash,linenums]
----
cloudhub load-balancer start [options] <name>
----
This command starts the load balancer specified in <name>. +
This command does not take any options, except for the default --help.


=== cloudhub load-balancer stop
[source,bash,linenums]
----
cloudhub load-balancer stop [options] <name>
----
This command stops the load balancer specified in <name>. +
This command does not take any options, except for the default --help.

=== cloudhub load-balancer delete
[source,bash,linenums]
----
cloudhub load-balancer delete [options] <name>
----
This command deletes the load balancer specified in <name>. +

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default --help.

=== cloudhub load-balancer ssl-endpoint add
[source,bash,linenums]
----
cloudhub load-balancer ssl-endpoint add [options] <name> <certificate> <privateKey>
----
This command adds an SSL endpoint to the load balancer specified in <name>, using the certificate and private key passed.

[cols="12a,53a,35a",options="header"]
|===
|Value |Description |Example
| name |Name for the load balancer. | newtestloadbalancer
| Certificate |Absolute path to the `.pem` file of your certificate in your local hard drive. | /Users/mule/Documents/cert.pem
| privateKey |Absolute path to the `.asc` file of your private key in your local hard drive. | /Users/mule/Documents/privateKey.asc
|===

[NOTE]
Cloudhub does not implement the Online Certificate Status Protocol (OCSP), so in order to keep your certification revocation list up to date, it's recommended to use the link:https://anypoint.mulesoft.com/apiplatform/sebastiankorol/#/portals/organizations/e853b9c5-6fb4-4590-8b25-0d29efeb8e98/apis/66762/versions/69421[REST API] to programmatically update your certificates.

This command does not take any options, except for the default --help.

=== cloudhub load-balancer ssl-endpoint remove
[source,bash,linenums]
----
cloudhub load-balancer ssl-endpoint remove [options] <name> <certificateName>
----
This command removes the ssl certificate specified in <certificateName> from the load balancer specified in <name>.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default --help.

=== cloudhub load-balancer ssl-endpoint set-default
[source,bash,linenums]
----
cloudhub load-balancer ssl-endpoint set-default [options] <name> <certificateName>
----
This command sets the certificate specified in <certificateName> as the default  certificate for the load balancer passed in <name>. +
This command does not take any options, except for the default --help.

=== cloudhub load-balancer ssl-endpoint describe
[source,bash,linenums]
----
cloudhub load-balancer ssl-endpoint describe [options] <name> <certificateName>
----
This command shows information about the configuration of the load balancer passed in <name> for the common name of the certificate specified in <certificateName>. +
This command does not take any options, except for the default --help.

=== cloudhub load-balancer whitelist add
[source,bash,linenums]
----
cloudhub load-balancer whitelist add [options] <name> <cidrBlock>
----
This command adds an IP, or range of IPs addresses specified in <cidrBlock> to the whitelist of the load balancer specified in <name>.

[NOTE]
The whitelist works at the load balancer level, not at the CN certificate level. Make sure you only pass IP addresses.

This command does not take any options, except for the default --help.

=== cloudhub load-balancer whitelist remove
[source,bash,linenums]
----
$ cloudhub load-balancer whitelist remove <name> <cidrBlock>
----
This command removes an IP, or range of IPs addresses specified in <cidrBlock> to the whitelist of the load balancer specified in <name>.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default --help.

=== cloudhub load-balancer mappings describe
[source,bash,linenums]
----
$ cloudhub load-balancer mappings describe <name> [certificateName]
----
This command lists the mapping rules for the load balancer specified in <name>. +
If no `certificateName` is passed, Anypoint CLI returns the mappings for the default SSL endpoint.

Beyond the `--certificateName` option, this command takes the default `--help` option.

=== cloudhub load-balancer mappings add
[source,bash,linenums]
----
$ cloudhub load-balancer mappings add <name> <index> <inputUri> <appName> <appUri> [certificateName]
----
This command adds a proxy mapping rule to the load balancer specified in <name> at the priority index specified in <index> in the CN passed under the `certificateName` option, using the values set in the variables +

[cols="12a,68a,20a",options="header"]
|===
|Value |Description |Example
|name|Name of the load balancer to which this rule is applied. |testloadbalancer
|index|Priority of the rule.  |1
// |inputSubdomain|Name of the sub-domain of your input URL |{app}.api
|inputUri|Name of the URI of your input URL |example.com
|appName|Name of the app of your output URL to which the request is forwarded |{app}-example
|appUri|URI of the app of your output URL to which the request is forwarded |/
|===

For the values in the example above, for an input call to `my-superapp.api.example.com/status?limit=10`, the endpoint `my-superapp-example: /status?limit=10` will be called for the application.

Beyond the `--certificateName` option, this command takes the default `--help` option. +
If no `certificateName` is passed, Anypoint CLI adds the mappings for the default SSL endpoint.

=== cloudhub load-balancer mappings remove
[source,bash,linenums]
----
$ cloudhub load-balancer mappings remove <name> <index> [certificateName]
----
This command removes the proxy mapping rules from the load balancer specified in <name> at the priority index specified in <index> and the CN specified as the `certificateName` option.

Beyond the `--certificateName` option, this command takes the default `--help` option. +
If no `certificateName` is passed, Anypoint CLI removes the mappings for the default SSL endpoint.

=== cloudhub describe-regions
[source,bash]
----
$ cloudhub describe-regions [options]
----
This command lists all supported regions. +
This command does not take any options, except for the default `--help`.

=== cloudhub describe-runtimes
[source,bash]
----
$ cloudhub describe-runtimes [options]
----
This command lists all supported runtimes. +
This command does not take any options, except for the default `--help`.

=== cloudhub vpc list
[source,bash]
----
$ cloudhub vpc list [options]
----
This command lists all available VPCs. It returns ID, region, and environment of the network and wether it is the default VPC or not.

=== cloudhub vpc describe
[source,bash,linenums]
----
$ cloudhub vpc describe [options] <name>
----
This command displays information about the VPC that is specified in <name>. +
You can start typing your VPC's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== cloudhub vpc describe-json
[source,bash,linenums]
----
cloudhub vpc describe [options] <name>
----
This command displays raw JSON response of the VPC that is specified in <name>. +
You can start typing your VPC's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== cloudhub vpc create
[source,bash,linenums]
----
$ cloudhub vpc create [environments...] <name> <region> <cidrBlock>
----
This command creates a VPC using the name in <name> in the region specified in <region>, with the size passed in <cidrBlock> in the form of a Classless Inter-Domain Routing (CIDR) block, using link:https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing#IPv4_CIDR_blocks[CIDR notation]. +
More information on how to size your VPC can be found here.


[CAUTION]
--
When creating a VPC, make sure to allow your outbound address. +
By default, all IP addresses are blocked and you need to authorize IP addresses, or range of addresses to your VPC firewall rule.
--

[NOTE]
A VPC needs to be bound to either an organization, or business group within that organization. When creating a VPC, you need to assign it somewhere, otherwise the VPC will not work.

Beyond the default `--help` option, this command also takes the `--environments` option. You need to pass the link:/access-management/environments[environment] to which this VPC is associated.

=== cloudhub vpc delete
[source,bash,linenums]
----
$ cloudhub vpc delete <name>
----
This command deletes the VPC specified in <name>.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default `--help`.

=== cloudhub vpc environments add
[source,bash,linenums]
----
cloudhub vpc environments add [environments...] <vpc>
----
This command assigns the VPC defined in <vpc> to the environment passed in the `--environments` option. +
Beyond the `--environments` option, this command also takes the default `--help` option.

=== cloudhub vpc business-groups add
[source,bash,linenums]
----
$ cloudhub vpc business-groups add [options] <vpc> <businessGroups...>
----
This command assigns the VPC defined in <vpc> to the business group passed in <businessGroups> +
This command does not take any options, except for the default `--help`.

=== cloudhub vpc business-groups remove
[source,bash,linenums]
----
$ cloudhub vpc business-groups remove [options] <vpc> <businessGroups...>
----
This command removes the VPC defined in <vpc> from the business group passed in <businessGroups> +

[WARNING]
This command does not prompt twice before removing the VPC from the specified resource. If you send a remove instruction, it does not ask for confirmation.

This command does not take any options, except for the default `--help`.

=== cloudhub vpc dns-servers set
[source,bash,linenums]
----
$ cloudhub vpc dns-servers set [options] <vpc>
----
This command sets a list of local host names (internal domain names) to be resolved using your internal DNS servers for which you need to provide their public IP addresses. +
Whenever those private domains are provided, your worker will resolve them using your private DNS, so you can still use the internal host names of your private network.

[NOTE]
This feature is supported by workers running Mule versions 3.4 and older.

This command does not take any options, except for the default `--help`.


=== cloudhub vpc firewall-rules describe
[source,bash,linenums]
----
$ cloudhub vpc firewall-rules describe <vpc>
----
This command describes all the firewall rules for the VPC defined in <vpc>. +
This command does not take any options, except for the default `--help`.


=== cloudhub vpc firewall-rules add
[source,bash,linenums]
----
$ cloudhub vpc firewall-rules add <vpc> <cidrBlock> <protocol> <fromPort> [toPort]
----
This command adds a firewall rule to the VPC defined in <vpc> using the values set in the variables +

[cols="18a,62a,20a",options="header"]
|===
|Value |Description |Example
| vpc |Id of the VPC to which this load balancer is bound. | vpc-827160e6
| cidrBlock | IP address or range of addresses for the firewall to allow  | 192.0.1.*
| protocol | |
| fromPort | |
| toPort | |
|===

This command does not take any options, except for the default `--help`.

=== cloudhub vpc firewall-rules remove
[source,bash,linenums]
----
$ cloudhub vpc firewall-rules remove <vpc> <index>
----
This command removes the firewall rule from the VPC specified in <vpc> at the index passed in the <index>. +
This command does not take any options, except for the default `--help`.


=== token
[source,bash]
----
$ token [options]
----
This command returns your API access token. +
This command does not take any options, except for the default `--help`.

=== exit
[source,bash]
----
$ exit [options]
----
This command exits Anypoint-CLI. +
This command does not take any options, except for the default `--help`
