= API Gateway Runtime 101
:keywords: gateway, cloudhub, policy, connectors

Mule 3.8.0 unifies the API Gateway runtime with the core Mule runtime.

=== What is an API Gateway Runtime?

An API Gateway runtime is used with Mule 3.7.x and earlier. API Gateway runtime was designed and optimized to host an API or to open a connection to an API deployed to another runtime. The API Gateway runtime performs a number of functions critical to running and managing APIs.

* Serves as a point of control over APIs, determining which traffic is authorized to pass through the API to backend services, to meter the traffic flowing through, to log all transactions, and to apply runtime policies to enforce governance like rate limiting, throttling, and caching.
* Integrate APIs with the backend services that power them. An API is just an interface that calls functionality living in a service or application, and unless that functionality lives in a well-defined web service, integration and orchestration capabilities are required to connect it to the API.

=== What are the capabilities and limitations of the API Gateway runtime?

The API Gateway runtime capabilities are limited in the following ways:

[cols=",",options]
|===
|*Connectors* a|
* HTTP/S
* Jetty
* Web Services Consumer
* JDBC
File
|*Custom Connectors* |Not supported
|*Integration Capabilities* a|
* Message processors
* Transaction management
* Error handling
* Mule Expression Language (MEL)
* DataWeave (Transform Message)
* DataMapper
* DataWeave
|*Batch Processing* |Not supported
|===

[NOTE]
To use other connectors or components you must purchase a license for Mule Enterprise. Contact a  mailto:info@mulesoft.com[sales representative]  for more information.

=== What is a policy?

A policy is a mechanism for enforcing filters on traffic. These filters generally control things like authentication, access, allotted consumption, and SLAs. The Anypoint Platform for APIs comes with a number of pre-built policies including Rate Limiting, Throttling, OAuth 2, Basic HTTP Authentication, and XML and JSON threat protection. Custom policies can be built to support needs not addressed by out-of-the-box policies. Policy features are licensed to API Gateway runtime and API Manager functions.

=== Where is an API Gateway runtime deployed?

An API Gateway runtime can be deployed to the cloud or on premises. Deciding on the right environment for your use case depends on a number of factors including the location of backend endpoints, enterprise architecture, and corporate security policy. Gateways can be deployed as single nodes or in clusters to support HA and high throughput use cases.

=== Where can I get more information about configuring my API Gateway runtime?

See link:/anypoint-platform-for-apis/configuring-an-api-gateway[Configuring an API Gateway] for more details.

=== What are the support policies for API Gateway versions and API Gateway Runtimes?

The support policies for these offerings are described in the link:https://www.mulesoft.com/legal/versioning-back-support-policy[Product Versioning and Back Support Policy].
