= To Deploy a Mule Application to CloudHub (Mule Maven Plugin)

== Prerequesites

To successfully deploy your Mule application to CloudHub, consider the following requirements:

* The host and port number of your HTTP Listener flow sources are properly configured. +
:: If you are using the HTTP Listener as sources for your flow, you need to set its host to *0.0.0.0* and its port to *${http.port}*. +
CloudHub then dynamically allocates a port at deployment time.
* All your external classes and resources are properly declared in the `mule-artifact.json` file of your Mule application. +
:: Due to Mule 4.x classloading isolation mechanism, all external classes and resources must be explicitly declared in the "exportedPackages" and "exportedResources" fields on the mule-artifact.json file before packaging and deploying the application. +
+
See the link:/mule4-user-guide/v/4.1/how-to-export-resources[How to Export Resources] task to learn more about working with external resources in your Mule application.

== Deploying to CloudHub

. Make sure you added the Mule Maven Plugin to your pom.xml file.
. Inside the plugin you element, add a configuration for your CloudHub deployment as shown below:
+
[source,xml,linenums]
----
<plugin>
  ...
    <configuration>
        <cloudHubDeployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <muleVersion>${mule.version}</muleVersion>
            <username>${username}</username>
            <password>${password}</password>
            <applicationName>${cloudhub.application.name}</applicationName>
            <environment>${environment}</environment>
            <properties>
                <key>value</key>
            </properties>
        </cloudHubDeployment>
    </configuration>

</plugin>
----
+
The example is using placeholder values. Configure each value with your own CloudHub information.
. From the command line in your project's folder, package the application and run the deploy goal:
+
[source,bash,linenums]
----
> mvn clean package deploy -DmuleDeploy
----

== Redeploying to CloudHub

To redeploy the application, run the same command as you did to deploy. +
CloudHub rewrites the application you had deployed.

== See Also

* link:cloudhub-deployment-mmp-reference[CloudHub Deployment Reference (Mule Maven Plugin)]
* link:add-mmp-task[To Add the Mule Maven Plugin to a Project]
