= Example: Conditional List Reduction Via a Function
:keywords: studio, anypoint, transform, transformer, format, aggregate, rename, split, filter convert, xml, json, csv, pojo, java object, metadata, dataweave, data weave, datamapper, dwl, dfl, dw, output structure, input structure, map, mapping

//TODO: EXAMPLE NOT WORKING, CHANGED when to if.

This example flattens the input to something simpler. For each element in the input, it conditionally includes a "contentTypes" field only in case it has any values. It then rearranges this content into a more readable shape.


The example uses these functions:

* `map` to go through every element in the input array.
* `reduce` to aggregate the multiple elements in the "tags" array into one field.
* `splitBy` to parse the values in the "tags" array, so as to only select the first part of each string (through `[0]`) and discard the second.
* `++` to concatenate these elements into one single string, with commas as separators.
* `if` include the last field only if the "contentTypes" array is bigger than 0.

.DataWeave
[source,dataweave, linenums]
----
%dw 2.0
output application/json
fun
reduceMapFor(data) data reduce(($$ splitBy ":")[0] ++ "," ++ ($ splitBy ":")[0])
---
payload.results map
    {
        email: $.profile.email,
        name: $.profile.firstName,
        tags: reduceMapFor($.data.interests.tags[0]),
        (contenttypes: reduceMapFor($.data.interests.contenttypes[0])) if (sizeOf($.data.interests.contenttypes[0])) > 0
    }
----

.Input JSON
[source,json, linenums]
----
{
  "results": [
    {
      "profile": {
        "firstName": "john",
        "lastName": "doe",
        "email": "johndoe@demo.com"
      },
      "data": {
        "interests": [
          {
            "language": "English",
            "tags": [
              "digital-strategy:Digital Strategy",
              "innovation:Innovation"
            ],
            "contenttypes": []
          }
        ]
      }
    },
    {
      "profile": {
        "firstName": "jane",
        "lastName": "doe",
        "email": "janedoe@demo.com"
      },
      "data": {
        "interests": [
          {
            "language": "English",
            "tags": [
              "tax-reform:Tax Reform",
              "retail-health:Retail Health"
            ],
            "contenttypes": [
              "News",
              "Analysis",
              "Case studies",
              "Press releases"
            ]
          }
        ]
      }
    }
  ],
  "objectsCount": 2,
  "totalCount": 2,
  "statusCode": 200,
  "errorCode": 0,
  "statusReason": "OK"
}
----

.Output JSON
[source,json, linenums]
----
[
  {
    "email": "johndoe@demo.com",
    "name": "john",
    "tags": "digital-strategy,innovation"
  },
  {
    "email": "janedoe@demo.com",
    "name": "jane",
    "tags": "tax-reform,retail-health",
    "contenttypes": "News,Analysis,Case studies,Press releases"
  }
]
----

== Related Examples

* link:dataweave-cookbook-exclude-field[Excluding Fields from the Output]

* link:dataweave-cookbook-output-a-field-when-present[Outputting a Field When Present]

* link:dataweave-cookbook-use-constant-directives[Using Constant Directives]

* link:dataweave-cookbook-define-function-to-flatten-list[Defining a Function that Flattens Data in a List]

* link:dataweave-cookbook-pass-functions-as-arguments[Passing Functions as Arguments]


== See Also


// * link:dw-functions-core[DataWeave Core Functions]

* link:dataweave-selectors[DataWeave Selectors]

* link:dataweave-cookbook[DataWeave Cookbook]
