= How to Export Resources

Mule Applications, Mule Domains and Mule Policies contain a set of resources which may be properties files, dataweave transformation files, java classes, etc. By default all of these files are internal to the artifact in which they are defined and can't be accesible from other artifacts. For instance, a resource defined at the domain level, if it's not exported, it can't be accesed within the applications that belong to that domain. Another example are classes from an application that are meant to be used by the java module. If those clases are not exported then the java module won't be able to access them.

== How to export java classes

To export java classes use the `exportedPackages` field of the `mule-artifact.json` file of your artifact. Have in mind that only complete packages can be exported and not individual classes.

[source, json, linenums]
----
{
    "name": "MyApp",
    "minMuleVersion": "4.0.0",
    "classLoaderModelLoaderDescriptor": {
        "id": "mule",
        "attributes": {            
            "exportedPackages": [
                "org.mule.myapp.api.customer",
                "org.mule.myapp.api.account"
            ]
        }
    }
}
----

CAUTION: Export the minimum number of classes required for your application to work. This will diminish the likelyhood of conflicts with other artifacts like modules or connectors that you may be using within your application.

TIP: Try to use `.api.` within public packages and `.internal.` within your non public pacakges.


== How to export resource files

To export resources use the `exportedResources` filed of the `mule-artifact.json` file of you artifact.

[source, json, linenums]
----
{
    "name": "MyApp",
    "minMuleVersion": "4.0.0",
    "classLoaderModelLoaderDescriptor": {
        "id": "mule",
        "attributes": {        
            "exportedResources": [
                "/org/mule/myapp/customer-to-user.dwl",
                "/org/mule/myapp/beans.xml"        
            ]        
        }
    }
  } 
}
----

IMPORTANT: This same mechanism applys to every artifact including extensions develop with the Mule SDK.