= Mule 4 for Mule 3 Users
// author: Dan D

Mule 4 improvements make it easier to learn, develop, and manage than Mule 3. For an overview of these capabilities, you should read link:mule-runtime-updates[What's New in Mule 4].

This documentation describes the differences between Mule 3 and Mule 4, indicates when you should migrate to Mule 4, and shows what it takes to migrate apps manually. It includes information on these topics:

* link:intro-overview[Introduction to Mule 4]: An overview of Mule 4 for those who already know Mule 3.
* link:migration-prep[Preparing for a Migration]: Steps to think about before migrating a Mule app.
* link:migration-process[About the Migration Process]: An overview of the major steps involved in a migration.
* link:migration-example-complex[Migration Example]: End-to-end example that shows the before (Mule 3) and after (Mule 4) syntax used for Mule apps.
* More in-depth migration details:
 ** link:migration-patterns[Migration Patterns]
 ** link:migration-core[Migrating Core Components]
 ** link:migration-connectors[Migrating Connectors]
 ** link:migration-api-gateways[Migrating API Gateways]
 ** link:migration-mel[Migrating from MEL to DataWeave]
 ** link:migration-dataweave[Migrating from DataWeave 1.0 to 2.x]
 ** link:migration-munit[Migrating MUnit]
+
// ** link:migration-devkit-to-mule-sdk[Migrating DevKit to the Mule SDK]

IMPORTANT: MuleSoft will be releasing a tool to help automatically update applications to Mule 4 soon. Unless there is some urgent need to migrate now, we recommend that for now only use Mule 4 for new projects and only use this guide as a learning tool for existing Mule 3 users.

This guide should apply to all 3.x versions. However, the 3.x examples use Mule 3.9.
