= About Exchange Portals

Exchange enables organizations to create a customized external view of Exchange
within an organization with specific logo, banner image, text, and a favicon for the browser tab.

Exchange portals are public on the internet and are used to 
externalize an organization's APIs to outside developers.

Organization users can log into the portal to customize the look and content of the portal.

Exchange portals let an organization share REST, SOAP, and HTTP APIs.

Exchange Administrators can share an API asset to a public portal as described in the sections that follow. 

== To Share an API Asset to a Public Portal

. Click an asset to show its details and click Share.
. Click *Add to the public portal*.
. (Optional) Click Share Internally if you decide to not put the asset in the public portal and instead return 
to the previous Share menu.
. (Optional) Click API Instances to manage instance visibility before proceeding. After following this link, you are 
returned to the previous Share menu.
. Click the version of the asset you want to publish in the public portal.
. Click Share. If no action occurs when you click Share, refresh your browser and log in again to repeat sharing the asset.

== To Make a Public Asset Private

. Click the asset in Exchange and click Share. 
. Click Add to the Public Portal. 
. Click the version field checkbox to uncheck the field. 
. Click Share.
. In Exchange, refresh the browser screen and you can see that the Visibility 
setting in the asset's Overview has changed to Private.

== See Also

* link:/anypoint-exchange/to-customize-portal[To Customize an Exchange Public Portal]
