= To Add an Anypoint Exchange Asset

////
Upload a REST Asset - Uploading an OAS (aka Swagger) or RAML API specification.
Upload a SOAP Asset - Uploading a WSDL for SOAP access.
Upload a Connector Asset - Uploading a connector asset
Add a New Version of an Asset
Browse Across Different Asset Versions
Upload a Custom Asset - Upload JARs, node.js, and other executables
////

== Contributing to Anypoint Exchange

Users must sign up with Anypoint Platform, log in, and be assigned either the “Exchange Contributors/Administrators” role to contribute items to an organization’s Exchange.

An organization can have up to 25 pieces of content on Exchange to start, after which they need to request more space from MuleSoft. Contact a mailto:info@mulesoft.com[sales representative] for more information.

All preloaded content from MuleSoft in Anypoint Exchange is read-only.
A “Submit Item” button on the top left of Exchange is displayed for users with the entitlements to create an entry in the organization’s Exchange. When a user submits an item, they are required to pick the item type from a drop down list. The item type denotes what fields are displayed on the item submission form. Irrespective of the content type selected, a number of standard metadata items are available to describe the item:

* *Name:* Name of the item to be displayed. (Mandatory)
* *Item ID:* The URI – string of characters used to identify a name of a resource so that the item can be shared as its own entity with its own URL internally. Authentication required. (Mandatory)
* *Icon URL:* URL of a web-hosted image. (Optional)
* *Summary:* A headline summary of the item. (Optional)
* *Author:* The creator(s) of the item and an image of them/their team. This is useful when the organization has many contributors and partners. (Optional)
* *Description:* Detailed description of the item. Use Markdown or HTML to edit this section.
* *YouTube Video URL:* YouTube video to provide more information about the item. This can be particularly useful for describing examples or how to leverage a template or connector.
* *Versions:* MuleSoft requires version information when adding an item to the Exchange. This allows users to identify and locate specific versions of an asset within the Exchange as it develops and matures over time.
** *File URL/Link:* Reference to the physical asset that constitutes the specific version of the item.
** *Version:* Version of the item.
** *Runtime:* The Mule runtime version the asset is supported on.
** *Documentation URL:* Reference to detailed documentation on a versioned asset (such as for developer reference documentation).
* *Tags:* Metadata tags that help describe the item and make it easier to discover and search in the Exchange.
* *Links:* Links to any additional or related resources.
When items are submitted, they are added to the Exchange in an unpublished state.  An unpublished item is only visible to the creator and Exchange Administrators. Exchange Administrators are responsible for publishing items. Following a review of the item, an administrator can publish the item and make it live at a click of a button.  Similarly Exchange Administrators can unpublish items.

=== Storing Assets

Anypoint Exchange does not store or host an organization’s assets. The Exchange provides a platform-wide interface for discovering and consuming the assets, but assets must be stored in external repositories.

Typically the assets themselves are stored in existing organizational repositories such as:

*	Source code repositories, such as GitHub or Atlassian Stash
*	Artifact repositories, such as Nexus or Artifactory
*	Content Management Systems (CMS), such as Wiki or Sharepoint
*	API portals
*	Other internet based resources, such as web sites


== Upload a REST Asset

== Upload a SOAP Asset

== Add a New Version of an Asset

== Browse Across Asset Versions

== Upload a Custom Asset


== See Also

* link:/anypoint-exchange/[Anypoint Exchange]
* link:/anypoint-exchange/access[Access Exchange]
* link:/anypoint-exchange/consume[Consume from Exchange]
* link:/anypoint-exchange/install-connector[Install a Connector]
* link:/anypoint-exchange/create-portal[Create Portal]
* link:/anypoint-exchange/administer[Administer]