= To Add an Asset
:keywords: exchange 2, exchange, asset, add

You can add an asset to Anypoint Exchange so that users in your organization can benefit from the asset. This feature lets Exchange act as a library where you can provide users examples, templates, APIs, blogs,
and other content that helps them use Anypoint products more effectively.


== To Contribute to Anypoint Exchange

To contribute an asset: 

. Log in or sign up at 
link:https://anypoint.mulesoft.com/#/signin[Anypoint Platform].
. Click *Exchange*. 
. In Exchange, click *Upload asset*. If this button is grayed out, in Anypoint Platform, 
click *Access Management* > *Roles*, and ensure you have access to  
*Exchange Contributors*.
. In *Creating an asset*, specify this information:
+
[%header%autowidth.spread]
|===
|Field |Required? |Description
|*Name:* |Yes |Name of the item to be displayed.
|*Asset Type* |Yes |Choose an asset type:

* *Example* - An Anypoint Studio generated Deployable Archive zip file that contains a complete Studio project. Users use Studio's Import feature to open the project in Studio and use it directly or add their
use case solution to it.
* *REST API* - A link:http://www.raml.org[RAML] or link:https://www.openapis.org[OAS] portal at 
link:https://anypoint.mulesoft.com/apiplatform/portal[API Platform Portal] that shows the API in action.
* *WSDL* - 
|===

=== About Storing Assets

Anypoint Exchange does not store or host an organization’s assets. The Exchange provides a platform-wide interface for discovering and consuming the assets, but assets must be stored in external repositories.

Typically the assets themselves are stored in existing organizational repositories such as:

*	Source code repositories, such as GitHub or Atlassian Stash
*	Artifact repositories, such as Nexus or Artifactory
*	Content Management Systems (CMS), such as Wiki or Sharepoint
*	API portals
*	Other internet based resources, such as web sites


== Upload a REST Asset

== Upload a SOAP Asset

== Add a New Version of an Asset

== Browse Across Asset Versions

== Upload a Custom Asset


== See Also

* link:/anypoint-exchange/[Anypoint Exchange]
* link:/anypoint-exchange/access[Access Exchange]
* link:/anypoint-exchange/consume[Consume from Exchange]
* link:/anypoint-exchange/install-connector[Install a Connector]
* link:/anypoint-exchange/create-portal[Create Portal]
* link:/anypoint-exchange/administer[Administer]