= To Administer Anypoint Exchange
:keywords: exchange, admin, administer

For a user to create, publish, update, or delete elements from an organization’s Exchange, a user must first be provisioned with the appropriate permissions. No user has permissions to submit or edit items by default, not even “Organization Administrators”.

The Anypoint Platform provides these roles that define who can administer or contribute content on the Exchange:

* *Exchange Contributors* - A role that allows users to add and edit their own items. However, any content created remains unpublished and is only visible to the creator and to “Exchange Administrators”, until such an administrator chooses to set the status of this contribution as “published”. Contributors can see all of the published content from others, but they cannot edit or delete any of it.

* *Exchange Administrator* - A role that allows users to add, edit, publish and delete all items. Exchange Administrators act as governors of the organization’s internal content with the ability to publish his own and others’ unpublished content to the Exchange. Once published, the content is visible to everyone in the organization. They can see, edit, or delete any content from others, whether it is published or not.

* *Organization Administrators* - Administer Exchange-specific roles through the standard Anypoint Platform user interface. See link:access-management/managing-permissions[Managing Permissions] for more details.

== See Also

* link:/anypoint-exchange/[Anypoint Exchange]
* link:/anypoint-exchange/access[Access Exchange]
* link:/anypoint-exchange/consume[Consume from Exchange]
* link:/anypoint-exchange/install-connector[Install a Connector]
* link:/anypoint-exchange/create-portal[Create Portal]
* link:/anypoint-exchange/add-asset[Add Asset]
