= To Use the Exchange Editor
:keywords: exchange, editor, edit

////
Use the Editor - Editing controls, and entering or modifying text using wysiwyg or Markdown syntax, as well as inserting a graphic, or video.
////

== Overview

Anypoint Exchange provides an editor you can use to describe an Exchange asset.

Anypoint Exchange uses link:https://help.github.com/categories/writing-on-github/[GitHub Markdown].

Sample commands are (see link:https://help.github.com/articles/basic-writing-and-formatting-syntax/[Basic writing and formatting syntax] for more commands):

* Headings:
+
[source,Syntax]
----
# The largest heading
## The second largest heading
###### The smallest heading
----
+
* Type:
+
[source,Syntax]
----
Bold:              **This is bold text**
Italics:           _Text in italics_
Bold and Italics:  **_Bold and italics_**
----
+
* Lists:
+
[source,Syntax]
----
* Bullet list
1. Numbered list
----
+
* Link: `(MuleSoft.com)[http://www.mulesoft.com]`

== See Also

* link:/anypoint-exchange/[Anypoint Exchange]
* link:/anypoint-exchange/access[Access Exchange]
* link:/anypoint-exchange/consume[Consume from Exchange]
* link:/anypoint-exchange/install-connector[Install a Connector]
* link:/anypoint-exchange/create-portal[Create Portal]
* link:/anypoint-exchange/administer[Administer]