= To Migrate Assets from Exchange 1 to Exchange 2
:keywords: exchange, migrate, migration, exchange 1, exchange 2, anypoint exchange

Anypoint Exchange 2 introduces a new way of working with your assets. Where Exchange 1 is a listing service that only provides links to where assets are stored, Exchange 2 is a package management system that stores assets. 

link:/anypoint-exchange/ex2-delete[Need to delete or deprecate an asset?]

Migration to Exchange 2 differs by asset type:

[%header,cols="30a,70a"]
|===
|Asset Type |Migration Approach
|Example, Template |Anypoint Studio > Publish to Exchange +
Document: xref:exortemp[To Migrate an Example or Template to Exchange]
|OAS REST API |Publish using Exchange +
Document: link:/anypoint-exchange/ex2-add-asset[Add an Asset to Exchange]
|RAML REST API |Publish using Design Center - *Note:* The API Designer in Design Center is only available to new customers. Existing customers must continue to use the API Designer in API Manager and must wait for Crowd Phase 2 release to migrate APIs.  +
Document: link:/design-center/v/1.0/upload-raml-task[To Upload an Existing RAML File to Exchange] and xref:restapi[To Migrate a RAML]. +
Video: https://youtu.be/WTIJrYydViQ[REST Assets]
|WSDL SOAP API |Manual publish in Exchange +
Document: link:/anypoint-exchange/ex2-add-asset[To Add an Asset to Exchange] and xref:soapapi[To Migrate a WSDL]. +
Video: https://youtu.be/BOAR9glreMw[SOAP Assets]
|Connectors |Use NPM +
Document: xref:connectors[To Migrate Connectors From Exchange 1 to Exchange 2]
|===	

[[exortemp]]
== To Migrate an Example or Template to Exchange

*Note:* This procedure requires https://maven.apache.org/download.cgi[Maven].

. In https://anypoint.mulesoft.com/exchange1/#!/[Anypoint Exchange 1], locate an example or template from your private Exchange and click Download. This puts the example or template on your computer.
. If you are using Anypoint Studio 6.3.0, create the .m2/setting.xml file. In a Mac or Linux, create the `~/.m2/settings.xml` file. In Windows create the `\Users\LOGIN_NAME\.m2\settings.xml` file.
+
Use this content in the settings.xml file:
+
[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
</settings>
----
+
. Open Anypoint Studio 6.3.0 and later, and click File > Import. 
. In the Import menu, click Anypoint Studio > Anypoint Studio Generated Deployable Archive (.zip). Click Next. For the zip file name, click the `...` browse button, click the name of the zip file you downloaded, and click Open. 
. Click Finish. Click OK for the Runtime version. 
. If you have not used Maven before, right-click the project name in the Package Explorer and click Mule > 
Configure Maven to locate the folder where you downloaded Maven. 
In Studio, click Test Maven Configuration to ensure Maven is ready to use and click OK.
+
When Maven is ready, right-click the project name in the Package Explorer and click Mule > Mavenize. 
At the Maven Support prompt, click Yes.
+
. In the Action to Perform menu, click OK. 
. Right-click the project name and click Anypoint Platform > Publish to Exchange.
. Studio prompts you for your Anypoint Platform username and password. Click Signin. Or click Configure to specify an external identity provider such as OAuth and the organization's domain.
. In the Publish to Exchange menu:
.. If present in the Name field, remove special characters such as an underscore and parentheses. Only letters, numbers, spaces, dots, and dashes are permitted.
.. If present in the Version field, remove the `-SNAPSHOT` value.
.. Set the Project Type to either Example or Template as needed.
. After setting all fields as required, click Finish. Click Yes for the Proceed Anyway prompt.
. Upon successful deployment, a link appears to let you view the asset in Exchange 2. Click the link.
. Click the asset in Exchange 2 and click Edit. In the Exchange editor, click Visual. Copy the description text from Exchange 1 to the Exchange 2 editor and paste the description into the editor. Format as needed. Click Save As Draft to save 
your edits. Click Publish.
. In Studio, click OK to dismiss the publish to Exchange menu.

[[soapapi]]
== To Migrate a SOAP API WSDL

. Go to Exchange 1 and download your WSDL file.
. Go to Exchange 2 and click New.
. Select API Spec - WSDL in the types drop-down.
. In the File field, select your WSDL file.
. Fill in the remaining fields.
. Click Create.

[[restapi]]
== To Migrate a REST API RAML

. Go to the API Manager Portal for the API and export the API Specification as a zip file.
. Go to Design Center API Designer and create a project of type API Specification.
. Import the zip.
. Publish to Exchange 2.

[[connectors]]
== To Migrate Connectors From Exchange 1 to Exchange 2

. Download and install NPM from https://www.npmjs.com/package/npm - instructions are provided for Mac, Linux, and Windows installations.
. In Exchange 1, log into your private Exchange and download the connector to your computer.
. Locate the connector JAR file and pom.xml file. You also need the connector zip file.
. Get the connector-uploader NPM application:
+
[source]
----
npm install -g connector-uploader
----
+
. Run the upload program:
+
[source]
----
connector-uploader
----
+
. When prompted, enter the Anypoint Platform credentials for the organization you want to upload the connector to. You are asked to select a business group and enter the Asset ID and version. The Group ID is generated for you. You are prompted to specify each file to upload if you are uploading more than one connector.

