= Workflow: To Share An Asset
:keywords: exchange, exchange 2, anypoint exchange

* Create a RAML API specification in Design Center and publish it to Exchange.
+
See: link:/design-center/v/1.0/upload-raml-task[To Upload an Existing RAML File to Exchange]
+
* To share an OAS API specification, name it index.json or index.yaml, compress it into a zip file, and click New to create an Exchange asset.
+
See: link:/anypoint-exchange/ex2-share-oas[To Upload an OAS Specification]
+
* To share a SOAP WSDL specification, click New to create an Exchange asset.
+
See: link:/anypoint-exchange/ex2-share-oas[To Share a SOAP WSDL Specification]
+
* To share a document or video, click New to create an Exchange Custom asset. You can use the Exchange editor to describe the asset and provide a link to it.
+
See: link:/anypoint-exchange/ex2-share-oas[To Share a Document or Video]
+
* To share an example or template, create it in Anypoint Studio, and click Anypoint Platform > Publish to Exchange.
+
See: link:/anypoint-exchange/ex2-share-example-template[To Share an Example or Template]


