= About Sharing Assets in Exchange

Anypoint Exchange lets you share assets you previously created, or to share text, videos, or links as a custom asset. 

To share assets, you specify the name for the asset, and use Exchange to display information and links to describe the asset. In addition, Exchange provides  features that let you view and test each API function and to test assets using the API Notebook built into Exchange. 

Using Exchange Portals you can create a site for your organization and share assets for your private Exchange.

When you share APIs for OAS REST or WSDL SOAP API in Exchange, you can quickly create assets. For assets such as RAML, you use Design Center, which lets you customize and mock test your RAML before publishing to Exchange. 

Examples, templates, and connectors start in Anypoint Studio to refine their code so you can add Mule components, test, and export as a Studio deployable resource.

After you publish your asset in Exchange, you can use the description editor to describe your asset and provide videos, links, tags, and examples that help users more effectively use and locate your asset.

Exchange also lets users review assets so that asset providers can get feedback.