= To Migrate Assets from Exchange 1 to Exchange 2
:keywords: exchange, migrate, migration, exchange 1, exchange 2, anypoint exchange

Anypoint Exchange 2 introduces a new way of working with your assets. Where Exchange 1 is a listing service that only provides links to where assets are stored, Exchange 2 is a package management system that stores assets. 

link:/anypoint-exchange/ex2-delete[Need to delete or deprecate an asset?]

Migration Videos:

* https://youtu.be/WTIJrYydViQ[REST Assets]
* https://youtu.be/BOAR9glreMw[SOAP Assets]
* https://youtu.be/kcIdsbJ7Puc[Examples and Templates]

Migration to Exchange 2 differs by asset type:

[%header,cols="25a,50a,25a"]
|===
|Asset Type |Migration Approach |Documents
|Example, Template |Anypoint Studio > Publish to Exchange|<<To Migrate an Example or Template to Exchange>>
|OAS API |Publish using Exchange |link:/anypoint-exchange/ex2-add-asset[Add an Asset to Exchange]
|RAML APIs |Publish using Design Center - *Note:* The API Designer in Design Center is only available to new customers. Existing customers must continue to use the API Designer in API Manager and must wait for Crowd Phase 2 release to migrate APIs.  |link:/design-center/v/1.0/upload-raml-task[To Upload an Existing RAML File to Exchange] and <<To Migrate a RAML>>. 
|WSDL APIs |Manual publish in Exchange |link:/anypoint-exchange/ex2-add-asset[To Add an Asset to Exchange] and <<To Migrate a WSDL>>.
|===	


== To Migrate an Example or Template to Exchange

. In https://anypoint.mulesoft.com/exchange1/#!/[Anypoint Exchange 1], locate an example or template from your private Exchange and click Download.
. Open Anypoint Studio 6.3.0 and later, and click File > Import. 
. In the Import menu, click Anypoint Studio > Anypoint Studio Generated Deployable Archive (.zip). Click Next. For the zip file name, click the `...` browse button, click the name of the zip file you downloaded, and click Open. 
. Click Finish. Click OK for the Runtime version. 
. Right-click the project name in the Package Explorer, and click Mule > Mavenize. Click Yes.
. In the Action to Perform menu, click OK. 
. Right-click the project name and click Anypoint Platform > Publish to Exchange.
. Studio prompts you for your Anypoint Platform username and password. Click Signin. Or click Configure to specify an external identity provider such as OAuth and the organization's domain.
. In the Publish to Exchange menu:
.. In the Name field, remove special characters such as an underscore and parentheses. Only letters, numbers, spaces, dots, and dashes are permitted.
.. In the Version field, remove the `-SNAPSHOT` value.
.. Set the Project Type to either Example or Template as needed.
. After setting all fields as required, click Finish. Click Yes for the Proceed Anyway prompt.
. Upon successful deployment, a link appears to let you view the asset in Exchange 2.
. Click the asset in Exchange 2 and click Edit. Copy the description text from Exchange 1 to the Exchange 2 editor and format as needed. Publish the asset when done.

== To Migrate a WSDL

. Go to Exchange 1 and download your WSDL file.
. Go to Exchange 2 and click New.
. Select API Spec - WSDL in the types drop-down.
. In the File field, select your WSDL file.
. Fill in the remaining fields.
. Click Create.


== To Migrate a RAML

. Go to the API Manager Portal for the API and export the API Specification as a zip file.
. Go to Design Center API Designer and create a project of type API Specification.
. Import the zip.
. Publish to Exchange 2.

