= To Migrate Assets from Exchange 1 to Exchange 2
:keywords: exchange, migrate, migration, exchange 1, exchange 2, anypoint exchange

Anypoint Exchange 2 introduces a new way of working with your assets. Where Exchange 1 is a listing service that only provides links to where assets are stored, Exchange 2 is a package management system that stores assets. 

Migration to Exchange 2 differs by asset type:

[%header,cols="25a,50a,25a"]
|===
|Asset Type |Migration Approach |Documents
|Connector, Example, Template |Anypoint Studio > Publish to Exchange|<<To Publish to Exchange Using Studio>>
|OAS API |Publish using Exchange |link:/anypoint-exchange/ex2-add-asset[Add an Asset to Exchange]
|RAML APIs |Publish using Design Center - *Note:* Use of new API Designer is only available for existing customers with existing RAMLs in Exchange. Entitlement is required to view the API Designer in the Design Center. You can request access by submitting a case to Customer Support for migration purposes only.|link:/design-center/v/1.0/upload-raml-task[To Upload an Existing RAML File to Exchange] and <<To Migrate a RAML>>. 
|WSDL APIs |Manual publish in Exchange |link:/anypoint-exchange/ex2-add-asset[To Add an Asset to Exchange] and <<To Migrate a WSDL>>
|===	

== To Publish to Exchange Using Studio

You can use Anypoint Studio to publish a connector, example, or template to Exchange.

. In Anypoint Studio, when you create your Mule project (File > New > Mule Project), 
click Use Maven in the create project menu. If Maven is not configured in Studio, use the prompts to locate the Maven folder and test the Maven setup. 
If Maven is not on your computer, first download it from the https://maven.apache.org/download.cgi[Apache Maven Project].
+
. Create the connector, example, or template.
. Right-click the project name and click Anypoint Platform > Publish to Exchange.
. In the Publish to Exchange menu under the Name field, ensure that the name is unique and does not already exist in your Exchange. If the name is already in use, increment the Version number. Studio does not prompt to replace an existing asset, the publish just fails.
. After setting all fields as required, click Finish. 

== To Migrate a WSDL

. Go to Exchange 1 and download your WSDL file.
. Go to Exchange 2 and click New.
. Select API Spec - WSDL in the types drop-down.
. In the File field, select your WSDL file.
. Fill in the remaining fields.
. Click Create.


== To Migrate a RAML

. Go to the API Manager Portal for the API and export the API Specification as a zip file.
. Go to Design Center API Designer and create a project of type API Specification.
. Import the zip.
. Publish to Exchange 2.

