= To Set Access Permissions for Exchange
:keywords: access, permissions

*Note:* Access to the Anypoint Exchange 2.0 Beta version requires an entitlement. 
Contact your mailto:amit.saxena@mulesoft.com[MuleSoft representative] for more information. After you get access, you can create, edit, and publish assets.

For users to create, publish, or update assets in an organization's Exchange, you need to provision their user accounts with the appropriate permissions.

. In link:https://anypoint.mulesoft.com/#/signin[Anypoint Platform], click Access Management. 
. Click Roles and set access to:
** Exchange Viewers - Can review assets and download assets.
** Exchange Contributors - All of Viewers privileges, plus can also create content, add new versions, and add tags.
** Exchange Administrator - All of Contributors and Viewers privileges, plus can also give permissions, delete an asset, and delete reviews from other users.

== See Also

* link:/access-management/managing-permissions[Access Management Managing Permissions] for more details.
