= To Migrate Assets from Exchange 1 to Exchange 2
:keywords: exchange, migrate, migration, exchange 1, exchange 2, anypoint exchange

Anypoint Exchange 2 introduces a new way of working with your assets. Where Exchange 1 is a listing service that only provides links to where assets are stored, Exchange 2 is a package management system that stores assets. 

Migration to Exchange 2 differs by asset type:

[%header,cols="25a,50a,25a"]
|===
|Asset Type |Migration Approach |Documents
|Connector, Example, Template |Anypoint Studio > Publish to Exchange|<<To Migrate a Connector, Example, or Template to Exchange>>
|OAS API |Publish using Exchange |link:/anypoint-exchange/ex2-add-asset[Add an Asset to Exchange]
|RAML APIs |Publish using Design Center - *Note:* New API Designer is only available for new customers.  Customers with existing RAMLs in Exchange may request entitlement to view the new API Designer in the Design Center for migration purposes only. Once the migration is completed, the entitlement must be revoked until new API designer is rolled out to all customers.|link:/design-center/v/1.0/upload-raml-task[To Upload an Existing RAML File to Exchange] and <<To Migrate a RAML>>. 
|WSDL APIs |Manual publish in Exchange |link:/anypoint-exchange/ex2-add-asset[To Add an Asset to Exchange] and <<To Migrate a WSDL>>
|===	

== To Migrate a Connector, Example, or Template to Exchange

. Locate an asset in your private Exchange and download the asset from Exchange 1. This is a zip file.
. Open Anypoint Studio 6.2.5 and click File > Import. Locate the zip file you downloaded from Exchange 1.
. Right-click the project name in the Package Explorer, and click Mule > Convert to Anypoint Studio Project.
. Right-click the project name and click Mule > Configure Maven. Configure Maven and click Test Maven Configuration. 
. Right-click the project name and click Mule > Enable Support.
. Open your project's pom.xml file and set the Group ID, artifact ID, and version to what is appropriate 
for your project. Also change the Name to what you want for the Exchange 2 asset. Save the project.
. Right-click the project name and click Anypoint Platform > Publish to Exchange.
. Studio prompts you for your Anypoint Platform username and password, or click Configure to specify an external identity provider such as OAuth and the organization's domain.
. In the Publish to Exchange menu:
.. Specify the Project Type, which can be App, Connector, Example, Template, or Undefined. 
.. If needed, specify an alternate name for the asset you are creating. *Note:* If an asset of the same name in your organization already exists in Exchange, the publish fails.
.. Provide a description.
. After setting all fields as required, click Finish.
. Upon successful deployment, a link appears to let you view the asset in Exchange 2.
. Click the asset in Exchange 2 and click Edit. Copy the description text from Exchange 1 to the Exchange 2 editor and format as needed. Publish the asset when done.

== To Migrate a WSDL

. Go to Exchange 1 and download your WSDL file.
. Go to Exchange 2 and click New.
. Select API Spec - WSDL in the types drop-down.
. In the File field, select your WSDL file.
. Fill in the remaining fields.
. Click Create.


== To Migrate a RAML

. Go to the API Manager Portal for the API and export the API Specification as a zip file.
. Go to Design Center API Designer and create a project of type API Specification.
. Import the zip.
. Publish to Exchange 2.

