= Workflow: To Share An Asset
:keywords: exchange, exchange 2, anypoint exchange

[%header%autowidth.spread]
|===
|Asset Type |Action
|Document or Video |Create an Exchange Custom asset. 

See: link:/anypoint-exchange/ex2-share-oas[To Share a Document or Video]
|Example |Create a Mavenized Anypoint Studio project and publish to Exchange.

See: link:/anypoint-exchange/ex2-share-example-template[To Share an Example or Template]
|OAS |Name the OAS specfication as index.json or index.yaml, compress it into a zip file, and create an Exchange asset specifying the type as OAS.

See: link:/anypoint-exchange/ex2-share-oas[To Upload an OAS Specification]
|RAML |Create a RAML API specification in Design Center and publish it to Exchange.

See: link:/design-center/v/1.0/upload-raml-task[To Upload an Existing RAML File to Exchange]
|SOAP API |Create an Exchange asset and indicate the WSDL file.

See: link:/anypoint-exchange/ex2-share-oas[To Share a SOAP WSDL Specification]

|Template |Create a Mavenized Anypoint Studio project and publish to Exchange.

See: link:/anypoint-exchange/ex2-share-example-template[To Share an Example or Template]
|===
