= To Access Anypoint Exchange
:keywords: exchange, access, anypoint exchange

Anypoint Exchange lets you publish design tools that
others in your organization can reuse to improve and
design their solutions. Exchange provides both public
and private assets that enable an organization to 
use each in applications.

You can search Anypoint Exchange for a name, summary, 
or description, or click Any Types to filter the view.

Exchange lets you discover public assets, that is, those from MuleSoft, 
and private assets that you create for your organization.

For APIs you can also view the link:/api-manager/engaging-users-of-your-api[API Portal].

See Also: link:/anypoint-exchange/ex2-add-asset[To Add an Asset to Exchange]


== To Access from Anypoint Platform

. Sign into Anypoint Platform.
. Click Exchange 2.0.
. Click All Types to view assets by type, or search for an asset by name.
. To view the private Exchange for your organization, click your organization name 
in the left navigation bar.

== To Create Content for Anypoint Exchange

. Design the description of your asset considering the visual tools available in the 
link:/anypoint-exchange/ex2-editor[Exchange Editor] document.
. From within Exchange, click New.
. In Creating An Asset, specify the name of your asset, its type, and if needed, upload a file.
. Click Publish. This publishes an empty asset to your private Exchange organization.
. Use the editor to add the content you created in Step 1.
. Publish the updated asset content.

See Also: link:/anypoint-exchange/ex2-editor[To Edit An Asset Description]
