= To Explore Exchange

This document helps you explore Anypoint Exchange by performing a series of tasks.

*link:_attachments/index.json.zip[OAS JSON API Specification]*

== Task 1: Create a New Asset or Listing

To upload a file:

. Go to the Exchange landing page. 
. Click New and name the asset as <your name>. 
. Select the `Custom` asset type.
. Edit the asset to add description in the Visual editor and use the Markdown editor to embed a video by copying a embed video link from YouTube (or Vimeo). 
. Add a new page to add additional content about this asset. 
. Publish the asset.

* Embed MuleSoft video: +
`![](https://www.youtube.com/embed/K3tuHUZ1J04)`

Expected Result: Able to create a listing and enrich content of the listing using the Visual or Markdown editor. Able to Publish the asset. 

link:/anypoint-exchange/ex2-delete[Need to delete or deprecate an asset?]


== Task 2: Add Tags and Review 

Review an existing asset:

. Go to the Exchange landing page. 
. Find the asset you created in the Task 2. 
. Add 1-2 tags. 
. Go to the Exchange home page and find the asset using the tag you added. 
. Go to the detail view of your asset. Click the star rating to review the asset. 
. Add a review title, review text, and select/update the rating.
. Submit the review. 

Expected Result: Able to add tags to an asset or listing, and search using tags. Able to review an asset. 

== Task 3: Upload an OAS Swagger API Specification

Able to upload an link:https://www.openapis.org/[OAS (Swagger)] API specification file. 

Use this link:_attachments/index.json.zip[OAS JSON API Specification] for this task. 

. Select a file for a OAS 2.0 specification or use the attachment.
. After the asset uploads, add tags to the asset for searching. 
. Download the file in RAML format. 
. Download the file in OAS format.

Expected Result: Able to upload an OAS specification. Able to download the specification in either RAML or OAS format. 

== See Also

link:/anypoint-exchange/[Exchange documentation set]
