= To Share an Asset in Exchange

Anypoint Exchange lets you share assets you previously created, or to share text, videos, or links as a custom asset.

Sharing consists of creating an asset in Exchange and adding content and links to the asset to identify the type of asset. Asset types can be APIs, code examples and templates, connectors, and custom assets for sharing information. Programs such as Anypoint Studio work with Exchange to enable downloads of asset content. 

Exchange provides features such as an editor to add descriptions, videos, and links, as well as the ability to examine and test each API function. The API Notebook built into Exchange lets you share information about each API method and so that users can experiment with the API by changing variables and running it in the notebook.

Using Exchange Portals you can create a site for your organization and share assets for your private Exchange.

== About Sharing Assets by Type

You can quickly share APIs for OAS REST or WSDL SOAP API in Exchange. For assets such as RAML, use Design Center to customize and mock test your RAML before publishing to Exchange. 

Examples, templates, and connectors start in Anypoint Studio to refine their code so you can add Mule components, test, and export as a Studio deployable resource.

After you publish your asset in Exchange, you can use the description editor to describe your asset and provide videos, links, tags, and examples that help users more effectively use and locate your asset.

Exchange also lets users review assets so that asset providers can get feedback.

== See Also

* link:/design-center/v/1.0/upload-raml-task[Share a RAML file to Exchange]
* https://beta-anypt.docs-stgx.mulesoft.com/anypoint-studio/v/7/export-to-exchange-task[Share an example or template from Studio to Exchange]
* link:/anypoint-exchange/ex2-to-publish-assets-maven[Share a connector to Exchange]
* link:/anypoint-exchange/