= Exchange 2 FAQ

This topic lists frequently asked questions and provides answers.

== Can I add a RAML to Exchange without using Design Center?

You can use a RAML-to-OAS converter to change the RAML to an OAS file. In Anypoint Exchange, 
create an asset and specify the type as API Spec - OAS. Exchange lets you test the specification
and if needed download it as either an OAS or RAML file.

== When I rename an asset, why does Exchange use the old name?

After changing the name for an asset, press the Return (or Enter) key on your keyboard. If you don't
press Return, Exchange reverts the asset name back to what it was before you changed it.

== Why don't my assets appear in my Public Portal?

You can add OAS or RAML REST API assets to the Public Portal by clicking the Share button and clicking Add to the public portal. When you share an asset to the Public Portal, the asset is then public and visible by anyone on the internet at the URL of your Public Portal.

== How do I remove an asset from a Public Portal?

Click the asset in Exchange and click Share. Click Add to the Public Portal. Click 
the version field checkbox to uncheck the field. Click Share. In Exchange, refresh 
the browser screen and you can see that the Visibility setting in the asset's Overview has
changed to Private.

== Can I add a JSON snippets to Exchange and refer to the snippets from another JSON schema?

You can use RAML data types, but not a JSON referenced by another JSON schema.

== Why is the CSS missing in Exchange assets in Windows 7 using Studio 6?

Exchange only works in Windows with the latest versions of Chrome, Firefox, and Internet Explorer 11. IE 9 is not supported and displays Exchange incorrectly.

== When I push a custom connector through Maven to Exchange, how can i define a custom icon?

You can upload an SVG icon with the icon classifier using a PUT to the Exchange REST API. Exchange adds the round border around the icon. You need to pass the authorization header with a bearer and access token.

For example, add the icon file to the HTTP body and use a PUT such as:

[source]
----
https://maven.anypoint.mulesoft.com/api/v1/organizations/:organizationId/maven/:groupId/:assetId/:version/:assetId-:version-icon.svg
----

== Can I integrate publication of assets to Exchange as part of a CI and CD pipeline?

You can use the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/2559c34c-bbc7-4a5a-b078-bc1154594906/apis/5152896/versions/98485[Exchange Experience API] to detect the difference if it exists so you don't republish to Exchange when there is no change.

// What difference?

