= Anypoint Exchange

Anypoint Exchange helps you create API portals, view and test APIs, add mocking services to APIs, create assets, and create API Notebooks that let you describe and test API functions. 

== Getting Started

Go to the public https://www.anypoint.mulesoft.com/exchange/[Exchange] and click the boxes (known as assets) and view the descriptions. Click Login to view a private Exchange for your organization. Your organization may have a public portal where 
API assets are available to anyone.

After you log into Exchange, you can create assets for APIs, connectors, templates, examples, and custom assets. 

== Try APIs

Click All Types > REST APIs and choose any API. Click the asset and notice how the API functions appear in the left 
navigation area. Exchange lets you view the functions in an API. Click a function and more information appears. At the right side of the screen, you can test the API by entering sample values to send to the API and get responses from the API. 

== Need More Information on an Asset?

Click the Helpful Links item in the left navigation area for links to documentation.

== About Content

Exchange assets are also accessible from API Manager and Runtime Manager in Anypoint Platform, and you can publish APIs
from Design Center to Exchange.

MuleSoft certifies its public content, and reviews and approves partner connectors. All private content is internal to an organization and not visible outside their organization. Customers are responsible for any private content they publish within their Exchange.

== See Also

* link:/release-notes/anypoint-exchange-release-notes[Anypoint Exchange Release Notes]
* link:/anypoint-exchange/migrate[Migrate Assets from Exchange 1]
