= Anypoint Exchange
:keywords: exchange, exchange2, anypoint exchange

Anypoint Exchange provides a unified user interface and API for discovery and consumption of connectivity and API assets.   

* Works directly with Anypoint Design Center, Anypoint Platform, and Anypoint Studio
to provide a single point of access for information and assets.
* Provides an central hub for your organization’s APIs, best practices, templates, examples, and information.

== To Navigate Anypoint Exchange

You can search Anypoint Exchange using tags and keywords for a name, summary, description, and tags of the items. Each element is tagged with labels that refer to a version, the Mule Runtime versions it supports, and more. 

Exchange lets you discover public assets from MuleSoft and private assets that you create for your organization. 

You can click View details for more information, or Download to add the item to  Studio workspace and open it in Studio.

For APIs you can also view the API's link:/api-manager/engaging-users-of-your-api[API Portal.]

== About Public and Private Cloud

Anypoint Exchange Private Cloud Edition (beta) enables companies to manage 
Exchange from their site.

For more information, see link:/release-notes/exchange-on-prem-release-notes[Anypoint Exchange Private Cloud Edition Release Notes].

* Anypoint Exchange private cloud does not allow users to access the MuleSoft tenant available on the cloud, and thus is shipped with no default content.
* Exchange Private Cloud is currently not accessible from Anypoint Studio.

== About Exchange Assets

Exchange provides assets for:

* Connectors - Connection software to third-party APIs and standard integration protocols. Anypoint Studio is preloaded with connectors that are listed in Exchange. 
* Templates - Packaged integration patterns that address common use cases and are built on best practices. 
* Examples - Ready to run implementation projects that demonstrate a use case or solution.
* REST APIs - link:https://www.raml.org[RAML] and link:https://www.openapis.org/[OAS] specifications that create access portals.
* SOAP APIs - API descriptions in a WSDL to create an access portal.
* Others - Blogs/Articles/Videos and more.

== About Certification

MuleSoft certifies its public content, and reviews and approves partner connectors. 

All private content is internal to an organization and not visible outside their organization. Customers are responsible for any private content they publish within their Exchange.

== About Ratings

Every piece of content, regardless of its type, has a rating associated to it. This rating is displayed next to the element once it has received two or more ratings.

*Note:* If you're rating a Connector, it needs to be installed in Anypoint Studio to rate it.

== About Other Resources

* link:/anypoint-exchange/access[Access Exchange]
* link:/anypoint-exchange/consume[Consume from Exchange]
* link:/anypoint-exchange/install-connector[Install a Connector]
* link:/anypoint-exchange/create-portal[Create Portal]
* link:/anypoint-exchange/add-asset[Add Asset]

