= To Set Access Permissions
:keywords: access, permissions

*Note:* Access to the Anypoint Exchange 2.0 Beta version requires an entitlement. 
Contact your mailto:amit.saxena@mulesoft.com[MuleSoft representative] for more information.

To create, publish, update, or delete elements from an organization’s Exchange, a user must first be provisioned with the appropriate permissions. No user has permissions to submit or edit items by default, not even “Organization Administrators”.

. Before adding an asset, log into link:https://anypoint.mulesoft.com/#/signin[Anypoint Platform] 
and click Access Management. 
. Click Roles and set access to Exchange Contributors - This role lets you add and edit your own items. However, any content created remains unpublished and is only visible to the creator and to “Exchange Administrators”, until such an administrator chooses to set the status of this contribution as “published”. Contributors can see all of the published content from others, but they cannot edit or delete any of it.
+
You can also set Exchange Administrator, which lets you add, edit, publish, and delete all Exchange assets. Exchange Administrators act as governors of the organization’s internal content with the ability to publish his own and others’ unpublished content to the Exchange. Once published, the content is visible to everyone in the organization. They can see, edit, or delete any content from others, whether it is published or not.

*Note:* Ensure Exchange users have unique organization IDs by setting the organization name in the Access Management > Organizations menu in Anypoint Platform.

== See Also

* link:access-management/managing-permissions[Access Management Managing Permissions] for more details.