= To Set Access Permissions
:keywords: access, permissions

*Note:* Access to the Anypoint Exchange 2.0 Beta version requires an entitlement. Contact your MuleSoft
representative for more information.

== About Role Access

To create, publish, update, or delete elements from an organization’s Exchange, a user must first be provisioned with the appropriate permissions. No user has permissions to submit or edit items by default, not even “Organization Administrators”.

The Anypoint Platform provides these roles for who can administer or contribute content on the Exchange:

* *Exchange Contributors* - Allows users to add and edit their own items. However, any content created remains unpublished and is only visible to the creator and to “Exchange Administrators”, until such an administrator chooses to set the status of this contribution as “published”. Contributors can see all of the published content from others, but they cannot edit or delete any of it.

* *Exchange Administrator* - Allows users to add, edit, publish and delete all items. Exchange Administrators act as governors of the organization’s internal content with the ability to publish his own and others’ unpublished content to the Exchange. Once published, the content is visible to everyone in the organization. They can see, edit, or delete any content from others, whether it is published or not.

* *Organization Administrators* - Administer Exchange-specific roles through the standard Anypoint Platform user interface. 

== See Also

* link:access-management/managing-permissions[Access Management Managing Permissions] for more details.