= To Configure Portal Settings

Anypoint Exchange lets you configure what groups of users access each service instance in an Exchange Portal. Typical services that you would set visibility for are proxies or policies associated with your API that you set using API Manager.

Visibility for each instance is either private or public. Public pertains to any user within a business group's Exchange Portal. Private is only those who can see the asset via Sharing the asset or per an Anypoint Platform role.

. Click a REST API that was created in your organization and click API Settings in the left navigation bar.
. The initial setting for each API is for the Mocking Service which provides data that you can use to test API features. The Mocking Service is always public. 
. Click *+ Add New Instance* to set the visibility for a policy or proxy that you created in API Manager.
. If you want the instance public, change the Visibility indicator.
. You can also edit the instance by clicking the pencil icon, or delete it by clicking the X icon.

