= To Configure Portal Settings

Anypoint Exchange lets you configure whether REST API services are public or private in an Exchange Portal. Typical services that you would set visibility for are proxies or policies associated with your API that you set using API Manager. 

Visibility for each instance is either private or public:

* Public pertains to any user within a business group's Exchange Portal. 
* Private is only those who can see the asset via Sharing the asset or per an Anypoint Platform role.

To configure:

. Click a REST API that was created in your organization and click Portal Settings in the left nav bar.
. Click *+ Add New Instance* to set the visibility for a policy or proxy that you created (or will create) in API Manager.
. If you want the instance public, change the Visibility indicator.
. You can also edit the instance by clicking the pencil icon, or delete it by clicking the X icon.

*Notes:* 

* The Portal Settings icon only appears in private Exchange REST assets. The icon does not appear in MuleSoft REST assets.
* The Mocking Service is listed so that you can know it's available. The Mocking Service provides data that you can use to test API features. The Mocking Service is always public. 

== See Also

* https://docs.mulesoft.com/design-center/v/1.0/design-api-ui-reference#mocking-service-baseuri[Mocking Service]
* https://docs.mulesoft.com/release-notes/api-mocking-service-release-notes[Mocking Service Release Notes]
