= To Set User Access Permissions

Exchange provides multiple ways to set up access management to meet governance requirements and at the same time drive collaboration across teams. Anypoint Platform comes with predefined role groups that can be set in the Access Management > Roles settings to provide users with different access levels.

== Exchange Role Groups 

These role groups pertain to every Business Group level: 

* Exchange Viewer: This role group gives permission to users to view and download assets within a business group. The users with this role group cannot add new assets, edit asset portal content, or share an asset with another user. Assign this role to those who consume your assets in a specific business group. 

* Exchange Contributor: This role group gives permission to users to view, create, and download assets within a business group. Users with this role group can edit asset portal content in an existing asset version. Use this role to invite users to edit and maintain your asset portal descriptions. 

* Exchange Administrator: This role group gives permission to users to view, create, and download assets within a business group. Users with this role group can do everything that the Exchange Contributor and Exchange Viewer roles can do plus  share an asset with another user and delete an asset. Use this role to set up Exchange Administrator for all the assets within a specific business group. 

== Asset Roles

These role groups pertain to every asset level:  

These roles extend access on assets in addition to the role group that a user has at the business group level: 

* Asset Viewer: This role gives permission to users to view and download an asset. Users with this role cannot edit asset portal content or share an asset with another user. Use this role to invite a user outside your business group to view and download an asset. 

* Asset Contributor: This role gives permission to users to view, add a new version, and download an asset. Use this role to invite a user outside your business group to view, download, and add edit portal content for an asset. 

* Asset Administrator: This role gives permission to users to view, create, and download an asset. Users with this role can do everything the Exchange Administrator role can do on a single asset only. This role is assigned by default to an asset creator. Use this role to set extend administrator permissions on an asset to an additional user. Asset Administrators users can delete an asset.


== See Also

* link:/access-management/roles[Access Management Roles].
* https://docs.mulesoft.com/access-management/managing-permissions[Access Management Managing Permissions].
