= To Share an Asset with Another User

Exchange Administrators can share an asset with another user or to share an API asset to the public portal. 

== Share With a User

If the person is not in your organization, 
click Access Management > Users to add them. 

. Click an asset to show its details and click Share.
. In the Share menu, type a few letters of the person's name you want to share this asset with.
Or click a filter to list only users who have Viewer, Contributor, or Admin rights. 
. Click Add.
. Repeat steps 2 and 3 to add additional users to share the asset with.

You can also use the Share menu to change who you are sharing the asset with or to stop sharing with one or more users.

== Share an API Asset to the Public Portal

. Click an asset to show its details and click Share.
. Click Add to The Public Portal.
. (Optional) Click Share Internally if you decide to not put the asset in the public portal and instead return 
to the previous Share menu.
. (Optional) Click API Instances to manage instance visibility before proceeding. After following this link, you are 
returned to the previous Share menu.
. Click the version of the asset you want to publish in the public portal.
. Click Share. If no action occurs when you click Share, refresh your browser and log in again to repeat sharing the asset.

