= To Share an Asset in Exchange

Sharing an asset depends on its type.

== To Upload an API Spec - OAS

. Name your OAS API file as either index.json or index.yaml.
. Log into Exchange and click New.
. Specify the type as API Spec - OAS and locate the API specification file.
. Click Publish.

After you click Publish, the detail view opens. 

On the left is the API Summary that lists the resources in the API specification. You can click each to view methods and descriptions.

You can download the OAS API specification as either an OAS or RAML file.
Downloading as RAML converts the OAS file to the RAML 1.0 language.

You can specify a description and add tags so that users can find this API.

=== To Upload OAS from the CLI

. Construct a command line interface statement in this form:
+
[source,code,linenums]
----
anypoint-cli --username=“XXXXXXX” --password=“YYYYYYYY” \
 --environment=“Development” --organization=“ZZZZZZZ” \
 api-mgr definition upload --swagger --root index.json api-name
----
+
. Specify a description and add tags so that users can find this API.

== To Upload an API Spec - WSDL

. Log into Exchange and click New.
. Specify the type as API Spec - WSDLS and locate the WSDL API 
specification file.
. Click Publish.
. Specify a description and add tags so that users can find this API.

You can also download the WSDL, which is a copy of the source file.

== API HTTP

The API HTTP is a placeholder you can use with API Manager to create an HTTP endpoint. There is no file upload capability.

. Log into Exchange and click New.
. Specify the type as API HTTP.
. Click Publish.
. You can specify a description and add tags so that users can find this API.
. In API Manager, click Manage API and click Import API from Exchange.
. 
