= To Search Using the Graph API
:keywords: query, exchange, exchange2, graph, api, graph api

The Exchange Graph API lets you search Exchange assets for a string value. You can specify what values
to receive in each search. 

Because the Graph API accesses Anypoint Exchange and Anypoint Platform, inquiries should 
have an access token if you want to access assets in private exchange. If you only search for MuleSoft public assets, you don't need an asset token.

== To Obtain an Access Token

You only need an access token if you are searching for assets that are not created by MuleSoft.

Access tokens time out 
in approximately 5 minutes and must be renewed to continue use of the Graph API.

. Log into Anypoint Platform.
. Obtain an access token with a curl command such as the following. You can also use Postman or another application for sending HTTP commands. 
+
[source,json,linenums]
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/login \
  -H 'content-type: application/json' \
  -d '{
  "username": "YOUR_ANYPOINT_PLATFORM_USER_NAME",
  "password": "YOUR_ANYPOINT_PLATFORM_PASSWORD"
}'
----

== To Search Only a Private Exchange

. Get the organization ID for the Private Exchange by clicking an asset in your Private Exchange.
+
An example URL is:
+
[source,xml]
----
https://anypoint.mulesoft.com/exchange/42424242/product-api/1.0.0/
----
+
`42424242` is the organization ID.
+
. Add the organization ID using the organizationIds field in GraphiQL:
+
[source,json,linenums]
----
{
  assets(
    query: {
      searchTerm: "product",
      organizationIds: "42424242"
    },
    latestVersionsOnly: true
  ) {
    assetId,
    description
  }
}
----
+
The output for this example is:
+
[source,json,linenums]
----
{
  "data": {
    "assets": [
      {
        "assetId": "product-datatype",
        "description": "Product Datatype Asset"
      },
      {
        "assetId": "product-api",
        "description": "Product API Asset"
      }
    ]
  }
}
----

== Reference: Query Filter Parameters

You can specify filters to display additional information about each asset. 

The following filters let you refine query output:

[%header%autowidth.spread]
|===
|Parameter |Description
|assetId |Asset ID for each asset.
|createdAt |Date and time an asset was created, for example, 2017-08-11T04:48:20.585Z.
|createdBy { id, userName, firstName, lastName } |Display who created the asset.
|dependencies { groupId, assetId, version, name, type } |Dependency snippet information tp specify an asset 
in Maven, Gradle, SBT, and Ivy.
|files { classifier, packaging, externalLink, md5 } |File information. 
|name |Asset name
|numberOfRates |The number of star ratings for an asset.
|organizationId |Organization ID for an asset.
|rating |Star rating value for an asset.
|runtimeVersion |Mule Runtime version.
|tags { value, key, mutable } |Each tag for an asset, value is the tag type or version, key is the tag name or null,
and mutable indicates whether or not a tag name can be changed. You can ignore the mutable value - its setting 
is arbitrary. Exchange tags cannot be set to immutable.
|type |Lowercase values corresponding to the Exchange All Types menu: connector, template, example, rest-api, soap-api, raml-fragment, and custom.
|version |Version for an asset.
|groupId |Group ID for an asset.
|===

== See Also

* https://www.anypoint.mulesoft.com/exchange/[Anypoint Exchange]
* link:/anypoint-exchange/[Exchange Documentation]
