= Workflow: Anypoint Exchange 2.0
:keywords: workflow, exchange

To access Anypoint Exchange 2.0:

. To view and download assets, log into link:https://www.mulesoft.com/exchange[https://www.mulesoft.com/exchange] or Anypoint Platform > Exchange 2.0. For more information, see 
link:/anypoint-exchange/access[To Access Anypoint Exchange].
. To download a connector, access Exchange from Anypoint Studio. For more information, see 
link:/anypoint-exchange/install-connector[To Install a Connector].
. To upload an asset, first log into Anypoint Platform and click Access Management. 
Click Roles and ensure you have access to Exchange Contributors. For more information, see 
link:/anypoint-exchange/permissions[To Get Permissions].
. Click Exchange 2.0 and click *Upload asset* in Anypoint Platform. For more information, see 
link:/anypoint-exchange/upload-asset[To Upload an Asset].
. Specify a name, a type, and a description. If you don't have a file to upload, set the Asset Type to Custom. *Note:* In Beta for the Custom type, if the Create button is not illuminated, create an empty text file and upload that file.
. Use the editor to describe your asset. For more information, see 
link:/anypoint-exchange/editor[To Use the Editor]
. Publish your asset's description page. For more information, see 
link:/anypoint-exchange/publish-share[To Publish, Share, and Rate an Asset].
. Return to the Assets list to view your asset.