= To Configure OpenID Connect Client Management

MuleSoft verifies support in Anypoint Platform for Okta and OpenAM Dynamic Client Registration.

The following table contains examples of the URLs you need to provide, depending on your provider, during registration.

[%autowidth.spread]
|===
| URL Name | Okta Example URL | OpenAM Example URL 
| Base | https://example.okta.com/oauth2/v1 | https://example.com/openam/oauth2 
| Client Registration | {BASE URL}/clients | {BASE URL}/connect/register 
| Authorize | {BASE URL}/authorize | {BASE URL}/authorize 
| Token | {BASE URL}/token | {BASE URL}/access_token 
| Token Introspection | {BASE URL}/introspect | {BASE URL}/introspect 
|===

. Log into the master Organization in Anypoint Platform as Administrator.
. In Anypoint Platform, click Access Management > External Identity.
. From Client Management, select OpenID Connect Dynamic Client Registration.
+
The External Identity - Client Management OpenID Connect Dynamic Client Registration form appears.
+
. Fill in the following required fields after obtaining values from your identity provider’s configuration:
+
* Client Registration URL
+
The URL to dynamically register client applications with your identity provider.
+
* Authorize Header
+
The authorization header for dynamic client registration request. This is an optional field under the Advanced Settings link. This header is required if the provider restricts registration requests to authorized clients.
+
** Okta: This value is `SSWS ${api_token}`, where `api_token` is an API token created through Okta.
+
** OpenAM: This value is `Bearer ${api_token}`, where `api_token` is an API token created through OpenAM. For more information, see Procedure 14.4  in the "OpenAM 13.5 Developer's Guide."
+
* Authorize URL
+
The URL where the user authenticates and grants OpenID Connect client applications access to the user's identity.
+
* Token URL
+
The URL that provides an access token for an OpenID Connect client application to hit an API hosted in API Gateway.
+
* Token Introspection URL
+
The URL that returns metadata about an OpenID Connect access token, including expiration and token active state.
+
. Save your configuration.

== See Also

* link:https://backstage.forgerock.com/docs/openam/13.5/admin-guide#register-openid-connect-client-dynamic[OpenAM 13.5 Developer's Guide, Procedure 14.4 To Register a Relying Party Dynamically]
* link:https://developer.okta.com/docs/api/resources/oauth-clients.html#register-new-client[Okta OpenID Connect, Dynamic Client Registration]
* link:https://developer.okta.com/docs/api/resources/oidc.html#authentication-request[Okta OpenID Connect, Authentication Request]
* link:https://developer.okta.com/docs/api/resources/oidc.html#token-request[Okta OpenID Connect, Token Request]
* link:https://developer.okta.com/docs/api/resources/oidc.html#introspection-request[Okta Introspection Request]
* link:https://backstage.forgerock.com/docs/openam/13.5/dev-guide#rest-api-oauth2-client-endpoints[OpenAM 13.5 Developer's Guide, Section 2.1.14.1.1 OAuth 2.0 Client and Resource Server Endpoints]