
= Anypoint Access Management
:keywords: anypoint platform, permissions, configuring

The *Anypoint Access Management* section shows you how to link:/access-management/managing-your-account#how-to-create-your-account[create your Anypoint Platform account] or configure federated link:/access-management/external-identity[External Identity].

[TIP]
--
Account creation and user invitation from the platform is not available for Anypoint Platform Private Cloud Edition.
Users running Anypoint Platform Private Cloud Edition need to define a method to link:/access-management/external-identity#managing-users[manage users]. +
--

Additionally you can learn how to configure access and permissions within your link:/access-management/organization[Organization] and, based on your access level, how to manage the link:/access-management/users[Users] and link:/access-management/roles[Roles].

To access the Organization Administration page:

. Log into an Organization Administrator account.
. Select the *Access Management* option from the main page, or select it from the left side bar by clicking the _menu_ button on your top right corner.

[NOTE]
As of November 2014, accounts in both the Anypoint Platform for APIs and CloudHub have been merged. For more information about what this merging of accounts implies and how it's being handled, read Upcoming Changes to Anypoint Platform Accounts.

If you have any questions about your account, please contact your MuleSoft Account Team for assistance.

Anypoint Access Management also provides a REST API for you to programmatically access the resources related to user and client management, organizations and business groups, and roles and permissions.
Check the link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/11270/versions/11646/pages/11244[Access Management API Portal].
