= About Client Management

This topic provides an overview of client management on Anypoint Platform. As an API owner, you can apply an Anypoint Platform OAuth 2.0 policy to an API to authenticate client applications that try to access it. You need an OAuth provider to use the policy. One of the following OAuth providers is recommended: 

* OpenAM versions 11 - 13
* PingFederate
* Dynamic Client Registration compliant Identity Providers

To configure client management on Anypoint Platform for these providers, you need to first have an IdP account. On all versions of Anypoint Platform, except Private Cloud edition, set client management as instructed in this documentation.


== See Also

* link:/access-management/conf-client-mgmt-openam-task[To Configure Client Management By OpenAM]
* link:/access-management/conf-client-mgmt-pf-task[To Configure Client Management By PingFederate]
* link:/access-management/configure-client-management-openid-task[To Configure OpenID Connect Client Management]
