= To Configure SAML in Anypoint Platform

After choosing an identity provider (IdP), familiarize yourself with the IdP documentation. All attribute names you configure must match on both the IdP and Anypoint Platform side. If any information needs to be changed after submitting this form, log into the MuleSoft Support Portal and submit a request.

Before performing this procedure, set up your Anypoint Platform organization as your audience in your IdP configuration.

. In Anypoint Platform, click Access Management > External Identity.
. From Identity Management, select SAML 2.0.
+
The External Identity - Identity Management SAML 2.0 form appears.
+
. Fill in the following required fields:
+
* Sign On URL
+
URL where users must sign in.
+
* Sign Off URL
+
URL to redirect sign out requests, so users both sign out of the Anypoint Platform and have their SAML user's status set to signed out.
+
* Issuer
+
ID of the identity provider instance that sends SAML assertions.
+
* Public Key
+
Public key provided by the identity provider, used to sign the SAML assertion.
+
* Audience
+
An arbitrary string value that identifies your Anypoint Platform organization. The typical value for this string is `<organizationDomain>.anypoint.mulesoft.com`.
+
. Expand Advanced Settings, and optionally fill in the following fields.
+
* Username Attribute
+
Field name in the SAML repository that maps to username. By default, the 'NameID' attribute in the SAML assertion is used.
+
* First Name Attribute
+
Field name in the SAML repository that maps to First Name.
+
* Last Name Attribute
+
Field name in the SAML repository that maps to Last Name.
+
* Email Attribute
+
Field name in the SAML repository that maps to Email.
+
* Group Attribute
+
Field name in the SAML repository that maps to Group.
