= Managing API Clients

Client Management allows any client connecting to your application to identify itself using OAuth 2.0.

[NOTE]
--
Client management is only available for Enterprise Edition users
--

[CAUTION]
Having a single audience (an Anypoint Platform organization) served by multiple issuers (multiple SAML provider instances) is currently not supported.

== openAM

[TIP]
Anypoint Platform currently supports Open AM versions 11 and 12

If you want to use openAM for client management and if you're *not using* Anypoint Platform on premises, you need to request that your account be configured in that way, as you can't set this up manually. +
Work with your MuleSoft account representative to ensure that we are aware of your needs for configuring your organization with openAM.

Complete the link:https://docs.google.com/forms/d/1ZvNUWU3u0lzLk6H5R3lKcEN2Dcyg1zekc1HYtYIcZP0/viewform[OpenAM form] and MuleSoft will get back to you within 48 hours with either the completion of the configuration or follow-up questions to complete the configuration.

[NOTE]
====
If you are using Anypoint Platform on premises, you do not need to provide this information to MuleSoft.
====

== Ping Federate

[TIP]
Anypoint Platform currently supports Ping Federate versions 7 and 8

If you want to use Ping Federate for client management and if you're *not using* Anypoint Platform on premises, you need to request that your account be configured in that way, as you can't set this up manually. +
Work with your MuleSoft account representative to ensure that we are aware of your needs for configuring your organization with PingFederate.

Complete the link:https://docs.google.com/a/mulesoft.com/forms/d/16ZQjXcLmuXO8140svkjUxywzkZjv01GTgbf_3kfEebQ/viewform[Ping Federate Form]. After you complete this form, MuleSoft gets back to you within 48 hours with either the completion of the configuration or follow-up questions to complete the configuration.

[NOTE]
====
If you are using Anypoint Platform on premises, you do not need to provide this information to MuleSoft.
====

== External Mule OAuth 2.0 Provider

By deploying your application and exposing its API through an link:/api-manager/tutorial-create-an-api-portal[API Portal] you can apply an link:/api-manager/external-oauth-2.0-token-validation-policy[OAuth 2.0 Access Token Enforcement Using External Provider policy] to manage your clients.

You can generate link:/api-manager/browsing-and-accessing-apis#accessing-your-application-client-id-and-client-secret[API credentials] and grant them to your clients through an *external Mule OAuth service provider*.  +
Learn how to create your own Mule OAuth provider following link:/api-manager/building-an-external-oauth-2.0-provider-application[this tutorial].
