= To Obtain the Bearer Token Using SAML

If you are using SAML as your identity provider, federated users can access platform APIs using a bearer token.
Any user that has the bearer token can access the API. The validity of the bearer token is determined by the value defined for the Default Session Timeout property.

. Obtain a SAML response for your identity provider. The specific steps you must perfom depend on which identity provider you are using.

. Obtain the bearer token by running the following `curl` command:
+
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/login/receive-id \
  -H 'Content-Type: application/json' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -d '{
    "SAMLResponse": "<SAML_RESPONSE>"
}'
----
+
Replace `<SAML_RESPONSE>` in this example with the SAML response you obtained in the previous step.

Using the bearer token a federated user can access a platform API by supplying the `-bearer` option to the `anypoint-cli` command. See link:/runtime-manager/anypoint-platform-cli#logging-in[Anypoint CLI] for more information.

== See Also

* link:/runtime-manager/anypoint-platform-cli#logging-in[Anypoint CLI]
* link:/access-management/troubleshoot-saml-assertions-task[To Troubleshoot SAML Assertions]