= To Obtain the Bearer Token Using SAML

Federated users can access your API by obtaining a bearer token for the API. Any user that has the bearer token can access the API.

. Obtain a SAML response for your identity provider. The specific steps you must perfom depend on which identity provider you are using.

. Obtain the bearer token by running the following `curl` command:
+
----
curl -X POST \
  https://anypoint.mulesoft.com/accounts/login/receive-id \
  -H 'Content-Type: application/json' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -d '{
    "SAMLResponse": "<SAML_RESPONSE>"
}'
----
+
Replace `<SAML_RESPONSE>` in this example with the SAML response you obtained in the previous step.

Using the bearer token a federated user can access a platform API by supplying the `-bearer` option to the `anypoint-cli` command. See link:/runtime-manager/anypoint-platform-cli#logging-in[Anypoint CLI] for more information.

The validity of the bearer token is determined by the value defined for the Default Session Timeout property. This

== See Also

* /access-management/troubleshoot-saml-assertions-task