= To Perform Single Log Out

As Administrator you can configure single log out as described in this procedure. Using single log out, a user or user agent can log out of an authenticated environment and ensure that both service providers and identity servers process the log out correctly.

. In PingFederate for example, click the SP Configuration for the Anypoint Platform.
. In Browser SSO > Configure Browser SSO > SAML Profiles, ensure that these fields are set:
+
* IdP-Initiated SSO
* IdP-Initiated SLO
* SP-Initiated SLO
+
. In Protocol Settings > Configure Protocol Settings, configure a SLO Service Url with the following values:
+
* Binding: POST
* Endpoint URL: Set PARTNER_SP_ID to the correct value: `https://anypoint.mulesoft.com/accounts/logout/receive-id`
+
You can control where the user is redirected after signing out. Redirecting the user to a different page is often prefered. You can configure such a redirect in your PingFederate's service provider configuration. You can add a `redirect_uri` query parameter to the SLO Service URL and Anypoint Platform routes the user there rather than to the Anypoint Platform sign-in page.
+
For example, to route the users back to your signin page, use the following URL:
+
[source]
----
https://anypoint.mulesoft.com/accounts/logout/receive-id?redirect_uri=https%3A%2F%2Fanypoint.mulesoft.com%2Faccounts%2Flogin%2Fyour-domain
----
+
To route the users back to your portal page, use the following URL:
+
[source]
----
https://anypoint.mulesoft.com/accounts/logout/receive-id?redirect_uri=https%3A%2F%2Fanypoint.mulesoft.com%2Fapiplatform%2Fyour-domain%2F%23%2Fportals
----
+
. In Allowable SAML Bindings, click Redirect.
. In Encryption Policy, make certain that nothing is encrypted.
. Save and exit Protocol Settings and Browser SSO.
. When viewing the SP Configuration for Anypoint Platform, go to Credentials > Configure Credentials.
. Set Signature Verification Settings > Manage Signature Verification Settings > Trust Model to Unanchored, and import the certificate from the following location:
+
`+https://docs.mulesoft.com/access-management/_attachments/anypoint-platform-slo.pem+`
+
. Make this certificate the active certificate.