= About SSO Prerequisites

If you configure an IdP to handle user information assertion, log into Anypoint Platform at the following location:

`+https://anypoint.mulesoft.com/accounts/login/{yourorgDomain}+`

Your IdP needs to be configured to send Username and Email in your assertion, and your Anypoint Platform needs to be configured to map them to the expected attribute name. Otherwise, the login fails with a 403 unauthorized error message.

User accounts that you create before configuring your federated organization remain. However, the users can login only through the Anypoint Plaform Sign In page and not through the IdP redirected custom login page. With external identity enabled, the invite button is disabled and no new non-federated users can be added. Existing non-federated users can continue to work normally, with some exceptions:

* If a user session times out, the user is redirected to the federated identity login page instead of the generic one.
* Links and bookmarks that identify the organization redirect the user to the federated login page, which fails for non-federated users.

== Limitations

Federated users cannot use platform APIs.


