= To View a SAML Response in Your Browser

This topic describes how to obtain a SAML response if you are using an identity provider configured to use SAML 2.0. The SAML response is can be helpful

. Open a new tab in your browser and use Chrome Developer Tools, Firebug for Firefox, or a SAML tracer to be prepared to capture the SAML response. Ensure that you are preserving logs.

. Select Access Management -> Organizations -> <Master org> to determine your organizations's domain name.

. Go to the following URL, replacing `domain_name` with your organization's domain name:
+
----
anypoint.mulesoft.com/accounts/login/<domain_name>
----
+
This URL redirects to your identity provider's  Sigle Sign On page. 

. Enter your account credentials and authenticate yourself. 

. After successfully authenticating with the identity provider, capture the SAML assertion by inspecting the `HTTP POST` sent by the browser to the following SAML assertion URL:
+
`+https://anypoint.mulesoft.com/accounts/login/receive-id+`
+

. Click on the specific row that contains the URL mentioned above. 

. In the Form data window on the right select the Params tab. 

. Record the SAML response element.

After recording the SAML response element, you can use it to obtain a bearer token to access platform APIs. It is also useful to provide the SAML response for troubleshooting when contacting MuleSoft support.

. Log in to the MuleSoft Support Portal at the following URL:
+
`+https://www.mulesoft.com/support-login+`

. Provide a screen shot of your SAML configuration in Anypoint Platform.
. Include an XML SAML assertion.

