= To Troubleshoot SAML Assertions

This procedure describes how to get MuleSoft to assist you in troubleshooting your SAML assertions. Some providers support generating sample assertions. If supported, you can capture a SAML assertion by inspecting the `HTTP POST` sent by the browser to the SAML Assertion URL (`https://anypoint.mulesoft.com/accounts/login/receive-id`) after successfully authenticating to the IdP. 
Use Chrome Developer Tools, Firebug for Firefox or SAML tracer to inspect the HTTP request, which is base64-encoded.

Anypoint Platform does not initiate the SAML assertion for the single sign on. The _Sign On URL_ that you configure is the initiated SSO of your IdP.

Exporting assertion metadata to later import it in your selected IdP is currently not supported.

. Log in to the MuleSoft Support Portal at the following URL:
+
`+https://www.mulesoft.com/support-login[MuleSoft Support Portal]+`
+
. Provide a screenshot of your SAML configuration in Anypoint Platform.
. Include an XML SAML assertion.

