= User Management SSO Reference

If you configure an IdP to handle user information assertion, the login URL for accessing Anypoint Platform will then be `https://anypoint.mulesoft.com/accounts/login/{yourorgDomain}`. 

////
looks like the new form takes care of this -- khahn May 2, 2017
* Your IdP needs to be configured to send both Username and Email in your assertion, and your Anypoint Platform needs to be configured to map them to the expected attribute name. Otherwise the login fails with a 403 unauthorized error message.

////

User accounts that you create before configuring your federated organization remain. However, the users can login only through the Anypoint Plaform Sign In page and not through the IdP redirected custom login page. With External Identity enabled, the invite button is disabled and no new non-federated users can be added. Existing non-federated users continue to work as normal, with some exceptions:
+
* If a user session times out, the user is redirected to the Federated Identity login page instead of the generic one.
* Links and bookmarks that identify the organization redirect the user to the Federated login, which fails for non-federated users.

Federated users cannot use platform APIs.

The `email` `firstname` and `lastname` fields of the SAML configuration are updated automatically every time a user signs into the IdP using the value in the `username` field.
