= About Using External Identity

After configuring your organization’s external identity provider, you can test the integration by visiting your organization’s login URL, for example:

`+https:/anypoint.mulesoft.com/accounts/login/{organization-domain-name}+` 

Find your organization’s domain name by logging into Anypoint Platform administrator account, clicking Access Management > Organization, and selecting your organization name. Look for the value in Domain Name.

The next time you log in, you are redirected to your identity provider. After authenticating, you are redirected back to Anypoint Platform as an authenticated user.

== Logging In for the First Time

When you log into the configured IdP for the first time, an Anypoint user is created using the your IdP information. Your user profile includes a username, your name, and email address.

== Updating Profile Information

Update your user profile information in your configured IdP. Log into Anypoint Platform through the IdP. Your user profile information is updated within Anypoint Platform using the updates from the IdP.

Typically, the OpenID Connect `userinfo` endpoint provides a `preferred_username` claim that contains the authenticated user’s user name. However, some IdPs such as OpenAM and PingFederate do not support the `preferred_username` claim. Therefore, when creating an Anypoint user, Anypoint Platform uses the email and subclaims as fallback values for the user name if the `preferred_username` claim isn't present.

== See Also

* 


