= To Verify SAML Information

The SAML assertion is an XML file that is issued by the external identity provider. This assertion must be signed for verification of its integrity, but unencrypted because the assertion itself is POSTed through HTTPS. During verification of SAML information, if you determine that information needs to be changed, log into the MuleSoft Support Portal and submit a request. All attribute names must match on both the IdP and Anypoint Platform's side.

. In Anypoint Platform, click Access Management > External Identity.
. From Identity Management, select SAML 2.0.
+
Your SAML 2.0 configuration appears.
+
. Verify that the group_attribute value is set to the correct attribute name.
+
For example, if the group_attriburte is "memberOf", the sample SAML assertion appears as follows:
+
[source,xml,linenums]
----
<saml:Attribute NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" Name="memberOf">
  <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">cn=jira-users,ou=groups,dc=muleforge,dc=org</saml:AttributeValue>
  <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">cn=confluence-users,ou=groups,dc=muleforge,dc=org</saml:AttributeValue>
  <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">cn=mule-community,ou=groups,dc=muleforge,dc=org</saml:AttributeValue>
  <saml:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">cn=SR-User,ou=Groups,dc=muleforge,dc=org</saml:AttributeValue>
</saml:Attribute>
----
+
All other information is provided when registering an organization to use Anypoint Platform. 

== See Also

link:https://www.mulesoft.com/support-login[MuleSoft Support Portal]