= RAML API Design

_Requires November 2017 Release_

In Design Center, you can create and publish reusable projects of type API Specification or API Fragment. RESTful API Modeling Language (RAML) defines documents of these types:

* API Specification
+
A RAML API definition document that begins with the text `#%RAML` followed by a single space and the version number `1.0`. 
+
* API Fragment
+ 
A document, such as a data type, that begins with the RAML version and includes a fragment identifier.

You can publish an API Fragment in Exchange and add it to your specification as a dependency. You can change the fragment outside the specification, update the fragment version in the specification, and reuse the fragment in other specifications.

To create and publish an API Specification or fragment, you need to have the permissions covered in "User Access to Design Center" below.

== OAS Support

Design Center supports the RAML and the Open API Specification (OAS) 2.0, also known as Swagger. You can import an OAS specification to convert the OAS code to RAML. You can modify the resulting RAML code in the RAML editor.

== See Also

* link:/design-center/v/1.0/user-access-to-design-center[User Access to Design Center]
* link:/design-center/v/1.0/designing-api-reference[Reference: OAS/RAML Importing and Exporting]

