= About API Fragments

_Requires November 2017 Release_

An API fragment is a RAML document that has a version and an identifier, but is not in itself a complete RAML specification. An API fragment is one of the following types defined by RAML.org:

* Trait
* Resource Type
* Library
* Type
* User Documentation
* Example
* Annotation Type
* Security Scheme

You can publish an API fragment to Exchange, include fragments as dependencies in a project, and revise a fragment. After revising a fragment, update API specifications that use the fragment to include the new version.

To make any an API specification or fragment available for use by others, you need to publish the design to Exchange.

== See Also

* link:/design-center/v/1.0/create-reuse-part-task[To Create and Publish an API Fragment]
* link:/design-center/v/1.0/add-dependencies-task[To Add a Fragment to an API]
* link:/design-center/v/1.0/design-branch-filelock-concept[About Sharing Work]
* link:/design-center/v/1.0/publish-project-exchange-task[To Publish an API Design Project]
