= Design and Develop with Anypoint Platform
:keywords: design, develop, anypoint platform, studio, mule, devkit, studio, connectors, auth, exchange, api design, apikit, raml, application network

The *Anypoint Platform* comprises a complete application and API development suite that you can use to model, build, and transform existing applications and APIs or create new ones. With our platform, you can transform practically any digital resource for your needs and organizational goals.

Think of the Anypoint Platform as a bundle of products you can use across your organization as a vehicle of continuous improvement for your applications and API ecosystem. Get started and link:https://anypoint.mulesoft.com/login/#/signup?apintent=exchange[Create an Anypoint Platform account].

Unlock the potential of your application architecture in the cloud or on-premises easily. Get started with one of our new application design and development link:/quickstarts/[Quickstarts] or start creating and managing APIs right away with *API Designer*.

[NOTE]
With our programming language-agnostic platform, you can use the development tools to iteratively develop in step with changing web service needs.

== Mule Application Development in Anypoint Studio

link:/anypoint-studio/v/6/[Anypoint Studio] is an IDE for integration applications that run on Mule runtime. This IDE supports applications composed of reusable, modular building blocks, and makes debugging, testing, and deployment easy. Mule applications comprise one or more user-defined *flows* that define how data is transmitted across the application, to internal or external services. The building blocks of these flows are referred to as *elements*; they each provide configurable fields that define how information is received, transformed and returned, like most software program functions would. However, you don’t have to code these elements yourself - they are easily accessible from a palette, and you can configure them from the UI, which is chock full of resources to help you route and process data.

[NOTE]
Start setting up your link:/anypoint-studio/v/6/setting-up-your-development-environment[Development Environment].

Develop your Mule applications using either the:

* *Graphical user interface* for drag-and-drop of flow elements and easy configuration in properties windows, or
* An *XML editor* where these same elements can be configured

Each building block in an application’s flow(s) represents a modular part of a process along which Mule messages are transmitted. Thanks to link:/anypoint-studio/v/6/datasense[DataSense], you can view the metadata that describes the data in the Mule messages transitioning any given point in a flow. This data may be referenced using the link:/mule-user-guide/v/3.8/mule-expression-language-mel[Mule Expression Language (MEL)], which is a Mule application-specific syntax. link:/mule-user-guide/v/3.8/dataweave[DataWeave] is a powerful tool for data transformation, which can be used through its intuitive drag and drop UI or by describing the desired output in its transformation language by the same name.

It is easy to design and test applications using Studio. Depending on the use case, you may not need to write any code at all.

Mule supports very many internet communications protocols out of the box, such as FTP and SMTP. Mule applications support use and re-use of elements called link:/mule-user-guide/v/3.8/anypoint-connectors[Anypoint Connectors] that facilitate connections, normally to web services which handle essential business services: databases, SaaS providers, payment systems, etc. See the whole connector offering here on link:/mule-fundamentals/v/3.8/anypoint-exchange[Anypoint Exchange].

[TIP]
If you do not see the Anypoint Connector you need in Anypoint Exchange, consider creating your own connector using the link:/anypoint-connector-devkit/v/3.8/[Anypoint Connector DevKit]. link:/anypoint-connector-devkit/v/3.8/setting-up-your-dev-environment[Set up your development environment] and follow the link:/anypoint-connector-devkit/v/3.8/devkit-tutorial[DevKit Tutorial].

You can also use link:/anypoint-mq/[Anypoint MQ] to coordinate messaging between applications, Object Store to share content between applications, and more.

After your Mule application has been designed, you can seamlessly add _unit testing_ to your continuous development environment using link:/munit/v/1.2.0/[MUnit], a Mule application testing framework embedded within Studio.

Make sure that your integrations and APIs behave the way you intend by designing and running _test suites_, a collection of tests using resources such as _assertions_, _verifications_, _mocks_, and _spies_. +
MUnit also allows you to run integration tests in a local environment allowing you to start a local FTP/SFTP, DB, or mail server.

Get quality metrics for your development by running link:/munit/v/1.2.0/munit-maven-support#coverage[coverage repots].

You can run your application and test suite from within the IDE using the embedded *Mule runtime*, or link:/anypoint-fundamentals/operate-and-manage#deploy[deploy your application] to production (or a development environment) in the cloud on *CloudHub*, also without having to leave the IDE.

== API Development

To elaborate on what design and development means for business transformation, consider the data you want to provide, govern, transform, and expose at various levels of your organization, both internally and for customers.

After planning your development strategy, you are ready to begin designing APIs to support each piece of the connectivity puzzle for your organization. We recommend using link:http://raml.org/[RAML], the API-modeling language, to describe your APIs. RAML allows you to define the methods and resources of a REST-ful API in a syntax similar to that of *YAML*. The Anypoint Platform even uses RAML to auto-generate interactive API documentation for each API via its own API Portal, and Anypoint Studio uses RAML scaffold Mule flows.

Let’s take a look at this diagram, a conceptual framework you can use to orient yourself in intelligent API design.

[diagram]

link:/api-manager/designing-your-api#accessing-api-designer[API Designer], accessible from the browser, or link:/apikit/[APIkit], commonly leveraged from within Studio. You can manage APIs defined in any format, by proxy for example. We promote API development following an API model where APIs are segmented into three logical layers of your organization:

* *System APIs*
* *Process APIs*
* *Experience APIs*

== Anypoint Platform for Application Networks

Developing an application network is an iterative process that involves developers and resources working together and in parallel to design an architecture supporting multiple applications and APIs that can be recomposed as business demands change. Taking inventory of data, applications, SaaS and APIs is a necessary first step.

This involves knowing the details that define where your service model is today, and where it needs to go in order to meet the demands of your organization and customers now, and the group of users you want to connect and engage with tomorrow.

Context is essential to identifying functions and areas of ownership of APIs, which is why these are considerations that are always present as you develop. Needs change and so must your applications, which is why we give our developers a head start with templates, examples, and best practices for success in the integrated enterprise.


== Resources

* link:/mule-fundamentals/v/3.8/basic-studio-tutorial[Basic Studio Tutorial]
* link:https:/api-manager/designing-your-api[Designing an API]
* link:/anypoint-connector-devkit/v/3.8/index[Anypoint Connector DevKit]
* link:https://anypoint.mulesoft.com/login/#/signin?apintent=exchange[Sign into Anypoint Platform]
