= Design and Develop with Anypoint Platform
:keywords: design, develop, anypoint platform, studio, mule, devkit, studio, connectors, auth, exchange, api design, apikit, raml, application network

The *Anypoint Platform* comprises a complete application and API development suite that you can use to model, build and transform existing applications or create new ones. With our platform you can transform practically any digital resource for your needs and organizational aspirations.

Think of the Anypoint Platform as a bundle of products you can use across your organization as a vehicle of continuous improvement for your applications and API ecosystem. Get started by *Creating an Anypoint Platform account*.

Unlock the potential of your application architecture in the cloud or on-premises easily. Get started with one of our new application design and development *Quickstarts* or start creating and managing APIs right away with *API Notebook*.


== Orchestrate Data Delivery


With our programming language-agnostic platform, your technical staff can take ownership of their part of your organization’s journey toward a seamlessly connected business that adapts to its changing service landscape and is in touch with its customers, without having to compromise data security.

== Mule Application Development in Studio

*Anypoint Studio* is a design and development platform for designing smart applications. This IDE supports applications composed of reusable modular building blocks, and makes debugging, testing and deployment easy. Mule applications compromise one or more user-defined *flows* that define how data is transmitted across one or more flows, or even other applications. The building blocks of these flows are referred to as elements; these define how information is received, transformed and returned, like any program function does. However, you don’t have to code these elements yourself - they are easily accessible from a palette that is chock full of resources to help you route and process data.

Anypoint Studio allows you to develop your Mule applications using either a

* graphical user interface for drag-and-drop of flow elements and easy configuration in properties windows, or
* an XML editor where these same elements can be configured

Each building block in an application’s flow(s) represents a modular part of a process along which Mule messages are transmitted. Thanks to *DataSense*, you can view the metadata that describes the data in the Mule messages transitioning any given point in a flow. This data may be referenced using the *Mule Expression Language (MEL)*, which is a Mule application-specific syntax. *DataWeave* is a powerful tool for data transformation, which can be used through its intuitive drag and drop UI or by describing the desired output in its transformation language by the same name. Test out DataWeave *here*.

It is easy to design and test applications using Studio. Depending on the use case, you may not need to write any code at all.

Mule supports very many internet communications protocols out of the box, such as FTP and SMTP. Mule applications support use and re-use of elements called *Anypoint Connectors* that facilitate hooking applications into external web services. See the whole connector offering here on *Anypoint Exchange*.

[TIP]
If you do not see the Anypoint Connector you need in our Anypoint Exchange, consider creating your own connector tailored to your needs using the *Anypoint Connector DevKit*. Go to the *DevKit Tutorial*.

You can also use *Anypoint MQ* to coordinate messaging between applications, Object Store to share content between applications, and more.

After your Mule application is designed, you can seamlessly add _unit testing_ to your continuous development environment using link:/munit/v/1.2.0/[MUnit], a Mule application testing framework embedded within Studio.

Make sure that your integrations and APIs behave the way you intend by designing and running _test suites_, a collection of tests using resources such as _assertions_, _verifications_, _mocks_ and _spies_. +
MUnit also allows you to run integration tests in a local environment allowing you to start a local FTP/SFTP, DB or mail server.

Get quality metrics for your development by running link:/munit/v/1.2.0/munit-maven-support#coverage[coverage repots].

You can run your application and test suite from within the IDE using the embedded *Mule runtime*, or link:/anypoint-fundamentals/operate-and-manage#deploy[deploy your application] to production (or a development environment) in the cloud on *CloudHub*, also without having to leave the IDE.

== API Development Strategy

To elaborate on what design and development means for business transformation, consider the data you want to provide, govern, transform, and expose at various levels of your organization, both internally and customer-facing.

After planning your development strategy, you are ready to begin designing APIs to support each piece of the connectivity puzzle for your organization. We recommend using *RAML*, the API-modeling language, to describe your APIs. RAML allows you to define the methods and resources of a REST-ful API in a syntax similar to that of *YAML*. The Anypoint Platform even uses RAML to auto-generate interactive API documentation for users' APIs on *API Portal*, and Anypoint Studio uses it scaffold Mule flows.

Let’s take a look at this diagram, a conceptual framework you can use to orient yourself in intelligent API design.

[diagram]

*API Designer*, accessible from the browser, or *APIkit*, available within Studio. Via the use of proxies, the Anypoint Platform can manage APIs that are defined in any format. We promote API development following a model where APIs are segmented into three logical layers on your organization:

* System
* Process
* Experience

== Anypoint Platform for Application Networks

Developing an application network with the Anypoint Platform is no small task. In fact, it is a gradual process that involves many people and resources - but the process does not have to be painful. Many teams may be working in parallel to create an API architecture that can be updated as organizational demands change, this is a crucial undertaking for business survival. But before you begin, you have to know the context in which your data and applications exist. This involves knowing the details that define where your service model is today, and where it needs to go in order to meet the demands of your organization and customers now, and the group of users you want to connect and engage with tomorrow.

Context is essential to identifying functions and areas of ownership of APIs, which is why these are considerations that are always present as you develop. Needs change and so must your applications, which is why we give our developers a head start with templates, examples and best practices for success in the integrated enterprise.


*NEXT:*
Look beyond application design to see how to manage your APIs to support their proper access and use.
