= Engage User and Developer Communities

After your application or API has been designed, deployed, and managed to guarantee best performance, it is time for you to _engage_ developers and users by making your content available to them, to amplify the utility of your application or API.

== Anypoint Exchange

link:/mule-fundamentals/v/3.8/anypoint-exchange[Anypoint Exchange] lets you create organization-specific repositories called _private exchanges_ where you can share templates, connectors, examples, RAMLs, and WSDLs throughout your organization. You can also find  artifacts published by MuleSoft on the public link:https://www.mulesoft.com/exchange#!/[Exchange] site. Whether private or public, Exchange lets you create pages for each item with explanation text, videos of how to use the artifact, and links to documentation.

== Portals

After deploying an API, use API Portals to publicize the API and attract a user community. Create a multi-page portal for users to consume your public APIs and find assets, such as examples and policies, and set up users to access your private APIs. From the portal editing environment, include an API Notebook to convey technical workflows, for example, how to make an authenticated call to your RAML-based API. Include images, attachments, and an API Console for simulating calls to your RAML-based API. Engage the community through interaction with the API to solicit feedback and contributions. 

== API Notebook

The best way to present your API to users is through the link:/anypoint-platform-for-apis/walkthrough-notebook[API Notebook], a web-based, persistent, JavaScript-supported workspace that can generate an API client from a RAML API definition.

This allows users to explore and test examples for the resources in your API, executing authenticated live calls to an API on a real server or on an empty API interface.

You can make the API Notebook available to everyone and even save it as a "gist" in your GitHub account, making it versionable, forkable, shareable, and embeddable anywhere as markdown text.
