= Backup and Disaster Recovery
:keywords:on-prem, anypoint platform on-prem, anypoint platform, on prem, on premise, on premises, backup, disaster recovery

== Performing Backups

Scheduling hourly backups to external storage every hour is recommended to preserve your data. Make sure you copy the archive to an external reliable storage outside of the Anypoint cluster, using appropriate storage system used in your organization.

[IMPORTANT]
====
These instructions must be performed on a _master node_. If you originally installed the platform with a 6 server "flavour", then only three of the original servers should be _master nodes_, if you instead used a 1 or 3 server "flavour", then all servers should be _master nodes_.

To know which of your nodes are registered as master, run the following command on any node of the cluster:

`kubectl get nodes -o yaml|grep master -A 5|grep hostname`
====

You can launch the creation of a backup by running the commands below from any one of the servers registered as *master nodes* in the cluster:

. Enter the gravity utility through this command:
+
----
sudo gravity enter
----

. Create the backup:
+
----
gravity system backup gravitational.io/anypoint:0.0.0+latest /ext/share/backup.tar.gz
----

This will create an archive of the system state, stored in `/var/lib/gravity/planet/share/backup.tar.gz`.

[NOTE]
====
After running the backup command, you may see the following error message:

`Error from server: container "anypoint-backup" in pod "anypoint-backup-<pod-id>" is waiting to start: PodInitializing`

This simply means that the Kubernetes pod that runs the backup job is not up and running yet. It should start in a couple seconds
====

== Restoring the System

To restore a system from your backup, use the existing cluster or create a new fresh cluster with the same amount of servers as the restored version. In either case, you must do the following:

. Enter one of the nodes in your cluster, having root access.
. Place the ‘tar.gz` archive file in the location `/var/lib/gravity/planet/share`. You can transfer this file securely via the following command:

+
----
scp /backup-path/to-restore.tar.gz your_username@remotehost.edu:/var/lib/gravity/planet/share
----

. Enter the gravity utility through this command:
+
----
sudo gravity enter
----


. Run the command below:
+
----
gravity system restore gravitational.io/anypoint:0.0.0+latest /ext/share/to-restore.tar.gz
----
+
This command will restore your entire cluster from one of your backups.

. Then run this other command:
+
----
ACCESS_KEY=$(kubectl get secret pithos-keys -o yaml | grep master.key | awk '{print $2}' | base64 -d) && SECRET_KEY=$(kubectl get secret pithos-keys -o yaml | grep master.secret | awk '{print $2}' | base64 -d) && \
kubectl get secret hybrid-rest-cloudhub -o yaml | grep override.properties | awk '{print $2}' | base64 -d | sed "s/\(hybrid\.storage\.s3\.accessKey=\).*\$/\1${ACCESS_KEY}/" | sed "s/\(hybrid\.storage\.s3\.secretKey=\).*\$/\1${SECRET_KEY}/" | base64 | tr -d '\n' | { read a; kubectl patch secret hybrid-rest-cloudhub -p '{"data":{"override.properties":"'$a'"}}'; }
----
+
This command manually updates a secret on Kubernetes. This step won't be necessary in further releases.

. Restart all of the pods in your cluster to pull up the new secrets. You can do that through the following command:
+
----
kubectl delete pods --all
----
+
Kubernetes will take care of reinstancing every pod automatically, this will take a couple of minutes.



== Applying Updates

Application updates will be provided to you as a `.tar.gz` archive file. To apply them, do the following:

. Copy the file to the server with scp (i.e. scp anypoint-update.tar.gz username@server:/home/username)
. SSH to the server
. Copy the update file to `/var/lib/gravity/planet/share`
. Enter the gravity utility through this command:
+
----
sudo gravity enter
----

. Run the following command:
+
----
gravity app import --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure /ext/share/anypoint-update.tar.gz
----

. Then run:
+
----
gravity app export --ops-url=https://gravity-site.kube-system.svc.cluster.local:3009 --insecure gravitational.io/anypoint:<version>
----

. Finally, in the Site management UI in your browser. Click the ‘Update’ button on the new version now available on the ‘Updates’ screen.
