= Anypoint Platform On-Premises Edition

This section shows you how to install and use the *Anypoint Platform On-Premises Edition*. The Anypoint Platform On-Premises Edition offers all of the features that are available in the online version of the link:https://anypoint.mulesoft.com[Anypoint Platform] as a service that you can run on your local servers, guarded by any security policies you may require.

When you choose to run Anypoint Platform on-premises, MuleSoft systems do not interact with your data at all. You configure and run the software and handle all storing, processing and transmitting of data directly, without interference from MuleSoft.

The Anypoint Platform On-Premises Edition includes the following functionalities:

* link:/runtime-manager/index[Runtime Manager], which lets you keep track of your deployed Mule applications
* link:/api-manager/index[API Manager], which lets you keep track of your registered APIs
* link:/getting-started/anypoint-exchange[Anypoint Exchange], where your organization can share various kinds assets that can be reused throughout your integrations

The Anypoint Platform on-Premises Edition 1.5.0 is based on Kubernetes, and provides built in high availability.



* link:/anypoint-platform-on-premises/v/1.5/installing-anypoint-on-premises[Installing Anypoint On-Premises]
* link:https://docs.mulesoft.com/api-manager/[API Manager]
* link:https://docs.mulesoft.com/runtime-manager/[Anypoint Runtime Manager]
* link:https://docs.mulesoft.com/access-management/[Access Management]
