= Anypoint MQ FAQ
:keywords: mq, faq, questions

This document lists frequently asked questions about Anypoint MQ.

== Questions and Answers

=== Why is MQ not shown in Anypoint Platform?

Anypoint MQ requires a separate Enterprise subscription and is not included in the Anypoint Platform trial version. Contact your mailto:support@mulesoft.com[MuleSoft representative] for more information. If you don't have an Enterprise subscription,
you can use link:/mule-user-guide/v/3.8/amqp-connector[Active MQ]
or link:https://www.rabbitmq.com/[Rabbit MQ].

=== How do I create and send messages into Anypoint MQ from Mule?

After you obtain an Enterprise subscription and contacted your MuleSoft representative to activate Anypoint MQ, you can use Anypoint Platform to create a queue or exchange, and send messages to it. For more information, see the link:/anypoint-mq/mq-tutorial[MQ Tutorial].

=== Can I use Anypoint MQ on premise?

On premise use of Anypoint MQ is not currently supported. Use link:/mule-user-guide/v/3.8/amqp-connector[Active MQ] instead.

=== Can one listen to a queue and be notified when messages are delivered?

Anypoint MQ provides long polling. You can do a REST request and ask the server
to keep the socket open for up to 20 seconds to fulfill your request if there are not enough messages.

=== Can Anypoint MQ connector support be added to Mule shared resources?

At the moment, the only officially supported connectors and transports for shared resources are: HTTP/HTTPS, VM,  JMS, JMS Caching Connection Factory, Database, WMQ, JBoss Transaction Manager, and Bitronix Transaction Manager.

=== How do I get the Anypoint MQ connector to work with a retry strategy?

The Anypoint MQ connector does not exactly use a connection-based protocol,
but uses REST behind the scenes, and therefore,
you cannot use reconnection strategies with this connector.

On the inbound side, you can easily mimic a retry strategy using a max redelivery attribute set to your maximum number of retries and an exception strategy to move to a DLQ when the limit is hit.

On the outbound side, stick to the same triggering mechanism.
Otherwise you can use the *until-successful* element with this connector.

You should also configure the HTTP connector so that Global Element Properties > *Set Max Redelivery* is set to the `-1` value.

== See Also

* link:/anypoint-mq/mq-tutorial[Anypoint MQ Tutorial]
* link:/anypoint-mq/mq-access-management[User and Role Access]
* link:/anypoint-mq/mq-queues-and-exchanges[Queues and Exchanges]
* link:/anypoint-mq/mq-usage[Usage Information]
* link:/anypoint-mq/mq-ack-mode[Acknowledgement Mode]
* link:/anypoint-mq/mq-studio[Anypoint MQ Connector]
* link:/anypoint-mq/mq-apis[MQ REST APIs]
* link:/anypoint-mq/mq-understanding[Concepts]
* link:/release-notes/anypoint-mq-release-notes[Release Notes]
