= Anypoint Object Store v2 REST APIs
:keywords: osv2, os2, object store, store, rest, apis

Anypoint Object Store v2 (OSv2) provides REST APIs that let you get and store store and key/list values.

NOTE: MuleSoft currently provides customers with client ID and client secret values. Before using the Object Store REST APIs, obtain this information from your MuleSoft representative.

The object store is deployed in an environment in an organization. Therefore, after getting
the client ID and secret, you can use a program such as Postman to send and get responses
from the object store REST API.

== Object Store 2 Operations

Object Store 2 provides these operations:

[%header,cols="30a,70a"]
|===
|Task |Operations

|Define (Post) |

* Object Store:
** TTL for the object store (when you create the object store) - By default TTL is 1,209,600 seconds (14 days). TTL values are in seconds. MAX TTL of 2,592,000 Seconds (30 days).
** Persistence property
** Usage limits for each application or environment, includes options for limiting based on keys or size and how to enforce them.
* Key and list (item) value

|Get |

* Get keys
* Get item
* Get items
* Get all items
* Get regions for an organization

|Put |

* Put item as String
* Put item as Number
* Put item as confirmable String
* Put store

|Delete |

* Remove object store
* Delete key
* Delete item
|===

== Object Store 2 Workflow

Using Object Store 2 works as follows:

. Log into link:https://anypoint.mulesoft.com/#/signin[Anypoint Platform].
. Click *Runtime Manager*.
. If you have an existing application, click it and *Manage Application*.
+
If this is your first use, create an application in Anypoint Studio and export it as a Mule project zip file. In Runtime Manager, click *Deploy application* and choose the exported project.
+
. After you click the application and *Manage Application*, click *Object Store*.

== Mapping Object Store Connector Operations to OSv2

The link:[Object Store Connector] provides operations that are similar to the
