= Using Mule with Spring
:keywords: anypoint studio, studio, mule esb, spring

Mule leverages the Spring framework for developing Java applications. Mule ESB 3.7 supports the latest version of the framework, Spring 4.1.6, making use of the Eclipse-based development environment.

== About the XML Configuration File

The most common way to configure Mule ESB is with Spring XML files that use custom Mule namespaces.
Use one of the two namespaces in your spring framework schema in Mule:

* `http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.1.xsd`
* `http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-current.xsd`

link:/mule-user-guide/v/3.7/about-the-xml-configuration-file[Learn more about the XML Configuration File.]

== Spring Application Contexts


Mule offers several options for creating and managing link:/mule-user-guide/v/3.7/spring-application-contexts[Spring Application Contexts] for your application.

* Single application context
* Multiple application context
* Existing application context
* Existing application context as parent

== Using Spring Beans as Flow Components

Build Spring beans to define component behaviors which Mule applications can reference. link:/mule-user-guide/v/3.7/using-spring-beans-as-flow-components[Learn more.]

== Spring Bean Definition Profiles

Mule’s configuration file takes advantage of Spring 4.1's ability to create *bean definition profiles*. You can use Spring bean definition profiles to register different beans for different target environments, instead of using one bean for all target environments. Refer to link:http://docs.spring.io/spring/docs/4.1.6.RELEASE/spring-framework-reference/htmlsingle/[Spring’s blog posting] for more information about bean definition profiles.

== See Also

* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
