= API Analytics
:keywords: analytics

API Analytics can provide insight into how your APIs are being used and how they are performing. From API Manager, you can access the Analytics dashboard, create a custom dashboard, create and manage charts, and create reports. In API Manager, you can get following types of analytics:

* API viewing analytics
* API events analytics
* Charted metrics in API Manager
* Consumer analytics

You can view data from a policy perspective in the Analytics dashboard, Analytics chart, or API Manager by including policy violations. This action tracks traffic rejected, or not rejected, by a policy. 

== See Also

*** link:/api-manager/v/1.x/viewing-api-analytics[Viewing Analytics]
*** link:/api-manager/v/1.x/analytics-event-api[Analytics Event API]
*** link:/api-manager/v/1.x/analytics-chart[Chart in API Manager]
*** link:/api-manager/v/1.x/api-consumer-analytics[Analytics - API Consumer]
*** link:/api-manager/v/1.x/analytics-event-forward[About Event Forwarding]







