= To Set the API URL

On the API version details page, you can configure the inbound endpoint of the API you plan to deploy. This action is required for Anypoint Platform to manage the API, either directly or by proxy. Defining a value in the RAML for the baseURI configures the Implementation URL of the API endpoint configuration Configure Endpoint.

. In API Manager, in API Administration, click an API version link.
. On the API version details page, click Configure Endpoint.
. Provide the actual inbound URL of the API, not a placeholder URL. If the API is deployed on-premises and you are using a load balancer, enter your load balancer endpoint here.
. Configure or accept other settings to set up and deploy an API proxy.
. Click Configure.

== See Also

* link:/api-manager/v/1.x/tutorial-set-up-and-deploy-an-api-proxy[API version details page]
* link:/api-manager/v/1.x/configuring-endpoint-reference[Endpoint Configuration Reference]
* link:/api-manager/v/1.x/configuring-an-api-gateway[Load balancer endpoint]
* link:/api-manager/v/1.x/tutorial-set-up-and-deploy-an-api-proxy[To Set Up and Deploy an API Proxy]
