= To Access the Developer Portal

API portals listed on an organization's developer portal that are public, or to which you have been granted Portals Viewer access, are visible to you. From the public Anypoint Platform Developer portal, you can access Anypoint Platform APIs to automate Anypoint Platform activities.

To access the Anypoint Platform Developer Portal:

The Anypoint Platform developer portal is a public portal that you can find by searching on the internet or by clicking the link at the bottom of this page. 

To access your organization's developer portal, use one of the following methods:

* Enter the name of your organization in a URL as follows:
+
`+http://anypoint.mulesoft.com/apiplatform/\{yourorgdomain}/#/portals+`
+
* From the API Administration page, use the hamburger menu on the right.

== See Also

* link:https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals[Anypoint Platform developer portal]
* link:/access-management/roles#default-roles[Portals Viewer]