= About Auto-Discovery (New and Classic)

API auto-discovery is the mechanism to manage an API from API Manager by pairing the deployed application to an API created on the platform. Auto-discovery plays a key role in API governance through policies. Critical to the auto-discovery process is providing one of the following types of credentials, depending on the API Manager version you use, correctly:

* apiId (New API Manager)
* API name and version (Classic API Manager)

To connect to an organization from Mule Runtime:

* If the API is registered in the latest API Manager, you need to provide the client id and client secret of the organization's environment.
* If the API is registered in the classic API Manager, you need to provide the client id and client secret of the organization's business group. 

These credentials are set as follows:

* Deploy from Studio
+
Studio 6.0: Add organization credentials to Studio Preferences. For more information, see the Studio 6 documentation (link below).
+
* Deploy the API through API Manager or Runtime Manager
+
The client ID and client secret are configured automatically
+
* Deploy from the Mule command line
+
You configure the client ID and client secret in `$MULE_HOME/conf/wrapper.conf` as described in the next topic.
+
* Deploy some other way
+
Set system properties in Runtime Manager. In the property settings using the following names:
+
** anypoint.platform.client_id={your client ID}
** anypoint.platform.client_secret={your client secret}

== No Support for Auto-Discovery (Studio 7)

// How do you add the element exactly? Example to come.

The auto-discovery element is not supported in Studio 7.0. In order to connect and to manage an API from Studio, you need to manually add the element to your Studio 7 applications.

== See Also

* link:/anypoint-studio/v/6/setting-up-your-development-environment#configure-anypoint-platform-credentials[Configure Anypoint Platform Credentials - Studio 6]
* link:/api-manager/configure-auto-discovery-task[To Configure Auto-Discovery]


// Eng will provide Studio 7 example application showing auto-discovery configuration


