= API Gateway Runtime--Archive
:keywords: gateway, cloudhub, policy, connectors

Mule 3.8.0 unifies the API Gateway runtime with the core Mule runtime.

An API Gateway runtime is used with Mule 3.7.x and earlier. API Gateway runtime was designed and optimized to host an API or to open a connection to an API deployed to another runtime. The API Gateway runtime performs a number of functions critical to running and managing APIs.

* Serves as a point of control over APIs, determining which traffic is authorized to pass through the API to backend services, to meter the traffic flowing through, to log all transactions, and to apply runtime policies to enforce governance like rate limiting, throttling, and caching.
* Integrate APIs with the backend services that power them. An API is just an interface that calls functionality living in a service or application, and unless that functionality lives in a well-defined web service, integration and orchestration capabilities are required to connect it to the API.

== Capabilities and Limitations of API Gateway runtime

API Gateway runtime is limited in the following ways:

[%autowidth.spread]
|===
|*Connectors* a|
* HTTP/S
* Jetty
* Web Services Consumer
* JDBC
File
|*Custom Connectors* |Not supported
|*Integration Capabilities* a|
* Message processors
* Transaction management
* Error handling
* Mule Expression Language (MEL)
* DataWeave (Transform Message)
* DataMapper
* DataWeave
|*Batch Processing* |Not supported
|===

To use other connectors or components you must purchase a license for Mule Enterprise. Contact a  mailto:info@mulesoft.com[sales representative]  for more information.

== API Gateway Deployment

API Gateway runtime can be deployed to the cloud or on premises. Deciding on the right environment for your use case depends on a number of factors including the location of backend endpoints, enterprise architecture, and corporate security policy. Gateways can be deployed as single nodes or in clusters to support HA and high throughput use cases.

== Starting and Stopping API Gateway

To run API Gateway in the background:

. Use the `cd` command to navigate to the `<MULE_HOME>/bin` directory.
. Run the startup script according to the options below.
** *Windows:* `gateway.bat start`
** *Linux:* `./gateway start`

To start API Gateway in the foreground:

. Navigate to the `<MULE_HOME>/bin` directory.
. Run the startup script with the start option.

* *Windows:* `<MULE_HOME>\bin\gateway`
* *Linux:* `<MULE_HOME>/bin/gateway`


To stop the gateway, run the script with the `stop` parameter.

== See Also

* link:/api-manager/configuring-an-api-gateway[Configuring an API Gateway]
* link:https://www.mulesoft.com/legal/versioning-back-support-policy[Support policies for API Gateway versions and API Gateway Runtimes].
