= API Manager Reference
:keywords: user guide, api, api manager

You can set up an API on Anypoint Platform in one of the following ways:

* Using API Manager to define a name and version
+
You can register the name you want to use for an API and build it from the ground up in API Manager.
+
* Using API Manager to import an API that was exported from API Manager
+
You can import a Mule app and register it as an API in API Manager.
+
* Configuring API auto-discovery on the API to register it with API Manager
+
API Manager can link:https://docs.mulesoft.com/api-manager/api-auto-discovery[discover] and register a Mule app deployed from Studio without user intervention.

After registering an API in API Manager, you can use API Manager tools for deployment, analysis, management, publication, and more.

You can design, develop, and manage APIs in Anypoint Platform using the following tools that you access from API Manager:

* API Designer, the custom environment for defining an API in RAML

* An analytics dashboard (anypoint.mulesoft.com/analytics), one or more charts that display metrics for the APIs registered in your organization

* API portal tools for publishing your API and related information, such as documentation

* API Notebook (anypoint.mulesoft.com/apinotebook), a versatile interactive JavaScript programming environment that you can embed in an API portal to demonstrate calls to an API for example

* API Console that you can use with API Designer to simulate calls to the API

Some features that might not be visible or accessible to you, depending on the link:/release-notes/api-manager-release-notes#april-2016-release[entitlements you purchased].
