= API Auto-Discovery Reference (New)
:keywords: auto-discovery, autodiscovery, auto-discovery schema, auto-discovery namespace

The configuration.xml of a project that includes auto-discovery references the main flow, where you configure the HTTP listener. From the auto-discovery configuration, API Manager obtains the information necessary to register the APIs described by the global elements. 

=== api-platform-gw Attributes

The api-platform-gw attributes include the `flowRef` attribute. In an APIkit project, the global element includes an `apikitRef` that references the APIkit global configuration. 

==== API Manager 

The following table lists the `api-platform-gw` attributes:

[%header,cols="3*a"]
|===
|Attribute |Required |Description
|*apiId* |Yes |The friendly API name that appears on API Manager and in Studio on Global Element Properties.
|*flowRef* |Yes |A reference to the main flow of your project. It triggers the agent to discover this flow and use it when performing the auto-registration.
|*apikitRef* |No |A reference to the APIkit configuration. Used to upload the RAML file to Anypoint Platform after API registration completes and for resource level policies.
|*create* |No |Enables/disables the automatic creation of APIs in the auto-discovery process. If false or not present, the API is still tracked by Anypoint Platform if it already exists. If it doesn't already exist, the application won't communicate with the platform. 
|===

The following configuration.xml is an example of an API configured for auto-discovery:

[source, xml, linenums]
----
<api-platform-gw:api apiId="${api.id}" flowRef="proxy" create="true" apikitRef="api-config" doc:name="API Autodiscovery">
  <api-platform-gw:description>Consume site statistics and perform Q3 computations</api-platform-gw:description>
  <api-platform-gw:tag>Q3results</api-platform-gw:tag>
</api-platform-gw:api>
----

The `api-platform-gw` global element contains the information needed to register an API in Anypoint Platform. The global element includes the description and tag attributes. The values you set for these attributes appear on the API version details page after registration:



=== api-platform-gw Nested Elements

The following attributes list the `api-platform-gw` nested elements.

[%header,cols="34a,33a,33a"]
|===
|Nested Element |Required |Description
|*api-platform-gw:description* |No |A description of the API that appears on the API version details page when Anypoint Platform discovers and registers the API.
|*api-platform-gw:tag* |No |The tag is searchable metadata in the API Manager and API that appears on the API version details page when Anypoint Platform discovers and registers the API.
|===

== Auto-Discovery Namespace, Schema, and Dependency Information

TBD


*Auto-Discovery Dependency Information*

----
<dependency>
  <groupId>com.mulesoft.anypoint</groupId>
  <artifactId>mule-module-autodiscovery</artifactId>
  <version>TBD</version>
</dependency>
----

