= To Apply ID-protected Policies

You can set up client ID-based policies, such as throttling and rate limiting, to obtain the client ID and secret as query parameters. Define a trait as described in this procedure.

. On the API version details page of a deployed API, click the *Policies* tab.
+
The list of available policies appears.
+
. Click *Apply* for the Throttling - SLA-based policy.
+
The *Apply "Throttling - SLA based" policy* dialog appears.
+
. Accept the defaults, click *Apply*.
+
. Click *Apply* for the Rate limiting - SLA-based policy.
+
The *Apply "Rate limited - SLA based" policy* dialog appears.
+
. Accept the defaults, click *Apply*.
. On the list of available policies, click the *Raml snippet* for either of the policies you applied.
. Follow instructions to add traits to RAML for enforcing the policies: Open API Designer and edit the RAML as follows:
+
* Add a section called `traits:` at the root level to define query parameters:
+
[source,yaml,linenums]
----
traits:
  - client-id-required:
      queryParameters:
       client_id:
        type: string
      client_secret:
        type: string
----
+
* Reference the trait in each of the methods to specify that each of the methods require these query parameters. After each method in the RAML file, add `is: [client-id-required]`. For example:
+
[source,yaml,linenums]
----
/products:
  get:
    is: [client-id-required]
    description: Gets a list of all the inventory products.
----