= About the Client ID Enforcement Policy (Nov 2017)

In Mule 3.8.5 or later, these OAuth 2.0 Token Enforcement policies include a client ID from the OAuth provider:

* OAuth 2.0 Access Token Enforcement Using External Provider
* PingFederate Access Token Enforcement
* OpenID Connect Enforcement Access Token Enforcement

The OpenAM Enforcement policy does not provide validation.

The Client ID Enforcement policy checks that all requests are made by a valid client application. The enforcement checks the request for a client ID and optional secret that matches the provider's. As this data is in API Manager, each Mule Runtime keeps a cache, which updates periodically. This cache is persistent, and is useful for performance, and in the event of a sudden loss of connectivity to the platform. The enforcement is applied regardless of the state of the management plane.

Common uses of this policy are: 

* Client ID and (optional) secret as headers.
* Client ID and (optional) secret as query parameters.
* Client ID and secret as a basic access authentication header.
* Client ID and secret as a basic access authentication header.

In Mule 4, MEL expressions are replaced by DataWeave expressions.

== See Also

* link:/api-manager/oauth2-policies-new[About OAuth 2 Policies]
* link:/api-manager/configure-federate-proxy[To Configure the Federated Proxy Connection]
* link:/api-manager/oauth-policy-implementation-concept[About OAuth 2 Policy Implementation]