= To Grant Permission to Access Environments

API Manager Environment Administration is the only permission available for accessing API Manager. To grant this permission to a user, first make the user a member of a role that supports this permission.

. In Access Management > Roles, select a role from the list of roles defined for your organization. For example, click the CloudHub Admin (QA) name.
+
In Permissions, the following categories of permissions you can grant to the role you selected appear:
+
* APIs
* API Manager
* Runtime Manager
* Data Gateway
* Design Center
+
If these categories do not appear, the role you selected doesn't support granting these types of permissions. Select a different role.
. Select API Manager.
. In Environment, click the text entry box.
+
A list of environments defined for your organization appears.
+
. Select an environment.
+
. In Permissions, select API Manager Environment Administration.
. In Environment, select another environment.
. In Permissions, select API Manager Environment Administration.


