= OAuth 2.0 Access Token Enforcement Policies (Nov 2017 and Jul 2017)
:keywords: oauth, raml, token, validation, policy

To secure an API in Anypoint Platform using OAuth, use one of the following policies and the matching OAuth provider instead of the OAuth 2.0 Access Token Enforcement Using External Provider Policy and a Mule Provider:

* OpenAM OAuth Token Enforcement policy
* PingFederate OAuth Token Enforcement policy
* OpenID Connect Access Token Enforcement Policy

Any of these token enforcement policies do _not work_ with a Mule client app to access OAuth 2.0-protected resources outside Anypoint Platform. You need to configure the HTTP Requester connector. 

An authorization enforcement policy, which you apply to an API in Anypoint Platform, connects to an OpenAM authorization server, an OpenID Connect Token Introspection endpoint, PingFederate authorization server, or a custom OAuth 2.0 provider.

*Important:* To use the OAuth 2.0 Access Token Enforcement Using External Provider policy, you need a Mule OAuth 2.0 provider to provide an access token. You _cannot use_ any other OAuth 2.0 provider, such as Facebook, Google, or Azure. 

If for some reason, you cannot use one of the recommended providers, use OAuth 2.0 Access Token Enforcement Using External Provider Policy for protecting your APIs using OAuth. Like other API Manager-enforced policies, the API needs to be registered in API Manager to apply and OAuth 2.0 Access Token policy.

== Prerequisites

* You are an Anypoint Platform organization administrator or have permission to create or manage APIs in an environment.
* You set up your Anypoint Platform organization as a federated organization using either OpenAM, OpenID Connect, or PingFederate. See link below. Alternatively, you have a Mule OAuth 2.0 provider configured and running.


== See Also


* link:/mule-user-guide/v/3.8/authentication-in-http-requests[the HTTP Requester connector]
* link:/api-manager/aes-oauth-faq[OAuth 2.0 provider]
* link:/api-manager/openam-oauth-token-enforcement-policy[OpenAM OAuth Token Enforcement]
* link:/api-manager/openid-oauth-token-enforcement-policy[OpenID Connect OAuth Token Enforcement]
* link:/api-manager/pingfederate-oauth-token-enforcement-policy[PingFederate OAuth Token Enforcement]
* link:/access-management/managing-api-clients[About Client Management for federated users and OpenID Connect introspection endpoint]


