= Using Gatekeeper to Enhance Security

As a security improvement in Mule Runtime 3.8.0 and later, API Manager uses Gatekeeper to disable a managed API until the following conditions are met:

* Connection is made to API Manager
* Policies are downloaded
* Policies are applied 

During the disabled period, an API returns a 503 (Service Unavailable) status code until the runtime can communicate, retrieve, and apply the list of policies.

The released version of Gatekeeper is enabled by default in the standalone version of Mule. The development version of Gatekeeper in Studio 6.0.1 is disabled by default. Enable and configure the gatekeeper property to enhance security. Add and set the `anypoint.platform.gatekeeper` property to true in the Mule `wrapper.conf` file. For example:

----
 #On-Prem Configuration: 
 ...
 wrapper.java.additional.<n>=-Danypoint.platform.gatekeeper=true
 ...
----

The gatekeeper feature is available only in Studio and standalone instances. Cluster support will be addressed in a future release.


