= HTTP Policy Transform Extension

The intention of this extension is to make easier the modification of HTTP Requests and Responses that go
 through the different policies.

== Operations

- <<Add Headers>>

- <<Remove Headers>>

- <<Set Response>>

- <<Set Request>>

=== Add Headers

Allows to add headers in both requests and responses of the HTTP Listener and Requester In some cases, it will create a new request / response
with the specified headers. This happens when the output type defined in the operation is not correlated with
it is actually present in the Mule Message.

For example, if the outputType specified is `response`, but when the operation
is executed the Mule Message still contains the HTTP Request, then it will overwrite the whole value instead of just adding
the headers to the request.

====== Parameters

 - outputType: Valid values are `response`, `request`, `requester-request`. Defines the type of the attributes of
 operation's response. Its value depends on where is the operation being called from:

 .. From Source Policy, before the `execute-next` is invoked, then `request` should be the value

 .. From Source Policy, after the `execute-next` is invoked, then `response` should be the value

 .. From Operation Policy, before the `execute-next` is invoked, then `requester-request` should be the value

 .. From Operation Policy, after the `execute-next` is invoked, then `response` should be the value

 - headers: A Data-Weave expression that resolves to the Map of headers to be added to present message attributes

.Example
----
<http-transform:add-headers outputType="response">
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
</http-transform:add-headers>
----

=== Remove Headers

Allows to remove headers from both requests and responses of the HTTP Listener and Requester.
Returned attributes are always of the same type of the input attributes. Operation is case-insensitive

====== Parameters

 - headers: A Data-Weave expression that resolves to an Array of header names to be removed.

.Example
----
<http-transform:remove-headers>
    <http-transform:headers>#[['FirstHeader', 'SecondHeader']]</http-transform:headers>
</http-transform:remove-headers>
----

=== Set Response

Allows to set a complete HTTP Response. This is useful for scenarios, where the
policy prevented the flow from being executed, thus there is not a HTTP Response in place.

====== Parameters

 - statusCode: An integer representing the HTTP Status Code of the response.

 - reasonPhrase: A String representing the HTTP Reason Phrase of the response.

 - body: The content of the HTTP Response.

 - headers: A Data-Weave expression that resolves to the Map of headers of the HTTP response

.Example
----
<http-transform:set-response statusCode="203" reasonPhrase="policyReasonPhrase">
    <http-transform:body>#['policyPayload']</http-transform:body>
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
</http-transform:set-response>
----

=== Set Request

Allows to set a complete HTTP Request that the HTTP Requester is going to execute.

====== Parameters

 - requestPath: The path where the HTTP Request is being sent.

 - body: The content of the HTTP Request.

 - headers: A Data-Weave expression that resolves to the Map of headers of the HTTP request

 - uriParams: A Data-Weave expression that resolves to the Map of Uri Params of the HTTP request

 - queryParams: A Data-Weave expression that resolves to the Map of Query Params of the HTTP request

.Example
----
<http-transform:set-requester-request requestPath="/backend/policy/{policyUriParam}">
    <http-transform:body>#['policyPayload']</http-transform:body>
    <http-transform:headers>#[
        {
            'FirstHeader': 'FirstHeaderValue',
            'SecondHeader': 'SecondHeaderValue',
            'ThirdHeader': 'ThirdHeaderValue'
        }
    ]</http-transform:headers>
    <http-transform:uri-params>#[
        {
            'FirstUriParam': 'FirstUriParamValue',
            'SecondUriParam': 'SecondUriParamValue'
        }
    ]</http-transform:uri-params>
    <http-transform:query-params>#[
        {
            'FirstQueryParam': 'FirstQueryParamValue',
            'SecondQueryParam': 'SecondQueryParamValue'
        }
    ]</http-transform:query-params>
</http-transform:set-requester-request>
----
