= To Import an API

You can import an API into API Manager from Exchange or your file system under the following conditions:

* You have access to APIs published in your organization's Exchange.
* On your file system, you have an ZIP file containing an API that was exported from Anypoint Platform.

== To Import an API from Exchange

. After logging into Anypoint Platform, click API Manager.
. In API Administration, select Manage API > Import API From Exchange.
+
Import API From Exchange appears.
. In Import API from Exchange, select import options:
+
* In API Name, select the API you want to import from the list of published APIs.
* In API Version, select a version of the API published in Exchange.
* In API Specification Version, select the API in Design Center that might be unpublished or published in Exchange.
+
A link to the RAML specification in Design Center appears so you can verify that you want this version.
* Optionally, in Implementation URL, select the URL of the site that hosts the API or click Add A New URL.
+
Typically, you skip this step because the URL is not required at this point. 
* Click Configure.
. In Manage New API, accept the default to set the type of API to Embedded or change the type to Proxy.
+
Set the type to Embedded if you deploy the API on Anypoint Platform, for example on CloudHub. Set the type to Proxy if you plan to deploy the API on your own server.
. Click Save, or Save And Deploy, to import the API.
+
Under the following conditions, Save and Deploy also deploys the API:
+
* You are an API Versions Owner or re assigned the Organization Administrators role.
* You set the URL of the site earlier in this procedure.


== To Import an API from the File System

. After logging into Anypoint Platform, click API Manager.
. In API Administration, select Manage API > Import API from the Desktop
. Browse to and select the file ZIP file that contains the exported API to import.
. Repeat the steps in the procedure to import an API from Exchange starting at step 3.
