= Introduction to Policy Management
:keywords: policy, endpoint, policy management architecture

A policy is a mechanism for enforcing filters on traffic. These filters generally control authentication, access, allotted consumption, and SLAs. API Manager offers a number of pre-built policies, listed in link:/api-manager/using-policies#available-policies["Available Policies"]. You can also build link:/api-manager/creating-a-policy-walkthrough[custom policies] to extend policy capabilities beyond those of the pre-built policies. 

You deploy a proxy API application and apply one or more policies to control how and when a received request is forwarded to its implementation endpoint. For example, you can apply the Client ID Enforcement policy to govern your API version at runtime. This policy allows only authorized applications to access the deployed API implementation. 

Each authorized application is configured with credentials: client_id and client_secret. At runtime, authorized applications provide the credentials with each request to the API implementation. Depending on the policy configuration, the application usually needs to provide credentials in one of these ways:

* In the headers of the HTTP request
* In the URL as query parameters

If the credentials are valid, the policy grants access to the deployed API implementation; otherwise, the policy denies access. Credentials are granted per version. If an application obtains credentials to access v1 of the API, the application cannot use the same credentials to access v2 of the API. The application needs to explicitly request access for v2 of the API even through the application credentials are the same as those for v1. 

== Architecture of API Policy Management

Policies are implemented through coordinated communication between three components:

* API Manager
* One or more API Gateway runtimes or Mule 3.8.0 or later runtimes
* One or more API proxy applications

You apply and configure policies in the API Manager from a particular Anypoint Platform account and a specific organization. You apply policies to a particular API version. A particular API version can also be tied to a particular API implementation endpoint, which can then auto-generate an API proxy application. You can then deploy each API proxy application to one or more API Gateway runtimes or Mule 3.8.0 or later. Mule 3.8.0 or later includes all the legacy API Gateway runtime features. 

Each API proxy application receives requests on HTTP or HTTPS URLs specified by the API. Normally requests are forwarded to the corresponding API implementation endpoint URL, and then the response travels through the API proxy application back to the requesting client application. 

== Policy Injection and Enforcement

When you deploy an API proxy application for a specific API version to a legacy API Gateway runtime or to Mule 3.8.0 runtime or later, any applied policies in the runtime /policies folder are injected into the API proxy. This changes the behavior of the application. 

When the proxy application receives a new request, all injected policies are applied to decide if, and how, the request is forwarded to the API implementation endpoint. 

In this way, the actual policy enforcement occurs inside the proxy application itself, minimizing the cross talk between the API proxy, which is processing the received request, the Anypoint Platform agent, and online API Manager. The API proxy applicaiton does not require any communication with the Anypoint Platform agent running in the runtime, nor does it require any communication with API Manager.

However, the Anypoint Platform agent remains connected to API Manager. After policies are reconfigured or removed from API Manager, those policies are downloaded to any connected API Gateway or Mule runtimes, which updates each runtime /policies folder. The policy changes are then again injected into each API proxy application. This allows policies to be dynamically changed without having to redeploy the API proxy application, and without having to restart the API Gateway or Mule runtimes.  