= Managing an API
:keywords: api, manage

== Assumptions

The pages in this section all assume that you have API Version Owner permissions for the API version that you are trying to manage, or that you are an Organization Administrator. It also assumes that you have link:/api-manager/setting-your-api-url[set your API URL].

API management features might not be visible or accessible to you, depending on link:/release-notes/api-manager-release-notes#april-2016-release[entitlements you purchased].

== API Version Management and Governance Options

Via the API Versions Details page, you have access to all API management functionality of the Anypoint Platform. Click to learn more about:

* link:/api-manager/using-policies[Using Policies]
* link:/api-manager/defining-sla-tiers[Defining SLA Tiers]
* link:/api-manager/managing-api-versions[Managing API Versions]

== See Also

* link:/analytics/viewing-api-analytics[view analytics for APIs].
* link:/api-manager/engaging-users-of-your-api[engage users of your API].
