= Managing an API
:keywords: api, manage, start, stop, configuration

Managing an API includes the following tasks:

* Redeploy, restart, and stop an API from running
* Viewing and changing the endpoint configuration
* link:/analytics/viewing-api-analytics[Monitoring the API analytics]
* link:/api-manager/using-policies[Applying policies] and link:/api-manager/defining-sla-tiers[SLA-tiered access]
* link:/api-manager/managing-api-versions[Managing API Versions]
* link:/api-manager/engaging-users-of-your-api[Working with API Users]

Manage APIs and applications, including starting and stoping a proxy deployed on CloudHub using link:/runtime-manager/managing-cloudhub-applications[Runtime Manager]. View and change the API endpoint configuration in the Status area of the link:/api-manager/tutorial-set-up-and-deploy-an-api-proxy#navigate-to-the-api-version-details-page[API Version Details page].

API management features might not be visible or accessible to you, depending on link:/release-notes/api-manager-release-notes#april-2016-release[entitlements you purchased].

