= Mule 4 Policy Reference (Nov 2017)

Rate limited APIs running under Mule 4 can use the following flags that APIs running under earlier releases cannot: Clusterizable and Expose headers

== Clusterizable Flag

In 2.x and 3.x API Gateway Runtimes configured as a cluster, the policy automatically runs in distributed mode. In Mule 4.x. you can choose distributed or standalone mode, despite the Gateways being configured as a cluster. If the mode is standalone, the clusterizable flag does not change any behavior.

== Expose Headers Flag

This flag backs out x-rate-limit headers from the response.

== Other Mule 4 Features

Other features that affect policies are:

* Policies ordering
+
In API Gateway Runtime 2.x and 3.x, with the exception of CORS which runs always first, Rate Limiting and Throttling would run first in the chain. Now, which policies run first is completely configurable with the exception of CORS.

* DataWeave
+
MEL expressions are replaced by DataWeave.

* Optional Client Secret
+
You can choose to check only the Client Id in your SLA policy. This is especially useful when combining this policy with a federated one.

* Compatibility with federation policies
+
Federation policies are fully compatible with SLA policies. As the later can now be ordered, and client secret is not required. Federation policies can exchange the token for the client ID and feed the client ID to the SLA policy.

* link:/api-manager/throttling-rate-limit-reference[Throttling And Rate Limiting Policies Reference]
* link:/api-manager/tutorial-manage-an-api[To Apply a Resource-Level Policy and SLA Tier]
* link://api-manager/delete-sla-tier-task[To Delete an SLA Tier]

