= PingFederate and OpenAM OAuth Clients and Grant Types Reference (New)

OpenAM supports two types of OAuth clients:

* A Confidential Client keeps its credentials confidential and includes the following grant types:
** Client Credentials
** Implicit
** Password
* A Public Client shares its credentials with other parties and includes the following grant types:
** Authorization Code
** Implicit
** Password

Each type of client supports three of the four OAuth grant types. For this reason, when configuring the OpenAM client, you can select only three of the four grant types. The other grant type is unavailable because it belongs to the other client. You determine the public or confidential property of the OpenAM client depending on the grant types you select.

A PingFederate client allows any combination of OAuth grant types: Implicit, Client Credentials, Resource Owner Password Credentials, and Authorization Code. As a PingFederate user, you can enable or disable grant types in any order you want.

== See Also

* link:/api-manager/oauth2-policies-new[About OAuth 2 Policies]
* link:/api-manager/configure-federate-proxy[To Configure the Federated Proxy Connection]
* link:/api-manager/client-id-enforcement-new-concept[About Client ID Enforcement Policy]
* link:/api-manager/oauth-policy-implementation-concept[About OAuth 2 Policy Implementation]

