= About Policy Changes in Mule 4 (Latest)

A policy is a mechanism for enforcing filters on traffic. These filters generally control authentication, access, allotted consumption, and service level access (SLA). Policies applied to APIs in the latest release of API Manager are those in the classic API Manager with some noteable exceptions covered in this topic. 

Mule 4 offers classloader isolation between the application, the runtime and the connectors, and policies. To fulfill the isolation requirement, policies are self-contained and packaged to include libraries needed for execution, similar to an application.

Other changes to policies are:

* All policies are non-blocking, as described in Mule 4 documentation. 
* All policies except CORS, which is executed first, can be ordered. 
* Resource level policy support, which was restricted to RAML-based APIs, is extended to any HTTP API. 
* You can distribute policies outside of the runtime, providing frictionless upgrades.

API management includes the following key enhancements to policies:

* Policy packaging
* Policy scope
* Policy size

== Changes to Out-of-the-Box Policies

Noteable changes to policies for governinng APIs are:

// Expose Headers might change to Propagate Headers

* You can apply the RAML Validator policy to RAML-based APIs or proxies. 
* Mule 4 removes dependencies between policies, resulting in the incorporation of security managers policies. Two HTTP Basic Authentication policies are available: one based on the simple security manager configuration and the other on the LDAP configuration. 
* Header propagation no longer occurs by default. You can configure header propagation for token enforcement and rate limiting policies by checking the Expose Headers checkbox. 
* You can configure the rate limiting policy if the cluster shares the quota or not. By default the cluster shares the quota.
* The throttling policy is not supported.

== See Also

* Link to non-blocking in Mule 4
* link:/api-manager/policy-scope-size-concept[About Policy Packaging, Scope, and Size]


