= About Policy Packaging, Scope, and Size (Latest)

A policy consists of the following things:

* A YAML file
* An XML template
* Resources

The YAML file defines the configurable parameters of the policy. This file is rendered by the UI to display the input of the policy.

The XML template contains the implementation of the policy. The template POM defines the policy dependencies. The packaging type needs to be ‘mule-policy’

Optionally if the policy depends on other resources, such as a certificate, the resources have to be defined as part of the policy. For example, the mule-artifact.json descriptor and `mule-policy` classifier need to be defined. For more information, see the header policy.

== Policy Scope

Policies are isolated from the application and other policies, however there are ways to expose information about a policy:

* The authentication information about a policy can be propagated in the Security Context Principal object.
* Headers are not propagated by default. If a policy is expected to forward headers, the implementation needs to be explicit about it. 
* Out of the box policies provide a configurable option to propagate headers.
* A policy can modify message content.
* A policy can stop the execution flow.
* Variables set on a policy have only the scope of the policy.

== Policy Size

The size of a policy varies based on its dependencies. The first time the API Gateway polls for policies it will take longer to fetch them. However, after policies are retrieved, they are cached on the file system. This ensures offline availability and also reduces latency to fetch policies. 

== See Also

* Header policy
* link:/api-manager/policies-4-concept[About Policies]
