= What's New in Policy Management (Nov 2017)

In Mule 4, classloader isolation exists between the application, the runtime and the connectors, and policies. 

Other changes to policies are:

* All policies are non-blocking, which is described in Mule 4 documentation. 
* All policies except CORS, which is executed first, can be ordered. 
* Resource level policy support, which was restricted to RAML-based APIs, is extended to any HTTP API. 
* You can distribute policies outside of the runtime, which simplifies upgrades.

Mule 4 introduces changes to the packaging, size and scope of a policy.

== Changes to Out-of-the-Box Policies

Notable changes to policies for governing APIs are:

* API Manager now provides two HTTP Basic Authentication policies, one based on the simple security manager configuration and the other on the LDAP configuration.
* Header propagation no longer occurs by default. You can configure header propagation for token enforcement and rate limiting policies by checking the Expose Headers checkbox.
* You can configure the rate limiting policy to share the quota among the cluster nodes (default) or not.

== See Also

// Link to non-blocking in Mule 4

* link:/api-manager/policy-scope-size-concept[About Policy Packaging, Scope, and Size]
