= About Deploying a Proxy (New)

To deploy an API, you typically use a proxy application that serves to stop attacks aimed at the actual server. API Manager auto-generates the proxy when you configure the API as an endpoint with a proxy. Mule Runtime is the server that hosts a Mule proxy application. API manager automatically generates the proxy app and includes an auto-discovery element in the app. After you deploy the app, Mule Runtime calls API Manager using the business group client id and secret to gets the policies for the API. Mule locks the API to receiving calls based on the policies. The client app (consumer) calls the proxy which forwards the call to the API.

In most cases, the proxy you generate in API Manager is suitable for deployment out of the box. However, you can modify the proxy to log data to a file or send data to a Splunk account with the Anypoint Splunk Connector, for example. 

You can import a proxy that you download from API Manager into Studio as a Mule Deployable Archive. You can then modify the proxy in Studio.

If you configured an endpoint with a proxy to use the HTTPS scheme, you need to modify a proxy to add HTTPS credentials.

== See Also

* link:/api-manager/proxy-configure-https-task[To Modify a Proxy for HTTPS - CloudHub]
link:/api-manager/proxy-configure-https-task[To Modify a Proxy for HTTPS - Hybrid]
* link:/api-manager/proxy-deployment-prerequisties-concept[Deployment Prerequisites]


