= To Deploy a Proxy to a Hybrid Environment (Latest)

After configuring the managing type of an API instance as endpoint with a proxy and selecting a hybrid deployment, use this procedure to deploy the proxy.

To perform this procedure you need to meet the following prerequisites:

* Completion of API configuration.
* API Versions Owner permissions for the API, or membership in the Organization Administrators for the master organization. Permissions for the Runtime Manager.
* Access to a Mule Runtime that has been configured to pair with your organization in the case of a private server. Also, the private server must be registered.

After saving the API Configuration if managing an API from Exchange or importing an API, Deployment Configuration appears:


. TBD

. If you chose HTTPS for the scheme of the deployment, complete the steps to build HTTPS services.

== See Also

* link:/runtime-manager/building-an-https-service#services-under-api-manager-proxies[To Build HTTPS Services]
* link:/api-manager/manage-exchange-api-task[To Manage an API from Exchange]
* link:/api-manager/import-api-task[To Import an API Instance]
