= To Deploy a Proxy to a Hybrid Environment (New)

During the configuration of an API instance, you specify to manage the instance as a basic endpoint or as endpoint with a proxy. If you specify deployment to a hybrid of an endpoint with a proxy, use this deployment procedure. 

To perform this procedure you need to meet the following prerequisites:

// what permissions do  you need?

* Completion of API configuration.
* Access to a Mule Runtime that has been configured to pair with your organization in the case of a private server. 
* You need to register your private server with Mule Agent 1.9.0 to deploy the API to a hybrid target.

After saving the API Configuration you manage from Exchange or you import,  Deployment Configuration appears:


. In Deployment Configuration, in Hybrid Target, select the private server you registered with Mule Agent 1.9.0.
. Click Deploy.
. If you chose HTTPS for the scheme of the deployment, complete the steps to build HTTPS services.

== See Also

* link:/runtime-manager/servers-create[Registering a server]
* link:/runtime-manager/building-an-https-service#services-under-api-manager-proxies[To Build HTTPS Services]
* link:/api-manager/manage-exchange-api-task[To Manage an API from Exchange]
* link:/api-manager/import-api-task[To Import an API Instance]
