= Rate Limiting and Throttling

This page describes the configuration and runtime application instructions for two policies:

* *Rate Limiting*
* *Throttling*

To configure these policies, see link:/api-manager/client-id-based-policies[Client ID Based Policies].

== Rate Limiting

Rate limiting consists of putting a limit on how many requests can be accepted within a defined period of time. Any messages beyond the maximum amount within the time period are rejected. There are two policies in the Anypoint Platform that allow you to do this: *Rate Limiting* and **Rate Limiting - SLA Based**.

With the regular rate limiting policy, a limit is imposed globally over all of the requests that reach your API. With the SLA based rate limiting policy, the requests from each application that accesses your API are managed separately.

== Throttling

Throttling works a lot like rate limiting, except that requests that exceeed the limits aren’t rejected, they are delayed and put in a queue. They can then be processed in the following period, or eventually rejected if they get left out repeatedly for an established number of times. There are two policies in the Anypoint Platform that allow you to do this: *Throttling* and **Throttling - SLA Based**.

With the regular throttling policy, a limit is imposed globally over all of the requests that reach your API. With the SLA based throttling policy, the requests from each application that accesses your API are managed separately.

You can also set the delay time in between attempts for when requests are not accepted, as well as the amounts of attempts to try.

