= Rate Limiting and Throttling

You link:/api-manager/using-policies#applying-and-removing-policies[configure and apply] the Rate Limiting policy to limit the number of requests an API accepts within a period of time. The API rejects requests that exceed the limit.

The Throttling policy is similar to the Rate Limiting policy, except requests that exceed the limits enter a queue for possible processing in a subsequent period. The API eventually rejects the request if unable to process it after a certain number of attempts. You can configure a delay between attempts to retry processing rejected requests, as well as a limit on the number of retries.

The Rate Limiting and Throttling policies impose a limit on all requests. The link:/api-manager/rate-limiting-and-throttling-sla-based-policies[SLA-based Rate Limiting and Throttling] policies manage the requests based on the level of access granted to the requesting application.

== Adjusting the Rate Limit for Multiple Workers

If the workers cannot share usage data, which is the case in non-clustered environment, the rate limit needs to be divided among all the deployed workers: rate limit/number of workers. Adjusting the workload in this manner is recommended if the workload for an application is equally distributed across the workers.

