= Rate Limiting and Throttling

You link:/api-manager/using-policies#applying-and-removing-policies[configure and apply] Rate Limiting and Rate Limiting - SLA Based policies to limit the number of requests an API accepts within a period of time. The API rejects requests that exceed the limit.

With the regular rate limiting policy, a limit is imposed globally over all of the requests that reach your API. With the SLA based rate limiting policy, the requests from each application that accesses your API are managed separately.

== Adjusting the Rate Limit for Multiple Workers

In a non-clustered environment (cloud or on-premises), adjust the rate limit based on the number of workers in the deployment as follows: rate limit x number of workers

== Throttling

Throttling and Throttling - SLA Based policies are similar to the rate limiting policies, except requests that exceed the limits enter a queue for possible processing in a subsequent period. The API eventually rejects the request if unable to process it after a certain number of attempts. 

The throttling policy imposes a limit globally over all of the requests that reach the API. The SLA-based throttling policy manages the requests from each application that accesses your API separately.

You can delay the time between attempts to retry processing rejected requests, as well as the number of retries.

