= To Set Up SLA Tiers
In this procedure, you first create tiers of access for developers who want to call your API:

*  A tier that accepts anyone who wants to access the API, but limits this person's application to three requests per minute, and rejects additional requests.
* A tier for a premium access level that accepts up to five requests per minute and requires API Versions Owner approval of the developer who wants to access the API.

Next, you apply SLA-based throttling and rate limiting policies to handle requests that exceed SLA limits that you added.

. In Anypoint Platform, click API Manager, and in API Administration, click an API version link.
. On the API version details page, select the SLA Tiers.
. Add an SLA Tier and set up one limit on the tier as follows:
+
* *Name*: Free
* *Approval*: Automatic
* *Limits*
** *# of Reqs*: 3
** *Time Period*: 1
** *Time Unit*: Minute
+
. Go back to the API version details page, click *Add SLA Tier* again, and set up one limit on the tier as follows:
+
* *Name*: Premium
* *Approval*: Manual
* *Limits*
** *# of Reqs*: 5
** *Time Period*: 1
** *Time Unit*: Minute