= Studio Custom Policy Editor (Beta)

Studio 6.1 (and newer) grants you the ability to create a *policy project*, under which you can group your *custom API policies* and apply them to your local Studio deployments. +
This way you can compose, debug and test custom API policies within Studio, using an editor that fully supports and validates custom API policies design.

[NOTE]
--
The custom policy editor is still in beta and is available only for Enterprise Edition users of link:/release-notes/anypoint-studio-6.1-with-3.8-runtime-release-notes[Anypoint Studio 6.1] and newer.
--

== Assumptions

This article assumes that you are familiar link:/api-manager/using-policies[using policies] in Anypoint Platform and that you are able to link:/api-manager/creating-a-policy-walkthrough[create] and link:/applying-custom-policies[apply] custom policies. +
It also assumes that you are familiar with link:/mule-fundamentals/v/3.8/anypoint-studio-essentials#the-visual-editor[Studio´s Visual Editor].

== Usage

[NOTE]
--
For this beta release, Studio only supports policy creation and edition through XML.
--

In order to create a Policy Project:

. Right click in your *Package explorer* and select, *New* and *Mule Custom Policy Project (beta)*.
. Give a Name to your Policy Project

This creates a link:/api-manager/creating-a-policy-walkthrough#create-the-policy-configuration-file[policy configuration file] (xml) and a link:/api-manager/creating-a-policy-walkthrough#create-the-custom-policy-definition[policy definition file] (yaml).

Note that when the XML editor opens the configuration file, both the `<before>` and `<after>` tags are marked with an error. This is because when creating a custom policy using the policy editor, none of those tags can be empty.

The configuration file also contains a link:/api-manager/applying-custom-policies#using-pointcuts[<pointcut> tag] with two link:/api-manager/applying-custom-policies#referencing-properties[reference properties]:

* `{{ apiName }}`
* `{{ apiVersionName }}`.

These variables are relevant (but not fully required) to associate your custom policy to an underlying API. More details are given in the <<Apply the Custom Policy in Your Local Deployment, deployment  instructions>> below.


== Designing a Custom Policy in Studio

//////
TODO
  Add design steps for custom policies
  Good practices
  Example
//////

== Applying the Custom Policy in Your Local Deployment

Custom policies are independent of the APIs to which you want to apply them. In order to _point_ a policy to an API (or several), you need to link:/api-manager/applying-custom-policies#customizing-a-pointcut[customize the pointcut conditions] to meet your needs. You can either set up an API name and a version (using the reference properties mentioned earlier), or a regex expression to match it with endpoints and resources.

//////
TODO

  Add steps for running configurations when applying policies
//////

== Know Limitations

Being a beta release, the Custom Policy Editor for Studio has some limitations. Keep the following points in mind when designing and testing your custom policy:

=== Limitations for the Configuration File

* XML validation for sections within the policy configuration file (such as `{{#isWsdlEndpoint}} {{/isWsdlEndpoint}}`) is not supported. Policies configured using sections such as the one in the example below will run, but the editor won´t validate them before running.
+
[source,XML,linenums]
----
<mule:processor-chain name="{{policyId}}-build-response">
       <mule:set-property propertyName="http.status" value="403"/>
       {{#isWsdlEndpoint}}
         <mule:set-property propertyName="Content-Type" value="text/xml"/>
         <mule:set-payload value="#[soapFault('client', _invalidClientMessage)]"/>
       {{/isWsdlEndpoint}}

       {{^isWsdlEndpoint}}
         <mule:set-property propertyName="Content-Type" value="application/json"/>
         <mule:set-payload value="#[_invalidClientMessage]"/>
       {{/isWsdlEndpoint}}
   </mule:processor-chain>
----

=== Limitations for the Definition File

* The only supported YAML types for the policy definition file are: `String`, `Boolean`, `Int`, `Expression` and `IpAddress`.
* The `hasContract` boolean to define wether this custom policy has credentials defined to access other APIs or not, is currently not supported.
* Studio does not validate the `gatewayCompatibility` attribute
* `requiredCharacteristics` and `providedCharacteristics` fields are not validated from Studio
* The `{{order}}` attribute from the YAML file is not supported. The order of the policy is overwritten by the other set in the *Run Configurations.* screen.

=== Limititations for Studio

* Importing and exporting custom policies from API Platform is not supported
* Importing custom policies from Exchange is not supported
* As stated earlier, this feature is currently aimed for local testing. Currently it´s not possible to run your custom policies against your APIs in API Manager and validate them there.
* You can only configure one `ApiName` and `ApiVersion` attribute in the Run Configuration.
* The Visual Debugger does not support debugging of custom policies.
* There is no MUnit support
* Maven support for Custom Policies is not supported
