= Studio Custom Policy Editor (Beta)

Studio 6.1 (and newer) grants you the ability to create a *policy project*, under which you can group your *custom API policies* and apply them to your local Studio deployments. +
This way you can compose, debug and test custom API policies within Studio, using an editor that fully supports and validates custom API policies design.

[NOTE]
--
The custom policy editor is still in beta and is available only for Enterprise Edition users for link:/release-notes/anypoint-studio-6.1-with-3.8-runtime-release-notes[Anypoint Studio 6.1] and newer.
--

== Assumptions

This article assumes that you are familiar link:/api-manager/using-policies[using policies] in Anypoint Platform and that you are able to link:/api-manager/creating-a-policy-walkthrough[create] and link:/applying-custom-policies[apply] custom policies. +
It also assumes that you are familiar with link:/mule-fundamentals/v/3.8/anypoint-studio-essentials#the-visual-editor[Studio´s Visual Editor].

== Usage

[NOTE]
--
For this beta release, Studio only supports policy creation and edition through XML.
--

//////
TODO

  Mention the autocomplete feature
//////



In order to create a Policy Project:

. Right click in your *Package explorer* and select, *New* and *Mule Custom Policy Project (beta)*.
. Give a Name to your Policy Project

This creates a link:/api-manager/creating-a-policy-walkthrough#create-the-policy-configuration-file[policy configuration file] (xml) and a link:/api-manager/creating-a-policy-walkthrough#create-the-custom-policy-definition[policy definition file] (yaml).

Note that when the XML editor opens the configuration file, both the `<before>` and `<after>` tags are marked with an error. This is because when creating a custom policy using the policy editor, none of those tags can be empty.

The configuration file also contains a link:/api-manager/applying-custom-policies#using-pointcuts[<pointcut> tag] with two link:/api-manager/applying-custom-policies#referencing-properties[reference properties]:

* `{{ apiName }}`
* `{{ apiVersionName }}`.

These variables are relevant (but not fully required) to associate your custom policy to an underlying API. More details are given in the <<Apply the Custom Policy in Your Local Deployment, deployment  instructions>> below.


== Designing a Custom Policy in Studio

//////
TODO
  Add design steps for custom policies
  Good practices
  Example
//////

== Applying the Custom Policy in Your Local Deployment

Custom policies are independent of the APIs to which you want to apply them. In order to _point_ a policy to an API (or several), you need to link:/api-manager/applying-custom-policies#customizing-a-pointcut[customize the pointcut conditions] to meet your needs. You can either set up an API name and a version (using the reference properties mentioned earlier), or a regex expression to match it with endpoints and resources.

//////
TODO

  Add steps for running configurations when applying policies
//////
