= To Test an Alert (New and Classic)

This procedure describes how to test a request count alert on a sample API that you can download from the link below. This procedure requires the following preparation:

. Design an API.
. If you use the new API Manager, perform these steps; otherwise, skip these steps and go straight to deployment.
* Publish the API to Exchange. 
* In API Manager, manage the API from Exchange.
. Deploy a proxy of the API instance (New) or version (Classic) to CloudHub.
. Apply the Rate Limiting Policy as follows:
* Request Count greater than 1 for at least 1 consecutive minute.
+
Specifically, add the request count alert described in the linked topic below.
. Call the API.
+
. Recall the page two more times (reload the page), and check that `API calls exceeded` appears if you performed the last three steps within the 1 minute period. Any additional page reload operations within the 1 minute period have no effect.
. Check that selected users receive email notifications that requests exceeded the alert threshold and that the alert was resolved.

== See Also

* link:/api-manager/add-api-alert-task[To Add an API Alert]
* link:/design-center/v/1.0/designing-api-about[About Designing a RAML-based API]
* link:/design-center/v/1.0/publish-project-exchange-task[To Publish an API Design Project]
* link:/api-manager/proxy-deploy-cloudhub-latest-task[To Deploy a Proxy to CloudHub]