= Use a Portal as an App Developer 
:keywords: portal, api, console, documentation

Assuming someone in your organization published a portal using API portal tools, and you have permission to view it, you can browse and search your organization's developer portal for APIs to see what members of your organization have posted. 

If you don't see any APIs listed in your organization's Developer portal, first confirm that you are logged in, then check with your organization administrator to request Portals Viewer permissions for APIs of interest to you.

To browse and search the Developer Portal:

. In Anypoint Platform, go to your organization's developer portal using a URL in the following format:
+
`http://apiplatform.anypoint.mulesoft.com/apiplatform/\{yourorgdomain}/#/portals`
+
. Browse APIs in the list, or search for an API by name, version, or its tags
. Explore the API from the left hand navigation. 

== See Also

link:/api-manager/tutorials#check-permissions-and-roles[Permissions]
