= About the API Life Cycle
:keywords: walkthrough, api, tutorial

The procedures in this section cover basic life cycle management in Anypoint Platform. If you don't already have an account, you can sign up to use Anypoint Platform in the cloud:

`+https://anypoint.mulesoft.com+`

The life of an API can begin in API Manager. You name the API to start and you can design a basic RAML by accessing the RAML editor from API Manager. As part of the design, you can use a mocking service to simulate calls to the API. Next, you set up and deploy the API. Finally, you can engage users by publishing the API on a portal. Governing how users access the API through policies and SLA tiers is a key benefit of using API platform. 

Work with the procedures in this section to familiarize yourself with API life cycle management.

== See Also

* link:/api-manager/tutorial-set-up-an-api[Set up an API].
* link:/api-manager/design-raml-api-task[Design a Basic RAML API].
* link:/api-manager/simulate-api-task[Simulate calls to the API].
* link:/api-manager/tutorial-set-up-and-deploy-an-api-proxy[Set up and deploy an API proxy].
* link:/api-manager/tutorial-create-an-api-portal[Publish an API on a portal].
* link:/api-manager/tutorial-manage-an-api[Apply policies and SLA tiers].
* link:/api-manager/tutorial-use-a-portal-as-an-app-developer[Use an API Portal as an App Developer].
* link:/api-manager/tutorial-manage-consuming-applications[Manage API access requests].
* link:/api-manager/delete-sla-tier-task[Delete SLA tiers].
* link:/access-management/roles[Permissions and roles]
* link:/api-manager/tutorial-set-up-and-deploy-an-api-proxy[API version details page]