= Use a Portal as an App Developer 
:keywords: portal, api, console, documentation

Assuming someone in your organization published a portal using API portal tools, and you have link:/api-manager/tutorials#check-permissions-and-roles[permission] to view it, you can browse and search your organization's developer portal for APIs to see what members of your organization have posted. 

If you don't see any APIs listed in your organization's Developer portal, first confirm that you are logged in, then check with your organization administrator to request Portals Viewer permissions for APIs of interest to you.

To browse and search the Developer Portal:

. link:/api-manager/tutorials#get-started[Sign in] to Anypoint Platform.
. Go to your organization's developer portal using a URL in the following format:
+
`http://apiplatform.anypoint.mulesoft.com/apiplatform/\{yourorgdomain}/#/portals`
+
. Browse APIs in the list, or search for an API by name, version, or its tags. For example, browse to the **T-Shirt Ordering Service** you created in the link:/api-manager/tutorial-create-an-api-portal[API Portal tutorial]. 
. Click *T-Shirt Ordering API Simulation* from the left hand navigation. 
+
The API Console based on the API's RAML definition simulates API calls.

== Requesting Access to an API

If the owner of the API has set up an endpoint for it in Anypoint Platform, you see a button at the top of the page that reads *Request API Access*. Click this button to register your application with this API. Registering your application allows the API owner to see key information, including contact information, about who and what is accessing their API version, helping them with needs analysis and lifecycle management. If the API owner has applied certain policies to the API, such as client id enforcement, you'll need to register your application and then pass your client id and client secret in any calls to that API in order to satisfy the requirements of that governance policy.

== Registering Your Application

When you request API access, you are given the option to create a new application or to request access on behalf of an existing application that you created previously. When you create a new application, you provide key information about your application and yourself that helps API owners identify the characteristics and needs of your application so they can make good decisions when approving your for a particular SLA tier, for example. It also gives them the information they need in to contact you (should they need to migrate you to a new version of the API, for example).

When you create an application, you are prompted for a *Name*, *Description*, *Application URL*, and *Callback URL*. If your organization is signed up to use PingFederate for identity management, you are also prompted to select an *OAuth Grant Type*. Many of these fields are optional – fill them out if they are relevant for your application.

Click Submit to commit your application details, then click Request Access. If the API owner has not configured any policies restricting access, or has set those policies to auto-approve access requests, you see a message that reads "Your API access request has been approved." If the access request requires manual approval, wait for the API owner to grant your request.

After you have created your application, you can access information about it on the *My Applications* tab on your organization's developer portal. You need to be logged in to see your applications, because this information is available only to you. The My Applications display provides you with the unique client id and client secret for your application, which you may need to pass in your API calls for APIs that are protected with certain policies.
