= About Basic API Management Tasks
:keywords: walkthrough, api, tutorial

The procedures in this section cover basic life cycle management in Anypoint Platform. If you don't already have an account, you can sign up to use Anypoint Platform in the cloud:

`+https://anypoint.mulesoft.com+`

The Crowd release unifies the setup and design of an API for governance in API Manager. If you have the Crowd release can use the Design Center to author and update RAML specifications. You can use a mocking service to simulate calls to the API. Deployment to CloudHub occurs automatically as you design an API in Design Center. To deploy an API proxy to other servers, you can use API Manager. You can engage users by publishing the API on a portal. In API manager, you govern how users access the API through policies and SLA tiers is a key benefit of using API platform. 

Work with the procedures in this section to familiarize yourself with API life cycle management.

== See Also

* link:/api-manager/tutorial-set-up-and-deploy-an-api-proxy[To Set Up and Deploy an API Proxy]
* link:/api-manager/api-mgr-deploy-soap-proxy[To Set Up and Deploy a SOAP API]
* link:/api-manager/create-api-version-task[To Create a New API Version]
* link:/api-manager/api-permissions[To Share or Remove API Permissions]
* link:/api-manager/import-api-version-task[To Import an API Version]
* link:/api-manager/export-api-version-task[To Export an API Version]
* link:/api-manager/tutorial-create-an-api-portal[To Publish an API on the Portal]
* link:/api-manager/deprecate-api-task[To Deprecate an API Version]
* link:/api-manager/tutorial-use-a-portal-as-an-app-developer[To Use a Portal as an App Developer]
* link:/api-manager/tutorial-create-an-api-notebook[To Create an API Notebook]
* link:/api-manager/play-share-api-notebook-task[To Play and Share an API Notebook]