= WSDL, RAML, and HTTP Proxy Reference (Nov 2017)

In Mule 4, WSDL, RAML, and HTTP proxies have characteristics and benefits that are important to understand for successful and efficient deployments. The following applies to a request that goes through any of these proxies:

* X-Forwarded-For headers are included in request through the proxy.
* Headers received by the proxy are sent to the implementation API, except the ones that Mule includes: X-MULE-SESSION, X-MULE-ENCODING, and so on.
* If a request to the proxy can’t be fulfilled because of a timeout problem, the client receives a response with status code: 504.

Using these proxies results in the following Mule benefits:

* API Manager gathers and reports analytics if you configure auto-discovery in the API. 
* API Manager governs the proxy if you apply policies. 

== WSDL Proxy

A Web Service Definition Language (WSDL) proxy takes advantage of Mule Runtime capabilities and protects your web service. Errors related to out-of-the-box policies are sent as soap:fault messages.

== RAML Proxy

When you deploy a RAML proxy, the resources provided by the API specification are handled and sent to the backend service. Validation against your RAML (0.8/1.0) spec occurs. This includes validation of the following components:

* Headers
* Uri parameters
* Query parameters
* Form parameters
* Body (against JSON schema / XML schema / RAML type)

If the RAML spec specifies optional parameters with a default value, and the request does not provide that parameter, the proxy adds it. This proxy includes the API Console to test your requests. By default, you can open API Console using a URL `host_of_your_proxy:port_of_your_proxy/console`. 

If the RAML spec includes optional parameters with a default value, and the request does not provide that parameter, the proxy adds it.

If a request to the proxy can't be fulfilled for one of the following reasons, the client receives a response code:

* Bad request (Validation result)
+
Code 400
* Not found (The resouce/method could not be found in the RAML spec.)
+
Code 404

== See Also

* link:https://mule4-docs.mulesoft.com/apikit/apikit-simulate.html[API Console - To Simulate API Calls]



