= About Designing a RAML-based API

// tech review by Christian, week of mid-April 2017 (kris 4/18/2017)

In Design Center, you can create, simulate, and publish reusable projects of type API specification or API fragment. RAML.org defines documents of these types something like this:

* API specification
+
A RAML API definition document that begins with the text `#%RAML` followed by a single space and the version number `1.0`. 
+
* API fragment
+ 
A document, such as a data type, that begins with a RAML version comment and a fragment identifier just like a RAML specification, but is not a complete specification. 

You can add API fragments that you store in Exchange to your specifications as dependencies. You can change the fragment independent of the specification, or you can determine if others have made changes. You can update the specification to use another version of the fragment.

To create and publish an API specification or fragment, you need to have the permissions covered in "User Access to Design Center." 

== OAS Support

Design Center supports the RESTful API Modeling Language (RAML) and the Open API Specification (OAS) 2.0, also known as Swagger. When you import an OAS specification, OAS code is converted to RAML. You can edit the resulting RAML code in the RAML editor.

== See Also

* link://design-center/v/1.0/user-access-to-design-center[User Access to Design Center]
* link:/design-center/v/1.0/designing-api-reference[Reference: OAS/RAML Importing and Exporting]

