= Visual Design

link:/getting-started/api-lifecycle-overview#which-version[_Requires Crowd Release_]

Design Center includes visual editing capabilities for RAML API design. If you know a little about REST APIs, you can specify methods and responses visually. RAML expertise isn't required. Design Center lowers the barrier to API specification languages. 

To define a restful endpoint using a GUI instead of writing RAML code, you populate a GUI with values for resources, including resource types, relationships, and HTTP methods. The GUI then generates the RAML specification. The editor prompts you to describe endpoints and formats the specifications with proper indenting. From the visual mode, you can move the design to the full-featured API design mode to enhance or test the design. You can then publish to Exchange.

The resulting RAML output file begins the API life cycle and API design collaboration. 

== Supported RAML Components

The following RAML components are supported:

* Root properties
* Data types (payloads)
* Resources and methods
** Headers
** Query parameters and query strings
** Request body
** HTTP and HTTPS protocols
** Responses and status codes, including associated headers and body

== See Also

* link:/design-center/v/1.0/design-manage-revisions-task[To Manage API Revisions Using Branches]
* link:/design-center/v/1.0/design-raml-api-v-task[To Design a RAML API Specification (Visual Editing)]
* link:/design-center/v/1.0/design-api-basics-tasks[RAML Code Design]

