= FAQ: Design Center
:keywords: mozart, design center, api designer



== General Questions

=== How do I set up an HTTP listener/server?

See link:/connectors/http-trigger-app-from-browser[HTTP to Trigger App From Browser].


=== How do I test my flow?

See link:/design-center/v/1.0/to-debug-a-mule-project[To Debug a Mule Project].


=== Are Apps Created With Design Center and Deployed to Production Supported by MuleSoft?

Currently, they are not supported for using in production. Design Center creates projects with Mule runtime version 4.0.0, which is not officially released yet.

=== Export to Studio & Import from Studio

I only see an ‘Export’ option on Design Center when creating a Mule application, but no ‘Import’.
For our Beta 1 release, we are supporting only the *export* functionality to Studio.

== Connectivity Testing Questions

=== Why is the Test button disabled in the card?

The test button is greyed out until the application worker is created.
Connectivity Testing requires that there’s a worker running in the background to use the runtime.
By hovering over the Test button, a tooltip indicating why it’s disabled is displayed.

=== Do I need to upload a JDBC driver to connect to Oracle DB?

Yes

=== If some of the DBs are listed out of the box, then why do I need to upload drivers?

Due to legal restrictions, it’s necessary that you upload the driver.
Legally, MuleSoft is not allowed to distribute these.

=== When using the FTP connector, I'm not able to connect to my computer as host, though I am able to connect with my locally installed Filezilla client.

The Mule runtime your project is running on isn’t able to connect to your local machine. It’s running in a virtual worker on Cloudhub, its local environment is that virtual machine alone.


== Application Status Questions

=== Why does my app show up as Paused in Design Center but looks green when viewed in the Runtime Manager?

The “Pause” option in Design Center doesn’t pause your CloudHub worker, it just pauses the application that runs in it.



== Metadata Questions

=== Why do I sometimes not see metadata below the cards?

While the worker space is being created, metadata is not accessible. The processing of metadata can only be performed once the worker space is ready.

=== Custom Types

Where can I create new Data Types before I start building a flow?
See link:/design-center/v/1.0/to-manage-data-types#custom-data-types[Custom Data Types]

== Data Transform Questions

=== How can I unassociate a custom data type that has been set up in the Transform without needing to remove the Transform card?

Select the tree root (payload / attributes or variables) in the Transform card, where you already assigned a custom data type. Then click the the option to customize data type. Once the data type editor view is displayed, select clear and cancel. Your tree will be displayed without any custom data type assigned
