= FAQ: Design Center
:keywords: mozart, design center, api designer


== Use Cases

In spite of being simple, the flow designer is still quite powerful, you can build Mule applications that:

* Send and receive requests via HTTP, FTP, create entries in Data Bases, create files.
* Run tasks at regular intervals.
* Orchestrate processes across APIs, such as Salesforce, Twitter, Facebook, GitHub, Zendesk, and many more.
* Send automatic emails.
* Powerfully map fields through link:/mule-user-guide/v/4.0/dataweave[DataWeave] transformations to make virtually any two data formats compatible

Just like with link:/anypoint-studio[Anypoint Studio], the resulting application is meant for deploying to a Mule Runtime, either in link:/runtime-manager/deploying-to-cloudhub[CloudHub] or in a link:/runtime-manager/deploying-to-your-own-servers[customer-managed server].




== Current Limitations


With the flow designer, you currently can't:

* Automatically build out an API backend based on a RAML API definition file
* Deploy directly to a customer-managed server (ie: a runtime outside CloudHub)
* Use TLS for secure protocols such as HTTPS and SMTPS
* Write custom code
* Use advanced functionality such as Spring or Maven
* Create Mule projects that run on a runtime version prior to 4.0.0
* Create flows that reference other flows or subflows. A project may have multiple flows but all of them are independent.


All of these things can be accomplished with link:/anypoint-studio[Anypoint Studio], our more advanced desktop eclipse-based IDE.


== How do I set up an HTTP listener/server?

See link:/connectors/http-to-make-http-request[to Make HTTP Request].


== How do I test my flow?

See link:/design-center/v/1.0/to-debug-a-flow-designer-project[To Debug a Flow Designer Project].

== Are Apps Created With Flow Designer and Deployed to Production Supported by MuleSoft?

Currently, they are not. Flow designer creates projects with Mule runtime version 4.0.0, which is not officially released yet.



Test Connectivity

== Why is the Test button disabled in the card?

The test button is greyed out until the application worker is created.
Connectivity Testing requires that there’s a worker running in the background to use the runtime.
By hovering over the Test button, a tooltip indicating why it’s disabled is displayed.

== Do I need to upload a JDBC driver to connect to Oracle DB?

Yes

== If some of the DBs are listed out of the box, then why do I need to upload drivers?

Due to legal restrictions, it’s necessary that you upload the driver.
Legally, MuleSoft is not allowed to distribute these.

== When using the FTP connector, I'm not able to connect to my computer as host, though I am able to connect with my locally installed Filezilla client.

The Mule runtime your project is running on isn’t be able to connect to your local machine. It’s running in a virtual worker on Cloudhub, its local environment is that virtual machine alone.


Application Status

== How come my app shows up as Paused in the design center but is still green when viewed in the Runtime Manager?

The “Pause” option in flow designer doesn’t pause your CloudHub worker, it just pauses the application that runs in it.



Metadata

== Why do I sometimes not see metadata below the cards?

While the worker space is being created, metadata is not accessible. The processing of metadata can only be performed once the worker space is ready.

== Custom Types

Where can I create new Data Types before start building a flow?
See link:/design-center/v/1.0/to-manage-data-types#custom-data-types[Custom Data Types]

Transform

== How can I unassociate a custom data type that has been set up in the Transform without the need of removing the transform card?

Select the tree root (payload / attributes or variables) in the Transform card, where you already assigned a custom data type. Then click the the option to customize data type
Once the data type editor view is displayed, select clear and cancel. Your tree will be displayed without any custom data type assigned

== Export to Studio & Import from Studio

I only see an ‘Export’ option on flow designer, but no ‘Import’.
For our Beta 1 release, we are supporting only the *export* functionality to Studio.









== Minimum Requirements

The following browsers are supported for running the Design Center

* Chrome (version 54.0.x)
* FireFox (version 50.0.x)

== Known Issues

* Rename a project that has already been created is not fully supported
* Projects that include a *logger* component placed immediately in a flow after a *Tranform* component don't work as expected at runtime
