= FAQ: Design Center
:keywords: mozart, design center, api designer


== Use Cases

In spite of being simple, the flow designer is still quite powerful, you can build Mule applications that:

* Send and receive requests via HTTP, FTP, create entries in Data Bases, create files.
* Run tasks at regular intervals.
* Orchestrate processes across APIs, such as Salesforce, Twitter, Facebook, GitHub, Zendesk, and many more.
* Send automatic emails.
* Powerfully map fields through link:/mule-user-guide/v/4.0/dataweave[DataWeave] transformations to make virtually any two data formats compatible

Just like with link:/anypoint-studio[Anypoint Studio], the resulting application is meant for deploying to a Mule Runtime, either in link:/runtime-manager/deploying-to-cloudhub[CloudHub] or in a link:/runtime-manager/deploying-to-your-own-servers[customer-managed server].

[TIP]
====
In future releases, applications built in the flow designer will also be exportable to Anypoint Studio (the desktop IDE) for configuring advanced settings.

With that feature, you could have a workflow where the desired overall functionality is drafted by line-of-business users on Design Center, and then the project can be exported to Anypoint Studio, where additional details that bring robustness to the application are implemented by specialized integration developers.
====



== Limitations


With the flow designer, you currently can't:

* Automatically build out an API backend based on a RAML API definition file _(coming soon)_
* Deploy directly to a customer-managed server (ie: a runtime outside CloudHub) _(coming soon)_
* Use TLS for secure protocols such as HTTPS and SMTPS _(coming soon)_
* Write custom code
* Used advanced functionality such as Spring or Maven
* Create Mule projects that run on a runtime version prior to 4.0.0



All of these things can be accomplished with link:/anypoint-studio[Anypoint Studio], our more advanced desktop eclipse-based IDE.


////
== What is coming in the next releases?

There are lots of new capabilities coming between now and our GA release:
* Discover APIs in Exchange directly from flow designer as you design your flows
* Support for RAML and auto-discovery of HTTP resources, URI parameters, etc.
* More Mule components including Choice, Flow Ref, Scatter-Gather, Foreach, and other scopes/routers.
* Error handling
* Viewing messages and errors in real time through your applications
* Ability to interactively test flows
////

== How do I set up an HTTP listener/server?

See link:/connectors/http-to-make-http-request[to Make HTTP Request].


== How do I test my flow?

See link:/design-center/v/1.0/to-debug-a-flow-designer-project[To Debug a Flow Designer Project].


== Minimum Requirements

The following browsers are supported for running the Design Center

* Chrome (version 54.0.x)
* FireFox (version 50.0.x)
