= FAQ: Design Center
:keywords: mozart, design center, api designer


== Use Cases

In spite of being simple, the flow designer is still quite powerful, you can build Mule applications that:

* Send and receive requests via HTTP, FTP, create entries in Data Bases, create files.
* Run tasks at regular intervals.
* Orchestrate processes across APIs, such as Salesforce, Twitter, Facebook, GitHub, Zendesk, and many more.
* Send automatic emails.
* Powerfully map fields through link:/mule-user-guide/v/4.0/dataweave[DataWeave] transformations to make virtually any two data formats compatible

Just like with link:/anypoint-studio[Anypoint Studio], the resulting application is meant for deploying to a Mule Runtime, either in link:/runtime-manager/deploying-to-cloudhub[CloudHub] or in a link:/runtime-manager/deploying-to-your-own-servers[customer-managed server].

[TIP]
====
In future releases, applications built in the flow designer will also be exportable to Anypoint Studio (the desktop IDE) for configuring advanced settings.

With that feature, you could have a workflow where the desired overall functionality is drafted by line-of-business users on Design Center, and then the project can be exported to Anypoint Studio, where additional details that bring robustness to the application are implemented by specialized integration developers.
====




== Limitations


With the flow designer, you currently can't:

* Automatically build out an API backend based on a RAML API definition file _(coming soon)_
* Deploy directly to a customer-managed server (ie: a runtime outside CloudHub) _(coming soon)_
* Write custom code
* Used advanced functionality such as Spring or Maven
* Create Mule projects that run on a runtime version prior to 4.0.0

* Use TLS for secure protocols such as HTTPS and SMTPS _(coming soon)_


All of these things can be accomplished with link:/anypoint-studio[Anypoint Studio], our more advanced desktop eclipse-based IDE.



== What is coming in the next releases?

There are lots of new capabilities coming between now and our GA release:
* Discover APIs in Exchange directly from flow designer as you design your flows
* Support for RAML and auto-discovery of HTTP resources, URI parameters, etc.
* More Mule components including Choice, Flow Ref, Scatter-Gather, Foreach, and other scopes/routers.
* Error handling
* Viewing messages and errors in real time through your applications
* Ability to interactively test flows

== How do I set up an HTTP listener/server?

* When creating a flow for the first time, select HTTP as the event source for the flow.
  This will add an HTTP listener for your flow.
* Click "Set up" to set up the HTTP listener
* Set the host to "0.0.0.0". This instructs HTTP to listen on all interfaces.
* Set the port to 8081
* Click Save
* Set the path for the HTTP listener to the URL path you want to listen for requests on, e.g. `/orders`

Once you've configured your flow, deploy your changes to your CloudHub worker by clicking the Run or Update
button on the top.

Then, click on the status bar up top, and select "Copy Link". This will copy the URL to where your applications
is running. You can then combine this url with your URL path. For example, if your URL is
`http://orders.cloudhub.io` and your URL path is `/orders`, your URL will be `http://orders.cloudhub.io/orders`.


== Will the flow designer support implementing APIs?

Of course! We are working on this for a future release. Our initial goal is to enable _consuming_ APIs,
so that users can connect their APIs to other applications, partners, databases and data warehouses.

== How do I test my flow?

# Trigger the event source for your flow. This will differ depending on the event source for your flow:
## If you have a Poll as the event source, you can trigger this by forcing a redeployment of your applications
   by clicking the `Update` button on the top nav bar.
## For an HTTP Listener, copy the URL from the status bar on the top of the screen and clicking "Copy Link".
   Then use your favorite browser or tool to invoke that URL.
# Open up the logs view, by clicking the logs tab on the bottom left of your screen

== Supported Browsers

* Chrome (version 54.0.x)
* FireFox (version 50.0.x)
