= User Access to Design Center



* In order to access the Design Center, your user account must have a `Design Center Developer` role assigned.

* To use all of the features in Design Center and deploy applications to a design environment, your user account must also have a `CloudHub Admin` role for that specific design environment.
* Your Anypoint organization also needs to have at least one CloudHub Design Environment, with 0.2 VCores of capacity available.
* To be able to deploy to production from the editor, your user account also needs a `CloudHub Developer` role specific to the used production environment.
* To be able to create new assets in Anypoint Exchange (such as an API Specification), your user account also needs an `Exchange Contributor` role.


[TIP]
If you need to assign this set of roles to multiple users, you could create a custom role that includes all of the above. Then you only need to assign this single custom role to each.

[NOTE]
Note that roles are assigned per environment. Multiple roles are needed for having the same permissions in separate environments.


////
API permission?

Exchange permissions?


////


== See Also

* link:https://docs.mulesoft.com/access-management/roles[Roles]

* link:https://docs.mulesoft.com/access-management/environments[CloudHub Environments]

* link:/design-center/v/1.0/index[About Design Center]
