= User Access to Design Center



* In order to access the Design Center, your user account must have a `Design Center Developer` role assigned.
<<<<<<< HEAD
* To use all of the features in Design Center and deploy applications to a design environment, your user must also have a CloudHub Admin role for that specific design environment.
* Your Anypoint organization also needs to have at least one CloudHub design environment, with 0.2 VCores of capacity available.
* To be able to deploy to production from the editor, the CloudHub developer role is also needed in the production environment.
=======
* To use all of the features in Design Center and deploy applications to a design environment, your user must also have a CloudHub Developer Role for that specific design environment.
* Your Anypoint organization also needs to have at least one CloudHub Design Environment, with 0.2 VCores of capacity available.
* To be able to deploy to production from the editor, the CloudHub Developer Role is also needed in the production environment.
>>>>>>> nico-crowd

[TIP]
If you need to assign this set of roles to multiple users, you could create a custom role that includes all of the above. Then you only need to assign this single custom role to each.

[NOTE]
Note that roles are assigned per environment. Multiple roles are needed for having the same permissions in separate environments.


////
API permission?

Exchange permissions?


////

<<<<<<< HEAD

== See Also

* link:https://docs.mulesoft.com/access-management/roles[Roles]
* link:https://docs.mulesoft.com/access-management/roles#creating-custom-roles[Creating Custom Roles]
* link:https://docs.mulesoft.com/access-management/environments[CloudHub Environments]
=======
== See Also

* link:https://docs.mulesoft.com/access-management/roles[Roles]

* link:https://docs.mulesoft.com/access-management/environments[CloudHub Environments]

* link:/design-center/v/1.0/index[About Design Center]
>>>>>>> nico-crowd
