= User Access to Design Center



* In order to access the Design Center, your user account must have a `Design Center Developer` role assigned.
* To use all of the features in Design Center and deploy applications to a design environment, your user must also have a link:/access-management/roles[CloudHub developer role] for that specific design environment.
* Your Anypoint organization also needs to have at least one CloudHub design link:/access-management/environments[environment], with 0.2 VCores of capacity available.
* To be able to deploy to production from the editor, the link:/access-management/roles[CloudHub developer role] is also needed in the production environment.

[TIP]
If you need to assign this set of roles to multiple users, you could create a link:/access-management/roles#creating-custom-roles[custom role] that includes all of the above. Then you only need to assign this single custom role to each.

[NOTE]
Note that roles are assigned per environment. Multiple roles are needed for having the same permissions in separate environments.


////
API permission?

Exchange permissions?


////
