= About Accessing Design Center

Here are the requirements for accessing Design Center and using all the features, including deploying apps to a Design environment and publishing designs, such as an API Specification, to Exchange:

* The Design Center Developer role or you need to be the Organization Owner.
+
The user who first signs up for the Anypoint Platform organization is the Organization Owner.
+
* The CloudHub Admin role for the Design environment
* Exchange Contributor
* At least one CloudHub Design Environment, with 0.2 VCores of capacity available, for your Anypoint organization


To deploy to production from Design Center, your user account also needs a CloudHub Developer role to the used for the production environment specifically.

To assign a set of roles to multiple users, you can create a custom role. Roles are assigned per environment. You need to be assigned multiple roles to have the same permissions in separate environments.


== See Also

* link:https://docs.mulesoft.com/access-management/roles[Roles]

* link:https://docs.mulesoft.com/access-management/environments[CloudHub Environments]
