= To Design a Basic RAML API Spec

This procedure covers how to design an API using an example of connecting to the free online REST service JSONPlaceholder. The API consumes the service. For simplicity, the procedure describes an example API that has only one resource: user information. The JSONPlaceholder service returns requests for user information in JSON. 

. In Anypoint Platform, click Design Center, and in Projects click Create.
. In New Project, set up a project:
+
* In Project Name type an arbitrary project name. For example, type Placeholder.
* In Project Type, select API Spec or API Fragment. For this example, select API Spec. 
* Click Create. 
+
Two lines of code based on the title and version of the API appears.
+
. At the root level, enter the optional baseUri and a value. For example:
+
`baseUri: http://jsonplaceholder.typicode.com`
+
. Go to the next line of code, and include the resources in the RAML, formatting each resource as a URI relative to the `baseUri`.
+
For example, create a `/users` resource as shown in the following example:
+
----
...
baseUri: http://jsonplaceholder.typicode.com
/users:
----
+
. Enter the method associated with the resource. For example, specify the GET method to retrieve the information defined in `+http://jsonplaceholder.typicode.com+`. Indent the method name followed by a colon on the lines below the resource name.
+
At this point the API definition looks like this:
+
----
#%RAML 1.0
title: placeholder
version: 1.0.development
baseUri: http://jsonplaceholder.typicode.com
/users:
  get:
    description: Retrieve a list of all the users
----
+
. Include HTTP responses in the RAML for simulating the API. For example, include the Placeholder responses:
+
----
responses:
      200:
        body:
----
+
. Download the `user-example.json` from the "Downloads" section of this document and import the file:
* Select Files > Import.
* Select the type of file to import from the drop-down: RAML, OAS file, OAS spec, and click Choose File to browse to and select the file. For example, select `user-example.json`.
+
. In the RAML code, declare an include file for use as the example:
+
----
...
      application/json:
        example: !include user-example.json
----
. Click Files > Save All.

== Download

* link:_attachments/placeholder.raml[RAML code for this tutorial]
* link:_attachments/user-example.json[Include file], `user-example.json`

