= User Access to Design Center



* In order to access the Design Center, your user account must have a `Design Center Developer` role assigned.
* To use all of the features in flow designer and deploy applications to a test sandbox environment, this user must also have a link:/access-management/roles[CloudHub developer role] for the sandbox environment.
* For that user to be able to deploy to production from the editor, the link:/access-management/roles[CloudHub developer role] is also needed in the production environment.
* To use the flow designer, your Anypoint organization needs to have at least one CloudHub sandbox link:/access-management/environments[environment], with 0.2 VCores of capacity available.


[TIP]
If you need to assign this set of roles to multiple users, you could create a link:/access-management/roles#creating-custom-roles[custom role] that includes all of the above. Then you only need to assign this single custom role to each.

[NOTE]
Note that roles are assigned per environment. Multiple roles are needed for having the same permissions in separate environments.


////
API permission?

Exchange permissions?


////
