= Workflow: Create and Run a Mule Application Project


. link:/design-center/v/1.0/to-create-a-mule-application-project[To Create a Mule Application Project]
+
In Design Center, create a new project and select its environment.

. Place cards


. link:/design-center/v/1.0/to-populate-fields[To Populate Fields]
+
Configure the fields in the cards you placed in your flow, with either fixed values, functions or mappings.

. link:/design-center/v/1.0/to-set-up-connector-configurations[To Set Up Connector Configurations]
+
Connectors must reference a configuration element that holds reusable connection parameters.

. link:/design-center/v/1.0/run-app-desing-env-design-center[To Run an Application in a Design Environment]
+
Push your application to run in a design environment as you build it, incrementally checking that each part works as expected.


. link:/design-center/v/1.0/to-debug-a-mule-project[To Debug a Mule Project]
+
Verify that your application works as expected before promoting it to production.

. link:/design-center/v/1.0/promote-app-prod-env-design-center[To Promote an Application to a Production Environment]
+
Once your app is ready to be used by others, promote it to a production or a test environment.
