= Workflow: Create and Run a Mule Application Project (Design Center)


. link:/design-center/v/1.0/to-create-a-new-project[To Create a Mule Application Project]
+
In Design Center, create a new project and select its environment.

. link:/design-center/v/1.0/arrange-cards-flow-design-center[Arrange Cards to Build a Flow]
+
Place a set of cards in order. Each card represents a component that carries out a task and passes the result to the next component in line.

. link:/design-center/v/1.0/provide-values-fields-design-center[To Provide Values for Fields]
+
Configure the fields in the cards you placed in your flow, with either fixed values, functions or mappings.

. link:/design-center/v/1.0/to-set-up-connector-configurations[To Set Up Connector Configurations]
+
Operations must reference a connector configuration element that holds reusable connection parameters.

. link:/design-center/v/1.0/run-app-design-env-design-center[To Run an Application in a Design Environment]
+
Push your application to run in a design environment as you build it, incrementally checking that each part works as expected.


. link:/design-center/v/1.0/to-debug-a-mule-project[To Debug a Mule Project]
+
Verify that your application works as expected before promoting it to production.

. link:/design-center/v/1.0/promote-app-prod-env-design-center[To Promote an Application to a Production Environment]
+
Once your app is ready to be used by other people, promote it to a production or a test environment.


== See Also

* link:/design-center/v/1.0/index[About Design Center]

* link:/design-center/v/1.0/workflow-create-mapping-ui-design-center[Workflow: Create a Mapping via UI]

* link:/design-center/v/1.0/export-studio-design-center[Export a Project to Anypoint Studio]
