= About Mock When Event Processor
:version-info: 2.0 and later
:keywords: munit, testing, unit testing

The Mock When processor allows you to mock an Event Processor when it matches the defined name and attributes.

For example, you can use the Mock Event processor to mock a POST request with a mocked payload:

[source,xml,linenums]
----
<munit-tools:mock-when processor="http:request">
   <munit-tools:with-attributes>
       <munit-tools:with-attribute attributeName="method" whereValue="#['POST']"/>
   </munit-tools:with-attributes>
   <munit-tools:then-return>
       <munit-tools:payload value="#['mockPayload']"/>
   </munit-tools:then-return>
</munit-tools:mock-when>
----

You can set the `processor` attribute to define the processor to mock and the `with-attribute` element to define the attribute's name and value using atributeName and whereValue respectively. In the example above you are defining a POST method. +
Finally you can configure a then-return element you configure the type of response the mocked processor should return. It could be a payload, a variable, attributes, or even an error. +
In the example above, your mocked HTTP requester is returning 'mockPayload'.

You can apply this structure to any other processor in Mule 4.

For example, you can configure a web service consumer with a specific operation:

[source,xml,linenums]
----
<munit-tools:mock-when processor="wsc:consume">
    <munit-tools:with-attributes>
        <munit-tools:with-attribute attributeName="operation" whereValue="#['operationToMock']"/>
    </munit-tools:with-attributes>
</munit-tools:mock-when>
----

Or mock a logger and configure it to raise an error if the payload is not the expected one:

[source,xml,linenums]
----
<munit-tools:mock-when processor="mule:logger">
    ...
    <munit-tools:then-return>
        <munit-tools:payload value="#['expectedPayload']"/>
        <munit-tools:error typeId="#['MULE:ANY']"/>
        <munit-tools:variables>
            <munit-tools:variable key="#['aVariable']" value="#['aVariableValue']"/>
        </munit-tools:variables>
    </munit-tools:then-return>
    ...
</munit-tools:mock-when>
----



== See Also

* link:/munit/v/2.1/assertion-message-processor[About Assert That Event Processor]
* link:/munit/v/2.1/fail-event-processor[About Fail Event Processor]
* link:/munit/v/2.1/run-custom-event-processor[About Run Custom Event Processor]
* link:/munit/v/2.1/set-message-processor[About Set Event Processor]
* link:/munit/v/2.1/verify-message-processor[About Verify Event Processor]
