= Server Groups

This document, as well as the rest of the documents that make up the link:/mule-management-console/v/3.8/rest-api-reference[Mule Management Console REST API Reference Guide], are a technical reference only. This document does not provide contextual information such as instructions, use cases or scenarios. To understand this document, you should be familiar with http://www.mulesoft.org/documentation/display/MULE3USER/Home[MULE ESB], Server Groups and the link:/mule-management-console/v/3.8/using-the-management-console-api[REST API].

[width="100a",cols="20a,20a,20a,20a,20a"]
|===
|*Assumptions:* |
[width="100a",cols="50a,50a"]
!===
!Host !localhost
!===

|
[width="100a",cols="50a,50a"]
!===
!Port !8080
!===

|
[width="100a",cols="50a,50a"]
!===
!Deployed app !mmc.war
!===

|
[width="100a",cols="50a,50a"]
!===
!User/Password !admin/admin
!=== 
|===

For a detailed description of the format used in this document, consult link:/mule-management-console/v/3.8/rest-api-reference[Content Organization and Conventions].

#*/api/serverGroups*#

[width="100a",cols="33a,33a,33a"]
|===
|#*POST*#
|*CREATE*
|
|===

Creates a new Server Group.

[tabs]
------
[tab,title="STUDIO Visual Editor"]
....

===== JSON

[source, code, linenums]
----
{
  "name": "NewGroupName"
}
----

[width="100",cols="25,25,25,25",options="header"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the Server Group to be created |—
|===

===== Using CURL on Windows
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
 curl --basic -u admin:admin -d "{ \"name\" : \"NewGroupName\" }" --header "Content-Type: application/json" http://localhost:8080/mmc-console-3.7.3/api/serverGroups
----

===== Using CURL on Linux

[source, code, linenums]
----
 curl --basic -u admin:admin -d '{ "name" : "NewGroupName" }" --header 'Content-Type: application/json' http://localhost:8080/mmc-console-3.7.3/api/serverGroups
----

....
[tab,title="Response"]
....

===== JSON
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc-console-3.7.3/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100",cols="25,25,25,25",options="header"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the created Server Group |—
|id |String |MMC ID for the Server Group. |—
|serverCount |String |Number of servers assigned to the Server Group |—
|href |String |Full link to the Server Group resource on which you can perform an operation |—
|===

....
[tab,title="Common Return codes"]
....

[width="100a",cols="50a,50a"]
|===
|*201* |The request has been fulfilled and resulted in a new Server Group being created
|*409* |A server group with that name already exists
|*500* |Error while creating a Server Group
|===

....
[tab,title="MMC version"]
....

[width="100a",cols="50a,50a"]
|===
|From |3.2.2
|===

....
------

[width="100a",cols="33a,33a,33a"]
|===
|#*GET*#
|*LIST ALL*
| 
|===

Lists all available Server Groups.

[tabs]
------
[tab,title="STUDIO Visual Editor"]
....

===== Using CURL
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
 curl --basic -u admin:admin http://localhost:8080/mmc-console-3.7.3/api/serverGroups
----

....
[tab,title="Response"]
....

===== JSON
Note that this syntax is an example. Be sure to find your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the mmc .war file).

[source, code, linenums]
----
{
  "total": 1,
  "data": [
    {
      "name": "NewGroupName",
      "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
      "serverCount": 0,
      "href": "http://localhost:8080/mmc-console-3.7.3/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
    }
  ]
}
----

[width="100",cols="25,25,25,25",options="header"]
|===
|Key |Type |Summary |Child of
|total |Integer |The total number of Server Groups |—
|data |Array |An array of server group types |—
|name |String |The identifying name of the server group |data
|id |String |The server group identifier |data
|serverCount |Integer |The number of servers in the server group |data
|href |String |Full link to the Server Group resource to which you can perform an operation |data
|===

....
[tab,title="Common Return codes"]
....

[width="100a",cols="50a,50a"]
|===
|*200* |The operation was successful
|===

....
[tab,title="MMC version"]
....

[width="100a",cols="50a,50a"]
|===
|From |3.2.2
|===

....
------

#*/api/serverGroups/\{serverGroupId}*#

[width="100a",cols="33a,33a,33a"]
|===
|#*GET*#
|*LIST*
| 
|===

Lists details for a specific Server Group.

[tabs]
------
[tab,title="Request"]
....

===== SYNTAX
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

GET http://localhost:8080/mmc-console-3.7.3/api/serverGroups/{serverGroupId}

[width="100",cols="25,25,25,25",options="header"]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be listed. Invoke LIST ALL to obtain it |—
|===

===== Using CURL
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
 curl --basic -u admin:admin http://localhost:8080/mmc-console-3.7.3/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----

....
[tab,title="Response"]
....

===== JSON
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc-console-3.7.3/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100",cols="25,25,25,25",options="header"]
|===
|Key |Type |Summary |Child of
|name |String |  |—
|id |String |Id of the Server Group |—
|serverCount |Number of servers belonging to the Server Group |  |—
|href |String |Full link to the Server Group resource |—
|===

....
[tab,title="Common Return codes"]
....

[width="100a",cols="50a,50a"]
|===
|*200* |The operation was successful
|*404* |A server with that ID was not found
|===

....
[tab,title="MMC version"]
....

[width="100a",cols="50a,50a"]
|===
|From |3.2.2
|===
....
------

[width="100a",cols="33a,33a,33a"]
|===
|#*PUT*#
|*RENAME*
| 
|===

Renames a specific Server Group.

[tabs]
------
[tab,title="Request"]
....

===== JSON
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc-console-3.7.3/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100",cols="15,10,40,5,5",options="header"]
|===
|Key |Type |Summary |Child of |Required 
|name |String |Name of the created Server Group |— |Yes
|id |String |MMC ID of the Server Group |— |No
|serverCount |String |Number of servers assigned to the Server Group |— |No
|href |String |Full link to the Server Group resource on which you can perform an operation |— |No
|===

Note that the "name" attribute is the only required attribute. The other attributes are include to match the JSON response from an /api/ServerGroups or /api/serverGroups/{serverGroupId} GET request. 

===== Using CURL on Windows
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the mmc .war file).

[source, code, linenums]
----
 curl --basic -u admin:admin -X PUT -d "{\"name\":\"NewName\",\"id\":\"330d9139-4462-4e36-b76c-569776cc3da9\",\"href\": \"http://localhost:8080/mmc-console-3.7.3/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9\",\"serverCount\":0}" --header "Content-Type:application/json" http://localhost:8080/mmc-console-3.7.3/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----

===== Using CURL on Linux
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
curl --basic -u admin:admin -X PUT -d '{"name":"NewName","id":"330d9139-4462-4e36-b76c-569776cc3da9","href": "http://localhost:8080/mmc-console-3.7.3/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9","serverCount":0}' --header 'Content-Type:application/json' http://localhost:8080/mmc-console-3.7.3/api/serverGroups/330d9139-4462-4e36-b76c-569776cc3da9
----

....
[tab,title="Response"]
....

===== JSON
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
{
  "name": "NewGroupName",
  "id": "73d89173-290e-4cb3-a61c-e11deb74767d",
  "serverCount": 0,
  "href": "http://localhost:8080/mmc-console-3.7.3/api/serverGroups/73d89173-290e-4cb3-a61c-e11deb74767d"
}
----

[width="100",cols="25,25,25,25",options="header"]
|===
|Key |Type |Summary |Child of
|name |String |Name of the created Server Group |—
|id |String |MMC ID of the Server Group |—
|serverCount |String |Number of servers assigned to the Server Group |—
|href |String |Full link to the Server Group resource to which you can perform an operation |—
|===

....
[tab,title="Common Return codes"]
....

[width="100a",cols="50a,50a"]
|===
|*200* |The operation was successful
|*500* |Error while renaming a Server Group
|===

....
[tab,title="MMC version"]
....

[width="100a",cols="50a,50a"]
|===
|From |3.2.2
|===

....
------

[width="100a",cols="33a,33a,33a"]
|===
|#*DELETE*#
|*REMOVE*
| 
|===

Removes a specific Server Group.

[tabs]
------
[tab,title="Request"]
....

===== SYNTAX
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

DELETE http://localhost:8080/mmc-console-3.7.3/api/serverGroups/{serverGroupId}

[width="100",cols="25,25,25,25",options="header"]
|===
|Key |Type |Summary |Child of
|serverGroupdId |String |ID of the server group to be removed. Invoke LIST ALL to obtain it |—
|===

===== Using CURL
Note that this syntax is an example. Be sure to replace http://locahost:8080/mmc-console-3.7.3 with your own MMC hostname, port number, and setting for mmc-console-3.7.3 (which is usually the name of the deployed mmc .war file).

[source, code, linenums]
----
 curl --basic -u admin:admin -X DELETE http://localhost:8080/mmc-console-3.7.3/api/serverGroups/37f6cd27-98b3-44b1-97e6-50b75e47f8c1
----

....
[tab,title="Response"]
....

===== JSON

`200 OK`

....
[tab,title="Common Return codes"]
....

[width="100a",cols="50a,50a"]
|===
|*200* |The operation was successful
|===

....
[tab,title="MMC version"]
....

[width="100a",cols="50a,50a"]
|===
|From |3.2.2
|===
....
------
