= Add TLS Certificate to Enable Inbound Traffic on Anypoint Runtime Fabric
:noindex:

When enabling inbound traffic on Anypoint Runtime Manager, a key-certificate pair and a TLS configuration are required. +
These should be stored as secrets in a secret group using Anypoint Secrets Manager.

== Before You Begin

* Make sure you have the *Write Secrets* permission enabled for your Anypoint user.
* A .PEM certificate-key pair for the internal load balancer in Runtime Fabric.

== Procedure

. Navigate to the Secrets Manager from the Anypoint Platform homepage.
. On top of the left navigation bar, select the environment in which you want to create the secret group.
. Select the Create Secret Group button.
. In General, type the name of your secret group. +
. Select Keystore from the left navigation bar.
.. Click the Add Keystore button.
.. In Name, add a name for your keystore. +
This name is the ID that will identify the certificate-key pair.
.. In Type, select PEM
.. In Certificate File, select Choose File and browse in your machine for your .pem certificate file. +
If you are setting this for testing purposes, you can upload a self-signed certificate.
.. In Key File, select Choose  File and browse in your machine for your .pem key file.
.. Click Save.
. Select TLS Context from the left navigation bar.
.. Click the Add TLS Context.
.. In Name, type a name for your TLS Context configuration.
.. In TLS Version, select the TLS verion that your Edge instance supports. +
TLS v1.2 if the default. TLS v1.1 is also supported.
.. In Target, select Anypoint Security.
.. In Keystore, select the name of the keystore you set up in step 5b.
.. Select Save.
. Click on the back arrow on top of the left navigation bar to go back to your secret groups.
. Click Finish on the secret group that you just created to finish the editing process. +
To preserve secrets integrity, all edit sessions must be closed before other users can update the secrets inside the secret group.

== See Also

//_TODO: Add links to the secret manager relevant links (DOCS-2430)
link:/anypoint-runtime-fabric/v/1.0/enable-inbound-traffic[Enable Inbound Traffic to Anypoint Runtime Fabric]
