= Enable Edge for Anypoint Runtime Fabric

Anypoint Edge lets you configure the security required by Runtime Fabric to enable inbound requests to your APIs. +
You cannot expose any endpoints until you configured Edge.

== Before You Begin

* Verify that your account has at least one Anypoint Runtime Fabric installed and configured. See link:/project-worker-cloud/install-about[Install Anypoint Runtime Fabric] for more information.
* Edge requires you to configure TLS context and a certificate for your instance. Make sure you uploaded a keystore and a TLS Context configuration into a secret group using Anypoint Secrets Manager. +
Follow the link:edge-create-certificate-tls[Configure Security for Anypoint Edge Security] steps for a quick overview of this process.
//_COMBAK: Should This task be documented in the Edge documentation?
* Ensure that you have read permissions on the environment where your secret group was created.

== Procedure

. In your Runtime Manager UI, select Runtime Fabrics on the left navigation bar.
. Select the name of your Runtime Fabric to which you want to enable Edge.
. Select the Edge Configuration tab, and select the Enable Edge checkbox.
. Under Basic Configuration:
.. Select the number of replicas you want.
//_COMBAK: Is this the amount of Edge replicas? Why is it important. How to know what's optimum?
. Under TLS Configuration:
.. In the Environment drop-down menu, select the environment of the secret group that stores the Keystore and TLS Context for your Edge instance.
.. In the Secret Group drop-down menu, select the secret group that stores the keystore and TLS Context for your Edge instance.
.. In the TLS Context drop-down menu, select the TLS Context for your Edge instance.
//_TODO: Document Advanced Options Configuration (DOCS-2429).
== Advanced Options


[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
| *Max Connections*
| The maximum amount of simultaneous connections that you are going to allow.

*Default Value*: 512

| *Max Requests Per Connection*
| The Maximum amount of requests per connections that you are allowing. +
Keep in mind that it is resource expensive to take TLS connections up and down. This value lets you reuse a connection.

*Maximum allowed*: 1000 requests per connection.

*Default Value*: 1000

| *Connection Idle Time-out*
| Maximum amount of time that you allow an idle connection. +
This value helps you terminate idle connections that take processing capacity for no reason. +
This value should always be higher than your *read request time-out*. See the option below for more information.

*Default Value*: 15 (seconds)


| *Read Request Time-out*
| Maximum amount of time that you allow your edge endpoint to read a request before terminating it. +
This value lets you terminate requests that send a very large message, or requests whose clients are very slow sending the message. +
This is useful to prevent attacks that try to consume all your connections sending very slow requests. Or to prevent clients that don't close the connection after receiving a response.

If your edge endpoint takes longer than the time set here, it will automatically close the connection. +
To ensure that this feature works as expected, this value should always be lower than the *Connection Idle Time-Out* configured above.

*Default Value*: 10 (seconds)

| *Max Pipeline Depth*
| The maximum amount of requests that you allow from the same client. +
This value lets you define how many simultaneous requests can send a client, before getting a response. +
If a client exceeds this number, the exceeding requests will not be read until the requests in the queue receive a response.

*Default Value*: 10

| *Source IP Header Name* and *Enable Proxy Protocol*
| You can use these configurations if your Runtime fabric is sitting behind a load balancer.

The values to configure here depends on your scenario:

. Your Runtime Fabric is not behind a load balancer. +
:: If your Runtime Fabric is not sitting behind a load balancer, you should not configure these values.
+
*Source IP Header Name*: blank +
*Enable Proxy Protocol*: Unchecked
. Your Runtime Fabric is behind an AWS Load Balancer with a Proxy Protocol configured. +
:: If your Runtime Fabric is deployed behind an AWS load balancer with a proxy protocol enabled, you must select the *Enable Proxy Protocol* checkmark.
+
*Source IP Header Name*: blank +
*Enable Proxy Protocol*: checked
. Your Runtime Fabric is behind a different type of Load Balancer. +
:: If your Runtime Fabric is deployed behind another type of Load Balancer (for example F5, or nginx), you need to provide two common source IP header:
+
* Forwarded: An RFC7239 compliant ip header.
* X-Forwarded-For: Non-standard pre-2014 header containing one or more IPs from a Load Balancer (For example: “192.16.23.34, 172.16.21.36")
+
*Source IP Header Name*: non-blank +
*Enable Proxy Protocol*: unchecked

*Default Value*: blank and unchecked.

|===
//_TODO: Document Logs Options (DOCS-2428).
. Click Deploy. +
The platform displays a "Request to Deployer Sent Successfully" message.
//_COMBAK: What does this mean? What happens next?


== See Also

//_COMBAK: Should we link to Secrets Manager docs?
* Anypoint Secrets Manager
