= Enable Edge for Anypoint Runtime Fabric

Anypoint Edge lets you configure the security required by Runtime Fabric to enable inbound requests to your APIs. +
You cannot expose any endpoints until you configured Edge.

== Before You Begin

* Verify that your account has at least one Anypoint Runtime Fabric installed and configured. See link:/project-worker-cloud/install-about[Install Anypoint Runtime Fabric] for more information.
* Edge requires you to configure TLS context and a certificate for your instance. Make sure you uploaded a keystore and a TLS Context configuration into a secret group using Anypoint Secrets Manager. +
Follow the link:edge-create-certificate-tls[Configure Security for Anypoint Edge Security] steps for a quick overview of this process.
//_COMBAK: Should This task be documented in the Edge documentation?
* Ensure that you have read permissions on the environment where your secret group was created.

== Procedure

. In your Runtime Manager UI, select Runtime Fabrics on the left navigation bar.
. Select the name of your Runtime Fabric to which you want to enable Edge.
. Select the Edge Configuration tab, and select the Enable Edge checkbox.
. Under Basic Configuration:
.. Select the number of replicas you want.
//_COMBAK: Is this the amount of Edge replicas? Why is it important. How to know what's optimum?
. Under TLS Configuration:
.. In the Environment drop-down menu, select the environment of the secret group that stores the Keystore and TLS Context for your Edge instance.
.. In the Secret Group drop-down menu, select the secret group that stores the keystore and TLS Context for your Edge instance.
.. In the TLS Context drop-down menu, select the TLS Context for your Edge instance.
. Under Security Policies:
.. Select a DoS Policy.
.. Select a CAP Policy.
.. Select a ACL Policy.
//_TODO: Document Advanced Options Configuration (DOCS-2429).
//_TODO: Document Logs Options (DOCS-2428).
. Click Deploy. +
The platform displays a "Request to Deployer Sent Successfully" message.
//_COMBAK: What does this mean? What happens next?


== See Also

//_COMBAK: Should we link to Secrets Manager docs?
* Anypoint Secrets Manager
