= Configure Secrets for Your Edge Endpoint
:noindex:

Each instance of  requires a key-certificate pair, and a TLS configuration. +
You need to store these type of secrets in a secret group using Anypoint Secrets Manager.

== Before You Begin

* Make sure you have the Write Secrets permission enabled for your user.
* A .pem certificate-key pair for your Edge instance.

== Procedure

. Go to your Anypoint Platform UI and select *Secrets Manager*.
. On top of the left navigation bar, select the environment in which you want to create the secret group.
. Select the *Create Secret Group* button.
. In General, type the name of your secret group. +
. Select *Keystore* from the left navigation bar.
.. Click the *Add Keystore* button.
.. In Name, add a name for your keystore. +
This name is the ID that will identify the certificate-key pair.
.. In *Type*, select PEM
.. In *Certificate File*, select Choose File and browse in your machine for your .pem certificate file. +
If you are setting this for testing purposes, you can upload a self-signed certificate.
.. In *Key File*, select Choose File and browse in your machine for your .pem key file.
.. Click *Save*.
. Select *TLS Context* from the left navigation bar.
.. Click the *Add TLS Context*.
.. In *Name*, type a name for your TLS Context configuration.
.. In *TLS Version*, select the TLS verion that your Edge instance supports. +
TLS v1.2 if the default. TLS v1.1 is also supported.
.. In *Target*, select Anypoint Security.
.. In *Keystore*, select the name of the keystore you set up in step 5b.
.. Select *Save*.
. Click on the back arrow on top of the left navigation bar to go back to your secret groups.
. Click *Finish* on the secret group that you just created to finish the editing process. +
To preserve secrets integrity, all edit sessions must be closed before other users can update the secrets inside the secret group.

== See Also

//_TODO: Add links to the secret manager relevant links (DOCS-2430)
link:/anypoint-runtime-fabric/v/1.0/configure-edge[Enable an Edge Endpoint for Anypoint Runtime Fabric]
