= Enable Inbound Traffic on Anypoint Runtime Fabric
:noindex:

Anypoint Runtime Fabric includes built-in load balancing capabilities to manage inbound traffic to its Mule applications and API gateways. These capabilities load balance inboud traffic across multiple replicas of your application, which by default reside across different worker VMs. 

[NOTE]
This capability is disabled by default, and will need to be enabled before inbound requests can be received by Mule applications and API gateways.

== Overview

Each controller VM is able to run a replica of the internal load balancer, and is configured to listen on port 443 on each VM. When running multiple controller VMs, it's required to run an external load balancer outside Runtime Fabric to front each of the controller VMs. The external load balancer should support TCP load balancing and be configured with a server pool containing the IP addresses of each controller VM. A health check should also be set up on the external load balancer by listening on port 443. 

This configuration ensures high availability, protects against failures, and gracefully handles automated failover in the event a replica of the internal load balancer were to restart or become evicted and rescheduled on aother controller VM.

[NOTE]
Controller VMs are virtual machines dedicated to run the components which power Anypoint Runtime Fabric.

All inbound traffic entering Anypoint Runtime Fabric is encrypted using TLS. A TLS certificate must be configured before enabling inbound traffic. HTTP requests 
sent to Runtime Fabric will receive a 301 response to redirect to HTTPS on port 443.

== Before You Begin

* Ensure your Anypoint organization has the desired TLS certificate stored in the link:add-tls-secret-manager[Secrets Manager]. If you need to add the TLS certificate, you'll need the following permissions on your user account under the Secrets Manager tab in Access Management. The environemnt field should be scoped to the environment you wish to be associated to the certificate.
** *Manage Secrets Groups*
** *Write Secrets*
** *Read Secrets*
* Your user will also require the *Manage Runtime Fabrics* permission under Runtime Manager, or the *Organization Administrator* role.
* Verify your account has Runtime Fabric installed and registered to your Anypoint organization.
** Visit Anypoint Runtime Manager and click on "Runtime Fabrics" on the left bar to view your registered Runtine Fabrics.

[NOTE]
Use Access Management to manage permissions for Anypoint users. You may need to request permissions from your administrator.

== Procedure

. Under Anypoint Runtime Manager, navigate to *Runtime Fabrics* by clicking on the link in the bottom of the left side bar.
. Select the name of the Runtime Fabric to enable inbound traffic to, and click *Manage* on the right side bar.
. Select the *Edge Configuration* tab and toggle *Enable Edge*.

. Under *Basic Configuration*:
+
.. Set the number of replicas to run the internal load balancer with. A minimum of 2 replicas is required for production environments. These replicas will only run on the controller VMs.
.. Determine the amount of CPU and memory to allocate for each replica of the internal load balancer.+
+
[NOTE]
TLS termination is computationally expensive. Allocate more CPU to increase throughput and decrease latency by allocating more CPU to each replica.
+
. Under *TLS Configuration*:
.. In the Environment drop-down menu, select the environment of where the secrets group was created under in the Secrets Manager.
.. In the Secrets Group drop-down menu, select the secrets group that stores the keystore and TLS Context.
.. In the TLS Context drop-down menu, select the TLS Context to be used for Runtime Fabric.
. Click *Deploy* to begin the deployment on Runtime Fabric.

== Advanced Options


[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
| *Max Connections*
| The maximum amount of simultaneous connections that you are going to allow.

*Default Value*: 512

| *Max Requests Per Connection*
| The Maximum amount of requests per connections that you are allowing. +
Keep in mind that it is resource expensive to take TLS connections up and down. This value lets you reuse a connection.

*Maximum allowed*: 1000 requests per connection.

*Default Value*: 1000

| *Connection Idle Time-out*
| Maximum amount of time that you allow an idle connection. +
This value helps you terminate idle connections that take processing capacity for no reason. +
This value should always be higher than your *read request time-out*. See the option below for more information.

*Default Value*: 15 (seconds)


| *Read Request Time-out*
| Maximum amount of time that you allow your edge endpoint to read a request before terminating it. +
This value lets you terminate requests that send a very large message, or requests whose clients are very slow sending the message. +
This is useful to prevent attacks that try to consume all your connections sending very slow requests. Or to prevent clients that don't close the connection after receiving a response.

If your edge endpoint takes longer than the time set here, it will automatically close the connection. +
To ensure that this feature works as expected, this value should always be lower than the *Connection Idle Time-Out* configured above.

*Default Value*: 10 (seconds)

| *Max Pipeline Depth*
| The maximum amount of requests that you allow from the same client. +
This value lets you define how many simultaneous requests a client can send. +
If a client exceeds this number, the exceeding requests will not be read until the requests in the queue receive a response.

*Default Value*: 10

| *Source IP Header Name* and *Enable Proxy Protocol*
| You can use these configurations if your Runtime fabric is behind a load balancer.

The values to configure here depends on your scenario:

. Your Runtime Fabric is not behind a load balancer. +
:: If your Runtime Fabric is not deployed behind a load balancer, you should not configure these values.
+
*Source IP Header Name*: blank +
*Enable Proxy Protocol*: Unchecked
. Your Runtime Fabric is behind an AWS Load Balancer with a Proxy Protocol configured. +
:: If your Runtime Fabric is deployed behind an AWS load balancer with a proxy protocol enabled, you must select the *Enable Proxy Protocol* checkmark.
+
*Source IP Header Name*: blank +
*Enable Proxy Protocol*: checked
. Your Runtime Fabric is behind a different type of Load Balancer. +
:: If your Runtime Fabric is deployed behind another type of Load Balancer (for example F5, or nginx), you need to provide the source IP header name. Two common source IP headers are:
+
* Forwarded: An RFC7239 compliant ip header.
* X-Forwarded-For: Non-standard pre-2014 header containing one or more IPs from a Load Balancer (For example: “192.16.23.34, 172.16.21.36")
+
*Source IP Header Name*: non-blank +
*Enable Proxy Protocol*: unchecked

*Default Value*: blank and unchecked.

|===

== Logs

You can define the log levels for your edge endpoint. Avaialble values are:

* FATAL
* ERROR
* WARNING
* INFO
* VERBOSE
* DEBUG
* TRACE

Keep in mind that more verbose log levels between "WARNING" and "TRACE" consume more CPU resources for each request, therefore you should raise log levels carefully. +
By default, the activity of all IPs behind your endpoint is being tracked. To help you reduce the vCPU usage when you need to use more verbose log levels, you can configure IP filters. +
If you have a high amount of traffic and you don't want to use a lot of vCPU resources of your node, you can apply a filter so only specific IP addresses are tracked.

This feature is also helpful for reducing the quantity of logs when you need to debug a connection for a specific or limited number of IP addresses.

=== Configuring Logs

. Click the Add Filter.
. in the *IP* field, enter the IP addresses or sub-set of addresses using CIDR notation.
. Select the log level you want for this filter.
. Click OK.

After you finish configuring all these values, click *Deploy*. +
The platform displays a "Request to Deployer Sent Successfully" message.

== See Also


* link:edge-create-certificate-tls[Configure Secrets for Your Edge Endpoint].
