= Enable Inbound Traffic on Anypoint Runtime Fabric
:noindex:

Anypoint Runtime Fabric includes built-in load balancing capabilities to manage inbound traffic to its Mule applications and API gateways. These capabilities load balance inbound traffic across multiple replicas of your application, which by default reside across different worker VMs. 

[NOTE]
This capability is disabled by default, and will need to be enabled before inbound requests can be received by Mule applications and API gateways.

== Overview

Each controller VM is able to run a replica of the internal load balancer, and is configured to listen on port 443 on each VM. When running multiple controller VMs, it's required to run an external load balancer outside Runtime Fabric to front each of the controller VMs. The external load balancer should support TCP load balancing and be configured with a server pool containing the IP addresses of each controller VM. A health check should also be set up on the external load balancer by listening on port 443. 

This configuration ensures high availability, protects against failures, and gracefully handles automated fail-over in the event a replica of the internal load balancer were to restart or become evicted and rescheduled on another controller VM.

[NOTE]
Controller VMs are virtual machines dedicated to run the components which power Anypoint Runtime Fabric.

All inbound traffic entering Anypoint Runtime Fabric is encrypted using TLS. A TLS certificate must be configured before enabling inbound traffic. HTTP requests 
sent to Runtime Fabric will receive a 301 response to redirect to HTTPS on port 443.

== Before You Begin

* Ensure your Anypoint organization has the desired TLS certificate stored in the link:add-tls-secrets-manager[Secrets Manager]. To add a TLS certificate, you'll need the following permissions on your user account under the Secrets Manager tab in Access Management. The environment field should be scoped to the environment you wish to be associated with the certificate.
** *Manage Secrets Groups*
** *Write Secrets*
** *Read Secrets*
* Your Anypoint user will also require the *Manage Runtime Fabrics* permission under Runtime Manager, or the *Organization Administrator* role.
* Verify your account has Runtime Fabric installed and registered to your Anypoint organization.
** Visit Anypoint Runtime Manager and click on "Runtime Fabrics" on the left bar to view your registered Runtime Fabrics.

[NOTE]
Use Access Management to manage permissions for Anypoint users. You may need to request permissions from your administrator.

== Procedure

. Under Anypoint Runtime Manager, navigate to *Runtime Fabrics* by clicking on the link in the bottom of the left side bar.
. Select the name of the Runtime Fabric to enable inbound traffic to, and click *Manage* on the right side bar.
. Select the *Edge Configuration* tab and toggle *Enable Edge*.

. Under *Basic Configuration*:
+
.. Set the number of replicas to run the internal load balancer with. A minimum of 2 replicas is required for production environments. These replicas will only run on the controller VMs.
.. Determine the amount of CPU and memory to allocate for each replica of the internal load balancer.+
+

[NOTE]
TLS termination is computationally expensive. Allocate more CPU to increase throughput and decrease latency by allocating more CPU to each replica.
+
. Under *TLS Configuration*:
.. In the Environment drop-down menu, select the environment of where the secrets group was created under in the Secrets Manager.
.. In the Secrets Group drop-down menu, select the secrets group that stores the keystore and TLS Context.
.. In the TLS Context drop-down menu, select the TLS Context to be used for Runtime Fabric.
+
[NOTE]
If a wildcard certificate is used (for example, \*.example.com), each application URL would take the format of *_{app-name}_.example.com* Otherwise, the application URL will be in the format of *example.com/_{app-name}_*.
+
. Click *Deploy* to begin the deployment on Runtime Fabric. A toast message should appear towards the bottom right area of the page to indicate a successful response. The internal load balancer will begin deployment. When the status of the deployment transitions from _Applying_ to _Applied_, the internal load balancer is successfully deployed and inbound traffic has been enabled.

=== Verification

To resolve the Common Name (CN) to applications deployed on Runtime Fabric, DNS will need to be configured to map the CN to the IP address of the external load balancer or of each controller VM. To test inbound traffic for enabled applications before configuring DNS, a request can be sent using the IP address along with a host header set to the domain. The domain will be based on whether a wildcard certificate was used.

* A CN with a wildcard certificate (`\*.example.com`) will require a request header equal to `Host: {app-name}.example.com`. The following is an example cURL command to verify:
+
====
curl -Lvk -XGET https://{ip-address}/{path} -H 'Host: {app-name}.example.com'
====
+
* A CN without a wildcard certificate (`example.com`) will require a request header equal to `Host: example.com`. The following is an example cURL command to verify:
+
====
curl -Lvk -XGET https://{ip-address}/{app-name}/{path} -H 'Host: example.com'
====

== Next Steps

Runtime Fabric should be configured to route incoming traffic to each enabled application. Below are remaining steps to complete in order for clients to send requests to deployed applications.

* An external load balancer should be set up and configured to load balance HTTPS traffic between each controller VM on Runtime Fabric.
** The advanced options should be reviewed when adding an external load balancer.
* DNS should be configured before the Common Name obtained from the TLS certificate can be used to send requests to applications or API gateways deployed to Runtime Fabric. An "A record" should be added to your DNS provider to map the Common Name to the IP address of the external load balancer or controller VM.
* When deploying new applications or managing existing applications on Runtime Fabric, the _Ingress_ tab will be enabled to determine if inbound traffic should be allowed.

== Advanced Options

[%header%autowidth.spread,cols="a,a"]
|===
|Value |Description
| *Max connections*
| The maximum amount of simultaneous connections to allow.

*Default value*: 512 connections

| *Max requests per connection*
| The maximum number of requests per connections to allow. +
This value will determine how much reuse a connection can allow; consider the amount of CPU required to terminate and re-establish a TLS encrypted connection when lowering this value.

*Maximum allowed*: 1000 requests per connection

*Default value*: 1000

| *Connection idle time-out*
| The maximum amount of time that you allow an idle connection. +
This value helps you terminate idle connections and free up resources. +
This value should always be higher than your *read request time-out*.

*Default value*: 15 seconds

| *Read request time-out*
| The maximum amount of time spent to read a request before it is terminated.+
This value enables requests with large payloads or slow clients to be terminated to keep resources available.+
This helps guard against connection pool exhaustion from slow requests or from clients who don't close connections after a response is sent.

If a Mule application takes longer to respond than this value, the connection will automatically be closed. +
This value should always be lower than the *connection idle time-out* value configured above.

*Default value*: 10 seconds

| *Max pipeline depth*
| The maximum amount of requests to allow from the same client. +
This value defines how many simultaneous requests a client can send. +
If a client exceeds this number, the exceeding requests will not be read until the requests in the queue receive a response.

*Default value*: 10 requests per client

| *Source IP header name* and *enable proxy protocol*
| Set these configurations if Runtime Fabric is behind a load balancer.

The values to configure here depend on your scenario:

. Runtime Fabric is not behind a load balancer. +
::Runtime Fabric is not deployed behind a load balancer, these values should not be configured.
+
*Source IP header name*: blank +
*Enable proxy protocol*: Unchecked
. Runtime Fabric is behind an AWS Load Balancer with a Proxy Protocol configured. +
:: If Runtime Fabric is deployed behind an AWS load balancer with a proxy protocol enabled, you must select the *enable proxy protocol* option.
+
*Source IP header name*: blank +
*Enable proxy protocol*: checked
. Runtime Fabric is behind a non-AWS load balancer. +
:: If Runtime Fabric is deployed behind another type of load balancer, such as F5 or nginx, the source IP header name will need to be provided. Two common source IP headers are:
+
* Forwarded: An RFC7239 compliant IP header.
* X-Forwarded-For: Non-standard pre-2014 header containing one or more IPs from a Load Balancer (For example: “192.16.23.34, 172.16.21.36")
+
*Source IP header name*: non-blank +
*Enable proxy protocol*: unchecked

*Default value*: blank and unchecked.

|===

== Logs

You can define the log levels for the internal load balancer. Available values are the following, in ascending order of least verbosity:

* FATAL
* ERROR
* WARNING
* INFO
* VERBOSE
* DEBUG
* TRACE

The more verbose log levels ("WARNING" to "TRACE") consume more CPU resources for each request; consider this when adjusting the log level and allocating resources for the internal load balancer. +
By default, the activity across all IPs addresses behind your endpoint are logged. To help reduce CPU consumption when using more verbose log levels, IP filters can be added to only log specific IP addresses. +

This feature is also helpful for reducing the quantity of logs when you need to debug a connection for a specific or limited number of IP addresses.

=== Configuring Logs

. Under the Edge Configuration tab in the Manage Runtime Fabrics page, click the "Logs +" link.
. Click the *Add Filter* button.
. In the *IP* field, enter a single IP address or subset of addresses using CIDR notation.
. Select the log level to apply for this IP filter.
. Click *OK*.

After all values have been configured, click the *Deploy* button. +
A toast message should be displayed towards the bottom right area of the page to indicate a successful response. The internal load balancer will redeploy with the new changes.

== See Also


* link:add-tls-secrets-manager[Add a TLS certificate to the Secrets Manager].
