= About Anypoint Runtime Fabric

Anypoint Runtime Fabric is a container service that automates the deployment and orchestration of your Mule applications and gateways. Runtime Fabric runs on customer-managed infrastructure on AWS, Azure, virtual machines (VMs) or bare-metal servers.

Some of the capabilites Anypoint Runtime Fabric provides are the following:

* Isolation between applications by running a separate Mule runtime per application.
* The ability to run multiple versions of the Mule runtime on the same set of resources.
* Scaling applications across multiple replicas.
* Automated application failover capabilities.
* Application management with Anypoint Runtime Manager.

== Architecture

Anypoint Runtime Fabric is composed of a set of VMs, each serving as one of the following roles:

* *Controller* - VMs dedicated for operating Runtime Fabric, including orchestration services, distributed database, load balancing, and services enabling Anypoint Platform management.
* *Worker* - VMs dedicated for running Mule applications and API gateways.

This separation of responsibilities enables the ability to scale the worker VMs based on the number of Mule applications, and to scale the controller VMs based on the frequency of deployments, changes in application state, and amount of inbound traffic. To ensure resources are available to re-schedule and re-deploy applications in the event of a hardware failure, it's recommended to over-provision the number of worker VMs.

By default, the services operating Runtime Fabric are deployed across the controller VMs to avoid a single point of failure in the system.

Anypoint Runtime Fabric uses a set of technologies, including Docker and Kubernetes, which are tuned to work well with the Mule runtime. Knowledge of these technologies are not required to deploy or manage Mules on Runtime Fabric. Managing Runtime Fabric requires the same level of operational and infrastructure-level experience needed to support any system at scale. As always, following best practices and running fire drill scenarios in controlled environments are highly recommended to help prepare for unexpected failures.

[NOTE]
Deployments of non-Mule applications or gateways on Anypoint Runtime Fabric is not supported.

=== Connectivity to Anypoint Cloud Control Plane

Anypoint Runtime Fabric supports deployments of applications using Anypoint Runtime Manager, API gateways using API Manager, and integrates with Anypoint Exchange to store and retrieve related-assets. To enable this, Runtime Fabric establishes a connection to Anypoint Cloud Control Plane. A set of services running on the controller VMs initiate outbound connections to retrieve deployment requests and assets required for application deployment. These services then use the APIs provided by Kubernetes to to d

[NOTE]
Anypoint Runtime Fabric uses the AMQP protocol to connect to Anypoint Cloud Control Plane. Check with your network administrator on enabling outbound connections from your organization's network using this protocol.

== Comparing to Standalone Mule Runtimes

On-premise deployments of Mule applications involve installing a version of the Mule runtime on a server and deploying one or more applications on the server. Each application shares the resources available to the Mule runtime. Other resources such as certificates or database connections can also be shared via domains.

On Anypoint Runtime Fabric, each Mule application and API gateway runs with their own Mule runtime, and in their own container. Each application deployment specifies the amount of resources the container has access to. This enables Mule applications to horizontally scale across VMs without relying on dependencies, and safeguards each application from competing with another's resources on the same VM.