= Install Runtime Fabric on AWS

This topic describes how to install and register Anypoint Runtime Fabric on your AWS account.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware requirements. An operations specialist may be needed to provision the required infrastructure.
====

== Overview
The installation process is divided into the following stages:

. Provision infrastructure
. Set up each VM (operating system, disks)
. Install Runtime Fabric across VMs
. Register the Runtime Fabric
. Add your Mule license key

* To help provision the required infrastructure, a Terraform script (fabric.tf) is included with the installer. It is configured to create a new VPC and run within its own network, but this can be adjusted per your company's requirements by modifying the script.
* By default, the Terraform script also adds public IP addresses to each VM to make it easy to access across environments. This can also be safely removed by adjusting the script.
* The Terraform script requires a set of parameters which will be added to VMs as environment variables. These variables will be consumed by a setup script which will be executed automatically on each VM.
* The setup script performs the following actions:
** Formats and mounts each dedicated disk
** Adds mount entries to /etc/fstab
** Adds iptable rules
** Enables required kernel modules
** Starts the installation
* Each VM will act as one of two roles:
** Controller VMs are dedicated to operate and run Runtime Fabric services. The internal load balancer also runs within these VMs.
** Worker VMs are dedicated to run Mule applications.
* One controller VM will act as a leader during the installation. This VM will download and execute the installer.
* All other VMs download the installer files from the installer VM on port 32009, perform the installation, and join the installer VM to form a cluster.
* During the installation, a set of pre-flight checks will run to verify the minimum hardware, operating system, and network requirements for Runtime Fabric as ./install-sys-reqs.adoc[defined]. If these requirements are not met, the installer will not succeed.

== Download Installer
The installer package includes the necessary scripts and binaries needed to install Runtime Fabric.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Click the installer link to begin the download.
. Once downloaded, unpack the installer using `mkdir installer && tar -zxf /path/to/installer -C installer`

[NOTE]
The extension for the installer is packaged as `tar.gz`. You'll need a utility to unpack tar files.

You'll find a directory named `aws` inside the installer, which contains the following:

* `fabric.tf`: a https://terraform.io/[Terraform] script to provision infrastructure on your AWS account.
* `README.md`: a markdown file containing installation instructions.

== Provision Infrastructure
Use the included Terraform script to easily provision the required hardware and network settings needed to install and operate Runtime Fabric.

[NOTE]
You'll need a https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[key pair] to provision the VMs. This is required to enable secure access to your VMs via SSH (Secure Shell).

You'll need to configure AWS API access in your shell. For example, make sure you have `AWS_ACCESS_KEY`, `AWS_ACCESS_SECRET_KEY`, etc defined. You should be able to run the `aws` cli tool, for example.

=== Variables

* `cluster_name`: name of cluster (e.g. rtf).
* `key_pair`: name of the aws keypair (e.g. my-cluster-key)
* `workers`: number of worker machines to provision. (e.g. 3)
* `controllers`: number of controller machines to provision. (e.g. 3)
* `installer_url`: url of the RTF installation package

_(Optional - will auto-register your cluster to Anypoint platform during provisioning)_

* `registration_org_id`: Anypoint Organization Id (eg `13b68b3c-ce9b-4429-84cf-03646c34dabc`)
* `registration_token`: Anypoint bearer token (eg `bearer 53668b3c-ce9b-4429-84cf-03646c34d796`)
* `node_wait_join_count`: Total number of nodes to wait for before cluster is registered

You can either run `terraform` natively, or via `docker`.

=== With terraform
```
terraform apply \
  -var cluster_name=<cluster-name> \
  -var key_pair=<keypair-name> \
  -var controllers=3 \
  -var workers=3 \
  -var installer_url=<url> \
  -var registration_org_id=<orgid> \
  -var registration_token=<token> \
  -var node_wait_join_count=6 \
  -state=tf-data/rtf.tfstate
```

=== With Docker
```
docker run -v $(pwd):/src -w /src/aws \
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY \
  hashicorp/terraform:0.11.7 init
```

```
docker run -v $(pwd):/src -w /src/aws \
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY \
  hashicorp/terraform:0.11.7 apply \
  -var cluster_name=<cluster-name> \
  -var key_pair=<keypair-name> \
  -var controllers=3 \
  -var workers=3 \
  -var installer_url=<url> \
  -var registration_org_id=<orgid> \
  -var registration_token=<token> \
  -var node_wait_join_count=6 \
  -state=tf-data/rtf.tfstate
```

[NOTE]
This step will install Runtime Fabric across all servers to form a cluster. It may take 15-25 minutes or longer to complete.

=== Monitoring the installation
`cloud-init` executes the Runtime Fabric installation script. As it progresses, it can be monitored by tailing its log file.
```
tail -f /var/log/rtf-init.log
```

When the installation completes successfully, the file `/opt/anypoint/runtimefabric/init-succeeded` is touched.

== Registering Runtime Fabric

After the installation script has completed, you'll need to register Runtime Fabric to Anypoint Runtime Manager.

. Navigate to Runtime Manager, select the Runtime Fabrics tab, and select the "Create Runtime Fabric" button.
. Near the registration script, choose a name for your Runtime Fabric. Copy the script to your clipboard.
. SSH onto the installer machine (first controller) running Runtime Fabric and paste and run the registration script. This process may take up to 5 minutes to complete.
. After the script completes the registration process, Runtime Fabric should be registered and visible on the "Runtime Fabrics" tab in Runtime Manager.
