= Install Runtime Fabric on a Virtual Machine

This topic describes how to install and register Anypoint Runtime Fabric on a virtual machine in a user-hosted data center. 

== Before You Begin

Before provisioning your environment and installing Anypoint Runtime Fabric, perform the following:

* Ensure that you have installed a utility that can uncompress `.tar` files.
* Ensure that your infrastructure meets the minimum hardware requirements as described in link:/anypoint-runtime-fabric/v/1.0/install-sys-reqs[Verify System Requirements for Anypoint Runtime Fabric].
* Ensure that you have enabled the ports required to run the installas as described in link:/anypoint-runtime-fabric/v/1.0/install-port-reqs[Network Port Requirements for Anypoint Runtime Fabric].

== Download Installer

The installer package includes the necessary scripts and binaries needed to install Runtime Fabric.

. Log in to Anypoint Platform and navigate to Runtime Manager.
. On the left navigation pane, select *Runtime Fabrics*.
. Click *Create Runtime Fabric*.
. Click the installer link to download the installer.
. When the download finishes, unpack the installer file to view its contents.

[NOTE]
The extension for the installer is packaged as `tar.gz`.

The contents inside the installation binary include the following:

* `auto_installer.py`: the installation bootstrap script.
* `controller-init.sh`: a script to configure each VM serving as a controller.
* `worker-init.sh`: a script to configure each VM serving as a worker.
* `README.md`: a markdown file containing instructions to aid with installation.

== Running the Command Line Installation

. Copy and run the `controller-init.sh` script, in privileged mode, to each VM acting as a controller. The script accepts 2 parameters which are required. The first parameter describes the disk block device path for _Disk 1_, while the second parameter describes the same for _Disk 2_. After running the script, you may be prompted to accept the changes. 
+
----
chmod +x setup.sh
sudo ./setup.sh /dev/sdc /dev/sdd
----
+
[NOTE]
To help identify the paths to your block devices, use `lsblk`.
+

. Copy the `installer.tar.gz` binary, the `auto-installer.py` script, and your private key to a single server or virtual machine. The installer URL can be found by navigating to Anypoint Runtime Manager, selecting the *Runtime Fabric* tab, and clicking the *Create Runtime Fabric* button.
+
----
wget <installer_URL> -O installer.tar.gz
----

. Move the `installer.tar.gz` binary to the user's home directory.
+
----
mv installer.tar.gz ~
----
+
[NOTE]
Ensure the installation binary file name is equal to `installer.tar.gz`.
+

. Move `auto-installer.py` to a temp directory, and change to that directory.
+
----
mv auto-installer.py /tmp/
cd /tmp/
----

. Run the following command on the same server or virtual machine to start the `auto-installer.py` script. This script requires Python 2.7 to run. The private and public IP addresses, admin username for the servers, the block device path for _Disk 2_, and the private ssh key pair should be filled in as environment variables before running.
+
----
PRIVATE_IPS="<private-ip-1> <private-ip-2> <private-ip-3> \
 PUBLIC_IPS="<public-ip-1> <public-ip-2> <public-ip-3>" \
 FLAVOR=three \
 USER=<username> \
 KEY=</path/to/private/ssh/key> \
 DOCKER_DEVICE=</dev/sdd> \
 python auto_installer.py
----
+
Using the following values:
+
[%header,cols="2*a"]
|===
|Parameter | Description
|PRIVATE_IPS | Specifies the private IP address for each server.
|PUBLIC_IPS | Specifies the public IP address for each server.
|FLAVOR | Specifies the number of nodes in your cluster. Valid values are: `one`, `three`, and `six`.
|USER | Specifies the username on the servers.
|KEY | Specifies the path for the private ssh key pair.
|DOCKER_DEVICE | Specifies the path to _Disk 2_ device on each server. Use `lsblk` to list the available devices.
|===
+
[NOTE]
This step will install the Project Worker Cloud appliance across all servers to form a cluster. It may take 10-15 minutes or longer to complete.

== Registering the Project Worker Cloud appliance

After the installation script has completed, you must register Runtime Fabric to Anypoint Runtime Manager.

. Navigate to Runtime Manager, select the *Runtime Fabric* tab, then select *Create Runtime Fabric*.
. Choose a name for your Runtime Fabric.
. Copy the script to your clipboard.
. SSH into one of the virtual machines running Runtime Fabric and paste and run the registration script. This process may take up to 15 minutes to complete.
. After the script completes the registration process, Runtime Fabric should be registered and visible on the *Runtime Fabric* tab in Runtime Manager.

== Known Issues

The following are issues which may be present during the beta program for Project Worker Cloud. 

* The `region` parameter of the registration script may need to be manually set to `us-east-1`. 
* In Runtime Manager, stopping an application deployed to a Project Worker Cloud appliance will not alter its state.
* Applications must be uploaded to Anypoint Exchange before they can be deployed to Project Worker Cloud.
* When deleting a Project Worker Cloud appliance which has been disconnected from the Anypoint Control Plane, you may encounter an error asking to remove all applications. Reach out to the Product/Engineering team to help resolve this issue.
