= Install Runtime Fabric on AWS
:noindex:

This topic describes how to install and register Anypoint Runtime Fabric on your AWS account.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware, operating system, and networking requirements. An operations and networking specialist may be needed to provision the required infrastructure.
====

== Before you Begin

Prepare the necessary steps and understand the core conepts prior to installing Runtime Fabric. In addition, ensure the following criteria have been met before beginning the installation:

* Your AWS user has access to create EC2 instances, Disks, VPCs, Security Groups.
* Your AWS account has enough quota for the infrastructure being provisioned.
* If your organization does not allow using public IPs, you may need to pass in an existing VPC in the Terraform. See [here] for instructions.

== Download Installer
The installer package includes the necessary scripts and binaries needed to install Runtime Fabric.

[NOTE]
Ensure your Anypoint user account has the Manage Runtime Fabrics permission or the Organization Administrators role.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Click the installer link to begin the download.
. Once downloaded, unpack the installer.
.. On Mac or Linux, run: `mkdir -p installer && tar -zxf /path/to/installer -C ./installer`.
.. On Windows, use your favorite archive utility to unpack to a new directory named `installer`.

[NOTE]
The extension for the installer is packaged as `tar.gz`. You'll need a utility to unpack tar.gz files.

Inside the `installer` directory, you'll find a directory named `aws` which contains the following:

* `fabric.tf`: a https://terraform.io/[Terraform] script to provision infrastructure on your AWS account.
* `README.md`: a markdown file containing installation instructions.

== Provision Infrastructure and Install
Run the included Terraform script to easily provision the required hardware and network settings to install and operate Runtime Fabric.

[NOTE]
Your AWS account will need access to create EC2 instances, VPCs, Security Groups, and disks. A https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[key pair] is also required to provision the instances. This is required to enable secure access to your VMs via SSH (Secure Shell).

To run the Terraform script, AWS API access should be configured in your terminal. Define your values for `AWS_ACCESS_KEY`, `AWS_ACCESS_SECRET_KEY`, or other environment variables (such as `AWS_SESSION_TOKEN`) to access the AWS API for your account. As a test, you should be able to run the `aws-cli` tool, if installed on your machine.

=== Variables to Define
[%header,cols="3*a"]
|===
|Variable | Description | Example
| `cluster_name` | The name for your Runtime Fabric cluster. | rtf-aws
| `key_pair` | The name of the keypair in the AWS region you’re deploying to. | my-keypair
| `region` | The AWS region you're deploing to. | us-east-1
| `installer_url` | The URL of the Runtime Fabric installation package. Navigate to the _Create Runtime Fabrics_ page in Anypoint Runtime Manager to copy the link for the installer download. | https://s3.amazonaws.com/runtimefabric/...
| `controllers` | The number of controller VMs to provision. | 3
| `workers` | The number of worker VMs to provision. | 3
| `node_wait_join_count` | The number of VMs to have joined before completing the installer. | 6
|===

=== Running Terraform

There are a couple of ways to run the Terraform script:
* If you have Terraform installed on your machine, use the native terraform method.
** Check the version of terraform installed is `0.11.7` or higher by running `terraform --version` on your terminal.
* If you do not have Terraform installed, but have Docker installed, use the Docker method.
* If you do not have Terraform or Docker installed, pick your most comfortable option. 

[NOTE]
Regardless of which option you choose to run the Terraform, keep the state file (`tf-data/rtf.tfstate`) in a safe place. You'll need to reference it when making changes to this deployment.

==== Run using Native Terraform

. Copy the script below in a text editor to easily define the variables.
+
----
terraform apply \
  -var cluster_name=<cluster-name> \
  -var key_pair=<keypair-name> \
  -var region=<aws-region> \
  -var installer_url=<url> \
  -var controllers=3 \
  -var workers=3 \
  -var node_wait_join_count=6 \
  -state=tf-data/rtf.tfstate
----
+
. Use the Variables to Define table above to help define the variables.
. Ensure your terminal has access to the `AWS_ACCESS_KEY`, `AWS_ACCESS_SECRET_KEY`, and other related AWS environment variables (such as `AWS_SESSION_TOKEN`) as expected by Terraform.
.. If you experience an error related to AWS authorization, ensure you're using the same terminal window for verifying the variables and running the Terraform command.
. Verify your present working directory is the `installer` directory, and not the `aws` directory.
.. You should be able to see the `aws` directory when running `ls` or `dir` in your terminal.
. Run the script.

==== Run using Docker

This method is preferred if you don't have Terraform installed on your machine. 

. Initialize the script:
+
----
docker run -v $(pwd):/src -w /src/aws \
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN \
  hashicorp/terraform:0.11.7 init
----

. Provision the infrastructure:
----
docker run -v $(pwd):/src -w /src/aws \
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY \
  hashicorp/terraform:0.11.7 apply \
  -var cluster_name= \
  -var key_pair= \
  -var installer_url= \
  -var controllers=3 \
  -var workers=3 \
  -var node_wait_join_count=6 \
  -state=tf-data/rtf.tfstate
----

[NOTE]
This step will install Runtime Fabric across all servers to form a cluster. It may take 15-25 minutes or longer to complete.

=== Monitor the Installation

`cloud-init` executes the Runtime Fabric installation script. As it progresses, it can be monitored by tailing its log file.

. SSH onto the installer VM.
. Tail the log output file.
+
----
tail -f /var/log/rtf-init.log
----

[NOTE]
You can tail the log on each VM to view its progress.

When the installation completes successfully, the file `/opt/anypoint/runtimefabric/init-succeeded` is touched.
To verify Runtime Fabric has been set up, SSH onto one of the controller VMs and run `gravity status`. If you see `healthy` next to each VM created during the installation, Runtime Fabric has installed successfully and is ready to be registered.

== Registering Runtime Fabric

After the installation script has completed, you'll need to register Runtime Fabric to Anypoint Runtime Manager.

. Navigate to Runtime Manager, select the Runtime Fabrics tab, and select the "Create Runtime Fabric" button.
+
[NOTE]
If you have this page open, refresh the page to ensure you're currently logged into Anypoint Platform.

. On Step 3, choose a name for your Runtime Fabric, and copy the script to your clipboard.
. SSH onto the installer VM and paste and run the registration script. This process may take up to 5 minutes to complete.
. After the script completes the registration process, Runtime Fabric should be registered and visible on the "Runtime Fabrics" tab in Runtime Manager.
. You'll see details for how to access the administration portal for Runtime Fabric. Store these details in a safe place for reference.
