= Install a Runtime Fabric on Amazon Web Services (AWS)

This topic describes how to install and register Anypoint Runtime Fabric on your AWS account. It also describes how to provision the infrastructure required to run Anypoint Runtime Fabric.

== Before You Begin

Before provisioning your environment and installing Anypoint Runtime Fabric, perform the following:

* Ensure that your infrastructure meets the minimum hardware requirements as described in link:/anypoint-runtime-fabric/v/1.0/install-sys-reqs[Verify System Requirements for Anypoint Runtime Fabric].
* Ensure that you have enabled the ports required to run the installas as described in link:/anypoint-runtime-fabric/v/1.0/install-port-reqs[Network Port Requirements for Anypoint Runtime Fabric].

== Download Installer

The installer package includes the necessary scripts and binaries needed to install Runtime Fabric.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Click the installer link to begin the download.
. Once downloaded, unpack the installer file to view its contents.

[NOTE]
The extension for the installer is packaged as `tar.gz`. You must have a utility to unpack tar files.

The uncompressed installer contains a directory named `azure`. This directory contains the following:

* `resource-template.json`: the Azure Resource Template used to provision infrastructure on your Azure account.
* `auto_installer.py`: the installation bootstrap script.
* `README.md`: a markdown file containing instructions to install on Azure.