= Manually Install Runtime Fabric

This topic describes how to install and register Anypoint Runtime Fabric on VMs hosted in your data center.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware requirements. An operations specialist may be needed to provision the required infrastructure.
====

== Download Installer
The installer package includes the necessary scripts and binaries needed to install Runtime Fabric.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Click the installer link to begin the download.
. Once downloaded, unpack the installer file to view its contents.

[NOTE]
The extension for the installer is packaged as `tar.gz`. You'll need a utility to unpack tar files.

The contents inside the installation binary include the following:

* `auto_installer.py`: the installation bootstrap script.
* `controller-init.sh`: a script to configure each VM serving as a controller.
* `worker-init.sh`: a script to configure each VM serving as a worker.
* `README.md`: a markdown file containing instructions to aid with installation.

== Running the Command Line Installation

. Copy and run the `controller-init.sh` script, in proviledged mode, to each VM acting as a controller. The script accepts 2 parameters which are required. The first parameter describes the disk block device path for _Disk 1_, while the second parameter describes the same for _Disk 2_. After running the script, you may be prompted to accept the changes. 
+
----
chmod +x setup.sh
sudo ./setup.sh /dev/sdc /dev/sdd
----
+
[NOTE]
To help identify the paths to your block devices, use `lsblk`.
+

. Copy the `installer.tar.gz` binary, the `auto-installer.py` script, and your private key to a single server or virtual machine. The installer URL can be found by navigating to Anypoint Runtime Manager, selecting the *Runtime Fabric* tab, and clicking the *Create Runtime Fabric* button.
+
----
wget <installer_URL> -O installer.tar.gz
----

. Move the `installer.tar.gz` binary to the user's home directory.
+
----
mv installer.tar.gz ~
----
+
[NOTE]
Ensure the installation binary file name is equal to `installer.tar.gz`.
+

. Move `auto-installer.py` to a temp directory, and change to that directory.
+
----
mv auto-installer.py /tmp/
cd /tmp/
----

. Run the following command on the same server or virtual machine to start the `auto-installer.py` script. This script requires Python 2.7 to run. The private and public IP addresses, admin username for the servers, the block device path for _Disk 2_, and the private ssh key pair should be filled in as environment variables before running.
+
----
PRIVATE_IPS="<private-ip-1> <private-ip-2> <private-ip-3> \
 PUBLIC_IPS="<public-ip-1> <public-ip-2> <public-ip-3>" \
 FLAVOR=three \
 USER=<username> \
 KEY=</path/to/private/ssh/key> \
 DOCKER_DEVICE=</dev/sdd> \
 python auto_installer.py
----
+
Using the following values:
+
[%header,cols="2*a"]
|===
|Parameter | Description
|PRIVATE_IPS | Specifies the private IP address for each server.
|PUBLIC_IPS | Specifies the public IP address for each server.
|FLAVOR | Specifies the number of nodes in your cluster. Valid values are: `one`, `three`, and `six`.
|USER | Specifies the username on the servers.
|KEY | Specifies the path for the private ssh key pair.
|DOCKER_DEVICE | Specifies the path to _Disk 2_ device on each server. Use `lsblk` to list the available devices.
|===
+
[NOTE]
This step will install the Project Worker Cloud appliance across all servers to form a cluster. It may take 10-15 minutes or longer to complete.

== Registering the Project Worker Cloud appliance

After the installation script has completed, you'll need to register the Project Worker Cloud appliance to Anypoint Runtime Manager.

. Navigate to Runtime Manager, select the Worker Clouds tab, and select the Create Worker Cloud button.
. On Step 3, choose a name for your Project Worker Cloud appliance. Copy the script to your clipboard.
. On a server running the appliance, paste and run the registration script with a privledged user.
. After the script completes the registration process, your appliance should be registered and visible on the Worker Clouds tab in Runtime Manager.
+
[NOTE]
A new sandbox environment must be created with the name `Worker-Cloud-beta` in order to deploy applications to the Project Worker Cloud appliance. This is a limitation placed during the beta program.

== Known Issues

The following are issues which may be present during the beta program for Project Worker Cloud. 

* The `region` parameter of the registration script may need to be manually set to `us-east-1`. 
* In Runtime Manager, stopping an application deployed to a Project Worker Cloud appliance will not alter its state.
* Applications must be uploaded to Anypoint Exchange before they can be deployed to Project Worker Cloud.
* When deleting a Project Worker Cloud appliance which has been disconnected from the Anypoint Control Plane, you may encounter an error asking to remove all applications. Reach out to the Product/Engineering team to help resolve this issue.
