= Manually Install Runtime Fabric

This topic describes how to install and register Anypoint Runtime Fabric on VMs hosted in your data center.

== Prerequisites
. Provision the necessary hardware for the controller VMs and worker VMs as outlined in the system requirements page.
. Ensure the required disks are listed as a block device for each VM. The disks do not need to be mounted or formatted.
. Runtime Fabric supports RedHat v7.4 or CentOS v7.4. Each VM should be running a compatible operating system.
. The necessary ports should be opened as described on the port requirements page.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware requirements. An operations specialist may be needed to provision the required infrastructure.
====

== Download Installer
The installer package includes the necessary scripts and binaries needed to install Runtime Fabric.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Click the installer link to begin the download.
. Once downloaded, unpack the installer using `mkdir installer && tar -zxf /path/to/installer -C installer`

You'll find a directory named `manual` inside the installer, which contains the following:

* `generate-configs.sh`: a script to configure each VM serving as a worker.
* `README.md`: a markdown file containing instructions to aid with installation.

== Prepare VMs for Installation
The initialization process perform the following actions:

* Formats the dedicated disks.
* Mounts the dedicated disks to the appropriate path.
* Sets iptable rules.
* Enables the required kernel modules.
* Enables and reloads system services.

To begin, we will run a configuration tool. This aids in generating the properties required on each machine.

=== Required environment variables:
[%header,cols="2*a"]
|===
|Parameter | Description
| `RTF_INSTALLER_IP` | ip address of the installer node
|===

=== Optional environment variables:
[%header,cols="3*a"]
|===
|Parameter | Description | Default
| `RTF_DOCKER_DEVICE` |  Block device path for the dedicated disk used for etcd, supporting 1000 provisioned IOPS.     | `/dev/xvdc`
|`RTF_ETCD_DEVICE` |  Block device path for the dedicated disk used for Docker, supporting 3000 provisioned IOPS.   | `/dev/xvdb`
| `RTF_TOKEN` |               Token used by nodes to auto-join the cluster. | my-cluster-token
| `RTF_INSTALL_PACKAGE_URL` | URL to download the installation package from. 

If this is not specified, the installer will expect you to manually copy the installation package to `/opt/anypoint/runtimefabric/installer.tar.gz` |
| `RTF_NAME` |                Name to give this cluster. | runtime-fabric
| `RTF_NODE_WAIT_COUNT` |     Number of nodes expected to form the cluster. | 6
| `RTF_AUTH_TOKEN` |          Anypoint authentication to register this cluster.

Example: `bearer 53668b3c-ce9b-4429-84cf-03646c34d796`| 
| `RTF_ORG_ID` |              Anypoint organization id to register this cluster to. |
| `RTF_REGION` |              Region to register this cluster. | us-east-1
|===

[NOTE]
To help identify the block device paths to your disks, use `lsblk`.

Please provide any overrides to the defaults listed above, then execute `generate-configs.sh`:
----
RTF_INSTALLER_IP=1.2.3.4 RTF_NAME=my-name  generate-configs.sh
----

The output is a configuration snippet for the `installer`, `controller`, and `worker` machine roles. Execute the snippet on each machine based on its desired role.

Transfer the `installer/scripts/init.sh` file to `/opt/anypoint/runtimefabric` on each machine:
```
scp installer/scripts/init.sh <user>@<machine-ip>:/opt/anypoint/runtimefabric
```

1. Run the script in privileged mode, on the `installer` node:
----
sudo /opt/anypoint/runtimefabric/init.sh
----

2. Once the installer machine has successfully completed its checks and is running the installation process, run the init script in privileged mode on all the other nodes. This can be done concurrently on all the nodes.
----
sudo /opt/anypoint/runtimefabric/init.sh
----

[NOTE]
This step will install Runtime Fabric across all VMs to form a cluster. It may take 15-25 minutes or longer to complete.

When the process is completed, you will have a Runtime Fabric instance registered in your Anypoint environment. 

== Associate Environments to Runtime Fabric

Before using your Runtime Fabric, you must associate it with one or more environemnts.

. Navigate to Runtime Manager, select the Runtime Fabric tab, then select the Runtime Fabric based on the name used during registration.
. On the Environments tab, select the environemnt you want to associate with this Runtime Fabric and click Add.
. Click Apply to confirm the changes.
