= Install Runtime Fabric on AWS

This topic describes how to install and register Anypoint Runtime Fabric on your AWS account.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware, operating system, and networking requirements. An operations and networking specialist may be needed to provision the required infrastructure.
====

== Before you Begin

Prepare the necessary steps and understand the core concepts prior to installing Runtime Fabric. In addition, ensure the following criteria have been met before beginning the installation:

* Review the link:./installation/[installation details] to ensure you're ready to install Runtime Fabric.
* Your AWS user has access to create EC2 instances, Disks, VPCs, Security Groups.
* Your AWS account has enough quota for the infrastructure being provisioned.
* If your organization does not allow using public IPs, you may need to pass in an existing VPC in the Terraform script. 

== Download Script

The installer script ZIP file includes the necessary scripts needed to install Runtime Fabric.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Click the "Download files" link.
. Once downloaded, unzip the `rtf-install-scripts-\*.zip` file.

You'll find a directory named `aws` inside the installer which contains the following:

* `fabric.tf`: a https://terraform.io/[Terraform] script to provision infrastructure on your AWS account.
* `README.md`: a markdown file containing installation instructions.

== Provision Infrastructure
Use the included Terraform script to easily provision the required hardware and network settings needed to install and operate Runtime Fabric.

[NOTE]
You'll need a https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[key pair] to provision the VMs. This is required to enable secure access to your VMs via SSH (Secure Shell).

You'll need to configure AWS API access in your shell. For example, make sure you have `AWS_ACCESS_KEY`, `AWS_ACCESS_SECRET_KEY`, etc. defined. You should be able to run the `aws` CLI tool, for example.

To run the Terraform script, AWS API access should be configured in your terminal. Define your values for `AWS_ACCESS_KEY`, `AWS_ACCESS_SECRET_KEY`, or other environment variables (such as `AWS_SESSION_TOKEN`) to access the AWS API for your account. As a test, you should be able to run the `aws-cli` tool, if installed on your machine.

=== Variables to Define

Some of the values for the variables below are available on the Install Runtime Fabric page on Anypoint Runtime Manager.

[%header,cols="3*a"]
|===
|Variable | Description | Example
| `cluster_name` | The name for your Runtime Fabric cluster. | rtf-aws
| `key_pair` | The name of the keypair in the AWS region you’re deploying to. | my-keypair
| `enable_public_ips` | Provision public IP addresses for each VM. | false
| `registration_org_id` | The ID for your Anypoint organization, available on the Create Runtime Fabrics page. | None
| `registration_token` | An active Bearer token of your Anypoint user, available on the Create Runtime Fabrics page. | None
| `region` | The AWS region you're deploying to, available on the Create Runtime Fabrics page. | us-east-1
| `installer_url` | The URL of the Runtime Fabric installation package. | https://s3.amazonaws.com/runtimefabric/...
| `controllers` | The number of controller VMs to provision. | 3
| `workers` | The number of worker VMs to provision. | 3
| `node_wait_join_count` | The number of VMs to have joined before completing the installer. | 6

|===

=== Running Terraform

There are a couple of ways to run the Terraform script:
* If you have Terraform installed on your machine, use the native terraform method.
** Check the version of terraform installed is `0.11.7` or higher by running `terraform --version` on your terminal.
* If you do not have Terraform installed, but have Docker installed, use the Docker method.
* If you do not have Terraform or Docker installed, pick your most comfortable option. 

[NOTE]
Regardless of which option you choose to run the Terraform, keep the state file (`tf-data/rtf.tfstate`) in a safe place. You'll need to reference it when making changes to this deployment.

==== Run using Native Terraform

. Copy the script below in a text editor to easily define the variables.
+
----
terraform apply \
  -var cluster_name= \
  -var key_pair= \
  -var region= \
  -var installer_url=> \
  -var controllers=3 \
  -var workers=3 \
  -var installer_url= \
  -var registration_org_id=> \
  -var registration_token= \
  -var node_wait_join_count=6 \
  -state=tf-data/rtf.tfstate
----
+
. Use the Variables to define table above to help define the variables.
. Ensure your terminal has access to the `AWS_ACCESS_KEY`, `AWS_ACCESS_SECRET_KEY`, and other related AWS environment variables (such as `AWS_SESSION_TOKEN`) as expected by Terraform.
.. If you experience an error related to AWS authorization, ensure you're using the same terminal window for verifying the variables and running the Terraform command.
. Verify your present working directory is the `installer` directory, and not the `aws` directory.
.. You should be able to see the `aws` directory when running `ls` or `dir` in your terminal.
. Run the script.

==== Run using Docker

This method is preferred if you don't have Terraform installed on your machine. 

. Initialize the script:
+
----
docker run -v $(pwd):/src -w /src/aws \
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN \
  hashicorp/terraform:0.11.7 init
```

```
docker run -v $(pwd):/src -w /src/aws \
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY \
  hashicorp/terraform:0.11.7 apply \
  -var cluster_name= \
  -var key_pair= \
  -var installer_url= \
  -var controllers=3 \
  -var workers=3 \
  -var installer_url=<url> \
  -var registration_org_id=<orgid> \
  -var registration_token=<token> \
  -var node_wait_join_count=6 \
  -state=tf-data/rtf.tfstate
```

[NOTE]
This step will install Runtime Fabric across all servers to form a cluster. It may take 15-25 minutes or longer to complete.

=== Monitoring the installation
`cloud-init` executes the Runtime Fabric installation script. As it progresses, it can be monitored by tailing its log file.
```
tail -f /var/log/rtf-init.log
----

[NOTE]
You can tail the log on each VM to view its progress.

When the installation completes successfully, the file `/opt/anypoint/runtimefabric/init-succeeded` is touched.

== Registering Runtime Fabric

After the installation script has completed, you'll need to register Runtime Fabric to Anypoint Runtime Manager.

. Navigate to Runtime Manager, select the Runtime Fabrics tab, and select the "Create Runtime Fabric" button.
. Near the registration script, choose a name for your Runtime Fabric. Copy the script to your clipboard.
. SSH onto the installer machine (first controller) running Runtime Fabric and paste and run the registration script. This process may take up to 5 minutes to complete.
. After the script completes the registration process, Runtime Fabric should be registered and visible on the "Runtime Fabrics" tab in Runtime Manager.
 