= Install Anypoint Runtime Fabric

Anypoint Runtime Fabric is a container service built for running Mule applications and API gateways on a set of VMs. The installation procedure has been optimized to require minimal user intervention in most cases. There are important configuration steps required which do require input after the installation has completed.

=== Overview
Setting up Runtime Fabric can be divided into the following steps:

. Provision and set up infrastructure
. Install & Register Runtime Fabric across VMs
. link:/anypoint-runtime-fabric/v/1.0/configure-log-forwarding.html[Configure log forwarding]
. link:/anypoint-runtime-fabric/v/1.0/configure-alerting.html[Configure alerting]
. link:/anypoint-runtime-fabric/v/1.0/associate-environments.html[Associate Runtime Fabric to environments]
. link:/anypoint-runtime-fabric/v/1.0/enable-inbound-traffic.html[Enable inbound traffic]

==== Infrastructure

Anypoint Runtime Fabric enables 

[NOTE]
link:/anypoint-runtime-fabric/v/1.0/install-sys-reqs[Verify System Requirements for Anypoint Runtime Fabric] before starting installation.


The installation uses the included Terraform script to combine the first three steps. Below are more details on each step of the installation process:

* To help provision the required infrastructure, a Terraform script (`fabric.tf`) is included with the installer. It is configured to create a new VPC and run Runtime Fabric within its own network, but this can be adjusted per your company's requirements by modifying the script.
* By default, the Terraform script also adds public IP addresses to each VM to make it easy to access across environments. This can also be safely removed by adjusting the script.
* The Terraform script requires a set of parameters which will be added to VMs as environment variables. These variables will be consumed by a setup script which will be executed automatically on each VM.
* The setup script performs the following actions:
** Formats and mounts each dedicated disk
** Adds mount entries to /etc/fstab
** Adds iptable rules
** Enables required kernel modules
** Starts the installation
* Each VM will act as one of two roles:
** Controller VMs are dedicated to operate and run Runtime Fabric services. The internal load balancer also runs within these VMs.
** Worker VMs are dedicated to run Mule applications.
* One controller VM will act as a leader during the installation. This VM will download the installer and make it accessible for each other VM on port 32009.
* All other VMs will copy the installer files from the installer VM, perform the installation, and join the installer VM to form a cluster.
* During the installation, a set of pre-flight checks will run to verify the minimum hardware, operating system, and network requirements for Runtime Fabric as ./install-sys-reqs.adoc[defined]. If these requirements are not met, the installer will not succeed.

== Before you Begin

Ensure the following criteria have been met before beginning the installation. If unsure on any of the requirements below, consult with your network or operations administrators before attempting installation.

* You're familiar with using Anypoint Runtime Manager to deploy and manage applications.
* You're familiar with using Anypoint Access Management to manage permissions for Anypoint users.
** Your Anypoint user account will require the *Organization Administrators* role or the *Manage Runtime Fabrics* permission on the corresponding environments.
** You may also require permissions under the Secrets Manager tab in Access Management to enable inbound traffic to Runtime Fabric:
** Grant Access to Secrets
** Manage Secret Groups
** Read Secrets Metadata
** Write Secrets
* You're familiar with your organization's network and security policies: 
** You know if your organization allows provisioning VMs with public IP addresses.
** You know If your organization does not allow using public IPs, you may need to pass in an existing VPC in the Terraform. See [here] for instructions.
* You're familiar with the Mule applications to understand if inbound traffic should be enabled for Anypoint Runtime Fabric.
** If so, you have a TLS certificate with the desired Common Name set to route traffic to Runtime Fabric.
** You're able to create or configure an external TCP load balancer to manage traffic to applications running in Runtime Fabric.
** You're able to configure DNS settings to associate the Common Name on the TLS certificate to the IP address of the external load balancer.
* You have the required hardware provisioned, or have enough quota with your infrastructure provider to create the required hardware.
** Virtual machines
** Disks with provisioned IOPS
** Virtual networks
** Firewall rules / security groups
** Load balancers
* If provisioning hardware with AWS or Azure, you have the right permissions to create the above resources.
* Your organization's Mule license key.
* Details on how to forward logs to your organization's logging provider.

* link:/anypoint-runtime-fabric/v/1.0/install-sys-reqs[Verify System Requirements for Anypoint Runtime Fabric]
* link:/anypoint-runtime-fabric/v/1.0/install-port-reqs[Network Port Requirements for Anypoint Runtime Fabric]
//* link:/anypoint-runtime-fabric/v/1.0/install-aws[Install a Runtime Fabric on AWS]
* link:/anypoint-runtime-fabric/v/1.0/install-azure[Install a Runtime Fabric on Azure]
* link:/anypoint-runtime-fabric/v/1.0/install-manual[Install a Runtime Fabric Manually]
* link:/anypoint-runtime-fabric/v/1.0/install-add-license[Create and Add a License Secret to a Runtime Fabric]
* link:/anypoint-runtime-fabric/v/1.0/configure-log-forwarding[Set up Log Forwarding on Runtime Fabric]
//* Configure alerts for Runtime Fabric
//* Associate environments to Runtime Fabric
