= Install Runtime Fabric on Azure

This topic describes how to install and register Anypoint Runtime Fabric on your Azure account.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware requirements. An operations specialist may be needed to provision the required infrastructure.
====

== Download Installer
The installer package includes the necessary scripts and binaries needed to install Runtime Fabric.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Click the installer link to begin the download.
. Once downloaded, unpack the installer file to view its contents.

[NOTE]
The extension for the installer is packaged as `tar.gz`. You'll need a utility to unpack tar files.

You'll find a directory named `azure` inside the installer, which contains the following:

* `resource-template.json`: the Azure Resource Template used to provision infrastructure on your Azure account.
* `auto_installer.py`: the installation bootstrap script.
* `README.md`: a markdown file containing instructions to install on Azure.

== Provision Infrastructure
Use the included Azure Resource Manager Template to easily provision the required hardware and network settings needed to install and operate Runtime Fabric.

There are multiple methods to apply the Azure Resource Manager Template to your Azure account. Below are instructions to apply the template via the Azure Portal.

[NOTE]
You'll need a private and public key as a PEM file to provision the VMs. This is required to enable secure access to your VMs via SSH (Secure Shell).

. Log into your Azure account.
. Navigate to "Create a resource".
. On the "Search the marketplace" search bar, type in "Template deployment".
. Click "Create".
. Select "Build your own template in the editor."
. On the bar above the editor, click "Load file" and select the `resource-template.json`.
. After the editor is populated with the contents of the file, click "Save".
. Verify your Subscription selection, Resource group, and Region for deployment. In most cases, it's recommended to create a separate Resource group.
. Under Settings, fill in the `Public_keys_data` field with your public key string. This will enable you to SSH into each VM with your associated private key.
. Review and select the Terms and Conditions on the bottom of the page, and click "Purchase".

Your infrastructure will begin be created and configured. Follow these steps to view the progress:

. On the left navigtion bar, click on "Resource groups".
. Select the Resource group used to provision your Runtime Fabric infrastructure. 
. On the Overview pane under Deployments, click on the link below, which may read "1 Deploying".
. Click on the Deployment Name "Microsoft.Template".

You should be able to see the list of infrastructure and its cooresponding status as it's being provisioned. Click the "Refresh" button to periodicaly refresh the pane and status.

=== Common Errors
Depending on the policies set and the quotas defined with your Azure account, you may encounter errors during the provisioning process. Consult your operations team as needed.

* Exceed max core quota: File a ticket with Azure Support to increase quota for your deployment region. If you believe you have enough quota, ensure the right region is selected with the increased quota. Also, try modifying the Resource Group name to ensure it is unique to your account.
* Network policy violation: By defualt, the Netowrk Security Groups defined in the Azure Resource Template are associated at the subnet level and the NIC for each VM. Depending on your company's policy, you may need to adjust the template to remove an association.

== Install Runtime Fabric

After the required infrastructure has been provisioned successfully, you can now begin the installation process.

. Connect to the `rtf-controller-1` VM using your preferred SSH utility. You may need to reference your private key cooresponding to the public key provided during the provisioning process.
+
----
ssh rtf-user@<PUBLIC-IP-ADDRESS> -i <private_key.pem>
----
+
. Change directory to the `/tmp` directory.
+
----
cd /tmp
----
+
. Upload your private key as a PEM file that is associated to the public key used earlier in the provisioning step into the `/tmp/installer` directory. A secure method to transfer files is by using an SCP utility, such as WinSCP.
+
[NOTE]
If your private key is not a PEM file, you can typically convert it using a utility such as PuTTYgen.
+
. Change directory to the `/tmp/installer` directory.
. Start the installation by setting the following variables and executing the `auto_installer.py` script:
+
----
RTF_PRIVATE_IPS="10.3.0.4 10.3.0.5 10.3.0.6" \
WORKER_PRIVATE_IPS="10.3.0.11 10.3.0.12 10.3.0.13" \
FLAVOR=prod \
USER=rtf-user \
KEY=key.pem \
python auto_installer.py
----
+
Using the following values:
+
[%header,cols="2*a"]
|===
|Parameter | Description
|RTF_PRIVATE_IPS | Specifies the private IP address for each virtual machine running Runtime Fabric.
|WORKER_PRIVATE_IPS | Specifies the private IP address for each virtual machine dedicated to running Mule runtimes.
|FLAVOR | Specifies the function for the installer. Valid values are: `prod`, `dev`, and `demo`.
|USER | Specifies the username on the virtual machines.
|KEY | Specifies the path for the private ssh key pair.
|===
+
[NOTE]
This step will install Runtime Fabric across all servers to form a cluster. It may take 15-25 minutes or longer to complete.

== Registering Runtime Fabric

After the installation script has completed, you'll need to register Runtime Fabric to Anypoint Runtime Manager.

. Navigate to Runtime Manager, select the Runtime Fabrics tab, and select the "Create Runtime Fabric" button.
. Near the registration script, choose a name for your Runtime Fabric. Copy the script to your clipboard.
. SSH onto a virtual machine running Runtime Fabric and paste and run the registration script. This process may take up to 15 minutes to complete.
. After the script completes the registration process, Runtime Fabric should be registered and visible on the "Runtime Fabrics" tab in Runtime Manager.