= Create and Add a License Secret to a Runtime Fabric

This topic describes how to add a license to a runtime fabric. To deploy applications to a runtime fabric, you must add a provide a Mule runtime license as a kubernetes secret.

== Before You Begin

Contact your customer success represntative to obtain an enterprise license.

== Generate a Mule License Key on Mule 3.x

After obtaining a license file, perform the following to generate a license key:

. Upload license.lic to the Mule license verifier URL:
+
https://mulelicenseverifier.cloudhub.io/

. Click *Verify*x. 
. After verification, click *Download digested license*.
+
_Result:_ A file called `muleLicenseKey.lic` is downloaded to your file system.

. Rename this downloaded file to: `3.x.muleLicenseKey.lic`

== Generate a Mule License Key on Mule 4.x

. Download and uncompress the Mule 4 binary file from the Download Site at:
+
`https://support.mulesoft.com/s/downloads`
+
The Mule 4 binary files are located under Downloads > Mule Runtime. 

. Set the `MULE_HOME` env variable to the followinng value: 
+
----
export MULE_HOME=~/Downloads/mule-enterprise-standalone-4.1.1/
----

. From the `$MULE_HOME/bin` directory, run the following command:
+
----
./mule -installLicense <path to license.lic file>
----
+
_Result:_ The script generates the `muleLicenseKey.lic` file at `$MULE_HOME/conf/muleLicenseKey.lic`

. Copy and rename this file to 4.x.muleLicenseKey.lic


== Install the License Key on Kubernetes

After generating a license key for your Mule runtime, perform the following to install the license key in Kubernetes:

. Download the Mule Runtime License Helper from the following URL:
+
----
https://github.com/mulesoft/poseidon-agent/blob/master/muleruntime-license-helper.sh
----

. Run the following command, depending on your Mule runtime version:
+
----
./muleruntime-license-helper -3=<path to 3.x.muleLicenseKey.lic>
----
+
Or:
+
----
./muleruntime-license-helper -4=<path to 4.x.muleLicenseKey.lic>
----

_Result:_ Running this command generates `kubectl` command to create secret in poseidon namespace.