= Create and Add a Mule License Key to Runtime Fabric
:noindex:

This topic describes how to add a license key to runtime fabric. This is required in order to deploy applications to runtime fabric.

== Before You Begin

Contact your customer success representative to obtain an enterprise license to the Mule runtime.

== Generate a Mule License Key on Mule 3.x

After obtaining a license file, perform the following to generate a license key:

. Upload license.lic to the Mule license verifier URL:
+
https://mulelicenseverifier.cloudhub.io/

. Click *Verify*x. 
. After verification, click *Download digested license*.
+
_Result:_ A file called `muleLicenseKey.lic` is downloaded to your file system.

. Rename this downloaded file to: `3.x.muleLicenseKey.lic`

== Generate a Mule License Key on Mule 4.x

. Download and uncompress the Mule 4 binary file from the Download Site at:
+
`https://support.mulesoft.com/s/downloads`
+
The Mule 4 binary files are located under Downloads > Mule Runtime. 

. Set the `MULE_HOME` env variable to the followinng value: 
+
----
export MULE_HOME=~/Downloads/mule-enterprise-standalone-4.1.1/
----

. From the `$MULE_HOME/bin` directory, run the following command:
+
----
./mule -installLicense <path to license.lic file>
----
+
_Result:_ The script generates the `muleLicenseKey.lic` file at `$MULE_HOME/conf/muleLicenseKey.lic`

. Copy and rename this file to 4.x.muleLicenseKey.lic


== Install the License Key on Runtime Fabric

After generating a license key for your Mule runtime, perform the following to install the license key in runtime fabric:

. Download the Mule Runtime License Helper from the following URL:
+
----
https://github.com/mulesoft/poseidon-agent/blob/master/muleruntime-license-helper.sh
----

. Run the following command, depending on your Mule runtime version:
+
----
./muleruntime-license-helper -3=<path to 3.x.muleLicenseKey.lic>
----
+
Or:
+
----
./muleruntime-license-helper -4=<path to 4.x.muleLicenseKey.lic>
----
+
_Result:_ Running this command generates a command to insert the Mule license key in runtime fabric.
+
. On a runtime fabric server, run the command `sudo gravity enter`.
. Run the script generated from the license key script. This will enter the license key in runtime fabric.
. Exit the system by running the command `exit`.
