= Manually Install Runtime Fabric

This topic describes how to install and register Anypoint Runtime Fabric on VMs hosted in your data center.

== Prerequisites
. Provision the necessary hardware for the controller VMs and worker VMs as outlined in the system requirements page.
. Ensure the required disks are listed as a block device for each VM. The disks do not need to be mounted or formatted.
. Runtime Fabric supports RedHat v7.4 or CentOS v7.4. Each VM should be running a compatible operating system.
. The necessary ports should be opened as described on the port requirements page.

[WARNING]
====
Before running the installer, ensure that your infrastructure meets the minimum hardware requirements. An operations specialist may be needed to provision the required infrastructure.
====

== Download Script

The installer script ZIP file includes the necessary scripts needed to install Runtime Fabric. Download it to a controller VM you wish to act as the leader during the installation. It'll be referred to as the installer VM.

. Log in to Anypoint platform and navigate to Runtime Manager.
. On the left navigation pane, select "Runtime Fabrics".
. Click "Create Runtime Fabric".
. Copy the "Download files" link.
.. Right-click the button and select an option closet to "Copy link location".
. Download the file to the installer VM.
.. Open a shell (SSH session) to the installer VM.
.. Download the file: `curl {INSTALLER_URL} --output rtf-install-scripts.zip`
. Once downloaded, unzip the `rtf-install-scripts.zip` file in a separate directory.
----
mkdir -p ./rtf-install-scripts && unzip rtf-install-scripts.zip -d ./rtf-install-scripts
----

Inside `rtf-install-scripts/`. you'll find a directory named `manual` containing the following:

* `generate-configs.sh`: a script to help generate environment variables for each VM.
* `README.md`: a markdown file containing instructions to aid with installation.

== Prepare VMs for Installation
The initialization process perform the following actions:

* Formats the dedicated disks.
* Mounts the dedicated disks to the appropriate path.
* Sets iptable rules.
* Enables the required kernel modules.
* Enables and reloads system services.

To begin, we will run a configuration tool. This aids in generating the environment variables required on each machine. The script reads these variables during execution.

=== Variables to specify:
[%header,cols="3*a"]
|===
|Parameter | Description | Example
| `RTF_CONTROLLER_IPS` | IP addresses of the controller VMs, separated by whitespace. | `"10.3.0.4 10.3.0.5 10.3.0.6"`
| `RTF_WORKER_IPS` | IP addresses of the worker VMs, separated by whitespace. | `"10.3.0.11 10.3.0.12 10.3.0.13"`
| `RTF_DOCKER_DEVICE` |  Block device path for the dedicated disk used for Docker, supporting 1000 provisioned IOPS. | `/dev/xvdc`
| `RTF_ETCD_DEVICE` |  Block device path for the dedicated disk used for etcd, supporting 3000 provisioned IOPS. | `/dev/xvdb`
| `RTF_TOKEN` | The token used by VMs to auto-join the cluster. | `my-cluster-token`
| `RTF_INSTALL_PACKAGE_URL` | URL to download the installation package from available on the Create Runtime Fabrics page. | `https://s3.amazonaws.com/runtimefabric/...`
| _If this is not specified, the installer will expect you to manually copy the installation package to_ `/opt/anypoint/runtimefabric/installer.tar.gz` |
| `RTF_NAME` | The name of your Runtime Fabric cluster. | `runtime-fabric`
| `RTF_NODE_WAIT_COUNT` |  The number of VMs to have joined before completing the installer. | `6`
| `RTF_AUTH_TOKEN` | An active Bearer token for your Anypoint user, available on the Create Runtime Fabric page. | `Bearer 626d7810-0730-498b-bd48-544490c2226b`
| `RTF_ORG_ID` | The ID for your Anypoint organization, available on the Create Runtime Fabric page. | `2f99d26-a3c2-4023-b303-5528sdd5v022`
| `RTF_REGION` | The Anypoint control plane region you're registering to, available on the Create Runtime Fabrics page. | `us-east-1`
| `RTF_MULE_LICENSE` | The digest (`muleLicenseKey.lic`) of your organization's Mule Enterprise license key. Learn more on how to link:/mule-user-guide/v/3.9/installing-an-enterprise-license[install a Mule Enterprise license]. |
|===

[NOTE]
To help identify the block device paths to your disks, use the `lsblk` command on the VMs.

. If needed, open a shell/SSH on the installer VM and navigate to the `manual` directory from the unzipped directory.
. Fill in the values to each variable and execute `generate-configs.sh`. It may be easier to paste the command in a text editor to fill in the variables.
----
RTF_CONTROLLER_IPS="" \
RTF_WORKER_IPS="" \
RTF_DOCKER_DEVICE= \
RTF_ETCD_DEVICE= \
RTF_TOKEN= \
RTF_INSTALL_PACKAGE_URL= \
RTF_NAME= \
RTF_NODE_WAIT_COUNT= \
RTF_AUTH_TOKEN="" \
RTF_ORG_ID= \
RTF_REGION= \
RTF_MULE_LICENSE="" \
./generate-configs.sh
----
+
. The output is a configuration snippet for the `installer`, `controller`, and `worker` VMs. Execute the snippet on each VM based on its desired role to add the expected environment variables.
.. On the `installer` VM, paste and execute the `installer` snippet to prepare it for the installation script.
.. On the `controller` VM(s), paste and execute the `controller` snippet.
.. On the `worker` VMs, paste and execute the `worker` snippet.
. On each VM, copy the `installer/scripts/init.sh` file to `/opt/anypoint/runtimefabric`, and ensure the script is executable:
+
----
mkdir -p /opt/anypoint/runtimefabric && cp ./rtf-install-scripts/scripts/init.sh /opt/anypoint/runtimefabric/init.sh && chmod +x /opt/anypoint/runtimefabric/init.sh
----

== Installation

. Run the `init.sh` script in privileged mode, on the `installer` VM:
----
sudo /opt/anypoint/runtimefabric/init.sh
----

2. Once the installer machine has successfully completed its checks and is running the installation process, run the `init.sh` script in privileged mode on all the other VMs. This can be done concurrently on all the nodes.
----
sudo /opt/anypoint/runtimefabric/init.sh
----

[NOTE]
This step will install Runtime Fabric across all VMs to form a cluster. It may take 15-25 minutes or longer to complete.

When the process is completed, you will have a Runtime Fabric instance registered in your Anypoint environment. 

== Associate Environments to Runtime Fabric

Before using your Runtime Fabric, you must associate it with one or more environments.

. Navigate to Runtime Manager, select the Runtime Fabric tab, then select the Runtime Fabric based on the name used during registration.
. On the Environments tab, select the environment you want to associate with this Runtime Fabric and click Add.
. Click Apply to confirm the changes.
