= About Deploying to CloudHub (Anypoint Studio)

When developing your application in Anypoint Studio, consider the following requirements to deploy it to CloudHub:

If you are using HTTP Listener connectors as sources for your flow, you need to set its host to *0.0.0.0* and its port to *${http.port}*. +
CloudHub can then dynamically allocate a port at deployment time.

You can configure the CloudHub instance to which you are deploying when using the Anypoint Studio interface. +
Anypoint Studio uses your package name as the name for your application on CloudHub. This name is part of the domain of your deployed app. For example, naming your application application-1 makes your app's public domain +application-1.cloudhub.io+.

You can also configure the runtime version. By default, Studio uses the application version you are using in your project during development. +
To reduce compatibility risks, you should always deploy to the runtime version in which your Mule project is created or the closest alternative.

Additionally you can also configure the amount of worker and worker size for the CloudHub instance you are going to use, enable Insight, static IPs, configure log levels and properties placeholders for your application.

== See Also

** link:/anypoint-studio/v/7.1/deploy-mule-application-task[To Deploy a Mule Applcation to CloudHub (Anypoint Studio)]
// _TODO: Add links to runtime manager after 4.1 Release.
