= About Mule Domains (Anypoint Studio)

The Mule runtime supports Mule domain projects, to share global configuration elements between different Mule applications implementing the same domain. A Mule domain project is deployed to the $MULE_HOME/domains folder, rather than the $MULE_HOME/apps folder. 

Like a Mule application, when a Mule domain project is deployed to a Mule runtime's $MULE_HOME/domains folder, a corresponding anchor file is created. You can gracefully remove the Mule domain by deleting its anchor file. 

Every Mule application belongs to a Mule domain. By default, a new Mule application is added to the `default` domain. The `default` domain is a special Mule domain that does not share global configuration elements between Mule applications. 

== Creating a Mule Domain Project

Anypoint Studio allows you to create, edit and maintain Mule domains. 

+
To create a Mule domain project: 
. From the Studio main menu select File > New > Mule Domain Project.
. Type in a new Project Name.
. Select the Mule runtime version this Mule domain will support. 
. Select the Project location. 

The new Mule domain project appears in Anypoint Studio with a special folder icon to indicate it is a Mule domain project. Inside the project folder is a Mule configuration xml file. Here is an example of a the Mule configuration XML file for a new Mule domain project for a Mule domain named sales-domain:

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<domain:mule-domain
        xmlns="http://www.mulesoft.org/schema/mule/core"
        xmlns:domain="http://www.mulesoft.org/schema/mule/ee/domain"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
        xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/ee/domain http://www.mulesoft.org/schema/mule/ee/domain/current/mule-domain-ee.xsd">

    <!-- configure here resource to be shared within the domain -->

</domain:mule-domain>
----
Notice Mule domain projects use a `domain` namespace, rather than the `mule` namespace for a Mule application. 

Like a Mule application, a Mule domain contains a mule-artifacts.json file. Here is an example of a newly generated Mule domain project for the `sales-domain` Mule domain:

[source, json, linenums]
----
{
  "configs": [
    "mule-domain-config.xml"
  ],
  "secureProperties": [],
  "redeploymentEnabled": true,
  "name": "sales-domain",
  "minMuleVersion": "4.1.0",
  "requiredProduct": "MULE_EE",
  "classLoaderModelLoaderDescriptor": {
    "id": "mule",
    "attributes": {
      "exportedResources": []
    }
  },
  "bundleDescriptorLoader": {
    "id": "mule",
    "attributes": {}
  }
}
----
Notice the domain name is indicated in this file. 

Like Mule applications, a Mule domain is also a Maven project, so it also contains a pom.xml file. Here is the pom.xml file generated by the new sales-domain Mule domain project:


[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.mycompany</groupId>
    <artifactId>sales-domain</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>mule-domain</packaging>

    <name>sales-domain</name>

    <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<app.runtime>4.1.0</app.runtime>
		<mule.maven.plugin.version>3.1.0</mule.maven.plugin.version>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.mule.tools.maven</groupId>
                <artifactId>mule-maven-plugin</artifactId>
                <version>${mule.maven.plugin.version}</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
    </dependencies>

	<repositories>
          <repository>
            <id>anypoint-exchange</id>
            <name>Anypoint Exchange</name>
            <url>https://maven.anypoint.mulesoft.com/api/v1/maven</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>mulesoft-releases</id>
            <name>MuleSoft Releases Repository</name>
            <url>https://repository.mulesoft.org/releases/</url>
            <layout>default</layout>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>mulesoft-releases</id>
            <name>mulesoft release repository</name>
            <layout>default</layout>
            <url>https://repository.mulesoft.org/releases/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</project>
----

First, notice the critical information that defines this Mule domain:

[source, xml, linenums]
----
    <groupId>com.mycompany</groupId>
    <artifactId>sales-domain</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>mule-domain</packaging>

    <name>sales-domain</name>
----

=== How Mule Applications Share Resources in a Mule Domain. 
A Mule domain let's Mule applications share any global configuration elements. For example, several Mule applications could share the same HTTP connection. Then if all the Mule applications are deployed into the same Mule runtime, they can share one HTTP connection. This can conserve system resources and avoid TCP bind errors from conflicting Mule application configurations. For example, by adding several Mule applications to one Mule domain, they could all be configured to use the standard TCP port 80 for their HTTP Listeners. Instead of each Mule application configuring its own HTTP Listener global element, when the applications are added to the common Mule domain, they will all see the same HTTP Listener that is configured at the domain level. 

=== Adding Mule Modules to a Mule Domain
The Mule shows two different tabs:
* Global Elements +
Here you can define the global configurations that your domain makes available for other applications to reuse.
* Configuration XML +
This tab allows you to edit your Mule Domain configuration XML code using autocomplete.

Like to the Mule application configuration XML file editor, the Mule domain's configuration XML file editor has two different editor tabs - the visual Global Elements editor tab, and the Configuration XML source code editor tab. However, unlike Mule applications, a Mule domain does not support any flows, so there is no visual flow editor. 

Before you can add global configuration elements to your Mule domain, you must import the Mule modules. 

First, in the Mule domain Global Elements editor, there is a button named Manage Modules. When you click this button, a Properties editor appears that lets you add and remove modules. 

When you click the Add Module button, the Add Modules to Project wizard appears. This is the same wizard you see in a Mule application when you add modules to the Modules Palette in the visual editor. You can search for Modules already installed into Studio, or you can add modules from Anypoint Platform Exchange. 

[NOTE]
You can also access the by right-clicking on the pom.xml file, then selecting Mule > Manage Modules. 

Here is the part of the pom.xml file where an HTTP Connector module dependency is added to the Mule domain:

[source, xml, linenums]
----
    <dependencies>
        ...
    	<dependency>
            <groupId>org.mule.connectors</groupId>
            <artifactId>mule-http-connector</artifactId>
            <version>1.1.0</version>
            <classifier>mule-plugin</classifier>
        </dependency>
    </dependencies>
----

here is the updated mule-domain-config.xml file for this Mule domain project, with the http namespace

=== Adding Global Configuration Elements to a Mule Domain
To add global configuration elements, you can manually copy and paste any global configuration element from a Mule application into a Mule domain using the XML file editor tab, but you must then also copy over the correct XML namespace and XSD information, and you must also configure the `pom.xml` file with any dependencies required by those global configuration elements. 

A much easier (and recommended) method is to use the Mule Domain configuration editor to automate all these steps. This editor is very similar to the Mule application Global Elements editor, but there are a few differences. 

Here is the Mule domain's configuration XML file after adding an HTTP Listener global element:

[source, xml, linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<domain:mule-domain
        xmlns:http="http://www.mulesoft.org/schema/mule/http"
        xmlns="http://www.mulesoft.org/schema/mule/core"
        xmlns:domain="http://www.mulesoft.org/schema/mule/ee/domain"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:doc="http://www.mulesoft.org/schema/mule/documentation" 
        xsi:schemaLocation="
               http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
               http://www.mulesoft.org/schema/mule/ee/domain http://www.mulesoft.org/schema/mule/ee/domain/current/mule-domain-ee.xsd
               http://www.mulesoft.org/schema/mule/http http://www.mulesoft.org/schema/mule/http/current/mule-http.xsd" >
	<http:listener-config name="HTTP_Listener_config" doc:name="HTTP Listener config" doc:id="b42a8807-6f69-436d-896f-c189e8f181ac" >
		<http:listener-connection host="0.0.0.0" port="${http.port}" />
	</http:listener-config>

    <!-- configure here resource to be shared within the domain -->

</domain:mule-domain>
----

Notice the new xmlns:http namespace attribute is added, as well as two new entries in the xsi:schemaLocation attribute. 

The <http:listener-config> element can now be shared with multiple Mule applications once those Mule applications are added to this Mule domain. 

=== Making Mule Domains Visible to Mule Applications
Mule domains must be either available in your Studio Workspace or deployed in the Nexus repository declared in your application's POM file.

When a Mule domain is installed in your Nexus repository, and you configured it as a dependency on your Mule application, Anypoint Studio can automatically resolve your Mule domain's modules and add them to your application project. However, when working with remote Mule Domain projects from Anypoint Studio keep in mind the following restrictions:

* You can't edit the global elements of a remote Mule domain.
* You can't edit the modules of a remote Mule domain.
* You can't run a Test Connection from a global element defined in your remote Mule domain.

Domains are only editable when they are open projects in your workspace.

=== Adding Mule Applications to a Mule Domain
A Mule application is added to a Mule domain by editing the Mule application's pom.xml file. But the easier (and recommended) method is to right-click on the Mule application folder, then select Mule > Open Mule Project Properties. This opens the Properties editor for the Mule application with Mule Project selected. Select the new Mule domain name from the drop-down list. 

This adds the Mule domain dependency to the Mule application's pom.xml file. Here is an example pom.xml file of a Mule application that was added to the sales-domain Mule domain:

[source, xml, linenums]
----
	<dependencies>
    	<dependency>
            <groupId>org.mule.modules</groupId>
            <artifactId>mule-validation-module</artifactId>
            <version>1.0.0</version>
            <classifier>mule-plugin</classifier>
        </dependency>
    	<dependency>
            <groupId>com.mycompany</groupId>
            <artifactId>sales-domain</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <classifier>mule-domain</classifier>
            <scope>provided</scope>
        </dependency>
    </dependencies>
----

Notice how the groupId, artifactId, and version exactly match the values from the Mule domain's pom.xml file. 

Now you can select this HTTP Listener in the event processors in the Mule application's flows. 

[NOTE]
All modules inside a Mule Domain are automatically inherited by all Mule applications under it. +
Module versioning between your Mule domain and you applications must be consistent. It is not possible to add a module to your Mule Application if the same module already exists in your Mule domain. If the Mule application was already using the same Mule module, you may get conflicts after adding the Mule application to the Mule domain. In this case, delete the repeated dependency tag from the Mule application's pom.xml file. 


=== Exporting a Mule Domain Project 
To export a Mule domain project from Anypoint Studio:

  . From the Anypoint Studio main menu, select File > Export. 
  . Select Anypoint Studio Project to Mule Deployable Archive (includes Studio metadata). 
  . Browse for the location to export the Mule domain's deployable archive file, then type in the file name at the end of the path. 
  . Check or uncheck the check boxes to attach project sources and to include project modules and dependencies. 
  . Click Finish. 

[NOTE]
If you do not include the project modules and dependencies, you may not be able to deploy the the deployable archive to a Mule runtime, but you can import the Mule domain project into another Anypoint Studio workspace, then all the dependencies will be downloaded again based on what is indicated in the pom.xml file. 

=== Deploying a Mule Domain Project to a Mule Runtime
To deploy a Mule domain project, copy the deployable archive JAR file to the $MULE_HOME/domains folder. You should see a console message indicating the Mule domain was correctly deployed into the Mule runtime. 

[NOTE]
Mule domains are not currently supported by CloudHub workers. You can only deploy Mule domain projects to Mule runtimes installed in customer-hosted infrastructure. 

=== Deploying a Mule Application into a Mule Domain
Once the Mule domain is deployed into the Mule runtime, you can deploy Mule applications as usual by copying the deployable archive JAR files into the $MULE_HOME/apps folder. 


== See Also

* link:/anypoint-studio/v/7.1/domain-studio-tasks[To Design Mule Domains (Anypoint Studio)]
* link:/anypoint-studio/v/7.1/add-modules-in-studio-to[To Add Modules to Your Studio Project]
