= FAQ: Troubleshooting JDK Requirement

Anypoint Studio 7.1 requires JDK 8 to run properly.

To verify that you have the correct JDK version installed, type `java -version` in the command line. +
If you get the error `java: Command not found`, install JDK 1.8. +
If you get a version different than 1.8, make sure to upgrade, or downgrade to 1.8.

After downloading the JDK and following the installation instructions, make sure that the JAVA_HOME environment variable is pointing to your JDK installation:



Under certain circumstances, if you had a JRE installation previous to installing the JDK, your default VM could still be configured as the JRE. +
To correct this, configure Anypoint Studio to point to your JDK installation as the default VM:



If after doing so, Anypoint Studio still does not recognize your JDK installation, consider uninstalling your the JRE.



== See Also

* link:/anypoint-studio/v/7.1/jdk-requirement-wx-workflow[Workflow: Installing and Configuring JDK (Windows)]
* link:/anypoint-studio/v/7.1/jdk-requirement-lnx-worflow[To Configure Java JDK (Linux)]
