= To Configure Proxy Settings (Anypoint Studio)

Anypoint Studio allows you to configure proxy configurations for when your computer is behind a proxy server and needs to connect to the internet to download plugins and install updates. +
Anypoint Studio only supports configurations for non-authenticated proxies.

. Open the preferences view. +
In OSx go to Anypoint Studio > Preferences.. or hit `cmd + ,`. +
In Windows and Linux go to Window > Prefereces...
. Under General select Network Connections.
. Select your Active Provider: +
* Direct causes Anypoint Studio to open connections without the use of a proxy server.
* Manual causes Anypoint Studio to open connections using the settings defined in the options below.
* Native causes Anypoint Studio to open connections using settings discovered in the OS where Anypoint Studio is installed.
. Click the Edit button when selecting the proxy entry for each schema to configure its host and port number.

If necessary, you can add bypasses to your proxy. This is a list of hosts that should not use any proxy. +
Click Add Host... to add hostnames to your proxy bypass list.

== See Also

* link:/anypoint-studio/v/7.1/proxy-settings-reference[Proxy Settings Reference (Anypoint Studio)]
