= To Download and Install Anypoint Studio 7.1 (Linux)

To support some of Studio Themes in Linux, it is recommended to have GTK version 2 installed.

* Before downloading and launching Anypoint Studio, make sure you have the Java SE JDK 8 installed.

To install Anypoint Studio 7.1:

. Download Anypoint Studio from the link:https://www.mulesoft.com/lp/dl/studio[Anypoint Studio Download Site] and extract it.
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace. +
+
[NOTE]
--
You cannot reuse a workspace used by Anypoint Studio 6.x or below. +
If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--

Anypoint Studio displays a welcome message when it loads for the first time. +
Click Get Started to start using Anypoint Studio.



== See Also

* link:/anypoint-studio/v/7.1/studio-xulrunner-lnx-task[To Configure XULRunner as Studio's Default Layout Engine (Linux)]
* link:/anypoint-studio/v/7.1/jdk-requirement-lnx-worflow[To Configure Java JDK (Linux)]
* link:/anypoint-studio/v/7.1/studio-configure-vm-task-lnx[To Configure Studio's Default VM (Linux)]
