= Anypoint Access Management Release Notes
:keywords: release notes, access management, anypoint platform, permissions, entitlements, roles, users, administrator, gear icon

== July 16, 2016 Pre-Release
*_Version 0.13.1_*

[NOTE]
--
This is a pre-release note. This feature will be available on July 16th.
--

The Access Management V0.13.0 release is scheduled for July 16th and features the addition of granting impersonation privileges to the Mulesoft support team to access your organization and bussiness groups configurations.

=== Hardware and Software Requirements

No change.

=== Compatibility

NA

=== Features and Functionality

Starting on July 16th, you will notice a *Grant MuleSoft Support access to my Anypoint organization* checkbox in your link:/access-management/[Access Management] panel. +
This checkbox will be enabled by default for your organization and business groups and grants our support team access to impersonate an user inside your organization or business group to troubleshoot Anypoint Platform issues. +
All the activity made by a MuleSoft support agent is logged and can be reviewed and filtered via the link:/access-management/audit-logging[Audit logging UI].

=== Deprecated Features or Functionality

None.

=== Resolved Issues

None.

=== Migration Guidance

No migration required.

// V0.13.0 missing

== May 14, 2016 Release
*_Version 0.12.0_*

The Access Management V0.12.0, is a minor release that makes the Audit Logs UI a GA functionality. Using this UI users can query and filter Audit logs.

=== Hardware and Software Requirements

No change.

=== Compatibility

NA

=== Features and Functionality

Audit Logs UI for Anypoint Platform: Changes made by users within an Anypoint Platform organization are logged through an audit logging service. You can now access the data logs through the  Audit Logs UI under Access Management  or by leveraging the Audit Logging Query API. See Audit Logs.

=== Deprecated Features or Functionality

None.

=== Resolved Issues

None.

=== Migration Guidance

No migration required.
