= Amazon S3 Connector Release Notes
:keywords: release notes, amazon s3, s3, connector

_Select_

The Anypoint Amazon S3 Connector provides connectivity to the the Amazon S3 API, enabling you to interface with Amazon S3 to store objects, download and use data with other AWS services, and build applications that call for internet storage. Instant access to the Amazon S3 API enables seamless integrations between Amazon S3 and other databases, CMS applications such as Drupal, and CRM applications such as Salesforce.

Starting with v.4.0.0, the S3 Connector is licensed commercially with Anypoint Platform as with other Select connectors.  Prior versions remain freely available to the community.

== Version 5.0.0 - November 18, 2017

=== Version 5.0.0 Compatibility

The Amazon S3 connector is compatible with:

[width="100%",cols="50a,50a",options="header"]
|===
|Application/Service|Version
|Mule Runtime|4.0.x or later
|AWS SDK for Java	|1.11.79
|===

=== Version 5.0.0 Features

* Migrated to Mule 4.0.0 runtime

=== Version 5.0.0 Fixed in this Release

None.

=== Version 5.0.0 Known Issues

None.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]