= Amazon RDS Connector Release Notes
:keywords: release notes, amazon rds, rds, connector

_Select_

*November 2017*

Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and scale a relational database in the cloud. The Anypoint Connector for Amazon RDS provides connectivity to the Amazon Relational Database Service (Amazon RDS) API, enabling you to interface with Amazon RDS to provide cost-efficient and resizable capacity while automating time-consuming administration tasks such as hardware provisioning, database setup, patching, and backups. 

Starting with v.1.0.0, the RDS connector is licensed commercially with Anypoint Platform as with other Select connectors.

== Version 1.0.0 - November 18, 2017

Release notes for version 1.0.0 of the Amazon RDS connector.

=== Version 1.0.0 Compatibility

The Amazon RDS Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.0.0
|Amazon Java SDK for RDS|v1.11.172
|Java|1.8 or higher
|Anypoint Studio|7.0 or higher
|===

=== Version 1.0.0 Features

* Built with the new AnyPoint SDK (Extensions Framework) v1.0.0-rc-SNAPSHOT.
* Built with AWS SDK v1.11.172
* Support for Temporary Credentials - A checkbox named Try Default AWS Credentials Provider Chain has been added to the Global Configuration Elements. If selected, the connector will first try to obtain the credentials from an AWS environment.
* Support for Retry Policy - The connector can be configured with a Reconnection strategy that is provided in the Advanced tab
* The following operations are supported:

** *DB Instances*
*** CreateDBInstance
*** CreateDBInstanceReadReplica
*** DeleteDBInstance
*** DescribeDBInstances
*** ModifyDBInstance
*** RebootDBInstance
*** RestoreDBInstanceFromDBSnapshot
*** RestoreDBInstanceToPointInTime
*** StartDBInstance
*** StopDBInstance

**  *DB Snapshots*
*** CreateDBSnapshot
*** DeleteDBSnapshot
*** DescribeDBSnapshots
*** ModifyDBSnapshot

**  *Events*
*** DescribeEvents

**  *Reserved DB Instances*
*** DescribeReservedDBInstances
*** DescribeReservedDBInstancesOfferings
*** PurchaseReservedDBInstancesOffering


=== Version 1.0.0 Fixed in this Release

Initial version.

=== Version 1.0.0 Known Issues

None.

== See Also

* MuleSoft maintains this connector under the https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[_Select_] support policy.
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]

