= Amazon SNS Connector Release Notes
:keywords: release notes, amazon sns, sns, connector

_Select_

Amazon Simple Notification Service (SNS) provides a hosted multi-protocol "push" messaging for applications. The Anypoint Connector for Amazon SNS allows Mule applications to interact with Amazon SNS. 

Starting with v.3.0.0, the SNS connector is licensed commercially with Anypoint Platform as with other Select connectors.  Prior versions remain freely available to the community.

== Version 4.0.0 - November 18, 2017

Release notes for version 4.0.0 of the Amazon SNS connector.

=== Version 4.0.0 Compatibility

The Amazon SNS Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.0.0 or higher
|Amazon Java SDK for SNS|v1.11.79
|Java|1.8.x
|Anypoint Studio|7.0 or higher
|===

=== Version 4.0.0 Features

* Upgraded to support AWS SDK v1.11.79
* Upgraded to Mule Runtime v4.0.0

=== Version 4.0.0 Fixed in this Release

None.

=== Version 4.0.0 Known Issues

None.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]