= Amazon EC2 Connector Release Notes
:keywords: release notes, amazon ec2, ec2, connector

_Select_

*November 2017*

Amazon Elastic Compute Cloud (Amazon EC2) provides scalable computing capacity in the Amazon Web Services (AWS)
cloud. The Anypoint Connector for Amazon EC2 provides connectivity to the Amazon Elastic Compute Cloud (Amazon EC2) API enabling you to interface with Amazon EC2 to launch as many or as few virtual servers as you need, configure security and networking, and manage storage. 

== Version 2.0.0 - November 18, 2017

Release notes for version 2.0.0 of the Amazon EC2 connector.

=== Version 2.0.0 Compatibility

The Amazon EC2 Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.0.0 and later
|Amazon Java SDK for EC2|v1.11.134
|Java|1.8.0_x
|Anypoint Studio|7.0 and later
|===

=== Version 2.0.0 Features

* Migrated to Mule 4.0.0 runtime.

=== Version 2.0.0 Fixed in this Release

None.

=== Version 2.0.0 Known Issues

None.


* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
