= AMQP Connector Release Notes
:keywords: amqp, release, notes

*June 2017*

== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |3.5 and later
|Anypoint Studio |3.5 and later
|===

== Version 3.7.1 - June 2017

Fixed in this release:

* AMQP-44: Outbound endpoint is not declaring fully defined exchanges and queues.
* AMQP-59: Close connection when channel cannot be started.
* AMQP-63: AMQPS reconnection strategy is not working after SocketTimeoutException.
* MULE-11577: Fix Re-creating queues and exchanges while reconnecting to RabbitMQ.

== Version 3.7.0 - July 2016

This release includes improvements and fixes.

*Note:* The minimum Mule version for 3.7.0 is Mule 3.5.

=== Improvements

* AMQP-16: Studio - Support SSL connectivity to the broker. (Support for AMQPS in Studio.)
* AMQP-46: Upgrade AMQP Client jar from version 3.3.5 to version 3.6.1.
* AMQP-47: Take advantage of TLS protocol/cipher control.
** Support for TLS versions 1.1 and 1.2 (Only available using JDK 7).	
** The sslProtocol attribute now supports the values TLSv1, TLSv1.1, and TLSv1.2 apart from the previously available TLS.
** The connector now validates its configuration against the `tls-default.conf` parameters and respects the protocols and cipher setup.

=== Fixed Issues

* AMQP-51: Method getChannel(...) from `org.mule.transport.amqp.internal.client.ChannelHandler` returns the wrong channel when bridging using different AMQP connectors.
* AMQP-52: Studio - Object-to-amqpmessage-transformer operation is not defined for AMQP and AMQPS.
