= Anypoint MQ Connector Release Notes
:keywords: mq, connector, release, notes

*November 2017*

https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[_Select_]

To support Exchange 2.0 properly, the feature ID of Anypoint MQ Connector has changed. Before you download  link:https://www.mulesoft.com/exchange/org.mule.tooling.messaging/mule-module-anypoint-mq-ee-studio/[v1.2.0 and later from Exchange 2.0],  *uninstall* the existing version of this connector in Studio.

This release of the Anypoint MQ Connector lets you add messaging access to Anypoint MQ queues and exchanges from Anypoint Studio applications.


== Compatibility

[%header%autowidth.spread]
|===
|Software|Version
|Mule Runtime |4.0.0 and newer
|Anypoint Studio |7.0.0
|===

== Version 2.0.0 - November 17, 2017

The Anypoint MQ connector now adds support for Mule 4 and Studio 7, replacing Mule 3 and Studio 6.


== Known Issues

* The Anypoint MQ connector doesn't support tracking.
+
Example with tracking:
+
[source,xml,linenums]
----
<flow name="customers-all-get" tracking:enable-default-events="true">
  <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="testQueue" acknowledgementMode="AUTO"/>
  <tracking:transaction id="customers-all-get"/>
</flow>
----
+
This is the same example with the subscriber tracking statement removed:
+
[source,xml,linenums]
----
<flow name="customers-all-get">
  <anypoint-mq:subscriber config-ref="Anypoint_MQ_Configuration" destination="testQueue" acknowledgementMode="AUTO"/>
</flow>
----

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
