= Anypoint Platform Command Line Interface Release Notes
:keywords: cli, command line interface, command line, release notes, anypoint platform cli

== Version 2.0.3 - June 8, 2017

This release of the Anypoint CLI fixes the following issues:

* Fixed `cloudhub load-balancer describe` fails to show LB information if the sslEndpoint doesn't have publicKeySANs.
* Fixed `anypoint-cli api-mgr definition copy` does not copy RAML files in folders on Windows.
* Fixed `api-mgr definition copy` creates a new file "api.raml" in the target API which does not exist in the source API.
* Fixed `api-mgr portal copy` does not preserve order of portal pages


== Version 2.0.2 - May 17, 2017

This release of the Anypoint CLI fixes the following issues:

* Fixed `api-mgr definition download` raises multiple errors when trying to download to an empty folder.
* Fixed `api-mgr definition upload` creates nested folders incorrectly. E.g. users/employees turns into users/users/employees.
* Fixed `api-mgr definition copy` individual files in the root folder arent’t copied properly.
* Fixed `api-mgr definition copy` when the source contains nested directories (>=2 levels), content is not copied properly.
* Fixed `api-mgr definition copy` & `* upload` after 2+ concecutive runs, copy fails with a message saying “This name already exists in your organization”.


== Version 2.0.1 - May 16, 2017

This release of the Anypoint CLI fixes the following issue:

* Fixed `runtime-mgr cloudhub-application deploy` not working properly when `--property` is passed


== Version 2.0.0 - April 28, 2017

This release of the Anypoint CLI introduces:

* Ability to copy information across organizations (and environments for `runtime-mgr`).
* Ability to deploy applications to hybrid servers and PCF with runtime manager.

It also fixes the following issues:

* Fixed an issue when a command had arguments surrounded with quotes and containing spaces.
* Fixed an issue with `api-mgr definition copy` when the source definition contained folders.
* Fixed an issue with `api-mgr definition copy` not copying notebooks.

And introduces the following changes:

* The `cloudhub applications` commands have been renamed.
* The syntax for the `copy` commands has changed.

See the link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI documentation] for more details.


== Version 1.1.4 - March 15, 2017

This release of the Anypoint CLI fixes the following issues:

* `runtime-mgr application download-logs` not working properly on Windows/Linux.
* `--fields <field_list>` option returns misleading warning.


== Version 1.1.3 - February 25, 2017

This release of the Anypoint CLI fixes the following issues:

* `runtime-mgr application restart` throws an error in non-interactive mode.
* Some arguments should not be converted to integers.

See the link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI documentation] for more details.


== Version 1.1.2 - January 10, 2017

This release of the Anypoint Platform CLI introduces link:/runtime-manager/anypoint-platform-cli#list-of-commands[support for API Manager commands] and a lot of API lifecycle/promotion scenarios.

It also introduces new features such as:

* Support for API Manager, including managing APIs, policies, definitions, portals, client applications, and more.
* Copying API definitions, portals, and policies from one API to another for easy promotion
* More control over the CLI output:
** Ability to format the output in plain text, JSON or tables.
** Ability to specify the fields you want the output to display.
* Improved security
// ** Your interactive mode session asks for credentials renewal after the current session expires based on your configuration on Anypoint Platform.
* Support for Anypoint Platform Private Cloud Edition

See the link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI documentation] for more details.
