= Anypoint Platform - EU Control Plane, December 15 2017 Release Notes

This document describes new features and enhancements, known limitations, issues, and fixes in EU Control Plane. 

== New Features and Enhancements

Beginning on December 15, 2017 the Anypoint Platform control plane is available in the European Union. This enables all customer and MuleSoft data to be transmitted and stored entirely within the EU. 

This release includes the following new features and enhancements:



== Changes in This Release 

There are no changes in this release.

== Fixed Issues

There are no fixed issues in this release.

== Known Limitations and Workarounds

This section lists known limitations and workarounds for this release.

* Public exchange is not fully supported in this release. Although certain public assets are available in the EU Control Plane, the full set of public assets are not available.
+
To take advantage of assets available in the public Exchange of the US Control Plane, copy those assets to a private Exchange within the EU control plane. Private Exchange is fully supported in the EU Control Plane.

* When deploying to CloudHub, you can only deploy applications and gateways to the Frankfurt region. Additionally, the number of supported Mule runtime versions is smaller.

* Only Object Store v2 is supported.

* Anypoint Platform users must create a separate account to access the EU Control Plane.

== Upgrade Requirements

There are no upgrade requirements in this release.

== Compatibility Notes

* Mule Runtime
+
When deploying an application to CloudHub in the EU Control Plane, only the following versions of the Mule runtime are supported:
+
** 3.8.5
** 3.9.0
** 4.0.0
** API Gateway 2.2.0
+
When deploying to a customer-managed runtime, Mule runtime version 3.x is supported as long as you are using version Mule Runtime Manager Agent, version 1.9.2. This version is bundled with Mule runtime, version 3.8.x.

* Runtime Manager Agent
+
When deploying to a customer-managed runtime, you must use Runtime Manager Agent version 1.9.2. This version is bundled with Mule runtime, version 3.8.x.

* Anypoint Studio
+
Anypoint Studio versions 6.4.2 and 7.0.1 support the Anypoint Platform EU Control Plane.

== See Also

* link:/eu-control-plane/[About the EU Control Plane]
* link:/eu-control-plane/app-deploy-eu[To Deploy an Application (EU Control Plane)]
* link:/eu-control-plane/object-store-eu[About Object Store in the EU Control Plane]