= Anypoint Platform Private Cloud Edition 1.7.0 Release Notes

**December 15, 2017**

== New Features and Enhancements

This version of Anypoint Platform Private Cloud Edition contains the following features and enhancements:

[%header,cols="2*a"]
|===
| Feature | Description

> New Alerting on
 Docker on the host went down
 IPV4 forwarding on the host is off
 Br_netfilter is off
 Etcd is down
 Free space (including /tmp) on the mounts high watermark
 High CPU watermark
 High memory watermark
 Node down or not ready in K8s

> New Self-service operations run book

> Upgraded to Kubernetes 1.7, which has many security related features

> ELK integration is generally available

> AWS support

> 
|===


== Installing

See link:/anypoint-private-cloud/v/1.6/install-workflow[Workflow: Install Anypoint Private Cloud] for information on how to install Anypoint Platform Private Cloud Edition.

== Upgrading to 1.7.0

See link:/anypoint-private-cloud/v/1.7/upgrade[To Migrate to Anypoint Platform Private Cloud Edition] for information on how to upgrade to the current version.

Before upgrading, you must backup your system as described in link:/anypoint-private-cloud/v/1.6/backup-and-disaster-recovery[To Backup and Restore Your System] After the upgrade is complete, perform a restore to return your system to its previous state.

[NOTE]
The procedures for performing a backup and restore have changed in this release. See link:/anypoint-private-cloud/v/1.6/backup-and-disaster-recovery[To Backup and Restore Your System]


== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime | 3.7.x - 3.8.4
| API Gateway Runtime | 2.1.x - 2.2.x
| Runtime Manager Agent | 1.5.2 - 1.5.3
| Infrastructure providers |
* VMWare
* Bare Metal
| Compatible browsers when running the installer |
* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
|===

== Fixed Issues

[%header%autowidth.spread]
|===
|Issue ID |Description 
|TBD | TBD
|===

== Known Issues

[%header%autowidth.spread]
|===
|Issue ID |Description |Workaround
| TBD | TBD | TBD
|===

== Anypoint Platform Features

The following sections outline the Anypoint Platform features and bug fixes added to this version of Anypoint Platform Private Cloud Edition. This information is compiled from the release notes of each platform component.

=== Anypoint Runtime Manager

[%header,cols="2*a"]
|===
| Runtime Manager Release | Features and Issue Fixes
|TBD | TBD
|===

=== Anypoint Exchange

No new features or fixes in this release.

=== Access Management

[%header,cols="2*a"]
|===
|Access Management Release | Features and Issue Fixes
| TBD | TBD
|===

=== API Manager

[%header,cols="2*a"]
|===
|API Manager Release | Features and Issue Fixes
| TBD | TBD
|===

=== API Designer

[%header,cols="2*a"]
|===
|API Designer Release | Features and Issue Fixes
| TBD | TBD
|===
