= Anypoint Partner Manager 1.2.2 Release Notes

== Browser Support

Anypoint Platform (https://anypoint.mulesoft.com) supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

== Compatibility

Compatible with:

* X12 Module 1.2.0
* EDIFACT Module 1.2.0
* Partner Manager Connector 2.0.x
* FTPS Connector 1.0.6
* AS2 Connector 2.0.1

== New Features

* Made import/export/promote jobs asyncronous in background, with update for user in UI when complete
* Extended max length of error message to 5000 characters
* Added an operation to Partner Manager Connector to search for a document definition
* Updated Error Message Pop Up window in Tracking screen to display error messages with multiple lines when new line characters are included in message.
* Added Refresh button to update the dashboard to reflect new transactions
* Added infinite scrolling in Tracking screen grids


== Fixed in this Release

* Various validations and UI enhancements for maintaining Document Types, Maps, Endpoints, Channels, and Routes
* Document Type Screen - CSV options check boxes are not defaulted to checked
* Added message why user can't delete an artifact when it is being referenced by other artifacts.
* Partner list not filtering properly
* If the Error Message is empty (undefined) and the user clicks on that row, the UI goes into a state where it doesn't refresh the right detail panel.
* Replays of replays  in Tracking screen not linking correctly to original transaction



== Deprecated Features or Functionality
Display and search of “Custom Metadata” in B2B Transactions monitoring screen.  Can still be written and can be retrieved using the apis.  Will be brought back to B2B Transactions monitoring screen in future release.


== Known Issues
* On the B2B Transmissions screen, for the Documents View, clicking the Clear Filters button does not clear the filename filter.  Filter can be cleared by manually deleting the text.
* When you click *New Partner* on the Trading Partner page, the Partner page appears; before you can use the left-hand navigation bar, you must type a character in the Company Name box.
* Business Property extraction currently does not work for CSV files.
