= Anypoint Partner Manager Release Notes
:keywords: b2b, partner manager, mule, release notes

*link:/anypoint-b2b/anypoint-partner-manager[Anypoint Partner Manager User Documentation]*

== Version 1.7.0  - December, 2016

=== Version 1.7.0 Browser Support

Anypoint Partner Manager, as a component of link:https://anypoint.mulesoft.com[Anypoint Platform] supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

=== Version 1.7.0 Compatibility

Compatible with:

* X12 Module 1.2.1
* EDIFACT Module 1.2.1
* Partner Manager Connector 3.0.x
* FTPS Connector 1.0.8
* AS2 Connector 2.0.1

=== Version 1.7.0 New Features

* Added validation for Start and Stop dates to custom Date picker in tracking screen
* Added ability to enter custom message type and version for RosettaNet
* Added date options to Overview and Filters for all views
* Added Property Source Type field to Document Properties
* Added support for Context Properties on Endpoints
// * Added support for correlating multiple document exchange in Business Process View to Tracker UI screen
* Enable creation of multiple Maps for same Document Type
* Added auditing for Anypoint Partner Manager


== Version 1.6.0  - December, 2016

=== Version 1.6.0 Browser Support

Anypoint Partner Manager, as part of link:https://anypoint.mulesoft.com[Anypoint Platform] supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

=== Version 1.6.0 Compatibility

Compatible with:

* X12 Module 1.2.1
* EDIFACT Module 1.2.1
* Partner Manager Connector 3.0.x
* FTPS Connector 1.0.8
* AS2 Connector 2.0.1

=== Version 1.6.0 New Features

* Add support for lookup tables

=== Version 1.6.0 Fixed in This Release

* Fixed - Error on Channels Page while choosing map
* Fixed - Validation error during channel creation at partner level when using a document defined at home org level
* Fixed - On Document Definition page, if schema file is already uploaded for a document, the label says no file uploaded and there is no indication that a schema has already been uploaded.
* Fixed - B2B Transactions Overview dashboard does not show correct Transmission/Tracking/Error count

== Version 1.5.0  - November, 2016

=== Version 1.5.0 Browser Support

Anypoint Partner Manager, as part of link:https://anypoint.mulesoft.com[Anypoint Platform] supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

=== Version 1.5.0 Compatibility

Compatible with:

* X12 Module 1.2.1
* EDIFACT Module 1.2.1
* Partner Manager Connector 3.0.x
* FTPS Connector 1.0.8
* AS2 Connector 2.0.1

=== Version 1.5.0 New Features

* Client-side processing of documents - send metadata to Tracking API only (increases processing speed, enhances security)
* Caching of document property information (increases processing speed)
* Support for SMTP, POP3, and IMAP endpoints

=== Version 1.5.0 Fixed in This Release

* Fixed - Issues with creating channels across Home Org and Partners.
* Fixed - Display of long names jumbled in many places across APM system.
* Fixed - No error message if Channel information is provided incorrectly.
* Fixed - No validation or error message is provided preventing creating a duplicate partner.


== Version 1.4.0  - October, 2016

=== Version 1.4.0 Browser Support

Anypoint Partner Manager, as part of link:https://anypoint.mulesoft.com[Anypoint Platform] supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

=== Version 1.4.0 Compatibility

Compatible with:

* X12 Module 1.2.1
* EDIFACT Module 1.2.1
* Partner Manager Connector 3.0.x
* FTPS Connector 1.0.8
* AS2 Connector 2.0.1

=== Version 1.4.0 New Features

• Configuration of persisted message security settings
• Configuration of security settings for http send endpoints
• Configuration of FTP Endpoints
• Configuration of RosettaNet document definitions


== Version 1.3.0  - October, 2016

=== Version 1.3.0 Browser Support

Anypoint Partner Manager, as part of link:https://anypoint.mulesoft.com[Anypoint Platform] supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

=== Version 1.3.0 Compatibility

Compatible with:

* X12 Module 1.2.1
* EDIFACT Module 1.2.1
* Partner Manager Connector 3.0.x
* FTPS Connector 1.0.8
* AS2 Connector 2.0.1

=== Version 1.3.0 New Features

* Configuration of SFTP endpoints
* Configuration of JMS endpoints
* Configuration of custom error codes

=== Version 1.3.0 Fixed in this Release

* Resolve routes not matching partner by ISA identifier

== Version 1.2.2

=== Version 1.2.2 Browser Support

Anypoint Partner Manager, as part of link:https://anypoint.mulesoft.com[Anypoint Platform], supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

=== Version 1.2.2 Compatibility

Compatible with:

* X12 Module 1.2.1
* EDIFACT Module 1.2.1
* Partner Manager Connector 3.0.x
* FTPS Connector 1.0.8
* AS2 Connector 2.0.1

=== Version 1.2.2 New Features

* Made import/export/promote jobs asyncronous in background, with update for user in UI when complete
* Extended max length of error message to 5000 characters
* Added an operation to Partner Manager Connector to search for a document definition
* Updated Error Message Pop Up window in Tracking screen to display error messages with multiple lines when new line characters are included in message.
* Added Refresh button to update the dashboard to reflect new transactions
* Added infinite scrolling in Tracking screen grids


=== Version 1.2.2 Fixed in this Release

* Various validations and UI enhancements for maintaining Document Types, Maps, Endpoints, Channels, and Routes
* Document Type Screen - CSV options check boxes are not defaulted to checked
* Added message why user can't delete an artifact when it is being referenced by other artifacts.
* Partner list not filtering properly
* If the Error Message is empty (undefined) and the user clicks on that row, the UI goes into a state where it doesn't refresh the right detail panel.
* Replays of replays  in Tracking screen not linking correctly to original transaction


=== Version 1.2.2 - Deprecated Features or Functionality

Display and search of “Custom Metadata” in B2B Transactions monitoring screen.  Can still be written and can be retrieved using the apis.  Will be brought back to B2B Transactions monitoring screen in future release.


=== Version 1.2.2 - Known Issues

* On the B2B Transmissions screen, for the Documents View, clicking the Clear Filters button does not clear the filename filter.  Filter can be cleared by manually deleting the text.
* When you click *New Partner* on the Trading Partner page, the Partner page appears; before you can use the left-hand navigation bar, you must type a character in the Company Name box.
* Business Property extraction currently does not work for CSV files.

== Version 1.2.1 Release Notes

=== Version 1.2.1 Browser Support

Anypoint Partner Manager, as part of link:https://anypoint.mulesoft.com[Anypoint Platform], supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

=== Version 1.2.1 Compatibility

Compatible with:

* X12 Module 1.2.0
* EDIFACT Module 1.2.0
* Partner Manager Connector 2.0.x
* FTPS Connector 1.0.6
* AS2 Connector 2.0.1

=== Version 1.2.1 New Features

* Implemented throttling of tracking events to prevent tracking delays
* Added all X12 Versions for Document Definitions
* Added auto-naming to endpoints screen
* Updated TPM UI rules to support configuring routes in external partner with channels from home partner
* Ability to display originalTransactionId in detail pane for replays
* Ability to navigate from replay to original transaction id and all associated replays


=== Version 1.2.1 Fixed in this Release

* Track Document operation no longer fails when you select JSON as type of document
* Prevented user entry of spaces in object names for Partners, Document Types, Maps, Channels, Endpoints, and Routes fields
* Added user message indicating that names for Partners, Document Types, Maps, Channels, Endpoints, and Routes must be unique
* Error tracking message now appears in pop-up modal window


=== Version 1.2.1 Deprecated Features or Functionality

* Display and search of “Custom Metadata” in B2B Transactions monitoring screen.  Can still be written and can be retrieved using the apis.  Will be brought back to B2B Transactions monitoring screen in future release.

=== Version 1.2.1 Migration Guidance

* The following API endpoints for transmissions have been removed.  Applications that depend on these should be re-written to use the /businessDocuments endpoint:
** /ediX12Transmissions
** /edifactTransmissions
** /xmlTransmissions
* The /query API endpoint has been removed.  Applications that depend on this endpoint should be re-written to use the endpoints for specific resources, which have been changed to support the “searchable” trait.

=== Version 1.2.1 Known Issues

* On the B2B Transmissions screen, for the Documents View, clicking the Clear Filters button does not clear the filename filter.  Filter can be cleared by manually deleting the text.
* When you click *New Partner* on the Trading Partner page, the Partner page appears; before you can use the left-hand navigation bar, you must type a character in the Company Name box.
* Business Property extraction currently does not work for CSV files.

== Version 1.0.0 - January 2016


=== Version 1.0.0 Features

* Integration into Anypoint Platform top navigation bar
* Support for Anypoint Permissions, Environments, Business Groups, and Entitlements
* Added *executionId* to expand ability to correlate multiple B2B-related events
* Local caching of Partner Manager settings


For more information, see
link:/anypoint-b2b/anypoint-partner-manager[Introduction to Anypoint Partner Manager].

=== Version 1.0.0 Compatibility

[%header,cols="2*"]
|===
|Application/Service |Version
|Mule Runtime |Mule 3.6.0 and above
|===

== See Also

* link:/anypoint-b2b/anypoint-partner-manager[Introduction to Anypoint Partner Manager]
* link:/anypoint-b2b/anypoint-partner-manager-users-guide[Anypoint Partner Manager User's Guide]
