= Anypoint Exchange Release Notes
:keywords: release notes, exchange

*July 29, 2017*

== Version 2.0.0 - July 29, 2017

We are pleased to announce the general availability of the latest release of Anypoint Exchange. This product enables Anypoint Platform users to publish and access Mule-related content within their own organization increasing visibility and reuse.


=== Compatibility

[%header,cols="30a,70a"]
|===
|Software |Version
|Browsers |

* Chrome (Version 54.0.x) or later
* Firefox  (Version 50.0.x) or later
* Safari (Version 10.1.x) or later
* Internet Explorer 11 
|Anypoint Studio |6.3.0
|===

The new Anypoint Exchange 2 in Anypoint Platform offers a complete rework of Exchange with support for OAS and RAML 1.0 specifications, an improved user interface, a new editor supporting both Visual and Markdown text creation, and the ability to rate assets.

=== Version 2.0.0 - New Features

Anypoint Exchange lets you:

* Store all integration assets in one place in Exchange, such as best practices, integration patterns, API fragments, API specifications, examples, templates, and connectors.
* Enrich portal content using the Visual editor and Markdown editor.
* Quickly upload Open API specifications (Swagger) in Exchange which automatically convert to RAML for use across the Anypoint toolset.
* Quickly upload WSDLs (SOAP APIs) in Exchange.
* Consume and reuse all existing MuleSoft public content in Anypoint Studio and Design Center.
* Collaborate with API owners and designers including the ability to comment and write reviews, ask questions, and provide feedback on each asset.
* Share an asset within a business group with users outside of the business group to drive cross business organization collaboration.
* Auto-generate a Mule 4.0 Design Center connector (using REST Connect) for any valid API specification for use within Design Center.
* View a list of dependencies (API Fragments) for any API specification.
* Version any asset published to Exchange.
* View Dependency Snippet for connectors for use in Maven, Gradle, SBT, and Ivy.
* Publish connector, examples, and templates using Studio 6.2.5.


=== Version 2.0.0 - Known Issues and Limitations

* EXC-1140: Unable to type anything below an image in the Visual editor. Switch to Markdown editor to continue editing.
* EXC-1253: Visual editor is not supported for use with Internet Explorer 11. Use the Markdown editor instead.
* Searching by tag at the user interface only works for the latest asset version. 
* Admin user cannot delete reviews created by other users.
* Rating is not refreshed when a version is deleted.
* Unable to deprecate an asset.
* EXC-1522: Incorrect error message when a user without Exchange Contributor permission within a Business Group tries to create an asset.
* EXC-1269: In Firefox, when a token is expired and user tries to publish to exchange, it throws a 403 error page. Clear cookies for Anypoint Platform and try again.

== Version 1.7.1 - September 2016 Release

This version of Anypoint Exchange fixes internal issues and provides
these two updates:

* The *RAMLs* label is changed to *REST APIs*
* The *WSDLs* label is changed to *SOAP APIs*

== Version 1.7.0 - July 2016 Release

This version of Anypoint Exchange provides new features and fixes.

=== Features

* Connectors linked to from a private Exchange can now be installed in Anypoint Studio.
* Audit Logs now provide Exchange Administrators with a log of all actions that occur in a private Exchange.

=== Fixed Issues

[%header,cols="20a,80a"]
|===
|Issue |Description
|EXCHANGE-1126 |Scope drop-down now shows the Business Group Hierarchy on search and in publish/republish drop-down
|EXCHANGE-1125 |Fix a bug on missing buttons when editing versions
|EXCHANGE-1115 |Improve error messages and avoid data lost during validations
|EXCHANGE-1099 |Scope drop-down now shows the Business Group Hierarchy on search and in publish/republish drop-down
|EXCHANGE-1073 |Fix a bug showing the version header without data and saving an empty version
|EXCHANGE-1072 |Changes the place of back to the list button
|EXCHANGE-1063 |Fix the  item and name inputs on IE when Create/Clone Artifact
|EXCHANGE-1006 |Improve error messages and avoid data lost during validations
|EXCHANGE-872 |Fix a bug showing the version header without data and saving an empty version
|EXCHANGE-809 |Disables the video caption field until you add a video URL
|EXCHANGE-779 |Add a `?` next to itemID with more information
|EXCHANGE-778 |Ad a `?` next to itemID with more information
|===


== Version 1.6.2 - June 2016 Release

This version of Anypoint Exchange provides bug fixes and improvements.

=== Fixed Issues

[%header,cols="25a,75a"]
|===
|Issue |Description
|EXCHANGE-869 |Hide non-relevant calls to actions in Exchange UI when the user launches it from Studio
|EXCHANGE-1038 |Download and docs icons should match the 2.2.1 MuleSoft styles
|EXCHANGE-1096 |Fix issue with removing filter terms (tags) from search results when the tag filter is launched from the item detail page
|EXCHANGE-1106 |All link versions wrongly point to only to the first version of the artifact
|EXCHANGE-1112 |User needs to update page to see the download icon when adding versions on an artifact
|===

=== Improvements

[%header,cols="25a,75a"]
|===
|Issue |Description
|EXCHANGE-553 |Simplify the artifact's share URL by removing "/mulesoft" from the path
|EXCHANGE-1086 |MuleSoft tag should not be displayed for anonymous users
|EXCHANGE-1087 |The focus should return to the beginning of the list when the user returns to search results from the detail page
|EXCHANGE-1088 |Remove Exchange settings from Anypoint Platform Access Management
|EXCHANGE-1094 |Instead of displaying the main organization name, display "Master Organization" in the Publish/Republish dropdown
|EXCHANGE-1104 |Refactor how pre-defined search terms are treated in the backend to improve performance
|===

== May 2016 Release

This new version of Anypoint Exchange includes new features & functionality for addressing the viewing and publishing of artifacts across a hierarchical organization structure. Also within this version of Exchange aligns with the Anypoint Platform Styles and use of the new Nav Bar.

=== Features and Functionality

The following sections describe the new features in this release.

==== Visual Enhancements

Alignment with the Anypoint Platforms Styles and Integration with the latest Anypoint Platform Navigation Bar.

==== Roles for Exchange

Besides the existing Organization Owner, Contributor and Administrator Roles, a separate Viewer role was created.

==== New State and Flow Transition of an Artifact

To address the movement of an artifact across a hierarchical structure, Exchange now provides new states for an artifact and also specific actions to be performed on them.

==== Business Groups

Business Groups are being incorporated in Exchange . This feature across with the Exchange Roles and the new state transition flow of an artifact provides:

* Ability of Central IT (maybe the root organization) to create artifacts and make them available to all Lines of Businesses (business groups)
* Ability of Central IT to locate artifacts published in a business group and make it available to the rest of the business
* Ability of an LOB to publish artifacts for internal (to that business group) consumption

==== UI and UX Improvements

New Filters and actions now support the new Business Groups, Artifacts States, and Transition Flows functionalities.

==== Edit Types Removal

Edit Terms only available on Master Organization for Admin and Owner Organization

==== API Changes

Before this release, Exchange used an internal Organization ID in the API resource, but this organization ID is replaced with the Core Services Organization ID to allow Business Groups.
New endpoints are being incorporated in Exchange to work with Business Groups.
New permissions are applied using the Business Groups hierarchy.

==== Avoid Losing User Data

When a session expires, Exchange prompts for credentials and completes the action.
Exchange now displays a warning when a user tries to leave the edit page if there are unsaved changes.

=== Removed Features

* The object amount limitation for private tenants has been removed. The possibility to request to increase the object amount limit it’s already removed from the Exchange configuration in Anypoint Platform access management.
* The possibility to edit types was removed, all organizations now share the same types.
* The feature to edit terms can now only be enabled for users with Admin roles in master organizations.

=== Architecture Changes

* Split UI from backend in different servers and all the related changes to fulfill this Architecture change.
* Update Node.js version to v4.

== Dec 2015 Release

=== Dec 2015 Features and Functionality

This Anypoint Exchange release includes the following new features and functionality:

* WSDL Support: At the moment WSDL type does not have a Studio integration, however WSDLs can be added and managed via web UI.

* Visual enhancements such as new colors for item types and UX improvements.

* Auto-populated URI when creating new items.

* Automatically resizable description container when editing content.

* Firefox and Internet Explore 11 bugs fixed.

=== Dec 2015 Known Limitations

The version of the exchange available with the on-premises installation of the Anypoint Platform comes with an empty library of content, you must populate it with your own content.

== May 2015 Release

=== May 2015 Features and Functionality

This Anypoint Exchange release includes the following new features and functionality:

* Ratings: All content has a rating associated to it. Users can rate only from Exchange in Anypoint Studio (Connectors need to be installed in Studio in order to rate them). Objects have their rating displayed only when they have two ratings or more.

* Author: Objects can have the author’s name and photo. This can be used for partners or community contributors. This section is hidden if not filled out.

* UI Refresh: Object type indicators have been improved . Text areas and button sizes have changed to improve readability

=== May 2015 Known Limitations

To access private content from Anypoint Studio, version 4.2.0 or newer must be used.

== February 2015 Release

=== February 2015 Features and Functionality

This Anypoint Exchange release includes the following new features and functionality:

* Create and Publish private content: Choose between a variety of content types (templates, examples, connectors, etc) to add, describe your asset and publish it in your organization’s exchange. Only the people you choose may have access to create and publish new content.

* Search for Content: Users within your organization can find the internally published content (as well as MuleSoft’s public content), increasing the chance of reuse and avoiding redundant work.  Exchange Admins can customize search filters to make internal content easier to find.

* Seamless Anypoint Studio Integration: Access your private content seamlessly from Anypoint Studio.  You can open templates or install connectors by opening Anypoint Exchange from Studio and logging into your Anypoint Platform account.

=== February 2015 Known Limitations

To access private content from Anypoint Studio, version 4.2.0 or newer must be used.

== Support

If you need help using the product, refer to the documentation for the link:/getting-started/anypoint-exchange[Anypoint Exchange]. If you have additional questions or want to report a problem, Contact MuleSoft.

== See Also

* link:https://www.mulesoft.com/exchange#!/[Anypoint Exchange]




