= Anypoint Platform Private Cloud Edition 1.5.1 Releae Notes
*February 27, 2017*

[WARNING]
This product was previously named Anypoint Platform On-Premises Edition. Beginning with the 1.5.1 release, it is named Anypoint Platform Private Cloud Edition. For the Release Notes of previous  

= New Features and Functionality

The following sections outline the new features and enhancements added to this release.

== Security Improvements

* Improves docker app execution security when running as root
* Provides support for the latest Runtime Manager Agent which includes security fixes

== General Improvements

* Provides support for CentOS / and Red Hat Enterprise Linux (RHEL) 7.3
* Provides unified SMTP configuration for Runtime Manager and API Platform alerts
* Improves backup error reporting

== Management Platform Monitoring Capabilities

* Adds a monitoring dashboard to the Ops Center
* Improves the dashboard for viewing the object store, pods, database and services

== Enhanced Installer

* Adds support for 3 and 6 node configurations
* Enables the installer to perform automatic checking and validation, including disk and network verification
* Provides out-of-the-box scaling
* Provides an embedded LDAP server for demo and testing
* Improves diagnostic error reporting during installation failure
* Creates a default Ops Center admin user during installation

== Stability

* Enables the Cassandra database to peform periodic repair

== Issue Fixes

* journald is restarting causing iptables to be broken and traffic stopped floating through. 
* Multiple localhost hostnames entries causing installer failure
* Ignored localhost /etc/hosts entry
* PostgreSQL restart causing stale replica being elected
* NodeJS for API Platform updated to 4.6.1 version to include the latest security fixes.
* Problem that prevents enabling API Analytics
* Solves disclaimer javascript errors in IE 11
* Solves invalid URL error rendering  in API Platform on scenarios of wrong address
* Mule-message-processor and amc-facade logs now collected in OpsCenter
* Runtime Manager server alerts is a Cloud feature still not supported in Private Cloud. The fix removes the configuration of this type of alerts in Runtime Manager console.
* Fix custom policies support policy dependencies

== Known issues

[%header%autowidth.spread]
|===
|Issue ID |Description |Workaround
|AOP-510 | ARM Alerts should not show CPU and Memory based Alerts on Server|
|AOP-525 | Enable TLS connection between API platform and RAML mocking services |
|AOP-560 | Do lazy initialization of Database Pool |
|AOP-518 | Updating license takes about 2 minutes to refresh |
|===

