= Anypoint Platform - EU Control Plane, December 15 2017 Release Notes

This document describes new features and enhancements, known limitations, issues, and fixes in EU Control Plane. 

== New Features and Enhancements

Beginning on December 15, 2017 the Anypoint Platform control plane is available in the European Union. This enables all customer and MuleSoft data to be transmitted and stored entirely within the EU. 

This release includes the following new features and enhancements:



== Changes in This Release 

* New URL
* Must have an account on the EU Control Plane
* Fewer runtimes supported

== Fixed Issues

There are no fixed issues in this release.

== Known Limitations and Workarounds

This section lists known limitations and workarounds for this release.

* Public exchange is not fully supported in this release. Although certain public assets are available in the EU Control Plane, the full set of public assets are not available.
+
To take advantage of assets available in the public portal of the US Control Plane copy those assets to a private portal within the EU control plane. Private portals are fully supported in the EU Control Plane.

* Partner manager
* Nexus
* Forums
* Community Crowd
* JIRA
* Salesforce Support
* Global CloudHub
* Data Gateway
* Only Object Store v2 is supported.

== Upgrade Requirements

There are no upgrade requirements in this release.

== Compatibility Notes

* Mule Runtime
+
When deploying an application to CloudHub in the EU Control Plane, only the following versions of the Mule runtime are supported:
+
** 3.8.5
** 3.9.0
** 4.0.0
** API Gateway 2.2.0

* Runtime Manager Agent
+
** Need to follow up with Martin **

* Studio
+
** List supported version of Studio