= Anypoint Object Store v2 Release Notes
:keywords: osv2, release notes, object store v2, object, store, v2

*January 2018*

The Anypoint Object Store v2 release allows applications and users to share data and share states across batch processes, Mule components, and multiple distributed applications.

== Version 2.3.0 - January 27, 2018

The Object Store v2 is now GA and suitable for both test and production applications.  This new service is a re-architecture of the current Runtime Manager object store with a focus on performance, scalability, and data privacy.  Customers now have the option to select Object Store v2 as a configuration option in the Runtime Manager application deployment settings.

Object Store v2 is supported in the following locations.

Note: If OSv2 is not supported in a region, OSv2 transparently maps to the closest location.

Supported regions:

* ap-northeast-1
* ap-southeast-1
* ap-southeast-2
* ca-central-1
* eu-central-1
* eu-west-1
* eu-west-2
* sa-east-1
* us-east-1
* us-west-2

=== Version 1.0 - Compatibility

Anypoint Object Store v2 works with Mule 3.7.3 and later, and Mule 4 and later.

Anypoint Object Store v2 works with these browser versions:

* Chrome - Version 34 or later
* Firefox - Version 29 or later
* Internet Explorer - Version 10 or later
* Safari - Version 7 or later

== See Also

* link:/object-store/index[Object Store v2]
* link:/release-notes/objectstore-release-notes[Object Store Connector Release Notes]
