= Anypoint Connector DevKit 3.9.x Release Notes
:keywords: devkit, release notes, jdk8, connector

link:/anypoint-connector-devkit/v/3.8[Anypoint Connector DevKit Guide]

== Version 3.9.0 New Features

Anypoint Connector DevKit 3.9.0 supports two new features for DevKit-built connectors, as well as several fixes for earlier versions.

Building a connector using DevKit 3.9.0 (i.e. specifying this version number in the connector project's `pom.xml`) allows the connector end user to retrieve information about the connector's `@Processor`(s) in the Mule Debugger in Anypoint Studio.

This version also allows the developer to package multiple sets of connector icons to be presented in Studio UI Visual Editor depending on connector end user's preference of Studio UI.

== Version 3.9.0 Compatibility

DevKit version 3.9.0 is compatible with:

[width="100%",cols="50a,50a",options="header"]
|===
|Software|Version
|Mule Runtime|3.8.0 or later
|Anypoint Studio |*Debugging support for DevKit-built connector*:

* Studio 6.0.0 and later

*Support for multiple Studio theme DevKit-built connector icons*:

* Expected for Studio 6.0.2 and later
|===

== Version 3.9.0 - Fixed Issues

This release includes several fixes:

* DevKit now correctly sets category, instead of setting it to `DEFAULT`, when building `DefaultComposedMetaDataKey` from `MetaDataKey`
* Supports connector icons for Anypoint Studio's "Light" Theme, along with the "Classic" theme
