= Anypoint Exchange Release Notes
:keywords: release notes, exchange

*June 24, 2017*

We are excited to announce the final beta availability of the latest release of Anypoint Exchange. This product enables Anypoint Platform users to publish and access Mule-related content within their own organization increasing visibility and reuse.

*Guide:*
link:https://beta-anypt.docs-stgx.mulesoft.com/anypoint-exchange[Anypoint Exchange 2 - Beta]

*See Also:*

* link:/anypoint-exchange/ex2-rest-connect-faq[REST Connect FAQ]
* link:/release-notes/rest-connect-release-notes[REST Connect Release Notes]

== Version 2.0.0 - Beta - June 24, 2017

The new Anypoint Exchange 2 - Beta in the Anypoint Platform offers a complete rework of Exchange with support for OAS and RAML 1.0 specifications, an improved user interface, a new editor supporting both WYSIWYG and Markdown text creation, and the ability to rate assets.

== New Features in Final Beta

* Visual Editor:
** You can add images from URLs and links.
** Fix to support code blocks.
** Fixes to not lose edits made while switching from WYSIWYG to Markdown editor or vice versa.
* Internet Explorer 11 support.
* Publishing an asset:
** Improved speed of publication and fixed a timeout bug when publishing large OAS files.
** Validation for file extension for WSDL and OAS assets during manual upload.
** Improved user experience on draft and publication workflows.
** You can edit asset name after publication.
** You can now edit or delete your reviews.
** Support for auto-generation of a Connector using Mule-Plugin when a valid API specification is published to Exchange for used within the flow designer. 
** You can delete an asset after publishing within 24 hours as long as the asset is not used as dependency by some other asset.
** Improved publication from API designer to Exchange.
* Support for Exchange Viewer role to allow read-only view to Exchange and able to read and consume an asset.
* Support for API version of assets for API Specifications from RAML and OAS.

== Known Issues

* Non-descriptive error message when uploading an asset with same name in same business group. 
* Unable to redirect to login page when authentication token is expired. 
* Unable to type anything below the image in portal editor. 
* WYSIWYG editor not displayed in Internet Explorer 11.
* Searching by tag at the UI only works for the latest asset version.
* When creating an asset within a Business Group, an error messages may display `"{"name":"Bad Gateway","status":502,"message":" {\"message\":\"500 Internal Server Error\"}`
* Admin user cannot delete reviews created from other users.

