= Anypoint Visualizer Version 1.0.0 Release Notes

_June 30, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes for Anypoint Visualizer, version 1.0.0.

== New Features and Enhancements

This is the initial release of Anypoint Visualizer. Anypoint Visualizer provides a graphical representation of the APIs, and Mule applications, and third-party systems within your application network.

See link:/anypoint-visualizer[Anypoint Visualizer] for more information.

== Changes in This Release

This release contains no feature changes.

== Fixed Issues

There are no fixed issues in this release.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

To use Anypoint Visualizer, you must deploy you application to a supported version of Mule Runtime on CloudHub.

== Compatibility Notes

Anypoint Visualizer supports the following Mule runtimes running on CloudHub:

* Mule Runtime, version 3.9.x
* Mule Runtime, version 4.1.x

**Note**: Applications using supported runtimes before June 30th, will have to update the runtime, which can be done with 0-downtime for CloudHub applications, APIs and proxies.