= Anypoint Platform Private Cloud Edition 1.6.0 Release Notes

**June 2, 2017**

== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime | 3.7.x - 3.8.x
| API Gateway Runtime | 2.1.x - 2.2.x
| Runtime Manager Agent | 1.5.2 and later
| Infrastructure providers |
* VMWare
* Bare Metal
| Compatible browsers when running the installer |
* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
|===


== Feature Enhancements

**Need to add content here**

== Security Enhancements

== Fixed Issues

**Need to add content here**

== Known Issues

[%header%autowidth.spread]
|===
|Issue ID |Description |Workaround
|AOP-1295 |Kapacitor is not restarted when SMTP config is changed.
|AOP-1285 |In Demo deplyment, LDAP admin application is not started in documented port
|AOP-1143 |Connection with Redis, API Manager Cache, is not encrypted
|===

== Anypoint Platform Features

The following sections outline the Anypoint Platform features and bug fixes added to this version of Anypoint Platform Private Cloud Edition. This information is compiled from the release notes of each platform component.

=== Anypoint Runtime Manager

[%header,cols="2*a"]
|===
| Runtime Manager Release | Features and Issue Fixes
|2.1.0 |
* Improves support for promotion of hybrid applications between environment from the UI
* Adds ability to enable and disable insights at deployment time for hybrid applications
* Adds ability to configure the log levels at deployment time for hybrid applications
|2.0.0 | 
* Enhances flow management by providing the ability to manage their problematic flows at runtime. You can disable a flow without disrupting the entire application.
* Suppoorts flow management, v2.0 functionality.
|===

=== API Manager

[%header,cols="2*a"]
|===
|API Manager Release | Features and Issue Fixes
|1.14.4 |

* Adds pagination on the custom policies page.
* Increases granularity of the Rate Limiting and Throttling policy configuration.
* Adds ability to specify multiple throughput limits for an SLA tier using different time periods and units.
|1.14.2 |

* Fixed the View Application link that was not working with Runtime Manager.
* Fixed the client secret on the developer portal applications detail page.
* Fixed the link on the notification email when a new application is pending approval and the API belongs to a sub-organization.
* Fixed an issue with uppercase WSDL on SOAP proxies.
* Fixed the Basic Authentication template that was not working properly with Mule Runtime 3.8.1 and later when HTTP is used for LDAP instead of HTTPS.
|1.14.1 |

* API Manager 1.14.1 includes the following new features:
* An advanced configuration to customize the response timeout of the auto-generated proxy.
* To customize the response timeout of the deployed proxy, use the advanced options as described in step 5-h of section "Setting up a Proxy".
* Fixed auto-generated proxy that was configured to an incorrect WSDL.
* Fixed problems with import/export of an API on Windows.
* API Designer 0.3.0 support
|1.14.0 |

* Updated the clients API to show multiple owners as well as the app ID.
* Added a new API to query by client ID.
* Fixed API Tooling bugs to support new API tooling.
* Added performance enhancements
|1.13.0 |

* Added ability to enable and disable policies.
* Fixed bugs to support new API tooling. 
* Improved support for dependencies between configurable policies using the required characteristics parameter.
|===

=== Anypoint Exchange

No new features or fixes in this release.

=== Access Management

[%header,cols="2*a"]
|===
|Access Management Release | Features and Issue Fixes
|0.20.0 | 

* Added support for the client UI configuration forms for PingFederate and OpenAM.
|0.16.0 | 

* Access Management v0.16 enables organization administrators and audit log viewers to see entitlement changes to their organization from the Audit Logs UI. 
* Added support for Ping Federate v8.2.1.1 for External Identity.
|===



