= Anypoint Partner Manager 1.2.1 Release Notes

== Browser Support

Anypoint Platform (https://anypoint.mulesoft.com) supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

== Compatibility

Compatible with:

* X12 Module 1.2.0
* EDIFACT Module 1.2.0
* Partner Manager Connector 2.0.x
* FTPS Connector 1.0.6
* AS2 Connector 2.0.1

== New Features

* Implemented throttling of tracking events to prevent tracking delays
•	Added all X12 Versions for Document Definitions
•	Added auto-naming to endpoints screen
•	Updated TPM UI rules to support configuring routes in external partner with channels from home partner

== Fixed in this Release

•	Track Document operation no longer fails when you select JSON as type of document
•	Prevented user entry of spaces in object names for Partners, Document Types, Maps, Channels, Endpoints, and Routes fields
•	Added user message indicating that names for Partners, Document Types, Maps, Channels, Endpoints, and Routes must be unique

== Deprecated Features or Functionality
* Display and search of “Custom Metadata” in B2B Transactions monitoring screen.  Can still be written and can be retrieved using the apis.  Will be brought back to B2B Transactions monitoring screen in future release.

== Migration Guidance
* The following api endpoints for transmissions have been removed.  Applications that depend on these should be re-written to use the /businessDocuments endpoint:
** /ediX12Transmissions
** /edifactTransmissions
** /xmlTransmissions
* The /query api endpoint has been removed.  Applications that depend on this endpoint should be re-written to use the endpoints for specific resources, which have been changed to support the “searchable” trait.

== Known Issues
* On the B2B Transmissions screen, for the Documents View, clicking the Clear Filters button does not clear the filename filter.  Filter can be cleared by manually deleting the text.
* When you click *New Partner* on the Trading Partner page, the Partner page appears; before you can use the left-hand navigation bar, you must type a character in the Company Name box.
* Business Property extraction currently does not work for CSV files.
