= Anypoint Platform Command Line Interface Release Notes
:keywords: cli, command line interface, command line, release notes, anypoint platform cli

== Version 1.1.0 - January 10, 2017

This release of the Anypoint Platform CLI introduces link:/runtime-manager/anypoint-platform-cli#list-of-commands[support for API Manager commands] and a lot of API lifecycle/promotion scenarios.

It also introduces new features such as:

* Support for API Manager, including managing APIs, policies, definitions, portals, client applications, and more.
* Copying API definitions, portals, and policies from one API for another for easy promotion
* More control over the CLI output:
** Ability to format the output in plain text, JSON or tables.
** Ability to specify the fields you want the output to display.
* Improved security allowing your interactive mode session to expire based on your configuration on Anypoint Platform.
* Support for Anypoint Platform On-Premises Edition

See the link:link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI documentation] for more details.
