= Anypoint Platform Command Line Interface Release Notes
:keywords: cli, command line interface, command line, release notes, anypoint platform cli



== Version 1.1.4 - March 15, 2017

This release of the Anypoint CLI fixes the following issues:

* `runtime-mgr application download-logs` not working properly on Windows/Linux
* `--fields <field_list>` option returns misleading warning

== Version 1.1.3 - February 25, 2017

This release of the Anypoint CLI fixes the following issues:

* `runtime-mgr application restart` throws an error in non-interactive mode
* Some arguments should not be converted to integers

See the link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI documentation] for more details.


== Version 1.1.2 - January 10, 2017

This release of the Anypoint Platform CLI introduces link:/runtime-manager/anypoint-platform-cli#list-of-commands[support for API Manager commands] and a lot of API lifecycle/promotion scenarios.

It also introduces new features such as:

* Support for API Manager, including managing APIs, policies, definitions, portals, client applications, and more.
* Copying API definitions, portals, and policies from one API to another for easy promotion
* More control over the CLI output:
** Ability to format the output in plain text, JSON or tables.
** Ability to specify the fields you want the output to display.
* Improved security
// ** Your interactive mode session asks for credentials renewal after the current session expires based on your configuration on Anypoint Platform.
* Support for Anypoint Platform Private Cloud Edition

See the link:/runtime-manager/anypoint-platform-cli[Anypoint Platform CLI documentation] for more details.
