= Anypoint Platform Private Cloud Edition 1.6.0 Release Notes

**May 31, 2017**

== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime | 3.7.x - 3.8.x
| API Gateway Runtime | 2.1.x - 2.2.x
| Runtime Manager Agent | 1.5.2 and later
| Infrastructure providers |
* VMWare
* Bare Metal
| Compatible browsers when running the installer |
* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
|===


== Feature Enhancements

**Need to add content here**

== Security Enhancements

== Fixed Issues

**Need to add content here**

== Known Issues

**Need to add content here**

== Anypoint Platform Features

The following sections outline the Anypoint Platform Features added to Anypoint Platform Private Cloud Edition, version 1.6.

=== Anypoint Runtime Manager

[%header,cols="2*a"]
|===
|Runtime Manager Release |Feature Added
|2.1.0 |
* Improved support for promotion of hybrid applications between environment from the UI
* Capability to enable and disable insights at deployment time for hybrid applications
* Capability to configure the log levels at deployment time for hybrid applications
* CHHYBRID-2542 Deployment partially persisted
* CHHYBRID-2386 Enhance performance of the Audit Logging Aspect
* CHHYBRID-2517 Add request tracing logging to the Hybrid-Console
|2.0.0 | 
* Flow Management: Users will have the ability to manage their problematic flows at runtime. They can now just disable a flow without disrupting the entire application.

* Flow management V2.0 functionality is available for integration applications.
|===

=== API Manager

[%header,cols="2*a"]
|===
|API Manager Release |Feature Added
|1.14.4 |

* Added pagination on the custom policies page.
* Increased granularity of the Rate Limiting and Throttling policy configuration.
* You can now specify multiple throughput limits for an SLA tier using different time periods and units.
|1.14.2 | Resolved Issues:

* Fixed the "View application" link that wasn’t working with Runtime Manager.
* Obfuscated the client secret on the developer portal applications detail page.
* Fixed the link on the notification email when a new application is pending approval and the API belongs to a sub-organization.
* Fixed an issue with uppercase WSDL on SOAP proxies.
* Fixed the Basic Authentication template that was not working properly with Mule Runtime 3.8.1 and later when HTTP is used for LDAP instead of HTTPS.
|1.14.1 | New features:

* API Manager 1.14.1 includes the following new features:
* An advanced configuration to customize the response timeout of the auto-generated proxy.
* To customize the response timeout of the deployed proxy, use the advanced options as described in step 5-h of section "Setting up a Proxy".

Resolved Issues:

* Fixed auto-generated proxy that was configured to an incorrect WSDL.
* Fixed problems with import/export of an API on Windows.
* API Designer 0.3.0 support
|1.14.0 | Resolved Issues and Improvements

* Updated the clients API to show multiple owners as well as the app ID.
* Added a new API to query by client ID.
* Fixed API Tooling bugs to support new API tooling.
* Enhanced performance
|1.13.0 | New Feature

* API Manager 1.13.0 includes the capability to enable and disable policies.

Resolved Issues and Improvements

* API Manager 1.13.0 fixes API Tooling bugs to support new API tooling. API Manager has been improved to support dependencies between policies that you configure using the required characteristics parameter.
|===


=== Access Manager

0.20 Through a new UI for external identity configurations, this release also brings the client UI configuration forms for PingFederate and OpenAM into the platform.

October 22, 2016
Version 0.16.0

Access Management v0.16 allows Organization administrators and Audit Log Viewers to view entitlement changes to their organization from the Audit Logs UI.

Additionally, Access Management now supports Ping Federate v8.2.1.1 for External Identity.

