= Anypoint Platform July and November Release: Release Notes

This topic describes the major feature enhancements added for the July and November releases of Anypoint Platform.

* Anypoint Exchange
+
** July Release: Provides full integrated with all components of Anypoint Design Center. Updates also include repository capabilities, comments/feedback form for assets, and a new platform API for search.  
+
** Nov Relese: Unifies Anypoint Exchange and API portals, making Exchange the place to manage and share all reusable assets, whether for internal or external use. This update also brings the following tools into Exchange:  
+
*** API console: Adds a new UI, providing a Postman-like experience for consuming and testing APIs. 
+
*** Mocking service: Automatically creates an API endpoint for RAML and OAS specifications published to Exchange, allowing the API to be tested without having to implement it. 
+
*** API notebook: Introduces the ability to add API Notebook snippets into content pages within Anypoint Exchange. 

* Anypoint Design Center - Flow Designer Editor
+
** July Release: Introduces a new Web-based integration flow designer for ad hoc integrators, who need a simple tool for accomplishing basic integration tasks.

* Anypoint Design Center’s API designer
+
** July: Updated to enable discovery, saving and reuse of API fragments and API specs possible from within API designer through integration with Exchange.  
+
** Nov: A new visual editor for APIs, allowing users to design API specs without the need to understand RAML or API design principles.   

* API Manager
+
** November Release: Adds support for environments and the ability to promote APIs through different environments
Integration with Exchange for automatic update of API endpoints and easier management of APIs

== See Also

* link:/getting-started/api-lifecycle-overview[About Availability of the November Release]
* link:/release-notes/design-center-release-notes#1-2-november-18-2017[Design Center Release Notes]
* link:/release-notes/anypoint-exchange-release-notes[Anypoint Exchange Release Notes]
* link:/release-notes/api-manager-release-notes[API Manager Release Notes]
* link:/release-notes/access-management-release-notes[Anypoint Access Management Release Notes]
* link:/release-notes/runtime-manager-2.6.1-release-notes[Runtime Manager v2.6.1 Release Notes]