= Anypoint Partner Manager 1.2.0 Release Notes

== Browser Support

Anypoint Platform (https://anypoint.mulesoft.com) supports the following browsers:

* Firefox (latest version)
* Chrome (latest version)

== Hardware and Software Requirements
Mule 3.7.3

== Compatibility

Compatible with:

* X12 Module 1.2.0
* EDIFACT Module 1.2.0
* Partner Manager Connector 1.1.0
* FTPS Connector 1.0.5
* AS2 Connector 2.0.1

== Features and Functionality

=== New Features or Functionality
* Re-designed B2B Transaction monitoring page for improved search and navigation
* Managing schemas, maps, endpoints, and routes to support dynamic custom processing of messages for different partners
* Improved support for non-EDI formats - XML, CSV, JSON
* Import/Export/Promotion of Partner Settings

=== Deprecated Features or Functionality
* Display and search of “Custom Metadata” in B2B Transactions monitoring screen.  Can still be written and can be retrieved using the apis.  Will be brought back to B2B Transactions monitoring screen in future release.
* The following api endpoints have been removed

== Migration Guidance
* The following api endpoints for transmissions have been removed.  Applications that depend on these should be re-written to use the /transmissions endpoint:
   * /ediX12Transmissions
   * /edifactTransmissions
   * /xmlTransmissions
* The /query api endpoint has been removed.  Applications that depend on this endpoint should be re-written to use the endpoints for specific resources, which have been changed to support the “searchable” trait.

== Known Issues
* On the B2B Transmissions screen, for the Documents View, clicking the Clear Filters button does not clear the filename filter.  Filter can be cleared by manually deleting the text.
* When you click *New Partner* on the Trading Partner page, the Partner page appears; before you can use the left-hand navigation bar, you must type a character in the Company Name box.

== Support
No Change
