= Anypoint Platform Private Cloud Edition 1.6.0 Release Notes

**May 31, 2017**

== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime | 3.7.x - 3.8.x
| API Gateway Runtime | 2.1.x - 2.2.x
| Runtime Manager Agent | 1.5.2 and later
| Infrastructure providers |
* VMWare
* Bare Metal
| Compatible browsers when running the installer |
* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
|===


== Feature Enhancements

**Need to add content here**

== Fixed Issues

**Need to add content here**

== Known Issues

**Need to add content here**

== Anypoint Platform Features

The following sections outline the Anypoint Platform Features added to Anypoint Platform Private Cloud Edition.

=== Anypoint Runtime Manager

==== Runtime Manager 2.2.0

Flow Monitoring: Users now have the ability to monitor key metrics in each Mule flow over time with the help of monitoring charts for flow metrics. This release includes metrics for:

* Mule messages
* Errors
* Response time

==== Runtime Manager 2.1.0

This release introduces the following capabilities:

Improved support for promotion of hybrid applications between environment from the UI

Capability to enable and disable insights at deployment time for hybrid applications

Capability to configure the log levels at deployment time for hybrid applications

CHHYBRID-2542 Deployment partially persisted

CHHYBRID-2386 Enhance performance of the Audit Logging Aspect

CHHYBRID-2517 Add request tracing logging to the Hybrid-Console

==== Runtime Manager 2.0.0

Insight for Hybrid Users: Insight gives users the ability to troubleshoot their applications for performance and health related issues at a granular level, thus enabling users to determine the root cause of an issue quickly and efficiently. This is now available for all users.

Flow Management: Users will have the ability to manage their problematic flows in runtime. They can now just disable a flow without disrupting the entire application.

Monitoring V2.0: This release contains granular monitoring charts for metrics that are pertinent to On-Premises servers and are hence used by Hybrid users.
The new charts include:

Garbage Collection

Heap/Non-Heap

Load average

Thread count.

Additionally alerts have been set for Load Average and Thread count.

Flow management and monitoring V2.0 functionality is only available for integration applications deployed On-Premises, but management occurs through a cloud console.


==== Runtime Manager 1.5.1

Resolved Issues

Several Application/Server dashboards enhancements

CHHYBRID-1954 - New timepicker in the applications tab of SG/Cluster Dashboard

CHHYBRID-1957 - Increase applications and targets timeouts

CHHYBRID-1956 - Fix "Last updated" label style in latest Chrome version

CHHYBRID-1968 - Alerts now have links to the pertinent dashboards

CHHYBRID-1961 - Ability to filter per resource type in alert conditions

CHHYBRID-1980 - Warning in server group/Cluster page if the plugins are incompatible

=== Anypoint Exchange

=== API Manager

==== Browser Support

Anypoint Platform (https://anypoint.mulesoft.com) supports the following browsers:

Firefox (latest version)

Chrome (latest version)

Internet Explorer 11 and newer

==== API Manager 1.15.0

In this release, the invalid console path generated for RAML proxies with paths ending with /* was fixed. This release includes the following enhancements:

Resource Level Policies

Layout Changes

Display OAuth Grant Types

Resource Level Policies
This feature provides the flexibility to apply policies to specific resources and/or methods of an API instead to the entire API. This feature is enabled only for RAML-based APIs or proxies. For more information, see "About Resource Level Policies" and "To Apply Policies and SLA Tiers."

Custom policies require changes to enable Resource Level granularity. For more information, see "To Add Resource Level Policy Support to a Custom Policy."

Layout Changes
This release includes layout changes to improve the user experience and align the UX with the rest of the platform.

Display OAuth Grant Types
Now, the OAuth Grant Types of the application are shown on the application detail page and for the API Owner at the time of approving an access request.


==== API Manager 1.14.4

This release introduces the following enhancements:

Added pagination on the custom policies page.

Increased granularity of the Rate Limiting and Throttling policy configuration.

You can now specify multiple throughput limits for an SLA tier using different time periods and units.

==== API Manager 1.14.2

Resolved Issues
Fixed the "View application" link that wasn’t working with Hybrid.

Obfuscated the client secret on the developer portal applications detail page.

Fixed the link on the notification email when a new application is pending approval and the API belongs to a sub-organization.

Fixed an issue with uppercase WSDL on SOAP proxies.

Fixed the Basic Authentication template that was not working properly with Mule Runtime 3.8.1 and later when HTTP is used for LDAP instead of HTTPS.

==== API Manager 1.14.1 

New Features
API Manager 1.14.1 includes the following new features:

The capability to set alerts for policy violations, response time, count, and codes.

An advanced configuration to customize the response timeout of the auto-generated proxy.

To customize the response timeout of the deployed proxy, use the advanced options as described in step 5-h of section "Setting up a Proxy".

Resolved Issues
Fixed auto-generated proxy that was configured to an incorrect WSDL.

Fixed problems with import/export of an API on Windows.

API Designer 0.3.0 support

=== API Manager 1.14.0

Resolved Issues and Improvements
Updated the clients API to show multiple owners as well as the app ID.

Added a new API to query by client ID.

Fixed API Tooling bugs to support new API tooling.

Made performance improvements.

=== API Manager 1.13.0

This release includes a new feature, an improvement, and bug fixes.

New Feature
API Manager 1.13.0 includes the capability to enable and disable policies.

Resolved Issues and Improvements
API Manager 1.13.0 fixes API Tooling bugs to support new API tooling. API Manager has been improved to support dependencies between policies that you configure using the required characteristics parameter.

=== API Manager 1.12.0

This release includes bug fixes and a security improvement related to Regular expression Denial of Service (ReDoS).

Resolved Issues
API Manager 1.12.0 resolves the following issues:

In previous releases, all apps appeared in the Developer Portal to users in the Organizational Administrator role. Now, users in this role see only their own apps.

An incomplete URL of an app deployed to CloudHub appeared on the API Version details page. The URL now includes the AWS region of deployment.

The error message associated with a URI conflict during auto-discovery API deployment has been improved and now returns the appropriate HTTP error code.

Mule Runtime 3.8.1 now supports the configuration of scopes for the OpenAM token enforcement policy.

The Anypoint Platform UI indicated the 3.8.0 version of Mule. Now, the UI indicates 3.8.x.

The Client ID Enforcement policy problem that occurred during migration from API Gateway 2.2.0 or earlier to Mule 3.8.1 has been resolved.

