= Anypoint Studio 7.1 EA with Mule Runtime 4.1.0 Release Notes

*Janaury 29, 2018* +
*Build ID: 201801301552*

xref:migration[Skip to Migration Guide]

== Compatibility

[cols="30a,70a"]
|===
| Product | Version
| *Mule Runtime*
| Version: 4.1.0 EA

|*Anypoint Studio*
|Version: 7.1.0 EA +
Build Id: 201801301552

|*Maven*
|Version: 3.3.9

|*DataWeave* +
|Version: 2.0.0

|*MUnit* +
|Version: 2.0.0 (munit-studio-plugin)

|*Eclipse* +
|Version: 4.6.2

|===

=== Modules bundled with Studio:

[cols="30a,70a"]
|===
| Module | Version
| *APIkit*
| Version:  1.0.0

|*HTTP*  +
*Sockets* +
*WSC* +
*JMS* +
*FTP* +
*File* +
*Email* +
*Database* +
*VM* +
*Objectstore* +
*Validation* +
*OAuth* +
*Spring* +
*Scripting*
|Version: 1.0.0


| *MUnit Runner* +
*MUnit Tools*
| Version: 2.1.0

|*Salesforce Connector* +
*Workday Connector*
|Version:  9.0.0

|*NetSuite Conncetor* +
|Version:  8.0.0

|*ServiceNow Connector* +
|Version: 6.0.0

|*SAP Connector* +
|Version: 4.0.0


|===

== What's New

This version of Anypoint Studio introduces Mule domain projects support from Anypoint Studio. +
This version also supports Mule Runtime 4.1.0.

== Hardware Requirements

* For most use cases, Anypoint Studio with the 4.1.0 Runtime does not change hardware or software requirements from the previous Studio 7  versions.
* MuleSoft recommends a minimum of 4GB of free RAM available on a developer workstation. As applications become complex, consider adding more RAM.

* 4GB of free memory available.
* 2GHz CPU.
* 10GB free hard drive space.

== Software Requirements

[cols="30a,70a"]
|===
| Software | Version
|Java Environments
| * Oracle JDK 1.8.0
|Operating Systems |* MacOS 10.12.0 +
* Windows (32- and 64-bit) Windows 7, Windows 8, Windows 10 +
* RHEL 7.0 +
* Ubuntu 15.04 or later
|Suggested Web Browsers by Platform. +
_Studio will always use the OS default web browser_ | * Windows: +
** Microsoft Edge 25.0  +
** Internet Explorer 11 +
* Linux +
** Mozilla Firefox 51.0.1  +
* OS X +
** Safari 10.1
| Maven
| Studio comes with Maven 3.3.9 bundled, but you can externally use the versions: 3.3.3 or your own  3.3.9
|===

[NOTE]
--
If you are running McAfee VirusScan on your Windows OS, Eclipse-based Anypoint Studio may experience negative performance impacts. McAfee has suggested the following remedy link:https://kc.mcafee.com/corporate/index?page=content&id=KB58727[options].
--

[[migration]]
== Migration Guide

== Migration Guide

Studio 7.1 only supports Mule 4.x projects. The structure of the project, export format, xml and scripting language are different. +
Users must migrate Mule 3 projects to Mule 4 manually, before they can be used in Studio 7. See the Mule migration guide for more information.

== JIRA Ticket List for Anypoint Studio

=== Known Issues

* Some existing features in Studio 6.x are not yet supported in Studio 7.1: Custom Policies, API Sync, Anypoint Private Cloud.
* Anypoint Studio uses your configured default browser to display web content such as Exchange and the Runtime Manager UI when deploying an application to Anypoint Platform. If your default internet browser does not display this content correctly, you can configure Anypoint Studio to use a Mozilla/XULRunner runtime environment as the underlying renderer for the Web UI. +
Follow the link:/anypoint-studio/v/7/faq-default-browser-config[FAQ: Troubleshooting Issues with Your Default OS Browser] for more details.
* When referencing a RAML spec using Json Schema draft 3, DataSense fails. STUDIO-10033
* When adding a Raml v0.8 from exchange as a dependency, it throws an error and it's not added it. STUDIO-10247
* Copybook import fails with no message. STUDIO-10206
* Copybook import file not copied to project. STUDIO-10207
* Menu items get grayed out after opening Exchange using XulRunner. STUDIO-9684
* Mule modules needs to provide icons, today many of the modules have the generic icon. STUDIO-9628
* Running application "Pom.xml" is not updated when changing dependencies. STUDIO-9148
* Debugger: payload shown while debugging is partial but there is no way to view the rest of the payload STUDIO-9704
* When referencing a RAML spec using Json Schema draft 3, DataSense fails STUDIO-10033
* When setting WSC, it does not trigger datasense and not update metadata tree automatically. STUDIO-10242
* Mule plugins with snapshot versions should always be regenerated.STUDIO-8716
* All module and internet interactions behind a proxy are not supported STUDIO-10372
* Studio hangs when trying to open a big sample data file in DataWeave STUDIO-10523
* When setting WSC, it does not trigger datasense and not update metadata tree automatically STUDIO-10523
* Move static caches form IntrospectionUtils to an object in the app registry MULE-14495
* InfrastructureTypeMapping#TYPE_MAPPING keeps references to applications classloader MULE-14548

==== KNWON ISSUES SOAP API

* WSDL from URL does not work, you must copy the file in src\main\resources\api even if the UI suggest to use a URL.
* Sometimes scaffolding of flows in Windows does not work (right click on a WSDL in src\main\resources\api  - Mule > Generate Flows from WSDL - No exception logged).
* Metadata Keys in Windows do not work, the Service and Port combo boxes are never populated with the values.
* In OS X, after configuring a WSDL you have to manually do click in Refresh icon in order to get the Service and Port combo boxes populated and you have to do it once for Service and once for Port.
* In OS X there is a NPE in metadata propagation after manually configure the global SoapKit router values and going to the SopaKit router in the canvas.
* In Windows there is a different NPE after configuring the WSDL location and clicking OK in the Global Config.
* When searching for a WSDL file that is not in the api folder there is no warning and it doens’t work.

=== Story

* STUDIO-10282 - As a user I don't want to see any modules when inside the Add Modules Dialog until I do a search.
* STUDIO-10283 - As a user I would like to add known modules to my project from the palette.
* STUDIO-10284 - As a user I want to be able to find operations of modules that are Local, yet not in the project.
* STUDIO-10285 - As a user I always want to be able to search in exchange when looking from the palette.
* STUDIO-10287 - As a user I want to be able to configure my client and secret for API Manager.
* STUDIO-10288 - As a user I want to be able to configure the global Autodiscovery element.
* STUDIO-10290 - As a user I want to be able to select the module version when dropping an operation from the palette.
* STUDIO-10291 - A user should be able to create a project of type Domain.
* STUDIO-10292 - As a user, I want to import a domain project from different sources.
* STUDIO-10293 - As a user, I want to manage modules for a domain project.
* STUDIO-10294 - A user should be able to change certain configurations in Domain project.
* STUDIO-10295 - As a user, I want to be informed when a module defined in an application project conflicts with one from its domain.
* STUDIO-10298 - As a user I want to see a simplified version of the current new mule project wizard.
* STUDIO-10318 - A user should be able to link or unlink an application to a Domain project.
* STUDIO-10319 - A user should be provided with DataSense information when using elements from domain project.
* STUDIO-10320 - A user should be able to use Test Connection on global elements from a Domain project.
* STUDIO-10321 - A user should be able to Run/Debug an application using module operations and/or global configurations in the Domain project.
* STUDIO-10322 - As a user, I want to export my domain project into a deployable archive.
* STUDIO-10323 - As a user, I want to export my application linked to a domain.
* STUDIO-10324 - As a user, I want to use shared resources in my app defined in its domain.


=== Enhancement Requests

* STUDIO-8312 - Add a soapkit version compatible with mule 4.
* STUDIO-8556 - Add support for multi level keys for Extension API generated editors.
* STUDIO-8831 - SVG to Eclipse icons.
* STUDIO-9140 - Support for Test extensions in project.
* STUDIO-9335 - "APIKit Settings" in New Project is confusing.
* STUDIO-9960 - Support for DW functions contributed through the extension model.
* STUDIO-10231 - Support DataSense propagation from MUnit tests.
* STUDIO-10348 - MavenMuleProjectDecorator should inform current plugins versions.

=== Epics

* STUDIO-8435 - Domains in Studio 7.
* STUDIO-9709 - Debugger Studio 7 (Phase 3).
* STUDIO-10094 - Add Gateway support in Studio 7.
* STUDIO-10278 - Support the Anypoint Platform in EU.
* STUDIO-10281 - Studio Palette Improvements.
* STUDIO-10286 - API Gateway.
* STUDIO-10289 - New Project Wizard.

=== Tasks

* STUDIO-8502 - Define UI for operation UX
* STUDIO-8830 - Create icons for the Properties View local toolbar
* STUDIO-8833 - Define the design of the Error Mapping panel
* STUDIO-8961 - Technical spike on Platform Login
* STUDIO-9557 - Support mule-artifact.json descriptor for domains
* STUDIO-9647 - Manage Modules: enhance Adding a Module experience in Global Elements UX
* STUDIO-9995 - Define UX/UI for managing maven dependencies
* STUDIO-10015 - Create Studio 7 GA icon
* STUDIO-10069 - [UX] Review experience of installing modules from Exchange UI (Phase 1)
* STUDIO-10103 - Define experience when opening old workspaces in Studio 7
* STUDIO-10105 - [UX] Revamp New Project dialog
* STUDIO-10106 - [UX] Warn users when importing Studio 6.x projects into Studio 7
* STUDIO-10107 - [UX] Improve UX for fields that support expressions
* STUDIO-10116 - Add old keywords in the search palette engine to find name replacements done in Studio 7
* STUDIO-10151 - Implement changes in object store in elements
* STUDIO-10210 - Implement searching of bundled modules from the palette
* STUDIO-10220 - [UX] Improve palette and Add Modules dialog for bundled connectors
* STUDIO-10256 - Publish to Exchange and Import from Design Center must support the EU infrastructure
* STUDIO-10262 - [UX] Support for Domains in Studio 7
* STUDIO-10300 - Remove java configurations wizard pages
* STUDIO-10301 - Add location component into the first wizard page
* STUDIO-10302 - Update APIKit component labeling in the new project wizard
* STUDIO-10303 - Remove git ignore UI component
* STUDIO-10316 - Create Local palette icon and add it to the Studio Images plugin
* STUDIO-10356 - Implement overwriting of API gateway urls when changing of region.
* STUDIO-10358 - Use Mule 4.1-SNAPSHOT in development branch
* STUDIO-10362 - Create API to generate/retrieve a domain archive
* STUDIO-10394 - Add values in the default autocompletion list
* STUDIO-10411 - Review security report from Nexus IQ
* STUDIO-10412 - Integrate Apikit for SOAP for Studio 7
* STUDIO-10434 - Change label for API Gateway preference page
* STUDIO-10454 - Expose serialization service in ToolingClient
* STUDIO-10485 - Make Mule Server 4.1.0 feature update the Mule 4.0.0 runtime for 7.1 release
* STUDIO-10488 - Update APIKIT dependencies to 1.1.0-SNAPSHOT
* STUDIO-10495 - Change Domain project icon
* STUDIO-10496 - Domains: Distinguish in the label when a Domain is referenced from Workspace or from an External resource
* STUDIO-10514 - Add option to go to Manage Domain Modules when deleting a module from project


== Support

* link:http://forums.mulesoft.com/[MuleSoft’s Forum].
* link:http://www.mulesoft.com/support-login[MuleSoft’s Customer Portal].
