= Anypoint Platform Private Cloud Edition 1.6.1 Release Notes

**June 2017**

== New Features and Enhancements

No new features or enhancements.

== Installing

See link:/anypoint-private-cloud/v/1.6/install-workflow[Workflow: Install Anypoint Private Cloud] for information on how to install Anypoint Platform Private Cloud Edition.

== Upgrading from 1.5.x to 1.6.x

See link:/anypoint-private-cloud/v/1.6/upgrade[To Migrate to Anypoint Platform Private Cloud Edition, Version 1.6.x] for information on how to upgrade to the current version.

Before upgrading, you must backup your system as described in link:/anypoint-private-cloud/v/1.6/backup-and-disaster-recovery[To Backup and Restore Your System] After the upgrade is complete, perform a restore to return your system to its previous state.

[NOTE]
The procedures for performing a backup and restore have changed in this release. See link:/anypoint-private-cloud/v/1.6/backup-and-disaster-recovery[To Backup and Restore Your System]


== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime | 3.7.x - 3.8.x
| API Gateway Runtime | 2.1.x - 2.2.x
| Runtime Manager Agent | 1.5.2 - 1.5.3
| Infrastructure providers |
* VMWare
* Bare Metal
| Compatible browsers when running the installer |
* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
|===

== Fixed Issues

[%header%autowidth.spread]
|===
|Issue ID |Description 
| . | .
|===

== Known Issues

[%header%autowidth.spread]
|===
|Issue ID |Description |Workaround
| . | .
|===