= Anypoint Platform for Pivotal Cloud Foundry 1.5.1 Release Notes

The Anypoint Platform for PCF solution is a fully integrated solution that enables organisations to design, develop, deploy, manage and operate APIs, connectivity apps and microservices within the fully automated and transparent infrastructure provided by  link:https://pivotal.io/platform[Pivotal Cloud Foundry]. The different deployment scenarios that Runtime Manager supports are described in detail here: link:/runtime-manager/deployment-strategies[Deployment Strategies].

== System Requirements

See link:/anypoint-platform-private-cloud-edition/v/1.5/prerequisites-anypoint-platform-private-cloud[Prerequisites for Anypoint Platform] for installing the platform on premises.

== Compatibility

[%header%autowidth.spread]
|===
|Compatible with |Version
|Mule Runtime | 3.8.1 and later
|===

== Features

This release adds the following feature:

* **PCF Metrics**: enables you to specify usage limits for development, production and staging environments from Ops Manager. Using PCF Metrics, you can also collect and view usage metrics for Mule applications running on PCF.
