= Anypoint Platform Private Cloud Edition 1.6.0 Release Notes

**May 31, 2017**

== Software Compatibility

[%header,cols="2*a"]
|===
| Compatible with |Version
| Mule runtime | 3.7.x - 3.8.x
| API Gateway Runtime | 2.1.x - 2.2.x
| Runtime Manager Agent | 1.5.2 and later
| Infrastructure providers |
* VMWare
* Bare Metal
| Compatible browsers when running the installer |
* Firefox (latest version)
* Chrome (latest version)
* Safari (latest version)
|===


== Feature Enhancements

**Need to add content here**

== Fixed Issues

**Need to add content here**

== Known Issues

**Need to add content here**

== Anypoint Platform Features

The following sections outline the Anypoint Platform Features added to Anypoint Platform Private Cloud Edition, version 1.6.

=== Anypoint Runtime Manager

[%header,cols="2*a"]
|===
|Runtime Manager Release |Feature Added
|2.2.0 | Flow Monitoring: Users now have the ability to monitor key metrics in each Mule flow over time with the help of monitoring charts for flow metrics. This release includes metrics for:

	* Mule messages
	* Errors
	* Response time
|2.1.0 |
* Improved support for promotion of hybrid applications between environment from the UI
* Capability to enable and disable insights at deployment time for hybrid applications
* Capability to configure the log levels at deployment time for hybrid applications
* CHHYBRID-2542 Deployment partially persisted
* CHHYBRID-2386 Enhance performance of the Audit Logging Aspect
* CHHYBRID-2517 Add request tracing logging to the Hybrid-Console
|2.0.0 | 
* Insight for Hybrid Users: Insight gives users the ability to troubleshoot their applications for performance and health related issues at a granular level, thus enabling users to determine the root cause of an issue quickly and efficiently. This is now available for all users.
* Flow Management: Users will have the ability to manage their problematic flows in runtime. They can now just disable a flow without disrupting the entire application.
* Monitoring V2.0: This release contains granular monitoring charts for metrics that are pertinent to On-Premises servers and are hence used by Hybrid users. The new charts include:
+
	* Garbage Collection
	* Heap/Non-Heap
	* Load average
	* Thread count.

Additionally alerts have been set for Load Average and Thread count.

Flow management and monitoring V2.0 functionality is only available for integration applications deployed On-Premises, but management occurs through a cloud console.
|1.5.1 |This release resolved the following issues:

* Several Application/Server dashboards enhancements
* CHHYBRID-1954 - New timepicker in the applications tab of SG/Cluster Dashboard
* CHHYBRID-1957 - Increase applications and targets timeouts
* CHHYBRID-1956 - Fix "Last updated" label style in latest Chrome version
* CHHYBRID-1968 - Alerts now have links to the pertinent dashboards
* CHHYBRID-1961 - Ability to filter per resource type in alert conditions
* CHHYBRID-1980 - Warning in server group/Cluster page if the plugins are incompatible
|===

