= Auto-Upgrade Notice for Anypoint Platform (November Release)

The November release includes many improvements across API Designer, API Portal, and API Manager.

MuleSoft will _automatically_ upgrade customers with twenty (20) or fewer APIs unless your platform administrator opts out (<<opt_out>>). The automatic upgrades will occur on a rolling schedule. A self-service upgrade process will be available for other customers.

The upgrade schedule depends on the number of APIs in your organization:

* January 29-31: Customers with two (2) or fewer APIs will be automatically upgraded.
* Starting February 26th: All other customers will be offered self-service experience to migrate.

== What’s in the release?

* New experience (video on YouTube): https://www.youtube.com/watch?v=oL827WlMmfM&feature=youtu.be[Nov. 2017 Release: UI Updates for Existing Users]
* New capabilities: https://www.mulesoft.com/platform/new-product-features[New Product Features]
* Changes and features: link:anypoint-november-release[Anypoint Platform July and November Release: Release Notes]

Because many of the new products have new features and a different UX, please consider the following:

* For API Portal, the look and feel is changing. This change is especially important for public API portals that are exposed to external developers.
* The API lifecycle is slightly different, so if you are in the middle of a big release, be sure to communicate this to your team(s).
* Other Anypoint accounts used by you or other developers in your organization might retain the same, “old” Anypoint Platform experience.

== After the upgrade

All your APIs in API Manager will be in the unclassified environment.

To access your APIs:

. Go to API Manager.
. Select the unclassified environment.
+
From the unclassified environment, you can manage your APIs in the same way that you did before the November release.
+
. When you are ready for the new environment capabilities of the November release, classify your APIs into environments, or create new APIs in them.

== Learn more here:

* link:/api-manager/manage-exchange-api-task[Manage an API from Exchange]
* link:/api-manager/environment-permission-task[Grant Permission to Access Environments]
* link:/api-manager/classify-api-task[Classify an API]

[[opt_out]]
== Want to opt out?

Send us an email with your organization ID to crowd@mulesoft.com if you want to be excluded from the automatic upgrade. You can find the ID from Anypoint Platform by navigating to Access Management -> Organization -> _your_organization_ and then finding the Organization ID in the Organization Info window.

Note that all customers are required to upgrade in 2018.

If you have problems with the new experience of Anypoint Platform, please open a support ticket from link:https://support.mulesoft.com/s/[MuleSoft Support].
