= Anypoint Studio 7.0.0 Beta with Mule Runtime 4.0.0 Beta
*July 14, 2017* +
*Build ID: *

xref:migration[Skip to Migration Guide]

== Compatibility

[cols="30a,70a"]
|===
| Product | Version
| *Mule Runtime*
| Version: 4.0.0 BETA

|*Anypoint Studio*
|Version: 7.0.0 BETA  +
Build Id:

|*Maven*
|Version: 3.3.9

|*DataWeave* +
|Version: 2.0.0 BETA

|*MUnit* +
|Version: 2.0.0 BETA (munit-studio-plugin)

|===

=== Modules bundled with Studio:

[cols="30a,70a"]
|===
| Module | Version
| *APIkit*
| Version:  1.0.0 BETA.3

|*HTTP* +
*Sockets* +
*JMS* +
*Validations* +
*File* +
*WSC* +
*FTP* +
*Oauth* +
*Email* +
*Database*
|Version: 0.8.0-BETA.3

|*Salesforce Connector* +
*Workday Connector*
|Version:  9.0.0-BETA.3

|*NetSuite Conncetor* +
|Version:  8.0.0-BETA.3

|*ServiceNow Connector* +
|Version: 6.0.0-BETA.3
|===

== What's New

* Improved palette which enables users to more quickly discover what they’re looking for by searching directly for operations and saving favorites
* Users can now explicitly manage which connectors and modules are associated with a project.
* Connectors and modules are now managed directly by Anypoint Studio, and do not require users to manage update sites.
* Easily navigate to code from visual view by right clicking on a component and clicking “View XML”
* Maven is now embedded out of the box inside Studio. Additionally, every project now has a Maven POM, making it easier to incorporate projects into CI/CD systems.
* Flows and scopes are now collapsable.
* Updated icons make flows easier to read.
* DataSense metadata is now stored in a human readable format this is easier to share, commit and merge.
* Support for importing API specifications from Design Center
* Improved user experience for connector and modules
* Simplified experience to manage credentials when logging into the Anypoint Platform


[NOTE]
--
Beta status in this release indicates the functionality is open for customers to trial for the purpose of learning the new functionality and/or testing functionality in a non-production environment. Basic functionalities to enable core use cases are complete, and MuleSoft is in the process of verifying design and evolving feature completeness. There is no SLA or technical support obligations for the Beta features. Beta releases are suitable for use in test environments or for limited-use tests.  Please see our link:https://www.mulesoft.com/legal/product-trial-commercialfree-licenses[beta trial license] for full terms of use.
--

== Hardware Requirements

* 4GB of free memory available
* 2GHz CPU
* 10GB free hard drive space

== Software Requirements

[cols="30a,70a"]
|===
| Software | Version
|Java Environments
| * Oracle JDK 1.8.0
|Operating Systems |* MacOS 10.10.0 +
* Windows (32- and 64-bit) Windows 7, Windows 8, Windows 10 +
* RHEL 7.0 +
* Ubuntu 15.04 or later
|Suggested Web Browsers by Platform. +
_Studio will always use the OS default web browser_ | * Windows: +
** Microsoft Edge 25.0  +
** Internet Explorer 11 +
* Linux +
** Mozilla Firefox 46.0  +
* OS X +
** Safari 9.1
|===

[NOTE]
--
If you are running McAfee VirusScan on your Windows OS, Eclipse-based Anypoint Studio may experience negative performance impacts. McAfee has suggested the following remedy link:https://kc.mcafee.com/corporate/index?page=content&id=KB58727[options].
--

== Known Issues

* DataWeave editor does not support regex as function parameters STUDIO-9069
* Metadata: can not create XML types from samples that contains CDATA STUDIO-9436
* Application-types file is not updated when deleting MP from XML view. STUDIO-9505
* Metadata tree is not being updated for Flows. STUDIO-9522
* Dependencies are not refreshed properly if the pom is updated while the dependencies are being resolved.STUDIO-9540
* APIKit does not support metadata
* First time you create a MUnit test from a Flow you get a message saying that you have to wait for the dependencies to be added to the project and then try again. +
Some existing features in Studio 6.x are not yet supported in Studio 7: Domains, Custom Policies, APISync, Anypoint Private Cloud, Gateway runtime connectivity.
* To be able to deploy a project which uses the runtime 4.0.0 into Cloudhub you need to have certain permissions in your Anypoint Platform user to see runtime 4.0.0 when deploying it.
* Anypoint Studio uses your configured default browser to display web content such as Exchange and the Runtime Manager UI when deploying an application to Anypoint Platform. If your default internet browser does not display this content correctly, you can configure Anypoint Studio to use a Mozilla/XULRunner runtime environment as the underlying renderer for the Web UI. See link:/anypoint-studio/v/7/troubleshoot-studio-issues-faq[Troubleshooting Studio] for more information.
* Mule modules needs to provide icons, today many of the modules have the generic icon. MULE-11437
* XML Metadata is not generated correctly when the provided sample has namespaces. MULE-12859
* Validation error when required attribute is written with double quotes in a Choice expression. STUDIO-9386
* Generated UI in Mule properties editors for Modules that use Map<String,List<String>> type of structures such as MongoDB will not work. STUDIO-9570
* Includes are not resolved correctly when creating a new apikit project.  STUDIO-9573
* Running application "Pom.xml" is not updated when changing dependencies. STUDIO-9148
* Mule plugins with snapshot versions should always be regenerated.STUDIO-8716

== JIRA Ticket List for Anypoint Studio

=== Bug Fixes



=== Enhancement Request



=== Tasks




== Support

* Access link:http://forums.mulesoft.com/[MuleSoft’s Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[subscribe to Mule ESB Enterprise] and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal].
