= API Notebook Release Notes

== API Notebook 1.2.0

June 17, 2017

This release focuses on a few RAML 1.0-related improvements and bug fixes.

=== Resolved Issues

* Fixed an issue that caused an error that prevented adding some APIs as an API client in Notebook.
* Fixed an issue with loading a RAML 1.0 API and lack of details in the error reporting.
* Fixed an issue that caused the API Notebook to make an invalid suggestions for available methods in some cases.
* Fixed an issue preventing you from deleting a code cell after a text cell.
* Fixed a CSS issue with executing a code cell that produced an inordinately long, partially displayed error message that you could not scroll horizontally.
* Fixed an issue preventing “{proxy: false}” from working.
* Fixed a UI issue preventing the example field from expanding properly.

=== Improvements

* Bumped JS parser version to link:https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.18[1.1.18]
* Added support for queryString introduced in RAML 1.0.
* Added support for the Pass Through security scheme introduced in RAML 1.0.
