= API Console Release Notes

* <<API Console 3.0.16>>
* <<API Console 3.0.14>>
* <<API Console 3.0.13>>
* <<API Console 3.0.12>>
* <<API Console 3.0.11>>
* <<API Console 3.0.9>>

== API Console 3.0.16

April 8, 2017

This release focuses on minor bug fixes.

== Resolved Issues

* Fixed an issue preventing API documentation from being displayed at the Portal due to incorrect url resolution after library expansion.
* Fixed an issue preventing error feedback from being displayed (white page or greyed page was displayed instead, depending on implementation). 
* Fixed an issue that response type and examples weren’t refreshed accurately when changing methods.
* Fixed an issue causing multiple inheritance types to be incompletely rendered in the method response.

== Improvements

* Bumped RAML Parser to version to link:https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.19[1.1.19]
* Added an improvement for rendering the root description of an API on the top of the page.


== API Console 3.0.14

March 11, 2017

This release includes a JS parser update.

=== Improvements

Bumped JS parser version to link:https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.14[1.1.14].

== API Console 3.0.13

February 3, 2017

This release includes a JS parser update.

=== Improvements

Bumped JS parser version to 1.1.13.

== API Console 3.0.12

January 14, 2017

This release includes a JS parser update.

=== Improvements

Bumped JS parser version to 1.1.12.

== API Console 3.0.11

December 3, 2016

This release includes several fixes for rendering information as well as fixes for issues around RAML 1.0.

=== Resolved Issues

* Add support for Pass Through to reflect the complete set of security schemes defined in RAML 1.0.
* In the previous version, the error output was not correctly handled and had to be updated.
* Several other smaller bug fixes.

=== Improvements

* Bumped JS parser version to 1.1.8.
* Several other smaller improvements.

== API Console 3.0.9

November 19, 2016

=== Improvements

Bumped JS parser version to 1.1.6.

