= API Gateway 3.8.0 Release Notes
:keywords: api, gateway, 2.2.0, release notes

== Compatibility

[width="100%",cols="50a,50a",options="header",]
|===
|Software |Version
|APIkit |3.8.0
|Anypoint Studio |6.0
|===

== New Features

* AGW-498: Add support for handling the X-Forwarded-For headers in the generated proxies.
* AGW-693: Add support for RAML 1.0.
* AGW-695: Honor the tls-default configuration in the client communication with API Manager.
* AGW-741: Now that api-gateway domain is not bundled with the distribution, create a script to generate API Gateway domain. 
* AGW-746: Enhance security when Gateway is started and policies are not yet applied. This feature doesn’t include support for Cluster scenarios yet.
* AGW-767: Support persistence of throttling and rate limiting quota. This feature doesn’t include support for quota persistence in Cluster or Cloudhub.
* AGW-779: Enable order granularity at the before and after components level on the policy template configuration.
* AGW-785: Extend the Client Id Enforcement policy to extract client credentials from the Authorization Header.

== Fixed in This Release

* AGW-411: When Gateway is started in offline mode, and comes when online again, it never communicates with API Manager again.
* AGW-675: Custom policies are not picking up common beans defined in the `default-mule-config.xml`.
* AGW-720: Duplicated autodiscovery elements are present in the registry when Gateway is restarted.
* AGW-732: When a contract service URL is unreachable, no log is generated.
* AGW-745: When offline, restarting API Gateway removes all online policies currently applied.
* AGW-755: A spring injected property is null when a policy is applied.
* AGW-759: The Extended CORS policy is not validating headers.
* AGW-782: In the federated policies, invalid requests return incorrect status codes.

== Migration Guide from 2.x to API Gateway 3.8.0

Follow the migration instructions in this section to continue using API Gateway domain with Mule 3.8.0.

=== API Gateway Domain Migration

API Gateway 2.x included an out-of-the-box domain with a listener configuration binding to all interfaces and using port 8081. The purpose of this domain was to enable shared resources on the generated proxies, however, the experience with the default domain was not the expected and the decision was to remove it in this release. 

If you want to continue using the domain, run the script included in the Mule 3.8.0 distribution to generate the API Gateway domain before deploying the proxy. Alternatively, you can copy the api-gateway domain from your old release to the new one. API Manager supports generating a proxy for referencing the domain. 

Refer to link:/anypoint-platform-for-apis/api-gateway-domain[API Gateway domain] documentation for more information. 

== See Also

* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]

