
= API Designer Release Notes

* <<API Designer 0.3.0 Release Notes>>

* <<API Designer 0.2.0 Release Notes>>

== API Designer 0.3.0 Release Notes

December 3, 2016

This release includes a new, improved menu to simplify creating RAML documents, as well as a beta version for importing OAS 2.0 documents.

=== Resolved Issues

* Several mocking service issues.
* In the previous version, the baseUri was duplicated after quitting the designer with the mocking service enabled.

=== Improvements

* Improved main menu.
* Bumped JS parser version to 1.1.8.
* Bumped API Console version to 3.0.11.

=== New Features

Import OAS 2.0 (beta).

== API Designer 0.2.0 Release Notes

November 19, 2016

This release incorporates full support for RAML 1.0 and fixes bugs.

=== Resolved Issues

* The mocking server no longer  returns “unknown type” when type is defined in a library.
* In the previous versions, importing files did not get automatically saved. This release fixes that issue and also eliminates the confusing error indicator that appeared after import in a valid RAML file.

=== Improvements

Bumped JS parser version to 1.1.6.

=== New Features

* Improved warnings and trace information for better error management.
* Auto-completion for any named variable such as `paging` trait or `collection` resource type across all RAML typed fragments. 
* Validation of RAML 1.0 typed fragments.


