= APIkit 4.0 Release Notes

These release notes briefly describe changes, known issues, and limitations in APIkit 4.0.

== What’s New

* Performance improved by supporting non-blocking strategy for APIKit operations
* API Console no longer appears in Studio. The URL for launching the Console appears in the logs in Studio when you create an APIkit API. To launch the Console, enter the URL in a browser.
* APIkit now processes the operations declared after the APIkit router component.
* Only one of two 3.x-supported methods of configuring the Console is supported in this release.
* You can configure the Console only from within the apikit:config element, as described in "Changing the API Console URL."
* Retrieving the RAML is supported from the Console, but not from the API.
* Generated XML code differs from that generated by APIkit 3.x. The XML code complies with new Mule 4.0 components as shown in the following snippets:
+
*3.x* 
+
----
<apikit:config name="api-config" raml="api.raml" consoleEnabled="true" consolePath="console" doc:name="Router" keepRamlBaseUri="false" />
----
+
*Mule 4.0*
+
----
<apikit:config name="api-config" raml="api.raml" outboundHeadersMapName="outboundHeaders" httpStatusVarName="httpStatus" />
----

== Compatibility

* Mule Runtime 4.0.0
* Anypoint Studio 7.0.0
* Java Parser RAML 1.0 v1.0.16
* Java Parser RAML 0.8 v0.8.19
* API Console 4.0.0

== Now available in this release

* Non-blocking requests
* DataSense metadata
* The Community edition

== Limitations

This release does not support the following :

* Inbound endpoints
* APIkit for SOAP
* OData

Post requests using form parameters are supported, but not validated.


== Features and Functionality

=== Enhancement Requests

* [APIKIT-868] Check that custom headers are not duplicated
* [APIKIT-869] Strict validation of query parameters and headers

=== Fixed in this release

* [APIKIT-793] PUT and POST requires a request body
* [APIKIT-839] Form Parameter type is not being validated
* [APIKIT-850] Fixing Exception caused by trying to load a JSON Schema from a path with spaces
* [APIKIT-873] Apikit scaffolder is generating mule-deploy.properties file.
* [APIKIT-876] Critical vulnerability in Jackson prior to 2.8.9
* [APIKIT-889] Expose Console Resources to the RAML GW Proxy
* [APIKIT-901] Resource found in raml but not in config, throws 500 server error
* [APIKIT-902] Console source location should be saved to a file
* [APIKIT-925] Error 500 when sending a request to a resource without schema defined
* [APIKIT-931] Scaffolder: Build fails when mule version is not sent (default CE version)
* [APIKIT-940] Metadata is not reported for APIKit routes
* [APIKIT-942] Use single quote on set-variable tag
* [APIKIT-949] Porting to 4.0: Only one HTTP Response code evaluated for return from APIKit Rest Requests
* [APIKIT-951] Ensure multiple success status defined in RAML are considered for the REST response in APIKIT 4
* [APIKIT-956] ApikitErrorTypes is using a not exported mule-core class
* [APIKIT-963] Use Optional instead of null in FlowMetadata
* [APIKIT-973] Multipart: Bad request when expecting default value in the response
* [APIKIT-994] APIKit console does not start. Error : "No listener for endpoint: /console/"
* [APIKIT-957] Mule4 :APIKit fails on XML starting with BOM and containing tab character
