= APIkit 4.0 Beta Release Notes

These release notes briefly describe changes, known issues, and limitations in APIkit 4.0 Beta.

== Changes

* APIkit Console no longer appears in Studio. The URL for launching the Console appears in the logs in Studio when you create an APIkit API. To launch the Console, enter the URL in a browser.
* APIkit now processes the operations declared after the APIkit router component.
* Only one of two 3.x-supported methods of configuring the console is supported in this release.
+
You can configure the console only from within the apikit:config element. <<link to how to>>
+
* Retrieving the RAML is supported from the Console, but not from the API.  <<link to how to>>
* Generated XML code differs from that generated by APIkit 3.x. The XML code complies with new Mule 4.0 components as shown in the following snippets:

*3.x*: `<apikit:config name="api-config" raml="api.raml" consoleEnabled="true" consolePath="console" doc:name="Router" keepRamlBaseUri="false" />`

*Mule 4.0*: `<apikit:config name="api-config" raml="api.raml" outboundHeadersMapName="outboundHeaders" httpStatusVarName="httpStatus" />`

== Known Issue

APIKIT-859 Form data and URL-encoded parameters are not validated.

== Limitations

This release does not support the following things:

* Non-blocking processing
* DataSense metadata
* The Community edition
* POST requests using form parameters
* Inbound endpoints
* APIkit for SOAP
* OData

Post requests using form parameters are supported, but not validated.
