= Cassandra Connector Release Notes
:keywords: cassandra

May 16, 2017

The initial release of Anypoint Cassandra connector provides the capability to connect a Mule app to a Cassandra database or cluster. The MuleSoft support category for the Cassandra connector is link:/mule-user-guide/v/3.8/anypoint-connectors#connector-categories[Select]. 

== Compatibility

The Cassandra connector was implemented using the DataStax Java Driver for Apache Cassandra 3.1. The connector is compatible with the following software:

* Cassandra database or cluster 1.2 or later
* CQL spec 3.x
* Anypoint Studio/Mule Runtime 3.5 or later

== Key Features

The Cassandra connector supports the following capabilities:

* Basic Authentication for accessing the database as configured in the cassandra.yaml
* Executing any CQL query using a custom POJO
* Performing the following Cassandra Query Language (CQL) database operations, which are described in the Cassandra Connector javadoc, using a wizard:
+
[frame=none]
|===
| Add new column | Delete columns value | Drop table | Select 
| Change column type | Delete rows | Drop keyspace | Update 
| Create keyspace | Drop Column  | Rename column |  
| Create table | Get table names from keyspace | Insert |  
|===
+
* Configuring Cassandra cluster operations, such as compression and SSL
* All CQL primitive data types except:
** list
** map
** set
** tuple





