= CloudHub Runtimes Release Notes
:keywords: release notes, cloudhub, cloud hub

These are the release notes for patches which are made to the Mule runtimes on CloudHub. In addition to these release notes, see the link:/release-notes/cloudhub-release-notes[CloudHub release notes] and complete link:/runtime-manager/cloudhub[CloudHub] documentation.

== April 12, 2017
3.8.4 runtime update

== March 21, 2017
This runtime update comes with the following fixes:

* Fixes an issue where after until-successful flow variables loses mime type [MULE-11382]
* Fixes a problem with DataWeave FlatFile transformation not working as expected when unbounded nested segments are in place
* Fixes an issue with HTTP requester when sending request to Microsoft IIS 
* Fixes a problem where Oauth authentication uses refreshToken when parameter is overriding payload [MULE-11949]
* Fixes an issue where Mule Listener stopped serving request after one grizzly listener is killed due to NoClassDefFoundError [MULE-11337]

These updates are available for Mule Runtime version link:/release-notes/mule-3.8.3-release-notes[3.8.3]

== March 2, 2017
Patched API Gateway 2.2.0 with link:https://www.mulesoft.org/jira/browse/MULE-9163[MULE-9163] fix.

== February 7, 2017
Patched 3.8.x runtimes to upgrade to Python 3 and accomodate to AWS new instances id (long id).

== December 1, 2016
This set of runtime updates includes the following:

* Fixes a vulnerability with JAXB and Jersey which could result in a DoS attack
* Fixes a problem where a 403 error would appear in the logs when using Insight

These updates will be released for the following versions: 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, API Gateway 2.0.2, API Gateway 2.0.3, API Gateway 2.0.4, API Gateway 2.1.0, API Gateway 2.1.1, API Gateway 2.2.0

== November 23, 2016
This set of runtime updates includes the following:

* Fixes a vulnerability with JAXB and Jersey which could result in a DoS attack
* Fixes a problem where a 403 error would appear in the logs when using Insight
* Fixes an issue with DataWeave which would result in running out of space on the drive for 3.8.x
* Fixes an issue with APIkit where it would cast a numeric string query param to Integer, which then caused a InvalidQueryParameterException

Runtimes updated include 3.5.4, 3.7.4, and 3.8.2
