= CloudHub Runtimes Release Notes
:keywords: release notes, cloudhub, cloud hub

These are the release notes for patches which are made to the Mule runtimes on CloudHub. In addition to these release notes, see the link:/release-notes/cloudhub-release-notes[CloudHub release notes] and complete link:/runtime-manager/cloudhub[CloudHub] documentation.

== August 29, 2017

3.8.5 Runtime Update comes with the following improvements:

* Fixes an issue where Event Tracking blocks Message Source thread [SE-6147]
* Fixes a problem where Worker Unresponsive alert is triggered on a healthy worker [SE-6365] 

== August 4, 2017

3.8.5 Runtime Update comes with the following improvements:

* Better logging for Replay Transactions
* Increased retries for storing replay data
* Added request timeout for storing replay data
* Increased maximum payload size for replay transactions

3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5 Runtime Updates come with the following improvement:

* Support for Persistent Queues in new regions

== August 1, 2017

3.8.0, 3.8.1, 3.8.2, 3.8.4 Runtime Updates come with following fix:

* Fixes an issue with Persistent Queues raising java.lang.NoSuchMethodError [SE-6421]

== July 27, 2017

3.8.3 and 3.8.5 Runtimes Update comes with the following fix:

* Fixes an issue with Persistent Queues raising java.lang.NoSuchMethodError [SE-6421]

3.8.5 Runtime Update comes with the following fix:

* Fixes a problem where dw-buffer-input*.tmp file is getting created in tmp directory [SE-6424]
* Fixes an issue where API Console does not render in Studio [FV-103]
* Fixes an issue where Includes with absolute paths are not resolved in Studio [APIKIT-888]
* Fixes an issue where APIKit examples were not being generated taking into account the response mimetype [APIKIT-752]

== July 19, 2017

3.8.4 Runtime Update comes with the following fix:

* Fixes a configuration problem that prevented HTTP Request responseTimeout from being honored when doing non-preemptive authentication HTTP calls and caused the HTTP requester to throw an exception if the remote side sends a close connection header

== July 13, 2017

3.8.0, 3.8.1, 3.8.2, 3.8.3 and 3.8.4 Runtime Update comes with the following fix:

* Updated Amazon SDK to 1.11.153

3.8.4 Runtime Update also comes with the following fixes:

* Fixes an issue where HTTP Request responseTimeout is not honored when doing non-preemptive authentication HTTP call [MULE-12943]
* Fixes an issue related CORS policy when different versions of the same API are deployed in one application
* Fixes a problem where HTTP requester throws exception if the remote side sends a close connection header
* Added support for WS-Security with CXF [MULE-12995]
* Fixes performance issues related to RAML 1.0 Parser

== June 22, 2017

3.8.4 Runtime Update comes with the follwing fix:

* Fixes Performance Degradation due to MVEL optimizer not refreshing when the payload type changes MULE-11274 and MULE-12718.
* Upgrade JDK to 8u131.

== May 18, 2017

3.8.4 Runtime Update comes with the following fixes: 

* Fixes an issue where Multiple JDBC Connector in foreach scope component cause null pointer due to NotificationUtils not checking for null parentElement [MULE-12267]
* Fixes a problem where XsltTransformer should close underlying InputStream when using XMLStreamReader [MULE-12360]
* Fixes an issue of race condition in batch when the thread dispatcher reads from the persistent queue which leads to delayed processing in a batch process
* Fixes an issues related to high CPU due to infinite loop in a batch job
* Fixes a problem where com.mulesoft.weave.model.values.NameValue$MaterializedNameValue cannot be cast to com.mulesoft.weave.model.capabilities.AttributesCapablet
* Fixes an issue where large payload is getting dropped while performing only set-variable DW transform

== May 9, 2017

3.8.3 Runtime Update comes with the following fix:

* Fixes an issue where MuleWeaveFactory$.createGlobalContext(...) blocks threads

== May 2, 2017

3.8.4 Runtime Update comes with the following fixes:

* Fixes a problem where token refresh overrides payload when resending request [MULE-11949]
* Fixes issue where SedaStageInterceptingMessageProcessor thread should clear RequestContext [MULE-12206]
* Fixes an issue where MuleWeaveFactory$.createGlobalContext(...) blocks threads
* Fixes a problem with High CPU usage caused by internal configuration

3.8.3 Runtime Update comes with the following fixes:

* MVEL optimizer does not refresh when the payload type changes [MULE-11274]

== April 12, 2017

3.8.4 runtime update

== March 21, 2017

This runtime update comes with the following fixes:

* Fixes an issue where after until-successful flow variables loses mime type [MULE-11382]
* Fixes a problem with DataWeave FlatFile transformation not working as expected when unbounded nested segments are in place
* Fixes an issue with HTTP requester when sending request to Microsoft IIS 
* Fixes a problem where Oauth authentication uses refreshToken when parameter is overriding payload [MULE-11949]
* Fixes an issue where Mule Listener stopped serving request after one grizzly listener is killed due to NoClassDefFoundError [MULE-11337]

These updates are available for Mule Runtime version link:/release-notes/mule-3.8.3-release-notes[3.8.3]

== March 2, 2017
Patched API Gateway 2.2.0 with link:https://www.mulesoft.org/jira/browse/MULE-9163[MULE-9163] fix.

== February 7, 2017
Patched 3.8.x runtimes to upgrade to Python 3 and accomodate to AWS new instances id (long id).

== December 1, 2016
This set of runtime updates includes the following:

* Fixes a vulnerability with JAXB and Jersey which could result in a DoS attack
* Fixes a problem where a 403 error would appear in the logs when using Insight

These updates will be released for the following versions: 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, API Gateway 2.0.2, API Gateway 2.0.3, API Gateway 2.0.4, API Gateway 2.1.0, API Gateway 2.1.1, API Gateway 2.2.0

== November 23, 2016
This set of runtime updates includes the following:

* Fixes a vulnerability with JAXB and Jersey which could result in a DoS attack
* Fixes a problem where a 403 error would appear in the logs when using Insight
* Fixes an issue with DataWeave which would result in running out of space on the drive for 3.8.x
* Fixes an issue with APIkit where it would cast a numeric string query param to Integer, which then caused a InvalidQueryParameterException

Runtimes updated include 3.5.4, 3.7.4, and 3.8.2
