= Design Center Release Notes
:keywords: release notes, design center, flow designer, api designer, mule application, editor, raml, swagger

== 1.0 - July 21, 2017


This release includes the new web-based Design Center that enables you to easily create web-based integration flows, design API specifications, and create reusable API fragments.

*Create Mule Applications*

With release you can:

* Create and manage Mule application projects.
* Design flows using a simple step-by-step process with the ability to quickly navigate to Exchange to see more information.
* Connect to systems and protocols using different connectors, including databases, FTP, HTTP, SOAP web services, Salesforce, Workday, and others.
* Support for REST connect, which provides a connector in the component selector for every API that is published in Exchange. This enables you to discover APIs as part of your design process and consume them without having to know the details of how the API works.
* Perform complex data transformations using DataWeave with a visual drag-and-drop editor.
* View live data, so you can easily debug your flows.
* Create and manage data types for XML, JSON, CSV, and objects.
* Control the flow of data:
** Choice Router enables you to make logical decisions and route to specific event processors or other flows.
** For Each Scope enables you to loop over payload content.
** Try Scope enables you to incorporate error-handling logic into your flows. Using error handlers, you can select specific error types that could occur, and define a behavior to deal with each.
** Flow Refs enable you to call out to other flows from your main flow.
* Store and retrieve information from the Mule Object Store.
* Use design environments, which enable you to develop applications using flow designer, without consuming your Sandbox VCores.
* Manage dependencies, so you can control the versions of your connectors and modules, to upgrade or downgrade at any time.


Underpinning this release is the initial release of Mule 4.o Runtime. This release is currently only available to Design Center users. More details on what’s new in Mule 4 can be found in the Mule Runtime section.

*Create API Specifications*

With release you can:

* Edit RAML API specifications and fragments.
* Publish and consume reusable API fragments, so that common best practices, data types, or security schemes can be reused across APIs.
* Mock and test APIs.
* Import and export Open API Specification (OAS) 2.0.
* Create and delete branches for your API specification or fragment.
* View projects in edit and read-only mode to avoid conflicts in collaboration.
* See suggestions and discover RAML syntax via a “shelf” built.
* Preview markdown and JSON files.
* Many bug fixes.
* Improved syntax highlighting.
* Preview your API with the new RAML console.

////
== Known Issues

////
