= Design Center Release Notes

== Design Center 1.0 beta 4

=== New Features

*Flow Designer*

* Support for new flow control components
** link:/mule-user-guide/v/4.0/choice-router-concept[Choice Router] enables you to make logical decisions and route to specific event processors or other flows.
** link:/mule-user-guide/v/4.0/for-each-scope-concept[For Each Scope] enables you to loop over payload content.
** link:/mule-user-guide/v/4.0/try-scope-concept[Try Concept] enables you to to incorporate link:/mule-user-guide/v/4.0/error-handling[Error Handling Logic] into your flows. Using error handlers, you can select specific errors that occur
** link:/connectors/v/latest/flowref_about[Flow Refs] enable you to call out to other flows from your main flow.

* Support for REST connect [LINK to docs], which provides a connector in the component selector for every API that is published in Exchange. This enables you to easily discover APIs as part of your design process and consume them without having to know the details of how the API works.
* A new card selector, which provides summaries of what the components do and enables you to quickly navigate to Exchange to see more information.
* Simplified HTTP experience: You can now use a URL directly, without needing to split the host and path into separate fields. There is also a suggested set of methods you can use.
* link:/design-center/v/1.0/user-access-to-design-center[Design environments] enable you to develop applications using flow designer, without consuming your Sandbox VCores.
* link:/design-center/v/1.0/manage-dependency-versions-design-center[Dependency management] enables you to manage the versions of your connectors and modules, so that you can upgrade or downgrade at any time.
* You can now rearrange flows by clicking on a card and dragging that card to a different location.
* Support for deleting event processors where the component no longer exists or is unknown, e.g. due to a version change where the operation no longer exists.
* Support for the Mule 4.0 Beta release [LINK release notes]

*API Desiger*

* Suggestions “shelf” built into the RAML console, to help you to discover RAML language syntax.
* Introduced an initial version of the new branching capabilities, which enables you to create and delete a branches for your API specification
* Introduced edit and read-only mode for branches to avoid conflicts in collaboration.
* Added autosave capability.
* New previews for markdown and JSON files.
* Improved syntax highlighting
* RAML Parser bug fixes
* Improved API console
* Support for exporting OpenAPI 2.0 documents



=== Known issues:

*Flow Designer*

* TLS configuration fields are now available, but will not yet result in a valid CloudHub application.
* DataWeave does not support XML attributes yet

*API Designer*

* Publish may occasionally fail with a "Exchange error: Not Found" and user needs to retry operation.
* Logout menu does not open inside API designer and user needs to go to Project List.
* RAML shelf dos not always return complete list of suggestions for the cursor position.
* Query parameters examples are not send unless modified inside the console TryIt.



== Design Center 1.0 beta 3

=== New Features

* Improved usability of the Live tab by splitting it into separate Input and Output tabs and reorganizing the layout.
* Project cloning capabilities
* Improved support for operations without parameters
* Many bug fixes
