= Design Center Release Notes: Features for Creating API Specifications

These release notes cover the following versions of these features:

* link:/release-notes/design-center-release-notes-api_specs#2-2-7-may-16-2018[2.2.7]
* link:/release-notes/design-center-release-notes-api_specs#2-2-6-april-20-2018[2.2.6]
* link:/release-notes/design-center-release-notes-api_specs#2-2-5-april-6-2018[2.2.5]


== 2.2.7 May 16, 2018

This release fixes these issues:

* Supplying a base URI parameter in the visual editor, using the parameter in a base URI, closing the visual editor, and then reopening the project resulted in an error message and a blank middle panel.
* Selecting the type Number for a new Data Type in the visual editor, specifying a format, and changing the type to Integer resulted in the RAML viewer still including the specified number format.
* In the visual editor, changing the type for a base URI parameter caused the RAML viewer to show the new type, but the *Type* field continued to show the previously selected type.


== 2.2.6 April 20, 2018

This release fixes these issues:

* Attempts to import OAS JSON files would result in this error message being displayed: `Cannot read property 'hasOwnProperty' of null`  Such files could also fail to be converted by the JSON-to-RAML online conversion tool.
* Some warning and error messages were not being displayed.


== 2.2.5 April 6, 2018

This release includes two enhancements and fixes an issue:

=== Enhancements

* The left sidebar of the editor now lists groups, their resources, and their datatypes.
* An example API to use in the visual editor is now available from a link in the left sidebar.

=== Fixed Issue

The word "type" could not be used as the name of a property in a RAML API specification.
