= Design Center Release Notes
:keywords: release notes, design center, flow designer, api designer, mule application, editor, raml, swagger

== 1.0 - July 29, 2017


This release includes the new web-based Design Center that enables you to easily create web-based integration flows, design API specifications, and create reusable API fragments.

=== Flow designer

With release you can:

* Create and manage Mule application projects.
* Design flows using a simple step-by-step process with the ability to quickly navigate to Exchange to see more information.
* Connect to systems and protocols using different connectors, including databases, FTP, HTTP, SOAP web services, Salesforce, Workday, and others.
* Support for REST connect, which provides a connector in the component selector for every API that is published in Exchange. This enables you to discover APIs as part of your design process and consume them without having to know the details of how the API works.
* Perform complex data transformations using DataWeave with a visual drag-and-drop editor.
* View live data, so you can easily debug your flows.
* Create and manage data types for XML, JSON, CSV, and objects.
* Control the flow of data:
** Choice Router enables you to make logical decisions and route to specific event processors or other flows.
** For Each Scope enables you to loop over payload content.
** Try Scope enables you to incorporate error-handling logic into your flows. Using error handlers, you can select specific error types that could occur, and define a behavior to deal with each.
** Flow Refs enable you to call out to other flows from your main flow.
* Store and retrieve information from the Mule Object Store.
* Use design environments, which enable you to develop applications using flow designer, without consuming your Sandbox VCores.
* Manage dependencies, so you can control the versions of your connectors and modules, to upgrade or downgrade at any time.

Underpinning this release is the initial release of Mule 4.0 Runtime. This release is currently only available to Design Center users. More details on what’s new in Mule 4 can be found in the Mule Runtime section.


=== API designer

This release of Design Center enables you to:

* Edit RAML API specifications and fragments.
* Publish and consume reusable API fragments, so that common best practices, data types, or security schemes can be reused across APIs.
* Mock and test APIs.
* Import and export Open API Specification (OAS) 2.0.
* Create and delete branches for your API specification or fragment.
* View projects in edit and read-only mode to avoid conflicts in collaboration.
* See suggestions and discover RAML syntax via a “shelf” built.
* Preview your API with the new RAML console.



== Browser Compatibility

[%header,cols="2*a"]
|===
| Browser | Version
| Chrome | 54.0.x or later
| FireFox | 50.0.x or later
| Safari | 10.1.x or later
| Edge | Version 40.12 or later
|===


== Known Issues (Flow designer)
* Currently the flow fesigner is not supported on IE Browser
* Exporting to Studio, some DataWeave expressions on fields aren't exported. Specifically those that reference nested elements using selectors.
* Metadata: While creating the application, no metadata is resolved until the worker is finally created. Once the application is running, the metadata will be refreshed for existing cards in the flow.
* Live View does not properly show list of message objects for FTP List operations.
* Live View - sometimes Consume is not retrieving anything, therefore live view does not show anything
* Publishing assets to exchange or uploading Drivers. User will need to have exchange permissions. Also a more accurate error is required to be retrieved when not having enough permissions
* Currently Datasense is not supported for Flow Ref
* Transform presents some mapping simple types issues 
* Cloning Projects is only available for Mule Applications type projects
* The validation all operation is not available 
* Project management view does not show correct dates in the project list and in the detail panel
* Unlock takes 5 min to unlock a project
* Test connectivity failure causes deployment failure
* Uploading files for every connector other than HTTP, like keystores or private keys, is not currently supported

== Known Issues (API designer)
* Users cannot move files to a folder via drag and drop in Firefox
* API Designer does not delete baseUri parameter if header of file is changed to a fragment and mocking server is running



