= Design Center Release Notes
:keywords: release notes, design center, flow designer, api designer, mule application, editor, raml, swagger

These release notes cover the following versions of Design Center:

* link:/release-notes/design-center-release-notes#1-1-september-30-2017[1.1]
* link:/release-notes/design-center-release-notes#1-0-3-august-26-2017[1.0.3]
* link:/release-notes/design-center-release-notes#1-0-2-august-12-2017[1.0.2]
* link:/release-notes/design-center-release-notes#1-0-1-august-4-2017[1.0.1]
* link:/release-notes/design-center-release-notes#1-0-july-29-2017[1.0]

== 1.1 - September 30, 2017

This release incorporates new features, changes, and bug fixes.

*Summary of enhancements* 

* New flow design features at the runtime level
* DataWeave and UX improvements
* Capability to open a project in a new tab
* Warnings of an API design file or directory deletion


=== Features and Changes

* To simplify DataWeave scripts, the “variable” keyword was replaced by “vars”.

* A new “targetValue” attribute simplifies enrichment: this parameter defaults to #[payload] but is only considered if the target attribute is provided.

* Email connector: #[payload.body] is now available to access the body with or without attachments.

* WebServiceConsumer and SC based extensions: Soap Headers have been moved from attributes to the payload.  For accessing the body with or without attachments #[payload.body] is now available.

* Reconnection and connectivity testing: when connectivity is tested at start time but fails, the default behavior now is to log a warning message and continue with the deployment. Also, operations can now  have a reconnection strategy different from the one in the connector configuration.

* DataWeave improvements: now arrays of binary data are supported and data type names or type aliases are displayed as labels in the input/output view.

* You can now right-click a project name and choose Open in a new tab.

=== Fixes/Improvements

*Flow design*

* Support for Internet Explorer 11 and Edge on Windows 7 and 10.
* New messages to inform the lack of resources when creating, deploying and cloning projects.
* Capability to remove applications that are associated with non-existing Design environments.
* Dependency manager improvements: unknown dependency removal messages.
* New “Fix it” messages in the transform when applicable.
* Dictionary editor input expression in the value is fixed.
* Improvement in the mapping messages for cardinality issues.
* Drag and drop cards into a Try scope.
* New confirmation popup for the Clear Data Type and the Keep Transformation operations.
* Allow adding capital characters in the project list search.
* Session expired relogin improvement popup now redirects to Design Center.
* New custom types support in flows. 
* Improve workspace restart experience.
* Fixed project unlock when closing the browser.
* Improved Datasense/Dataweave performance.
* Target Variable is now working for Foreach.

*API design*

* Fixed an issue that randomly caused lost files.
* Scrolling left no longer causes an unexpected back function to occur in the browser.
* After importing a large zip file, the project lock is not longer lost.
* Fixed an issue causing inaccuracies in the Business Group drop-down in the Consume Fragment dialog.
* Fixed the issue that caused importing a file to replace a file inside a folder to fail. 
* Fixed an issue preventing decompression of .zip files generated by exporting a project on Windows OS. 
* Fixed an issue causing file autocomplete to fail when used with files inside folders.

=== Known Issues 

* Some of the limitations of v1.0.2 apply to this version.
* Literal arrays cannot be edited from function editor in the transform.
* To use Object Store v2, the user needs certain entitlements. Otherwise, Object Store V1 is used.
* Web Service Consumer XML validation error leaves application in a failed state.
* Re-login popup and some other issues with Safari version 10.1.2 and 11.0.0.
* Adding other connector next to the WSC will require the use of a transformation between them 
* Adding a Data Type from the Live View for a WSC will not be possible

*Known Issues -- Applies to Mule Applications Created in Design Center 1.0 - 1.0.3*

* Flows using Email without attachments trying to access  the body: for accessing the body you need to use payload.body instead of payload.
* Flows using Web Service Consumer having transformations or expressions using `attributes.headers` need to be updated to `payload.headers`.
* Flows using cards that enable Reconnection strategy need to be re-setup to start using the runtime functionality changes.
* The output for Web Service Consumer and Email is now changed from a MultipartPayload to an object; therefore, some applications may stop working until the output mapping is fixed.

== API 

== 1.0.3 - August 26, 2017

API designer bug improvements and bug fixes are included in this release:

=== Improvements

* Added filtering by business group when searching for Exchange dependencies.

=== Bugs Fixed

* Fixed a random connection issue with an underlying service (VCS).
* Fixed an issue with the deletion of special characters from resources that included uriParameters.
* The autocomplete option is no longer hidden by other components from the UI.

== 1.0.2 - August 12, 2017

This release includes in-app links to documentation, it also includes bug fixes in several components such as the Choice, Try, and Transform components. 

=== Bugs Fixed

* For the Choice component, the Default option isn't shown by default unless the user adds it initially.
* A parser error occurs when adding a Try card. This is because it's not made clear that the Type field is required.
* Missing tooltips on the top (right) toolbar - the following were added: "Download Mule Application" and "Support".
* Auto completion doesn't work in the DataWeave function editor.
* DataWeave unnecessarily underlines the script as having an error.
* Improve transformer inline function editor error handling in DataWeave. Errors aren't shown in the DataWeave inline Function Editor because the provided model caused false errors during scoping.
* The Transform Message component forces you to select a mapping when you shouldn't have to.
* Suggestions get cut off in the Choice card.
* When restarting a workspace, an error is shown before the workspace is created.
* File leak issue in the Execution Service.
* Improve Transform component`s performance.
* Null File-Name error issue in Runtime Manager.
 
 
=== Known Issues

* The Same limitations from version 1.0.0 apply to this version.
* Live View for Transform Card is not working when placed before a DataBase card.
* Dictionary Editor is not working in Windows chrome.
* Literal arrays can not be edited from function editor in the transform.
* Web Service Consumer xml validation error leaves application in a failed state.
* Target Variable is not working for Foreach.


== 1.0.1 - August 4, 2017

This release included the following improvements:

* Fix around the Get Started button: it's hidden when a user has no API Designer entitlement
* Segment.io integration fixes
* 3 minor UI fixes


== 1.0 - July 29, 2017


This release includes the new web-based Design Center that enables you to easily create web-based integration flows, design API specifications, and create reusable API fragments.

=== Flow designer

With release you can:

* Create and manage Mule application projects.
* Design flows using a simple step-by-step process with the ability to quickly navigate to Exchange to see more information.
* Connect to systems and protocols using different connectors, including databases, FTP, HTTP, SOAP web services, Salesforce, Workday, and others.
* Support for REST connect, which provides a connector in the component selector for every API that is published in Exchange. This enables you to discover APIs as part of your design process and consume them without having to know the details of how the API works.
* Perform complex data transformations using DataWeave with a visual drag-and-drop editor.
* View live data, so you can easily debug your flows.
* Create and manage data types for XML, JSON, CSV, and objects.
* Control the flow of data:
** Choice Router enables you to make logical decisions and route to specific event processors or other flows.
** For Each Scope enables you to loop over payload content.
** Try Scope enables you to incorporate error-handling logic into your flows. Using error handlers, you can select specific error types that could occur, and define a behavior to deal with each.
** Flow Refs enable you to call out to other flows from your main flow.
* Store and retrieve information from the Mule Object Store.
* Use design environments, which enable you to develop applications using flow designer, without consuming your Sandbox VCores.
* Manage dependencies, so you can control the versions of your connectors and modules, to upgrade or downgrade at any time.

Underpinning this release is the initial release of Mule 4.0 Runtime. This release is currently only available to Design Center users. More details on what’s new in Mule 4 can be found in the Mule Runtime section.


=== API designer

This release of Design Center enables you to:

* Edit RAML API specifications and fragments.
* Publish and consume reusable API fragments, so that common best practices, data types, or security schemes can be reused across APIs.
* Mock and test APIs.
* Import and export Open API Specification (OAS) 2.0.
* Create and delete branches for your API specification or fragment.
* View projects in edit and read-only mode to avoid conflicts in collaboration.
* See suggestions and discover RAML syntax via a “shelf” built.
* Preview your API with the new RAML console.



== Browser Compatibility

[%header,cols="2*a"]
|===
| Browser | Version
| Chrome | 54.0.x or later
| FireFox | 50.0.x or later
| Safari | 10.1.x or later
| Edge | Version 40.12 or later
|===


== Known Issues (Flow designer)
* Currently the flow fesigner is not supported on IE Browser
* Exporting to Studio, some DataWeave expressions on fields aren't exported. Specifically those that reference nested elements using selectors.
* Metadata: While creating the application, no metadata is resolved until the worker is finally created. Once the application is running, the metadata will be refreshed for existing cards in the flow.
* Live View does not properly show list of message objects for FTP List operations.
* Live View - sometimes Consume is not retrieving anything, therefore live view does not show anything
* Publishing assets to exchange or uploading Drivers. User will need to have exchange permissions. Also a more accurate error is required to be retrieved when not having enough permissions
* Currently Datasense is not supported for Flow Ref
* Transform presents some mapping simple types issues 
* Cloning Projects is only available for Mule Applications type projects
* The validation all operation is not available 
* Project management view does not show correct dates in the project list and in the detail panel
* Unlock takes 5 min to unlock a project
* Test connectivity failure causes deployment failure
* Uploading files for every connector other than HTTP, like keystores or private keys, is not currently supported


== Known Issues (API designer)

* In a Try scope, selecting errors of Type `CORE` in the error handler doesn't work.

* The For Each scope doesn't support using a target variable as an output.

* Users cannot move files to a folder via drag and drop in Firefox

* API Designer does not delete baseUri parameter if header of file is changed to a fragment and mocking server is running



