= Anypoint Exchange On-Premise Edition Release Notes
:keywords: release notes, exchange, on-premise

*October, 2016 -- Beta*

== Description

Anypoint Exchange On-Premise Edition takes the power of cloud-based Anypoint Exchange and enables companies to run the platform inside their data centers.

IMPORTANT: Because this is a private version of Anypoint Exchange, you cannot see the public content available in the Cloud Version.

=== System Requirements

See "System Requirements" in the link:/release-notes/v/latest/anypoint-platform-on-prem-1.1.0-release-notes[Anypoint Platform On-Premise Edition Release Notes].

== Version 1.7.1 - On-Premise Release (Beta)

This release provides new features and bug fixes.

=== Version 1.7.1 - Features

The following features comprise changes that occurred between the previous Anypoint Exchange
On-Premise version 1.4.1 (May 2015) and the currently release:

. Content ratings
. Objects can now have the author's name and photo
. WSDL support
. Item type colors
. Auto populating URI for new items
. Auto resizing description container for editing
. Core services organization ID
. Business groups
. Artifact states
. Transition flows
. Exchange roles
. Private Exchange connectors can be installed in Studio
. Audit log of all actions in a private Exchange
. The RAMLs label was changed to REST APIs and the WSDLs label was changed to SOAP APIs
. Requires Studio 4.2.0 and newer

=== Version 1.7.1 - Changed Features

The following features changed between versions 1.4.1 and 1.7.1:

. Removed video caption field until a video URL is added.
. Removed `/mulesoft` from a path.
. Removed object amount limitation for private Exchanges.
. Removed editing types within an organization.
. Editing terms are now only available to Admin roles.

=== Version 1.7.1 - Current Differences with the Cloud Version

At the time of this release notes, the Anypoint Exchange Cloud version is at 1.7.0. The only
change in the on-premise beta is the new REST APIs and SOAP APIs labels.

=== Version 1.7.1 - Known Issues

None.

== Version 1.4.1 - On-Premise Release

This Anypoint Exchange release includes the following new features and functionality:

* Create and Publish private content: Choose between a variety of content types (templates, examples, connectors, and more) to add, describe your asset, and publish it in your organization’s exchange. Only the people you choose may have access to create and publish new content.

* Search for Content: Users within your organization can find the internally published content (as well as MuleSoft’s public content), increasing the chance of reuse and avoiding redundant work. Exchange Admins can customize search filters to make internal content easier to find.

=== Version 1.4.1 - Known Issues
To access private content from Anypoint Studio, version 4.2.0 or newer must be used.

== See Also

* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
