= May 2016 Exchange Release Notes (Draft)

== May 2016 Release

This new version of Anypoint Exchange includes new features & functionality for addressing the viewing and publishing of artifacts across a hierarchical organization structure. Also within this version of Exchange aligns with the Anypoint Platform Styles and use of the new Nav Bar.

=== Features and Functionality

The following sections describe the new features in this release.

==== Visual Enhancements

Alignment with the Anypoint Platforms Styles and Integration with the latest Anypoint Platform Navigation Bar.

==== Roles for Exchange

Besides the existing Organization Owner, Contributor and Administrator Roles, a separate Viewer role was created.

==== New State and Flow Transition of an Artifact

To address the movement of an artifact across a hierarchical structure, Exchange now provides new states for an artifact and also specific actions to be performed on them.

==== Business Groups

Business Groups are being incorporated in Exchange . This feature across with the Exchange Roles and the new state transition flow of an artifact provides:

* Ability of Central IT (maybe the root organization) to create artifacts and make them available to all Lines of Businesses (sub organizations)
* Ability of Central IT to locate artifacts published in a sub organization and make it available to the rest of the business
* Ability of an LOB to publish artifacts for internal (to that sub organization) consumption

==== UI and UX Improvements

New Filters and actions now support the new Business Groups, Artifacts States, and Transition Flows functionalities.

==== Edit Types Removal

Edit Terms only available on Master Organization for Admin and Owner Organization

==== API Changes

Before this release, Exchange used an internal Organization ID in the API resource, but this organization ID is replaced with the Core Services Organization ID to allow Business Groups.
New endpoints are being incorporated in Exchange to work with Business Groups.
New permissions are applied using the Business Groups hierarchy.

==== Avoid Losing User Data

When a session expires, Exchange prompts for credentials and completes the action.
Exchange now displays a warning when a user tries to leave the edit page if there are unsaved changes.

=== Removed Features

* The object amount limitation for private tenants has been removed. The possibility to request to increase the object amount limit it’s already removed from the Exchange configuration in Anypoint Platform access management.
* The possibility to edit types was removed, all organizations now share the same types.
* The feature to edit terms can now only be enabled for users with Admin roles in master organizations.

=== Architecture Changes

* Split UI from backend in different servers and all the related changes to fulfill this Architecture change.
* Update Node.js version to v4.

== See Also

* link:http://training.mulesoft.com[MuleSoft Training]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://blogs.mulesoft.com[MuleSoft Blogs]
* link:http://forums.mulesoft.com[MuleSoft Forums]
