= HL7 Connector Release Notes
:keywords: release notes, connectors, hl7

_Premium_  

*Documentation* :  link:/healthcare-toolkit/v/3.0/[Healthcare Toolkit]

== Version 3.0.0 - January 6, 2017
[IMPORTANT]
Release notes for version 3.0 of the HL7 EDI Connector. (HL7 stands for link:http://en.wikipedia.org/wiki/Health_Level_7[Health Level 7].)
Anypoint Connector for HL7 is a collection of features that facilitates integration with healthcare systems by providing the tools needed to easily create, read, and transform HL7 version v2.x messages within Mule.  The releae notes for HL7 MLLP v1.0.0 can be found link:https://docs.mulesoft.com/release-notes/hl7-mllp-connector-release-notes[here].

HL7 EDI Connector v3.0.0 is compatible with the following:

[%header,cols="2*"]
|===
a|
Application/Service

 a|
Version

|Mule ESB Runtime |3.6.0 and later
|Anypoint Studio |5.0.0/January 2015
|HL7 | v2.1, v2.2, v2.3, v2.3.1, v2.4, v2.5, v2.5.1, v2.6, v2.7, v2.7.1, v2.8, v2.8.1
|===

* Extension segments supported using overlay or custom schemas, or by generic handling for segments matching a pattern
* Parsing throws an exception when the message is not properly formatted or an error occurs when reading the input stream
* Fatal errors in parsing (as per configuration) result in acknowledgment code 'AR' (for Application Reject) in the ACK message generated by the parse; non-fatal errors result in acknowledgment code 'AE'

=== Version 3.0 Fixed in this Release

There are no bug fixes in this release.

=== Version 3.0 Known Issues

HL7 EDI Connector only support ER7 format of HL7 messages.

== Version 2.0 - February 13, 2015

Release notes for version 2.0 of the HL7 connector. (HL7 stands for link:http://en.wikipedia.org/wiki/Health_Level_7[Health Level 7].)

Anypoint Connector for HL7 is a collection of features that facilitates integration with healthcare systems by providing the tools needed to easily create, read, and transform HL7 version v2.x messages within Mule.

=== Version 2.0 Compatibility

HL7 connector v2.0 is compatible with the following:

[%header,cols="2*"]
|===
a|
Application/Service

 a|
Version

|Mule ESB Runtime |3.6.0 and later
|Anypoint Studio |5.0.0/January 2015
|HL7 | v2.1, v2.2, v2.3, v2.3.1, v2.4, v2.5, v2.5.1, v2.6
|===

[IMPORTANT]
HL7 connector v2.0 is not backward compatible with Mule versions prior to 3.6.0.  If you are using an older version of Mule runtime, please use HL7 connector 1.4.0.

=== Version 2.0 Features and Functionality

Version 2.0 supports updated:

* *HAPI libraries*: The connector now uses HAPI 2.2 libraries, enabling extended compatibility across systems using HL7 standard messages.
* *Mule runtime versions:* The connector is now compatible with Anypoint Studio 5.0.0 (January 2015) and Mule ESB 3.6.0 and later.

=== Version 2.0 Fixed in this Release

There are no bug fixes in this release.

=== Version 2.0 Known Issues

HL7 messages are currently supported only in ASCII character set.

== Version 1.3.0 - May 21, 2014

Anypoint Connector for HL7 is a collection of features that facilitates integration with healthcare systems by providing the tools needed to easily create, read and transform HL7 version v2.x messages within Mule.

=== Version 1.3.0 Compatibility

HL7 Connector 1.3.0 is compatible with the following versions of Mule Runtime and HL7 respectively.

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |3.5.0
|Anypoint Studio |May 2014
|HL7 |2.X
|===

=== Version 1.3.0 Features and Functionality

There are no additional features introduced in this release. With the latest release, however, the existing features and functionality of HL7 connector are supported in  Mule runtime 3.5.0. For Mule versions prior to 3.5.0, please use HL7 Connector 1.2.0.

=== Version 1.3.0 Fixed in this Release

There are no bug fixes in this release.

=== Version 1.3.0 Known Issues

There are no reported issues that are unresolved in this release.


== See Also

* Learn how to link:/getting-started/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Learn more about link:/healthcare-toolkit/v/2.0/hl7-global-connector[HL7 connector].
* Access MuleSoft’s link:http://forums.mulesoft.com[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[subscribe] to Mule Enterprise and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal].
