= IBM CICS Transaction Gateway Connector Release Notes
:keywords: release notes, ibm ctg, cics, jca, connector

*September 2017*

*_Premium_*

The IBM CICS Transaction Gateway (IBM CTG) connector provides integration with back-end CICS applications using the CICS Transaction Gateway. For Java platforms, CTG implements the JCA resource adapter to connect Java applications to the CICS system.
This connector provides access between Mule applications and the CTG.

link:/mule-user-guide/v/3.8/ibm-ctg-connector[IBM CTG Connector User Guide]

== Version 1.0.0 - September 28, 2017

=== Compatibility

[%headercols="50a,50a"]
|===
|Software |Version
|Mule Runtime |3.8
|IBM CICS TG (for Multiplatforms and for z/OS) |9.1 and 9.2
|IBM CICS TG SDK |9.1 and 9.2
|===

*Notes:*

* The remote CICS TG must be at the same or a higher release level as the version of the JCA resource adapter.
* The JCA resource adapter must match the CICS TG platform. For example, if you have CICS TG for Multiplatforms, you cannot connect to it from a CICS TG for the z/OS resource adapter.

Required JAR files to configure this connector:

* `ccf2.jar` (CICS Common Connector Framework)
* `cicsjee.jar` (CICS JEE)
* `ctgclient.jar` (CTG Client Library)
* `ctgserver.jar` (CTG Server Library)
* `geronimo-j2ee-connector_1.6_spec-1.0.jar` (JCA 1.6 specification)

*Note:*

* JCA 1.6 is needed as a required library to overcome conflicts with JCA 1.5 shipped with the Mule Runtime.

=== Features

* Authentication - The connector uses the IPIC (IP interconnectivity) protocol to establish communication with CICS regions over TCP/IP. This type of connection also supports SSL authentication.
* Execution of CICS Programs - The connector allows users to invoke CICS programs:
** Using Channels and Containers.
** Using a COMMAREA. Data transfers are limited to 32 KB.
* Transactions - The connector leverages XA Transactions by means of Mule's Transactional scope and the Bitronix Transaction Manager components.
* DataSense - The connector supports adding metadata using through the Custom Metadata Tab option. Using the copybook feature, you can import a schema that describes the data structure going in and out of CTG for use with DataWeave.

See: https://docs.mulesoft.com/anypoint-studio/v/6/defining-metadata[User-defined metadata in Anypoint Studio].

=== Fixed in this Release

* None.

=== Known Issues

* Although the inclusion of JCA 1.6 as a required library is meant to solve compatibility conflicts with the JCA 1.5 shipped with the Mule Runtime, it is yet unknown if this will cause side effects.

== See Also

* Learn how to link:/mule-user-guide/v/3.8/installing-connectors[Install Anypoint Connectors] using Anypoint Exchange.
* Access the http://forum.mulesoft.org/mulesoft[MuleSoft Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, visit the https://support.mulesoft.com[Support Portal].