= LDAP Connector Release Notes
:keywords: release notes, ldap, active directory, connector

_Select_

*November 2017*

The Lightweight Directory Access Protocol (LDAP) is an open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol (IP) network. The LDAP connector allows Mule applications to interact with LDAP servers.

== Version 3.0.0 - November 18, 2017

Release notes for version 3.0.0 of the LDAP connector.

=== Version 3.0.0 Compatibility

The LDAP Connector is compatible with:

[%header%autowidth]
|===
|Application/Service|Version
|Mule Runtime|4.0.0
|Java|1.8 or higher
|===

=== Version 3.0.0 Features

* The LDAP connector is built with the new AnyPoint SDK (aka Extensions Framework) v1.0.0-rc-SNAPSHOT.

=== Version 3.0.0 Fixed in this Release

* Fixed an exception when member ranges were used along schemaEnabled.
  (P.S. : Member ranges are feature specific to Active Directory.)
* Added support for custom trust store through Extended configuration parameters. 

=== Version 3.0.0 Known Issues

None.


== Version 2.1.0 - October 13, 2016

Release notes for version 2.1.0 of the LDAP connector.

=== Version 2.1.0 Compatibility

The LDAP Connector is compatible with:

[%header%autowidth]
|===
|Application/Service|Version
|Mule Runtime|3.5.0 or higher
|Java|1.7 or higher
|===

=== Version 2.1.0 Features

* Bind Operation now accepts authDN, authPassword and authentication.

=== Version 2.1.0 Fixed in this Release

* Fixed TLS connection to use the correct context on which TLS is initialised, now TLS can be used to set password for Active Directory.
* LDAP Entry allows DN to be obtained by getting attribute dn. Get call on LDAPEntry for DN returns the distinguished name.
* LDAP Entry allows having null attribute value. Get call on LDAPEntry for a null valued attribute returns null instead of throwing a null pointer exception.

=== Version 2.1.0 Known Issues

None.

== Version 2.0.1 - April 8, 2016

Release notes for version 2.0.1 of the LDAP connector.

== Version 2.0.1 - April 8, 2016

Release notes for version 2.0.1 of the LDAP connector.

=== Version 2.0.1 Compatibility

The LDAP Connector is compatible with:

[%header%autowidth]
|===
|Application/Service|Version
|Mule Runtime|3.6.x or higher
|Java|1.7.0_x or higher
|Anypoint Studio|5.2 or higher
|===

=== Version 2.0.1 Features

* Upgraded connector for compatibility with Anypoint Connector DevKit v3.8.1
* The following operations are supported:
** Bind - Authenticates against the LDAP server. This occurs automatically before each operation but can also be performed on request.
** Search - Performs a LDAP search in a base DN with a given filter.
** Search one - Performs a LDAP search that is supposed to return a unique result.
** Paged result search - Performs a LDAP search and streams result to the rest of the flow.
** Lookup - Retrieves a unique LDAP entry.
** Exists - Checks whether a LDAP entry exists in the LDAP server or not.
** Add - Creates a new LDAP entry.
** Add single value attribute - Adds specific single valued attribute to an existing LDAP entry.
** Add multi-value attribute - Adds specific multi-valued attribute to an existing LDAP entry.
** Modify - Update an existing LDAP entry.
** Modify single value attribute - Updates specific single valued attribute of an existing LDAP entry.
** Modify multi-value attribute - Updates specific multi-valued attribute of an existing LDAP entry.
** Delete - Delete an existing LDAP entry.
** Delete single value attribute - Deletes specific single valued attribute to an existing LDAP entry.
** Delete multi-value attribute - Deletes specific multi-valued attribute to an existing LDAP entry.

=== Version 2.0.1 Fixed in this Release

* Deprecated message processors (addFromMap & modifyFromMap) have been sunset and no longer available.

=== Version 2.0.1 Known Issues

None.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
