= LDAP Connector Release Notes
:keywords: release notes, ldap, active directory, connector

Lightweight Directory Access Protocol (LDAP) is an Internet protocol used to access information from a server. The LDAP connector allows Mule applications to interact with LDAP servers.

*Guide*: link:/mule-user-guide/v/3.8/ldap-connector[LDAP Connector]

== Version 2.0.1 - April 8, 2016

Release notes for version 2.0.1 of the LDAP connector.

=== Version 2.0.1 Compatibility

The LDAP Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|3.6.x or higher
|Java|1.7.0_x or higher
|Anypoint Studio|5.2 or higher
|===

=== Version 2.0.1 Features

* Upgraded connector for compatibility with Anypoint Connector DevKit v3.8.1
* The following operations are supported:
** Bind - Authenticates against the LDAP server. This occurs automatically before each operation but can also be performed on request.
** Search - Performs a LDAP search in a base DN with a given filter.
** Search one - Performs a LDAP search that is supposed to return a unique result.
** Paged result search - Performs a LDAP search and streams result to the rest of the flow.
** Lookup - Retrieves a unique LDAP entry.
** Exists - Checks whether a LDAP entry exists in the LDAP server or not.
** Add - Creates a new LDAP entry.
** Add single value attribute - Adds specific single valued attribute to an existing LDAP entry.
** Add multi-value attribute - Adds specific multi-valued attribute to an existing LDAP entry.
** Modify - Update an existing LDAP entry.
** Modify single value attribute - Updates specific single valued attribute of an existing LDAP entry.
** Modify multi-value attribute - Updates specific multi-valued attribute of an existing LDAP entry.
** Delete - Delete an existing LDAP entry.
** Delete single value attribute - Deletes specific single valued attribute to an existing LDAP entry.
** Delete multi-value attribute - Deletes specific multi-valued attribute to an existing LDAP entry.

=== Version 2.0.1 Fixed in this Release

* Deprecated message processors (addFromMap & modifyFromMap) have been sunset and no longer available.

=== Version 2.0.1 Known Issues

None.

== See Also

* Learn how to link:/mule-fundamentals/v/3.7/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Read more about the link:/mule-user-guide/v/3.8/ldap-connector[LDAP Connector], including examples of how to use it
* Access MuleSoft’s link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, link:http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s link:http://www.mulesoft.com/support-login[Customer Portal]. 
