= LDAP Connector Release Notes
:keywords: release notes, ldap, active directory, connector

_Select_

*November 2017*

The Lightweight Directory Access Protocol (LDAP) is an open, vendor-neutral, industry standard application protocol for accessing and maintaining distributed directory information services over an Internet Protocol (IP) network. The LDAP connector allows Mule applications to interact with LDAP servers.

== Version 3.0.0 - November 18, 2017

Release notes for version 3.0.0 of the LDAP connector.

=== Version 3.0.0 Compatibility

The LDAP Connector is compatible with:

[%header%autowidth]
|===
|Application/Service|Version
|Mule Runtime|4.0.0
|Java|1.8 or higher
|===

=== Version 3.0.0 Features

* The LDAP connector is built with the new AnyPoint SDK (aka Extensions Framework) v1.0.0-rc-SNAPSHOT.

=== Version 3.0.0 Fixed in this Release

* Fixed an exception when member ranges were used along schemaEnabled.
  (P.S. : Member ranges are feature specific to Active Directory.)
* Added support for custom trust store through Extended configuration parameters. 

=== Version 3.0.0 Known Issues

None.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
