= Microsoft Service Bus Connector Release Notes
:keywords: release notes

*_Select_*

== Version 1.3.0 - April 04, 2017

Included in this release:

* The connector now supports sending/receiving large messages(more than 256KB) through Azure Service Bus queues. To enable this functionality a Azure Storage Account is needed, and the connection credentials for this account must be specified under the Azure Service Bus Connection Strategy. If these credentials are specified then the storage is used to store as a blob every message body sent through the queues using the specific Connection Strategy. When you're expecting to receive large messages the Storage credentials must also be specified so the connector can retrieve the message body from the Blob storage and delete the blob afterwards.
* Improved the connection management to prevent a potential deadlock issue.
* Fixed message loss issue when flow was running under Async processing strategies.
* Exposed additional metadata via DataSense
* Improved Demo packages including web forms to publish new messages to queues or topics.


== Version 1.2.0 - November 30, 2016

Included in this release:

* Added custom logic to handle non trivial types at message's properties.
* Added option to skip connectivity test at connector's startup.
* Improved performance when sending messages using SAS-based authentication.
* Improved reliability and stability with high-load.

== Version 1.1.0 - October 4, 2016

Included in this release:

* Added support to SAS-based authentication (that is, avoid providing username/password at configuration settings).
* Fixed message processing and acknowledge to ensure zero message loss high-reliability (that is, at-least-once delivery).

== Version 1.0.4 - April 7, 2016

A hotfix has been released for the Microsoft Service Bus Connector - version 1.0.4.

Changes in this release:

* Fixed message's consumption from partitioned topics.
* Improved error message for invalid property types.
* Improved message's production performance by caching connections.

== Version 1.0.3 - October 9, 2015

A hotfix has been released for the Microsoft Service Bus Connector - version 1.0.3.

Changes in this release:

* Added support for sending mule outbound properties as custom properties in the AMQP message.

== Version 1.0.2 - September 15, 2015

A hotfix has been released for the Microsoft Service Bus Connector - version 1.0.2.

Changes in this release:

* Upgraded qpid dependency to 0.3.2

== Version 1.0.1 - September 9, 2015

A hotfix has been released for the Service Bus connector - version 1.0.1.

Fixed in this release:

* The connector kept dequeuing message after the Mule application stopped or was undeployed. This has been fixed and the connector now stops dequeuing messages when the Mule application stops or undeploys.

== Version 1.0 - January 21, 2015

We are pleased to release a new connector for Service Bus. The ServiceBus connector v1.0 enables Windows Service Bus on-premises, or Azure Service Bus cloud-hosted reliable messaging integration scenarios. Support for queues, topics and event hubs is provided, with messages being sent or received via the AMQP 1.0 transport. Dynamic discovery and provisioning of Service Bus objects is possible via the built-in management API.

*Connector Guide*: link:/mule-user-guide/v/3.8/microsoft-service-bus-connector[Microsoft Service Bus Connector]

=== Version 1.0 Compatibility

[%header,cols="2*"]
|===
|Application/Service |Version
|Mule Runtime |3.5+
|Anypoint Studio |January 2015
|Service Bus a|
* Microsoft Azure Service Bus (Cloud)
* Microsoft Windows Service Bus (on-premises)
|===

== See Also

* Learn about the connector using the link:/mule-user-guide/v/3.8/microsoft-service-bus-connector[Microsoft Service Bus Connector] guide. 
* Read the link:/mule-user-guide/v/3.8/microsoft-service-bus-connector-faq[Microsoft Service Bus Connector FAQ].
* Learn how to link:/getting-started/anypoint-exchange[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s link:http://forums.mulesoft.com[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[subscribe] to Mule ESB Enterprise and log into MuleSoft http://www.mulesoft.com/support-login[Customer Portal].
