= Mule Agent 1.4.0 Release Notes
:keywords: mule, agent, 1.3, release notes

_Enterprise Edition_

*April 04, 2016*

Mule Agent 1.4.0 provides a new downloadable zip file to easily update Mule Agent.

link:http://mule-agent.s3.amazonaws.com/1.3.1/mule-agent-1.4.0.zip[Download Mule Agent 1.4.0 zip file].

*Mule Agent Install Guide*: link:/mule-agent/v/1.3.0/installing-mule-agent[Install the Mule Agent]

== Compatibility

[width="70%",cols="50a,50a",options="header"]
|===
|Software|Version
|Mule Runtime|3.6.n and 3.7.n
|API Gateway|2.n
|===

== Hardware and Software Requirements

No change.

== Features in this Release

* Support for static IP addresses: Agent can now support specific static addresses. Click here for latest Agent.

* Addition of an external handler to manage monitoring service tracked beans

== Deprecated Features and Functionality

None.


== Fixed Issues

AGENT-275  -  Remove the /mule/agent/ping endpoint since it's not used and causes the mule to exit

AGENT-277  -  Retrieve the correct Mule and GW version for the unified Mule Runtime 3.8.0

AGENT-278  -  The tracking tests are failing with a org/apache/http/ssl/TrustStrategy class not found error

AGENT-284  -  Mule Agent isn't detecting that the 3.8.0-M1 Mule Runtime is an unified runtime

AGENT-297  -  Configuring REST transport with custom key store isn't using the given file

AGENT-286  -  Report the runtime as Mule on server registration for Unified Runtimes


== Known Issues

None.

== See Also

* link:/mule-agent/v/1.3.0/[Mule Agent]
* link:https://www.mulesoft.com/webinars[MuleSoft Webinars]
* link:http://forums.mulesoft.com[MuleSoft's Forums]
* link:https://www.mulesoft.com/support-and-services/mule-esb-support-license-subscription[MuleSoft Support]
* mailto:support@mulesoft.com[Contact MuleSoft]
