= NetSuite Connector Release Notes 
:keywords: release notes, netsuite, oracle, connector

*March 2018*

The Anypoint Connector for NetSuite synchronizes data and automates business processes between NetSuite and third-party applications, either on-premises or in the cloud.

== Version 8.1.0 - March 13, 2018

=== Version 8.1.0 - Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is not the same as the SuiteTalk API version. Your account may be running on a version of NetSuite different to the version of the the API you are using.

=== Version 8.1.0 - Features

* Support for SuiteTalk API version 2017.2. For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2017.2 Release Notes > SuiteTalk (Web Services) Integration.

=== Version 8.1.0 - Fixed in this Release

None.

=== Version 8.1.0 - Known Issues

None.

== Version 8.0.0 - November 18, 2017

=== Version 8.0.0 - Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0
|SuiteTalk API | 2017.1
|===

The NetSuite version is not the same as the SuiteTalk API version. Your account may be running on a version of NetSuite different to the version of the the API you are using.

=== Version 8.0.0 - Features

* Support for SuiteTalk API version 2017.1. GA For a detailed list of changes, log into NetSuite, open *Help Center* and navigate to *New Release* -> *Release Notes* -> *NetSuite 2017.1 Release Notes* -> *SuiteTalk (Web Services) Integration*.
* Added support for *Mule 4* and removed support for *Mule 3*.

=== Version 8.0.0 - Fixed in this Release

None.

=== Version 8.0.0 - Known Issues

None.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
