= NetSuite Connector Release Notes 
:keywords: release notes, netsuite, oracle, connector

*March 2018*

The Anypoint Connector for NetSuite synchronizes data and automates business processes between NetSuite and third-party applications, either on-premises or in the cloud.

== 8.1.0

*March 13, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.2
|===

[NOTE]
The NetSuite version is not the same as the SuiteTalk API version. Your account may be running on a version of NetSuite different to the version of the the API you are using.

=== Features

* Support for SuiteTalk API version 2017.2. For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2017.2 Release Notes > SuiteTalk (Web Services) Integration.

== 8.0.0

*November 18, 2017*

=== Compatibility

[%header%autowidth.spread]
|===
|Software | Version
|Mule Runtime | 4.0.0 and later
|SuiteTalk API | 2017.1
|===

The NetSuite version is not the same as the SuiteTalk API version. Your account may be running on a version of NetSuite different to the version of the the API you are using.

=== Features

* Support for SuiteTalk API version 2017.1. GA For a detailed list of changes, log into NetSuite, open Help Center and navigate to New Release > Release Notes > NetSuite 2017.1 Release Notes > SuiteTalk (Web Services) Integration.
* Added support for Mule 4.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
