= NetSuite OpenAir Connector Release Notes
:keywords: openair, netsuite, release notes

The Anypoint Connector for NetSuite OpenAir is a closed source Enterprise connector which provides a connection between OpenAir and third party software.

link:/connectors/netsuite-openair-connector[NetSuite OpenAir Connector User Guide]

== Version 2.0.0 - Unreleased

=== Compatibility

[width="100%", cols=",", options="header"]
|===
|Software | Version
|Mule Runtime | 4.1.0
|===

=== Features

* Added support for *Mule 4* and removed support for *Mule 3*.

=== Fixed in this Release

None.

=== Known Issues

* **Metadata in Flow Designer** - Although metadata works under Anypoint Studio, Flow Designer shows incomplete structures. The connector can still be used, but metadata cannot be used as a guide.

== Version 1.0.2 - March 3, 2017

=== Fixed in this Release

* **Metadata is correctly generated in Studio** - Previously, when selecting any operation, the **oaObject** dropdown menu displayed duplicated entries and, in some cases, the input/output metadata was incomplete or truncated. Now, the connector displays list of oaObjects and the associated metadata.
* **Connector compatibility with Windows** - In some scenarios, the user would get an `Illegal character in path` error message when attempting to use the connector in a Mule environment under Windows. This was fixed.
* **Disable chunking on HTTP requests** - When the requests made by the connector contained a relatively large payload, OpenAir would fail to parse it. This is no longer the case.
* **Token refresh** - When the authentication token was invalidated, the connector would not always refresh it properly.
* **Namespace URI in requests** - Outgoing SOAP messages contained illegal `||` characters in the `bodyPrefix` attibute. Despite this not causing any issues, SOAP Envelopes were technically invalid.

== Version 1.0.1 - December 14, 2016

=== Compatibility

[cols=",",options="header",]
|===
|Software |Version
|Mule Runtime |3.7.0
|===

[NOTE]
The OpenAir Connector requires an *Enterprise* License. MuleSoft maintains this connector under the link:/mule-user-guide/v/3.7/anypoint-connectors#connector-categories[_Select_] support policy.

=== Features

None.

=== Fixed in this Release

* XML External Entities (XXE) vulnerability - By default, XML parsers are weakly configured thus enabling XML External Entity attack (e.g. disclosure of confidential data, denial of service, server side request forgery) when the application parses XML input. To prevent XXE,  DTDs (External Entities) have been completely disabled in all the XML parsers used by the connector.

== Version 1.0.0 - April 14, 2016

=== Compatibility

[cols=",",options="header",]
|===
|Software |Version
|Mule Runtime |3.7.0
|===

[NOTE]
The OpenAir Connector requires an *Enterprise* License. MuleSoft maintains this connector under the link:/mule-user-guide/v/3.7/anypoint-connectors#connector-categories[_Select_] support policy.

=== Features

* WSDL is retrieved dynamically from the user's OpenAir instance
* Supports OpenAir custom fields
* XML based request
* Auto Reconnection when session is expired
* Supported Operations:
** Add
** Createaccount
** Createuser
** Delete
** Getcrystalinfo
** Makeurl
** Modify
** Read
** Runreport
** Servertime
** Servertimewithtimezone
** Submit
** Upsert
** Version
** Whoami

=== Fixed in this Release

* The selected OpenAir object is added to the processor's Metadata.

== See Also

* NetSuite link:http://www.openair.com/download/NetSuiteOpenAirSOAPAPIGuide.pdf[OpenAir SOAP API Guide]
* https://forums.mulesoft.com[MuleSoft Forum].
* https://support.mulesoft.com[Contact MuleSoft Support].
