= Object Store v2 Release Notes
:keywords: osv2, object store, store

*August 2017 - Beta*

== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |3.7.4 and 3.8.2
|Anypoint Studio *&#8224;* |3.5.n and newer
|===

*&#8224;* The Object Store Connector works for both Object Store v1 and v2. 

The Object Store Connector saves values in key:value format whereas the Object Store capability in Anypoint Platform saves values in key:list format. If the Object Store Connector reads data stored with OSv2, only the element at position zero of the key:list is obtainable.

== Version 1.1 August 12, 2017 - Beta

Organization admins now have the ability to retrieve Object Store V2 client credentials used by Runtime Manager (CloudHub) applications to interact with the new beta object store service through the REST API.

== Version 1.0 November 5, 2016 - Beta

Introducing the new Object Store v2 beta release allowing users to share data and share states across batch processes, Mule components, and multiple distributed applications.

An object store is associated with an application.

=== Accessing Object Store v2

* You can view Object Store v2 features by logging into link:https://anypoint.mulesoft.com/#/signin[Anypoint Platform], clicking *Runtime Manager*, clicking an application, clicking *Manage Application*, and clicking *Application Data*.

* Use the Object Store Connector to retrieve data stored by Object Store v2.

* A REST API is provided that lets you store and retrieve values, and to perform administrative activities for an object store.

