= Partner Manager Connector Release Notes
:keywords: partner manager, connector, release notes, b2b

== Version 5.1.0 - March 1, 2017

=== Compatibility

Supported Mule Runtime Versions: 3.5.2, 3.6.1, 3.7.2, 3.7.3

=== New Features and Functionality

*harvest-document-properties* operation

=== Fixed Issues

*ClassCastException* no longer happens when attempting to read an XML document from *java.io.InputStream*.

=== Known Issues

Multiple configurations are not supported when *asynchronousMode* is enabled.


== Version 5.0.0 - February 23, 2017

=== Compatibility

Supported Mule Runtime Versions: 3.5.2, 3.6.1, 3.7.2, 3.7.3

=== New Features and Functionality

* Added support for asynchronous tracking
* Removed _lastEventId_ entry from _b2bTransmissionSession_ flow variable
* Added support for parent transactions
* Made _toPartyIdentifier_ optional in _resolve-routes_ operation
* Allowing the maximum number of HTTP connections to each Partner Manager service to be configurable
* Adding support for route filtering by properties

=== Migrating from Older Versions

* Replace references to lastEventId with transactionId

=== Known Issues

* Multiple configs are not supported when *asynchronousMode* is enabled


== Version 4.0.0 - December 13, 2016

=== Compatibility

Supported Mule Runtime Versions: 3.5.2, 3.6.1, 3.7.2, 3.7.3

=== New Features and Functionality

* Added *update-transaction-status* operation
* Removed deprecated *transportType* attribute in *resolve-routes* operation
* Added *harvest-endpoint-properties* operation
* Added ability to *track-document* operation to harvest properties
* Added *propagate-endpoint-properties* operation
* Added *lookup* operation

=== Migrating from Older Versions

* Remove *transportType* attribute in *resolve-routes* operation


== Version 3.1.0 - November 11, 2016

=== Compatibility

Supported Mule Runtime Versions: 3.5.2, 3.6.1, 3.7.2, 3.7.3

=== New Features and Functionality

* Added support for RosettaNet
* Added document property harvesting

=== Fixed Issues

* Fixed NullPointerException happening when *config-file-storage-custom* is used with EDIFACT or X12 module
* Permitting *partnerIdentifier* in *track-document* operation to override party identifiers in EDI documents
* Optimised caching


== Version 3.0.0 - September 22, 2016

=== Compatibility

Supported Mule Runtime Versions: 3.5.2, 3.6.1, 3.7.2, 3.7.3

=== Migrating from Older Versions

* Rename *document* attribute in *track-document* operation to *document-ref*
* Rename *partnerIdentifier* attribute in *resolve-routes* operation to *fromPartyIdentifier*
* Rename *partnerIdentifierType* attribute in *resolve-routes* operation to *partyIdentifierType*

=== New Features and Functionality

* Added document definition to list of resources that can be searched
* Added *count*, *offset*, *orderBy*, and *descending* attributes to *search* operation
* Added *toPartyIdentifier* attribute to *resolve-routes* operation

=== Fixed Issues

* Fixed issue where maps representing X12 and EDIFACT documents cannot be processed
* Fixed issue in resolve-routes operation where standard instead of version is passed to query parameter
* Propagating message properties to flow set in *config-file-storage-custom* config
* Ensuring HTTP connections are closed in instances where no content is returned
* Fixed issue where byte stream is mistakenly serialized to string when content is saved to custom file storage
* Removed test connectivity check on connector start up to make error message more friendly when testing the connection from Anypoint Studio


== Version 2.0.0 - July 8, 2016

=== Compatibility

Supported Mule Runtime Versions: 3.5.2, 3.6.1, 3.7.2, 3.7.3

=== New Features and Functionality

* Renamed *executionId* in *b2bTransmissionSession* to *transactionId*
* Added support for reporting errors to Anypoint Partner Manager
* Added operation for searching
* Added operation for resolving routes
* Added operation for tracking documents
* Added operations for replaying transactions
* Including last event ID in *b2bTransmissionSession* flowVar
* Removed *formatType* and *toPartyIdentifier* attributes from *track-transmission* operation
* Renamed *fromPartyIdentifier* attribute to *partnerIdentifier* and content attribute to *file* in *track-transmission* operation
* Added *transport* attribute to *track-transmission* operation


== Version 1.0.0 - December 22, 2015

=== Compatibility

Supported Mule Runtime Versions: 3.5.2, 3.6.1, 3.7.2, 3.7.3

=== New Features and Functionality

- Added facility to test connection
- Renamed connector to Partner Manager Connector
- Renamed environment attribute to environmentId and removed default value
- Caching options
