= RAML 1.0 Early Access Support

With the latest releases of the tooling and Anypoint Platform, MuleSoft introduces early access support for the official RAML 1.0 specification.  The new version introduces several new features, listed in the RAML.org comparison of releases. 

We are releasing our MuleSoft product support for RAML 1.0 at almost the same time as the GA release of RAML 1.0. To achieve this, we worked closely with the RAML workgroup for a  few months. As a result, we can enable MuleSoft customers to explore 1.0 concepts in Anypoint Platform via RAML release candidates. In most cases, customers should be able to write API definitions using RAML 1.0 without issues. 

This documentation lists known gaps in the early access support. 

== Migration Notice

Since the support for RAML 1.0 is early access, the default version used in the tooling is 0.8. Users who want to try version 1.0 have to change the version. 

For users migrating from RAML 0.8 to RAML 1.0 see the list of breaking changes between RAML 0.8 and RAML 1.0. 

IMPORTANT: 
RAML proxies based on RAML files written using the 1.0 version are valid only for Mule 3.8.0 runtimes. Previous Gateway versions don’t include support for RAML 1.0. 

== Underlying Parsers and Known Gaps

To include support for RAML 1.0 a new version of the JavaScript and Java parsers have been implemented. Mulesoft’s tooling relies on these parsers to validate the RAML and expose the required APIs. The following table shows the tooling dependencies for the parser implementations:

[width="100%",cols="30a,70a",options="header"]
|================
|Parser  | Tooling 
.5+| JavaScript | * API Designer
| * Mocking Service
| * API Console
| * Notebook
| * API Console in Studio
.4+| Java | * Mule 3.8.0
| * APIkit 3.8.0
| * RAML Editor in Studio
| * HTTP Connector
|================

== JavaScript Parser Known Gaps

The current JavaScript parser is 100% compliant with the specification, without any known gaps.  

== Java Parser Known Gaps
The current java parser is not fully compliant yet with the specification. The following table  lists feature gaps:

[width="100%",cols="30a,70a",options="header"]
|================
|Text  | Parameter 
| uses key | The link:https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#annotating-scalar-valued-nodes[spec] allows using uses in any fragment. At this moment the parser only allows its use in root level RAML documents and libraries.
| Annotations for scalar fields | The link:https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#annotating-scalar-valued-nodes[spec] allows applying annotations to scalar nodes besides certain mapping nodes. Annotations at scalar level are not supported.
| Overlays restrictions | Overlay application is not enforcing all the required restrictions. The extra restrictions that Overlays enforce vs. Extensions are not being validated.
.2+| Security Schemes gaps | * OAuth 1.0 `signatures` setting is not supported
| * OAuth 2.0 `authorizationUri` is always optional, no matter which authorization grants are used
| XML Examples validations against YAML types | Validation of XML examples against types defined in YAML are not supported. XML validations are only supported for schemas defined in XSD format.
.8+| type system gaps | These features, related to the definition, are not supported:  
| * Inheritance of primitive types 
| * discriminator field 
| * Examples nested in a value
| * Xml Facet field
| * Additional properties
| * null type
| * Properties named with trailing question marks
|================

Refer to link:https://github.com/raml-org/raml-java-parser/blob/0.1.0-alpha-2/MISSING.md[“RAML 1.0 Features Gap”] for the latest list. 

== Support Gaps by Product

=== API Console and Mocking Service

API Console and mocking service depends on the JavaScript parser for parsing out data types and overall API behaviors. API Console and Mocking Service currently doesn’t support link:https://github.com/raml-org/raml-spec/blob/raml-10/versions/raml-10/raml-10.md#annotations[annotations]. When you run an RAML file with RAML 1.0 annotations in API Console, Annotations do not appear in the Console documentation and Try It tab. Annotations are visible only from the RAML definition in API Designer, and don’t have any effect in Console and Mocking Service tools. 

=== API Notebook

API Notebook supports RAML 1.0 with the following limitations:

* Data types are not meaningful in this context
* Overlays are not meaningful in this context

=== APIKit

APIKit depends on the Java Parser for validating and scaffolding the RAML file, therefore it inherits the limitations of the Java parser listed above in “Java Parser Known Gaps” section. When the customer tries to scaffold a RAML file that contains elements not yet supported by the Java Parser, validation will fail and the flows will not be generated.

OData APIKit extension beta does not support RAML 1.0 and the new APIKit integrated within Studio 6.0. For customers using OData extension, postpone upgrading and continue to use Studio 5.4. The GA version of the OData implementation feature with Studio will be released in the near future.

=== Studio

Studio’s embedded RAML editor depends on the Java Parser for validating and suggesting RAML 1.0 syntax. The embedded APIKit also depends also on the Java Parser for the scaffolding feature (see below). The embedded API Console depends on the JavaScript parser, and has parity with API console standalone (see below). 

* Suggester for RAML 1.0 does not support RAML types and RAML files without a  header. Users might not benefit fully from the editor suggesting certain tags and auto-completion. 
* The embedded RAML 1.0 editor validation feature has parity with the Java parser. When users use the syntax related to RAML 1.0 listed above in the “Java Parser Known Gaps” section, they might get incorrect validations. 
* MUnit RAML-to-Test auto-generation feature does not support RAML 1.0. We are actively working to evolve the feature. 
* DataSense currently does not support RAML 1.0 types. When the customer uses RAML 1.0, the metadata is not passed and leveraged by DataSense. 

=== API Manager

Mule 3.8.0 depends on the Java Parser. API Manager relies on Mule 3.8.0 support for auto-generated proxies based on RAML 1.0. In most cases, the proxy generation feature works well on API Manager for RAML 1.0-defined APIs. However, if a user tries to auto-generate proxies based on a RAML file, and definition has known gaps, which are not covered by the java parser on API Manager, the deployed proxy will fail.

== Details on Known Validation Discrepancies among Products

API Designer supports RAML 1.0 based on the JavaScript parser, while Studio’s RAML editor and APIKit use the Java parser instead. Due to the java parser incomplete support in RAML 1.0,  users might see discrepancies among products.

The following sections describe known discrepancies in validation behavior.

=== A. Annotating scalar annotations 

The spec allows applying annotations to scalar nodes in addition to certain mapping nodes. If a user specifies the following:

----
baseUri:
  value: http://www.example.com/api
  (redirectable): true
----

* In current RAML spec: VALID
* In JS Parser (i.e. API Designer): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID 

=== B. uses in any fragment

The spec allows using uses in any fragment. The Java parser only allows its use in root level RAML documents and libraries.

----
#%RAML 1.0 ResourceType
# This file is located at files-resource.raml
uses:
  files: libraries/files.raml
get:
  is: files.drm
----

* In current RAML spec: VALID
* In JS Parser (i.e. API Designer): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID 

=== C. Null type 

RC2 introduced the null type. If a user specifies the following:

----
annotationTypes:
  deprecated: null
  testHarness: null | string
  badge: string? # equivalent to ‘null | string’
----

* In current RAML spec: VALID
* In JS Parser (i.e. API Designer): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID

=== D. Examples / Example 

RC2 loosened the syntax requirements for examples / example and replaced “content” with “value”. If a user specifies the following, 

----
types:
  Org:
    type: object
    properties:
      name: string
      address?: string
    examples:
      acme:
        name: Acme
      softwareCorp:
        value:
          name: Software Corp
          address: 35 Central Street

-----
example:
  height: 12
  width: 4

-----
example:
  (pii): true
  strict: false
  value:
    height: 12
    width: 4
----

* In current RAML spec RC2: VALID
* In JS Parser (i.e. API Designer, API Console): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID

=== E. Additional properties (pattern properties) 

RC2 changed the syntax from `[]` to `//` since that introduced conflicts with YAML. If a user specifies the following:

----
types:
  Person:
    properties:
      a: string
      [a]: number
----

* In current RAML spec RC2: INVALID
* In JS Parser (i.e. API Designer, API Console): INVALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): VALID

If a user specifies the following:

----
types:
  Person:
    properties:
      a: string
      //: number
----

* In current RAML spec RC2: VALID
* In JS Parser (i.e. API Designer, API Console): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID

=== F. Question Mark 

If a user specifies the following:

----
types:
  profile:
    properties:
      preference?:
        required: true
----

* In current RAML spec RC2: VALID
* In JS Parser (i.e. API Designer, API Console): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID

=== G. Inheritance of primitive values 

If a user specifies the following:

----
types:
  Number1:
   type: number
   minimum: 4
  Number2:
   type: number
   maximum: 10
  Number3: [ Number1, Number2]
----

* In current RAML spec RC2: VALID
* In JS Parser (i.e. API Designer, API Console): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID

=== H. Discriminator 

If a user specifies the following:

----
application/json: 
   type: Phone | Notebook
   discriminator: kind
----

* In current RAML spec RC2: INVALID
* In JS Parser (i.e. API Designer, API Console): INVALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): VALID

=== I. Type within Types

If a user specifies the following:

----
types:
  Next:
    type:
      properties:
        another: string
    properties:
      name: string
----

* In current RAML spec: VALID
* In JS Parser (i.e. API Designer, API Console): VALID
* In Java Parser (i.e. RAML editor in Studio, APIKit): INVALID

For the complete list of known features gap refer to the Java parser link:https://github.com/raml-org/raml-java-parser/blob/v2/MISSING.md[MISSING readme]. 



