= Redis Connector Release Notes
:keywords: cluster, redis, release notes, connector, object store

*November 2017*

_Select_

Redis is an open source advanced key-value store that is often referred to as a data structure server because the keys can contain strings, hashes, lists, sets. and sorted sets.

The Redis Connector offers complete support for its CRUD API.

== Redis connector 4.0.0 - November 18, 2017

=== Version 4.0.0 Compatibility

[width="100%", cols=",", options="header"]
|===
|Software |Version
|Mule Runtime | 3.6 and higher
|Redis server | 2.8.x, 3.0.x and 3.2.x
|===

=== Version 4.0.0 Features

. Moved connector to the Select category.
. Redis commands supported by this connector through its operations:
+
DEL EXPIRE GET HEXISTS HGET HKEYS HSET HSETNX KEYS LPOP LPUSH LPUSHX MULTI PSUBSCRIBE PUBLISH RPOP RPUSH RPUSHX SADD SET SETNX SPOP SRANDMEMBER ZADD ZRANGE
+
. Added entryTTL to connector's config. This is default time to live to be set on keys stored through connector or when connector is used as an object store.
. Removed defaultPartitionName from connector's configuration as it is not used any more.

=== Version 4.0.0 Fixed in this Release

No issues fixed as there are no known issues.

=== Version 4.0.0 Known Issues

No known issues.

=== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
