= REST Connect Release Notes
:keywords: rest, connect, release notes

*Nov 18, 2017*

*Guide:* link:/anypoint-exchange/ex2-rest-connect-faq[FAQ: REST Connect]

REST Connect quickly converts a RAML 1.0 API specification to a connector, which you can use in a Mule Application in the Design Center feature of Anypoint Platform.

== Version 1.2.0 - November 18, 2017

Version 1.2.0 supports the following security schemes defined in RAML v1.0:

 * OAuth2 - Authorization Code
 * Digest Authentication
 * Pass Through

== Version 1.1.0 - October 2, 2017

Version 1.1.0 supports creating Mule 3 connectors. When an API specification publishes to Exchange, REST Connect generates two connectors: one for Mule 4 and the other for Mule 3.

=== Version 1.1.0 - Fixes

REST Connect v1.1.0 now generates a connector properly whether a description is present or not. In REST Connect v1.0.0, if a description was not provided, REST Connector was unable to generate a connector properly.

== Version 1.0.0 - July 28, 2017

Version 1.0.0 provides the following features:

* Transforms a RAML 1.0 specification into a connector in Design Center.
* Supports for unauthorized requests, **basic authentication**, and **OAuth2 (Client Credentials)**.
* Support for query parameters, URI parameters and headers as input attributes.
* Support for metadata defined as RAML datatypes, XML schemas or JSON schemas.
* Inference of operation names given their parameters.
 
=== Version 1.0.0 - Known issues

* A RAML with the following type definition is not supported:
+
[source,xml,linenums]
----
types:
  RecursiveType:
    type: object
    properties:
      aString:
        type: RecursiveType
        description: This modifies the reference and causes a stack overflow error.
----
+
* No support for connectivity testing in the configuration for Design Center.
* REST Connect doesn’t generate friendly names for input attributes.
* Connector for Mule 3.x is not supported.
* Custom SSL certificates are not supported.

== See Also

* link:/anypoint-exchange/[Anypoint Exchange Documentation]
