= RosettaNet Connector Release Notes
:keywords: release notes, RosettaNet, b2b, connector

The Anypoint Connector for RosettaNet sends and receives RosettaNet messages 
using RNIF 2.00.01. The connector automatically handles send timeouts and retries, 
and responds to received messages with the appropriate HTTP response and/or
signal. Users work directly with the RosettaNet message service content as an XML document.

link:/mule-user-guide/v/3.8/rosettanet-connector[RosettaNet Connector]

== Version 1.0.0 - March 31, 2017

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |3.7.0
|Java | 7
|===

=== Features

* *Receive action message* - The connector acts as the source for flows processing received action messages matching the PIP configuration.
* *Receive failure notification message* - The connector acts as the source for flows processing received failure notification messages (PIP 0A1).
* *Receive signal message* - The connector acts as the source for flows processing received acknowledgment or exception signals, or send failures (after retries exceeded).
* *Set metadata for received action* - The connector adds metadata for a received action message matching the PIP configuration, simplifying DataWeave usage.
* *Set metadata for received failure* - The connector adds metadata for a received failure notification message, simplifying DataWeave usage.
* *Set metadata for receive signal* - The connector adds metadata supplied by acknowledgment or exception signals, or by send failures, simplifying DataWeave usage.
* *Send action message* - The connector sends action messages matching the PIP configuration.
* *Send failure message* - The connector sends failure notification messages (PIP 0A1).


=== 1.0.0 Fixed in this Release

None.

=== 1.0.0 Known Issues

Only supports:

* HTTP transport binding
* Asynchronous response messages
* RNIF 2.00.01
* Cluster 3 PIPs (limited selection)

No support for:

* Message encryption
* Certificate revocation (directly managed by used in keystore)

=== Support Resources

* Learn how to link:/mule-user-guide/v/3.8/installing-connectors[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s MuleForge link:https://forums.mulesoft.com/[Forum] to pose questions and get help from Mule’s broad community of users.
