:keywords: arm, runtime manager, release notes

= Anypoint Runtime Manager Release Notes


== Version 1.5 (to release on July 30th)

This release includes the following new features:

* Dashboards for applications and servers on-premises
* Insights for applications deployed on-premises
* Migration tool to automatically migrate deployments on – soon to be deprecated – Mule Management Console (MMC) to Runtime Manager

== Version 1.4.1

This release includes the following new features:

* link:/runtime-manager/alerts-on-runtime-manager[Alerts] for applications and servers on-premises
* Support for link:/mule-agent/v/1.4.0/installing-mule-agent#ports-and-ips-to-whitelist[static IP addresses]

See the full link:/release-notes/runtime-manager-1.4.1-release-notes[Anypoint Runtime Manager 1.4.1 Release Notes].


== Version 1.4.0

This release includes the following new features:

* link:/access-management/audit-logging[Audit Logging] for Runtime Manager Events
* Name change on homepage, the console formerly known as CloudHub is now known as Runtime Manager.

+
[NOTE]
The name CloudHub is from now on only used to reference the features of the Runtime Manager that involve deploying applications to cloud workers, VPC, and load balancing.

See the full link:/release-notes/runtime-manager-1.4.0-release-notes[Anypoint Runtime Manager 1.4.0 Release Notes].


== Version 1.3.1

This release includes the following new features:

* Enhancements to the handler for link:/runtime-manager/sending-data-from-arm-to-external-monitoring-software[sending data to Splunk]
* JMX handler enhancements

See the full link:/release-notes/anypoint-runtime-manager-1.3.1-release-notes[Anypoint Runtime Manager 1.3 Release Notes].


== Version 1.3.0

This release includes the following new features:

* Usability Enhancements for link:/runtime-manager/managing-servers#create-a-cluster[Clustering]
* RDBMS support (Beta)


See the full link:/release-notes/anypoint-runtime-manager-1.3-release-notes[Anypoint Runtime Manager 1.3 Release Notes].


== Version 1.2.0

This release includes the following new features:

* link:/runtime-manager/sending-data-from-arm-to-external-monitoring-software[Agent Plugins Integration] for Splunk and generic Logs

* API Gateway runtime Integration


See the full link:/release-notes/runtime-manager-1.2.0-release-notes[Anypoint Runtime Manager 1.2.0 Release Notes].
