= Runtime Manager 2.2.0 Release Notes
:keywords: arm, runtime manager, release notes

The Anypoint Runtime Manager V2.2.0, is scheduled for release on April 8th.

This release includes new functionality for monitoring flows.

== Hardware and Software Requirements

No change.

== Compatibility

Agent plugins integration is compatible with the following runtime versions:

[cols="2*a"]
|===
|Mule | 3.6.x and above.
|Availability | Cloud only.
|API GateWay | 2.x and above for API Analytics
|Runtime Manager Agent | link:/release-notes/runtime-manager-agent-1.5.0-release-notes[1.5.0 and above] for Insight and link:/release-notes/runtime-manager-agent-1.6.0-release-notes[1.6.0 and above] for link:/runtime-manager/flow-management[Flow Management] and link:/runtime-manager/monitoring-dashboards[all metrics charts]
|===


== Features and Functionality

This release introduces the following capabilities:

* Flow Monitoring: Users now have the ability to monitor key metrics in each Mule flow over time with the help of monitoring charts for flow metrics. This release includes metrics for:
** Mule messages
** Errors
** Response time

[NOTE]
Flow Monitoring is only available for integration applications deployed On-Premises, but management occurs through a cloud console.


== Deprecated Features or Functionality

None.
