= Runtime Manager Agent 1.9.1 Release Notes
:keywords: mule, agent, release notes

*November 10, 2017*

Download Runtime Manager Agent, version 1.9.1 at the following URL:

<insert URL>

== Compatibility

[%header,cols="2*a",width=70%]
|===
|Software|Version
|Mule Runtime|3.6.x, 3.7.x, 3.8.x, 3.9.x
|API Gateway|2.x and above
|Runtime Manager | V2.0
|===


== Hardware and Software Requirements

No change.

== Improvements and Fixed Issues

- For servers experiencing issues with long disconnects, moved the Keep Alive condition to runtime boot instead of application startup.
- Fixed issue where application properties managed in Runtime Manager did not default to the correct values.
- Changed log level from debug to info when JMX is not found.
- Fixed issue where Memory Server Metrics were not being collected correctly when configuring a different garbage collector in the `wrapper.conf` file.
- Fixed issue with `FileNotFoundException` after installing the RUagent with -I flag.
- [SE-6934] Fixed issue where global flags were not being considered when they were not set for `trackedApplication`.
- [SE-6307] Fixed issue where the Runtime Manager Agent failed to work on the IBM JDK.

== Known Issues

None

== See Also

* link:/runtime-manager/runtime-manager-agent[Runtime Manager Agent]
* link:/runtime-manager/installing-and-configuring-runtime-manager-agent[Installing and configuring Runtime Manager Agent]
* link:/runtime-manager/installing-and-configuring-runtime-manager-agent#updating-a-previous-installation[Updating the Runtime Manager Agent]


