:keywords: arm, runtime manager, release notes

= Anypoint Runtime Manager Release Notes

[NOTE]

The releases listed in this page correspond to changes that involve the hybrid modality of Runtime Manager, which handles deployments on-premises but manages and monitors them through MuleSoft's cloud based platform.

== Version 2.0 - November 19, 2016

This release is scheduled for November 19th and contains the following new features:

* link:/runtime-manager/insight[Insight] for Hybrid Users.
* Flow Management
* Monitoring V2.0

See the full link:/release-notes/runtime-manager-2.0-release-notes[Runtime Manager 2.0 Release Notes].

== Version 1.5.1 - August 27, 2016

This release includes a few minor enhancements.


See the full link:/release-notes/runtime-manager-1.5.1-release-notes[Anypoint Runtime Manager 1.5.1 Release Notes].

== Version 1.5 - July 21, 2016

This release includes the following new features:

* link:/runtime-manager/monitoring-dashboards[Dashboards] for applications and servers on-premises, and new link:/runtime-manager/alerts-on-runtime-manager[alerts] linked to the metrics these display
* link:/runtime-manager/insight[Insights] for applications deployed on-premises
* Migration tool to automatically migrate deployments on – soon to be deprecated – Mule Management Console (MMC) to Runtime Manager

See the full link:/release-notes/runtime-manager-1.5.0-release-notes[Anypoint Runtime Manager 1.5.0 Release Notes].

== Version 1.4.1 - May 6, 2016

This release includes the following new features:

* link:/runtime-manager/alerts-on-runtime-manager[Alerts] for applications and servers on-premises
* Support for link:/runtime-manager/installing-and-configuring-mule-agent#ports-ips-and-hostnames-to-whitelist[static IP addresses]

See the full link:/release-notes/runtime-manager-1.4.1-release-notes[Anypoint Runtime Manager 1.4.1 Release Notes].


== Version 1.4.0 - April 23, 2016

This release includes the following new features:

* link:/access-management/audit-logging[Audit Logging] for Runtime Manager Events
* Name change on homepage, the console formerly known as CloudHub is now known as Runtime Manager.

+
[NOTE]
The name CloudHub is from now on only used to reference the features of the Runtime Manager that involve deploying applications to cloud workers, VPC, and load balancing.

See the full link:/release-notes/runtime-manager-1.4.0-release-notes[Anypoint Runtime Manager 1.4.0 Release Notes].


== Version 1.3.1

This release includes the following new features:

* Enhancements to the handler for link:/runtime-manager/sending-data-from-arm-to-external-analytics-software[sending data to Splunk]
* JMX handler enhancements

See the full link:/release-notes/anypoint-runtime-manager-1.3.1-release-notes[Anypoint Runtime Manager 1.3.1 Release Notes].


== Version 1.3.0

This release includes the following new features:

* Usability Enhancements for link:/runtime-manager/managing-servers#create-a-cluster[Clustering]
* RDBMS support (Beta)


See the full link:/release-notes/anypoint-runtime-manager-1.3-release-notes[Anypoint Runtime Manager 1.3 Release Notes].


== Version 1.2.0

This release includes the following new features:

* link:/runtime-manager/sending-data-from-arm-to-external-analytics-software[Agent Plugins Integration] for Splunk and generic Logs

* API Gateway runtime Integration


See the full link:/release-notes/runtime-manager-1.2.0-release-notes[Anypoint Runtime Manager 1.2.0 Release Notes].
