= Runtime Manager Agent 1.9.4 Release Notes

_March 2, 2018_

This document describes new features and enhancements, known limitations, issues, and fixes in Anypoint Runtime Manager Agengt, version 1.9.4.

== New Features and Enhancements

* Added a script to analyze networking status.
+
The 1.9.4 release introduces a new script that enables network debugging. The script is available for UNIX and Windows and is available at the following location:
+
link:https://github.com/mulesoft/mule-agent-plugin/tree/develop-mule-4.x/scripts
+
For example, you can use the script to run a series of networking commands every 10 seconds to all PROD and PROD-EU relevant endpoints checking the connectivity.
+
----
./networking.sh -f ../logs/mule-agent.log -t "Failed attempt to connect" -s 10s
----
+
This example also checks the `mule-agent.log` file and searches for disconnections, including MCM and log any occurrence. The script can continue to run on a client for an extended time to check and parse the activity in order to discover networking behaviors.

* Added log entries for web socket disconnections to help understand the root cause of server disconnections.

* Reduced logging verbosity of the Runtime Manager Agent to avoid unnecessary log noise

== Changes in This Release

This release contains no changes to existing functionality.

== Fixed Issues

There are no fixed issues in this release.

== Known Limitations and Workarounds

There are no known limitations or workarounds in this release.

== Upgrade Requirements

There are no upgrade requirements for this release.

== Compatibility Notes

There are no compatibility notes for this release.