= Salesforce Composite Connector Release Notes
:keywords: release notes, salesforce, composite, connector


The Anypoint(TM) Connector for Salesforce Composite provides you a way to integrate with Salesforce Composite API link:https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite.htm[Salesforce Composite API]. The connector exposes convenient methods for preparing sub-requests, execute them in one batch and parse the results. It provides DataSense on both preparation of sub-requests and parsing response of their execution.

== Contents

.xref:sco-connector-1.0.0[Salesforce Composite Connector 1.0.0 - March 10, 2016]
* xref:sco-connector-1.0.0-compatibility[Version 1.0.0 Compatibility]
* xref:sco-connector-1.0.0-features[Version 1.0.0 Features]
* xref:sco-connector-1.0.0-fixes[Version 1.0.0 Fixes]
* xref:sco-connector-1.0.0-known-issues[Version 1.0.0 Known Issues]

[[sco-connector-1.0.0]]
== Version 1.0.0 - March 10, 2016

Release Notes for version 1.0.0 of the Salesforce Composite connector. These Release Notes accompany the
link:/mule-user-guide/v/3.8/salesforce-composite-connector[Salesforce Composite Connector User Guide].

[[sco-connector-1.0.0-compatibility]]
=== Version 1.0.0 Compatibility

The Salesforce Composite connector is compatible with:

[%header,frame=topbot,width=80%]
|======================
|Application/Service |Version
|Mule Runtime | 3.5.0 and higher
|Salesforce Rest API | v36.0
|======================

[[sco-connector-1.0.0-features]]
=== Features
1. Prepare sub-request for "Create" new SObject.
* The purpose of this method is to provide metadata for create operation based on the object that is going to be created and generates the sub-request.
2. Prepare sub-request for "Update" existing SObject.
* The purpose of this method is to provide metadata for update operation based on the object that is going to be updated and generates the sub-request.
3. Prepare sub-request for "Delete" existing SObject.
* The purpose of this method is to provide metadata for delete operation based on object that is going to be deleted and generates the sub-request.
4. Prepare sub-request for "Retrieve" existing SObject.
* The purpose of this method is to provide metadata for delete operation based on object that is going to be deleted and generates the sub-request.
5. Prepare sub-request for "GetLimits".
* The purpose of this method is to provide metadata for getLimits operation and generates the sub-request.
6. Prepare sub-request for "Query" existing SObjects.
* The purpose of this method is to provide metadata for query operation based on the object that is going to be queried and generates the sub-request.
7. Prepare sub-request for "QueryAll" existing SObjects.
* The purpose of this method is to provide metadata for query operation based on object that is going to be queried and generates the sub-request.
8. Prepare sub-request for "Search" into existing SObjects.
* The purpose of this method is to provide the user a way to input a SOSL String and generates the sub-request.
9. Execute a list of sub-requests in one API call.
* The purpose of this method is to send all the sub-requests in one batch for execution to server.
10. Parse sub-request result for "Create".
* The purpose of this method is to provide metadata for the result of the create operation.
11. Parse sub-request result for "Update".
* The purpose of this method is to provide metadata for the result of the update operation.
12. Parse sub-request result for "Delete".
* The purpose of this method is to provide metadata for the result of the delete operation.
13. Parse sub-request result for "Retrieve".
* The purpose of this method is to provide metadata for the result of the retrieve operation.
14. Parse sub-request result for "GetLimits".
* The purpose of this method is to provide metadata for the result of the getLimits operation.
15. Parse sub-request result for "Query".
* The purpose of this method is to provide metadata for the result of the query operation.
16. Parse sub-request result for "QueryAll".
* The purpose of this method is to provide metadata for the result of the queryAll operation.
17. Parse sub-request result for "Search".
* The purpose of this method is to provide metadata for the result of the search operation.
18. Create SObject Trees
* The purpose of this method is to send a list of SObject trees to Salesforce to be created.

[[sco-connector-1.0.0-fixes]]
=== Version 1.0.0 Fixed in this Release
None.

[[sco-connector-1.0.0-known-issues]]
=== Version 1.0.0 Known Issues
* Support for TLS1.0 is discontinued in Salesforce.
* If by default the application tries to use TLS1.0, then, when running it, the following VM argument should be added: -Dhttp.protocols=TLSv1.1,TLSv1.2
This will ensure the fact that TLS1.1 or TLS1.2 will be used for the communication with Salesforce.
