= Twilio Connector Release Notes

*January 2018*

_Select_

Twilio is an API cloud provider for voice and SMS communications for customers who want to use phone services as marketing leverage. The Mule Twilio Connector allows users to interact with the Twilio API within the Mule Runtime.

== 2.0.0

*January, 2018*

This version provides support for Mule 4.

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime |4.0
|Twilio REST API |2010-04-01
|===

=== Migrating from Older Versions

This version of the connector is not compatible with v1.0.0. To migrate your applications using the older version, remove all your current Twilio endpoints and replace them with ones from the latest version.

=== Features

The following operations are supported:

* Messages

** Delete Media
** Delete Message
** Get Media
** Get Media List
** Get Message
** Get Message List
** Redact Message
** Send Message

=== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
