= Anypoint Platform Upgrade to Latest Software Guide

Anypoint Platform provides three steps to upgrade your APIs to the latest Anypoint Platform software:

. Group your APIs together.
. Request your data migration upgrade.
. After the upgrade, move assets to each of your environments as needed.

== To Group Assets

Grouping APIs enables you to collect multiple APIs into a single API to simplify
upgrading. This also gives you an opportunity to remove APIs with low use or ones 
no longer needed. This is also important if your APIs list an environment in the API name -- after upgrading, there are new environments. 

In Anypoint Platform > API Manager, to the right of each API you should see a message that reads:

* Prepare To Group - You can add the asset to a new or existing group.
* Grouped - The asset is now part of an asset group. You can click Edit to change the New API Name, New API Version, or to include or exclude your portal.

If neither Group name is present, contact MuleSoft for the correct entitlement.

To group assets:

. Log into Anypoint Platform and locate API Manager.
. In API Manager, for each asset, click Prepare To Group. In the Group an API screen, API Manager lists the Current API Name and Current API Version.
. Specify a New API Name. This can be any string of ASCII characters.
. Specify a New API Version Name. This can be any string of ASCII characters.
. Optional. If you have a private or public portal for the API, you can 
upgrade the portal as well. A private portal becomes an asset in your
organization's private Exchange. A public portal becomes an asset in your
organization's Public Portal in Exchange.

Notes: 

* If you use Business Groups instead of environments to group your APIs, API grouping is not needed or recommended.
* After you group one or more APIs to an API group (New API Name in the API Grouping screen), you can't ungroup the APIs. However you can change the group for each API individually to direct it to a differnt API group.

== To Request Your Data Migration Upgrade

This step is fully automated. This takes place during the timeslot that you sign up for with your MuleSoft representative. The estimated time is 15 min for each 50-100 APIs.

During this stage, APIs and portals are moved into their appropriate new home. RAMLs and OAS specifications are stored in Anypoint Exchange, and new projects are created for them in Anypoint Design Center. SOAP APIs or APIs without specifications are moved to Exchange only and not added to Design Center. Portals for all APIs, whether internal or external are created during this stage.  

After this process completes, those in your organization administrator role  receive an email with a status report for each API. 

Reviewing these emails are critical as there may be errors to resolve. You can contact MuleSoft Customer Support with any questions on resolving these errors. 

== To Classify APIs by Environments

After the data migration, all APIs are listed in the unclassified environment. From here, you can classify APIs into their appropriate environment 

Note: The names of APIs you see in the unclassified environment reflect the original API names you had prior to grouping your APIs. This is so that you can easily determine the environment for each API. 

== To Classify Your APIs After Migration

. Update the server where the API or API proxy is running.
. Classify the API into the suggested environment.

The sections that follow help you classify your APIs depending on how you deployed proxies before migration.

=== API Managed by Proxy Deployed Through API Manager

If your API was deployed in Runtime Manager:

. From API Manager, click an API. 
. Click Configure Endpoint > Redeploy Proxy.
. Speciy a runtime version.
. Click Redeploy Proxy.

If your API was deploy in an on-premises standalone runtime:

. From API Manager, click an API. 
. Click Configure Endpoint > Redeploy Proxy.
. Speciy a runtime version for Mule Agent 1.9 and later.
. Click Redeploy Proxy.

To update an existing server:

. Use SSH to access the standalone runtime server.
. Download the Runtime Agent 1.9 or later.
. Update the Gateway runtime agent.
. Restart tehe Gateway.

=== Managed By Basic Endpoint Or Proxy Deployed Through Runtime Manager

If your API was deployed in Runtime Manager:

. Go to Access Manager.
. Click Environments.
. Click the environment name you want to use.
. Copy the Client ID and Client Secret.

To update an application in Runtime Manager:

. Go to the proxy application in Runtime Manager.
. Click Settings.
. Click Properties.
. Change the values of the following properties to the values from the Environment:
** Anypoint.platform.client_id
** Anypoint.platform.client_secret
. Click Apply changes.

To update an application deployed in standalone Mule Runtime:

. Use SSH to access the standalone runtime server where the application is deployed.
. Download Runtime Agent 1.9.x.
. Update the Runtime Agent.
. Restart the Mule Runtime.

=== Other Deployments

This section explains the manual steps needed to prepare Mule Runtime to use API environments without updating the agent or registering the server with Runtime Manager.

Getting the environment client ID and secret:

. Go to Access Manager.
. Click  Environments.
. Click the environment name that you want to use.
. Copy the Client ID and Client Secret.


Updating an application in Runtime Manager:

. Go to the proxy application in Runtime Manager.
. Click Settings.
. Click Properties.
. Change the values of the following properties to the values from the environment:
** anypoint.platform.client_id
** anypoint.platform.client_secret


Updating standalone runtimes:

. Use SSH to access the runtime server that you want to update.
. Edit the `<mule_home>/<conf>/wrapper.conf` file.
. Change the values of the following properties to the values from the environment:
** anypoint.platform.client_id
** anypoint.platform.client_secret
. Restart Mule Runtime.

== FAQ

*Is there any downtime?*

There is no downtime grouping and migrating APIs. Classifying APIs may cause downtime when restarting a proxy. However, do not use API Manager during the upgrade process to prevent any data inconsistency.

*Who should customers contact for questions during the process?*

Open a case in the support portal. See the See Also section of this document for
Support information.

*After the upgrade, how does API usability change?*

After the upgrade is complete, existing APIs stored in API Manager move as follows:

[%header,cols="25a,25a,50a"]
|===
|Before the Upgrade |Afterwards |Description
|API Manager: +
API Specifications |Design Center
|All RAML files from API Manager automatically appear as an API Specification Project within Design Center. This project is visible to everyone within a business group.
|API Portals |Anypoint Exchange
|API Portals are available for access through Anypoint Exchange, instead of API Manager. 
|API Proxies |API Manager
|APIs stored in the API Manager move to the Unclassified Environment. API providers need to classify each API to the appropriate environment. 
|===

*Can I bulk classify APIs into a specific environment?*

No. 


*What is the Unclassified Environment?*

After the migration completes, all APIs appear in the Unclassified Environment. This environment is a virtual environment from where all APIs that haven’t been classified into a real environment can be managed. This environment has the same user interface and permissions model as the pre-upgrade API Manager.

All APIs in the unclassified environment can be classified into a real environment by following the process described in this document. If API grouping information was provided before the migration, that information is used as the API name and version of the API being classified in the target environment.

== New and Changed Features

What’s new:

* All APIs created using existing API Manager appear in the Unclassified Environment after the upgrade.
* APIs in the Unclassified environment can be classified into the corresponding environment following this process.
* Autodiscovery element for new APIs after the upgrade should be configured in the following way (all values can be gotten from the API and the UI):
** `name=”groupId:{{groupId}}:assetId:{{assetId}}”`
** `version=”{{version}}:{{instanceId}}”`
* A new version of API Manager API (v3.x) is available to leverage all new API Manager capabilities. 
* User’s permissions model has changed to be action-based at the environment level, which is aligned to the rest of the management center. After the upgrade, administrators should set environment-level permissions to all users. Default environment-level admin roles are available. The permission model in the unclassified environment works in the same way as API Manager permission model worked before migration. Assigned permissions for APIs in the unclassified environment also remained untouched during the upgrade process.

=== API Designer

* To make changes to a RAML of a running or published API, users need to republish any specifications in Exchange that have versions. 
* Design Center projects do not have tags like old API Manager projects.
* API sync from Studio 6 and 7 only supports pull only. 

=== API Portals in Exchange

* External links from the navigation panel are grouped under the Helpful links section in Exchange.
* Existing portal URLs redirect to corresponding API Portals in a new Exchange.
* Invisible pages are deprecated and replaced with draft functionality of Exchange * All invisible pages become draft after the upgrade is complete.
* Branding at the API portal level is deprecated and replaced with global branding control. This means that all API portal pages inherit global styles.
* To update an API specification available in Exchange or used by an API proxy in API Manager, users need to publish a new version of API specification to Exchange using API designer. 
* Internal API consumers can see all API endpoints and versions through an API portal they have access to. Existing API Manager controls permissions per API version.
* Onboarding of external users of API Public Portals onboarding has been simplified and there’s no need to invite external users for them to be able to consume APIs and request API keys.
* When APIs are migrated to Exchange, Exchange calls REST Connect to generate connectors for Mule 4 and Mule 3. Because REST Connect only supports RAML v1.0, owners for API specifications based on RAML v0.8 receive an email notification with a message that the connector creation has failed. They can still use Design Center to open and edit these API specifications, but these specifications cannot be used as a connector in Design Center, Studio 6, and Studio 7.

=== APIs in API Manager Changes After the Upgrade

* APIs utilizing an autodiscovery ee uplement now use API Manager instead.
* API Manager API can be used with APIs in the unclassified environment with some restrictions (see below).
* Because the upgrading to the latest software is moving all portals and RAMLs cannot be used to modify, create, or delete them after the upgrade. After the upgrade, the API Manager API v2.x changes its behavior in the following way:
** The following resources related to managing RAMLs return 400. Use Design Center APIs instead.
+
[source,xml,linenums]
----
/organizations/{organizationId}/apis/{apiId}/versions/{apiVersionId}/addRootRaml
/organizations/{organizationId}/apis/{apiId}/versions/{apiVersionId}/files/*
----
+
** The following resources related to managing portals (including permission setting) return 400. Use Exchange APIs instead.
+
[source,xml,linenums]
----
/organizations/{organizationId}/apis/{apiId}/portals
/organizations/{organizationId}/apis/{apiId}/versions/{apiVersionId}/portal/*
/organizations/{organizationId}/portals/*
organizations/{organizationId}/public/*
----
+
** API creation needs to be done in Exchange first, thus creation of an API using API Manager API return 400.
* APIs exported before the upgrade cannot be imported after upgrade.

== Continuous Integration and Delivery

When working with large teams and multiple applications, the manual process for testing and deployment is difficult, for that reason you should use a continuous integration and deployment server like Jenkins.

To prepare the applications for this:

* Use a source code repository such as GitHub or BitBucket.
* Add the following configurations to each Maven pom.xml of each application
** Mule Maven plugin for CloudHub | ARM | Standalone deployment
** Mule Maven plugin for MUnit
* If using Jenkins pipeline, add the Jenkins files to the Mule project

=== Continuous Integration 

The need for continuous integration (CI) for a project is very important. By using Maven as your build tool, you can create a build that gets triggered on every project change, and run all its unit and functional tests automatically.
The advantages of CI are:

* Early notification of issues in the software development lifecycle.
* Ensures code gets fully tested before release.
* Successfully tested branches ensure better success when merging to the master branch.

=== Continuous Integration Objectives

. Listens for new commits to a project’s source code management system. The CI watches many branches for new commits. You can use either polling to find new commits, or the management system can trigger events that inform your program of commits.
. Pulls the newest branch into a centralized server.
. Creates build jobs on a centralized server.
. Runs configurable unit and integration tests on the code base that compile, test, package, and deploy the project in a sandbox to ensure the project works correctly.
. Stores artifacts in a repository.
. Displays the results of each build.
. Deploys passing builds to production.

=== To Deploy Mule Applications

* Import the API into API Manager. See Set Up an API in the See Also section of 
this document.
* Runtime Manager Agent for on-premise systems. For more information, 
view the See Also section of this document.

You can create functional tests with MUnit Unit Testing.

=== Mule Maven Plugin

The mule-maven-plugin supports deployments to:

* Anypoint Runtime Manager
* Mule Agent
* Local instances

== See Also

* https://docs.mulesoft.com/api-manager/tutorial-set-up-an-api[Set Up an API]
* https://docs.mulesoft.com/runtime-manager/runtime-manager-agent[Runtime Manager Agent]
* https://docs.mulesoft.com/munit/v/1.3/[MUnit]
* https://docs.mulesoft.com/mule-user-guide/v/3.9/mule-maven-plugin[Mule Maven Plugin]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
