= X12 and EDIFACT Modules Release Notes
:keywords: b2b, x12, edifact, release notes

MuleSoft maintains these EDI connector modules under the link:/mule-user-guide/v/3.8/anypoint-connectors#connector-categories[_Premium_] support policy.


== X12 1.2.2 - December 27, 2016
=== Version 1.2.2 - Compatibility

[%header,cols="50,50"]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

=== Version 1.2.2 - Fixed Issues

* Supports '\n' as a segmentTerminator.

== X12 and EDIFACT Modules 1.2.1 - September 28, 2016

=== Version 1.2.1 - Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

=== Version 1.2.1 - New Features

* Added support for inline components in ESL schema definitions.
* Added support for writing Data Weave-compatible types.
* Improved overlay handling, allowing segments to specify only modified components and change component type
* Support writing repeating composite.
* Add interchange information (with sender and receiver reversed) to X12 TA1 interchange acknowledgments generated by parsing.
* Support sending X12 messages with only TA1 interchange acknowledgments, no transaction data.

=== Version 1.2.1 - Fixed Issues

* Corrected some off-by-one errors in reporting data errors for both X12 and EDIFACT, and some segment off-by-one errors for EDIFACT.
* Changed loop/group keys in data, eliminating position numbers previously used at start of key.
* Corrected loop position tracking and reporting in X12 ACK3/IK3, ACK4/IK4 segments (997/999 functional acknowledgments).
* Correct check for data present when reading a composite to work correctly when first value of composite is empty.
* Abort parsing of EDIFACT message if the initial UNA/UNB cannot be read (since there's no way to know the delimiters being used for message).

== X12 and EDIFACT Modules 1.0.2 - March 9, 2016

=== Version 1.0.2 - Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

=== Version 1.0.2 - New Features

* Add more details to error logging.

=== Version 1.0.2 - Fixed Issues

* Changed identifiers for X12 loops with numeric values as names, using the number as part of the identifier (rather than the identifier of the first segment in the loop).
* Correct handling of X12 repeating group inside LS/LE wrapper.
* Fix issue causing X12 parser IllegalStateException "Illegal structure at position...".

== X12 and EDIFACT Modules 1.0.1 - November 10, 2015

=== Version 1.0.1 - Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===

=== Version 1.0.1 - New in This Release

This release contains the following fixes:

* Fixed dead lock when acquiring lock to increment control number
* Writing now correctly fails when writing invalid characters and repeating values outside defined limits
* New icons for the connector

For more information, such as how to install or use these modules, see
link:/anypoint-b2b[Anypoint B2B], link:/anypoint-b2b/edifact-module[EDIFACT Module], and link:/anypoint-b2b/x12-module[X12 Module].

=== Version 1.0.1 - Migration Guide

No application changes are needed from 1.0.0.


== Version 1.0.0 - Sept 21, 2015

=== Version 1.0.0 - Compatibility

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule 3.6.0 and newer
|===


=== Version 1.0.0 - New in This Release

This release contains many improvements, including:

* Support for reading/writing multiple versions of the same transaction type within a single message
* Additional EDIFACT message types d03A and d95B
* Improved structure usability with DataWeave and MEL by including "Loop" in the key name for loops and using underscores instead of spaces. You will need to update your integrations appropriately for this (see below).
* Improved validation logic on writing.
* Many bug fixes

For more information, such as how to install or use these modules, see
link:/anypoint-b2b/[Anypoint B2B], link:/anypoint-b2b/edifact-module[EDIFACT Module], and link:/anypoint-b2b/x12-module[X12 Module].

=== Version 1.0.0 - Migration Guide

All of your transformations and expressions that references parts of the EDI message structure must be updated for the following changes:

* The "Transactions" list has been changed to "TransactionSets" and now has an additional level for the version of the transactions.
** Example: payload.Transactions."850" now becomes payload.TransactionSets.v5010."850"
* All keys no longer have spaces - instead they have underscores
** Example: payload."0100 PO1" becomes payload."0100_PO1"
* Any segment that is a loop
** Example: payload.Detail."0100 PO1" becomes payload.Detail."0100_PO1_Loop"

== Known Issues

The following issues apply to all versions:

* X12 binary segments are not supported, are not included in schema definitions, and cause errors.
* EDIFACT packages (containers for binary data) are not supported, and cause errors if you attempt to use them.
* EDIFACT interactive exchanges (using UIB header segment and UIZ trailer segment) are not supported.
* Code values are not currently verified for either reading or writing.
* X12 syntax rules and EDIFACT dependency notes are not currently enforced for either reading or writing.
* EDIFACT groups are not supported.

