= Zuora Connector Release Notes
:keywords: release notes, zuora, connector

*Guide*: link:/mule-user-guide/v/3.8/zuora-connector[Zuora Connector]

[IMPORTANT]
Starting with v.3.0.0, the Zuora Connector is licensed commercially with Anypoint Platform as with other link:/mule-user-guide/v/3.8/anypoint-connectors#connector-categories[_Select_] connectors. Prior versions will remain freely available to the community.

== Version 3.1.0 - October 25, 2016

=== Version 3.1.0 Compatibility

The Zuora connector 3.1.0 is compatible with the following applications:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule Enterprise Edition 3.5.2 and later
|Zuora|v75
|===

=== Version 3.1.0 Features

* Added *Post Usage* processor that receives the location of a csv file and imports the usage data for one or more accounts fromn the
csv file to Zuora  link:https://knowledgecenter.zuora.com/DC_Developers/REST_API/B_REST_API_reference/Usage/1_POST_usage[Zuora Post Usage].
* Added *Check Import Status* processor that receives an import URL as input and returns the status of the input.
* Added Multi-Entity support for Multi-Entity API for the REST operations link:https://knowledgecenter.zuora.com/BB_Introducing_Z_Business/Multi-entity[Multi Entity API].
* Added connectTimeout and readTimeout fields in the connector configuration to increase the connection time and the time to wait for a response from the server.
* Added SocketTimeoutException, ConnectTimeoutException, SocketException and ConnectException to the list of exceptions that trigger a reconnection.
* Added  *Query* processor with support for both *DataSense Query Language* and *Native Query Language*.
* Added support for Aqua API link:https://knowledgecenter.zuora.com/DC_Developers/Aggregate_Query_API[Zuora Aqua API]. Besides the processors that
expose the Aqua API operations, to periodically check the status of a Aqua job and
retrieve its batches when it is complete, you can use the *Aqua post query* processor and *Aqua get batch results* source. For
more details on how to use these processors, please consult the connector guide link:/mule-user-guide/v/3.8/zuora-connector[Zuora Connector].


=== Version 3.1.0 Fixes

* Modified the XML parsing classes in order to defend against the XML External Entity attacks.

=== Version 3.1.0 Known Issues

* ConnectionTimeout and ReadTimeout fields will not affect the *Invoke Soap Service* operations.

== Version 3.0.1 - August 20, 2016

=== Version 3.0.1 Compatibility

The Zuora connector 3.0.1 is compatible with the following applications:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule Enterprise Edition 3.5.2 and later
|Zuora|v75
|===


=== Version 3.0.1 Fixes

* Fixed a compatibility issue between Zuora and other connectors.

=== Version 3.0.1 Known Issues

None.


== Zuora Connector 3.0.0 - July 21, 2016

=== Version 3.0.0 Compatibility

Zuora connector version 3.0.0 is compatible with:

[%header%autowidth.spread]
|===
|Application/Service|Version
|Mule Runtime|Mule Enterprise Edition 3.5.2 and later
|Zuora|v75
|===

=== Version 3.0.0 Features

* The connector is supported under the *Select* category
* The connector can support older versions of the Zuora SOAP API
(only version v75.0 was extensively tested)
* The connector needs a Zuora WSDL in order to call SOAP-based operations
* *Invoke SOAP Service* processor is used to call SOAP-based operations.



== Version 2.1.3 - September 07, 2015

=== Version 2.1.3 Compatibility

The Zuora connector 2.1.3 is compatible with the following applications:


[%header%autowidth.spread]
|===
| Application/Service |Version
|Mule Runtime	|3.5.0 or later
|Zuora API version	|68.0 |
|===

=== Version 2.1.3 Features

* Support for 68.0 API version

=== Version 2.1.3 Fixes

None.

=== Version 2.1.3 Known Issues

None.

== See Also

* Learn how to link:/mule-user-guide/v/3.8/installing-connectors[Install Anypoint Connectors] using Anypoint Exchange.
* Access MuleSoft’s link:http://forum.mulesoft.org/mulesoft[Forum] to pose questions and get help from Mule’s broad community of users.
* To access MuleSoft’s expert support team, http://www.mulesoft.com/mule-esb-subscription[subscribe] to Mule ESB Enterprise and log in to MuleSoft’s http://www.mulesoft.com/support-login[Customer Portal].
