= Object Store v2 FAQ
:imagesdir: ./_images

== Where is OSv2 available?

APAC: Tokyo (ap-northeast-1), Singapore (ap-southeast-1), and Sydney (ap-southeast-2).
EU: Frankfurt (eu-central-1), Ireland (eu-west-1), and London (eu-west-2).
North America: Central Canada (ca-central-1), Northern Virginia (us-east-1), and Oregon (us-west-2). 
South America: Sao Paulo (sa-east-1).

== Is OSv2 persistent in the same region as the worker?

Yes. For example, if you deploy to the Singapore region, the object store persists in the Singapore region.

== How long can data persist in OSv2?

30 days maximum. The default is 14 days.

== What's the maximum number of keys that can persist in OSv2?

In OSv2 there is no limit on the number of keys per application. In Object Store v1, the limit was 100,000 keys and attempts to store more were rejected.

== Where is the OSv2 REST API portal?

This API is available in the Anypoint Platform Developer's portal. See link below.

== Where is the Object Store connector?

You can use Anypoint Studio to download from Anypoint Exchange the Mule 3 Object Store connector or the Mule 4 Object Store connector. In Mule 4, OSv2 is a core connector that is pre-installed in Mule 4 and in Anypoint Studio 7. Note: The Mule 3 Object Store connector writes a key-value pair, whereas the Mule 4 Object Store connector writes a key-list pair.

== Do I need a different Object Store connector for Object Store v2 and Object Store v1?

The Mule 3 Object Store connector works for both OSv1 and OSv2. The Mule 4 Object Store connector only works with OSv2. See links below to each connector.

== Are there rate limits on OSv2?

Free accounts are rate limited to 10 transactions per second per application. Premium customers who purchase the Object Store SKU have no rate limits; however, the number of API requests premium customers can make is limited by their subscription value. If a free account application exceeds the rate limit, the 429 HTTP status code results.

== Can OSv2 be shared between workers?

No. One object store per application. Other applications cannot access the object store of another application. However you can use the REST API to read from one application and store to another.

== Can OSv2 be used on premises?

No, but applications running on-premises can use the OSv2 REST API to store data in OSv2 and retrieve it.

== How is OSv2 data secured?

Object Store v2 uses TLS for secure transport. Data at rest is stored using FIPS 140-2 compliant encryption standards.

== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform-eng/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/object-store-v2/[Anypoint Exchange Object Store v2].
* https://www.anypoint.mulesoft.com/exchange/org.mule.modules/mule-module-objectstore/[Mule 3 Object Store Connector].
* https://www.anypoint.mulesoft.com/exchange/org.mule.connectors/mule-objectstore-connector/[Mule 4 Object Store Connector]
* link:/object-store/[Object Store Documentation].
* https://forums.mulesoft.com[MuleSoft Forum].
* https://support.mulesoft.com[Contact MuleSoft Support].
