= Healthcare Toolkit
:keywords: hl7, healthcare, toolkit, hapi, mllp, er7
:license-info: Enterprise, CloudHub

The Mule Healthcare Toolkit is a collection of features that facilitates integration with healthcare systems by providing the tools needed to easily create, read, and transform HL7 messages within Mule.

This document assumes a working knowledge of Mule Runtime and Anypoint Studio. 

== Overview

Health Level Seven International is a standards development organization that defines a set of standards for the transport and communication of healthcare information. 

The version of the MuleSoft HL7 connector is different from the HL7 version numbering. The HL7 connector supports HL7 software versions v2.1, v2.2, v2.3.1, v2.3, v2.4, v2.5, v2.5.1, v2.6, 2.7, 2.7.1, 2.8, and 2.8.1. 


The Mule Healthcare toolkit allows you to send and receive HL7 messages in ER7 format over MLLP and other transport protocols and corresponding connectors supported by Mule, such as HTTP. Minimal Lower Layer Protocol (MLLP) uses the HL7 MLLP connector.

This page describes the functionality included in the MuleSoft Healthcare toolkit, and provides installation instructions.

== Toolkit Contents

The Mule Healthcare Toolkit includes the following elements.

[%header,cols="20s,80a"]
|===
|Type |Description
|Connector |link:/healthcare-toolkit/v/3.1/hl7-edi[HL7 EDI] - Electronic Data Interchange (EDI) schemas, configuration, and operations.
|API Documentation |https://mulesoft.github.io/mule-hl7-connector/[HL7 Technical Reference]
|Connector |link:/healthcare-toolkit/v/3.1/mllp-connector[HL7 MLLP Reference] - Minimal Lower Layer Protocol (MLLP)
|Testing |link:/healthcare-toolkit/v/3.1/connector-testpanel[Connector Testing with TestPanel]
|Release Notes |link:/release-notes/hl7-connector-release-notes[HL7 EDI Connector Release Notes], link:/release-notes/hl7-mllp-connector-release-notes[HL7 MLLP Connector Release Notes]
|===


== Installing the Mule Healthcare Toolkit

The Mule Healthcare Toolkit is available for free on a trial basis. Contact mailto:info@mulesoft.com[MuleSoft Sales Inquiries] to request a license to use the Healthcare Toolkit components in a production environment.

. In Anypoint Studio, click the Exchange icon in the Studio taskbar.
. Click Login in Anypoint Exchange.
. Search for HL7 and click Install.
. Follow the prompts to install the connector.
. Repeat steps 3 and 4 to install the HL7 MLLP Connector too.


== See Also

* https://mulesoft.github.io/mule-hl7-connector/[HL7 Technical Reference]
* http://www.hl7.org[Health Level Seven International]
* Use the link:/healthcare-toolkit/v/3.1/connector-testpanel[Connector Testing with TestPanel] to test your HL7 connector application.
* link:/healthcare-toolkit/v/3.1/mllp-connector[HL7 MLLP Reference]
* mailto:info@mulesoft.com[MuleSoft Sales Inquiries]

