= Workflow: Creating API Specifications with the Visual Editor

API Designer includes visual-editing capabilities for creating APIs in RAML. You define RESTful endpoints by populating forms with values for RAML components.

== Before you begin
Within Anypoint Platform, you must be assigned a role that has the _Design Center Developer_ permission.

== About this workflow

The visual editor supports the following subset of RAML components:

* Root properties
* Data types (payloads)
* Resources and methods
* Headers
* Query parameters and query strings
* Request body
* HTTP and HTTPS protocols
* Responses and status codes, including associated headers and body

As you fill in the forms, API Designer generates the API specification.
You can then publish to Exchange and test the design.

If at any time you want to edit the specification directly (for example, to add RAML components that the visual editor does not support), click *Edit RAML* to switch to the RAML editor. After you switch, however, you cannot switch back to the visual editor to continue editing the API specification.

// Mention the auto-mapper
