= Workflow: Creating and Publishing API Specifications with the RAML Editor

You can start a new file or you can import an existing file.

== Procedure
. Create a project from the *Projects* page in the Design Center by clicking *Create* and selecting *API Specification*.
. In the New API Specification dialog, name your project and select *Start with API Designer* to use the RAML editor.
+
*Result:*
+
The RAML editor opens. The editor is divided into three panels:
+
* The list of files in your project. By default, the editor creates a .raml file that has the same name as the project.
* The editor. Appearing in the editor are the first two lines of the default .raml file.
. If you want to start from an existing RAML or OAS file, import that file.
// Question: If you want to start from an existing file, do you delete the default .raml file after importing the existing file?
. Draft your API specification.
+
If you want to simulate calls to your API, use the mocking service.
+
At any time, you can export your specification. You can export an API for use in another tool, or to store the API outside Anypoint Platform. For example, you can export an API from Design Center and work on the file using API Workbench on a local computer. The file must contain a RAML 1.0 (only) API specification. You can import the zip file back into Design Center or Studio. You can also export the specification, subject to some limitations, to an OAS file in JSON or YAML format.

== What to do next
Publish your API specification on Exchange.

== See also
