= Create an API Specification with the RAML Editor

You can start a new file or you can import an existing file...


== Before you begin
Within Anypoint Platform, you must be assigned a role that has the _Design Center Developer_ permission.
// What guidance can I give for designing an API specification before using the API Designer?

== Procedure
. Create a project from the *Projects* page in the Design Center by clicking *Create* and selecting *API Specification*.
. In the *New API Specification* dialog, name your project and select the option *Start with API Designer* to use the RAML editor.
+
_Result:_ The RAML editor opens. The editor is divided into three panels:
+
* The left panel lists thefiles in your project. By default, the editor creates a `.raml` file that has the same name as the project.
+
[TIP]
====

You can create more than one API specification in a single project. If you want to include additional API specifications in your project, click the plus sign in the Files panel to create a new file or click the dots that are next to the plus sign to import a file.


====
* The central panel displays the editor in which you create an API specification. Select a file in the left panel to work on it in the editor. Appearing in the editor when you create a project or start a new API specification are the first two lines of a valid `.raml` file.
* The right panel lists the types and resources that are in the API specification that is in the editor.
+

. If you want to start from an existing RAML or OAS file, import that file.
.. At the top of the left panel, click the three dots and select *Import*.
.. In the *Import* dialog, select one of the following options:
+
* If you are importing a `.raml` file, select *File or ZIP* or *URL*, depending on the import method that you want to use.
* If you are importing an OAS file, select *OAS file or ZIP* or *OAS URL*, depending on the import method that you want to use.
// Question: If you want to start from an existing file, do you delete the default `.raml` file after importing the existing file?

+
_Result:_ The imported file appears in the list of files for your project.
. Draft your API specification.
+
Simulate calls to your API:: Turn on the mocking service to ... For more information, view the topic "Simulate Calls to an API", which is listed in the *See Also* section at the end of this topic.
Export your API specification:: At any time, you can export your specification. You can export an API for use in another tool, or to store the API outside Anypoint Platform. For example, you can export an API from Design Center and work on the file using API Workbench on a local computer. The file must contain a RAML 1.0 (only) API specification. You can import the zip file back into Design Center or Studio. You can also export the specification, subject to some limitations, to an OAS file in JSON or YAML format.

== What to do next
Publish your API specification on Exchange. For the steps, view the topic "Publish an API Specification on Exchange", which is listed in the *See Also* section at the end of this topic.

== See also
* link:/design-center/design-mocking-service[Simulate Calls to an API]
* link:/design-center/design-publish-to-exchange[Publish an API Specification on Exchange]
