= To Backup and Restore Anypoint Private Cloud
:keywords:on-prem, Anypoint Platform Private Cloud Edition, anypoint platform, on prem, on premise, on premises, backup, disaster recovery

== To Create a Backup

To preserve your data in case of system failure, you must ensure that you system is automatically backed up. You should configure your backup to run at least once per day, although MuleSoft recommends that you back up your system hourly.

Your backup archive must be stored on external storage outside the Anypoint cluster.

You can trigger backups from any of the nodes of your installation.

To create a backup, run the following command on any node in the cluster.

----
gravity backup /var/lib/gravity/planet/share/backup.tar.gz
----

This command creates an archive of the current system state in: `/var/lib/gravity/planet/share/backup.tar.gz`.

== To Perform a System Restore

To restore a system from your backup, use the existing cluster or create a new cluster containing the same number of servers as the cluster being restored.

[WARNING]
You can not perform a backup between different versions of Anypoint Platform Private Cloud Edition. The new installation you create must be using the same version of Anypoint Platform Private Cloud Edition as your backup. 

. Log in to one of the nodes in your cluster.

. Move the compressed backup archive file to a folder in any of the nodes of the to-restore environment. You can transfer this file securely via the following command:
+
----
scp /backup-path/to-restore.tar.gz your_username@remotehost.edu:/var/lib/gravity/planet/share
----

. Restore the cluster from the backup archive:
+
----
sudo gravity restore /var/lib/gravity/planet/share/to-restore.tar.gz
----

This will take a few minutes.

== See Also

* link:install-workflow[Workflow: Install Anypoint Platform Private Cloud Edition]
* link:upgrade[To Migrate to Anypoint Platform Private Cloud Edition, Version 1.7.x]
