= To Create Anypoint Private Cloud Resources on Amazon Web Services (AWS)

. Download the Anypoint Platform Private Cloud Edition terraform script from the following URL:
+
----
URL TBD
----

. Extract the downloaded archive.
+
**Need to know the folder name**

. Download the Terraform binary and place it in the **Need PCE Terraform Folder Name**
. Set the following environment variables on your system:
+
* **Environment vars**
+
These environment variables define the credentials and URL required for Terraform to connect to your AWS environment.

. From the **Need PCE Terraform Folder Name** run the following command:
+
----
make create-cluster
----
+
This script outputs the terraform plan that outlines all of the resources that are created.

. Confirm the terraform plan.
+
After confirmation, Terraform creates the required resources within your AWS account.

. Login to the AWS console to determine the IP address of the bastion.
+
You must use this IP address to connect to the bastion to install Anypoint Platform Private Cloud Edition.


