= Workflow: Install and Verify Prerequisites for Anypoint Private Cloud

This topic describes the workflow for verifying that your system is ready to install Anypoint Platform Private Cloud Edition.

. Contact your customer success representative to obtain a product license.

. link:/anypoint-private-cloud/v/1.7/prereq-hardware[About Hardware Requirements for Anypoint Private Cloud]
+
Review the minimum hardware requirements for Anypoint Platform Private Cloud Edition.
+
[WARNING] 
If your system does not meet all of the minimum system requirements, you cannot install Anypoint Platform Private Cloud Edition.

. .
+
Although the installation wizard enables you to install the platform without using Docker or Kubernetes, it is important to be familiar with how these work for managing and troubleshooting the platform.

. (Optional) Create a Virtual Machine

. Verify your disk and network performance.
+
Before running the Anypoint Platform Private Cloud Edition installer, ensure that your disk and network performance meets the minimum requirements. See link:./prereq-verify[To Verify System Requirements] for tips on how to complete this prerequisite.

. Enable forwarding when using firewalld
+
If you are running Red Hat Enterprise Linux (RHEL), 7.3 using firewalld, you must enable forwarding as described in link:./prereq-firewalld-forwarding[To Enable Forwarding When Using firewalld]

. Ensure that the clocks on all servers are synchronized. Unsynchronized clocks can cause problems with platform communications.

After installing and verifying these prerequisites, you are ready to perform the installation. See link:install-workflow[Workflow: Install Anypoint Platform Private Cloud Edition] for more information.
