= To Create Anypoint Private Cloud Resources on Amazon Web Services (AWS)

This topic describes how to create the resources required to install Anypoint Platform Private Cloud Edition on Amazon Web Services (AWS). Anypoint Private Cloud supports 3-node and 6-node configurations in a production environment on AWS.

== Prerequisites

To install Anypoint Platform Private Cloud Edition on AWS, you must have an AWS account with the following:

* Your account must have AWS keys with EC2FullAccess permissions. 
* When creating your AWS environment, the following resources are created:
+
[%header%autowidth.spread]
|===
| AWS Resource | Number required (3-node) | Number required (6-node)
| m4.2xlarge | 3 | 6
| root disk @ 500 iops | 3 | 6
| EBS volumes @ 1500 iops | 6 | 12
| EBS volume @ 3000 iops | 6 | 12
| Amazon ELB | 1 | 1
| t2.medium | 1 | 1
|===

* Download Terraform version 0.11.0. This is the only version of Terraform supported.

== Creating Your Environment in AWS

. Ensure that you have an AWS account that contains the prerequisites mentioned above.
. Contact your customer success representative to obtain the Anypoint Platform Private Cloud Edition terraform configuration.
+
[WARNING]
Do not modify the Terraform files provided. Anypoint Platform Private Cloud Edition does not support modifying or customizing the Terraform script.

. Extract the downloaded archive.
. Copy the Terraform binary into the folder you extracted previously.
. Set the following environment variables on your system:
+
[%header%autowidth.spread]
|===
| Property | Description
| ROLE_TAG_VALUE | (Optional) Specifies a label for the assets terraform creates. If you do not supply a value, Terraform uses `anypoint-platform` by default
| CLUSTER_NAME | Specifies the name of the cluster in AWS. This value cannot contain any whitespace.
| AWS_ACCESS_KEY_ID | Specifies the AWS access ID Terraform uses to connect to your AWS account. 
| AWS_SECRET_ACCESS_KEY  | Specifies the AWS access key Terraform uses to connect to your AWS account.
| REGION | Specifies the AWS region where Terraform creates the cluster.
| NODES | Specifies the number of nodes that Terraform creates. Valid values are: `1`, `3`, `6`
| KEY_PAIR | Specifies the AWS key pair that Terraform uses when creating the cluster. Do not include the `.pem` extension as part of this value.
|===
+
These environment variables define the credentials for Terraform to connect to your AWS environment.

. From the archive folder run the following command:
+
----
terraform apply -state test-vpc.tfstate -var 'cluster_name=test-vpc' -var 'nodes=3' -var 'instance_type=m4.2xlarge' -var 'key_pair=key_name' -var 'access_key=XXXXX' -var 'secret_key=XXXXX' -var 'region=us-west-2' -var 'role_tag_value=anypoint' -var-file=prod.tfvars
----
+
This script displays the Terraform plan that outlines all of the resources to be created in your AWS environment.

. Confirm the Terraform plan by entering `yes` and pressing Return/Enter.
+
After confirmation, Terraform creates the required resources within your AWS account.

. Login to the AWS console to determine the public IP address of the bastion.
+
You must use this IP address to connect to the nodes of your cluster through bastion in order to install Anypoint Platform Private Cloud Edition.

== Install Anypoint Platform Private Cloud Edition

After provisioning resources in your AWS environment and uploading the installer to one of the nodes, install Anypoint Platform Private Cloud Edition using one of the installers:

* link:/anypoint-private-cloud/v/1.7/install-installer[To Install Anypoint Private Cloud using the GUI Installer]
* link:/anypoint-private-cloud/v/1.7/install-auto-install[To Install Anypoint Private Cloud using the Command Line Installer]

== Disabling Port 61009 After Installation

When provisioning resources on AWS the Terraform script enables inbound and outbound traffic on port 61009. This port is required to allow browser access to the installer. After you complete the installation of Anypoint Platform Private Cloud Edition, you must disable external inbound traffic on port 61009 in the `<cluster-name>-cluster` security group from the AWS web console.

== See Also

* https://www.terraform.io/intro/getting-started/install.html[Install Terraform]
* https://docs.aws.amazon.com/quickstart/latest/linux-bastion/welcome.html[Linux Bastion Hosts on the AWS Cloud: Quick Start Reference Deployment]