= To Migrate Anypoint Platform Private Cloud, Version 1.6.x to 1.7.0

This topic provides information about upgrading Anypoint Platform Private Cloud Edition to the most recent version. The following migration paths are supported in this verions:

[%header%autowidth.spread]
|===
| Base Version | Intermediate Version | Target Version | Comments
| 1.6.1 | N/A | 1.7.0 | Direct migration is supported
| 1.6.0 | N/A | 1.7.0 | Direct migration is supported
| 1.5.2 | 1.6.1 | 1.7.0 | Must upgrade to 1.6.1 first
| 1.5.1 | 1.6.1 | 1.7.0 | Must upgrade to 1.6.1 first
|===

[WARNING]
During the migration process, there may be some downtime as each node is migrated.


== Prerequisites

Before migrating, ensure that you have performed and met the following prerequisites:

* Perform a backup of your system as described in link:backup-and-disaster-recovery[About Backup and Recovery].

* Ensure that your environment meets all of the system and network requirements described in link:system-requirements[About Minimum System Requirements]

* Enable TCP ports `5973`, `3022`, `7373` intra-node to enable communication with the database cluster.

* Ensure you have permission to run the `sudo` command on the node where you launch the migration tool.

* Ensure the `kubectl` command is available in the node where you are performing the migration. To verify that `kubectl` is installed, run the following:
+
----
$ sudo gravity enter
$ kubectl
----

== To Perform the Upgrade

. Obtain the installer from your customer success representative.

. Use `ssh` to login to one of the nodes of your cluster.
+
Performing these procedures from a single node updates the entire platform.

. Uncompress the application archive.
+
----
tar -xvf anypoint-1.7.0-installer.tar.gz
----

. Navigate to the `anypoint-1.7.0` directory, then run the upload script.
+
----
sudo ./upgrade
----
+
This command updates the platform to the current version and restarts each pod in the cluster.
+
----
$ sudo ./upgrade
-> initializing upload
-> uploading update package
importing anypoint:1.7.0-rc.3
synchronizing anypoint:1.7.0-rc.3 with Docker registry at 172.31.0.26:5000
synchronizing anypoint:1.7.0-rc.3 with Docker registry at 172.31.0.45:5000
synchronizing anypoint:1.7.0-rc.3 with Docker registry at 172.31.0.5:5000
anypoint:1.7.0-rc.3 has been uploaded
updating anypoint from 1.6.1 to 1.7.0-rc.3
update operation (bae00abf-98a7-4ca9-b0d2-06f3bfea3024) has been started
the cluster is updating in background
----
+
Depending on your network configuration, this command may take a while to complete. Wait until the command finishes before proceeding to the next step.

. Verify that the migration was successful by performing one of the following:
+
* Run the following command from the node where you performed the upgrade:
+
----
$ sudo gravity enter
$ kubectl get pods
----
+
* Login to the Ops Center at the following URL:
+
----
https://{platform-host}:9500
----

