= To Migrate Anypoint Platform Private Cloud, Version 1.6.x to 1.7.0

This topic provides information about upgrading Anypoint Platform Private Cloud Edition to the most recent version.

[WARNING]
During the migration process, there may be some downtime as each node is migrated.


== Prerequisites

Before migrating, ensure that you have performed and met the following prerequisites:

* Perform a backup of your system as described in link:backup-and-disaster-recovery[About Backup and Recovery].

* Ensure that your environment meets all of the system and network requirements described in link:system-requirements[About Minimum System Requirements]

* Enable TCP ports `5973`, `3022`, `7373` intra-node to enable communication with the database cluster.

* Ensure you have permission to run the `sudo` command on the node where you launch the migration tool.

* Ensure the `kubectl` command is available in the node where you are performing the migration. To verify that `kubectl` is installed, run the following:
+
----
$ sudo gravity enter
$ kubectl
----

== To Perform the Upgrade

. Obtain the installer from your customer success representative.

. Use `ssh` to login to one of the nodes of your cluster.
+
Performing these procedures from a single node updates the entire platform.

. Uncompress the application archive.
+
----
tar -xvf anypoint-1.7.0-installer.tar.gz
----

. Navigate to the `anypoint-1.7.0` directory, then run the upload script.
+
----
sudo ./upgrade
----
+
This command updates the platform to the current version and restarts each pod in the cluster.
+
----
$ sudo ./upgrade

----
+
Depending on your network configuration, this command may take a while to complete. Wait until the command finishes before proceeding to the next step.

. **Any additional steps?**

== See Also

* link:/anypoint-private-cloud/v/1.6/upgrade-1.6.1[To Migrate Anypoint Platform Private Cloud Edition, Version 1.5.x to 1.6.1]
* link:/anypoint-private-cloud/v/1.6/upgrade-1.6.0-1.6.1-one-node[To Migrate Anypoint Platform Private Cloud Edition, Version 1.6.0 to 1.6.1 (One Node)]
* link:/anypoint-private-cloud/v/1.6/system-requirements[About Minimum System Requirements]
* link:/anypoint-private-cloud/v/1.6/managing-via-the-ops-center[To Manage Anypoint Platform Private Cloud Edition Using Ops Center]
