= About Secret Groups

A Secret Group is a namespace to which all your secrets are bound. +
Anypoint Secrets Manager stores your secrets per secret group, per environment, and per business group. Meaning that only applications deployed to those specific business groups and environments within your organization can access the secrets stored in each secret group.

Each secret group can store the following security object types:

* Keystore +
A keystore is a Directory Service Markup Language (DSML) file that defines a logical identity using X.509 certificates, symmetric keys, and a username/password. The keystore supports the full abstract relationship permitted by XML security standards. At least one keystore is required for each secret group.

* Truststore +
This security object contains a file of PEM formatted Certificate Authorities certificates concatenated together. +
A Certificate Authority (CA) is an entity that vouches for the validity of a certificate. A CA identifies the entity that issued the digital certificate, verifies the certificate information, and digitally signs the certificate using its own private key.
+
In the PEM file, each certificate identifies a trusted CA. These trusted CA certificates can be either root or immediate CA certificates. If a far-end certificate has a valid chain of trust (path of intermediate CA certificates) to any trusted CA certificate in this PEM file, that far-end is considered to be authenticated.

* Certificate +
This security object contains an X.509 certificate, an electronic document that uses a digital signature to bind together a public key with an identity. +
Anypoint Secrets Manager supports PEM and JKS certificates.

* Certificate Pinset +
List of Certificate Pinset. +
Certificate pinning associates a remote host with the expected X.509 certificate. Once a certificate is known or seen for a host, the certificate is associated or pinned to that host. If more than one certificate is acceptable, then the program holds a pinset.
+
Anypoint Secrets Manager lets you upload one or more concatenated PEM format CA certificates.

* Shared Secret +
This security object contains a username and password or a base64 encoded symmetric key. +
The shared secret is used for symmetric encryption and decryption, where the secret is known by both the message sender and the message recipient. The sender uses the key to encrypt and/or sign the message. The recipient uses the key to decrypt the message and/or verify a message’s digital signature.
+
Anypoint Secrets Manager allows an administrator to define either a static username/password combination, a static symmetric key, or S3 bucket.

* Certificate Revocation List (CRL) Distribution Configuration +
A Certificate Revocation List (CRL) distributor is an entity that creates and maintains a list of certificates issued by the CA that are no longer trusted because their associated private keys, or a signing CA, were compromised. +
+
Anypoint Secets Manager lets you create CRL distribution points to query a CRL Distributor for a specific CA certificate. If the secrets manager finds your queried CA in a CRL list, it revokes any policy using certificates signed by this CA certificate.

* TLS Context +
This security object defines all SSL critical security parameters.

Secret groups are a shared space. To make sure that the data bound to them remains consistent, each secret group maintains a state information. Possible values are Clear, Finishing, and Deleting. +
The state information must always be "clear" to serve the secret to a requesting client.

Additionally, the secrets manager service assigns locks to users modifying the secrets group content. +
Before performing any action to the secret, the user must get a lock from the secrets manager. After the operation is finished, the secrets manager releases the lock. +
This prevents other users from modifying a locked secret. This process is automatic, and there is no extra configuration needed from your end.


== See Also
