= About Secret Groups

A Secret Group is a namespace to which all your secrets are bound. +
Anypoint Secrets Manager stores your secrets per secret group, per environment, and per business group. Meaning that only applications deployed to those specific business groups and environments within your organization can access the secrets stored in each secret group.

Each secret group can store the following secret types:

* Keystore +
A certificate and its associated private key combined in single file in JKS or P12 or JCEKS formats or separate RSA/DSA public private key pair in PEM format.
* Truststore +
List of trusted Certificate Authorities One or more PEM/JKS/JCEKS/P12 format CA certificates concatenated.
* Certificate +
X.509 certificates. Certificate must be one PEM or JKS format certificate.
* Certificate Pinset +
List of Certificate Pinset One or more PEM format CA certificates concatenated.
* Shared Secret +
Allows an administrator to define either a static username/password combination,  a static symmetric key, or S3 bucket.
* Certificate Revocation List (CRL) Distribution Configuration +
Control interaction with Certificate Revocation List (CRL) Distributor.A single CRL Distributor may generate CRL file for one or more Certificate Authorities.
* TLS Context +
Defines all SSL critical security parameters except for actual tokens.

Secret groups are a shared space. To make sure that the data bound to them remains consistent, each secret group maintains a state information. Possible values are Clear, Finishing, and Deleting. +
The state information must always be "clear" to serve the secret to a requesting client.

Additionally, the secrets manager service assigns locks to users modifying the secrets group content. +
Before performing any action to the secret, the user must get a lock from the secrets manager. After the operation is finished, the secrets manager releases the lock. +
This prevents other users from modifying a locked secret. This process is automatic, and there is no extra configuration needed from your end.


== See Also
