= About Secret Groups

A Secret Group is a unique secrets vault to which all your secrets are bound. Each Secret Group has individual access and authorization controls.

Anypoint Secrets Manager stores your secrets per secret group, per environment, and per business group. Meaning that only applications deployed to those specific business groups and environments within your organization can access the secrets stored in each secret group.

Each secret group lets you store different security object types.

== Supported Security Objects

=== Keystore

A keystore is a Directory Service Markup Language (DSML) file that defines a logical identity using X.509 certificates, symmetric keys, and a username/password. The keystore supports the full abstract relationship permitted by XML security standards. At least one keystore is required for each secret group.

=== Truststore

A truststore is a repository of security certificates from other parties with which you expect to communicate, or from Certificate Authorities that you trust to identify other parties. +
A Secrets Manager truststore accepts the following standard format inputs

* PEM
* JKS
* PKCS12
* JCEKS

=== Certificate

This security object contains an X.509 certificate, an electronic document that uses a digital signature to bind together a public key with an identity. +
Anypoint Secrets Manager supports PEM and JKS certificates.

=== Certificate Pinset

A Certificate Pinset is a repository of security certificates from other parties that associate a client or host with their expected X.509 certificate or public key. These security certificate identities are then "pinned" to clients or hosts. +
This repository or "Pin Set" act as a white list of certificates that can be used, for instance, to identify clients in an SSL/TLS connection. Anypoint Secrets Manager would accept a concatenated list of PEM certificates as input.

=== Shared Secret

This security object contains a username and password or a base64 encoded symmetric key. +
The shared secret is used for symmetric encryption and decryption, where the secret is known by both the message sender and the message recipient. The sender uses the key to encrypt and/or sign the message. The recipient uses the key to decrypt the message and/or verify a message’s digital signature.

Anypoint Secrets Manager allows an administrator to define either a static username/password combination, a static symmetric key, or S3 bucket.

=== Certificate Revocation List (CRL) Distribution Configuration

A Certificate Revocation List (CRL) distributor is an entity that creates and maintains a list of certificates issued by the CA that are no longer trusted because their associated private keys, or a signing CA, were compromised.

Anypoint Secets Manager lets you create CRL distribution points to query a CRL Distributor for a specific CA certificate. +
To configure a CRL distributor, you must to provide a URL of the CRL distributor, a CA certificate, and a frequency to check the list for updates. +
As some CRL lists can grow very large, you can provide an optional "Delta CRL Issuer URL" if the CRL distributor supports it, to retrieve deltas to the CRL list instead of retrieving the entire list.

=== TLS Context

This security object defines all SSL critical security parameters.

Secret groups are a shared space. To make sure that the data bound to them remains consistent, each secret group maintains a state information. Possible values are Clear, Finishing, and Deleting. +
The state information must always be "clear" to serve the secret to a requesting client.

Additionally, the secrets manager service assigns locks to users modifying the secrets group content. +
Before performing any action to the secret, the user must get a lock from the secrets manager. After the operation is finished, the secrets manager releases the lock. +
This prevents other users from modifying a locked secret. This process is automatic, and there is no extra configuration needed from your end.


== See Also
