= Create a Monitor

You can create a simple monitor by filling in fields if you do not know how to write tests in the Behavior Driven Development (BDD) test-writing language or how to use the BAT CLI. This method of creating a monitor creates a test suite that contains one test, and schedules the test suite to run at intervals that you select.

After every interval, you can view the results of the test and statistics about API performance


== Before you begin

* Determine which endpoint you want to test and the REST method that you want to test it with.
* Decide upon the return code that you expect the method to return. When you create a test using this method, you can test only one assertion.
* Figure out the frequency at which you would like the monitor to test the endpoint. The shortest interval is every fifteen minutes. You can also choose to run the monitor hourly, daily, weekly, or monthly. The schedule begins immediately after you create the monitor. After you create the monitor, you can schedule another monitor for the same test suite that is more detailed, if you prefer.
* Determine which execution location you would like to run the monitor in.
* Decide whether you would like the return message to include additional header information.
* Obtain one of the following pieces of information, if you would like to send reports to one of these reporting tools:
+
|===
|Reporting Tool |Required Information

|NewRelic
|License Key

|PagerDuty
|RoutingKey

|Slack
|Webhook

|SumoLogic
|Endpoint
|===


== Procedure
To create a monitor for a test of one endpoint:

. In the *Functional Monitoring* section of Anypoint Monitoring, click *Create*.
. Specify a name and a short description for the monitor.
. Fill in the fields with the information that you have gathered.
. Click *Create*.

== Result

The dashboard opens. The monitor is listed on the left. Initially, the list item will indicate that the scheduled monitor has not yet run. Also, the *Monitored Endpoints*, *Tests*, and *Schedules* sections will all be empty. However, the monitor is in fact running. After the monitor has run, the list item for the test suite will indicate whether the monitored endpoint passed or failed.

== What to do next

Click the *Scheduling* tab to see the schedule for the monitor. You can add additional schedules and delete schedules that you no longer want to run. You can also disable schedules, if you want to pause them, and then enable them again.

After the monitor runs, click the *Monitored Endpoints* tab to see:

* Whether the endpoint returned the expected code, as indicated by *PASSED* in the first column of the table
* Statistics about the execution of the test of the endpoint

As your monitor continues to run at the scheduled intervals, the statistics in this table are updated. They show the minimum, average, and maximum runtime for up to five executions of the test.

Click *Tests* to see statistics and information pertaining to the monitor. Because you have only one test in the monitor, the statistics and information in this section apply to the test, too.

If you want to delete the monitor, delete all versions of it in the *Tests* section.
