= Write and Run BAT Tests in IntelliJ IDEA

You can write and run BAT tests in IntelliJ IDEA. The DataWeave 2.0 Intellij plugin, which adds the required support, offers these features:

* Support for local refactoring
* Syntax highlighting
* A view of the structure of the BAT test that you are editing
* MULE XML language injection
* String interpolation
* Support for running and debugging tests

== About this task

The steps in this procedure explain how to modify a BAT project for support in IntelliJ IDEA, open that project, create a new test file, and run a test.

== Before you begin

* Install the DataWeave 2.0 IntelliJ plugin by following these steps:
+
. In IntelliJ IDEA, open the preferences.
. Select *Plugins* and then click *Browse Repositories*.
. Click *Manage Repositories*.
. Click the plus icon to add a custom repository.
. Paste in the following URL: https://github.com/mulesoft-labs/data-weave-intellij-plugin
. Click *Check Now* to verify that the repository is reachable. Then, click *OK*.

* Log into BAT and run the `bat --update` command to be sure that you have the latest version of the BAT CLI.

== Procedure

. If you do not already have a BAT project that you want to work with, create one with the `bat` command.
. Inside the project folder, run the command `bat idea`.
+
*Result*: The command creates a new file in the project: `_project-name_.iml`
. In IntelliJ IDEA, open the project.
. Set the Java SDK for your project.
