= Configure Log Forwarding

This topic provides guidelines for how to configure Runtime Fabric to forward application logs and Runtime Fabric cluster logs to an external logging service. 

The log forwarder included in Runtime Fabric enables users to send logs to an rsyslog server over TCP or UDP.

1. On the Runtime Fabric cluster, create a file named `log-forwarder.yaml`.
2. Add the contents of the YAML file below, ensuring the following fields are updated.
+
----
kind: logforwarder
version: v2
metadata:
   name: forwarder1
spec:
   address: 192.168.100.1:514
   protocol: udp
----
+
Using the following values:
+
[%header,cols="2*a"]
|===
|Key | Description
|name | Specifies the name of the log forwarding rule.
|address | Specifies the endpoint and port to forward the log data
|protocol | An optional field specifying the protocol to send the data to. Supported protocols are TCP or UDP.
|===
+
3. Run the following command on the cluster, referencing the file created earlier.
----
gravity resource create log-forwarder.yaml
----

Your logs should now be forwarded to your external logging service.

== See Also
