= To Consume AMQP Messages
:keywords: amqp, connector, consume, message
:toc:
:toc-title:

The Consume operation in the AMQP connector provides the ability to consume a Message at any given time of the flow, from any given AMQP Queue.

== Consuming A Message
The syntax to consume a message from a Queue is:

[source, xml, linenums]
----
<amqp:consume config-ref="AMQP_config" queueName="#[vars.queue]"/>
----

The operation above consumes the first available message in the Queue identified by the queueName, and then converts it to a `AmqpMessage` resulting in the following structure:

* The message's content as payload.
* The message's metadata in the message attribute

Once received, the Message will be immediately ACKed by default. If you want to control the ACK of the Message after some processing, then `ackMode` should be set to `MANUAL`
For more information regarding a Message ACK, check the link:amqp-ack[How to handle Acknowledgement].

== Waiting for a Message

By default, the maximum wait time is configured in 10 seconds, producing a `AMQP:TIMEOUT` error if no message is available in that period.
In order to configure a timeout that fits better your use case, customize the `maximumWait` and `maximumWaitUnit` parameters.

In order to wait indefinitely for a Message to arrive, the `maximumWait` value has to be set to `-1`. In this case, no `TIMEOUT` error will be thrown.

== Mime Types and Encoding

The AMQP Connector does its best to auto determine a Message’s mime type (`contentType`) based on the `contentType` property of the message. However, there are cases in which that best guess is not enough, and you need first-hand knowledge of the Message’s content.

In such cases, you can force that content type to a particular value by using the `contentType` parameter.

The same process works for encoding. By default, the connector will assume that the runtime’s default encoding matches the one in the Message if no other information is provided. You can set this by using the `encoding` parameter.

== Declaring a Queue in the Consume Operation

By default, the `consume` operation will fail in case the defined queue does not exist with an `AMQP:QUEUE_NOT_FOUND` error.

For cases where the queue has to be declared, a definition for the entity should be referenced or inline defined so that the queue is declared.

[source, xml, linenums]
----
<amqp:consume config-ref="Amqp_Config" queueName="testQueue">
	<amqp:fallback-queue-definition removalStrategy="SHUTDOWN" exchangeToBind="exchangeToBind" />
</amqp:consume>
----

Notice that in the definition of the queue a binding can be created using the parameter exchangeToBind.

The queue can also be defined as a high level element:

[source, xml, linenums]
----
<amqp:queue-definition name="targetQueueDefinition" exchangeToBind="testExchange" />

<amqp:consume  config-ref="AMQP_Config" queueName="testQueue" fallbackQueueDefinition="targetQueueDefinition">
----

A high level element can also be referenced using an expression.

[source, xml, linenums]
----
<amqp:consume  config-ref="AMQP_Config" queueName="testQueue" fallbackQueueDefinition="#[targetQueueDefinition]">
----

== How to avoid changing the AMQP Topography

You can set the `createFallbackQueue` global config properties so that any declaration of AMQP queues is disabled. This parameter has been added for those scenarios where it must be guaranteed that no changes to the AMQP topography will be attempted. In those cases, both the declaration of queues which does not previously exist will result in an `AMQP:CREATION_NOT_ALLOWED` error.

Take for example the following flow:

[source, xml, linenums]
----
<amqp:config name="Amqp_Config" createFallbackQueue="false" >
	<amqp:connection host="localhost" username="guest" password="guest" />
</amqp:config>


<flow name="mule-no-create-fallback-queue">
	<http:listener doc:name="Listener"config-ref="HTTP_Listener_config" path="/"/>
	<amqp:consume config-ref="Amqp_Config" queueName="testQueue">
		<amqp:fallback-queue-definition removalStrategy="SHUTDOWN" exchangeToBind="exchangeToBind" />
	</amqp:consume>
</flow>
----

If the `testQueue` exchange does not exist and the createFallbackQueue is set to false, an invocation of the consume operation shall derive in a `AMQP:CREATION_NOT_ALLOWED` error. 
Notice that the createFallbackQueue can be overridden at the operation level and it can get an expression as a value. For example:

[source, xml, linenums]
----
<flow name="mule-no-create-fallback-queue">
	<http:listener doc:name="Listener"config-ref="HTTP_Listener_config" path="/"/>
	<amqp:consume config-ref="Amqp_Config" queueName="testQueue" createFallbackQueue="true">
		<amqp:fallback-queue-definition removalStrategy="SHUTDOWN" exchangeToBind="exchangeToBind" />
	</amqp:consume>
</flow>
----

== Incoming Message Metadata

As stated before, each Message received will consist of two parts:

* The payload, containing the content of the Message
* The attributes, containing metadata regarding the Message

This Metadata has four parts that map all the information available in a AMQP Message:

* Envelope
* AckId
* Headers
* Properties

Check the link:amqp-documentation[AMQP Reference] for details regarding the Attributes structure.

== See Also

* link:amqp-listener[To Listen For New Messages]

