= About TLS

Transport Layer Security (TLS) alleviates the problem of securing data in an application network. Some connectors provide a secure, server-side connection over a protocol, such as HTTPS or SMTPS (Simple Mail Transfer Protocol Secure). These connectors require configuration of TLS. Design Center supports TLS 1.1/1.2. You can set up a connector to use one or both of the following TLS configurations:

* A trust store
* A key store in Java KeyStore (JKS) format 

You can configure TLS on the server-side using the connector UI, such as HTTP Listener, or a Mule XML editor. Some connectors also provide a secure client-side connection. In the HTTP Request configuration, for example, you can explicitly configure TLS in the request. If you don't configure TLS in the request, the app uses default JVM certificates to establish communications.

In XML, you configure the tls:context child element of the listener-config. 

**QUESTION FOR REVIEWERS: WHAT DO WE NEED TO SAY IN DESIGN CENTER CONNECTOR DOCS ABOUT TLS CONFIGURATION IN MULE?**

== See Also

* link:/connectors/common-workflow-conf-tls[Workflow: Configuring TLS]
* link:/connectors/common-tls-conf-reference[TLS Configuration Reference]




