= To Copy a File with a Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title: To Copy a File

You can use the Copy operation to the File connector in a Mule app to copy files in a local file system.

. Select the Copy operation from the File connector.
. Provide the File Path to the file that you want to copy, including the file name.
+
The supplied path must point to a file. Attempts to read a file that does not exist or to read a directory without specifying a file result in a `FILE:ILLEGAL_PATH` error.
+
. [Optional] Perform other tasks, for example:
  ** Set up or select a configuration for the connector.
  ** Use Advanced settings:
    *** To explicitly set the Mime Type (for example, `application/xml`) or Encoding (for example, `UTF-8`) of the file that you are reading.
      **** Encoding can be any accepted by your operating system. If you do not specify it, the output encoding will be the same as the input.
      **** Mime type can be any standard mime type. If you do not specify it, the operation will attempt to guess it based on the file extension, and will use the input if the mime type cannot be determined from the extension.
    *** To create a Target Variable that holds the output of the Read operation.
    *** To apply a filesystem-level lock to prevent simultaneous access to the file by multiple processes.
  ** Map custom error messages to error codes.


[[xml_example]]
== XML Example

This example copies `full_record.json` to a new location (`/Users/me/testing/out/`) and provides a new file name (`full_record_copy.json`) for the copy.

----
<file:copy config-ref="File_Config_Out" sourcePath="full_record.json" targetPath="/" doc:name="Copy" doc:id="1f86eccf-468d-46ad-9163-83473df81fc5" renameTo="/Users/me/testing/out/full_record_copy.json" overwrite="true" />
----

[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]
* link:/connectors/file-to-set-up-a-file-connector-config[To Set Up a File Connector Configuration]
* link:/connectors/target-variables[About Target Variables]
* link:/mule-user-guide/reconnection-strategy-about[About Reconnection Strategies]
