= To Perform Basic File Operations
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

toc::[]

// For Anypoint Studio, Design Center: FTP connector
Basic file operations include reading from a file, writing to a file, creating directories, as well as copying, moving, renaming, and deleting files.

// do not remove this anchor
[[preconditions]]
== Preconditions for all FTP operations

* You must configure a trigger (for example, with the HTTP or Polling connector) for your flow before adding an FTP operation to your flow.
* After adding the FTP connector to your flow, you select an FTP operation, such as Read or Write.
* All operations require you to set up or select an <<see_also,FTP or SFTP configuration>> for the connector.


// Steps: shared with other operations and connectors

//== To Read from a File
[[read_file]]
include::include-to-read-a-file.adoc[]

//== To Write to a file
[[write_to_file]]
include::include-to-write-to-a-file.adoc[]

//== To List files
[[list_files]]
include::include-to-list-files.adoc[]

== To Copy or Move a File

You can use the Copy or Move operation with this procedure.

include::include-to-copy-or-move-a-file.adoc[]

== To Create a Directory

This procedure uses the Create Directory operation.

include::include-to-create-a-directory.adoc[]

== To Rename a File

This procedure uses the Rename operation.

include::include-to-rename-a-file.adoc[]

== To Delete a File

This procedure uses the Delete operation.

include::include-to-delete-a-file.adoc[]

// do not remove this anchor
[[see_also]]
== See Also

include::include_link_list.adoc[tags=ftp-set-up]

include::include_link_list.adoc[tags=sftp-set-up]

include::include_link_list.adoc[tags=set-data-types]

include::include_link_list.adoc[tags=ftp-connector]

include::include_link_list.adoc[tags=tech-ref-ftp]



////
=== Example
PROBABLY WILL REMOVE THIS

[source,xml,linenums]
....
<spring:beans>
    <spring:import resource="file-read-config.xml"/>
</spring:beans>

<flow name="readAndDo">
    <file:read path="input" />
    <file:copy sourcePath="input/source.txt" targetPath="backup" overwrite="true" createParentDirectories="true"/>
</flow>
....
////
