= To Read a File with a Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title: To Copy a File

////
toc::[]

For Anypoint Studio, Design Center:
include::include_link_list.adoc[tags=file-connector]
include::include_link_list.adoc[tags=ftp-connector]
////

You use the Read operation to the File connector to read a file at any given point in a flow of a Mule app. The connector returns a MuleMessage with the following attributes:

* Payload: The body of the file, an `InputStream`.
* Attributes: File metadata, a `FileAttributes` instance.

. Within your flow, select the Read operation from the File connector.
. Provide the File Path to the file that you want to read, including the file name.
+
The supplied path must point to a file. Attempts to read a file that does not exist or to read a directory without specifying a file result in a `FILE:ILLEGAL_PATH` error.
+
. [Optional] Perform other tasks:
  ** Set up or select a configuration for the connector.
  ** Use Advanced settings:
    *** To explicitly set the Mime Type (for example, `application/xml`) or Encoding (for example, `UTF-8`) of the file that you are reading.
      **** Encoding can be any accepted by your operating system. If you do not specify it, the output encoding will be the same as the input.
      **** Mime type can be any standard mime type. If you do not specify it, the operation will attempt to guess it based on the file extension, and will use the input if the mime type cannot be determined from the extension.
    *** To create a Target Variable that holds the output of the Read operation.
    *** To apply a filesystem-level lock to prevent simultaneous access to the file by multiple processes.

== XML Example

This example reads a JSON file and specifies an output Mime type and encoding.

----
<file:read config-ref="File_Config_In" path="in/full_record.json" outputMimeType="application/json" outputEncoding="UTF-8"/>
----

[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]
* link:/connectors/file-to-set-up-a-file-connector-config[To set up a File connector]
* link:/connectors/target-variables[About Target Variables]
* link:/mule-user-guide/reconnection-strategy-about[About Reconnection Strategies]


////
[[troubleshooting]]
== Troubleshooting
//TODO: SUSS OUT HOW TO TALK ABOUT THESE IN THE DOCS, maybe not here, TBD

* In the case of using "target" to load the InputStream, it’s the user’s responsibility to make sure that the returned InputStream is fully consumed or eventually closed. (_QUESTION: HOW is the user to DO THIS FOR THE TARGET, or is this note to the Mule developer? only relevant when using a lock?_) This is important because the underlying file handle and file system lock (if locking was enabled) will only be released once that InputStream is closed.

* If the connector is not capable of writing the file or to create the directories, whether because it doesn’t have write permissions, something’s wrong with the file system, etc, a `MuleRuntimeException` will be thrown.

* If the path points to a directory instead of a file, an `IllegalArgumentException` will be thrown.
////


////
== TODO: EXAMPLES FROM TEST CASES ==
[[read]]
=== Read Files

.Syntax
[source,xml,linenums]
----
<file:read path="#[path]"
lock="true|false"
outputEncoding="UTF-8"
outputMimeType="application/xml" />
----

<file:config name="file">
    <file:connection workingDir="${workingDir}" />
</file:config>

<flow name="read">
    <logger level="ERROR" message="#[streaming]" />
    <choice>
        <when expression="#[streaming]">
            <file:read path="#[path]" />
            <object-to-string-transformer />
        </when>
        <otherwise>
            <file:read path="#[path]">
                <in-memory-stream />
            </file:read>
        </otherwise>
    </choice>
</flow>

<flow name="readWithLock">
    <file:read path="#[path]" lock="true">
        <in-memory-stream />
    </file:read>
</flow>

<flow name="readWithForcedMimeType">
    <file:read path="#[path]" outputMimeType="test/test"/>
    <object-to-string-transformer />
</flow>

<file:read path="#[path]"
lock="true|false"
outputEncoding="UTF-8"
outputMimeType="application/xml" />

From functional spec:
"The processor above reads the file in the path and returns a MuleMessage with an InputStream as payload and a FileAttributes instance as attributes. By default, if the file does not exist an IllegalArgumentException will be thrown."
////
