== Dynamic Connections

Many integrations require connecting to different servers depending on a certain condition. Examples of this include:

* Connecting to different invoice storage servers depending on the branch that emitted the invoice.
* Connecting to different servers depending on a given integration subject, like in a multi-tenant use case.

To accommodate these use cases, the `config` element supports expressions, which make it possible for connection parameters to evaluate these conditions and connect to the correct server.

The next examples show dynamic multicast apps that:

<1> Define an FTP or SFTP `config` in which the `host`, `username`, and `password` are expressions.
<2> Describe a flow in which content is posted through HTTP.
<3> Use the File connector to read a CSV file that contains a random set of SFTP destinations with columns such as host, user, and port.
<4> Use a `<foreach>` component to iterate over each of the lines in the CSV file.
<5> On each `<foreach>` iteration, resolve each expression in the FTP or SFTP `config` to a different value, establishing different connections to each of the servers.

.Example: Using FTP Write
[source, xml, linenums]
----
<ftp:config name="ftp"> // <1>
  <ftp:connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
</ftp:config>

<flow name="ftpMultitenant" >
  <http:listener config-ref="HTTP_Listener_config" path="/multitenant"/> // <2>
  <set-variable variableName="content" value="#[payload]" />
  <file:read path="recipients.csv" outputMimeType="application/csv" /> // <3>

  <foreach> // <4>
    <ftp:write path="demo.txt" config-ref="ftp"> // <5>
      <ftp:content >#[vars.content]</ftp:content>
    </ftp:write>
  </foreach>

  <set-payload value="Multicast OK"/>
</flow>
----

The next is example is identical to the previous one, except that it uses an SFTP Write operation.

.Example: Using SFTP Write
[source, xml, linenums]
----
<sftp:config name="ftp"> // <1>
  <sftp:connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
</sftp:config>

<flow name="ftpMultitenant" >
  <http:listener config-ref="HTTP_Listener_config" path="/multitenant"/> // <2>
  <set-variable variableName="content" value="#[payload]" />
  <file:read path="recipients.csv" outputMimeType="application/csv" /> // <3>

  <foreach> // <4>
    <sftp:write path="demo.txt" config-ref="ftp"> // <5>
      <sftp:content>#[vars.content]</sftp:content>
    </sftp:write>
  </foreach>

  <set-payload value="Multicast OK"/>
</flow>
----

Notes on Mule 4 behavior (for Mule 3 users):

* The examples above use the File connector to read a file in the middle of the flow. The information posted through the `<http:listener>` component is written to each FTP or SFTP site multiple times. Because the component makes use of the link:/mule-user-guide/v/4.0/streaming-about[repeatable streams feature], you do not need to worry about consuming the stream multiple times.

* The `<foreach>` component automatically goes through each line of the CSV file. In Mule 3, you first needed to transform the CSV file into a Java structure, but because Mule 4 is now Java agnostic, this works out-of-the-box.
