= About TLS

The HTTP connector supports Transport Level Security (TLS) 1.1/1.2 when you use HTTPS protocol. The Web Service Consumer connector also supports TLS. 

You can customize the TLS configuration using the connector UI or a Mule XML editor. Follow the steps in the "To Configure TLS" topic, or in XML, you configure the tls:context child element of this listener-config. If you don't explicitly configure TLS, the app uses default JVM certificates to establish communications.

You can configure one- or two-way TLS authentication. To configure one-way authentication, set up either the key store or the trust store. To configure two-way authentication, set up both.

== Configuring a Key Store

You can configure two passwords for the key store: 

* One to access the entire key store file
* Another (keyPassword) to access the private key of the server inside the key store file

If the server validates certificates from the clients, in the Mule UI, set the path field to the location of the key store file that contains the private and public keys of the client. Alternatively, in the XML Editor, add the <tls:key-store> element.

== Configuring a Trust Store

If the client requires a certificate from the server, in the Mule UI, set the path to the location of the trust store file that contains the certificates of the trusted servers. Alternatively, in the XML Editor, add the <tls:trust-store> element. 

Certificates can be generated by a well-known Certificate Authority (CA) or can be generated locally without external approval (self-signed certificates). Certificates generated from Certificate Authorities include digital signatures and are usually accepted as trusted by any client that includes the CA certificate in its repository of trusted certificates (trust store). 

If you don’t provide any values for the trust-store, the default Java trust store is used. The default trust store is updated with the Java version. Use an updated Java version that includes updates to well known CA certificates.

== Configuring Two-Way Authentication

A TLS service needs to have two-way authentication: a private key and a public certificate. As mentioned, to configure two-way authentication, set up both a key store and a trust store. Configure the key store on the server to enforce two-way authentication with the client. The private key never leaves the server. The public certificate is exposed through TLS so clients can verify that they trust the server.

== See Also



