= To Perform Basic File Operations with the FTP or SFTP Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

toc::[]

// For Anypoint Studio, Design Center: FTP connector
Basic file operations include reading from a file, writing to a file, creating directories, as well as copying, moving, renaming, and deleting files.

// do not remove this anchor
[[preconditions]]
== Preconditions

* In your flow, select an FTP or SFTP operation, such as Read or Write.
* All operations require you to set up or select an <<see_also,FTP or SFTP configuration>> for the connector.


// Steps: shared with other operations and connectors

//== To Read from a File
[[read_file]]
include::include-to-read-a-file.adoc[]

//== To Write to a file
[[write_to_file]]
include::include-to-write-to-a-file.adoc[]

//== To List files
[[list_files]]
include::include-to-list-files.adoc[]

== To Copy or Move a File

You can use the Copy or Move operation with this procedure.

Note that copying and moving files over FTP is slower than over SFTP because FTP does not provide native support for the operations.

include::include-to-copy-or-move-a-file.adoc[]

== To Create a Directory

This procedure uses the Create Directory operation. Note that if you simply want to write, copy, or move a file to a new directory, you can instead use the Write, Copy, or Move operations with Create Parent Directories checked (or set to true).

include::include-to-create-a-directory.adoc[]

== To Rename a File

This procedure uses the Rename operation. You can use this operation to rename  files and directories.

include::include-to-rename-a-file.adoc[]

== To Delete a File

This procedure uses the Delete operation.

include::include-to-delete-a-file.adoc[]

// do not remove this anchor
[[see_also]]
== See Also

link:ftp-to-set-up-ftp[To Set Up an FTP Configuration]

link:sftp-to-set-up-sftp[To Set Up an SFTP Configuration]

link:https://docs.mulesoft.com/design-center/v/1.0/to-manage-data-types[To Handle Data Types]


////
=== Example
PROBABLY WILL REMOVE THIS

[source,xml,linenums]
....
<spring:beans>
    <spring:import resource="file-read-config.xml"/>
</spring:beans>

<flow name="readAndDo">
    <file:read path="input" />
    <file:copy sourcePath="input/source.txt" targetPath="backup" overwrite="true" createParentDirectories="true"/>
</flow>
....
////
