= To Rename a File or Directory with a Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title: To rename a file or directory

toc::[]

For Anypoint Studio, Design Center:
include::include_link_list.adoc[tags=file-connector]
include::include_link_list.adoc[tags=ftp-connector]

. After adding the connector to your flow, select the *Rename* operation.
. Set up or select a configuration for the connector (see link:to-set-up-a-file-connector-config[To set up a File connector]).
. Set the *Path* to the file that you want to write. If you do not provide a path, the operation will attempt to discover it from the local file attributes associated with the message. If the attempt is unsuccessful, you will receive an error message.
. TODO, TODO

[[see_also]]
== See Also
include::include_link_list.adoc[tags=tech-ref-ftp]

////
===== test case =====
<spring:beans>
    <spring:import resource="file-read-config.xml"/>
</spring:beans>

<flow name="rename">
    <file:rename path="#[path]" to="#[to]" overwrite="#[overwrite]"/>
</flow>

<flow name="readAndRename">
    <file:read path="#[path]" />
    <file:rename path="#[path]" to="#[to]"/>
</flow>

[[rename]]
=== Rename Files or Directories

Rename file or directory example.

[source,xml,linenums]
----
<file:rename path="invoices/current" to="archived" />
----
=====


Renaming is also supported:

<file:rename path="invoices/current" to="archived" />

Parameter Name
Required?
Default Value
Description
path
NO
See below
The path to the file to be renamed


to
YES


The file’s new name


overwrite
NO
false
Whether to overwrite the target file if it already exsits


It can handle both files and directories. Throws IllegalArgumentException if the sourcePath doesn’t exists or if the “to” path already exists but overwrite is set to false.
////
