
= To Create a Matcher
:keywords: file, ftp, email, connector, listener
:toc:
:toc-title:

toc::[]

For Anypoint Studio, Design Center: Email, FTP connectors

Specifies properties (such as name patterns, dates, locations, and sizes) to match
before triggering an operation. Operations, such as *List* for FTP and *List Pop3* for Email, accept files that match _all_ the specified values and ignore files that do not, even files that match some of the criteria.

. Step _TODO: Nav to config for the operation_
. Step _TODO: CONFIG_
  * If you intend to use the same matching criteria for multiple operations, a global matcher configuration is a good choice.
  * If the matching criteria is unique to a specific operation, a local matcher within the operation is sufficient.
. Provide properties to match.

[[example_matcher_email]]
  ** Email example:
    *** *Subject Regex*: `Important Info`
    *** *From Regex*: `@mycompany`
    *** *Seen* (for IMAP only): `false`

[[example_matcher_ftp]]
  ** FTP example:
    *** *Created Since* (as a `DateTime` instance or a `String` in ISO-8601 format), for example: `2016-06-03T13:21:58+00:00`
    *** *Filename Pattern* (as a regular expression _TODO, or glob, like the File connector?_): `a?*.{htm,html,pdf}` or `*[1-2]*.html`
    *** *Directory*: `false`
    *** *Max Size* (in bytes): `1024`

//Matching is useful for operations and sources (such as watchers and listeners) that only need to accept a subset of files in a given directory. Operations (such as *List*) and sources (such as the *Directory Listener*) support matching based on optional attributes (or properties), such as a filename or path, a creation or access date, and so on. Files and directories that do not match are ignored.

[[see_also]]
== See Also

include::include_link_list.adoc[tags=ftp-set-up]

include::include_link_list.adoc[tags=imap-set-up]

include::include_link_list.adoc[tags=pop3-set-up]

include::include_link_list.adoc[tags=tech-ref-email]

include::include_link_list.adoc[tags=tech-ref-ftp]

////
[NOTE]
* The file or directory must match all the specified properties. It will be ignored if it only matches some of the properties.
* Sizes are measured in bytes
* Date-Time values can be a `DateTime` instance or a `String` in ISO-8601 format. _TODO/QUESTION: ANY MORE EXPLANATION NEEDED HERE FOR CUSTOMERS, E.G. LINK TO http://www.iso.org/iso/iso8601? and for DateTime are you talking about the Joda-Time library class, i.e, http://www.joda.org/joda-time/apidocs/org/joda/time/DateTime.html?_
* _PERHAPS A NOTE ON HOW THIS DIFFERS FROM MESSAGE FILTERING?_ Unlike a message filtering, file

_TODO: NEED SOMETHING LIKE THIS, NOT IN XML, PERHAPS IN CONTEXT OF A LISTENER. SCREENSHOT OR TABLE? MIGHT MAKE MORE SENSE FOR THERE TO BE EXAMPLES IN THE REF_

Use a matcher with an operation or listener to work with files that match certain criteria.
NOTE: The term file filtering could also be applied to describe the functionality.

`<file:matcher>` element defines the criteria used to either accept or reject a file for processing by connector. This is how the matcher can be defined.

[source,xml,linenums]
----
<file:matcher
	filename-pattern="a?*.{htm,html,pdf}"
path-pattern="a?*.{htm,html,pdf}"
	createdSince="2015-06-03T13:21:58+00:00"
	createdUntil="2015-07-03T13:21:58+00:00"
	updatedSince="2015-05-03T13:21:58+00:00"
	updatedUntil="2015-06-03T13:21:58+00:00"
accessedSince="2015-06-03T13:21:58+00:00"
accessedUntil="2015-06-03T13:21:58+00:00"
directory="true|false"
regularFile="true|false"
symbolicLink="true|false"
minSize="0"
maxSize="1024" />
----

A look at each attribute:

* `filename-pattern`: Similar to the current filename pattern filter but more powerful. Glob expressions and regex will be supported. Glob will be the default. You can select which one to use by setting a prefix. E.g: glob:**.{java, js} , regex:[0-9]*_test.csv
 * `path-pattern`: the same as filename-pattern but applies over the entire file path. Not just the filename
 * `createdSince`: an inclusive lower boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `createdUntil`: an inclusive upper boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `updatedSince`: an inclusive lower boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `updatedUntil`: an inclusive upper boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `accessedSince`: an inclusive lower boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `accessedUntil`: an inclusive upper boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `directory`: matches only if the file is a directory
 * `regularFile`: matches only if the file is a regular file
 * `symbolicLink`: matches only if the file is a symbolic link
 * `minSize`: an inclusive lower boundary for the file size expressed in bytes
 * `maxSize`: an inclusive upped boundary for the file size expressed in bytes

==== Notes

* All attributes above are optional. They are ignored if not provided. All attributes are considered together (implicit `AND`) when qualifying files.

For that, a <file:matcher> element will be created. This element defines the possible criterias that can be used to either accept or reject a file. This is how the matcher can be defined

To exemplify, here’re the two ways of using it:

Example of top level, reusable matcher

<file:matcher name="smallFileMatcher" maxSize="100" />

<flow name="smallFiles">
    <file:list path="~/smallfiles" matcher="smallFileMatcher" />
    ..
</flow>

Example of inner, not reusable, matcher

<flow name="smallFiles">
    <file:list path="~/smallfiles" matcher="smallFileMatcher">
<file:match-with>
<file:matcher maxSize="100" />
</file:match-with>
    </file:list>
    ...
</flow>
////
