
:keywords: file, ftp, connector, listener
:toc:
:toc-title: To Match File Properties with a Connector

toc::[]

////
For Anypoint Studio, Design Center:
include::include_link_list.adoc[tags=file-connector]
include::include_link_list.adoc[tags=ftp-connector]
////

= To Match File Properties

Specifies file properties (such as file name patterns, dates, locations, or size) to match before triggering an operation. You can configure a matcher locally on an operation, or you can reference a global matcher configuration.
* If you intend to use the same matching criteria for multiple operations, a global matcher configuration is a good choice.
* If the matching criteria is unique to a specific operation, a local matcher within the operation (such as List) is sufficient.

. Decide whether to create a global or local matcher configuration.
. For a global matcher,

Matching is useful for operations and sources (such as watchers and listeners) that only need to accept a subset of files in a given directory. Operations (such as List) and sources (such as the Directory Listener) support matching based on optional attributes (or properties), such as a filename or path, a creation or access date, and so on. Files and directories that do not match are ignored.

[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]

////
_QUESTION: Where do I find it as a top-level element in the connector UI? SPEC SAYS THAT file matcher "can either be used as a named top level element (allowing it to be reused), or as an inner element proprietary to a particular component." Need to double-check, as I haven't seen the Matcher property available as a top-level element, as part of the GUI. Have seen it as an inline property._

[NOTE]
* The file or directory must match all the specified properties. It will be ignored if it only matches some of the properties.
* Sizes are measured in bytes
* Date-Time values can be a `DateTime` instance or a `String` in ISO-8601 format. _TODO/QUESTION: ANY MORE EXPLANATION NEEDED HERE FOR CUSTOMERS, E.G. LINK TO http://www.iso.org/iso/iso8601? and for DateTime are you talking about the Joda-Time library class, i.e, http://www.joda.org/joda-time/apidocs/org/joda/time/DateTime.html?_
* _PERHAPS A NOTE ON HOW THIS DIFFERS FROM MESSAGE FILTERING?_ Unlike a message filtering, file

. Open the the configuration for the operation or source.
. Provide the matching properties, for example:
  * *Created Since*: 2016-06-03T13:21:58+00:00
  * *Filename Pattern*: a?*.{htm,html,pdf}
  * *Directory*: false
  * *Max Size*: 1024
////

////
== Example

_TODO: NEED SOMETHING LIKE THIS, NOT IN XML, PERHAPS IN CONTEXT OF A LISTENER. SCREENSHOT OR TABLE? MIGHT MAKE MORE SENSE FOR THERE TO BE EXAMPLES IN THE REF_

_TODO: Matcher as a global element_
[source,xml]
----
<file:matcher
  filename-pattern="a?*.{htm,html,pdf}"
  path-pattern="a?*.{htm,html,pdf}"
  createdSince="2015-06-03T13:21:58+00:00"
  createdUntil="2015-07-03T13:21:58+00:00"
  updatedSince="2015-05-03T13:21:58+00:00"
  updatedUntil="2015-06-03T13:21:58+00:00"
  accessedSince="2015-06-03T13:21:58+00:00"
  accessedUntil="2015-06-03T13:21:58+00:00"
  directory="true|false"
  regularFile="true|false"
  symbolicLink="true|false"
  minSize="0"
  maxSize="1024" />
----

_TODO: Example of top level, reusable matcher_
[source,xml]
----
<file:matcher name="smallFileMatcher" maxSize="100" />

<flow name="smallFiles">
    <file:list path="~/smallfiles" matcher="smallFileMatcher" />
    ..
</flow>
----

_TODO: Example of inner, not reusable, matcher_
[source,xml]
----
<flow name="smallFiles">
  <file:list path="~/smallfiles" matcher="smallFileMatcher">
  <file:match-with>
  <file:matcher maxSize="100" />
  </file:match-with>
  </file:list>
  ...
</flow>

[[define-matcher]]
=== Define a File Matcher

Use a matcher with an operation or listener to work with files that match certain criteria.

NOTE: The term file filtering could also be applied to describe the functionality.

`<file:matcher>` element defines the criteria used to either accept or reject a file for processing by connector. This is how the matcher can be defined.

[source,xml,linenums]
----
<file:matcher
	filename-pattern="a?*.{htm,html,pdf}"
path-pattern="a?*.{htm,html,pdf}"
	createdSince="2015-06-03T13:21:58+00:00"
	createdUntil="2015-07-03T13:21:58+00:00"
	updatedSince="2015-05-03T13:21:58+00:00"
	updatedUntil="2015-06-03T13:21:58+00:00"
accessedSince="2015-06-03T13:21:58+00:00"
accessedUntil="2015-06-03T13:21:58+00:00"
directory="true|false"
regularFile="true|false"
symbolicLink="true|false"
minSize="0"
maxSize="1024" />
----

A look at each attribute:

* `filename-pattern`: Similar to the current filename pattern filter but more powerful. Glob expressions and regex will be supported. Glob will be the default. You can select which one to use by setting a prefix. E.g: glob:**.{java, js} , regex:[0-9]*_test.csv
 * `path-pattern`: the same as filename-pattern but applies over the entire file path. Not just the filename
 * `createdSince`: an inclusive lower boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `createdUntil`: an inclusive upper boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `updatedSince`: an inclusive lower boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `updatedUntil`: an inclusive upper boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `accessedSince`: an inclusive lower boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `accessedUntil`: an inclusive upper boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
 * `directory`: matches only if the file is a directory
 * `regularFile`: matches only if the file is a regular file
 * `symbolicLink`: matches only if the file is a symbolic link
 * `minSize`: an inclusive lower boundary for the file size expressed in bytes
 * `maxSize`: an inclusive upped boundary for the file size expressed in bytes

==== Notes

* All attributes above are optional. They are ignored if not provided. All attributes are considered together (implicit `AND`) when qualifying files.
* File matcher can either be used as a top level element referenced by `name` (allowing it to be reused in flows), or as an inner element belonging to a particular connector instance.
** Here are the two ways:

.Example of top level reusable matcher
[source,xml,linenums]
----
<file:matcher name="smallFileMatcher" maxSize="100" />

<flow name="smallFiles">
	<file:list path="~/smallfiles" matcher="smallFileMatcher" />
	..
</flow>
----


.Example of inline non-reusable matcher

[source,xml,linenums]
----
<flow name="smallFiles">
	<file:list path="~/smallfiles" matcher="smallFileMatcher">
<file:match-with>
<file:matcher maxSize="100" />
</file:match-with>
	</file:list>
	...
</flow>
----

----

== Related topics
* TODO: LINK TO REFERENCE MATERIAL FOR THE


NOTE: The term file filtering could also be applied to describe the functionality below. However, I’m intentionally choosing the word matching to avoid confusion with the concept of  message filter that already exists in mule.

Another common scenario (which also applies to the watch message source but not exclusively) is the need for only accept files which match with certain criteria.

For that, a <file:matcher> element will be created. This element defines the possible criterias that can be used to either accept or reject a file. This is how the matcher can be defined

<file:matcher
    filename-pattern="a?*.{htm,html,pdf}"
path-pattern="a?*.{htm,html,pdf}"
    createdSince="2015-06-03T13:21:58+00:00"
    createdUntil="2015-07-03T13:21:58+00:00"
    updatedSince="2015-05-03T13:21:58+00:00"
    updatedUntil="2015-06-03T13:21:58+00:00"
accessedSince="2015-06-03T13:21:58+00:00"
accessedUntil="2015-06-03T13:21:58+00:00"
directory="true|false"
regularFile="true|false"
symbolicLink="true|false"
minSize="0"
maxSize="1024" />


All of the attributes above are optional and all are ignored if not provided. Also, they all related to each other under an AND operator.

Let’s take a look at each individual attribute:

filename-pattern: Similar to the current filename pattern filter but more powerful. Glob expressions and regex will be supported. Glob will be the default. You can select which one to use by setting a prefix. E.g: glob:**.{java, js} , regex:[0-9]*_test.csv
path-pattern: the same as filename-pattern but applies over the entire file path. Not just the filename
createdSince: an inclusive lower boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
createdUntil: an inclusive upper boundary for the file creation stamp expressed as either a DateTime instance or a String in ISO-8601 format.
updatedSince: an inclusive lower boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
updatedUntil: an inclusive upper boundary for the file modification stamp expressed as either a DateTime instance or a String in ISO-8601 format.
accessedSince: an inclusive lower boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
accessedUntil: an inclusive upper boundary for the file access stamp expressed as either a DateTime instance or a String in ISO-8601 format.
directory: matches only if the file is a directory
regularFile: matches only if the file is a regular file
symbolicLink: matches only if the file is a symbolic link
minSize: an inclusive lower boundary for the file size expressed in bytes
maxSize: an inclusive upped boundary for the file size expressed in bytes

A good thing about the file matcher is that it can either be used as a named top level element (allowing it to be reused), or as an inner element proprietary to a particular component.

To exemplify, here’re the two ways of using it:

Example of top level, reusable matcher

<file:matcher name="smallFileMatcher" maxSize="100" />

<flow name="smallFiles">
    <file:list path="~/smallfiles" matcher="smallFileMatcher" />
    ..
</flow>

Example of inner, not reusable, matcher

<flow name="smallFiles">
    <file:list path="~/smallfiles" matcher="smallFileMatcher">
<file:match-with>
<file:matcher maxSize="100" />
</file:match-with>
    </file:list>
    ...
</flow>
////
