= To List Files with a File Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

You can use the List operation to the File connector in a Mule app to list all files in a given directory path that match. This path can be absolute or relative. If the path is relative, then it will be relative to the working directory set in the connector configuration. The operation can recurse through subdirectories, and you narrow the list of files to return by specifying file properties to match.

. In your flow, select the List operation from the File connector.
. Provide a Directory Path to the directory that contains the files you want to list.
. Perform any optional tasks you need:
  ** Set up or select a configuration for the connector.
  ** Check Recursive if you also want to list the files within subdirectories.
  ** Provide File Matching Rules if you want to narrow the list of files to return. The files must match all the rules you set.
  ** Set a Target Variable if you need to store output of the operation in a variable for later use in the flow.
  ** Set a Reconnection Strategy.

[[xml_example]]
== XML Example

This example uses a matcher list all files with the extension `*.json` that are found in the `in/` directory path and all of its subdirectories. It also specifies a reconnection strategy.

----
<file:list config-ref="File_Config_In" directoryPath="in/" doc:name="List" recursive="true">
  <reconnect frequency="5000" count="4"/>
  <file:matcher filenamePattern="*.json"/>
</file:list>
----

[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]
* link:/connectors/file-about-the-file-connector[About the Connector]
* link:/connectors/file-to-set-up-a-file-connector-config[To Set Up a File connector]
* link:/mule-user-guide/reconnection-strategy-about[About Reconnection Strategies]
* link:/connectors/ftp-about-matchers[About File Matchers]
* link:/connectors/target-variables[About Target Variables]
