= To Set Up Timeouts for Operations
:keywords: email, ftp, connector, configuration
:toc:
:toc-title:

toc::[]

// Anypoint Studio, Design Center: *Email*, *FTP*, _? TODO, others ?_ connectors

Some connector configurations provide settings for changing timeouts for actions such as reading, writing, making connections, or waiting for responses from a server.

. From an operation in your flow, click the Add or Edit link for a Connector configuration.
. From the Configuration window that opens, click the Advanced tab.
. Scroll to the Timeout Configuration area.
. Set your timeout preferences.
+
For example, for an FTP configuration, you might change the Connection Timeout or Response Timeout from a default of `10` to `20`. You might change the Connection Timeout Unit or Response Timeout Unit from the default of `Seconds` to `Minutes`.

////
FTP Configuration Example:
* Connection Timeout (defaults to `10`) for the Timeout Unit.
* Timeout Unit (one of these):
  ** Nanoseconds
  ** Microseconds
  ** Milliseconds
  ** Seconds (the default)
  ** Minutes
  ** Hours
  ** Days
* Response Timeout (defaults to `10`)
* Response Timeout Unit (one of these):
  ** Nanoseconds
  ** Microseconds
  ** Milliseconds
  ** Seconds (the default)
  ** Minutes
  ** Hours
  ** Days
////
