= To Write a File
:keywords: file, connector, write
:toc:
:toc-title:

A Write operation is available to the File, FTP, and SFTP connectors. For these connectors, the operation writes content into the given path on demand. It supports common use cases described below.

== Embedded DataWeave Transformations

By default, the connector writes whatever is in the message payload:

.Example: File Connector
[source, xml, linenums]
----
<file:write path="output.csv" />
----

.Example: FTP Connector
[source, xml, linenums]
----
<ftp:write path="output.csv" />
----

.Example: SFTP Connector
[source, xml, linenums]
----
<sftp:write path="output.csv" />
----

However, if the payload is a different format (for example, not CSV) and you need to transform it before writing it, what do you do? If you place a Transform component before the Write operation, the message payload changes and that impacts the operation that is placed after the Write operation.

To avoid this undesired impact, you can place the transformation inside the Write operation to generate content that will be written without producing a side effect on the message in transit.

The next example uses the File connector to write the content:

.Example: Transformation within a File Write Operation
[source, xml, linenums]
----
<file:write path="output.csv">
  <file:content>#[%dw 2.0
                  output application/csv
                  ---
                  payload.customers.email
                ]
  </file:content>
</file:write>
----

The next example uses the FTP connector to write the content:

.Example: Transformation within an FTP Write Operation
[source, xml, linenums]
----
<ftp:write path="output.csv">
  <ftp:content>#[%dw 2.0
                 output application/csv
                 ---
                 payload.customers.email
                ]
  </ftp:content>
</ftp:write>
----

The next example uses the SFTP connector to write the content:

.Example: Transformation within an SFTP Write Operation
[source, xml, linenums]
----
<sftp:write path="output.csv">
  <sftp:content>#[%dw 2.0
                   output application/csv
                   ---
                   payload.customers.email
                  ]
  </sftp:content>
</sftp:write>
----

== Writing into Directories

If any of the `a`, `b`, or `c` directories in the examples below do not exist, the Write operation will fail by default. However, if you set the `createParentDirectories` to `true`, the connector will automatically create any missing directories.

.Example: File Connector writes to a Directory
[source, xml, linenums]
----
<file:write path="a/b/c/myFile.txt" />
----

.Example: File Connector writes to a Directory
[source, xml, linenums]
----
<ftp:write path="a/b/c/myFile.txt" />
----

.Example: SFTP Connector writes to a Directory
[source, xml, linenums]
----
<sftp:write path="a/b/c/myFile.txt" />
----

== Writing to Existing Files

There are several file write modes you can use when writing content to a file:

* OVERWRITE: If the file exists, overwrite it completely.
* APPEND: If the file exists, write the content at the end of it the existing file.
* CREATE_NEW: Create a new file. If the file already exists, then you will receive an error.

== Locks

This Write operation supports locking in a fashion similar to the Read operation. The main difference is that the lock will be released automatically once the Write operation finishes.
