== To Write to a File with a Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

You can use the Write operation to the File connector in a Mule app to create, overwrite, or append content to a file that is in a local file system.

. Within your flow, elect the Write operation from the File connector.
. Set the Path to the file that you want to write.
+
If you do not provide a path, the operation will attempt to discover it from the local file attributes associated with the message. Unsuccessful attempts produce an error message.
+
. Provide the Content you want to write to the file.
+
Note that the operation will attempt to transform that content. If that attempt is unsuccessful, the operation will fail.
+
. [Optional] Perform other tasks:
  ** Set up or select a configuration for the connector.
  ** Check Create Parent Directories if the directory for the file to which the operation is writing does not exist yet.
  ** Set the Write Mode:
    * Append: Appends the content to the file.
    * Create New: Creates a new file with the content.
    +
    Note that you will receive an error if a file with that name already exists.
    +
    * Overwrite (Default): Overwrites an existing file with the same name.
    +
    Note that you will receive an error if a file with that name does not exist.
    +
  ** Perform any Advanced configuration.
    *** Encoding
    *** Lock
  ** Set a reconnection strategy to if you want to retry the connection to your directory after a failed attempt.

[[xml_example]]
== XML Example

This example writes (`file:write`) just the addresses in the payload (`#[payload.address]`) that it receives from the Read operation (`file:read`) on `full_record.json`.

----
<file:read config-ref="File_Config_In" path="full_record.json" doc:name="Read" doc:id="5ff55625-8a27-49a0-9edf-397eabeed3e7" />
<file:write config-ref="File_Config_Out" path="full_record_addresses_only.json" doc:name="Write" doc:id="05918741-06e5-4267-b407-8f9958313834" >
  <file:content ><![CDATA[#[payload.address]]]></file:content>
</file:write>
----

[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]
* link:/connectors/file-to-set-up-a-file-connector-config[To Set Up a File Connector Configuration]
* link:/connectors/target-variables[About Target Variables]
* link:/mule-user-guide/reconnection-strategy-about[About Reconnection Strategies]
