= To Rename a File or Directory with a Connector
:keywords: file, ftp, connector, operation
:toc:
:toc-title: To rename a file or directory

You use the Rename operation to the File connector to rename a file or directory on a local file system.

. Select the Rename operation from the File connector in a Mule app.
. Set the Path to the file that you want to rename.
+
If you do not provide a path, the operation will attempt to discover it from the local file attributes associated with the message. If the attempt is unsuccessful, you will receive an error message.
+
. Provide a new name for the file.
. Indicate whether to overwrite an existing file with the same name.
+
Defaults to False.
+
Note that you can provide DataWeave expression, for example, if you want to overwrite certain circumstances but not in others.
+
. [Optional] Perform other tasks, for example:
  ** Set up or select a configuration for the connector.
  ** Provide a Display Name for the connector.
  ** Set a reconnection strategy to if you want to retry the connection to your directory after a failed attempt.
  ** Set up error mapping.

== XML Example

This example renames `full_record.json` to `full_record_renamed.json`.

----
<file:rename config-ref="File_Config_Out" to="full_record_renamed.json" doc:name="Rename" doc:id="906bd9cd-562c-4617-b14f-264c1874bfb1" path="full_record.json"/>
----

[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]
* link:/connectors/file-to-set-up-a-file-connector-config[To Set Up a File Connector]
* link:/mule-user-guide/reconnection-strategy-about[About Reconnection Strategies]
