= Database Connector
:keywords: database, mysql, derby, jdbc, oracle, connector
:toc:
:toc-title: Basics
:toc-levels: 3


toc::[]


[[what-is]]
== What is the Database Connector?

A connector for Mule that allows you to establish connections to standard JDBC, Derby, MySQL, and Oracle databases out of the box.

Along with the option to set up a generic JDBC configuration is the possibility to connect to an SQL DataSource. In all cases, you must first configure a connection to a database in order to set the connector up to perform database operations.

== How to Configure

There is a single configuration element `<db:config>` with fields that are required. Inside the `<db:config>` you have inner child elements where you place other details like the database connection string, driver and other elements. You may specify any custom data types available to your database instance. Reference this configuration element from the connector in your flow.

When developing your Mule app with the database connector, refer to the link:/database-connector-reference[Database Connector Reference].

== Which Operations are Available?

Execute any typical SQL operation, stored procedure, execute in bulk, or run an SQL script inline or from a file.

* Select
* Insert
* Update
* Delete
* Stored Procedure
* Execute DDL
* Bulk Operations (Insert, Update, Delete)
* Execute Script

[NOTE]
With *Execute Script* you can execute an SQL script in one single Database statement, except for a Select query. The script is executed as provided by the user, without any parameter binding. This was formerly `bulk-execute` in Mule 3.x.

== Migrating from Mule 3.x

* `<sql>` element unifies the options: parameterized or dynamic. You no longer specify these.
* Syntax for declaring parameters is more verbose
* Operations *Insert* and *Update* return a `StatementResult` object
//MG what does this return and how does user map the types from this object
* Syntax for template queries has changed
//MG how changed?
* Bulk operations
