= To Schedule a Database Scan

In this procedure, you do the following things:

* Set up a scheduler to update the database every 15 seconds.
* Store a default value in an ObjectStore component.

In ObjectStore, you set up retrieval of a persistent variable having a default value lower than the lowest primary key value of the database rows you want to insert. On the first execution of the flow, the default value being lower than the lowest primary key, causes insertion of all rows in the database that matches the conditions. On subsequent executions, the variable retrieved from ObjectStore contains the primary key of the last row inserted into the database.

. Create a new Mule Application project. In New Flow, click Trigger, select Scheduler, and set the following properties in Scheduler:
+
* Frequency: 15
* Time Unit: Seconds
* Accept other defaults and close Scheduler.
+
. Click + to add another component to the flow, select Object Store, select the Retrieve operation, and set the following properties in Object Store - Retrieve:
+
* In General, in Key type the key name:
+
*lastOrder*
+
* In Default Value, enter a number lower than lowest primary key value in the Classic Models database orders table:
+
*10099*
+
* In Advanced, in Target Variable, type:
+
*lastOrder*
+
This sets a variable to the key-value pair "lastOrder":10099.
+
* Close Object Store - Retrieve.


