= To Schedule a Database Scan

In this procedure, you do the following things:

* Set up a scheduler to update the database every 15 seconds.
* Store an default value in an ObjectStore component.
* Connect the MySQL Classic Models database to a Mule app. 
* Construct a query to select a row in the Classic Models database based on customer number and the primary key.

In ObjectStore, you set up a persistent variable having a default value lower than the lowest primary key value in the Classic Models orders table. Using a greater-than conditional statement in the WHERE clause of the query, selected rows have a primary key value higher than the default value on the first iteration. 

. Create a new Mule Application project. In New Flow, click Trigger, select Scheduler, and set the following properties in Scheduler:
+
* Frequency: 15
* Time Unit: Seconds
* Accept other defaults and close Scheduler.
+
. Click + to add another component to the flow, select Object Store, select the Retrieve operation, and set the following properties in Object Store - Retrieve:
+
* In General, in Key type *lastOrder*.
* In Default Value, enter a number lower than lowest orderNumber value in the Classic Models database orders table. For example:
+
*10099*
+
* In Advanced, in Target Variable, type:
+
*lastOrder*
+
This sets a variable to the key-value pair.
+
* Close Object Store - Retrieve.
+
. Click + to add another component to the flow, select Database, select the Select operation, and connect a MySQL database to the flow (see See Also).
. Set the following properties in Database - Select.
+
* In SQL Query Text, type:
+
*SELECT * FROM ORDERS WHERE customerNumber = "353" and orderNumber > :lastOrder*
+
* In Input Parameters, add a parameter key:
+
*lastOrder*
+
* Add a value:
+
*variables.lastOrder.payload*

== See Also

* link:/connectors/db-connect-database-task[To Connect a Database (Design Center)]
