= To Schedule a Database Scan

In this procedure, you connect the popular MySQL Classic Models database to a Mule app. You retrieve order information from the orders table and insert it into another database. The procedure assumes you imported the database into a MySQL server. You can download the Classic Models database from the internet:

`+http://www.mysqltutorial.org/download/2+`

You also need a JDBC driver compatible with your database server. 

. Create a new Mule Application project. In New Flow, click Trigger, select Scheduler, and set the following properties in Scheduler:
+
* Frequency: 15
* Time Unit: Seconds
* Accept other defaults and close Scheduler.
+
. Click + to add another component to the flow, select Object Store, select the Retrieve operation, and set the following properties in Object Store - Retrieve:
+
* In General, in Key type *lastOrder*.
* In Default Value, type *10100*, which is the lowest orderNumber value in the Classic Models database orders table.
* In Advanced, in Target Variable, type *lastOrder* to create a variable set to the key-value pair.
* Close Object Store - Retrieve.
+
. Click + to add another component to the flow, select Database, select the Select operation, and connect a MySQL database using classicmodels as described (see See Also).
. Set the following properties in Database - Select.
* In SQL Query Text, type *SELECT * FROM ORDERS WHERE customerNumber = "353" and orderNumber > :lastOrder*.
* In Input Parameters, add a parameter key named *lastOrder* and a value *variables.lastOrder.payload*.

== See Also

* link:/connectors/db-connect-database-task[To Connect a Database (Design Center)]
