= To Bulk Insert Data from One Database to Another

In this procedure, you bulk insert data from the Classic Models database to another database. 

. Create a new MySQL database and table using the following commands:
+
----
CREATE DATABASE `neworders`;

USE `neworders`;

DROP TABLE IF EXISTS `orders`;

CREATE TABLE `orders` (
  `orderNumber` int(11) NOT NULL,
  `orderDate` date NOT NULL,
  `requiredDate` date NOT NULL,
  `shippedDate` date DEFAULT NULL,
  `status` varchar(15) NOT NULL,
  `comments` text,
  `customerNumber` int(11) NOT NULL,
  PRIMARY KEY (`orderNumber`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
----
+
. Click + next to If, select Database, and Select Bulk Insert.
. In Database - Bulk Insert, click Change, click Add, and in Database Configuration, set the following properties:
+
* Configuration Name: DatabaseToSync
* Connection Type: MySQL Connection
* Host: the URL of your MySQL host
* Port: 3306
* User: your MySQL user name
* Password: your MySQL password
* Database: neworders.
* In the banner at the top of the page, click Set Up to set up a driver.
* On Database Drivers, choose File, select, and upload a database driver from your file system. Alternatively, put your cursor in the File text box and pause. When options appear, select a driver, and click Done.
+
. Close the configuration and in Database - Bulk Insert, in General, enter the following SQL Query Text:
+
----
INSERT INTO orders(orderNumber, orderDate, requiredDate, shippedDate,status,comments,customerNumber) VALUES (:orderNumber, :orderDate, :requiredDate, :shippedDate, :status, :comments, :customerNumber)
----
. In Advanced, in Target Variable, type *syncResult* for use in the next object store.