= To Schedule a Database Scan

In this procedure, you do the following things:

* Set up a scheduler to update the database every 15 seconds.
* Store an default value in an ObjectStore component.

In ObjectStore, you set up a persistent variable having a default value lower than the lowest primary key value of the database rows you want to insert. 

. Create a new Mule Application project. In New Flow, click Trigger, select Scheduler, and set the following properties in Scheduler:
+
* Frequency: 15
* Time Unit: Seconds
* Accept other defaults and close Scheduler.
+
. Click + to add another component to the flow, select Object Store, select the Retrieve operation, and set the following properties in Object Store - Retrieve:
+
* In General, in Key type *lastOrder*.
* In Default Value, enter a number lower than lowest orderNumber value in the Classic Models database orders table. For example:
+
*10099*
+
* In Advanced, in Target Variable, type:
+
*lastOrder*
+
This sets a variable to the key-value pair.
+
* Close Object Store - Retrieve.


