= To Connect the Classic Models Database

This procedure assumes you already imported the Classic Models database into a MySQL server. You can download this database from the internet:

`+http://www.mysqltutorial.org/download/2+`

Import the database from the command line or using a tool, such as MySQL Workbench. You also need a JDBC driver compatible with the database. During configuration of the database connector, you upload, or refer to a previously uploaded, JDBC driver compatible with your database server. 

. Click + to add another component to the flow, and select Database. Choose an operation, for example, Select.
. At the top of Database - Select, click Set Up, and set the following options:
+
* In Connection, select the MySQL Connection type.
* In Host, enter the URL of the MySQL server host on the Internet.
* In Port, enter *3306*.
* User: Enter your MySQL server user name.
* Password: Enter your MySQL server password.
* Database: Enter *classicmodels*.
* In the banner at the top of the page, click Set Up to set up a driver.
* On Database Drivers, choose File, select, and upload a database driver from your file system. Alternatively, if you or someone in your organization already uploaded a driver for the database, put your cursor in the File text box and pause. When options appear, select a driver, and click Done.
. After completing the upload, test, and if successful, save the configuration.
+
. Set the following properties in Database - Select.
+
* In SQL Query Text, type:
+
*SELECT * FROM ORDERS WHERE customerNumber = "353" and orderNumber > :lastOrder*
+
* In Input Parameters, add a parameter key:
+
*lastOrder*
+
* Add a value:
+
*variables.lastOrder.payload*

