= About the Database Connector
:keywords: database migration, mysql, oracle, derby, jdbc, postgres, ms sql, relational

The database connector establishes communication between your app and a relational database. The connector facilitates setting up the following databases for use in a Mule app:

* Derby
* MySQL
* Oracle

The connector also supports the set up of these, and other JDBC databases, using a generic JDBC configuration. If you have a JDBC driver for a database, you can use the database connector to connect to that database.

== Using the Database Connector

The prerequisites for using the database connector are:

* Upload a JDBC driver for the database you plan to use during the configuration of the connector.
+
This process stores the connector in Exchange for reuse in other projects.
* Obtain the host name, port, and database user and password for connecting to a database on the same network as Design Center. 
+
Design Center on Anypoint Platform needs to connect to a database on the internet.

Before adding a database connector to a flow, you need to place a trigger, such as an HTTP listener component, in the flow. Prior to adding the trigger, the option to add a database connector is unavailable. 

Next, you add the database connector. From a list of database operations, which include Select, Insert, Update, and Delete, you choose the operation you plan to perform. Setup options for the operation appear. 

The Database Connector Technical Reference describes the setup options for each operation. Complete the setup, which includes uploading the database driver for the database type you choose. The driver you upload is added to Exchange and is available for reuse.

After configuring the database, you can test the connection from the app to the database if the app is running; otherwise, Test is unavailable. Save the database configuration, and check that Running appears in Design Center.

Finally, enter a SQL query. For example, enter a select statement if you set up a Select operation. Do not include a delimiter, for example a semicolon, at the end of the SQL statement. 

Typically, you add more logic to transform the results of the query into a readable form. Now, you can run the app and get the query results.

== Supported Operations

The database connector supports the following operations:

* Creating and running stored procedures
* Creating tables using the EXECUTE DDL operation
* Issuing select, insert, update, and delete queries
* Executing inline and file-based SQL scripts
* Performing bulk operations: delete, insert, update
* Operations, such as running DDL statements against the database, using a script



== See Also

* link:/connectors/db-connector-xml-reference[Database Connector XML Reference]
* link:/connectors/database-documentation[Database Connector Technical Reference]