= Database Connector Streaming Reference

Large database tables, typical in integration applications, have tens of thousands of records or more. Fetching all the data at once is problematic: performance degradation and memory problems occur. Mule 4.0 and later releases offer the following ways to solve these problems:

* Streaming incorporated into Mule 4.0 and later 
* Limiting the resultset

Streaming is transparent, always enabled, and repeatable. Streams can be processed in parallel.

You can limit the resultset as shown in the following example, which sets the fetchSize to limit the resultset.

[source,xml,linenums]
----
<db:select fetchSize="200" config-ref="dbConfig"> 
  <db:sql>select * from some_table</db:sql>
</db:select>
----

The following example shows a query over a table with many rows. The query yields a resultset limited to the first 1000. 

[source,xml,linenums]
----
<db:select maxRows="1000" config-ref="dbConfig">
   <db:sql>select * from some_table</db:sql>
</db:select>
----

== See Also

* Mule 4 Streaming mechanism documentation
* link:/connectors/database-documentation[Database Connector Technical Reference]
