= Database Connector XML Overview

The Database connector has a single configuration that accommodates child elements that define providers, as shown in the following examples:

* `<db:generic-connection url="jdbc:derby:muleEmbeddedDB;create=true" driverClassName="org.apache.derby.jdbc.EmbeddedDriver"/>`
* `<db:my-sql-connection  host="0.0.0.0" port="3306" user="Max" password="POWERS" database="someSchema"/>`
* `<db:derby-connection database="target/muleEmbeddedDB" create="true">`
* `<db:oracle-connection host="192.168.99.100" port="1521" instance="xe" user="system" password="oracle" />`

The Database Connector Technical Reference describes exclusive and common parameters for each provider. A child element of the provider element defines custom data types. For example:

[source,xml,linenums]
----
<db:config name="dbConfig">
   <db:derby-connection url="jdbc:derby:muleEmbeddedDB;create=true">
       <db:custom-data-types>
           <!-- Derby uses JAVA_OBJECT for UDT-->
           <db:custom-data-type typeName="CONTACT_DETAILS" id="2000"/>
       </db:custom-data-types>
   </db:derby-connection>
</db:config>
----

== Formatting the Output of a Query

The db:output-parameter converts the output of a query from binary to a JDBC or custom type, such as JSON. For example:

`<db:output-parameter paramName="myParam" type="VARCHAR"/>`

== Forcing Parameter types
 
Although uncommon, at some point you might need to force the underlying JDBC driver to coerce an input parameter to an specific type. For example, if your JDBC driver cannot determine the type of the input, or a parameter is of a custom type, you might need to apply force by specifing the type of each input parameter:

[source,xml,linenums]
----
<db:bulk-insert queryTimeout="0" queryTimeoutUnit="SECONDS">
     <db:sql>INSERT INTO PLANET(POSITION, NAME) VALUES (:position, :name)</db:sql>
     <db:parameter-types>
         <db:parameter-type key="name" type="VARCHAR" />
         <db:parameter-type key="position" type="INTEGER" />
     </db:parameter-types>
 </db:bulk-insert>
----

== See Also

* link:/connectors/database-documentation[Database Connector Technical Reference]
* link:/connectors/db-connector-sql-ops-ref[SQL Operations Reference]
* link:/design-center/v/1.0/to-manage-data-types[To Manage Data Types]
* link://mule-user-guide/v/4.0/dataweave-formats[Custom Types]
