= Database Connector

* Release Notes: link:/release-notes/connector-db-rns-home[Mule Runtime Database Connector Release Notes]

The Database connector establishes communication between your Mule app and a relational database. In Studio, you need to add the Database connector as described in link:common-add-module-task[To Add a Connector to Studio]. After adding the connector to Studio, the connector and its operations appear in the Mule Palette.
//TODO? WHAT ABOUT DESIGN CENTER/FLOW DESIGNER?

The Database connector provides configurations for communicating with these databases through a Mule app:

* Derby
* MySQL
* Oracle
* Microsoft SQL Server

You can set up other JDBC databases using a generic JDBC configuration. You can also reference a JDBC `DataSource` object or a `XADataSource` object, which is required for XA transactions. You typically create the object in Studio using Spring.

== What's New in the Database Connector
// TODO? NEW RELATIVE TO WHAT? 3.X? THIS SORT OF INFO IS USUALLY IN A NEW FEATURES SECTION OF THE RELEASE NOTES, NOT IN THE MAIN DOCS. INSTEAD, AN OVERVIEW LIKE THIS WOULD TYPICALLY DESCRIBE THE MAIN FEATURES OF THE CONNECTOR. THIS WILL NOT BE NEW ANYMORE ONCE THE NEXT VERSION OF THE CONNECTOR IS OUT.

* Improved operations: Operations are streamlined and now simpler to use. MuleSoft extracted bulk functionality to its own set of operations so that operations no longer that change behaviors depending on the payload they receive.
* Dynamic queries simplified: There is a single experience for executing static and dynamic queries.
* Embeddable transformations: You can embed DataWeave transformations inside the Insert and Update operations to construct the data sets that you want to send to the database without a side effect on the message or the need to use enrichers.
* Streaming simplified: You no longer need to configure streaming on your operations. The connector uses Mule’s streaming framework to handle that automatically. You can even execute a Select statement and process the results asynchronously without worrying about leaking connections.

== See Also

// * link:[Mule 4 streaming]

* link:db-configure-connection[Configuring connections to a Database]
* link:db-connector-query[Querying data from a Database]
* link:db-connector-insert-update-delete[Inserting, Updating and Deleting data in a Database]
* link:db-connector-transactions-ref[Using Transactions in a Database]
* link:db-connector-execute-script-ref[Executing Database scripts]
* link:db-connector-datatypes-ref[Using Database custom types]
* link:db-connector-ddl[Creating tables, triggers, procedures and other schema objects in a Database]
* link:database-documentation[Database connector Technical Reference]
* link:/mule-user-guide/v/4.0/migration-connectors-database[Migrating the Database Connector]
