= About Preventing SQL Injection

In some cases, it's tempting to use expressions in a database query to construct a query dynamically from user input the app receives over HTTP protocol. For example, you might want to issue queries of online, historic tables depending on a condition. You might have complex queries in which the project columns need to vary. The database connector supports using expressions in any part of the query, but doing so is not recommended. Using the colon-parameter name syntax `:param` to a define a dynamic value parameter, such as the parameter in a WHERE clause, is recommended. 

For example, the following code shows how to use the colon-parameter syntax in the WHERE clause:

[source,xml,linenums]
----
   <set-variable variableName="table" value="PLANET"/>
   <db:select config-ref="dbConfig">
       <db:sql>#["SELECT * FROM $(table) WHERE colA = :colvalue”]</db:sql>
       <db:input-parameters>
           #[{'colvalue' : payload}]
       </db:input-parameters>
   </db:select>
----

This example also shows a variable table name in the FROM clause varies. The database connector supports the `:param` syntax in the WHERE clause of this example, but not in the FROM clause. You cannot use the syntax to reference structures, such as a table. For example, do not use expressions, such as `attributes.queryParams.table` in the FROM clause to reference a table structure.

To safely vary the `table`, the app needs to get the table names from a safe data source, such as a pre-constructed file of possible table names the user can select. 

== See Also

* link:/connectors/db-dynamic-query-task[To Query Data Dynamically]
* link:/connectors/db-filter-query-task[To Filter Data Using an Input Parameter]
* link:/connectors/database-documentation[Database Connector Technical Reference]
