= Database Connector XML Reference

The Database connector has a single configuration that accommodates child elements that define providers, as shown in the following examples:

* `<db:generic-connection url="jdbc:derby:muleEmbeddedDB;create=true" driverClassName="org.apache.derby.jdbc.EmbeddedDriver"/>`
* `<db:my-sql-connection  host="0.0.0.0" port="3306" user="Max" password="POWERS" database="someSchema"/>`
* `<db:derby-connection database="target/muleEmbeddedDB" create="true">`
* `<db:oracle-connection host="192.168.99.100" port="1521" instance="xe" user="system" password="oracle" />`

The Database Connector Technical Reference describes exclusive and common parameters for each provider. A child element of the provider element defines custom data types. For example:

[source,xml,linenums]
----
<db:config name="dbConfig">
   <db:derby-connection url="jdbc:derby:muleEmbeddedDB;create=true">
       <db:custom-data-types>
           <!-- Derby uses JAVA_OBJECT for UDT-->
           <db:custom-data-type typeName="CONTACT_DETAILS" id="2000"/>
       </db:custom-data-types>
   </db:derby-connection>
</db:config>
----

== Operations

The database connector supports the following SQL queries:

* Select
* Insert
* Update
* Delete

=== Select Operation

The Select operation returns one of the following types, depending on streaming:

* List of Map<String, Object> (no streaming)
* Iterator

If the results are streamed, the connection and its underlying resources are not released until the returned stream is fully consumed or the flow ends.

The following examples shows the syntax of a select operation:

[source,xml,linenums]
----
<db:select maxRows="2">
  <db:sql>SELECT * FROM planet ORDER BY Id</db:sql>
</db:select>
----

=== Insert Operation

You supply parameters as key value pairs to insert data into the database. This operation supports dynamic queries. Do _not_ use dynamic queries to actually assign parameter values, as described in the Select Operation, to avoid exposure to SQL injection.
 
The Insert operation returns an StatementResult, an object that communicates the result of a statement that doesn’t have a projection.

The following example shows the syntax of an insert operation:

[source,xml,linenums]
----
<db:insert config-ref="dbConfig">
  <db:sql>
      INSERT INTO PLANET(POSITION, NAME, DESCRIPTION) VALUES (777, 'Pluto', :description)
  </db:sql>
   <db:input-parameters>
       #[
           {'description' : payload}
       ]
   </db:input-parameters>
</db:insert>

----

=== Update Operation

You supply parameters as key value pairs to update data in the database. This operation supports dynamic queries. Do _not_ use dynamic queries to actually assign parameter values, as described in the Select Operation, to avoid exposure to SQL injection. The Update operation returns an StatementResult, an object that communicates the result of a statement that doesn’t have a projection. The following example shows the syntax of an update operation:

[source,xml,linenums]
----
<db:update config-ref="dbConfig">
  <db:sql>
      UPDATE PLANET SET DESCRIPTION = :description where POSITION = :position
  </db:sql>
   <db:input-parameters>
       #[
           {'description' : payload,
     'position' : 7,
    }
       ]
   </db:input-parameters>
</db:update>
----

=== Delete Operation

You supply parameters as key value pairs to delete data from the database. This operation supports dynamic queries. Do _not_ use dynamic queries to actually assign parameter values, as described in the Select Operation, to avoid exposure to SQL injection. 

The following example shows the Delete operation:

[source,xml,linenums]
----
<db:delete config-ref="dbConfig">
  <db:sql>
      DELETE FROM PLANET where POSITION = :position
  </db:sql>
   <db:input-parameters>
       #[
           {'position' : 7}
       ]
   </db:input-parameters>
</db:insert>
----

This operation returns the number of affected rows. You can use $(affected), a target parameter which all operations have, to log the result of the query:

`<logger message="#['Deleted a total of $(affected) planets at position $(payload.id)']" />`

////
=== Hybrid Queries

You can mix dynamic and parametrized queries. For example:

[source,xml,linenums]
----
<flow name="selectHybridQuery">
  <set-variable variableName="tableName" value="PLANET"/>
  <db:select>
    <db:sql>SELECT * FROM #[tableName] WHERE Name = :name</db:sql>
      <db:input-parameters>
        <db:input-parameter key="name" value="#[payload]"/>
      </db:input-parameters>
  </db:select>
</flow>
----


Do _not_ swap the position of the dynamic and parametrized query because the dynamic `#[tableName]` construct misplaced in the WHERE clause makes the code vulnerable to SQL injection. 
////

=== Parametrized Queries

Queries can include parameters.  Parametrized queries are parameters you reference and set by name. You can use a colon (:) to reference a parameter by name. To include parameters in queries, use parametrized queries instead of dynamic queries for the following reasons:

* Immunity from SQL injection attacks
* Performance

You can use input parameters only in a WHERE clause. For example, use the colon syntax in a parametrized query as follows:

[source,xml,linenums]
----
<flow name="selectParameterizedQuery">
   <db:select config-ref="dbConfig">
       <db:sql>select * from PLANET where name = :name</db:sql>
       <db:input-parameters>
           #[{'name' : payload}]
       </db:input-parameters>
   </db:select>
</flow>
----

This operation uses DataWeave to supply the parameters.


=== Stored Procedures

This operation accepts input, output, and input-output parameters. 

*Input Parameters Example*

[source,xml,linenums]
----
<db:stored-procedure config-ref="dbConfig">
   <db:sql>call updatePlanetDescription('Venus', :description)</db:sql>
   <db:parameter-types>
       <db:parameter-type key="description" type="CLOB" />
   </db:parameter-types>
   <db:input-parameters>
       #[{'description' : payload}]
   </db:input-parameters>
</db:stored-procedure>
----

*Output Parameters Example*

[source,xml,linenums]
----
<db:stored-procedure config-ref="dbConfig">
   <db:sql>{ CALL countTestRecords(:count) }</db:sql>
   <db:output-parameters>
       <db:output-parameter key="count"/>
   </db:output-parameters>
</db:stored-procedure>
----

*Input-output Parameters*

[source,xml,linenums]
----
<db:stored-procedure config-ref="dbConfig">
   <db:sql>{ call doubleMyInt(:myInt) }</db:sql>
   <db:in-out-parameters>
       <db:in-out-parameter key="myInt" value="3"/>
   </db:in-out-parameters>
</db:stored-procedure>
----

DataSense is not supported when you work with stored procedures because the return value is unpredictable.

////
You can reuse a stored procedure as shown in the following example:

[source,xml,linenums]
----
<db:stored-procedure name=”split” streaming="true">
   <db:sql>{ call getSplitTestRecords() }</db:sql>
</db:stored-procedure>

<flow name="getResultSet">
   <db:stored-procedure template=”split” />
</flow>
----
////

=== Execute DDL

This operation supports any DDL statement you can run on the database connected to Mule. For example, you can create, alter, or drop a table using this operation. For example:

[source,xml,linenums]
----
<db:execute-ddl config-ref="dbConfig" queryTimeout="10" queryTimeoutUnit="SECONDS">
   <db:sql>
       create TABLE patients (
           PATIENT_ID integer NOT NULL UNIQUE,
           FIRST_NAME varchar(255),
           LAST_NAME varchar(800),
           PHONE varchar(20),
           DATE_OF_BIRTH varchar(20),
           GENDER varchar(1))
   </db:sql>
</db:execute-ddl>
----

== Formatting the Output of a Query

The db:output-parameter converts the output of a query from binary to a JDBC or custom type, such as JSON. For example:

`<db:output-parameter paramName="myParam" type="VARCHAR"/>`

== Forcing Parameter types
 
Although uncommon, at some point you might need to force the underlying JDBC driver to coerce an input parameter to an specific type. For example, if your JDBC driver cannot determine the type of the input, or a parameter is of a custom type, you might need to apply force by specifing the type of each input parameter:

[source,xml,linenums]
----
<db:bulk-insert queryTimeout="0" queryTimeoutUnit="SECONDS">
     <db:sql>INSERT INTO PLANET(POSITION, NAME) VALUES (:position, :name)</db:sql>
     <db:parameter-types>
         <db:parameter-type key="name" type="VARCHAR" />
         <db:parameter-type key="position" type="INTEGER" />
     </db:parameter-types>
 </db:bulk-insert>
----

== See Also

link:/connectors/database-documentation[Database Connector Technical Reference]