= About Preventing SQL Injection

Improper use of expressions in a database query can lead to SQL injection. Follow best practices to construct a query dynamically from user input the app receives over HTTP protocol. Avoid constructing parts of the query involving a structure, such as table, directly from user input. Use the colon-parameter syntax to construct parts of the query involving values, such as the conclusion of a WHERE clause. 

For example, you might want to run the same query on different historic tables depending on a condition or filter the query to select certain values. The database connector supports using expressions in any part of the query, but do so following best practices. 

== Best Practices for Handling Dynamic Queries

* Use the colon-parameter name syntax `:param` to a define a dynamic value parameter, such as the parameter in a WHERE clause. 
* To safely vary a database structure, such as a table:
+
** The app needs to get the table names from a safe data source, such as a pre-constructed file of possible table names the user can select. 
** Construct the SQL Query Text by referencing the variable.

For example, the following code shows how to use the colon-parameter syntax in the WHERE clause:

[source,xml,linenums]
----
   <set-variable variableName="table" value="PLANET"/>
   <db:select config-ref="dbConfig">
       <db:sql>#["SELECT * FROM $(table) WHERE colA = :colvalue”]</db:sql>
       <db:input-parameters>
           #[{'colvalue' : payload}]
       </db:input-parameters>
   </db:select>
----

This example also shows a variable table name in the FROM clause varies. The database connector supports the `:param` syntax in the WHERE clause of this example, but not in the FROM clause. You cannot use the syntax to reference structures, such as a table. For example, do not use expressions, such as `attributes.queryParams.table` in the FROM clause to reference a table structure.

== See Also

* link:/connectors/db-dynamic-query-task[To Query Data Dynamically]
* link:/connectors/db-filter-query-task[To Filter Data Using an Input Parameter]
* link:/connectors/database-documentation[Database Connector Technical Reference]
