= To Connect a Database (Design Center)

In this procedure, you connect the popular MySQL Classic Models database to a Mule app. The procedure assumes you imported the database into a MySQL server. You can download this database from the internet:

`+http://www.mysqltutorial.org/download/2+`

You also need a JDBC driver compatible with the database you want to set up. 

. Create a new Mule Application project. In New Flow, in Trigger, select the HTTP Listener.
. In General, set Path to the path of the URL you plan to use to start the app from the browser. For example, set Path to */trigger*.
. Accept or change the existing CloudHub HTTP configuration. For example, accept the default CloudHub HTTP configuration:
+
* Protocol: HTTP
* Host: *0.0.0.0*
* Port: 8081
+
. Click + to add another connector operation to the flow, and select Database. Choose an operation, for example, Select.
. At the top of Database - Select, click Set Up, and set the following options:
+
* Configuration Name: Optionally, change the name from the default Database to Classic Models Database.
* In Connection, select the Type: MySQL Connection.
+
Other fields to fill in appear.
+
* In Host, enter the URL of the MySQL server host on the Internet.
* In Port, enter *3306*.
* User: Enter your MySQL server user name.
* Password: Enter your MySQL server password.
* Database: Enter *classicmodels*.
* In the banner at the top of the page telling you to set up a driver, click Set Up.
* On Database Drivers, click Upload, and choose a database driver from your file system. Alternatively, if you, or someone in your organization, already uploaded a driver for the database, do the following:
+
** Put your cursor in the text box and pause.
** When the list of options appears, scroll to and select a driver.
+
. After completing the upload, test and save the configuration.
+
You are ready to set up the SQL Query Text to complete the database connector configuration.

== See Also

* link:/connectors/db-query-db-task[To Query a Database]
* link:/connectors/http-trigger-app-from-browser[To Start an App from a Browser]
* link:/connectors/database-documentation[Database Connector Technical Reference]
* link:/connectors/db-connector-mysql-concept[About Connecting to a MySQL Database]
* link:/connectors/db-connector-oracle-concept[About Connecting to an Oracle Database]
* link:/connectors/db-connector-generic-concept[About Connecting to a Generic Database]


