= To Insert Data in Bulk

This procedure builds on the example that connects a Mule app to a database using the Classic Models sample database. 

. Create a new project and a new flow. Add an HTTP connector.
. In HTTP-Listener, in Path, enter */bulkinsert* and in Allowed Methods, enter *POST,GET*. Accept other default settings.
. Click + to add a Transform component to the flow. In Source, enter the following DataWeave code:
+
----
%dw 1.0
%output application/java  

---
[
  {
    "pline": "Electric Cars",
    "tdesc": "Speedy but silent driving."
  }, 
  {
    "pline": "Self-Driving Cars",
    "tdesc": "Text in safety."
  }
]
----
+
. Click + to add a Database connector, and select the Bulk Insert operation.
. Configure the database as follows:
+
* In Type, select MySQL Connection.
* In Host, enter the URL of a database on the internet.
* In Port, enter the port that the database listens on. For example, enter *3306*.
* In User and Password, enter the database user name and password.
* In Database, enter *classicmodels*.
. Configure the database driver, selecting or uploading a JDBC driver. Test and save the configuration.
. In SQL Query Text, enter the following query:
+
----
INSERT INTO productlines(productLine, textDescription) VALUES (:pline, :tdesc)
----
+
. Sync and copy the CloudHub link for your app. In an HTTP client, such as Postman, set up the following request:
+
* Select POST.
* Paste the CloudHub link in the address text box.
* Select Body > Raw and select JSON (application/json).
* Paste the following JSON code in the Body:
----
[{
	"pline": "Electric Cars",
	"tdesc": "Speedy but silent driving."
}, {
	"pline": "Self-Driving Cars",
	"tdesc": "Text in safety."
}]
----
. Click Send.
+
Status 200 appears in the client and querying the database shows the new product line rows.