= To Connect a Database

This procedure, and others in this documentation, connect the popular MySQL Classic Models database to a Mule app. The procedure assumes you imported the database into a MySQL server. You can download this database from the internet:

`+http://www.mysqltutorial.org/download/2+`

You also might need to download a JDBC driver, compatible with the database you want to set up, to your hard drive. For example, download a MySQL database driver. During the configuration of the database connector, you upload the driver to Exchange where it becomes available for reuse in other projects.

. Create a new project. In New Flow, in Trigger, select the HTTP Listener.
. In a Connector configuration, accept or change the existing CloudHub HTTP configuration. For example, accept the default CloudHub HTTP configuration:
+
* Protocol: HTTP
* Host: *0.0.0.0*
* Port: 8081
+
. In General, set Path to the path of the URL you plan to use to start the app from the browser. For example, set Path to */trigger*.
. Click + to add another connector to the flow, and select Database. Choose an operation, for example, Select.
. At the top of Database Select, click Set Up, and set the following options:
+
* Configuration Name: Optionally, change the name from the default Database to Classic Models Database.
* In Connection, select the Type: MySQL Connection.
+
Other fields to fill in appear.
+
* In Host, enter the URL of the MySQL server host on the Internet.
* In Port, enter *3306*.
* User: Enter your MySQL server user name.
* Password: Enter your MySQL server password.
* Database: Enter *classicmodels*.
* In the banner at the top of the page tellin you to set up a driver, click Set Up.
* On Database Drivers, if you, or someone in your organization, already uploaded a driver for the database, look for and select it; otherwise, click Upload and choose a database driver for MySQL stored on your file system. 
+
To look for a connector, put the cursor in the text box, pause, and when the list of connectors appears, scroll to and select your connector.
+ 
* Click Upload again, and then Done.
+
. Test the connection, and if successful, save.

== See Also

* link:/connectors/http-trigger-app-from-browser[To Start an App from a Browser]
* link:/connectors/database-documentation[Database Connector Technical Reference]
* link:/connectors/db-connector-mysql-concept[About Connecting to a MySQL Database]
* link:/connectors/db-connector-oracle-concept[About Connecting to an Oracle Database]
* link:/connectors/db-connector-generic-concept[About Connecting to a Generic Database]


