= Dynamic Query Reference

The database connector supports dynamic queries, which substitute an expression for a database object name. For example, you might want to parameterize the WHERE clause and also parts of the query itself. For example, you might want to issue queries of online, historic tables depending on a condition. You might have complex queries in which the project columns need to vary. In these cases, use expressions in the query:
 
[source,xml,linenums]
----
   <set-variable variableName="table" value="PLANET"/>
   <db:select config-ref="dbConfig">
       <db:sql>#["SELECT * FROM $(table) WHERE name = :name”]</db:sql>
       <db:input-parameters>
           #[{'name' : payload}]
       </db:input-parameters>
   </db:select>
----
 
In this example, a full expression builds the query using a variable `table`. Although the query text is dynamic, it still uses an input parameter name = :name. This is ok.

Do _not_ use expressions to define parameters. Doing so makes the code vulnerable to SQL injection. For example, do not use name = `$(payload)`, or other expressions, in the WHERE clause. Use only input parameters and the colon syntax, such as `name = :name`, in the WHERE clause.  To modify other parts of a query, use DataWeave expressions.

== See Also

link:/connectors/db-dynamic-query-task[To Query Data Dynamically]
link:/connectors/db-filter-query-task[Issuing a parametrized query]
