= What's New in the Database Connector

If you are a Mule 3.x user, the Mule 4 database connector, which connects your app to relational databases, has a familiar UI. The new version includes these improvements:

* Easier to use operations 
+
For example, bulk insert, update, and delete are now separate operations. A bulk operation behavior no longer depends on the received payload.
+
* Simplified dynamic queries
+
You perform dynamic queries basically the same way as static queries.
+
* Insert and update operations using DataWeave transformations
+
You can construct the datasets that insert or update the database without message side effects. You no longer use message enrichers.
+
* Simplified streaming
+
The new Mule streaming framework is automatically configured for your operations. You can execute a select statement and process the results asynchronously without worrying about leaking connections.

== See Also

* link:[Mule 4 streaming]
* link:/connectors/db-connector-bulk-insert-task[To Insert Data in Bulk]
* link:/connectors/db-connector-bulk-ops-ref[Bulk Operations Reference]
* link:/connectors/db-dynamic-query-task[To Query Data Dynamically]
* link:/connectors/db-connector-dynamic-query-ref[Dynamic Query Reference]
* link:/connectors/db-connector-streaming-ref[Database Connector Steaming Reference]

