= To Insert Data in Bulk

This procedure shows how to insert multiple data objects into a database using a single SQL statement. The procedure builds on the example that connects a Mule app to a database using the MySQL Classic Models sample database. You create JSON objects to represent the new product line data you want to insert: 

* Electric Cars
* Self-Driving Cars 

After insertion into the Classic Models database, these product line names serve as primary keys in the productLines table. You post the JSON objects from the client, such as Postman, to the Mule app. In the Mule app, you configure the bulk insert operation of the database connector. SQL statement parameters match the names of keys in the JSON objects. A transform component between the HTTP listener and the database connector converts the JSON objects to a Java.util.HashMap that the database connector can parse.  

. Create a new project and in the new flow, add an HTTP Listener connector.
. In Path, enter */bulkinsert* and in Allowed Methods, enter *POST,GET*. Accept other default settings.
. Add a Transform component to the flow. In Source, enter DataWeave code based on the JSON objects and specify Java output as follows:
+
----
%dw 2.0
output application/java  

---
[
  {
    "pline": "Electric Cars",
    "tdesc": "Speedy but silent driving."
  }, 
  {
    "pline": "Self-Driving Cars",
    "tdesc": "Text in safety."
  }
]
----
+
. Add a Database connector, and select the Bulk Insert operation.
. Configure the database as follows:
+
* In Type, select MySQL Connection.
* In Host, enter the URL of a database on the Internet.
* In Port, enter the port that the database listens on. For example, enter *3306*.
* In User and Password, enter the database user name and password.
* In Database, enter *classicmodels*.
. Configure the database driver. Select or upload a JDBC driver. 
. Test and save the database configuration. In SQL Query Text, enter the following query using the colon syntax to specify the values for bulk insertion:
+
----
INSERT INTO productlines(productLine, textDescription) VALUES (:pline, :tdesc)
----
+
. Sync the app. Copy the CloudHub link for your app. In an HTTP client, such as Postman, set up the request for the bulk insertion of the JSON objects:
+
* Select POST.
* Paste the CloudHub link plus the HTTP path you configured in the address text box. For example: `myapp.cloudhub.io/bulkinsert`.
* Select Body > Raw. Select the JSON (application/json) mime type.
* Paste the following JSON code in Body:
+
----
[{
	"pline": "Electric Cars",
	"tdesc": "Speedy but silent driving."
}, {
	"pline": "Self-Driving Cars",
	"tdesc": "Text in safety."
}]
----
+
. Click Send.
+
Status 200 appears in the client. The database contains two new rows.

== See Also

* link:/connectors/db-connect-database[To Connect a Database]
* link:/connectors/db-connector-bulk-ops-ref[Bulk Operations Reference]
* link:http://www.mysqltutorial.org/download/2[Classic Models database download]