= To Connect a Database (Studio)

In this procedure, you connect the popular MySQL Classic Models database to a Mule app. The procedure assumes you imported the database into a MySQL server. You can download this database from the internet:

`+http://www.mysqltutorial.org/download/2+`

You also need a JDBC driver compatible with the database you want to set up. 

. Create a new Mule Application project. From Mule Palette, drag an HTTP Listener operation to a new flow.
+
. Configure the listener:
+
* Click + and set the default host, port and base path. For example, host = 0.0.0.0, port = 8081, and no base path.
+
* In General, set Path to the URL you plan to use to start the app from the browser. For example, set Path to /trigger.
* Accept the other default listener settings, and save the configuration.
. From Mule Palette, drag a Database Select operation to the flow, and click +.
. In Database Config > Connection, select MySQL Connection.
. In MySQL JDBC Driver, if you haven't already set up a MySQL JDBC driver for reuse, click Add Dependency, search the Maven repository for a MySQL driver that matches your database, and select it. 
+
Alternatively, manually configure the Maven information for the driver.
+
----
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>5.1.6</version>
</dependency>
----
+
. Fill in other fields:
+
* In Host, enter the URL of the MySQL server host. For example, enter *localhost*.
* In Port, enter *3306*.
* User: Enter your MySQL server user name.
* Password: Enter your MySQL server password.
* Database: Enter *classicmodels*.
+
You are ready to set up the SQL Query Text to complete the configuration.

== See Also

* link:/connectors/db-query-db-task[To Query a Database]
* link:/connectors/http-trigger-app-from-browser[To Start an App from a Browser]
* link:/connectors/database-documentation[Database Connector Technical Reference]
* link:/connectors/db-connector-mysql-concept[About Connecting to a MySQL Database]
* link:/connectors/db-connector-oracle-concept[About Connecting to an Oracle Database]
* link:/connectors/db-connector-generic-concept[About Connecting to a Generic Database]


