= About Connecting to an Oracle Database 

To configure a connection to an Oracle database, you select the Oracle connection type and provide access to an Oracle JDBC driver and the database. 

* In Design Center, click Set Up > Upload, browse for and select the driver on your file system, and then upload it. 
+
Alternatively, search for and select a driver that is already uploaded.
+
* In Studio, add a Maven dependency on the Oracle JDBC driver.
+
For example, in Database Config, click Add Dependency, search the Maven repository for an Oracle driver that is compatible with your database, and select it. When you select an Oracle driver, the connector captures the Maven information for it. Alternatively, you can manually configure the Maven information for the driver.

To configure the database, you provide the following additional information:

* Host: The host portion of the URL in the connection string. In Design Center, the host needs to be a location on the internet.
* Port: The default is 1521.
* User: The name of the user that is set up for authentication against the database.
* Password: The password that is set up for authentication against the database.
* Instance: The name of the Oracle DB instance you want to connect to the app.

The following example shows the XML configuration for the Oracle connection:

[source,xml,linenums]
----
<db:config name="dbConfig">
  <db:oracleconnection host="192.168.99.100" port="1521" instance="xe" user="system" password="oracle" />
</db :config >
----

== See Also

* link:/connectors/database-documentation[Database Connector Technical Reference]
* link:/connectors/db-connect-database-task[To Connect a Database]


