= Database Connector Overview
:keywords: db, connector, Database
:toc:
:toc-title:

The database connector establishes communication between your app and a relational database. You need to add the database connector to Studio as described in "Add a Connector to Studio." After adding the connector to Studio, the connector and its operations appear in the Mule Palette.

The database connector facilitates setting up the following databases for use in a Mule app:

* Derby
* MySQL
* Oracle
* Microsoft SQL Server

You can set up other JDBC databases using a generic JDBC configuration. You can also reference a JDBC DataSource object, or XADataSource object which is required for XA transactions. You typically create the object in Studio using Spring.

== What's New in the Database Connector

* Improved operations: Operations are streamlined and now simpler to use. We’ve extracted bulk functionality to their own set of operations so that you no longer have operations that change behaviors depending on the received payload
* Dynamic queries simplified: Now there’s a single experience for executing static and dynamic queries.
* Embeddable transformations: you can now embed DataWeave transformations inside the insert/update operations so that you can construct the datasets you want to send to the DB without having a side effect on the message or using enrichers
* Streaming simplified: you no longer have to worry about configuring streaming on your operations. The connector will use Mule’s new streaming framework to handle that automatically. You can now even execute a select statement and process the results asynchronously without worrying about leaking connections!

== See Also

// * link:[Mule 4 streaming]

* link:db-configure-connection[Configuring connections to a Database]
* link:db-connector-query[Querying data from a Database]
* link:db-connector-insert-update-delete[Inserting, Updating and Deleting data in a Database]
* link:db-connector-transactions-ref[Using Transactions in a Database]
* link:db-connector-execute-script-ref[Executing Database scripts]
* link:db-connector-datatypes-ref[Using Database custom types]
* link:db-connector-ddl[Creating tables, triggers, procedures and other schema objects in a Database]
* link:database-documentation[Database connector Technical Reference]
* link:/mule-user-guide/v/4.0/migration-connectors-database[Migrating the Database Connector]
