== To Connect to a Generic Database

You can use the generic database connector with any database engine for which you have a driver. In this procedure you connect to a Postgresql database.

. Start the database and create a table. For example, create a table named testdb.
. In Studio, create a new project. Include a postgresql shared library in the mule maven plugin and postgresql as a dependency in your pom.xml file.
+
[source,xml,linenums]
----
<plugins>
    <plugin>
        <groupId>org.mule.tools.maven</groupId>
        <artifactId>mule-maven-plugin</artifactId>
        <version>${mule.maven.plugin.version}</version>
        <extensions>true</extensions>
        <configuration>
                <sharedLibraries>
                    <sharedLibrary>
                    <groupId>postgresql</groupId>
                    <artifactId>postgresql</artifactId>
                    </sharedLibrary>
            </sharedLibraries>
         </configuration>
    </plugin>
</plugins>
...
<dependencies>
...
    <dependency>
        <groupId>postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>9.4.1208-jdbc42-atlassian-hosted</version>
    </dependency>
</dependencies>
----
+
. Set up an HTTP Listener or other trigger.
. Drag a generic database operation, such as Select, to the flow.
. In Extension Configuration, click +. In Database Config, in Connection, type the URL. For example:
+
`+jdbc:postgresql://localhost:5432/testdb+`
+
. In Driver Class Name, type the name of the driver class. For example:
+
*org.postgresql.Driver*
. Click Test Connection, and if successful, OK.
+
Now, you can set up the query in SQL Query Text.

