= To Execute a Script

This procedure builds on the example that connects a Mule app to a database using the Classic Models sample database. In this procedure, you use the execute script operation of the database connector to execute a script that inserts two rows into the database. You then add another database connector to check that the table contains the new rows.

. In Design Center, create a new project and select a trigger, for example, select HTTP, and accept or change the listener configuration. For example, accept the default CloudHub HTTP configuration, which is host name = 0.0.0.0 and port = 8081.
. In General, set Path to the path of the HTTP URL, for example, set Path to `/`, and accept the other default listener settings. Close the connector.
. Add a database connector to the flow, and set up a classicmodels database for an Execute DDL operation.
. In Execute - Script, enter the SQL query text, ending with a semicolon, or a path to the script. For example, enter the following queries as text:
+
----
insert into productlines(productLine, textDescription) VALUES ("Electric Cars", "Sweet speedy-but-silent driving experience only available from battery-to-motor power, these plug-in model rebates save you big bucks.");

insert into productlines(productLine, textDescription) VALUES ("Self-Driving Cars", "Sit back and relax, work on your presentation to customers or safely text as you are transported by this robotic chauffeur.");
----
+
. In Design Center, click Run or Sync. Fire the app trigger:
+
* Select Running > Copy Link.
+
* Paste the link in a browser or client.

///
. Click + and add another database connector, choose the Select operation, and accept the default configuration to reuse the configuration of the last connector.

. TBD (Connector view output still in design)

///