= To Alter, Create, or Drop a Table

In this procedure, you use the DDL Execute operation of the database connector to execute an ALTER, CREATE, or DROP operation. This procedure builds on the example that connects a Mule app to a database using the Classic Models sample database. 

. Create a new project, a new flow, and add an HTTP connector to the flow. Accept the default or change the listener configuration. For example, accept the default configuration, which is host name = 0.0.0.0 and port = 8081.
. In General, set Path to the path of the HTTP URL, for example, set Path to `/`, and accept the other default listener settings. Close the connector.
. Add a database connector to the flow, and set up a classicmodels database for an Execute DDL operation.
. In Execute - DDL, enter the SQL query text to alter, create, or drop a table. For example, create a table named testddl having one column called name.
+
`CREATE TABLE testddl7 (name VARCHAR(255))`
+
. Click Run or Sync. Fire the app trigger:
+
* Select Running > Copy Link.
+
* Paste the link in a browser or client.
+
The HTTP listener hears the request, starts the app, and a file, which you can delete, containing the binary query results is downloaded from the browser to your localhost. 
. In the database connector Output, the query results appear.