= To Execute a Script (Design Center)

In this procedure, you use the execute script operation of the database connector to execute a script that inserts two rows into the database. You then add another database operation to check that the table contains the new rows. This procedure builds on the example that connects a Mule app to a database using the Classic Models sample database. 

. Create a new project and in the new flow. In a Connector configuration, accept an existing configuration or add one as follows:
+
* Protocol: Select HTTP.
* Host: *0.0.0.0*
* Port: 8081
+
. In General, set Path to the path of the HTTP URL, for example, set Path to */*, and accept the other default Listener settings. Close the configuration.
. Add an Execute DDL operation to the flow, and set up a classicmodels database.
. In Execute - Script, enter the SQL query text, ending with a semicolon, or a path to the script. For example, enter the following queries as text:
+
----
insert into productlines(productLine, textDescription) VALUES ("Electric Cars", "Speedy-but-silent driving experience only available from battery-to-motor power.");

insert into productlines(productLine, textDescription) VALUES ("Self-Driving Cars", "Sit back and relax, safely text.");
----
+
. Click Deploy, and the execute the flow:
+
* Select Copy Link.
+
* Paste the link in a browser or client.
+
The query results appear in Output.

== See Also

* link:/connectors/db-connect-database-task[To Connect a Database]
* link:/connectors/db-connector-execute-script-ref[Execute Script Reference]
* link:http://www.mysqltutorial.org/download/2[Classic Models database download]