= To Execute a Script

In this procedure, you use the execute script operation of the database connector to execute a script that inserts two rows into the database. You then add another database connector to check that the table contains the new rows. This procedure builds on the example that connects a Mule app to a database using the Classic Models sample database. 

. Create a new project and in the new flow. In a Connector configuration, accept an existing configuration or add one as follows:
+
* Protocol: Select HTTP.
* Host: *0.0.0.0*
* Port: 8081
+
. In General, set Path to the path of the HTTP URL, for example, set Path to */*, and accept the other default listener settings. Close the connector.
. Add a database connector to the flow, and set up a classicmodels database for an Execute DDL operation.
. In Execute - Script, enter the SQL query text, ending with a semicolon, or a path to the script. For example, enter the following queries as text:
+
----
insert into productlines(productLine, textDescription) VALUES ("Electric Cars", "Sweet speedy-but-silent driving experience only available from battery-to-motor power, these plug-in model rebates save you big bucks.");

insert into productlines(productLine, textDescription) VALUES ("Self-Driving Cars", "Sit back and relax, work on your presentation to customers or safely text as you are transported by this robotic chauffeur.");
----
+
. Click Run or Sync. Fire the app trigger:
+
* Select Running > Copy Link.
+
* Paste the link in a browser or client.
+
The query results appear in database connector Output.

== See Also

* link:/connectors/db-connect-database[To Connect a Database]
* link:http://www.mysqltutorial.org/download/2[Classic Models database download]