= To Alter, Create, or Drop a Table (Design Center)

In this procedure, you use the Execute DDL operation of the database connector to execute an ALTER, CREATE, or DROP operation. This procedure builds on the example that connects a Mule app to a database using the Classic Models sample database. 

. Create a new project and in the new flow, add an HTTP Listener operation. In a Listener configuration, accept an existing configuration or add one as follows:
+
* Protocol: Select HTTP.
* Host: *0.0.0.0*
* Port: 8081
+
. In General, set Path to the path of the HTTP URL, for example, set Path to `/`, and accept the other default settings. Close the Listener.
. Add a database connector Execute DDL operation to the flow, and set up a classicmodels database.
. In Execute - DDL, enter the SQL query text to alter, create, or drop a table. For example, create a table named testddl having one column called name.
+
`CREATE TABLE testddl (name VARCHAR(255))`
+
. Click Sync, and the execute the flow as follows:
+
* Select Running > Copy Link.
+
* Paste the link in a browser or client.
+
The HTTP Listener hears the request, starts the app, and a file, which you can delete, containing the binary query results is downloaded from the browser to your localhost. 
. In the database operation Output, the query results appear.

== See Also

* link:/connectors/db-connect-database-task[To Connect a Database]
* link:/connectors/db-connector-sql-ops-ref#execute-ddl[Execute DDL operation reference]
* link:http://www.mysqltutorial.org/download/2[Classic Models database download]