= To Connect a Database

This procedure, and others in this documentation, use the popular MySQL Classic Models database for example purposes. The procedure assumes you imported the database into a MySQL server. You can download this database from the internet:

`+http://www.mysqltutorial.org/download/2+`

You also might need to download a JDBC driver, compatible with the database you want to set up, to your hard drive. For example, download a MySQL database driver. During the configuration of the database connector, you upload the driver to Exchange where it becomes available for reuse in other projects.

. In Design Center, add a trigger, such as an HTTP listener, to initiate an app from a browser. For example, listen on port 8081 of all interfaces 0.0.0.0.
. In Design Center, click + to add a component to a flow.
. Choose the Database component, and then choose an operation, such as Select.
. At the top of Database Configuration, click Set Up and set the following options:
+
* Configuration Name: Change the name from the default Database to Classic Models Database.
* In Connection, select the Type: MySQL Connection
* In Host, enter the URL of the MySQL server host on the internet.
* In Port, enter `3306`
* User: Enter your MySQL server user name.
* Password: Enter your MySQL server password.
* Database: Enter `classicmodels`
* On Database Drivers, if you, or someone in your organization, already uploaded a driver for the database, look for and select it; otherwise, click Upload and choose a database driver on a file system.
+
To look for a connector, put the cursor in the text box, pause, and when the list of connectors appears, scroll to and select your connector.
+ 
. Test the connection, and if successful, save the configuration.

== See Also

* link:/connectors/http-to-trigger-app-from-browser[To Trigger an App from a Browser]
* link:/connectors/database-documentation[Database Connector Technical Reference]


