= To Set Up the Database

. Download the driver, which is compatible with the database you want to set up, to your hard drive. 
. In a new flow, set up an HTTP connector to listen for a request. Close the connector and click +.
. Select the Database component, and then select an operation, such as Select.
. Set up Database - Select:
+
* In Configuration Name, accept the default or type a new name.
* In Connection, select a type. For example, select MySQL.
* In Host, enter the name of the host running MySQL.
* In Port, enter the number of the port the host listens on, for example 3306.
* In User, enter the name of the MySQL database user.
* In Password, enter the password of the MySQL database user.
* In Database, enter the name of the MySQL database you want to use.
+
. Set Up the database driver:
+
* On Database Drivers, click Upload.
* Choose the MySQL database driver that you downloaded.
* Click Done.
+
. On Database Configuration, click Test and if successful, save the database configuration.
. In General, in SQL Query Text, enter a SQL select statement, omitting the semicolon. For example, `SELECT * FROM flights LIMIT 3`. Close Database - Select.
+
The database set up is complete. 

Before running the app, you need to transform the output from binary data to readable data.

== See Also

* To Make an HTTP Request
* Database Connector Technical Reference


