= To Set Up the Database

First, you set up a message source to initiate the app. Next, you set up a database connector to connect to a database on the network with Anypoint Platform. Finally, you test the connection and enter a query. 

. Download a driver, compatible with the database you want to set up, to your hard drive. 
. Create a new flow in a new project, and in Trigger select a message source. For example, select HTTP.
. Set up or change the listener configuration: 
+
* In Configuration Name, accept the default name HTTP Listener. 
* In Connection, accept the default protocol HTTP.
* Set the host and port. For example, host = 0.0.0.0 and port = 8081. 
* In Base Path, accept the default no base path.
* Click Save.
+
. In General, set Path to `/`, accept the other default listener settings, and close the connector.
. Click +, select the Database component, and then select an operation, such as Select.
. Set up Database - Select:
+
* In Configuration Name, accept the default or type a new name.
* In Connection, select a type. For example, select MySQL.
* In Host, enter the name of the host running MySQL.
* In Port, enter the number of the port the host listens on, for example 3306.
* In User, enter the name of the MySQL database user.
* In Password, enter the password of the MySQL database user.
* In Database, enter the name of the MySQL database you want to use.
+
. Set Up the database driver:
+
* On Database Drivers, click Upload.
* Choose the MySQL database driver that you downloaded.
* Click Done.
+
. On Database Configuration, click Test and if successful, save the database configuration.
. In General, in SQL Query Text, enter a SQL select statement, omitting the semicolon. For example, `SELECT * FROM flights LIMIT 
+
The database set up is complete. Close Database - Select.

== See Also

* To Make an HTTP Request
* Database Connector Technical Reference


