= To Set Up the Database

. Download to your hard drive the driver that is compatible with the database you want to set up. 
. After selecting a database operation, such as Select, configure the database options in Database - Select:
+
* In Configuration Name, accept the default or type a new name.
* In Connection, select a type from the drop-down. For example, select MySQL.
* In Host, enter the URL of the host running MySQL.
* In Port, enter the number of the port the host listens on, for example 3306.
* In User, enter the name of the MySQL database user.
* In Password, enter the password of the MySQL database user.
* In Database, enter the name of the MySQL database you want to query.
. Click Set Up to load the database driver. 
. On Database Drivers, click Upload and choose the MySQL database driver that you downloaded.
. Click Submit.
. On Database Configuration, click Test. If successful, proceed to the next step; otherwise, check and correct the configuration.
. Save the database configuration.
. In General, in SQL Query Text, enter a SQL select statement, omitting the semicolon. For example, `SELECT * FROM flights LIMIT 3`.
. Close Database - Select.


