= To Use a Stored Procedure

This workflow uses the popular Classic Models MySQL database for example purposes. Generally, you perform similar tasks regardless of the database.

. On a database server on the same network as Design Center, create a stored procedure. For example, on a MySQL database server on the internet, run the following MySQL commands on the command line.
+
----
USE classicmodels;
DELIMITER //
CREATE PROCEDURE GetVehicles()
BEGIN
SELECT * FROM products;
END //
----
+
. Reset the delimiter to the default. For example, `DELIMITER ;`.
. In Design Center, create a new project, and start a flow using an HTTP component that triggers an app from a browser.
. Follow instructions to link:/connectors/db-to-connect-database[connect the app to a database] except, in Select an Operation, select Stored Procedure.
. In SQL Query Text, enter: `Call GetAllProducts()` and close the connector.
. Capture the results of the query and format the results for readability.
+
* For example, add a logger to the flow.
* In General, type the following message: `payload.` and pause.
+
DataSense displays the database column names and other valid payloads.
+
* Select the name of a column, for example productLine.
* Accept the default JSON type.
* Close Logger - Config.
. In Designer, click Run or Update.
. Select Running > Copy Link and go to the URL.
+
. View the log.
+
The product lines appear:
+
----
    "Motorcycles",
    "Classic Cars",
    "Motorcycles",
    "Classic Cars",
    "Trucks and Buses",
    ...
----

== See Also

* link:http://www.mysqltutorial.org/download/2[Classic Models database download site]
* link:/connectors/http-to-trigger-app-from-browser[To Trigger an App from a Browser]

