= To List Email over IMAP(S)
:keywords: email, connector, configuration
:toc:
:toc-title:

toc::[]

Anypoint Studio, Design Center: *Email* connector

[[short_description]]
Lists all email in a mailbox folder that matches specified criteria, such as the sender, text in the subject, a given date, or other properties. Supports pagination of the results. Defaults to the inbox folder.

Note that emails in the list output have a number of attributes, such as a subject, an ID, sent and received dates, various address types (such as CC and BCC), email flags (such as Answered, Deleted, Seen). _TODO, PROVIDE REALISTIC EXAMPLE THAT USES THIS FUNCTIONALITY_

[[list_email]]
. After adding the *Email* connector to your flow, select the *List Imap* operation.
. Provide any optional settings you need:
  ** For a list of files from a folder other than the inbox (the default), provide the name of the *Mailbox Folder*, for example, `Sent`. _TODO, VERIFY VALID VALUES_
  ** To return a list that matches specific email properties, use *Match with* criteria, for example _... TODO, PROVIDE AN EXAMPLE, LINK TO OR MENTION THE REF?_
  ** Opt to use the *Delete After Retrieve* option (disabled by default).
  ** Change the *Output Type* to `STRING` or `MULTIPART`. Defaults to `ANY`. _TODO, USE CASE EXAMPLE?_
  ** Change the number of emails to list per page. The *Page Size* defaults to `10` emails per page.
  ** Provide a *Target Variable* to store the output of the *List* operation. _TODO, USE CASE EXAMPLE?_

[[see_also]]
== See Also

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]

////
[[errors]]
== Errors
_TODO, error MAPPING_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:CONNECTIVITY
////
