= To Delete Email (IMAP or IMAPS)

Provides procedures for marking email for deletion, then deleting them individually or along with all email within a folder.

[[mark-for-deletion]]
== To Mark Email for Deletion (IMAP, IMAPS)

Marks an email for deletion by the Delete or Expunge Folder operation.

. After adding the Email connector to your flow, select the Mark As Deleted operation.
. Set up or select an IMAP or IMAPS configuration for the operation.
. If you are deleting the file from a folder other than the Inbox, provide the name of the folder, for example, `Trash`.
. Add the Delete or Expunge Folder operation to your flow to complete the deletion process.

////
[[errors]]
== Errors
_TODO, error MAPPING_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:ACCESSING_FOLDER
* EMAIL:EMAIL_NOT_FOUND
* EMAIL:CONNECTIVITY
////

Note that you can also mark email for deletion after listing them with *List Imap* operation.

[[delete_email]]
== To Delete an Email (IMAP, IMAPS)

Deletes an email from a mailbox folder based on the ID of the email. Defaults to the inbox folder.

. Mark the email for deletion with the link:#mark-for-deletion[Mark As Deleted] operation.
. After adding the Email connector to your flow, select the Delete operation.
. Set up or select an IMAP or IMAPS configuration for the operation.
. If you are deleting the file from a folder other than the inbox, provide the name of the folder. Example: `Drafts`.
. Provide the ID of the email that you want to delete, for example: `#[attributes.id]`

////
== Errors
_TODO, error MAPPING_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:ACCESSING_FOLDER
* EMAIL:EMAIL_NOT_FOUND
* EMAIL:CONNECTIVITY
////

[[expunge_folder]]
== To Delete Email from a Folder (IMAP, IMAPS)

Eliminates (expunges) all email from an email folder that are marked for deletion. Other email in the folder is not deleted.

. Mark email for deletion with the link:#mark-for-deletion[Mark As Deleted] operation.
. After adding the Email connector to your flow, select the Expunge Folder operation.
. Set up or select an IMAP or IMAPS configuration for the operation.
. If you are deleting the file from a folder other than the Inbox (the default), provide the name of the folder. Example: `Trash`.

////
[[errors]]
== Errors
_TODO, error MAPPING_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:ACCESSING_FOLDER
* EMAIL:CONNECTIVITY
////

[[see_also]]
=== See Also
link:email-imap-to-set-up[To Set Up an IMAP or IMAPS Configuration]

link:common-to-create-error-messages[To Create Messages for Error Types]

link:email-imap-to-list-email[To List Email over IMAP or IMAPS]

link:email-about-the-email-connector[About the Email Connector]

link:email-documentation[Email Connector Technical Reference]
