= To Set Up an Email Configuration (POP3, POP3S)
:keywords: email, connector, configuration, pop3
:toc:
:toc-title:

toc::[]

Anypoint Studio, Design Center: *Email* connector

[[short_description]]
A POP3 configuration is required for all email retrieval operations that take place over the POP3 or POP3S protocol. The POP3S configuration requires a TLS configuration for encryption. Otherwise, the setup is identical to POP3.

[[set_up_pop3]]
. Open the `Email POP3` window from any POP3 operation in your flow or from the *Connections Explorer* in Anypoint Studio.
. Provide a *Name* for the configuration, for example, `Email POP3 configuration`.
. Set the *Connection* to the email server:
  ** Identify which connection *Type* to use:
    *** *POP3*
    *** *POP3S*
  ** Identify the *Host (required)*, for example, `pop.mail.somehost.com` or the IP address.
  ** Provide any optional connection configurations, such as the *User*, *Password*, or alternative *Port* to use.
. For IMAPS only, set up the *TLS Configuration* for security, for example:
  ** *Enabled Protocols*: `TLSv1.2,SSLv3`
  ** *Trust store*: `greenmail.jks`
  ** *Password*: `somepassword`
  ** _TODO, LOOKS LIKE OTHERS ARE REQUIRED_

For other configuration options, go to link:#see_also[See Also].

////
TODO: CREATE FILES FOR THESE, SEE SEE ALSO FOR FILE NAMES
. Provide any optional settings you need:
  ** Customize *Properties* for the connection setting, _TODO, FOR EXAMPLE?_:
    *** From expression, _TODO, USAGE EXAMPLE?_
    *** Create a map of key value pairs, _TODO, USAGE EXAMPLE?_
  ** Opt to change the *Timeout Configuration* for the email connection,
  read, and write processes, for example, where the *Timeout Unit* changes from `SECONDS` to `HOURS` or the *Connection Timeout* changes from `5` to `6`.
  ** Opt to change the *Pooling Profile* that configures the connection pool. _TODO, NEED FILE THAT EXPLAINS POOLING_
  ** Provide a *Reconnection Strategy* that includes the frequency, count, and whether to block. _TODO, UNDERSTAND BLOCKING..._
// NOT a pop3 task:  ** Opt to disable `Eagerly fetch content`
////

[[see_also]]
== See Also

include::include_link_list.adoc[tags=set-up-tls]

include::include_link_list.adoc[tags=set-connection-timeout]

include::include_link_list.adoc[tags=set-pooling-profile]

include::include_link_list.adoc[tags=set-reconnection-config]

include::include_link_list.adoc[tags=customize-email-props]

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]
