= About the Email Connector
:keywords: email, connector, send, retrieve, manage, match, matcher, smtp, pop3, imap
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center connector
[[short_description]]
The Email connector can receive and send email messages over standard protocols, and it supports secure connections for all protocols over Transport Layer Security (TLS).

[cols="1,1,3", options="header"]
|===
| SMTP Operations
| POP3 Operations
| IMAP Operations

| Send
| List Pop3
| Delete, Expunge Folder, List Imap, Mark As Deleted, Mark As Read, Store
|===

List Pop3 versus List Imap operations:

* POP3 downloads email, then deletes it from the server. IMAP does not delete email from the server. So if you want to read emails from multiple devices, for example, you should use List Imap.

Email connector configurations provide settings for connecting to an email server over a specific protocol and setting up the body of outgoing email.  You can create one or more configurations for each.

////
Email attributes, such as the subject, ID, from address, and so on form the metadata of the email message. You can use this metadata for data transformations.
////

Connection settings available for all protocols:

* Connection profile for the host, user, password, and port
* Timeouts for attempts to connect, read, and write. Default to 5 seconds.
* Reconnection strategies
* Connection pooling
* Option to disable validation of the connection
* Custom connection properties for complex mailbox configurations. The properties are from the Java Mail API specification.
* TLS, configured with a key and trust store.

Connection settings for incoming email only:

* Connection types (IMAP, IMAPS, POP3, POP3S)
* IMAP and IMAPS only: Option to open and mark retrieved emails as read (Eagerly Fetch Content). You might disable this option if you want to go through all the subjects of an email without reading the email. It is not possible to get inline content and attachments from unopened email.
+
Note that POP3 and POP3S email are always opened.

Connection settings for outgoing email only:

* Connection types (SMTP or SMTPS)
* Global From address setting
* Default character encoding setting for all messages


[[see_also]]
== See Also
include::include_link_list.adoc[tags=tech-ref-email]
