= To Create the Body of an SMTP(S) Email
:keywords: email, connector, configuration, smtp
:toc:
:toc-title:

toc::[]

Anypoint Studio, Design Center: *Email* connector

[[short_description]]
Sends an email message over SMTP. You use the *Email Builder* to construct  the outgoing email, including its addresses (to, from, cc, bcc), the subject, body,  attachments, and headers.

[[send_email]]
. After adding the *Email* connector to your flow, select the *Send* operation.
. Set up or select an SMTP or SMTPS configuration for the operation.
. Use the *Email Builder* create the outgoing email message:
  ** Provide addresses for the outgoing email. You need to add *From Addresses* and *To Addresses*. You can also provide a *Cc Addresses* and *Bcc Addresses*.
  ** Provide a *Subject* for the email. _TODO_
  ** Set up the *Body* of the email. _TODO_
  ** Set up any *Attachments* of the email, for example:
    *** *ID*: `text`
    *** *Content*: `Attachment`
    *** *Content Type*: `text-plain`
  ** Set up any *Header* properties for the email. _TODO_

[[see_also]]
== See Also

include::include_link_list.adoc[tags=smtp-set-up]

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]

////
[[Errors]]
== Errors
_TODO_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:ATTACHMENT
* EMAIL:CONNECTIVITY
////

////
Example
[source,xml,linenums]
----
<email:send config-ref="config" subject="Email Subject">
<email:builder>
<email:content>
<email:email-content name="emailContent" body="Email Content"  charset="UTF-8"/>
</email:content>
	<email:to-addresses>
	<email:to-address value="recip1@mule.com"/>
	<email:to-address value="recip2@mule.com"/>
<email:to-addresses>
<email:cc-addresses> … <email:cc-addresses>
<email:attachments>
  <email:attachment id="text" content="Attachment" contentType="text-plain" />
</email:attachments>
</email:builder>
</smtp:send>
////
