= To Send Emails Using the Email Connector
:keywords: email, connector, configuration, smtp, send, smtps
:toc:
:toc-title:

toc::[]

The Email connector allows you to send messages through the SMTP (and SMTPS) protocol.

== Configuring the Connector

There are 2 configurations that enables you to list the emails stored in a server: The SMTP
Configuration and it's secured version SMTPS.

Lets see an example of an SMTP configuration:

.SMTP Configuration
[source, xml, linenums]
----
<email:smtp-config name="smtp">
    <email:stmp-connection host="smtp.gmail.com" port="995" user="pablo.musumeci@mulesoft.com" password="#netherlands!"/>
</email:smtp-config>
----

=== Secured Configuration

The SMTP configuration provides an SMTPS connection type that allows you to configure a TLS
context, the same way as many others connectors do, to enabled SSL/TLS encryption and send
encrypted messages over the secured version of the SMTP protocol, SMTPS.

Let's see an SMTPS example:

.SMTP Configuration with TLS
[source, xml, linenums]
----
<email:smtp-config name="smtp">
    <email:stmps-connection host="pop.gmail.com" port="995" user="pablo.musumeci@mulesoft.com" password="#netherlands!"/>
        <tls:context enabledProtocols="TLSv1.2,SSLv3">
            <tls:key-store path="aKeystore" password="password"/>
            <tls:trust-store path="aTruststore.jks" password="changeit"/>
        </tls:context>
    </email:smtps-connection>
</email:smtp-config>
----

== Sending an Email

Sending emails pretty is straightforward, for example:

[source, xml, linenums]
----
<email:send config-ref="smtp" subject="IMPORTANT!" fromAddress="musumeci@mulesoft.com">
    <email:to-addresses>
        <email:to-address value="ale.gamarra@mulesoft.com"/>
        <email:to-address value="agustin.celentandios@mulesoft.com"/>
    </email:to-addresses>
    <email:body contentType="text/html">
        <email:content>"<h1>Hello this is an important message</h1>"</email:content>
    </email:body>
</email:send>
----

In the example above, the `to-addresses` parameter lists the primary recipient addresses of the
outgoing email, the `fromAddress` is the email sender address and the `subject` is
the email subject.
The body parameter is composed of text content and a `contentType` that specifies the
*text mime type* of the content (for example, `text/xml` or `text/plain`). If no body parameter is specified,
the content of the message payload will be used as default, if is not a text payload the operation will fail
with an `EMAIL:SEND` error.



== Sending Attachments

When sending attachments through SMTP, you use DataWeave to handle the attachments.

In this example, a flow reads a JSON file using the File connector, then uses the Email connector to
send the contents of the file as an attachment over SMTP:

[source, xml, linenums]
----
<flow name="attachment">
  <file:read path="/file.json"/>
  <email:send config-ref="config">
      <email:to-addresses>
          <email:to-address value="agusto.celentandios@mulesoft.com"/>
      </email:to-addresses>
      <email:body>
          <email:content>Sending attachments!</email:content>
      </email:body>
      <email:attachments>
        #[{
          'json-attachment' : payload
        }]
      </email:attachments>
  </email:send>
</flow>
----

As you can see, the `email:attachments` parameter expects a DataWeave expression in which
each element is an attachment. For instance, the example above adds a new attachment
named `json-attachment`. Notice that `payload` is the content of the
JSON file that was read by the File connector.
