= To Store Email (IMAP, IMAPS)
:keywords: email, connector, configuration, imap
:toc:
:toc-title:

toc::[]

// Anypoint Studio, Design Center: Email connector

[[short_description]]
This operation stores an email from the specified email folder into a local directory. It saves the email as a `txt` file and bases the file name on the subject.

[[store_email]]
. After adding the Email connector to your flow, select the Store operation.
. Set up or select an IMAP or IMAPS configuration for the operation.
. Specify the Local Directory to store the file, for example, `/Users/someuser/email/archive`.
. If you are selecting file from a folder other than the Inbox, provide the name for the Mailbox Folder, for example, `Sent`.
. Provide any optional settings:
  ** You can use the File Name field to provide a prefix (such as `archive-`) to the full file name, which appends the ID of the email and the date that the email was received (if available) to that prefix.
  +
  By default, the prefix is the subject of the email.
  +
  ** You can provide an Email ID of the email that you want to store.
  ** You can check the Should Overwrite option to overwrite any file with the same file name. Defaults to false.

[[see_also]]
== See Also

include::include_link_list.adoc[tags=imap-set-up]

include::include_link_list.adoc[tags=set-reconnection-config]

include::include_link_list.adoc[tags=tech-ref-email]

////
[[errors]]
== Errors
_TODO_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:CONNECTIVITY
////
