= To Delete Email over IMAP(S)
:keywords: email, connector, email, imap
:toc:
:toc-title:

toc::[]

Anypoint Studio, Design Center: *Email* connector

[[short_description]]
Deletes an email from a mailbox folder based on the ID of the email. Defaults to the inbox folder.

The email must be marked for deletion with with *Mark As Deleted* before you can delete it.

[[delete_email]]
. After adding the *Email* connector to your flow, select the *Delete* operation.
. Set up or select an IMAP or IMAPS configuration for the operation.
. If you are deleting the file from a folder other than the inbox, provide the name of the folder, for example, `Drafts`.
. Provide the ID of the email that you want to delete, for example, `#[mel:payload.attributes.get().id]` to delete the first email in the folder. _TODO, NEED DW EXPRESSION? NEED EXPRESSION THAT WOULD DELETE ANY EMAIL THAT GOES IN THE FOLDER?_
// Juani: You might get the ID by saving it from a returned email.
//_TODO, HOW DO THEY GET THE ID? CAN THEY AUTOMATE THIS SOMEHOW? REGEX? REALISTIC USE CASE?_

[[see_also]]
== See Also

include::include_link_list.adoc[tags=imap-set-up]

include::include_link_list.adoc[tags=imap-mark-deleted]

include::include_link_list.adoc[tags=imap-expunge-folder]

include::include_link_list.adoc[tags=create-error-messages]

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]

////
== Errors
_TODO, error MAPPING_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:ACCESSING_FOLDER
* EMAIL:EMAIL_NOT_FOUND
* EMAIL:CONNECTIVITY
////
