= To Configure TLS for Email
:keywords: email, connector, configuration
:toc:
:toc-title:

toc::[]

For Anypoint Studio, Design Center: link:email-about-the-email-connector[Email], HTTP, and Sockets connector _TODO, NEED TO COORDINATE WITH KRIS, ETC._

[[short_description]]
To provide secure connections to an email server over IMAPS, POP3S, and SMTPS protocols, you need to configure Transport Layer Security (TLS) as part of your overall configuration for them.
_TODO, APPLIES TO HTTP, ETC., GOES BEYOND EMAIL PROTOCOLS AND SERVER, THOUGH COULD SINGLE SOURCE COMMON CONTENT, TBD..._

[[set_up_tls]]
. _TODO, CLARIFY_ Open the window for the configuration. You can find in from the *Email IMAP*, *Email POP3*, or *Email SMTP* windows for an email operation in your flow or from the *Connections Explorer* in Anypoint Studio.

_TODO, SEE IF KRIS HAS ALREADY PROVIDED SOMETHING TO LINK TO THAT WILL WORK FOR EMAIL_

[[see_also]]
== See Also
* link:email-imap-to-set-up[To Set Up an IMAP Configuration for the Email Connector]
* link:email-pop3-to-set-up[To Set Up a POP3 Configuration for the Email Connector]
* link:email-smtp-to-set-up[To Set Up an SMTP Configuration for the Email Connector]

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]
