= About the Email Connector
:keywords: email, connector, send, retrieve, manage, match, matcher, smtp, pop3, imap
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center connector
[[short_description]]
The Email connector handles the send and retrieval of email messages over the standard protocols. It's main features
include:

* Retrieve emails from POP3 mailboxes.
* Retrieve, Delete and Store emails from IMAP mailboxes.
* Send emails through the SMTP protocol.
* Supports secure connections for all protocols over Transport Layer Security (TLS).


[[connection_settings]]
== Configuring the connector

Email connector configurations vary depending on what protocol you are trying to use, but they share
a basic set of parameters that are required to establish a connection:

 * host: the host name of the mail server.
 * port: the port number of the mail server. Each protocol has a default port number, if none is set.
 * username: the username used to connect with the mail server.
 * password: the user password used to connect with the protected mail server.

Both username and password are optional since the servers may not be secured with username/password.

Also the secured versions of the protocols (SMTPS, POP3S, IMAPS) allows the you to configure a TLS context
for SSL/TLS encryption, the same way that many others connectors do.

This example sets a configuration for the POP3S gmail mailbox.

[source, xml, linenums]
----
<email:pop3-config name="config">
    <email:pop3s-connection host="pop.gmail.com" port="995" user="pablo.musumeci@mulesoft.com" password="#netherlands!">
        <tls:context insecure="true"></tls:context>
    </email:pop3s-connection>
</email:pop3-config>
----

== Attributes

When listing emails, users are often not only interested in the email's content, but in its metadata as well (for example: the subject, from addresses, to addresses, received date, and so on). This attributes may vary depending
on the type of configuration that you are using.
The email connector will use the Mule Message Attributes to access this information, while the Message Payload will always contain the email's content.

For details on the Email Attributes structure, please read the link:email-documentation[techincal reference].

== See Also
* link:email-list[To List emails]
* link:email-send[To Send emails]

[[see_also]]
== See Also
link:email-documentation[Email Connector Technical Reference]
