= To Set Up an Email Configuration (IMAP, IMAPS)
:keywords: email, connector, configuration, imap
:toc:
:toc-title:

toc::[]

// Anypoint Studio, Design Center: *Email* connector

[[short_description]]
An IMAP configuration is required for all email retrieval operations that take place over the IMAP or IMAPS protocol. The IMAPS configuration requires a TLS configuration for encryption. Otherwise, the setup is identical to IMAP.

Before you begin, add an Email operation (such as List Imap) to your flow. This procedure assumes that you have not set up any other IMAP configurations in your app.

[[set_up_imap]]
. Open the Email IMAP Configuration window from an Email operation.
  ** In Design Center, you select Set Up from the Configuration tab in the operation.
  ** In Anypoint Studio, you select the `+` under Basic Settings in the General tab.
. Provide a Name for the configuration, for example, `My Email IMAP configuration`.
. Set the Connection to the email server:
  ** Identify which connection Type to use:
    *** IMAP
    *** IMAPS
  ** Identify the Host (required), for example, `imap.hostname.com` or the IP address.
  ** Provide any optional connection configurations, such as the User, Password, or alternative Port to use.
. For IMAPS only, set up the TLS Configuration for security, for example:
  ** Enabled Protocols: `TLSv1.2,SSLv3`
  ** Trust store: `greenmail.jks`
  ** Password: `somepassword`
. If you do not want emails to be marked as opened and read when they are retrieved, disable `Eagerly fetch content`. For example, you might disable it if you only want to retrieve subjects without reading the content.

For other configuration options, go to link:#see_also[See Also].

////
TODO: CREATE FILES FOR THESE, SEE SEE ALSO FOR FILE NAMES
. Provide any optional settings you need:
  ** Customize *Properties* for the connection setting, _TODO, FOR EXAMPLE?_:
    *** From expression, _TODO, USAGE EXAMPLE?_
    *** Create a map of key value pairs, _TODO, USAGE EXAMPLE?_
  ** Opt to change the *Timeout Configuration* for the email connection,
  read, and write processes, for example, where the *Timeout Unit* changes from `SECONDS` to `HOURS` or the *Connection Timeout* changes from `5` to `6`.
  ** Opt to change the *Pooling Profile* that configures the connection pool.
  ** Provide a *Reconnection Strategy* that includes the frequency, count, and whether to block. _TODO, UNDERSTAND BLOCKING..._
////

[[see_also]]
== See Also

include::include_link_list.adoc[tags=set-up-tls]

include::include_link_list.adoc[tags=set-connection-timeout]

include::include_link_list.adoc[tags=ref-pooling-profile]

include::include_link_list.adoc[tags=set-reconnection-config]

include::include_link_list.adoc[tags=customize-email-props]

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]
