= To List Emails Using the Email Connector

The Mule 4 connector provides the ability to list emails in any part of
the flow, unlike the old Mule 3 transport which can only retrieve emails as a result
of inbound endpoint polling.

NOTE: both POP3 and IMAP configurations contains a `list` operation. This section covers both
together and explains the differences. The examples used in this section might use `list-pop3`
or `list-imap` but all the sections apply for both configurations *unless stated otherwise*.

== Configuring the Connector

There are two configurations that enables you to list the emails stored in a server: The POP3 Configuration and
the IMAP configuration.

They share a basic set of the parameters that are required to establish a connection: the server host and port, and
an username and password to connect with a protected mail server if required (Both username and password are
optional because the servers might not be secured with a username and password).

Lets see an example of a POP3 and IMAP configurations:

.POP3 Configuration
[source, xml, linenums]
----
<email:pop3-config name="pop3-config">
    <email:pop3-connection host="pop.gmail.com" port="995" user="pablo.musumeci@mulesoft.com" password="#netherlands!"/>
</email:pop3-config>
----

.IMAP Configuration
[source, xml, linenums]
----
<email:imap-config name="imap-config">
    <email:imap-connection host="imap.gmail.com" port="912" user="pablo.musumeci@mulesoft.com" password="#netherlands!"/>
</email:imap-config>
----

They look similar, for differences take look at the Configurations section in
the full link:email-documentation[Email Connector Technical Reference].

=== Secured Connections

The IMAP and POP3 configurations provides a secured connection type to work over the secured
versions of the protocols (POP3S, IMAPS) allowing you to configure a TLS
context, the same way as many others connectors do, to enabled SSL/TLS encryption.

Let's see an IMAPS example:

.IMAP Configuration with TLS
[source, xml, linenums]
----
<email:imap-config name="tls">
    <email:imaps-connection host="${port}" port="${port}">
        <tls:context enabledProtocols="TLSv1.2,SSLv3">
            <tls:key-store path="aKeystore" password="password"/>
            <tls:trust-store path="aTruststore.jks" password="changeit"/>
        </tls:context>
    </email:imaps-connection>
</email:imap-config>
----

NOTE: A TLS context is also available for the POP3S connection the same way as it is for IMAPS.

== Listing Emails

The list operations will return all the emails in the configured mailbox server (specified in the connection)
that reside in a parameterized mailbox folder.

The basic syntax to list the emails in a mailbox is:

.For POP3
[source, xml, linenums]
----
<email:list-pop3 config-ref="pop3-config" mailboxFolder="INBOX"/>
----

.For IMAP
[source, xml, linenums]
----
<email:list-imap config-ref="imap-config" mailboxFolder="INBOX"/>
----

This simple examples returns all the emails in the configured mailbox servers that
reside in the *INBOX* folder.

NOTE: The `config-ref` attributes points to the configs declared in the configuration examples.

== Getting the Email's Data

Incoming emails carry the content of the email in the payload, both email body and attachments
if they have any. Let's look the following example in which we iterate between all the
retrieved emails:

[source, xml, linenums]
----
<flow name="retrieveWithAttachments">
    ...
    <email:list-imap config-ref="imap-config"/>
    <foreach>
        <set-variable variableName="email-content" value="payload.body" />
        <set-variable variableName="json-attachment" value="payload.attachments.json" />
    </foreach>
</flow>
----

When working with a single email in the payload, you do `payload.body` to access the
email content, For instance the example sets the body to a variable called `email-content`.

To access the email attachments, you can do `payload.attachments.{nameOfTheAttachment}`, the example
sets an attachment called `json` that is being carried by the retrieved email to a new variable `json-attachment`.

== Attributes

When listing emails, users are often not only interested in the email's content, but in its metadata, as
well (for example, the subject, from addresses, to addresses, received date, and so on).
These attributes vary depending on the type of configuration that you are using, because the
IMAP protocol provides more metadata about the retrieved email like the `recent`, `seen`, `deleted`, and `answered` flags.

The email connector uses Mule message attributes to access this information, while the message payload, as explained
before, always contains the email's content.

For details on the structure of email attributes, please read the link:email-documentation[Email Module Documentation Reference].

== Matching

When listing emails, you can filter emails that match certain criteria using the `<email:pop3-matcher>`
and `<email:imap-matcher>` elements. These elements define the criteria that can be used to process an email or not.

This example of an IMAP matcher rejects emails with subjects that do not match
the `[0-9]` regular expression and that have not been seen before.

[source, xml, linenums]
----
<email:list-imap config-ref="config">
    <email:imap-matcher subjectRegex="[0-9]" seen="EXCLUDE"/>
</email:list-imap>
----

All matcher attributes are optional and are ignored if they are not provided, and they are
all related to each other under an AND operator.

The example above declares an inner, non-reusable, matcher that is proprietary to a particular component,
but matchers can be declared as a reusable element (as a named top-level element).
For example, this `pop3-matcher`:

[source, xml, linenums]
----
<email:pop3-matcher name="pop3Matcher"
                    subjectRegex="Email Subject"
                    fromRegex="@mulesoft"/>

<flow name="listEmails">
  ...
  <file:list pop3-matcher="pop3Matcher" />
  ...
</flow>
----

=== IMAP Matcher vs POP3 Matcher

The IMAP protocol provides metadata about the email that allows for more
precise filters than POP3.

The POP3 matcher contains these parameters:

[source, xml, linenums]
----
<email:pop3-matcher
  receivedSince="2015-06-03T13:21:58+00:00"
  receivedUntil="2015-07-03T13:21:58+00:00"
  sentSince="2015-05-03T13:21:58+00:00"
  sentUntil="2015-06-03T13:21:58+00:00"
  subjectRegex="BETA:"
  fromRegex="@mulesoft"/>
----

The IMAP matcher looks like this:

[source, xml, linenums]
----
<email:imap-matcher
  receivedSince="2015-06-03T13:21:58+00:00"
  receivedUntil="2015-07-03T13:21:58+00:00"
  sentSince="2015-05-03T13:21:58+00:00"
  sentUntil="2015-06-03T13:21:58+00:00"
  subjectRegex="BETA:"
  fromRegex="@mulesoft"
  recent="EXCLUDE|INCLUDE|REQUIRE"
  seen="EXCLUDE|INCLUDE|REQUIRE"
  deleted="EXCLUDE|INCLUDE|REQUIRE"
  answered="EXCLUDE|INCLUDE|REQUIRE"/>
----

Notice that the IMAP matcher includes the `recent`, `seen`, `deleted`, and `answered` parameters.
