= XML Reference for the Email Connector (Studio)
:keywords: email, connector, configuration, pop3
:toc:
:toc-title:

toc::[]

[[short_description]]
These examples show common email configurations.

[[email_xml_configs]]
== Email Connection Configurations

POP3 configuration example:
----
<email:pop3-config name="pop3Config">
   <email:pop3-connection
     host="pop.gmail.com" port="995"
     password="myPassword" user="my.account@gmail.com"/>
</email:pop3-config>
----

POP3S example with a TLS configuration:
----
<email:pop3-config name="mySecureConfig">
   <email:pop3s-connection host="127.0.0.1" port="995" password="myPassword" user="my.account@gmail.com">
       <tls:context enabledProtocols="TLSv1.2,SSLv3">
           <tls:trust-store path="greenmail.jks" password="changeit"/>
       </tls:context>
   </email:pop3s-connection>
</email:pop3-config>
----

IMAP configuration example with Eagerly Fetch Content disabled:
----
<email:imap-config eagerlyFetchContent="false" name="email_imap">
    <email:imap-connection host="imap.gmail.com" password="changeme" user="me@gmail.com"/>
</email:imap-config>
----

SMTP configuration examples:
----
<email:smtp-config name="smtpConfig">
   <email:smtp-connection
     host="smtp.gmail.com" port="465"
     password="myPassword" user="my.account@gmail.com"/>
</email:smtp-config>
----

----
<email:smtp-config name="senderConfig" defaultEncoding=”UTF-8”>
   <email:smtp-connection host="127.0.0.1" port="587"/>
</email:smtp-config>
----

== Operations

List operation: This example retrieves the body (`payload`) and subject (the `subject` attribute) of email. The List operation retrieves email through a configurable pagination process that defaults to `10` per page rather than retrieving all email at once.

----
<flow name=”retrieveEmails”>
<email:list-pop3 config-ref=”pop3Config”/>
  <foreach>
    <logger level=”INFO” message=”#[output application/java --- ‘Email body: $(payload)’]”/>
    <logger level=”INFO” message=”#[output application/java --- ‘Email subject: $(attributes.subject)’]”/>
  </foreach>
</flow>
----

Send operation:

----
<email:send config-ref="senderConfig" fromAdress=”sender.account@mulesoft.com”>
    <email:to-addresses>
        <email:to-address value="test.account@mulesoft.com"/>
    </email:to-addresses>

    <email:body>
        <email:content>Email Content</email:content>
    </email:body>

</email:send>
----

Store operation: Stores email to a local directory.

----
<email:store config-ref="config" mailboxFolder="INBOX" localDirectory="/Users/home”  emailID=”5” overwrite=”true”/>
----

Mark As Read operation:

----
<email:mark-as-read config-ref="imapConfig" emailId="123">
----

Mark As Deleted operation: Marks email for deletion by the Expunge operation.

----
<email:mark-as-deleted config-ref="imapConfig" emailId="123">
----

Expunge operation: Works on emails that are marked for deletion with the Mark As Deleted operation.

----
<email:expunge-folder config-ref="imapConfig" mailboxFolder="INBOX" >
----

Delete operation:

----
<email:delete config-ref="imapConfig" mailboxFolder="INBOX" emailId=”123”>
----

Attachments: TODO TODO You need to create a DataWeave map with the name of the attachments as keys and its values with the respective mime types.

----
<flow name="sendEmailWithAttachments">

   <set-variable variableName="json" value="#[output application/json --- {key: 'value'}]" mimeType="application/json"/>
   <set-variable variableName="textPlain" value="This is the email text attachment" mimeType="text/plain"/>
   <set-variable variableName="octetStream" value="#[myBinaryVariable]" mimeType="application/octet-stream"/>

   <email:send config-ref="senderConfig" subject="This is the email subject">
       <email:to-addresses>
           <email:to-address value="test.account@mulesoft.com"/>
       </email:to-addresses>
----

----

TODO TODO:
Advanced SMTP Configuration Parameters:
----

// How do you get the ID? How/why would you ever know it?

[[see_also]]
== See Also

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]
