= To Set Up an Email Configuration (SMTP, SMTPS)
:keywords: email, connector, configuration, smtp
:toc:
:toc-title:

toc::[]

// Anypoint Studio, Design Center: *Email* connector
////
TODO:
* is there a default encoding on Mozart
 + The default encoding is set on the Mule _Runtime?_ instance.
* tls setting examples need to be checked, the values and whether all required ones are covered. Does it even make sense to cover them here? As a user, I'd want to know how to figure out what the settings are.
* talk about optional settings? see below.
////

[[short_description]]
An SMTP configuration is required for all email delivery operations that take place over the SMTP or SMTPS protocol. The SMTPS configuration requires a TLS configuration for encryption. Otherwise, the setup is identical to SMTP.

[[set_up_smtp]]
. Open the `Email SMTP` window from any POP3 operation in your flow or from the Connections Explorer in Anypoint Studio.
. Provide a Name for the configuration, for example, `Email SMTP configuration`.
. Set the Connection to the email server:
  ** Identify which connection Type to use:
    *** SMTP
    *** SMTPS
  ** Identify the Host (for example, `smtp.mycompany.com`), and if necessary, the User, Password, and Port.
  ** Provide any General settings that you need:
    *** Opt to provide a From address for the sender.
    *** Opt to change the Default Encoding, for example, `UTF-8`, `UTN-32`, or `ISO 8859-1`.
  ** Provide any optional connection configurations, such as the User, Password, or alternative Port to use.
. For SMTPS only, set up the TLS Configuration for security, for example:
  ** Enabled Protocols: `TLSv1.2,SSLv3`
  ** Trust store: `greenmail.jks`
  ** Password: `somepassword`
. For other configuration options, go to link:#see_also[See Also].

[[see_also]]
== See Also

include::include_link_list.adoc[tags=set-up-tls]

include::include_link_list.adoc[tags=set-connection-timeout]

include::include_link_list.adoc[tags=set-pooling-profile]

include::include_link_list.adoc[tags=set-reconnection-config]

include::include_link_list.adoc[tags=customize-email-props]

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]
