= To Set Up an SMTP(S) Email Configuration
:keywords: email, connector, configuration, smtp
:toc:
:toc-title:

toc::[]

Anypoint Studio, Design Center: *Email* connector

[[short_description]]
An SMTP configuration is required for all email delivery operations that take place over the SMTP or SMTPS protocol. The SMTPS configuration requires a TLS configuration for encryption. Otherwise, the setup is identical to SMTP.

[[set_up_smtp]]
. Open the `Email SMTP` window from any POP3 operation in your flow or from the *Connections Explorer* in Anypoint Studio.
. Provide a *Name* for the configuration, for example, `Email SMTP configuration`.
. Set the *Connection* to the email server:
  ** Identify which connection *Type* to use:
    *** *SMTP*
    *** *SMTPS*
  ** Identify the *Host* (for example, `smtp.mycompany.com`), and if necessary, the *User*, *Password*, and *Port*.
  ** Provide any *General* settings that you need:
    *** Opt to provide a *From* address for the sender.
    *** Opt to change the *Default Encoding*, for example, `UTF-8`, `UTN-32`, or `ISO 8859-1`. _TODO, IS THERE A DEFAULT ON MOZART?_
    + The default encoding is set on the Mule _TODO, Runtime?_ instance. _TODO, NOT SURE WHAT THE CASE IS FOR MOZART_
  ** Provide any optional connection configurations, such as the *User*, *Password*, or alternative *Port* to use.
. For SMTPS only, set up the *TLS Configuration* for security, for example:
  ** *Enabled Protocols*: `TLSv1.2,SSLv3` _TODO, CHECK VALUE FOR SMTPS_
  ** *Trust store*: `greenmail.jks` _TODO, CHECK VALUE FOR SMTPS_
  ** *Password*: `somepassword`
  ** _TODO, LOOKS LIKE OTHERS ARE REQUIRED_

For other configuration options, go to link:#see_also[See Also].

////
. Provide any other optional settings you need:
  ** Customize *Properties* for the connection setting, _TODO, FOR EXAMPLE?_:
    *** From expression, _TODO, USAGE EXAMPLE?_
    *** Create a map of key value pairs, _TODO, USAGE EXAMPLE?_
  ** Opt to change the *Timeout Configuration* for the email connection,
  read, and write processes, for example, where the *Timeout Unit* changes from `SECONDS` to `HOURS` or the *Connection Timeout* changes from `5` to `6`.
  ** Opt to change the *Pooling Profile* that configures the connection pool. _TODO, NEED FILE THAT EXPLAINS POOLING_
  ** Provide a *Reconnection Strategy* that includes the frequency, count, and whether to block. _TODO, UNDERSTAND BLOCKING..._
// NOT a pop3 task:  ** Opt to disable `Eagerly fetch content`
////

[[see_also]]
== See Also

include::include_link_list.adoc[tags=set-up-tls]

include::include_link_list.adoc[tags=set-connection-timeout]

include::include_link_list.adoc[tags=set-pooling-profile]

include::include_link_list.adoc[tags=set-reconnection-config]

include::include_link_list.adoc[tags=customize-email-props]

include::include_link_list.adoc[tags=email-connector]

include::include_link_list.adoc[tags=tech-ref-email]
