= About the Email Connector
:keywords: email, connector, send, retrieve, manage, match, matcher, smtp, pop3, imap
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center connector
[[short_description]]
The Email connector can receive and send email messages over standard protocols, and it supports secure connections for all protocols over Transport Layer Security (TLS).

[cols="1,1,3", options="header"]
|===
| SMTP Operations
| POP3 Operations
| IMAP Operations

| Send
| List Pop3
| Delete, Expunge Folder, List Imap, Mark As Deleted, Mark As Read, Store
|===

Email connector configurations provide the settings needed to perform email operations and to set up the body of outgoing email. You can create one or more configurations for each.

////
Email attributes, such as the subject, ID, from address, and so on form the metadata of the email message. You can use this metadata for data transformations.
////

Connection settings available for all protocols:

* Connection profile for the host, user, password, and port
* Timeouts for attempts to connect, read, and write. Default to 5 seconds.
* Reconnection strategies
* Connection pooling
* Option to disable validation of the connection
* Custom connection properties for complex mailbox configurations. The properties are from the Java Mail API specification.
* TLS, configured with a key and trust store.

Connection settings for incoming email only:

* Connection types (IMAP, IMAPS, POP3, POP3S)
* IMAP and IMAPS only: Option to open and mark retrieved emails as read (Eagerly Fetch Content). It is not possible to get inline content and attachments from unopened email.
+
Note that POP3 and POP3S email are always opened.

Connection settings for outgoing email only:

* Connection types (SMTP or SMTPS)
* Global From address setting
* Default character encoding setting for all messages

The Email Event


////

include::include_link_list.adoc[tags=imap-set-up]

include::include_link_list.adoc[tags=pop3-set-up]

include::include_link_list.adoc[tags=smtp-set-up]

include::include_link_list.adoc[tags=set-up-email-body]
////

////
== Operations

Email operations are specific to the email transport protocol.

IMAP operations:
include::include_link_list.adoc[tags=imap-delete-email]

include::include_link_list.adoc[tags=imap-expunge-folder]

include::include_link_list.adoc[tags=imap-list-email]
(includes filtering options)

include::include_link_list.adoc[tags=imap-mark-deleted]

include::include_link_list.adoc[tags=imap-store-email]

POP3 operations:

include::include_link_list.adoc[tags=pop3-list-email]
(includes filtering options)

SMTP operations:

include::include_link_list.adoc[tags=smtp-send-email]

include::include_link_list.adoc[tags=set-up-email-body]
////

[[see_also]]
== See Also
include::include_link_list.adoc[tags=tech-ref-email]

////
TODO, LOOK for link:#configure-secure[How to Configure a Secure Connection]


POP3 and IMAP transports can only be used as inbound-endpoints, and both are polling only.
SMTP transport can only be used as an outbound-endpoint.
There is not a good way to filter the received emails
There are basic operations that are not supported such as delete, markAsRead and store.

Also we want to give the user a more friendly way of using the connector without knowing so much of the low level protocols and not worrying about properties and special configurations, but also without removing the possibility of extending and overriding the default configurations that are bundled with the connector.

 The connector will have 3 different configurations one for each protocol and each of this configuration will have a 2 providers associated one that operates secured by SSL/TLS and the other without it.
The connector will be based on the Java Mail Api as the old transports do in order to perform all the operations, but none of its domain will be exposed to the final user, all the api objects and definitions will be wrapped up in more simple abstractions.
The IMAP and POP3 connectors will have associated all the receive and email folder management operations, and the SMTP will have the send operations associated to it.
For both IMAP and POP3 protocols almost all the same operations apply, there are some flag setting operations that only IMAP support and some differences when performing the email deletion.
////
/////
[[configure]]
== How to Configure

. Place the connector into your flow as applicable for your use case.
. Choose a configuration for your connector that matches the protocol your use case requires:
* link:#config-imap[Configure IMAP(S)] ("S" = with secure connection)
* link:#config-POP3[Configure POP3(S)]
* link:#config-SMTP[Configure SMTP(S)]
[TIP]
If you need to secure the connection with TLS, choose the connection provider for IMAPS, SMTPS or POP3S accordingly. See
. Select an operation for the connector instance and fill in necessary fields.

[NOTE]
Any of these configurations can be created without setting attributes--all of them have default values.

=== Which configuration do I choose?

Choose a configuration that supports the the email protocol for the operation you are trying to perform through your email server:

* Retrieve and manage email using *IMAP or POP3*
* Send email using *SMTP*

[NOTE]
IMAP and POP3 operations allow email retrieval and management, offering an email matcher to filter email.

=== How is the secure connection provider different from the normal provider?

Secure providers include one more parameter of type `TLSContext`.

`TlsContext` is configured with a key store and a trust store to perform a secure connection with the server.

[[configure-secure]]
=== How to Configure a Secure Connection

`TlsContext` is the element you configure to set up a secure connection for the connector. It can be defined inline or defined as a global element outside the flow and referenced by name.

.TlsContext defined inline
[source,xml,linenums]
----
<email:imap name="config">
<email:imaps-connection username="user" password="pass" host="host.imap">
<tls:context name="tlsContext">
<tls:key-store path="serverKeystore"
keyPassword="key-pass"
password="mulepass"/>
 	<tls:trust-store path="trustStore" password="mulepassword"/>
</tls:context>
</email:imaps-connection>
</email:imap>
----

A reference to a global `</tls:context>` can be provided instead of declaring the child element inline.

.Global TlsContext referenced
[source,xml,linenums]
----
<email:imap name="config" password="pass" user="User" host="host.imap">
	<email:imaps-connection tls-context="tlsContext" />
</email:imap>
----

If no `</tls:context>` is provided, the connection takes the default TLS Context created by Mule.

.Default TlsContext used
[source,xml,linenums]
----
<email:imap name="config" password="pass" user="User" host="host.imap">
<email:imaps-connection>
</email:imap>
----

[[config-imap]]
=== IMAP(S) Configuration

The IMAP configuration `<email:imap name="config-imap">` must contain an IMAP or IMAPS connection provider:

* `<email:imap-connection/>`
* `<email:imaps-connection/>`


The IMAP configuration has an optional parameter `eagerlyFetchContent`. This boolean sets whether the retrieved emails should be opened and read or not.

[NOTE]
By default, all emails retrieved by IMAP configuration are opened.

.Example IMAP configuration
[source,xml,linenums]
----
<email:imap name="config"  eagerlyFetchContent="false">
   <email:imap-connection host="127.0.0.1" … />
</email:imap>
----

The IMAPS connection's `TlsContext` is defined inline in this example:

.Example IMAPS configuration
[source,xml,linenums]
----
<email:imap name="config">
<email:imaps-connection username="user" password="pass" host="host.imap">
<tls:context name="tlsContext">
<tls:key-store path="serverKeystore"
keyPassword="key-pass"
password="mulepass"/>
 	<tls:trust-store path="trustStore" password="mulepassword"/>
</tls:context>
</email:imaps-connection>
</email:imap>
----

==== Notes

* If email content is not opened, it is marked as "NOT OPEN". You won't be able to get the inline content and the attachments.

[[config-POP3]]
=== POP3(S) Configuration

The POP3 configuration `<email:pop3 name="config-pop3">` does not define any attributes. It is just a container for the connection. The POP3 configuration must contain either a POP3 or POP3S connection provider:

* `<email:pop3-connection/>`
* `<email:pop3s-connection/>`


.POP3 Example
[source,xml,linenums]
----
<email:pop3 name="config">
   <email:pop3-connection host="127.0.0.1" … />
</email:pop3>
----

==== Notes

* Email retrieved through the POP3 configuration is always opened automatically.

[[config-SMTP]]
=== SMTP(S) Configuration

The SMTP configuration `<email:smtp name="config-smtp">` must contain a SMTP or SMTPS connection provider:

* `<email:smtp-connection/>`
* `<email:smtps-connection/>`

The SMTP configuration defines two optional attributes:

* `from`: the from address. The person that is going to send messages using this configuration. This attribute is optional and will fallback to the default session user.
* `defaultEncoding`: default encoding to be used (if no other is specified in the operation that uses this configuration)  in the messages sent using SMTP. This attribute is optional and it will fallback to the default mule configuration encoding.

.Example SMTP Configuration
[source,xml,linenums]
----
<email:smtp name="config" from="owow@mule.com" defaultEncoding="UTF-8">
   <email:smtp-connection host="127.0.0.1" … />
</email:smtp>
----

[[use-cases]]
== Use Cases

Operations and use cases for the File connector.

=== Manage Existing Email (IMAP)

* link:#list[List email] (also available using POP3)
* link:#store-email[Store email]
* link:#mark-asread[Mark as read]
* link:#mark-as-deleted[Mark as deleted]
* link:#expunge-folder[Expunge folder]

[NOTE]
Learn how to link:#define-filter[Define an Email Filter] with the link:#list[List operation] (POP3/IMAP)

=== Create and Send Email (SMTP)

Send email using the link:#send-email[Send Email] operation. The operation provides an "email builder" where you define recipients, email body/content, attachments, recipients, etc.

* link:#send-email[Send Email]
** link:#email-builder[Email Builder]
*** link:#email-body[Email Body]
*** link:#email-attachment[Email Attachment]


[TIP]
See the link:/connector[Connector Technical Reference] for all connector operations and attributes.


[[define-filter]]
=== Define Email Filter

Define a filter that matches the emails you want to handle with the connector.

Create an `<email:matcher>` element where you define the criteria.

Since POP3 and IMAP differ in what they retrieve, there are two matcher implementations, one for each protocol.

.Example POP3 Matcher Definition
[source,xml,linenums]
----
<email:pop3-matcher
	subjectRegex="a?*[0-9]"
fromRegex="a?*[0-9]"
	receivedSince="2015-06-03T13:21:58+00:00"
	receivedUntil="2015-07-03T13:21:58+00:00"
	sentSince="2015-06-03T13:21:58+00:00"
	sentUntil="2015-07-03T13:21:58+00:00"
/>
<email:pop3-matcher>
----

[NOTE]
The POP3 protocol does not ensure a received date is present, it depends on each POP3 server implementation.

.Example IMAP Matcher Definition
[source,xml,linenums]
----
<email:imap-matcher
	subjectRegex="a?*[0-9]"
fromRegex="a?*[0-9]"
	receivedSince="2015-06-03T13:21:58+00:00"
	receivedUntil="2015-07-03T13:21:58+00:00"
	sentSince="2015-06-03T13:21:58+00:00"
	sentUntil="2015-07-03T13:21:58+00:00"
read="true|false"
deleted="true|false"
recent="true|false"
answered="true|false"
/>
<email:imap-matcher>
----

All of the attributes are optional. They are ignored if not provided. All attributes are considered together (implicit `AND`) when qualifying files.

Let’s take a look at each individual attribute:

Shared attributes
`subjectRegex`: regex that will match with the subject.
`fromRegex`: same as subject-pattern but will match from addresses.
`receivedSince`: an inclusive lower boundary for the email received date stamp expressed as either a DateTime instance or a String in ISO-8601 format.
`receivedUntil`: an inclusive upper boundary for the email received date stamp expressed as either a DateTime instance or a String in ISO-8601 format.
`sentSince`: an inclusive lower boundary for the email sent date stamp expressed as either a DateTime instance or a String in ISO-8601 format.
`sentUntil`: an inclusive upper boundary for the email sent date stamp expressed as either a DateTime instance or a String in ISO-8601 format.

==== IMAP Only Attributes

`read`: matches seen emails.
`deleted`: matches deleted emails.
`recent`: matches recent emails. Folder implementations set this flag to indicate that this message is new to this folder, that is, it has arrived since the last time this folder was opened.
`answered`: matches answered emails.

The filter can be defined globally, or inline within an operation.

.Example of top level, reusable matcher
[source,xml,linenums]
----
<email:pop3-matcher name="matcher" receivedUntil="2015-06-03T13:21:58+00:00" seen="true"/>

<flow name="flow">
	<email:pop3-list config-ref="config" matchWith="matcher" />
</flow>
----


.Example of inner, not reusable, matcher
[source,xml,linenums]
----
<flow name="flowWithMatcher">
	<email:list config-ref="config"/>
		<email:pop3-matcher receivedUntil="2015-06-03T13:21:58+00:00"/>
	</email:list>
	...
</flow>
----

[[list]]
=== List Emails

List all the emails in the configured mailbox folder that match with the specified matcher criteria.

Use `<email:list-pop3 … />` or `<email:list-imap … />`

.Example POP3 List Operation
[source,xml,linenums]
----
<email:list-pop3 config-ref="config" mailboxFolder="INBOX">
	<email:matcher since="2015-06-03T13:21:58+00:00"
seen="false"
until="2015-07-03T13:21:58+00:00">
</email:matcher>
</email:list-pop3>
----

Parameters:

`mailboxFolder`: the folder name from which email is fetched. Defaults to `INBOX`
`matcher`: a matcher to filter the output emails
`deleteAfterRetrieve`: if true, deletes the email messages after being retrieved.
`pageSize`: Page size to be used for the fetching

The matcher can be defined inline or outside the operation.


==== Email Attributes Listed

Email metadata is returned as attributes of the `MuleMessage` at every `list` operation execution. If multiple emails are returned, `list` returns multiple Mule messages.

Email attributes contain all the metadata of an email, such as subject, recipients, etc.

For POP3 configured operations, the attributes are:

`From address`: the address of the person who has sent the email
`To addresses`: all the to (primary) email addresses to send the email to.
`Cc addresses`: all the carbon copy/forward email addresses to send the email to.
`Bcc addresses`: all the blind carbon copy/forward email addresses to.
`Reply to addresses`: all the email addresses that this email should reply to.
`Subject`: the subject of the email
Sent date: the sent date of the email.
`Received date`: the received date of the email
`Id`: the unique identifier number of the email
`Number`: the number of the email in the mailbox in a particular moment.

For *IMAP* configured operations the same attributes apply but in addition, a set of flags that marks the emails to add more specific information, POP3 mailboxes don't have flag support.

`Flags`: an `EmailFlags` object that contains the following flags:

* `answered` (boolean)
* `deleted` (boolean)
* `draft` (boolean)
* `recent` (boolean)
* `seen` (boolean)

==== Notes

* This operation is paginated, and the page size represents the size of the page that will be fetched from the email server before applying the matcher criteria.
** If none of the emails in the retrieved block match the criteria, another page will be fetched until at least one email is found, or all the emails have been retrieved.
** The implementation of the list operation for each protocol is the same, but each one receives a different matcher implementation used in the list command, so creating an operation for each protocol enables the creation of each matcher from xml, enforcing the one for the desired protocol.
* A new `MuleMessage` carrying a multipart payload is created for each fetched email from the folder, where the payload contains the text body of the email and the attachments as other payload parts. The other metadata is carried in the email attributes, such as subject, received date, flags,  etc.
* If no matcher is specified it will fetch all folder emails.
* For IMAP configurations, opening email depends on how it was configured--if the email is not opened the content is not accessed and the body and attributes are not fetched, and the email is not marked with the `SEEN` flag.

[[store-email]]
=== Store Email

Stores the specified email of `emailId` into the configured `localDirectory` as a .txt file.

`<email:store config-ref="config" mailboxFolder="INBOX" localDirectory="/Users/home"/>`

==== Parameters

`mailboxFolder`: the folder name where the emails that wants to be deleted are located. Defaults to INBOX
`emailId`: an optional email number to look up in the folder and delete.
`localDirectory`: the local directory where the emails are going to be stored.
`fileName`: the prefix name of the file that is going to be stored, the operation appends the id of the email and the received date (if have) at the end. As default the prefix is the subject of the email.
`overwrite`: if a file with the same name already exists should be overwritten or not. Defaults to false.

[[mark-as-read]]
=== Mark as Read

Marks the email with the given email id as read email by setting the `SEEN` flag on it.

`<email:mark-as-read config-ref="config" emailId="123">`

==== Parameters

`mailboxFolder`: the folder name where the emails that wants to be deleted are located. Defaults to `INBOX` +
`emailId`: an optional email number to look up in the folder and delete.

[[mark-as-deleted]]
=== Mark as Deleted

Marks the email with the given email id as deleted by setting the `DELETED` flag on it; this way the emails are scheduled for deletion.

.Marking a single email as deleted
`<email:mark-as-deleted config-ref="config" emailId="123">`

Falling back to mark all the emails that are in the incoming `MuleMessage` if any.

`<email:mark-as-deleted config-ref="config"/>`

==== Parameters

`mailboxFolder`: the folder name where the emails that wants to be deleted are located. Defaults to `INBOX`. +
`emailId`: an optional email number to look up in the folder and delete.

[[expunge-folder]]
=== Expunge Folder Emails

Eliminates from the mailbox all the messages scheduled for deletion with the `DELETED` flag set.

.Expunge the emails from the `RECENT` folder.

`<email:expunge-folder config-ref="config" mailboxFolder="RECENT">`

==== Parameters

`mailboxFolder`: the folder name where the emails that wants to be deleted are located. Defaults to `INBOX`.

[[email-builder]]
=== Email Builder

Construct an email with attributes typically defined when

.Email Builder Example
[source,xml,linenums]
----
<email:email-builder>
<email:body charset="#[flowVars.encoding]">
   <email:content>#[payload]</email:content>
</email:body>
	<email:to-addresses>
	<email:to-address value="recip@mule.com"/>
	<email:to-address value="recip2@mule.com"/>
<email:to-addresses>
<email:cc-addresses> … </email:cc-addresses>
<email:bcc-addresses> … </email:bcc-addresses>
<email:attachments>
	<email:attachment id="text" content="..." contentType="text-plain" />
</email:attachments>
</email:email-builder>
----

==== Parameters

Subject: the subject of the email
Content: the body of the email. Represented by an EmailContent object.
Attachments: the attachments that are bounded with the email
To addresses: the primary addresses of the email message recipients
Cc Addresses: the carbon copy addressed of the email message recipients
Bcc Addresses: the blind carbon copy addressed of the email message recipients
Headers: a custom set of headers that are bounded with the email

[[email-body]]
=== Email Body

In the `email-body` you can specify the body of the email, content type and character encoding of the email content.

[source,xml,linenums]
----
<email:email-body body="Email Content" contentType="text/plain" charset="UTF-8"/>
----

* `contentType`: the content type of the email content. Of type text and one of its subtypes "text/*". Defaults to text/plain
* `body`:  the content of the email itself.
* `charset`: the character encoding of the email content. Defaults to the mule charset.

[[email-attachment]]
=== Email Attachment

Represents and enables the construction an email attachment with content, content type and an identifier.

The `<email:attachment>` element defines a message that can be sent or forwarded.

[source,xml,linenums]
----
<email:attachments>
<email:attachment content="#[payload]" contentType="application/octet-stream"id="3"/>
</email:attachments>
----


`content`:  the content of the attachment itself, of any type.
`contentType`: the content type of the the attachment, represented as {primaryType}/{subType}[; charset={charset}]
`id`: the name identifier of the email attachment.

----
