= To Store Email over IMAP(S)
:keywords: email, connector, configuration, imap
:toc:
:toc-title:

toc::[]

Anypoint Studio, Design Center: *Email* connector

[[short_description]]
Stores an email into a specified local directory based on the ID of the email. Saves the email as a `txt` file and bases the file name on the subject.

[[store_email]]
. After adding the *Email* connector to your flow, select the *Store* operation.
. Set up or select an IMAP or IMAPS configuration for the operation (see link:email-imap-to-set-up[To Set Up an IMAP or IMAPS Email Configuration]).
. Specify the *Local Directory* to store the file, for example, `/Users/someuser/email/archive`.
. If you are selecting file from a folder other than the inbox, provide the name for the *Mailbox Folder*, for example, `Sent`. _TODO, VERIFY VALID VALUES_
. Provide any optional settings: _TODO, TODO_
  ** Opt to provide the *File Name* of the file that you want to store.
  ** Opt to provide an *Email ID* of the email that you want to store. _TODO, HOW TO GET EMAIL ID?_
  ** Use the *Should Overwrite* option if you want to overwrite a file with the same name.

[[see_also]]
== See Also

include::include_link_list.adoc[tags=set-reconnection-config]

include::include_link_list.adoc[tags=tech-ref-email]

////
[[errors]]
== Errors
_TODO_

* EMAIL:RETRY_EXHAUSTED
* EMAIL:CONNECTIVITY
////
