= To Set Up a File Connector Configuration
:keywords: file, connector, configuration
:toc:
:toc-title:

Though the File connector does not always require configuration, it is good practice to define one. The most important configuration parameter is the Working Directory (`workingDir`), which is the path to a directory that is treated as the root of every relative path that you specify with this connector. If you do not provide a working directory, the connector configuration will default to the value of the `user.home` system property. If the system property is not set, the connector will fail to initialize.

You can also set the default encoding to use when writing files. It defaults to Mule runtime’s default encoding. If you use any File connector operations without referencing a configuration, the operation use the default values.

. After adding a File connector to your flow, provide a Name for the configuration.
. Perform any optional tasks you need, for example:
** Specify a Working Directory as the root for all relative paths that you set for this connector, for example, `/Users/myname/workingdir`.
** Provide a Reconnection Strategy.
** Set the default write encoding for File connector operations that use this connection.
+
Note that you can override this setting from a specific File operation.

== XML Example

This example sets a working directory for the File connector.

----
<file:config name="File_Config" doc:name="File Config" doc:id="d10311e4-4d4a-427d-ae04-1717840d410d" >
  <file:connection workingDir="/Users/me/myfiles" />
</file:config>
----

[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]
* link:/connectors/file-about-the-file-connector[About the File Connector]
* link:/mule-user-guide/reconnection-strategy-about[About Reconnection Strategies]


////
== Troubleshooting on Mac?
Do you want the application “AnypointStudio.app” to accept incoming network connections?

Clicking Deny may limit the application’s behavior. This setting can be changed in the Firewall pane of Security & Privacy preferences.
////
