= About the File Connector
:keywords: file, connector, matcher, directory, listener
:toc:
:toc-title:

The File connector handles files and folders on a locally mounted file system. Its main features include:

* The ability to read files or fully list directory contents on demand.
* Support for common file system operations such as copying, moving, renaming, deleting, and creating directories.
* Support for locking files on the file system level.
* File matching functionality.
* A design that is fully consistent with the FTP, and SFTP connectors. The same set of operations is available on all four connectors, and they behave _almost_ the same way.

[[connection_settings]]
== Configuring the connector

Though the File connector does not always require configuration, it is good practice to define one. The most important configuration parameter is the Working Directory (`workingDir`), which is the path to a directory that is treated as the root of every relative path that you specify with this connector. If you do not provide a working directory, the connector configuration will default to the value of the `user.home` system property. If the system property is not set, the connector will fail to initialize.

You can also set the default encoding to use when writing files. It defaults to Mule runtime’s default encoding. If you use any File connector operations without referencing a configuration, the operation will use the default values.

This example sets a working directory for the File connector:

[source, xml, linenums]
----
<file:config name="File_Config">
  <file:connection workingDir="/Users/me/myfiles" />
</file:config>
----

== Attributes

When reading or listing files, users are often not only interested in the file's content, but in its metadata as well (for example, file name, full path, size, creation and modification timestamps, and so on). The file connector will use the Mule Message Attributes to access this information, while the Message Payload will always contain the file's content. For details on the File Attributes structure, please read the link:file-documentation[techincal reference].

== See Also
* link:file-read[To Read files]
* link:file-write[To Write files]
* link:file-list[To List files]
* link:file-on-new-file[To Listen for New or Modified Files]
* link:file-copy-move[To Copy or Move Giles]
* link:file-documentation[File Connector Technical Reference]
