= About the File Connector
:keywords: file, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

Associated products: Anypoint Studio, Design Center

The File connector can operate on or retrieve information about files on a locally mounted file system.

_TODO: IS THIS CORRECT? Special file-like device files are not supported (for example, `/dev/null`)._

This connector consists of a link:#file-about-the-file-listener[File Listener] and a number of file operations:
* link:#common-to-read-a-file[Read Files]
* link:#common-to-write-to-a-file[Write to File]
* link:#common-to-list-files[List Files]
* link:#common-to-copy-a-file[Copy Files]
* link:#common-to-move-a-file[Move Files]
* link:#common-to-rename-a-file[Rename Files or Directories]
* link:#common-to-delete-a-file[Delete Files]
* link:#common-to-match-file-properties[Define a Matcher] to filter lists of files
* link:#poll-watermark[Poll a Directory or File] with the `<poll>` and `<watermark>` elements
* link:#common-to-create-a-directory[Create Directory]
* link:#to-listen-for-file-events[Configure as a Directory Listener] for created, updated or deleted files

_TODO, TODO_ Supporting operations:
* _TODO:_ Obtaining the MIME type of a file when reading or listing files or obtaining resolved MIME type using `#[dataType.mimeType]`
*  _TODO:_ Recursing through a directory and its subdirectories.
*  _TODO:_ link:#common-to-set-file-metadata[Retrieving File Metadata]
//MG include how to limit recursion level with walker once implemented



[[see_also]]
== See Also
_TODO, TODO_
* See the link:/connector[Connector Technical Reference] for all operations and attributes.
* link:/connectors[Connectors]
* link:/mule[Mule]

////
TODO: READ THROUGH THE WHAT FOLLOWS TO FIND GENERAL INFO THAT SHOULD GO HERE.
SEE WHAT OF THE REST FITS INTO OTHER FILES:

* If the `directory` path does not map to a directory then you get a `ConfigurationException`.
* You can optionally disable up to two of the types of events by setting two of `notifyOnCreate`, `notifyOnUpdate` or `notifyOnDelete` to false.
** If you disable all three, the listener does not work and a `ConfigurationException` is thrown.
* The listener should not be considered the recommended approach over a poll-list-watermark approach
** The tradeoff between poll and listener performance is reliability. Since operating system events don't generally include the concept of transaction or replay, there's no way to guarantee that an event is going to be captured if failure or server crash happens.
* Use the recursive attribute  to listen on a subdirectory (default: false).
* payload is a `FileInputStream` instance when the triggered event type is `CREATE` or `UPDATE`,
* when a file is deleted as the file no longer exists anymore the `MuleMessage` has a `NullPayload` and a `FileAttributes` instance.
* when the event refers to the creation of a directory, the `MuleMessage` has a `NullPayload` and a `FileAttributes` instance.
* the `FileAttributes` instance contained in the created Message holds the event type (`CREATE` | `UPDATE` | `DELETE`).
*  if file is deleted, file attributes are not available.
** Only `path` and `name` attributes are available.
** Message attributes are an instance of `DeletedFileAttributes`.
** If unavailable attribute requested, throws `IllegalStateException`.
* if event references a deleted directory, then the payload is also a NullPayload

==== Notes

* Reads the file in a given path and returns a `MuleMessage` with an `InputStream` as the payload
* Returns a `FileAttributes` instance as attributes.
* By default, if the file does not exists an `IllegalArgumentException` is thrown.
* If using "target" to load the `InputStream` make sure that the returned `InputStream` is fully consumed or eventually


[IMPORTANT]
The underlying file handle and file system lock (if locking was enabled) will only be released once the `InputStream` is closed.
+
* If not able to write the file or create directories, whether due to no write permissions, problem with the file system, etc, a `MuleRuntimeException` is thrown.
* If the path points to a directory instead of a file, an `IllegalArgumentException` will be thrown.


==== Laziness
_TODO: NOT SURE WHETHER CUSTOMERS NEED THIS INFO OR WHERE TO PUT IT JUST YET_
Both the payload `InputStream` and the `FileAttributes` POJO are as lazy as possible. Creating a message with an `InputStream` payload returned won’t actually mean that it opened a file handler with the OS. It is only opened when the stream is read. Therefore, if many files are returned from a `list` operation, the user doesn’t have to worry about closing the ones that were discarded. At the same time, the `FileAttributes` POJO won’t actually fetch the file metadata until the first getter is invoked.
////
