= To Set Up a File Connector Configuration
:keywords: file, connector, configuration
:toc:
:toc-title:

toc::[]

Associated products: Anypoint Studio, Design Center

This configuration is a prerequisite for all File connector operations.

. After adding a File connector or listener to your flow, provide a Name for the configuration.
. Perform any optional tasks you need:
  ** Specify a Working Directory as the root for all relative paths that you set for this connector, for example, `/Users/myname/workingdir`. Defaults to your User Home (`user.home`) if the system property is set.
  ** Provide a Reconnection Strategy.
  ** Opt to Disable Validation of the connection to the directory.

// TODOS:
// Reconnection strategy Defaults to _TODO_.
// _TODO: SAY WHY YOU MIGHT DISABLE validation

////
== Troubleshooting on Mac?
Do you want the application “AnypointStudio.app” to accept incoming network connections?

Clicking Deny may limit the application’s behavior. This setting can be changed in the Firewall pane of Security & Privacy preferences.
////

// INCLUDED ANYMORE? ** Specify a *Default Write Encoding*. _TODO: SAY WHY YOU MIGHT WANT TO SPECIFY THIS._

////
===== test case =====
<file:config name="file">
    <file:connection workingDir="${workingDir}" />
</file:config>
=====
////


[[see_also]]
== See Also

* link:/connectors/file-documentation[Connector Technical Reference]
