= About the File Connector
:keywords: file, connector, matcher, directory, listener
:toc:
:toc-title:

The File connector handles files and folders on a locally mounted file system. Its main features include:

* The ability to read files or fully list directory contents on demand.
* Support for common file system operations such as copying, moving, renaming, deleting, and creating directories.
* Support for locking files on the file system level.
* File matching functionality.

//_TODO: IS THIS CORRECT? Special file-like device files are not supported (for example, `/dev/null`)._

The File connector provides the same set of operations as the FTP connector.

[cols="1,3", options="header"]
|===
| File Connector Operations |

| Copy
| Copies the file from a source path to a target path.

| Create Directory
| Creates a new directory at a given directory path.

| Delete
| Deletes a file at a given path, provided that it is not locked.

| List
| Lists all files in a given directory path that match a specified matcher, such as file name patterns, dates, locations, and sizes.

| Move
| Moves a file from a given source path to a target path.

| Read
| Reads the file in a given path, sets its content in the
payload, and sets its attributes.

| Rename
| Provides a new file name for the a file at a given path.

| Write
| Writes content to a file. It can also map data and perform transformations similar to the Transform component.
|===

More detailed information about these operations is available in the _File Connector Technical Reference_.

[[connection_settings]]
== Connection Settings

The File connector configurations specify these properties:

* Working Directory where your files are located, which is required.
* [Optional] Reconnection strategies for cases where the initial attempt to connect fails.
* [Optional] A default write encoding for all files to which you write content. You can override this default encoding when specifying a particular Write operation.

Advanced connection settings available for all protocols:

  ** Connection pooling
  ** Option to disable validation of the connection
  ** Default write encoding
  ** Timeouts for connections and responses

== Attributes

In addition to handling the content of a file (the message payload), the connector can use file attributes (`fileAttributes`), such as the file name, path, size, and timestamp. For example, the List operation provides fields for matching the values of file attributes so that you can narrow the list of files to return. It is also possible to perform DataWeave expressions that use file attributes.

[[mime_encoding_locks]]
== Mime Types, Character Encoding, Locks

Both the Read and Write operations support configuring a mime type (such as `application/xml`) and character encoding (such as `UTF-8`) on the payload, and the Read operation allows you to place a lock on the output file.

* Encoding - The default encoding is the Mule Runtime default. Setting the correct encoding in your Read operation can help ensure that any DataWeave expressions you use in your configurations are handled properly. For example, it can help with type coercion and with generating the correct output.

* Mime Type - The connector attempts to determine the mime type of a file based on its extension if you do not provide one when configuring the Read operation. You might specify the mime type of the content if you know it and want to ensure that the connector applies that mime type to the file.

* Lock - A lock prevents other processes and flows in a Mule app from accessing the file while the Read operation is in progress. If your app is running in a cluster, the lock applies across all nodes in that cluster. So other operations in the app or cluster cannot read it, write to it, move it, delete it, or perform other changes to it. However, processes external to your Mule app or cluster are not affected by the lock.
+
Note that a lock that is distributed across a cluster can significantly slow the performance of your app.
+
For the Read operation, the lock is released automatically once the file is fully read, or the flow that locked the file ends. The Write operation releases the lock automatically once the operation is complete. If the file is locked by another operation when you try to read or write to it, the connector will throw an error to indicate that it cannot lock the file.

== See Also
* link:/connectors/file-documentation[File Connector Technical Reference]
* link:/connectors/file-to-set-up-a-file-connector-config[To Set Up a File Connector Configuration]
* link:/connectors/common-to-copy-a-file[To Copy a File]
* link:/connectors/common-to-create-a-directory[To Create a Directory]
* link:/connectors/common-to-delete-a-file[To Delete a File]
* link:/connectors/common-to-list-files[To List Files]
* link:/connectors/common-to-move-a-file[To Move a File]
* link:/connectors/common-to-read-a-file[To Read a File]
* link:/connectors/common-to-rename-a-file[To Rename a File]
* link:/connectors/common-to-write-to-a-file[To Write to a File]
* link:/connectors/common-about-file-attributes[About File Attributes]
