= About the File Connector
:keywords: file, connector, matcher, directory, listener
:toc:
:toc-title:

Release Notes: link:/release-notes/connector-file[File Connector Release Notes]

The File connector handles files and folders on a locally mounted file system. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::common-file-actions.adoc[]

[[connection_settings]]
== Configuring the File Connector

The File connector does not always require configuration. However, it is good practice to define one. The most important configuration parameter is the Working Directory (`workingDir`), which is the path to a directory that is treated as the root of every relative path that you specify with this connector. If you do not provide a working directory, the connector configuration will default to the value of the `user.home` system property. If the system property is not set, the connector will fail to initialize.

You can also set the default encoding to use when writing files. It defaults to Mule runtime's default encoding. If you use any File connector operations without referencing a configuration, the operation will use the default values.

This example sets a working directory for the File connector:

[source, xml, linenums]
----
<file:config name="File_Config">
  <file:connection workingDir="/Users/me/myfiles" />
</file:config>
----

//INCLUDED IN FTP, SFTP, FILE
include::common-file-attributes.adoc[]

[[see_also]]
== See Also

link:file-documentation[File Connector Documentation Reference]

link:file-read[To Read Files]

link:file-write[To Write Files]

link:file-list[To List Files]

link:file-on-new-file[To Listen for New or Modified Files]

link:file-copy-move[To Copy or Move Files]
