= About the File listener

:keywords: file, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

Associated products: Anypoint Studio, Design Center

Listens for file creation, deletion, or update events that take place within a directory or on files in its subdirectories. Examples include _trigger files_, the addition of _transaction files_ to a drop folder, updates to file settings, and so on.

Applicable connectors:
link:about-file-connector[File], link:about-ftp-connector[FTP]
//* Reference: _ANY REFERENCE FOR THIS?_

*Performance vs. Reliability*
Instead of using the File listener, you can use the Poll scope to check for filesystem-related events at regular intervals. In general, the File listener performs better than the Poll scope, while the Poll scope is more reliable than the listener. However, some operating systems (such as older OSX versions) do not support file system notifications, so they revert to polling, which
eliminates any performance gain.

Note that you should use the Poll scope if you need to ensure that events are not lost in cases of a failure or server crash, for example, in highly concurrent scenarios where a file is associated with many events per second. For an example that uses polling, see link:common-to-list-files[To List Files], which uses the *List* operation within a Poll scope and a watermark.


[[see_also]]
== See Also
link:file-to-listen-for-file-events[To Listen for File Events]

////
==== Operating System Limitations

Listener behavior might be slightly different depending on the OS to which it is deployed.

The main differences are usually (but not exclusively) related to:

* Overflows: In highly concurrent scenarios a given file might be associated to hundreds of events per second. Some OS might not be able to handle that gracefully and decide to drop some of those events or even fail.
* Polling: Some operation systems (like older versions of OSX) don't actually support file system notifications. In those cases, the JRE decides to compensate by using a high frequency poll, in which case the listener becomes pretty much the same as a poll element.
////
