= Example: To List Files (FTP, SFTP)
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

toc::[]

// For Anypoint Studio, Design Center: FTP connector

This example lists files with the FTP or SFTP connector.

. Provide a source to your flow, such as a Scheduler trigger with a Fixed Frequency of every 30 seconds (where Frequency = 30 and Time Unit = Seconds).
+
. Set up a List operation for the FTP or SFTP connector:
.. Set up or select a configuration for the FTP or SFTP connector.
+
You can set up an <<see_also,FTP or SFTP configuration>>.
+
.. Provide the Path (or Directory Path) to the files
+
Example: `/output`
+
. After the List operation, add For Each to your flow.
+
You can retain the default configuration.
+
. Within the For Each component, add a Logger.
+
* In Design Center, use the f(x) button to provide this Message: `attributes.fileName`
* In Anypoint Studio, add the following Message to your Logger: `#[attributes.fileName]`
. Deploy or Run your application.
. Once your application is deployed (or running), check the Logs or Console.
+
You can find the file names in the log, for example:
+
----
INFO 12:40:49 my_file.txt
INFO 12:40:49 my_file2.txt
INFO 12:40:49 my_record_2017-07-29T21:35:52.397Z.json
INFO 12:40:49 my_record_2017-07-29T21:35:58.513Z.json
----

[[see_also]]
== See Also

link:ftp-to-write-a-file[Example: To Write and Read a File]

link:ftp-to-set-up-ftp[To Set Up an FTP Configuration]

link:sftp-to-set-up-sftp[To Set Up an SFTP Configuration]


////
link:common-to-perform-basic-file-operations[To Perform Basic File Operations]
////
