= To Set Up an FTP Configuration
:keywords: ftp, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

// Anypoint Studio, Design Center: FTP connector

[[short_description]]
An FTP configuration is required for all FTP operations with the FTP connector.

. Open the FTP Configuration from an FTP operation.
+
You can open it from the Add or Edit link within any FTP operation in your flow.
+
. Provide a Name for the configuration.
+
Example: FTP configuration
+
. Provide connection settings:
+
* Connection Type: FTP Connection
* Host domain name or server IP address.
+
Example: my.ftpsite.com
+
* Port for the transport protocol.
+
Defaults to `21`.
+
* Password (if required by the host).
. Provide a Working Directory (if needed).
+
Example: `my/working/dir`
+
. Provide a Transfer Mode (one of these):
+
* Binary (default)
* Ascii
+
A use case for the Ascii transfer mode is when you are transferring files with text-based formats between operating systems that handle line breaks differently, such as Windows and Unix.
+
. Indicate whether to use Passive mode to establish the data ports.
+
Defaults to `true`.
+
. Click Test to check your connection to the server.
+
You should make sure that the connection is successful before running your application. If the Test button is disabled, then a worker to test the connection is not available yet. You can come back later and test the connection once the button is enabled.
+
. Save the configuration.

[[see_also]]
== See Also

include::include_link_list.adoc[tags=sftp-set-up]

include::include_link_list.adoc[tags=set-connection-timeout]

include::include_link_list.adoc[tags=ftp-connector]

include::include_link_list.adoc[tags=tech-ref-ftp]


////
TODO: MAKE SURE ALL THESE ARE COVERED:

disable validation
pooling profile
default write encoding
timeout configuration
////
