= Example: To Write a File to the FTP Server
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

toc::[]

// For Anypoint Studio, Design Center: FTP connector

This example writes a JSON file to an FTP server, then reads the file and passes its contents (payload) into the logs.

. Add an HTTP Listener as a trigger with the Path to `/write`.
+
. Set up a Write operation for the FTP connector:
.. Set up or select a configuration for the FTP connector.
+
You can set up an <<see_also,FTP or SFTP configuration>>.
+
.. Provide the File Path to a JSON file.
+
Example: `/in/full_record.json`
+
.. Provide JSON content like this:
+
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org"
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net"
  }
]
----
+
.. Set the Write Mode to Create New.
. After the Write operation, configure a Read operation for the FTP connector:
.. Continue to use the same FTP connection configuration that you used for the Write operation.
.. Provide a Path to your new JSON file.
+
`/in/full_record.json`
+
. Add a Logger to the end of your flow with `payload` as the message.
. Deploy, Run, or Sync your application.
. Once the app is running, copy the link to the app to a browser, and append the Listener path, for example:
+
`myftpproject-abcd.some.cloudhub.io/write`
+
. Check the logs.
+
The `/in/full_record.json` content should appear as INFO on a single line:
+
----
INFO14:11:56
[{id=1, name=Leanne Graham, username=Bret, email=Sincere@april.biz, address={street=Kulas Light, suite=Apt. 556, city=Gwenborough, zipcode=92998-3874, geo={lat=-37.3159, lng=81.1496}}, phone=1-770-736-8031 x56442, website=hildegard.org}, {id=2, name=Ervin Howell, username=Antonette, email=Shanna@melissa.tv, address={street=Victor Plains, suite=Suite 879, city=Wisokyburgh, zipcode=90566-7771, geo={lat=-43.9509, lng=-34.4618}}, phone=010-692-6593 x09125, website=anastasia.net}]
----
+
[Optional] You can use a locally hosted FTP client, such a FileZilla, to see the new JSON file.

[[see_also]]
== See Also

include::include_link_list.adoc[tags=ftp-set-up]

include::include_link_list.adoc[tags=sftp-set-up]

include::include_link_list.adoc[tags=ftp-connector]

include::include_link_list.adoc[tags=tech-ref-ftp]

////
include::include_link_list.adoc[tags=perform-basic-file-ops]
////
