= Dynamic Connections with the SFTP or FTP Connector (Studio)
:keywords: ftp, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center: FTP connector

// TODO: DO NOT ADD TO REPO UNTIL REQUIRED COMPONENTS IN THE RELEASE OR MARIANO PROVIDES ALTERNATIVE

[[short_description]]
Many integrations require connecting to different servers depending on a certain condition, for example:

* Connecting to different invoice storage servers depending on the branch that emitted the invoice.
* Connecting to different servers depending on a given integration subject, such as a multi-tenant use case.

To accommodate for these use cases, the configuration element supports expressions so that connection parameters can evaluate these conditions and connect to the correct server.

Example of dynamic connection that uses the SFTP connector:

----

<sftp:config name="SFTP_Config" doc:name="SFTP Config" >
		<sftp:sftp-connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
	</sftp:config>

	<flow name="streaming-multitenantFlow" >
		<http:listener config-ref="HTTP_Listener_config" path="/multitenant" doc:name="Listener" />

		<set-variable variableName="content" value="#[payload]" doc:name="Variable" />
		<file:read config-ref="File_Config" path="recipients.csv" doc:name="Read" outputMimeType="application/csv" />
		<ee:transform doc:name="Transform Message">
			<ee:message>
				<ee:set-payload ><![CDATA[%dw 2.0
output application/java
---
payload map using (row = $) {
    host: row.Host,
    user: row.User,
    password: row.Password
}]]>
				</ee:set-payload>
			</ee:message>
		</ee:transform>
		<foreach doc:name="For Each" >
			<sftp:write config-ref="FTP_Config" doc:name="Write" path="demo.txt">
				<sftp:content >#[content]</sftp:content>
			</sftp:write>
		</foreach>
		<set-payload doc:name="Set Payload" value="Multicast OK"/>
	</flow>
----

To use the FTP connector in the example instead of SFTP, the only difference is to replace the prefix `sftp:` to element name with `ftp:`, for example:
`<ftp:config/>`, `<ftp:ftp-connection/>`, `<sftp:write/>`, `<ftp:content/>`

[[see_also]]
== See Also

link:sftp-about-the-sftp-connector[About the SFTP Connector]

link:sftp-documentation[SFTP Connector Technical Reference]

////
examples identity files
+
Examples: ~/.ssh/identity, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_rsa
+
////
