= Connection Pooling Reference
:keywords: email, ftp, connector, configuration
:toc:
:toc-title:

toc::[]

// Anypoint Studio, Design Center: *Email*, *FTP*, _? TODO, others ?_ connectors

Connection Pooling allows you to use a set of logical connection instances that share a physical connection to a server. Pooling can speed operations, such as file transfers between an FTP client and server. Once a physical connection to the server is established by an operation that is configured to use the pool, other similarly configured operations can make use of that connection instead of opening a new physical connection to the server.

* Max Active: Maximum number of active connections allowed in the connection pool at one time.
* Max Idle: Maximum number of idle connections allowed in the connection pool at one time.
* Max Wait: Maximum number of milliseconds to wait for an available connection before aborting.
* Min Eviction Millis: Minimum number of milliseconds that a connection instance can remain idle before it is marked for eviction from the pool. A negative value prevents evictions from the pool based on an idle state.
* Eviction Check Interval Millis: The number of milliseconds before connection instances that are marked for eviction are removed from the pool. A negative value prevents the eviction of connection instances.
* Exhausted Action: Specifies the behavior of the pool when it becomes exhausted.  WHEN_EXHAUSTED_GROW, which will create a new Mule instance and return it, essentially making maxActive meaningless. If a positive maxWait value is supplied, it will block for at most that many milliseconds, after which a NoSuchElementException will be thrown. If maxThreadWait is a negative value, it will block indefinitely.
  ** When Exhausted Grow: Creates a new connection
  ** When Exhausted Wait: Blocks (or waits) until a new or idle object is available.
  ** When Exhausted Fail: Throws an exception when the pool is exhausted.
* Initialisation Policy: Determines how components in a pool should be initialized.
  * Initialise None: Does not load any components into the pool on startup.
  * Initialise One: Loads one initial component into the pool on startup.
  * Initialise All: Loads all components into the pool on startup.
* Disabled: Disables connection pooling. A new physical connection to the server would have to be established for each separate operation in the flow that uses that config.
