= To Set Up an SFTP Configuration
:keywords: ftp, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center: FTP connector

[[short_description]]
An SFTP configuration is required for all SFTP operations with the FTP connector. The FTP connector supports SFTP connections and file transfer operations over SFTP.

. Open the FTP Configuration window from an operation.
+
You can open it from any FTP operation in your flow.
+
. Provide a Name for the configuration.
+
Example: SFTP configuration
+
. Provide connection settings:
+
* Connection Type: SFTP Connection
* Host domain name or server IP address.
+
Example: my.sftpsite.com
+
* Port for the transport protocol.
+
Defaults to `22`.
+
* Password (if required by the host).
* Passphrase or a password-protected key in an Identity File (if needed).
* Identity File location for a PKI private key (if needed).
+
This file supplies the private key that is used for public key authentication.
+
. Provide a Working Directory (if needed).
+
Example: `my/working/dir`
+
. Provide the Preferred Authentication Methods (one of these, if needed):
+
* gssapi_with_mic
* public_key
* keyboard_interactive
* password
+
. Provide the path to the Known Hosts File (if needed) to check whether the server key matches the key in the file.
+
The operation aborts if keys do not match.
+
. Click Test to check your connection to the server.
+
You should make sure that the connection is successful before running your application. If the Test button is disabled, then a worker to test the connection is not available yet. You can come back later and test the connection once the button is enabled.
+
. Save the configuration.

[[see_also]]
== See Also

include::include_link_list.adoc[tags=ftp-set-up]

include::include_link_list.adoc[tags=set-connection-timeout]

include::include_link_list.adoc[tags=ftp-connector]

include::include_link_list.adoc[tags=tech-ref-ftp]

////
examples identity files
+
Examples: ~/.ssh/identity, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_rsa
+
////
