= Example: To List Files on an FTP Server
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

toc::[]

// For Anypoint Studio, Design Center: FTP connector

This example uses FTP connector operations to list files on an FTP server.

. Provide a source to your flow, such as a Scheduler trigger with a Fixed Frequency of every 30 seconds (where Frequency = 30 and Time Unit = Seconds).
+
. Set up a List operation for the FTP connector:
.. Set up or select a configuration for the FTP connector.
+
You can set up an <<see_also,FTP or SFTP configuration>>.
+
.. Provide the Path (or Directory Path) to the files
+
Example: `/output`
+
. After the List operation, add For Each to your flow.
+
You can retain the default configuration.
+
. Within the For Each component, add a Logger.
+
* In Design Center, use the f(x) button to provide this Message: `attributes.fileName`
* In Anypoint Studio, add the following Message to your Logger: `#[attributes.fileName]`
. Deploy or Run your application.
. Once your application is deployed (or running), check the Logs or Console.
+
You can find the file names in the log, for example:
+
----
INFO 12:40:49 my_file.txt
INFO 12:40:49 my_file2.txt
INFO 12:40:49 my_record_2017-07-29T21:35:52.397Z.json
INFO 12:40:49 my_record_2017-07-29T21:35:58.513Z.json
----

[[see_also]]
== See Also

link:ftp-to-write-a-file[Example: To Write and Read a File]

include::include_link_list.adoc[tags=ftp-set-up]

include::include_link_list.adoc[tags=sftp-set-up]

include::include_link_list.adoc[tags=ftp-connector]

include::include_link_list.adoc[tags=tech-ref-ftp]

////
include::include_link_list.adoc[tags=perform-basic-file-ops]
////
