= About the FTP Connector
:keywords: FTP, connector, matcher, directory, listener
:toc:
:toc-title:

Release Notes: link:/release-notes/connector-ftp-1.1.0[Mule Runtime FTP 1.1.0 Release Notes]

This connector provides access to files and folders on an FTP server. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::common-file-actions.adoc[]

[[connection_settings]]
== Connecting to an FTP Server

As usual with Mule, connections are established through config elements:

[source, xml, linenums]
----
<ftp:config name="ftp">
  <ftp:connection username="anonymous" password="password" host="localhost" port="${ftpPort}" workingDir="${workingDir}"/>
</ftp:config>
----
Othen than the host, port, and credential parameters, the `workingDir` is probably the most important connection parameter. The `workingDir` is the path to a directory that is treated as the root of every relative path used with this connector. If the directory is not provided, it will default to the remote server’s default. Notice that this is exactly the same functionality as the new File Connector, except, of course, that the default value is different.

// Included in FTP, SFTP
include::common-dynamic-connections.adoc[]

//INCLUDED IN FTP, SFTP, FILE
include::common-attributes.adoc[]

[[see_also]]
== See Also

link:ftp-documentation[FTP Connector Documentation Reference]

link:ftp-read[To Read Files]

link:ftp-write[To Write Files]

link:ftp-list[To List Files]

link:ftp-on-new-file[To Listen for New or Modified Files]

link:ftp-copy-move[To Copy or Move Files]

link:ftp-documentation[FTP Connector Technical Reference]
