= About the FTP Connector
:keywords: ftp, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center connector

[[short_description]]
The FTP connector operations can handle file transfers over FTP and FTPS protocols.
// NOTE FROM MARIANO: "Ftps is a separate EE only connector" testing save

[cols="1,3", options="header"]
|===
| FTP Operations |

| Copy
| Copies the file from a source path to a target path.

| Create Directory
| Creates a new directory at a given directory path.

| Delete
| Deletes a file at a given path, provided that it is not locked.

| List
| Lists all files in a given directory path that match a specified matcher, such as file name patterns, dates, locations, and sizes.

| Move
| Moves a file from a given source path to a target path.

| Read
| Reads the file in a given path, sets its content in the
payload, and sets its attributes.

| Rename
| Provides a new file name for the a file at a given path.

| Write
| Writes content to a file. It can also map data and perform transformations similar to the Transform component.
|===

More detailed information about these operations is available in the _FTP Connector Technical Reference_.

== Connection Settings

FTP connector configurations provide settings for connecting to an FTP or FTPS server. You can create one or more configurations for each protocol.

Connection settings:

* Connection profile for the host, port, username, and password
* General settings:
  ** Working directory - Path to a directory that serves as the root of every relative path used with this connector. Defaults to the remote FTP server’s default.
  ** Transfer mode (Binary or Ascii)
  ** Whether to use Passive mode

Advanced connection settings:

  ** Connection pooling
  ** Option to disable validation of the connection
  ** Default write encoding
  ** Timeouts for connections and responses

== Attributes

In addition to handling the content of a file (the message payload), the connector can use file attributes, such as the file name, path, size, and timestamp. For example, the List operation provides fields for matching the values of file attributes so that you can narrow the list of files to return. It is also possible to perform DataWeave expressions that use file attributes.

== Mime Types, Character Encoding, Locks

Both the FTP Read and Write operations support configuring a mime type (such as `application/xml`) and character encoding (such as `UTF-8`) on the payload, and the Read operation allows you to place a lock on the output file.

* Encoding - The default encoding is the Mule Runtime default. Setting the correct encoding in your Read operation can help ensure that any DataWeave expressions you use in your configurations are handled properly. For example, it can help with type coercion and with generating the correct output.

* Mime Type - The connector attempts to determine the mime type of a file based on its extension if you do not provide one when configuring the Read operation. You might specify the mime type of the content if you know it and want to ensure that the connector applies that mime type to the file.

* Lock - A lock prevents other processes and flows in a Mule app from accessing the file while the Read operation is in progress. If your app is running in a cluster, the lock applies across all nodes in that cluster. So other operations in the app or cluster cannot read it, write to it, move it, delete it, or perform other changes to it. However, processes external to your Mule app or cluster are not affected by the lock.
+
Note that a lock that is distributed across a cluster can significantly slow the performance of your app.
+
For the Read operation, the lock is released automatically once the file is fully read, or the flow that locked the file ends. The Write operation releases the lock automatically once the operation is complete. If the file is locked by another operation when you try to read or write to it, the connector will throw an FTP:FILE_LOCK error to indicate that it cannot lock the file.

[[see_also]]
== See Also

link:ftp-documentation[FTP Connector Technical Reference]

link:ftp-to-set-up-ftp[To Set Up an FTP Configuration]

link:ftp-about-matchers[About Matchers]

link:/connectors/sftp-connector[SFTP Connector]

////
link:common-to-perform-basic-file-operations[To Perform Basic File Operations]
////
