= About the FTP Connector
:keywords: ftp, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center connector

[[short_description]]
The FTP connector operations can handle file transfers over FTP and SFTP protocols.
// NOTE FROM MARIANO: "Ftps is a separate EE only connector" testing save

[cols="1, options="header"]
|===
| FTP and SFTP Operations

| Copy, Create Directory, Delete, List, Move, Read, Rename, Write
|===

In addition to handling the content of a file (the message payload), the FTP connector can use file attributes, such as the file name, path, size, timestamp. For example, the List operation provides fields for matching the values of file attributes.

The FTP Write operation can write content to a file, as well as map data and perform transformations similar to the Transform component.

The FTP Read and Write operations both support configuring a mime type (such as `application/xml`) and character encoding (such as `UTF-8`) on the payload, and the Read operation allows you to place a lock on the output file.

* Encoding - The default encoding is the Mule Runtime default. Setting the correct encoding in your Read operation can help ensure that any DataWeave expressions you use in your configurations are handled properly. For example, it can help with type coercion and with generating the correct output.

* Mime Type - The connector attempts to determine the mime type of a file based on its extension if you do not provide one when configuring the Read operation. You might specify the mime type of the content if you know it and want to ensure that the connector applies that mime type to the file.

* Lock - A lock prevents other processes and flows in a Mule app from accessing the file while the Read operation is in progress. If your app is running in a cluster, the lock applies across all nodes in that cluster. So other operations in the app or cluster cannot read it, write to it, move it, delete it, or perform other changes to it. However, processes external to your Mule app or cluster are not affected by the lock.
+
Note that a lock that is distributed across a cluster can significantly slow the performance of your app.
+
The lock is released automatically once the file is fully read or the flow that locked the file ends. If the file is locked by another operation when you try to read it, the connector will throw an FTP:FILE_LOCK error to indicate that it cannot lock the file.

== Connection Settings

FTP connector configurations provide settings for connecting to an FTP or FTPS server. You can create one or more configurations for each protocol.

Connection settings available to FTP:

* Connection profile for the host, port, username, and password
* General settings:
  ** Working directory - Path to a directory that serves as the root of every relative path used with this connector. Defaults to the remote FTP server’s default.
  ** Transfer mode (Binary or Ascii)
  ** Whether to use Passive mode

Connection settings available to SFTP:

* Connection profile:
  ** Host, port, username, password
  ** Passphrase
  ** Identity file
* General settings:
  ** Working directory
  ** Preferred authentication methods: `gssapi_with_mic`, `public_key`, `keyboard_interactive`, `password`
  ** Known hosts file

Advanced connection settings available for all protocols:

  ** Connection pooling
  ** Option to disable validation of the connection
  ** Default write encoding
  ** Timeouts for connections and responses

[[see_also]]
== See Also

include::include_link_list.adoc[tags=tech-ref-ftp]

include::include_link_list.adoc[tags=ftp-set-up]

include::include_link_list.adoc[tags=sftp-set-up]

include::include_link_list.adoc[tags=perform-basic-file-ops]

include::include_link_list.adoc[tags=about-matchers]
