= Connection Pooling Reference
:keywords: email, ftp, connector, configuration
:toc:
:toc-title:

toc::[]

// Anypoint Studio, Design Center: *Email*, *FTP*, _? TODO, others ?_ connectors

Connection Pooling allows you to use a set of Mule connection components that share a single physical connection to a server. Pooling can speed operations, such as file transfers between an FTP client and server.

Once a physical connection to the server is established by an operation that is configured to use the pool, other similarly configured operations can make use of that connection instead of opening a new physical connection to the server.

* Max Active: Maximum number of connection components available for use in a session at one time. When the value is a negative number, any number of components can be active at one time. When the Max Active value is exceeded, the pool is exhausted.
+
Default: 5
+
* Max Idle: Maximum number of idle connection components allowed in the connection pool at one time.
+
Default: 5
+
* Min Eviction Millis: Minimum number of milliseconds that a connection component can remain idle before it is marked for eviction from the pool. A negative value prevents the eviction of idle connections from the pool.
+
Default: 1800000
+
* Eviction Check Interval Millis: The number of milliseconds before connection components that are marked for eviction are removed from the pool. A negative value prevents the eviction of connection components.
+
Default: -1
+
* Exhausted Action: Specifies the behavior of the pool when there are no available connection components.
  ** When Exhausted Grow (default): Creates a new connection component. The Max Active setting has no effect in this case. (If a positive maxWait value is supplied, it will block for at most that many milliseconds, after which a NoSuchElementException will be thrown. If maxThreadWait is a negative value, it will block indefinitely. The Max Wait default is 4000. )
  ** When Exhausted Wait: Blocks (or waits) until a new or idle component is available.
  ** When Exhausted Fail: Throws an exception when the pool is exhausted.
* Initialisation Policy: Determines how components in a pool should be initialized.
  ** Initialise None: Does not load any components into the pool on startup.
  ** Initialise One (default): Loads one initial component into the pool on startup.
  ** Initialise All: Loads all components into the pool on startup.
* Disabled: Disables connection pooling. This means that a new physical connection to the server is needed for each separate operation in the flow that uses the connector configuration.
