= About the FTP Connector
:keywords: FTP, connector, matcher, directory, listener
:toc:
:toc-title:

Release Notes: link:/release-notes/connector-ftp[FTP Connector Release Notes]

This connector provides access to files and folders on an FTP server. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::common-file-actions.adoc[]

[[connection_settings]]
== Connecting to an FTP Server

You set up a connection through an `ftp:config` element, for example:

[source, xml, linenums]
----
<ftp:config name="ftp">
  <ftp:connection username="anonymous" password="password" host="localhost" port="${ftpPort}" workingDir="${workingDir}"/>
</ftp:config>
----

The `workingDir` provides the path to a directory that is treated as the root of every relative path used with this connector. If the directory is not provided, the remote server’s default serves as the working directory.
The `username`, `password`, `host`, and `port` attributes are self explanatory.

// Included in FTP, SFTP
include::common-dynamic-connections.adoc[]

.Example: Using FTP Write
[source, xml, linenums]
----
<ftp:config name="ftp"> // <1>
  <ftp:connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
</ftp:config>

<flow name="ftpMultitenant" >
  <http:listener config-ref="HTTP_Listener_config" path="/multitenant"/> // <2>
  <set-variable variableName="content" value="#[payload]" />
  <file:read path="recipients.csv" outputMimeType="application/csv" /> // <3>

  <foreach> // <4>
    <ftp:write path="demo.txt" config-ref="ftp"> // <5>
      <ftp:content >#[vars.content]</ftp:content>
    </ftp:write>
  </foreach>

  <set-payload value="Multicast OK"/>
</flow>
----

// Notes on Mule 4 behavior (for Mule 3 users):
//INCLUDED IN FTP, SFTP
include::common-note-mule4.adoc[]

// == Attributes
//INCLUDED IN FTP, SFTP, FILE
include::common-file-attributes.adoc[]

[[see_also]]
== See Also

link:ftp-documentation[FTP Connector Documentation Reference]

link:ftp-read[To Read Files]

link:ftp-write[To Write Files]

link:ftp-list[To List Files]

link:ftp-on-new-file[To Listen for New or Modified Files]

link:ftp-copy-move[To Copy or Move Files]
