= To trigger a flow when a new file is created or modified
:keywords: ftp, connector, trigger, new file, updated file, message source
:toc:
:toc-title:

 The `<ftp:listener>` (shows as `On New or Updated file` in Studio and Flow Designer), polls a directory looking for files that have been created or updated. One message will be generated for each file that is found.
 +
 The key part of this functionality is how to determine that a file is actually new. There're three strategies for that:
 
 * Set the `autoDelete` parameter to `true`: This will delete each processed file after it has been processed, causing all files obtained in the next poll to be necessarily new
 * Set `moveToDirectory` parameter: This will move each processed file to a different directory after it has been processed, achieving the same effect as `autoDelete` but without loosing the file
 * Use the `watermark` parameter to only pick files that have been created/updated after the last poll was executed.
 * A matcher can also be used for additional filtering of files.

Example:

[source,xml, linenums]
----
<flow name="onNewFile">
    <ftp:listener config-ref="file" directory="test-data/in" autoDelete="true">
      <scheduling-strategy>
        <fixed-frequency frequency="1000"/>
      </scheduling-strategy>
    </ftp:listener>
    
    <flow-ref name="processFile" />
</flow>
----

== Streaming

This message source leverages the new repeatable streams functionality introduced in Mule 4. It generates messages representing a found file. Each of those messages holds a stream to the found file, and that stream is repeatable by default.

For more information, read about link:/mule-user-guide/v/4.0/streaming-about[how automatic streaming works in Mule 4].

== See also

link:/mule-user-guide/v/4.0/streaming-about[Streaming in Mule 4.0]