= About the FTP Connector
:keywords: FTP, connector, matcher, directory, listener
:toc:
:toc-title:

The FTP connector provides access to files and folders on a FTP server. Its main features include:

* The ability to read files or fully list directory contents on demand.
* Support for common FTP operations such as copying, moving, renaming, deleting, and creating directories.
* Support for locking files.
* File matching functionality.
* A design that is fully consistent with the File, and SFTP connectors. The same set of operations are available on all  connectors, and they behave _almost_ the same way.

[[connection_settings]]
== Connecting to an FTP Server

As usual with Mule, connections are established through config elements:

[source, xml, linenums]
----
<ftp:config name="ftp">
  <ftp:connection username="anonymous" password="password" host="localhost" port="${ftpPort}" workingDir="${workingDir}"/>
</ftp:config>
----
Othen than the host, port, and credential parameters, the `workingDir` is probably the most important connection parameter. The `workingDir` is the path to a directory that is treated as the root of every relative path used with this connector. If the directory is not provided, it will default to the remote server’s default. Notice that this is exactly the same functionality as the new File Connector, except, of course, that the default value is different.

== Dynamic connections

Many integrations require connecting to different servers depending on a certain condition. Examples of this include:

* Connecting to different invoice storage servers depending on the branch that emitted the invoice.
* Connecting to different servers depending on a given integration subject, like in a multi-tenant use case.

To accommodate these use cases, the config element supports expressions, so the connection parameters can evaluate these conditions and connect to the correct server.

For example, consider the following application example:

[source, xml, linenums]
----
<ftp:config name="ftp"> // <1>
  <ftp:connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
</ftp:config>

<flow name="ftpMultitenant" >
  <http:listener config-ref="HTTP_Listener_config" path="/multitenant"/> // <2>
  <set-variable variableName="content" value="#[payload]" />
  <file:read path="recipients.csv" outputMimeType="application/csv" /> // <3>

  <foreach> // <4>
    <ftp:write path="demo.txt" config-ref="ftp"> // <5>
      <ftp:content >#[content]</ftp:content>
    </ftp:write>
  </foreach>

  <set-payload value="Multicast OK"/>
</flow>
----


This sample is a dynamic multicast application:

<1> It starts by defining a FTP config in which the host, username, and password are expressions.
<2> Then it has a flow on which content is posted through HTTP.
<3> Then it uses the File connector to load a recipient’s file, which is a CSV file containing a random set of SFTP destinations with columns such as host, user, and port.
<4> Then it uses a <foreach> to go over each of the lines in the CSV file.
<5> On each <foreach> iteration, each expression in the SFTP config will resolve to a different value, establishing different connections to each of the servers.

Notice:

* This example uses the new File connector to read a file in the middle of the flow. 
The information posted through the `<http:listener>` component is written to each SFTP site multiple times. Because the component makes use of the link:/mule-user-guide/v/4.0/streaming-about[repeatable streams feature], you don’t have to worry about consuming the stream multiple times. You don’t even need to know streaming is taking place.

[TIP]
 Notice that `<foreach>` is automatically going through each line of the CSV file. In Mule 3, you first needed to transform the CSV file into a Java structure, but because Mule 4 is now Java agnostic, this works out-of-the-box.

== Attributes

When reading or listing files, users are often not only interested in the file's content, but in its metadata as well (for example, the file name, full path, size, timestamp, and so on). The connector will use the Mule Message Attributes to access this information, while the Message Payload will always contain the file's content. For details on the Attributes structure, please read the link:ftp-documentation[FTP Connector Technical Reference].

== See Also
* link:ftp-read[To Read Files]
* link:ftp-write[To Write Files]
* link:ftp-list[To List Files]
* link:ftp-on-new-file[To Listen for New or Modified Files]
* link:ftp-copy-move[To Copy or Move Files]
* link:ftp-documentation[FTP Connector Technical Reference]
