= Dynamic Connections with the FTP Connector (Studio)
:keywords: ftp, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center: FTP connector

// TODO: DO NOT ADD TO REPO UNTIL REQUIRED COMPONENTS IN THE RELEASE OR MARIANO PROVIDES ALTERNATIVE

[[short_description]]
Many integrations require connecting to different servers depending on a certain condition, for example:

* Connecting to different invoice storage servers depending on the branch that emitted the invoice.
* Connecting to different servers depending on a given integration subject, such as a multi-tenant use case.

To accommodate for these use cases, the configuration element supports expressions so that connection parameters can evaluate these conditions and connect to the correct server.

Example of dynamic connection:

----

<ftp:config name="FTP_Config" doc:name="FTP Config" >
		<ftp:sftp-connection host="#[payload.host]" username="#[payload.user]" password="#[payload.password]" />
	</ftp:config>

	<flow name="streaming-multitenantFlow" >
		<http:listener config-ref="HTTP_Listener_config" path="/multitenant" doc:name="Listener" />

		<set-variable variableName="content" value="#[payload]" doc:name="Variable" />
		<file:read config-ref="File_Config" path="recipients.csv" doc:name="Read" outputMimeType="application/csv" />
		<ee:transform doc:name="Transform Message">
			<ee:message>
				<ee:set-payload ><![CDATA[%dw 2.0
output application/java
---
payload map using (row = $) {
    host: row.Host,
    user: row.User,
    password: row.Password
}]]>
				</ee:set-payload>
			</ee:message>
		</ee:transform>
		<foreach doc:name="For Each" >
			<ftp:write config-ref="FTP_Config" doc:name="Write" path="demo.txt">
				<ftp:content >#[content]</ftp:content>
			</ftp:write>
		</foreach>
		<set-payload doc:name="Set Payload" value="Multicast OK"/>
	</flow>
----

[[see_also]]
== See Also

link:ftp-about-the-ftp-connector[About the FTP Connector]

link:ftp-documentation[FTP Connector Technical Reference]

////
examples identity files
+
Examples: ~/.ssh/identity, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_rsa
+
////
