= About the FTPS Connector
:keywords: FTPS, connector
:toc:
:toc-title:

This connector provides all the same functionalities as the standard FTP connector, but adding the ability to secure the connection through SSL.

This is done by setting a TLS context in the connection:

[source, xml, linenums]
----
<ftp:config name="ftp">
    <ftps:connection username="anonymous" password="password" host="localhost" port="${ftpPort}" workingDir="${workingDir}">
        <tls:context>
            <tls:trust-store path="path/to/keystore" password="mulepassword" />
        </tls:context>
    </ftps:connection>
</ftp:config>
----

* For further information on how to configure SSL in Mule, please read the link:/mule-user-guide/tls-configuration[TLS documentation page]
* For further information on the rest of the functionality of this connector, please read the link:ftp-connector[FTP Connector Documentation]

To use the FTPS module, you simply add it to your Mule app through the Studio or Flow Designer UI, or you can add the following dependency in your `pom.xml` file:

[source,XML,linenums]
----
<dependency>
    <groupId>com.mulesoft.connectors</groupId>
    <artifactId>mule-ftps-connector</artifactId>
    <version>1.0.0</version> <!-- or newer -->
    <classifier>mule-plugin</classifier>
</dependency>
----


[[see_also]]
== See Also

* link:ftp-connector[FTP Connector Documentation]
* link:ftps-documentation[FTPS Connector Technical Reference]
