= About the HTTP Connector (Design Center)
:keywords: connectors, http, https

Using the HTTP or HTTPS protocol, the HTTP connector performs one of the following operations:

* Listener
+
Starts executing the Mule flow upon receiving a message from a source.
+
* Request
+
Consumes a web service.

Mule preconfigures the first HTTP connector in an empty flow as a listener and trigger. When the app runs and the listener hears a request, the flow executes.

By default, the listener configuration connects to CloudHub using HTTP and the request configuration connects to port 80 using HTTP and GET.  You can quickly configure an app to consume a web service using the two HTTP connector instances as follows:

* Listener configuration: Path = */somepath*, for example
* Request configuration: Path Or URL = the URL of the web service you want to consume

== See Also

* link:/connectors/http-consume-web-service[To Consume a Web Service]
* link:/connectors/http-about-http-connector-migration[About HTTP Connector Migration]
* link:/connectors/http-documentation[HTTP Connector Technical Reference]

