= About Making an HTTP Request
:keywords: connectors, http, https

The HTTP connector executes HTTP methods using HTTP or HTTPS protocol. The request body is passed to the next element of the flow as the message payload. Headers, query parameters, URI parameters and other metadata are returned in the `MuleMessage` as `HttpResponseAttributes`. You access the attributes using DataWeave.

== About HTTP Responses to Requests

The response to a request can include the following information:

* Query parameters
* Headers
* URI parameters
* Status code
* Reason phrase

You can format the output of a request as follows:

* A stream
* Multipart/form data
* X-form-urlencoded
* A byte array

Multipart/form data accommodates a map payload, converting map keys and values to parameter keys and values in a form. X-form-urlencoded data accommodates a message that contains attachments. Each attachment is converted to part of the HTTP request body. The ANY default output type for metadata converts the payload to a byte array.

== Secure Requests

You can use the default Transport Layer Security (TLS) configuration for HTTPS requests based on the JVM settings for TLS. The JVM usually includes a trust store with certificates for major certifying authorities. Alternatively, you can configure a key store or trust store, or both. 


== See Also

* link:/connectors/http-connector-xml-reference[HTTP Connector XML Reference]
* link:/connectors/http-documentation[HTTP Connector Technical Reference]

