= About HTTP Connector Migration
:keywords: http, https, request, requester

Key changes in the HTTP connector for Mule Runtime 4.0 and later that can affect migration are:

* The `http:listener-config` has a new, inner connection element. 
* The HTTP body option option replaces the source parameter in the request.
* An HTTP request returns attributes, which include a headers map, status, and reason phrase.
* The `static-resource-handler` is renamed `load-static-resource` and moved from the source to the operation side of a flow.
+
* To access source HTTP listener and HTTP request attributes, the following DataWeave syntax replaces the Mule Expression Language (MEL)
+
`#[attributes.<parameter>]`

The "HTTP Connector XML Reference" maps Mule 3.x MEL expressions to Mule 4.0 DataWeave expressions.

The following constructs are removed in Mule Runtime 4.0:

* Request and response builders, `http:request-builder` and `http:response-builder`
* Worker threading profile

The request, response, and error-response replace the builders. Using DataWeave expressions eliminates the need for building parameters.

== See Also

* HTTP Connector XML Reference
* HTTP Connector Technical Reference

