= About Making an HTTP Request
:keywords: connectors, http, https

The HTTP connector can make HTTP or HTTPS requests. The request body is passed to the next element of the flow as the message payload. Headers, query parameters, URI parameters and other metadata are returned in the `MuleMessage` as `HttpResponseAttributes`. You access the attributes using DataWeave.

You can format the metadata output of a request as follows:

* A stream
* Multipart/form data
* X-form-urlencoded
* A byte array

Multipart/form data accommodates a map payload. Converts the keys and values of the map to form parameter keys and values in the body of the HTTP request. X-form-urlencoded data accommodates a message that contains attachments. Each attachment is converted to part of the HTTP request body. The ANY default output type for metadata converts the payload to a byte array.

== Secure Requests

You can use the default Transport Layer Security (TLS) configuration for HTTPS requests based on the JVM settings for TLS. The JVM usually includes a trust store with certificates for major certifying authorities. Alternatively, you can configure a key store or trust store, or both. 

== About HTTP Responses to Requests

The response to a request can include the following information:

* Query parameters
* Headers
* URI parameters
* Status code
* Reason phrase


== See Also

* To Make an HTTP Request
* To Create an HTTPS Listener
* HTTP Connector XML Reference
* HTTP Connector Technical Reference

