= To Create an HTTPS Listener
:keywords: anypoint, connectors, transports

. Create a key store. For example, use the Java keytool as follows:
+
`keytool -genkey -alias mule -keyalg RSA -keystore keystore.jks`
+
* In response to keytool prompts, enter a password and arbitrary values to other prompts except the last one.
* To the last keytool prompt, press RETURN to use the same password as the key store password.
+
. In an empty flow, select an HTTP connector to trigger the flow.
. Set up the listener configuration: 
+
* In Configuration Name, accept the default name HTTP Listener. 
* In Protocol, select HTTPS.
* Set the host and port. For example, host = 0.0.0.0, port = 8082.
* Accept the default no base path.
. Click Security, and enter the following values:
+
* Scroll down to Key Store, and ... TBD (upload?) the path to the key store you created.
* In Key Password and again in Password, enter the password you created using the Java keytool.
* Accept all other default security settings.
* Save the configuration.
. In General, set Path to `/` and close the configuration.
. Click + to add another component to the flow, select HTTP, and select the Request operation.
. Set up the request configuration. 
* In Protocol, select HTTPS.
* Set the host. For example, set the host to `jsonplaceholder.typicode.com`. 
* Set the port to 443.
* Set the base path to `/users`.
* Click Save.
+
. Accept the other default settings and close the connector.
. TBD ... Deploy the app, run the app, open a browser, and go to the URL you set up in the listener configuration. For example, `<host URL>.cloudhub.io:8082`.
+
The listener hears the request on port 8082, and starts the app. The requester gets a list of users, which appears in the browser.

== See Also

* About the HTTP Request Operation
* HTTP Connector Reference
* HTTP Connector Documentation Reference
* link:/mule-user-guide/v/3.8/tls-configuration#generating-keystores-and-truststores[Generating Keystores and Truststores]