= To Consume a REST Service 

You can integrate a web service into an application by setting up one HTTP connector as a listener and another as a request.

. In a new project, set up an HTTP connector to trigger an app from a browser.
. Click + to add another component to the flow.
. Select HTTP.
. Set up the request configuration: 
+
* In Protocol, select HTTP or HTTPS.
* Set the host. For example, set the host to `jsonplaceholder.typicode.com`. 
* Set the port. For example, to make an HTTPS request, port = 443. To make an HTTP request, port = 80.
* In URL configuration, set the base path to `/users`.
+
. Accept the other default settings, save, and close the connector.
. Click Run or Update.
. Select Running > Copy Link, go to a browser, paste the link, and go to the URL that triggers the app.
+
The HTTP listener hears the request, and starts the app. The list of JSON Placeholder users appears in the browser.
+
. Open HTTP - Request, and click the Live tab. 
+
The list of users appears in Payload, and in Attributes, the attributes you can use in DataWeave expressions appear. 

== See Also

* link:https://jsonplaceholder.typicode.com/[JSONPlaceholder site]
* link:/connectors/http-trigger-app-from-browser[To Trigger an App from a Browser]