= To Load a Static Resource
:keywords: anypoint, connectors

. In Design Center, create a new project, and start a flow using an HTTP component that triggers an app from a browser.
. Click +, and add another component to the flow:
+
* Select HTTP.
* Select the Load Static Resource operation.
. Set the resource base path to the path and file name of the resource.
. Set the default file to the name of a backup file to load in the event of a failure to load the resource.
. Accept the other default settings and close the connector.
+
. Click Run or Update.
. Select Running > Copy Link, go to a browser, paste the link, and go to the URL.
+
The listener hears the request, and starts the app. The contents of the resource appear in the browser.

== See Also

* link:/connectors/http-about-loading-static-resource[About Loading a Static Resource]
* link:/connectors/http-documentation[HTTP Connector Technical Reference]
* link:/connectors/http-to-trigger-app-from-browser[To Trigger an App from a Browser]