= To Consume a REST Service (Studio)

You can design an app to consume a web service by setting up one HTTP connector as a listener and another as a request. In this procedure, you first consume a REST API service using primarily default HTTP connector configurations for the listener and request. Next, you test the HTTP request. You edit the request configuration to make a secure HTTPS request. Finally, you test the HTTPS request.

. From Mule Palette, drag an HTTP connector configured for the Listener operation, to a new flow.
. Set up the listener configuration: Click + and set the default host, port and base path. For example, host = 0.0.0.0, port = 8081, and no base path.
. In General, set Path to */trigger*.
. Accept the other default listener settings, and save the configuration.
. From Mule Palette, drag HTTP > Request, to the flow.
. Set up the request configuration:
+
* Set URL Or Path to `+http://jsonplaceholder.typicode.com/users+`.
* Accept the other default settings and save.
+
. Deploy the app, run the app, open a browser, and go to `+localhost:8081/trigger+`.
+
The listener hears the request on port 8081, and starts the app. The requester gets a list of users, which appears in the browser.

== See Also

* About the HTTP Request Operation
* About HTTP Connector Migration
* HTTP Connector Reference
* HTTP Connector Documentation Reference