= To Consume a REST Service 

You can integrate a web service into an application by setting up one HTTP connector as a listener and another as a request. In this procedure, you first consume a REST API service using primarily default HTTP connector configurations for the listener and request. Next, you test the HTTP request. You edit the request configuration to make a secure HTTPS request. Finally, you test the HTTPS request.

. In a new project, set up the HTTP connector to listen for a message from the browser to start this app: Use the default CloudHub HTTP configuration and set Path to */trigger*.
. Click + to add another component to the flow, and select HTTP Request.
. In HTTP Request, in General, set Path Or URL to *http://jsonplaceholder.typicode.com/users*. Accept the other default settings and close the connector.
. Click Sync. Fire the app trigger:
+
* Select Running > Copy Link.
* Paste the link in a browser or client, and type */trigger* at the end.
+
The HTTP listener hears the request, and starts the app. The list of JSON Placeholder users appears in the browser.
+
. Open HTTP - Request, and click Output. 
+
The list of users appears in Payload, and in Payload > Attributes, the attributes you can use in DataWeave expressions appear. 
+
. Click Configuration > Edit, and configure the following options:
* In HTTP Configuration, in Protocol, select HTTPS.
* In Port, enter *443*
* Save.
. In HTTP Request, change Path Or URL as follows:
+
* FROM: `http://jsonplaceholder.typicode.com/users`
* TO: `https://jsonplaceholder.typicode.com/users`
. Click Sync. Fire the app trigger:
+
* Select Running > Copy Link.
* Paste the link in a browser or client, and type */trigger* at the end.
+
The list of users appears in Payload, and in Payload > Attributes, the attributes you can use in DataWeave expressions appear. 

== See Also

* link:https://jsonplaceholder.typicode.com/[JSONPlaceholder site]
* link:/connectors/http-trigger-app-from-browser[To Start an App from a Browser]
* link:/connectors/http-documentation[HTTP Connector Technical Reference]

////
click Edit. Set up the request configuration: 
+
* Accept the default configuration name HTTP Request.
* In Protocol, select HTTP or HTTPS. 
* Set the host. For example, set the host to *jsonplaceholder.typicode.com*. 
* Set the port. For example, to make an HTTP request, port = 80. To make an HTTPS request, port = 443. 
* Accept the other default settings, and save. 

////