= To Consume a REST Service 

You can integrate a web service into an application by setting up one HTTP connector as a listener and another as a request.

. In a new project, set up an HTTP listener connector to start an app from a browser.
. Click + to add another component to the flow.
. Select HTTP Request, and in HTTP Request, click Edit.
. Set up the request configuration: 
+
* Accept the default configuration name HTTP Request.
* In Protocol, select HTTP or HTTPS. 
* Set the host. For example, set the host to `jsonplaceholder.typicode.com`. 
* Set the port. For example, to make an HTTP request, port = 80. To make an HTTPS request, port = 443. 
+
. Accept the other default settings, and save. In General, set Path Or URL to */users*. In Method, select GET. Close the connector.
. Click Run or Update.
. Select Running > Copy Link, go to a browser, paste the link, and go to the URL that starts the app.
+
The HTTP listener hears the request, and starts the app. The list of JSON Placeholder users appears in the browser.
+
. Open HTTP - Request, and go to Output. 
+
The list of users appears in Payload, and in Attributes, the attributes you can use in DataWeave expressions appear. 

== See Also

* link:https://jsonplaceholder.typicode.com/[JSONPlaceholder site]
* link:/connectors/http-trigger-app-from-browser[To Start an App from a Browser]