= HTTP Connectors
:keywords: anypoint studio, esb, connectors, http, https, http headers, query parameters, rest, raml
:toc:
:toc-title:



toc::[]


HTTP connectors for Mule include:

* *HTTP listener*
* *HTTP requester*
* *Load static resource*
* *Basic auth security filter*

All are accessible from your Mule application design palette, typing "HTTP". The listener and requester require a *connector configuration*. With the connectors you can handle and customize HTTP responses, set up authentication with a *TLS Context* and send customized requests.

=== About HTTP Listener

Use the HTTP listener in the source (left) side of a flow to listen for requests that should trigger a Mule flow.

* Process the HTTP request(s) and process needed values
* Build a response for the HTTP client that sent the request
* link:/mule-user-guide/v/latest/http-listener-reference[HTTP Listener Reference]
// List special configuration procedures from above doc below

=== About HTTP Requester

Use to send requests to a certain address. Receive and process the returned response. Place the HTTP requester in the process (right) side of the flow.

The request will return a `MuleMessage` with specific `HttpResponseAttributes`.

* link:/mule-user-guide/v/latest/http-request-reference[HTTP Requester Reference]
* link:/mule-user-guide/v/3.8/http-listener-connector#mapping-between-http-requests-and-mule-messages[Mapping HTTP Requests to MuleMessage]

// List special configuration procedures from above doc below

=== About Load Static HTTP Resource

Add the Load Static Resource operation to return to a requester a static HTTP resource, such as .html, CSS, scripts, etc. This gets sent back automatically with the response.

Put the Load Static Resource component in the flow and define the resource to send, or a default resource in case of failure.

link:/load-static-resource-reference[Load Static Resource Reference]

=== About Basic Auth Security Filter

Put a listener and then security filter to secure and authenticate requests to your service.

== HTTP Listener Use Cases

=== Route Incoming Requests to HTTP Listeners

* link:/#route-path[Route Requests Based on URI] by setting *Path*.
* Route based on HTTP method be setting the *Allowed Methods* for each listener, `GET`, `POST`, `UPDATE`, etc.

[IMPORTANT]
To host your application on CloudHub, set all listeners' *Host* to `0.0.0.0`.

[[route-path]]
==== Route Requests Based on URI

To route requests to different listeners that trigger different flows, set the *Path* for each listener to a different valid subpath in the domain.

To route to `+http://localhost:8081/employee+` or `+http://localhost:8081/account+`, set up the listeners as follows:

* Set one listener's *Path* to `account` and the other listener's to `employee`
* Set *Host* to `localhost`
* Set *Port* to `8081`


===== Ways to Set the Path

* Wildcards such as * are accepted in paths, for example a *Path* of `/regions/*/prospects` is valid.

[NOTE]
====
Listeners with a more specific path are always given priority in routing.

Given a listener for *Path* `account/\*` and another on `account/*/main-contact`, if a request arrives for `account/mulesoft/main-contact`, it arrives on the listener for `account/*/main-contact`.
====

* Use a variable for a URI parameter to get the value from a part of a path that may vary depending on the request `accountId`.

Old: `#[message.inboundProperties.'http.uri.params'.accountId]`


=== Implement Authentication when Listening for Requests

Add a Basic Security filter after a listener. This requires you to reference the HTTP status code and a reference to the header in the response.

[source,xml,linenums]
----
<flow name="listenerBasicAuth">
   <http:listener config-ref="listenerConfigBasicAuth" path="/basic">
       <http:error-response-builder>
           <http:http-response-builder statusCode="#[statusCode]" headersRef="#[headers]"/>
       </http:error-response-builder>
   </http:listener>
   <http:basic-security-filter realm="mule-realm"/>
   <set-payload value="TestBasicAuthOk"/>
</flow>
----


Another option is to add a Spring security component. See Spring Security manager.
//TODO

=== Configuring Connection Attributes

Set maximum connection idle time and enable/disable connection persistence through the listener configuration.

=== Streaming a File

To stream the file content through the HTTP connection, the `Transfer-Encoding` header is used to send the HTTP message body in chunks, avoiding having to know the body length in advance. Each chunk is separated by a predefined line separator, which contains the length of the particular chunk.

=== Processing Transfer-Encoding:chunked Request Body

* When HTTP request has a `Transfer-Encoding:chunked` header, the listener decodes the body into an `InputStream` automatically.
* `Transfer-encoding` header is used to send the HTTP message body in chunks, so you do not need to know the body length in advance. Each chunk is separated by a predefined line separator, which contains the length of the particular chunk

=== Parsing HTTP Request Body

The *Parse request* field can be toggled to *true* or set dynamically using an expression.

=== Generating the HTTP Response

Optionally set up the HTTP response so that it contains the desired body, attachment, headers and status. The response body is generated from the Mule message payload.

The only exceptional scenarios are when the payload is a `Map` or there are attachments `multipart/form-data` in the message.

==== Generating the Response Body

.Response properties when payload of type `Map`
[%header]
|===
|Payload |Response Body |Response Header
|Map |`application/x-www-form-urlencoded` | `Content-Type: application/x-www-form-urlencoded`
|===

==== Generating Response with Attachments

Message outbound attachments are used. Message payload is not used.

.Response properties when Mule Message has Attachments
[%header]
|===
|Payload |Response Body |Response Header
|Not used |`multipart/form-data` | link:/#gen-header[Set the header explicitly]
|===

[[gen-header]]
==== Generating HTTP Response Headers

Response headers are generated from outbound properties which the exception of an outbound property named "Connection", "Host", or "Transfer-Encoding".
//TODO

*Other topics*:

* link:/#set-header-ex[Set Header Explicitly using Properties]
* link:/#disable-headers[Disable outbound properties as headers] in response
* Set Headers in the Listener Configuration
//TODO confirm use of properties in Mule 4? Are these set in Configuration?

[[set-header-ex]]
==== Set Header Explicitly

* Set a header using the Property Transformer `<set-property>`.
* Use Response Builder to set headers, even dynamically
* Set the HTTP status code and reason phrase using Property Transformer
//TODO confirm how to set headers

[[disable-headers]]
==== Disable Outbound Properties as Headers

In the HTTP Listener properties editor, in the *Response Settings* section.
//TODO confirm what should be done "Create child?"

==== Other Response Details

Normally, HTTP Listener computes the length of the payload and sets the value of the `Content-Length` header.

* If the payload is an `InputStream`, the HTTP listener adds a `Transfer-Encoding:chunked` header to the response
** For all other cases, HTTP listener computes the length of the payload and sets the value of the `Content-Length`
* Override the listener's attempts to set `Content-Length` or `Transfer-Encoding` by setting the *Response streaming mode*.

For streaming options in the HTTP Requester, see link:/#stream-requester[How to Stream through Requester]


== HTTP Requester Use Cases

=== Send Authenticated Requests

link:/mule-user-guide/v/latest/authentication-in-http-requests[Authenticated Requests], via *Basic Authentication, Digest and OAuth*

=== Send Multipart HTTP Requests

Use an Attachment component from the palette to upload the file in a POST request with `ContentType: multipart/form-data`. Each attachment is sent in parts.
//TODO how to?

=== Adding Custom Parameters

The HTTP requester allows you to include maps or singles of the following parameter types:

* query params
* URI params
* headers

=== Changing Default Behavior for Sending Request Body


The message *payload* is the body of the request, except for with methods `GET`, `HEAD` and `OPTIONS`, which mean sending HTTP requests with an empty body (the payload of the Mule message won’t be used at all). If you need to change this default behavior, you can specify in the *Request Builder*.
//TODO: confirm

Customize the body of the request using the `source` and `target` attributes.
//TODO how to access now?

==== Additional Custom Parameters

* Send form parameters with your request, included in the Mule message payload
* Include attachments in your request by adding an Attachment building block to your flow.
//TODO how else to send attachments?
* Set headers, URI parameters explicitly or dynamically, using DataWeave language.
* Send form parameters in `POST` request

[[stream-requester]]
=== Streaming through the HTTP Requester

To do so, set the attribute *Request streaming mode*. When streaming, request contains `Transfer-Encoding` header and sends body in chunks until stream consumed; it does not contain the `Content-Length` header.

=== Parsing HTTP Response Body

As with the listener, when HTTP responses have a content type of `application/x-www-form-urlencoded` or `multipart/form-data`, the HTTP Requester automatically parses the message. You can disable this parsing functionality.

=== Validating HTTP Responses

You can set an expression to do this from *Response Settings*.
//TODO how to do this now. Before was done from Success Status Code Validator?

== Additional Reference

Other attributes in this connector allow you to set up more advanced functionality such as response timeout, set whether redirects are followed, cookies gathered from responses and if responses are parsed.

=== Send or Receive HTTPS requests

Set the protocol to HTTP in the configuration.

[NOTE]
Configuration depends on whether you have a HTTP server or client and whether or not you need two-way authentication.

Configure a TLS Context (keystore and/or trust store) to set up HTTPS (see
link:/mule-user-guide/v/3.8/tls-configuration[TLS Configuration]). Setting both a trust store and a key store means having two-way TLS.

*One-way scenarios*

- Server implements *key store* to enforce client authentication
- Client implements *trust store* (JVM's will be used if not provided)

=== Migrate from Mule 3 HTTP Connectors

Mule 3.0
Mule 3.6
Mule 4
//TODO

=== Map HTTP Responses to Mule Messages

An HTTP response is mapped to the Mule message in exactly the same way that the HTTP request is mapped to a Mule message in the HTTP Listener Connector, except that the following elements don’t apply to HTTP responses:

* Query parameters
* URI parameters
* All inbound properties related to the HTTP request URI

In addition, the HTTP Request Connector adds the following inbound properties to the Mule message when receiving a response:

`http.status`: Status code of the HTTP response
`http.reason`: Reason phrase of the HTTP response



== See Also

* See the link:/mule-user-guide/v/3.8/http-connector-reference[full reference]﻿ for the available XML configurable options in this connector.
