= IBM MQ Tuning For Performance
:keywords: jms, ibm mq, mq, performance, connector, consume, message, source, listener
:toc:
:toc-title:


Performance can be a significant factor when processing loads of messages, which
means that you probably want to check the following configurations to make sure
you get the most out of the IBM MQ Connector.

== Don't Disable Connections Reuse

Connections are expensive to create, so it's important to reuse them as much as possible.

*By default, the IBM MQ Connector uses an aggressive* `caching-strategy` that
reuses as much Consumers and Producers as possible. It is recommended to keep
this configuration untouched since any modification could reduce the performance
of your application.

WARNING: Disabling connections caching will reduce the performance of your application.


== Increasing Concurrent Messages Processing

A good way of improving the performance of your application is to increase the
number of concurrent consumers that receive messages from the same destination.
This can be done easily in the IBM MQ Connector by configuring the `numberOfConsumers`
parameter.

Out of the box, the `listener` will use *four consumers* concurrently on the same
destination, but you can increase this number to the one that fits better your needs:

[source, xml, linenums]
----
<ibm-mq:listener config-ref="config" destination="#[vars.destination]" numberOfConsumers="20"/>
----

TIP: Increasing the `numberOfConsumers` is the easiest way to improve the throughput of your listeners.

== Optimize Your Configuration For Clusters

For applications running in clusters, you have to keep in mind the concept of
*primary node* and how the connector will behave. When running in a cluster,
the IBM MQ `listener` *default behaviour will be to receive messages only in the _primary node_*,
no matter what kind of destination you are consuming from.

In case of consuming messages from a *Queue*, you'll want to
*change this configuration to receive messages in all the nodes* of the cluster,
not just the primary. This can be done with the `primaryNodeOnly` parameter:

[source, xml, linenums]
----
<ibm-mq:listener config-ref="config" destination="${inputQueue}" primaryNodeOnly="false"/>
----

Consuming messages from a *Topic* is a bit different, since the default behaviour
of *receiving messages only in the primary node is the most common use case*,
given that it avoids processing the same message multiple times across the cluster.

If you are using the JMS 2.0 *shared subscriptions* mechanism, then you'll want
to *change the cluster configuration to consume from all the nodes*, again
setting `primaryNodeOnly` to `false`:

[source, xml, linenums]
----
<ibm-mq:listener config-ref="JMS_20_config" destination="${inputTopic}" primaryNodeOnly="false">
     <ibm-mq:consumer-type>
         <ibm-mq:topic-consumer shared="true" subscriptionName="clusteredEventListener"/>
     </ibm-mq:consumer-type>
 </ibm-mq:listener>
----

TIP: When listening from a *Queue* in a cluster, change the `primaryNodeOnly`
configuration to `false`.

WARNING: When listening from a *Topic* in a cluster, not using the `primaryNodeOnly`
configuration will cause the cluster to process the same message more than once
unless shared-subscriptions is used.

== See Also

* link:ibm-mq-consume[To Consume Messages]
* link:ibm-mq-topic-subscription[Using Topic Subscriptions]
