= Handling Transactions in JMS
:keywords: jms, ibm mq, mq, xa, connector, transactions, transactional
:toc:
:toc-title:


Transactional connections in IBM MQ allow you to execute a series of operations
that are actually performed only when the transaction is committed. This has two main scenarios:

* Publishing a Message as part of a transaction: When performing a `publish`,
the Message will be effectively sent to the destination once the transaction is
*committed*. If for some reason the transaction fails and a *rollback* occurs,
then the Message will never be sent.

* Consuming a Message as part of a transaction: In case of consuming a Message,
either with the `listener` or `consume`, the Message will be acknowledged
*only after the transaction is committed*, and instead it will be returned to
the destination for redelivery if the transaction is *rolled-back*.


The IBM MQ Connector provides support for executing its operations in a
transactional way out of the box using Mule's `transactionalAction` configuration.

In order to execute an operation as part of the transaction, we have the following two options.

== Processing New Messages With Transactional Session

If you want a IBM MQ `On New Message` Listener to use a transactional session when dispatching the
messages, you should set the `transactionalAction` to 'ALWAYS_BEGIN':

[source, xml, linenums]
----
<ibm-mq:listener config-ref="IBM_MQ_Config" destination="${originQueue}" transactionalAction="ALWAYS_BEGIN"/>
----

With this configuration, each new message will be processed in a transaction
that is propagated to all the flow's components and is committed once the flow
execution is completed successfully.
The transaction will be rolled-back if the flow execution is completed with an error.

By default, *other components* in the flow *will not join the transaction*
created by the listener.
In order to execute other operations using the listener’s transaction, you must
declare them either with `ALWAYS_JOIN`, or `JOIN_IF_POSSIBLE`.

== Execute Operations As Part Of A Transaction

To execute an operation like `publish` or `consume` as part of a transaction,
we have to set the `transactionalAction` to `ALWAYS_JOIN`, or `JOIN_IF_POSSIBLE`:

This operations can join a transaction initiated by the listener:
[source, xml, linenums]
----

<flow name="joiningToListenerTransaction">
    <ibm-mq:listener config-ref="IBM_MQ_Config" destination="${originQueue}" transactionalAction="ALWAYS_BEGIN"/>
    <ibm-mq:publish config-ref="IBM_MQ_Config" destination="#[attributes.properties.userProperties.redirectDestination]" transactionalAction="JOIN_IF_POSSIBLE"/>
    <ibm-mq:consume config-ref="IBM_MQ_Config" destination="#[attributes.properties.userProperties.callbackDestination]" transactionalAction="JOIN_IF_POSSIBLE"/>
</flow>
----

Or they can join an scoped transaction:
[source, xml, linenums]
----
<flow name="nonTxPublishMustNotJoinCurrentTx">
    <http:listener config-ref="HTTP_Config" path="/orders"/>
    <try transactionalAction="ALWAYS_BEGIN">
        <ibm-mq:publish config-ref="config" destination="${billingService}" transactionalAction="ALWAYS_JOIN"/>
        <ibm-mq:publish config-ref="config" destination="${shipmentService}" transactionalAction="ALWAYS_JOIN"/>
        <ibm-mq:publish-consume config-ref="IBM_MQ_Config" destination="${invoicesVerificationService}"/>
        <validation:is-true expression="#[payload]"/>
    </try>
</flow>
----

== XA Transactions

IBM MQ Connector supports to create and join XA Transactions, this enables the
connector to participate in a transaction with multiple resources, this means
execute transactional actions with other connections of IBM MQ or other connectors
like *DB Connector* or *VM Connector*.

To enable XA Transactions, two steps are required:

1 - Create a XA Enabled connection: configure `enableXa` in true.
[source, xml, linenums]
----
<ibm-mq:config name="IBM_MQ_Config" >
		<ibm-mq:connection enableXa="true" >
			<ibm-mq:connection-mode >
				<ibm-mq:client host="0.0.0.0" queueManager="QM1" />
			</ibm-mq:connection-mode>
		</ibm-mq:connection>
	</ibm-mq:config>
----

2 - Configure to create a XA Transaction: This means to configure the `transactionType` as `XA`:

[source, xml, linenums]
----
<flow name="joiningToListenerTransaction">
    <ibm-mq:listener config-ref="IBM_MQ_Config" destination="${originQueue}" transactionalAction="ALWAYS_BEGIN" transactionType="XA"/>
    <ibm-mq:publish config-ref="IBM_MQ_Config" destination="#[attributes.properties.userProperties.redirectDestination]" transactionalAction="JOIN_IF_POSSIBLE" transactionType="XA"/>
    <ibm-mq:consume config-ref="IBM_MQ_Config" destination="#[attributes.properties.userProperties.callbackDestination]" transactionalAction="JOIN_IF_POSSIBLE" transactionType="XA"/>
</flow>
----

Or they can join an scoped transaction:
[source, xml, linenums]
----
<flow name="nonTxPublishMustNotJoinCurrentTx">
    <http:listener config-ref="HTTP_Config" path="/orders"/>
    <try transactionalAction="ALWAYS_BEGIN" transactionType="XA">
        <ibm-mq:publish config-ref="config" destination="${billingService}" transactionalAction="ALWAYS_JOIN" transactionType="XA"/>
        <ibm-mq:publish config-ref="config" destination="${shipmentService}" transactionalAction="ALWAYS_JOIN" transactionType="XA"/>
        <ibm-mq:publish-consume config-ref="IBM_MQ_Config" destination="${invoicesVerificationService}"/>
        <validation:is-true expression="#[payload]"/>
    </try>
</flow>
----
