== To List Files
:keywords: file, ftp, connector, operation
:toc:
:toc-title:

// toc::[]

// For Anypoint Studio, Design Center: FTP connector

This operation lists all the files and folders in a given Directory Path. This path can be absolute, or it can be relative to the Working Directory specified in the connector configuration. In addition, it provides a setting for recursing through subdirectories.

The List operation returns a List of messages with a payload and file attributes. Each message represents a file or subdirectory in the directory. The payload of a subdirectory is `null`.

The connector streams the file content without opening the file until it is needed, which avoids excess memory use and the assignment of handles by the OS to access and open the file.

This example uses the List operation to list all files in a directory on the FTP server that match file properties. This operation can recurse through subdirectories.

. Meet the <<preconditions,Preconditions>> for the List operation.
. Provide a Directory Path to the files that you want to list.
. Select Recursive if you want to include the contents of subdirectories.
. Opt to provide a Matcher to the files that you want to list.
+
Example:
+
Filename Pattern: `*[1-2]*.html`
