= Example: To Invoke Methods Using the Java Module
:keywords: Java, create instance
:toc:
:toc-title:

toc::[]

This example shows how to invoke instance methods. First, it creates the instance on which the method will be invoked. Then it invokes a method that does not take any arguments.

[source, xml, linenums]
----
<java:new class="com.foo.TaxCalculator"
  constructor="TaxCalculator()"
  target="taxCalculator"/>
<java:invoke instance="#[vars.taxCalculator]"
  class="com.foo.TaxCalculator"
  method="init()"/>
----

Note that you can obtain a method from elsewhere instead of creating an instance with the `<java:new>`.

The next example invokes a method that takes arguments:

[source, xml, linenums]
----
<java:new class="com.foo.TaxCalculator"
  constructor="TaxCalculator()"
  target="taxCalculator"/>
<java:invoke instance="#[vars.taxCalculator]"
  class="com.foo.TaxCalculator"
  method="calculate(Long)">
    <java:args>#[{price: payload.price}]</java:args>
</java:invoke>
----

//TODO: WOULD HELP TO SHOW OR CLARIFY WHAT "GET DATASENSE" MEANS:
Note that you get DataSense with `<java:new/>` and both the output value and the input arguments.

== Invoking Static Methods

You can invoke static Java methods like this:

[source, xml, linenums]
----
<java:invoke-static
  class="java.lang.Math"
  method="toRadians(double)">
    <java:args>#[{a: 180}]</java:args>
</java:invoke-static>
----

== Invoking Methods with DataWeave

You can invoke methods using DataWeave functions. This is especially helpful for methods that return `boolean` values:

[source, xml, linenums]
----
<choice>
    <when
      expression="#[Java::invoke('com.foo.TaxCalculator',
      'isTaxFree(Invoice)', vars.taxCalculator,
      {invoice: vars.invoice})]">
        <flow-ref name="skipTax" />
    </when>
</choice>
----
