= About the NetSuite Connector
:keywords: anypoint studio, connector, endpoint, netsuite

The NetSuite connector makes use of the SuiteTalk WSDL to provide SOAP-based integration and generate NetSuite business objects, makes use of different authentication levels, and supports error handling. This connector also provides access using REST calls to RESTlets that expose APIs created with SuiteScript.

NetSuite provides cloud-based business management software that helps companies manage core business processes, ERP/financials, CRM, e-commerce, inventory, and more.

MuleSoft maintains this connector under the Select Connector Support Policy.

== Prerequisites

This document assumes that you are familiar with Mule, Anypoint connectors, Anypoint Studio, Mule flows, and global elements.

To use this connector, you should have:

* A NetSuite account with Web Services Features enabled.
* (optional) Anypoint Studio. If you are upgrading from a previous version of the connector, a small popup appears in the bottom right corner of Anypoint Studio with the "Updates Available" message. Click the popup and follow the prompts to install the latest version. You can also use this connector in Design Center in Anypoint Platform, and as a standalone application developed in XML.

== What’s New in this Connector

Retrieved values from operations provide the object type from an API and not a wrapper type, which you used to receive after a successful call.

== See Also 

* link:/connectors/netsuite-to-use-design-center[To Configure NetSuite Connector in Design Center]
* link:/release-notes/netsuite-connector-release-notes[NetSuite Connector Release Notes]
* link:/connectors/netsuite-reference[NetSuite Reference]
