= Example: To store and retrieve information in an Object Store
:keywords: ObjectStore, store, retrieve
:toc:
:toc-title:

toc::[]

== Storing information from the ObjectStore

You can use it to store single values:
`<os:store key="userId" value="#[attributes.queryParams.id]" />`

You can use it to store complex structures you can build inline:

[source, xml]
----
<os:store key="state">
  <os:value>
    <![CDATA[#[
      output application/json
       ---
       {
          "id": attributes.queryParams.id,
          "timestamp": now(),
          "name": payload.name
        }
      ]]]>
  </os:value>
</os:store>
----


This operation can be used either for storing new values or updating existing ones, depending on the value of the `failIfPresent` parameter. When that parameter is set to false (default value) then any pre existing value associated to that key will be overwritten. If the parameter is set to true, then a `OS:KEY_ALREADY_EXISTS` error will be thrown instead.

Another important consideration is regarding null values. It is not allowed to store a null value. However, a common use case is to:
Obtain a value (most likely by evaluating an expression or transformation)
* Testing the value for not null
* Storing it if present
* Do nothing otherwise.

The `failOnNullValue` parameter simplifies this use case. On its default value of true, a `OS:NULL_VALUE` error is thrown if a null value is supplied. However, when set to false, a null value will cause this operation to do nothing: no error will be raised but no value will be altered either.

== Retrieving information from the ObjectStore

Retrieves the value stored for the given key.

You can use it to retrieve single values:

[source, xml]
----
<os:retrieve key="userId" />
----

You can use it to provide default values when the key is not present in the store:

[source, xml]
----
<os:retrieve key="timestamp">
  <os:default-value>#[now()]</os:default-value>
</os:retrieve>
---

You can even have default complex structures:

[source, xml]
----
<os:retrieve key="state">
  <os:default-value>
    <![CDATA[#[
     output application/json
     ---
     {
        "id": attributes.queryParams.id,
        "timestamp": now(),
        "name": payload.name
      }
    ]]]>
  </os:default-value>
</os:retrieve>
----

To facilitate use cases in which no value exists for that key, behavior will depend on the defaultValue parameter.

If the parameter was not provided or resolved to a null value, then a OS:KEY_NOT_FOUND error will be thrown. Otherwise, the defaultValue will be returned BUT keep in mind that such value WILL NOT be stored.

[TIP]
All these operations are synchronized on the key level. No other operation will be able to access the same key, on the same object store while this operation is running. If the runtime is running on cluster mode, this synchronization is also guaranteed across nodes.
