= Object Store Connector Reference

A Mule connector that provides functionality to access, create and manage Object stores.

== Parameters

[%header,cols="25a,75a"]
|===
|Name |Description
|Name |The name of this configuration, which can be later referenced.

Type: String +
Default: none +
Required: yes
|===
 

== Clear Operation

Removes all the contents in the store.

== Contains Operation

Checks if there is any value associated to the given key. If no value exist for the key, then false is returned.

This operation is synchronized on the key level. No other operation can access the same key on the same object store while this operation is running. If the runtime is running on cluster mode, synchronism is also guaranteed across nodes.

=== Contains Operation Parameters

[%header,cols="25a,75a"]
|===
|Name |Description
|Key |The key of the object to be removed.

Type: String +
Default: none +
Required: yes
|Target Variable |The name of a variable on which the operation's output is placed.

Type: String +
Default: none +
Required: yes
|===

The output type is a Boolean.

== Remove Operation

Removes the value associated to the given key. If no value exist for the key, then a OS:KEY_NOT_FOUND error is thrown.

This operation is synchronized on the key level. No other operation can access the same key on the same object store while this operation is running. If the runtime is running on cluster mode, this synchronism is also guaranteed across nodes.

=== Remove Operation Parameters

[%header,cols="25a,75a"]
|===
|Name |Description
|Key |The key of the object to be removed.

Type: String +
Default: none +
Required: yes +
Throws: +
OS:INVALID_KEY +
OS:KEY_NOT_FOUND
|===

== Retrieve Operation

Retrieves the value stored for the given key.

*Note:* If no value exists for the key, the behavior depends on the defaultValue parameter. If the parameter is not provided or resolves to a null value, then a OS:KEY_NOT_FOUND error is thrown. Otherwise, the default value is returned, but this value is not stored.

This operation is synchronized on the key level. No other operation can access the same key on the same object store while this operation is running. If the runtime is running on cluster mode, this synchronism is also guaranteed across nodes.

=== Retrieve Operation Parameters

[%header,cols="25a,75a"]
|===
|Name |Description
|Key |The key of the value to be retrieved.

Type: String +
Default: none +
Required: yes
|Default Value |Value that is returned if a key doesn't exist in the store.

Type: Any +
Default: none +
Required: no
|Target Variable |The name of a variable on which the operation's output is placed.

Type: String +
Default: none +
Required: no
|===

The output type is any.

The Retrieve operation can throw:

* OS:INVALID_KEY  
* OS:KEY_NOT_FOUND  

== Store Operation

Stores the given value using the given key.
This operation can be used either for storing new values or updating existing ones, depending on the value of the failIfPresent. When that parameter is set to false (default value) then any pre existing value associated to that key is overwritten. If the parameter is set to true, then a OS:KEY_ALREADY_EXISTS error is thrown instead.

Another important consideration is regarding null values. It is not allowed to store a null value. However, a common use case is to obtain a value (most likely by evaluating a expression or transformation), testing the value for not null, storing it if present and doing nothing otherwise. The failOnNullValue parameter simplifies this use case. On its default value of true, a OS:NULL_VALUE error is thrown if a null value is supplied. However, when set to false, a null value  causes this operation to do nothing, no error is raised but no value is altered.

This operation is synchronized on the key level. No other operation can access the same key on the same object store while this operation is running. If the runtime is running on cluster mode, this synchronism is also guaranteed across nodes.

=== Store Operation Parameters

[%header,cols="25a,75a"]
|===
|Name |Description
|Key |The key of the value to store.

Type: String +
Default: none +
Required: yes
|Value |The value to store. Should not be null if failOnNullValue is set to true.

Type: Any +
Default: payload +
Required: no
|Fail If Present |Whether or not to fail or update the pre-existing value if the key already exists on the store.

Type: Boolean +
Default: false +
Required: no
|Fail On Null Value |Whether or not to fail or skip the operation if the value is null.

Type: Boolean +
Default: true +
Required: no
|===

The Store operation can throw:

* OS:NULL_VALUE  
* OS:INVALID_KEY  
* OS:KEY_ALREADY_EXISTS
