= To Receive Custom Event Notifications (Salesforce Connector)
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
:imagesdir: _images
:icons: font

The Salesforce connector provides two operations that are useful for getting custom event notifications. These notifications pertain to general events that are not tied to Salesforce data changes.

. Create a streaming channel with the Publish Channel operation.
+
A `StreamingChannel` is a special Salesforce object that represents a channel used for notifying listeners of generic Streaming API events.
+
Note that you can also create a streaming channel through the Salesforce or through Workbench.
+
. Subscribe to the channel through the Subscribe Channel operation.
+
The Salesforce connector converts the custom events in your streaming channel to Mule events and dispatches them to your flows.

== See Also

link:/connectors/salesforce-to-work-with-streaming-channels[To Work with Streaming Channels]

link:/connectors/salesforce-about[About the Salesforce Connector]

link:/connectors/salesforce-connector-tech-ref[Salesforce Connector Technical Reference]

link:https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/create_a_streaming_channel.htm[Salesforce Documentation: Creating a Streaming Channel]

link:https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/streamingChannel.htm[Salesforce Documentation: StreamingChannel]

link:https://workbench.developerforce.com/about.php[Workbench Documentation]

////
Generic streaming in Salesforce allows you to push and receive custom events you define, in a secure and scalable way. Generic streaming uses Streaming API to send notifications of general events that are not tied to Salesforce data changes.
////
