= Salesforce Connector
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
:imagesdir: _images
:icons: font


The Salesforce connector lets you connect to the Salesforce platform. The connector exposes convenient methods for exploiting the capabilities of Salesforce, including working with Apex classes.

THe Flow Designer in Anypoint Platform lets you configure the Salesforce connector to authenticate by Username Password,  OAuth JWT, OAuth SAML, and OAuth Username Password. 

== Prerequisites

* Salesforce developer account - Sign up for an account at link:https://developer.salesforce.com[Salesforce].
* Security token - Sign into link:https://developer.salesforce.com[Salesforce], click your name in the upper right corner, then click Setup > My Personal Information > Reset Security Token. Click Reset My Security Token. Salesforce sends your security token via email to your registered email address.
* Consumer key and Secret - If you are using the Salesforce connector to access an OAuth API, you also need a consumer key and secret. 

To use a Salesforce connector in your Mule application, be sure to include the correct namespace and schema location if you are creating the XML by hand.

When Anypoint Studio is used, the namespace and schema location are provided for you, when you drag and drop the connector into a project.


== To Configure the Salesforce Connector

To access the data in a Salesforce instance, you have to set up a configuration that supports the authentication with the Salesforce service you require.

* link:https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login.htm[Basic Authentication]
+
Basic authentication is the easiest to implement. All you need to do is provide your credentials in a global configuration, then reference the global configuration file in any Salesforce connector in your application. Basic authentication is generally recommended for internal applications.
+
* link:https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_web_server_flow.htm&language=en_US[OAuth 2.0]
* link:https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm[OAuth 2.0 JWT Bearer]
* link:https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_SAML_bearer_flow.htm&language=en_US[OAuth 2.0 SAML Bearer]
* link:https://help.salesforce.com/articleView?id=remoteaccess_oauth_username_password_flow.htm&type=0&language=en_US[OAuth 2.0 Username-Password]

Implementing *OAuth 2.0*-based authentication mechanisms involves a few extra steps, but may be preferred if your service is exposed to external users, as it ensures better security.

== To Set up Basic Authentication

* Username: Enter the Salesforce username. (required)
* Password: Enter the corresponding password.
* Security Token: Enter the corresponding security token.

Implementing *OAuth 2.0*-based authentication mechanisms involves a few extra steps, but may be preferred if your service is exposed to external users, as it ensures better security.


== To Set Required Parameters for the OAuth 2.0 Configuration

* Consumer Key - The consumer key for the Salesforce connected app. See link:#create-consumer-key[To Create a Consumer Key].
* Consumer Secret - The consumer secret for the connector to access Salesforce.

=== Required Parameters for the OAuth 2.0 JWT Bearer Configuration

* Consumer Key - The consumer key for the Salesforce connected app. See link:#create-consumer-key[To Create a Consumer Key].
* Keystore File
* Store Password - The password for the keystore.
* Principal - The Salesforce username that you want to use.

== To Set Required Parameters for the OAuth 2.0 SAML Bearer Configuration

* Consumer Key - The consumer key for the Salesforce connected app. See link:#create-consumer-key[To Create a Consumer Key].
* Keystore File - The path to the key store used to sign data during authentication. Only Java key store format is allowed.
* Store Password - Key store password
* Principal - Username of desired Salesforce user

== To Set Required Parameters for the OAuth 2.0 Username-Password Configuration

* Consumer Key - The consumer key for the Salesforce connected app. See link:#create-consumer-key[To Create a Consumer Key].
* Consumer Secret - The consumer secret for the connector to access Salesforce.
* Username: Enter the Salesforce username.
* Password: Enter the corresponding password.
* Security Token: Enter the corresponding security token.

[[create-consumer-key]]
== To Create a Consumer Key

To create a consumer key:

. Log into Salesforce, and go to Setup > Build > Create > Apps.
. Under the Connected App section, click New.
. Follow these steps to created a new connected app:
.. Enter the following information in the appropriate fields:
... A name for the connected app.
... The API name.
... Contact email.
.. Under API (Enable OAuth Settings), select Enable OAuth Settings.  
.. Enter the Callback URL.
.. Select the Use digital signatures checkbox.
.. Click Browse and navigate to the Studio workspace that contains your Mule application. 
.. Select salesforce-cert.crt, and then click Open.
.. Add the Full access (full) and Perform requests on your behalf at any time (refresh_token, offline_access) OAuth scopes to  Selected OAuth Scopes .
.. Click Save, and then click Continue.
. Configure the Authorization settings for the app:
..  Click Manage, and then click Edit.
.. Under the OAuth Policies section, expand the Permitted Users dropdown, and select Admin approved users are pre-authorized.
.. Click Save.
. Under the Profiles section, click Manage Profiles.
. Select your user profile, and then click Save.
. Go back to the list of Connected Apps: Build > Create > Apps.
. Under the Connected Apps section, select the connected app you create.

You can see the Consumer Key that you need to provide in your connector's configuration.

== To Generate a Keystore File

The *Keystore* is the path to the keystore used to sign data during authentication. Only Java keystore format is allowed.

To generate a keystore file:

. Go to your Mule workspace, and open the command prompt (for Windows) or Terminal (for Mac). 
. Type `keytool -genkeypair -alias salesforce-cert -keyalg RSA -keystore salesforce-cert.jks` and press enter.  
. Enter the following details: 
.. Password for the keystore. 
.. Your first name and last name. 
.. Your organization unit. 
.. Name of your city, state, and the two letters code of your county.
+
The system generates a java keystore file containing a private/public key pair in your workspace.
+
. Provide the file path for the *Keystore* in your connector configuration.
+
Type `keytool -exportcert -alias salesforce-cert -file salesforce-cert.crt -keystore salesforce-cert.jks` and press enter.
+
The system now exports the public key from the keystore into the workspace. This is the public key that you need to enter in your Salesforce instance.
+
. Make sure that you have both the keystore (salesforce-cert.jks) and the public key (salesforce-cert.crt) files in your workspace.

== To Configure Session Invalidation

New in Salesforce Connector version 7.0.0, for all the configurations *except OAuth v2.0*, you have
the option to keep the session alive until it expires by checking the *Disable session invalidation*
checkbox.

If the checkbox is unchecked, the connector automatically destroys the session after it's no longer needed.

You should keep the session alive when you are working with threads or concurrency in general. Salesforce uses
the same session for all your threads (for example, if you have an active session and you log in again, Salesforce will use the existing session instead of
creating a new one), so to make sure the connection doesn't close when a thread is finished, you should check the *Disable session invalidation* checkbox from in the "Connection" section of the connector's global element properties.

== To Configure Apex and Proxy Settings

All the Salesforce connector configurations support Apex and Proxy settings. Configure them as follows:

. Apex Settings values:
.. Fetch All Apex SOAP Metadata - Fetches the metadata of all the Apex SOAP classes.
.. Fetch All Apex REST Metadata - Fetches the metadata of all the all Apex REST classes.
.. Apex Class Name:
... None - No Apex class name is mentioned for DataSense to acquire. 
... From Message - Lets you specify the class name from a MEL expression.
... Create Object manually - A user creates a list and adds class names to the list - only those classes and their methods are acquired by DataSense.
+
The Fetch All Apex SOAP Metadata and Fetch All Apex REST Metadata checkboxes take precedence over the Apex Class Name settings. If these boxes are selected, they fetch all the Apex SOAP metadata or Apex REST metadata regardless of your selection in the Apex Class Names section.

. Proxy Settings values:
.. Host - Host name of the proxy server.
.. Port - The port number the proxy server runs on.
.. Username - The username to log in to the server.
.. Password - The corresponding password. 
. Click OK. 
. In the main Salesforce connector screen, selection an operation from the dropdown menu. 
. The Invoke Apex REST method operation is new in version 6.2.0 of the Salesforce connector and works with the Apex Class Names settings. DataSense gets the names of the Apex classes and their methods that can be invoked using REST, which can be found in the dropdown for the Apex Class Method Name parameter. Choose a method and DataSense to get the input and output for that method.
. The Invoke Apex SOAP method operation is new in version 6.1.0 of the Salesforce connector and works with the Apex Class Names settings. DataSense gets the names of the Apex classes and their methods, which can be found in the dropdown for the Apex Class Method Name parameter. Choose a method and DataSense to get the input and output for that method.
Input Reference is a XMLStreamReader - Create from XML representing the input of the method selected (similar to the input of a SOAP operation):
+
[source, xml, linenums]
----
<soap:testSOAPMethod>
    <soap:name>John</soap:name>
    <soap:someNumber>54</soap:someNumber>
</soap:testSOAPMethod>
----
+
*Input Reference* is set by default as `#[payload]` and represents the input of the method selected previously, as you would expect. If DataSense is used, then the Transform Message component can be used to create the input from any other format (JSON, POJO etc.)
The output of the invokeApexSoapMethod operation is similar to Input Reference.


== To Store Date Objects

To store Date fields just use a Date Java object and for Datetime use Calendar Java objects. You can achieve this using DataWeave. It will create the objects for you behind the scenes.

== To Push a Topic

To push a topic:

. Click _Your Name_ > *System Log*.
. On the *Logs*  tab, click  *Execute*.
. In the *Enter Apex Code* window, paste the following Apex code, and click *Execute*.
+
[source, code, linenums]
----
PushTopic pushTopic = new PushTopic();
pushTopic.ApiVersion = 23.0;
pushTopic.Name = 'AllAccounts';
pushTopic.Description = 'All records for the Account object';
pushtopic.Query = 'SELECT Id, Name FROM Account';
insert pushTopic;
System.debug('Created new PushTopic: '+ pushTopic.Id);
----

You can either use the *create* operation or the exclusive  *publish-topic* operation as follows:

[source, xml]
----
<sfdc:publish-topic name="AccountUpdates" query="SELECT Id, Name FROM Account"/>
----

== To Subscribe to a Topic

After you create a topic, you can start receiving events by subscribing to the topic. The subscribe-topic acts like an inbound endpoint and it can be used as such:

[source, xml, linenums]
----
<flow name="accountUpdatesSubscription">
    <!-- INBOUND ENDPOINT -->
    <sfdc:subscribe-topic topic="AccountUpdates"/>
    <!-- REST OF YOUR FLOW -->
    <logger level="INFO" message="Received an event for Salesforce Object ID #[map-payload:Id]"/>
</flow>
----

A Mule flow is divided in two. The first portion of it is usually an inbound endpoint (or an HTTP connector) and a message source. The Mule flow is an entity that receives and generates events that later are processed by the rest of the flow. The other portion is a collection of message processors that processes the messages (also known as events) that are received and generated by the inbound endpoint.

Every time our subscription to AccountUpdates receives an event it executes the rest of the flow. In the case of this example it prints a message to the log at INFO level.


== To Replay Events from a Topic

A subscriber can choose which events to receive, such as all events within the retention window or starting after a particular event. The default is to receive only the new events sent after subscribing. Events outside the 24-hour retention period are discarded.

Replay options:

. Replay ID	Subscriber receives all events after the event specified by its `replayId` value.
. -1	- Subscriber receives new events that are broadcast after the client subscribes.
. -2	- Subscriber receives all events, including past events that are within the 24-hour retention window and new events sent after subscription.

The replay options values are encapsulated in the connector in a more easy to use manner:

. ALL: -2
. ONLY_NEW: -1
. FROM_REPLAY_ID: replayId

The connector also supports automatic replay of stored events, based on the replay id of the last event that has been processed by the connector. This has proved useful in cases when the connector stopped listening for some reason (server shutdown, connection dropped).

By setting the Resume From the Last Replay ID flag to true, upon starting, the connector replays all the events starting with the last processed event's replay ID.

Salesforce stores events for only 24 hours. If the stored replay ID is out of this time frame, then the replay option selected by the user determiness what events replay.

The `replay-topic` acts like an inbound endpoint and it can be used as such:

[source, xml, linenums]
----
<flow name="accountUpdatesReplay">
    <!-- INBOUND ENDPOINT -->
    <sfdc:replay-topic topic="AccountUpdates" replayId="1" replayOption="ALL" autoReplay="true"/>
    <!-- REST OF YOUR FLOW -->
    <logger level="INFO" message="Replayed events: #[payload]"/>
</flow>
----

If ALL or ONLY_NEW replay option is selected, then the `replayId` value is ignored.

== To Replay Events from a Streaming Channel

The streaming channel replay works identical with the topic replay.

The `replay-streaming-channel` acts like an inbound endpoint and it can be used as such:

[source, xml, linenums]
----
<flow name="flowStreamingChannelReplay">
    <!-- INBOUND ENDPOINT -->
    <sfdc:replay-streaming-channel streamingChannel="/u/Notifications" replayId="1" replayOption="ALL"/>
    <!-- REST OF YOUR FLOW -->
    <logger level="INFO" message="Replayed events: #[payload]"/>
</flow>
----

If ALL or ONLY_NEW replay option is selected, then the replayId value is ignored.

== To Push Events to a Streaming Channel

Salesforce offers to possiblity to push custom events to a specific streaming channel through the REST API.
The user can achieve this using link:https://workbench.developerforce.com/about.php[Workbench] or using this connector.

You can use `push-generic-event` operation as follows:

[source, xml, linenums]
----
<flow name="flowPushGenericEvent">
    <!-- INBOUND ENDPOINT -->
    <sfdc:push-generic-event channelId="0M6j0000000KyjBCAS">
    	<sfdc:events>
            <sfdc:event payload="Notification message text"/>
        </sfdc:events>
	</sfdc:push-generic-event>
    <logger level="INFO" message="Replayed events: #[payload]"/>
</flow>
----

The channel ID can be retrieved from the response map of the *publish-streaming-channel* operation.
Another way of retrieving the id of the channel is from the Salesfroce page, as follows:

. Log into your Developer Edition organization.
. Under All Tabs (+) select Streaming Channels.

If the channel ID field on the is not visible on the channel list, then:

. Click on Create New View.
. Type a name for the view in the Name input field.
. In the Available Fileds list, select Streaming Channel ID, and click Add.
. Add any other fields you want.
. Click Save.

Now you should see the channel ID for each streaming channel in the list.

The JSON received as response from the push event operation looks something like:

[source, xml, linenums]
----
[
	{
	"userOnlineStatus": {
	},
	"fanoutCount": 0
	}
]
----


== To Create Objects in Bulk

There is little practical difference between create and create-bulk. Dealing with a Bulk operation means that the actual creation process is handled by Salesforce in the background, so the connector doesn't reply with a collection of SaveResults, because it does not have them yet. Instead the connector replies with a BatchInfo object which contains the ID of the batch and the id of the job it just created to upload those objects.

This change in behavior remains true for all operations that support "bulk".

== To Monitor a Batch in Salesforce

You can monitor a Bulk API batch in Salesforce.

To track the status of bulk data load jobs and their associated batches, click __Your Name__ > Setup > Monitoring > Bulk Data Load Jobs. Click the Job ID to view the job detail page.

The job detail page includes a related list of all the batches for the job. The related list provides View Request and View Response links for each batch. If the batch is a CSV file, the links return the request or response in CSV format. If the batch is an XML file, the links return the request or response in XML format. These links are available for batches created in Salesforce API version 19.0 and later.

== To Create a Streaming Channel

To create a streaming channel:

You must have the proper Streaming API permissions enabled in your organization.

. Log into your Developer Edition organization.
. Under All Tabs (+) select Streaming Channels.
. On the Streaming Channels tab, select New to create a new Streaming Channel.
. Enter /u/notifications/ExampleUserChannel in Streaming Channel Name, and an optional description.
+
Your New Streaming Channel page should look something like this:

You can either use the *create* operation or the exclusive  *publish-streaming-channel* operation as follows:

[source, xml]
----
<sfdc:publish-streaming-channel name="/u/Notifications" description="General notifications"/>
----

== To Subscribe to a Streaming Channel

After you create a streaming channel, you can start receiving events by subscribing to the channel. The `subscribe-streaming-channel`Â acts like an inbound endpoint and it can be used as such:

[source, xml, linenums]
----
<flow name="notificationsChannelSubscription">
	<!-- INBOUND ENDPOINT -->
	<sfdc:subscribe-streaming-channel streamingChannel="/u/TestStreaming"/>
	<!-- REST OF YOUR FLOW -->
	<logger level="INFO" message="Received an event: #[payload]"/>
</flow>
----

A Mule flow is divided in two. The first portion of it is usually an inbound endpoint (or an HTTP connector) and a message source. The Mule flow is an entity that receives and generates events that later are processed by the rest of the flow. The other portion is a collection of message processors that processes the messages (also known as events) that are received and generated by the inbound endpoint.

Every time our subscription to `/u/TestStreaming` receives an event it executes the rest of the flow. In the case of this example it prints a message to the log at INFO level.

== About the Streaming API

Using the Streaming API allows you to receive events for changes to Salesforce data that match a Salesforce Object Query Language (SOQL) query you define, in a secure and scalable way.

Events convert to Mule events and dispatch to your flows.

== About Creating a PushTopic

Before you can start receiving events for changes in Salesforce, you must first create a PushTopic. A link:https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/pushtopic.htm[PushTopic] is a special object in Salesforce that binds a name (the topic's name) and SOQL together. Once a PushTopic is created you can then subscribe to it by using only its name.

There are several ways in which you can create a PushTopic; we cover using Salesforce itself and using this connector. You could potentially also use link:https://workbench.developerforce.com/about.php[Workbench].

== About Salesforce Connector Integration Patterns

Salesforce recognizes five integration patterns for connecting with other systems. The Salesforce connector is the "window" through which you can access or act upon data in Salesforce from within your Mule application, addressing these patterns, as the table below illustrates. 

All patterns are supported by the Salesforce Connector.

[%header,cols="30a,70a"]
|===
|Integration Pattern |Description
|*Remote Process Invocation: Request-Reply* |Salesforce kicks off a process in a remote system, waits for the remote system to finish processing, then accepts control back again from the remote system.
|*Remote Process Invocation: Fire and Forget* |Salesforce initiates a process in a third-party system and receives an acknowledgement that the process has started. The third-party system continues processing independent of Salesforce.
|*Batch Data Synchronization* |An external system accesses, changes, deletes, or adds data in Salesforce _in batches_, and vice versa (Salesforce to external system).
|*Remote Call-In* |An external system accesses, changes, deletes or adds data in Salesforce, and vice versa (Salesforce to external system).
|*User Interface Update Based on Data Changes* |The Salesforce UI updates in response to a change in a third-party system.
|===

== About Salesforce Operations

Salesforce exposes operations that address these integration patterns via several APIs. Note that the Salesforce connector does not expose _all_ possible operations of these Salesforce APIs. Though it makes little difference to how you use the connector in your application, it's useful to know that Mule's Salesforce connector performs many of the operations that Salesforce exposes via the following six APIs.

=== About the SOAP API

The Salesforce link:http://www.salesforce.com/us/developer/docs/api/index.htm[SOAP API] provides secure access to your organization's information on Salesforce via SOAP calls. Most of the operations that the Salesforce connector performs map to operations this API exposes.

All the Salesforce operations that are performed through the SOAP API have an optional parameter called
"Headers" that can take any of the following link:https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/soap_headers.htm[Salesforce SOAP Headers]:

* AllOrNoneHeader
* AllowFieldTruncationHeader
* AssignmentRuleHeader
* CallOptions
* EmailHeader
* LocaleOptions
* MruHeader
* OwnerChangeOptions
* QueryOptions
* UserTerritoryDeleteHeader
* DuplicateRuleHeader

*Note:* The Salesforce connector does not perform operations exposed by the following Salesforce APIs:

* Chatter REST API
* Tooling API

=== About the Bulk API

The Salesforce link:https://www.salesforce.com/us/developer/docs/api_asynch/[Bulk API] offers the ability to quickly and securely load batches of your organization's data into Salesforce. 

=== About the Streaming API

The Salesforce link:http://www.salesforce.com/us/developer/docs/api_streaming/[Streaming API] securely receives notifications for changes to your organization's information in Salesforce.

=== About the Metadata API

The Salesforce link:http://www.salesforce.com/us/developer/docs/api_meta/[Metadata API] manages customizations and build tools that can manage the metadata model, not the data itself.

=== About the Apex SOAP API

The Salesforce link:https://www.salesforce.com/us/developer/docs/apexcode/[Apex SOAP API] exposes Apex class methods as custom SOAP Web service calls. This allows an external application to invoke an Apex Web service to perform an action in Salesforce.

=== About the Apex REST API

The Salesforce link:https://developer.salesforce.com/page/Creating_REST_APIs_using_Apex_REST[Apex REST API] - Create your own REST-based web services using Apex. It has all of the advantages of the REST architecture, and provides the ability to define custom logic and includes automatic argument/object mapping.


== About Examining the Topic Event

The event that gets pushed through the flows contains information about the Salesforce data that has changed, how it changes, and when. Usually the raw JSON that the subscription receives looks something like this:

[source, json, linenums]
----
"channel": "/topic/AccountUpdates",
  "data": {
    "event": {
      "type": "created",
      "createdDate": "2011-11-35T19:14:31.000+0000"
    },
    "sobject": {
      "Id": "a05D0000002jKF1IAM"
    }
  }
}
----

The connector parses this information and sends you information that a flow can actually work with.

== About Channel Inbound Properties

Information that gets passed along as inbound properties:

[%header,cols="3*a"]
|===
|Property Name |Scope |Maps to
|channel |INBOUND |Channel JSON property
|type |INBOUND |Type JSON property in data
|createdDate |INBOUND |createdDate JSON property in data
|===

Except for "channel", every property inside _event_ is available as an INBOUND property.

== About Event Payload

The payload of the event is actually a map, which contains everything inside the `SObject` object in the received JSON data. This is a map for the convenience of being able to use the map-payload expression evaluator to extract the information of the SObject.

See how in the <<Subscribing to a Topic>> example we used `#[map-payload:Id]` to print the ID of the SObject.

== About Message Durability in Salesforce

Salesforce stores events for 24 hours, so you can retrieve stored events during that retention window. The Streaming API event framework decouples event producers from event consumers.

A subscriber can retrieve events at any time and isn’t restricted to listening to events at the time they’re sent.

Each broadcasted event is assigned a numeric ID. IDs are incremented and not guaranteed to be contiguous for consecutive events. Each ID is guaranteed to be higher than the ID of the previous event. For example, the event following the event with ID 999 can have an ID of 1,025. The ID is unique for the org and the channel. The IDs of deleted events aren’t reused.

See Salesforce link:https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/using_streaming_api_durability.htm[Message Durability].


== About Generic Streaming

Using the Generic Streaming allows you to push and receive custom events you define, in a secure and scalable way.
Generic streaming uses Streaming API to send notifications of general events that are not tied to Salesforce data changes.

Events convert to Mule events and dispatch to your flows.

== About Publishing a Streaming Channel

Before you can start receiving custom events in Salesforce, you must first create a StreamingChannel. A link:https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/streamingChannel.htm[StreamingChannel] is a special object in Salesforce that represents a channel that is the basis for notifying listeners of generic Streaming API events. Once a Streaming Channel is created you can then subscribe to it by using only its name.

There are several ways in which you can create a Streaming Channel; we cover using Salesforce itself and using this connector. You could potentially also use link:https://workbench.developerforce.com/about.php[Workbench].

== About Event Structure

The event that gets pushed through the flows contains information about the Salesforce data that has changed, how it changes, and when. Usually the raw JSON that the subscription receives looks something like this:

[source, json, linenums]
----
"payload"="Event content text",
	"event": {
		"createdDate": "2016-10-10T11:27:09.853Z",
		"replayId": "92"
		},
	}
}
----

The connector parses this information and sends you information that a flow can actually work with.

== About Event Inbound Properties

Information that gets passed along as inbound properties:

[%header,cols="3*",width=90%]
|===
|Property Name |Scope |Maps to
|payload |INBOUND |payload JSON property
|createdDate |INBOUND |createdDate JSON property in event
|replayId |INBOUND |replayId JSON property in event
|===

== Tips

* *Fields To Null*: The configurations have a checkbox called *Can Clear Fields by Updating Field value to Null*. If checked, all the fields in a request that have a Null value will be added to the *fieldsToNull* field and sent to Salesforce.
Using this feature, you can decide which fields to set to null without being forced to use the *fieldsToNull* field.
* *Upsert*: Unless you configure the *link:http://help.salesforce.com/apex/HTViewHelpDoc?id=faq_import_general_what_is_an_external.htm[External ID Field Name]* for the link:http://www.salesforce.com/us/developer/docs/officetoolkit/Content/sforce_api_objects_list.htm[sObject] to which you're trying to upsert, every use of the upsert will fail. 
* *Upsert*: The upsert operation does not work with the sObject  `priceBookentry2`. 
* *Query*: Even though you can see the fields of an SObject and their corresponding types via DataSense, the *Query* operation returns _all_ fields as `String`.
+
If you want to use the actual type of the field, you must convert that field to the desired type using a *Transform Message* component.
+
In this example, although *CreatedDate* field appears as dateTime, the query returns a String representing the date.
In order to actually use the field as a dateTime, you can configure it using Transform Message, like in the example.
* *Inserting into Dropdown*: Be aware, inserting dependent values into an existing drop-down list field in Salesforce doesn't always work. Test to confirm functionality.
* *Evaluating Values in Dropdown*: If you're evaluating against a value in an existing drop-down list field in Salesforce, be sure to use the _exact value_ in the dropdown. For example, if you use the value "US" to evaluate against the contents of a drop-down list which contains the value "USA", the evaluation will work, but you end up with two values in the dropdown: one for US and one for USA.
* *Currency*: Currency values cannot exceed 18 characters in length.
* *Currency*: When working with multiple currencies, be aware of which currency your sObject uses, to avoid inaccurate entries. The default currency matches the location at the organization level.
* *Limits on API Calls*: Check the link:http://help.salesforce.com/apex/HTViewHelpDoc?id=integrate_api_rate_limiting.htm[limit on the number of API calls] to which you're entitled. Ensure that your app does not exceed the number of allotted calls per day.
* *Opportunity sObject*: When extracting data from an Opportunity, be aware that a "quarter" is not relative to a calendar year; a "quarter" in this context is relative to the financial year of the organization. 

== See Also

* Access the link:https://developer.salesforce.com/docs[Salesforce developer documentation] for detailed documentation on Salesforce objects and queries.
