= To Create a Consumer Key (Salesforce Connector)
:keywords: salesforce connector, inbound, outbound, streaming, poll, dataweave, datasense
:imagesdir: _images
:icons: font

A consumer key is required when setting up an OAuth 2.0 configurations for the Salesforce connector. It is used by the OAuth 2.0 JWT and SAML bearer configurations and the OAuth 2.0 Username-Password configuration.

[[create-consumer-key]]
. Log into Salesforce, and go to Setup > Build > Create > Apps. *TODO: WHERE IS THIS? I see Setup Create Apps, no Build*
. Under the Connected App section, click New.
. Follow these steps to created a new connected app:
.. Enter the following information in the appropriate fields:
+
* A name for the connected app.
* The API name.
* Contact email.
+
.. Under API (Enable OAuth Settings), select Enable OAuth Settings.  
.. Enter the Callback URL.
.. Select the Use digital signatures checkbox.
.. *TODO: Studio ONLY! what to do for Design Center apps? Do we need to export them to Studio?* *Click Browse and navigate to the Studio workspace that contains your Mule application.* 
.. Select `salesforce-cert.crt`, and then click Open.
.. Add the Full access (full) and Perform requests on your behalf at any time (refresh_token, offline_access) OAuth scopes to  Selected OAuth Scopes .
.. Click Save, and then click Continue.
. Configure the Authorization settings for the app:
..  Click Manage, and then click Edit.
.. Under the OAuth Policies section, expand the Permitted Users dropdown, and select Admin approved users are pre-authorized.
.. Click Save.
. Under the Profiles section, click Manage Profiles.
. Select your user profile, and then click Save.
. Go back to the list of Connected Apps: Build > Create > Apps.
. Under the Connected Apps section, select the connected app you create.

You can see the Consumer Key that you need to provide in your connector's configuration.

== See Also

link:/connectors/salesforce-about-authentication[About Authentication through the Salesforce Connector]
