= About ServiceNow Connector 6.0
:keywords: anypoint studio, connector, endpoint, servicenow, http
:imagesdir: ./_images

The ServiceNow Connector facilitates connections between Mule and ServiceNow apps. The ServiceNow Connector 6.0 supports these operations: aggregate, deleteMultiple, deleteRecord, get, getKeys, getRecords, insert, insertMultiple, and update. You can use these operations with the custom ServiceNow tables, along with any operations available through the installed plugins.

Prerequisites:

* A ServiceNow account.
* Anypoint Studio, Design Center, or a standalone application developed in XML.
+
Note that if you are upgrading from a previous version of the connector through Anypoint Studio, you can "Updates Available" message.

== See Also

//link:/mule-user-guide/v/3.8/hardware-and-software-requirements[Hardware and Software Requirements]

link:/release-notes/servicenow-connector-release-notes[ServiceNow Connector Release Notes]

link:/anypoint-exchange/ex2-studio[To Add Exchange Assets to Studio]

link:http://mulesoft.github.io/servicenow-connector/[Technical Reference]
