= About ServiceNow Connector 6.0
:keywords: anypoint studio, connector, endpoint, servicenow, http
:imagesdir: ./_images

The ServiceNow Connector facilitates connections between Mule and ServiceNow apps. The ServiceNow Connector 6.0 supports these operations: aggregate, deleteMultiple, deleteRecord, get, getKeys, getRecords, insert, insertMultiple, and update. You can use these operations with the custom ServiceNow tables, along with any operations available through the installed plugins.

Prerequisites:

* A ServiceNow account.
* Anypoint Studio, Design Center, or a standalone application developed in XML.
+
If you are upgrading from a previous version of the connector through Anypoint Studio, you can click the "Updates Available" message.

[[operations]]
== Operations

* Aggregate
* Insert
* Insert multiple
* Delete record
* Delete multiple
* Update
* Get
* Get keys
* Get records

Note that the ServiceNow SOAP site provides a full list of operations for any version of the ServiceNow connector.

