= About the SFTP Connector
:keywords: SFTP, connector, matcher, directory, listener
:toc:
:toc-title:

Release Notes: link:/release-notes/connector-sftp-1.1.0[Mule Runtime SFTP 1.1.0 Release Notes]

The SFTP connector provides access to files and folders on a SFTP server. Its main features include:

// INCLUDE FOR file, ftp, and sftp connectors
include::common-file-actions.adoc[]

[[connection_settings]]
== Connecting to an SFTP Server

You set up a connection through a `config` element, for example:

[source, xml, linenums]
----
<sftp:config name="ftp">
  <sftp:connection username="anonymous" password="password"
    host="localhost" port="${ftpPort}"
    workingDir="${workingDir}"/>
</sftp:config>
----

The `workingDir` provides the path to a directory that is treated as the root of every relative path used with this connector. If the directory is not provided, the remote server’s default serves as the working directory.
The `username`, `password`, `host`, and `port` attributes are self explanatory.

// Included in FTP, SFTP
include::common-dynamic-connections.adoc[]

//INCLUDED IN FTP, SFTP, FILE
include::common-attributes.adoc[]

[[see_also]]
== See Also

link:sftp-documentation[SFTP Connector Documentation Reference]

link:sftp-read[To Read Files]

link:sftp-write[To Write Files]

link:sftp-list[To List Files]

link:sftp-on-new-file[To Listen for New or Modified Files]

link:sftp-copy-move[To Copy or Move Files]

link:sftp-documentation[SFTP Connector Technical Reference]
