= To Set Up an SFTP Configuration
:keywords: ftp, connector, matcher, directory, listener
:toc:
:toc-title:

toc::[]

//Anypoint Studio, Design Center: FTP connector

[[short_description]]
The SFTP connector supports SFTP connections and file transfer operations. 

. From an SFTP operation in your flow, set up a configuration in the SFTP Configuration window.
+
You can open the SFTP Configuration window by clicking Set Up or Add from within any SFTP operation in your flow.
+
. Provide required configurations:
+
* Provide a Name for the configuration.
+
Example: `My SFTP configuration`
+
* Provide a Host domain name or server IP address:
+
Example: `my.sftpsite.com`
+
* Provide a Port for the transport protocol, or use the default.
+
Defaults to `22`.
+
. Provide any optional settings you need to add:
+
* Username or Password (if required by the host).
* Identity File location for a PKI private key.
* Passphrase or a password-protected key in an Identity File.
+
This file supplies the private key that is used for public key authentication.
+
* Working directory:
+
Example: `my/working/dir`
+
* Preferred Authentication Method:
+
** Gssapi With Mic (`gssapi_with_mic`)
** Public Key (`public_key`)
** Keyboard Interactive (`keyboard_interactive`)
** Password (`password`)
+
* Path to the Known Hosts File (if needed) to check whether the server key matches the key in the file.
+
The operation aborts if keys do not match.
+
* SFTP proxy configuration:
+
The Host, Port, Username, and Protocol is required if you set up a proxy. You can also supply a Password, if needed.
+
Supported protocols:
+
** HTTP
** SOCKS4
** SOCKS5
+
* Advanced configuration options:
** A Reconnection strategy.
** Pooling Profile.
** Default Write Encoding.
** Timeout Configuration.
. Click Test to check your connection to the server.
+
You should make sure that the connection is successful before running your application. If the Test button is disabled, then a worker to test the connection is not available yet. You can come back later and test the connection once the button is enabled.
+
. Save the configuration.

[[see_also]]
== See Also

link:sftp-about-the-sftp-connector[About the SFTP Connector]

link:sftp-documentation[SFTP Connector Technical Reference]

link:common-connection-pooling[Connection Pooling Reference]

link:common-to-set-up-timeouts[To Set Connection Timeouts]

link:common-about-tls[About TLS]

////
examples identity files
+
Examples: ~/.ssh/identity, ~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_rsa
+
////
