= About Target Variables

When creating a flow in a Mule app, you might need to store data in a variable so that any component in the flow can use it. Non-void operations (such as the Read operation to the File connector) can store the message data that they return in a target variable. Once defined, target variables are available for use within the flow, and you can access them like you access any other variable.

You define a target variable through these fields:

* Target Variable (`target`): Name of the variable in which you want to store message data.
* Target Value (`targetValue`): Value of the data to store in the target variable. By default, the value is the message payload (`payload`). The field accepts any value that a variable accepts: any supported data type, DataWeave expressions, the keywords `payload`, `attributes`, and `message`, but _not_ the keyword `vars`.

It is important to understand that setting a target variable changes the typical course of the message through the flow. Normally, an operation outputs a different message than it receives as input. However, when you set a target variable for an operation, the operation outputs to the _next_ component in the flow the same message that it received as input. For example, assume you have a flow consisting of component A, followed by component B with a target value of `myMessage`, and then component C. In this case, component C will receive the same message that B received from A.

Here, a Read operation with these settings stores payload of `readme.txt` in `myVar` by default:

* Path: `readme.txt`
* Target Variable: `myVar`
+
This is an XML example of the same settings in Anypoint Studio:
+
----
<file:read path="readme.txt" target="myVar" />
----

Here, the entire message is stored in `myVar`:

* Path: `readme.txt`
* Target Variable: `myVar`
* Target Value: `message` in Design Center, `#[message]` in Anypoint Studio.
+
This is an XML example of the same settings in Anypoint Studio:
+
----
<file:read path="readme.txt" target="myVar" targetValue="#[message]" />
----

Here, only the file size is stored in `myVar`:

* Path: `readme.txt`
* Target Variable: `size`
* Target Value: `attributes.size` in Design Center, `#[attributes.size]` in Anypoint Studio.
+
This is an XML example of the same settings in Anypoint Studio:
+
----
<file:read path="readme.txt" target="size" targetValue="#[attributes.size]" />
----

The scenarios describe some cases where you might use target variables.

== Scenario: Setting a Target Variable from within an Operation

Assume that you want to log the entire message (payload and attributes) returned by a Database connector operation, such as Insert. Instead of using a Set Variable component after the operation, you can instead capture the message data by adding a target variable directly to the operation:

* Target Variable for the Insert operation: `result`
* Target Value: `message` in Design Center, `#[message]` in Anypoint Studio.

Then you might retrieve the result from the Logger like this:

* Message: `[vars.result.payload ++ vars.result.attributes]`

Assume that you want to log the name of the first entry in a customer database. You can define a target variable like this one through the Select operation of the Database connector:

* Target Variable for the Select operation: `customerName`
* Target Value: `payload[0].name` in Design Center, `#[payload[0].name]` in Anypoint Studio.

Then you might retrieve the result from the Logger like this:

* Message: `'Customer name is: ' ++ vars.customerName`

== Scenario: Using the Stored Value as Input to an Operation

Assume that you want to access a customer's most recent order by its order number. You might create a target variable called `lastOrder` within an operation (such as the Retrieve operation to the Object Store connector) to capture the `payload` containing that order number.

* Target Variable for the Retrieve operation: `lastOrder`

Then you can use the Input Parameter of another operation in your flow (such as the Select operation to the Database connector) to make the variable available for use in your query, for example:

* Input Parameter definition for the Select operation:
 ** Key: `lastOrder`
 ** Value: `vars.lastOrder` in Design Center, `#[vars.lastOrder]` in Anypoint Studio.
* Query for the Select operation that uses the `lastOrder` key to specify the order number:
+
`SELECT * FROM ORDERS WHERE customerNumber = "353" and orderNumber > :lastOrder`

== Scenario: Bypassing the Normal Message Flow

Assume that you want to insert a number of records into a database, then pass those same records on for further processing by the next component in your flow. Though you want to use the Bulk Insert operation to the Database connector to insert the records, the operation returns a success message. So, to pass on the records to the next component instead of passing on the returned success message, you can store success message in a target variable, for example:

* Target Variable: `resultingPayload`
* Target Value: `payload`

Then the next operation in your flow can process the records that Bulk Insert received. For example, you might use a DataWeave function in the Store operation to return the highest `orderNumber` value from the record payload: `max(payload.orderNumber)`. Here, `payload` is the same payload received by Bulk Insert.

== See Also

* link:/mule-user-guide/v/4.0/about-mule-event[About the Mule Event]
* link:/mule-user-guide/v/4.0/about-mule-variables[About Variables in the Mule Event]
* link:/connectors/v/latest/database-sync-workflow[Workflow: Synchronize a Database]

//* link:/mule-user-guide/v/4.0/target-variable-scenarios[Target Variable Scenarios]
