= About Target Variables

Non-void operations (such as the Read operation to the File connector) provide fields for storing message data in a variable that you can reference and use within the scope of a flow.

* Target Variable: Name of your variable.
* Target Value: Value to store in the named target variable. Stores the message payload by default but can instead store the entire message (the payload and attributes) or just attributes. Note that you cannot store other variables in a target variable.

Here, the payload of `readme.txt` is stored in `myVar` by default. File attributes and anything else in the message is lost:

* Path: `readme.txt`
* Target Variable: `myVar`
+
This is an XML example of the same settings:
+
----
<file:read path="readme.txt" target="myVar" />
----

Here, the entire message is stored in `myVar`:

* Path: `readme.txt`
* Target Variable: `myVar`
* Target Value: `message`
+
This is an XML example of the same settings:
+
----
<file:read path="readme.txt" target="myVar" targetValue="#[message]" />
----

Here, only the file size is stored in `myVar`:

* Path: `readme.txt`
* Target Variable: `size`
* Target Value: `attributes.size`
+
This is an XML example of the same settings:
+
----
<file:read path="readme.txt" target="size" targetValue="#[attributes.size]" />
----

== Use Case: Using a Target Variable as Input to an Operation

Assume that you want to access a customer's most recent order by its order number. You might create a target variable called `lastOrder` within one operation (such as the Retrieve operation to the Object Store connector) to capture the `payload` that contains that order number:

* Target Variable: `lastOrder`
* Target Value: `payload`

Then you can use the Input Parameters of another operation (such as the Select operation to the Database connector) to input the target value, for example:

* Key: `lastOrder`
* Value: `vars.lastOrder.payload`

Now an SQL query like this can use the `lastOrder` target variable to specify the order number:

`SELECT * FROM ORDERS WHERE customerNumber = "353" and orderNumber > :lastOrder`

////
TODO: VERIFY THIS BEFORE PUBLISHING
== Use Case: Using a target variable to retain the payload of a bulk operation

The BULK INSERT operation to the Database connector returns a success message that overrides the Database payload. You can create a target variable to prevent this override, for example:

* Target Variable: `syncResult`
* Target Value: `payload`

Then you can access that payload for further operations. For example, you might create a script in the Store operation of the Object Store connector to get the highest `orderNumber` value in the payload: `max(syncResult.orderNumber)`.
////

== Use Case: Logging the Value of a Target Variable

Assume that you want to log the entire message (payload and attributes) returned by a Database connector operation, such as Insert. You might add this target variable to the operation:

* Target Variable: `result`
* Target Value: `message` or `#[message]`

Then you can retrieve the result from the Logger like this:

* Message: `'This is the resulting message: ' ++ vars.result`

== See Also

* link:/mule-user-guide/v/4.0/about-mule-event[About the Mule Event]

* link:/mule-user-guide/v/4.0/database-sync-workflow[Workflow: Synchronize a Database]
