= Example: To publish and get a response in the VM Connector
:keywords: VM, queues, connector, publish, listen, response, request-response
:toc:
:toc-title:

toc::[]

In certain cases, you might be interested in getting a response back. For those cases, the publish-consume operation exists. This operation is exactly the same as publish, except that it waits for the message to be processed in the other end notifies the response.

Let’s keep working with link:/connectors/vm-publish-listen[the publish and listen example] and let’s suppose we want to send the response back, we would just change it like this:

[source, xml]
----
    <flow name="publish">
        <http:listener path="/json-here" allowedMethods="POST" config-ref="httpListener" />
        <vm:publish-consume queueName="#[payload.destination]">
            <vm:content>#[payload.body]</vm:content>
        </vm:publish>
        <logger/>
    </flow>
----

At this point, there’s an additional feature of the <vm:listener> source which becomes quite handy, which is the ability to embed a DataWeave expression to build the response.

Suppose that you want the response to also be a json in a predefined format. For the sake of simplicity, let’s suppose it’s just a json with a body and an origin value:

[source, xml]
----
<flow name="listener">
        <vm:listener queueName="queue" queueType="TRANSIENT">
            <vm:response>
                <vm:content><![CDATA[#[
                    %dw 2.0
                    output application/json
                    ---
                    {
                    	"origin": "Awesome Mule 4 VM connector",
                        "body" : payload
                    }
                ]]>
                </vm:content>
            </vm:response>
        </vm:listener>
        <flow-ref name="theIntegrationLogic" />
    </flow>
----
