= Web Service Consumer
:keywords: core, connector, web service consumer
:toc:
:toc-title: Page Contents

toc::[]

The Web Service Consumer connector configures a connection to a SOAP service using a WSDL file. 

This connector consists of a configuration with a single connection provider that returns instances of connections based on a WSDL definition, returns a specific service and port and, optionally, the service address (we take the one bound in the binding as default). Using the information contained in a service’s WSDL, this connector pre-configures most of the information you need to establish the connection you need to consume a service from within your Mule application. You need only specify the location of the Web service’s WSDL file, and the host, port, address to access the WSDL. 

The connector is based on link:http://cxf.apache.org/docs/why-cxf.html[Apache CXF], 
which handles all the SOAP message parsing and building.

The web service consumer has a single operation, the Consume operation that provides all the available operations for the given connection and only accepts a SOAP message that is valid for the selected SOAP operation. To use the Web Service Consumer, define the Web Service with which you want to connect, to achieve this only three parameters, since the connector provides out of the box configuration elements to make it easier to configure the most common scenarios.

As with the old module, the underlying transport can be configured. 
//MG what do we mean by simple configuration?


== Features

* Full metadata support for headers, body and attachments (including for multipart SOAP message operations) for both input and output.
* SOAP multipart messages
* SOAP Headers
* Web Service Security (Timestamp, UsernameToken, Signature, Encryption)
* Datasense support for Soap Headers, Soap Body and Attachments
* You can now embed DataWeave transformations inside the invoke operation so that you can construct the request without having a side effect on the message nor having multiple components to create it.
* Reviewed SOAP with Attachments/MTOM attachments handling.
* Request body is not coupled to the payload.

=== Limitations

* Works only with the HTTP protocol.

== See Also

* link:/connectors/wsc-workflow[Workflow: Web Service Consumer Connector]
* link:/connectors/wsc-to-configure[To Configure]
* link:/connectors/wsc-to-configure-security[To Configure Security]
* link:/connectors/wsc-to-create-connection[To Create a Connection]
* link:/connectors/wsc-to-consume[To Consume from the Connector]
