= Web Service Consumer
:keywords: core, connector, web service consumer, WSS, service, consumer, wsdl, soap

When developing applications with Mule, users often need to be able to consume a SOAP Web service
to acquire data from an external source. In the best case scenario, you can use an existing connector
to connect to a specific service provider, such as Workday or Service Now. However,
where no web service specific connector exists to facilitate the connection, the quickest,
easiest way to consume a Web service from within a Mule application is to use the Web Service Consumer.

Its main features include:

* Consuming DOC Literal web services
* SOAP multipart messages
* SOAP Headers
* DataSense support for SOAP Headers, SOAP Body, and Attachments
* Embedded DataWeave transformations inside the operation.
* Support and Unified experience for SOAP with attachments and MTOM handling.
* Custom HTTP configuration as transport (Runtime + Design Time)
* WS Securities support

== See Also

* link:/connectors/web-service-consumer-reference[Web Service Consumer Technical Reference]
* link:/connectors/web-service-consumer-configure[To Configure the WSC]
* link:/connectors/web-service-consumer-consume[To Consume a Service]


NOTE: RPC WSDLs are not supported by the Web Service Consumer.
