= Web Service Consumer
:keywords: core, connector, web service consumer
:toc:
:toc-title: Page Contents

The Web Service Consumer connector configures a connection to a SOAP service using a 
WSDL file that you supply. Use this connector when you have a WSDL and no other 
Anypoint connector works for the service.

This connector consists of a configuration with a single connection provider that returns instances 
of connections based on a WSDL definition, returns a specific service and port, and optionally, 
the service address using the binding as the default. Using the information contained in a service’s WSDL, 
this connector configures the connection you consume from the service from a Mule application. 
Identify the location of the WSDL file and the connector configures the HTTP host, port, and address.  

This connector is based on link:http://cxf.apache.org/docs/why-cxf.html[Apache CXF], 
which handles the SOAP message parsing and building.

The web service consumer has a single operation, the *Consume* operation that provides all the available operations for the given connection and only accepts a SOAP message that is valid for the selected SOAP operation.

== Features
 
* Support for SOAP multipart operations. Also provides full metadata support for headers, body and attachments (including for multipart SOAP message operations) for both input and output.
* DataSense support for SOAP Headers, SOAP body, and attachments.
* Embed DataWeave transformations only for the current scope.
* Handle SOAP with attachments and Message Transmission Optimization Mechanism (MTOM) attachments.
* Request body not coupled to the payload.
* Web service security for the timestamp, username token, signature, and encryption.

== Limitations

Only works with the HTTP protocol.

== See Also

* link:/connectors/wsc-workflow[Workflow: Web Service Consumer Connector]
* link:/connectors/wsc-to-configure[To Configure]
* link:/connectors/wsc-to-configure-security[To Configure Security]
* link:/connectors/wsc-to-create-connection[To Create a Connection]
* link:/connectors/wsc-to-consume[To Consume from the Connector]
