= XML Module
:keywords: XML, xpath, xslt, xquery, XSD, validation

The XML Module provides functionality to process and extract data from an XML document. This module should be used for use cases associated with XML standards such as XSLT, XPath and XQuery, or XSD.
+
Although DataWeave can handle most XML-related use cases (it's actually Mulesoft's recommended approach), there are still valid use cases for users who want to use XML standards such as XSLT, XPath, XQuery, and XSD validation.

To use the XML module, simply add it to your application using the Studio palette or Flow Designer card, or add the following dependency in your `pom.xml` file:

[source,XML,linenums]
----
<dependency>
    <groupId>org.mule.modules</groupId>
    <artifactId>mule-xml-module</artifactId>
    <version>1.1.0</version> <!-- or newer -->
    <classifier>mule-plugin</classifier>
</dependency>
----

== See also

* link:/xml-xpath[To use XPath]
* link:/xml-xslt[To use XSLT]
* link:/xml-schema-validation[To validate XML documents using XSD schemas]
* link:/xml-xquery[To use XQuery]
* link:/xml-reference[XML Module Technical Reference]
