= Validating documents against an XSD schema with the XML module
:keywords: XML, schema, xsd, validate

The `<xml-module:xpath-extract>` operation validates that the input content is compliant with a given schema. This operation supports referencing many schemas (using comma as a separator) which include each other.

As an example, let's look at how to work with a sample XML which contains the script of the play Othello by William Shakespeare. The XML file looks roughly like this:

[source, xml, linenums]
----
<flow name="process">
    <xml-module:validate-schema schemas="schema1.xsd, schema2.xsd" />
    <flow-ref name="processValidDocument" />
</flow>
----

Although by default this operation will try look for the input document at the message payload, you can supply your own input. For example:

[source, xml, linenums]
----
<flow name="process">
    <file:read path="document.xml" target="xmlDoc" />
    <xml-module:validate-schema schemas="schema1.xsd, schema2.xsd">
        <xml-module:content>#[vars.xmlDoc]</xml-module:content>
    </xml:module:validate-schema>
    <flow-ref name="processValidDocument" />
</flow>
----

[TIP]
If you want, you can use the `<xml-module:validate-schema>` component inside a `<validation:all>` element

== Handling the Validation Error

If the validation is sucessful, nothing will happend and the flow will continue with the next operation. If it fails, a `XML-MODULE:SCHEMA_NOT_HONOURED` error will be raised.

The `XML-MODULE:SCHEMA_NOT_HONOURED` is a complex one. Since the validation may fail for any number of reasons, the error contains a list of Messages. Each of those messages contain a `SchemaViolation` object which has the following structure:

[source, json, linenums]
----
{
    lineNumber: Number,
    columnNumber: Number,
    description: String
}
----

So let's consider the following example:

[source, xml, linenums]
----
 <flow name="extractErrorsFromException">
    <try>
        <xml-module:validate-schema schemas="schema.xsd" /> // <1>
        <error-handler>
            <on-error-propagate type="XML-MODULE:SCHEMA_NOT_HONOURED"> // <2>
                <foreach collection="#[error.errorMessage.payload]">
                    <logger level="ERROR" message="#['At line: $(payload.lineNumber), column: $(payload.columnNumber) -> $(payload.description)']" /> // <3>
                </foreach>
            </on-error-propagate>
        </error-handler>
    </try>
</flow>
----

```
ERROR 2018-02-16 14:35:45,722 [[MuleRuntime].cpuIntensive.01: [SchemaValidationTestCase#extractErrorsUsingExpressions].extractErrorsFromException.CPU_INTENSIVE @411e886b] org.mule.runtime.core.internal.processor.LoggerMessageProcessor: At line: -1, column: -1 -> cvc-complex-type.2.4.a: Invalid content was found starting with element 'fail'. One of '{used}' is expected.
```

== See also

* link:xml-module[XML Module documentation]
